CREATE TABLE [dbo].[ACCOUNT_EXECUTIVE] (
    [CL_CODE]       VARCHAR (6) NOT NULL,
    [DIV_CODE]      VARCHAR (6) NOT NULL,
    [PRD_CODE]      VARCHAR (6) NOT NULL,
    [EMP_CODE]      VARCHAR (6) NOT NULL,
    [INACTIVE_FLAG] SMALLINT    NULL,
    [DEFAULT_AE]    SMALLINT    NULL,
	[MGMT_LVL_ID]	INT			NOT NULL DEFAULT(1)
);

