CREATE TABLE [dbo].[ADVANCE_BILLING] (
    [AB_ID]             INT             NOT NULL,
    [SEQ_NBR]           SMALLINT        NOT NULL,
    [AB_FLAG]           SMALLINT        NOT NULL,
    [JOB_NUMBER]        INT             NOT NULL,
    [JOB_COMPONENT_NBR] SMALLINT        NOT NULL,
    [FNC_CODE]          VARCHAR (6)     NOT NULL,
    [FNC_TYPE]          VARCHAR (1)     NULL,
    [ADV_BILL_NET_AMT]  DECIMAL (14, 2) NULL,
    [COMMISSION_PCT]    DECIMAL (9, 3)  NULL,
    [AR_INV_NBR]        INT             NULL,
    [AR_INV_SEQ]        SMALLINT        NULL,
    [AR_TYPE]           VARCHAR (3)     NULL,
    [AR_INV_VOID]       SMALLINT        NULL,
    [CREATE_DATE]       SMALLDATETIME   DEFAULT (getdate()) NULL,
    [USER_ID]           VARCHAR (100)   NULL,
    [TAX_CODE]          VARCHAR (4)     NULL,
    [TAX_STATE_PCT]     DECIMAL (7, 4)  NULL,
    [TAX_COUNTY_PCT]    DECIMAL (7, 4)  NULL,
    [TAX_CITY_PCT]      DECIMAL (7, 4)  NULL,
    [TAX_RESALE]        SMALLINT        NULL,
    [TAX_COMM]          SMALLINT        NULL,
    [TAX_COMM_ONLY]     SMALLINT        NULL,
    [CALC_METHOD]       SMALLINT        NULL,
    [CALC_PERCENT]      DECIMAL (7, 3)  NULL,
    [BILLING_USER]      VARCHAR (100)   NULL,
    [ESTIMATE_NUMBER]   INT             NULL,
    [EST_COMPONENT_NBR] SMALLINT        NULL,
    [EST_QUOTE_NBR]     SMALLINT        NULL,
    [EST_REVISION_NBR]  SMALLINT        NULL,
    [GLACODE_SALES]     VARCHAR (30)    NULL,
    [GLACODE_COS]       VARCHAR (30)    NULL,
    [GLACODE_ACC_AP]    VARCHAR (30)    NULL,
    [GLACODE_STATE]     VARCHAR (30)    NULL,
    [GLACODE_CNTY]      VARCHAR (30)    NULL,
    [GLACODE_CITY]      VARCHAR (30)    NULL,
    [GLEXACT]           INT             NULL,
    [GLESEQ_SALES]      SMALLINT        NULL,
    [GLESEQ_COS]        SMALLINT        NULL,
    [GLESEQ_ACC_AP]     SMALLINT        NULL,
    [GLESEQ_STATE]      SMALLINT        NULL,
    [GLESEQ_CNTY]       SMALLINT        NULL,
    [GLESEQ_CITY]       SMALLINT        NULL,
    [FINAL_AB_FLAG]     SMALLINT        NULL,
    [FINAL_DATE]        SMALLDATETIME   NULL,
    [FINAL_AB_ID]       INT             NULL,
    [FINAL_SEQ_NBR]     SMALLINT        NULL,
    [FINAL_USER]        VARCHAR (100)   NULL,
    [EXT_MARKUP_AMT]    DECIMAL (14, 2) NULL,
    [EXT_NONRESALE_TAX] DECIMAL (14, 2) NULL,
    [EXT_STATE_RESALE]  DECIMAL (14, 2) NULL,
    [EXT_COUNTY_RESALE] DECIMAL (14, 2) NULL,
    [EXT_CITY_RESALE]   DECIMAL (14, 2) NULL,
    [LINE_TOTAL]        DECIMAL (14, 2) NULL,
    [POST_PERIOD]       VARCHAR (8)     NULL,
    [METHOD_DESC]       VARCHAR (30)    NULL,
    [BILL_DATE]         SMALLDATETIME   NULL,
    [USE_CONTINGENCY]   SMALLINT        NULL,
    [CMP_UPD_INV_DATE]  SMALLINT        NULL,
    [CMP_UPD_PP]        SMALLINT        NULL,
    [BCC_ID]            INT             NULL
);

