CREATE TABLE [dbo].[AGY_SETTINGS_DTYPE] (
    [DTYPE_ID]            INT          IDENTITY (1, 1) NOT NULL,
    [ADVAN_DTYPE_ID]      SMALLINT     NOT NULL,
    [AGY_SETTINGS_PREC]   SMALLINT     NULL,
    [AGY_SETTINGS_SCALE]  SMALLINT     NULL,
    [AGY_SETTINGS_DW_COL] VARCHAR (50) NULL
);

