CREATE TABLE [dbo].[AGY_BINARY_IMAGES] (
    [BINARY_IMAGE_CODE]  VARCHAR (20)  NOT NULL,
    [BINARY_IMAGE_DESC]  VARCHAR (100) NOT NULL,
    [BINARY_IMAGE_VALUE] IMAGE         NULL,
    [BINARY_IMAGE_APP]   SMALLINT      NULL
);

