CREATE TABLE [dbo].[AGY_SETTINGS] (
    [AGY_SETTINGS_CODE]  VARCHAR (20)  NOT NULL,
    [AGY_SETTINGS_DESC]  VARCHAR (100) NOT NULL,
    [AGY_SETTINGS_VALUE] SQL_VARIANT   NULL,
    [AGY_SETTINGS_DEF]   SQL_VARIANT   NULL,
    [AGY_SETTINGS_MIN]   INT           NULL,
    [AGY_SETTINGS_MAX]   INT           NULL,
    [AGY_SETTINGS_APP]   SMALLINT      NULL,
    [AGY_SETTINGS_TAB]   SMALLINT      NULL,
    [AGY_SETTINGS_GRP]   SMALLINT      NULL,
    [AGY_SETTINGS_ORDER] INT           NULL,
    [DTYPE_ID]           INT           NULL
);

