/****** Object:  Table [dbo].[ALERT_NOTIFY_DEPT_TEAM]    Script Date: 9/16/2013 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ALERT_NOTIFY_DEPT_TEAM](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ALRT_NOTIFY_HDR_ID] [int] NOT NULL,
	[ALERT_STATE_ID] [int] NOT NULL,
	[DEPT_TEAM_CODE] [varchar](4) NOT NULL,
 CONSTRAINT [PK_ALERT_NOTIFY_DEPT_TEAM] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


