CREATE TABLE [dbo].[ALERT_DOCUMENT] (
    [ADVANTAGE_ID] INT           IDENTITY (1, 1) NOT NULL,
    [ALERT_ID]     INT           NOT NULL,
    [NAME]         VARCHAR (255) NULL,
    [LOCATION]     VARCHAR (500) NULL,
    [CREATE_DATE]  SMALLDATETIME NOT NULL
);

