CREATE TABLE [dbo].[AP_CHK_TEMP] (
    [USER_ID]            VARCHAR (100)   NOT NULL,
    [AP_ID]              INT             NOT NULL,
    [AP_SEQ]             SMALLINT        NULL,
    [AP_TYPE]            VARCHAR (1)     NULL,
    [VN_FRL_EMP_CODE]    VARCHAR (6)     NOT NULL,
    [AP_INV_VCHR]        VARCHAR (20)    NULL,
    [AP_DESC]            VARCHAR (30)    NULL,
    [AP_INV_DATE]        SMALLDATETIME   NULL,
    [AP_DATE_PAY]        SMALLDATETIME   NULL,
    [GLACODE]            VARCHAR (30)    NULL,
    [VN_NAME]            VARCHAR (40)    NULL,
    [VN_PAY_TO_CODE]     VARCHAR (6)     NULL,
    [VN_PAY_TO_NAME]     VARCHAR (40)    NULL,
    [VN_CATEGORY]        VARCHAR (1)     NULL,
    [AP_INV_AMT]         DECIMAL (14, 2) NULL,
    [AP_SHIPPING]        DECIMAL (11, 2) NULL,
    [AP_SALES_TAX]       DECIMAL (11, 2) NULL,
    [AP_DISC_PCT]        DECIMAL (6, 3)  NULL,
    [ONE_CHECK_PER_INV]  SMALLINT        NULL,
    [CC_INV_TOTAL]       DECIMAL (14, 2) NULL,
    [CC_PAY_FLAG]        SMALLINT        NULL,
    [CC_AMT_TO_PAY]      DECIMAL (14, 2) NULL,
    [CC_DISC_AMT]        DECIMAL (14, 2) NULL,
    [CC_PAID_BY_CL]      DECIMAL (14, 2) NULL,
    [CC_NON_BILL_AMT]    AS              ([dbo].[udf_ap_get_non_bill_amt]([AP_ID])),
    [CC_BILL_AMT]        AS              ([dbo].[udf_ap_get_billable_amt]([AP_ID], [VN_CATEGORY])),
    [CC_INV_PAID_AMT]    AS              ([dbo].[udf_ap_get_pmt_disc_amt]([AP_ID])),
    [CC_INV_BAL]         AS              ([CC_INV_TOTAL] - [dbo].[udf_ap_get_pmt_disc_amt]([AP_ID])),
    [CC_TOTAL_QUALIFIED] DECIMAL (14, 2) NULL,
    [CC_CASH_RECEIVED]   VARCHAR (1)     NULL,
    [CC_BAL_TO_PAY]      DECIMAL (14, 2) NULL,
    [CC_DISC_AVAILABLE]  DECIMAL (14, 2) NULL,
    [CC_ROW_HDR]         VARCHAR (1)     NULL,
    [CC_DUMMY]           SMALLINT        NULL,
    [VN_ACCT_NBR]        VARCHAR (30)    NULL,
    [CC_PROD_ADV_AMT]    AS              ([dbo].[udf_ap_get_prod_adv_amt]([AP_ID])),
    [CC_CASH_AMT]        DECIMAL (14, 2) NULL,
    [CC_DIRECT_BILL_AMT] AS              ([dbo].[udf_ap_get_direct_bill_amt]([AP_ID], [VN_CATEGORY]))
);

