CREATE TABLE [dbo].[AP_NEWSPAPER] (
    [AP_ID]            INT             NOT NULL,
    [AP_SEQ]           SMALLINT        NOT NULL,
    [LINE_NUMBER]      SMALLINT        NOT NULL,
    [ORDER_NBR]        INT             NOT NULL,
    [ORDER_LINE_NBR]   SMALLINT        NOT NULL,
    [REV_NBR]          SMALLINT        NOT NULL,
    [SEQ_NBR]          SMALLINT        NOT NULL,
    [OFFICE_CODE]      VARCHAR (4)     NULL,
    [NET_GROSS]        SMALLINT        NULL,
    [COMM_PCT]         DECIMAL (6, 3)  NULL,
    [MARKUP_PCT]       DECIMAL (6, 3)  NULL,
    [REBATE_PCT]       DECIMAL (6, 3)  NULL,
    [TAX_CODE]         VARCHAR (4)     NULL,
    [TAX_STATE_PCT]    DECIMAL (7, 4)  NULL,
    [TAX_COUNTY_PCT]   DECIMAL (7, 4)  NULL,
    [TAX_CITY_PCT]     DECIMAL (7, 4)  NULL,
    [TAXAPPLYC]        SMALLINT        NULL,
    [TAXAPPLYLN]       SMALLINT        NULL,
    [TAXAPPLYLND]      SMALLINT        NULL,
    [TAXAPPLYNC]       SMALLINT        NULL,
    [TAXAPPLYNCD]      SMALLINT        NULL,
    [TAXAPPLYR]        SMALLINT        NULL,
    [TAX_RESALE]       SMALLINT        NULL,
    [POST_PERIOD]      VARCHAR (8)     NULL,
    [GLACODE]          VARCHAR (30)    NOT NULL,
    [GLACODE_DUE_FROM] VARCHAR (30)    NULL,
    [GLACODE_DUE_TO]   VARCHAR (30)    NULL,
    [GLEXACT]          INT             NULL,
    [GLESEQ]           SMALLINT        NULL,
    [GLESEQ_DUE_FROM]  SMALLINT        NULL,
    [GLESEQ_DUE_TO]    SMALLINT        NULL,
    [NET_AMT]          DECIMAL (14, 2) NULL,
    [GROSS_AMT]        DECIMAL (14, 2) NULL,
    [COMM_AMT]         DECIMAL (14, 2) NULL,
    [REBATE_AMT]       DECIMAL (14, 2) NULL,
    [VENDOR_TAX]       DECIMAL (14, 2) NULL,
    [STATE_TAX]        DECIMAL (14, 2) NULL,
    [COUNTY_TAX]       DECIMAL (14, 2) NULL,
    [CITY_TAX]         DECIMAL (14, 2) NULL,
    [COLOR_NET_AMT]    DECIMAL (16, 4) NULL,
    [COLOR_GROSS_AMT]  DECIMAL (16, 4) NULL,
    [NETCHARGES]       DECIMAL (14, 2) NULL,
    [DISCOUNT_LN]      DECIMAL (14, 2) NULL,
    [DISCOUNT_NC]      DECIMAL (14, 2) NULL,
    [NET_PLUS]         DECIMAL (16, 4) NULL,
    [GROSS_PLUS]       DECIMAL (16, 4) NULL,
    [DISBURSED_AMT]    DECIMAL (14, 2) NULL,
    [LINE_TOTAL]       DECIMAL (14, 2) NULL,
    [MODIFY_DELETE]    SMALLINT        NULL,
    [REC_FLAG]         SMALLINT        NULL,
    [DELETE_FLAG]      SMALLINT        NULL,
    [CONVERTED_521X]   SMALLINT        NULL,
    [PRINT_LINES]      DECIMAL (11, 2) NULL,
    [RATE]             DECIMAL (16, 4) NULL,
	[CREATED_BY]	   VARCHAR(100)	   NULL,
	[CREATE_DATE]	   SMALLDATETIME   NULL,
	[MODIFIED_BY]	   VARCHAR(100)    NULL,
	[MODIFY_DATE]	   SMALLDATETIME   NULL
);

