CREATE TABLE [dbo].[APP_VARS] (
    [USERID]         VARCHAR (100) NOT NULL,
    [APPLICATION]    VARCHAR (1000)  NOT NULL,
    [VARIABLE_GROUP] VARCHAR (1000)  NULL,
    [VARIABLE_NAME]  VARCHAR (1000)  NOT NULL,
    [VARIABLE_TYPE]  VARCHAR (200)  NULL,
    [VARIABLE_ORDER] INT           NULL,
    [VARIABLE_VALUE] VARCHAR (MAX) NULL
);

