CREATE TABLE [dbo].[ASSOCIATE] (
    [ASSOCIATE_ID]       INT            NOT NULL,
    [ASSOCIATE_CL_CODE]  VARCHAR (6)    NOT NULL,
    [ASSOCIATE_VN_CODE]  VARCHAR (6)    NULL,
    [ASSOCIATE_EMP_CODE] VARCHAR (6)    NULL,
    [ASSOCIATE_PCT]      DECIMAL (7, 3) NOT NULL,
    [ASSOCIATE_DIV_CODE] VARCHAR (6)    NULL,
    [ASSOCIATE_PRD_CODE] VARCHAR (6)    NULL,
    [ASSOCIATE_MED_TYPE] VARCHAR (1)    NULL,
    [ASSOCIATE_RPT_LVL]  SMALLINT       NULL
);

