CREATE TABLE [dbo].[ATB_HDR](
	[ATB_NUMBER] [int] IDENTITY(1,1) NOT NULL,
	[CL_CODE] [varchar](6) NOT NULL,
	[DIV_CODE] [varchar](6) NOT NULL,
	[PRD_CODE] [varchar](6) NOT NULL,
	[INACTIVE_FLAG] [smallint] NULL,
 CONSTRAINT [PK_ATB_HDR] PRIMARY KEY CLUSTERED 
(
	[ATB_NUMBER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[ATB_HDR]  WITH CHECK ADD  CONSTRAINT [FK_ATB_HDR_CLIENT] FOREIGN KEY([CL_CODE])
REFERENCES [dbo].[CLIENT] ([CL_CODE])
GO

ALTER TABLE [dbo].[ATB_HDR] CHECK CONSTRAINT [FK_ATB_HDR_CLIENT]
GO

ALTER TABLE [dbo].[ATB_HDR]  WITH CHECK ADD  CONSTRAINT [FK_ATB_HDR_DIVISION] FOREIGN KEY([CL_CODE], [DIV_CODE])
REFERENCES [dbo].[DIVISION] ([CL_CODE], [DIV_CODE])
GO

ALTER TABLE [dbo].[ATB_HDR] CHECK CONSTRAINT [FK_ATB_HDR_DIVISION]
GO

ALTER TABLE [dbo].[ATB_HDR]  WITH CHECK ADD  CONSTRAINT [FK_ATB_HDR_PRODUCT] FOREIGN KEY([CL_CODE], [DIV_CODE], [PRD_CODE])
REFERENCES [dbo].[PRODUCT] ([CL_CODE], [DIV_CODE], [PRD_CODE])
GO

ALTER TABLE [dbo].[ATB_HDR] CHECK CONSTRAINT [FK_ATB_HDR_PRODUCT]
GO