CREATE TABLE [dbo].[BANK_REC_HDR] (
    [BKH_CODE]           VARCHAR (4)     NOT NULL,
    [BKH_STMT_DT]        SMALLDATETIME   NOT NULL,
    [BKH_POST_PERIOD]    VARCHAR (6)     NULL,
    [BKH_OPEN_BAL]       DECIMAL (15, 2) NOT NULL,
    [BKH_END_BAL]        DECIMAL (15, 2) NOT NULL,
    [BKH_SERVICE_FEE]    DECIMAL (15, 2) NULL,
    [BKH_SERVICE_ACCT]   VARCHAR (30)    NULL,
    [BKH_INTEREST_AMT]   DECIMAL (15, 2) NULL,
    [BKH_INTEREST_ACCT]  VARCHAR (30)    NULL,
    [BKH_RECON_FLAG]     SMALLINT        NULL,
    [BKH_ADJ_GL_BAL]     DECIMAL (15, 2) NULL,
    [BKH_ADJ_STMT_BAL]   DECIMAL (15, 2) NULL,
    [BKH_RECON_DATETIME] SMALLDATETIME   NULL,
    [BKH_RECON_USER]     VARCHAR (100)   NULL
);

