CREATE TABLE [dbo].[BILL_APPR_DTL] (
    [BA_DTL_ID]           INT             IDENTITY (1, 1) NOT NULL,
    [BA_ID]               INT             NOT NULL,
    [JOB_NUMBER]          INT             NOT NULL,
    [JOB_COMPONENT_NBR]   SMALLINT        NOT NULL,
    [FNC_CODE]            VARCHAR (6)     NOT NULL,
    [QTY_HRS]             DECIMAL (15, 3) NULL,
    [BILLING_RATE]        DECIMAL (9, 2)  NULL,
    [FNC_DESC]            VARCHAR (30)    NULL,
    [APPROVED_AMT]        DECIMAL (15, 2) NULL,
    [FNC_COMMENTS]        TEXT            NULL,
    [CLIENT_COMMENTS]     TEXT            NULL,
    [ROW_TYPE]            TINYINT         NULL,
    [ITEM_EXISTS]         AS              ([dbo].[advfn_bill_appr_item_exists]([BA_DTL_ID])),
    [APPR_NET]            DECIMAL (14, 2) NULL,
    [APPR_MARKUP_PCT]     DECIMAL (6, 3)  NULL,
    [APPR_MARKUP_AMT]     DECIMAL (14, 2) NULL,
    [APPR_TAX_CODE]       VARCHAR (4)     NULL,
    [APPR_TAX_COMM]       SMALLINT        NULL,
    [APPR_TAX_COMM_ONLY]  SMALLINT        NULL,
    [APPR_TAX_RESALE]     SMALLINT        NULL,
    [APPR_RESALE_TAX]     DECIMAL (14, 2) NULL,
    [APPR_VENDOR_TAX]     DECIMAL (14, 2) NULL,
    [APPR_TAX_STATE_PCT]  DECIMAL (8, 4)  NULL,
    [APPR_TAX_COUNTY_PCT] DECIMAL (8, 4)  NULL,
    [APPR_TAX_CITY_PCT]   DECIMAL (8, 4)  NULL,
    [IS_USER_ROW]         BIT             NULL
);

