CREATE TABLE [dbo].[BILLING_CMD_CENTER] (
    [BCC_ID]             INT           IDENTITY (1, 1) NOT NULL,
    [BILLING_USER]       VARCHAR (100) NOT NULL,
    [CREATE_DATE]        SMALLDATETIME NOT NULL,
    [P_SELECT_BY]        SMALLINT      NULL,
    [PROD_FLAG]          BIT           NULL,
    [INC_NO_DTL]         BIT           NULL,
    [AB_JOBS_ONLY]       BIT           NULL,
    [P_ET_CUTOFF_DATE]   SMALLDATETIME NULL,
    [P_IO_CUTOFF_DATE]   SMALLDATETIME NULL,
    [P_AB_CUTOFF_DATE]   SMALLDATETIME NULL,
    [P_AP_CUTOFF_PPD]    VARCHAR (6)   NULL,
    [BA_BATCH_ID]        INT           NULL,
    [MEDIA_FLAG]         BIT           NULL,
    [M_SELECT_BY]        SMALLINT      NULL,
    [M_CUTOFF_DATE]      SMALLDATETIME NULL,
    [NEWSPAPER]          BIT           NULL,
    [MAGAZINE]           BIT           NULL,
    [RADIO]              BIT           NULL,
    [TELEVISION]         BIT           NULL,
    [OUT_OF_HOME]        BIT           NULL,
    [INTERNET]           BIT           NULL,
    [M_BRDCAST_MTH1]     SMALLDATETIME NULL,
    [M_BRDCAST_MTH2]     SMALLDATETIME NULL,
    [INCL_ZERO_SPOTS]    BIT           NULL,
    [SELECTED_ORDERS]    AS            ([dbo].[advfn_bcc_order_count]([BCC_ID])),
    [M_START_DATE]       SMALLDATETIME NULL,
    [DATE_CUTOFF_TO_USE] SMALLINT      NULL,
    [INCL_UNBILLED_ONLY] SMALLINT      NULL,
    [SEL_OPTION]         SMALLINT      NULL,
    [IN_USE]             BIT           NULL,
    [SELECTED_JOBS]      AS            ([dbo].[advfn_bcc_job_count]([BCC_ID])),
    [RADIO_DAILY]        BIT           NULL,
    [TV_DAILY]           BIT           NULL,
    [RADIO_MONTHLY]      BIT           NULL,
    [TV_MONTHLY]         BIT           NULL
);

