CREATE TABLE [dbo].[BILL_CMD_CTR_CONFIG] (
    [BILLING_USER] VARCHAR (100) NOT NULL,
    [SEQ_NBR]      SMALLINT      NOT NULL,
    [BCCC_ID]      SMALLINT      NOT NULL,
    [TAB_ORDER]    SMALLINT      NOT NULL,
    [COL_WIDTH]    SMALLINT      NOT NULL
);

