CREATE TABLE [dbo].[BRD_IMPORT_VOUCHER] (
    [VOUCHER]     DECIMAL (8)     NULL,
    [VENDOR]      VARCHAR (8)     NULL,
    [INVNO]       VARCHAR (30)    NULL,
    [INVDATE]     SMALLDATETIME   NULL,
    [DUEDATE]     SMALLDATETIME   NULL,
    [DISCDATE]    SMALLDATETIME   NULL,
    [PAYAMT]      DECIMAL (12, 2) NULL,
    [DISCAMT]     DECIMAL (12, 2) NULL,
    [TAXAMT]      DECIMAL (12, 2) NULL,
    [BALAMT]      DECIMAL (12, 2) NULL,
    [GROSSAMT]    DECIMAL (12, 2) NULL,
    [ROUNDAMT]    DECIMAL (4, 2)  NULL,
    [SYSTEM]      VARCHAR (4)     NULL,
    [MEDIA]       VARCHAR (2)     NULL,
    [CLIENT]      VARCHAR (4)     NULL,
    [PRODUCT]     VARCHAR (4)     NULL,
    [ESTIMATE]    VARCHAR (30)    NULL,
    [STATION]     VARCHAR (5)     NULL,
    [MARKET]      VARCHAR (4)     NULL,
    [BAND]        VARCHAR (2)     NULL,
    [CONTRCTNO]   VARCHAR (12)    NULL,
    [USCAN]       VARCHAR (1)     NULL,
    [TRNXTYPE]    VARCHAR (1)     NULL,
    [HOLDSTAT]    DECIMAL (1)     NULL,
    [SLCTSTAT]    VARCHAR (1)     NULL,
    [PAIDSTAT]    VARCHAR (1)     NULL,
    [PAIDDATE]    SMALLDATETIME   NULL,
    [CHECKNO]     VARCHAR (10)    NULL,
    [GLPERIOD]    VARCHAR (5)     NULL,
    [ADDDATE]     SMALLDATETIME   NULL,
    [ADDTIME]     VARCHAR (8)     NULL,
    [CUSER]       VARCHAR (100)   NULL,
    [CLTINT1]     VARCHAR (8)     NULL,
    [CLTINT2]     VARCHAR (8)     NULL,
    [PRODINT1]    VARCHAR (8)     NULL,
    [PRODINT2]    VARCHAR (8)     NULL,
    [ESTINT1]     VARCHAR (8)     NULL,
    [ESTINT2]     VARCHAR (8)     NULL,
    [STNINT1]     VARCHAR (8)     NULL,
    [STNINT2]     VARCHAR (8)     NULL,
    [CLTNAME]     VARCHAR (30)    NULL,
    [PRODNAME]    VARCHAR (30)    NULL,
    [ESTNAME]     VARCHAR (30)    NULL,
    [NOTE1]       VARCHAR (80)    NULL,
    [NOTE2]       VARCHAR (80)    NULL,
    [NOTE3]       VARCHAR (80)    NULL,
    [IMPORT_STAT] VARCHAR (1)     NULL,
    [STAT_DATE]   SMALLDATETIME   DEFAULT (getdate()) NULL,
    [COL_ID]      FLOAT           NULL
);

