CREATE TABLE [dbo].[BRDCAST_IMPORT_INV] (
    [RECSEQ]          INT             NOT NULL,
    [REV_NBR]         SMALLINT        NOT NULL,
    [MEDIA_TYPE]      VARCHAR (2)     NOT NULL,
    [LINK_ID]         INT             NOT NULL,
    [ORD_LINE_NBR]    VARCHAR (3)     NULL,
    [INV_NUMBER]      VARCHAR (20)    NOT NULL,
    [INV_DATE]        SMALLDATETIME   NOT NULL,
    [CL_CODE]         VARCHAR (6)     NULL,
    [PROD_CODE]       VARCHAR (6)     NULL,
    [DIV_CODE]        VARCHAR (6)     NULL,
    [VENDOR_CODE]     VARCHAR (6)     NOT NULL,
    [TOTAL_GROSS]     DECIMAL (14, 2) NULL,
    [TOTAL_NET]       DECIMAL (14, 2) NULL,
    [BC_MONTH]        VARCHAR (3)     NULL,
    [BC_YEAR]         SMALLINT        NULL,
    [BC_WEEK]         SMALLDATETIME   NULL,
    [BAD_FLAG]        SMALLINT        NULL,
    [GL_PERIOD]       VARCHAR (5)     NULL,
    [INV_DESC]        VARCHAR (30)    NULL,
    [ADVAN_ORDER_NBR] INT             NULL,
    [ORG_VN_CODE]     VARCHAR (6)     NULL,
    [MEDIA_INTERFACE] VARCHAR (2)     NULL,
    [CREATE_DATE]     SMALLDATETIME   NULL,
    [CREATE_TIME]     VARCHAR (8)     NULL,
    [VOUCHER_ID]      VARCHAR (8)     NULL,
    [BUYER]           VARCHAR (8)     NULL,
    [POST_FLAG]       SMALLINT        NOT NULL,
    [GL_CODE]         VARCHAR (30)    NULL,
    [TOTAL_INV_AMT]   DECIMAL (14, 2) NULL,
    [TOTAL_INV_TAX]   DECIMAL (14, 2) NULL,
    [TOTAL_TAX]       DECIMAL (14, 2) NULL,
    [POST_TO_VENDOR]  VARCHAR (6)     NULL,
    [DELETE_INV]      SMALLINT        NULL
);

