
/****** Object:  Table [dbo].[BRDCAST_IMPORT_UNITS]    Script Date: 05/06/2014 16:03:38 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[BRDCAST_IMPORT_UNITS]') AND type in (N'U'))
DROP TABLE [dbo].[BRDCAST_IMPORT_UNITS]
GO

/****** Object:  Table [dbo].[BRDCAST_IMPORT_UNITS]    Script Date: 05/06/2014 16:03:38 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING OFF
GO

CREATE TABLE [dbo].[BRDCAST_IMPORT_UNITS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[LINK_ID] [int] NOT NULL,
	[LINE_NBR] [int] NOT NULL,
	[LINK_UNITID] [int] NOT NULL,	
	[PRD_CODE] [varchar](6) NOT NULL,
	[UNITS] [int] NOT NULL,		
	[UNIT_DATE] [smalldatetime] NOT NULL,
	[CANCEL_FLAG] [int] NULL,
	[POST_FLAG] [int] NOT NULL

) ON [PRIMARY]

SET ANSI_PADDING ON

ALTER TABLE [dbo].[BRDCAST_IMPORT_UNITS] ADD  CONSTRAINT [PK_BRDCAST_IMPORT_UNITS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

ALTER TABLE [dbo].[BRDCAST_IMPORT_UNITS] ADD UNIQUE([LINK_ID], [LINE_NBR], [LINK_UNITID])
GO

GRANT SELECT, INSERT, UPDATE, DELETE ON [BRDCAST_IMPORT_UNITS] TO PUBLIC AS dbo
GO

SET ANSI_PADDING OFF
GO


