CREATE TABLE [dbo].[BUDGET_APPROVE_COMMENT] (
    [BUDGET_CODE]      VARCHAR (10)  NOT NULL,
    [APPROVED_BY]      VARCHAR (6)   NULL,
    [APPROVED_USER]    VARCHAR (6)   NULL,
    [APPROVAL_DATE]    SMALLDATETIME NULL,
    [APPROVAL_COMMENT] TEXT          NULL
);

