CREATE TABLE [dbo].[CAMPAIGN] (
    [CL_CODE]           VARCHAR (6)     NOT NULL,
    [DIV_CODE]          VARCHAR (6)     NULL,
    [PRD_CODE]          VARCHAR (6)     NULL,
    [CMP_CODE]          VARCHAR (6)     NOT NULL,
    [CMP_BEG_DATE]      SMALLDATETIME   NULL,
    [CMP_END_DATE]      SMALLDATETIME   NULL,
    [CMP_COMMENTS]      TEXT            NULL,
    [CMP_NAME]          VARCHAR (60)    NULL,
    [CMP_DIRECT]        SMALLINT        NULL,
    [CMP_MAGAZINE]      SMALLINT        NULL,
    [CMP_NEWSPAPER]     SMALLINT        NULL,
    [CMP_OUTDOOR]       SMALLINT        NULL,
    [CMP_PRINT_COLL]    SMALLINT        NULL,
    [CMP_RADIO]         SMALLINT        NULL,
    [CMP_TELEVISION]    SMALLINT        NULL,
    [CMP_OTHER]         SMALLINT        NULL,
    [CMP_OTHER_EXPLAIN] VARCHAR (30)    NULL,
    [CMP_IDENTIFIER]    INT             NOT NULL,
    [CMP_CLOSED]        SMALLINT        NULL,
    [ACTIVE_FLAG]       SMALLINT        NULL,
    [CMP_BILL_BUDGET]   DECIMAL (18, 2) NULL,
    [CMP_INC_BUDGET]    DECIMAL (18, 2) NULL,
    [CMP_TYPE]          SMALLINT        NOT NULL,
    [OFFICE_CODE]       VARCHAR (4)     NULL,
    [ALERT_GROUP]       VARCHAR (50)    NULL,
    [CMP_INTERNET]      SMALLINT        NULL
);

