CREATE TABLE [dbo].[CLIENT_XREF](
	[CLIENT_XREF_ID] [int] IDENTITY(1,1) NOT NULL,
	[CL_CODE] [varchar](6) NOT NULL,
	[DIV_CODE] [varchar](6) NOT NULL,
	[PRD_CODE] [varchar](6) NOT NULL,
	[SOURCE_CL_CODE] [varchar](100) NULL,
	[SOURCE_DIV_CODE] [varchar](100) NULL,
	[SOURCE_PRD_CODE] [varchar](100) NULL,
	[REC_TYPE] [int] NOT NULL,
 CONSTRAINT [PK_CLIENT_XREF] PRIMARY KEY CLUSTERED 
(
	[CLIENT_XREF_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
