CREATE TABLE [dbo].[CLIENT] (
    [CL_CODE]            VARCHAR (6)     NOT NULL,
    [CL_NAME]            VARCHAR (40)    NULL,
    [CL_ADDRESS1]        VARCHAR (40)    NULL,
    [CL_ADDRESS2]        VARCHAR (40)    NULL,
    [CL_CITY]            VARCHAR (20)    NULL,
    [CL_COUNTY]          VARCHAR (20)    NULL,
    [CL_STATE]           VARCHAR (10)    NULL,
    [CL_COUNTRY]         VARCHAR (20)    NULL,
    [CL_ZIP]             VARCHAR (10)    NULL,
    [CL_ATTENTION]       VARCHAR (40)    NULL,
    [CL_BADDRESS1]       VARCHAR (40)    NULL,
    [CL_BADDRESS2]       VARCHAR (40)    NULL,
    [CL_BCITY]           VARCHAR (20)    NULL,
    [CL_BCOUNTY]         VARCHAR (20)    NULL,
    [CL_BSTATE]          VARCHAR (10)    NULL,
    [CL_BCOUNTRY]        VARCHAR (20)    NULL,
    [CL_BZIP]            VARCHAR (10)    NULL,
    [CL_SADDRESS1]       VARCHAR (40)    NULL,
    [CL_SADDRESS2]       VARCHAR (40)    NULL,
    [CL_SCITY]           VARCHAR (20)    NULL,
    [CL_SCOUNTY]         VARCHAR (20)    NULL,
    [CL_SSTATE]          VARCHAR (10)    NULL,
    [CL_SCOUNTRY]        VARCHAR (20)    NULL,
    [CL_SZIP]            VARCHAR (10)    NULL,
    [CL_FOOTER]          VARCHAR (60)    NULL,
    [CL_ALPHA_SORT]      VARCHAR (20)    NULL,
    [CL_FISCAL_START]    SMALLINT        NULL,
    [CL_CREDIT_LIMIT]    DECIMAL (15, 2) NULL,
    [CL_HIGH_BALANCE]    DECIMAL (15, 2) NULL,
    [CL_INV_BY]          SMALLINT        NULL,
    [INV_FORMAT]         VARCHAR (12)    NULL,
    [CL_MATTENTION]      VARCHAR (40)    NULL,
    [PINV_FORMAT]        VARCHAR (12)    NULL,
    [BINV_FORMAT]        VARCHAR (12)    NULL,
    [CL_MINV_BY]         SMALLINT        NULL,
    [CL_MFOOTER]         VARCHAR (60)    NULL,
    [ACTIVE_FLAG]        SMALLINT        NULL,
    [NEW_BUSINESS]       SMALLINT        NULL,
    [CMP_CODE_R]         SMALLINT        NULL,
    [ACCT_NBR_R]         SMALLINT        NULL,
    [JT_CODE_R]          SMALLINT        NULL,
    [PROMO_CODE_R]       SMALLINT        NULL,
    [REQ_FLDS]           SMALLINT        NULL,
    [JOB_FIRST_USE_DT_R] SMALLINT        NULL,
    [COMPLEX_CODE_R]     SMALLINT        NULL,
    [FORMAT_SC_CODE_R]   SMALLINT        NULL,
    [DP_TM_CODE_R]       SMALLINT        NULL,
    [MARKET_CODE_R]      SMALLINT        NULL,
    [EMAIL_GR_CODE_R]    SMALLINT        NULL,
    [BILL_COOP_CODE_R]   SMALLINT        NULL,
    [AD_NBR_R]           SMALLINT        NULL,
    [JOB_CLI_REF_R]      SMALLINT        NULL,
    [JOB_DATE_OPENED_R]  SMALLINT        NULL,
    [JOB_AD_SIZE_R]      SMALLINT        NULL,
    [PROD_CONT_CODE_R]   SMALLINT        NULL,
    [JOB_COMP_BUDGET_R]  SMALLINT        NULL,
    [OINV_FORMAT]        VARCHAR (12)    NULL,
    [IINV_FORMAT]        VARCHAR (12)    NULL,
    [START_DATE_R]       SMALLINT        NULL,
    [JOB_LOG_UDV1_R]     SMALLINT        NULL,
    [JOB_LOG_UDV2_R]     SMALLINT        NULL,
    [JOB_LOG_UDV3_R]     SMALLINT        NULL,
    [JOB_LOG_UDV4_R]     SMALLINT        NULL,
    [JOB_LOG_UDV5_R]     SMALLINT        NULL,
    [JOB_CMP_UDV1_R]     SMALLINT        NULL,
    [JOB_CMP_UDV2_R]     SMALLINT        NULL,
    [JOB_CMP_UDV3_R]     SMALLINT        NULL,
    [JOB_CMP_UDV4_R]     SMALLINT        NULL,
    [JOB_CMP_UDV5_R]     SMALLINT        NULL,
    [PINV_FORMAT2]       VARCHAR (12)    NULL,
    [CL_AR_COMMENT]      TEXT            NULL,
    [REQ_PROD_CAT]       SMALLINT        NULL,
    [TAX_FLAG_R]         SMALLINT        NULL,
    [FISCAL_PD_R]        SMALLINT        NULL,
    [BLACKPLATE_VER_R]   SMALLINT        NULL,
    [BLACKPLATE_VER2_R]  SMALLINT        NULL,
    [CL_P_PAYDAYS]       SMALLINT        NULL,
    [CL_M_PAYDAYS]       SMALLINT        NULL
);

