--GO
--GO
--GO
CREATE TABLE [dbo].[CONTRACT](
	[CONTRACT_ID] [int] IDENTITY(1,1) NOT NULL,
	[CONTRACT_CODE] [varchar](6) NOT NULL,
	[CL_CODE] [varchar](6) NOT NULL,
	[DIV_CODE] [varchar](6) NULL,
	[PRD_CODE] [varchar](6) NULL,
	[DESCRIPTION] [varchar](100) NULL,
	[IS_CONTRACT] [bit] NOT NULL,
	[START_DATE] [smalldatetime] NULL,
	[END_DATE] [smalldatetime] NULL,
	[FEE_FLAG] [bit] NOT NULL,
	[PROJECT_HOURLY_FLAG] [bit] NOT NULL,
	[FEE_RETAINER] [decimal](14, 2) NULL,
	[FEE_INCENTIVE_BONUS] [decimal](14, 2) NULL,
	[FEE_ROYALTY] [decimal](14, 2) NULL,
	[FEE_PROJECT_HOURLY] [decimal](14, 2) NULL,
	[MEDIA_COMMISSION] [decimal](14, 2) NULL,
	[PRODUCTION_COMMISSION] [decimal](14, 2) NULL,
	[BILLING_RATE_COMMENT] [varchar](max) NULL,
	[BILLING_TERMS] [varchar](max) NULL,
	[ESTIMATING_TERMS] [varchar](max) NULL,
	[INACTIVE_FLAG] [bit] NOT NULL,
	[CREATED_BY] [varchar](100) NOT NULL,
	[CREATE_DATE] [smalldatetime] NOT NULL,
	[MODIFIED_BY] [varchar](100) NULL,
	[MODIFIED_DATE] [smalldatetime] NULL,
 CONSTRAINT [PK_CONTRACT] PRIMARY KEY CLUSTERED 
(
	[CONTRACT_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CONTRACT] ADD UNIQUE([CONTRACT_CODE], [CL_CODE])
GO

ALTER TABLE [dbo].[CONTRACT] ADD  CONSTRAINT [DF_CONTRACT_INACTIVE_FLAG]  DEFAULT ((0)) FOR [INACTIVE_FLAG]
GO


