CREATE TABLE [dbo].[CRTV_BRF_LVL1] (
    [CRTV_BRF_LVL1_ID]   SMALLINT      NOT NULL,
    [CRTV_BRF_LVL1_DESC] VARCHAR (254) NULL,
    [CRTV_BRF_DEF_ID]    INT           NOT NULL,
    [LVL1_ORDER]         SMALLINT      NULL,
    [QUERY_TYPE]         VARCHAR (8)   NULL
);

