CREATE TABLE [dbo].[CRTV_BRF_LVL2] (
    [CRTV_BRF_LVL2_ID]   SMALLINT      NOT NULL,
    [CRTV_BRF_LVL2_DESC] VARCHAR (254) NULL,
    [CRTV_BRF_LVL1_ID]   SMALLINT      NOT NULL,
    [LVL2_ORDER]         SMALLINT      NULL,
    [QUERY_TYPE]         VARCHAR (8)   NULL
);

