CREATE TABLE [dbo].[CRTV_BRF_APPR] (
    [JOB_NUMBER]        INT           NOT NULL,
    [JOB_COMPONENT_NBR] SMALLINT      NOT NULL,
    [CB_APPR_BY]        VARCHAR (40)  NOT NULL,
    [CB_APPR_COMMENT]   TEXT          NULL,
    [CB_APPR_USER_ID]   VARCHAR (100) NULL,
    [CB_APPR_DATE]      SMALLDATETIME NULL
);

