CREATE TABLE [dbo].[DASH_DATA_PROJ_HDR] (
    [OFFICE_CODE]        VARCHAR (4)     NULL,
    [OFFICE_NAME]        VARCHAR (30)    NULL,
    [CL_CODE]            VARCHAR (6)     NULL,
    [CL_NAME]            VARCHAR (40)    NULL,
    [DIV_CODE]           VARCHAR (6)     NULL,
    [DIV_NAME]           VARCHAR (40)    NULL,
    [PRD_CODE]           VARCHAR (6)     NULL,
    [PRD_DESCRIPTION]    VARCHAR (40)    NULL,
    [CMP_CODE]           VARCHAR (6)     NULL,
    [CMP_IDENTIFIER]     INT             NULL,
    [CMP_NAME]           VARCHAR (60)    NULL,
    [CMP_BEGIN_DATE]     SMALLDATETIME   NULL,
    [CMP_END_DATE]       SMALLDATETIME   NULL,
    [CMP_BILL]           DECIMAL (18, 2) NULL,
    [CMP_INC]            DECIMAL (18, 2) NULL,
    [SC_CODE]            VARCHAR (6)     NULL,
    [SC_DESCRIPTION]     VARCHAR (30)    NULL,
    [JOB]                INT             NULL,
    [JOB_DESC]           VARCHAR (60)    NULL,
    [JOB_COMMENTS]       TEXT            NULL,
    [BILL_COMMENT]       VARCHAR (254)   NULL,
    [JOB_CLI_REF]        VARCHAR (30)    NULL,
    [JOB_UDV1_CODE]      VARCHAR (10)    NULL,
    [JOB_UDV1_DESC]      VARCHAR (40)    NULL,
    [JOB_UDV2_CODE]      VARCHAR (10)    NULL,
    [JOB_UDV2_DESC]      VARCHAR (40)    NULL,
    [JOB_UDV3_CODE]      VARCHAR (10)    NULL,
    [JOB_UDV3_DESC]      VARCHAR (40)    NULL,
    [JOB_UDV4_CODE]      VARCHAR (10)    NULL,
    [JOB_UDV4_DESC]      VARCHAR (40)    NULL,
    [JOB_UDV5_CODE]      VARCHAR (10)    NULL,
    [JOB_UDV5_DESC]      VARCHAR (40)    NULL,
    [JOB_COMPONENT_NBR]  SMALLINT        NULL,
    [JOB_COMP_DESC]      VARCHAR (60)    NULL,
    [JOB_COMP_DATE]      SMALLDATETIME   NULL,
    [JOB_FIRST_USE_DATE] SMALLDATETIME   NULL,
    [JOB_COMP_COMMENTS]  TEXT            NULL,
    [APPR_COMMENT]       TEXT            NULL,
    [ACCT_EXEC]          VARCHAR (6)     NULL,
    [EMP_LNAME]          VARCHAR (30)    NULL,
    [EMP_FNAME]          VARCHAR (30)    NULL,
    [EMP_MI]             VARCHAR (1)     NULL,
    [CLIENT_PO]          VARCHAR (40)    NULL,
    [DP_TM_CODE]         VARCHAR (4)     NULL,
    [DP_TM_DESC]         VARCHAR (30)    NULL,
    [JOB_TYPE]           VARCHAR (10)    NULL,
    [JT_DESC]            VARCHAR (30)    NULL,
    [BUDGET_AMT]         DECIMAL (11, 2) NULL,
    [APPR_REQ_TYPE]      VARCHAR (6)     NULL,
    [APPR_TOTAL]         DECIMAL (11, 2) NULL,
    [COMP_UDV1_CODE]     VARCHAR (10)    NULL,
    [COMP_UDV1_DESC]     VARCHAR (40)    NULL,
    [COMP_UDV2_CODE]     VARCHAR (10)    NULL,
    [COMP_UDV2_DESC]     VARCHAR (40)    NULL,
    [COMP_UDV3_CODE]     VARCHAR (10)    NULL,
    [COMP_UDV3_DESC]     VARCHAR (40)    NULL,
    [COMP_UDV4_CODE]     VARCHAR (10)    NULL,
    [COMP_UDV4_DESC]     VARCHAR (40)    NULL,
    [COMP_UDV5_CODE]     VARCHAR (10)    NULL,
    [COMP_UDV5_DESC]     VARCHAR (40)    NULL,
    [JOB_PROCESS_CONTRL] SMALLINT        NULL,
    [COMPLETED_DATE]     SMALLDATETIME   NULL
);

