CREATE TABLE [dbo].[DEPT_TEAM] (
    [DP_TM_CODE]          VARCHAR (4)    NOT NULL,
    [DP_TM_DESC]          VARCHAR (30)   NULL,
    [INACTIVE_FLAG]       SMALLINT       NULL,
    [DIRECT_HRS_PER_GOAL] DECIMAL (7, 4) NULL,
    [CATEGORY]            VARCHAR (30)   NULL,
    [PO_APPR_RULE_CODE]   VARCHAR (6)    NULL,
	[SERVICE_FEE_TYPE_CODE] VARCHAR (6) NULL
);

