CREATE TABLE [dbo].[EMAIL_DEF_SUB_BODY] (
    [EMAIL_USER_ID] VARCHAR (100) NOT NULL,
    [EMAIL_APP]     VARCHAR (20)  NOT NULL,
    [EMAIL_SUBJECT] TEXT          NULL,
    [EMAIL_BODY]    TEXT          NULL,
    [EMAIL_CC]      SMALLINT      NULL
);

