CREATE TABLE [dbo].[EMP_TIME_INFO] (
    [EMP_CODE]          VARCHAR (6)     NOT NULL,
    [TIME_DATE]         SMALLDATETIME   NOT NULL,
    [ET_ID]             INT             NOT NULL,
    [SEQ_NBR]           SMALLINT        NOT NULL,
    [TIME_TYPE]         VARCHAR (6)     NOT NULL,
    [FNC_CODE]          VARCHAR (10)    NOT NULL,
    [DESCRIPTION]       VARCHAR (40)    NULL,
    [EMP_FNAME]         VARCHAR (30)    NULL,
    [EMP_MI]            VARCHAR (1)     NULL,
    [EMP_LNAME]         VARCHAR (30)    NULL,
    [DP_TM_CODE]        VARCHAR (4)     NULL,
    [DP_TM_DESC]        VARCHAR (40)    NULL,
    [EMP_HOURS]         DECIMAL (7, 2)  NULL,
    [BILL_RATE]         DECIMAL (7, 2)  NULL,
    [COST_RATE]         DECIMAL (7, 2)  NULL,
    [AB_FLAG]           SMALLINT        NULL,
    [CL_CODE]           VARCHAR (6)     NULL,
    [CL_NAME]           VARCHAR (40)    NULL,
    [DIV_CODE]          VARCHAR (6)     NULL,
    [DIV_NAME]          VARCHAR (40)    NULL,
    [PRD_CODE]          VARCHAR (6)     NULL,
    [PRD_DESCRIPTION]   VARCHAR (40)    NULL,
    [CMP_CODE]          VARCHAR (6)     NULL,
    [CMP_NAME]          VARCHAR (40)    NULL,
    [SC_CODE]           VARCHAR (6)     NULL,
    [SC_DESC]           VARCHAR (40)    NULL,
    [JOB_NUMBER]        INT             NULL,
    [JOB_DESC]          VARCHAR (30)    NULL,
    [JOB_COMPONENT_NBR] SMALLINT        NULL,
    [JOB_COMP_DESC]     VARCHAR (30)    NULL,
    [JOB_DP_TM]         VARCHAR (4)     NULL,
    [JOB_DP_TM_DESC]    VARCHAR (40)    NULL,
    [TAX_CODE]          VARCHAR (4)     NULL,
    [TAX_DESC]          VARCHAR (30)    NULL,
    [TAX_STATE_PCT]     DECIMAL (8, 4)  NULL,
    [TAX_COUNTY_PCT]    DECIMAL (8, 4)  NULL,
    [TAX_CITY_PCT]      DECIMAL (8, 4)  NULL,
    [TAX_RESALE]        SMALLINT        NULL,
    [TAX_COMM]          SMALLINT        NULL,
    [TAX_COMM_ONLY]     SMALLINT        NULL,
    [COMM_PCT]          DECIMAL (7, 3)  NULL,
    [NON_BILL_FLAG]     SMALLINT        NULL,
    [BILL_HOLD_FLG]     SMALLINT        NULL,
    [RATE_FROM]         VARCHAR (3)     NULL,
    [AR_TYPE]           VARCHAR (3)     NULL,
    [AR_INV_NBR]        INT             NULL,
    [GLEXACT_BILL]      INT             NULL,
    [GLESEQ_SALES]      SMALLINT        NULL,
    [GLESEQ_STATE]      SMALLINT        NULL,
    [GLESEQ_CNTY]       SMALLINT        NULL,
    [GLESEQ_CITY]       SMALLINT        NULL,
    [GLACODE_SALES]     VARCHAR (30)    NULL,
    [GLACODE_STATE]     VARCHAR (30)    NULL,
    [GLACODE_CNTY]      VARCHAR (30)    NULL,
    [GLACODE_CITY]      VARCHAR (30)    NULL,
    [TIME_COMMENT]      TEXT            NULL,
    [ADJ_COMMENTS]      TEXT            NULL,
    [BILLING_USER]      VARCHAR (100)   NULL,
    [DATE_ENTERED]      SMALLDATETIME   DEFAULT (getdate()) NULL,
    [USER_ID]           VARCHAR (100)   NULL,
    [TOTAL_COST]        DECIMAL (14, 2) NULL,
    [TOTAL_BILL]        DECIMAL (14, 2) NULL
);

