IF NOT EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'EMPLOYEE_ADDL_EMAIL') BEGIN

	CREATE TABLE [dbo].[EMPLOYEE_ADDL_EMAIL](
	    [EMP_CODE] [varchar](6) NOT NULL,
	    [EMP_EMAIL] [varchar](50) NULL,
     CONSTRAINT [PK_EMPLOYEE_ADDL_EMAIL] PRIMARY KEY CLUSTERED 
    (
	    [EMP_CODE] ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
    ) ON [PRIMARY]

END
GO