--Braxton
CREATE TABLE [dbo].[EMPLOYEE_TITLE] (
    [EMPLOYEE_TITLE_ID]    INT          IDENTITY (1, 1) NOT NULL,
    [EMPLOYEE_TITLE]       VARCHAR (50) NOT NULL,
    [EMPLOYEE_CATEGORY_ID] INT          NULL,
	[DP_TM_CODE]		   VARCHAR (4) NULL,
    [INACTIVE_FLAG]        SMALLINT     NULL
);

