CREATE TABLE [dbo].[EMPLOYEE_CLOAK] (
    [EMP_CODE]              VARCHAR (6)     NOT NULL,
    [DP_TM_CODE]            VARCHAR (4)     NULL,
    [EMP_LNAME]             VARCHAR (30)    NULL,
    [EMP_FNAME]             VARCHAR (30)    NULL,
    [EMP_MI]                VARCHAR (1)     NULL,
    [EMP_COST_RATE]         DECIMAL (9, 2)  NULL,
    [EMP_ADDRESS1]          VARCHAR (30)    NULL,
    [EMP_ADDRESS2]          VARCHAR (30)    NULL,
    [EMP_ALPHA_SORT]        VARCHAR (20)    NULL,
    [EMP_CITY]              VARCHAR (20)    NULL,
    [EMP_COUNTRY]           VARCHAR (20)    NULL,
    [EMP_COUNTY]            VARCHAR (20)    NULL,
    [EMP_PAY_TO_ADDR1]      VARCHAR (30)    NULL,
    [EMP_PAY_TO_ADDR2]      VARCHAR (30)    NULL,
    [EMP_PAY_TO_CITY]       VARCHAR (20)    NULL,
    [EMP_PAY_TO_COUNTRY]    VARCHAR (20)    NULL,
    [EMP_PAY_TO_COUNTY]     VARCHAR (20)    NULL,
    [EMP_PAY_TO_STATE]      VARCHAR (10)    NULL,
    [EMP_PAY_TO_ZIP]        VARCHAR (10)    NULL,
    [EMP_PHONE]             VARCHAR (13)    NULL,
    [EMP_STATE]             VARCHAR (10)    NULL,
    [EMP_OTHER_INFO]        VARCHAR (20)    NULL,
    [EMP_ZIP]               VARCHAR (10)    NULL,
    [EMP_TITLE]             VARCHAR (30)    NULL,
    [EMP_DATE]              SMALLDATETIME   NULL,
    [EMP_TERM_DATE]         SMALLDATETIME   NULL,
    [EMP_BIRTH_DATE]        SMALLDATETIME   NULL,
    [EMP_LAST_INCREASE]     SMALLDATETIME   NULL,
    [EMP_NEXT_REVIEW]       SMALLDATETIME   NULL,
    [EMP_ANNUAL_SALARY]     DECIMAL (15, 2) NULL,
    [EMP_MONTHLY_SALARY]    DECIMAL (11, 2) NULL,
    [EMP_EMAIL]             VARCHAR (50)    NULL,
    [MTH_HRS_GOAL]          DECIMAL (9, 3)  NULL,
    [OFFICE_CODE]           VARCHAR (4)     NULL,
    [SUPERVISOR_CODE]       VARCHAR (6)     NULL,
    [VAC_HRS]               DECIMAL (9, 3)  NULL,
    [VAC_FROM_DATE]         SMALLDATETIME   NULL,
    [VAC_TO_DATE]           SMALLDATETIME   NULL,
    [SICK_HRS]              DECIMAL (9, 3)  NULL,
    [SICK_FROM_DATE]        SMALLDATETIME   NULL,
    [SICK_TO_DATE]          SMALLDATETIME   NULL,
    [STD_WORK_HRS]          DECIMAL (9, 3)  NULL,
    [EMP_WORK_DAYS]         VARCHAR (30)    NULL,
    [EMP_TIME_ALERT]        SMALLINT        NULL,
    [SMTP_SERVER]           VARCHAR (40)    NULL,
    [EMAIL_PWD]             VARCHAR (50)    NULL,
    [MON_HRS]               DECIMAL (9, 3)  NULL,
    [TUE_HRS]               DECIMAL (9, 3)  NULL,
    [WED_HRS]               DECIMAL (9, 3)  NULL,
    [THU_HRS]               DECIMAL (9, 3)  NULL,
    [FRI_HRS]               DECIMAL (9, 3)  NULL,
    [SAT_HRS]               DECIMAL (9, 3)  NULL,
    [SUN_HRS]               DECIMAL (9, 3)  NULL,
    [ALERT_EMAIL]           SMALLINT        NULL,
    [FREELANCE]             SMALLINT        NULL,
    [PERS_HRS]              DECIMAL (9, 3)  NULL,
    [PERS_FROM_DATE]        SMALLDATETIME   NULL,
    [PERS_TO_DATE]          SMALLDATETIME   NULL,
    [DEF_FNC_CODE]          VARCHAR (6)     NULL,
    [PO_LIMIT]              DECIMAL (15, 2) NULL,
    [EMP_ACCOUNT_NBR]       VARCHAR (30)    NULL,
    [EMP_PHONE_WORK]        VARCHAR (13)    NULL,
    [EMP_PHONE_CELL]        VARCHAR (13)    NULL,
    [EMP_PHONE_ALT]         VARCHAR (13)    NULL,
    [EMP_PHONE_WORK_EXT]    VARCHAR (10)    NULL,
    [STD_ANNUAL_HRS]        DECIMAL (9, 3)  NULL,
    [VN_CODE_EXP]           VARCHAR (6)     NULL,
    [CC_NUMBER]             VARCHAR (30)    NULL,
    [CC_DESC]               VARCHAR (40)    NULL,
    [CC_GL_ACCOUNT]         VARCHAR (30)    NULL,
    [EXP_APPR_REQ]          SMALLINT        NULL,
    [MISSING_TIME]          SMALLINT        NULL,
    [WEEKLY_TIME]           SMALLINT        NULL,
    [SIGNATURE_PATH]        VARCHAR (256)   NULL,
    [STATUS]                SMALLINT        NULL,
    [DIRECT_HRS_PER]        DECIMAL (7, 4)  NULL,
    [DEF_TRF_ROLE]          VARCHAR (6)     NULL,
    [EMP_COMMENT]           TEXT            NULL,
    [EMPLOYEE_TITLE_ID]     INT             NULL,
    [PO_APPR_RULE_CODE]     VARCHAR (6)     NULL,
    [PO_GL_SELECTION]       SMALLINT        NULL,
    [PO_GL_LIMIT_BY_OFFICE] SMALLINT        NULL,
    [SENIORITY]             SMALLINT        NULL,
    [EMP_START_TIME]        SMALLDATETIME   NULL,
    [EMP_END_TIME]          SMALLDATETIME   NULL,
    [EMP_START_TIME_MON]    SMALLDATETIME   NULL,
    [EMP_END_TIME_MON]      SMALLDATETIME   NULL,
    [EMP_START_TIME_TUE]    SMALLDATETIME   NULL,
    [EMP_END_TIME_TUE]      SMALLDATETIME   NULL,
    [EMP_START_TIME_WED]    SMALLDATETIME   NULL,
    [EMP_END_TIME_WED]      SMALLDATETIME   NULL,
    [EMP_START_TIME_THU]    SMALLDATETIME   NULL,
    [EMP_END_TIME_THU]      SMALLDATETIME   NULL,
    [EMP_START_TIME_FRI]    SMALLDATETIME   NULL,
    [EMP_END_TIME_FRI]      SMALLDATETIME   NULL,
    [EMP_START_TIME_SAT]    SMALLDATETIME   NULL,
    [EMP_END_TIME_SAT]      SMALLDATETIME   NULL,
    [EMP_START_TIME_SUN]    SMALLDATETIME   NULL,
    [EMP_END_TIME_SUN]      SMALLDATETIME   NULL,
    [EMAIL_USERNAME]        VARCHAR (50)    NULL,
    [EMAIL_REPLY_TO]        VARCHAR (50)    NULL,
    [EMP_SIG]               IMAGE           NULL,
    [WV_TMPLT_HDR_ID]       INT             NULL,
    [ALT_COST_RATE]         DECIMAL (9, 2)  NULL,
    [ALT_DATE_FRM]          SMALLDATETIME   NULL,
    [ALT_DATE_TO]           SMALLDATETIME   NULL,
    [CREATED_BY]            VARCHAR (100)   NULL,
    [CREATED_DATE]          SMALLDATETIME   NULL,
    [LAST_MODIFIED_BY]      VARCHAR (100)   NULL,
    [LAST_MODIFIED_DATE]    SMALLDATETIME   NULL,
    [METHOD]                VARCHAR (1)     NULL,
    [EXP_RPT_APPROVER]      VARCHAR (6)     NULL,
    [VAC_TIME_RULE_ID]      INT             NULL,
    [SICK_TIME_RULE_ID]     INT             NULL,
    [PERS_TIME_RULE_ID]     INT             NULL,
    [GOOGLE_TOKEN]			VARCHAR(MAX)    NULL,
	[EMP_OMIT_MISSING]		SMALLINT		NULL
);

