CREATE TABLE [dbo].[ETF_OFFDTL] (
    [ETF_OFFDTL_ID] INT           IDENTITY (1, 1) NOT NULL,
    [ETF_ID]        INT           NOT NULL,
    [REV_NBR]       INT           NOT NULL,
    [USER_CREATED]  VARCHAR (100) NOT NULL,
    [USER_MODIFIED] VARCHAR (100) NULL,
    [CREATED_DATE]  SMALLDATETIME NOT NULL,
    [MODIFIED_DATE] SMALLDATETIME NULL,
    [OFFICE_CODE]   VARCHAR (4)   NOT NULL,
    [APPROVED]      BIT           NOT NULL,
    [FC_COMMENT]    VARCHAR (100) NOT NULL,
    [APPROVED_BY]   VARCHAR (100) NULL,
    [APPROVED_DATE] SMALLDATETIME NULL,
    [USER_ASSIGNED] VARCHAR (100) NOT NULL
);

