CREATE TABLE [dbo].[EXPORT_SYSTEMS] (
    [EXPORT_SYSTEM] VARCHAR (20) NOT NULL,
    [ADV_COL_NAME]  VARCHAR (20) NOT NULL,
    [COLUMN_LABEL]  VARCHAR (30) NULL,
    [MAX_CHAR]      INT          DEFAULT (0) NOT NULL,
    [MIN_CHAR]      INT          DEFAULT (0) NOT NULL
);

