CREATE TABLE [dbo].[FCUR] (
    [FCURCODE]    VARCHAR (3)   NOT NULL,
    [FCURNAME]    VARCHAR (30)  NULL,
    [FCURSYM]     VARCHAR (3)   NULL,
    [FCURDECIMAL] SMALLINT      NULL,
    [FCURPROFILE] INT           NULL,
    [FCURGLAP]    VARCHAR (30)  NULL,
    [FCURGLAR]    VARCHAR (30)  NULL,
    [FCURGLCASH]  VARCHAR (30)  NULL,
    [FCURGLCHK]   VARCHAR (30)  NULL,
    [FCUSER]      VARCHAR (100) NULL,
    [FCURENTDATE] SMALLDATETIME NULL,
    [FCURMODDATE] SMALLDATETIME NULL,
    [FCURMOD]     VARCHAR (1)   NULL,
    [FCURGLRGAIN] VARCHAR (30)  NULL,
    [FCURGLUGAIN] VARCHAR (30)  NULL,
    [FCURUSER]    VARCHAR (100) NULL
);

