CREATE TABLE [dbo].[GL_REPORT](
	[GL_REPORT_ID] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPTION] [varchar](100) NOT NULL,
	[USER_CREATED] [varchar](100) NOT NULL,
	[CREATED_DATE] [smalldatetime] NOT NULL,
	[USER_MODIFIED] [varchar](100) NULL,
	[MODIFIED_DATE] [smalldatetime] NULL,
 CONSTRAINT [PK_GL_REPORT] PRIMARY KEY CLUSTERED 
(
	[GL_REPORT_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO


