CREATE TABLE [dbo].[GLALPOSTINGLOG] (
    [GLALPXACT]     INT          NOT NULL,
    [GLALPPPERIOD]  VARCHAR (6)  NULL,
    [GLALPGLEXACT]  INT          NULL,
    [GLALPCOMMENT]  VARCHAR (60) NULL,
    [GLALPREVERSED] SMALLINT     NULL
);

