CREATE TABLE [dbo].[GLDXREF] (
    [GLDXGLDEPT]  VARCHAR (20)  NOT NULL,
    [GLDXDEPT]    VARCHAR (4)   NULL,
    [GLDXUSER]    VARCHAR (100) NULL,
    [GLDXENTDATE] SMALLDATETIME NULL,
    [GLDXMODDATE] SMALLDATETIME NULL
);

