CREATE TABLE [dbo].[GLSUMMARY] (
    [GLSCODE]   VARCHAR (30) NOT NULL,
    [GLSPP]     VARCHAR (6)  NOT NULL,
    [GLSDEBIT]  FLOAT        DEFAULT (0) NOT NULL,
    [GLSCREDIT] FLOAT        DEFAULT (0) NOT NULL,
    [GLSQTY]    FLOAT        DEFAULT (0) NOT NULL,
    [GLSBUDGET] FLOAT        DEFAULT (0) NOT NULL,
    [GLSBUD2]   FLOAT        DEFAULT (0) NOT NULL,
    [GLSBUD3]   FLOAT        DEFAULT (0) NOT NULL,
    [GLSMOD]    VARCHAR (1)  NULL
);

