CREATE TABLE [dbo].[IMP_DIVISION_STAGING](
	[IMPORT_ID] [int] IDENTITY(1,1) NOT NULL,
	[BATCH_NAME] [varchar](50) NULL,
	[IS_NEW] [bit] NOT NULL,
	[ON_HOLD] [bit] NOT NULL,
	[CL_CODE] [varchar](6) NOT NULL,
	[DIV_CODE] [varchar](6) NOT NULL,
	[DIV_NAME] [varchar](40) NULL,
	[DIV_ATTENTION] [varchar](40) NULL,
	[DIV_BADDRESS1] [varchar](40) NULL,
	[DIV_BADDRESS2] [varchar](40) NULL,
	[DIV_BCITY] [varchar](30) NULL,
	[DIV_BCOUNTY] [varchar](20) NULL,
	[DIV_BSTATE] [varchar](10) NULL,
	[DIV_BCOUNTRY] [varchar](20) NULL,
	[DIV_BZIP] [varchar](10) NULL,
	[DIV_SADDRESS1] [varchar](40) NULL,
	[DIV_SADDRESS2] [varchar](40) NULL,
	[DIV_SCITY] [varchar](30) NULL,
	[DIV_SCOUNTY] [varchar](20) NULL,
	[DIV_SSTATE] [varchar](10) NULL,
	[DIV_SCOUNTRY] [varchar](20) NULL,
	[DIV_SZIP] [varchar](10) NULL,
	[DIV_ALPHA_SORT] [varchar](20) NULL,
	[ACTIVE_FLAG] [smallint] NULL,
CONSTRAINT [PK_IMP_DIVISION_STAGING] PRIMARY KEY CLUSTERED 
(
	[IMPORT_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
