CREATE TABLE [dbo].[IMP_CLR_CHK_STAGING](
	[ROW_ID] [int] IDENTITY(1,1) NOT NULL,
	[BATCH_NAME] [varchar](50) NOT NULL,
	[FILE_NAME] [varchar](100) NULL,
	[BANK_CODE] [varchar](50) NULL,
	[CHECK_NUMBER] [varchar](25) NULL,
	[CHECK_AMOUNT] [decimal](10, 3) NULL,
	[VENDOR_NAME] [varchar](100) NULL,
 CONSTRAINT [PK_IMP_CLR_CHK_STAGING] PRIMARY KEY CLUSTERED 
(
	[ROW_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
