--GO
CREATE TABLE [dbo].[IMP_PRODUCT_STAGING](
	[IMPORT_ID] [int] IDENTITY(1,1) NOT NULL,
	[BATCH_NAME] [varchar](50) NULL,
	[IS_NEW] [bit] NOT NULL,
	[ON_HOLD] [bit] NOT NULL,
	[CL_CODE] [varchar](6) NOT NULL,
	[DIV_CODE] [varchar](6) NOT NULL,
	[PRD_CODE] [varchar](6) NOT NULL,
	[PRD_DESCRIPTION] [varchar](40) NULL,
	[PRD_ATTENTION] [varchar](40) NULL,
	[PRD_BILL_ADDRESS1] [varchar](40) NULL,
	[PRD_BILL_ADDRESS2] [varchar](40) NULL,
	[PRD_BILL_CITY] [varchar](30) NULL,
	[PRD_BILL_COUNTY] [varchar](20) NULL,
	[PRD_BILL_STATE] [varchar](10) NULL,
	[PRD_BILL_COUNTRY] [varchar](20) NULL,
	[PRD_BILL_ZIP] [varchar](10) NULL,
	[PRD_BILL_TELEPHONE] [varchar](13) NULL,
	[PRD_BILL_EXTENTION] [varchar](4) NULL,
	[PRD_BILL_FAX] [varchar](13) NULL,
	[PRD_BILL_FAX_EXT] [varchar](4) NULL,
	[PRD_STATE_ADDR1] [varchar](40) NULL,
	[PRD_STATE_ADDR2] [varchar](40) NULL,
	[PRD_STATE_CITY] [varchar](30) NULL,
	[PRD_STATE_COUNTY] [varchar](20) NULL,
	[PRD_STATE_STATE] [varchar](10) NULL,
	[PRD_STATE_COUNTRY] [varchar](20) NULL,
	[PRD_STATE_ZIP] [varchar](10) NULL,
	[PRD_STATE_TELEPHON] [varchar](13) NULL,
	[PRD_STATE_EXT] [varchar](4) NULL,
	[PRD_STATE_FAX] [varchar](13) NULL,
	[PRD_STATE_FAX_EXT] [varchar](4) NULL,
	[PRD_ALPHA_SORT] [varchar](20) NULL,
	[OFFICE_CODE] [varchar](4) NOT NULL,
	[PRD_CONSOL_FUNC] [smallint] NULL,
	[PRD_CONT_PCT] [decimal](7, 3) NULL,
	[PRD_PROD_MARKUP] [decimal](7, 3) NULL,
	[PRD_PROD_BILL_NET] [smallint] NULL,
	[PRD_PROD_VEN_DISC] [smallint] NULL,
	[PRD_PROD_ESTIMATE] [smallint] NULL,
	[PRD_PROD_TAX_CODE] [varchar](4) NULL,
	[PRD_RADIO_REBATE] [decimal](7, 3) NULL,
	[PRD_RADIO_BILL_NET] [smallint] NULL,
	[PRD_RADIO_VEN_DISC] [smallint] NULL,
	[PRD_RADIO_COM_ONLY] [smallint] NULL,
	[PRD_RADIO_TAX_CODE] [varchar](4) NULL,
	[PRD_RADIO_DAYS] [smallint] NULL,
	[PRD_RADIO_PRE_POST] [smallint] NULL,
	[PRD_RADIO_BF_AF] [smallint] NULL,
	[PRD_TV_REBATE] [decimal](7, 3) NULL,
	[PRD_TV_BILL_NET] [smallint] NULL,
	[PRD_TV_VEN_DISC] [smallint] NULL,
	[PRD_TV_COM_ONLY] [smallint] NULL,
	[PRD_TV_TAX_CODE] [varchar](4) NULL,
	[PRD_TV_DAYS] [smallint] NULL,
	[PRD_TV_PRE_POST] [smallint] NULL,
	[PRD_TV_BF_AF] [smallint] NULL,
	[PRD_MAG_REBATE] [decimal](7, 3) NULL,
	[PRD_MAG_BILL_NET] [smallint] NULL,
	[PRD_MAG_VEN_DISC] [smallint] NULL,
	[PRD_MAG_COM_ONLY] [smallint] NULL,
	[PRD_MAG_TAX_CODE] [varchar](4) NULL,
	[PRD_MAG_DAYS] [smallint] NULL,
	[PRD_MAG_PRE_POST] [smallint] NULL,
	[PRD_MAG_BF_AF] [smallint] NULL,
	[PRD_NEWS_COMM] [decimal](7, 3) NULL,
	[PRD_NEWS_BILL_NET] [smallint] NULL,
	[PRD_NEWS_VEN_DISC] [smallint] NULL,
	[PRD_NEWS_COM_ONLY] [smallint] NULL,
	[PRD_NEWS_TAX_CODE] [varchar](4) NULL,
	[PRD_NEWS_DAYS] [smallint] NULL,
	[PRD_NEWS_PRE_POST] [smallint] NULL,
	[PRD_NEWS_BF_AF] [smallint] NULL,
	[PRD_NEWS_REBATE] [decimal](7, 3) NULL,
	[PRD_OTDR_REBATE] [decimal](7, 3) NULL,
	[PRD_MISC_REBATE] [decimal](7, 3) NULL,
	[PRD_RADIO_COMM] [decimal](7, 3) NULL,
	[PRD_TV_COMM] [decimal](7, 3) NULL,
	[PRD_MAG_COMM] [decimal](7, 3) NULL,
	[PRD_OTDR_COMM] [decimal](7, 3) NULL,
	[PRD_MISC_COMM] [decimal](7, 3) NULL,
	[PRD_OTDR_BF_AF] [smallint] NULL,
	[PRD_OTDR_BILL_NET] [smallint] NULL,
	[PRD_OTDR_COM_ONLY] [smallint] NULL,
	[PRD_OTDR_DAYS] [smallint] NULL,
	[PRD_OTDR_PRE_POST] [smallint] NULL,
	[PRD_OTDR_TAX_CODE] [varchar](4) NULL,
	[PRD_OTDR_VEN_DISC] [smallint] NULL,
	[PRD_MISC_BF_AF] [smallint] NULL,
	[PRD_MISC_BILL_NET] [smallint] NULL,
	[PRD_MISC_COM_ONLY] [smallint] NULL,
	[PRD_MISC_DAYS] [smallint] NULL,
	[PRD_MISC_PRE_POST] [smallint] NULL,
	[PRD_MISC_TAX_CODE] [varchar](4) NULL,
	[PRD_MISC_VEN_DISC] [smallint] NULL,
	[EMAIL_GR_CODE] [varchar](50) NULL,
	[ACTIVE_FLAG] [smallint] NULL,
	[USER_DEFINED1] [varchar](50) NULL,
	[USER_DEFINED2] [varchar](50) NULL,
	[USER_DEFINED3] [varchar](50) NULL,
	[USER_DEFINED4] [varchar](50) NULL,
	[USE_TAX_FLAGS_R] [smallint] NULL,
	[TAXAPPLYLN_R] [smallint] NULL,
	[TAXAPPLYND_R] [smallint] NULL,
	[TAXAPPLYNC_R] [smallint] NULL,
	[TAXAPPLYAI_R] [smallint] NULL,
	[TAXAPPLYC_R] [smallint] NULL,
	[TAXAPPLYR_R] [smallint] NULL,
	[USE_TAX_FLAGS_T] [smallint] NULL,
	[TAXAPPLYLN_T] [smallint] NULL,
	[TAXAPPLYND_T] [smallint] NULL,
	[TAXAPPLYNC_T] [smallint] NULL,
	[TAXAPPLYAI_T] [smallint] NULL,
	[TAXAPPLYC_T] [smallint] NULL,
	[TAXAPPLYR_T] [smallint] NULL,
	[USE_TAX_FLAGS_M] [smallint] NULL,
	[TAXAPPLYLN_M] [smallint] NULL,
	[TAXAPPLYND_M] [smallint] NULL,
	[TAXAPPLYNC_M] [smallint] NULL,
	[TAXAPPLYAI_M] [smallint] NULL,
	[TAXAPPLYC_M] [smallint] NULL,
	[TAXAPPLYR_M] [smallint] NULL,
	[USE_TAX_FLAGS_N] [smallint] NULL,
	[TAXAPPLYLN_N] [smallint] NULL,
	[TAXAPPLYND_N] [smallint] NULL,
	[TAXAPPLYNC_N] [smallint] NULL,
	[TAXAPPLYAI_N] [smallint] NULL,
	[TAXAPPLYC_N] [smallint] NULL,
	[TAXAPPLYR_N] [smallint] NULL,
	[USE_TAX_FLAGS_O] [smallint] NULL,
	[TAXAPPLYLN_O] [smallint] NULL,
	[TAXAPPLYND_O] [smallint] NULL,
	[TAXAPPLYNC_O] [smallint] NULL,
	[TAXAPPLYAI_O] [smallint] NULL,
	[TAXAPPLYC_O] [smallint] NULL,
	[TAXAPPLYR_O] [smallint] NULL,
	[USE_TAX_FLAGS_I] [smallint] NULL,
	[TAXAPPLYLN_I] [smallint] NULL,
	[TAXAPPLYND_I] [smallint] NULL,
	[TAXAPPLYNC_I] [smallint] NULL,
	[TAXAPPLYAI_I] [smallint] NULL,
	[TAXAPPLYC_I] [smallint] NULL,
	[TAXAPPLYR_I] [smallint] NULL,
	[PROD_SETUP_COMPLETE] [smallint] NULL,
	[RADIO_SETUP_COMPLETE] [smallint] NULL,
	[TV_SETUP_COMPLETE] [smallint] NULL,
	[MAG_SETUP_COMPLETE] [smallint] NULL,
	[NEWS_SETUP_COMPLETE] [smallint] NULL,
	[OOH_SETUP_COMPLETE] [smallint] NULL,
	[INET_SETUP_COMPLETE] [smallint] NULL,
	[USE_EST_BILL_RATE] [smallint] NULL,
	[CURRENCY_CODE] [varchar](5) NULL,
CONSTRAINT [PK_IMP_PRODUCT_STAGING] PRIMARY KEY CLUSTERED 
(
	[IMPORT_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO