CREATE TABLE [dbo].[IMP_VENDOR_STAGING](
	[IMPORT_ID] [int] IDENTITY(1,1) NOT NULL,
	[IS_NEW] [bit] NOT NULL,
	[FIELD_NAME] [varchar](MAX) NULL,
	[VN_CODE] [varchar](6) NULL,
	[VN_NAME] [varchar](40) NULL,
	[VN_ADDRESS1] [varchar](40) NULL,
	[VN_ADDRESS2] [varchar](40) NULL,
	[VN_ADDRESS3] [varchar](30) NULL,
	[VN_CITY] [varchar](25) NULL,
	[VN_COUNTY] [varchar](20) NULL,
	[VN_STATE] [varchar](10) NULL,
	[VN_COUNTRY] [varchar](20) NULL,
	[VN_ZIP] [varchar](10) NULL,
	[VN_PHONE] [varchar](13) NULL,
	[VN_PHONE_EXT] [varchar](4) NULL,
	[VN_FAX_NUMBER] [varchar](13) NULL,
	[VN_FAX_EXTENTION] [varchar](4) NULL,
	[VN_PAY_TO_CODE] [varchar](6) NULL,
	[VN_PAY_TO_NAME] [varchar](40) NULL,
	[VN_PAY_TO_ADDRESS1] [varchar](40) NULL,
	[VN_PAY_TO_ADDRESS2] [varchar](40) NULL,
	[VN_PAY_TO_ADDRESS3] [varchar](30) NULL,
	[VN_PAY_TO_CITY] [varchar](25) NULL,
	[VN_PAY_TO_COUNTY] [varchar](20) NULL,
	[VN_PAY_TO_STATE] [varchar](10) NULL,
	[VN_PAY_TO_COUNTRY] [varchar](20) NULL,
	[VN_PAY_TO_ZIP] [varchar](10) NULL,
	[VN_PAY_TO_PHONE] [varchar](13) NULL,
	[VN_PAY_TO_EXT] [varchar](4) NULL,
	[VN_PAY_TO_FAX_NBR] [varchar](13) NULL,
	[VN_PAY_TO_FAX_EXT] [varchar](4) NULL,
	[VT_CODE] [varchar](3) NULL,
	[VN_TAX_ID] [varchar](20) NULL,
	[VN_1099_FLAG] [smallint] NULL,
	[VN_CATEGORY] [varchar](1) NULL,
	[GLACODE_AP] [varchar](30) NULL,
	[VN_NOTES] [text] NULL,
	[GLACODE_EXP] [varchar](30) NULL,
	[ASSOC_OFFICE] [smallint] NULL,
	[OFFICE_CODE] [varchar](4) NULL,
	[VN_1099_ADDRESS1] [varchar](40) NULL,
	[VN_1099_ADDRESS2] [varchar](40) NULL,
	[VN_1099_ADDRESS3] [varchar](30) NULL,
	[VN_1099_CITY] [varchar](25) NULL,
	[VN_1099_STATE] [varchar](10) NULL,
	[VN_1099_ZIP] [varchar](10) NULL,
	[VN_1099_COUNTY] [varchar](20) NULL,
	[VN_1099_COUNTRY] [varchar](20) NULL,
	[VN_USE_1099] [smallint] NULL,
	[VN_ACCT_NBR] [varchar](30) NULL,
	[DEF_FNC_CODE] [varchar](6) NULL,
	[EMP_VENDOR] [int] NULL,
	[ONE_CHECK_PER_INV] [smallint] NULL,
	[VN_EMAIL] [varchar](50) NULL,
	[PYMT_MGR_EMAIL] [varchar](50) NULL,
	[VN_ACTIVE_FLAG] [smallint] NULL,
	[ON_HOLD] [bit] NOT NULL,
 CONSTRAINT [PK_IMP_VENDOR_STAGING] PRIMARY KEY CLUSTERED 
(
	[IMPORT_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]