CREATE TABLE [dbo].[INVOICE_FORMAT] (
    [INV_FORMAT]   VARCHAR (12) NOT NULL,
    [INV_ACTIVE]   SMALLINT     NULL,
    [INV_TYPE]     VARCHAR (1)  NOT NULL,
    [INV_DESC]     VARCHAR (40) NOT NULL,
    [INV_CATEGORY] VARCHAR (4)  NULL,
    [INV_NUMBER]   VARCHAR (4)  NULL
);

