CREATE TABLE [dbo].[INVOICE_RPT_DATES_TEMP] (
    [RPT_DATES_ID]       INT           IDENTITY (1, 1) NOT NULL,
    [USER_ID]            VARCHAR (100) NOT NULL,
    [INVOICE_TYPE]       VARCHAR (1)   NOT NULL,
    [CL_CODE]            VARCHAR (6)   NOT NULL,
    [CDP_CONTACT_ID]     INT           NULL,
    [CONTACT_CODE]       VARCHAR (6)   NULL,
    [CONTACT_EMAIL]      VARCHAR (50)  NULL,
    [PRINT_FLAG]         SMALLINT      NULL,
    [EMAIL_FLAG]         SMALLINT      NULL,
    [INVOICE_PRINT_DATE] SMALLDATETIME NULL,
    [INVOICE_EMAIL_DATE] SMALLDATETIME NULL
);

