CREATE TABLE [dbo].[JF_HDR](
	[JF_ID] [int] IDENTITY(1,1) NOT NULL,
	[JF_DESCRIPTION] [varchar](100) NOT NULL,
	[JF_COMMENT] [varchar](100) NULL,
	[PPPERIOD_START] [varchar](6) NOT NULL,
	[PPPERIOD_END] [varchar](6) NOT NULL,
	[BUDGET] [decimal](15,2) NULL,
	[USER_ASSIGNED] [varchar](100) NOT NULL,
	[USER_CREATED] [varchar](100) NOT NULL,
	[CREATED_DATE] [smalldatetime] NOT NULL,
	[USER_MODIFIED] [varchar](100) NULL,
	[MODIFIED_DATE] [smalldatetime] NULL
 CONSTRAINT [PK_JF_HDR] PRIMARY KEY CLUSTERED 
(
	[JF_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[JF_HDR]  WITH CHECK ADD CONSTRAINT [FK_JFHDR_POSTPERIOD_START] FOREIGN KEY([PPPERIOD_START])
REFERENCES [dbo].[POSTPERIOD] ([PPPERIOD])
GO

ALTER TABLE [dbo].[JF_HDR] CHECK CONSTRAINT [FK_JFHDR_POSTPERIOD_START]
GO

ALTER TABLE [dbo].[JF_HDR]  WITH CHECK ADD CONSTRAINT [FK_JFHDR_POSTPERIOD_END] FOREIGN KEY([PPPERIOD_END])
REFERENCES [dbo].[POSTPERIOD] ([PPPERIOD])
GO

ALTER TABLE [dbo].[JF_HDR] CHECK CONSTRAINT [FK_JFHDR_POSTPERIOD_END]
GO
