CREATE TABLE [dbo].[JF_JOB_DTL](
	[JF_JOB_DTL_ID] [int] IDENTITY(1,1) NOT NULL,
	[JF_JOB_ID] [int] NOT NULL,
	[JF_REV_ID] [int] NOT NULL,
	[JF_ID] [int] NOT NULL,
	[PPPERIOD] [varchar](6) NOT NULL,
	[BILLING_AMT] [decimal](15,2) NULL,
	[REVENUE_AMT] [decimal](15,2) NULL,
	[USER_CREATED] [varchar](100) NOT NULL,
	[CREATED_DATE] [smalldatetime] NOT NULL,
	[USER_MODIFIED] [varchar](100) NULL,
	[MODIFIED_DATE] [smalldatetime] NULL
 CONSTRAINT [PK_JF_JOB_DTL] PRIMARY KEY CLUSTERED 
(
	[JF_JOB_DTL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[JF_JOB_DTL]  WITH CHECK ADD CONSTRAINT [FK_JFJOBDTL_JFHDR] FOREIGN KEY([JF_ID])
REFERENCES [dbo].[JF_HDR] ([JF_ID])
GO

ALTER TABLE [dbo].[JF_JOB_DTL] CHECK CONSTRAINT [FK_JFJOBDTL_JFHDR]
GO

ALTER TABLE [dbo].[JF_JOB_DTL]  WITH CHECK ADD CONSTRAINT [FK_JFJOBDTL_JFREV] FOREIGN KEY([JF_REV_ID])
REFERENCES [dbo].[JF_REV] ([JF_REV_ID])
GO

ALTER TABLE [dbo].[JF_JOB_DTL] CHECK CONSTRAINT [FK_JFJOBDTL_JFREV]
GO

ALTER TABLE [dbo].[JF_JOB_DTL]  WITH CHECK ADD CONSTRAINT [FK_JFJOBDTL_JFJOB] FOREIGN KEY([JF_JOB_ID])
REFERENCES [dbo].[JF_JOB] ([JF_JOB_ID])
GO

ALTER TABLE [dbo].[JF_JOB_DTL] CHECK CONSTRAINT [FK_JFJOBDTL_JFJOB]
GO

ALTER TABLE [dbo].[JF_JOB_DTL]  WITH CHECK ADD CONSTRAINT [FK_JFJOBDTL_POSTPERIOD] FOREIGN KEY([PPPERIOD])
REFERENCES [dbo].[POSTPERIOD] ([PPPERIOD])
GO

ALTER TABLE [dbo].[JF_JOB_DTL] CHECK CONSTRAINT [FK_JFJOBDTL_POSTPERIOD]
GO