CREATE TABLE [dbo].[JF_JOB](
	[JF_JOB_ID] [int] IDENTITY(1,1) NOT NULL,
	[JF_REV_ID] [int] NOT NULL,
	[JF_ID] [int] NOT NULL,
	[JOB_NUMBER] [int] NOT NULL,
	[JOB_COMPONENT_NBR] [smallint] NOT NULL,
	[JF_JOB_COMMENT] [varchar](100) NULL,
	[INCOME_AMT] [decimal](15,2) NULL,
	[COLOR] [int] NULL,
	[USER_CREATED] [varchar](100) NOT NULL,
	[CREATED_DATE] [smalldatetime] NOT NULL,
	[USER_MODIFIED] [varchar](100) NULL,
	[MODIFIED_DATE] [smalldatetime] NULL
 CONSTRAINT [PK_JF_JOB] PRIMARY KEY CLUSTERED 
(
	[JF_JOB_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[JF_JOB]  WITH CHECK ADD CONSTRAINT [FK_JFJOB_JFHDR] FOREIGN KEY([JF_ID])
REFERENCES [dbo].[JF_HDR] ([JF_ID])
GO

ALTER TABLE [dbo].[JF_JOB] CHECK CONSTRAINT [FK_JFJOB_JFHDR]
GO

ALTER TABLE [dbo].[JF_JOB]  WITH CHECK ADD CONSTRAINT [FK_JFJOB_JFREV] FOREIGN KEY([JF_REV_ID])
REFERENCES [dbo].[JF_REV] ([JF_REV_ID])
GO

ALTER TABLE [dbo].[JF_JOB] CHECK CONSTRAINT [FK_JFJOB_JFREV]
GO

ALTER TABLE [dbo].[JF_JOB]  WITH CHECK ADD CONSTRAINT [FK_JFJOB_JOBCOMPONENT] FOREIGN KEY([JOB_NUMBER], [JOB_COMPONENT_NBR])
REFERENCES [dbo].[JOB_COMPONENT] ([JOB_NUMBER], [JOB_COMPONENT_NBR])
GO

ALTER TABLE [dbo].[JF_JOB] CHECK CONSTRAINT [FK_JFJOB_JOBCOMPONENT]
GO