CREATE TABLE [dbo].[JF_REV](
	[JF_REV_ID] [int] IDENTITY(1,1) NOT NULL,
	[JF_ID] [int] NOT NULL,
	[REV_NBR] [int] NOT NULL,
	[JF_REV_COMMENT] [varchar](100) NULL,
	[USER_CREATED] [varchar](100) NOT NULL,
	[CREATED_DATE] [smalldatetime] NOT NULL,
	[USER_MODIFIED] [varchar](100) NULL,
	[MODIFIED_DATE] [smalldatetime] NULL,
	[APPROVED] [bit] NOT NULL,
	[APPROVED_BY] [varchar](100) NULL,
	[APPROVED_DATE] [smalldatetime] NULL
 CONSTRAINT [PK_JF_REV] PRIMARY KEY CLUSTERED 
(
	[JF_REV_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[JF_REV]  WITH CHECK ADD CONSTRAINT [FK_JFREV_JFHDR] FOREIGN KEY([JF_ID])
REFERENCES [dbo].[JF_HDR] ([JF_ID])
GO

ALTER TABLE [dbo].[JF_REV] CHECK CONSTRAINT [FK_JFREV_JFHDR]
GO