IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[JOB_TRAFFIC_VER_DET_EMPS]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
	DROP TABLE [dbo].[JOB_TRAFFIC_VER_DET_EMPS]
END

/****** Object:  Table [dbo].[JOB_TRAFFIC_VER_DET_EMPS]    Script Date: 8/9/2013 8:59:44 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[JOB_TRAFFIC_VER_DET_EMPS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[EMP_CODE] [varchar](6) NOT NULL,
	[HOURS_ALLOWED] [decimal](8, 2) NULL,
	[TEMP_COMP_DATE] [smalldatetime] NULL,
	[COMPLETED_COMMENTS] [text] NULL,
	[PERCENT_COMPLETE] [decimal](7, 3) NULL,
	[DETAIL_ID] [int] NOT NULL,
 CONSTRAINT [PK_JOB_TRAFFIC_VER_DET_EMPS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[JOB_TRAFFIC_VER_DET_EMPS] ADD  CONSTRAINT [DF_JOB_TRAFFIC_DET_VER_EMPS_HOURS_ALLOWED]  DEFAULT ((0)) FOR [HOURS_ALLOWED]
GO

ALTER TABLE [dbo].[JOB_TRAFFIC_VER_DET_EMPS]  WITH CHECK ADD  CONSTRAINT [FK_JOB_TRAFFIC_VER_DET_EMPS_JOB_TRAFFIC_VER_DET1] FOREIGN KEY([DETAIL_ID])
REFERENCES [dbo].[JOB_TRAFFIC_VER_DET] ([ID])
GO

ALTER TABLE [dbo].[JOB_TRAFFIC_VER_DET_EMPS] CHECK CONSTRAINT [FK_JOB_TRAFFIC_VER_DET_EMPS_JOB_TRAFFIC_VER_DET1]
GO

ALTER TABLE [dbo].[JOB_TRAFFIC_VER_DET_EMPS]  WITH CHECK ADD  CONSTRAINT [FK_JOB_TRAFFIC_VER_EMP] FOREIGN KEY([EMP_CODE])
REFERENCES [dbo].[EMPLOYEE_CLOAK] ([EMP_CODE])
GO

ALTER TABLE [dbo].[JOB_TRAFFIC_VER_DET_EMPS] CHECK CONSTRAINT [FK_JOB_TRAFFIC_VER_EMP]
GO