CREATE TABLE [dbo].[JOB_VER_TMPLT_DTL] (
    [JV_TMPLT_DTL_ID]    INT           IDENTITY (1, 1) NOT NULL,
    [JV_TMPLT_CODE]      VARCHAR (6)   NOT NULL,
    [JV_DTYPE_ID]        INT           NOT NULL,
    [JV_TMPLT_LABEL]     VARCHAR (25)  NOT NULL,
    [JV_TMPLT_ORDER]     SMALLINT      NOT NULL,
    [JV_TMPLT_REQ]       SMALLINT      NOT NULL,
    [INACTIVE_FLAG]      SMALLINT      NULL,
    [JV_TMPLT_DTL_INSTR] VARCHAR (255) NULL
);

