CREATE TABLE [dbo].[JOB_PUB_VENDOR] (
    [JOB_NUMBER]         INT           NOT NULL,
    [JOB_COMPONENT_NBR]  SMALLINT      NOT NULL,
    [SPEC_ID]            SMALLINT      NOT NULL,
    [VN_CODE]            VARCHAR (6)   NOT NULL,
    [JOB_PUB_BLEED_SIZE] VARCHAR (40)  NULL,
    [JOB_PUB_CLOSE_DATE] SMALLDATETIME NULL,
    [JOB_PUB_COLOR]      VARCHAR (20)  NULL,
    [JOB_PUB_EXT_DATE]   SMALLDATETIME NULL,
    [JOB_PUB_LIVE_AREA]  VARCHAR (40)  NULL,
    [JOB_PUB_RUN_DATE]   SMALLDATETIME NULL,
    [JOB_PUB_SCREEN]     VARCHAR (20)  NULL,
    [JOB_PUB_TRIM_SIZE]  VARCHAR (40)  NULL,
    [JOB_PUB_DENSITY]    VARCHAR (25)  NULL,
    [JOB_PUB_FILM]       VARCHAR (25)  NULL,
    [JOB_PUB_SHIP_COMM]  TEXT          NULL,
    [JOB_PUB_SPCL_INST]  TEXT          NULL,
    [STATUS_CODE]        VARCHAR (20)  NULL,
    [REGION_CODE]        VARCHAR (20)  NULL,
    [AD_SIZE]            VARCHAR (6)   NULL
);

