IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[JOB_TRAFFIC_VER_DET_CNTS]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
	DROP TABLE [dbo].[JOB_TRAFFIC_VER_DET_CNTS]
END

/****** Object:  Table [dbo].[JOB_TRAFFIC_VER_DET_CNTS]    Script Date: 8/9/2013 8:59:07 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[JOB_TRAFFIC_VER_DET_CNTS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CDP_CONTACT_ID] [int] NOT NULL,
	[DETAIL_ID] [int] NOT NULL,
 CONSTRAINT [PK_JOB_TRAFFIC_VER_DET_CONTACTS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[JOB_TRAFFIC_VER_DET_CNTS]  WITH CHECK ADD  CONSTRAINT [FK_JOB_TRAFFIC_DET_VER_CONTACT] FOREIGN KEY([CDP_CONTACT_ID])
REFERENCES [dbo].[CDP_CONTACT_HDR] ([CDP_CONTACT_ID])
GO

ALTER TABLE [dbo].[JOB_TRAFFIC_VER_DET_CNTS] CHECK CONSTRAINT [FK_JOB_TRAFFIC_DET_VER_CONTACT]
GO

ALTER TABLE [dbo].[JOB_TRAFFIC_VER_DET_CNTS]  WITH CHECK ADD  CONSTRAINT [FK_JOB_TRAFFIC_VER_DET_CNTS_JOB_TRAFFIC_VER_DET] FOREIGN KEY([DETAIL_ID])
REFERENCES [dbo].[JOB_TRAFFIC_VER_DET] ([ID])
GO

ALTER TABLE [dbo].[JOB_TRAFFIC_VER_DET_CNTS] CHECK CONSTRAINT [FK_JOB_TRAFFIC_VER_DET_CNTS_JOB_TRAFFIC_VER_DET]
GO