CREATE TABLE [dbo].[JOB_DET_ANAL] (
    [CL_CODE]            VARCHAR (6)     NULL,
    [CL_NAME]            VARCHAR (40)    NULL,
    [DIV_CODE]           VARCHAR (6)     NULL,
    [DIV_NAME]           VARCHAR (40)    NULL,
    [PRD_CODE]           VARCHAR (6)     NULL,
    [PRD_DESCRIPTION]    VARCHAR (40)    NULL,
    [OFFICE_CODE]        VARCHAR (4)     NULL,
    [OFFICE_NAME]        VARCHAR (30)    NULL,
    [JOB_AE_CODE]        VARCHAR (6)     NULL,
    [JOB_AE_NAME]        VARCHAR (70)    NULL,
    [JOB_NUMBER]         INT             NULL,
    [JOB_DESC]           VARCHAR (60)    NULL,
    [JOB_CLI_REF]        VARCHAR (30)    NULL,
    [JOB_COMPONENT_NBR]  SMALLINT        NULL,
    [JOB_BILL_HOLD]      VARCHAR (40)    NULL,
    [JOB_MARKUP_PCT]     DECIMAL (7, 3)  NULL,
    [JOB_PROCESS_CONTRL] VARCHAR (40)    NULL,
    [JOB_COMP_DESC]      VARCHAR (60)    NULL,
    [JOB_BILL_STATUS]    VARCHAR (40)    NULL,
    [ESTIMATE_NUMBER]    INT             NULL,
    [EST_COMPONENT_NBR]  SMALLINT        NULL,
    [AB_FLAG]            SMALLINT        NULL,
    [FNC_CODE]           VARCHAR (6)     NULL,
    [FNC_DESCRIPTION]    VARCHAR (40)    NULL,
    [FNC_TYPE]           VARCHAR (1)     NULL,
    [EST_REV_QUANTITY]   DECIMAL (15, 2) NULL,
    [EST_REV_EXT_AMT]    DECIMAL (15, 2) NULL,
    [EST_MARKUP_AMT]     DECIMAL (14, 2) NULL,
    [EST_NONRESALE_TAX]  DECIMAL (14, 2) NULL,
    [EST_STATE_RESALE]   DECIMAL (14, 2) NULL,
    [EST_COUNTY_RESALE]  DECIMAL (14, 2) NULL,
    [EST_CITY_RESALE]    DECIMAL (14, 2) NULL,
    [EST_CONTINGENCY]    DECIMAL (14, 2) NULL,
    [EST_MU_CONT]        DECIMAL (14, 2) NULL,
    [EST_STATE_CONT]     DECIMAL (14, 2) NULL,
    [EST_COUNTY_CONT]    DECIMAL (14, 2) NULL,
    [EST_CITY_CONT]      DECIMAL (14, 2) NULL,
    [EST_NR_CONT]        DECIMAL (14, 2) NULL,
    [EST_LINETOT_CONT]   DECIMAL (14, 2) NULL,
    [EST_LINE_TOTAL]     DECIMAL (14, 2) NULL,
    [ADV_AB_ID]          INT             NULL,
    [ADV_AB_FLAG]        SMALLINT        NULL,
    [ADV_AR_INV_NBR]     INT             NULL,
    [ADV_BILL_NET_AMT]   DECIMAL (14, 2) NULL,
    [ADV_LINE_TOTAL]     DECIMAL (14, 2) NULL,
    [ADV_BILLED_AMT]     DECIMAL (14, 2) NULL,
    [ADV_AR_TYPE]        VARCHAR (3)     NULL,
    [ADV_GL_SALES]       VARCHAR (30)    NULL,
    [ADV_GLEXACT]        INT             NULL,
    [ADV_POST_PERIOD]    VARCHAR (8)     NULL,
    [ADV_NONRESALE]      DECIMAL (14, 2) NULL,
    [ADV_STATE_RESALE]   DECIMAL (14, 2) NULL,
    [ADV_COUNTY_RESALE]  DECIMAL (14, 2) NULL,
    [ADV_CITY_RESALE]    DECIMAL (14, 2) NULL,
    [EMP_HOURS]          DECIMAL (7, 2)  NULL,
    [EMP_TOTAL_BILL]     DECIMAL (14, 2) NULL,
    [AP_PROD_QUANTITY]   DECIMAL (14, 2) NULL,
    [AP_NONRESALE_TAX]   DECIMAL (14, 2) NULL,
    [AP_INV_VCHR]        VARCHAR (20)    NULL,
    [AP_PO_NUMBER]       INT             NULL,
    [AP_PO_LINE_NUMBER]  SMALLINT        NULL,
    [PO_PO_NUMBER]       INT             NULL,
    [PO_LINE_NUMBER]     INT             NULL,
    [PO_DUE_DATE]        SMALLDATETIME   NULL,
    [PO_EXT_AMOUNT]      DECIMAL (14, 2) NULL,
    [PO_COMPLETE]        SMALLINT        NULL,
    [USER_ID]            VARCHAR (100)   NOT NULL,
    [VN_CODE]            VARCHAR (6)     NULL,
    [THE_DATE]           SMALLDATETIME   NULL,
    [ITEM_DESC]          VARCHAR (70)    NULL,
    [NONBILL_FLAG]       SMALLINT        NULL,
    [AB_ID]              INT             NULL,
    [POST_PERIOD]        VARCHAR (8)     NULL,
    [AR_INV_NBR]         INT             NULL,
    [AR_TYPE]            VARCHAR (3)     NULL,
    [GL_SALES]           VARCHAR (30)    NULL,
    [GL_EXACT]           INT             NULL,
    [NET_COST]           DECIMAL (14, 2) NULL,
    [MARKUP]             DECIMAL (14, 2) NULL,
    [STATE_RESALE]       DECIMAL (14, 2) NULL,
    [COUNTY_RESALE]      DECIMAL (14, 2) NULL,
    [CITY_RESALE]        DECIMAL (14, 2) NULL,
    [REC_ORDER]          INT             NULL,
    [RPT_TITLE]          VARCHAR (200)   NULL,
    [RPT_CUR_YYYY_MM]    VARCHAR (6)     NULL,
    [SORT_BY_TEXT]       VARCHAR (200)   NULL,
    [LINE_TOTAL]         DECIMAL (15, 2) NULL,
    [BILL_HOLD_FLAG]     SMALLINT        NULL,
    [ITEM_CODE]          VARCHAR (20)    NULL,
    [UNBILLED_AMT]       DECIMAL (15, 2) NULL,
    [BILLED_AMT]         DECIMAL (15, 2) NULL,
    [BILL_HRS]           DECIMAL (10, 2) NULL,
    [NONBILL_HRS]        DECIMAL (10, 2) NULL,
    [NONBILL_AMT]        DECIMAL (15, 2) NULL,
    [ADV_HIST]           SMALLINT        NULL,
    [PRT_DTL]            SMALLINT        NULL,
    [ADV_HIST_ARINVNBR]  VARCHAR (10)    NULL,
    [ADV_HIST_AR_TYPE]   VARCHAR (3)     NULL,
    [PRT_ADV_HIST_HEAD]  SMALLINT        NULL,
    [COMPONENT_CTRL_BRK] VARCHAR (6)     NULL,
    [ROW_NUM]            INT             NOT NULL,
    [JOB_PO_NBR]         VARCHAR (40)    NULL
);

