CREATE TABLE [dbo].[JOB_VER_DTYPE] (
    [JV_DTYPE_ID]     INT          IDENTITY (1, 1) NOT NULL,
    [JV_DTYPE_DESC]   VARCHAR (50) NULL,
    [ADVAN_DTYPE_ID]  SMALLINT     NOT NULL,
    [JV_DTYPE_PREC]   SMALLINT     NULL,
    [JV_DTYPE_SCALE]  SMALLINT     NULL,
    [JV_DTYPE_DW_COL] VARCHAR (50) NULL,
    [VALUE_LIST_FLAG] SMALLINT     NULL
);

