CREATE TABLE [dbo].[JOB_COMPONENT] (
    [JOB_NUMBER]         INT             NOT NULL,
    [JOB_COMPONENT_NBR]  SMALLINT        NOT NULL,
    [JOB_BILL_HOLD]      SMALLINT        NULL,
    [EMP_CODE]           VARCHAR (6)     NOT NULL,
    [JOB_COMP_DATE]      SMALLDATETIME   NULL,
    [JOB_FIRST_USE_DATE] SMALLDATETIME   NULL,
    [START_DATE]         SMALLDATETIME   NULL,
    [JOB_AD_SIZE]        VARCHAR (60)    NULL,
    [JOB_SPEC_TYPE]      VARCHAR (1)     NOT NULL,
    [DP_TM_CODE]         VARCHAR (4)     NULL,
    [JOB_MARKUP_PCT]     DECIMAL (7, 3)  NULL,
    [CREATIVE_INSTR]     TEXT            NULL,
    [JOB_LAYOUT_THUMB]   SMALLINT        NULL,
    [JOB_LAYOUT_ROUGH]   SMALLINT        NULL,
    [JOB_LAYOUT_COMP]    SMALLINT        NULL,
    [JOB_LAYOUT_NONE]    SMALLINT        NULL,
    [JOB_LAYOUT_SPECIAL] SMALLINT        NULL,
    [JOB_LAYOUT_SPC_EXP] VARCHAR (60)    NULL,
    [JOB_PROCESS_CONTRL] SMALLINT        NULL,
    [JOB_COMP_DESC]      VARCHAR (60)    NOT NULL,
    [JOB_COMP_COMMENTS]  TEXT            NULL,
    [JOB_COMP_BUDGET_AM] DECIMAL (11, 2) NULL,
    [ESTIMATE_NUMBER]    INT             NULL,
    [EST_COMPONENT_NBR]  SMALLINT        NULL,
    [BILLING_USER]       VARCHAR (100)   NULL,
    [AB_FLAG]            SMALLINT        NULL,
    [JOB_DEL_INSTRUCT]   TEXT            NULL,
    [JT_CODE]            VARCHAR (10)    NULL,
    [TAX_FLAG]           SMALLINT        NULL,
    [TAX_CODE]           VARCHAR (4)     NULL,
    [NOBILL_FLAG]        SMALLINT        NULL,
    [EMAIL_GR_CODE]      VARCHAR (50)    NULL,
    [AD_NBR]             VARCHAR (30)    NULL,
    [ACCT_NBR]           VARCHAR (30)    NULL,
    [PRD_AB_INCOME]      SMALLINT        NULL,
    [MARKET_CODE]        VARCHAR (10)    NULL,
    [SERVICE_FEE_FLAG]   SMALLINT        NULL,
    [ARCHIVE_FLAG]       SMALLINT        NULL,
    [ROWID]              INT             IDENTITY (1, 1) NOT NULL,
    [ADJUST_USER]        VARCHAR (100)   NULL,
    [TRF_SCHEDULE_BY]    SMALLINT        NULL,
    [TRF_SCHEDULE_REQ]   SMALLINT        NULL,
    [JOB_CL_PO_NBR]      VARCHAR (40)    NULL,
    [UDV1_CODE]          VARCHAR (10)    NULL,
    [UDV2_CODE]          VARCHAR (10)    NULL,
    [UDV3_CODE]          VARCHAR (10)    NULL,
    [UDV4_CODE]          VARCHAR (10)    NULL,
    [UDV5_CODE]          VARCHAR (10)    NULL,
    [JOB_TMPLT_CODE]     VARCHAR (6)     NULL,
    [FEE_TIME]           SMALLINT        NULL,
    [FISCAL_PERIOD_CODE] VARCHAR (6)     NULL,
    [JOB_QTY]            INT             NULL,
    [BLACKPLT_VER_CODE]  VARCHAR (6)     NULL,
    [BLACKPLT_VER_DESC]  VARCHAR (60)    NULL,
    [BLACKPLT_VER2_CODE] VARCHAR (6)     NULL,
    [BLACKPLT_VER2_DESC] VARCHAR (60)    NULL,
    [CDP_CONTACT_ID]     INT             NULL,
    [PRD_CONT_CODE]      AS              ([dbo].[udf_get_cont_code]([CDP_CONTACT_ID])),
    [BA_BATCH_ID]        INT             NULL,
    [SELECTED_BA_ID]     INT             NULL,
    [BCC_ID]             INT             NULL,
    [ALRT_NOTIFY_HDR_ID] INT             NULL
);

