CREATE TABLE [dbo].[JOB_TRAFFIC_DET] (
    [JOB_NUMBER]         INT            NOT NULL,
    [JOB_COMPONENT_NBR]  SMALLINT       NOT NULL,
    [SEQ_NBR]            SMALLINT       NOT NULL,
    [FNC_CODE]           VARCHAR (10)   NULL,
    [FNC_EST]            VARCHAR (6)    NULL,
    [TASK_DESCRIPTION]   VARCHAR (40)   NULL,
    [TASK_START_DATE]    SMALLDATETIME  NULL,
    [JOB_DUE_DATE]       SMALLDATETIME  NULL,
    [JOB_REVISED_DATE]   SMALLDATETIME  NULL,
    [DUE_DATE_LOCK]      SMALLINT       NULL,
    [JOB_COMPLETED_DATE] SMALLDATETIME  NULL,
    [JOB_ORDER]          SMALLINT       NULL,
    [JOB_DAYS]           SMALLINT       NULL,
    [PARENT_TASK]        VARCHAR (10)   NULL,
    [FNC_COMMENTS]       TEXT           NULL,
    [DUE_DATE_COMMENTS]  TEXT           NULL,
    [REV_DATE_COMMENTS]  TEXT           NULL,
    [JOB_HRS]            DECIMAL (8, 2) NULL,
    [DUE_TIME]           VARCHAR (10)   NULL,
    [REVISED_DUE_TIME]   VARCHAR (10)   NULL,
    [TASK_STATUS]        VARCHAR (1)    NULL,
    [MILESTONE]          SMALLINT       NULL,
    [TRAFFIC_PHASE_ID]   INT            NULL,
    [ROWID]              INT            IDENTITY (1, 1) NOT NULL,
    [TEMP_SEQ]           SMALLINT       NULL,
    [TRF_ROLE]           VARCHAR (6)    NULL,
    [HOURS_ASSIGNED]     AS             ([dbo].[udf_get_task_hours]([JOB_NUMBER], [JOB_COMPONENT_NBR], [SEQ_NBR])),
    [EMP_CODE]           AS             ([dbo].[udf_get_task_employee]([JOB_NUMBER], [JOB_COMPONENT_NBR], [SEQ_NBR])),
    [TEMP_COMP_DATE]     AS             ([dbo].[udf_get_temp_comp_date]([JOB_NUMBER], [JOB_COMPONENT_NBR], [SEQ_NBR])),
	[PARENT_TASK_SEQ]	 SMALLINT		NULL,
	[GRID_ORDER]		 SMALLINT		NULL
);

