CREATE TABLE [dbo].[JOB_LOG] (
    [JOB_NUMBER]       INT           NOT NULL,
    [OFFICE_CODE]      VARCHAR (4)   NULL,
    [CL_CODE]          VARCHAR (6)   NOT NULL,
    [DIV_CODE]         VARCHAR (6)   NOT NULL,
    [PRD_CODE]         VARCHAR (6)   NOT NULL,
    [CMP_CODE]         VARCHAR (6)   NULL,
    [SC_CODE]          VARCHAR (6)   NULL,
    [USER_ID]          VARCHAR (100) NULL,
    [CREATE_DATE]      SMALLDATETIME DEFAULT (getdate()) NULL,
    [JOB_DESC]         VARCHAR (60)  NULL,
    [JOB_DATE_OPENED]  SMALLDATETIME NULL,
    [JOB_RUSH_CHARGES] SMALLINT      NULL,
    [JOB_ESTIMATE_REQ] SMALLINT      NULL,
    [JOB_COMMENTS]     TEXT          NULL,
    [JOB_CLI_REF]      VARCHAR (30)  NULL,
    [BILL_COOP_CODE]   VARCHAR (6)   NULL,
    [FORMAT_SC_CODE]   VARCHAR (6)   NULL,
    [FORMAT_CODE]      VARCHAR (8)   NULL,
    [COMPLEX_CODE]     VARCHAR (8)   NULL,
    [PROMO_CODE]       VARCHAR (8)   NULL,
    [CMP_IDENTIFIER]   INT           NULL,
    [CMP_LINE_NBR]     SMALLINT      NULL,
    [ROWID]            INT           IDENTITY (1, 1) NOT NULL,
    [JOB_BILL_COMMENT] VARCHAR (254) NULL,
    [FEE_JOB]          SMALLINT      NULL,
    [UDV1_CODE]        VARCHAR (10)  NULL,
    [UDV2_CODE]        VARCHAR (10)  NULL,
    [UDV3_CODE]        VARCHAR (10)  NULL,
    [UDV4_CODE]        VARCHAR (10)  NULL,
    [UDV5_CODE]        VARCHAR (10)  NULL,
    [COMP_OPEN]        AS            ([dbo].[udf_get_comp_open]([JOB_NUMBER])),
    [LOCKED_USER]      VARCHAR (100) NULL,
    [NP_COOP_SPLIT]    SMALLINT      NULL
);

