CREATE TABLE [dbo].[JOB_TMPLT_HDR] (
    [JOB_TMPLT_CODE]  VARCHAR (6)  NOT NULL,
    [JOB_TMPLT_DESC]  VARCHAR (50) NULL,
    [DEF_SALES_CLASS] VARCHAR (6)  NULL,
    [CRTV_BRF_CODE]   VARCHAR (6)  NULL,
    [SPEC_TYPE_CODE]  VARCHAR (6)  NULL,
    [TRF_PRESET_CODE] VARCHAR (6)  NULL,
    [INACTIVE_FLAG]   SMALLINT     NULL
);

