IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[JOB_TRAFFIC_VER_LOG]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
	DROP TABLE [dbo].[JOB_TRAFFIC_VER_LOG]
END

/****** Object:  Table [dbo].[JOB_TRAFFIC_VER_LOG]    Script Date: 8/9/2013 9:00:58 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[JOB_TRAFFIC_VER_LOG](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[JOB_NUMBER] [int] NOT NULL,
	[JOB_COMPONENT_NBR] [smallint] NOT NULL,
	[VERSION_ID] [int] NOT NULL,
	[LAST_APPLIED_BY_USER_CODE] [varchar](100) NOT NULL,
	[LAST_APPLIED_DATE] [smalldatetime] NOT NULL,
	[LAST_APPLIED_COMMENT] [varchar](max) NOT NULL,
 CONSTRAINT [PK_JOB_TRAFFIC_VER_LOG] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[JOB_TRAFFIC_VER_LOG]  WITH CHECK ADD  CONSTRAINT [FK_JOB_TRAFFIC_VER_LOG_JOB_TRAFFIC_VER] FOREIGN KEY([VERSION_ID])
REFERENCES [dbo].[JOB_TRAFFIC_VER] ([ID])
GO

ALTER TABLE [dbo].[JOB_TRAFFIC_VER_LOG] CHECK CONSTRAINT [FK_JOB_TRAFFIC_VER_LOG_JOB_TRAFFIC_VER]
GO