CREATE TABLE [dbo].[LAME_SUBPROCESS] (
    [LAME_SUBPROCESS_ID] INT           IDENTITY (1, 1) NOT NULL,
    [LAME_PROCESS_ID]    INT           NOT NULL,
    [SEC_MODULE_ID]      INT           NULL,
    [SUBPROCESS_NAME]    VARCHAR (255) NULL,
    [SUBPROCESS_START]   SMALLDATETIME NOT NULL
);

