CREATE TABLE [dbo].[MAG_GL] (
    [ORDER_NBR]      INT          NOT NULL,
    [LINE_NBR]       SMALLINT     NOT NULL,
    [REV_NBR]        SMALLINT     NOT NULL,
    [SEQ_NBR]        SMALLINT     NOT NULL,
    [GLEXACT]        INT          NULL,
    [GLESEQ_SALES]   SMALLINT     NULL,
    [GLESEQ_COS]     SMALLINT     NULL,
    [GLESEQ_WIP]     SMALLINT     NULL,
    [GLESEQ_STATE]   SMALLINT     NULL,
    [GLESEQ_COUNTY]  SMALLINT     NULL,
    [GLESEQ_CITY]    SMALLINT     NULL,
    [GLACODE_SALES]  VARCHAR (30) NULL,
    [GLACODE_COS]    VARCHAR (30) NULL,
    [GLACODE_WIP]    VARCHAR (30) NULL,
    [GLACODE_STATE]  VARCHAR (30) NULL,
    [GLACODE_COUNTY] VARCHAR (30) NULL,
    [GLACODE_CITY]   VARCHAR (30) NULL,
    [GLEXACT_DEF]    INT          NULL
);

