CREATE TABLE [dbo].[MEDIA_PLAN_DTL_LEVEL](
	[MEDIA_PLAN_DTL_LEVEL_ID] [int] IDENTITY(1,1) NOT NULL,
	[MEDIA_PLAN_DTL_ID] [int] NOT NULL,
	[MEDIA_PLAN_ID] [int] NOT NULL,
	[DESCRIPTION] [varchar](100) NOT NULL,
	[ORDER_NUMBER] [int] NOT NULL,
	[WIDTH] [int] NOT NULL,
	[TAG_TYPE] [int] NOT NULL DEFAULT(0),
 CONSTRAINT [PK_MEDIA_PLAN_DTL_LEVEL] PRIMARY KEY CLUSTERED 
(
	[MEDIA_PLAN_DTL_LEVEL_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[MEDIA_PLAN_DTL_LEVEL]  WITH CHECK ADD  CONSTRAINT [FK_MEDIA_PLAN_DTL_LEVEL_MEDIA_PLAN] FOREIGN KEY([MEDIA_PLAN_ID])
REFERENCES [dbo].[MEDIA_PLAN] ([MEDIA_PLAN_ID])
GO

ALTER TABLE [dbo].[MEDIA_PLAN_DTL_LEVEL] CHECK CONSTRAINT [FK_MEDIA_PLAN_DTL_LEVEL_MEDIA_PLAN]
GO

ALTER TABLE [dbo].[MEDIA_PLAN_DTL_LEVEL]  WITH CHECK ADD  CONSTRAINT [FK_MEDIA_PLAN_DTL_LEVEL_MEDIA_PLAN_DTL] FOREIGN KEY([MEDIA_PLAN_DTL_ID])
REFERENCES [dbo].[MEDIA_PLAN_DTL] ([MEDIA_PLAN_DTL_ID])
GO

ALTER TABLE [dbo].[MEDIA_PLAN_DTL_LEVEL] CHECK CONSTRAINT [FK_MEDIA_PLAN_DTL_LEVEL_MEDIA_PLAN_DTL]
GO


