CREATE TABLE [dbo].[MEDIA_PLAN](
	[MEDIA_PLAN_ID] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPTION] [varchar](100) NOT NULL,
	[USER_CREATED] [varchar](100) NOT NULL,
	[CREATED_DATE] [smalldatetime] NOT NULL,
	[USER_MODIFIED] [varchar](100) NULL,
	[MODIFIED_DATE] [smalldatetime] NULL,
	[APPROVED] [bit] NOT NULL,
	[APPROVED_BY] [varchar](6) NULL,
	[APPROVED_DATE] [smalldatetime] NULL,
	[COMMENT] [varchar](100) NOT NULL,
	[CL_CODE] [varchar](6) NOT NULL,
	[DIV_CODE] [varchar](6) NULL,
	[PRD_CODE] [varchar](6) NULL,
	[CDP_CONTACT_ID] [int] NULL,
	[CMP_CODE] [varchar](6) NULL,
	[START_DATE] [smalldatetime] NOT NULL,
	[END_DATE] [smalldatetime] NOT NULL,
	[GROSS_BUDGET_AMT] [decimal](10, 2) NULL,
 CONSTRAINT [PK_MEDIA_PLAN] PRIMARY KEY CLUSTERED 
(
	[MEDIA_PLAN_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[MEDIA_PLAN]  WITH CHECK ADD  CONSTRAINT [FK_MEDIA_PLAN_CLIENT] FOREIGN KEY([CL_CODE])
REFERENCES [dbo].[CLIENT] ([CL_CODE])
GO

ALTER TABLE [dbo].[MEDIA_PLAN] CHECK CONSTRAINT [FK_MEDIA_PLAN_CLIENT]
GO


