CREATE TABLE [dbo].[MEDIA_RPT_ORDERS] (
    [USER_ID]    VARCHAR (100) NOT NULL,
    [ORDER_NBR]  INT           NOT NULL,
    [ORDER_TYPE] VARCHAR (2)   NULL,
    PRIMARY KEY CLUSTERED ([USER_ID] ASC, [ORDER_NBR] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);

