CREATE TABLE [dbo].[MEDIA_SPECS_HDR] (
    [SPEC_ID]       INT           NOT NULL,
    [VN_CODE]       VARCHAR (6)   NOT NULL,
    [AD_SIZE]       VARCHAR (6)   NOT NULL,
    [CREATE_DATE]   SMALLDATETIME NOT NULL,
    [CREATE_USER]   VARCHAR (100) NOT NULL,
    [MODIFIED_DATE] SMALLDATETIME NULL,
    [MODIFIED_BY]   VARCHAR (100) NULL
);

