CREATE TABLE dbo.MEDIA_ORDER_DETAIL (
	MD_ID						integer identity(1, 1) NOT NULL,
	[USER_ID]					varchar(100) NOT NULL,
	ORDER_NBR					int NOT NULL,
	LINE_NBR					smallint NOT NULL,
	REV_NBR						smallint NULL,
	SEQ_NBR						tinyint NULL,
	DATE_TYPE					varchar(3) COLLATE SQL_Latin1_General_CP1_CS_AS,
	[MONTH]						tinyint NULL,
	[YEAR]						smallint NULL,
	INSERT_DATE					smalldatetime,
	END_DATE					smalldatetime,
	DATE_TO_BILL				smalldatetime,
	CLOSE_DATE					smalldatetime,
	MATL_CLOSE_DATE				smalldatetime,
	LINE_DESC					varchar(60) COLLATE SQL_Latin1_General_CP1_CS_AS,
	AD_SIZE						varchar(60) COLLATE SQL_Latin1_General_CP1_CS_AS,
	EDITION_ISSUE				varchar(60) COLLATE SQL_Latin1_General_CP1_CS_AS,
	SECTION						varchar(60) COLLATE SQL_Latin1_General_CP1_CS_AS,
	MATERIAL					varchar(60) COLLATE SQL_Latin1_General_CP1_CS_AS,
	REMARKS						text,
	URL							varchar(60) COLLATE SQL_Latin1_General_CP1_CS_AS,
	COPY_AREA					text,
	MATL_NOTES					text,
	POSITION_INFO				text,
	MISC_INFO					text,
	JOB_NUMBER					int NULL,
	JOB_COMPONENT_NBR			smallint NULL,
	COST_TYPE					varchar(60) COLLATE SQL_Latin1_General_CP1_CS_AS,
	RATE_TYPE					varchar(60) COLLATE SQL_Latin1_General_CP1_CS_AS,
	PRINT_LINES					varchar(60) COLLATE SQL_Latin1_General_CP1_CS_AS,
	GUARANTEED_IMPRESS			int NULL,
	NON_BILL_FLAG				tinyint NULL DEFAULT 0,
	LINE_CANCELLED				tinyint NULL DEFAULT 0,
	BILLED_TYPE_FLAG			tinyint NULL DEFAULT 0,
	LINK_ID						int NULL,
	SPOTS						int NULL, 
  CONSTRAINT PK_MEDIA_ORDER_DETAIL PRIMARY KEY ( MD_ID ))
