CREATE TABLE [dbo].[MEDIA_RPT_DATES] (
    [RPT_DATES_ID]     INT           IDENTITY (1, 1) NOT NULL,
    [ORDER_NBR]        INT           NOT NULL,
    [VN_VR_TYPE]       SMALLINT      NOT NULL,
    [VN_VR_CODE]       VARCHAR (6)   NOT NULL,
    [VN_VR_NAME]       VARCHAR (40)  NULL,
    [VN_VR_EMAIL]      VARCHAR (50)  NULL,
    [VN_VR_PRINT_DATE] SMALLDATETIME NULL,
    [VN_VR_EMAIL_DATE] SMALLDATETIME NULL
);

