CREATE TABLE [dbo].[MISSING_TIME_HDR] (
    [LAST_DATE_UPDATED]  DATETIME      NULL,
    [START_DATE]         SMALLDATETIME NULL,
    [END_DATE]           SMALLDATETIME NULL,
    [EXCLUDE_HOL_WKENDS] SMALLINT      NULL,
    [MISSING_TIME_ONLY]  SMALLINT      NULL
);

