CREATE TABLE [dbo].[NEWS_DETAIL] (
    [ORDER_NBR]         INT             NOT NULL,
    [LINE_NBR]          SMALLINT        NOT NULL,
    [REV_NBR]           SMALLINT        NOT NULL,
    [SEQ_NBR]           SMALLINT        NOT NULL,
    [INSERT_DATE]       SMALLDATETIME   NULL,
    [CLOSE_DATE]        SMALLDATETIME   NULL,
    [MATL_CLOSE_DATE]   SMALLDATETIME   NULL,
    [EXT_CLOSE_DATE]    SMALLDATETIME   NULL,
    [EXT_MATL_DATE]     SMALLDATETIME   NULL,
    [MATERIAL]          VARCHAR (25)    NULL,
    [EDITION]           VARCHAR (25)    NULL,
    [SECTION]           VARCHAR (25)    NULL,
    [HEADLINE]          VARCHAR (40)    NULL,
    [RATE_CARD]         VARCHAR (10)    NULL,
    [MARKET_CODE]       VARCHAR (10)    NULL,
    [RATE_DESC]         VARCHAR (30)    NULL,
    [RATE_BY]           SMALLINT        NULL,
    [RATE]              DECIMAL (14, 3) NULL,
    [NET_GROSS]         SMALLINT        NULL,
    [FLAT_NET]          DECIMAL (14, 4) NULL,
    [FLAT_GROSS]        DECIMAL (14, 4) NULL,
    [NET_RATE]          DECIMAL (14, 4) NULL,
    [GROSS_RATE]        DECIMAL (14, 4) NULL,
    [COMM_PCT]          DECIMAL (7, 3)  NULL,
    [COMM_AMT]          DECIMAL (14, 2) NULL,
    [MARKUP_PCT]        DECIMAL (7, 3)  NULL,
    [REBATE_PCT]        DECIMAL (7, 3)  NULL,
    [REBATE_AMT]        DECIMAL (14, 2) NULL,
    [SIZE1]             DECIMAL (6, 2)  NULL,
    [SIZE2]             DECIMAL (6, 2)  NULL,
    [COLORCHARGE]       DECIMAL (14, 3) NULL,
    [COLORDESC]         VARCHAR (10)    NULL,
    [USE_COLOR]         SMALLINT        NULL,
    [COLOR_TYPE]        SMALLINT        NULL,
    [COLOR_AMT]         DECIMAL (14, 2) NULL,
    [PICTURE]           VARCHAR (30)    NULL,
    [LINE_CANCELLED]    SMALLINT        NULL,
    [JOB_NUMBER]        INT             NULL,
    [JOB_COMPONENT_NBR] SMALLINT        NULL,
    [PRINTED]           SMALLINT        NULL,
    [DATE_TO_BILL]      SMALLDATETIME   NULL,
    [BILLING_USER]      VARCHAR (100)   NULL,
    [AR_INV_NBR]        INT             NULL,
    [AR_TYPE]           VARCHAR (2)     NULL,
    [AR_INV_SEQ]        SMALLINT        NULL,
    [LINE_TOTAL]        DECIMAL (15, 2) NULL,
    [EXT_NET_AMT]       DECIMAL (15, 2) NULL,
    [EXT_GROSS_AMT]     DECIMAL (15, 2) NULL,
    [EXT_NET_FLAT]      DECIMAL (15, 2) NULL,
    [EXT_GROSS_FLAT]    DECIMAL (15, 2) NULL,
    [LINK_ID]           INT             NULL,
    [LINK_DETID]        INT             NULL
);

