CREATE TABLE [dbo].[OFF_FNC_ACCTS] (
    [OFFICE_CODE]    VARCHAR (4)  NOT NULL,
    [FNC_CODE]       VARCHAR (6)  NOT NULL,
    [PGLACODE_SALES] VARCHAR (30) NOT NULL,
    [PGLACODE_COS]   VARCHAR (30) NOT NULL
);

