CREATE TABLE [dbo].[OFF_TAX_ACCTS] (
    [OFFICE_CODE]       VARCHAR (4)  NOT NULL,
    [TAX_CODE]          VARCHAR (4)  NOT NULL,
    [GLACODE_TAX_STATE] VARCHAR (30) NOT NULL,
    [GLACODE_TAX_CNTY]  VARCHAR (30) NOT NULL,
    [GLACODE_TAX_CITY]  VARCHAR (30) NOT NULL
);

