CREATE TABLE [dbo].[OFF_INTER_CO] (
    [OFFICE_CODE]   VARCHAR (4)  NOT NULL,
    [INTER_CO_CODE] VARCHAR (4)  NOT NULL,
    [DUE_FROM]      VARCHAR (30) NOT NULL,
    [DUE_TO]        VARCHAR (30) NOT NULL
);

