CREATE TABLE [dbo].[ORD_PROCESS_LOG] (
    [ORDER_NBR]          INT           NOT NULL,
    [ORIG_PROCESS_CNTRL] SMALLINT      NULL,
    [NEW_PROCESS_CNTRL]  SMALLINT      NULL,
    [PROCESS_DATE]       SMALLDATETIME DEFAULT (getdate()) NULL,
    [PROCESS_USER]       VARCHAR (100) NULL,
    [PROCESS_COMMENT]    TEXT          NULL
);

