CREATE TABLE [dbo].[PARTNER] (
    [PARTNER_CODE]      VARCHAR (6)    NOT NULL,
    [PARTNER_NAME]      VARCHAR (60)   NOT NULL,
    [PARTNER_ADDRESS1]  VARCHAR (40)   NULL,
    [PARTNER_ADDRESS2]  VARCHAR (40)   NULL,
    [PARTNER_CITY]      VARCHAR (25)   NULL,
    [PARTNER_STATE]     VARCHAR (10)   NULL,
    [PARTNER_ZIP]       VARCHAR (10)   NULL,
    [PARTNER_COUNTRY]   VARCHAR (20)   NULL,
    [PARTNER_PHONE]     VARCHAR (13)   NULL,
    [PARTNER_PHONE_EXT] VARCHAR (4)    NULL,
    [PARTNER_FAX]       VARCHAR (13)   NULL,
    [PARTNER_FAX_EXT]   VARCHAR (4)    NULL,
    [PARTNER_EMAIL]     VARCHAR (50)   NULL,
    [PARTNER_PCT]       DECIMAL (7, 3) NOT NULL,
    [MARKET_CODE]       VARCHAR (10)   NULL,
    [REGION_CODE]       VARCHAR (20)   NULL,
    [PARTNER_COMMENT]   TEXT           NULL,
    [INACTIVE_FLAG]     SMALLINT       NOT NULL
);

