CREATE TABLE [dbo].[PBCATCOL] (
    [PBC_TNAM] VARCHAR (19)  NOT NULL,
    [PBC_TID]  INT           NULL,
    [PBC_OWNR] VARCHAR (9)   NOT NULL,
    [PBC_CNAM] VARCHAR (19)  NOT NULL,
    [PBC_CID]  SMALLINT      NULL,
    [PBC_LABL] VARCHAR (254) NULL,
    [PBC_LPOS] SMALLINT      NULL,
    [PBC_HDR]  VARCHAR (254) NULL,
    [PBC_HPOS] SMALLINT      NULL,
    [PBC_JTFY] SMALLINT      NULL,
    [PBC_MASK] VARCHAR (31)  NULL,
    [PBC_CASE] SMALLINT      NULL,
    [PBC_HGHT] SMALLINT      NULL,
    [PBC_WDTH] SMALLINT      NULL,
    [PBC_PTRN] VARCHAR (31)  NULL,
    [PBC_BMAP] VARCHAR (1)   NULL,
    [PBC_INIT] VARCHAR (254) NULL,
    [PBC_CMNT] VARCHAR (254) NULL,
    [PBC_EDIT] VARCHAR (31)  NULL,
    [PBC_TAG]  VARCHAR (254) NULL
);

