CREATE TABLE [dbo].[PO_PRINT_DEF] (
    [USER_ID]            VARCHAR (100) NOT NULL,
    [DATE_TO_PRINT]      SMALLINT      NULL,
    [SHP_INSTRUCTION]    SMALLINT      NULL,
    [PO_INSTRUCTION]     SMALLINT      NULL,
    [FOOTER_COMMENT]     SMALLINT      NULL,
    [DETAIL_DESCRIPTION] SMALLINT      NULL,
    [DETAIL_INSTRUCTION] SMALLINT      NULL,
    [VENDOR_CONTACT]     SMALLINT      NULL,
    [CLIENT_NAME]        SMALLINT      NULL,
    [PRODUCT_NAME]       SMALLINT      NULL,
    [JOB_CMP_NBR]        SMALLINT      NULL,
    [LOCATION_ID]        VARCHAR (6)   NULL,
    [LOGO_PATH]          VARCHAR (254) NULL,
    [REPORT_FORMAT]      VARCHAR (50)  NULL,
    [FNC_DESCRIPTION]    SMALLINT      NULL,
    [JOB_DESC]           SMALLINT      NULL,
    [USE_EMP_SIG]        SMALLINT      NULL,
    [USE_USER_SIG]        SMALLINT      NULL
);

