CREATE TABLE [dbo].[POSTPERIOD] (
    [PPPERIOD]   VARCHAR (6)   NOT NULL,
    [PPARMONTH]  SMALLINT      NULL,
    [PPARYEAR]   VARCHAR (5)   NULL,
    [PPARCURMTH] VARCHAR (1)   NULL,
    [PPGLMONTH]  SMALLINT      NULL,
    [PPGLYEAR]   VARCHAR (5)   NULL,
    [PPGLCURMTH] VARCHAR (1)   NULL,
    [PPAPCURMTH] VARCHAR (1)   NULL,
    [PPSRTDATE]  SMALLDATETIME NULL,
    [PPENDDATE]  SMALLDATETIME NULL,
    [PPDESC]     VARCHAR (10)  NOT NULL,
    [PPUSER]     VARCHAR (100) NULL,
    [PPENTDATE]  SMALLDATETIME NULL,
    [PPMODDATE]  SMALLDATETIME NULL,
    [PPMOD]      VARCHAR (1)   NULL,
    [ROWID]      INT           IDENTITY (1, 1) NOT NULL,
    [PPTECURMTH] VARCHAR (1)   NULL
);

