CREATE TABLE [dbo].[PRD_SRT_KEY] (
    [CL_CODE]     VARCHAR (6)  NOT NULL,
    [DIV_CODE]    VARCHAR (6)  NOT NULL,
    [PRD_CODE]    VARCHAR (6)  NOT NULL,
    [PRD_SRT_KEY] VARCHAR (20) NOT NULL
);

