CREATE TABLE [dbo].[PRODUCT_CATEGORY] (
    [CL_CODE]       VARCHAR (6)  NOT NULL,
    [DIV_CODE]      VARCHAR (6)  NOT NULL,
    [PRD_CODE]      VARCHAR (6)  NOT NULL,
    [PROD_CAT_CODE] VARCHAR (10) NOT NULL,
    [PROD_CAT_DESC] VARCHAR (60) NOT NULL,
    [INACTIVE_FLAG] SMALLINT     NULL
);

