CREATE TABLE [dbo].[PROFIT_RPT_CLI] (
    [CL_CODE]          VARCHAR (6)     NULL,
    [MEDIA_TYPE]       VARCHAR (15)    NULL,
    [SC_CODE]          VARCHAR (6)     NULL,
    [CURRENT_BILLING]  DECIMAL (15, 2) NULL,
    [YTD_BILLING]      DECIMAL (15, 2) NULL,
    [CURRENT_INCOME]   DECIMAL (15, 2) NULL,
    [YTD_INCOME]       DECIMAL (15, 2) NULL,
    [CURPCTBILLINCOME] DECIMAL (15, 4) NULL,
    [YTDPCTBILLINCOME] DECIMAL (15, 4) NULL,
    [CURRENT_EMP_COST] DECIMAL (15, 2) NULL,
    [CURRENT_HOURS]    DECIMAL (15, 2) NULL,
    [YTD_EMP_COST]     DECIMAL (15, 2) NULL,
    [YTD_HOURS]        DECIMAL (15, 2) NULL,
    [CURRENT_DIR_EXP]  DECIMAL (15, 2) NULL,
    [YTD_DIRECT_EXP]   DECIMAL (15, 2) NULL,
    [CURRENT_OH_PCT]   DECIMAL (15, 4) NULL,
    [CURRENT_OVERHEAD] DECIMAL (15, 2) NULL,
    [YTD_OH_PCT]       DECIMAL (15, 4) NULL,
    [YTD_OVERHEAD]     DECIMAL (15, 2) NULL
);

