CREATE TABLE [dbo].[PROFIT_RPT_DTL] (
    [POST_PERIOD]     VARCHAR (8)     NULL,
    [OVERHEAD]        DECIMAL (14, 2) NULL,
    [EMP_HOURS]       DECIMAL (14, 2) NULL,
    [EMP_COST]        DECIMAL (14, 2) NULL,
    [DIRECT_EXPENSE]  DECIMAL (14, 2) NULL,
    [INCOME_AMT]      DECIMAL (14, 2) NULL,
    [BILLING_AMT]     DECIMAL (14, 2) NULL,
    [PCT_BILL_INCOME] DECIMAL (15, 3) NULL,
    [DATE_UPDATED]    SMALLDATETIME   NULL
);

