CREATE TABLE dbo.RPT_RUNTIME_SPECS (
	RRS_ID					integer identity(1, 1) NOT NULL,
	ADVAN_DSN				varchar(255) NOT NULL,
	[USER_ID]				varchar(100) NOT NULL,
	APP_TYPE				varchar(2) NOT NULL,
	LINK_ID					tinyint NULL DEFAULT 1,
	SEL_DATE				smalldatetime NULL,
	DATE_SQL				smalldatetime NULL,
	PRINT_DATE				smalldatetime NULL,
	MEMO_OPT				tinyint NULL,
	ADDRESS_OPT				tinyint NULL,
	NAME_OVERIDE_OPT		tinyint NULL,
	FUNCTION_OPT			tinyint NULL,
	PREVIEW					tinyint NOT NULL,
	DRAFT					tinyint NOT NULL,
	ONE_TIME				tinyint NOT NULL,
	USER_FORMS_PATH			varchar(255) NULL,
	ACCESS_TMP_PATH			varchar(255) NULL,
	[FROM]					varchar(255) NULL,
	[SUBJECT]				varchar(255) NULL,
	BODY					text NULL,
	CC_ME					tinyint NULL,
	INV_ORD_TYPE			varchar(2) NULL,
	FROM_PERIOD				integer NULL,
	TO_PERIOD				integer NULL,
	FROM_DATE				smalldatetime NULL,
	TO_DATE					smalldatetime NULL,
	SIGNATURE_FILE			varchar(255) NULL,
  CONSTRAINT PK_RPT_RUNTIME_SPECS PRIMARY KEY ( RRS_ID ) )
