CREATE TABLE [dbo].[SEC_USER_UDRACCESS] (
    [SEC_USER_UDRACCESS_ID] INT IDENTITY (1, 1) NOT NULL,
    [SEC_USER_ID]           INT NOT NULL,
    [USER_DEF_REPORT_ID]    INT NOT NULL,
    [IS_BLOCKED]            BIT NOT NULL
);

