CREATE TABLE [dbo].[SEC_MODULE] (
    [SEC_MODULE_ID]      INT           IDENTITY (1, 1) NOT NULL,
    [SEC_MODULE_CODE]    VARCHAR (100) NOT NULL,
    [DESCRIPTION]        VARCHAR (100) NOT NULL,
    [IS_INACTIVE]        BIT           NOT NULL,
    [IS_MENU_ITEM]       BIT           NOT NULL,
    [IS_CATEGORY]        BIT           NOT NULL,
    [IS_APPLICATION]     BIT           NOT NULL,
    [IS_REPORT]          BIT           NOT NULL,
    [IS_DESKTOP_OBJECT]  BIT           NOT NULL,
    [IS_DASH_QUERY]      BIT           NOT NULL,
    [SEC_MODULE_INFO_ID] INT           NOT NULL,
    UNIQUE NONCLUSTERED ([SEC_MODULE_CODE] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY]
);

