CREATE TABLE [dbo].[SEC_GROUP_UDRACCESS] (
    [SEC_GROUP_UDRACCESS_ID] INT IDENTITY (1, 1) NOT NULL,
    [SEC_GROUP_ID]           INT NOT NULL,
    [USER_DEF_REPORT_ID]     INT NOT NULL,
    [IS_BLOCKED]             BIT NOT NULL
);

