CREATE TABLE [dbo].[SEC_CPUSER_APPACCESS](
	[SEC_CPUSER_APPACCESS_ID] [int] IDENTITY(1,1) NOT NULL,
	[CPUSER_GUID] [uniqueidentifier] NOT NULL,
	[SEC_APPLICATION_ID] [int] NOT NULL,
	[IS_BLOCKED] [bit] NOT NULL,
	[CAN_PRINT] [bit] NOT NULL,
	[CAN_UPDATE] [bit] NOT NULL,
	[CAN_ADD] [bit] NOT NULL,
	[CUSTOM1] [bit] NOT NULL,
	[CUSTOM2] [bit] NOT NULL,
 CONSTRAINT [PK_SEC_CPUSER_APPACCESS] PRIMARY KEY CLUSTERED 
(
	[SEC_CPUSER_APPACCESS_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
