CREATE TABLE [dbo].[SERVICE_FEE_DEF] (
    [USER_ID]                      VARCHAR (100) NOT NULL,
    [INCOME_ONLY_INCL]             SMALLINT      NULL,
    [PRODUCT_COMM_INCL]            SMALLINT      NULL,
    [MEDIA_COMM_INCL]              SMALLINT      NULL,
    [STD_FEE_JOB_COMP]             SMALLINT      NULL,
    [STD_FEE_SC]                   SMALLINT      NULL,
    [STD_FEE_FUNC]                 SMALLINT      NULL,
    [PROD_COMM_SC]                 SMALLINT      NULL,
    [PROD_COMM_FUNC]               SMALLINT      NULL,
    [BROAD_COMM]                   SMALLINT      NULL,
    [MAG_COMM]                     SMALLINT      NULL,
    [NEWS_COMM]                    SMALLINT      NULL,
    [INT_COMM]                     SMALLINT      NULL,
    [OOH_COMM]                     SMALLINT      NULL,
    [CDP_INCL]                     SMALLINT      NULL,
    [UN_REC_ONLY]                  SMALLINT      NULL,
    [FEETIME_TYPE_INCL_STD]        SMALLINT      NULL,
    [FEETIME_TYPE_INCL_PROD_COMM]  SMALLINT      NULL,
    [FEETIME_TYPE_INCL_MEDIA_COMM] SMALLINT      NULL,
    [PRIMARY_DISPL_OPT]            SMALLINT      NULL,
    [GRD_DISPL_OPT_CMPN]           SMALLINT      NULL,
    [GRD_DISPL_OPT_JOB_NBR]        SMALLINT      NULL,
    [GRD_DISPL_OPT_JOB_NAME]       SMALLINT      NULL,
    [GRD_DISPL_OPT_COMP_NBR]       SMALLINT      NULL,
    [GRD_DISPL_OPT_COMP_NAME]      SMALLINT      NULL,
    [GRD_DISPL_OPT_FUNC]           SMALLINT      NULL
);

