CREATE TABLE [dbo].[STRATA_PRINT_INV] (
    [RECSEQ]            INT             NOT NULL,
    [INV_NUMBER]        VARCHAR (20)    NOT NULL,
    [REV_NBR]           SMALLINT        NOT NULL,
    [INV_DATE]          SMALLDATETIME   NULL,
    [INV_DESC]          VARCHAR (30)    NULL,
    [LINK_ID]           INT             NOT NULL,
    [ORD_LINE_NBR]      VARCHAR (4)     NULL,
    [MEDIA_TYPE]        VARCHAR (2)     NOT NULL,
    [ADVAN_ORDER_NBR]   INT             NULL,
    [CL_CODE]           VARCHAR (6)     NULL,
    [PROD_CODE]         VARCHAR (6)     NULL,
    [DIV_CODE]          VARCHAR (6)     NULL,
    [VENDOR_CODE]       VARCHAR (6)     NULL,
    [INV_LINE_GROSS]    DECIMAL (14, 2) NULL,
    [INV_LINE_NET]      DECIMAL (14, 2) NULL,
    [BAD_FLAG]          SMALLINT        NULL,
    [ORG_VN_CODE]       VARCHAR (6)     NULL,
    [POST_FLAG]         SMALLINT        NOT NULL,
    [QTY]               INT             NULL,
    [LINE_NETCHARGES]   DECIMAL (14, 2) NULL,
    [TOTAL_INV_AMT]     DECIMAL (16, 2) NULL,
    [MEDIA_INTERFACE]   VARCHAR (2)     DEFAULT ('ST') NOT NULL,
    [LN_RATE_CHG_GROSS] DECIMAL (14, 2) NULL,
    [LN_RATE_CHG_NET]   DECIMAL (14, 2) NULL,
    [PRINT_LINES]       DECIMAL (11, 2) NULL,
    [DELETE_INV]        SMALLINT        NULL
);

