CREATE TABLE [dbo].[TEMP_RADIO_AP] (
    [ORDER_NBR]  INT             NULL,
    [NET_AMT]    DECIMAL (15, 2) NULL,
    [COMM_AMT]   DECIMAL (15, 2) NULL,
    [DISC_AMT]   DECIMAL (15, 2) NULL,
    [REBATE_AMT] DECIMAL (15, 2) NULL,
    [NETCHARGES] DECIMAL (15, 2) NULL,
    [TAX_AMT]    DECIMAL (15, 2) NULL,
    [TOTAL_AMT]  DECIMAL (15, 2) NULL
);

