IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[TIME_ZONE]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN 
	DROP TABLE [dbo].[TIME_ZONE]
END

CREATE TABLE [dbo].[TIME_ZONE](
	[ID] [int] NOT NULL,
	[NAME] [varchar](100) NOT NULL,
	[UTC_OFFSET_TICKS] [int] NOT NULL,
	[OFFSET_HOURS] [decimal](9,3) NOT NULL,
 CONSTRAINT [PK_TIME_ZONE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
