CREATE TABLE [dbo].[UDR_REPORT_CATEGORY](
	[UDR_REPORT_CATEGORY_ID] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPTION] [varchar](100) NOT NULL,
 CONSTRAINT [PK_UDR_REPORT_CATEGORY] PRIMARY KEY CLUSTERED 
(
	[UDR_REPORT_CATEGORY_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO