CREATE TABLE [dbo].[VENDOR_QTE_HDR] (
    [ESTIMATE_NUMBER]   INT           NOT NULL,
    [EST_COMPONENT_NBR] SMALLINT      NOT NULL,
    [VENDOR_QTE_NBR]    INT           NOT NULL,
    [VENDOR_QTE_DESC]   VARCHAR (60)  NULL,
    [VN_QTE_MEMO]       TEXT          NULL,
    [CREATED_BY]        VARCHAR (100) NULL,
    [CREATE_DATE]       SMALLDATETIME NULL
);

