CREATE TABLE [dbo].[VENDOR] (
    [VN_CODE]            VARCHAR (6)     NOT NULL,
    [VN_NAME]            VARCHAR (40)    NULL,
    [VN_ADDRESS1]        VARCHAR (40)    NULL,
    [VN_ADDRESS2]        VARCHAR (40)    NULL,
    [VN_CITY]            VARCHAR (25)    NULL,
    [VN_COUNTY]          VARCHAR (20)    NULL,
    [VN_STATE]           VARCHAR (10)    NULL,
    [VN_COUNTRY]         VARCHAR (20)    NULL,
    [VN_ZIP]             VARCHAR (10)    NULL,
    [VN_PHONE]           VARCHAR (13)    NULL,
    [VN_PHONE_EXT]       VARCHAR (4)     NULL,
    [VN_FAX_NUMBER]      VARCHAR (13)    NULL,
    [VN_FAX_EXTENTION]   VARCHAR (4)     NULL,
    [VN_PAY_TO_NAME]     VARCHAR (40)    NULL,
    [VN_PAY_TO_ADDRESS1] VARCHAR (40)    NULL,
    [VN_PAY_TO_ADDRESS2] VARCHAR (40)    NULL,
    [VN_PAY_TO_CITY]     VARCHAR (25)    NULL,
    [VN_PAY_TO_COUNTY]   VARCHAR (20)    NULL,
    [VN_PAY_TO_STATE]    VARCHAR (10)    NULL,
    [VN_PAY_TO_COUNTRY]  VARCHAR (20)    NULL,
    [VN_PAY_TO_ZIP]      VARCHAR (10)    NULL,
    [VN_PAY_TO_PHONE]    VARCHAR (13)    NULL,
    [VN_PAY_TO_EXT]      VARCHAR (4)     NULL,
    [VN_PAY_TO_FAX_NBR]  VARCHAR (13)    NULL,
    [VN_PAY_TO_FAX_EXT]  VARCHAR (4)     NULL,
    [VN_PAY_TO_CODE]     VARCHAR (6)     NULL,
    [VT_CODE]            VARCHAR (3)     NULL,
    [VN_TAX_ID]          VARCHAR (20)    NULL,
    [VN_1099_FLAG]       SMALLINT        NULL,
    [VN_ALPHA_SORT]      VARCHAR (20)    NULL,
    [PO_FORMAT]          VARCHAR (4)     NULL,
    [VN_CATEGORY]        VARCHAR (1)     NULL,
    [GLACODE_AP]         VARCHAR (30)    NULL,
    [VN_NOTES]           TEXT            NULL,
    [VN_ACTIVE_FLAG]     SMALLINT        NULL,
    [GLACODE_EXP]        VARCHAR (30)    NULL,
    [WH_VENDOR_TYPE]     SMALLINT        NULL,
    [WH_WAIVER]          SMALLINT        NULL,
    [WH_BASE_AMT]        DECIMAL (14, 2) NULL,
    [WH_PERCENT]         DECIMAL (6, 3)  NULL,
    [GLACODE_AP_WH]      VARCHAR (30)    NULL,
    [GLACODE_VOL_DISC]   VARCHAR (30)    NULL,
    [ASSOC_OFFICE]       SMALLINT        NULL,
    [OFFICE_CODE]        VARCHAR (4)     NULL,
    [DEF_SALES_TAX]      VARCHAR (4)     NULL,
    [VN_1099_ADDRESS1]   VARCHAR (40)    NULL,
    [VN_1099_ADDRESS2]   VARCHAR (40)    NULL,
    [VN_1099_CITY]       VARCHAR (25)    NULL,
    [VN_1099_STATE]      VARCHAR (10)    NULL,
    [VN_1099_ZIP]        VARCHAR (10)    NULL,
    [VN_1099_COUNTY]     VARCHAR (20)    NULL,
    [VN_1099_COUNTRY]    VARCHAR (20)    NULL,
    [VN_USE_1099]        SMALLINT        NULL,
    [VN_COMM]            DECIMAL (7, 3)  NULL,
    [VN_ADDRESS3]        VARCHAR (30)    NULL,
    [VN_PAY_TO_ADDRESS3] VARCHAR (30)    NULL,
    [VN_ACCT_NBR]        VARCHAR (30)    NULL,
    [MARKET_CODE]        VARCHAR (10)    NULL,
    [VN_1099_ADDRESS3]   VARCHAR (30)    NULL,
    [DAILY_CIRC]         INT             NULL,
    [SUNDAY_CIRC]        INT             NULL,
    [MATL_CLOSE]         SMALLINT        NULL,
    [SPACE_CLOSE]        SMALLINT        NULL,
    [DEF_FNC_CODE]       VARCHAR (6)     NULL,
    [EMP_VENDOR]         INT             NULL,
    [DEF_UNITS]          VARCHAR (2)     NULL,
    [DEF_NET_GROSS]      SMALLINT        NULL,
    [COOP_FLAG]          SMALLINT        NULL,
    [VN_MF_VN_CODE]      VARCHAR (10)    NULL,
    [DEF_VN_CONT]        VARCHAR (4)     NULL,
    [ONE_CHECK_PER_INV]  SMALLINT        NULL,
    [ISSUES]             INT             NULL,
    [CYCLE]              VARCHAR (3)     NULL,
    [USE_TAX_FLAGS]      SMALLINT        NULL,
    [TAXAPPLYC]          SMALLINT        NULL,
    [TAXAPPLYLN]         SMALLINT        NULL,
    [TAXAPPLYND]         SMALLINT        NULL,
    [TAXAPPLYNC]         SMALLINT        NULL,
    [TAXAPPLYR]          SMALLINT        NULL,
    [TAXAPPLYAI]         SMALLINT        NULL,
    [COLUMN_SIZE]        DECIMAL (6, 2)  NULL,
    [WEB_ADDR]           VARCHAR (250)   NULL,
    [EDITIONS]           TEXT            NULL,
    [VN_EMAIL]           VARCHAR (50)    NULL,
    [VN_PAY_TO_EMAIL]    VARCHAR (50)    NULL,
    [TECH_GEN_INFO]      TEXT            NULL,
    [PUB_FREQ]           VARCHAR (250)   NULL,
    [DEF_SIZE]           VARCHAR (10)    NULL,
    [DEF_SIZE_TYPE]      VARCHAR (1)     NULL,
    [SHIP_NAME]          VARCHAR (40)    NULL,
    [SHIP_ADDR1]         VARCHAR (40)    NULL,
    [SHIP_ADDR2]         VARCHAR (40)    NULL,
    [SHIP_ADDR3]         VARCHAR (40)    NULL,
    [SHIP_CITY]          VARCHAR (25)    NULL,
    [SHIP_COUNTY]        VARCHAR (20)    NULL,
    [SHIP_STATE]         VARCHAR (10)    NULL,
    [SHIP_COUNTRY]       VARCHAR (20)    NULL,
    [SHIP_ZIP]           VARCHAR (10)    NULL,
    [VN_1099_INC_TYPE]   SMALLINT        NULL,
    [DEF_VN_REP1]        VARCHAR (4)     NULL,
    [DEF_VN_REP2]        VARCHAR (4)     NULL,
    [VN_CODE_XREF]       VARCHAR (12)     NULL,
    [IN_CATEGORY]        SMALLINT        NULL,
    [MG_CATEGORY]        SMALLINT        NULL,
    [NP_CATEGORY]        SMALLINT        NULL,
    [OD_CATEGORY]        SMALLINT        NULL,
    [RD_CATEGORY]        SMALLINT        NULL,
    [TV_CATEGORY]        SMALLINT        NULL,
    [PRD_CATEGORY]       SMALLINT        NULL,
    [OVERAGE_PCT]        DECIMAL (7, 3)  NULL,
    [FOLD]               SMALLINT        NULL,
    [CURRENCY_CODE]      VARCHAR (5)     NULL,
    [ACH]                SMALLINT        NULL,
    [ACH_TYPE]           VARCHAR (3)     NULL
);

