IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[WORKFLOW_REQUIREMENT]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN

	CREATE TABLE [dbo].[WORKFLOW_REQUIREMENT](
		[WORKFLOW_REQUIREMENT_ID] [int] IDENTITY(1,1) NOT NULL,
		[KEY_NAME] [varchar](100) NOT NULL,
		[WORKFLOW_ID] [int] NOT NULL,
	 CONSTRAINT [PK_WORKFLOW_REQ] PRIMARY KEY CLUSTERED 
	(
		[WORKFLOW_REQUIREMENT_ID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY];

END