IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[WORKFLOW_ALERT_STATE]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN

	CREATE TABLE [dbo].[WORKFLOW_ALERT_STATE](
		[WORKFLOW_ALERT_STATE_ID] [int] NOT NULL,
		[WORKFLOW_ID] [int] NOT NULL,
		[ALRT_NOTIFY_HDR_ID] [int] NOT NULL,
		[ALERT_STATE_ID] [int] NOT NULL,
	 CONSTRAINT [PK_WORKFLOW_ALERT_STATE] PRIMARY KEY CLUSTERED 
	(
		[WORKFLOW_ALERT_STATE_ID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY];

END

IF NOT EXISTS (SELECT * 
               FROM sys.foreign_keys 
               WHERE object_id = OBJECT_ID(N'[dbo].[FK_WORKFLOW_ALERT_STATE_ALERT_NOTIFY_HDR]') 
               AND parent_object_id = OBJECT_ID(N'[dbo].[WORKFLOW_ALERT_STATE]'))
BEGIN

	ALTER TABLE [dbo].[WORKFLOW_ALERT_STATE]  WITH CHECK ADD  CONSTRAINT [FK_WORKFLOW_ALERT_STATE_ALERT_NOTIFY_HDR] FOREIGN KEY([ALRT_NOTIFY_HDR_ID])
	REFERENCES [dbo].[ALERT_NOTIFY_HDR] ([ALRT_NOTIFY_HDR_ID]);

END

IF NOT EXISTS (SELECT * 
               FROM sys.foreign_keys 
               WHERE object_id = OBJECT_ID(N'[dbo].[FK_WORKFLOW_ALERT_STATE_ALERT_STATES]') 
               AND parent_object_id = OBJECT_ID(N'[dbo].[WORKFLOW_ALERT_STATE]'))
BEGIN

	ALTER TABLE [dbo].[WORKFLOW_ALERT_STATE]  WITH CHECK ADD  CONSTRAINT [FK_WORKFLOW_ALERT_STATE_ALERT_STATES] FOREIGN KEY([ALERT_STATE_ID])
	REFERENCES [dbo].[ALERT_STATES] ([ALERT_STATE_ID]);

END

IF NOT EXISTS (SELECT * 
               FROM sys.foreign_keys 
               WHERE object_id = OBJECT_ID(N'[dbo].[FK_WORKFLOW_ALERT_STATE_WORKFLOW]') 
               AND parent_object_id = OBJECT_ID(N'[dbo].[WORKFLOW_ALERT_STATE]'))
BEGIN

	ALTER TABLE [dbo].[WORKFLOW_ALERT_STATE]  WITH CHECK ADD  CONSTRAINT [FK_WORKFLOW_ALERT_STATE_WORKFLOW] FOREIGN KEY([WORKFLOW_ID])
	REFERENCES [dbo].[WORKFLOW] ([WORKFLOW_ID]);

END