IF NOT EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'COMSCORE_PRECACHE_MARKET') BEGIN

    CREATE TABLE [dbo].[COMSCORE_PRECACHE_MARKET](
	    [COMSCORE_PRECACHE_MARKET_ID] [int] IDENTITY(1,1) NOT NULL,
	    [MARKET_CODE] [varchar](10) NOT NULL,
     CONSTRAINT [PK_COMSCORE_PRECACHE_MARKET] PRIMARY KEY CLUSTERED
    (
	    [COMSCORE_PRECACHE_MARKET_ID] ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
    ) ON [PRIMARY]

    CREATE UNIQUE NONCLUSTERED INDEX [COMSCORE_PRECACHE_MARKET_UNIQUE] ON [dbo].[COMSCORE_PRECACHE_MARKET]
    (
	    [MARKET_CODE] ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
    
    ALTER TABLE [dbo].[COMSCORE_PRECACHE_MARKET]  WITH CHECK ADD  CONSTRAINT [FK_COMSCORE_PRECACHE_MARKET_MARKET] FOREIGN KEY([MARKET_CODE])
    REFERENCES [dbo].[MARKET] ([MARKET_CODE])

    ALTER TABLE [dbo].[COMSCORE_PRECACHE_MARKET] CHECK CONSTRAINT [FK_COMSCORE_PRECACHE_MARKET_MARKET]
END
GO
