IF NOT EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'MEDIA_SPOT_TV_PUERTO_RICO_RESEARCH_DEMO') BEGIN
    CREATE TABLE [dbo].[MEDIA_SPOT_TV_PUERTO_RICO_RESEARCH_DEMO](
	    [MEDIA_SPOT_TV_PUERTO_RICO_RESEARCH_DEMO_ID] [int] IDENTITY(1,1) NOT NULL,
	    [MEDIA_SPOT_TV_PUERTO_RICO_RESEARCH_ID] [int] NOT NULL,
	    [ORDER] [smallint] NOT NULL,
	    [MEDIA_DEMO_ID] [int] NOT NULL,
     CONSTRAINT [PK_MEDIA_SPOT_TV_PUERTO_RICO_RESEARCH_DEMO] PRIMARY KEY CLUSTERED 
    (
	    [MEDIA_SPOT_TV_PUERTO_RICO_RESEARCH_DEMO_ID] ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
    ) ON [PRIMARY]
    
    ALTER TABLE [dbo].[MEDIA_SPOT_TV_PUERTO_RICO_RESEARCH_DEMO]  WITH CHECK ADD  CONSTRAINT [FK_MEDIA_SPOT_TV_PUERTO_RICO_RESEARCH_DEMO_MEDIA_DEMO] FOREIGN KEY([MEDIA_DEMO_ID])
    REFERENCES [dbo].[MEDIA_DEMO] ([MEDIA_DEMO_ID])
    
    ALTER TABLE [dbo].[MEDIA_SPOT_TV_PUERTO_RICO_RESEARCH_DEMO] CHECK CONSTRAINT [FK_MEDIA_SPOT_TV_PUERTO_RICO_RESEARCH_DEMO_MEDIA_DEMO]
    
    ALTER TABLE [dbo].[MEDIA_SPOT_TV_PUERTO_RICO_RESEARCH_DEMO]  WITH CHECK ADD  CONSTRAINT [FK_MEDIA_SPOT_TV_PUERTO_RICO_RESEARCH_DEMO_MEDIA_SPOT_TV_PUERTO_RICO_RESEARCH] FOREIGN KEY([MEDIA_SPOT_TV_PUERTO_RICO_RESEARCH_ID])
    REFERENCES [dbo].[MEDIA_SPOT_TV_PUERTO_RICO_RESEARCH] ([MEDIA_SPOT_TV_PUERTO_RICO_RESEARCH_ID])
    
    ALTER TABLE [dbo].[MEDIA_SPOT_TV_PUERTO_RICO_RESEARCH_DEMO] CHECK CONSTRAINT [FK_MEDIA_SPOT_TV_PUERTO_RICO_RESEARCH_DEMO_MEDIA_SPOT_TV_PUERTO_RICO_RESEARCH]
END
   