IF NOT EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'NPR_UNIVERSE') BEGIN
    CREATE TABLE [dbo].[NPR_UNIVERSE] (
	    NPR_UNIVERSE_ID int IDENTITY(1,1) NOT NULL,
	    [DATE] [smalldatetime] NOT NULL,
	    HOMES_UE [int] NOT NULL,
	    PEOPLE_2PLUS_UE [int] NOT NULL,
	    MALES_2PLUS_UE [int] NOT NULL,
	    MALES_2TO5_UE [int] NOT NULL,
	    MALES_6TO11_UE [int] NOT NULL,
	    MALES_12TO14_UE [int] NOT NULL,
	    MALES_15TO17_UE [int] NOT NULL,
	    MALES_18TO20_UE [int] NOT NULL,
	    MALES_21TO24_UE [int] NOT NULL,
	    MALES_25TO34_UE [int] NOT NULL,
	    MALES_35TO44_UE [int] NOT NULL,
	    MALES_45TO49_UE [int] NOT NULL,
	    MALES_50TO54_UE [int] NOT NULL,
	    MALES_55TO64_UE [int] NOT NULL,
	    MALES_65PLUS_UE [int] NOT NULL,
	    FEMALES_2PLUS_UE [int] NOT NULL,
	    FEMALES_2TO5_UE [int] NOT NULL,
	    FEMALES_6TO11_UE [int] NOT NULL,
	    FEMALES_12TO14_UE [int] NOT NULL,
	    FEMALES_15TO17_UE [int] NOT NULL,
	    FEMALES_18TO20_UE [int] NOT NULL,
	    FEMALES_21TO24_UE [int] NOT NULL,
	    FEMALES_25TO34_UE [int] NOT NULL,
	    FEMALES_35TO44_UE [int] NOT NULL,
	    FEMALES_45TO49_UE [int] NOT NULL,
	    FEMALES_50TO54_UE [int] NOT NULL,
	    FEMALES_55TO64_UE [int] NOT NULL,
	    FEMALES_65PLUS_UE [int] NOT NULL,
	    WORKING_WOMEN_UE [int] NOT NULL,
     CONSTRAINT [PK_NPR_UNIVERSE] PRIMARY KEY CLUSTERED 
    (
	    [NPR_UNIVERSE_ID] ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
    ) ON [PRIMARY]
    CREATE NONCLUSTERED INDEX [NPR_UNIVERSE_DATE] ON [dbo].[NPR_UNIVERSE]
    (
	    [DATE] ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
END
GO
