IF NOT EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'VENUE') BEGIN

    CREATE TABLE [dbo].[VENUE](
	    [VENUE_CODE] [varchar](1) NOT NULL,
	    [DESCRIPTION] [varchar](20) NOT NULL,
	    [IS_INACTIVE] [bit] NOT NULL,
    CONSTRAINT [PK_VENUE] PRIMARY KEY CLUSTERED 
    (
	    [VENUE_CODE] ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
    ) ON [PRIMARY]

END
GO

IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'VENUE') BEGIN

    INSERT INTO [dbo].[VENUE]([VENUE_CODE], [DESCRIPTION], [IS_INACTIVE])
    VALUES('N', 'Network', 0)
    
    INSERT INTO [dbo].[VENUE]([VENUE_CODE], [DESCRIPTION], [IS_INACTIVE])
    VALUES('S', 'Syndication', 0)
    
    INSERT INTO [dbo].[VENUE]([VENUE_CODE], [DESCRIPTION], [IS_INACTIVE])
    VALUES('C', 'Cable', 0)
    
END
GO
