CREATE PROCEDURE [dbo].[advsp_nielsen_radio_county_get_periods]
	@CLIENT_CODE varchar(6)
AS 
BEGIN
	
	SELECT DISTINCT
		[NielsenRadioCountyPeriodID] = b.NIELSEN_RADIO_COUNTY_PERIOD_ID,
		[State] = b.[STATE],
		[Year] = b.[YEAR],
		[NielsenRadioMarketNumber] = b.NIELSEN_RADIO_MARKET_NUMBER 
	FROM dbo.NIELSEN_RADIO_COUNTY_PERIOD b
		INNER JOIN dbo.CLIENT_ORDER co ON b.[YEAR] = co.END_YEAR AND co.ALL_STATES = 0 AND co.IS_SUSPENDED = 0
		INNER JOIN dbo.CLIENT c ON co.CLIENT_ID = c.CLIENT_ID AND c.CODE = @CLIENT_CODE
		INNER JOIN dbo.CLIENT_ORDER_STATE com ON co.CLIENT_ORDER_ID = com.CLIENT_ORDER_ID AND com.[STATE] = b.[STATE]
		
	UNION

	SELECT
		[NielsenRadioCountyPeriodID] = b.NIELSEN_RADIO_COUNTY_PERIOD_ID,
		[State] = b.[STATE],
		[Year] = b.[YEAR],
		[NielsenRadioMarketNumber] = b.NIELSEN_RADIO_MARKET_NUMBER 
	FROM dbo.NIELSEN_RADIO_COUNTY_PERIOD b
		INNER JOIN dbo.CLIENT_ORDER co ON b.[YEAR] = co.END_YEAR AND co.ALL_STATES = 1 AND co.IS_SUSPENDED = 0
		INNER JOIN dbo.CLIENT c ON co.CLIENT_ID = c.CLIENT_ID AND c.CODE = @CLIENT_CODE
	
END
GO