CREATE PROC [dbo].[advsp_tranfer_nielsen_radio_station_to_hosted]
AS

BEGIN TRAN

SET IDENTITY_INSERT NIELSENHOSTED.dbo.NIELSEN_RADIO_STATION ON

INSERT INTO NIELSENHOSTED.dbo.NIELSEN_RADIO_STATION (NIELSEN_RADIO_STATION_ID, NIELSEN_RADIO_MARKET_NUMBER, COMBO_ID, NAME, CALL_LETTERS, BAND, 
	FREQUENCY, COMBO_TYPE, NIELSEN_RADIO_FORMAT_CODE, IS_SPILLIN, [SOURCE])
SELECT NIELSEN_RADIO_STATION_ID, NIELSEN_RADIO_MARKET_NUMBER, COMBO_ID, NAME, CALL_LETTERS, BAND, 
	FREQUENCY, COMBO_TYPE, NIELSEN_RADIO_FORMAT_CODE, IS_SPILLIN, [SOURCE]
FROM NIELSENDATASTORE.dbo.NIELSEN_RADIO_STATION
WHERE NIELSEN_RADIO_STATION_ID NOT IN (SELECT NIELSEN_RADIO_STATION_ID FROM NIELSENHOSTED.dbo.NIELSEN_RADIO_STATION)

SET IDENTITY_INSERT NIELSENHOSTED.dbo.NIELSEN_RADIO_STATION OFF

COMMIT TRAN

GO



