CREATE PROCEDURE [dbo].[advsp_hosted_spottv_get_fusion_ue_ids]
	@CLIENT_CODE varchar(6),
	@NIELSEN_MARKET_NUM int
AS
BEGIN

	SELECT DISTINCT
		[ID] = b.NCC_TV_FUSION_UE_ID
	FROM dbo.NCC_TV_FUSION_UE b
		INNER JOIN dbo.CLIENT_ORDER co ON b.[YEAR] BETWEEN co.START_YEAR AND co.END_YEAR AND co.ALL_MARKETS = 0 AND co.IS_SUSPENDED = 0
		INNER JOIN dbo.CLIENT_ORDER_MARKET com ON co.CLIENT_ORDER_ID = com.CLIENT_ORDER_ID AND com.MARKET_NUMBER = b.NIELSEN_MARKET_NUM
		INNER JOIN dbo.CLIENT c ON co.CLIENT_ID = c.CLIENT_ID AND c.CODE = @CLIENT_CODE AND c.IS_NCC_SUBSCRIBED = 1
	WHERE 
		((b.[YEAR] BETWEEN co.START_YEAR AND co.END_YEAR - 1 AND b.[MONTH] = 9 AND com.SEPTEMBER = 1)
	OR  (b.[YEAR] BETWEEN co.START_YEAR AND co.END_YEAR - 1 AND b.[MONTH] = 10 AND com.OCTOBER = 1)
	OR  (b.[YEAR] BETWEEN co.START_YEAR AND co.END_YEAR - 1 AND b.[MONTH] = 11 AND com.NOVEMBER = 1)
	OR  (b.[YEAR] BETWEEN co.START_YEAR AND co.END_YEAR - 1 AND b.[MONTH] = 12 AND com.DECEMBER = 1)
	OR	(b.[YEAR] BETWEEN co.START_YEAR + 1 AND co.END_YEAR AND b.[MONTH] = 1 AND com.JANUARY = 1)
	OR	(b.[YEAR] BETWEEN co.START_YEAR + 1 AND co.END_YEAR AND b.[MONTH] = 2 AND com.FEBRUARY = 1)
	OR	(b.[YEAR] BETWEEN co.START_YEAR + 1 AND co.END_YEAR AND b.[MONTH] = 3 AND com.MARCH = 1)
	OR	(b.[YEAR] BETWEEN co.START_YEAR + 1 AND co.END_YEAR AND b.[MONTH] = 4 AND com.APRIL = 1)
	OR	(b.[YEAR] BETWEEN co.START_YEAR + 1 AND co.END_YEAR AND b.[MONTH] = 5 AND com.MAY = 1)
	OR	(b.[YEAR] BETWEEN co.START_YEAR + 1 AND co.END_YEAR AND b.[MONTH] = 6 AND com.JUNE = 1)
	OR	(b.[YEAR] BETWEEN co.START_YEAR + 1 AND co.END_YEAR AND b.[MONTH] = 7 AND com.JULY = 1)
	OR	(b.[YEAR] BETWEEN co.START_YEAR + 1 AND co.END_YEAR AND b.[MONTH] = 8 AND com.AUGUST = 1))
	AND
		(
			(c.FUSION_DIARY_MARKETS = 1 AND EXISTS(SELECT 1 FROM dbo.NIELSEN_TV_BOOK ntb 
													WHERE ntb.NIELSEN_MARKET_NUM = b.NIELSEN_MARKET_NUM
													AND ntb.[MONTH] = b.[MONTH]
													AND ntb.[YEAR] = b.[YEAR]
													AND ntb.COLLECTION_METHOD NOT IN ('2','3')
													AND ntb.REPORTING_SERVICE = '1' AND ntb.EXCLUSION = '' AND ntb.ETHNICITY = ''))
		OR
			(c.FUSION_METERED_MARKETS = 1 AND EXISTS(SELECT 1 FROM dbo.NIELSEN_TV_BOOK ntb 
													WHERE ntb.NIELSEN_MARKET_NUM = b.NIELSEN_MARKET_NUM
													AND ntb.[MONTH] = b.[MONTH]
													AND ntb.[YEAR] = b.[YEAR]
													AND ntb.COLLECTION_METHOD IN ('2','3')
													AND ntb.REPORTING_SERVICE = '1' AND ntb.EXCLUSION = '' AND ntb.ETHNICITY = ''))
		)
	AND	b.NIELSEN_MARKET_NUM = @NIELSEN_MARKET_NUM 

	UNION

	SELECT
		[ID] = b.NCC_TV_FUSION_UE_ID
	FROM dbo.NCC_TV_FUSION_UE b
		INNER JOIN dbo.CLIENT_ORDER co ON b.[YEAR] BETWEEN co.START_YEAR AND co.END_YEAR AND co.ALL_MARKETS = 1 AND co.IS_SUSPENDED = 0
		INNER JOIN dbo.CLIENT c ON co.CLIENT_ID = c.CLIENT_ID AND c.CODE = @CLIENT_CODE AND c.IS_NCC_SUBSCRIBED = 1
	WHERE 
		((b.[YEAR] BETWEEN co.START_YEAR AND co.END_YEAR - 1 AND b.[MONTH] >= 9)
	OR	(b.[YEAR] BETWEEN co.START_YEAR + 1 AND co.END_YEAR AND b.[MONTH] <= 8))
	AND
		(
			(c.FUSION_DIARY_MARKETS = 1 AND EXISTS(SELECT 1 FROM dbo.NIELSEN_TV_BOOK ntb 
													WHERE ntb.NIELSEN_MARKET_NUM = b.NIELSEN_MARKET_NUM
													AND ntb.[MONTH] = b.[MONTH]
													AND ntb.[YEAR] = b.[YEAR]
													AND ntb.COLLECTION_METHOD NOT IN ('2','3')
													AND ntb.REPORTING_SERVICE = '1' AND ntb.EXCLUSION = '' AND ntb.ETHNICITY = ''))
		OR
			(c.FUSION_METERED_MARKETS = 1 AND EXISTS(SELECT 1 FROM dbo.NIELSEN_TV_BOOK ntb 
													WHERE ntb.NIELSEN_MARKET_NUM = b.NIELSEN_MARKET_NUM
													AND ntb.[MONTH] = b.[MONTH]
													AND ntb.[YEAR] = b.[YEAR]
													AND ntb.COLLECTION_METHOD IN ('2','3')
													AND ntb.REPORTING_SERVICE = '1' AND ntb.EXCLUSION = '' AND ntb.ETHNICITY = ''))
		)
	AND	b.NIELSEN_MARKET_NUM = @NIELSEN_MARKET_NUM 

END
GO

GRANT EXEC ON [advsp_hosted_spottv_get_fusion_ue_ids] TO PUBLIC
GO
