CREATE PROCEDURE [dbo].[advsp_nielsen_spot_tv_get_client_program_books]
	@CLIENT_CODE varchar(6)
AS 
BEGIN
	
	SELECT DISTINCT
		[NielsenTVProgramBookID] = b.NIELSEN_TV_PROGRAM_BOOK_ID,
		[NielsenMarketNumber] = b.NIELSEN_MARKET_NUM,
		[Year] = b.[YEAR],
		[Month] = b.[MONTH],
		[ReportingService] = b.REPORTING_SERVICE,
		[Exclusion] = b.EXCLUSION,
		[Ethnicity] = b.ETHNICITY
	FROM dbo.NIELSEN_TV_PROGRAM_BOOK b
		INNER JOIN dbo.CLIENT_ORDER co ON b.[YEAR] BETWEEN co.START_YEAR AND co.END_YEAR AND co.ALL_MARKETS = 0 AND co.IS_SUSPENDED = 0
		INNER JOIN dbo.CLIENT_ORDER_MARKET com ON co.CLIENT_ORDER_ID = com.CLIENT_ORDER_ID AND com.MARKET_NUMBER = b.NIELSEN_MARKET_NUM
		INNER JOIN dbo.CLIENT c ON co.CLIENT_ID = c.CLIENT_ID AND c.CODE = @CLIENT_CODE
	WHERE 
		(
			(b.[YEAR] BETWEEN co.START_YEAR AND co.END_YEAR - 1 AND b.[MONTH] = 9 AND com.SEPTEMBER = 1)
		OR  (b.[YEAR] BETWEEN co.START_YEAR AND co.END_YEAR - 1 AND b.[MONTH] = 10 AND com.OCTOBER = 1)
		OR  (b.[YEAR] BETWEEN co.START_YEAR AND co.END_YEAR - 1 AND b.[MONTH] = 11 AND com.NOVEMBER = 1)
		OR  (b.[YEAR] BETWEEN co.START_YEAR AND co.END_YEAR - 1 AND b.[MONTH] = 12 AND com.DECEMBER = 1)
		OR	(b.[YEAR] BETWEEN co.START_YEAR + 1 AND co.END_YEAR AND b.[MONTH] = 1 AND com.JANUARY = 1)
		OR	(b.[YEAR] BETWEEN co.START_YEAR + 1 AND co.END_YEAR AND b.[MONTH] = 2 AND com.FEBRUARY = 1)
		OR	(b.[YEAR] BETWEEN co.START_YEAR + 1 AND co.END_YEAR AND b.[MONTH] = 3 AND com.MARCH = 1)
		OR	(b.[YEAR] BETWEEN co.START_YEAR + 1 AND co.END_YEAR AND b.[MONTH] = 4 AND com.APRIL = 1)
		OR	(b.[YEAR] BETWEEN co.START_YEAR + 1 AND co.END_YEAR AND b.[MONTH] = 5 AND com.MAY = 1)
		OR	(b.[YEAR] BETWEEN co.START_YEAR + 1 AND co.END_YEAR AND b.[MONTH] = 6 AND com.JUNE = 1)
		OR	(b.[YEAR] BETWEEN co.START_YEAR + 1 AND co.END_YEAR AND b.[MONTH] = 7 AND com.JULY = 1)
		OR	(b.[YEAR] BETWEEN co.START_YEAR + 1 AND co.END_YEAR AND b.[MONTH] = 8 AND com.AUGUST = 1)
		)
	AND (
			(UPPER(b.ETHNICITY) = '' AND co.ETHNICITY = 0)
		OR	(UPPER(b.ETHNICITY) = 'HISP' AND co.ETHNICITY = 1)
		OR	(UPPER(b.ETHNICITY) = 'AF-AM' AND co.ETHNICITY = 2)
		OR	(UPPER(b.ETHNICITY) = 'ASIAN' AND co.ETHNICITY = 3)
		)
	AND (
			(UPPER(b.EXCLUSION) = '' AND co.IS_OLYMPIC = 0)
		OR	(UPPER(b.EXCLUSION) = 'EX' AND co.IS_OLYMPIC = 1)
		)

	UNION

	SELECT
		[NielsenTVProgramBookID] = b.NIELSEN_TV_PROGRAM_BOOK_ID,
		[NielsenMarketNumber] = b.NIELSEN_MARKET_NUM,
		[Year] = b.[YEAR],
		[Month] = b.[MONTH],
		[ReportingService] = b.REPORTING_SERVICE,
		[Exclusion] = b.EXCLUSION,
		[Ethnicity] = b.ETHNICITY
	FROM dbo.NIELSEN_TV_PROGRAM_BOOK b
		INNER JOIN dbo.CLIENT_ORDER co ON b.[YEAR] BETWEEN co.START_YEAR AND co.END_YEAR AND co.ALL_MARKETS = 1 AND co.IS_SUSPENDED = 0
		INNER JOIN dbo.CLIENT c ON co.CLIENT_ID = c.CLIENT_ID AND c.CODE = @CLIENT_CODE
	WHERE 
		(
			(b.[YEAR] BETWEEN co.START_YEAR AND co.END_YEAR - 1 AND b.[MONTH] >= 9)
		OR	(b.[YEAR] BETWEEN co.START_YEAR + 1 AND co.END_YEAR AND b.[MONTH] <= 8)
		)
	AND (
			(UPPER(b.ETHNICITY) = '' AND co.ETHNICITY = 0)
		OR	(UPPER(b.ETHNICITY) = 'HISP' AND co.ETHNICITY = 1)
		OR	(UPPER(b.ETHNICITY) = 'AF-AM' AND co.ETHNICITY = 2)
		OR	(UPPER(b.ETHNICITY) = 'ASIAN' AND co.ETHNICITY = 3)
		)
	AND (
			(UPPER(b.EXCLUSION) = '' AND co.IS_OLYMPIC = 0)
		OR	(UPPER(b.EXCLUSION) = 'EX' AND co.IS_OLYMPIC = 1)
		)
	
END
GO

GRANT EXEC ON [advsp_nielsen_spot_tv_get_client_program_books] TO PUBLIC
GO