CREATE PROC [dbo].[advsp_tranfer_nielsen_radio_period_to_hosted]
AS

BEGIN TRAN

SET IDENTITY_INSERT NIELSENHOSTED.dbo.NIELSEN_RADIO_PERIOD ON

INSERT INTO NIELSENHOSTED.dbo.NIELSEN_RADIO_PERIOD (NIELSEN_RADIO_PERIOD_ID, NIELSEN_RADIO_REPORT_TYPE_CODE, NIELSEN_PERIOD_ID, NIELSEN_RADIO_MARKET_NUMBER, SHORT_NAME, [NAME], [START_DATE], END_DATE, STANDARD_CONDENSED_INDICATOR, VALIDATED, COPYRIGHT, [SOURCE])
SELECT NIELSEN_RADIO_PERIOD_ID, NIELSEN_RADIO_REPORT_TYPE_CODE, NIELSEN_PERIOD_ID, NIELSEN_RADIO_MARKET_NUMBER, SHORT_NAME, [NAME], [START_DATE], END_DATE, STANDARD_CONDENSED_INDICATOR, VALIDATED, COPYRIGHT, [SOURCE]
FROM NIELSENDATASTORE.dbo.NIELSEN_RADIO_PERIOD
WHERE NIELSEN_RADIO_PERIOD_ID NOT IN (SELECT NIELSEN_RADIO_PERIOD_ID FROM NIELSENHOSTED.dbo.NIELSEN_RADIO_PERIOD)

SET IDENTITY_INSERT NIELSENHOSTED.dbo.NIELSEN_RADIO_PERIOD OFF

COMMIT TRAN

GO
