CREATE PROCEDURE advsp_neilsen_radio_period_delete
	@NIELSEN_RADIO_PERIOD_ID int
AS

SELECT NIELSEN_RADIO_SEGMENT_PARENT_ID
FROM dbo.NIELSEN_RADIO_SEGMENT_PARENT
WHERE NIELSEN_RADIO_PERIOD_ID = @NIELSEN_RADIO_PERIOD_ID

DELETE dbo.NIELSEN_RADIO_AUDIENCE 
WHERE NIELSEN_RADIO_SEGMENT_PARENT_ID IN (
	SELECT NIELSEN_RADIO_SEGMENT_PARENT_ID
	FROM dbo.NIELSEN_RADIO_SEGMENT_PARENT
	WHERE NIELSEN_RADIO_PERIOD_ID = @NIELSEN_RADIO_PERIOD_ID)

DELETE dbo.NIELSEN_RADIO_INTAB
WHERE NIELSEN_RADIO_SEGMENT_PARENT_ID IN (
	SELECT NIELSEN_RADIO_SEGMENT_PARENT_ID
	FROM dbo.NIELSEN_RADIO_SEGMENT_PARENT
	WHERE NIELSEN_RADIO_PERIOD_ID = @NIELSEN_RADIO_PERIOD_ID)
	
DELETE dbo.NIELSEN_RADIO_PUR
WHERE NIELSEN_RADIO_SEGMENT_PARENT_ID IN (
	SELECT NIELSEN_RADIO_SEGMENT_PARENT_ID
	FROM dbo.NIELSEN_RADIO_SEGMENT_PARENT
	WHERE NIELSEN_RADIO_PERIOD_ID = @NIELSEN_RADIO_PERIOD_ID)
	
DELETE dbo.NIELSEN_RADIO_UNIVERSE
WHERE NIELSEN_RADIO_SEGMENT_PARENT_ID IN (
	SELECT NIELSEN_RADIO_SEGMENT_PARENT_ID
	FROM dbo.NIELSEN_RADIO_SEGMENT_PARENT
	WHERE NIELSEN_RADIO_PERIOD_ID = @NIELSEN_RADIO_PERIOD_ID)

DELETE dbo.NIELSEN_RADIO_SEGMENT_PARENT
WHERE NIELSEN_RADIO_PERIOD_ID = @NIELSEN_RADIO_PERIOD_ID

DELETE dbo.NIELSEN_RADIO_PERIOD
WHERE NIELSEN_RADIO_PERIOD_ID = @NIELSEN_RADIO_PERIOD_ID
GO

GRANT EXEC ON advsp_neilsen_radio_period_delete TO PUBLIC
GO