CREATE PROC [dbo].[advsp_tranfer_nielsen_radio_county_universe_to_hosted]
AS

BEGIN TRAN

SET IDENTITY_INSERT NIELSENHOSTED.dbo.NIELSEN_RADIO_COUNTY_UNIVERSE ON

INSERT INTO NIELSENHOSTED.dbo.NIELSEN_RADIO_COUNTY_UNIVERSE ( NIELSEN_RADIO_COUNTY_UNIVERSE_ID, NIELSEN_RADIO_COUNTY_PERIOD_ID,
PERSONS_12PLUS_UE, PERSONS_12TO34_UE, PERSONS_18PLUS_UE, PERSONS_18TO34_UE, PERSONS_25TO54_UE, PERSONS_35PLUS_UE, PERSONS_35TO64_UE, MALES_18PLUS_UE, FEMALES_18PLUS_UE )
SELECT NIELSEN_RADIO_COUNTY_UNIVERSE_ID, NIELSEN_RADIO_COUNTY_PERIOD_ID,
PERSONS_12PLUS_UE, PERSONS_12TO34_UE, PERSONS_18PLUS_UE, PERSONS_18TO34_UE, PERSONS_25TO54_UE, PERSONS_35PLUS_UE, PERSONS_35TO64_UE, MALES_18PLUS_UE, FEMALES_18PLUS_UE
FROM NIELSENDATASTORE.dbo.NIELSEN_RADIO_COUNTY_UNIVERSE
WHERE NIELSEN_RADIO_COUNTY_UNIVERSE_ID NOT IN (SELECT NIELSEN_RADIO_COUNTY_UNIVERSE_ID FROM NIELSENHOSTED.dbo.NIELSEN_RADIO_COUNTY_UNIVERSE)

SET IDENTITY_INSERT NIELSENHOSTED.dbo.NIELSEN_RADIO_COUNTY_UNIVERSE OFF

COMMIT TRAN

GO
