CREATE PROCEDURE [dbo].[advsp_hosted_spottv_delete_program_reissues]

AS
BEGIN

	DECLARE @NIELSEN_TV_PROGRAM_BOOK_ID int,
			@ROWCOUNT int,
			@ROW_ID int

	DECLARE @BOOK_DELETE TABLE (
		ID							int IDENTITY (1, 1) NOT NULL,
		NIELSEN_TV_PROGRAM_BOOK_ID	int NOT NULL
	)

	INSERT INTO @BOOK_DELETE (NIELSEN_TV_PROGRAM_BOOK_ID)
	SELECT OLD_NIELSEN_TV_PROGRAM_BOOK_ID 
	FROM NIELSENDATASTORE.dbo.NIELSEN_TV_PROGRAM_BOOK_REVISION 

	SELECT @ROWCOUNT = COUNT(1) FROM @BOOK_DELETE 
	SELECT @ROW_ID = MIN(ID) FROM @BOOK_DELETE 

	IF @ROWCOUNT > 0 BEGIN

		WHILE @ROW_ID <= @ROWCOUNT
		BEGIN

			SELECT @NIELSEN_TV_PROGRAM_BOOK_ID = NIELSEN_TV_PROGRAM_BOOK_ID
			FROM @BOOK_DELETE 
			WHERE ID = @ROW_ID 
			
			DELETE NIELSENHOSTED.dbo.NIELSEN_TV_PROGRAM WHERE NIELSEN_TV_PROGRAM_BOOK_ID = @NIELSEN_TV_PROGRAM_BOOK_ID
			DELETE NIELSENHOSTED.dbo.NIELSEN_TV_PROGRAM_BOOK WHERE NIELSEN_TV_PROGRAM_BOOK_ID = @NIELSEN_TV_PROGRAM_BOOK_ID
			
			SET @ROW_ID = @ROW_ID + 1

		END

	END
END
GO

GRANT EXEC ON [advsp_hosted_spottv_delete_program_reissues] TO PUBLIC
GO