CREATE PROC [dbo].[advsp_tranfer_nielsen_radio_county_cluster_to_hosted]
AS

BEGIN TRAN

SET IDENTITY_INSERT NIELSENHOSTED.dbo.NIELSEN_RADIO_COUNTY_CLUSTER ON

INSERT INTO NIELSENHOSTED.dbo.NIELSEN_RADIO_COUNTY_CLUSTER ( NIELSEN_RADIO_COUNTY_CLUSTER_ID,
NIELSEN_RADIO_COUNTY_PERIOD_ID, COUNTY_CODE_WITHIN_CLUSTER, NAME, POP_12PLUS, [STATE], CLUSTER_MEASUREMENT_TYPE )
SELECT NIELSEN_RADIO_COUNTY_CLUSTER_ID,
NIELSEN_RADIO_COUNTY_PERIOD_ID, COUNTY_CODE_WITHIN_CLUSTER, NAME, POP_12PLUS, [STATE], CLUSTER_MEASUREMENT_TYPE
FROM NIELSENDATASTORE.dbo.NIELSEN_RADIO_COUNTY_CLUSTER
WHERE NIELSEN_RADIO_COUNTY_CLUSTER_ID NOT IN (SELECT NIELSEN_RADIO_COUNTY_CLUSTER_ID FROM NIELSENHOSTED.dbo.NIELSEN_RADIO_COUNTY_CLUSTER)

SET IDENTITY_INSERT NIELSENHOSTED.dbo.NIELSEN_RADIO_COUNTY_CLUSTER OFF

COMMIT TRAN

GO
