CREATE PROCEDURE [dbo].[advsp_hosted_spotradio_get_market_numbers]
	@CLIENT_CODE varchar(6)
AS
BEGIN
	SELECT DISTINCT com.MARKET_NUMBER
	FROM dbo.CLIENT c
		INNER JOIN dbo.CLIENT_ORDER co ON c.CLIENT_ID = co.CLIENT_ID AND co.IS_SUSPENDED = 0 AND co.ALL_MARKETS = 0
		INNER JOIN dbo.CLIENT_ORDER_MARKET com ON co.CLIENT_ORDER_ID = com.CLIENT_ORDER_ID
	WHERE co.ORDER_TYPE = 'R'
	AND c.CODE = @CLIENT_CODE
	
	UNION

	SELECT NUMBER 
	FROM dbo.NIELSEN_RADIO_MARKET 
	WHERE EXISTS (
		SELECT 1
		FROM dbo.CLIENT c
				INNER JOIN dbo.CLIENT_ORDER co ON c.CLIENT_ID = co.CLIENT_ID AND co.IS_SUSPENDED = 0 AND co.ALL_MARKETS = 1
		WHERE co.ORDER_TYPE = 'R'
		AND c.CODE = @CLIENT_CODE)
END
GO

GRANT EXEC ON [advsp_hosted_spotradio_get_market_numbers] TO PUBLIC
GO