'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DesktopCardsMyAssignments
    
    '''<summary>
    '''UpdatePanelDO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelDO As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''LabelTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelTitle As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DivSortOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivSortOptions As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''RadComboBoxSortOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadComboBoxSortOptions As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''ImageButtonRefreshDesktopCardsMyAssignments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonRefreshDesktopCardsMyAssignments As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ImageButtonSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonSettings As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''RadListViewAlertAssignmentsDirty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadListViewAlertAssignmentsDirty As Global.Telerik.Web.UI.RadListView
    
    '''<summary>
    '''RadDataPagerAlertAssignments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDataPagerAlertAssignments As Global.Telerik.Web.UI.RadDataPager
    
    '''<summary>
    '''HiddenFieldRecordCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenFieldRecordCount As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''MyUnityContextMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MyUnityContextMenu As Global.Webvantage.UnityUC
    
    '''<summary>
    '''RadScriptBlockFooter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptBlockFooter As Global.Telerik.Web.UI.RadScriptBlock
End Class
