'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DesktopInOutBoard
    
    '''<summary>
    '''UserControlInOutBoard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UserControlInOutBoard As Global.Webvantage.InOutBoard
    
    '''<summary>
    '''ddGroupBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddGroupBy As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''butRefresh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents butRefresh As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ImageButtonBookmark control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonBookmark As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''InOutRadGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InOutRadGrid As Global.Telerik.Web.UI.RadGrid
End Class
