CREATE FUNCTION [dbo].[advfn_nielsen_spot_radio_rowcount](
	@NIELSEN_RADIO_PERIOD_ID int
)
RETURNS bigint
WITH SCHEMABINDING
AS
BEGIN

	DECLARE @totalrows bigint

	SELECT @totalrows = COALESCE(COUNT(1), 0) 
	FROM dbo.NIELSEN_RADIO_SEGMENT_PARENT 
	WHERE NIELSEN_RADIO_PERIOD_ID = @NIELSEN_RADIO_PERIOD_ID

	SELECT @totalrows = @totalrows + COALESCE(COUNT(1), 0)
	FROM dbo.NIELSEN_RADIO_AUDIENCE a
		INNER JOIN dbo.NIELSEN_RADIO_SEGMENT_PARENT p ON a.NIELSEN_RADIO_SEGMENT_PARENT_ID = p.NIELSEN_RADIO_SEGMENT_PARENT_ID AND p.NIELSEN_RADIO_PERIOD_ID = @NIELSEN_RADIO_PERIOD_ID
	
	SELECT @totalrows = @totalrows + COALESCE(COUNT(1), 0)
	FROM dbo.NIELSEN_RADIO_INTAB i
		INNER JOIN dbo.NIELSEN_RADIO_SEGMENT_PARENT p ON i.NIELSEN_RADIO_SEGMENT_PARENT_ID = p.NIELSEN_RADIO_SEGMENT_PARENT_ID AND p.NIELSEN_RADIO_PERIOD_ID = @NIELSEN_RADIO_PERIOD_ID 
	
	SELECT @totalrows = @totalrows + COALESCE(COUNT(1), 0)
	FROM dbo.NIELSEN_RADIO_PUR i
		INNER JOIN dbo.NIELSEN_RADIO_SEGMENT_PARENT p ON i.NIELSEN_RADIO_SEGMENT_PARENT_ID = p.NIELSEN_RADIO_SEGMENT_PARENT_ID AND p.NIELSEN_RADIO_PERIOD_ID = @NIELSEN_RADIO_PERIOD_ID
	
	SELECT @totalrows = @totalrows + COALESCE(COUNT(1), 0)
	FROM dbo.NIELSEN_RADIO_UNIVERSE i
		INNER JOIN dbo.NIELSEN_RADIO_SEGMENT_PARENT p ON i.NIELSEN_RADIO_SEGMENT_PARENT_ID = p.NIELSEN_RADIO_SEGMENT_PARENT_ID AND p.NIELSEN_RADIO_PERIOD_ID = @NIELSEN_RADIO_PERIOD_ID
	
	SELECT @totalrows = @totalrows + COALESCE(COUNT(1), 0)
	FROM dbo.NIELSEN_RADIO_SEGMENT_CHILD 

	RETURN @totalrows
END
GO

GRANT EXEC ON [advfn_nielsen_spot_radio_rowcount] TO PUBLIC
GO
