CREATE FUNCTION [dbo].[advtf_nielsen_tv_cume_impressions](
	@NIELSEN_MARKET_NUM int,
	@BookIDs varchar(MAX),
	@MEDIA_DEMO_TYPE dbo.MEDIA_DEMO_TYPE READONLY, 
	@MEDIA_DEMO_DETAIL_TYPE [dbo].[MEDIA_DEMO_DETAIL_TYPE] READONLY,
	@StationCodes varchar(max),
	@MEDIA_SPOT_TV_RESEARCH_DAYTIME_TYPE dbo.MEDIA_SPOT_TV_RESEARCH_DAYTIME_TYPE READONLY
)
RETURNS
@RETURN_TABLE TABLE (
	--[NIELSEN_DEMO_CODE] varchar(7) NOT NULL,
	[CUME_IMPRESSIONS] bigint NOT NULL,
	MEDIA_DEMO_ID int NOT NULL,
	--NIELSEN_DEMO_ID int NOT NULL,
	STATION_CODE int NOT NULL,
	NIELSEN_TV_BOOK_ID int NOT NULL,
	[ID] int NOT NULL
)
WITH SCHEMABINDING
AS
BEGIN

	DECLARE @TIME_ZONE char(1),
			@IS50005000match bit,
			@IS50009230match bit,
			@START_HOUR_5000 smallint,
			@END_HOUR_5000 smallint,
			@LOCAL_MEDIA_SPOT_TV_RESEARCH_DAYTIME_TYPE dbo.MEDIA_SPOT_TV_RESEARCH_DAYTIME_TYPE
	
	INSERT INTO @LOCAL_MEDIA_SPOT_TV_RESEARCH_DAYTIME_TYPE (ID, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday, StartTime, EndTime, StartHour, EndHour, [Days])
	SELECT ID, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday, StartTime, EndTime, StartHour, EndHour, [Days]
	FROM @MEDIA_SPOT_TV_RESEARCH_DAYTIME_TYPE

	UPDATE @LOCAL_MEDIA_SPOT_TV_RESEARCH_DAYTIME_TYPE SET EndHour = EndHour + 1
	WHERE StartHour = EndHour

	SET @IS50005000match = 0
	SET @IS50009230match = 0

	SELECT TOP 1
		@TIME_ZONE = CASE WHEN ISNULL(NTCB.MARKET_TIME_ZONE, 0) = 1 OR ISNULL(NTCB.MARKET_TIME_ZONE, 0) = 4 THEN 'E' ELSE 'C' END
	FROM 
		dbo.NIELSEN_TV_CUME_BOOK NTCB
	WHERE 
		NTCB.NIELSEN_MARKET_NUM = @NIELSEN_MARKET_NUM
	
	IF EXISTS(SELECT 1
				FROM @LOCAL_MEDIA_SPOT_TV_RESEARCH_DAYTIME_TYPE MRDT
				WHERE @TIME_ZONE = 'E' 
				AND	(MRDT.Saturday = 1 OR MRDT.Sunday = 1) 
				AND	(
						(MRDT.StartHour BETWEEN 2000 AND 2300)
					AND
						(MRDT.EndHour BETWEEN 2000 AND 2300)
					)
				) BEGIN
		SET @IS50005000match = 1
		SET @START_HOUR_5000 = 2000
		SET @END_HOUR_5000 = 2300
	END ELSE IF EXISTS(SELECT 1
					FROM @LOCAL_MEDIA_SPOT_TV_RESEARCH_DAYTIME_TYPE MRDT
					WHERE @TIME_ZONE = 'E' 
					AND	(MRDT.Sunday = 1) 
					AND	(
							(MRDT.StartHour BETWEEN 1900 AND 2300)
						AND
							(MRDT.EndHour BETWEEN 1900 AND 2300)
						)
					) BEGIN
		SET @IS50005000match = 1
		SET @START_HOUR_5000 = 1900
		SET @END_HOUR_5000 = 2300
	END ELSE IF EXISTS(SELECT 1
					FROM @LOCAL_MEDIA_SPOT_TV_RESEARCH_DAYTIME_TYPE MRDT
					WHERE @TIME_ZONE = 'C' 
					AND	(MRDT.Saturday = 1 OR MRDT.Sunday = 1) 
					AND	(
							(MRDT.StartHour BETWEEN 1900 AND 2200)
						AND
							(MRDT.EndHour BETWEEN 1900 AND 2200)
						)
					) BEGIN
		SET @IS50005000match = 1
		SET @START_HOUR_5000 = 1900
		SET @END_HOUR_5000 = 2200
	END ELSE IF EXISTS(SELECT 1
					FROM @LOCAL_MEDIA_SPOT_TV_RESEARCH_DAYTIME_TYPE MRDT
					WHERE @TIME_ZONE = 'C' 
					AND	(MRDT.Sunday = 1) 
					AND	(
							(MRDT.StartHour BETWEEN 1800 AND 2200)
						AND
							(MRDT.EndHour BETWEEN 1800 AND 2200)
						)
					) BEGIN
		SET @IS50005000match = 1
		SET @START_HOUR_5000 = 1800
		SET @END_HOUR_5000 = 2200
	END
	
	IF EXISTS(SELECT 1
				FROM @LOCAL_MEDIA_SPOT_TV_RESEARCH_DAYTIME_TYPE MRDT
				WHERE
					(
						(MRDT.StartHour BETWEEN 300 AND 500)
					AND
						(MRDT.EndHour BETWEEN 300 AND 500)
					)
				OR
					(
						(MRDT.StartHour BETWEEN 200 AND 300)
					OR
						(MRDT.EndHour BETWEEN 200 AND 300)
					)
				) BEGIN
		SET @IS50009230match = 1
	END
	
	DECLARE @tt TABLE (
		[hh] decimal(21,2) NOT NULL,
		[c2-5] decimal(21,2) NOT NULL,
		[c6-11] decimal(21,2) NOT NULL,
		[m12-14] decimal(21,2) NOT NULL,
		[m15-17] decimal(21,2) NOT NULL,
		[m18-20] decimal(21,2) NOT NULL,
		[m21-24] decimal(21,2) NOT NULL,
		[m25-34] decimal(21,2) NOT NULL,
		[m35-49] decimal(21,2) NOT NULL,
		[m50-54] decimal(21,2) NOT NULL,
		[m55-64] decimal(21,2) NOT NULL,
		[m65P] decimal(21,2) NOT NULL,
		[f12-14] decimal(21,2) NOT NULL,
		[f15-17] decimal(21,2) NOT NULL,
		[f18-20] decimal(21,2) NOT NULL,
		[f21-24] decimal(21,2) NOT NULL,
		[f25-34] decimal(21,2) NOT NULL,
		[f35-49] decimal(21,2) NOT NULL,
		[f50-54] decimal(21,2) NOT NULL,
		[f55-64] decimal(21,2) NOT NULL,
		[f65P] decimal(21,2) NOT NULL,
		[ww] decimal(21,2) NOT NULL,
		[NIELSEN_TV_BOOK_ID] int NOT NULL,
		[NIELSEN_DAYPART_ID] int NOT NULL,
		[STATION_CODE] int NOT NULL,
		[ID] int NOT NULL,
		[NUMBER_QUARTER_HOURS] int NOT NULL,
		[REQUEST_NUM_QHRS] int NOT NULL
	)
	
	DECLARE @ttTEMP TABLE (
		[hh] decimal(21,2) NOT NULL,
		[c2-5] decimal(21,2) NOT NULL,
		[c6-11] decimal(21,2) NOT NULL,
		[m12-14] decimal(21,2) NOT NULL,
		[m15-17] decimal(21,2) NOT NULL,
		[m18-20] decimal(21,2) NOT NULL,
		[m21-24] decimal(21,2) NOT NULL,
		[m25-34] decimal(21,2) NOT NULL,
		[m35-49] decimal(21,2) NOT NULL,
		[m50-54] decimal(21,2) NOT NULL,
		[m55-64] decimal(21,2) NOT NULL,
		[m65P] decimal(21,2) NOT NULL,
		[f12-14] decimal(21,2) NOT NULL,
		[f15-17] decimal(21,2) NOT NULL,
		[f18-20] decimal(21,2) NOT NULL,
		[f21-24] decimal(21,2) NOT NULL,
		[f25-34] decimal(21,2) NOT NULL,
		[f35-49] decimal(21,2) NOT NULL,
		[f50-54] decimal(21,2) NOT NULL,
		[f55-64] decimal(21,2) NOT NULL,
		[f65P] decimal(21,2) NOT NULL,
		[ww] decimal(21,2) NOT NULL,
		[NIELSEN_TV_BOOK_ID] int NOT NULL,
		[NIELSEN_DAYPART_ID] int NOT NULL,
		[STATION_CODE] int NOT NULL,
		[ID] int NOT NULL,
		[NUMBER_QUARTER_HOURS] int NOT NULL,
		[REQUEST_NUM_QHRS] int NOT NULL
	)

	DECLARE @NIELSEN_TV_BOOKS TABLE (
		[NIELSEN_TV_BOOK_ID] int NOT NULL,
		[NIELSEN_MARKET_NUM] int NOT NULL,
		[MONTH] int NOT NULL,
		[YEAR] int NOT NULL
	)
	
	INSERT INTO @NIELSEN_TV_BOOKS([NIELSEN_TV_BOOK_ID], [NIELSEN_MARKET_NUM], [MONTH], [YEAR])
	SELECT 
		NTB.[NIELSEN_TV_BOOK_ID], NTB.[NIELSEN_MARKET_NUM], NTB.[MONTH], NTB.[YEAR]
	FROM
		dbo.NIELSEN_TV_BOOK AS NTB
	WHERE 
		NTB.NIELSEN_MARKET_NUM = @NIELSEN_MARKET_NUM
		AND NTB.NIELSEN_TV_BOOK_ID IN (SELECT items FROM dbo.udf_split_list_int(@BookIDs, ','))
				
	INSERT INTO @tt
	SELECT
		[hh] = NTCDI.HOUSEHOLD,
		[c2-5] = NTCDI.CHILDREN_2TO5,
		[c6-11] = NTCDI.CHILDREN_6TO11,
		[m12-14] = NTCDI.MALES_12TO14,
		[m15-17] = NTCDI.MALES_15TO17,
		[m18-20] = NTCDI.MALES_18TO20,
		[m21-24] = NTCDI.MALES_21TO24,
		[m25-34] = NTCDI.MALES_25TO34,
		[m35-49] = NTCDI.MALES_35TO49,
		[m50-54] = NTCDI.MALES_50TO54,
		[m55-64] = NTCDI.MALES_55TO64,
		[m65P] = NTCDI.MALES_65PLUS,
		[f12-14] = NTCDI.FEMALES_12TO14,
		[f15-17] = NTCDI.FEMALES_15TO17,
		[f18-20] = NTCDI.FEMALES_18TO20,
		[f21-24] = NTCDI.FEMALES_21TO24,
		[f25-34] = NTCDI.FEMALES_25TO34,
		[f35-49] = NTCDI.FEMALES_35TO49,
		[f50-54] = NTCDI.FEMALES_50TO54,
		[f55-64] = NTCDI.FEMALES_55TO64,
		[f65P] = NTCDI.FEMALES_65PLUS,
		[ww] = NTCDI.WORKING_WOMEN,
		NTB.NIELSEN_TV_BOOK_ID,
		NTD.NIELSEN_DAYPART_ID,
		NTCDI.STATION_CODE,
		MRDT.ID,
		NTD.NUMBER_QUARTER_HOURS * (CAST(NTD.MONDAY as int) + CAST(NTD.TUESDAY as int) + CAST(NTD.WEDNESDAY as int) + CAST(NTD.THURSDAY as int) + CAST(NTD.FRIDAY as int) + CAST(NTD.SATURDAY as int) + CAST(NTD.SUNDAY as int)),
		NumDays * NumHours
	FROM 
		dbo.NIELSEN_TV_CUME_DAYPART_IMPRESSION AS NTCDI
		INNER JOIN dbo.NIELSEN_TV_DAYPART AS NTD ON NTD.NIELSEN_TV_DAYPART_ID = NTCDI.NIELSEN_TV_DAYPART_ID
		INNER JOIN dbo.NIELSEN_TV_CUME_BOOK AS NTCB ON NTCB.NIELSEN_TV_CUME_BOOK_ID = NTCDI.NIELSEN_TV_CUME_BOOK_ID 
		INNER JOIN @NIELSEN_TV_BOOKS AS NTB ON NTB.NIELSEN_MARKET_NUM = NTCB.NIELSEN_MARKET_NUM
												AND NTB.[MONTH] = NTCB.[MONTH] 
												AND NTB.[YEAR] = NTCB.[YEAR] 
		INNER JOIN (SELECT 
						ID,
						StartHour,
						EndHour, 
						Sunday,
						Monday,
						Tuesday, 
						Wednesday,
						Thursday,
						Friday,
						Saturday,
						MonFri = CASE WHEN Monday=1 OR Tuesday=1 OR Wednesday=1 OR Thursday=1 OR Friday=1 THEN 1 ELSE 0 END,
						NumDays = CAST(Monday as int) + CAST(Tuesday as int) + CAST(Wednesday as int) + CAST(Thursday as int) + CAST(Friday as int) + CAST(Saturday as int) + CAST(Sunday as int),
						NumHours = dbo.advfn_calculate_num_quarter_hours(StartHour, EndHour)
					FROM 
						@LOCAL_MEDIA_SPOT_TV_RESEARCH_DAYTIME_TYPE) MRDT ON MRDT.ID > 0
	WHERE 
		NTCB.NIELSEN_MARKET_NUM = @NIELSEN_MARKET_NUM
		AND NTCB.VALIDATED = 1
		AND NTCDI.STATION_CODE IN (SELECT items FROM dbo.udf_split_list_int(@StationCodes, ','))
		AND NTD.TIME_ZONE = @TIME_ZONE 
		--AND (1 = CASE WHEN @NIELSEN_MARKET_NUM = 128 OR @NIELSEN_MARKET_NUM = 403 THEN 1 ELSE CASE WHEN NTD.IS_HISPANIC = 0 THEN 1 ELSE 0 END END)
		AND NTD.MIL_START_TIME = MRDT.StartHour 
		AND NTD.MIL_END_TIME = MRDT.EndHour 
		AND NTD.SATURDAY = MRDT.Saturday
		AND NTD.SUNDAY = MRDT.Sunday
		AND NTD.MONDAY = MRDT.MonFri			
	

	INSERT INTO @tt 
	SELECT
		[hh] = NTCDI.HOUSEHOLD,
		[c2-5] = NTCDI.CHILDREN_2TO5,
		[c6-11] = NTCDI.CHILDREN_6TO11,
		[m12-14] = NTCDI.MALES_12TO14,
		[m15-17] = NTCDI.MALES_15TO17,
		[m18-20] = NTCDI.MALES_18TO20,
		[m21-24] = NTCDI.MALES_21TO24,
		[m25-34] = NTCDI.MALES_25TO34,
		[m35-49] = NTCDI.MALES_35TO49,
		[m50-54] = NTCDI.MALES_50TO54,
		[m55-64] = NTCDI.MALES_55TO64,
		[m65P] = NTCDI.MALES_65PLUS,
		[f12-14] = NTCDI.FEMALES_12TO14,
		[f15-17] = NTCDI.FEMALES_15TO17,
		[f18-20] = NTCDI.FEMALES_18TO20,
		[f21-24] = NTCDI.FEMALES_21TO24,
		[f25-34] = NTCDI.FEMALES_25TO34,
		[f35-49] = NTCDI.FEMALES_35TO49,
		[f50-54] = NTCDI.FEMALES_50TO54,
		[f55-64] = NTCDI.FEMALES_55TO64,
		[f65P] = NTCDI.FEMALES_65PLUS,
		[ww] = NTCDI.WORKING_WOMEN,
		NTB.NIELSEN_TV_BOOK_ID,
		NTD.NIELSEN_DAYPART_ID,
		NTCDI.STATION_CODE,
		MRDT.ID,
		CASE WHEN NTD.NIELSEN_DAYPART_ID = 50005000 AND @IS50005000match = 1 THEN 616  -- (88 qtr hrs * 7 days)
		ELSE
			NTD.NUMBER_QUARTER_HOURS * (CAST(NTD.MONDAY as int) + CAST(NTD.TUESDAY as int) + CAST(NTD.WEDNESDAY as int) + CAST(NTD.THURSDAY as int) + CAST(NTD.FRIDAY as int) + CAST(NTD.SATURDAY as int) + CAST(NTD.SUNDAY as int))
		END,
		NumDays * NumHours
	FROM 
		dbo.NIELSEN_TV_CUME_DAYPART_IMPRESSION AS NTCDI
		INNER JOIN dbo.NIELSEN_TV_DAYPART AS NTD ON NTD.NIELSEN_TV_DAYPART_ID = NTCDI.NIELSEN_TV_DAYPART_ID
		INNER JOIN dbo.NIELSEN_TV_CUME_BOOK AS NTCB ON NTCB.NIELSEN_TV_CUME_BOOK_ID = NTCDI.NIELSEN_TV_CUME_BOOK_ID 
		INNER JOIN @NIELSEN_TV_BOOKS AS NTB ON NTB.NIELSEN_MARKET_NUM = NTCB.NIELSEN_MARKET_NUM
												AND NTB.[MONTH] = NTCB.[MONTH] 
												AND NTB.[YEAR] = NTCB.[YEAR] 
		INNER JOIN (SELECT 
						ID,
						StartHour,
						EndHour, 
						Sunday,
						Monday,
						Tuesday, 
						Wednesday,
						Thursday,
						Friday,
						Saturday,
						MonFri = CASE WHEN Monday=1 OR Tuesday=1 OR Wednesday=1 OR Thursday=1 OR Friday=1 THEN 1 ELSE 0 END,
						NumDays = CAST(Monday as int) + CAST(Tuesday as int) + CAST(Wednesday as int) + CAST(Thursday as int) + CAST(Friday as int) + CAST(Saturday as int) + CAST(Sunday as int),
						NumHours = dbo.advfn_calculate_num_quarter_hours(StartHour, EndHour)
					FROM 
						@LOCAL_MEDIA_SPOT_TV_RESEARCH_DAYTIME_TYPE) MRDT ON MRDT.ID > 0
	WHERE 
		MRDT.ID NOT IN (SELECT ID FROM @tt)
		AND NTCB.NIELSEN_MARKET_NUM = @NIELSEN_MARKET_NUM
		AND NTCB.VALIDATED = 1
		AND NTCDI.STATION_CODE IN (SELECT items FROM dbo.udf_split_list_int(@StationCodes, ','))
		AND 
			(
				(NTD.NIELSEN_DAYPART_ID = 50005000 AND @IS50005000match = 1)
			OR
				(NTD.NIELSEN_DAYPART_ID = 50009230 AND @IS50009230match = 1)
			)
			

	INSERT INTO @ttTEMP 
	SELECT
		[hh] = NTCDI.HOUSEHOLD,
		[c2-5] = NTCDI.CHILDREN_2TO5,
		[c6-11] = NTCDI.CHILDREN_6TO11,
		[m12-14] = NTCDI.MALES_12TO14,
		[m15-17] = NTCDI.MALES_15TO17,
		[m18-20] = NTCDI.MALES_18TO20,
		[m21-24] = NTCDI.MALES_21TO24,
		[m25-34] = NTCDI.MALES_25TO34,
		[m35-49] = NTCDI.MALES_35TO49,
		[m50-54] = NTCDI.MALES_50TO54,
		[m55-64] = NTCDI.MALES_55TO64,
		[m65P] = NTCDI.MALES_65PLUS,
		[f12-14] = NTCDI.FEMALES_12TO14,
		[f15-17] = NTCDI.FEMALES_15TO17,
		[f18-20] = NTCDI.FEMALES_18TO20,
		[f21-24] = NTCDI.FEMALES_21TO24,
		[f25-34] = NTCDI.FEMALES_25TO34,
		[f35-49] = NTCDI.FEMALES_35TO49,
		[f50-54] = NTCDI.FEMALES_50TO54,
		[f55-64] = NTCDI.FEMALES_55TO64,
		[f65P] = NTCDI.FEMALES_65PLUS,
		[ww] = NTCDI.WORKING_WOMEN,
		NTB.NIELSEN_TV_BOOK_ID,
		NTD.NIELSEN_DAYPART_ID,
		NTCDI.STATION_CODE,
		MRDT.ID,
		NTD.NUMBER_QUARTER_HOURS * (CAST(NTD.MONDAY as int) + CAST(NTD.TUESDAY as int) + CAST(NTD.WEDNESDAY as int) + CAST(NTD.THURSDAY as int) + CAST(NTD.FRIDAY as int) + CAST(NTD.SATURDAY as int) + CAST(NTD.SUNDAY as int)),
		NumDays * NumHours
	FROM 
		dbo.NIELSEN_TV_CUME_DAYPART_IMPRESSION AS NTCDI
		INNER JOIN dbo.NIELSEN_TV_DAYPART AS NTD ON NTD.NIELSEN_TV_DAYPART_ID = NTCDI.NIELSEN_TV_DAYPART_ID
		INNER JOIN dbo.NIELSEN_TV_CUME_BOOK AS NTCB ON NTCB.NIELSEN_TV_CUME_BOOK_ID = NTCDI.NIELSEN_TV_CUME_BOOK_ID 
		INNER JOIN @NIELSEN_TV_BOOKS AS NTB ON NTB.NIELSEN_MARKET_NUM = NTCB.NIELSEN_MARKET_NUM
												AND NTB.[MONTH] = NTCB.[MONTH] 
												AND NTB.[YEAR] = NTCB.[YEAR] 
		INNER JOIN (SELECT 
						ID,
						StartHour,
						EndHour, 
						Sunday,
						Monday,
						Tuesday, 
						Wednesday,
						Thursday,
						Friday,
						Saturday,
						MonFri = CASE WHEN Monday=1 OR Tuesday=1 OR Wednesday=1 OR Thursday=1 OR Friday=1 THEN 1 ELSE 0 END,
						NumDays = CAST(Monday as int) + CAST(Tuesday as int) + CAST(Wednesday as int) + CAST(Thursday as int) + CAST(Friday as int) + CAST(Saturday as int) + CAST(Sunday as int),
						NumHours = dbo.advfn_calculate_num_quarter_hours(StartHour, EndHour)
					FROM 
						@LOCAL_MEDIA_SPOT_TV_RESEARCH_DAYTIME_TYPE) MRDT ON MRDT.ID > 0
	WHERE 
		MRDT.ID NOT IN (SELECT ID FROM @tt)
		AND NTCB.NIELSEN_MARKET_NUM = @NIELSEN_MARKET_NUM
		AND NTCB.VALIDATED = 1
		AND NTCDI.STATION_CODE IN (SELECT items FROM dbo.udf_split_list_int(@StationCodes, ','))
		AND (
				(
					(NTD.MIL_START_TIME BETWEEN MRDT.StartHour AND MRDT.EndHour AND NTD.MIL_START_TIME <> MRDT.EndHour)
				OR
					(NTD.MIL_END_TIME BETWEEN MRDT.StartHour AND MRDT.EndHour AND NTD.MIL_END_TIME <> MRDT.StartHour)
				OR
					(MRDT.StartHour >= NTD.MIL_START_TIME AND MRDT.EndHour <= NTD.MIL_END_TIME)
				)
				AND NTD.SATURDAY = MRDT.Saturday
				AND NTD.SUNDAY = MRDT.Sunday
				AND NTD.MONDAY = MRDT.MonFri	
				AND NTD.TIME_ZONE = @TIME_ZONE
				--AND (1 = CASE WHEN @NIELSEN_MARKET_NUM = 128 OR @NIELSEN_MARKET_NUM = 403 THEN 1 ELSE CASE WHEN NTD.IS_HISPANIC = 0 THEN 1 ELSE 0 END END)
				--AND (
				--		@IS50005000match = 0
				--	OR
				--		@IS50005000match = 1 AND (NTD.MIL_END_TIME <= @START_HOUR_5000 OR NTD.MIL_START_TIME >= @END_HOUR_5000)
				--	)
				AND @IS50005000match = 0
				AND @IS50009230match = 0
			)

	DELETE @ttTEMP
	WHERE ID IN (SELECT ID FROM @ttTEMP
				GROUP BY ID
				HAVING COUNT(1) > 1
				)

	INSERT INTO @tt
	SELECT [hh],
		[c2-5],
		[c6-11],
		[m12-14],
		[m15-17],
		[m18-20],
		[m21-24],
		[m25-34],
		[m35-49],
		[m50-54],
		[m55-64],
		[m65P],
		[f12-14],
		[f15-17],
		[f18-20],
		[f21-24],
		[f25-34],
		[f35-49],
		[f50-54],
		[f55-64],
		[f65P],
		[ww],
		[NIELSEN_TV_BOOK_ID],
		[NIELSEN_DAYPART_ID],
		[STATION_CODE],
		[ID],
		[NUMBER_QUARTER_HOURS],
		[REQUEST_NUM_QHRS]
	FROM @ttTEMP


	INSERT INTO @tt
	SELECT
		[hh] = NTCDI.HOUSEHOLD,
		[c2-5] = NTCDI.CHILDREN_2TO5,
		[c6-11] = NTCDI.CHILDREN_6TO11,
		[m12-14] = NTCDI.MALES_12TO14,
		[m15-17] = NTCDI.MALES_15TO17,
		[m18-20] = NTCDI.MALES_18TO20,
		[m21-24] = NTCDI.MALES_21TO24,
		[m25-34] = NTCDI.MALES_25TO34,
		[m35-49] = NTCDI.MALES_35TO49,
		[m50-54] = NTCDI.MALES_50TO54,
		[m55-64] = NTCDI.MALES_55TO64,
		[m65P] = NTCDI.MALES_65PLUS,
		[f12-14] = NTCDI.FEMALES_12TO14,
		[f15-17] = NTCDI.FEMALES_15TO17,
		[f18-20] = NTCDI.FEMALES_18TO20,
		[f21-24] = NTCDI.FEMALES_21TO24,
		[f25-34] = NTCDI.FEMALES_25TO34,
		[f35-49] = NTCDI.FEMALES_35TO49,
		[f50-54] = NTCDI.FEMALES_50TO54,
		[f55-64] = NTCDI.FEMALES_55TO64,
		[f65P] = NTCDI.FEMALES_65PLUS,
		[ww] = NTCDI.WORKING_WOMEN,
		NTB.NIELSEN_TV_BOOK_ID,
		NTD.NIELSEN_DAYPART_ID,
		NTCDI.STATION_CODE,
		MRDT.ID,
		NTD.NUMBER_QUARTER_HOURS * (CAST(NTD.MONDAY as int) + CAST(NTD.TUESDAY as int) + CAST(NTD.WEDNESDAY as int) + CAST(NTD.THURSDAY as int) + CAST(NTD.FRIDAY as int) + CAST(NTD.SATURDAY as int) + CAST(NTD.SUNDAY as int)),
		NumDays * NumHours
	FROM 
		dbo.NIELSEN_TV_CUME_DAYPART_IMPRESSION AS NTCDI
		INNER JOIN dbo.NIELSEN_TV_DAYPART AS NTD ON NTD.NIELSEN_TV_DAYPART_ID = NTCDI.NIELSEN_TV_DAYPART_ID
		INNER JOIN dbo.NIELSEN_TV_CUME_BOOK AS NTCB ON NTCB.NIELSEN_TV_CUME_BOOK_ID = NTCDI.NIELSEN_TV_CUME_BOOK_ID 
		INNER JOIN @NIELSEN_TV_BOOKS AS NTB ON NTB.NIELSEN_MARKET_NUM = NTCB.NIELSEN_MARKET_NUM
												AND NTB.[MONTH] = NTCB.[MONTH] 
												AND NTB.[YEAR] = NTCB.[YEAR] 
		INNER JOIN (SELECT 
						ID,
						StartHour,
						EndHour, 
						Sunday,
						Monday,
						Tuesday, 
						Wednesday,
						Thursday,
						Friday,
						Saturday,
						MonFri = CASE WHEN Monday=1 OR Tuesday=1 OR Wednesday=1 OR Thursday=1 OR Friday=1 THEN 1 ELSE 0 END,
						NumDays = CAST(Monday as int) + CAST(Tuesday as int) + CAST(Wednesday as int) + CAST(Thursday as int) + CAST(Friday as int) + CAST(Saturday as int) + CAST(Sunday as int),
						NumHours = dbo.advfn_calculate_num_quarter_hours(StartHour, EndHour)
					FROM 
						@LOCAL_MEDIA_SPOT_TV_RESEARCH_DAYTIME_TYPE) MRDT ON MRDT.ID > 0
	WHERE 
		MRDT.ID NOT IN (SELECT ID FROM @tt)
		AND NTCB.NIELSEN_MARKET_NUM = @NIELSEN_MARKET_NUM
		AND NTCB.VALIDATED = 1
		AND NTD.USE_SEGMENT = 1
		AND NTCDI.STATION_CODE IN (SELECT items FROM dbo.udf_split_list_int(@StationCodes, ','))
		AND NTD.TIME_ZONE = @TIME_ZONE
		--AND (1 = CASE WHEN @NIELSEN_MARKET_NUM = 128 OR @NIELSEN_MARKET_NUM = 403 THEN 1 ELSE CASE WHEN NTD.IS_HISPANIC = 0 THEN 1 ELSE 0 END END)
		AND (
				(NTD.MIL_START_TIME BETWEEN MRDT.StartHour AND MRDT.EndHour AND NTD.MIL_START_TIME <> MRDT.EndHour)
			OR
				(NTD.MIL_END_TIME BETWEEN MRDT.StartHour AND MRDT.EndHour AND NTD.MIL_END_TIME <> MRDT.StartHour)
			OR
				(MRDT.StartHour >= NTD.MIL_START_TIME AND MRDT.EndHour <= NTD.MIL_END_TIME)
			)
		AND
			(
				(MRDT.Saturday = NTD.SATURDAY AND MRDT.Saturday = 1)
			OR 
				(MRDT.Sunday = NTD.SUNDAY AND MRDT.Sunday = 1)
			OR 
				(MRDT.MonFri = NTD.MONDAY AND MRDT.MonFri = 1)
			)
		AND (
				(@IS50005000match = 1 AND NTD.NIELSEN_DAYPART_ID NOT IN (10040800, 10042500, 10040800, 10042375, 10042675))
			OR
				@IS50005000match = 0
			)


	INSERT INTO @tt
	SELECT
		[hh] = NTCDI.HOUSEHOLD,
		[c2-5] = NTCDI.CHILDREN_2TO5,
		[c6-11] = NTCDI.CHILDREN_6TO11,
		[m12-14] = NTCDI.MALES_12TO14,
		[m15-17] = NTCDI.MALES_15TO17,
		[m18-20] = NTCDI.MALES_18TO20,
		[m21-24] = NTCDI.MALES_21TO24,
		[m25-34] = NTCDI.MALES_25TO34,
		[m35-49] = NTCDI.MALES_35TO49,
		[m50-54] = NTCDI.MALES_50TO54,
		[m55-64] = NTCDI.MALES_55TO64,
		[m65P] = NTCDI.MALES_65PLUS,
		[f12-14] = NTCDI.FEMALES_12TO14,
		[f15-17] = NTCDI.FEMALES_15TO17,
		[f18-20] = NTCDI.FEMALES_18TO20,
		[f21-24] = NTCDI.FEMALES_21TO24,
		[f25-34] = NTCDI.FEMALES_25TO34,
		[f35-49] = NTCDI.FEMALES_35TO49,
		[f50-54] = NTCDI.FEMALES_50TO54,
		[f55-64] = NTCDI.FEMALES_55TO64,
		[f65P] = NTCDI.FEMALES_65PLUS,
		[ww] = NTCDI.WORKING_WOMEN,
		NTB.NIELSEN_TV_BOOK_ID,
		NTD.NIELSEN_DAYPART_ID,
		NTCDI.STATION_CODE,
		MRDT.ID,
		NTD.NUMBER_QUARTER_HOURS * (CAST(NTD.MONDAY as int) + CAST(NTD.TUESDAY as int) + CAST(NTD.WEDNESDAY as int) + CAST(NTD.THURSDAY as int) + CAST(NTD.FRIDAY as int) + CAST(NTD.SATURDAY as int) + CAST(NTD.SUNDAY as int)),
		NumDays * NumHours
	FROM 
		dbo.NIELSEN_TV_CUME_DAYPART_IMPRESSION AS NTCDI
		INNER JOIN dbo.NIELSEN_TV_DAYPART AS NTD ON NTD.NIELSEN_TV_DAYPART_ID = NTCDI.NIELSEN_TV_DAYPART_ID
		INNER JOIN dbo.NIELSEN_TV_CUME_BOOK AS NTCB ON NTCB.NIELSEN_TV_CUME_BOOK_ID = NTCDI.NIELSEN_TV_CUME_BOOK_ID 
		INNER JOIN @NIELSEN_TV_BOOKS AS NTB ON NTB.NIELSEN_MARKET_NUM = NTCB.NIELSEN_MARKET_NUM
												AND NTB.[MONTH] = NTCB.[MONTH] 
												AND NTB.[YEAR] = NTCB.[YEAR] 
		INNER JOIN (SELECT 
						ID,
						StartHour,
						EndHour, 
						Sunday,
						Monday,
						Tuesday, 
						Wednesday,
						Thursday,
						Friday,
						Saturday,
						MonFri = CASE WHEN Monday=1 OR Tuesday=1 OR Wednesday=1 OR Thursday=1 OR Friday=1 THEN 1 ELSE 0 END,
						NumDays = CAST(Monday as int) + CAST(Tuesday as int) + CAST(Wednesday as int) + CAST(Thursday as int) + CAST(Friday as int) + CAST(Saturday as int) + CAST(Sunday as int),
						NumHours = dbo.advfn_calculate_num_quarter_hours(StartHour, EndHour)
					FROM 
						@LOCAL_MEDIA_SPOT_TV_RESEARCH_DAYTIME_TYPE) MRDT ON MRDT.ID > 0
	WHERE 
		MRDT.ID NOT IN (SELECT ID FROM @tt)
		AND NTCB.NIELSEN_MARKET_NUM = @NIELSEN_MARKET_NUM
		AND NTCB.VALIDATED = 1
		AND NTCDI.STATION_CODE IN (SELECT items FROM dbo.udf_split_list_int(@StationCodes, ','))
		AND NTD.TIME_ZONE = @TIME_ZONE
		--AND (1 = CASE WHEN @NIELSEN_MARKET_NUM = 128 OR @NIELSEN_MARKET_NUM = 403 THEN 1 ELSE CASE WHEN NTD.IS_HISPANIC = 0 THEN 1 ELSE 0 END END)
		AND (MRDT.Sunday = 1 OR	MRDT.Saturday = 1)
		AND MRDT.MonFri = 0
		AND
			(
				(
					(
						(@TIME_ZONE = 'C' AND MRDT.StartHour >= 2200 AND MRDT.StartHour < 2230)
					OR
						(@TIME_ZONE = 'E' AND MRDT.StartHour >= 2300 AND MRDT.StartHour < 2330)
					)
				AND 
					NTD.NIELSEN_DAYPART_ID = 40003000
				)
			OR
				(
					(@TIME_ZONE = 'C' AND MRDT.StartHour >= 2230 AND MRDT.StartHour < 2600)
				OR
					(@TIME_ZONE = 'E' AND MRDT.StartHour >= 2330 AND MRDT.StartHour < 2600)
				)
				AND 
					NTD.NIELSEN_DAYPART_ID = 40004000
			)

	DECLARE @CUMEFACTOR_TABLE TABLE (
		ID int,
		REQUEST_NUM_QHRS int,
		CUME_NUM_QHRS int,
		CUME_FACTOR decimal(5,4)
	)

	DECLARE @RNQ_COUNTER int,
			@ROW_COUNT int,
			@CUME_NUM_QHRS int,
			@ID int,
			@REQUEST_NUM_QHRS int,
			@CUME_FACTOR decimal(5,4)

	INSERT INTO @CUMEFACTOR_TABLE (ID, REQUEST_NUM_QHRS, CUME_NUM_QHRS, CUME_FACTOR)
	SELECT ID, REQUEST_NUM_QHRS, SUM(NUMBER_QUARTER_HOURS), 0
	FROM @tt
	GROUP BY ID, REQUEST_NUM_QHRS
	
	UPDATE @CUMEFACTOR_TABLE SET CUME_FACTOR = 1
	WHERE CUME_NUM_QHRS = REQUEST_NUM_QHRS

	SELECT @ROW_COUNT = COUNT(1) 
	FROM @CUMEFACTOR_TABLE
	WHERE CUME_FACTOR = 0

	WHILE @ROW_COUNT > 0
	BEGIN

		SELECT TOP 1 @ID = ID, @CUME_NUM_QHRS = CUME_NUM_QHRS, @REQUEST_NUM_QHRS = REQUEST_NUM_QHRS
		FROM @CUMEFACTOR_TABLE
		WHERE CUME_FACTOR = 0
		AND CUME_NUM_QHRS > 0

		SET @CUME_FACTOR = 2 * 1 / CAST(@CUME_NUM_QHRS as decimal)

		SET @RNQ_COUNTER = 2

		WHILE @RNQ_COUNTER <= @REQUEST_NUM_QHRS 
		BEGIN

			SET @CUME_FACTOR = @CUME_FACTOR + 3 * (1 - @CUME_FACTOR) / CAST(@CUME_NUM_QHRS as decimal)
			SET @RNQ_COUNTER = @RNQ_COUNTER + 1

		END

		UPDATE @CUMEFACTOR_TABLE SET CUME_FACTOR = @CUME_FACTOR
		WHERE ID = @ID

		SELECT @ROW_COUNT = COUNT(1) 
		FROM @CUMEFACTOR_TABLE
		WHERE CUME_FACTOR = 0

	END

	INSERT INTO @RETURN_TABLE
	SELECT
		SUM(A.CUME_IMPRESSIONS) * (SELECT CUME_FACTOR FROM @CUMEFACTOR_TABLE WHERE ID = A.ID), A.MediaDemographicID, A.STATION_CODE, A.NIELSEN_TV_BOOK_ID, A.ID
	FROM 
		(
		SELECT
			u.NIELSEN_DEMO_CODE, u.CUME_IMPRESSIONS, mdd.MediaDemographicID, mdd.NielsenDemographicID, STATION_CODE, NIELSEN_TV_BOOK_ID, [ID]
		FROM (
			SELECT 
				[hh] = SUM([hh]),
				[c2-5]	= SUM([c2-5]),
				[c6-11] = SUM([c6-11]),
				[m12-14] = SUM([m12-14]),
				[m15-17] = SUM([m15-17]),
				[m18-20] = SUM([m18-20]),
				[m21-24] = SUM([m21-24]),
				[m25-34] = SUM([m25-34]),
				[m35-49] = SUM([m35-49]),
				[m50-54] = SUM([m50-54]),
				[m55-64] = SUM([m55-64]),
				[m65P] = SUM([m65P]),
				[f12-14] = SUM([f12-14]),
				[f15-17] = SUM([f15-17]),
				[f18-20] = SUM([f18-20]),
				[f21-24] = SUM([f21-24]),
				[f25-34] = SUM([f25-34]),
				[f35-49] = SUM([f35-49]),
				[f50-54] = SUM([f50-54]),
				[f55-64] = SUM([f55-64]),
				[f65P] = SUM([f65P]),
				[ww] = SUM([ww]),
				STATION_CODE,
				NIELSEN_TV_BOOK_ID,
				[ID]
			FROM 
				(SELECT 
						[hh],
						[c2-5],
						[c6-11],
						[m12-14],
						[m15-17],
						[m18-20],
						[m21-24],
						[m25-34],
						[m35-49],
						[m50-54],
						[m55-64],
						[m65P],
						[f12-14],
						[f15-17],
						[f18-20],
						[f21-24],
						[f25-34],
						[f35-49],
						[f50-54],
						[f55-64],
						[f65P],
						[ww],
						[NIELSEN_TV_BOOK_ID],
						[NIELSEN_DAYPART_ID],
						[STATION_CODE],
						[ID]
					FROM 
						@tt) rawdata 
			GROUP BY STATION_CODE, NIELSEN_TV_BOOK_ID, [ID], [NIELSEN_DAYPART_ID]) CUMEDATA
			UNPIVOT
			(
				CUME_IMPRESSIONS
				FOR NIELSEN_DEMO_CODE in ([hh], [c2-5], [c6-11], [m12-14], [m15-17], [m18-20], [m21-24], [m25-34], [m35-49], [m50-54], [m55-64], [m65P], [f12-14], [f15-17], [f18-20], [f21-24], [f25-34], [f35-49], [f50-54], [f55-64], [f65P], [ww]) 
			) u
			INNER JOIN dbo.NIELSEN_DEMO nd ON u.NIELSEN_DEMO_CODE = nd.CODE
			INNER JOIN @MEDIA_DEMO_DETAIL_TYPE mdd ON nd.NIELSEN_DEMO_ID = mdd.NielsenDemographicID) AS A
	GROUP BY A.MediaDemographicID, A.NIELSEN_TV_BOOK_ID, A.STATION_CODE, A.ID

	RETURN
END
GO

GRANT SELECT ON advtf_nielsen_tv_cume_impressions TO PUBLIC
GO
