'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.CodeDom.Compiler
Imports System.Data.Entity.Core.Metadata.Edm
Imports System.Data.Entity.Infrastructure.MappingViews

<Assembly: DbMappingViewCacheTypeAttribute(
    GetType(AdvantageFramework.BillingCommandCenter.Database.DbContext),
    GetType(Edm_EntityMappingGeneratedViews.ViewsForBaseEntitySets1782c9f9779528b22f7da442b7b754dbf17565fb6cbd1d2ee2bad44636f5a3fd))>

Namespace Edm_EntityMappingGeneratedViews

    ''' <summary>
    ''' Implements a mapping view cache.
    ''' </summary>
    <GeneratedCode("Entity Framework 6 Power Tools", "0.9.2.0")>
    Friend NotInheritable Class ViewsForBaseEntitySets1782c9f9779528b22f7da442b7b754dbf17565fb6cbd1d2ee2bad44636f5a3fd
        Inherits DbMappingViewCache

        ''' <summary>
        ''' Gets a hash value computed over the mapping closure.
        ''' </summary>
        Public Overrides ReadOnly Property MappingHashValue As String
            Get
                Return "1782c9f9779528b22f7da442b7b754dbf17565fb6cbd1d2ee2bad44636f5a3fd"
            End Get
        End Property

        ''' <summary>
        ''' Gets a view corresponding to the specified extent.
        ''' </summary>
        ''' <param name="extent">The extent.</param>
        ''' <returns>The mapping view, or null if the extent is not associated with a mapping view.</returns>
        Public Overrides Function GetView(extent As EntitySetBase) As DbMappingView
            If extent Is Nothing Then
                Throw New ArgumentNullException("extent")
            End If

            Dim extentName = extent.EntityContainer.Name & "." & extent.Name

            If extentName = "CodeFirstDatabase.BillingApprovalBatch" Then
                Return GetView0()
            End If

            If extentName = "DbContext.BillingApprovalBatches" Then
                Return GetView1()
            End If

            If extentName = "CodeFirstDatabase.BillingCommandCenter" Then
                Return GetView2()
            End If

            If extentName = "DbContext.BillingCommandCenters" Then
                Return GetView3()
            End If

            Return Nothing
        End Function

        ''' <summary>
        ''' Gets the view for CodeFirstDatabase.BillingApprovalBatch.
        ''' </summary>
        ''' <returns>The mapping view.</returns>
        Private Shared Function GetView0() As DbMappingView
            Return New DbMappingView(
                "" & vbCrLf &
                "    SELECT VALUE -- Constructing BillingApprovalBatch" & vbCrLf &
                "        [CodeFirstDatabaseSchema.BillingApprovalBatch](T1.[BillingApprovalBatch.BA_BATCH_ID], T1.[BillingApprovalBatch.BA_BATCH_DESC], T1.[BillingApprovalBatch.BATCH_DATE], T1.[BillingApprovalBatch.CREATE_USER], T1.[BillingApprovalBatch.CREATE_DATE], T1.[BillingApprovalBatch.MODIFY_USER], T1.[BillingApprovalBatch.MODIFY_DATE], T1.[BillingApprovalBatch.DATE_CUTOFF], T1.[BillingApprovalBatch.PERIOD_CUTOFF], T1.[BillingApprovalBatch.EMP_CODE], T1.[BillingApprovalBatch.INCL_NO_DTL], T1.[BillingApprovalBatch.INCL_NB], T1.[BillingApprovalBatch.INCL_FEE], T1.[BillingApprovalBatch.INCL_INT], T1.[BillingApprovalBatch.INCL_NP], T1.[BillingApprovalBatch.INCL_MAG], T1.[BillingApprovalBatch.INCL_OD], T1.[BillingApprovalBatch.INCL_RA], T1.[BillingApprovalBatch.INCL_TV], T1.BillingApprovalBatch_APPROVED, T1.BillingApprovalBatch_FINISHED, T1.[BillingApprovalBatch.APPR_METHOD], T1.[BillingApprovalBatch.SEL_OPTION], T1.[BillingApprovalBatch.MANAGER_TYPE], T1.[BillingApprovalBatch.BA_EXISTS], T1.[BillingApprovalBatch.BILLED_ANY], T1.[BillingApprovalBatch.BILLED_ALL])" & vbCrLf &
                "    FROM (" & vbCrLf &
                "        SELECT " & vbCrLf &
                "            T.ID AS [BillingApprovalBatch.BA_BATCH_ID], " & vbCrLf &
                "            T.Description AS [BillingApprovalBatch.BA_BATCH_DESC], " & vbCrLf &
                "            T.BatchDate AS [BillingApprovalBatch.BATCH_DATE], " & vbCrLf &
                "            T.CreatedBy AS [BillingApprovalBatch.CREATE_USER], " & vbCrLf &
                "            T.CreatedDate AS [BillingApprovalBatch.CREATE_DATE], " & vbCrLf &
                "            T.ModifiedBy AS [BillingApprovalBatch.MODIFY_USER], " & vbCrLf &
                "            T.ModifiedDate AS [BillingApprovalBatch.MODIFY_DATE], " & vbCrLf &
                "            T.DateCutoff AS [BillingApprovalBatch.DATE_CUTOFF], " & vbCrLf &
                "            T.CutoffPostPeriodCode AS [BillingApprovalBatch.PERIOD_CUTOFF], " & vbCrLf &
                "            T.EmployeeCode AS [BillingApprovalBatch.EMP_CODE], " & vbCrLf &
                "            T.IncludeNoDTL AS [BillingApprovalBatch.INCL_NO_DTL], " & vbCrLf &
                "            T.IncludeNB AS [BillingApprovalBatch.INCL_NB], " & vbCrLf &
                "            T.IncludeFee AS [BillingApprovalBatch.INCL_FEE], " & vbCrLf &
                "            T.IncludeInternet AS [BillingApprovalBatch.INCL_INT], " & vbCrLf &
                "            T.IncludeNewspaper AS [BillingApprovalBatch.INCL_NP], " & vbCrLf &
                "            T.IncludeMagazine AS [BillingApprovalBatch.INCL_MAG], " & vbCrLf &
                "            T.IncludeOutOfHome AS [BillingApprovalBatch.INCL_OD], " & vbCrLf &
                "            T.IncludeRadio AS [BillingApprovalBatch.INCL_RA], " & vbCrLf &
                "            T.IncludeTV AS [BillingApprovalBatch.INCL_TV], " & vbCrLf &
                "            T.IsApproved AS BillingApprovalBatch_APPROVED, " & vbCrLf &
                "            T.IsFinished AS BillingApprovalBatch_FINISHED, " & vbCrLf &
                "            T.ApprovalMethod AS [BillingApprovalBatch.APPR_METHOD], " & vbCrLf &
                "            T.SelectionOption AS [BillingApprovalBatch.SEL_OPTION], " & vbCrLf &
                "            T.ManagerType AS [BillingApprovalBatch.MANAGER_TYPE], " & vbCrLf &
                "            T.BillingApprovalExists AS [BillingApprovalBatch.BA_EXISTS], " & vbCrLf &
                "            T.BillingApprovalBilledAny AS [BillingApprovalBatch.BILLED_ANY], " & vbCrLf &
                "            T.BillingApprovalBilledAll AS [BillingApprovalBatch.BILLED_ALL], " & vbCrLf &
                "            True AS _from0" & vbCrLf &
                "        FROM DbContext.BillingApprovalBatches AS T" & vbCrLf &
                "    ) AS T1")
        End Function

        ''' <summary>
        ''' Gets the view for DbContext.BillingApprovalBatches.
        ''' </summary>
        ''' <returns>The mapping view.</returns>
        Private Shared Function GetView1() As DbMappingView
            Return New DbMappingView(
                "" & vbCrLf &
                "    SELECT VALUE -- Constructing BillingApprovalBatches" & vbCrLf &
                "        [AdvantageFramework.BillingCommandCenter.Database.BillingApprovalBatch](T1.BillingApprovalBatch_ID, T1.BillingApprovalBatch_Description, T1.BillingApprovalBatch_BatchDate, T1.BillingApprovalBatch_CreatedBy, T1.BillingApprovalBatch_CreatedDate, T1.BillingApprovalBatch_ModifiedBy, T1.BillingApprovalBatch_ModifiedDate, T1.BillingApprovalBatch_DateCutoff, T1.BillingApprovalBatch_CutoffPostPeriodCode, T1.BillingApprovalBatch_EmployeeCode, T1.BillingApprovalBatch_IncludeNoDTL, T1.BillingApprovalBatch_IncludeNB, T1.BillingApprovalBatch_IncludeFee, T1.BillingApprovalBatch_IncludeInternet, T1.BillingApprovalBatch_IncludeNewspaper, T1.BillingApprovalBatch_IncludeMagazine, T1.BillingApprovalBatch_IncludeOutOfHome, T1.BillingApprovalBatch_IncludeRadio, T1.BillingApprovalBatch_IncludeTV, T1.BillingApprovalBatch_IsApproved, T1.BillingApprovalBatch_IsFinished, T1.BillingApprovalBatch_ApprovalMethod, T1.BillingApprovalBatch_SelectionOption, T1.BillingApprovalBatch_ManagerType, T1.BillingApprovalBatch_BillingApprovalExists, T1.BillingApprovalBatch_BillingApprovalBilledAny, T1.BillingApprovalBatch_BillingApprovalBilledAll)" & vbCrLf &
                "    FROM (" & vbCrLf &
                "        SELECT " & vbCrLf &
                "            T.BA_BATCH_ID AS BillingApprovalBatch_ID, " & vbCrLf &
                "            T.BA_BATCH_DESC AS BillingApprovalBatch_Description, " & vbCrLf &
                "            T.BATCH_DATE AS BillingApprovalBatch_BatchDate, " & vbCrLf &
                "            T.CREATE_USER AS BillingApprovalBatch_CreatedBy, " & vbCrLf &
                "            T.CREATE_DATE AS BillingApprovalBatch_CreatedDate, " & vbCrLf &
                "            T.MODIFY_USER AS BillingApprovalBatch_ModifiedBy, " & vbCrLf &
                "            T.MODIFY_DATE AS BillingApprovalBatch_ModifiedDate, " & vbCrLf &
                "            T.DATE_CUTOFF AS BillingApprovalBatch_DateCutoff, " & vbCrLf &
                "            T.PERIOD_CUTOFF AS BillingApprovalBatch_CutoffPostPeriodCode, " & vbCrLf &
                "            T.EMP_CODE AS BillingApprovalBatch_EmployeeCode, " & vbCrLf &
                "            T.INCL_NO_DTL AS BillingApprovalBatch_IncludeNoDTL, " & vbCrLf &
                "            T.INCL_NB AS BillingApprovalBatch_IncludeNB, " & vbCrLf &
                "            T.INCL_FEE AS BillingApprovalBatch_IncludeFee, " & vbCrLf &
                "            T.INCL_INT AS BillingApprovalBatch_IncludeInternet, " & vbCrLf &
                "            T.INCL_NP AS BillingApprovalBatch_IncludeNewspaper, " & vbCrLf &
                "            T.INCL_MAG AS BillingApprovalBatch_IncludeMagazine, " & vbCrLf &
                "            T.INCL_OD AS BillingApprovalBatch_IncludeOutOfHome, " & vbCrLf &
                "            T.INCL_RA AS BillingApprovalBatch_IncludeRadio, " & vbCrLf &
                "            T.INCL_TV AS BillingApprovalBatch_IncludeTV, " & vbCrLf &
                "            T.APPROVED AS BillingApprovalBatch_IsApproved, " & vbCrLf &
                "            T.FINISHED AS BillingApprovalBatch_IsFinished, " & vbCrLf &
                "            T.APPR_METHOD AS BillingApprovalBatch_ApprovalMethod, " & vbCrLf &
                "            T.SEL_OPTION AS BillingApprovalBatch_SelectionOption, " & vbCrLf &
                "            T.MANAGER_TYPE AS BillingApprovalBatch_ManagerType, " & vbCrLf &
                "            T.BA_EXISTS AS BillingApprovalBatch_BillingApprovalExists, " & vbCrLf &
                "            T.BILLED_ANY AS BillingApprovalBatch_BillingApprovalBilledAny, " & vbCrLf &
                "            T.BILLED_ALL AS BillingApprovalBatch_BillingApprovalBilledAll, " & vbCrLf &
                "            True AS _from0" & vbCrLf &
                "        FROM CodeFirstDatabase.BillingApprovalBatch AS T" & vbCrLf &
                "    ) AS T1")
        End Function

        ''' <summary>
        ''' Gets the view for CodeFirstDatabase.BillingCommandCenter.
        ''' </summary>
        ''' <returns>The mapping view.</returns>
        Private Shared Function GetView2() As DbMappingView
            Return New DbMappingView(
                "" & vbCrLf &
                "    SELECT VALUE -- Constructing BillingCommandCenter" & vbCrLf &
                "        [CodeFirstDatabaseSchema.BillingCommandCenter](T1.[BillingCommandCenter.BCC_ID], T1.[BillingCommandCenter.BILLING_USER], T1.[BillingCommandCenter.CREATE_DATE], T1.[BillingCommandCenter.P_SELECT_BY], T1.[BillingCommandCenter.PROD_FLAG], T1.[BillingCommandCenter.P_ET_CUTOFF_DATE], T1.[BillingCommandCenter.P_IO_CUTOFF_DATE], T1.[BillingCommandCenter.P_AB_CUTOFF_DATE], T1.[BillingCommandCenter.P_AP_CUTOFF_PPD], T1.[BillingCommandCenter.BA_BATCH_ID], T1.[BillingCommandCenter.MEDIA_FLAG], T1.[BillingCommandCenter.M_SELECT_BY], T1.[BillingCommandCenter.M_CUTOFF_DATE], T1.BillingCommandCenter_NEWSPAPER, T1.BillingCommandCenter_MAGAZINE, T1.BillingCommandCenter_RADIO, T1.BillingCommandCenter_TELEVISION, T1.[BillingCommandCenter.OUT_OF_HOME], T1.BillingCommandCenter_INTERNET, T1.[BillingCommandCenter.M_BRDCAST_MTH1], T1.[BillingCommandCenter.M_BRDCAST_MTH2], T1.[BillingCommandCenter.INCL_ZERO_SPOTS], T1.[BillingCommandCenter.M_START_DATE], T1.[BillingCommandCenter.DATE_CUTOFF_TO_USE], T1.[BillingCommandCenter.INCL_UNBILLED_ONLY], T1.[BillingCommandCenter.SEL_OPTION], T1.[BillingCommandCenter.RADIO_DAILY], T1.[BillingCommandCenter.TV_DAILY], T1.[BillingCommandCenter.RADIO_MONTHLY], T1.[BillingCommandCenter.TV_MONTHLY], T1.[BillingCommandCenter.BATCH_NAME], T1.[BillingCommandCenter.SEQ_NO], T1.[BillingCommandCenter.PROD_JOB_TYPE], T1.[BillingCommandCenter.PROD_LOCK_SELECTION], T1.[BillingCommandCenter.INCLUDE_LEGACY], T1.[BillingCommandCenter.JOB_MEDIA_BILL_DATE_FROM], T1.[BillingCommandCenter.JOB_MEDIA_BILL_DATE_TO], T1.[BillingCommandCenter.PRODUCTION_INCLUDE_MEDIA_BILL_DATES], T1.[BillingCommandCenter.PRODUCTION_MEDIA_BILL_DATE_FROM], T1.[BillingCommandCenter.PRODUCTION_MEDIA_BILL_DATE_TO])" & vbCrLf &
                "    FROM (" & vbCrLf &
                "        SELECT " & vbCrLf &
                "            T.ID AS [BillingCommandCenter.BCC_ID], " & vbCrLf &
                "            T.BillingUser AS [BillingCommandCenter.BILLING_USER], " & vbCrLf &
                "            T.CreateDate AS [BillingCommandCenter.CREATE_DATE], " & vbCrLf &
                "            T.ProductionSelectBy AS [BillingCommandCenter.P_SELECT_BY], " & vbCrLf &
                "            T.IsProduction AS [BillingCommandCenter.PROD_FLAG], " & vbCrLf &
                "            T.EmployeeTimeDateCutoff AS [BillingCommandCenter.P_ET_CUTOFF_DATE], " & vbCrLf &
                "            T.IncomeOnlyDateCutoff AS [BillingCommandCenter.P_IO_CUTOFF_DATE], " & vbCrLf &
                "            T.AdvanceBillingDateCutoff AS [BillingCommandCenter.P_AB_CUTOFF_DATE], " & vbCrLf &
                "            T.APPostPeriodCodeCutoff AS [BillingCommandCenter.P_AP_CUTOFF_PPD], " & vbCrLf &
                "            T.BillingApprovalBatchID AS [BillingCommandCenter.BA_BATCH_ID], " & vbCrLf &
                "            T.IsMedia AS [BillingCommandCenter.MEDIA_FLAG], " & vbCrLf &
                "            T.MediaSelectBy AS [BillingCommandCenter.M_SELECT_BY], " & vbCrLf &
                "            T.MediaEndDate AS [BillingCommandCenter.M_CUTOFF_DATE], " & vbCrLf &
                "            T.IsNewspaper AS BillingCommandCenter_NEWSPAPER, " & vbCrLf &
                "            T.IsMagazine AS BillingCommandCenter_MAGAZINE, " & vbCrLf &
                "            T.IsRadio AS BillingCommandCenter_RADIO, " & vbCrLf &
                "            T.IsTelevision AS BillingCommandCenter_TELEVISION, " & vbCrLf &
                "            T.IsOutOfHome AS [BillingCommandCenter.OUT_OF_HOME], " & vbCrLf &
                "            T.IsInternet AS BillingCommandCenter_INTERNET, " & vbCrLf &
                "            T.MediaBroadcastMonthStart AS [BillingCommandCenter.M_BRDCAST_MTH1], " & vbCrLf &
                "            T.MediaBroadcastMonthEnd AS [BillingCommandCenter.M_BRDCAST_MTH2], " & vbCrLf &
                "            T.IncludeZeroSpots AS [BillingCommandCenter.INCL_ZERO_SPOTS], " & vbCrLf &
                "            T.MediaStartDate AS [BillingCommandCenter.M_START_DATE], " & vbCrLf &
                "            T.DateCuttoffToUseFlag AS [BillingCommandCenter.DATE_CUTOFF_TO_USE], " & vbCrLf &
                "            T.IncludeUnbilledOrdersOnly AS [BillingCommandCenter.INCL_UNBILLED_ONLY], " & vbCrLf &
                "            T.ProductionSelectionOption AS [BillingCommandCenter.SEL_OPTION], " & vbCrLf &
                "            T.IsRadioDaily AS [BillingCommandCenter.RADIO_DAILY], " & vbCrLf &
                "            T.IsTelevisionDaily AS [BillingCommandCenter.TV_DAILY], " & vbCrLf &
                "            T.IsRadioMonthly AS [BillingCommandCenter.RADIO_MONTHLY], " & vbCrLf &
                "            T.IsTelevisionMonthly AS [BillingCommandCenter.TV_MONTHLY], " & vbCrLf &
                "            T.BatchName AS [BillingCommandCenter.BATCH_NAME], " & vbCrLf &
                "            T.SequenceNumber AS [BillingCommandCenter.SEQ_NO], " & vbCrLf &
                "            T.ProductionJobType AS [BillingCommandCenter.PROD_JOB_TYPE], " & vbCrLf &
                "            T.IsProductionSelectionLocked AS [BillingCommandCenter.PROD_LOCK_SELECTION], " & vbCrLf &
                "            T.IncludeLegacy AS [BillingCommandCenter.INCLUDE_LEGACY], " & vbCrLf &
                "            T.JobMediaBillDateFrom AS [BillingCommandCenter.JOB_MEDIA_BILL_DATE_FROM], " & vbCrLf &
                "            T.JobMediaBillDateTo AS [BillingCommandCenter.JOB_MEDIA_BILL_DATE_TO], " & vbCrLf &
                "            T.ProductionIncludeJobMediaBillDates AS [BillingCommandCenter.PRODUCTION_INCLUDE_MEDIA_BILL_DATES], " & vbCrLf &
                "            T.ProductionJobMediaBillDateFrom AS [BillingCommandCenter.PRODUCTION_MEDIA_BILL_DATE_FROM], " & vbCrLf &
                "            T.ProductionJobMediaBillDateTo AS [BillingCommandCenter.PRODUCTION_MEDIA_BILL_DATE_TO], " & vbCrLf &
                "            True AS _from0" & vbCrLf &
                "        FROM DbContext.BillingCommandCenters AS T" & vbCrLf &
                "    ) AS T1")
        End Function

        ''' <summary>
        ''' Gets the view for DbContext.BillingCommandCenters.
        ''' </summary>
        ''' <returns>The mapping view.</returns>
        Private Shared Function GetView3() As DbMappingView
            Return New DbMappingView(
                "" & vbCrLf &
                "    SELECT VALUE -- Constructing BillingCommandCenters" & vbCrLf &
                "        [AdvantageFramework.BillingCommandCenter.Database.BillingCommandCenter](T1.BillingCommandCenter_ID, T1.BillingCommandCenter_BillingUser, T1.BillingCommandCenter_CreateDate, T1.BillingCommandCenter_ProductionSelectBy, T1.BillingCommandCenter_IsProduction, T1.BillingCommandCenter_EmployeeTimeDateCutoff, T1.BillingCommandCenter_IncomeOnlyDateCutoff, T1.BillingCommandCenter_AdvanceBillingDateCutoff, T1.BillingCommandCenter_APPostPeriodCodeCutoff, T1.BillingCommandCenter_BillingApprovalBatchID, T1.BillingCommandCenter_IsMedia, T1.BillingCommandCenter_MediaSelectBy, T1.BillingCommandCenter_MediaEndDate, T1.BillingCommandCenter_IsNewspaper, T1.BillingCommandCenter_IsMagazine, T1.BillingCommandCenter_IsRadio, T1.BillingCommandCenter_IsTelevision, T1.BillingCommandCenter_IsOutOfHome, T1.BillingCommandCenter_IsInternet, T1.BillingCommandCenter_MediaBroadcastMonthStart, T1.BillingCommandCenter_MediaBroadcastMonthEnd, T1.BillingCommandCenter_IncludeZeroSpots, T1.BillingCommandCenter_MediaStartDate, T1.BillingCommandCenter_DateCuttoffToUseFlag, T1.BillingCommandCenter_IncludeUnbilledOrdersOnly, T1.BillingCommandCenter_ProductionSelectionOption, T1.BillingCommandCenter_IsRadioDaily, T1.BillingCommandCenter_IsTelevisionDaily, T1.BillingCommandCenter_IsRadioMonthly, T1.BillingCommandCenter_IsTelevisionMonthly, T1.BillingCommandCenter_BatchName, T1.BillingCommandCenter_SequenceNumber, T1.BillingCommandCenter_ProductionJobType, T1.BillingCommandCenter_IsProductionSelectionLocked, T1.BillingCommandCenter_IncludeLegacy, T1.BillingCommandCenter_JobMediaBillDateFrom, T1.BillingCommandCenter_JobMediaBillDateTo, T1.BillingCommandCenter_ProductionIncludeJobMediaBillDates, T1.BillingCommandCenter_ProductionJobMediaBillDateFrom, T1.BillingCommandCenter_ProductionJobMediaBillDateTo)" & vbCrLf &
                "    FROM (" & vbCrLf &
                "        SELECT " & vbCrLf &
                "            T.BCC_ID AS BillingCommandCenter_ID, " & vbCrLf &
                "            T.BILLING_USER AS BillingCommandCenter_BillingUser, " & vbCrLf &
                "            T.CREATE_DATE AS BillingCommandCenter_CreateDate, " & vbCrLf &
                "            T.P_SELECT_BY AS BillingCommandCenter_ProductionSelectBy, " & vbCrLf &
                "            T.PROD_FLAG AS BillingCommandCenter_IsProduction, " & vbCrLf &
                "            T.P_ET_CUTOFF_DATE AS BillingCommandCenter_EmployeeTimeDateCutoff, " & vbCrLf &
                "            T.P_IO_CUTOFF_DATE AS BillingCommandCenter_IncomeOnlyDateCutoff, " & vbCrLf &
                "            T.P_AB_CUTOFF_DATE AS BillingCommandCenter_AdvanceBillingDateCutoff, " & vbCrLf &
                "            T.P_AP_CUTOFF_PPD AS BillingCommandCenter_APPostPeriodCodeCutoff, " & vbCrLf &
                "            T.BA_BATCH_ID AS BillingCommandCenter_BillingApprovalBatchID, " & vbCrLf &
                "            T.MEDIA_FLAG AS BillingCommandCenter_IsMedia, " & vbCrLf &
                "            T.M_SELECT_BY AS BillingCommandCenter_MediaSelectBy, " & vbCrLf &
                "            T.M_CUTOFF_DATE AS BillingCommandCenter_MediaEndDate, " & vbCrLf &
                "            T.NEWSPAPER AS BillingCommandCenter_IsNewspaper, " & vbCrLf &
                "            T.MAGAZINE AS BillingCommandCenter_IsMagazine, " & vbCrLf &
                "            T.RADIO AS BillingCommandCenter_IsRadio, " & vbCrLf &
                "            T.TELEVISION AS BillingCommandCenter_IsTelevision, " & vbCrLf &
                "            T.OUT_OF_HOME AS BillingCommandCenter_IsOutOfHome, " & vbCrLf &
                "            T.INTERNET AS BillingCommandCenter_IsInternet, " & vbCrLf &
                "            T.M_BRDCAST_MTH1 AS BillingCommandCenter_MediaBroadcastMonthStart, " & vbCrLf &
                "            T.M_BRDCAST_MTH2 AS BillingCommandCenter_MediaBroadcastMonthEnd, " & vbCrLf &
                "            T.INCL_ZERO_SPOTS AS BillingCommandCenter_IncludeZeroSpots, " & vbCrLf &
                "            T.M_START_DATE AS BillingCommandCenter_MediaStartDate, " & vbCrLf &
                "            T.DATE_CUTOFF_TO_USE AS BillingCommandCenter_DateCuttoffToUseFlag, " & vbCrLf &
                "            T.INCL_UNBILLED_ONLY AS BillingCommandCenter_IncludeUnbilledOrdersOnly, " & vbCrLf &
                "            T.SEL_OPTION AS BillingCommandCenter_ProductionSelectionOption, " & vbCrLf &
                "            T.RADIO_DAILY AS BillingCommandCenter_IsRadioDaily, " & vbCrLf &
                "            T.TV_DAILY AS BillingCommandCenter_IsTelevisionDaily, " & vbCrLf &
                "            T.RADIO_MONTHLY AS BillingCommandCenter_IsRadioMonthly, " & vbCrLf &
                "            T.TV_MONTHLY AS BillingCommandCenter_IsTelevisionMonthly, " & vbCrLf &
                "            T.BATCH_NAME AS BillingCommandCenter_BatchName, " & vbCrLf &
                "            T.SEQ_NO AS BillingCommandCenter_SequenceNumber, " & vbCrLf &
                "            T.PROD_JOB_TYPE AS BillingCommandCenter_ProductionJobType, " & vbCrLf &
                "            T.PROD_LOCK_SELECTION AS BillingCommandCenter_IsProductionSelectionLocked, " & vbCrLf &
                "            T.INCLUDE_LEGACY AS BillingCommandCenter_IncludeLegacy, " & vbCrLf &
                "            T.JOB_MEDIA_BILL_DATE_FROM AS BillingCommandCenter_JobMediaBillDateFrom, " & vbCrLf &
                "            T.JOB_MEDIA_BILL_DATE_TO AS BillingCommandCenter_JobMediaBillDateTo, " & vbCrLf &
                "            T.PRODUCTION_INCLUDE_MEDIA_BILL_DATES AS BillingCommandCenter_ProductionIncludeJobMediaBillDates, " & vbCrLf &
                "            T.PRODUCTION_MEDIA_BILL_DATE_FROM AS BillingCommandCenter_ProductionJobMediaBillDateFrom, " & vbCrLf &
                "            T.PRODUCTION_MEDIA_BILL_DATE_TO AS BillingCommandCenter_ProductionJobMediaBillDateTo, " & vbCrLf &
                "            True AS _from0" & vbCrLf &
                "        FROM CodeFirstDatabase.BillingCommandCenter AS T" & vbCrLf &
                "    ) AS T1")
        End Function
    End Class
End Namespace
