CREATE PROC advsp_ap_import_delete_batch @batch_name varchar(50)

AS

DELETE dbo.IMP_AP_ERROR 
WHERE IMPORT_ID IN
	(
	SELECT IMPORT_ID FROM dbo.IMP_AP_HEADER 
	WHERE BATCH_NAME = @batch_name
	)
    
DELETE dbo.IMP_AP_GL 
WHERE IMPORT_ID IN
	(
	SELECT IMPORT_ID FROM dbo.IMP_AP_HEADER 
	WHERE BATCH_NAME = @batch_name
	)

DELETE dbo.IMP_AP_JOB
WHERE IMPORT_ID IN
	(
	SELECT IMPORT_ID FROM dbo.IMP_AP_HEADER 
	WHERE BATCH_NAME = @batch_name
	)
    
DELETE dbo.IMP_AP_BROADCAST_DTL
WHERE IMP_AP_MEDIA_ID IN
    (
    SELECT IMP_AP_MEDIA_ID
    FROM dbo.IMP_AP_MEDIA
    WHERE IMPORT_ID IN
	    (
	    SELECT IMPORT_ID FROM dbo.IMP_AP_HEADER 
	    WHERE BATCH_NAME = @batch_name
	    )
    )

DELETE dbo.IMP_AP_MEDIA
WHERE IMPORT_ID IN
	(
	SELECT IMPORT_ID FROM dbo.IMP_AP_HEADER 
	WHERE BATCH_NAME = @batch_name
	)

DELETE dbo.IMP_AP_HEADER 
WHERE BATCH_NAME = @batch_name

GO