CREATE PROCEDURE [dbo].[advsp_invoice_printing_load_estimatepriorcurrentttdinvoicedetails]
	@UserCode AS varchar(100),
	@InvoiceNumber AS int,
	@SequenceNumber AS smallint,
	@AddressBlockType AS smallint,
	@PrintClientName AS bit,
	@PrintDivisionName AS bit,
	@PrintProductDescription AS bit,
	@PrintContactAfterAddress AS bit,
	@PrintFunctionType AS smallint,
	@SortFunctionByType AS smallint,
	@ApplyExchangeRate AS smallint,
	@ExchangeRateAmount AS decimal(10, 6),
	@TotalsShowTaxSeparately AS bit,
	@TotalsShowCommissionSeparately AS bit,
	@UseInvoiceCategoryDescription AS bit,
	@InvoiceTitle AS varchar(MAX),
	@InvoiceFooterCommentType AS smallint,
	@InvoiceFooterComment AS varchar(MAX),
	@GroupingOptionInsideDescription AS varchar(MAX),
	@GroupingOptionOutsideDescription AS varchar(MAX),
	@ShowCodes AS bit,
	@ContactType AS int,
	@IsDraft AS bit,
	@Batch AS varchar(100),
	@IncludeEstimateComment AS bit,
	@IncludeEstimateComponentComment AS bit,
	@IncludeEstimateQuoteComment AS bit,
	@IncludeEstimateRevisionComment AS bit,
	@IncludeEstimateFunctionComment AS bit
AS
BEGIN
	
	SET NOCOUNT ON

	CREATE TABLE #JOBS_FUNCTIONS([JOB_NUMBER] [int] NOT NULL,
							     [JOB_COMPONENT_NBR] [smallint] NOT NULL,
							     [FNC_CODE] [varchar](6) COLLATE DATABASE_DEFAULT,
							     [FNC_TYPE] [varchar](1) COLLATE DATABASE_DEFAULT)

	CREATE TABLE #INVOICE_ITEMS([JOB_NUMBER] [int] NOT NULL,
								[JOB_COMPONENT_NBR] [smallint] NOT NULL,
								[FNC_CODE] [varchar](6) COLLATE DATABASE_DEFAULT,
								[FNC_TYPE] [varchar](1) COLLATE DATABASE_DEFAULT,
								[FNC_DESCRIPTION] [varchar](30) COLLATE DATABASE_DEFAULT,
								[FNC_ORDER] [smallint] NOT NULL,
								[FNC_HEADING_DESC] [varchar](60) COLLATE DATABASE_DEFAULT,
								[FNC_HEADING_SEQ] [int] NULL,
								[HRS_QTY] [decimal](18, 2) NOT NULL,
								[RATE] [decimal](18, 2) NOT NULL,
								[EXT_AMT] [decimal](18, 2) NOT NULL,
								[EXT_MARKUP_AMT] [decimal](18, 2) NOT NULL,
								[EXT_NONRESALE_TAX] [decimal](18, 2) NOT NULL,
								[EXT_STATE_RESALE] [decimal](18, 2) NOT NULL,
								[EXT_COUNTY_RESALE] [decimal](18, 2) NOT NULL,
								[EXT_CITY_RESALE] [decimal](18, 2) NOT NULL,
								[LINE_TOTAL] [decimal](18, 2) NOT NULL,
								[TTD_HRS_QTY] [decimal](18, 2) NOT NULL,
								[TTD_EXT_AMT] [decimal](18, 2) NOT NULL,
								[TTD_EXT_MARKUP_AMT] [decimal](18, 2) NOT NULL,
								[TTD_EXT_NONRESALE_TAX] [decimal](18, 2) NOT NULL,
								[TTD_EXT_STATE_RESALE] [decimal](18, 2) NOT NULL,
								[TTD_EXT_COUNTY_RESALE] [decimal](18, 2) NOT NULL,
								[TTD_EXT_CITY_RESALE] [decimal](18, 2) NOT NULL,
								[TTD_LINE_TOTAL] [decimal](18, 2) NOT NULL,
								[EST_EXT_AMT] [decimal](18, 2) NOT NULL,
								[EST_EXT_MARKUP_AMT] [decimal](18, 2) NOT NULL,
								[EST_EXT_NONRESALE_TAX] [decimal](18, 2) NOT NULL,
								[EST_EXT_STATE_RESALE] [decimal](18, 2) NOT NULL,
								[EST_EXT_COUNTY_RESALE] [decimal](18, 2) NOT NULL,
								[EST_EXT_CITY_RESALE] [decimal](18, 2) NOT NULL,
								[EST_LINE_TOTAL] [decimal](18, 2) NOT NULL,
								[PR_EXT_AMT] [decimal](18, 2) NOT NULL,
								[PR_EXT_MARKUP_AMT] [decimal](18, 2) NOT NULL,
								[PR_EXT_NONRESALE_TAX] [decimal](18, 2) NOT NULL,
								[PR_EXT_STATE_RESALE] [decimal](18, 2) NOT NULL,
								[PR_EXT_COUNTY_RESALE] [decimal](18, 2) NOT NULL,
								[PR_EXT_CITY_RESALE] [decimal](18, 2) NOT NULL,
								[PR_LINE_TOTAL] [decimal](18, 2) NOT NULL)
				
	CREATE TABLE #INVOICE([AR_INV_NBR] [int] NOT NULL, 
						  [AR_INV_SEQ] [smallint] NULL, 
						  [AR_TYPE] [varchar](2) COLLATE DATABASE_DEFAULT,
						  [AR_INV_DATE] [smalldatetime] NULL,
						  [CL_CODE] [varchar](6) COLLATE DATABASE_DEFAULT,
						  [DIV_CODE] [varchar](6) COLLATE DATABASE_DEFAULT,
						  [PRD_CODE] [varchar](6) COLLATE DATABASE_DEFAULT,
						  [OFFICE_CODE] [varchar](4) COLLATE DATABASE_DEFAULT,
						  [INV_CAT] [varchar](6) COLLATE DATABASE_DEFAULT,
						  [INV_CAT_DESC] [varchar](30) COLLATE DATABASE_DEFAULT,
						  [CDP_CONTACT_ID] [int] NULL,
						  [JOB_NUMBER] [int] NOT NULL,
						  [JOB_COMPONENT_NBR] [smallint] NOT NULL)
					
	DECLARE @InvoiceDate AS smalldatetime, @Font varchar(50), @Font2 varchar(10)	
	
	SET @Font = '<span style="font-family: Arial; font-size: 9pt;">'
	SET @Font2 = '</span>'			
			
	IF @IsDraft = 1 BEGIN
	
		INSERT INTO #JOBS_FUNCTIONS
		SELECT 
			DISTINCT 
			AR_FUNCTION.JOB_NUMBER,
			AR_FUNCTION.JOB_COMPONENT_NBR,
			AR_FUNCTION.FNC_CODE,
			AR_FUNCTION.FNC_TYPE
		FROM
			dbo.AR_FUNCTION
		WHERE
			 AR_FUNCTION.FNC_TYPE <> 'R' AND
			 AR_FUNCTION.JOB_NUMBER IS NOT NULL AND
			 AR_FUNCTION.JOB_COMPONENT_NBR IS NOT NULL AND
			 AR_FUNCTION.JOB_NUMBER IN (SELECT 
											DISTINCT AR_FUNCTION.JOB_NUMBER
										FROM
											dbo.AR_FUNCTION
										WHERE
											 AR_FUNCTION.AR_INV_NBR = @InvoiceNumber AND
											 AR_FUNCTION.DRAFT_INV_SEQ = @SequenceNumber AND
											 AR_FUNCTION.BILLING_USER = @Batch)
		 
		INSERT INTO #JOBS_FUNCTIONS
		SELECT 
			DISTINCT 
			AR_SUMMARY.JOB_NUMBER,
			AR_SUMMARY.JOB_COMPONENT_NBR,
			AR_SUMMARY.FNC_CODE,
			AR_SUMMARY.FNC_TYPE
		FROM
			dbo.AR_SUMMARY
		WHERE
			 AR_SUMMARY.FNC_TYPE <> 'R' AND
			 AR_SUMMARY.FNC_CODE NOT IN (SELECT DISTINCT FNC_CODE FROM #JOBS_FUNCTIONS JF WHERE JF.JOB_NUMBER = AR_SUMMARY.JOB_NUMBER AND JF.JOB_COMPONENT_NBR = AR_SUMMARY.JOB_COMPONENT_NBR) AND						 
			 AR_SUMMARY.JOB_NUMBER IN (SELECT 
											DISTINCT AR_FUNCTION.JOB_NUMBER
										FROM
											dbo.AR_FUNCTION
										WHERE
											 AR_FUNCTION.AR_INV_NBR = @InvoiceNumber AND
											 AR_FUNCTION.DRAFT_INV_SEQ = @SequenceNumber AND
											 AR_FUNCTION.BILLING_USER = @Batch)
		
		INSERT INTO #JOBS_FUNCTIONS
		SELECT 
			DISTINCT 
			EA.JOB_NUMBER,
			EA.JOB_COMPONENT_NBR,
			ERD.FNC_CODE,
			[FNC_TYPE] = ERD.EST_FNC_TYPE
		FROM
			[dbo].[ESTIMATE_APPROVAL] AS EA INNER JOIN 
			[dbo].[ESTIMATE_REV_DET] AS ERD ON ERD.EST_REV_NBR= EA.EST_REVISION_NBR AND 
												ERD.EST_QUOTE_NBR = EA.EST_QUOTE_NBR AND 
												ERD.EST_COMPONENT_NBR = EA.EST_COMPONENT_NBR AND 
												ERD.ESTIMATE_NUMBER = EA.ESTIMATE_NUMBER
		WHERE
			ERD.EST_FNC_TYPE <> 'R' AND
			ERD.FNC_CODE NOT IN (SELECT FNC_CODE FROM #JOBS_FUNCTIONS JF WHERE JF.JOB_NUMBER = EA.JOB_NUMBER AND JF.JOB_COMPONENT_NBR = EA.JOB_COMPONENT_NBR) AND 
			CAST(EA.JOB_NUMBER AS varchar(20)) + '|' + CAST(EA.JOB_COMPONENT_NBR AS varchar(20)) IN (SELECT CAST(JF.JOB_NUMBER AS varchar(20)) + '|' + CAST(JF.JOB_COMPONENT_NBR AS varchar(20)) FROM #JOBS_FUNCTIONS JF)

	END ELSE BEGIN
	
		INSERT INTO #JOBS_FUNCTIONS
		SELECT 
			DISTINCT 
			AR_SUMMARY.JOB_NUMBER,
			AR_SUMMARY.JOB_COMPONENT_NBR,
			AR_SUMMARY.FNC_CODE,
			AR_SUMMARY.FNC_TYPE
		FROM
			dbo.AR_SUMMARY
		WHERE
			 AR_SUMMARY.FNC_TYPE <> 'R' AND
			 AR_SUMMARY.JOB_NUMBER IN (SELECT 
											DISTINCT AR_SUMMARY.JOB_NUMBER
										FROM
											dbo.AR_SUMMARY
										WHERE
											 AR_SUMMARY.AR_INV_NBR = @InvoiceNumber AND
											 AR_SUMMARY.AR_INV_SEQ = @SequenceNumber)
		 
		INSERT INTO #JOBS_FUNCTIONS
		SELECT 
			DISTINCT 
			EA.JOB_NUMBER,
			EA.JOB_COMPONENT_NBR,
			ERD.FNC_CODE,
			[FNC_TYPE] = ERD.EST_FNC_TYPE
		FROM
			[dbo].[ESTIMATE_APPROVAL] AS EA INNER JOIN 
			[dbo].[ESTIMATE_REV_DET] AS ERD ON ERD.EST_REV_NBR= EA.EST_REVISION_NBR AND 
												ERD.EST_QUOTE_NBR = EA.EST_QUOTE_NBR AND 
												ERD.EST_COMPONENT_NBR = EA.EST_COMPONENT_NBR AND 
												ERD.ESTIMATE_NUMBER = EA.ESTIMATE_NUMBER
		WHERE
			ERD.EST_FNC_TYPE <> 'R' AND
			ERD.FNC_CODE NOT IN (SELECT FNC_CODE FROM #JOBS_FUNCTIONS JF WHERE JF.JOB_NUMBER = EA.JOB_NUMBER AND JF.JOB_COMPONENT_NBR = EA.JOB_COMPONENT_NBR) AND 
			CAST(EA.JOB_NUMBER AS varchar(20)) + '|' + CAST(EA.JOB_COMPONENT_NBR AS varchar(20)) IN (SELECT CAST(JF.JOB_NUMBER AS varchar(20)) + '|' + CAST(JF.JOB_COMPONENT_NBR AS varchar(20)) FROM #JOBS_FUNCTIONS JF)

	END
	
	IF @IsDraft = 1 BEGIN

		INSERT INTO #INVOICE
		SELECT
			ARS.AR_INV_NBR,
			ARS.DRAFT_INV_SEQ,
			[AR_TYPE] = 'IN',
			[AR_INV_DATE] = GETDATE(),
			ARS.CL_CODE,
			ARS.DIV_CODE,
			ARS.PRD_CODE,
			ARS.OFFICE_CODE,
			[INV_CAT] = NULL,
			[INV_CAT_DESC] = NULL,
			[CDP_CONTACT_ID] = NULL,
			ARS.JOB_NUMBER,
			ARS.JOB_COMPONENT_NBR
		FROM 
			[dbo].[AR_FUNCTION] AS ARS
		WHERE 
			ARS.DRAFT_INV_SEQ <> 99 AND
			ARS.JOB_NUMBER IS NOT NULL AND
			ARS.JOB_COMPONENT_NBR IS NOT NULL AND
			ARS.AR_INV_NBR = @InvoiceNumber AND
			ARS.DRAFT_INV_SEQ = @SequenceNumber AND
			ARS.BILLING_USER = @Batch
		GROUP BY
			ARS.AR_INV_NBR,
			ARS.DRAFT_INV_SEQ,
			ARS.CL_CODE,
			ARS.DIV_CODE,
			ARS.PRD_CODE,
			ARS.OFFICE_CODE,
			ARS.JOB_NUMBER,
			ARS.JOB_COMPONENT_NBR

	END ELSE BEGIN
	
		INSERT INTO #INVOICE
		SELECT
			ARS.AR_INV_NBR,
			ARS.AR_INV_SEQ,
			ARS.AR_TYPE,
			ARID.AR_INV_DATE,
			ARS.CL_CODE,
			ARS.DIV_CODE,
			ARS.PRD_CODE,
			ARS.OFFICE_CODE,
			AR.INV_CAT,
			IC.INV_CAT_DESC,
			AR.CDP_CONTACT_ID,
			ARS.JOB_NUMBER,
			ARS.JOB_COMPONENT_NBR
		FROM 
			[dbo].[AR_SUMMARY] AS ARS INNER JOIN 
			#JOBS_FUNCTIONS AS JF ON JF.JOB_NUMBER = ARS.JOB_NUMBER AND
									 JF.JOB_COMPONENT_NBR = ARS.JOB_COMPONENT_NBR AND
									 JF.FNC_CODE = ARS.FNC_CODE AND
									 JF.FNC_TYPE = ARS.FNC_TYPE INNER JOIN 
			(SELECT 
					AR.AR_INV_NBR, 
					AR.AR_TYPE, 
					[AR_POST_PERIOD] = MAX(AR.AR_POST_PERIOD), 
					[AR_INV_DATE] = MAX(AR.AR_INV_DATE) 
				FROM 
					[dbo].[ACCT_REC] AS AR
				WHERE 
					AR.AR_TYPE <> 'VO'
				GROUP BY 
					AR.AR_INV_NBR, 
					AR.AR_TYPE) AS ARID ON ARID.AR_INV_NBR = ARS.AR_INV_NBR AND 
										   ARID.AR_TYPE = ARS.AR_TYPE INNER JOIN 
			(SELECT 
					DISTINCT 
					AJ.AR_INV_NBR,
					AR.CL_CODE,		
					AR.DIV_CODE,	
					AR.PRD_CODE,	
					AR.OFFICE_CODE	
				FROM 
					[dbo].[ARINV_JOB] AS AJ INNER JOIN 
					[dbo].[ACCT_REC] AS AR ON AR.AR_INV_SEQ = AJ.AR_INV_SEQ AND 
											  AR.AR_INV_NBR = AJ.AR_INV_NBR
				WHERE 
					AR.MANUAL_INV IS NULL
				GROUP BY 
					AJ.AR_INV_NBR, 
					AR.CL_CODE, 
					AR.DIV_CODE, 
					AR.PRD_CODE, 
					AR.OFFICE_CODE
				HAVING 
					MAX(AR.AR_TYPE) <> 'VO') AS ARI ON ARI.AR_INV_NBR = ARS.AR_INV_NBR INNER JOIN 
			[dbo].[ACCT_REC] AS AR ON AR.AR_INV_NBR = ARS.AR_INV_NBR AND 
									  AR.AR_INV_SEQ = ARS.AR_INV_SEQ AND
									  AR.AR_TYPE = ARS.AR_TYPE LEFT OUTER JOIN 
			[dbo].[INVOICE_CATEGORY] AS IC ON IC.INV_CAT = AR.INV_CAT
		WHERE 
			ARS.AR_INV_NBR = @InvoiceNumber AND
			ARS.AR_INV_SEQ = @SequenceNumber
		GROUP BY
			ARS.AR_INV_NBR,
			ARS.AR_INV_SEQ,
			ARS.AR_TYPE,
			ARID.AR_INV_DATE,
			ARS.CL_CODE,
			ARS.DIV_CODE,
			ARS.PRD_CODE,
			ARS.OFFICE_CODE,
			AR.INV_CAT,
			IC.INV_CAT_DESC,
			AR.CDP_CONTACT_ID,
			ARS.JOB_NUMBER,
			ARS.JOB_COMPONENT_NBR
		
	END
	
	SELECT 
		@InvoiceDate = MAX([AR_INV_DATE]) 
	FROM 
		#INVOICE
	
	IF @IsDraft = 1 BEGIN
	
		INSERT INTO #INVOICE_ITEMS
		SELECT
			TD.JOB_NUMBER,
			TD.JOB_COMPONENT_NBR,
			TD.FNC_CODE,
			TD.FNC_TYPE,
			F.FNC_DESCRIPTION,
			[FNC_ORDER] = CAST(ISNULL(F.FNC_ORDER, 0) AS smallint),
			FH.FNC_HEADING_DESC,
			FH.FNC_HEADING_SEQ,
			[HRS_QTY] = ISNULL(TD.[HRS_QTY], 0),
			[RATE] = ISNULL(TD.[RATE], 0),
			[EXT_AMT] = ISNULL(TD.[EXT_AMT], 0),
			[EXT_MARKUP_AMT] = ISNULL(TD.[EXT_MARKUP_AMT], 0),
			[EXT_NONRESALE_TAX] = ISNULL(TD.[EXT_NONRESALE_TAX], 0),
			[EXT_STATE_RESALE] = ISNULL(TD.[EXT_STATE_RESALE], 0),
			[EXT_COUNTY_RESALE] = ISNULL(TD.[EXT_COUNTY_RESALE], 0),
			[EXT_CITY_RESALE] = ISNULL(TD.[EXT_CITY_RESALE], 0),
			[LINE_TOTAL] = ISNULL(TD.[LINE_TOTAL], 0),
			[TTD_HRS_QTY] = ISNULL(TD.[TTD_HRS_QTY], 0),
			[TTD_EXT_AMT] = ISNULL(TD.[TTD_EXT_AMT], 0),
			[TTD_EXT_MARKUP_AMT] = ISNULL(TD.[TTD_EXT_MARKUP_AMT], 0),
			[TTD_EXT_NONRESALE_TAX] = ISNULL(TD.[TTD_EXT_NONRESALE_TAX], 0),
			[TTD_EXT_STATE_RESALE] = ISNULL(TD.[TTD_EXT_STATE_RESALE], 0),
			[TTD_EXT_COUNTY_RESALE] = ISNULL(TD.[TTD_EXT_COUNTY_RESALE], 0),
			[TTD_EXT_CITY_RESALE] = ISNULL(TD.[TTD_EXT_CITY_RESALE], 0),
			[TTD_LINE_TOTAL] = ISNULL(TD.[TTD_LINE_TOTAL], 0),
			[EST_EXT_AMT] = ISNULL(TD.[EST_EXT_AMT], 0),
			[EST_EXT_MARKUP_AMT] = ISNULL(TD.[EST_EXT_MARKUP_AMT], 0),
			[EST_EXT_NONRESALE_TAX] = ISNULL(TD.[EST_EXT_NONRESALE_TAX], 0),
			[EST_EXT_STATE_RESALE] = ISNULL(TD.[EST_EXT_STATE_RESALE], 0),
			[EST_EXT_COUNTY_RESALE] = ISNULL(TD.[EST_EXT_COUNTY_RESALE], 0),
			[EST_EXT_CITY_RESALE] = ISNULL(TD.[EST_EXT_CITY_RESALE], 0),
			[EST_LINE_TOTAL] = ISNULL(TD.[EST_LINE_TOTAL], 0),
			[PR_EXT_AMT] = ISNULL(TD.[PR_EXT_AMT], 0),
			[PR_EXT_MARKUP_AMT] = ISNULL(TD.[PR_EXT_MARKUP_AMT], 0),
			[PR_EXT_NONRESALE_TAX] = ISNULL(TD.[PR_EXT_NONRESALE_TAX], 0),
			[PR_EXT_STATE_RESALE] = ISNULL(TD.[PR_EXT_STATE_RESALE], 0),
			[PR_EXT_COUNTY_RESALE] = ISNULL(TD.[PR_EXT_COUNTY_RESALE], 0),
			[PR_EXT_CITY_RESALE] = ISNULL(TD.[PR_EXT_CITY_RESALE], 0),
			[PR_LINE_TOTAL] = ISNULL(TD.[PR_LINE_TOTAL], 0)
		FROM 
			(SELECT
				J.JOB_NUMBER,
				J.JOB_COMPONENT_NBR,
				J.FNC_CODE,
				J.FNC_TYPE,
				CTD.[HRS_QTY],
				CTD.[RATE],
				[EXT_AMT] = ISNULL(CTD.[EXT_AMT], 0),
				[EXT_MARKUP_AMT] = ISNULL(CTD.[EXT_MARKUP_AMT], 0),
				[EXT_NONRESALE_TAX] = ISNULL(CTD.[EXT_NONRESALE_TAX], 0),
				[EXT_STATE_RESALE] = ISNULL(CTD.[EXT_STATE_RESALE], 0),
				[EXT_COUNTY_RESALE] = ISNULL(CTD.[EXT_COUNTY_RESALE], 0),
				[EXT_CITY_RESALE] = ISNULL(CTD.[EXT_CITY_RESALE], 0),
				[LINE_TOTAL] = ISNULL(CTD.[LINE_TOTAL], 0),
				[TTD_HRS_QTY] = ISNULL(TTD.[HRS_QTY], 0) + ISNULL(CTD.[HRS_QTY], 0),
				[TTD_EXT_AMT] = ISNULL(TTD.[EXT_AMT], 0) + ISNULL(CTD.[EXT_AMT], 0),
				[TTD_EXT_MARKUP_AMT] = ISNULL(TTD.[EXT_MARKUP_AMT], 0) + ISNULL(CTD.[EXT_MARKUP_AMT], 0),
				[TTD_EXT_NONRESALE_TAX] = ISNULL(TTD.[EXT_NONRESALE_TAX], 0) + ISNULL(CTD.[EXT_NONRESALE_TAX], 0),
				[TTD_EXT_STATE_RESALE] = ISNULL(TTD.[EXT_STATE_RESALE], 0) + ISNULL(CTD.[EXT_STATE_RESALE], 0),
				[TTD_EXT_COUNTY_RESALE] = ISNULL(TTD.[EXT_COUNTY_RESALE], 0) + ISNULL(CTD.[EXT_COUNTY_RESALE], 0),
				[TTD_EXT_CITY_RESALE] = ISNULL(TTD.[EXT_CITY_RESALE], 0) + ISNULL(CTD.[EXT_CITY_RESALE], 0),
				[TTD_LINE_TOTAL] = ISNULL(TTD.[LINE_TOTAL], 0) + ISNULL(CTD.[LINE_TOTAL], 0),
				[EST_EXT_AMT] = ISNULL(EST.[EXT_AMT], 0),
				[EST_EXT_MARKUP_AMT] = ISNULL(EST.[EXT_MARKUP_AMT], 0),
				[EST_EXT_NONRESALE_TAX] = ISNULL(EST.[EXT_NONRESALE_TAX], 0),
				[EST_EXT_STATE_RESALE] = ISNULL(EST.[EXT_STATE_RESALE], 0),
				[EST_EXT_COUNTY_RESALE] = ISNULL(EST.[EXT_COUNTY_RESALE], 0),
				[EST_EXT_CITY_RESALE] = ISNULL(EST.[EXT_CITY_RESALE], 0),
				[EST_LINE_TOTAL] = ISNULL(EST.[LINE_TOTAL], 0),
				[PR_EXT_AMT] = ISNULL(PR.[EXT_AMT], 0),
				[PR_EXT_MARKUP_AMT] = ISNULL(PR.[EXT_MARKUP_AMT], 0),
				[PR_EXT_NONRESALE_TAX] = ISNULL(PR.[EXT_NONRESALE_TAX], 0),
				[PR_EXT_STATE_RESALE] = ISNULL(PR.[EXT_STATE_RESALE], 0),
				[PR_EXT_COUNTY_RESALE] = ISNULL(PR.[EXT_COUNTY_RESALE], 0),
				[PR_EXT_CITY_RESALE] = ISNULL(PR.[EXT_CITY_RESALE], 0),
				[PR_LINE_TOTAL] = ISNULL(PR.[LINE_TOTAL], 0)
			FROM 
				(SELECT
						JF.JOB_NUMBER,
						JF.JOB_COMPONENT_NBR,
						JF.FNC_CODE,
						JF.FNC_TYPE,
						[HRS_QTY] = ESTF.[EST_HRS_QTY],
						[RATE] = ESTF.[EST_RATE],
						[EXT_AMT] = ISNULL(CASE JF.FNC_TYPE WHEN 'V' THEN ESTF.[EST_LINE_TOTAL] - ESTF.[EST_EXT_STATE_RESALE] - ESTF.[EST_EXT_COUNTY_RESALE] - ESTF.[EST_EXT_CITY_RESALE] - ESTF.[EST_EXT_MARKUP_AMT]
																	 ELSE ESTF.[EST_LINE_TOTAL] - ESTF.[EST_EXT_STATE_RESALE] - ESTF.[EST_EXT_COUNTY_RESALE] - ESTF.[EST_EXT_CITY_RESALE] END, 0),
						[EXT_MARKUP_AMT] = ISNULL(CASE JF.FNC_TYPE WHEN 'V' THEN ESTF.[EST_EXT_MARKUP_AMT]
																   ELSE 0 END, 0),
						[EXT_NONRESALE_TAX] = ISNULL(ESTF.[EST_EXT_NONRESALE_TAX], 0),
						[EXT_STATE_RESALE] = ISNULL(ESTF.[EST_EXT_STATE_RESALE], 0),
						[EXT_COUNTY_RESALE] = ISNULL(ESTF.[EST_EXT_COUNTY_RESALE], 0),
						[EXT_CITY_RESALE] = ISNULL(ESTF.[EST_EXT_CITY_RESALE], 0),
						[LINE_TOTAL] = ISNULL(ESTF.[EST_LINE_TOTAL], 0)
					FROM
						#JOBS_FUNCTIONS AS JF LEFT OUTER JOIN
						(SELECT 
								EA.JOB_NUMBER, 
								EA.JOB_COMPONENT_NBR, 
								ERD.FNC_CODE,
								[FNC_TYPE] = ERD.EST_FNC_TYPE, 
								[EST_HRS_QTY] = CAST(SUM(ISNULL(ERD.EST_REV_QUANTITY, 0)) AS decimal(15, 2)), 
								[EST_RATE] = CAST(0 AS decimal(15, 3)), 
								[EST_EXT_AMT] = CAST(SUM(ISNULL(ERD.EST_REV_EXT_AMT, 0) + ISNULL(ERD.EXT_CONTINGENCY, 0)) AS decimal(15, 2)),
								[EST_EXT_MARKUP_AMT] = CAST(SUM(ISNULL(ERD.EXT_MARKUP_AMT, 0) + ISNULL(ERD.EXT_MU_CONT, 0)) AS decimal(15, 2)),
								[EST_EXT_NONRESALE_TAX] = CAST(SUM(ISNULL(ERD.EXT_NONRESALE_TAX, 0) + ISNULL(ERD.EXT_NR_CONT, 0)) AS decimal(15, 2)), 
								[EST_EXT_STATE_RESALE] = CAST(SUM(ISNULL(ERD.EXT_STATE_RESALE, 0) + ISNULL(ERD.EXT_STATE_CONT, 0)) AS decimal(15, 2)), 
								[EST_EXT_COUNTY_RESALE] = CAST(SUM(ISNULL(ERD.EXT_COUNTY_RESALE, 0) + ISNULL(ERD.EXT_COUNTY_CONT, 0)) AS decimal(15, 2)), 
								[EST_EXT_CITY_RESALE] = CAST(SUM(ISNULL(ERD.EXT_CITY_RESALE, 0) + ISNULL(ERD.EXT_CITY_CONT, 0)) AS decimal(15, 2)),
								[EST_LINE_TOTAL] = CAST(SUM(ISNULL(ERD.LINE_TOTAL, 0) + ISNULL(ERD.LINE_TOTAL_CONT, 0)) AS decimal(15, 2))
							FROM 
								[dbo].[ESTIMATE_APPROVAL] AS EA INNER JOIN 
								[dbo].[ESTIMATE_REV_DET] AS ERD ON ERD.EST_REV_NBR= EA.EST_REVISION_NBR AND 
																   ERD.EST_QUOTE_NBR = EA.EST_QUOTE_NBR AND 
																   ERD.EST_COMPONENT_NBR = EA.EST_COMPONENT_NBR AND 
																   ERD.ESTIMATE_NUMBER = EA.ESTIMATE_NUMBER INNER JOIN 
								[dbo].[ESTIMATE_LOG] EL ON EL.ESTIMATE_NUMBER = EA.ESTIMATE_NUMBER INNER JOIN 
								[dbo].[FUNCTIONS] F ON F.FNC_CODE = ERD.FNC_CODE
							GROUP BY 
								EA.JOB_NUMBER, 
								EA.JOB_COMPONENT_NBR, 
								ERD.FNC_CODE, 
								ERD.EST_FNC_TYPE) AS ESTF ON ESTF.JOB_NUMBER = JF.JOB_NUMBER AND 
															 ESTF.JOB_COMPONENT_NBR = JF.JOB_COMPONENT_NBR AND 
															 ESTF.FNC_CODE = JF.FNC_CODE) AS EST LEFT OUTER JOIN 
					#JOBS_FUNCTIONS AS J ON J.JOB_NUMBER = EST.JOB_NUMBER AND 
											J.JOB_COMPONENT_NBR = EST.JOB_COMPONENT_NBR AND 
											J.FNC_CODE = EST.FNC_CODE LEFT OUTER JOIN
					(SELECT
						ARS.JOB_NUMBER,
						ARS.JOB_COMPONENT_NBR,
						ARS.FNC_CODE,
						ARS.FNC_TYPE,
						[HRS_QTY] = SUM(CAST(ARS.HRS_QTY AS decimal(18,2))),
						[RATE] = SUM(CAST(0 AS decimal(18,2))),
						[EXT_AMT] = SUM(CAST(CASE ARS.FNC_TYPE WHEN 'V' THEN ISNULL(ARS.TOTAL_BILL, 0) - ISNULL(ARS.STATE_TAX_AMT, 0) - ISNULL(ARS.CNTY_TAX_AMT, 0) - ISNULL(ARS.CITY_TAX_AMT, 0) - ISNULL(ARS.COMMISSION_AMT, 0) - ISNULL(ARS.AB_COMMISSION_AMT, 0)
															   ELSE ISNULL(ARS.TOTAL_BILL, 0) - ISNULL(ARS.STATE_TAX_AMT, 0) - ISNULL(ARS.CNTY_TAX_AMT, 0) - ISNULL(ARS.CITY_TAX_AMT, 0) END AS decimal(18,2))),
						[EXT_MARKUP_AMT] = SUM(CAST(CASE ARS.FNC_TYPE WHEN 'V' THEN ISNULL(ARS.COMMISSION_AMT,0) + ISNULL(ARS.AB_COMMISSION_AMT,0)
																	  ELSE 0 END AS decimal(18,2))),
						[EXT_NONRESALE_TAX] = SUM(CAST(ARS.NON_RESALE_AMT AS decimal(18,2))),
						[EXT_STATE_RESALE] = SUM(CAST(ISNULL(ARS.STATE_TAX_AMT, 0) AS decimal(18,2))),
						[EXT_COUNTY_RESALE] = SUM(CAST(ISNULL(ARS.CNTY_TAX_AMT, 0) AS decimal(18,2))),
						[EXT_CITY_RESALE] = SUM(CAST(ISNULL(ARS.CITY_TAX_AMT, 0) AS decimal(18,2))),
						[LINE_TOTAL] = SUM(CAST(ISNULL(ARS.TOTAL_BILL, 0) AS decimal(18,2)))
					FROM
						dbo.AR_SUMMARY AS ARS INNER JOIN
						#JOBS_FUNCTIONS AS J ON  J.JOB_NUMBER = ARS.JOB_NUMBER AND 
												 J.JOB_COMPONENT_NBR = ARS.JOB_COMPONENT_NBR AND
												 J.FNC_CODE = ARS.FNC_CODE INNER JOIN
						(SELECT 
								AR.AR_INV_NBR, 
								AR.AR_TYPE, 
								[AR_INV_DATE] = MAX(AR.AR_INV_DATE) 
							FROM 
								[dbo].[ACCT_REC] AS AR
							GROUP BY 
								AR.AR_INV_NBR, 
								AR.AR_TYPE) AS ARID ON ARID.AR_INV_NBR = ARS.AR_INV_NBR AND 
													   ARID.AR_TYPE = ARS.AR_TYPE
					WHERE 
						ARS.FNC_TYPE <> 'R' AND
						ARS.AR_INV_SEQ <> 99
					GROUP BY
						ARS.JOB_NUMBER,
						ARS.JOB_COMPONENT_NBR,
						ARS.FNC_CODE,
						ARS.FNC_TYPE) AS TTD ON TTD.JOB_NUMBER = J.JOB_NUMBER AND 
												TTD.JOB_COMPONENT_NBR = J.JOB_COMPONENT_NBR AND
												TTD.FNC_CODE = J.FNC_CODE LEFT OUTER JOIN
					(SELECT
						ARS.JOB_NUMBER,
						ARS.JOB_COMPONENT_NBR,
						ARS.FNC_CODE,
						ARS.FNC_TYPE,
						[HRS_QTY] = SUM(CAST(ARS.HRS_QTY AS decimal(18,2))),
						[RATE] = SUM(CAST(0 AS decimal(18,2))),
						[EXT_AMT] = SUM(CAST(CASE ARS.FNC_TYPE WHEN 'V' THEN ISNULL(ARS.TOTAL_BILL, 0) - ISNULL(ARS.STATE_TAX_AMT, 0) - ISNULL(ARS.CNTY_TAX_AMT, 0) - ISNULL(ARS.CITY_TAX_AMT, 0) - ISNULL(ARS.COMMISSION_AMT, 0) - ISNULL(ARS.AB_COMMISSION_AMT, 0)
															   ELSE ISNULL(ARS.TOTAL_BILL, 0) - ISNULL(ARS.STATE_TAX_AMT, 0) - ISNULL(ARS.CNTY_TAX_AMT, 0) - ISNULL(ARS.CITY_TAX_AMT, 0) END AS decimal(18,2))),
						[EXT_MARKUP_AMT] = SUM(CAST(CASE ARS.FNC_TYPE WHEN 'V' THEN ISNULL(ARS.COMMISSION_AMT,0) + ISNULL(ARS.AB_COMMISSION_AMT,0)
																	  ELSE 0 END AS decimal(18,2))),
						[EXT_NONRESALE_TAX] = SUM(CAST(ARS.NON_RESALE_AMT AS decimal(18,2))),
						[EXT_STATE_RESALE] = SUM(CAST(ISNULL(ARS.STATE_TAX_AMT, 0) AS decimal(18,2))),
						[EXT_COUNTY_RESALE] = SUM(CAST(ISNULL(ARS.CNTY_TAX_AMT, 0) AS decimal(18,2))),
						[EXT_CITY_RESALE] = SUM(CAST(ISNULL(ARS.CITY_TAX_AMT, 0) AS decimal(18,2))),
						[LINE_TOTAL] = SUM(CAST(ISNULL(ARS.TOTAL_BILL, 0) AS decimal(18,2)))
					FROM
						[dbo].[AR_SUMMARY] AS ARS INNER JOIN 
						[dbo].[ACCT_REC] AS AR ON AR.AR_INV_NBR = ARS.AR_INV_NBR AND 
												  AR.AR_INV_SEQ = ARS.AR_INV_SEQ AND
												  AR.AR_TYPE = ARS.AR_TYPE INNER JOIN
						#JOBS_FUNCTIONS AS J ON  J.JOB_NUMBER = ARS.JOB_NUMBER AND 
												 J.JOB_COMPONENT_NBR = ARS.JOB_COMPONENT_NBR AND
												 J.FNC_CODE = ARS.FNC_CODE 
					WHERE 
						ARS.FNC_TYPE <> 'R' AND
						ARS.AR_INV_SEQ <> 99
					GROUP BY
						ARS.JOB_NUMBER,
						ARS.JOB_COMPONENT_NBR,
						ARS.FNC_CODE,
						ARS.FNC_TYPE) AS PR ON PR.JOB_NUMBER = J.JOB_NUMBER AND 
											   PR.JOB_COMPONENT_NBR = J.JOB_COMPONENT_NBR AND
											   PR.FNC_CODE = J.FNC_CODE LEFT OUTER JOIN
					(SELECT
							ARS.JOB_NUMBER,
							ARS.JOB_COMPONENT_NBR,
							ARS.FNC_CODE,
							ARS.FNC_TYPE,
							[HRS_QTY] = SUM(CAST(ARS.HRS_QTY AS decimal(18,2))),
							[RATE] = SUM(CAST(0 AS decimal(18,2))),
							[EXT_AMT] = SUM(CAST(CASE ARS.FNC_TYPE WHEN 'V' THEN ISNULL(ARS.TOTAL_BILL, 0) - ISNULL(ARS.STATE_TAX_AMT, 0) - ISNULL(ARS.CNTY_TAX_AMT, 0) - ISNULL(ARS.CITY_TAX_AMT, 0) - ISNULL(ARS.COMMISSION_AMT, 0) - ISNULL(ARS.AB_COMMISSION_AMT, 0)
																   ELSE ISNULL(ARS.TOTAL_BILL, 0) - ISNULL(ARS.STATE_TAX_AMT, 0) - ISNULL(ARS.CNTY_TAX_AMT, 0) - ISNULL(ARS.CITY_TAX_AMT, 0) END AS decimal(18,2))),
							[EXT_MARKUP_AMT] = SUM(CAST(CASE ARS.FNC_TYPE WHEN 'V' THEN ISNULL(ARS.COMMISSION_AMT,0) + ISNULL(ARS.AB_COMMISSION_AMT,0)
																		  ELSE 0 END AS decimal(18,2))),
							[EXT_NONRESALE_TAX] = SUM(CAST(ARS.NON_RESALE_AMT AS decimal(18,2))),
							[EXT_STATE_RESALE] = SUM(CAST(ISNULL(ARS.STATE_TAX_AMT, 0) AS decimal(18,2))),
							[EXT_COUNTY_RESALE] = SUM(CAST(ISNULL(ARS.CNTY_TAX_AMT, 0) AS decimal(18,2))),
							[EXT_CITY_RESALE] = SUM(CAST(ISNULL(ARS.CITY_TAX_AMT, 0) AS decimal(18,2))),
							[LINE_TOTAL] = SUM(CAST(ISNULL(ARS.TOTAL_BILL, 0) AS decimal(18,2)))
						FROM
							dbo.AR_FUNCTION AS ARS
						WHERE 
							ARS.FNC_TYPE <> 'R' AND
							ARS.DRAFT_INV_SEQ <> 99  AND
							ARS.JOB_NUMBER IS NOT NULL AND
							ARS.JOB_COMPONENT_NBR IS NOT NULL AND
							ARS.AR_INV_NBR = @InvoiceNumber AND
							ARS.DRAFT_INV_SEQ = @SequenceNumber AND
							ARS.BILLING_USER = @Batch
						GROUP BY
							ARS.JOB_NUMBER,
							ARS.JOB_COMPONENT_NBR,
							ARS.FNC_CODE,
							ARS.FNC_TYPE) AS CTD ON CTD.JOB_NUMBER = J.JOB_NUMBER AND 
													CTD.JOB_COMPONENT_NBR = J.JOB_COMPONENT_NBR AND
													CTD.FNC_CODE = J.FNC_CODE
			WHERE J.JOB_NUMBER IS NOT NULL) AS TD LEFT OUTER JOIN
			[dbo].[FUNCTIONS] AS F ON F.FNC_CODE = TD.FNC_CODE LEFT OUTER JOIN 
			[dbo].[FNC_HEADING] AS FH ON FH.FNC_HEADING_ID = F.FNC_HEADING_ID
		
	END ELSE BEGIN
	
		INSERT INTO #INVOICE_ITEMS
		SELECT
			TD.JOB_NUMBER,
			TD.JOB_COMPONENT_NBR,
			TD.FNC_CODE,
			TD.FNC_TYPE,
			F.FNC_DESCRIPTION,
			[FNC_ORDER] = CAST(ISNULL(F.FNC_ORDER, 0) AS smallint),
			FH.FNC_HEADING_DESC,
			FH.FNC_HEADING_SEQ,
			[HRS_QTY] = ISNULL(TD.[HRS_QTY], 0),
			[RATE] = ISNULL(TD.[RATE], 0),
			[EXT_AMT] = ISNULL(TD.[EXT_AMT], 0),
			[EXT_MARKUP_AMT] = ISNULL(TD.[EXT_MARKUP_AMT], 0),
			[EXT_NONRESALE_TAX] = ISNULL(TD.[EXT_NONRESALE_TAX], 0),
			[EXT_STATE_RESALE] = ISNULL(TD.[EXT_STATE_RESALE], 0),
			[EXT_COUNTY_RESALE] = ISNULL(TD.[EXT_COUNTY_RESALE], 0),
			[EXT_CITY_RESALE] = ISNULL(TD.[EXT_CITY_RESALE], 0),
			[LINE_TOTAL] = ISNULL(TD.[LINE_TOTAL], 0),
			[TTD_HRS_QTY] = ISNULL(TD.[TTD_HRS_QTY], 0),
			[TTD_EXT_AMT] = ISNULL(TD.[TTD_EXT_AMT], 0),
			[TTD_EXT_MARKUP_AMT] = ISNULL(TD.[TTD_EXT_MARKUP_AMT], 0),
			[TTD_EXT_NONRESALE_TAX] = ISNULL(TD.[TTD_EXT_NONRESALE_TAX], 0),
			[TTD_EXT_STATE_RESALE] = ISNULL(TD.[TTD_EXT_STATE_RESALE], 0),
			[TTD_EXT_COUNTY_RESALE] = ISNULL(TD.[TTD_EXT_COUNTY_RESALE], 0),
			[TTD_EXT_CITY_RESALE] = ISNULL(TD.[TTD_EXT_CITY_RESALE], 0),
			[TTD_LINE_TOTAL] = ISNULL(TD.[TTD_LINE_TOTAL], 0),
			[EST_EXT_AMT] = ISNULL(TD.[EST_EXT_AMT], 0),
			[EST_EXT_MARKUP_AMT] = ISNULL(TD.[EST_EXT_MARKUP_AMT], 0),
			[EST_EXT_NONRESALE_TAX] = ISNULL(TD.[EST_EXT_NONRESALE_TAX], 0),
			[EST_EXT_STATE_RESALE] = ISNULL(TD.[EST_EXT_STATE_RESALE], 0),
			[EST_EXT_COUNTY_RESALE] = ISNULL(TD.[EST_EXT_COUNTY_RESALE], 0),
			[EST_EXT_CITY_RESALE] = ISNULL(TD.[EST_EXT_CITY_RESALE], 0),
			[EST_LINE_TOTAL] = ISNULL(TD.[EST_LINE_TOTAL], 0),
			[PR_EXT_AMT] = ISNULL(TD.[PR_EXT_AMT], 0),
			[PR_EXT_MARKUP_AMT] = ISNULL(TD.[PR_EXT_MARKUP_AMT], 0),
			[PR_EXT_NONRESALE_TAX] = ISNULL(TD.[PR_EXT_NONRESALE_TAX], 0),
			[PR_EXT_STATE_RESALE] = ISNULL(TD.[PR_EXT_STATE_RESALE], 0),
			[PR_EXT_COUNTY_RESALE] = ISNULL(TD.[PR_EXT_COUNTY_RESALE], 0),
			[PR_EXT_CITY_RESALE] = ISNULL(TD.[PR_EXT_CITY_RESALE], 0),
			[PR_LINE_TOTAL] = ISNULL(TD.[PR_LINE_TOTAL], 0)
		FROM 
			(SELECT
				J.JOB_NUMBER,
				J.JOB_COMPONENT_NBR,
				J.FNC_CODE,
				J.FNC_TYPE,
				CTD.[HRS_QTY],
				CTD.[RATE],
				[EXT_AMT] = ISNULL(CTD.[EXT_AMT], 0),
				[EXT_MARKUP_AMT] = ISNULL(CTD.[EXT_MARKUP_AMT], 0),
				[EXT_NONRESALE_TAX] = ISNULL(CTD.[EXT_NONRESALE_TAX], 0),
				[EXT_STATE_RESALE] = ISNULL(CTD.[EXT_STATE_RESALE], 0),
				[EXT_COUNTY_RESALE] = ISNULL(CTD.[EXT_COUNTY_RESALE], 0),
				[EXT_CITY_RESALE] = ISNULL(CTD.[EXT_CITY_RESALE], 0),
				[LINE_TOTAL] = ISNULL(CTD.[LINE_TOTAL], 0),
				[TTD_HRS_QTY] = ISNULL(TTD.[HRS_QTY], 0),
				[TTD_EXT_AMT] = ISNULL(TTD.[EXT_AMT], 0),
				[TTD_EXT_MARKUP_AMT] = ISNULL(TTD.[EXT_MARKUP_AMT], 0),
				[TTD_EXT_NONRESALE_TAX] = ISNULL(TTD.[EXT_NONRESALE_TAX], 0),
				[TTD_EXT_STATE_RESALE] = ISNULL(TTD.[EXT_STATE_RESALE], 0),
				[TTD_EXT_COUNTY_RESALE] = ISNULL(TTD.[EXT_COUNTY_RESALE], 0),
				[TTD_EXT_CITY_RESALE] = ISNULL(TTD.[EXT_CITY_RESALE], 0),
				[TTD_LINE_TOTAL] = ISNULL(TTD.[LINE_TOTAL], 0),
				[EST_EXT_AMT] = ISNULL(EST.[EXT_AMT], 0),
				[EST_EXT_MARKUP_AMT] = ISNULL(EST.[EXT_MARKUP_AMT], 0),
				[EST_EXT_NONRESALE_TAX] = ISNULL(EST.[EXT_NONRESALE_TAX], 0),
				[EST_EXT_STATE_RESALE] = ISNULL(EST.[EXT_STATE_RESALE], 0),
				[EST_EXT_COUNTY_RESALE] = ISNULL(EST.[EXT_COUNTY_RESALE], 0),
				[EST_EXT_CITY_RESALE] = ISNULL(EST.[EXT_CITY_RESALE], 0),
				[EST_LINE_TOTAL] = ISNULL(EST.[LINE_TOTAL], 0),
				[PR_EXT_AMT] = ISNULL(PR.[EXT_AMT], 0),
				[PR_EXT_MARKUP_AMT] = ISNULL(PR.[EXT_MARKUP_AMT], 0),
				[PR_EXT_NONRESALE_TAX] = ISNULL(PR.[EXT_NONRESALE_TAX], 0),
				[PR_EXT_STATE_RESALE] = ISNULL(PR.[EXT_STATE_RESALE], 0),
				[PR_EXT_COUNTY_RESALE] = ISNULL(PR.[EXT_COUNTY_RESALE], 0),
				[PR_EXT_CITY_RESALE] = ISNULL(PR.[EXT_CITY_RESALE], 0),
				[PR_LINE_TOTAL] = ISNULL(PR.[LINE_TOTAL], 0)
			FROM 
				(SELECT
						JF.JOB_NUMBER,
						JF.JOB_COMPONENT_NBR,
						JF.FNC_CODE,
						JF.FNC_TYPE,
						[HRS_QTY] = ESTF.[EST_HRS_QTY],
						[RATE] = ESTF.[EST_RATE],
						[EXT_AMT] = ISNULL(CASE JF.FNC_TYPE WHEN 'V' THEN ESTF.[EST_LINE_TOTAL] - ESTF.[EST_EXT_STATE_RESALE] - ESTF.[EST_EXT_COUNTY_RESALE] - ESTF.[EST_EXT_CITY_RESALE] - ESTF.[EST_EXT_MARKUP_AMT]
																	 ELSE ESTF.[EST_LINE_TOTAL] - ESTF.[EST_EXT_STATE_RESALE] - ESTF.[EST_EXT_COUNTY_RESALE] - ESTF.[EST_EXT_CITY_RESALE] END, 0),
						[EXT_MARKUP_AMT] = ISNULL(CASE JF.FNC_TYPE WHEN 'V' THEN ESTF.[EST_EXT_MARKUP_AMT]
																   ELSE 0 END, 0),
						[EXT_NONRESALE_TAX] = ISNULL(ESTF.[EST_EXT_NONRESALE_TAX], 0),
						[EXT_STATE_RESALE] = ISNULL(ESTF.[EST_EXT_STATE_RESALE], 0),
						[EXT_COUNTY_RESALE] = ISNULL(ESTF.[EST_EXT_COUNTY_RESALE], 0),
						[EXT_CITY_RESALE] = ISNULL(ESTF.[EST_EXT_CITY_RESALE], 0),
						[LINE_TOTAL] = ISNULL(ESTF.[EST_LINE_TOTAL], 0)
					FROM
						#JOBS_FUNCTIONS AS JF LEFT OUTER JOIN
						(SELECT 
								EA.JOB_NUMBER, 
								EA.JOB_COMPONENT_NBR, 
								ERD.FNC_CODE,
								[FNC_TYPE] = ERD.EST_FNC_TYPE, 
								[EST_HRS_QTY] = CAST(SUM(ISNULL(ERD.EST_REV_QUANTITY, 0)) AS decimal(15, 2)), 
								[EST_RATE] = CAST(0 AS decimal(15, 3)), 
								[EST_EXT_AMT] = CAST(SUM(ISNULL(ERD.EST_REV_EXT_AMT, 0) + ISNULL(ERD.EXT_CONTINGENCY, 0)) AS decimal(15, 2)),
								[EST_EXT_MARKUP_AMT] = CAST(SUM(ISNULL(ERD.EXT_MARKUP_AMT, 0) + ISNULL(ERD.EXT_MU_CONT, 0)) AS decimal(15, 2)),
								[EST_EXT_NONRESALE_TAX] = CAST(SUM(ISNULL(ERD.EXT_NONRESALE_TAX, 0) + ISNULL(ERD.EXT_NR_CONT, 0)) AS decimal(15, 2)), 
								[EST_EXT_STATE_RESALE] = CAST(SUM(ISNULL(ERD.EXT_STATE_RESALE, 0) + ISNULL(ERD.EXT_STATE_CONT, 0)) AS decimal(15, 2)), 
								[EST_EXT_COUNTY_RESALE] = CAST(SUM(ISNULL(ERD.EXT_COUNTY_RESALE, 0) + ISNULL(ERD.EXT_COUNTY_CONT, 0)) AS decimal(15, 2)), 
								[EST_EXT_CITY_RESALE] = CAST(SUM(ISNULL(ERD.EXT_CITY_RESALE, 0) + ISNULL(ERD.EXT_CITY_CONT, 0)) AS decimal(15, 2)),
								[EST_LINE_TOTAL] = CAST(SUM(ISNULL(ERD.LINE_TOTAL, 0) + ISNULL(ERD.LINE_TOTAL_CONT, 0)) AS decimal(15, 2))
							FROM 
								[dbo].[ESTIMATE_APPROVAL] AS EA INNER JOIN 
								[dbo].[ESTIMATE_REV_DET] AS ERD ON ERD.EST_REV_NBR= EA.EST_REVISION_NBR AND 
																   ERD.EST_QUOTE_NBR = EA.EST_QUOTE_NBR AND 
																   ERD.EST_COMPONENT_NBR = EA.EST_COMPONENT_NBR AND 
																   ERD.ESTIMATE_NUMBER = EA.ESTIMATE_NUMBER INNER JOIN 
								[dbo].[ESTIMATE_LOG] EL ON EL.ESTIMATE_NUMBER = EA.ESTIMATE_NUMBER INNER JOIN 
								[dbo].[FUNCTIONS] F ON F.FNC_CODE = ERD.FNC_CODE
							GROUP BY 
								EA.JOB_NUMBER, 
								EA.JOB_COMPONENT_NBR, 
								ERD.FNC_CODE, 
								ERD.EST_FNC_TYPE) AS ESTF ON ESTF.JOB_NUMBER = JF.JOB_NUMBER AND 
															 ESTF.JOB_COMPONENT_NBR = JF.JOB_COMPONENT_NBR AND 
															 ESTF.FNC_CODE = JF.FNC_CODE) AS EST LEFT OUTER JOIN 
					#JOBS_FUNCTIONS AS J ON J.JOB_NUMBER = EST.JOB_NUMBER AND 
											J.JOB_COMPONENT_NBR = EST.JOB_COMPONENT_NBR AND 
											J.FNC_CODE = EST.FNC_CODE LEFT OUTER JOIN
					(SELECT
						ARS.JOB_NUMBER,
						ARS.JOB_COMPONENT_NBR,
						ARS.FNC_CODE,
						ARS.FNC_TYPE,
						[HRS_QTY] = SUM(CAST(ARS.HRS_QTY AS decimal(18,2))),
						[RATE] = SUM(CAST(0 AS decimal(18,2))),
						[EXT_AMT] = SUM(CAST(CASE ARS.FNC_TYPE WHEN 'V' THEN ISNULL(ARS.TOTAL_BILL, 0) - ISNULL(ARS.STATE_TAX_AMT, 0) - ISNULL(ARS.CNTY_TAX_AMT, 0) - ISNULL(ARS.CITY_TAX_AMT, 0) - ISNULL(ARS.COMMISSION_AMT, 0) - ISNULL(ARS.AB_COMMISSION_AMT, 0)
															   ELSE ISNULL(ARS.TOTAL_BILL, 0) - ISNULL(ARS.STATE_TAX_AMT, 0) - ISNULL(ARS.CNTY_TAX_AMT, 0) - ISNULL(ARS.CITY_TAX_AMT, 0) END AS decimal(18,2))),
						[EXT_MARKUP_AMT] = SUM(CAST(CASE ARS.FNC_TYPE WHEN 'V' THEN ISNULL(ARS.COMMISSION_AMT,0) + ISNULL(ARS.AB_COMMISSION_AMT,0)
																	  ELSE 0 END AS decimal(18,2))),
						[EXT_NONRESALE_TAX] = SUM(CAST(ARS.NON_RESALE_AMT AS decimal(18,2))),
						[EXT_STATE_RESALE] = SUM(CAST(ISNULL(ARS.STATE_TAX_AMT, 0) AS decimal(18,2))),
						[EXT_COUNTY_RESALE] = SUM(CAST(ISNULL(ARS.CNTY_TAX_AMT, 0) AS decimal(18,2))),
						[EXT_CITY_RESALE] = SUM(CAST(ISNULL(ARS.CITY_TAX_AMT, 0) AS decimal(18,2))),
						[LINE_TOTAL] = SUM(CAST(ISNULL(ARS.TOTAL_BILL, 0) AS decimal(18,2)))
					FROM
						dbo.AR_SUMMARY AS ARS INNER JOIN
						#JOBS_FUNCTIONS AS J ON  J.JOB_NUMBER = ARS.JOB_NUMBER AND 
												 J.JOB_COMPONENT_NBR = ARS.JOB_COMPONENT_NBR AND
												 J.FNC_CODE = ARS.FNC_CODE INNER JOIN
						(SELECT 
								AR.AR_INV_NBR, 
								AR.AR_TYPE, 
								[AR_INV_DATE] = MAX(AR.AR_INV_DATE) 
							FROM 
								[dbo].[ACCT_REC] AS AR
							GROUP BY 
								AR.AR_INV_NBR, 
								AR.AR_TYPE) AS ARID ON ARID.AR_INV_NBR = ARS.AR_INV_NBR AND 
													   ARID.AR_TYPE = ARS.AR_TYPE
					WHERE 
						ARS.FNC_TYPE <> 'R' AND
						((ARS.AR_INV_NBR < @InvoiceNumber AND
						  ARS.AR_INV_SEQ = @SequenceNumber AND
						  ARID.AR_INV_DATE <= @InvoiceDate) OR 
						 (ARS.AR_INV_NBR = @InvoiceNumber AND
						  ARS.AR_INV_SEQ = @SequenceNumber))
					GROUP BY
						ARS.JOB_NUMBER,
						ARS.JOB_COMPONENT_NBR,
						ARS.FNC_CODE,
						ARS.FNC_TYPE) AS TTD ON TTD.JOB_NUMBER = J.JOB_NUMBER AND 
												TTD.JOB_COMPONENT_NBR = J.JOB_COMPONENT_NBR AND
												TTD.FNC_CODE = J.FNC_CODE LEFT OUTER JOIN
					(SELECT
						ARS.JOB_NUMBER,
						ARS.JOB_COMPONENT_NBR,
						ARS.FNC_CODE,
						ARS.FNC_TYPE,
						[HRS_QTY] = SUM(CAST(ARS.HRS_QTY AS decimal(18,2))),
						[RATE] = SUM(CAST(0 AS decimal(18,2))),
						[EXT_AMT] = SUM(CAST(CASE ARS.FNC_TYPE WHEN 'V' THEN ISNULL(ARS.TOTAL_BILL, 0) - ISNULL(ARS.STATE_TAX_AMT, 0) - ISNULL(ARS.CNTY_TAX_AMT, 0) - ISNULL(ARS.CITY_TAX_AMT, 0) - ISNULL(ARS.COMMISSION_AMT, 0) - ISNULL(ARS.AB_COMMISSION_AMT, 0)
															   ELSE ISNULL(ARS.TOTAL_BILL, 0) - ISNULL(ARS.STATE_TAX_AMT, 0) - ISNULL(ARS.CNTY_TAX_AMT, 0) - ISNULL(ARS.CITY_TAX_AMT, 0) END AS decimal(18,2))),
						[EXT_MARKUP_AMT] = SUM(CAST(CASE ARS.FNC_TYPE WHEN 'V' THEN ISNULL(ARS.COMMISSION_AMT,0) + ISNULL(ARS.AB_COMMISSION_AMT,0)
																	  ELSE 0 END AS decimal(18,2))),
						[EXT_NONRESALE_TAX] = SUM(CAST(ARS.NON_RESALE_AMT AS decimal(18,2))),
						[EXT_STATE_RESALE] = SUM(CAST(ISNULL(ARS.STATE_TAX_AMT, 0) AS decimal(18,2))),
						[EXT_COUNTY_RESALE] = SUM(CAST(ISNULL(ARS.CNTY_TAX_AMT, 0) AS decimal(18,2))),
						[EXT_CITY_RESALE] = SUM(CAST(ISNULL(ARS.CITY_TAX_AMT, 0) AS decimal(18,2))),
						[LINE_TOTAL] = SUM(CAST(ISNULL(ARS.TOTAL_BILL, 0) AS decimal(18,2)))
					FROM
						[dbo].[AR_SUMMARY] AS ARS INNER JOIN 
						[dbo].[ACCT_REC] AS AR ON AR.AR_INV_NBR = ARS.AR_INV_NBR AND 
												  AR.AR_INV_SEQ = ARS.AR_INV_SEQ AND
												  AR.AR_TYPE = ARS.AR_TYPE INNER JOIN
						#JOBS_FUNCTIONS AS J ON  J.JOB_NUMBER = ARS.JOB_NUMBER AND 
												 J.JOB_COMPONENT_NBR = ARS.JOB_COMPONENT_NBR AND
												 J.FNC_CODE = ARS.FNC_CODE 
					WHERE 
						ARS.FNC_TYPE <> 'R' AND
						ARS.AR_INV_NBR < @InvoiceNumber AND
						ARS.AR_INV_SEQ = @SequenceNumber AND
						AR.AR_INV_DATE <= @InvoiceDate
					GROUP BY
						ARS.JOB_NUMBER,
						ARS.JOB_COMPONENT_NBR,
						ARS.FNC_CODE,
						ARS.FNC_TYPE) AS PR ON PR.JOB_NUMBER = J.JOB_NUMBER AND 
											   PR.JOB_COMPONENT_NBR = J.JOB_COMPONENT_NBR AND
											   PR.FNC_CODE = J.FNC_CODE LEFT OUTER JOIN
					(SELECT
							ARS.JOB_NUMBER,
							ARS.JOB_COMPONENT_NBR,
							ARS.FNC_CODE,
							ARS.FNC_TYPE,
							[HRS_QTY] = SUM(CAST(ARS.HRS_QTY AS decimal(18,2))),
							[RATE] = SUM(CAST(0 AS decimal(18,2))),
							[EXT_AMT] = SUM(CAST(CASE ARS.FNC_TYPE WHEN 'V' THEN ISNULL(ARS.TOTAL_BILL, 0) - ISNULL(ARS.STATE_TAX_AMT, 0) - ISNULL(ARS.CNTY_TAX_AMT, 0) - ISNULL(ARS.CITY_TAX_AMT, 0) - ISNULL(ARS.COMMISSION_AMT, 0) - ISNULL(ARS.AB_COMMISSION_AMT, 0)
																   ELSE ISNULL(ARS.TOTAL_BILL, 0) - ISNULL(ARS.STATE_TAX_AMT, 0) - ISNULL(ARS.CNTY_TAX_AMT, 0) - ISNULL(ARS.CITY_TAX_AMT, 0) END AS decimal(18,2))),
							[EXT_MARKUP_AMT] = SUM(CAST(CASE ARS.FNC_TYPE WHEN 'V' THEN ISNULL(ARS.COMMISSION_AMT,0) + ISNULL(ARS.AB_COMMISSION_AMT,0)
																		  ELSE 0 END AS decimal(18,2))),
							[EXT_NONRESALE_TAX] = SUM(CAST(ARS.NON_RESALE_AMT AS decimal(18,2))),
							[EXT_STATE_RESALE] = SUM(CAST(ISNULL(ARS.STATE_TAX_AMT, 0) AS decimal(18,2))),
							[EXT_COUNTY_RESALE] = SUM(CAST(ISNULL(ARS.CNTY_TAX_AMT, 0) AS decimal(18,2))),
							[EXT_CITY_RESALE] = SUM(CAST(ISNULL(ARS.CITY_TAX_AMT, 0) AS decimal(18,2))),
							[LINE_TOTAL] = SUM(CAST(ISNULL(ARS.TOTAL_BILL, 0) AS decimal(18,2)))
						FROM
							dbo.AR_SUMMARY AS ARS
						WHERE 
							ARS.FNC_TYPE <> 'R' AND
							ARS.AR_INV_NBR = @InvoiceNumber AND
							ARS.AR_INV_SEQ = @SequenceNumber
						GROUP BY
							ARS.JOB_NUMBER,
							ARS.JOB_COMPONENT_NBR,
							ARS.FNC_CODE,
							ARS.FNC_TYPE) AS CTD ON CTD.JOB_NUMBER = J.JOB_NUMBER AND 
													CTD.JOB_COMPONENT_NBR = J.JOB_COMPONENT_NBR AND
													CTD.FNC_CODE = J.FNC_CODE
			WHERE J.JOB_NUMBER IS NOT NULL) AS TD LEFT OUTER JOIN
			[dbo].[FUNCTIONS] AS F ON F.FNC_CODE = TD.FNC_CODE LEFT OUTER JOIN 
			[dbo].[FNC_HEADING] AS FH ON FH.FNC_HEADING_ID = F.FNC_HEADING_ID
		
	END
	
	IF @IsDraft = 1 BEGIN
	
		SELECT 	
			[InvoiceNumber] = BIA.AR_INV_NBR, 
			[InvoiceSequenceNumber] = BIA.AR_INV_SEQ,
			[InvoiceDate] = BIA.AR_INV_DATE,
			[InvoiceType] = BIA.AR_TYPE,
			[FullInvoiceNumber] = RIGHT('000000' + CAST(BIA.AR_INV_NBR AS varchar(6)), 6) + '-' + RIGHT('000' + CAST(BIA.AR_INV_SEQ AS varchar(4)), 4),
			[JobNumber] = BIA.JOB_NUMBER,
			[JobDescription] = RIGHT(REPLICATE('0', 6) + CONVERT(VARCHAR(20), JL.JOB_NUMBER), 6) + ' - ' + JL.JOB_DESC, 
			[ComponentNumber] = BIA.JOB_COMPONENT_NBR, 
			[ComponentDescription] = RIGHT(REPLICATE('0', 3) + CONVERT(VARCHAR(20), JC.JOB_COMPONENT_NBR), 3) + ' - ' + JC.JOB_COMP_DESC,
			[ClientCode] = BIA.CL_CODE,
			[ClientName] = C.CL_NAME,
			[DivisionCode] = BIA.DIV_CODE,
			[DivisionName] = D.DIV_NAME,
			[ProductCode] = BIA.PRD_CODE,
			[ProductName] = P.PRD_DESCRIPTION,
			[SCType] = CASE WHEN @PrintFunctionType = 3 OR (@PrintFunctionType = 1 AND P.PRD_CONSOL_FUNC = 1) THEN 'C'
							ELSE 'S' END,
			[FunctionType] = CASE WHEN @PrintFunctionType = 3 OR (@PrintFunctionType = 1 AND P.PRD_CONSOL_FUNC = 1) THEN F.FNC_TYPE
								  ELSE BIA.FNC_TYPE END,
			[FunctionOrder] = CAST(CASE WHEN ISNULL(@SortFunctionByType, 1) = 2 THEN CASE WHEN @PrintFunctionType = 3 OR (@PrintFunctionType = 1 AND P.PRD_CONSOL_FUNC = 1) THEN F.FNC_ORDER
																					  ELSE BIA.FNC_ORDER END ELSE 0 END AS smallint),
			[OriginalFunctionCode] = BIA.FNC_CODE,
			[FunctionCode] = CASE WHEN @PrintFunctionType = 3 OR (@PrintFunctionType = 1 AND P.PRD_CONSOL_FUNC = 1) THEN F.CONSOL_FNC
								  ELSE BIA.FNC_CODE END,
			[FunctionDescription] =  CASE WHEN @PrintFunctionType = 3 OR (@PrintFunctionType = 1 AND P.PRD_CONSOL_FUNC = 1) THEN F.FNC_DESCRIPTION
										  ELSE BIA.FNC_DESCRIPTION END,
			[FunctionHeading] = CASE WHEN @PrintFunctionType = 3 OR (@PrintFunctionType = 1 AND P.PRD_CONSOL_FUNC = 1) THEN F.FNC_HEADING_DESC
									 ELSE BIA.FNC_HEADING_DESC END,
			[FunctionHeadingOrder] = CASE WHEN @PrintFunctionType = 3 OR (@PrintFunctionType = 1 AND P.PRD_CONSOL_FUNC = 1) THEN F.FNC_HEADING_SEQ
										  ELSE BIA.FNC_HEADING_SEQ END,
			[Quantity] = CASE WHEN @PrintFunctionType = 3 OR (@PrintFunctionType = 1 AND P.PRD_CONSOL_FUNC = 1) THEN CASE WHEN F.FNC_TYPE <> 'E' THEN BIA.HRS_QTY ELSE NULL END
							  ELSE CASE WHEN BIA.FNC_TYPE <> 'E' THEN BIA.HRS_QTY ELSE NULL END END, 
			[Hours] = CASE WHEN @PrintFunctionType = 3 OR (@PrintFunctionType = 1 AND P.PRD_CONSOL_FUNC = 1) THEN CASE WHEN F.FNC_TYPE = 'E' THEN BIA.HRS_QTY ELSE NULL END
						   ELSE CASE WHEN BIA.FNC_TYPE = 'E' THEN BIA.HRS_QTY ELSE NULL END END, 
			[Rate] = BIA.RATE,
			[NetAmount] = dbo.advfn_invoice_printing_xchge_net_amt(BIA.EXT_AMT, BIA.EXT_MARKUP_AMT, @TotalsShowCommissionSeparately, 
												  BIA.EXT_CITY_RESALE + BIA.EXT_COUNTY_RESALE + BIA.EXT_STATE_RESALE, 
												  @TotalsShowTaxSeparately, @ApplyExchangeRate, @ExchangeRateAmount), 
			[CommissionAmount] = dbo.advfn_invoice_printing_xchge_commission_amt(BIA.EXT_MARKUP_AMT, @TotalsShowCommissionSeparately, @ApplyExchangeRate, @ExchangeRateAmount),
			[NonResaleTax] = dbo.advfn_invoice_printing_xchge_tax_amt(BIA.EXT_NONRESALE_TAX, @TotalsShowTaxSeparately, @ApplyExchangeRate, @ExchangeRateAmount),
			[CityTax] = dbo.advfn_invoice_printing_xchge_tax_amt(BIA.EXT_CITY_RESALE, @TotalsShowTaxSeparately, @ApplyExchangeRate, @ExchangeRateAmount), 
			[CountyTax] = dbo.advfn_invoice_printing_xchge_tax_amt(BIA.EXT_COUNTY_RESALE, @TotalsShowTaxSeparately, @ApplyExchangeRate, @ExchangeRateAmount), 
			[StateTax] = dbo.advfn_invoice_printing_xchge_tax_amt(BIA.EXT_STATE_RESALE, @TotalsShowTaxSeparately, @ApplyExchangeRate, @ExchangeRateAmount), 
			[TotalTax] = (BIA.EXT_CITY_RESALE + BIA.EXT_COUNTY_RESALE + BIA.EXT_STATE_RESALE),
			[TotalAmount] = dbo.advfn_invoice_printing_xchge_total_amt(BIA.LINE_TOTAL, @ApplyExchangeRate, @ExchangeRateAmount),
			[DiscountAmount] = dbo.advfn_invoice_printing_xchge_total_amt(BIA.LINE_TOTAL, @ApplyExchangeRate, @ExchangeRateAmount) - dbo.advfn_invoice_printing_xchge_disocunt_amt(BIA.LINE_TOTAL - (BIA.EXT_CITY_RESALE + BIA.EXT_COUNTY_RESALE + BIA.EXT_STATE_RESALE), BIA.FNC_CODE, C.CLIENT_DISCOUNT_CODE, JC.CLIENT_DISCOUNT_CODE, @ApplyExchangeRate, @ExchangeRateAmount),
			[TTDNetAmount] = dbo.advfn_invoice_printing_xchge_net_amt(BIA.TTD_EXT_AMT, BIA.TTD_EXT_MARKUP_AMT, @TotalsShowCommissionSeparately, 
													 BIA.TTD_EXT_CITY_RESALE + BIA.TTD_EXT_COUNTY_RESALE + BIA.TTD_EXT_STATE_RESALE, 
													 @TotalsShowTaxSeparately, @ApplyExchangeRate, @ExchangeRateAmount), 
			[TTDCommissionAmount] = dbo.advfn_invoice_printing_xchge_commission_amt(BIA.TTD_EXT_MARKUP_AMT, @TotalsShowCommissionSeparately, @ApplyExchangeRate, @ExchangeRateAmount),
			[TTDNonResaleTax] = dbo.advfn_invoice_printing_xchge_tax_amt(BIA.TTD_EXT_NONRESALE_TAX, @TotalsShowTaxSeparately, @ApplyExchangeRate, @ExchangeRateAmount),
			[TTDCityTax] = dbo.advfn_invoice_printing_xchge_tax_amt(BIA.TTD_EXT_CITY_RESALE, @TotalsShowTaxSeparately, @ApplyExchangeRate, @ExchangeRateAmount), 
			[TTDCountyTax] = dbo.advfn_invoice_printing_xchge_tax_amt(BIA.TTD_EXT_COUNTY_RESALE, @TotalsShowTaxSeparately, @ApplyExchangeRate, @ExchangeRateAmount), 
			[TTDStateTax] = dbo.advfn_invoice_printing_xchge_tax_amt(BIA.TTD_EXT_STATE_RESALE, @TotalsShowTaxSeparately, @ApplyExchangeRate, @ExchangeRateAmount), 
			[TTDTotalTax] = (BIA.TTD_EXT_CITY_RESALE + BIA.TTD_EXT_COUNTY_RESALE + BIA.TTD_EXT_STATE_RESALE),
			[TTDTotalAmount] = dbo.advfn_invoice_printing_xchge_total_amt(BIA.TTD_LINE_TOTAL, @ApplyExchangeRate, @ExchangeRateAmount),
			[EstimateNetAmount] = dbo.advfn_invoice_printing_xchge_net_amt(BIA.EST_EXT_AMT, BIA.EST_EXT_MARKUP_AMT, @TotalsShowCommissionSeparately, 
														  BIA.EST_EXT_CITY_RESALE + BIA.EST_EXT_COUNTY_RESALE + BIA.EST_EXT_STATE_RESALE, 
														  @TotalsShowTaxSeparately, @ApplyExchangeRate, @ExchangeRateAmount), 
			[EstimateCommissionAmount] = dbo.advfn_invoice_printing_xchge_commission_amt(BIA.EST_EXT_MARKUP_AMT, @TotalsShowCommissionSeparately, @ApplyExchangeRate, @ExchangeRateAmount),
			[EstimateNonResaleTax] = dbo.advfn_invoice_printing_xchge_tax_amt(BIA.EST_EXT_NONRESALE_TAX, @TotalsShowTaxSeparately, @ApplyExchangeRate, @ExchangeRateAmount),
			[EstimateCityTax] = dbo.advfn_invoice_printing_xchge_tax_amt(BIA.EST_EXT_CITY_RESALE, @TotalsShowTaxSeparately, @ApplyExchangeRate, @ExchangeRateAmount), 
			[EstimateCountyTax] = dbo.advfn_invoice_printing_xchge_tax_amt(BIA.EST_EXT_COUNTY_RESALE, @TotalsShowTaxSeparately, @ApplyExchangeRate, @ExchangeRateAmount), 
			[EstimateStateTax] = dbo.advfn_invoice_printing_xchge_tax_amt(BIA.EST_EXT_STATE_RESALE, @TotalsShowTaxSeparately, @ApplyExchangeRate, @ExchangeRateAmount), 
			[EstimateTotalTax] = (BIA.EST_EXT_CITY_RESALE + BIA.EST_EXT_COUNTY_RESALE + BIA.EST_EXT_STATE_RESALE),
			[EstimateTotalAmount] = dbo.advfn_invoice_printing_xchge_total_amt(BIA.EST_LINE_TOTAL, @ApplyExchangeRate, @ExchangeRateAmount), 
			[PriorNetAmount] = dbo.advfn_invoice_printing_xchge_net_amt(BIA.PR_EXT_AMT, BIA.PR_EXT_MARKUP_AMT, @TotalsShowCommissionSeparately, 
													   BIA.PR_EXT_CITY_RESALE + BIA.PR_EXT_COUNTY_RESALE + BIA.PR_EXT_STATE_RESALE, 
													   @TotalsShowTaxSeparately, @ApplyExchangeRate, @ExchangeRateAmount), 
			[PriorCommissionAmount] = dbo.advfn_invoice_printing_xchge_commission_amt(BIA.PR_EXT_MARKUP_AMT, @TotalsShowCommissionSeparately, @ApplyExchangeRate, @ExchangeRateAmount),
			[PriorNonResaleTax] = dbo.advfn_invoice_printing_xchge_tax_amt(BIA.PR_EXT_NONRESALE_TAX, @TotalsShowTaxSeparately, @ApplyExchangeRate, @ExchangeRateAmount),
			[PriorCityTax] = dbo.advfn_invoice_printing_xchge_tax_amt(BIA.PR_EXT_CITY_RESALE, @TotalsShowTaxSeparately, @ApplyExchangeRate, @ExchangeRateAmount), 
			[PriorCountyTax] = dbo.advfn_invoice_printing_xchge_tax_amt(BIA.PR_EXT_COUNTY_RESALE, @TotalsShowTaxSeparately, @ApplyExchangeRate, @ExchangeRateAmount), 
			[PriorStateTax] = dbo.advfn_invoice_printing_xchge_tax_amt(BIA.PR_EXT_STATE_RESALE, @TotalsShowTaxSeparately, @ApplyExchangeRate, @ExchangeRateAmount), 
			[PriorTotalTax] = (BIA.PR_EXT_CITY_RESALE + BIA.PR_EXT_COUNTY_RESALE + BIA.PR_EXT_STATE_RESALE),
			[PriorTotalAmount] = dbo.advfn_invoice_printing_xchge_total_amt(BIA.PR_LINE_TOTAL, @ApplyExchangeRate, @ExchangeRateAmount),
			[BillingComment] = NULL,
			[BillingJobComment] = NULL,
			[BillingDetailComment] = NULL,
			[JobComment] = CASE WHEN ISNULL(CAST(JL.JOB_COMMENTS AS varchar(MAX)), '') <> '' THEN CAST(JL.JOB_COMMENTS AS varchar(MAX)) ELSE NULL END,
			[BillingApprovalClientComment] = CASE WHEN ISNULL(CAST(BAC.BILL_APPROVAL_COMMENT AS varchar(MAX)), '') <> '' THEN CAST(BAC.BILL_APPROVAL_COMMENT AS varchar(MAX)) ELSE NULL END,
			[BillingApprovalFunctionComment] = CASE WHEN ISNULL(CAST(BACF.BILL_APPROVAL_FUNCTION_COMMENT AS varchar(MAX)), '') <> '' THEN CAST(BACF.BILL_APPROVAL_FUNCTION_COMMENT AS varchar(MAX)) ELSE NULL END,
			[JobComponentComment] = CASE WHEN ISNULL(CAST(JC.JOB_COMP_COMMENTS AS varchar(MAX)), '') <> '' THEN CAST(JC.JOB_COMP_COMMENTS AS varchar(MAX)) ELSE NULL END,
			[EstimateComment] = CASE WHEN @IncludeEstimateComment = 1 THEN CASE WHEN ISNULL(ESTHC.EST_LOG_COMMENT_HTML, '') <> '' THEN ESTHC.EST_LOG_COMMENT_HTML 
																				ELSE CASE WHEN ISNULL(ESTHC.EST_LOG_COMMENT, '') <> '' THEN ESTHC.EST_LOG_COMMENT 
																						  ELSE NULL END END
									 ELSE NULL END,
			[EstimateComponentComment] = CASE WHEN @IncludeEstimateComponentComment = 1 THEN CASE WHEN ISNULL(ESTHC.EST_COMP_COMMENT_HTML, '') <> '' THEN ESTHC.EST_COMP_COMMENT_HTML 
																								  ELSE CASE WHEN ISNULL(ESTHC.EST_COMP_COMMENT, '') <> '' THEN ESTHC.EST_COMP_COMMENT 
																											ELSE NULL END END
											  ELSE NULL END,
			[EstimateQuoteComment] = CASE WHEN @IncludeEstimateQuoteComment = 1 THEN CASE WHEN ISNULL(ESTHC.EST_QTE_COMMENT_HTML, '') <> '' THEN ESTHC.EST_QTE_COMMENT_HTML 
																						  ELSE CASE WHEN ISNULL(ESTHC.EST_QTE_COMMENT, '') <> '' THEN ESTHC.EST_QTE_COMMENT 
																									ELSE NULL END END
										  ELSE NULL END,
			[EstimateRevisionComment] = CASE WHEN @IncludeEstimateRevisionComment = 1 THEN CASE WHEN ISNULL(ESTHC.EST_REV_COMMENT_HTML, '') <> '' THEN ESTHC.EST_REV_COMMENT_HTML 
																								ELSE CASE WHEN ISNULL(ESTHC.EST_REV_COMMENT, '') <> '' THEN ESTHC.EST_REV_COMMENT 
																										  ELSE NULL END END
											 ELSE NULL END,
			[EstimateFunctionComment] = CASE WHEN @IncludeEstimateFunctionComment = 1 THEN CASE WHEN ISNULL(ESTC.EST_FNC_COMMENT_HTML, '') <> '' THEN @Font + ESTC.EST_FNC_COMMENT_HTML + @Font2
																								ELSE CASE WHEN ISNULL(ESTC.EST_FNC_COMMENT, '') <> '' THEN @Font + ESTC.EST_FNC_COMMENT + @Font2  
																										  ELSE NULL END END
											 ELSE NULL END,
			[InvoiceDueDate] = NULL,
			[ClientReference] = JL.JOB_CLI_REF,
			[ClientPO] = JC.JOB_CL_PO_NBR,
			[AccountExecutive] = COALESCE((RTRIM(EMP.EMP_FNAME) + ' '),'') + COALESCE((EMP.EMP_MI + '. '),'') + COALESCE(EMP.EMP_LNAME,''),
			[SalesClassCode] = JL.SC_CODE,
			[SalesClassDescription] = SC.SC_DESCRIPTION,
			[Address] = CASE WHEN OCDPC.CDP_CONTACT_ID IS NOT NULL THEN dbo.advfn_invoice_printing_address(@AddressBlockType, @ShowCodes, @PrintClientName, @PrintDivisionName, @PrintProductDescription, @PrintContactAfterAddress,  
																											C.CL_CODE, C.CL_NAME, C.CL_ATTENTION,
																											C.CL_BADDRESS1, C.CL_BADDRESS2, C.CL_BCITY,
																											C.CL_BCOUNTY, C.CL_BSTATE, C.CL_BCOUNTRY, C.CL_BZIP,
																											D.DIV_CODE, D.DIV_NAME, D.DIV_ATTENTION,
																											D.DIV_BADDRESS1, D.DIV_BADDRESS2, D.DIV_BCITY,
																											D.DIV_BCOUNTY, D.DIV_BSTATE, D.DIV_BCOUNTRY, D.DIV_BZIP,
																											P.PRD_CODE, P.PRD_DESCRIPTION, P.PRD_ATTENTION,
																											P.PRD_BILL_ADDRESS1, P.PRD_BILL_ADDRESS2, P.PRD_BILL_CITY,
																											P.PRD_BILL_COUNTY, P.PRD_BILL_STATE, P.PRD_BILL_COUNTRY, P.PRD_BILL_ZIP,
																											OCDPC.CDP_CONTACT_ID, OCDPC.CONT_CODE, OCDPC.CONT_FNAME, OCDPC.CONT_LNAME, OCDPC.CONT_MI,
																											OCDPC.CONT_ADDRESS1, OCDPC.CONT_ADDRESS2, OCDPC.CONT_CITY,
																											OCDPC.CONT_COUNTY, OCDPC.CONT_STATE, OCDPC.CONT_COUNTRY, OCDPC.CONT_ZIP, @ContactType, 'Invoice') 
																   ELSE dbo.advfn_invoice_printing_address(@AddressBlockType, @ShowCodes, @PrintClientName, @PrintDivisionName, @PrintProductDescription, @PrintContactAfterAddress,  
																											C.CL_CODE, C.CL_NAME, C.CL_ATTENTION,
																											C.CL_BADDRESS1, C.CL_BADDRESS2, C.CL_BCITY,
																											C.CL_BCOUNTY, C.CL_BSTATE, C.CL_BCOUNTRY, C.CL_BZIP,
																											D.DIV_CODE, D.DIV_NAME, D.DIV_ATTENTION,
																											D.DIV_BADDRESS1, D.DIV_BADDRESS2, D.DIV_BCITY,
																											D.DIV_BCOUNTY, D.DIV_BSTATE, D.DIV_BCOUNTRY, D.DIV_BZIP,
																											P.PRD_CODE, P.PRD_DESCRIPTION, P.PRD_ATTENTION,
																											P.PRD_BILL_ADDRESS1, P.PRD_BILL_ADDRESS2, P.PRD_BILL_CITY,
																											P.PRD_BILL_COUNTY, P.PRD_BILL_STATE, P.PRD_BILL_COUNTRY, P.PRD_BILL_ZIP,
																											CDPC.CDP_CONTACT_ID, CDPC.CONT_CODE, CDPC.CONT_FNAME, CDPC.CONT_LNAME, CDPC.CONT_MI,
																											CDPC.CONT_ADDRESS1, CDPC.CONT_ADDRESS2, CDPC.CONT_CITY,
																											CDPC.CONT_COUNTY, CDPC.CONT_STATE, CDPC.CONT_COUNTRY, CDPC.CONT_ZIP, @ContactType, 'Job') END,
			[InvoiceCategory] = CASE WHEN @UseInvoiceCategoryDescription = 1 AND BIA.INV_CAT IS NOT NULL THEN BIA.INV_CAT_DESC 
									 WHEN @UseInvoiceCategoryDescription = 0 AND @InvoiceTitle IS NOT NULL AND DATALENGTH(@InvoiceTitle) > 0 THEN @InvoiceTitle
									 ELSE 'INVOICE' END,
			[InvoiceFooterComment] = CASE WHEN ISNULL(@InvoiceFooterCommentType, 1) = 2 THEN ISNULL(dbo.advfn_invoice_printing_comment('Invoices', 'Standard Footer', BIA.OFFICE_CODE, BIA.CL_CODE, BIA.DIV_CODE, BIA.PRD_CODE), C.CL_FOOTER)
										  WHEN ISNULL(@InvoiceFooterCommentType, 1) = 3 THEN @InvoiceFooterComment 
										  ELSE '' END,
			[InvoiceFooterCommentFontSize] = CASE WHEN ISNULL(@InvoiceFooterCommentType, 1) = 2 THEN ISNULL(dbo.advfn_invoice_printing_comment_font_size('Invoices', 'Standard Footer', BIA.OFFICE_CODE, BIA.CL_CODE, BIA.DIV_CODE, BIA.PRD_CODE), 10)
												  ELSE 10 END,
			[InsideDescription] = @GroupingOptionInsideDescription,
			[OutsideDescription] = @GroupingOptionOutsideDescription,
			[CampaignID] =  JL.CMP_IDENTIFIER,
			[CampaignCode] =  CAMP.CMP_CODE,
			[CampaignName] =  CAMP.CMP_NAME,
			[Campaign] =  CAMP.CMP_CODE + ' - ' + CAMP.CMP_NAME,
			[CampaignComment] =  CAST(CAMP.CMP_COMMENTS AS varchar(MAX)),
			[VATNumber] = C.VAT_NUMBER,
			[EstimateHours] = ESTC.EST_HRS_QTY,
			[TTDHoursBilled] = BIA.TTD_HRS_QTY
		FROM
			(SELECT 
					IT.*, 
					I.[AR_INV_NBR], 
					I.[AR_INV_SEQ], 
					I.[AR_TYPE],
					I.[AR_INV_DATE],
					I.[CL_CODE],
					I.[DIV_CODE],
					I.[PRD_CODE],
					I.[OFFICE_CODE],
					I.[INV_CAT],
					I.[INV_CAT_DESC],
					I.[CDP_CONTACT_ID]
				FROM 
					#INVOICE_ITEMS AS IT INNER JOIN 
					#INVOICE I ON I.JOB_NUMBER = IT.JOB_NUMBER AND
								  I.JOB_COMPONENT_NBR = IT.JOB_COMPONENT_NBR) AS BIA INNER JOIN 
				[dbo].[JOB_LOG] AS JL ON JL.JOB_NUMBER = BIA.JOB_NUMBER INNER JOIN
				[dbo].[JOB_COMPONENT] AS JC ON JC.JOB_NUMBER = BIA.JOB_NUMBER AND
											   JC.JOB_COMPONENT_NBR = BIA.JOB_COMPONENT_NBR LEFT OUTER JOIN 
				[dbo].[CLIENT] AS C ON C.CL_CODE = BIA.CL_CODE  LEFT OUTER JOIN 
				[dbo].[DIVISION] AS D ON D.CL_CODE = BIA.CL_CODE AND
										 D.DIV_CODE = BIA.DIV_CODE LEFT OUTER JOIN
				[dbo].[PRODUCT] AS P ON P.CL_CODE = BIA.CL_CODE AND 
										P.DIV_CODE = BIA.DIV_CODE AND 
										P.PRD_CODE = BIA.PRD_CODE INNER JOIN 
				(SELECT 
						F.FNC_CODE, 
						[CONSOL_FNC] = COALESCE(SF.FNC_CONSOLIDATION, F.FNC_CONSOLIDATION, F.FNC_CODE),
						[FNC_DESCRIPTION] = COALESCE(SF.FNC_DESCRIPTION, F.FNC_DESCRIPTION, F.FNC_DESCRIPTION),
						[FNC_TYPE] = COALESCE(SF.FNC_TYPE, F.FNC_TYPE, F.FNC_TYPE),
						[FNC_ORDER] = CAST(ISNULL(COALESCE(SF.FNC_ORDER, F.FNC_ORDER, F.FNC_ORDER), 0) AS smallint),
						[FNC_HEADING_DESC] = COALESCE(SFH.FNC_HEADING_DESC, FH.FNC_HEADING_DESC, FH.FNC_HEADING_DESC),
						[FNC_HEADING_SEQ] = COALESCE(SFH.FNC_HEADING_SEQ, FH.FNC_HEADING_SEQ, FH.FNC_HEADING_SEQ)
					FROM 
						[dbo].[FUNCTIONS] AS F LEFT OUTER JOIN 
						[dbo].[FUNCTIONS] AS SF ON SF.FNC_CODE = F.FNC_CONSOLIDATION LEFT OUTER JOIN 
						[dbo].[FNC_HEADING] AS FH ON FH.FNC_HEADING_ID = F.FNC_HEADING_ID LEFT OUTER JOIN 
						[dbo].[FNC_HEADING] AS SFH ON SFH.FNC_HEADING_ID = SF.FNC_HEADING_ID) AS F ON F.FNC_CODE = BIA.FNC_CODE LEFT OUTER JOIN
				(SELECT 
						BILL_APPR_HDR.BA_ID,
						BILL_APPR_HDR.JOB_NUMBER,
						BILL_APPR_HDR.JOB_COMPONENT_NBR,
						[BILL_APPROVAL_COMMENT] = BILL_APPR_HDR.CLIENT_COMMENTS
					FROM 
						[dbo].[BILL_APPR_HDR]) AS BAC ON BAC.BA_ID = JC.SELECTED_BA_ID AND
														 BAC.JOB_NUMBER = BIA.JOB_NUMBER AND 
														 BAC.JOB_COMPONENT_NBR = BIA.JOB_COMPONENT_NBR LEFT OUTER JOIN
				(SELECT 
						BILL_APPR_HDR.BA_ID,
						BILL_APPR_HDR.JOB_NUMBER,
						BILL_APPR_HDR.JOB_COMPONENT_NBR,
						BILL_APPR_DTL.FNC_CODE,
						[BILL_APPROVAL_FUNCTION_COMMENT] = BILL_APPR_DTL.CLIENT_COMMENTS
					FROM 
						[dbo].[BILL_APPR_HDR] INNER JOIN
						[dbo].[BILL_APPR_DTL] ON BILL_APPR_DTL.BA_ID = BILL_APPR_HDR.BA_ID AND
												 BILL_APPR_DTL.JOB_NUMBER = BILL_APPR_HDR.JOB_NUMBER AND
												 BILL_APPR_DTL.JOB_COMPONENT_NBR = BILL_APPR_HDR.JOB_COMPONENT_NBR) AS BACF ON BACF.BA_ID = JC.SELECTED_BA_ID AND
																															   BACF.JOB_NUMBER = BIA.JOB_NUMBER AND 
																															   BACF.JOB_COMPONENT_NBR = BIA.JOB_COMPONENT_NBR AND 
																															   BACF.FNC_CODE = BIA.FNC_CODE LEFT OUTER JOIN
				(SELECT 
						JC.JOB_NUMBER,
						JC.JOB_COMPONENT_NBR,
						EST_LOG_COMMENT = CAST(EL.EST_LOG_COMMENT AS varchar(MAX)), 
						EST_LOG_COMMENT_HTML = CAST(EL.EST_LOG_COMMENT_HTML AS varchar(MAX)), 
						EST_COMP_COMMENT = CAST(EC.EST_COMP_COMMENT AS varchar(MAX)), 
						EST_COMP_COMMENT_HTML = CAST(EC.EST_COMP_COMMENT_HTML AS varchar(MAX)), 
						EST_QTE_COMMENT = CAST(EQ.EST_QTE_COMMENT AS varchar(MAX)),  
						EST_QTE_COMMENT_HTML = CAST(EQ.EST_QTE_COMMENT_HTML AS varchar(MAX)),
						EST_REV_COMMENT = CAST(ER.EST_REV_COMMENT AS varchar(MAX)),  
						EST_REV_COMMENT_HTML = CAST(ER.EST_REV_COMMENT_HTML AS varchar(MAX))
					FROM 
						[dbo].[JOB_COMPONENT] AS JC LEFT OUTER JOIN 
						[dbo].[ESTIMATE_APPROVAL] AS EA ON EA.JOB_NUMBER = JC.JOB_NUMBER AND 
														   EA.JOB_COMPONENT_NBR = JC.JOB_COMPONENT_NBR LEFT OUTER JOIN 
						[dbo].[ESTIMATE_LOG] AS EL ON EL.ESTIMATE_NUMBER = EA.ESTIMATE_NUMBER LEFT OUTER JOIN 
						[dbo].[ESTIMATE_COMPONENT] AS EC ON EC.EST_COMPONENT_NBR = EA.EST_COMPONENT_NBR AND 
															EC.ESTIMATE_NUMBER = EA.ESTIMATE_NUMBER LEFT OUTER JOIN 
						[dbo].[ESTIMATE_QUOTE] AS EQ ON EQ.EST_QUOTE_NBR = EA.EST_QUOTE_NBR AND 
														EQ.EST_COMPONENT_NBR = EA.EST_COMPONENT_NBR AND 
														EQ.ESTIMATE_NUMBER = EA.ESTIMATE_NUMBER LEFT OUTER JOIN 
						[dbo].[ESTIMATE_REV] AS ER ON ER.EST_REV_NBR = EA.EST_REVISION_NBR AND 
													  ER.EST_QUOTE_NBR = EA.EST_QUOTE_NBR AND 
													  ER.EST_COMPONENT_NBR = EA.EST_COMPONENT_NBR AND 
													  ER.ESTIMATE_NUMBER = EA.ESTIMATE_NUMBER LEFT OUTER JOIN 
						[dbo].[ESTIMATE_REV_DET] AS ERD ON ERD.EST_REV_NBR = ER.EST_REV_NBR AND 
														   ERD.EST_QUOTE_NBR = ER.EST_QUOTE_NBR AND 
														   ERD.EST_COMPONENT_NBR = ER.EST_COMPONENT_NBR AND 
														   ERD.ESTIMATE_NUMBER = ER.ESTIMATE_NUMBER
					GROUP BY 
						JC.JOB_NUMBER,
						JC.JOB_COMPONENT_NBR, 
						ERD.EST_REV_NBR,
						ERD.EST_QUOTE_NBR,
						ERD.EST_COMPONENT_NBR,
						ERD.ESTIMATE_NUMBER,
						CAST(EL.EST_LOG_COMMENT AS varchar(MAX)), 
						CAST(EC.EST_COMP_COMMENT AS varchar(MAX)), 
						CAST(EQ.EST_QTE_COMMENT AS varchar(MAX)), 
						CAST(ER.EST_REV_COMMENT AS varchar(MAX)),
						CAST(EL.EST_LOG_COMMENT_HTML AS varchar(MAX)), 
						CAST(EC.EST_COMP_COMMENT_HTML AS varchar(MAX)), 
						CAST(EQ.EST_QTE_COMMENT_HTML AS varchar(MAX)), 
						CAST(ER.EST_REV_COMMENT_HTML AS varchar(MAX))) AS ESTHC ON ESTHC.JOB_NUMBER = BIA.JOB_NUMBER AND
																				   ESTHC.JOB_COMPONENT_NBR = BIA.JOB_COMPONENT_NBR LEFT OUTER JOIN
				(SELECT 
						JC.JOB_NUMBER,
						JC.JOB_COMPONENT_NBR,
						ERD.FNC_CODE,
						EST_FNC_COMMENT = dbo.[advfn_invoice_printing_estimate_function_comment](ERD.ESTIMATE_NUMBER, ERD.EST_COMPONENT_NBR, ERD.EST_QUOTE_NBR, ERD.EST_REV_NBR, ERD.FNC_CODE, 0), 
						EST_FNC_COMMENT_HTML = dbo.[advfn_invoice_printing_estimate_function_comment](ERD.ESTIMATE_NUMBER, ERD.EST_COMPONENT_NBR, ERD.EST_QUOTE_NBR, ERD.EST_REV_NBR, ERD.FNC_CODE, 1),
						[EST_HRS_QTY] = CAST(SUM(ISNULL(ERD.EST_REV_QUANTITY, 0)) AS decimal(15, 2))
					FROM 
						[dbo].[JOB_COMPONENT] AS JC LEFT OUTER JOIN 
						[dbo].[ESTIMATE_APPROVAL] AS EA ON EA.JOB_NUMBER = JC.JOB_NUMBER AND 
														   EA.JOB_COMPONENT_NBR = JC.JOB_COMPONENT_NBR LEFT OUTER JOIN 
						[dbo].[ESTIMATE_LOG] AS EL ON EL.ESTIMATE_NUMBER = EA.ESTIMATE_NUMBER LEFT OUTER JOIN 
						[dbo].[ESTIMATE_COMPONENT] AS EC ON EC.EST_COMPONENT_NBR = EA.EST_COMPONENT_NBR AND 
															EC.ESTIMATE_NUMBER = EA.ESTIMATE_NUMBER LEFT OUTER JOIN 
						[dbo].[ESTIMATE_QUOTE] AS EQ ON EQ.EST_QUOTE_NBR = EA.EST_QUOTE_NBR AND 
														EQ.EST_COMPONENT_NBR = EA.EST_COMPONENT_NBR AND 
														EQ.ESTIMATE_NUMBER = EA.ESTIMATE_NUMBER LEFT OUTER JOIN 
						[dbo].[ESTIMATE_REV] AS ER ON ER.EST_REV_NBR = EA.EST_REVISION_NBR AND 
													  ER.EST_QUOTE_NBR = EA.EST_QUOTE_NBR AND 
													  ER.EST_COMPONENT_NBR = EA.EST_COMPONENT_NBR AND 
													  ER.ESTIMATE_NUMBER = EA.ESTIMATE_NUMBER LEFT OUTER JOIN 
						[dbo].[ESTIMATE_REV_DET] AS ERD ON ERD.EST_REV_NBR = ER.EST_REV_NBR AND 
														   ERD.EST_QUOTE_NBR = ER.EST_QUOTE_NBR AND 
														   ERD.EST_COMPONENT_NBR = ER.EST_COMPONENT_NBR AND 
														   ERD.ESTIMATE_NUMBER = ER.ESTIMATE_NUMBER
					GROUP BY 
						JC.JOB_NUMBER,
						JC.JOB_COMPONENT_NBR, 
						ERD.EST_REV_NBR,
						ERD.EST_QUOTE_NBR,
						ERD.EST_COMPONENT_NBR,
						ERD.ESTIMATE_NUMBER,
						ERD.FNC_CODE) AS ESTC ON ESTC.JOB_NUMBER = BIA.JOB_NUMBER AND
												 ESTC.JOB_COMPONENT_NBR = BIA.JOB_COMPONENT_NBR AND
												 ESTC.FNC_CODE = BIA.FNC_CODE INNER JOIN
				[dbo].[EMPLOYEE_CLOAK] AS EMP ON EMP.EMP_CODE = JC.EMP_CODE LEFT OUTER JOIN
				[dbo].[SALES_CLASS] AS SC ON SC.SC_CODE = JL.SC_CODE LEFT OUTER JOIN 
				[dbo].[CDP_CONTACT_HDR] AS CDPC ON CDPC.CDP_CONTACT_ID = JC.CDP_CONTACT_ID LEFT OUTER JOIN
				[dbo].[CAMPAIGN] AS CAMP ON CAMP.CMP_IDENTIFIER = JL.CMP_IDENTIFIER LEFT OUTER JOIN 
				[dbo].[CDP_CONTACT_HDR] AS OCDPC ON OCDPC.CDP_CONTACT_ID = BIA.CDP_CONTACT_ID
		ORDER BY
			BIA.CL_CODE,
			BIA.AR_INV_NBR, 
			BIA.AR_INV_SEQ DESC, 
			BIA.AR_TYPE,
			CASE WHEN ISNULL(@SortFunctionByType, 1) = 2 THEN CASE WHEN @PrintFunctionType = 3 OR (@PrintFunctionType = 1 AND P.PRD_CONSOL_FUNC = 1) THEN F.FNC_ORDER
															   ELSE BIA.FNC_ORDER END ELSE 0 END,
			CASE WHEN @PrintFunctionType = 3 OR (@PrintFunctionType = 1 AND P.PRD_CONSOL_FUNC = 1) THEN F.CONSOL_FNC
				 ELSE BIA.FNC_CODE END
	
	END ELSE BEGIN
	
		SELECT 	
			[InvoiceNumber] = BIA.AR_INV_NBR, 
			[InvoiceSequenceNumber] = BIA.AR_INV_SEQ,
			[InvoiceDate] = BIA.AR_INV_DATE,
			[InvoiceType] = BIA.AR_TYPE,
			[FullInvoiceNumber] = RIGHT('000000' + CAST(BIA.AR_INV_NBR AS varchar(6)), 6) + '-' + RIGHT('000' + CAST(BIA.AR_INV_SEQ AS varchar(4)), 4),
			[JobNumber] = BIA.JOB_NUMBER,
			[JobDescription] = RIGHT(REPLICATE('0', 6) + CONVERT(VARCHAR(20), JL.JOB_NUMBER), 6) + ' - ' + JL.JOB_DESC, 
			[ComponentNumber] = BIA.JOB_COMPONENT_NBR, 
			[ComponentDescription] = RIGHT(REPLICATE('0', 3) + CONVERT(VARCHAR(20), JC.JOB_COMPONENT_NBR), 3) + ' - ' + JC.JOB_COMP_DESC,
			[ClientCode] = BIA.CL_CODE,
			[ClientName] = C.CL_NAME,
			[DivisionCode] = BIA.DIV_CODE,
			[DivisionName] = D.DIV_NAME,
			[ProductCode] = BIA.PRD_CODE,
			[ProductName] = P.PRD_DESCRIPTION,
			[SCType] = CASE WHEN @PrintFunctionType = 3 OR (@PrintFunctionType = 1 AND P.PRD_CONSOL_FUNC = 1) THEN 'C'
							ELSE 'S' END,
			[FunctionType] = CASE WHEN @PrintFunctionType = 3 OR (@PrintFunctionType = 1 AND P.PRD_CONSOL_FUNC = 1) THEN F.FNC_TYPE
								  ELSE BIA.FNC_TYPE END,
			[FunctionOrder] = CAST(CASE WHEN ISNULL(@SortFunctionByType, 1) = 2 THEN CASE WHEN @PrintFunctionType = 3 OR (@PrintFunctionType = 1 AND P.PRD_CONSOL_FUNC = 1) THEN F.FNC_ORDER
																					  ELSE BIA.FNC_ORDER END ELSE 0 END AS smallint),
			[OriginalFunctionCode] = BIA.FNC_CODE,
			[FunctionCode] = CASE WHEN @PrintFunctionType = 3 OR (@PrintFunctionType = 1 AND P.PRD_CONSOL_FUNC = 1) THEN F.CONSOL_FNC
								  ELSE BIA.FNC_CODE END,
			[FunctionDescription] =  CASE WHEN ISNULL(BCD.FNC_DESC_SOURCE, 1) = 0 THEN BCD.FNC_DESC
										  ELSE CASE WHEN @PrintFunctionType = 3 OR (@PrintFunctionType = 1 AND P.PRD_CONSOL_FUNC = 1) THEN F.FNC_DESCRIPTION
													ELSE BIA.FNC_DESCRIPTION END END,
			[FunctionHeading] = CASE WHEN @PrintFunctionType = 3 OR (@PrintFunctionType = 1 AND P.PRD_CONSOL_FUNC = 1) THEN F.FNC_HEADING_DESC
									 ELSE BIA.FNC_HEADING_DESC END,
			[FunctionHeadingOrder] = CASE WHEN @PrintFunctionType = 3 OR (@PrintFunctionType = 1 AND P.PRD_CONSOL_FUNC = 1) THEN F.FNC_HEADING_SEQ
										  ELSE BIA.FNC_HEADING_SEQ END,
			[Quantity] = CASE WHEN @PrintFunctionType = 3 OR (@PrintFunctionType = 1 AND P.PRD_CONSOL_FUNC = 1) THEN CASE WHEN F.FNC_TYPE <> 'E' THEN BIA.HRS_QTY ELSE NULL END
							  ELSE CASE WHEN BIA.FNC_TYPE <> 'E' THEN BIA.HRS_QTY ELSE NULL END END, 
			[Hours] = CASE WHEN @PrintFunctionType = 3 OR (@PrintFunctionType = 1 AND P.PRD_CONSOL_FUNC = 1) THEN CASE WHEN F.FNC_TYPE = 'E' THEN BIA.HRS_QTY ELSE NULL END
						   ELSE CASE WHEN BIA.FNC_TYPE = 'E' THEN BIA.HRS_QTY ELSE NULL END END, 
			[Rate] = BIA.RATE,
			[NetAmount] = dbo.advfn_invoice_printing_xchge_net_amt(BIA.EXT_AMT, BIA.EXT_MARKUP_AMT, @TotalsShowCommissionSeparately, 
												  BIA.EXT_CITY_RESALE + BIA.EXT_COUNTY_RESALE + BIA.EXT_STATE_RESALE, 
												  @TotalsShowTaxSeparately, @ApplyExchangeRate, @ExchangeRateAmount), 
			[CommissionAmount] = dbo.advfn_invoice_printing_xchge_commission_amt(BIA.EXT_MARKUP_AMT, @TotalsShowCommissionSeparately, @ApplyExchangeRate, @ExchangeRateAmount),
			[NonResaleTax] = dbo.advfn_invoice_printing_xchge_tax_amt(BIA.EXT_NONRESALE_TAX, @TotalsShowTaxSeparately, @ApplyExchangeRate, @ExchangeRateAmount),
			[CityTax] = dbo.advfn_invoice_printing_xchge_tax_amt(BIA.EXT_CITY_RESALE, @TotalsShowTaxSeparately, @ApplyExchangeRate, @ExchangeRateAmount), 
			[CountyTax] = dbo.advfn_invoice_printing_xchge_tax_amt(BIA.EXT_COUNTY_RESALE, @TotalsShowTaxSeparately, @ApplyExchangeRate, @ExchangeRateAmount), 
			[StateTax] = dbo.advfn_invoice_printing_xchge_tax_amt(BIA.EXT_STATE_RESALE, @TotalsShowTaxSeparately, @ApplyExchangeRate, @ExchangeRateAmount), 
			[TotalTax] = (BIA.EXT_CITY_RESALE + BIA.EXT_COUNTY_RESALE + BIA.EXT_STATE_RESALE),
			[TotalAmount] = dbo.advfn_invoice_printing_xchge_total_amt(BIA.LINE_TOTAL, @ApplyExchangeRate, @ExchangeRateAmount),
			[DiscountAmount] = dbo.advfn_invoice_printing_xchge_total_amt(BIA.LINE_TOTAL, @ApplyExchangeRate, @ExchangeRateAmount) - dbo.advfn_invoice_printing_xchge_disocunt_amt(BIA.LINE_TOTAL - (BIA.EXT_CITY_RESALE + BIA.EXT_COUNTY_RESALE + BIA.EXT_STATE_RESALE), BIA.FNC_CODE, C.CLIENT_DISCOUNT_CODE, JC.CLIENT_DISCOUNT_CODE, @ApplyExchangeRate, @ExchangeRateAmount),
			[TTDNetAmount] = dbo.advfn_invoice_printing_xchge_net_amt(BIA.TTD_EXT_AMT, BIA.TTD_EXT_MARKUP_AMT, @TotalsShowCommissionSeparately, 
													 BIA.TTD_EXT_CITY_RESALE + BIA.TTD_EXT_COUNTY_RESALE + BIA.TTD_EXT_STATE_RESALE, 
													 @TotalsShowTaxSeparately, @ApplyExchangeRate, @ExchangeRateAmount), 
			[TTDCommissionAmount] = dbo.advfn_invoice_printing_xchge_commission_amt(BIA.TTD_EXT_MARKUP_AMT, @TotalsShowCommissionSeparately, @ApplyExchangeRate, @ExchangeRateAmount),
			[TTDNonResaleTax] = dbo.advfn_invoice_printing_xchge_tax_amt(BIA.TTD_EXT_NONRESALE_TAX, @TotalsShowTaxSeparately, @ApplyExchangeRate, @ExchangeRateAmount),
			[TTDCityTax] = dbo.advfn_invoice_printing_xchge_tax_amt(BIA.TTD_EXT_CITY_RESALE, @TotalsShowTaxSeparately, @ApplyExchangeRate, @ExchangeRateAmount), 
			[TTDCountyTax] = dbo.advfn_invoice_printing_xchge_tax_amt(BIA.TTD_EXT_COUNTY_RESALE, @TotalsShowTaxSeparately, @ApplyExchangeRate, @ExchangeRateAmount), 
			[TTDStateTax] = dbo.advfn_invoice_printing_xchge_tax_amt(BIA.TTD_EXT_STATE_RESALE, @TotalsShowTaxSeparately, @ApplyExchangeRate, @ExchangeRateAmount), 
			[TTDTotalTax] = (BIA.TTD_EXT_CITY_RESALE + BIA.TTD_EXT_COUNTY_RESALE + BIA.TTD_EXT_STATE_RESALE),
			[TTDTotalAmount] = dbo.advfn_invoice_printing_xchge_total_amt(BIA.TTD_LINE_TOTAL, @ApplyExchangeRate, @ExchangeRateAmount),
			[EstimateNetAmount] = dbo.advfn_invoice_printing_xchge_net_amt(BIA.EST_EXT_AMT, BIA.EST_EXT_MARKUP_AMT, @TotalsShowCommissionSeparately, 
														  BIA.EST_EXT_CITY_RESALE + BIA.EST_EXT_COUNTY_RESALE + BIA.EST_EXT_STATE_RESALE, 
														  @TotalsShowTaxSeparately, @ApplyExchangeRate, @ExchangeRateAmount), 
			[EstimateCommissionAmount] = dbo.advfn_invoice_printing_xchge_commission_amt(BIA.EST_EXT_MARKUP_AMT, @TotalsShowCommissionSeparately, @ApplyExchangeRate, @ExchangeRateAmount),
			[EstimateNonResaleTax] = dbo.advfn_invoice_printing_xchge_tax_amt(BIA.EST_EXT_NONRESALE_TAX, @TotalsShowTaxSeparately, @ApplyExchangeRate, @ExchangeRateAmount),
			[EstimateCityTax] = dbo.advfn_invoice_printing_xchge_tax_amt(BIA.EST_EXT_CITY_RESALE, @TotalsShowTaxSeparately, @ApplyExchangeRate, @ExchangeRateAmount), 
			[EstimateCountyTax] = dbo.advfn_invoice_printing_xchge_tax_amt(BIA.EST_EXT_COUNTY_RESALE, @TotalsShowTaxSeparately, @ApplyExchangeRate, @ExchangeRateAmount), 
			[EstimateStateTax] = dbo.advfn_invoice_printing_xchge_tax_amt(BIA.EST_EXT_STATE_RESALE, @TotalsShowTaxSeparately, @ApplyExchangeRate, @ExchangeRateAmount), 
			[EstimateTotalTax] = (BIA.EST_EXT_CITY_RESALE + BIA.EST_EXT_COUNTY_RESALE + BIA.EST_EXT_STATE_RESALE),
			[EstimateTotalAmount] = dbo.advfn_invoice_printing_xchge_total_amt(BIA.EST_LINE_TOTAL, @ApplyExchangeRate, @ExchangeRateAmount), 
			[PriorNetAmount] = dbo.advfn_invoice_printing_xchge_net_amt(BIA.PR_EXT_AMT, BIA.PR_EXT_MARKUP_AMT, @TotalsShowCommissionSeparately, 
													   BIA.PR_EXT_CITY_RESALE + BIA.PR_EXT_COUNTY_RESALE + BIA.PR_EXT_STATE_RESALE, 
													   @TotalsShowTaxSeparately, @ApplyExchangeRate, @ExchangeRateAmount), 
			[PriorCommissionAmount] = dbo.advfn_invoice_printing_xchge_commission_amt(BIA.PR_EXT_MARKUP_AMT, @TotalsShowCommissionSeparately, @ApplyExchangeRate, @ExchangeRateAmount),
			[PriorNonResaleTax] = dbo.advfn_invoice_printing_xchge_tax_amt(BIA.PR_EXT_NONRESALE_TAX, @TotalsShowTaxSeparately, @ApplyExchangeRate, @ExchangeRateAmount),
			[PriorCityTax] = dbo.advfn_invoice_printing_xchge_tax_amt(BIA.PR_EXT_CITY_RESALE, @TotalsShowTaxSeparately, @ApplyExchangeRate, @ExchangeRateAmount), 
			[PriorCountyTax] = dbo.advfn_invoice_printing_xchge_tax_amt(BIA.PR_EXT_COUNTY_RESALE, @TotalsShowTaxSeparately, @ApplyExchangeRate, @ExchangeRateAmount), 
			[PriorStateTax] = dbo.advfn_invoice_printing_xchge_tax_amt(BIA.PR_EXT_STATE_RESALE, @TotalsShowTaxSeparately, @ApplyExchangeRate, @ExchangeRateAmount), 
			[PriorTotalTax] = (BIA.PR_EXT_CITY_RESALE + BIA.PR_EXT_COUNTY_RESALE + BIA.PR_EXT_STATE_RESALE),
			[PriorTotalAmount] = dbo.advfn_invoice_printing_xchge_total_amt(BIA.PR_LINE_TOTAL, @ApplyExchangeRate, @ExchangeRateAmount),
			[BillingComment] = CASE WHEN ISNULL(CAST(BC.BILL_COMMENT AS varchar(MAX)), '') <> '' THEN CAST(BC.BILL_COMMENT AS varchar(MAX)) ELSE NULL END,
			[BillingJobComment] = CASE WHEN ISNULL(CAST(BCJ.JOB_COMMENT AS varchar(MAX)), '') <> '' THEN CAST(BCJ.JOB_COMMENT AS varchar(MAX)) ELSE NULL END,
			[BillingDetailComment] = CASE WHEN ISNULL(CAST(BCD.DTL_COMMENT AS varchar(MAX)), '') <> '' THEN CAST(BCD.DTL_COMMENT AS varchar(MAX)) ELSE NULL END,
			[JobComment] = CASE WHEN ISNULL(CAST(JL.JOB_COMMENTS AS varchar(MAX)), '') <> '' THEN CAST(JL.JOB_COMMENTS AS varchar(MAX)) ELSE NULL END,
			[BillingApprovalClientComment] = CASE WHEN ISNULL(CAST(BAC.BILL_APPROVAL_COMMENT AS varchar(MAX)), '') <> '' THEN CAST(BAC.BILL_APPROVAL_COMMENT AS varchar(MAX)) ELSE NULL END,
			[BillingApprovalFunctionComment] = CASE WHEN ISNULL(CAST(BACF.BILL_APPROVAL_FUNCTION_COMMENT AS varchar(MAX)), '') <> '' THEN CAST(BACF.BILL_APPROVAL_FUNCTION_COMMENT AS varchar(MAX)) ELSE NULL END,
			[JobComponentComment] = CASE WHEN ISNULL(CAST(JC.JOB_COMP_COMMENTS AS varchar(MAX)), '') <> '' THEN CAST(JC.JOB_COMP_COMMENTS AS varchar(MAX)) ELSE NULL END,
			[EstimateComment] = CASE WHEN @IncludeEstimateComment = 1 THEN CASE WHEN ISNULL(ESTHC.EST_LOG_COMMENT_HTML, '') <> '' THEN ESTHC.EST_LOG_COMMENT_HTML 
																				ELSE CASE WHEN ISNULL(ESTHC.EST_LOG_COMMENT, '') <> '' THEN ESTHC.EST_LOG_COMMENT 
																						  ELSE NULL END END
									 ELSE NULL END,
			[EstimateComponentComment] = CASE WHEN @IncludeEstimateComponentComment = 1 THEN CASE WHEN ISNULL(ESTHC.EST_COMP_COMMENT_HTML, '') <> '' THEN ESTHC.EST_COMP_COMMENT_HTML 
																								  ELSE CASE WHEN ISNULL(ESTHC.EST_COMP_COMMENT, '') <> '' THEN ESTHC.EST_COMP_COMMENT 
																											ELSE NULL END END
											  ELSE NULL END,
			[EstimateQuoteComment] = CASE WHEN @IncludeEstimateQuoteComment = 1 THEN CASE WHEN ISNULL(ESTHC.EST_QTE_COMMENT_HTML, '') <> '' THEN ESTHC.EST_QTE_COMMENT_HTML 
																						  ELSE CASE WHEN ISNULL(ESTHC.EST_QTE_COMMENT, '') <> '' THEN ESTHC.EST_QTE_COMMENT 
																									ELSE NULL END END
										  ELSE NULL END,
			[EstimateRevisionComment] = CASE WHEN @IncludeEstimateRevisionComment = 1 THEN CASE WHEN ISNULL(ESTHC.EST_REV_COMMENT_HTML, '') <> '' THEN ESTHC.EST_REV_COMMENT_HTML 
																								ELSE CASE WHEN ISNULL(ESTHC.EST_REV_COMMENT, '') <> '' THEN ESTHC.EST_REV_COMMENT 
																										  ELSE NULL END END
											 ELSE NULL END,
			[EstimateFunctionComment] = CASE WHEN @IncludeEstimateFunctionComment = 1 THEN CASE WHEN ISNULL(ESTC.EST_FNC_COMMENT_HTML, '') <> '' THEN @Font + ESTC.EST_FNC_COMMENT_HTML + @Font2 
																								ELSE CASE WHEN ISNULL(ESTC.EST_FNC_COMMENT, '') <> '' THEN @Font + ESTC.EST_FNC_COMMENT + @Font2 
																										  ELSE NULL END END
											 ELSE NULL END,
			[InvoiceDueDate] = ARIDD.AR_INV_DUE_DATE,
			[ClientReference] = JL.JOB_CLI_REF,
			[ClientPO] = JC.JOB_CL_PO_NBR,
			[AccountExecutive] = COALESCE((RTRIM(EMP.EMP_FNAME) + ' '),'') + COALESCE((EMP.EMP_MI + '. '),'') + COALESCE(EMP.EMP_LNAME,''),
			[SalesClassCode] = JL.SC_CODE,
			[SalesClassDescription] = SC.SC_DESCRIPTION,
			[Address] = CASE WHEN OCDPC.CDP_CONTACT_ID IS NOT NULL THEN dbo.advfn_invoice_printing_address(@AddressBlockType, @ShowCodes, @PrintClientName, @PrintDivisionName, @PrintProductDescription, @PrintContactAfterAddress,  
																											C.CL_CODE, C.CL_NAME, C.CL_ATTENTION,
																											C.CL_BADDRESS1, C.CL_BADDRESS2, C.CL_BCITY,
																											C.CL_BCOUNTY, C.CL_BSTATE, C.CL_BCOUNTRY, C.CL_BZIP,
																											D.DIV_CODE, D.DIV_NAME, D.DIV_ATTENTION,
																											D.DIV_BADDRESS1, D.DIV_BADDRESS2, D.DIV_BCITY,
																											D.DIV_BCOUNTY, D.DIV_BSTATE, D.DIV_BCOUNTRY, D.DIV_BZIP,
																											P.PRD_CODE, P.PRD_DESCRIPTION, P.PRD_ATTENTION,
																											P.PRD_BILL_ADDRESS1, P.PRD_BILL_ADDRESS2, P.PRD_BILL_CITY,
																											P.PRD_BILL_COUNTY, P.PRD_BILL_STATE, P.PRD_BILL_COUNTRY, P.PRD_BILL_ZIP,
																											OCDPC.CDP_CONTACT_ID, OCDPC.CONT_CODE, OCDPC.CONT_FNAME, OCDPC.CONT_LNAME, OCDPC.CONT_MI,
																											OCDPC.CONT_ADDRESS1, OCDPC.CONT_ADDRESS2, OCDPC.CONT_CITY,
																											OCDPC.CONT_COUNTY, OCDPC.CONT_STATE, OCDPC.CONT_COUNTRY, OCDPC.CONT_ZIP, @ContactType, 'Invoice') 
																   ELSE dbo.advfn_invoice_printing_address(@AddressBlockType, @ShowCodes, @PrintClientName, @PrintDivisionName, @PrintProductDescription, @PrintContactAfterAddress,  
																											C.CL_CODE, C.CL_NAME, C.CL_ATTENTION,
																											C.CL_BADDRESS1, C.CL_BADDRESS2, C.CL_BCITY,
																											C.CL_BCOUNTY, C.CL_BSTATE, C.CL_BCOUNTRY, C.CL_BZIP,
																											D.DIV_CODE, D.DIV_NAME, D.DIV_ATTENTION,
																											D.DIV_BADDRESS1, D.DIV_BADDRESS2, D.DIV_BCITY,
																											D.DIV_BCOUNTY, D.DIV_BSTATE, D.DIV_BCOUNTRY, D.DIV_BZIP,
																											P.PRD_CODE, P.PRD_DESCRIPTION, P.PRD_ATTENTION,
																											P.PRD_BILL_ADDRESS1, P.PRD_BILL_ADDRESS2, P.PRD_BILL_CITY,
																											P.PRD_BILL_COUNTY, P.PRD_BILL_STATE, P.PRD_BILL_COUNTRY, P.PRD_BILL_ZIP,
																											CDPC.CDP_CONTACT_ID, CDPC.CONT_CODE, CDPC.CONT_FNAME, CDPC.CONT_LNAME, CDPC.CONT_MI,
																											CDPC.CONT_ADDRESS1, CDPC.CONT_ADDRESS2, CDPC.CONT_CITY,
																											CDPC.CONT_COUNTY, CDPC.CONT_STATE, CDPC.CONT_COUNTRY, CDPC.CONT_ZIP, @ContactType, 'Job') END,
			[InvoiceCategory] = CASE WHEN @UseInvoiceCategoryDescription = 1 AND BIA.INV_CAT IS NOT NULL THEN BIA.INV_CAT_DESC 
									 WHEN @UseInvoiceCategoryDescription = 0 AND @InvoiceTitle IS NOT NULL AND DATALENGTH(@InvoiceTitle) > 0 THEN @InvoiceTitle
									 ELSE 'INVOICE' END,
			[InvoiceFooterComment] = CASE WHEN ISNULL(@InvoiceFooterCommentType, 1) = 2 THEN ISNULL(dbo.advfn_invoice_printing_comment('Invoices', 'Standard Footer', BIA.OFFICE_CODE, BIA.CL_CODE, BIA.DIV_CODE, BIA.PRD_CODE), C.CL_FOOTER)
										  WHEN ISNULL(@InvoiceFooterCommentType, 1) = 3 THEN @InvoiceFooterComment 
										  ELSE '' END,
			[InvoiceFooterCommentFontSize] = CASE WHEN ISNULL(@InvoiceFooterCommentType, 1) = 2 THEN ISNULL(dbo.advfn_invoice_printing_comment_font_size('Invoices', 'Standard Footer', BIA.OFFICE_CODE, BIA.CL_CODE, BIA.DIV_CODE, BIA.PRD_CODE), 10)
												  ELSE 10 END,
			[InsideDescription] = @GroupingOptionInsideDescription,
			[OutsideDescription] = @GroupingOptionOutsideDescription,
			[CampaignID] =  JL.CMP_IDENTIFIER,
			[CampaignCode] =  CAMP.CMP_CODE,
			[CampaignName] =  CAMP.CMP_NAME,
			[Campaign] =  CAMP.CMP_CODE + ' - ' + CAMP.CMP_NAME,
			[CampaignComment] =  CAST(CAMP.CMP_COMMENTS AS varchar(MAX)),
			[VATNumber] = C.VAT_NUMBER,
			[EstimateHours] = ESTC.EST_HRS_QTY,
			[TTDHoursBilled] = BIA.TTD_HRS_QTY
		FROM
			(SELECT 
					IT.*, 
					I.[AR_INV_NBR], 
					I.[AR_INV_SEQ], 
					I.[AR_TYPE],
					I.[AR_INV_DATE],
					I.[CL_CODE],
					I.[DIV_CODE],
					I.[PRD_CODE],
					I.[OFFICE_CODE],
					I.[INV_CAT],
					I.[INV_CAT_DESC],
					I.[CDP_CONTACT_ID]
				FROM 
					#INVOICE_ITEMS AS IT INNER JOIN 
					#INVOICE I ON I.JOB_NUMBER = IT.JOB_NUMBER AND
								  I.JOB_COMPONENT_NBR = IT.JOB_COMPONENT_NBR) AS BIA INNER JOIN 
				[dbo].[JOB_LOG] AS JL ON JL.JOB_NUMBER = BIA.JOB_NUMBER INNER JOIN
				[dbo].[JOB_COMPONENT] AS JC ON JC.JOB_NUMBER = BIA.JOB_NUMBER AND
											   JC.JOB_COMPONENT_NBR = BIA.JOB_COMPONENT_NBR LEFT OUTER JOIN 
				[dbo].[CLIENT] AS C ON C.CL_CODE = BIA.CL_CODE  LEFT OUTER JOIN 
				[dbo].[DIVISION] AS D ON D.CL_CODE = BIA.CL_CODE AND
										 D.DIV_CODE = BIA.DIV_CODE LEFT OUTER JOIN
				[dbo].[PRODUCT] AS P ON P.CL_CODE = BIA.CL_CODE AND 
										P.DIV_CODE = BIA.DIV_CODE AND 
										P.PRD_CODE = BIA.PRD_CODE INNER JOIN 
				(SELECT 
						F.FNC_CODE, 
						[CONSOL_FNC] = COALESCE(SF.FNC_CONSOLIDATION, F.FNC_CONSOLIDATION, F.FNC_CODE),
						[FNC_DESCRIPTION] = COALESCE(SF.FNC_DESCRIPTION, F.FNC_DESCRIPTION, F.FNC_DESCRIPTION),
						[FNC_TYPE] = COALESCE(SF.FNC_TYPE, F.FNC_TYPE, F.FNC_TYPE),
						[FNC_ORDER] = CAST(ISNULL(COALESCE(SF.FNC_ORDER, F.FNC_ORDER, F.FNC_ORDER), 0) AS smallint),
						[FNC_HEADING_DESC] = COALESCE(SFH.FNC_HEADING_DESC, FH.FNC_HEADING_DESC, FH.FNC_HEADING_DESC),
						[FNC_HEADING_SEQ] = COALESCE(SFH.FNC_HEADING_SEQ, FH.FNC_HEADING_SEQ, FH.FNC_HEADING_SEQ)
					FROM 
						[dbo].[FUNCTIONS] AS F LEFT OUTER JOIN 
						[dbo].[FUNCTIONS] AS SF ON SF.FNC_CODE = F.FNC_CONSOLIDATION LEFT OUTER JOIN 
						[dbo].[FNC_HEADING] AS FH ON FH.FNC_HEADING_ID = F.FNC_HEADING_ID LEFT OUTER JOIN 
						[dbo].[FNC_HEADING] AS SFH ON SFH.FNC_HEADING_ID = SF.FNC_HEADING_ID) AS F ON F.FNC_CODE = BIA.FNC_CODE LEFT OUTER JOIN
				(SELECT 
						BC.AR_INV_NBR,
						BC.AR_INV_SEQ,
						BC.BILL_COMMENT
					FROM 
						[dbo].[BILL_COMMENT] AS BC
					WHERE 
						BC.BC_ID = (SELECT MAX(BCM.BC_ID) FROM [dbo].[BILL_COMMENT] AS BCM WHERE BC.AR_INV_NBR = BCM.AR_INV_NBR AND BC.AR_INV_SEQ = BCM.AR_INV_SEQ)) AS BC ON BC.AR_INV_NBR = BIA.AR_INV_NBR AND 
																																											  BC.AR_INV_SEQ = BIA.AR_INV_SEQ LEFT OUTER JOIN
				(SELECT 
						BILL_APPR_HDR.AR_INV_NBR,
						BILL_APPR_HDR.JOB_NUMBER,
						BILL_APPR_HDR.JOB_COMPONENT_NBR,
						[BILL_APPROVAL_COMMENT] = BILL_APPR_HDR.CLIENT_COMMENTS
					FROM 
						[dbo].[BILL_APPR_HDR]
					WHERE 
						BILL_APPR_HDR.BA_ID = (SELECT MAX(BAC.BA_ID) FROM [dbo].[BILL_APPR_HDR] AS BAC WHERE BAC.JOB_NUMBER = BILL_APPR_HDR.JOB_NUMBER AND 
																											 BAC.JOB_COMPONENT_NBR = BILL_APPR_HDR.JOB_COMPONENT_NBR AND 
																											 BAC.AR_INV_NBR = BILL_APPR_HDR.AR_INV_NBR)) AS BAC ON BAC.AR_INV_NBR = BIA.AR_INV_NBR AND 
																																								   BAC.JOB_NUMBER = BIA.JOB_NUMBER AND 
																																								   BAC.JOB_COMPONENT_NBR = BIA.JOB_COMPONENT_NBR LEFT OUTER JOIN
				(SELECT 
						BILL_APPR_HDR.AR_INV_NBR,
						BILL_APPR_HDR.JOB_NUMBER,
						BILL_APPR_HDR.JOB_COMPONENT_NBR,
						BILL_APPR_DTL.FNC_CODE,
						[BILL_APPROVAL_FUNCTION_COMMENT] = BILL_APPR_DTL.CLIENT_COMMENTS
					FROM 
						[dbo].[BILL_APPR_HDR] INNER JOIN
						[dbo].[BILL_APPR_DTL] ON BILL_APPR_DTL.BA_ID = BILL_APPR_HDR.BA_ID AND
												 BILL_APPR_DTL.JOB_NUMBER = BILL_APPR_HDR.JOB_NUMBER AND
												 BILL_APPR_DTL.JOB_COMPONENT_NBR = BILL_APPR_HDR.JOB_COMPONENT_NBR
					WHERE 
						BILL_APPR_HDR.BA_ID = (SELECT MAX(BAC.BA_ID) FROM [dbo].[BILL_APPR_HDR] AS BAC WHERE BAC.JOB_NUMBER = BILL_APPR_HDR.JOB_NUMBER AND 
																											 BAC.JOB_COMPONENT_NBR = BILL_APPR_HDR.JOB_COMPONENT_NBR AND 
																											 BAC.AR_INV_NBR = BILL_APPR_HDR.AR_INV_NBR)) AS BACF ON BACF.AR_INV_NBR = BIA.AR_INV_NBR AND 
																																								    BACF.JOB_NUMBER = BIA.JOB_NUMBER AND 
																																								    BACF.JOB_COMPONENT_NBR = BIA.JOB_COMPONENT_NBR AND 
																																								    BACF.FNC_CODE = BIA.FNC_CODE LEFT OUTER JOIN
				(SELECT 
						JC.JOB_NUMBER,
						JC.JOB_COMPONENT_NBR,
						EST_LOG_COMMENT = CAST(EL.EST_LOG_COMMENT AS varchar(MAX)), 
						EST_LOG_COMMENT_HTML = CAST(EL.EST_LOG_COMMENT_HTML AS varchar(MAX)), 
						EST_COMP_COMMENT = CAST(EC.EST_COMP_COMMENT AS varchar(MAX)), 
						EST_COMP_COMMENT_HTML = CAST(EC.EST_COMP_COMMENT_HTML AS varchar(MAX)), 
						EST_QTE_COMMENT = CAST(EQ.EST_QTE_COMMENT AS varchar(MAX)),  
						EST_QTE_COMMENT_HTML = CAST(EQ.EST_QTE_COMMENT_HTML AS varchar(MAX)),
						EST_REV_COMMENT = CAST(ER.EST_REV_COMMENT AS varchar(MAX)),  
						EST_REV_COMMENT_HTML = CAST(ER.EST_REV_COMMENT_HTML AS varchar(MAX))
					FROM 
						[dbo].[JOB_COMPONENT] AS JC LEFT OUTER JOIN 
						[dbo].[ESTIMATE_APPROVAL] AS EA ON EA.JOB_NUMBER = JC.JOB_NUMBER AND 
														   EA.JOB_COMPONENT_NBR = JC.JOB_COMPONENT_NBR LEFT OUTER JOIN 
						[dbo].[ESTIMATE_LOG] AS EL ON EL.ESTIMATE_NUMBER = EA.ESTIMATE_NUMBER LEFT OUTER JOIN 
						[dbo].[ESTIMATE_COMPONENT] AS EC ON EC.EST_COMPONENT_NBR = EA.EST_COMPONENT_NBR AND 
															EC.ESTIMATE_NUMBER = EA.ESTIMATE_NUMBER LEFT OUTER JOIN 
						[dbo].[ESTIMATE_QUOTE] AS EQ ON EQ.EST_QUOTE_NBR = EA.EST_QUOTE_NBR AND 
														EQ.EST_COMPONENT_NBR = EA.EST_COMPONENT_NBR AND 
														EQ.ESTIMATE_NUMBER = EA.ESTIMATE_NUMBER LEFT OUTER JOIN 
						[dbo].[ESTIMATE_REV] AS ER ON ER.EST_REV_NBR = EA.EST_REVISION_NBR AND 
													  ER.EST_QUOTE_NBR = EA.EST_QUOTE_NBR AND 
													  ER.EST_COMPONENT_NBR = EA.EST_COMPONENT_NBR AND 
													  ER.ESTIMATE_NUMBER = EA.ESTIMATE_NUMBER LEFT OUTER JOIN 
						[dbo].[ESTIMATE_REV_DET] AS ERD ON ERD.EST_REV_NBR = ER.EST_REV_NBR AND 
														   ERD.EST_QUOTE_NBR = ER.EST_QUOTE_NBR AND 
														   ERD.EST_COMPONENT_NBR = ER.EST_COMPONENT_NBR AND 
														   ERD.ESTIMATE_NUMBER = ER.ESTIMATE_NUMBER
					GROUP BY 
						JC.JOB_NUMBER,
						JC.JOB_COMPONENT_NBR, 
						ERD.EST_REV_NBR,
						ERD.EST_QUOTE_NBR,
						ERD.EST_COMPONENT_NBR,
						ERD.ESTIMATE_NUMBER,
						CAST(EL.EST_LOG_COMMENT AS varchar(MAX)), 
						CAST(EC.EST_COMP_COMMENT AS varchar(MAX)), 
						CAST(EQ.EST_QTE_COMMENT AS varchar(MAX)), 
						CAST(ER.EST_REV_COMMENT AS varchar(MAX)),
						CAST(EL.EST_LOG_COMMENT_HTML AS varchar(MAX)), 
						CAST(EC.EST_COMP_COMMENT_HTML AS varchar(MAX)), 
						CAST(EQ.EST_QTE_COMMENT_HTML AS varchar(MAX)), 
						CAST(ER.EST_REV_COMMENT_HTML AS varchar(MAX))) AS ESTHC ON ESTHC.JOB_NUMBER = BIA.JOB_NUMBER AND
																				   ESTHC.JOB_COMPONENT_NBR = BIA.JOB_COMPONENT_NBR LEFT OUTER JOIN
				(SELECT 
						JC.JOB_NUMBER,
						JC.JOB_COMPONENT_NBR,
						ERD.FNC_CODE,
						EST_FNC_COMMENT = dbo.[advfn_invoice_printing_estimate_function_comment](ERD.ESTIMATE_NUMBER, ERD.EST_COMPONENT_NBR, ERD.EST_QUOTE_NBR, ERD.EST_REV_NBR, ERD.FNC_CODE, 0), 
						EST_FNC_COMMENT_HTML = dbo.[advfn_invoice_printing_estimate_function_comment](ERD.ESTIMATE_NUMBER, ERD.EST_COMPONENT_NBR, ERD.EST_QUOTE_NBR, ERD.EST_REV_NBR, ERD.FNC_CODE, 1),
						[EST_HRS_QTY] = CAST(SUM(ISNULL(ERD.EST_REV_QUANTITY, 0)) AS decimal(15, 2))
					FROM 
						[dbo].[JOB_COMPONENT] AS JC LEFT OUTER JOIN 
						[dbo].[ESTIMATE_APPROVAL] AS EA ON EA.JOB_NUMBER = JC.JOB_NUMBER AND 
														   EA.JOB_COMPONENT_NBR = JC.JOB_COMPONENT_NBR LEFT OUTER JOIN 
						[dbo].[ESTIMATE_LOG] AS EL ON EL.ESTIMATE_NUMBER = EA.ESTIMATE_NUMBER LEFT OUTER JOIN 
						[dbo].[ESTIMATE_COMPONENT] AS EC ON EC.EST_COMPONENT_NBR = EA.EST_COMPONENT_NBR AND 
															EC.ESTIMATE_NUMBER = EA.ESTIMATE_NUMBER LEFT OUTER JOIN 
						[dbo].[ESTIMATE_QUOTE] AS EQ ON EQ.EST_QUOTE_NBR = EA.EST_QUOTE_NBR AND 
														EQ.EST_COMPONENT_NBR = EA.EST_COMPONENT_NBR AND 
														EQ.ESTIMATE_NUMBER = EA.ESTIMATE_NUMBER LEFT OUTER JOIN 
						[dbo].[ESTIMATE_REV] AS ER ON ER.EST_REV_NBR = EA.EST_REVISION_NBR AND 
													  ER.EST_QUOTE_NBR = EA.EST_QUOTE_NBR AND 
													  ER.EST_COMPONENT_NBR = EA.EST_COMPONENT_NBR AND 
													  ER.ESTIMATE_NUMBER = EA.ESTIMATE_NUMBER LEFT OUTER JOIN 
						[dbo].[ESTIMATE_REV_DET] AS ERD ON ERD.EST_REV_NBR = ER.EST_REV_NBR AND 
														   ERD.EST_QUOTE_NBR = ER.EST_QUOTE_NBR AND 
														   ERD.EST_COMPONENT_NBR = ER.EST_COMPONENT_NBR AND 
														   ERD.ESTIMATE_NUMBER = ER.ESTIMATE_NUMBER
					GROUP BY 
						JC.JOB_NUMBER,
						JC.JOB_COMPONENT_NBR, 
						ERD.EST_REV_NBR,
						ERD.EST_QUOTE_NBR,
						ERD.EST_COMPONENT_NBR,
						ERD.ESTIMATE_NUMBER,
						ERD.FNC_CODE) AS ESTC ON ESTC.JOB_NUMBER = BIA.JOB_NUMBER AND
												 ESTC.JOB_COMPONENT_NBR = BIA.JOB_COMPONENT_NBR AND
												 ESTC.FNC_CODE = BIA.FNC_CODE LEFT OUTER JOIN
				(SELECT	
						AR.AR_INV_NBR, 
						AR.AR_INV_SEQ,
						AR.AR_TYPE, 
						AR_INV_DUE_DATE = CASE WHEN AR.DUE_DATE IS NOT NULL THEN AR.DUE_DATE
											   WHEN AR.DUE_DATE IS NULL AND AR.REC_TYPE IN ('P', 'S') THEN DATEADD(DAY, ISNULL(C.CL_P_PAYDAYS, 0), AR.AR_INV_DATE)
											   ELSE DATEADD(DAY, ISNULL(C.CL_M_PAYDAYS, 0), AR.AR_INV_DATE) END
					FROM 
						[dbo].[ACCT_REC] AS AR INNER JOIN 
						[dbo].[CLIENT] AS C ON C.CL_CODE = AR.CL_CODE) AS ARIDD ON ARIDD.AR_INV_NBR = BIA.AR_INV_NBR AND 
																				   ARIDD.AR_INV_SEQ = BIA.AR_INV_SEQ AND 
																				   ARIDD.AR_TYPE = BIA.AR_TYPE INNER JOIN
				[dbo].[EMPLOYEE_CLOAK] AS EMP ON EMP.EMP_CODE = JC.EMP_CODE LEFT OUTER JOIN
				[dbo].[SALES_CLASS] AS SC ON SC.SC_CODE = JL.SC_CODE LEFT OUTER JOIN 
				[dbo].[CDP_CONTACT_HDR] AS CDPC ON CDPC.CDP_CONTACT_ID = JC.CDP_CONTACT_ID LEFT OUTER JOIN
				[dbo].[BILL_COMMENTS_JOB] AS BCJ ON BCJ.INV_NBR = BIA.AR_INV_NBR AND
													BCJ.JOB_NUMBER = BIA.JOB_NUMBER AND
													BCJ.JOB_COMPONENT_NBR = BIA.JOB_COMPONENT_NBR LEFT OUTER JOIN
				[dbo].[BILL_COMMENTS_DTL] AS BCD ON BCD.INV_NBR = BIA.AR_INV_NBR AND
													BCD.JOB_NUMBER = BIA.JOB_NUMBER AND
													BCD.JOB_COMPONENT_NBR = BIA.JOB_COMPONENT_NBR AND
													BCD.FNC_CODE = BIA.FNC_CODE LEFT OUTER JOIN
				[dbo].[CAMPAIGN] AS CAMP ON CAMP.CMP_IDENTIFIER = JL.CMP_IDENTIFIER LEFT OUTER JOIN 
				[dbo].[CDP_CONTACT_HDR] AS OCDPC ON OCDPC.CDP_CONTACT_ID = BIA.CDP_CONTACT_ID
		ORDER BY
			BIA.CL_CODE,
			BIA.AR_INV_NBR, 
			BIA.AR_INV_SEQ DESC, 
			BIA.AR_TYPE,
			CASE WHEN ISNULL(@SortFunctionByType, 1) = 2 THEN CASE WHEN @PrintFunctionType = 3 OR (@PrintFunctionType = 1 AND P.PRD_CONSOL_FUNC = 1) THEN F.FNC_ORDER
															   ELSE BIA.FNC_ORDER END ELSE 0 END,
			CASE WHEN @PrintFunctionType = 3 OR (@PrintFunctionType = 1 AND P.PRD_CONSOL_FUNC = 1) THEN F.CONSOL_FNC
				 ELSE BIA.FNC_CODE END
	
	END
		
	DROP TABLE #JOBS_FUNCTIONS
	DROP TABLE #INVOICE_ITEMS
	DROP TABLE #INVOICE

END
GO