CREATE PROCEDURE [dbo].[advsp_media_plan_estimate_template_vendors]
	@MEDIA_PLAN_ESTIMATE_TEMPLATE_ID int,
	@MEDIA_TYPE char(1)
AS

SELECT
	Selected = CAST(CASE WHEN mpetv.VN_CODE IS NOT NULL THEN 1 ELSE 0 END as bit),
	VendorCode = v.VN_CODE,
	VendorName = v.VN_NAME
FROM dbo.VENDOR v
	LEFT OUTER JOIN dbo.MEDIA_PLAN_ESTIMATE_TEMPLATE_VENDOR mpetv ON v.VN_CODE = mpetv.VN_CODE AND mpetv.MEDIA_PLAN_ESTIMATE_TEMPLATE_ID = @MEDIA_PLAN_ESTIMATE_TEMPLATE_ID
WHERE v.VN_CATEGORY = @MEDIA_TYPE
AND v.VN_ACTIVE_FLAG = 1

UNION

SELECT
	Selected = CAST(CASE WHEN mpetv.VN_CODE IS NOT NULL THEN 1 ELSE 0 END as bit),
	VendorCode = v.VN_CODE,
	VendorName = v.VN_NAME
FROM dbo.MEDIA_PLAN_ESTIMATE_TEMPLATE_VENDOR mpetv 
    INNER JOIN dbo.VENDOR v ON v.VN_CODE = mpetv.VN_CODE AND mpetv.MEDIA_PLAN_ESTIMATE_TEMPLATE_ID = @MEDIA_PLAN_ESTIMATE_TEMPLATE_ID
ORDER BY v.VN_CODE
GO
