IF EXISTS ( SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID( N'[dbo].[advsp_ap_vendor_search_media_orders]') AND OBJECTPROPERTY( id, N'IsProcedure' ) = 1 )
	DROP PROCEDURE [dbo].[advsp_ap_vendor_search_media_orders]
GO

CREATE PROCEDURE [dbo].[advsp_ap_vendor_search_media_orders]
AS
BEGIN
	SET NOCOUNT ON;
		
	SELECT
		[Number] = U.OrderNumber,
		[VendorName] = V.VN_NAME,
		[VendorCode] = V.VN_CODE,
        [CampaignCode] = C.CMP_CODE,
        [CampaignName] = C.CMP_NAME
	FROM [dbo].VENDOR V
		INNER JOIN (
		SELECT DISTINCT
			A.VN_CODE,
			[OrderNumber] = A.ORDER_NBR,
            A.CMP_IDENTIFIER
		FROM
			[dbo].INTERNET_HEADER A, [dbo].INTERNET_DETAIL O, [dbo].PRODUCT D
		WHERE	
					A.ORDER_NBR = O.ORDER_NBR 
			AND		A.MEDIA_TYPE IS NOT NULL
			AND		O.BILL_TYPE_FLAG <> 1
			AND   	A.ORD_PROCESS_CONTRL NOT IN (5,6,12)
			AND		O.ACTIVE_REV = 1
			AND  	(LINE_CANCELLED IS NULL OR LINE_CANCELLED = 0)
			AND		A.CL_CODE = D.CL_CODE AND A.DIV_CODE = D.DIV_CODE AND A.PRD_CODE = D.PRD_CODE

	    UNION

		SELECT DISTINCT
			A.VN_CODE,
			[OrderNumber] = A.ORDER_NBR,
            A.CMP_IDENTIFIER
		FROM
			[dbo].V_MAG_HEADER A, [dbo].V_MAG_DETAIL O, [dbo].PRODUCT D
		WHERE	
					A.ORDER_NBR = O.ORDER_NBR 
			AND		A.MEDIA_TYPE IS NOT NULL
			AND   	A.ORD_PROCESS_CONTRL NOT IN (5,6,12)
			AND  	(O.LINE_CANCELLED IS NULL OR O.LINE_CANCELLED = 0)
			AND  	
					(
						(
						O.REV_NBR =
							( 
							SELECT MAX (REV_NBR)
							FROM dbo.V_MAG_DETAIL
							WHERE	ORDER_NBR = O.ORDER_NBR 
							AND		LINE_NBR = O.LINE_NBR
							)
						AND	O.SEQ_NBR =
							(
							SELECT MAX (SEQ_NBR)
							FROM dbo.V_MAG_DETAIL
							WHERE ORDER_NBR=O.ORDER_NBR
							AND LINE_NBR = O.LINE_NBR
							)
						) 	
						OR ACTIVE_REV=1
					)
			AND		A.CL_CODE = D.CL_CODE AND A.DIV_CODE = D.DIV_CODE AND A.PRD_CODE = D.PRD_CODE
			AND NOT EXISTS (SELECT ORDER_NBR, LINE_NBR 
							FROM dbo.MAGAZINE_DETAIL MD
							WHERE
								ACTIVE_REV=1 
							AND	BILL_TYPE_FLAG=1
							AND	A.ORDER_NBR = MD.ORDER_NBR
							AND O.LINE_NBR = MD.LINE_NBR)

	    UNION

		SELECT DISTINCT
			A.VN_CODE,
			[OrderNumber] = A.ORDER_NBR,
            A.CMP_IDENTIFIER
		FROM
			[dbo].V_NEWS_HEADER A, [dbo].V_NEWS_DETAIL O, [dbo].PRODUCT D
		WHERE	
					A.ORDER_NBR = O.ORDER_NBR 
			AND		A.MEDIA_TYPE IS NOT NULL
			AND   	A.ORD_PROCESS_CONTRL NOT IN (5,6,12)
			AND  	(O.LINE_CANCELLED IS NULL OR O.LINE_CANCELLED = 0)
			AND  	
					(
						(
						O.REV_NBR =
							( 
							SELECT MAX (REV_NBR)
							FROM dbo.V_NEWS_DETAIL
							WHERE	ORDER_NBR = O.ORDER_NBR 
							AND		LINE_NBR = O.LINE_NBR
							)
						AND	O.SEQ_NBR =
							(
							SELECT MAX (SEQ_NBR)
							FROM dbo.V_NEWS_DETAIL
							WHERE ORDER_NBR=O.ORDER_NBR
							AND LINE_NBR = O.LINE_NBR
							)
						) 	
						OR ACTIVE_REV=1
					)
			AND		A.CL_CODE = D.CL_CODE AND A.DIV_CODE = D.DIV_CODE AND A.PRD_CODE = D.PRD_CODE
			AND NOT EXISTS (SELECT ORDER_NBR, LINE_NBR 
							FROM dbo.NEWSPAPER_DETAIL ND
							WHERE
								ACTIVE_REV=1 
							AND	BILL_TYPE_FLAG=1
							AND	A.ORDER_NBR = ND.ORDER_NBR
							AND O.LINE_NBR = ND.LINE_NBR)

	    UNION

		SELECT DISTINCT
			A.VN_CODE,
			[OrderNumber] = A.ORDER_NBR,
            A.CMP_IDENTIFIER
		FROM
			[dbo].OUTDOOR_HEADER A, [dbo].OUTDOOR_DETAIL O, [dbo].PRODUCT D
		WHERE	
					A.ORDER_NBR = O.ORDER_NBR 
			AND		A.MEDIA_TYPE IS NOT NULL
			AND		O.BILL_TYPE_FLAG <> 1
			AND   	A.ORD_PROCESS_CONTRL NOT IN (5,6,12)
			AND		O.ACTIVE_REV = 1
			AND  	(LINE_CANCELLED IS NULL OR LINE_CANCELLED = 0)
			AND		A.CL_CODE = D.CL_CODE AND A.DIV_CODE = D.DIV_CODE AND A.PRD_CODE = D.PRD_CODE

	    UNION

		SELECT DISTINCT
			A.VN_CODE,
			[OrderNumber] = A.ORDER_NBR,
            A.CMP_IDENTIFIER
		FROM [dbo].RADIO_HEADER A, [dbo].PRODUCT P,
			(SELECT MAX(REV_NBR) AS REV_NBR, ORDER_NBR
			 FROM [dbo].RADIO_HEADER
			 GROUP BY ORDER_NBR) AS C
		WHERE
					MEDIA_TYPE IS NOT NULL
			AND		A.ORDER_NBR = C.ORDER_NBR AND A.REV_NBR = C.REV_NBR 
			AND  	(ORD_PROCESS_CONTRL != 6 AND RECONCILE_FLAG <> 1)
			AND		A.BILL_TYPE_FLAG <> 1
			AND		(DELETE_FLAG IS NULL OR DELETE_FLAG=0)
			AND		A.CL_CODE = P.CL_CODE AND A.DIV_CODE = P.DIV_CODE AND A.PRD_CODE = P.PRD_CODE
			
		UNION

		SELECT DISTINCT
			A.VN_CODE,
			[OrderNumber] = A.ORDER_NBR,
            A.CMP_IDENTIFIER
		FROM
			[dbo].RADIO_HDR A, [dbo].RADIO_DETAIL O, [dbo].PRODUCT P
		WHERE
					A.ORDER_NBR = O.ORDER_NBR
			AND		A.MEDIA_TYPE IS NOT NULL
			AND   	A.ORD_PROCESS_CONTRL NOT IN (5,6,12)
			AND		O.ACTIVE_REV = 1
			AND  	(LINE_CANCELLED IS NULL OR LINE_CANCELLED = 0)
			AND		BILL_TYPE_FLAG <> 1
			AND		A.CL_CODE = P.CL_CODE AND A.DIV_CODE = P.DIV_CODE AND A.PRD_CODE = P.PRD_CODE

	    UNION

		SELECT DISTINCT
			A.VN_CODE,
			[OrderNumber] = A.ORDER_NBR,
            A.CMP_IDENTIFIER
		FROM [dbo].TV_HEADER A, [dbo].PRODUCT P,
			(SELECT MAX(REV_NBR) AS REV_NBR, ORDER_NBR
			 FROM [dbo].TV_HEADER
			 GROUP BY ORDER_NBR) AS C
		WHERE
					MEDIA_TYPE IS NOT NULL
			AND		A.ORDER_NBR = C.ORDER_NBR AND A.REV_NBR = C.REV_NBR 
			AND  	(ORD_PROCESS_CONTRL != 6 AND RECONCILE_FLAG <> 1)
			AND		A.BILL_TYPE_FLAG <> 1
			AND		(DELETE_FLAG IS NULL OR DELETE_FLAG=0)
			AND		A.CL_CODE = P.CL_CODE AND A.DIV_CODE = P.DIV_CODE AND A.PRD_CODE = P.PRD_CODE
			
		UNION

		SELECT DISTINCT
			A.VN_CODE,
			[OrderNumber] = A.ORDER_NBR,
            A.CMP_IDENTIFIER
		FROM
			[dbo].TV_HDR A, [dbo].TV_DETAIL O, [dbo].PRODUCT P
		WHERE	
					A.ORDER_NBR = O.ORDER_NBR 
			AND		A.MEDIA_TYPE IS NOT NULL
			AND   	A.ORD_PROCESS_CONTRL NOT IN (5,6,12)
			AND		O.ACTIVE_REV = 1
			AND  	(LINE_CANCELLED IS NULL OR LINE_CANCELLED = 0)
			AND		BILL_TYPE_FLAG <> 1
			AND		A.CL_CODE = P.CL_CODE AND A.DIV_CODE = P.DIV_CODE AND A.PRD_CODE = P.PRD_CODE
		) AS U ON V.VN_CODE = U.VN_CODE
		LEFT OUTER JOIN dbo.CAMPAIGN C ON U.CMP_IDENTIFIER = C.CMP_IDENTIFIER
		ORDER BY
			U.OrderNumber DESC

END
GO
