

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[usp_cp_calendar_GetMediaData]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [dbo].[usp_cp_calendar_GetMediaData]
GO




CREATE PROCEDURE usp_cp_calendar_GetMediaData
@MagazineInc Char(1),
@NewspaperInc Char(1),
@InternetInc Char(1),
@OutOfHomeInc Char(1),
@TelevisionInc Char(1),
@RadioInc Char(1),
@AcceptedOrdersOnly Char(1),
@ClientCode VarChar(10),
@DivCode VarChar(10),
@ProdCode VarChar(10),
@MediaType VarChar(10),
@Campaign VarChar(100),
@ClientPO VarChar(100),
@VendorID VarChar(100),
@BuyerID Varchar(100),
@StartDate smalldatetime,
@EndDate smalldatetime,
@MatDueDate Char(1),
@ExtMatDueDate Char(1),
@CloseDate Char(1),
@ExtCloseDate Char(1),
@RunInsertionDate Char(1),
@MediaMonth Varchar(6),
@MediaYear Int,
@LineCancelled Char(1),
@debug bit,
@CDPID int
WITH RECOMPILE
AS

Declare @Rescrictions Int

/* Temporary table to store returned rows */
CREATE TABLE #media_rows( 	
	TYPE				varchar(6) NULL,
	EST_ACT			    varchar(50) NULL,
	OFFICE_CODE			varchar(10) NULL,
	ORDER_NBR			int NULL,
	ORDER_DESC			varchar(200) NULL,
	MEDIA_TYPE			varchar(10) NULL,
	CL_CODE				varchar(10) NULL,
	DIV_CODE			varchar(10) NULL,
	PRD_CODE			varchar(10) NULL,
	CMP_IDENTIFIER		int NULL,
	CMP_CODE			varchar(6) NULL,
	CMP_NAME			varchar(128) NULL,
	VN_CODE				varchar(6) NULL,
	VN_NAME				varchar(100) NULL,
	BUYER				varchar(50) NULL,
	CLIENT_PO			varchar(30) NULL,
	MARKET_CODE			varchar(30) NULL,
	MARKET_DESC			varchar(30) NULL,
	ORDER_ACCEPTED		int NULL,
	LINE_NBR			int NULL,
	ACTIVE_REV			int NULL,
	FLIGHT_DATES		varchar(200) NULL,
	START_DATE			SmallDateTime,
	END_DATE			SmallDateTime,
	MEDIA_MONTH			varchar(50) NULL,
	MEDIA_YEAR			varchar(50) NULL,
	CLOSE_DATE			SmallDateTime,
	MATL_CLOSE_DATE		SmallDateTime,
	EXT_CLOSE_DATE		SmallDateTime,
	EXT_MATL_DATE		SmallDateTime,
	SIZE				varchar(100) NULL,
	PRINT_COLUMNS		decimal(18,0) NULL,
	PRINT_INCHES		decimal(18,0) NULL,
	PRINT_LINES			decimal(18,0) NULL,
	AD_NUMBER			varchar(30) NULL,
	HEADLINE			varchar(200) NULL,
	INTERNET_TYPE		varchar(10) NULL,
	OUTDOOR_TYPE		varchar(10) NULL,
	MATERIAL			varchar(60) NULL,
	EDITION_ISSUE		varchar(30) NULL,
	SECTION				varchar(30) NULL,
	START_TIME			varchar(50) NULL,
	END_TIME			varchar(50) NULL,
	LENGTH				varchar(50) NULL,
	TAG					varchar(50) NULL,
	PROGRAMMING			varchar(50) NULL,
	MATL_NOTES			varchar(500) NULL,
	REMARKS				varchar(300) NULL,
	JOB_NUMBER			int NULL,
	JOB_COMPONENT_NBR	smallint NULL,
	PRODUCTION_SIZE		varchar(30) NULL,
	EST_NBR				int NULL,
	EST_LINE_NBR		int NULL,
	EST_REV_NBR			int NULL,
	LINE_TOTAL			decimal(14,2) NULL,
	COST_PER			decimal(18,0) NULL,
	IMPRESSIONS			decimal(18,0) NULL,
	LINE_CANCELLED		int NULL,
	CL_NAME				varchar(500) NULL,
	DIV_NAME			varchar(500) NULL,
	PRD_DESCRIPTION		varchar(500) NULL,
	REV_NBR				int NULL,
	MAT_COMP			SmallDateTime,
	SIZE_DESC			varchar(500) NULL)
	
DECLARE @sql nvarchar(4000),
		@paramlist nvarchar(4000),
		@sql2 nvarchar(4000),
		@paramlist2 nvarchar(4000),
		@sql3 nvarchar(4000),
		@paramlist3 nvarchar(4000),
		@sql4 nvarchar(4000),
		@paramlist4 nvarchar(4000),
		@sql5 nvarchar(4000),
		@paramlist5 nvarchar(4000),
		@sql6 nvarchar(4000),
		@paramlist6 nvarchar(4000),
		@sqlradio nvarchar(4000),
		@paramlist7 nvarchar(4000),
		@sqltv nvarchar(4000),
		@paramlist8 nvarchar(4000)

DECLARE @Radio_Header_Max_Rev TABLE( 
		ORDER_NBR			int NULL,
		REV_NBR				int NULL)
	
DECLARE @Radio_Header_Data TABLE( 
		TYPE				varchar(6) NULL,
		OFFICE_CODE			varchar(10) NULL,
		ORDER_NBR			int NULL,
		REV_NBR				int NULL,
		CL_CODE				varchar(10) NULL,
		DIV_CODE			varchar(10) NULL,
		PRD_CODE			varchar(10) NULL,
		ORDER_DESC			varchar(200) NULL,
		VN_CODE				varchar(10) NULL,
		VN_NAME				varchar(100) NULL,
		BUYER				varchar(50) NULL,
		CMP_IDENTIFIER		int NULL,
		CMP_NAME			varchar(128) NULL,
		MEDIA_TYPE			varchar(6) NULL,
		MARKET_CODE			varchar(30) NULL,
		MARKET_DESC			varchar(30) NULL,
		FLIGHT_FROM			SmallDateTime,
		FLIGHT_TO			SmallDateTime,
		CLIENT_PO			varchar(30) NULL,
		CL_NAME				varchar(500) NULL,
		DIV_NAME			varchar(500) NULL,
		PRD_DESCRIPTION		varchar(500) NULL)

DECLARE @Radio_Detail_Max_Rev TABLE( 
		ORDER_NBR			int NULL,
		LINE_NBR			int NULL,
		REV_NBR				int NULL,
		BRDCAST_YEAR		int NULL)

DECLARE @Radio_Detail_Max_Rev_Seq TABLE( 
		ORDER_NBR			int NULL,
		LINE_NBR			int NULL,
		REV_NBR				int NULL,
		SEQ_NBR				int NULL,
		BRDCAST_YEAR		int NULL)

DECLARE @Radio_Detail_Data_No_Amounts TABLE( 
		ORDER_NBR			int NULL,
		LINE_NBR			int NULL,
		BRDCAST_YEAR		int NULL,
		CLOSE_DATE			SmallDateTime,
		EXT_CLOSE_DATE		SmallDateTime,
		MATL_CLOSE_DATE		SmallDateTime,		
		EXT_MATL_DATE		SmallDateTime,
		JOB_NUMBER			int NULL,
		JOB_COMPONENT_NBR	smallint NULL,
		START_TIME			varchar(15) NULL,
		END_TIME			varchar(15) NULL,
		LENGTH				smallint NULL,
		PROGRAMMING			varchar(50) NULL,
		TAG					varchar(15) NULL,
		REMARKS				varchar(500) NULL,
		MATL_NOTES			varchar(500) NULL,
		LINE_CANCELLED		int NULL,
		MAT_COMP			SmallDateTime)

--DECLARE @Radio_Detail_Amounts TABLE( 
--		ORDER_NBR			int NULL,
--		LINE_NBR			int NULL,
--		BRDCAST_YEAR		int NULL,
--		MONTH				int NULL,
--		MEDIA_MONTH			varchar(50) NULL,
		
DECLARE @TV_Header_Max_Rev TABLE( 
		ORDER_NBR			int NULL,
		REV_NBR				int NULL)

DECLARE @TV_Header_Data TABLE( 
		TYPE				varchar(6) NULL,
		OFFICE_CODE			varchar(10) NULL,
		ORDER_NBR			int NULL,
		REV_NBR				int NULL,
		CL_CODE				varchar(10) NULL,
		DIV_CODE			varchar(10) NULL,
		PRD_CODE			varchar(10) NULL,
		ORDER_DESC			varchar(200) NULL,
		VN_CODE				varchar(10) NULL,
		VN_NAME				varchar(100) NULL,
		BUYER				varchar(50) NULL,
		CMP_IDENTIFIER		int NULL,
		CMP_NAME			varchar(128) NULL,
		MEDIA_TYPE			varchar(10) NULL,
		MARKET_CODE			varchar(30) NULL,
		MARKET_DESC			varchar(30) NULL,
		FLIGHT_FROM			SmallDateTime,
		FLIGHT_TO			SmallDateTime,
		CLIENT_PO			varchar(30) NULL,
		CL_NAME				varchar(500) NULL,
		DIV_NAME			varchar(500) NULL,
		PRD_DESCRIPTION		varchar(500) NULL)

DECLARE @TV_Detail_Max_Rev TABLE( 
		ORDER_NBR			int NULL,
		LINE_NBR			int NULL,
		REV_NBR				int NULL,
		--SEQ_NBR				int NULL,
		BRDCAST_YEAR		int NULL)

DECLARE @TV_Detail_Max_Rev_Seq TABLE( 
		ORDER_NBR			int NULL,
		LINE_NBR			int NULL,
		REV_NBR				int NULL,
		SEQ_NBR				int NULL,
		BRDCAST_YEAR		int NULL)

DECLARE @TV_Detail_Data_No_Amounts TABLE( 
		ORDER_NBR			int NULL,
		LINE_NBR			int NULL,
		BRDCAST_YEAR		int NULL,
		CLOSE_DATE			SmallDateTime,
		EXT_CLOSE_DATE		SmallDateTime,
		MATL_CLOSE_DATE		SmallDateTime,		
		EXT_MATL_DATE		SmallDateTime,
		JOB_NUMBER			int NULL,
		JOB_COMPONENT_NBR	smallint NULL,
		START_TIME			varchar(15) NULL,
		END_TIME			varchar(15) NULL,
		LENGTH				smallint NULL,
		PROGRAMMING			varchar(50) NULL,
		TAG					varchar(15) NULL,
		REMARKS				varchar(500) NULL,
		MATL_NOTES			varchar(500) NULL,
		LINE_CANCELLED		int NULL,
		MAT_COMP			SmallDateTime)

--DECLARE @TV_Detail_Amounts TABLE( 
--		ORDER_NBR			int NULL,
--		LINE_NBR			int NULL,
--		BRDCAST_YEAR		int NULL,
--		MONTH				int NULL,
--		MEDIA_MONTH			varchar(50) NULL,

Select @Rescrictions = Count(*) 
FROM CP_SEC_CLIENT
Where CDP_CONTACT_ID = @CDPID

 --Magazine Media Data
If @MagazineInc = 'Y'
SELECT @sql = 
	'INSERT INTO #media_rows
     SELECT ''M'' AS TYPE, ''A'' AS EST_ACT, MH.OFFICE_CODE, MH.ORDER_NBR,
		 MH.ORDER_DESC, MH.MEDIA_TYPE, MH.CL_CODE, 
		 MH.DIV_CODE, MH.PRD_CODE, MH.CMP_IDENTIFIER, 
		 MH.CMP_CODE, C.CMP_NAME, MH.VN_CODE, V.VN_NAME, MH.BUYER, MH.CLIENT_PO, 
		 MH.MARKET_CODE, M.MARKET_DESC, MH.ORDER_ACCEPTED, MD.LINE_NBR, 
		 MD.ACTIVE_REV,'''' AS FLIGHT_DATES, MD.START_DATE, MD.END_DATE, 
		 '''' AS MEDIA_MONTH, '''' AS MEDIA_YEAR,
		 MD.CLOSE_DATE, MD.MATL_CLOSE_DATE, MD.EXT_CLOSE_DATE,
		 MD.EXT_MATL_DATE, MD.SIZE,
		 0 AS PRINT_COLUMNS, 0 AS PRINT_INCHES, 0 AS PRINT_LINES, MD.AD_NUMBER, 
	     MD.HEADLINE, '''' AS INTERNET_TYPE, '''' AS OUTDOOR_TYPE, MD.MATERIAL, MD.EDITION_ISSUE, 
		 '''' AS SECTION, '''' AS START_TIME, '''' AS END_TIME,'''' AS LENGTH, '''' AS TAG, '''' AS PROGRAMMING,
		 '''' AS MATL_NOTES, '''' AS REMARKS,
         MD.JOB_NUMBER, MD.JOB_COMPONENT_NBR, MD.PRODUCTION_SIZE,
		 MD.EST_NBR, MD.EST_LINE_NBR, MD.EST_REV_NBR, 
		 MD.LINE_TOTAL, 0 AS COST_PER, 0 AS IMPRESSIONS, MD.LINE_CANCELLED, CL.CL_NAME, D.DIV_NAME, P.PRD_DESCRIPTION, MD.REV_NBR, MD.MAT_COMP, '''' AS SIZE_DESC
	 FROM MAGAZINE_HEADER MH INNER JOIN MAGAZINE_DETAIL MD ON MH.ORDER_NBR = MD.ORDER_NBR
						  INNER JOIN VENDOR V ON MH.VN_CODE = V.VN_CODE
						  INNER JOIN CLIENT AS CL ON MH.CL_CODE = CL.CL_CODE INNER JOIN
						  DIVISION AS D ON CL.CL_CODE = D.CL_CODE INNER JOIN
						  PRODUCT AS P ON MH.CL_CODE = P.CL_CODE AND MH.DIV_CODE = P.DIV_CODE AND 
						  MH.PRD_CODE = P.PRD_CODE AND D.CL_CODE = P.CL_CODE AND 
						  D.DIV_CODE = P.DIV_CODE	
						  LEFT OUTER JOIN CAMPAIGN C ON MH.CMP_IDENTIFIER = C.CMP_IDENTIFIER
						  LEFT OUTER JOIN MARKET M ON MH.MARKET_CODE = M.MARKET_CODE'
		if @Rescrictions > 0 
			SELECT @sql = @sql + ' LEFT OUTER JOIN CP_SEC_CLIENT SC ON MH.CL_CODE = SC.CL_CODE AND 
						          MH.DIV_CODE = SC.DIV_CODE AND MH.PRD_CODE = SC.PRD_CODE 
								  WHERE SC.CDP_CONTACT_ID = @CDPID'
		else
			SELECT @sql = @sql + ' WHERE 1=1'

		if @AcceptedOrdersOnly = 'Y'
			SELECT @sql = @sql + ' AND MH.ORDER_ACCEPTED = 1'
		if @LineCancelled = 'N'
			SELECT @sql = @sql + ' AND MD.LINE_CANCELLED IS NULL'
		if @MatDueDate = 'Y'
			 SELECT @sql = @sql + ' AND MH.ORD_PROCESS_CONTRL <> 6 AND MD.ACTIVE_REV=1 AND MATL_CLOSE_DATE >= @StartDate AND MATL_CLOSE_DATE <= @EndDate'
		if @ExtMatDueDate = 'Y' 
			SELECT @sql = @sql + ' AND MH.ORD_PROCESS_CONTRL <> 6 AND MD.ACTIVE_REV=1 AND EXT_MATL_DATE >= @StartDate AND EXT_MATL_DATE <= @EndDate'
		if @CloseDate = 'Y'
			SELECT @sql = @sql + ' AND MH.ORD_PROCESS_CONTRL <> 6 AND MD.ACTIVE_REV=1 AND CLOSE_DATE >= @StartDate AND CLOSE_DATE <= @EndDate'
		if @ExtCloseDate = 'Y'
			SELECT @sql = @sql + ' AND MH.ORD_PROCESS_CONTRL <> 6 AND MD.ACTIVE_REV=1 AND EXT_CLOSE_DATE >= @StartDate AND EXT_CLOSE_DATE <= @EndDate'
		if @RunInsertionDate = 'Y' and @LineCancelled = 'N' and @Rescrictions > 0
			SELECT @sql = @sql + ' AND MH.ORD_PROCESS_CONTRL <> 6 AND MD.ACTIVE_REV=1 AND MD.START_DATE >= @StartDate AND MD.START_DATE <= @EndDate OR SC.CDP_CONTACT_ID = @CDPID AND MD.LINE_CANCELLED IS NULL AND MH.ORD_PROCESS_CONTRL <> 6 AND MD.ACTIVE_REV=1 AND MD.END_DATE >= @StartDate AND MD.END_DATE <= @EndDate OR SC.CDP_CONTACT_ID = @CDPID AND MD.LINE_CANCELLED IS NULL AND MH.ORD_PROCESS_CONTRL <> 6 AND MD.ACTIVE_REV=1 AND @StartDate >= MD.START_DATE AND @StartDate <= MD.END_DATE OR SC.CDP_CONTACT_ID = @CDPID AND MD.LINE_CANCELLED IS NULL AND MH.ORD_PROCESS_CONTRL <> 6 AND MD.ACTIVE_REV=1 AND @EndDate >= MD.START_DATE AND @EndDate <= MD.END_DATE					 '
		if @RunInsertionDate = 'Y' and @LineCancelled = 'Y' and @Rescrictions > 0
			SELECT @sql = @sql + ' AND MH.ORD_PROCESS_CONTRL <> 6 AND MD.ACTIVE_REV=1 AND MD.START_DATE >= @StartDate AND MD.START_DATE <= @EndDate OR SC.CDP_CONTACT_ID = @CDPID AND MH.ORD_PROCESS_CONTRL <> 6 AND MD.ACTIVE_REV=1 AND MD.END_DATE >= @StartDate AND MD.END_DATE <= @EndDate OR SC.CDP_CONTACT_ID = @CDPID AND MH.ORD_PROCESS_CONTRL <> 6 AND MD.ACTIVE_REV=1 AND @StartDate >= MD.START_DATE AND @StartDate <= MD.END_DATE OR SC.CDP_CONTACT_ID = @CDPID AND MH.ORD_PROCESS_CONTRL <> 6 AND MD.ACTIVE_REV=1 AND @EndDate >= MD.START_DATE AND @EndDate <= MD.END_DATE					 '
		if @RunInsertionDate = 'Y' and @LineCancelled = 'N' and @Rescrictions = 0
			SELECT @sql = @sql + ' AND MH.ORD_PROCESS_CONTRL <> 6 AND MD.ACTIVE_REV=1 AND MD.START_DATE >= @StartDate AND MD.START_DATE <= @EndDate OR MD.LINE_CANCELLED IS NULL AND MH.ORD_PROCESS_CONTRL <> 6 AND MD.ACTIVE_REV=1 AND MD.END_DATE >= @StartDate AND MD.END_DATE <= @EndDate OR MD.LINE_CANCELLED IS NULL AND MH.ORD_PROCESS_CONTRL <> 6 AND MD.ACTIVE_REV=1 AND @StartDate >= MD.START_DATE AND @StartDate <= MD.END_DATE OR MD.LINE_CANCELLED IS NULL AND MH.ORD_PROCESS_CONTRL <> 6 AND MD.ACTIVE_REV=1 AND @EndDate >= MD.START_DATE AND @EndDate <= MD.END_DATE					 '
		if @RunInsertionDate = 'Y' and @LineCancelled = 'Y' and @Rescrictions = 0
			SELECT @sql = @sql + ' AND MH.ORD_PROCESS_CONTRL <> 6 AND MD.ACTIVE_REV=1 AND MD.START_DATE >= @StartDate AND MD.START_DATE <= @EndDate OR MH.ORD_PROCESS_CONTRL <> 6 AND MD.ACTIVE_REV=1 AND MD.END_DATE >= @StartDate AND MD.END_DATE <= @EndDate OR MH.ORD_PROCESS_CONTRL <> 6 AND MD.ACTIVE_REV=1 AND @StartDate >= MD.START_DATE AND @StartDate <= MD.END_DATE OR MH.ORD_PROCESS_CONTRL <> 6 AND MD.ACTIVE_REV=1 AND @EndDate >= MD.START_DATE AND @EndDate <= MD.END_DATE					 '
		IF @debug = 1                                                      
		   PRINT @sql     

		SELECT @paramlist = '@StartDate smalldatetime, @EndDate smalldatetime, @CDPID varchar(20)'

		EXEC sp_executesql @sql, @paramlist, @StartDate, @EndDate, @CDPID
                                                  
-- Newspaper Media Data
If @NewspaperInc = 'Y'
	SELECT @sql2 = 
	'INSERT INTO #media_rows
     SELECT ''N'' AS TYPE, ''A'' AS EST_ACT, NH.OFFICE_CODE, NH.ORDER_NBR, 
		NH.ORDER_DESC, NH.MEDIA_TYPE, NH.CL_CODE, 
		NH.DIV_CODE, NH.PRD_CODE, NH.CMP_IDENTIFIER, 
		NH.CMP_CODE, C.CMP_NAME, NH.VN_CODE, V.VN_NAME, NH.BUYER, NH.CLIENT_PO, 
		NH.MARKET_CODE, M.MARKET_DESC, NH.ORDER_ACCEPTED, ND.LINE_NBR, 
		ND.ACTIVE_REV,'''' AS FLIGHT_DATES, ND.START_DATE, ND.END_DATE, 
		'''' AS MEDIA_MONTH, '''' AS MEDIA_YEAR,
		ND.CLOSE_DATE, ND.MATL_CLOSE_DATE, ND.EXT_CLOSE_DATE, 
		ND.EXT_MATL_DATE, ND.SIZE,
		ND.PRINT_COLUMNS, ND.PRINT_INCHES, ND.PRINT_LINES,
		ND.AD_NUMBER,	ND.HEADLINE,'''' AS INTERNET_TYPE, '''' AS OUTDOOR_TYPE,
		ND.MATERIAL, ND.EDITION_ISSUE, 
		ND.SECTION,'''' AS START_TIME, '''' AS END_TIME,'''' AS LENGTH, '''' AS TAG, '''' AS PROGRAMMING,'''' AS MATL_NOTES, '''' AS REMARKS,
		ND.JOB_NUMBER, ND.JOB_COMPONENT_NBR, 
		ND.PRODUCTION_SIZE, ND.EST_NBR, ND.EST_LINE_NBR, 
		ND.EST_REV_NBR, ND.LINE_TOTAL,0 AS COST_PER, 0 AS IMPRESSIONS, ND.LINE_CANCELLED,
		CL.CL_NAME, D.DIV_NAME, P.PRD_DESCRIPTION, ND.REV_NBR, ND.MAT_COMP, '''' AS SIZE_DESC
	FROM NEWSPAPER_HEADER NH INNER JOIN NEWSPAPER_DETAIL ND ON NH.ORDER_NBR = ND.ORDER_NBR
						  INNER JOIN VENDOR V ON NH.VN_CODE = V.VN_CODE
						  INNER JOIN CLIENT AS CL ON NH.CL_CODE = CL.CL_CODE INNER JOIN
						  DIVISION AS D ON CL.CL_CODE = D.CL_CODE INNER JOIN
						  PRODUCT AS P ON NH.CL_CODE = P.CL_CODE AND NH.DIV_CODE = P.DIV_CODE AND 
						  NH.PRD_CODE = P.PRD_CODE AND D.CL_CODE = P.CL_CODE AND 
						  D.DIV_CODE = P.DIV_CODE
						  LEFT OUTER JOIN CAMPAIGN C ON NH.CMP_IDENTIFIER = C.CMP_IDENTIFIER
						  LEFT OUTER JOIN MARKET M ON NH.MARKET_CODE = M.MARKET_CODE'
		if @Rescrictions > 0 
			SELECT @sql2 = @sql2 + ' LEFT OUTER JOIN CP_SEC_CLIENT SC ON NH.CL_CODE = SC.CL_CODE AND 
						          NH.DIV_CODE = SC.DIV_CODE AND NH.PRD_CODE = SC.PRD_CODE 
								  WHERE SC.CDP_CONTACT_ID = @CDPID'
		else
			SELECT @sql2 = @sql2 + ' WHERE 1=1'	  

		if @AcceptedOrdersOnly = 'Y'
			SELECT @sql2 = @sql2 + ' AND NH.ORDER_ACCEPTED = 1'
		if @LineCancelled = 'N'
			SELECT @sql2 = @sql2 + ' AND ND.LINE_CANCELLED IS NULL'			
		if @MatDueDate = 'Y'
			SELECT @sql2 = @sql2 + ' AND NH.ORD_PROCESS_CONTRL <> 6 AND ND.ACTIVE_REV=1 AND MATL_CLOSE_DATE >= @StartDate AND MATL_CLOSE_DATE <= @EndDate'
		if @ExtMatDueDate = 'Y' 
			SELECT @sql2 = @sql2 + ' AND NH.ORD_PROCESS_CONTRL <> 6 AND ND.ACTIVE_REV=1 AND EXT_MATL_DATE >= @StartDate AND EXT_MATL_DATE <= @EndDate'
		if @CloseDate = 'Y'
			SELECT @sql2 = @sql2 + ' AND NH.ORD_PROCESS_CONTRL <> 6 AND ND.ACTIVE_REV=1 AND CLOSE_DATE >= @StartDate AND CLOSE_DATE <= @EndDate'
		if @ExtCloseDate = 'Y'
			SELECT @sql2 = @sql2 + ' AND NH.ORD_PROCESS_CONTRL <> 6 AND ND.ACTIVE_REV=1 AND EXT_CLOSE_DATE >= @StartDate AND EXT_CLOSE_DATE <= @EndDate'
		if @RunInsertionDate = 'Y' and @LineCancelled = 'N' and @Rescrictions > 0
			SELECT @sql2 = @sql2 + ' AND NH.ORD_PROCESS_CONTRL <> 6 AND ND.ACTIVE_REV=1 AND ND.START_DATE >= @StartDate AND ND.START_DATE <= @EndDate OR SC.CDP_CONTACT_ID = @CDPID AND ND.LINE_CANCELLED IS NULL AND NH.ORD_PROCESS_CONTRL <> 6 AND ND.ACTIVE_REV=1 AND ND.END_DATE >= @StartDate AND ND.END_DATE <= @EndDate OR SC.CDP_CONTACT_ID = @CDPID AND ND.LINE_CANCELLED IS NULL AND NH.ORD_PROCESS_CONTRL <> 6 AND ND.ACTIVE_REV=1 AND @StartDate >= ND.START_DATE AND @StartDate <= ND.END_DATE OR SC.CDP_CONTACT_ID = @CDPID AND ND.LINE_CANCELLED IS NULL AND NH.ORD_PROCESS_CONTRL <> 6 AND ND.ACTIVE_REV=1 AND @EndDate >= ND.START_DATE AND @EndDate <= ND.END_DATE					 '
		if @RunInsertionDate = 'Y' and @LineCancelled = 'Y' and @Rescrictions > 0
			SELECT @sql2 = @sql2 + ' AND NH.ORD_PROCESS_CONTRL <> 6 AND ND.ACTIVE_REV=1 AND ND.START_DATE >= @StartDate AND ND.START_DATE <= @EndDate OR SC.CDP_CONTACT_ID = @CDPID AND NH.ORD_PROCESS_CONTRL <> 6 AND ND.ACTIVE_REV=1 AND ND.END_DATE >= @StartDate AND ND.END_DATE <= @EndDate OR SC.CDP_CONTACT_ID = @CDPID AND NH.ORD_PROCESS_CONTRL <> 6 AND ND.ACTIVE_REV=1 AND @StartDate >= ND.START_DATE AND @StartDate <= ND.END_DATE OR SC.CDP_CONTACT_ID = @CDPID AND NH.ORD_PROCESS_CONTRL <> 6 AND ND.ACTIVE_REV=1 AND @EndDate >= ND.START_DATE AND @EndDate <= ND.END_DATE					 '
		if @RunInsertionDate = 'Y' and @LineCancelled = 'N' and @Rescrictions = 0
			SELECT @sql2 = @sql2 + ' AND NH.ORD_PROCESS_CONTRL <> 6 AND ND.ACTIVE_REV=1 AND ND.START_DATE >= @StartDate AND ND.START_DATE <= @EndDate OR ND.LINE_CANCELLED IS NULL AND NH.ORD_PROCESS_CONTRL <> 6 AND ND.ACTIVE_REV=1 AND ND.END_DATE >= @StartDate AND ND.END_DATE <= @EndDate OR ND.LINE_CANCELLED IS NULL AND NH.ORD_PROCESS_CONTRL <> 6 AND ND.ACTIVE_REV=1 AND @StartDate >= ND.START_DATE AND @StartDate <= ND.END_DATE OR ND.LINE_CANCELLED IS NULL AND NH.ORD_PROCESS_CONTRL <> 6 AND ND.ACTIVE_REV=1 AND @EndDate >= ND.START_DATE AND @EndDate <= ND.END_DATE					 '
		if @RunInsertionDate = 'Y' and @LineCancelled = 'Y' and @Rescrictions = 0
			SELECT @sql2 = @sql2 + ' AND NH.ORD_PROCESS_CONTRL <> 6 AND ND.ACTIVE_REV=1 AND ND.START_DATE >= @StartDate AND ND.START_DATE <= @EndDate OR NH.ORD_PROCESS_CONTRL <> 6 AND ND.ACTIVE_REV=1 AND ND.END_DATE >= @StartDate AND ND.END_DATE <= @EndDate OR NH.ORD_PROCESS_CONTRL <> 6 AND ND.ACTIVE_REV=1 AND @StartDate >= ND.START_DATE AND @StartDate <= ND.END_DATE OR NH.ORD_PROCESS_CONTRL <> 6 AND ND.ACTIVE_REV=1 AND @EndDate >= ND.START_DATE AND @EndDate <= ND.END_DATE					 '

		IF @debug = 1                                                      
		   PRINT @sql2    

		SELECT @paramlist2 = '@StartDate smalldatetime, @EndDate smalldatetime, @CDPID varchar(20)'

		EXEC sp_executesql @sql2, @paramlist2, @StartDate, @EndDate, @CDPID

-- Internet Media Data
If @InternetInc = 'Y'
	SELECT @sql3 = 
	'INSERT INTO #media_rows
	 SELECT ''I'' AS TYPE, ''A'' AS EST_ACT, IH.OFFICE_CODE, IH.ORDER_NBR, 
		IH.ORDER_DESC, IH.MEDIA_TYPE, IH.CL_CODE, 
		IH.DIV_CODE, IH.PRD_CODE, IH.CMP_IDENTIFIER, 
		IH.CMP_CODE, C.CMP_NAME, IH.VN_CODE, V.VN_NAME, IH.BUYER, IH.CLIENT_PO, 
		IH.MARKET_CODE, M.MARKET_DESC, IH.ORDER_ACCEPTED, ID.LINE_NBR, 
		ID.ACTIVE_REV,'''' AS FLIGHT_DATES, ID.START_DATE, ID.END_DATE, 
		'''' AS MEDIA_MONTH, '''' AS MEDIA_YEAR,
		ID.CLOSE_DATE, ID.MATL_CLOSE_DATE, ID.EXT_CLOSE_DATE, 
		ID.EXT_MATL_DATE, ID.CREATIVE_SIZE AS SIZE,
		0 AS PRINT_COLUMNS, 0 AS PRINT_INCHES, 0 AS PRINT_LINES, ID.AD_NUMBER, 
		ID.HEADLINE, ID.INTERNET_TYPE, '''' AS OUTDOOR_TYPE, '''' AS MATERIAL,
		'''' AS EDITION_ISSUE,'''' AS SECTION, '''' AS START_TIME, '''' AS END_TIME,'''' AS LENGTH, '''' AS TAG, '''' AS PROGRAMMING,
		'''' AS MATL_NOTES, '''' AS REMARKS, ID.JOB_NUMBER, 
		ID.JOB_COMPONENT_NBR, '''' AS PRODUCTION_SIZE, ID.EST_NBR, ID.EST_LINE_NBR, 
		ID.EST_REV_NBR, ID.LINE_TOTAL,ID.COST_RATE AS COST_PER,  
		ID.GUARANTEED_IMPRESS AS IMPRESSIONS, ID.LINE_CANCELLED, CL.CL_NAME, D.DIV_NAME, P.PRD_DESCRIPTION, ID.REV_NBR, ID.MAT_COMP, ID.SIZE AS SIZE_DESC
	FROM INTERNET_HEADER IH INNER JOIN INTERNET_DETAIL ID ON IH.ORDER_NBR = ID.ORDER_NBR
						 INNER JOIN VENDOR V ON IH.VN_CODE = V.VN_CODE
						 INNER JOIN CLIENT AS CL ON IH.CL_CODE = CL.CL_CODE INNER JOIN
						 DIVISION AS D ON CL.CL_CODE = D.CL_CODE INNER JOIN
						 PRODUCT AS P ON IH.CL_CODE = P.CL_CODE AND IH.DIV_CODE = P.DIV_CODE AND 
						 IH.PRD_CODE = P.PRD_CODE AND D.CL_CODE = P.CL_CODE AND 
						 D.DIV_CODE = P.DIV_CODE
						 LEFT OUTER JOIN CAMPAIGN C ON IH.CMP_IDENTIFIER = C.CMP_IDENTIFIER
						 LEFT OUTER JOIN MARKET M ON IH.MARKET_CODE = M.MARKET_CODE'
		if @Rescrictions > 0 
			SELECT @sql3 = @sql3 + ' LEFT OUTER JOIN CP_SEC_CLIENT SC ON IH.CL_CODE = SC.CL_CODE AND 
						          IH.DIV_CODE = SC.DIV_CODE AND IH.PRD_CODE = SC.PRD_CODE 
								  WHERE SC.CDP_CONTACT_ID = @CDPID'
		else
			SELECT @sql3 = @sql3 + ' WHERE 1=1' 

		if @AcceptedOrdersOnly = 'Y'
			SELECT @sql3 = @sql3 + ' AND IH.ORDER_ACCEPTED = 1'
		if @LineCancelled = 'N'
			SELECT @sql3 = @sql3 + ' AND ID.LINE_CANCELLED IS NULL'
		if @MatDueDate = 'Y'
			 SELECT @sql3 = @sql3 + ' AND IH.ORD_PROCESS_CONTRL <> 6 AND ID.ACTIVE_REV=1 AND MATL_CLOSE_DATE >= @StartDate AND MATL_CLOSE_DATE <= @EndDate'
		if @ExtMatDueDate = 'Y' 
			SELECT @sql3 = @sql3 + ' AND IH.ORD_PROCESS_CONTRL <> 6 AND ID.ACTIVE_REV=1 AND EXT_MATL_DATE >= @StartDate AND EXT_MATL_DATE <= @EndDate'
		if @CloseDate = 'Y'
			SELECT @sql3 = @sql3 + ' AND IH.ORD_PROCESS_CONTRL <> 6 AND ID.ACTIVE_REV=1 AND CLOSE_DATE >= @StartDate AND CLOSE_DATE <= @EndDate'
		if @ExtCloseDate = 'Y'
			SELECT @sql3 = @sql3 + ' AND IH.ORD_PROCESS_CONTRL <> 6 AND ID.ACTIVE_REV=1 AND EXT_CLOSE_DATE >= @StartDate AND EXT_CLOSE_DATE <= @EndDate'
		if @RunInsertionDate = 'Y' and @LineCancelled = 'N' and @Rescrictions > 0
			SELECT @sql3 = @sql3 + ' AND IH.ORD_PROCESS_CONTRL <> 6 AND ID.ACTIVE_REV=1 AND ID.START_DATE >= @StartDate AND ID.START_DATE <= @EndDate OR SC.CDP_CONTACT_ID = @CDPID AND ID.LINE_CANCELLED IS NULL AND IH.ORD_PROCESS_CONTRL <> 6 AND ID.ACTIVE_REV=1 AND ID.END_DATE >= @StartDate AND ID.END_DATE <= @EndDate OR SC.CDP_CONTACT_ID = @CDPID AND ID.LINE_CANCELLED IS NULL AND IH.ORD_PROCESS_CONTRL <> 6 AND ID.ACTIVE_REV=1 AND @StartDate >= ID.START_DATE AND @StartDate <= ID.END_DATE OR SC.CDP_CONTACT_ID = @CDPID AND ID.LINE_CANCELLED IS NULL AND IH.ORD_PROCESS_CONTRL <> 6 AND ID.ACTIVE_REV=1 AND @EndDate >= ID.START_DATE AND @EndDate <= ID.END_DATE					 '
		if @RunInsertionDate = 'Y' and @LineCancelled = 'Y' and @Rescrictions > 0
			SELECT @sql3 = @sql3 + ' AND IH.ORD_PROCESS_CONTRL <> 6 AND ID.ACTIVE_REV=1 AND ID.START_DATE >= @StartDate AND ID.START_DATE <= @EndDate OR SC.CDP_CONTACT_ID = @CDPID AND IH.ORD_PROCESS_CONTRL <> 6 AND ID.ACTIVE_REV=1 AND ID.END_DATE >= @StartDate AND ID.END_DATE <= @EndDate OR SC.CDP_CONTACT_ID = @CDPID AND IH.ORD_PROCESS_CONTRL <> 6 AND ID.ACTIVE_REV=1 AND @StartDate >= ID.START_DATE AND @StartDate <= ID.END_DATE OR SC.CDP_CONTACT_ID = @CDPID AND IH.ORD_PROCESS_CONTRL <> 6 AND ID.ACTIVE_REV=1 AND @EndDate >= ID.START_DATE AND @EndDate <= ID.END_DATE					 '
		if @RunInsertionDate = 'Y' and @LineCancelled = 'N' and @Rescrictions = 0
			SELECT @sql3 = @sql3 + ' AND IH.ORD_PROCESS_CONTRL <> 6 AND ID.ACTIVE_REV=1 AND ID.START_DATE >= @StartDate AND ID.START_DATE <= @EndDate OR ID.LINE_CANCELLED IS NULL AND IH.ORD_PROCESS_CONTRL <> 6 AND ID.ACTIVE_REV=1 AND ID.END_DATE >= @StartDate AND ID.END_DATE <= @EndDate OR ID.LINE_CANCELLED IS NULL AND IH.ORD_PROCESS_CONTRL <> 6 AND ID.ACTIVE_REV=1 AND @StartDate >= ID.START_DATE AND @StartDate <= ID.END_DATE OR ID.LINE_CANCELLED IS NULL AND IH.ORD_PROCESS_CONTRL <> 6 AND ID.ACTIVE_REV=1 AND @EndDate >= ID.START_DATE AND @EndDate <= ID.END_DATE					 '
		if @RunInsertionDate = 'Y' and @LineCancelled = 'Y' and @Rescrictions = 0
			SELECT @sql3 = @sql3 + ' AND IH.ORD_PROCESS_CONTRL <> 6 AND ID.ACTIVE_REV=1 AND ID.START_DATE >= @StartDate AND ID.START_DATE <= @EndDate OR IH.ORD_PROCESS_CONTRL <> 6 AND ID.ACTIVE_REV=1 AND ID.END_DATE >= @StartDate AND ID.END_DATE <= @EndDate OR IH.ORD_PROCESS_CONTRL <> 6 AND ID.ACTIVE_REV=1 AND @StartDate >= ID.START_DATE AND @StartDate <= ID.END_DATE OR IH.ORD_PROCESS_CONTRL <> 6 AND ID.ACTIVE_REV=1 AND @EndDate >= ID.START_DATE AND @EndDate <= ID.END_DATE					 '	
									
		IF @debug = 1                                                      
		   PRINT @sql3     

		SELECT @paramlist3 = '@StartDate smalldatetime, @EndDate smalldatetime, @CDPID varchar(20)'

		EXEC sp_executesql @sql3, @paramlist3, @StartDate, @EndDate, @CDPID

-- Out of Home Media Data
If @OutOfHomeInc = 'Y'
	SELECT @sql4 = 
	'INSERT INTO #media_rows
	 SELECT ''O'' AS TYPE, ''A'' AS EST_ACT, OH.OFFICE_CODE, OH.ORDER_NBR, 
		OH.ORDER_DESC, OH.MEDIA_TYPE, OH.CL_CODE, OH.DIV_CODE, 
		OH.PRD_CODE, OH.CMP_IDENTIFIER, OH.CMP_CODE, C.CMP_NAME, OH.VN_CODE, V.VN_NAME, OH.BUYER,
		OH.CLIENT_PO, OH.MARKET_CODE, M.MARKET_DESC, OH.ORDER_ACCEPTED, 
		OD.LINE_NBR, OD.ACTIVE_REV,'''' AS FLIGHT_DATES, OD.POST_DATE AS START_DATE,
		OD.END_DATE,'''' AS MEDIA_MONTH, '''' AS MEDIA_YEAR,
		OD.CLOSE_DATE, OD.MATL_CLOSE_DATE, OD.EXT_CLOSE_DATE, 
		OD.EXT_MATL_DATE, OD.SIZE,
		0 AS PRINT_COLUMNS, 0 AS PRINT_INCHES, 0 AS PRINT_LINES,	OD.AD_NUMBER,
		OD.HEADLINE, '''' AS INTERNET_TYPE, OD.OUTDOOR_TYPE,'''' AS MATERIAL,
		'''' AS EDITION_ISSUE,'''' AS SECTION, '''' AS START_TIME, '''' AS END_TIME,'''' AS LENGTH, '''' AS TAG, '''' AS PROGRAMMING,
		'''' AS MATL_NOTES, '''' AS REMARKS, OD.JOB_NUMBER, 
		OD.JOB_COMPONENT_NBR,'''' AS PRODUCTION_SIZE, OD.EST_NBR, OD.EST_LINE_NBR, 
		OD.EST_REV_NBR, OD.LINE_TOTAL, 0 AS COST_PER, 0 AS IMPRESSIONS, OD.LINE_CANCELLED, CL.CL_NAME, D.DIV_NAME, P.PRD_DESCRIPTION, OD.REV_NBR, OD.MAT_COMP, AD_SIZE.SIZE_DESC
	FROM OUTDOOR_HEADER OH INNER JOIN OUTDOOR_DETAIL OD ON OH.ORDER_NBR = OD.ORDER_NBR
						INNER JOIN VENDOR V ON OH.VN_CODE = V.VN_CODE
						INNER JOIN CLIENT AS CL ON OH.CL_CODE = CL.CL_CODE INNER JOIN
						DIVISION AS D ON CL.CL_CODE = D.CL_CODE INNER JOIN
					    PRODUCT AS P ON OH.CL_CODE = P.CL_CODE AND OH.DIV_CODE = P.DIV_CODE AND 
						OH.PRD_CODE = P.PRD_CODE AND D.CL_CODE = P.CL_CODE AND 
						D.DIV_CODE = P.DIV_CODE
						LEFT OUTER JOIN CAMPAIGN C ON OH.CMP_IDENTIFIER = C.CMP_IDENTIFIER
						LEFT OUTER JOIN MARKET M ON OH.MARKET_CODE = M.MARKET_CODE 
						LEFT OUTER JOIN AD_SIZE ON OD.SIZE = AD_SIZE.SIZE_CODE'
		if @Rescrictions > 0 
			SELECT @sql4 = @sql4 + ' LEFT OUTER JOIN CP_SEC_CLIENT SC ON OH.CL_CODE = SC.CL_CODE AND 
						          OH.DIV_CODE = SC.DIV_CODE AND OH.PRD_CODE = SC.PRD_CODE 
								  WHERE SC.CDP_CONTACT_ID = @CDPID'
		else
			SELECT @sql4 = @sql4 + ' WHERE 1=1'	 

		if @AcceptedOrdersOnly = 'Y'
			SELECT @sql4 = @sql4 + ' AND OH.ORDER_ACCEPTED = 1'
		if @LineCancelled = 'N'
			SELECT @sql4 = @sql4 + ' AND OD.LINE_CANCELLED IS NULL'
		if @MatDueDate = 'Y'
			 SELECT @sql4 = @sql4 + ' AND OH.ORD_PROCESS_CONTRL <> 6 AND OD.ACTIVE_REV=1 AND MATL_CLOSE_DATE >= @StartDate AND MATL_CLOSE_DATE <= @EndDate'
		if @ExtMatDueDate = 'Y' 
			SELECT @sql4 = @sql4 + ' AND OH.ORD_PROCESS_CONTRL <> 6 AND OD.ACTIVE_REV=1 AND EXT_MATL_DATE >= @StartDate AND EXT_MATL_DATE <= @EndDate'
		if @CloseDate = 'Y'
			SELECT @sql4 = @sql4 + ' AND OH.ORD_PROCESS_CONTRL <> 6 AND OD.ACTIVE_REV=1 AND CLOSE_DATE >= @StartDate AND CLOSE_DATE <= @EndDate'
		if @ExtCloseDate = 'Y'
			SELECT @sql4 = @sql4 + ' AND OH.ORD_PROCESS_CONTRL <> 6 AND OD.ACTIVE_REV=1 AND EXT_CLOSE_DATE >= @StartDate AND EXT_CLOSE_DATE <= @EndDate'
		if @RunInsertionDate = 'Y' and @LineCancelled = 'N' and @Rescrictions > 0
			SELECT @sql4 = @sql4 + ' AND OH.ORD_PROCESS_CONTRL <> 6 AND OD.ACTIVE_REV=1 AND OD.POST_DATE >= @StartDate AND OD.POST_DATE <= @EndDate OR SC.CDP_CONTACT_ID = @CDPID AND OD.LINE_CANCELLED IS NULL AND OH.ORD_PROCESS_CONTRL <> 6 AND OD.ACTIVE_REV=1 AND OD.END_DATE >= @StartDate AND OD.END_DATE <= @EndDate OR SC.CDP_CONTACT_ID = @CDPID AND OD.LINE_CANCELLED IS NULL AND OH.ORD_PROCESS_CONTRL <> 6 AND OD.ACTIVE_REV=1 AND @StartDate >= OD.POST_DATE AND @StartDate <= OD.END_DATE OR SC.CDP_CONTACT_ID = @CDPID AND OD.LINE_CANCELLED IS NULL AND OH.ORD_PROCESS_CONTRL <> 6 AND OD.ACTIVE_REV=1 AND @EndDate >= OD.POST_DATE AND @EndDate <= OD.END_DATE'		
		if @RunInsertionDate = 'Y' and @LineCancelled = 'Y' and @Rescrictions > 0
			SELECT @sql4 = @sql4 + ' AND OH.ORD_PROCESS_CONTRL <> 6 AND OD.ACTIVE_REV=1 AND OD.POST_DATE >= @StartDate AND OD.POST_DATE <= @EndDate OR SC.CDP_CONTACT_ID = @CDPID AND OH.ORD_PROCESS_CONTRL <> 6 AND OD.ACTIVE_REV=1 AND OD.END_DATE >= @StartDate AND OD.END_DATE <= @EndDate OR SC.CDP_CONTACT_ID = @CDPID AND OH.ORD_PROCESS_CONTRL <> 6 AND OD.ACTIVE_REV=1 AND @StartDate >= OD.POST_DATE AND @StartDate <= OD.END_DATE OR SC.CDP_CONTACT_ID = @CDPID AND OH.ORD_PROCESS_CONTRL <> 6 AND OD.ACTIVE_REV=1 AND @EndDate >= OD.POST_DATE AND @EndDate <= OD.END_DATE'
		if @RunInsertionDate = 'Y' and @LineCancelled = 'N' and @Rescrictions = 0
			SELECT @sql4 = @sql4 + ' AND OH.ORD_PROCESS_CONTRL <> 6 AND OD.ACTIVE_REV=1 AND OD.POST_DATE >= @StartDate AND OD.POST_DATE <= @EndDate OR OD.LINE_CANCELLED IS NULL AND OH.ORD_PROCESS_CONTRL <> 6 AND OD.ACTIVE_REV=1 AND OD.END_DATE >= @StartDate AND OD.END_DATE <= @EndDate OR OD.LINE_CANCELLED IS NULL AND OH.ORD_PROCESS_CONTRL <> 6 AND OD.ACTIVE_REV=1 AND @StartDate >= OD.POST_DATE AND @StartDate <= OD.END_DATE OR OD.LINE_CANCELLED IS NULL AND OH.ORD_PROCESS_CONTRL <> 6 AND OD.ACTIVE_REV=1 AND @EndDate >= OD.POST_DATE AND @EndDate <= OD.END_DATE'		
		if @RunInsertionDate = 'Y' and @LineCancelled = 'Y' and @Rescrictions = 0
			SELECT @sql4 = @sql4 + ' AND OH.ORD_PROCESS_CONTRL <> 6 AND OD.ACTIVE_REV=1 AND OD.POST_DATE >= @StartDate AND OD.POST_DATE <= @EndDate OR OH.ORD_PROCESS_CONTRL <> 6 AND OD.ACTIVE_REV=1 AND OD.END_DATE >= @StartDate AND OD.END_DATE <= @EndDate OR OH.ORD_PROCESS_CONTRL <> 6 AND OD.ACTIVE_REV=1 AND @StartDate >= OD.POST_DATE AND @StartDate <= OD.END_DATE OR OH.ORD_PROCESS_CONTRL <> 6 AND OD.ACTIVE_REV=1 AND @EndDate >= OD.POST_DATE AND @EndDate <= OD.END_DATE'

		IF @debug = 1                                                      
		   PRINT @sql4     

		SELECT @paramlist4 = '@StartDate smalldatetime, @EndDate smalldatetime, @CDPID varchar(20)'

		EXEC sp_executesql @sql4, @paramlist4, @StartDate, @EndDate, @CDPID


If @RadioInc = 'Y'
SELECT @sqlradio = 'INSERT INTO #media_rows
					SELECT ''R'', ''A'' AS EST_ACT, RH.OFFICE_CODE,
							 RH.ORDER_NBR, RH.ORDER_DESC, RH.MEDIA_TYPE, RH.CL_CODE, 
							 RH.DIV_CODE, RH.PRD_CODE, RH.CMP_IDENTIFIER, '''' AS CMP_CODE, CAMPAIGN.CMP_NAME,
							 RH.VN_CODE, VENDOR.VN_NAME, RH.BUYER, RH.CLIENT_PO, RH.MARKET_CODE, MARKET.MARKET_DESC, '''' AS ORDER_ACCEPTED, 
							 RD.LINE_NBR, '''' AS ACTIVE_REV,
							 (CAST(RH.START_DATE AS varchar(30)) + '' - '' + CAST(RH.END_DATE AS varchar(30))) AS FLIGHT_DATES, RH.START_DATE, RH.END_DATE,
							 RD.MONTH_NBR AS MEDIA_MONTH, RD.YEAR_NBR AS MEDIA_YEAR, 
							 RD.CLOSE_DATE, RD.MATL_CLOSE_DATE,
							 RD.EXT_CLOSE_DATE, RD.EXT_MATL_DATE,
							 '''' AS SIZE, 0 AS PRINT_COLUMNS, 0 AS PRINT_INCHES, 0 AS PRINT_LINES, '''' AS AD_NUMBER, '''' AS HEADLINE,
							 '''' AS INTERNET_TYPE, '''' AS OUTDOOR_TYPE, '''' AS MATERIAL, '''' AS EDITION_ISSUE, '''' AS SECTION, 
							 RD.START_TIME, RD.END_TIME,
							 RD.LENGTH, RD.TAG,
							 RD.PROGRAMMING, '''' AS MATL_NOTES, RD.REMARKS,
							 RD.JOB_NUMBER, RD.JOB_COMPONENT_NBR,
							 '''' AS PRODUCTION_SIZE, 0  AS EST_NBR, 0 AS EST_LINE_NBR, 0 AS EST_REV_NBR, 0 AS LINE_TOTAL, 0 AS COST_PER,
							 0 AS IMPRESSIONS, RD.LINE_CANCELLED, CLIENT.CL_NAME, DIVISION.DIV_NAME, PRODUCT.PRD_DESCRIPTION, RD.REV_NBR, RD.MAT_COMP, '''' AS SIZE_DESC
					FROM  RADIO_HDR RH INNER JOIN
						  RADIO_DETAIL RD ON RH.ORDER_NBR = RD.ORDER_NBR INNER JOIN
							PRODUCT ON RH.CL_CODE = PRODUCT.CL_CODE AND RH.DIV_CODE = PRODUCT.DIV_CODE AND 
							RH.PRD_CODE = PRODUCT.PRD_CODE INNER JOIN
							DIVISION ON PRODUCT.CL_CODE = DIVISION.CL_CODE AND PRODUCT.DIV_CODE = DIVISION.DIV_CODE INNER JOIN
							CLIENT ON DIVISION.CL_CODE = CLIENT.CL_CODE INNER JOIN
							VENDOR ON RH.VN_CODE = VENDOR.VN_CODE LEFT OUTER JOIN
							MARKET ON RH.MARKET_CODE = MARKET.MARKET_CODE LEFT OUTER JOIN
							CAMPAIGN ON RH.CMP_IDENTIFIER = CAMPAIGN.CMP_IDENTIFIER'
			if @Rescrictions > 0 
				Begin
					SELECT @sqlradio = @sqlradio + ' INNER JOIN CP_SEC_CLIENT SC ON RH.CL_CODE = SC.CL_CODE AND RH.DIV_CODE = SC.DIV_CODE AND RH.PRD_CODE = SC.PRD_CODE
										  WHERE SC.CDP_CONTACT_ID = @CDPID AND RH.ORD_PROCESS_CONTRL <> 6'
				End
			else
				Begin
					SELECT @sqlradio = @sqlradio + ' WHERE RH.ORD_PROCESS_CONTRL <> 6'	 
				End
			if @MatDueDate = 'Y'
				Begin
					SELECT @sqlradio = @sqlradio + ' AND RD.MATL_CLOSE_DATE >= @StartDate AND RD.MATL_CLOSE_DATE <= @EndDate'	 
				End
			if @ExtMatDueDate = 'Y'
				Begin
					SELECT @sqlradio = @sqlradio + ' AND RD.EXT_MATL_DATE >= @StartDate AND RD.EXT_MATL_DATE <= @EndDate <= @EndDate'	 
				End
			if @CloseDate = 'Y'
				Begin
					SELECT @sqlradio = @sqlradio + ' AND RD.CLOSE_DATE >= @StartDate AND RD.CLOSE_DATE <= @EndDate <= @EndDate'	 
				End
			if @ExtCloseDate = 'Y'
				Begin
					SELECT @sqlradio = @sqlradio + ' AND RD.EXT_CLOSE_DATE >= @StartDate AND RD.EXT_CLOSE_DATE <= @EndDate <= @EndDate'	 
				End
			if @RunInsertionDate = 'Y'
				Begin
					SELECT @sqlradio = @sqlradio + ' AND ((RD.START_DATE >= @StartDate AND RD.START_DATE <= @EndDate) OR (RD.END_DATE >= @StartDate AND RD.END_DATE <= @EndDate) OR
											(@StartDate >= RD.START_DATE AND @StartDate <= RD.END_DATE) OR (@EndDate >= RD.START_DATE AND @EndDate <= RD.END_DATE))'	 
				End
			if @LineCancelled <> 'Y'
				Begin
					SELECT @sqlradio = @sqlradio + ' AND RD.LINE_CANCELLED IS NULL'	 
				End

			IF @debug = 1                                                      
				PRINT @sqlradio     

			SELECT @paramlist7 = '@StartDate smalldatetime, @EndDate smalldatetime, @CDPID varchar(20)'

			EXEC sp_executesql @sqlradio, @paramlist7, @StartDate, @EndDate, @CDPID

	--INSERT INTO @Radio_Header_Max_Rev			
	--	SELECT RADIO_HEADER.ORDER_NBR, Max(RADIO_HEADER.REV_NBR) AS REV_NBR
	--	FROM RADIO_HEADER
	--	GROUP BY RADIO_HEADER.ORDER_NBR

	--if @Rescrictions > 0 
	--	INSERT INTO @Radio_Header_Data
	--			SELECT 'R' AS TYPE, PRODUCT.OFFICE_CODE, RADIO_HEADER.ORDER_NBR, 
	--				RADIO_HEADER.REV_NBR, RADIO_HEADER.CL_CODE, RADIO_HEADER.DIV_CODE,
	--				RADIO_HEADER.PRD_CODE, RADIO_HEADER.ORDER_DESC, RADIO_HEADER.VN_CODE, VENDOR.VN_NAME, RADIO_HEADER.BUYER,
	--				RADIO_HEADER.CMP_IDENTIFIER, CAMPAIGN.CMP_NAME, RADIO_HEADER.MEDIA_TYPE, RADIO_HEADER.MARKET_CODE, MARKET.MARKET_DESC,  
	--				RADIO_HEADER.FLIGHT_FROM, RADIO_HEADER.FLIGHT_TO, RADIO_HEADER.CLIENT_PO, CLIENT.CL_NAME, DIVISION.DIV_NAME, PRODUCT.PRD_DESCRIPTION
	--			FROM (RADIO_HEADER INNER JOIN @Radio_Header_Max_Rev RHMR ON (RADIO_HEADER.REV_NBR = RHMR.REV_NBR) 
	--					AND (RADIO_HEADER.ORDER_NBR = RHMR.ORDER_NBR)) 
	--					INNER JOIN PRODUCT ON (RADIO_HEADER.PRD_CODE = PRODUCT.PRD_CODE) AND (RADIO_HEADER.DIV_CODE = PRODUCT.DIV_CODE) 
	--					AND (RADIO_HEADER.CL_CODE = PRODUCT.CL_CODE)
	--					INNER JOIN VENDOR ON RADIO_HEADER.VN_CODE = VENDOR.VN_CODE 
	--					INNER JOIN CLIENT ON RADIO_HEADER.CL_CODE = CLIENT.CL_CODE INNER JOIN
	--						  DIVISION ON PRODUCT.CL_CODE = DIVISION.CL_CODE AND PRODUCT.DIV_CODE = DIVISION.DIV_CODE AND 
	--						  CLIENT.CL_CODE = DIVISION.CL_CODE LEFT OUTER JOIN CP_SEC_CLIENT SC ON RADIO_HEADER.CL_CODE = SC.CL_CODE AND 
	--					          RADIO_HEADER.DIV_CODE = SC.DIV_CODE AND RADIO_HEADER.PRD_CODE = SC.PRD_CODE 						  
	--					LEFT OUTER JOIN CAMPAIGN ON RADIO_HEADER.CMP_IDENTIFIER = CAMPAIGN.CMP_IDENTIFIER
	--					LEFT OUTER JOIN MARKET ON RADIO_HEADER.MARKET_CODE = MARKET.MARKET_CODE	
	--			WHERE SC.CDP_CONTACT_ID = @CDPID AND RADIO_HEADER.ORD_PROCESS_CONTRL <> 6
	--else
	--	INSERT INTO @Radio_Header_Data
	--			SELECT 'R' AS TYPE, PRODUCT.OFFICE_CODE, RADIO_HEADER.ORDER_NBR, 
	--				RADIO_HEADER.REV_NBR, RADIO_HEADER.CL_CODE, RADIO_HEADER.DIV_CODE,
	--				RADIO_HEADER.PRD_CODE, RADIO_HEADER.ORDER_DESC, RADIO_HEADER.VN_CODE, VENDOR.VN_NAME, RADIO_HEADER.BUYER,
	--				RADIO_HEADER.CMP_IDENTIFIER, CAMPAIGN.CMP_NAME, RADIO_HEADER.MEDIA_TYPE, RADIO_HEADER.MARKET_CODE, MARKET.MARKET_DESC,  
	--				RADIO_HEADER.FLIGHT_FROM, RADIO_HEADER.FLIGHT_TO, RADIO_HEADER.CLIENT_PO, CLIENT.CL_NAME, DIVISION.DIV_NAME, PRODUCT.PRD_DESCRIPTION
	--			FROM (RADIO_HEADER INNER JOIN @Radio_Header_Max_Rev RHMR ON (RADIO_HEADER.REV_NBR = RHMR.REV_NBR) 
	--					AND (RADIO_HEADER.ORDER_NBR = RHMR.ORDER_NBR)) 
	--					INNER JOIN PRODUCT ON (RADIO_HEADER.PRD_CODE = PRODUCT.PRD_CODE) AND (RADIO_HEADER.DIV_CODE = PRODUCT.DIV_CODE) 
	--					AND (RADIO_HEADER.CL_CODE = PRODUCT.CL_CODE)
	--					INNER JOIN VENDOR ON RADIO_HEADER.VN_CODE = VENDOR.VN_CODE 
	--					INNER JOIN CLIENT ON RADIO_HEADER.CL_CODE = CLIENT.CL_CODE INNER JOIN
	--						  DIVISION ON PRODUCT.CL_CODE = DIVISION.CL_CODE AND PRODUCT.DIV_CODE = DIVISION.DIV_CODE AND 
	--						  CLIENT.CL_CODE = DIVISION.CL_CODE
	--					LEFT OUTER JOIN CAMPAIGN ON RADIO_HEADER.CMP_IDENTIFIER = CAMPAIGN.CMP_IDENTIFIER
	--					LEFT OUTER JOIN MARKET ON RADIO_HEADER.MARKET_CODE = MARKET.MARKET_CODE
	--			WHERE RADIO_HEADER.ORD_PROCESS_CONTRL <> 6
	
	--INSERT INTO @Radio_Detail_Max_Rev
	--		SELECT RADIO_DETAIL1.ORDER_NBR, RADIO_DETAIL1.LINE_NBR, Max(RADIO_DETAIL1.REV_NBR) AS REV_NBR,
	--			RADIO_DETAIL1.BRDCAST_YEAR
	--		FROM RADIO_DETAIL1
	--		WHERE RADIO_DETAIL1.BRDCAST_YEAR = @MediaYear
	--		GROUP BY RADIO_DETAIL1.ORDER_NBR, RADIO_DETAIL1.LINE_NBR, RADIO_DETAIL1.BRDCAST_YEAR
	
	--INSERT INTO @Radio_Detail_Max_Rev_Seq
	--	SELECT RADIO_DETAIL1.ORDER_NBR, RADIO_DETAIL1.LINE_NBR, RADIO_DETAIL1.REV_NBR, 
	--		Max(RADIO_DETAIL1.SEQ_NBR) AS SEQ_NBR, RADIO_DETAIL1.BRDCAST_YEAR
	--	FROM @Radio_Detail_Max_Rev RDMR INNER JOIN RADIO_DETAIL1 ON (RDMR.ORDER_NBR = RADIO_DETAIL1.ORDER_NBR) 
	--		 AND (RDMR.LINE_NBR = RADIO_DETAIL1.LINE_NBR) AND (RDMR.REV_NBR = RADIO_DETAIL1.REV_NBR) AND (RDMR.BRDCAST_YEAR = RADIO_DETAIL1.BRDCAST_YEAR)
	--	GROUP BY RADIO_DETAIL1.ORDER_NBR, RADIO_DETAIL1.LINE_NBR, RADIO_DETAIL1.REV_NBR, RADIO_DETAIL1.BRDCAST_YEAR

	--if @LineCancelled = 'Y' 
	--	INSERT INTO @Radio_Detail_Data_No_Amounts
	--		SELECT RADIO_DETAIL1.ORDER_NBR, RADIO_DETAIL1.LINE_NBR, RADIO_DETAIL1.BRDCAST_YEAR, 
	--			RADIO_DETAIL1.CLOSE_DATE, RADIO_DETAIL1.EXT_CLOSE_DATE, RADIO_DETAIL1.MATL_CLOSE_DATE, 
	--			RADIO_DETAIL1.EXT_MATL_DATE, RADIO_DETAIL1.JOB_NUMBER, RADIO_DETAIL1.JOB_COMPONENT_NBR, 
	--			RADIO_DETAIL1.START_TIME, RADIO_DETAIL1.END_TIME, RADIO_DETAIL1.LENGTH, RADIO_DETAIL1.PROGRAMMING,
	--			RADIO_DETAIL1.TAG, RADIO_DETAIL1.REMARKS, RADIO_DETAIL2.MATL_NOTES, RADIO_DETAIL1.LINE_CANCELLED, RADIO_DETAIL1.MAT_COMP
	--		FROM (@Radio_Detail_Max_Rev_Seq RDMRS INNER JOIN RADIO_DETAIL2 ON (RDMRS.ORDER_NBR = RADIO_DETAIL2.ORDER_NBR) 
	--			AND (RDMRS.LINE_NBR = RADIO_DETAIL2.LINE_NBR) 
	--			AND (RDMRS.REV_NBR = RADIO_DETAIL2.REV_NBR) 
	--			AND (RDMRS.SEQ_NBR = RADIO_DETAIL2.SEQ_NBR) 
	--			AND (RDMRS.BRDCAST_YEAR = RADIO_DETAIL2.BRDCAST_YEAR)) 
	--			INNER JOIN RADIO_DETAIL1 ON (RDMRS.ORDER_NBR = RADIO_DETAIL1.ORDER_NBR) 
	--			AND (RDMRS.LINE_NBR = RADIO_DETAIL1.LINE_NBR) 
	--			AND (RDMRS.REV_NBR = RADIO_DETAIL1.REV_NBR) 
	--			AND (RDMRS.SEQ_NBR = RADIO_DETAIL1.SEQ_NBR) 
	--			AND (RDMRS.BRDCAST_YEAR = RADIO_DETAIL1.BRDCAST_YEAR)
	--Else
	--	INSERT INTO @Radio_Detail_Data_No_Amounts
	--		SELECT RADIO_DETAIL1.ORDER_NBR, RADIO_DETAIL1.LINE_NBR, RADIO_DETAIL1.BRDCAST_YEAR, 
	--			RADIO_DETAIL1.CLOSE_DATE, RADIO_DETAIL1.EXT_CLOSE_DATE, RADIO_DETAIL1.MATL_CLOSE_DATE, 
	--			RADIO_DETAIL1.EXT_MATL_DATE, RADIO_DETAIL1.JOB_NUMBER, RADIO_DETAIL1.JOB_COMPONENT_NBR, 
	--			RADIO_DETAIL1.START_TIME, RADIO_DETAIL1.END_TIME, RADIO_DETAIL1.LENGTH, RADIO_DETAIL1.PROGRAMMING,
	--			RADIO_DETAIL1.TAG, RADIO_DETAIL1.REMARKS, RADIO_DETAIL2.MATL_NOTES, RADIO_DETAIL1.LINE_CANCELLED, RADIO_DETAIL1.MAT_COMP
	--		FROM (@Radio_Detail_Max_Rev_Seq RDMRS INNER JOIN RADIO_DETAIL2 ON (RDMRS.ORDER_NBR = RADIO_DETAIL2.ORDER_NBR) 
	--			AND (RDMRS.LINE_NBR = RADIO_DETAIL2.LINE_NBR) 
	--			AND (RDMRS.REV_NBR = RADIO_DETAIL2.REV_NBR) 
	--			AND (RDMRS.SEQ_NBR = RADIO_DETAIL2.SEQ_NBR) 
	--			AND (RDMRS.BRDCAST_YEAR = RADIO_DETAIL2.BRDCAST_YEAR)) 
	--			INNER JOIN RADIO_DETAIL1 ON (RDMRS.ORDER_NBR = RADIO_DETAIL1.ORDER_NBR) 
	--			AND (RDMRS.LINE_NBR = RADIO_DETAIL1.LINE_NBR) 
	--			AND (RDMRS.REV_NBR = RADIO_DETAIL1.REV_NBR) 
	--			AND (RDMRS.SEQ_NBR = RADIO_DETAIL1.SEQ_NBR) 
	--			AND (RDMRS.BRDCAST_YEAR = RADIO_DETAIL1.BRDCAST_YEAR)
	--		WHERE RADIO_DETAIL1.LINE_CANCELLED IS NULL

	
	--	if @MatDueDate = 'Y'
	--		INSERT INTO #media_rows
	--		SELECT RHD.TYPE, 'A' AS EST_ACT, RHD.OFFICE_CODE, 
	--			RDDNA.ORDER_NBR, RHD.ORDER_DESC, RHD.MEDIA_TYPE, RHD.CL_CODE, 
	--			RHD.DIV_CODE, RHD.PRD_CODE, RHD.CMP_IDENTIFIER, '' AS CMP_CODE, RHD.CMP_NAME AS CMP_NAME,
	--			RHD.VN_CODE, RHD.VN_NAME, RHD.BUYER, RHD.CLIENT_PO, RHD.MARKET_CODE, RHD.MARKET_DESC, '' AS ORDER_ACCEPTED,
	--			RDDNA.LINE_NBR, '' AS ACTIVE_REV,  
	--			(CAST(RHD.FLIGHT_FROM AS varchar(30)) + ' - ' + CAST(RHD.FLIGHT_TO AS varchar(30))) AS FLIGHT_DATES, RHD.FLIGHT_FROM AS START_DATE, RHD.FLIGHT_TO AS END_DATE,
	--			'' AS MEDIA_MONTH, RDDNA.BRDCAST_YEAR AS MEDIA_YEAR,
	--			RDDNA.CLOSE_DATE, RDDNA.MATL_CLOSE_DATE, 
	--			RDDNA.EXT_CLOSE_DATE, RDDNA.EXT_MATL_DATE, 
	--			'' AS SIZE, 0 AS PRINT_COLUMNS, 0 AS PRINT_INCHES, 0 AS PRINT_LINES, '' AS AD_NUMBER, '' AS HEADLINE,
	--			'' AS INTERNET_TYPE, '' AS OUTDOOR_TYPE, '' AS MATERIAL, '' AS EDITION_ISSUE, '' AS SECTION,
	--			RDDNA.START_TIME, RDDNA.END_TIME,
	--			RDDNA.LENGTH, RDDNA.TAG,
	--			RDDNA.PROGRAMMING, RDDNA.MATL_NOTES, RDDNA.REMARKS,
	--			RDDNA.JOB_NUMBER, RDDNA.JOB_COMPONENT_NBR, 
	--			'' AS PRODUCTION_SIZE, 0  AS EST_NBR, 0 AS EST_LINE_NBR, 0 AS EST_REV_NBR, 0 AS LINE_TOTAL, 0 AS COST_PER,
	--			0 AS IMPRESSIONS, RDDNA.LINE_CANCELLED, RHD.CL_NAME AS CL_NAME, RHD.DIV_NAME AS DIV_NAME, RHD.PRD_DESCRIPTION AS PRD_DESCRIPTION, RHD.REV_NBR AS REV_NBR, RDDNA.MAT_COMP AS MAT_COMP, '' AS SIZE_DESC		
	--		FROM @Radio_Header_Data RHD INNER JOIN @Radio_Detail_Data_No_Amounts RDDNA
	--			 ON RHD.ORDER_NBR = RDDNA.ORDER_NBR
	--		WHERE MATL_CLOSE_DATE >= @StartDate AND MATL_CLOSE_DATE <= @EndDate			
	--	if @ExtMatDueDate = 'Y' 
	--		INSERT INTO #media_rows
	--		SELECT RHD.TYPE, 'A' AS EST_ACT, RHD.OFFICE_CODE, 
	--			RDDNA.ORDER_NBR, RHD.ORDER_DESC, RHD.MEDIA_TYPE, RHD.CL_CODE, 
	--			RHD.DIV_CODE, RHD.PRD_CODE, RHD.CMP_IDENTIFIER, '' AS CMP_CODE, RHD.CMP_NAME AS CMP_NAME,
	--			RHD.VN_CODE, RHD.VN_NAME, RHD.BUYER, RHD.CLIENT_PO, RHD.MARKET_CODE, RHD.MARKET_DESC, '' AS ORDER_ACCEPTED,
	--			RDDNA.LINE_NBR, '' AS ACTIVE_REV,  
	--			(CAST(RHD.FLIGHT_FROM AS varchar(30)) + ' - ' + CAST(RHD.FLIGHT_TO AS varchar(30))) AS FLIGHT_DATES, RHD.FLIGHT_FROM AS START_DATE, RHD.FLIGHT_TO AS END_DATE,
	--			'' AS MEDIA_MONTH, RDDNA.BRDCAST_YEAR AS MEDIA_YEAR,
	--			RDDNA.CLOSE_DATE, RDDNA.MATL_CLOSE_DATE, 
	--			RDDNA.EXT_CLOSE_DATE, RDDNA.EXT_MATL_DATE, 
	--			'' AS SIZE, 0 AS PRINT_COLUMNS, 0 AS PRINT_INCHES, 0 AS PRINT_LINES, '' AS AD_NUMBER, '' AS HEADLINE,
	--			'' AS INTERNET_TYPE, '' AS OUTDOOR_TYPE, '' AS MATERIAL, '' AS EDITION_ISSUE, '' AS SECTION,
	--			RDDNA.START_TIME, RDDNA.END_TIME,
	--			RDDNA.LENGTH, RDDNA.TAG,
	--			RDDNA.PROGRAMMING, RDDNA.MATL_NOTES, RDDNA.REMARKS,
	--			RDDNA.JOB_NUMBER, RDDNA.JOB_COMPONENT_NBR, 
	--			'' AS PRODUCTION_SIZE, 0  AS EST_NBR, 0 AS EST_LINE_NBR, 0 AS EST_REV_NBR, 0 AS LINE_TOTAL, 0 AS COST_PER,
	--			0 AS IMPRESSIONS, RDDNA.LINE_CANCELLED, RHD.CL_NAME AS CL_NAME, RHD.DIV_NAME AS DIV_NAME, RHD.PRD_DESCRIPTION AS PRD_DESCRIPTION, RHD.REV_NBR AS REV_NBR, RDDNA.MAT_COMP AS MAT_COMP, '' AS SIZE_DESC				
	--		FROM @Radio_Header_Data RHD INNER JOIN @Radio_Detail_Data_No_Amounts RDDNA
	--			 ON RHD.ORDER_NBR = RDDNA.ORDER_NBR
	--		WHERE EXT_MATL_DATE >= @StartDate AND EXT_MATL_DATE <= @EndDate			
	--	if @CloseDate = 'Y'
	--		INSERT INTO #media_rows
	--		SELECT RHD.TYPE, 'A' AS EST_ACT, RHD.OFFICE_CODE, 
	--			RDDNA.ORDER_NBR, RHD.ORDER_DESC, RHD.MEDIA_TYPE, RHD.CL_CODE, 
	--			RHD.DIV_CODE, RHD.PRD_CODE, RHD.CMP_IDENTIFIER, '' AS CMP_CODE, RHD.CMP_NAME AS CMP_NAME,
	--			RHD.VN_CODE, RHD.VN_NAME, RHD.BUYER, RHD.CLIENT_PO, RHD.MARKET_CODE, RHD.MARKET_DESC, '' AS ORDER_ACCEPTED,
	--			RDDNA.LINE_NBR, '' AS ACTIVE_REV,  
	--			(CAST(RHD.FLIGHT_FROM AS varchar(30)) + ' - ' + CAST(RHD.FLIGHT_TO AS varchar(30))) AS FLIGHT_DATES, RHD.FLIGHT_FROM AS START_DATE, RHD.FLIGHT_TO AS END_DATE,
	--			'' AS MEDIA_MONTH, RDDNA.BRDCAST_YEAR AS MEDIA_YEAR,
	--			RDDNA.CLOSE_DATE, RDDNA.MATL_CLOSE_DATE, 
	--			RDDNA.EXT_CLOSE_DATE, RDDNA.EXT_MATL_DATE, 
	--			'' AS SIZE, 0 AS PRINT_COLUMNS, 0 AS PRINT_INCHES, 0 AS PRINT_LINES, '' AS AD_NUMBER, '' AS HEADLINE,
	--			'' AS INTERNET_TYPE, '' AS OUTDOOR_TYPE, '' AS MATERIAL, '' AS EDITION_ISSUE, '' AS SECTION,
	--			RDDNA.START_TIME, RDDNA.END_TIME,
	--			RDDNA.LENGTH, RDDNA.TAG,
	--			RDDNA.PROGRAMMING, RDDNA.MATL_NOTES, RDDNA.REMARKS,
	--			RDDNA.JOB_NUMBER, RDDNA.JOB_COMPONENT_NBR, 
	--			'' AS PRODUCTION_SIZE, 0  AS EST_NBR, 0 AS EST_LINE_NBR, 0 AS EST_REV_NBR, 0 AS LINE_TOTAL, 0 AS COST_PER,
	--			0 AS IMPRESSIONS, RDDNA.LINE_CANCELLED, RHD.CL_NAME AS CL_NAME, RHD.DIV_NAME AS DIV_NAME, RHD.PRD_DESCRIPTION AS PRD_DESCRIPTION, RHD.REV_NBR AS REV_NBR, RDDNA.MAT_COMP AS MAT_COMP, '' AS SIZE_DESC				
	--		FROM @Radio_Header_Data RHD INNER JOIN @Radio_Detail_Data_No_Amounts RDDNA
	--			 ON RHD.ORDER_NBR = RDDNA.ORDER_NBR
	--		WHERE CLOSE_DATE >= @StartDate AND CLOSE_DATE <= @EndDate			
	--	if @ExtCloseDate = 'Y'
	--		INSERT INTO #media_rows
	--		SELECT RHD.TYPE, 'A' AS EST_ACT, RHD.OFFICE_CODE, 
	--			RDDNA.ORDER_NBR, RHD.ORDER_DESC, RHD.MEDIA_TYPE, RHD.CL_CODE, 
	--			RHD.DIV_CODE, RHD.PRD_CODE, RHD.CMP_IDENTIFIER, '' AS CMP_CODE, RHD.CMP_NAME AS CMP_NAME,
	--			RHD.VN_CODE, RHD.VN_NAME, RHD.BUYER, RHD.CLIENT_PO, RHD.MARKET_CODE, RHD.MARKET_DESC, '' AS ORDER_ACCEPTED,
	--			RDDNA.LINE_NBR, '' AS ACTIVE_REV,  
	--			(CAST(RHD.FLIGHT_FROM AS varchar(30)) + ' - ' + CAST(RHD.FLIGHT_TO AS varchar(30))) AS FLIGHT_DATES, RHD.FLIGHT_FROM AS START_DATE, RHD.FLIGHT_TO AS END_DATE,
	--			'' AS MEDIA_MONTH, RDDNA.BRDCAST_YEAR AS MEDIA_YEAR,
	--			RDDNA.CLOSE_DATE, RDDNA.MATL_CLOSE_DATE, 
	--			RDDNA.EXT_CLOSE_DATE, RDDNA.EXT_MATL_DATE, 
	--			'' AS SIZE, 0 AS PRINT_COLUMNS, 0 AS PRINT_INCHES, 0 AS PRINT_LINES, '' AS AD_NUMBER, '' AS HEADLINE,
	--			'' AS INTERNET_TYPE, '' AS OUTDOOR_TYPE, '' AS MATERIAL, '' AS EDITION_ISSUE, '' AS SECTION,
	--			RDDNA.START_TIME, RDDNA.END_TIME,
	--			RDDNA.LENGTH, RDDNA.TAG,
	--			RDDNA.PROGRAMMING, RDDNA.MATL_NOTES, RDDNA.REMARKS,
	--			RDDNA.JOB_NUMBER, RDDNA.JOB_COMPONENT_NBR, 
	--			'' AS PRODUCTION_SIZE, 0  AS EST_NBR, 0 AS EST_LINE_NBR, 0 AS EST_REV_NBR, 0 AS LINE_TOTAL, 0 AS COST_PER,
	--			0 AS IMPRESSIONS, RDDNA.LINE_CANCELLED, RHD.CL_NAME AS CL_NAME, RHD.DIV_NAME AS DIV_NAME, RHD.PRD_DESCRIPTION AS PRD_DESCRIPTION, RHD.REV_NBR AS REV_NBR, RDDNA.MAT_COMP AS MAT_COMP, '' AS SIZE_DESC				
	--		FROM @Radio_Header_Data RHD INNER JOIN @Radio_Detail_Data_No_Amounts RDDNA
	--			 ON RHD.ORDER_NBR = RDDNA.ORDER_NBR
	--		WHERE EXT_CLOSE_DATE >= @StartDate AND EXT_CLOSE_DATE <= @EndDate			
	--	if @RunInsertionDate = 'Y'
	--		INSERT INTO #media_rows
	--		SELECT RHD.TYPE, 'A' AS EST_ACT, RHD.OFFICE_CODE, 
	--			RDDNA.ORDER_NBR, RHD.ORDER_DESC, RHD.MEDIA_TYPE, RHD.CL_CODE, 
	--			RHD.DIV_CODE, RHD.PRD_CODE, RHD.CMP_IDENTIFIER, '' AS CMP_CODE, RHD.CMP_NAME AS CMP_NAME,
	--			RHD.VN_CODE, RHD.VN_NAME, RHD.BUYER, RHD.CLIENT_PO, RHD.MARKET_CODE, RHD.MARKET_DESC, '' AS ORDER_ACCEPTED,
	--			RDDNA.LINE_NBR, '' AS ACTIVE_REV,  
	--			(CAST(RHD.FLIGHT_FROM AS varchar(30)) + ' - ' + CAST(RHD.FLIGHT_TO AS varchar(30))) AS FLIGHT_DATES, RHD.FLIGHT_FROM AS START_DATE, RHD.FLIGHT_TO AS END_DATE,
	--			'' AS MEDIA_MONTH, RDDNA.BRDCAST_YEAR AS MEDIA_YEAR,
	--			RDDNA.CLOSE_DATE, RDDNA.MATL_CLOSE_DATE, 
	--			RDDNA.EXT_CLOSE_DATE, RDDNA.EXT_MATL_DATE, 
	--			'' AS SIZE, 0 AS PRINT_COLUMNS, 0 AS PRINT_INCHES, 0 AS PRINT_LINES, '' AS AD_NUMBER, '' AS HEADLINE,
	--			'' AS INTERNET_TYPE, '' AS OUTDOOR_TYPE, '' AS MATERIAL, '' AS EDITION_ISSUE, '' AS SECTION,
	--			RDDNA.START_TIME, RDDNA.END_TIME,
	--			RDDNA.LENGTH, RDDNA.TAG,
	--			RDDNA.PROGRAMMING, RDDNA.MATL_NOTES, RDDNA.REMARKS,
	--			RDDNA.JOB_NUMBER, RDDNA.JOB_COMPONENT_NBR, 
	--			'' AS PRODUCTION_SIZE, 0  AS EST_NBR, 0 AS EST_LINE_NBR, 0 AS EST_REV_NBR, 0 AS LINE_TOTAL, 0 AS COST_PER,
	--			0 AS IMPRESSIONS, RDDNA.LINE_CANCELLED, RHD.CL_NAME AS CL_NAME, RHD.DIV_NAME AS DIV_NAME, RHD.PRD_DESCRIPTION AS PRD_DESCRIPTION, RHD.REV_NBR AS REV_NBR, RDDNA.MAT_COMP AS MAT_COMP, '' AS SIZE_DESC			
	--		FROM @Radio_Header_Data RHD INNER JOIN @Radio_Detail_Data_No_Amounts RDDNA
	--			 ON RHD.ORDER_NBR = RDDNA.ORDER_NBR
	--		WHERE FLIGHT_FROM >= @StartDate AND FLIGHT_FROM <= @EndDate OR FLIGHT_TO >= @StartDate AND FLIGHT_TO <= @EndDate OR
	--				@StartDate >= FLIGHT_FROM AND @StartDate <= FLIGHT_TO OR @EndDate >= FLIGHT_FROM AND @EndDate <= FLIGHT_TO					 

		
 --TV Media Data

If @TelevisionInc = 'Y'
SELECT @sqltv = 'INSERT INTO #media_rows
					SELECT ''T'', ''A'' AS EST_ACT, TH.OFFICE_CODE,
						TH.ORDER_NBR, TH.ORDER_DESC, TH.MEDIA_TYPE, TH.CL_CODE,
						TH.DIV_CODE, TH.PRD_CODE, TH.CMP_IDENTIFIER, '''' AS CMP_CODE, CAMPAIGN.CMP_NAME,
						TH.VN_CODE, VENDOR.VN_NAME, TH.BUYER, TH.CLIENT_PO, TH.MARKET_CODE, MARKET.MARKET_DESC, '''' AS ORDER_ACCEPTED,
						TD.LINE_NBR, '''' AS ACTIVE_REV,  
						(CAST(TH.START_DATE AS varchar(30)) + '' - '' + CAST(TH.END_DATE AS varchar(30))) AS FLIGHT_DATES, TH.START_DATE, TH.END_DATE,
						TD.MONTH_NBR AS MEDIA_MONTH, TD.YEAR_NBR AS MEDIA_YEAR,
						TD.CLOSE_DATE, TD.MATL_CLOSE_DATE, 
						TD.EXT_CLOSE_DATE, TD.EXT_MATL_DATE, 
						'''' AS SIZE, 0 AS PRINT_COLUMNS, 0 AS PRINT_INCHES, 0 AS PRINT_LINES, '''' AS AD_NUMBER, '''' AS HEADLINE,
						'''' AS INTERNET_TYPE, '''' AS OUTDOOR_TYPE, '''' AS MATERIAL, '''' AS EDITION_ISSUE, '''' AS SECTION,
						TD.START_TIME, TD.END_TIME,
						TD.LENGTH, TD.TAG,
						TD.PROGRAMMING, '''' AS MATL_NOTES, TD.REMARKS,
						TD.JOB_NUMBER, TD.JOB_COMPONENT_NBR, 
						'''' AS PRODUCTION_SIZE, 0 AS EST_NBR, 0 AS EST_LINE_NBR, 0 AS EST_REV_NBR, 0 AS LINE_TOTAL, 0 AS COST_PER, 
						0 AS IMPRESSIONS, TD.LINE_CANCELLED, CLIENT.CL_NAME, DIVISION.DIV_NAME, PRODUCT.PRD_DESCRIPTION, TD.REV_NBR, TD.MAT_COMP, '''' AS SIZE_DESC
					FROM  TV_HDR TH INNER JOIN
						  TV_DETAIL TD ON TH.ORDER_NBR = TD.ORDER_NBR INNER JOIN
							PRODUCT ON TH.CL_CODE = PRODUCT.CL_CODE AND TH.DIV_CODE = PRODUCT.DIV_CODE AND 
							TH.PRD_CODE = PRODUCT.PRD_CODE INNER JOIN
							DIVISION ON PRODUCT.CL_CODE = DIVISION.CL_CODE AND PRODUCT.DIV_CODE = DIVISION.DIV_CODE INNER JOIN
							CLIENT ON DIVISION.CL_CODE = CLIENT.CL_CODE INNER JOIN
							VENDOR ON TH.VN_CODE = VENDOR.VN_CODE LEFT OUTER JOIN
							MARKET ON TH.MARKET_CODE = MARKET.MARKET_CODE LEFT OUTER JOIN
							 CAMPAIGN ON TH.CMP_IDENTIFIER = CAMPAIGN.CMP_IDENTIFIER'
			if @Rescrictions > 0 
				Begin
					SELECT @sqltv = @sqltv + ' INNER JOIN CP_SEC_CLIENT SC ON TH.CL_CODE = SC.CL_CODE AND TH.DIV_CODE = SC.DIV_CODE AND TH.PRD_CODE = SC.PRD_CODE
										  WHERE SC.CDP_CONTACT_ID = @CDPID AND TH.ORD_PROCESS_CONTRL <> 6'
				End
			else
				Begin
					SELECT @sqltv = @sqltv + ' WHERE TH.ORD_PROCESS_CONTRL <> 6'	 
				End
			if @MatDueDate = 'Y'
				Begin
					SELECT @sqltv = @sqltv + ' AND TD.MATL_CLOSE_DATE >= @StartDate AND TD.MATL_CLOSE_DATE <= @EndDate'	 
				End
			if @ExtMatDueDate = 'Y'
				Begin
					SELECT @sqltv = @sqltv + ' AND TD.EXT_MATL_DATE >= @StartDate AND TD.EXT_MATL_DATE <= @EndDate <= @EndDate'	 
				End
			if @CloseDate = 'Y'
				Begin
					SELECT @sqltv = @sqltv + ' AND TD.CLOSE_DATE >= @StartDate AND TD.CLOSE_DATE <= @EndDate <= @EndDate'	 
				End
			if @ExtCloseDate = 'Y'
				Begin
					SELECT @sqltv = @sqltv + ' AND TD.EXT_CLOSE_DATE >= @StartDate AND TD.EXT_CLOSE_DATE <= @EndDate <= @EndDate'	 
				End
			if @RunInsertionDate = 'Y'
				Begin
					SELECT @sqltv = @sqltv + ' AND ((TD.START_DATE >= @StartDate AND TD.START_DATE <= @EndDate) OR (TD.END_DATE >= @StartDate AND TD.END_DATE <= @EndDate) OR
											(@StartDate >= TD.START_DATE AND @StartDate <= TD.END_DATE) OR (@EndDate >= TD.START_DATE AND @EndDate <= TD.END_DATE))'	 
				End
			if @LineCancelled <> 'Y'
				Begin
					SELECT @sqltv = @sqltv + ' AND TD.LINE_CANCELLED IS NULL'	 
				End

			IF @debug = 1                                                      
				PRINT @sqltv     

			SELECT @paramlist8 = '@StartDate smalldatetime, @EndDate smalldatetime, @CDPID varchar(20)'

			EXEC sp_executesql @sqltv, @paramlist8, @StartDate, @EndDate, @CDPID

	--INSERT INTO @TV_Header_Max_Rev			
	--	SELECT TV_HEADER.ORDER_NBR, Max(TV_HEADER.REV_NBR) AS REV_NBR
	--	FROM TV_HEADER
	--	GROUP BY TV_HEADER.ORDER_NBR
	
	--if @Rescrictions > 0 
	--	INSERT INTO @TV_Header_Data
	--		SELECT 'T' AS TYPE, PRODUCT.OFFICE_CODE, TV_HEADER.ORDER_NBR, 
	--			TV_HEADER.REV_NBR, TV_HEADER.CL_CODE, TV_HEADER.DIV_CODE,
	--			TV_HEADER.PRD_CODE, TV_HEADER.ORDER_DESC, TV_HEADER.VN_CODE, VENDOR.VN_NAME, TV_HEADER.BUYER,
	--			TV_HEADER.CMP_IDENTIFIER, CAMPAIGN.CMP_NAME, TV_HEADER.MEDIA_TYPE, TV_HEADER.MARKET_CODE, MARKET.MARKET_DESC, 
	--			TV_HEADER.FLIGHT_FROM, TV_HEADER.FLIGHT_TO, TV_HEADER.CLIENT_PO,  CLIENT.CL_NAME, DIVISION.DIV_NAME, PRODUCT.PRD_DESCRIPTION
	--		FROM (TV_HEADER INNER JOIN @TV_Header_Max_Rev THMR ON (TV_HEADER.REV_NBR = THMR.REV_NBR) 
	--				AND (TV_HEADER.ORDER_NBR = THMR.ORDER_NBR)) 
	--				INNER JOIN PRODUCT ON (TV_HEADER.PRD_CODE = PRODUCT.PRD_CODE) AND (TV_HEADER.DIV_CODE = PRODUCT.DIV_CODE) 
	--				AND (TV_HEADER.CL_CODE = PRODUCT.CL_CODE)
	--				INNER JOIN VENDOR ON TV_HEADER.VN_CODE = VENDOR.VN_CODE
	--				INNER JOIN CLIENT ON TV_HEADER.CL_CODE = CLIENT.CL_CODE INNER JOIN
	--						DIVISION ON PRODUCT.CL_CODE = DIVISION.CL_CODE AND PRODUCT.DIV_CODE = DIVISION.DIV_CODE AND 
	--						CLIENT.CL_CODE = DIVISION.CL_CODE LEFT OUTER JOIN CP_SEC_CLIENT SC ON TV_HEADER.CL_CODE = SC.CL_CODE AND 
	--					          TV_HEADER.DIV_CODE = SC.DIV_CODE AND TV_HEADER.PRD_CODE = SC.PRD_CODE 	
	--				LEFT OUTER JOIN CAMPAIGN ON TV_HEADER.CMP_IDENTIFIER = CAMPAIGN.CMP_IDENTIFIER
	--				LEFT OUTER JOIN MARKET ON TV_HEADER.MARKET_CODE = MARKET.MARKET_CODE
	--		WHERE SC.CDP_CONTACT_ID = @CDPID AND TV_HEADER.ORD_PROCESS_CONTRL <> 6
	--else
	--	INSERT INTO @TV_Header_Data
	--		SELECT 'T' AS TYPE, PRODUCT.OFFICE_CODE, TV_HEADER.ORDER_NBR, 
	--			TV_HEADER.REV_NBR, TV_HEADER.CL_CODE, TV_HEADER.DIV_CODE,
	--			TV_HEADER.PRD_CODE, TV_HEADER.ORDER_DESC, TV_HEADER.VN_CODE, VENDOR.VN_NAME, TV_HEADER.BUYER,
	--			TV_HEADER.CMP_IDENTIFIER, CAMPAIGN.CMP_NAME, TV_HEADER.MEDIA_TYPE, TV_HEADER.MARKET_CODE, MARKET.MARKET_DESC, 
	--			TV_HEADER.FLIGHT_FROM, TV_HEADER.FLIGHT_TO, TV_HEADER.CLIENT_PO,  CLIENT.CL_NAME, DIVISION.DIV_NAME, PRODUCT.PRD_DESCRIPTION
	--		FROM (TV_HEADER INNER JOIN @TV_Header_Max_Rev THMR ON (TV_HEADER.REV_NBR = THMR.REV_NBR) 
	--				AND (TV_HEADER.ORDER_NBR = THMR.ORDER_NBR)) 
	--				INNER JOIN PRODUCT ON (TV_HEADER.PRD_CODE = PRODUCT.PRD_CODE) AND (TV_HEADER.DIV_CODE = PRODUCT.DIV_CODE) 
	--				AND (TV_HEADER.CL_CODE = PRODUCT.CL_CODE)
	--				INNER JOIN VENDOR ON TV_HEADER.VN_CODE = VENDOR.VN_CODE
	--				INNER JOIN CLIENT ON TV_HEADER.CL_CODE = CLIENT.CL_CODE INNER JOIN
	--						DIVISION ON PRODUCT.CL_CODE = DIVISION.CL_CODE AND PRODUCT.DIV_CODE = DIVISION.DIV_CODE AND 
	--						CLIENT.CL_CODE = DIVISION.CL_CODE
	--				LEFT OUTER JOIN CAMPAIGN ON TV_HEADER.CMP_IDENTIFIER = CAMPAIGN.CMP_IDENTIFIER
	--				LEFT OUTER JOIN MARKET ON TV_HEADER.MARKET_CODE = MARKET.MARKET_CODE
	--		WHERE TV_HEADER.ORD_PROCESS_CONTRL <> 6	
	

	--INSERT INTO @TV_Detail_Max_Rev
	--	SELECT TV_DETAIL1.ORDER_NBR, TV_DETAIL1.LINE_NBR, Max(TV_DETAIL1.REV_NBR) AS REV_NBR,
	--		TV_DETAIL1.BRDCAST_YEAR
	--	FROM TV_DETAIL1
	--	WHERE TV_DETAIL1.BRDCAST_YEAR = @MediaYear
	--	GROUP BY TV_DETAIL1.ORDER_NBR, TV_DETAIL1.LINE_NBR, TV_DETAIL1.BRDCAST_YEAR
	
	--INSERT INTO @TV_Detail_Max_Rev_Seq
	--	SELECT TV_DETAIL1.ORDER_NBR, TV_DETAIL1.LINE_NBR, TV_DETAIL1.REV_NBR, 
	--		Max(TV_DETAIL1.SEQ_NBR) AS SEQ_NBR, TV_DETAIL1.BRDCAST_YEAR
	--	FROM @TV_Detail_Max_Rev TDMR INNER JOIN TV_DETAIL1 ON (TDMR.ORDER_NBR = TV_DETAIL1.ORDER_NBR) 
	--		 AND (TDMR.LINE_NBR = TV_DETAIL1.LINE_NBR) AND (TDMR.REV_NBR = TV_DETAIL1.REV_NBR) AND (TDMR.BRDCAST_YEAR = TV_DETAIL1.BRDCAST_YEAR)
	--	GROUP BY TV_DETAIL1.ORDER_NBR, TV_DETAIL1.LINE_NBR, TV_DETAIL1.REV_NBR, TV_DETAIL1.BRDCAST_YEAR
		
			
	--if @LineCancelled = 'Y'
	--	INSERT INTO @TV_Detail_Data_No_Amounts
	--		SELECT TV_DETAIL1.ORDER_NBR, TV_DETAIL1.LINE_NBR, TV_DETAIL1.BRDCAST_YEAR, 
	--			TV_DETAIL1.CLOSE_DATE, TV_DETAIL1.EXT_CLOSE_DATE, TV_DETAIL1.MATL_CLOSE_DATE, 
	--			TV_DETAIL1.EXT_MATL_DATE, TV_DETAIL1.JOB_NUMBER, TV_DETAIL1.JOB_COMPONENT_NBR, 
	--			TV_DETAIL1.START_TIME, TV_DETAIL1.END_TIME, TV_DETAIL1.LENGTH, TV_DETAIL1.PROGRAMMING,
	--			TV_DETAIL1.TAG, TV_DETAIL1.REMARKS, TV_DETAIL2.MATL_NOTES, TV_DETAIL1.LINE_CANCELLED, TV_DETAIL1.MAT_COMP
	--		FROM (@TV_Detail_Max_Rev_Seq TDMRS INNER JOIN TV_DETAIL2 ON (TDMRS.ORDER_NBR = TV_DETAIL2.ORDER_NBR) 
	--			AND (TDMRS.LINE_NBR = TV_DETAIL2.LINE_NBR) 
	--			AND (TDMRS.REV_NBR = TV_DETAIL2.REV_NBR) 
	--			AND (TDMRS.SEQ_NBR = TV_DETAIL2.SEQ_NBR) 
	--			AND (TDMRS.BRDCAST_YEAR = TV_DETAIL2.BRDCAST_YEAR)) 
	--			INNER JOIN TV_DETAIL1 ON (TDMRS.ORDER_NBR = TV_DETAIL1.ORDER_NBR) 
	--			AND (TDMRS.LINE_NBR = TV_DETAIL1.LINE_NBR) 
	--			AND (TDMRS.REV_NBR = TV_DETAIL1.REV_NBR) 
	--			AND (TDMRS.SEQ_NBR = TV_DETAIL1.SEQ_NBR) 
	--			AND (TDMRS.BRDCAST_YEAR = TV_DETAIL1.BRDCAST_YEAR)
	--Else
	--	INSERT INTO @TV_Detail_Data_No_Amounts
	--	SELECT TV_DETAIL1.ORDER_NBR, TV_DETAIL1.LINE_NBR, TV_DETAIL1.BRDCAST_YEAR, 
	--		TV_DETAIL1.CLOSE_DATE, TV_DETAIL1.EXT_CLOSE_DATE, TV_DETAIL1.MATL_CLOSE_DATE, 
	--		TV_DETAIL1.EXT_MATL_DATE, TV_DETAIL1.JOB_NUMBER, TV_DETAIL1.JOB_COMPONENT_NBR, 
	--		TV_DETAIL1.START_TIME, TV_DETAIL1.END_TIME, TV_DETAIL1.LENGTH, TV_DETAIL1.PROGRAMMING,
	--		TV_DETAIL1.TAG, TV_DETAIL1.REMARKS, TV_DETAIL2.MATL_NOTES, TV_DETAIL1.LINE_CANCELLED, TV_DETAIL1.MAT_COMP
	--	FROM (@TV_Detail_Max_Rev_Seq TDMRS INNER JOIN TV_DETAIL2 ON (TDMRS.ORDER_NBR = TV_DETAIL2.ORDER_NBR) 
	--		AND (TDMRS.LINE_NBR = TV_DETAIL2.LINE_NBR) 
	--		AND (TDMRS.REV_NBR = TV_DETAIL2.REV_NBR) 
	--		AND (TDMRS.SEQ_NBR = TV_DETAIL2.SEQ_NBR) 
	--		AND (TDMRS.BRDCAST_YEAR = TV_DETAIL2.BRDCAST_YEAR)) 
	--		INNER JOIN TV_DETAIL1 ON (TDMRS.ORDER_NBR = TV_DETAIL1.ORDER_NBR) 
	--		AND (TDMRS.LINE_NBR = TV_DETAIL1.LINE_NBR) 
	--		AND (TDMRS.REV_NBR = TV_DETAIL1.REV_NBR) 
	--		AND (TDMRS.SEQ_NBR = TV_DETAIL1.SEQ_NBR) 
	--		AND (TDMRS.BRDCAST_YEAR = TV_DETAIL1.BRDCAST_YEAR)
	--	WHERE TV_DETAIL1.LINE_CANCELLED IS NULL


	--	if @MatDueDate = 'Y'
	--		INSERT INTO #media_rows
	--		SELECT THD.TYPE, 'A' AS EST_ACT, THD.OFFICE_CODE, 
	--			TDDNA.ORDER_NBR, THD.ORDER_DESC, THD.MEDIA_TYPE, THD.CL_CODE, 
	--			THD.DIV_CODE, THD.PRD_CODE, THD.CMP_IDENTIFIER, '' AS CMP_CODE, THD.CMP_NAME AS CMP_NAME,
	--			THD.VN_CODE, THD.VN_NAME, THD.BUYER, THD.CLIENT_PO, THD.MARKET_CODE, THD.MARKET_DESC, '' AS ORDER_ACCEPTED,
	--			TDDNA.LINE_NBR, '' AS ACTIVE_REV,  
	--			--THD.FLIGHT_FROM,
	--			(CAST(THD.FLIGHT_FROM AS varchar(30)) + ' - ' + CAST(THD.FLIGHT_TO AS varchar(30))) AS FLIGHT_DATES, THD.FLIGHT_FROM AS START_DATE, THD.FLIGHT_TO AS END_DATE,
	--			'' as MEDIA_MONTH, TDDNA.BRDCAST_YEAR AS MEDIA_YEAR,
	--			TDDNA.CLOSE_DATE, TDDNA.MATL_CLOSE_DATE,
	--			TDDNA.EXT_CLOSE_DATE, TDDNA.EXT_MATL_DATE, 
	--			'' AS SIZE, 0 AS PRINT_COLUMNS, 0 AS PRINT_INCHES, 0 AS PRINT_LINES, '' AS AD_NUMBER, '' AS HEADLINE,
	--			'' AS INTERNET_TYPE, '' AS OUTDOOR_TYPE, '' AS MATERIAL, '' AS EDITION_ISSUE, '' AS SECTION,
	--			TDDNA.START_TIME, TDDNA.END_TIME,
	--			TDDNA.LENGTH, TDDNA.TAG,
	--			TDDNA.PROGRAMMING, TDDNA.MATL_NOTES, TDDNA.REMARKS,
	--			TDDNA.JOB_NUMBER, TDDNA.JOB_COMPONENT_NBR, 
	--			'' AS PRODUCTION_SIZE, 0 AS EST_NBR, 0 AS EST_LINE_NBR, 0 AS EST_REV_NBR, 0 AS LINE_TOTAL, 0 AS COST_PER,
	--			0 AS IMPRESSIONS, TDDNA.LINE_CANCELLED, THD.CL_NAME AS CL_NAME, THD.DIV_NAME AS DIV_NAME, THD.PRD_DESCRIPTION AS PRD_DESCRIPTION, THD.REV_NBR AS REV_NBR, TDDNA.MAT_COMP AS MAT_COMP, '' AS SIZE_DESC				
	--		FROM @TV_Header_Data THD INNER JOIN @TV_Detail_Data_No_Amounts TDDNA
	--			 ON THD.ORDER_NBR = TDDNA.ORDER_NBR
	--		WHERE MATL_CLOSE_DATE >= @StartDate AND MATL_CLOSE_DATE <= @EndDate			 
	--	if @ExtMatDueDate = 'Y' 
	--		INSERT INTO #media_rows
	--		SELECT THD.TYPE, 'A' AS EST_ACT, THD.OFFICE_CODE, 
	--			TDDNA.ORDER_NBR, THD.ORDER_DESC, THD.MEDIA_TYPE, THD.CL_CODE, 
	--			THD.DIV_CODE, THD.PRD_CODE, THD.CMP_IDENTIFIER, '' AS CMP_CODE, THD.CMP_NAME AS CMP_NAME,
	--			THD.VN_CODE, THD.VN_NAME, THD.BUYER, THD.CLIENT_PO, THD.MARKET_CODE, THD.MARKET_DESC, '' AS ORDER_ACCEPTED,
	--			TDDNA.LINE_NBR, '' AS ACTIVE_REV,  
	--			--THD.FLIGHT_FROM,
	--			(CAST(THD.FLIGHT_FROM AS varchar(30)) + ' - ' + CAST(THD.FLIGHT_TO AS varchar(30))) AS FLIGHT_DATES, THD.FLIGHT_FROM AS START_DATE, THD.FLIGHT_TO AS END_DATE,
	--			'' as MEDIA_MONTH, TDDNA.BRDCAST_YEAR AS MEDIA_YEAR,
	--			TDDNA.CLOSE_DATE, TDDNA.MATL_CLOSE_DATE,
	--			TDDNA.EXT_CLOSE_DATE, TDDNA.EXT_MATL_DATE, 
	--			'' AS SIZE, 0 AS PRINT_COLUMNS, 0 AS PRINT_INCHES, 0 AS PRINT_LINES, '' AS AD_NUMBER, '' AS HEADLINE,
	--			'' AS INTERNET_TYPE, '' AS OUTDOOR_TYPE, '' AS MATERIAL, '' AS EDITION_ISSUE, '' AS SECTION,
	--			TDDNA.START_TIME, TDDNA.END_TIME,
	--			TDDNA.LENGTH, TDDNA.TAG,
	--			TDDNA.PROGRAMMING, TDDNA.MATL_NOTES, TDDNA.REMARKS,
	--			TDDNA.JOB_NUMBER, TDDNA.JOB_COMPONENT_NBR, 
	--			'' AS PRODUCTION_SIZE, 0 AS EST_NBR, 0 AS EST_LINE_NBR, 0 AS EST_REV_NBR, 0 AS LINE_TOTAL, 0 AS COST_PER,
	--			0 AS IMPRESSIONS, TDDNA.LINE_CANCELLED, THD.CL_NAME AS CL_NAME, THD.DIV_NAME AS DIV_NAME, THD.PRD_DESCRIPTION AS PRD_DESCRIPTION, THD.REV_NBR AS REV_NBR, TDDNA.MAT_COMP AS MAT_COMP, '' AS SIZE_DESC						
	--		FROM @TV_Header_Data THD INNER JOIN @TV_Detail_Data_No_Amounts TDDNA
	--			 ON THD.ORDER_NBR = TDDNA.ORDER_NBR
	--		WHERE EXT_MATL_DATE >= @StartDate AND EXT_MATL_DATE <= @EndDate				
	--	if @CloseDate = 'Y'
	--		INSERT INTO #media_rows
	--		SELECT THD.TYPE, 'A' AS EST_ACT, THD.OFFICE_CODE, 
	--			TDDNA.ORDER_NBR, THD.ORDER_DESC, THD.MEDIA_TYPE, THD.CL_CODE, 
	--			THD.DIV_CODE, THD.PRD_CODE, THD.CMP_IDENTIFIER, '' AS CMP_CODE, THD.CMP_NAME AS CMP_NAME,
	--			THD.VN_CODE, THD.VN_NAME, THD.BUYER, THD.CLIENT_PO, THD.MARKET_CODE, THD.MARKET_DESC, '' AS ORDER_ACCEPTED,
	--			TDDNA.LINE_NBR, '' AS ACTIVE_REV,  
	--			--THD.FLIGHT_FROM,
	--			(CAST(THD.FLIGHT_FROM AS varchar(30)) + ' - ' + CAST(THD.FLIGHT_TO AS varchar(30))) AS FLIGHT_DATES, THD.FLIGHT_FROM AS START_DATE, THD.FLIGHT_TO AS END_DATE,
	--			'' as MEDIA_MONTH, TDDNA.BRDCAST_YEAR AS MEDIA_YEAR,
	--			TDDNA.CLOSE_DATE, TDDNA.MATL_CLOSE_DATE,
	--			TDDNA.EXT_CLOSE_DATE, TDDNA.EXT_MATL_DATE,  
	--			'' AS SIZE, 0 AS PRINT_COLUMNS, 0 AS PRINT_INCHES, 0 AS PRINT_LINES, '' AS AD_NUMBER, '' AS HEADLINE,
	--			'' AS INTERNET_TYPE, '' AS OUTDOOR_TYPE, '' AS MATERIAL, '' AS EDITION_ISSUE, '' AS SECTION,
	--			TDDNA.START_TIME, TDDNA.END_TIME,
	--			TDDNA.LENGTH, TDDNA.TAG,
	--			TDDNA.PROGRAMMING, TDDNA.MATL_NOTES, TDDNA.REMARKS,
	--			TDDNA.JOB_NUMBER, TDDNA.JOB_COMPONENT_NBR, 
	--			'' AS PRODUCTION_SIZE, 0 AS EST_NBR, 0 AS EST_LINE_NBR, 0 AS EST_REV_NBR, 0 AS LINE_TOTAL, 0 AS COST_PER,
	--			0 AS IMPRESSIONS, TDDNA.LINE_CANCELLED, THD.CL_NAME AS CL_NAME, THD.DIV_NAME AS DIV_NAME, THD.PRD_DESCRIPTION AS PRD_DESCRIPTION, THD.REV_NBR AS REV_NBR, TDDNA.MAT_COMP AS MAT_COMP, '' AS SIZE_DESC						
	--		FROM @TV_Header_Data THD INNER JOIN @TV_Detail_Data_No_Amounts TDDNA
	--			 ON THD.ORDER_NBR = TDDNA.ORDER_NBR
	--		WHERE CLOSE_DATE >= @StartDate AND CLOSE_DATE <= @EndDate			
	--	if @ExtCloseDate = 'Y'
	--		INSERT INTO #media_rows
	--		SELECT THD.TYPE, 'A' AS EST_ACT, THD.OFFICE_CODE, 
	--			TDDNA.ORDER_NBR, THD.ORDER_DESC, THD.MEDIA_TYPE, THD.CL_CODE, 
	--			THD.DIV_CODE, THD.PRD_CODE, THD.CMP_IDENTIFIER, '' AS CMP_CODE, THD.CMP_NAME AS CMP_NAME,
	--			THD.VN_CODE, THD.VN_NAME, THD.BUYER, THD.CLIENT_PO, THD.MARKET_CODE, THD.MARKET_DESC, '' AS ORDER_ACCEPTED,
	--			TDDNA.LINE_NBR, '' AS ACTIVE_REV,  
	--			--THD.FLIGHT_FROM,
	--			(CAST(THD.FLIGHT_FROM AS varchar(30)) + ' - ' + CAST(THD.FLIGHT_TO AS varchar(30))) AS FLIGHT_DATES, THD.FLIGHT_FROM AS START_DATE, THD.FLIGHT_TO AS END_DATE,
	--			'' as MEDIA_MONTH, TDDNA.BRDCAST_YEAR AS MEDIA_YEAR,
	--			TDDNA.CLOSE_DATE, TDDNA.MATL_CLOSE_DATE,
	--			TDDNA.EXT_CLOSE_DATE, TDDNA.EXT_MATL_DATE, 
	--			'' AS SIZE, 0 AS PRINT_COLUMNS, 0 AS PRINT_INCHES, 0 AS PRINT_LINES, '' AS AD_NUMBER, '' AS HEADLINE,
	--			'' AS INTERNET_TYPE, '' AS OUTDOOR_TYPE, '' AS MATERIAL, '' AS EDITION_ISSUE, '' AS SECTION,
	--			TDDNA.START_TIME, TDDNA.END_TIME,
	--			TDDNA.LENGTH, TDDNA.TAG,
	--			TDDNA.PROGRAMMING, TDDNA.MATL_NOTES, TDDNA.REMARKS,
	--			TDDNA.JOB_NUMBER, TDDNA.JOB_COMPONENT_NBR, 
	--			'' AS PRODUCTION_SIZE, 0 AS EST_NBR, 0 AS EST_LINE_NBR, 0 AS EST_REV_NBR, 0 AS LINE_TOTAL, 0 AS COST_PER,
	--			0 AS IMPRESSIONS, TDDNA.LINE_CANCELLED, THD.CL_NAME AS CL_NAME, THD.DIV_NAME AS DIV_NAME, THD.PRD_DESCRIPTION AS PRD_DESCRIPTION, THD.REV_NBR AS REV_NBR, TDDNA.MAT_COMP AS MAT_COMP, '' AS SIZE_DESC						
	--		FROM @TV_Header_Data THD INNER JOIN @TV_Detail_Data_No_Amounts TDDNA
	--			 ON THD.ORDER_NBR = TDDNA.ORDER_NBR
	--		WHERE EXT_CLOSE_DATE >= @StartDate AND EXT_CLOSE_DATE <= @EndDate						
	--	if @RunInsertionDate = 'Y'
	--		INSERT INTO #media_rows
	--		SELECT THD.TYPE, 'A' AS EST_ACT, THD.OFFICE_CODE, 
	--			TDDNA.ORDER_NBR, THD.ORDER_DESC, THD.MEDIA_TYPE, THD.CL_CODE, 
	--			THD.DIV_CODE, THD.PRD_CODE, THD.CMP_IDENTIFIER, '' AS CMP_CODE, THD.CMP_NAME AS CMP_NAME,
	--			THD.VN_CODE, THD.VN_NAME, THD.BUYER, THD.CLIENT_PO, THD.MARKET_CODE, THD.MARKET_DESC, '' AS ORDER_ACCEPTED,
	--			TDDNA.LINE_NBR, '' AS ACTIVE_REV,  
	--			--THD.FLIGHT_FROM,
	--			(CAST(THD.FLIGHT_FROM AS varchar(30)) + ' - ' + CAST(THD.FLIGHT_TO AS varchar(30))) AS FLIGHT_DATES, THD.FLIGHT_FROM AS START_DATE, THD.FLIGHT_TO AS END_DATE,
	--			'' as MEDIA_MONTH, TDDNA.BRDCAST_YEAR AS MEDIA_YEAR,
	--			TDDNA.CLOSE_DATE, TDDNA.MATL_CLOSE_DATE,
	--			TDDNA.EXT_CLOSE_DATE, TDDNA.EXT_MATL_DATE, 
	--			'' AS SIZE, 0 AS PRINT_COLUMNS, 0 AS PRINT_INCHES, 0 AS PRINT_LINES, '' AS AD_NUMBER, '' AS HEADLINE,
	--			'' AS INTERNET_TYPE, '' AS OUTDOOR_TYPE, '' AS MATERIAL, '' AS EDITION_ISSUE, '' AS SECTION,
	--			TDDNA.START_TIME, TDDNA.END_TIME,
	--			TDDNA.LENGTH, TDDNA.TAG,
	--			TDDNA.PROGRAMMING, TDDNA.MATL_NOTES, TDDNA.REMARKS,
	--			TDDNA.JOB_NUMBER, TDDNA.JOB_COMPONENT_NBR, 
	--			'' AS PRODUCTION_SIZE, 0 AS EST_NBR, 0 AS EST_LINE_NBR, 0 AS EST_REV_NBR, 0 AS LINE_TOTAL, 0 AS COST_PER,
	--			0 AS IMPRESSIONS, TDDNA.LINE_CANCELLED, THD.CL_NAME AS CL_NAME, THD.DIV_NAME AS DIV_NAME, THD.PRD_DESCRIPTION AS PRD_DESCRIPTION, THD.REV_NBR AS REV_NBR, TDDNA.MAT_COMP AS MAT_COMP, '' AS SIZE_DESC						
	--		FROM @TV_Header_Data THD INNER JOIN @TV_Detail_Data_No_Amounts TDDNA
	--			 ON THD.ORDER_NBR = TDDNA.ORDER_NBR
	--		WHERE FLIGHT_FROM >= @StartDate AND FLIGHT_FROM <= @EndDate OR FLIGHT_TO >= @StartDate AND FLIGHT_TO <= @EndDate OR
	--			  @StartDate >= FLIGHT_FROM AND @StartDate <= FLIGHT_TO OR @EndDate >= FLIGHT_FROM AND @EndDate <= FLIGHT_TO					


SELECT ISNULL(TYPE,'') AS TYPE, ISNULL(EST_ACT,'') AS EST_ACT, ISNULL(OFFICE_CODE,'') AS OFFICE_CODE, ISNULL(ORDER_NBR,'') AS ORDER_NBR, 
	   ISNULL(ORDER_DESC,'') AS ORDER_DESC, ISNULL(MEDIA_TYPE,'') AS MEDIA_TYPE, ISNULL(CL_CODE,'') AS CL_CODE, ISNULL(DIV_CODE,'') AS DIV_CODE,
	   ISNULL(PRD_CODE,'') AS PRD_CODE, ISNULL(CMP_IDENTIFIER,-1) AS CMP_IDENTIFIER, ISNULL(CMP_CODE,'') AS CMP_CODE, ISNULL(CMP_NAME,'') AS CMP_NAME, ISNULL(VN_CODE,'') AS VN_CODE, ISNULL(VN_NAME,'') AS VN_NAME, ISNULL(BUYER,'') AS BUYER,
	   ISNULL(CLIENT_PO,'') AS CLIENT_PO, ISNULL(MARKET_CODE,'') AS MARKET_CODE, ISNULL(MARKET_DESC,'') AS MARKET_DESC, ISNULL(ORDER_ACCEPTED,'') AS ORDER_ACCEPTED, ISNULL(LINE_NBR,'') AS LINE_NBR,
	   ISNULL(ACTIVE_REV,'') AS ACTIVE_REV, ISNULL(FLIGHT_DATES,'') AS FLIGHT_DATES, ISNULL(START_DATE,'') AS START_DATE, ISNULL(END_DATE,'') AS END_DATE,
	   ISNULL(MEDIA_MONTH,'') AS MEDIA_MONTH, ISNULL(MEDIA_YEAR,'') AS MEDIA_YEAR, ISNULL(CLOSE_DATE,'') AS CLOSE_DATE, ISNULL(MATL_CLOSE_DATE,'') AS MATL_CLOSE_DATE,
	   ISNULL(EXT_CLOSE_DATE,'') AS EXT_CLOSE_DATE, ISNULL(EXT_MATL_DATE,'') AS EXT_MATL_DATE, ISNULL(SIZE,'') AS SIZE, ISNULL(PRINT_COLUMNS,0) AS PRINT_COLUMNS,
	   ISNULL(PRINT_INCHES,0) AS PRINT_INCHES, ISNULL(PRINT_LINES,0) AS PRINT_LINES, ISNULL(AD_NUMBER,'') AS AD_NUMBER, ISNULL(HEADLINE,'') AS HEADLINE,
	   ISNULL(INTERNET_TYPE,'') AS INTERNET_TYPE, ISNULL(OUTDOOR_TYPE,'') AS OUTDOOR_TYPE, ISNULL(MATERIAL,'') AS MATERIAL, ISNULL(EDITION_ISSUE,'') AS EDITION_ISSUE,
	   ISNULL(SECTION,'') AS SECTION, ISNULL(START_TIME,'') AS START_TIMR, ISNULL(END_TIME,'') AS END_TIME, ISNULL(LENGTH,'') AS LENGTH,
	   ISNULL(TAG,'') AS TAG, ISNULL(PROGRAMMING,'') AS PROGRAMMING, ISNULL(MATL_NOTES,'') AS MATL_NOTES, ISNULL(REMARKS,'') AS REMARKS,
	   ISNULL(JOB_NUMBER,-1) AS JOB_NUMBER, ISNULL(JOB_COMPONENT_NBR,-1) AS JOB_COMPONENT_NBR, ISNULL(PRODUCTION_SIZE,'') AS PRODUCTION_SIZE,
	   ISNULL(EST_NBR,0) AS EST_NBR, ISNULL(EST_LINE_NBR,0) AS EST_LINE_NBR, ISNULL(EST_REV_NBR,0) AS EST_REV_NBR, ISNULL(LINE_TOTAL,0) AS LINE_TOTAL,
	   ISNULL(COST_PER,0) AS COST_PER, ISNULL(IMPRESSIONS,0) AS IMPRESSIONS, ISNULL(LINE_CANCELLED,'') AS LINE_CANCELLED, ISNULL(CL_NAME,'') AS CL_NAME, ISNULL(DIV_NAME,'') AS DIV_NAME,
       ISNULL(PRD_DESCRIPTION,'') AS PRD_DESCRIPTION, ISNULL(REV_NBR,'') AS REV_NBR, ISNULL(MAT_COMP,'') AS MAT_COMP, ISNULL(SIZE_DESC,'') AS SIZE_DESC,  0 AS DOCUMENT_COUNT				
from #media_rows
WHERE ISNULL(CL_CODE,'') LIKE '%' + @ClientCode AND ISNULL(DIV_CODE,'') LIKE '%' + @DivCode AND ISNULL(PRD_CODE,'') LIKE '%' + @ProdCode
	  AND ISNULL(MEDIA_TYPE,'') LIKE '%' + @MediaType AND ISNULL(CMP_CODE,'') LIKE '%' + @Campaign AND ISNULL(CLIENT_PO,'') LIKE '%' + @ClientPO COLLATE SQL_Latin1_General_Cp1_CI_AS
	  AND ISNULL(VN_CODE,'') LIKE '%' + @VendorID AND ISNULL(BUYER,'') LIKE '%' + @BuyerID

	
DROP TABLE #media_rows





