


/* ============================================================ */
/*   View: BILLED_NEWS_VIEW                                     */
/* ============================================================ */
CREATE VIEW dbo.BILLED_NEWS_VIEW ( AR_INV_NBR, AR_INV_SEQ, AR_TYPE, BILLING_SEQ, BILL_AMT, CITY_TAX, COMM_AMT, COUNTY_TAX,
	LINE_DISC, LINE_NBR, LINE_NET, MEDIA_TYPE, NETCHARGES, ORDER_NBR, REBATE_AMT, REV_NBR, SEQ_NBR, STATE_TAX,
	VENDOR_TAX, AR_INV_DATE, AR_POST_PERIOD, CMP_UPD_INV_DATE, CMP_UPD_PP, CMP_CODE, CMP_IDENTIFIER, CMP_LINE_NBR) 
AS
 SELECT ALL A.AR_INV_NBR, 
	A.AR_INV_SEQ, 
	A.AR_TYPE, 
	BILLING_SEQ, 
	BILL_AMT, 
	CITY_TAX, 
	COMM_AMT, 
	COUNTY_TAX, 
	LINE_DISC, 
	LINE_NBR, 
	LINE_NET, 
	A.MEDIA_TYPE, 
	NETCHARGES, 
	A.ORDER_NBR, 
	REBATE_AMT, 
	REV_NBR, 
	SEQ_NBR, 
	STATE_TAX, 
	VENDOR_TAX, 
	AR_INV_DATE, 
	AR_POST_PERIOD, 
	CMP_UPD_INV_DATE, 
	CMP_UPD_PP, 
	C.CMP_CODE, 
	CMP_IDENTIFIER, 
	CMP_LINE_NBR 
   FROM MEDIA_BILL_AMTS A, 
	ACCT_REC B,  
	NEWS_HEADER C 
  WHERE A.AR_INV_NBR=B.AR_INV_NBR 
    AND A.AR_INV_SEQ=B.AR_INV_SEQ 
    AND A.AR_TYPE=B.AR_TYPE 
    AND A.ORDER_NBR=C.ORDER_NBR 
    AND A.MEDIA_TYPE='NEWS'



