


/* ============================================================ */
/*   View: BILLED_AB_VIEW                                       */
/* ============================================================ */

CREATE VIEW [dbo].[BILLED_AB_VIEW] ( AB_ID, ADV_BILL_NET_AMT, AR_INV_NBR, AR_INV_SEQ, AR_TYPE, EXT_CITY_RESALE, EXT_COUNTY_RESALE,
	EXT_MARKUP_AMT, EXT_NONRESALE_TAX, EXT_STATE_RESALE, FNC_CODE, FNC_TYPE, JOB_COMPONENT_NBR, JOB_NUMBER, LINE_TOTAL,
	SEQ_NBR, AR_INV_DATE, AR_POST_PERIOD, CMP_UPD_INV_DATE, CMP_UPD_PP, CMP_CODE, CMP_IDENTIFIER, CMP_LINE_NBR) 
AS
 SELECT ALL [dbo].[ADVANCE_BILLING].[AB_ID], 
	[dbo].[ADVANCE_BILLING].[ADV_BILL_NET_AMT], 
	[A].[AR_INV_NBR], 
	[A].[AR_INV_SEQ], 
	[A].[AR_TYPE], 
	[dbo].[ADVANCE_BILLING].[EXT_CITY_RESALE], 
	[dbo].[ADVANCE_BILLING].[EXT_COUNTY_RESALE], 
	[dbo].[ADVANCE_BILLING].[EXT_MARKUP_AMT], 
	[dbo].[ADVANCE_BILLING].[EXT_NONRESALE_TAX], 
	[dbo].[ADVANCE_BILLING].[EXT_STATE_RESALE], 
	[dbo].[ADVANCE_BILLING].[FNC_CODE], 
	[dbo].[ADVANCE_BILLING].[FNC_TYPE], 
	[A].[JOB_COMPONENT_NBR], 
	[A].[JOB_NUMBER], 
	[dbo].[ADVANCE_BILLING].[LINE_TOTAL], 
	[dbo].[ADVANCE_BILLING].[SEQ_NBR], 
	[dbo].[ACCT_REC].[AR_INV_DATE], 
	[dbo].[ACCT_REC].[AR_POST_PERIOD], 
	[dbo].[ADVANCE_BILLING].[CMP_UPD_INV_DATE], 
	[dbo].[ADVANCE_BILLING].[CMP_UPD_PP], 
	[C].[CMP_CODE], 
	[dbo].[JOB_LOG].[CMP_IDENTIFIER], 
	[dbo].[JOB_LOG].[CMP_LINE_NBR] 
   FROM [dbo].[ADVANCE_BILLING] A, 
	[dbo].[ACCT_REC] B, 
	[dbo].[JOB_LOG] C 
  WHERE [A].[AR_INV_NBR]=[B].[AR_INV_NBR] 
    AND [A].[AR_INV_SEQ]=[B].[AR_INV_SEQ] 
    AND [A].[AR_TYPE]=[B].[AR_TYPE] 
    AND [A].[JOB_NUMBER]=[C].[JOB_NUMBER]



