SET QUOTED_IDENTIFIER ON 
GO

SET ANSI_PADDING OFF
GO

SET ANSI_NULLS ON 
GO

IF EXISTS ( SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID( N'[dbo].[CONTRACT_DOCUMENTS_ALL]') AND OBJECTPROPERTY( id, N'IsView' ) = 1 )
	DROP VIEW [dbo].[CONTRACT_DOCUMENTS_ALL]
GO

CREATE VIEW [dbo].[CONTRACT_DOCUMENTS_ALL]
AS
SELECT     dbo.CONTRACT_DOCUMENTS.CONTRACT_ID, dbo.DOCUMENTS.DOCUMENT_ID, dbo.DOCUMENTS.FILENAME, dbo.DOCUMENTS.MIME_TYPE, 
                      dbo.DOCUMENTS.DESCRIPTION, dbo.DOCUMENTS.KEYWORDS, dbo.DOCUMENTS.UPLOADED_DATE, dbo.DOCUMENTS.USER_CODE, 
                      dbo.DOCUMENTS.FILE_SIZE, 
						   dbo.DOCUMENTS.USER_CODE AS [USER_NAME], 
					   dbo.DOCUMENTS.REPOSITORY_FILENAME
FROM         dbo.DOCUMENTS  INNER JOIN
                      dbo.CONTRACT_DOCUMENTS ON dbo.DOCUMENTS.DOCUMENT_ID = dbo.CONTRACT_DOCUMENTS.DOCUMENT_ID
GO

IF ( @@ERROR = 0 )
	GRANT SELECT ON [CONTRACT_DOCUMENTS_ALL] TO PUBLIC AS dbo
GO	