


CREATE VIEW [dbo].[CP_OPEN_MILESTONE_TASKS]
AS
SELECT     dbo.JOB_LOG.CL_CODE, dbo.JOB_LOG.DIV_CODE, dbo.JOB_LOG.PRD_CODE, dbo.JOB_LOG.JOB_NUMBER, 
                      dbo.JOB_COMPONENT.JOB_COMPONENT_NBR, dbo.JOB_TRAFFIC_DET.TASK_DESCRIPTION, dbo.JOB_TRAFFIC_DET.FNC_CODE, 
                      dbo.JOB_TRAFFIC_DET.JOB_REVISED_DATE AS DueDate, dbo.JOB_TRAFFIC_DET.REVISED_DUE_TIME AS DueTime, 
                      dbo.JOB_TRAFFIC_DET.JOB_NUMBER AS JobNo, dbo.JOB_TRAFFIC_DET.JOB_COMPONENT_NBR AS JobComp, 
                      dbo.JOB_TRAFFIC_DET.JOB_HRS AS HoursAllowed, dbo.JOB_TRAFFIC_DET.SEQ_NBR AS SeqNo, 
                      dbo.JOB_TRAFFIC_DET.TEMP_COMP_DATE AS TempCompleteDate, dbo.JOB_TRAFFIC_DET.MILESTONE, dbo.JOB_TRAFFIC_DET.TASK_STATUS
FROM         dbo.JOB_LOG INNER JOIN
                      dbo.JOB_COMPONENT ON dbo.JOB_LOG.JOB_NUMBER = dbo.JOB_COMPONENT.JOB_NUMBER INNER JOIN
                      dbo.JOB_TRAFFIC_DET ON dbo.JOB_COMPONENT.JOB_NUMBER = dbo.JOB_TRAFFIC_DET.JOB_NUMBER AND 
                      dbo.JOB_COMPONENT.JOB_COMPONENT_NBR = dbo.JOB_TRAFFIC_DET.JOB_COMPONENT_NBR
WHERE     (dbo.JOB_TRAFFIC_DET.MILESTONE = 1) AND (dbo.JOB_TRAFFIC_DET.TEMP_COMP_DATE IS NULL)



