CREATE VIEW [dbo].[CURRENT_VENDOR_CONTRACT_DOCUMENTS]
AS
	
	SELECT
		[LEVEL] = 'Vendor Contract', 
		[CONTRACT_ID] = VENDOR_CONTRACT_DOCUMENTS.VENDOR_CONTRACT_ID, 
		[DOCUMENT_ID] = DOCUMENTS.DOCUMENT_ID, 
		[FILENAME] = DOCUMENTS.[FILENAME], 
		[MIME_TYPE] = DOCUMENTS.MIME_TYPE,
		[DESCRIPTION] = DOCUMENTS.[DESCRIPTION], 
		[KEYWORDS] = DOCUMENTS.KEYWORDS, 
		[UPLOADED_DATE] = DOCUMENTS.UPLOADED_DATE, 
		[USER_CODE] = DOCUMENTS.USER_CODE,
		[FILE_SIZE] = DOCUMENTS.FILE_SIZE, 
		[USER_NAME] = DOCUMENTS.USER_CODE, 
		[REPOSITORY_FILENAME] = DOCUMENTS.REPOSITORY_FILENAME,
		[DOCUMENT_TYPE_DESC] = DOCUMENT_TYPE.DOCUMENT_TYPE_DESC, 
		[PRIVATE_FLAG] = ISNULL(dbo.DOCUMENTS.PRIVATE_FLAG, 0)
	FROM         
		dbo.DOCUMENTS INNER JOIN
		dbo.VENDOR_CONTRACT_DOCUMENTS ON DOCUMENTS.DOCUMENT_ID = VENDOR_CONTRACT_DOCUMENTS.DOCUMENT_ID INNER JOIN
		dbo.DOCUMENT_TYPE ON DOCUMENTS.DOCUMENT_TYPE_ID = DOCUMENT_TYPE.DOCUMENT_TYPE_ID
WHERE     
		(dbo.DOCUMENTS.DOCUMENT_ID IN (SELECT
											MAX(CONTRACT_DOCUMENTS_1.DOCUMENT_ID) AS DOCUMENT_ID
										FROM          
											dbo.CONTRACT_DOCUMENTS AS CONTRACT_DOCUMENTS_1 INNER JOIN
											dbo.DOCUMENTS AS DOCUMENTS_1 ON CONTRACT_DOCUMENTS_1.DOCUMENT_ID = DOCUMENTS_1.DOCUMENT_ID
										GROUP BY 
											CONTRACT_DOCUMENTS_1.DOCUMENT_ID, 
											DOCUMENTS_1.[FILENAME]))

GO


