-- V_BA_COMMENT_DTL
-- #00 08/17/12 - initial version

SET QUOTED_IDENTIFIER ON 
GO

SET ANSI_NULLS ON 
GO

SET ANSI_PADDING OFF
GO

IF EXISTS ( SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID( N'[dbo].[V_BA_COMMENT_DTL]' ) AND OBJECTPROPERTY( id, N'IsView' ) = 1 )
	DROP VIEW [dbo].[V_BA_COMMENT_DTL]
GO

CREATE VIEW dbo.V_BA_COMMENT_DTL 
AS

SELECT
	bah.BA_ID,
	bah.AR_INV_NBR, 
	bah.JOB_NUMBER,
	bah.JOB_COMPONENT_NBR,
	bad.FNC_CODE,
	bad.CLIENT_COMMENTS AS CLIENT_FNC_COMMENTS
FROM dbo.V_BA_COMMENT_HDR bah
JOIN dbo.BILL_APPR_DTL bad
	ON bah.JOB_NUMBER = bad.JOB_NUMBER
	AND bah.JOB_COMPONENT_NBR = bad.JOB_COMPONENT_NBR
	AND bah.BA_ID = bad.BA_ID
WHERE bad.CLIENT_COMMENTS IS NOT NULL
	AND CAST(bad.CLIENT_COMMENTS AS varchar(1)) <> ''		--to suppress '' values

GO

IF ( @@ERROR = 0 )
	GRANT ALL ON [V_BA_COMMENT_DTL] TO PUBLIC AS dbo
GO	
