-- V_BA_COMMENT_HDR
-- #00 08/17/12 - initial version

SET QUOTED_IDENTIFIER ON 
GO

SET ANSI_NULLS ON 
GO

SET ANSI_PADDING OFF
GO

IF EXISTS ( SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID( N'[dbo].[V_BA_COMMENT_HDR]' ) AND OBJECTPROPERTY( id, N'IsView' ) = 1 )
	DROP VIEW [dbo].[V_BA_COMMENT_HDR]
GO

CREATE VIEW dbo.V_BA_COMMENT_HDR 
AS

SELECT
	bah.BA_ID,
	bah.AR_INV_NBR, 
	bah.JOB_NUMBER,
	bah.JOB_COMPONENT_NBR,
	bah.CLIENT_COMMENTS
FROM dbo.BILL_APPR_HDR bah
WHERE bah.CLIENT_COMMENTS IS NOT NULL
	AND bah.BA_ID = (SELECT MAX(bah2.BA_ID) FROM dbo.BILL_APPR_HDR bah2
		WHERE bah.JOB_NUMBER = bah2.JOB_NUMBER
		AND bah.JOB_COMPONENT_NBR = bah2.JOB_COMPONENT_NBR
		AND bah.AR_INV_NBR = bah2.AR_INV_NBR)

GO

IF ( @@ERROR = 0 )
	GRANT ALL ON [V_BA_COMMENT_HDR] TO PUBLIC AS dbo
GO	


