CREATE VIEW [dbo].[V_ETF_OFFDTLJC]

AS

	SELECT 
		[EmployeeTimeForecastID] = OFFDTLJC.ETF_ID,
		[EmployeeTimeForecastOfficeDetailID] = OFFDTLJC.ETF_OFFDTL_ID,
		[EmployeeTimeForecastOfficeDetailJobComponentID] = OFFDTLJC.ETF_OFFDTLJC_ID,
		[JobNumber] = JC.JOB_NUMBER,
		[JobDescription] = J.JOB_DESC,
		[ComponentNumber] = JC.JOB_COMPONENT_NBR,
		[ComponentDescription] = JC.JOB_COMP_DESC,
		[JobComponent] = RIGHT(REPLICATE('0', 6) + CONVERT(VARCHAR(20), JC.JOB_NUMBER), 6) + '-' + RIGHT(REPLICATE('0', 3) + CONVERT(VARCHAR(20), JC.JOB_COMPONENT_NBR), 3),
		[JobComponentDescription] = RIGHT(REPLICATE('0', 6) + CONVERT(VARCHAR(20), JC.JOB_NUMBER), 6) + '-' + J.JOB_DESC + ' | ' + RIGHT(REPLICATE('0', 3) + CONVERT(VARCHAR(20), JC.JOB_COMPONENT_NBR), 3) + '-' + JC.JOB_COMP_DESC,
		[OfficeCode] = OFFDTLJC.OFFICE_CODE,
		[OfficeDescription] = O.OFFICE_NAME,
		[ClientCode] = OFFDTLJC.CL_CODE,
		[ClientDescription] = C.CL_NAME,
		[DivisionCode] = OFFDTLJC.DIV_CODE,
		[DivisionDescription] = D.DIV_NAME,
		[ProductCode] = OFFDTLJC.PRD_CODE,
		[ProductDescription] = P.PRD_DESCRIPTION,
		[RevenueAmount] = OFFDTLJC.REV_AMT,
		[IsNonBillable] = ISNULL(CAST(JC.NOBILL_FLAG AS bit), 0)
	FROM 
		dbo.ETF_OFFDTLJC OFFDTLJC INNER JOIN 
		dbo.JOB_COMPONENT JC ON JC.JOB_NUMBER = OFFDTLJC.JOB_NUMBER AND JC.JOB_COMPONENT_NBR = OFFDTLJC.JOB_COMPONENT_NBR INNER JOIN
		dbo.JOB_LOG J ON J.JOB_NUMBER = OFFDTLJC.JOB_NUMBER INNER JOIN 
		dbo.CLIENT C ON C.CL_CODE = OFFDTLJC.CL_CODE INNER JOIN 
		dbo.DIVISION D ON D.CL_CODE = OFFDTLJC.CL_CODE AND
						  D.DIV_CODE = OFFDTLJC.DIV_CODE INNER JOIN 
		dbo.PRODUCT P ON P.CL_CODE = OFFDTLJC.CL_CODE AND
						 P.DIV_CODE = OFFDTLJC.DIV_CODE AND
						 P.PRD_CODE = OFFDTLJC.PRD_CODE INNER JOIN 
		dbo.OFFICE O ON O.OFFICE_CODE = OFFDTLJC.OFFICE_CODE 
		
GO
