CREATE VIEW [dbo].[V_ETF_OFFDTLJC_EMP]

AS

	SELECT 
		[EmployeeTimeForecastID] = OFFDTLJC_EMP.ETF_ID,
		[EmployeeTimeForecastOfficeDetailID] = OFFDTLJC_EMP.ETF_OFFDTL_ID,
		[EmployeeTimeForecastOfficeDetailJobComponentID] = OFFDTLJC_EMP.ETF_OFFDTLJC_ID,
		[EmployeeTimeForecastOfficeDetailJobComponentEmployeeID] = OFFDTLJC_EMP.ETF_OFFDTLJC_EMP_ID,
		[EmployeeTimeForecastOfficeDetailEmployeeID] = OFFDTLJC_EMP.ETF_OFFDTLEMP_ID,
		[EmployeeCode] = OFFDTLEMP.EMP_CODE,
		[EmployeeName] = CASE WHEN E.EMP_MI IS NULL OR E.EMP_MI = '' THEN RTRIM(LTRIM(ISNULL(E.EMP_FNAME, '') + ' ' + ISNULL(E.EMP_LNAME, ''))) ELSE E.EMP_FNAME + ' ' + E.EMP_MI + '. ' + E.EMP_LNAME END,
		[EmployeeOfficeCode] = E.OFFICE_CODE,
		[EmployeeOfficeDescription] = O.OFFICE_NAME,
		[Hours] = OFFDTLJC_EMP.[HOURS],
		[BillRate] = OFFDTLEMP.BILL_RATE,
		[CostRate] = OFFDTLEMP.COST_RATE
	FROM 
		dbo.ETF_OFFDTLJC_EMP OFFDTLJC_EMP INNER JOIN 
		dbo.ETF_OFFDTLEMP OFFDTLEMP ON OFFDTLEMP.ETF_ID = OFFDTLJC_EMP.ETF_ID AND
									   OFFDTLEMP.ETF_OFFDTL_ID = OFFDTLJC_EMP.ETF_OFFDTL_ID AND 
									   OFFDTLEMP.ETF_OFFDTLEMP_ID = OFFDTLJC_EMP.ETF_OFFDTLEMP_ID INNER JOIN
		dbo.EMPLOYEE E ON E.EMP_CODE = OFFDTLEMP.EMP_CODE LEFT JOIN 
		dbo.OFFICE O ON O.OFFICE_CODE = E.OFFICE_CODE 
			
GO
	
	