
CREATE VIEW [dbo].[V_FNC_BY_INV_JOB]
AS
	SELECT DISTINCT ap.AR_INV_NBR, ap.JOB_NUMBER, ap.JOB_COMPONENT_NBR, ap.FNC_CODE
	  FROM dbo.AP_PRODUCTION ap
	 WHERE ap.AR_INV_NBR IS NOT NULL   
	UNION 
	SELECT DISTINCT etd.AR_INV_NBR, etd.JOB_NUMBER, etd.JOB_COMPONENT_NBR, etd.FNC_CODE
	  FROM dbo.EMP_TIME_DTL etd
	 WHERE etd.AR_INV_NBR IS NOT NULL
	UNION
	SELECT DISTINCT inc.AR_INV_NBR, inc.JOB_NUMBER, inc.JOB_COMPONENT_NBR, inc.FNC_CODE
	  FROM dbo.INCOME_ONLY inc
	 WHERE inc.AR_INV_NBR IS NOT NULL
	UNION
	SELECT DISTINCT ab.AR_INV_NBR, ab.JOB_NUMBER, ab.JOB_COMPONENT_NBR, ab.FNC_CODE
	  FROM dbo.ADVANCE_BILLING ab
	 WHERE ab.AR_INV_NBR IS NOT NULL
