CREATE VIEW [dbo].[V_JOB_TRAFFIC_DET] 
AS
SELECT        jtd.JOB_NUMBER, jtd.JOB_COMPONENT_NBR, jtd.SEQ_NBR, jtd.FNC_CODE, jtde.EMP_CODE, jtd.FNC_EST, jtd.TASK_DESCRIPTION, jtd.TASK_START_DATE, jtd.JOB_DUE_DATE, jtd.JOB_REVISED_DATE, 
                         jtd.DUE_DATE_LOCK, jtd.JOB_COMPLETED_DATE, jtd.JOB_ORDER, jtd.JOB_DAYS, jtd.PARENT_TASK, jtd.FNC_COMMENTS, jtd.DUE_DATE_COMMENTS, jtd.REV_DATE_COMMENTS, 
                         jtde.HOURS_ALLOWED AS JOB_HRS, jtd.DUE_TIME, jtd.REVISED_DUE_TIME, jtd.TASK_STATUS, jtd.MILESTONE, jtd.TRAFFIC_PHASE_ID, jtd.ROWID, jtde.TEMP_COMP_DATE, jtde.COMPLETED_COMMENTS, 
                         jtde.PERCENT_COMPLETE, jtde.CARD_SEQ_NBR
FROM            dbo.JOB_TRAFFIC_DET AS jtd LEFT OUTER JOIN
                         dbo.JOB_TRAFFIC_DET_EMPS AS jtde ON jtd.JOB_NUMBER = jtde.JOB_NUMBER AND jtd.JOB_COMPONENT_NBR = jtde.JOB_COMPONENT_NBR AND jtd.SEQ_NBR = jtde.SEQ_NBR


GO


