IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[V_JOB_COMP_EST_HDR_INFO]') AND OBJECTPROPERTY(id, N'IsView') = 1)
	DROP VIEW [dbo].[V_JOB_COMP_EST_HDR_INFO]
GO

CREATE VIEW dbo.V_JOB_COMP_EST_HDR_INFO 
AS

-- V_JOB_COMP_EST_HDR_INFO
-- #00 08/17/12 - initial version
-- #01 04/01/13 - added jc.CDP_CONTACT_ID

SELECT 
		jl.JOB_NUMBER,
		jl.CL_CODE,
		jl.DIV_CODE,
		jl.PRD_CODE,
		jl.CMP_CODE,
		ISNULL(jl.CMP_IDENTIFIER,0) AS CMP_IDENTIFIER,
		cmp.CMP_NAME,
		jl.SC_CODE,
		sc.SC_DESCRIPTION,
		jl.JOB_DESC, 
		jl.JOB_COMMENTS,
		jl.JOB_CLI_REF,
		jl.COMPLEX_CODE,
		jl.PROMO_CODE,
		jl.JOB_BILL_COMMENT,
		ISNULL(p.PRD_CONSOL_FUNC,0) AS PRD_CONSOL_FNC,
		jc.JOB_COMPONENT_NBR,
		jc.JOB_AD_SIZE,
		jc.JOB_COMP_DESC, 
		jc.JOB_COMP_COMMENTS,
		jc.ACCT_NBR,
		jc.MARKET_CODE,
		mk.MARKET_DESC,
		jc.UDV1_CODE,
		jc.UDV2_CODE,
		jc.UDV3_CODE,
		jc.UDV4_CODE,
		jc.UDV5_CODE,
		jc.CDP_CONTACT_ID,				--#01
		IsNull(jc.PRD_CONT_CODE,'ZZ') AS PRD_CONT_CODE,
		jc.JOB_CL_PO_NBR, 
		el.EST_LOG_COMMENT, 
		ec.EST_COMP_COMMENT, 
		eq.EST_QTE_COMMENT, 
		er.EST_REV_COMMENT,
		e.EMP_FNAME + ' ' + e.EMP_LNAME AS EMPLOYEE
	FROM dbo.JOB_LOG AS jl
	JOIN dbo.SALES_CLASS sc
		ON jl.SC_CODE = sc.SC_CODE
	JOIN dbo.PRODUCT p
		ON jl.CL_CODE = p.CL_CODE
		AND jl.DIV_CODE = p.DIV_CODE
		AND jl.PRD_CODE = p.PRD_CODE
	JOIN dbo.CLIENT AS c
		ON jl.CL_CODE = c.CL_CODE	
	JOIN dbo.JOB_COMPONENT AS jc 
		ON jl.JOB_NUMBER = jc.JOB_NUMBER
	LEFT JOIN dbo.ESTIMATE_APPROVAL AS ea 
		ON jc.JOB_NUMBER = ea.JOB_NUMBER 
		AND jc.JOB_COMPONENT_NBR = ea.JOB_COMPONENT_NBR
	LEFT JOIN dbo.CAMPAIGN AS cmp
		ON jl.CMP_IDENTIFIER = cmp.CMP_IDENTIFIER	 
	LEFT JOIN dbo.ESTIMATE_LOG AS el 
		ON ea.ESTIMATE_NUMBER = el.ESTIMATE_NUMBER 
	LEFT JOIN dbo.ESTIMATE_COMPONENT AS ec 
		ON ea.EST_COMPONENT_NBR = ec.EST_COMPONENT_NBR 
		AND ea.ESTIMATE_NUMBER = ec.ESTIMATE_NUMBER 
	LEFT JOIN dbo.ESTIMATE_REV AS er 
		ON ea.EST_REVISION_NBR = er.EST_REV_NBR 
		AND ea.EST_QUOTE_NBR = er.EST_QUOTE_NBR 
		AND ea.EST_COMPONENT_NBR = er.EST_COMPONENT_NBR 
		AND ea.ESTIMATE_NUMBER = er.ESTIMATE_NUMBER
	LEFT JOIN dbo.ESTIMATE_QUOTE AS eq 
		ON ea.EST_QUOTE_NBR = eq.EST_QUOTE_NBR 
		AND ea.EST_COMPONENT_NBR = eq.EST_COMPONENT_NBR 
		AND ea.ESTIMATE_NUMBER = eq.ESTIMATE_NUMBER
	LEFT JOIN dbo.EMPLOYEE e
		ON jc.EMP_CODE = e.EMP_CODE
	LEFT JOIN dbo.MARKET mk
		ON jc.MARKET_CODE = mk.MARKET_CODE

GO

