--insert the next (3) statements at the top of the script while debugging
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[V_MEDIA_CURRENT_STATUS_SUM]') AND OBJECTPROPERTY(id, N'IsView') = 1)
	DROP VIEW [dbo].[V_MEDIA_CURRENT_STATUS_SUM]
GO

CREATE VIEW [dbo].[V_MEDIA_CURRENT_STATUS_SUM]

-- V_MEDIA_CURRENT_STATUS_SUM
-- #00 08/20/12 - initial version (used #05 02/20/13 MCS view as base)

AS

--For all print entries where info is by order/line number
SELECT     
	  dbo.MEDIA_ORDER_HEADER.USER_ID AS [User Code], 
	  dbo.MEDIA_ORDER_HEADER.TYPE AS [Order Type], 
	  dbo.MEDIA_ORDER_HEADER.ORDER_NBR AS [Order Number], 
	  dbo.MEDIA_ORDER_HEADER.REV_NBR AS [Revision Number], 
	  dbo.MEDIA_ORDER_HEADER.OFFICE_CODE AS [Office Code], 
	  dbo.OFFICE.OFFICE_NAME AS [Office Name],
	  dbo.MEDIA_ORDER_HEADER.CL_CODE AS [Client Code], 
	  dbo.CLIENT.CL_NAME AS [Client Name],
	  dbo.MEDIA_ORDER_HEADER.DIV_CODE AS [Division Code],
	  dbo.DIVISION.DIV_NAME AS [Division Name], 
	  dbo.MEDIA_ORDER_HEADER.PRD_CODE AS [Product Code],
	  dbo.PRODUCT.PRD_DESCRIPTION AS [Product Description],  
	  dbo.MEDIA_ORDER_HEADER.ORDER_DESC AS [Order Description], 
	  dbo.MEDIA_ORDER_HEADER.ORDER_COMMENT AS [Order Comment], 
	  dbo.MEDIA_ORDER_HEADER.VN_CODE AS [Vendor Code],
	  dbo.VENDOR.VN_NAME AS [Vendor Name], 
	  dbo.MEDIA_ORDER_HEADER.VR_CODE AS [Vendor Rep Code], 
	  ISNULL(dbo.VEN_REP.VR_FNAME,'') + ' ' + ISNULL(dbo.VEN_REP.VR_LNAME,'') AS [Vendor Rep Name],
	  dbo.MEDIA_ORDER_HEADER.VR_CODE2 AS [Vendor Rep Code2],
	  ISNULL(vr2.VR_FNAME,'') + ' ' + ISNULL(vr2.VR_LNAME,'') AS [Vendor Rep Name2], 
	  dbo.MEDIA_ORDER_HEADER.CMP_CODE AS [Campaign Code], 
	  dbo.MEDIA_ORDER_HEADER.CMP_IDENTIFIER AS [Campaign ID], 
	  dbo.MEDIA_ORDER_HEADER.CMP_NAME AS [Campaign Name], 
	  dbo.MEDIA_ORDER_HEADER.MEDIA_TYPE AS [Media Type], 
	  dbo.MEDIA_ORDER_HEADER.POST_BILL AS [Post Bill Flag], 
	  dbo.MEDIA_ORDER_HEADER.NET_GROSS AS [Net Gross Flag], 
	  dbo.MEDIA_ORDER_HEADER.MARKET_CODE AS [Market Code], 
	  dbo.MEDIA_ORDER_HEADER.MARKET_DESC AS [Market Description], 
	  dbo.MEDIA_ORDER_HEADER.ORDER_DATE AS [Order Date], 
	  dbo.MEDIA_ORDER_HEADER.FLIGHT_FROM AS [Order Flight From], 
	  dbo.MEDIA_ORDER_HEADER.FLIGHT_TO AS [Order Flight To], 
	  dbo.MEDIA_ORDER_HEADER.ORD_PROCESS_CONTRL AS [Order Process Control], 
	  dbo.MEDIA_ORDER_HEADER.BUYER AS [Buyer], 
	  dbo.MEDIA_ORDER_HEADER.CLIENT_PO AS [Client PO], 
	  dbo.MEDIA_ORDER_HEADER.LINK_ID AS [Link ID], 
	  dbo.MEDIA_ORDER_HEADER.ORDER_ACCEPTED AS [Order Accepted], 
	  CASE dbo.MEDIA_ORDER_HEADER.ADVAN_TYPE
		WHEN 1 THEN 0
		ELSE dbo.MEDIA_ORDER_DETAIL.LINE_NBR
	  END AS [Line Number], 
	  --dbo.MEDIA_ORDER_DETAIL.REV_NBR AS [Line Revision Number],
	  --dbo.MEDIA_ORDER_DETAIL.SEQ_NBR AS [Line Sequence Number], 
	  'PRN' AS [Order Date Type],
	  --COALESCE(dbo.MEDIA_ORDER_DETAIL.[YEAR],d.[YEAR]) * 100 +
			--COALESCE(dbo.MEDIA_ORDER_DETAIL.[MONTH],d.[MONTH])AS [Order Period], 
	  d.[YEAR] * 100 + d.[MONTH]AS [Order Period],	
	  CASE d.[MONTH]
	  		WHEN 1 THEN 'Jan'
			WHEN 2 THEN 'Feb'
			WHEN 3 THEN 'Mar'
			WHEN 4 THEN 'Apr'
			WHEN 5 THEN 'May'
			WHEN 6 THEN 'Jun'
			WHEN 7 THEN 'Jul'
			WHEN 8 THEN 'Aug'
			WHEN 9 THEN 'Sep'
			WHEN 10 THEN 'Oct'
			WHEN 11 THEN 'Nov'
			WHEN 12 THEN 'Dec'	  
	  END AS [Order Month], 
	  d.[YEAR] AS [Order year], 
	  dbo.MEDIA_ORDER_DETAIL.INSERT_DATE [Insertion Date], 
	  dbo.MEDIA_ORDER_DETAIL.END_DATE AS [Order End Date], 
	  dbo.MEDIA_ORDER_DETAIL.DATE_TO_BILL AS [Date To Bill], 
	  dbo.MEDIA_ORDER_DETAIL.CLOSE_DATE AS [Close Date], 
	  dbo.MEDIA_ORDER_DETAIL.MATL_CLOSE_DATE AS [Material Close Date], 
	  dbo.MEDIA_ORDER_DETAIL.LINE_DESC AS [Line Description], 
	  dbo.MEDIA_ORDER_DETAIL.AD_SIZE AS [Ad Size], 
	  dbo.MEDIA_ORDER_DETAIL.EDITION_ISSUE AS [Edition Issue], 
	  dbo.MEDIA_ORDER_DETAIL.SECTION AS [Section], 
	  dbo.MEDIA_ORDER_DETAIL.MATERIAL AS [Material], 
	  dbo.MEDIA_ORDER_DETAIL.REMARKS AS [Remarks], 
	  dbo.MEDIA_ORDER_DETAIL.URL AS [URL], 
	  dbo.MEDIA_ORDER_DETAIL.COPY_AREA AS [Copy Area], 
	  dbo.MEDIA_ORDER_DETAIL.MATL_NOTES AS [Material Notes], 
	  dbo.MEDIA_ORDER_DETAIL.POSITION_INFO AS [Position Info], 
	  dbo.MEDIA_ORDER_DETAIL.MISC_INFO AS [Miscellaneous Info], 
	  dbo.MEDIA_ORDER_DETAIL.JOB_NUMBER AS [Job Number], 
	  dbo.JOB_LOG.JOB_DESC AS [Job Description],
	  dbo.MEDIA_ORDER_DETAIL.JOB_COMPONENT_NBR AS [Job Component Number], 
	  dbo.JOB_COMPONENT.JOB_COMP_DESC AS [Job Component Description],
	  dbo.MEDIA_ORDER_DETAIL.COST_TYPE AS [Cost Type], 
	  dbo.MEDIA_ORDER_DETAIL.RATE_TYPE AS [Rate Type], 
	  dbo.MEDIA_ORDER_DETAIL.PRINT_LINES AS [Print Quantity], 
	  dbo.MEDIA_ORDER_DETAIL.GUARANTEED_IMPRESS AS [Guaranteed Impressions],
	  dbo.MEDIA_ORDER_DETAIL.LINK_ID AS [Line Link ID], 
	  d.ORDER_TYPE AS [Order Entry Type],
	 -- CASE d.REC_TYPE
		--WHEN 'O' THEN 'ORDER'
		--WHEN 'B' THEN 'BILLING'
		--WHEN 'A' THEN 'AP'
	 -- END AS [Record Type],
	  --d.SPOTS AS [Spots],  
	  d.EXT_NET_AMT AS [Extended Net Amount], 
	  d.NETCHARGES AS [Net Charge Amount], 
	  d.DISCOUNTS AS [Discount Amount], 
	  d.ADDL_CHARGE AS [Additional Charge Amount], 
	  d.COMM_AMT AS [Commission Amount], 
	  d.REBATE_AMT AS [Rebate Amount], 
	  d.VENDOR_TAX AS [Vendor Tax Amount], 
	  d.RESALE_TAX AS [Resale Tax Amount], 
	  d.LINE_TOTAL AS [Line Total Amount], 
	  d.NET_TOTAL_AMT AS [Net Total Amount], 
	  d.VENDOR_NET_AMT AS [Vendor Net Amount],
	  d.BILL_AMT AS [Bill Amount], 
	  d.RECNB_BILL_AMT AS [Reconcile No_Bill Bill Amount], 
	  d.RECNB_NET_AMT AS [Reconcile No_BILL Net Amount], 
	  d.SPOTS_QTY AS [Spots Quantity],				
	  --d.NON_BILL_FLAG AS [Non_billable Flag], 
	  --d.LINE_CANCELLED AS [Line Cancelled], 
	  --d.BILL_TYPE_FLAG AS [Bill Type Flag],
	  d.BILLED_EXT_NET_AMT AS [Billed Extended Net Amount], 
	  d.BILLED_DISC_AMT AS [Billed Discount Amount], 
	  d.BILLED_NC_AMT AS [Billed Net Charge Amount], 
	  d.BILLED_VTAX_AMT AS [Billed Vendor Tax Amount], 
	  d.BILLED_NET_AMT AS [Billed Net Amount], 
	  d.BILLED_ADDL_CHARGE AS [Billed Additional Charge Amount], 
	  d.BILLED_COMM_AMT AS [Billed Commission Amount], 
	  d.BILLED_REBATE_AMT AS [Billed Rebate Amount], 
	  d.BILLED_RTAX_AMT AS [Billed Resale Tax Amount], 
	  d.BILLED_BILL_AMT AS [Billed Bill Amount],
	  d.BILLED_SPOTS_QTY AS [Billed Spots Quantity],		
	  --d.AR_INV_NBR AS [Invoice Number], 
	  --d.AR_SEQ AS [Invoice Sequence Number], 
	  --d.AR_TYPE AS [Invoice Type], 
	  --d.GLXACT_BILL AS [GL Billing Trans Number],			
	  d.AP_NET_AMT AS [AP Net Amount], 
	  d.AP_NETCHARGES_AMT AS [AP Net Charge Amount], 
	  d.AP_DISC_AMT_AMT AS [AP Discount Amount], 
	  d.AP_COMM_AMT AS [AP Commission Amount], 
	  d.AP_REBATE_AMT AS [AP Rebate Amount], 
	  d.AP_VTAX_AMT AS [AP Vendor Tax Amount], 
	  d.AP_RTAX_AMT AS [AP Resale Tax Amount], 
	  d.AP_BILL_AMT AS [AP Bill Amount], 
	  d.AP_LINE_TOTAL AS [AP Line Total],
	  d.AP_SPOTS_QTY AS [AP Spots Quantity]		
	  --d.AP_INV_NBR AS [AP Invoice Number], 
	  --d.GLXACT_AP AS [AP GL Trans Number]			
FROM  dbo.MEDIA_ORDER_HEADER 
INNER JOIN dbo.MEDIA_ORDER_DETAIL 
	ON dbo.MEDIA_ORDER_HEADER.[USER_ID] = dbo.MEDIA_ORDER_DETAIL.[USER_ID]
	AND dbo.MEDIA_ORDER_HEADER.ORDER_NBR = dbo.MEDIA_ORDER_DETAIL.ORDER_NBR 
INNER JOIN dbo.V_MEDIA_ORDER_AMOUNTS_SUM AS d
	ON dbo.MEDIA_ORDER_HEADER.[USER_ID] = d.[USER_ID]
	AND dbo.MEDIA_ORDER_DETAIL.ORDER_NBR = d.ORDER_NBR 
	AND dbo.MEDIA_ORDER_DETAIL.LINE_NBR = d.LINE_NBR
JOIN dbo.OFFICE
	ON dbo.MEDIA_ORDER_HEADER.OFFICE_CODE = dbo.OFFICE.OFFICE_CODE
INNER JOIN dbo.CLIENT
	ON dbo.MEDIA_ORDER_HEADER.CL_CODE = dbo.CLIENT.CL_CODE	
INNER JOIN dbo.DIVISION
	ON dbo.MEDIA_ORDER_HEADER.CL_CODE = dbo.DIVISION.CL_CODE	
	AND dbo.MEDIA_ORDER_HEADER.DIV_CODE = dbo.DIVISION.DIV_CODE
INNER JOIN dbo.PRODUCT
	ON dbo.MEDIA_ORDER_HEADER.CL_CODE = dbo.PRODUCT.CL_CODE	
	AND dbo.MEDIA_ORDER_HEADER.DIV_CODE = dbo.PRODUCT.DIV_CODE
	AND dbo.MEDIA_ORDER_HEADER.PRD_CODE = dbo.PRODUCT.PRD_CODE
INNER JOIN dbo.VENDOR
	ON dbo.MEDIA_ORDER_HEADER.VN_CODE = dbo.VENDOR.VN_CODE
LEFT JOIN dbo.VEN_REP
	ON dbo.MEDIA_ORDER_HEADER.VN_CODE = dbo.VEN_REP.VN_CODE
	AND dbo.MEDIA_ORDER_HEADER.VR_CODE = dbo.VEN_REP.VR_CODE
LEFT JOIN dbo.VEN_REP AS vr2
	ON dbo.MEDIA_ORDER_HEADER.VN_CODE = vr2.VN_CODE
	AND dbo.MEDIA_ORDER_HEADER.VR_CODE = vr2.VR_CODE	
LEFT JOIN dbo.JOB_LOG
	ON dbo.MEDIA_ORDER_DETAIL.JOB_NUMBER = dbo.JOB_LOG.JOB_NUMBER
LEFT JOIN dbo.JOB_COMPONENT
	ON dbo.MEDIA_ORDER_DETAIL.JOB_NUMBER = dbo.JOB_COMPONENT.JOB_NUMBER
	AND dbo.MEDIA_ORDER_DETAIL.JOB_COMPONENT_NBR = dbo.JOB_COMPONENT.JOB_COMPONENT_NBR
WHERE dbo.MEDIA_ORDER_HEADER.[USER_ID] = dbo.fn_AdvanUser()
	--AND (dbo.MEDIA_ORDER_HEADER.ADVAN_TYPE = 2	
	--OR (dbo.MEDIA_ORDER_HEADER.ADVAN_TYPE = 1 AND d.REC_TYPE <> 'A'  ))	
	AND dbo.MEDIA_ORDER_HEADER.[TYPE] NOT IN('RADIO', 'TV')
	
--***************************************************************************************
--For all bcst where summary is by order number (no line number)
UNION ALL SELECT  
	  dbo.MEDIA_ORDER_HEADER.[USER_ID], 
	  dbo.MEDIA_ORDER_HEADER.[TYPE], 
	  dbo.MEDIA_ORDER_HEADER.ORDER_NBR, 
	  dbo.MEDIA_ORDER_HEADER.REV_NBR, 
	  dbo.MEDIA_ORDER_HEADER.OFFICE_CODE, 
	  dbo.OFFICE.OFFICE_NAME, 
	  dbo.MEDIA_ORDER_HEADER.CL_CODE,  
	  dbo.CLIENT.CL_NAME,
	  dbo.MEDIA_ORDER_HEADER.DIV_CODE, 
	  dbo.DIVISION.DIV_NAME,
	  dbo.MEDIA_ORDER_HEADER.PRD_CODE,
	  dbo.PRODUCT.PRD_DESCRIPTION,  
	  dbo.MEDIA_ORDER_HEADER.ORDER_DESC, 
	  dbo.MEDIA_ORDER_HEADER.ORDER_COMMENT, 
	  dbo.MEDIA_ORDER_HEADER.VN_CODE,
	  dbo.VENDOR.VN_NAME, 
	  dbo.MEDIA_ORDER_HEADER.VR_CODE, 
	  ISNULL(dbo.VEN_REP.VR_FNAME,'') + ' ' + ISNULL(dbo.VEN_REP.VR_LNAME,''), 
	  dbo.MEDIA_ORDER_HEADER.VR_CODE2, 
	  ISNULL(vr2.VR_FNAME,'') + ' ' + ISNULL(vr2.VR_LNAME,''),
	  dbo.MEDIA_ORDER_HEADER.CMP_CODE, 
	  dbo.MEDIA_ORDER_HEADER.CMP_IDENTIFIER, 
	  dbo.MEDIA_ORDER_HEADER.CMP_NAME, 
	  dbo.MEDIA_ORDER_HEADER.MEDIA_TYPE, 
	  dbo.MEDIA_ORDER_HEADER.POST_BILL, 
	  dbo.MEDIA_ORDER_HEADER.NET_GROSS, 
	  dbo.MEDIA_ORDER_HEADER.MARKET_CODE, 
	  dbo.MEDIA_ORDER_HEADER.MARKET_DESC, 
	  dbo.MEDIA_ORDER_HEADER.ORDER_DATE, 
	  dbo.MEDIA_ORDER_HEADER.FLIGHT_FROM, 
	  dbo.MEDIA_ORDER_HEADER.FLIGHT_TO, 
	  dbo.MEDIA_ORDER_HEADER.ORD_PROCESS_CONTRL, 
	  dbo.MEDIA_ORDER_HEADER.BUYER, 
	  dbo.MEDIA_ORDER_HEADER.CLIENT_PO, 
	  dbo.MEDIA_ORDER_HEADER.LINK_ID, 
	  dbo.MEDIA_ORDER_HEADER.ORDER_ACCEPTED, 
	  NULL,		--dbo.MEDIA_ORDER_DETAIL.LINE_NBR, 
	  --0,		--dbo.MEDIA_ORDER_DETAIL.REV_NBR AS LINE_REV_NBR,
	  --0,		--dbo.MEDIA_ORDER_DETAIL.SEQ_NBR, 
	  'BRD',	--dbo.MEDIA_ORDER_DETAIL.DATE_TYPE,
	  d.[YEAR] * 100 + d.[MONTH], 
	  CASE d.[MONTH]
			WHEN 1 THEN 'Jan'
			WHEN 2 THEN 'Feb'
			WHEN 3 THEN 'Mar'
			WHEN 4 THEN 'Apr'
			WHEN 5 THEN 'May'
			WHEN 6 THEN 'Jun'
			WHEN 7 THEN 'Jul'
			WHEN 8 THEN 'Aug'
			WHEN 9 THEN 'Sep'
			WHEN 10 THEN 'Oct'
			WHEN 11 THEN 'Nov'
			WHEN 12 THEN 'Dec'	  
	  END, 
	  d.[YEAR], 
	  NULL,   --dbo.MEDIA_ORDER_DETAIL.INSERT_DATE, 
	  NULL,   --dbo.MEDIA_ORDER_DETAIL.END_DATE, 
	  NULL,   --dbo.MEDIA_ORDER_DETAIL.DATE_TO_BILL, 
	  NULL,   --dbo.MEDIA_ORDER_DETAIL.CLOSE_DATE, 
	  NULL,   --dbo.MEDIA_ORDER_DETAIL.MATL_CLOSE_DATE, 
	  NULL,   --dbo.MEDIA_ORDER_DETAIL.LINE_DESC, 
	  NULL,   --dbo.MEDIA_ORDER_DETAIL.AD_SIZE, 
	  NULL,   --dbo.MEDIA_ORDER_DETAIL.EDITION_ISSUE, 
	  NULL,   --dbo.MEDIA_ORDER_DETAIL.SECTION, 
	  NULL,   --dbo.MEDIA_ORDER_DETAIL.MATERIAL, 
	  NULL,   --dbo.MEDIA_ORDER_DETAIL.REMARKS, 
	  NULL,   --dbo.MEDIA_ORDER_DETAIL.URL, 
	  NULL,   --dbo.MEDIA_ORDER_DETAIL.COPY_AREA, 
	  NULL,   --dbo.MEDIA_ORDER_DETAIL.MATL_NOTES, 
	  NULL,   --dbo.MEDIA_ORDER_DETAIL.POSITION_INFO, 
	  NULL,   --dbo.MEDIA_ORDER_DETAIL.MISC_INFO, 
	  NULL,   --dbo.MEDIA_ORDER_DETAIL.JOB_NUMBER,
	  NULL,   --dbo.JOB_LOG.JOB_DESC, 
	  NULL,   --dbo.MEDIA_ORDER_DETAIL.JOB_COMPONENT_NBR, 
	  NULL,   --dbo.JOB_COMPONENT.JOB_COMP_DESC,
	  NULL,   --dbo.MEDIA_ORDER_DETAIL.COST_TYPE, 
	  NULL,   --dbo.MEDIA_ORDER_DETAIL.RATE_TYPE, 
	  NULL,   --dbo.MEDIA_ORDER_DETAIL.PRINT_LINES, 
	  NULL,   --dbo.MEDIA_ORDER_DETAIL.GUARANTEED_IMPRESS, 
	  NULL,   --dbo.MEDIA_ORDER_DETAIL.LINK_ID AS LINE_LINK_ID, 
	  d.ORDER_TYPE,
	 -- CASE d.REC_TYPE
		--WHEN 'O' THEN 'ORDER'
		--WHEN 'B' THEN 'BILLING'
		--WHEN 'A' THEN 'AP'
	 -- END AS REC_TYPE,
	  --d.SPOTS,  
	  d.EXT_NET_AMT, 
	  d.NETCHARGES, 
	  d.DISCOUNTS, 
	  d.ADDL_CHARGE, 
	  d.COMM_AMT, 
	  d.REBATE_AMT, 
	  d.VENDOR_TAX, 
	  d.RESALE_TAX, 
	  d.LINE_TOTAL, 
	  d.NET_TOTAL_AMT, 
	  d.VENDOR_NET_AMT, 
	  d.BILL_AMT, 
	  d.RECNB_BILL_AMT, 
	  d.RECNB_NET_AMT,
	  d.SPOTS_QTY,			
	  --d.NON_BILL_FLAG, 
	  --d.LINE_CANCELLED, 
	  --d.BILL_TYPE_FLAG, 
	  d.BILLED_EXT_NET_AMT, 
	  d.BILLED_DISC_AMT, 
	  d.BILLED_NC_AMT, 
	  d.BILLED_VTAX_AMT, 
	  d.BILLED_NET_AMT, 
	  d.BILLED_ADDL_CHARGE, 
	  d.BILLED_COMM_AMT, 
	  d.BILLED_REBATE_AMT, 
	  d.BILLED_RTAX_AMT, 
	  d.BILLED_BILL_AMT,
	  d.BILLED_SPOTS_QTY,			 
	  --d.AR_INV_NBR, 
	  --d.AR_SEQ, 
	  --d.AR_TYPE, 
	  --d.GLXACT_BILL, 
	  d.AP_NET_AMT, 
	  d.AP_NETCHARGES_AMT, 
	  d.AP_DISC_AMT_AMT, 
	  d.AP_COMM_AMT, 
	  d.AP_REBATE_AMT, 
	  d.AP_VTAX_AMT, 
	  d.AP_RTAX_AMT, 
	  d.AP_BILL_AMT, 
	  d.AP_LINE_TOTAL,	  
	  d.AP_SPOTS_QTY		 
	  --NULL,		--d.AP_INV_NBR,	--set to NULL, was tripping error
	  --d.GLXACT_AP	  
FROM  dbo.MEDIA_ORDER_HEADER 
INNER JOIN dbo.V_MEDIA_ORDER_AMOUNTS_SUM AS d
	ON dbo.MEDIA_ORDER_HEADER.[USER_ID] = d.[USER_ID]
	AND dbo.MEDIA_ORDER_HEADER.ORDER_NBR = d.ORDER_NBR 
JOIN dbo.OFFICE
	ON dbo.MEDIA_ORDER_HEADER.OFFICE_CODE = dbo.OFFICE.OFFICE_CODE
INNER JOIN dbo.CLIENT
	ON dbo.MEDIA_ORDER_HEADER.CL_CODE = dbo.CLIENT.CL_CODE	
INNER JOIN dbo.DIVISION
	ON dbo.MEDIA_ORDER_HEADER.CL_CODE = dbo.DIVISION.CL_CODE	
	AND dbo.MEDIA_ORDER_HEADER.DIV_CODE = dbo.DIVISION.DIV_CODE
INNER JOIN dbo.PRODUCT
	ON dbo.MEDIA_ORDER_HEADER.CL_CODE = dbo.PRODUCT.CL_CODE	
	AND dbo.MEDIA_ORDER_HEADER.DIV_CODE = dbo.PRODUCT.DIV_CODE
	AND dbo.MEDIA_ORDER_HEADER.PRD_CODE = dbo.PRODUCT.PRD_CODE
INNER JOIN dbo.VENDOR
	ON dbo.MEDIA_ORDER_HEADER.VN_CODE = dbo.VENDOR.VN_CODE
LEFT JOIN dbo.VEN_REP
	ON dbo.MEDIA_ORDER_HEADER.VN_CODE = dbo.VEN_REP.VN_CODE
	AND dbo.MEDIA_ORDER_HEADER.VR_CODE = dbo.VEN_REP.VR_CODE
LEFT JOIN dbo.VEN_REP AS vr2
	ON dbo.MEDIA_ORDER_HEADER.VN_CODE = vr2.VN_CODE
	AND dbo.MEDIA_ORDER_HEADER.VR_CODE = vr2.VR_CODE	
--LEFT JOIN dbo.JOB_LOG
--	ON dbo.MEDIA_ORDER_DETAIL.JOB_NUMBER = dbo.JOB_LOG.JOB_NUMBER
--LEFT JOIN dbo.JOB_COMPONENT
--	ON dbo.MEDIA_ORDER_DETAIL.JOB_NUMBER = dbo.JOB_COMPONENT.JOB_NUMBER
--	AND dbo.MEDIA_ORDER_DETAIL.JOB_COMPONENT_NBR = dbo.JOB_COMPONENT.JOB_COMPONENT_NBR
WHERE dbo.MEDIA_ORDER_HEADER.[USER_ID] = dbo.fn_AdvanUser()
	--AND dbo.MEDIA_ORDER_HEADER.ADVAN_TYPE = 1	
	--AND d.REC_TYPE = 'A'  
	AND dbo.MEDIA_ORDER_HEADER.[TYPE] IN('RADIO', 'TV')

GO

IF ( @@ERROR = 0 )
	GRANT SELECT ON [V_MEDIA_CURRENT_STATUS_SUM] TO PUBLIC AS dbo
GO	


