CREATE VIEW [dbo].[V_ORDER_DOCUMENT]
WITH SCHEMABINDING
AS

	SELECT 
		AOD.DOCUMENT_ID,
		AOD.ORDER_NBR,
		AOD.[MEDIA_TYPE] 
	FROM
		(SELECT 
				MD.DOCUMENT_ID,
				MD.ORDER_NBR,
				[MEDIA_TYPE] = 'M'
			FROM
				[dbo].[MAGAZINE_DOCUMENT] AS MD
		
		UNION ALL
		
		SELECT 
				ND.DOCUMENT_ID,
				ND.ORDER_NBR,
				[MEDIA_TYPE] = 'N'
			FROM
				[dbo].[NEWSPAPER_DOCUMENT] AS ND
		
		UNION ALL
		
		SELECT 
				ID.DOCUMENT_ID,
				ID.ORDER_NBR,
				[MEDIA_TYPE] = 'I'
			FROM
				[dbo].[INTERNET_DOCUMENT] AS ID
		
		UNION ALL
		
		SELECT 
				OD.DOCUMENT_ID,
				OD.ORDER_NBR,
				[MEDIA_TYPE] = 'O'
			FROM
				[dbo].[OUTDOOR_DOCUMENT] AS OD
		
		UNION ALL
		
		SELECT 
				RD.DOCUMENT_ID,
				RD.ORDER_NBR,
				[MEDIA_TYPE] = 'R'
			FROM
				[dbo].[RADIO_DOCUMENT] AS RD
		
		UNION ALL
		
		SELECT 
				TD.DOCUMENT_ID,
				TD.ORDER_NBR,
				[MEDIA_TYPE] = 'T'
			FROM
				[dbo].[TV_DOCUMENT] AS TD) AS AOD


GO