
CREATE VIEW dbo.V_RADIO_DETAIL1(ORDER_NBR, LINE_NBR, REV_NBR, SEQ_NBR, BRDCAST_PER, BRDCAST_YEAR, MONTH_IND, MONTH_SHORT, LINE_NET, COMM_AMT, 
                      REBATE_AMT, DISCOUNT, VENDOR_TAX, STATE_TAX, COUNTY_TAX, CITY_TAX, SPOTS, BILLING_AMT, AR_INV_NBR, AR_TYPE, AR_INV_SEQ, 
                      BILLING_USER, RECONCILE_LINE, MEDIA_TYPE, DO_NOT_BILL, LINE_CANCELLED ) 
AS

SELECT     ORDER_NBR, LINE_NBR, REV_NBR, SEQ_NBR, BRDCAST_YEAR * 100 + 1, BRDCAST_YEAR, 1 AS MONTH_IND, 'JAN' AS MONTH_SHORT, JAN_LINE_NET, JAN_COMM_AMT, 
                JAN_REBATE_AMT, JAN_DISCOUNT, JAN_VENDOR_TAX, JAN_STATE_TAX, JAN_COUNTY_TAX, JAN_CITY_TAX, JAN_SPOTS, JAN_BILLING_AMT, 
                JAN_AR_INV_NBR, JAN_AR_TYPE, JAN_AR_INV_SEQ, BILLING_USER, RECONCILE_LINE, 'RADIO' AS MEDIA_TYPE, DO_NOT_BILL, LINE_CANCELLED
FROM         dbo.RADIO_DETAIL1 AS RADIO_DETAIL_12
WHERE		ABS(ISNULL(JAN_LINE_NET,0)) + ABS(ISNULL(JAN_COMM_AMT,0)) + ABS(ISNULL(JAN_REBATE_AMT,0)) + ABS(ISNULL(JAN_DISCOUNT,0)) 
				+ ABS(ISNULL(JAN_VENDOR_TAX,0)) + ABS(ISNULL(JAN_STATE_TAX,0)) + ABS(ISNULL(JAN_COUNTY_TAX,0)) + ABS(ISNULL(JAN_CITY_TAX,0)) 
				+ ABS(ISNULL(JAN_SPOTS,0)) + ABS(ISNULL(JAN_BILLING_AMT,0)) <> 0
UNION ALL
SELECT     ORDER_NBR, LINE_NBR, REV_NBR, SEQ_NBR, BRDCAST_YEAR * 100 + 2, BRDCAST_YEAR, 2 AS MONTH_IND, 'FEB' AS MONTH_SHORT, FEB_LINE_NET, FEB_COMM_AMT, 
                      FEB_REBATE_AMT, FEB_DISCOUNT, FEB_VENDOR_TAX, FEB_STATE_TAX, FEB_COUNTY_TAX, FEB_CITY_TAX, FEB_SPOTS, FEB_BILLING_AMT, 
                      FEB_AR_INV_NBR, FEB_AR_TYPE, FEB_AR_INV_SEQ, BILLING_USER, RECONCILE_LINE, 'RADIO' AS MEDIA_TYPE, DO_NOT_BILL, 
                      LINE_CANCELLED
FROM         dbo.RADIO_DETAIL1 AS RADIO_DETAIL1_11
WHERE		ABS(ISNULL(FEB_LINE_NET,0)) + ABS(ISNULL(FEB_COMM_AMT,0)) + ABS(ISNULL(FEB_REBATE_AMT,0)) + ABS(ISNULL(FEB_DISCOUNT,0)) 
				+ ABS(ISNULL(FEB_VENDOR_TAX,0)) + ABS(ISNULL(FEB_STATE_TAX,0)) + ABS(ISNULL(FEB_COUNTY_TAX,0)) + ABS(ISNULL(FEB_CITY_TAX,0)) 
				+ ABS(ISNULL(FEB_SPOTS,0)) + ABS(ISNULL(FEB_BILLING_AMT,0)) <> 0
UNION ALL
SELECT     ORDER_NBR, LINE_NBR, REV_NBR, SEQ_NBR, BRDCAST_YEAR * 100 + 3, BRDCAST_YEAR, 3 AS MONTH_IND, 'MAR' AS MONTH_SHORT, MAR_LINE_NET, MAR_COMM_AMT, 
                      MAR_REBATE_AMT, MAR_DISCOUNT, MAR_VENDOR_TAX, MAR_STATE_TAX, MAR_COUNTY_TAX, MAR_CITY_TAX, MAR_SPOTS, MAR_BILLING_AMT, 
                      MAR_AR_INV_NBR, MAR_AR_TYPE, MAR_AR_INV_SEQ, BILLING_USER, RECONCILE_LINE, 'RADIO' AS MEDIA_TYPE, DO_NOT_BILL, 
                      LINE_CANCELLED
FROM         dbo.RADIO_DETAIL1 AS RADIO_DETAIL1_10
WHERE		ABS(ISNULL(MAR_LINE_NET,0)) + ABS(ISNULL(MAR_COMM_AMT,0)) + ABS(ISNULL(MAR_REBATE_AMT,0)) + ABS(ISNULL(MAR_DISCOUNT,0)) 
				+ ABS(ISNULL(MAR_VENDOR_TAX,0)) + ABS(ISNULL(MAR_STATE_TAX,0)) + ABS(ISNULL(MAR_COUNTY_TAX,0)) + ABS(ISNULL(MAR_CITY_TAX,0)) 
				+ ABS(ISNULL(MAR_SPOTS,0)) + ABS(ISNULL(MAR_BILLING_AMT,0)) <> 0
UNION ALL
SELECT     ORDER_NBR, LINE_NBR, REV_NBR, SEQ_NBR, BRDCAST_YEAR * 100 + 4, BRDCAST_YEAR, 4 AS MONTH_IND, 'APR' AS MONTH_SHORT, APR_LINE_NET, APR_COMM_AMT, 
                      APR_REBATE_AMT, APR_DISCOUNT, APR_VENDOR_TAX, APR_STATE_TAX, APR_COUNTY_TAX, APR_CITY_TAX, APR_SPOTS, APR_BILLING_AMT, 
                      APR_AR_INV_NBR, APR_AR_TYPE, APR_AR_INV_SEQ, BILLING_USER, RECONCILE_LINE, 'RADIO' AS MEDIA_TYPE, DO_NOT_BILL, 
                      LINE_CANCELLED
FROM         dbo.RADIO_DETAIL1 AS RADIO_DETAIL1_9
WHERE		ABS(ISNULL(APR_LINE_NET,0)) + ABS(ISNULL(APR_COMM_AMT,0)) + ABS(ISNULL(APR_REBATE_AMT,0)) + ABS(ISNULL(APR_DISCOUNT,0)) 
				+ ABS(ISNULL(APR_VENDOR_TAX,0)) + ABS(ISNULL(APR_STATE_TAX,0)) + ABS(ISNULL(APR_COUNTY_TAX,0)) + ABS(ISNULL(APR_CITY_TAX,0)) 
				+ ABS(ISNULL(APR_SPOTS,0)) + ABS(ISNULL(APR_BILLING_AMT,0)) <> 0
UNION ALL
SELECT     ORDER_NBR, LINE_NBR, REV_NBR, SEQ_NBR, BRDCAST_YEAR * 100 + 5, BRDCAST_YEAR, 5 AS MONTH_IND, 'MAY' AS MONTH_SHORT, MAY_LINE_NET, MAY_COMM_AMT, 
                      MAY_REBATE_AMT, MAY_DISCOUNT, MAY_VENDOR_TAX, MAY_STATE_TAX, MAY_COUNTY_TAX, MAY_CITY_TAX, MAY_SPOTS, MAY_BILLING_AMT, 
                      MAY_AR_INV_NBR, MAY_AR_TYPE, MAY_AR_INV_SEQ, BILLING_USER, RECONCILE_LINE, 'RADIO' AS MEDIA_TYPE, DO_NOT_BILL, 
                      LINE_CANCELLED
FROM         dbo.RADIO_DETAIL1 AS RADIO_DETAIL1_8
WHERE		ABS(ISNULL(MAY_LINE_NET,0)) + ABS(ISNULL(MAY_COMM_AMT,0)) + ABS(ISNULL(MAY_REBATE_AMT,0)) + ABS(ISNULL(MAY_DISCOUNT,0)) 
				+ ABS(ISNULL(MAY_VENDOR_TAX,0)) + ABS(ISNULL(MAY_STATE_TAX,0)) + ABS(ISNULL(MAY_COUNTY_TAX,0)) + ABS(ISNULL(MAY_CITY_TAX,0)) 
				+ ABS(ISNULL(MAY_SPOTS,0)) + ABS(ISNULL(MAY_BILLING_AMT,0)) <> 0
UNION ALL
SELECT     ORDER_NBR, LINE_NBR, REV_NBR, SEQ_NBR, BRDCAST_YEAR * 100 + 6, BRDCAST_YEAR, 6 AS MONTH_IND, 'JUN' AS MONTH_SHORT, JUN_LINE_NET, JUN_COMM_AMT, 
                      JUN_REBATE_AMT, JUN_DISCOUNT, JUN_VENDOR_TAX, JUN_STATE_TAX, JUN_COUNTY_TAX, JUN_CITY_TAX, JUN_SPOTS, JUN_BILLING_AMT, 
                      JUN_AR_INV_NBR, JUN_AR_TYPE, JUN_AR_INV_SEQ, BILLING_USER, RECONCILE_LINE, 'RADIO' AS MEDIA_TYPE, DO_NOT_BILL, 
                      LINE_CANCELLED
FROM         dbo.RADIO_DETAIL1 AS RADIO_DETAIL1_7
WHERE		ABS(ISNULL(JUN_LINE_NET,0)) + ABS(ISNULL(JUN_COMM_AMT,0)) + ABS(ISNULL(JUN_REBATE_AMT,0)) + ABS(ISNULL(JUN_DISCOUNT,0)) 
				+ ABS(ISNULL(JUN_VENDOR_TAX,0)) + ABS(ISNULL(JUN_STATE_TAX,0)) + ABS(ISNULL(JUN_COUNTY_TAX,0)) + ABS(ISNULL(JUN_CITY_TAX,0)) 
				+ ABS(ISNULL(JUN_SPOTS,0)) + ABS(ISNULL(JUN_BILLING_AMT,0)) <> 0
UNION ALL
SELECT     ORDER_NBR, LINE_NBR, REV_NBR, SEQ_NBR, BRDCAST_YEAR * 100 + 7, BRDCAST_YEAR, 7 AS MONTH_IND, 'JUL' AS MONTH_SHORT, JUL_LINE_NET, JUL_COMM_AMT, 
                      JUL_REBATE_AMT, JUL_DISCOUNT, JUL_VENDOR_TAX, JUL_STATE_TAX, JUL_COUNTY_TAX, JUL_CITY_TAX, JUL_SPOTS, JUL_BILLING_AMT, 
                      JUL_AR_INV_NBR, JUL_AR_TYPE, JUL_AR_INV_SEQ, BILLING_USER, RECONCILE_LINE, 'RADIO' AS MEDIA_TYPE, DO_NOT_BILL, 
                      LINE_CANCELLED
FROM         dbo.RADIO_DETAIL1 AS RADIO_DETAIL1_6
WHERE		ABS(ISNULL(JUL_LINE_NET,0)) + ABS(ISNULL(JUL_COMM_AMT,0)) + ABS(ISNULL(JUL_REBATE_AMT,0)) + ABS(ISNULL(JUL_DISCOUNT,0)) 
				+ ABS(ISNULL(JUL_VENDOR_TAX,0)) + ABS(ISNULL(JUL_STATE_TAX,0)) + ABS(ISNULL(JUL_COUNTY_TAX,0)) + ABS(ISNULL(JUL_CITY_TAX,0)) 
				+ ABS(ISNULL(JUL_SPOTS,0)) + ABS(ISNULL(JUL_BILLING_AMT,0)) <> 0
UNION ALL
SELECT     ORDER_NBR, LINE_NBR, REV_NBR, SEQ_NBR, BRDCAST_YEAR * 100 + 8, BRDCAST_YEAR, 8 AS MONTH_IND, 'AUG' AS MONTH_SHORT, AUG_LINE_NET, AUG_COMM_AMT, 
                      AUG_REBATE_AMT, AUG_DISCOUNT, AUG_VENDOR_TAX, AUG_STATE_TAX, AUG_COUNTY_TAX, AUG_CITY_TAX, AUG_SPOTS, AUG_BILLING_AMT, 
                      AUG_AR_INV_NBR, AUG_AR_TYPE, AUG_AR_INV_SEQ, BILLING_USER, RECONCILE_LINE, 'RADIO' AS MEDIA_TYPE, DO_NOT_BILL, 
                      LINE_CANCELLED
FROM         dbo.RADIO_DETAIL1 AS RADIO_DETAIL1_5
WHERE		ABS(ISNULL(AUG_LINE_NET,0)) + ABS(ISNULL(AUG_COMM_AMT,0)) + ABS(ISNULL(AUG_REBATE_AMT,0)) + ABS(ISNULL(AUG_DISCOUNT,0)) 
				+ ABS(ISNULL(AUG_VENDOR_TAX,0)) + ABS(ISNULL(AUG_STATE_TAX,0)) + ABS(ISNULL(AUG_COUNTY_TAX,0)) + ABS(ISNULL(AUG_CITY_TAX,0)) 
				+ ABS(ISNULL(AUG_SPOTS,0)) + ABS(ISNULL(AUG_BILLING_AMT,0)) <> 0
UNION ALL
SELECT     ORDER_NBR, LINE_NBR, REV_NBR, SEQ_NBR, BRDCAST_YEAR * 100 + 9, BRDCAST_YEAR, 9 AS MONTH_IND, 'SEP' AS MONTH_SHORT, SEP_LINE_NET, SEP_COMM_AMT, 
                      SEP_REBATE_AMT, SEP_DISCOUNT, SEP_VENDOR_TAX, SEP_STATE_TAX, SEP_COUNTY_TAX, SEP_CITY_TAX, SEP_SPOTS, SEP_BILLING_AMT, 
                      SEP_AR_INV_NBR, SEP_AR_TYPE, SEP_AR_INV_SEQ, BILLING_USER, RECONCILE_LINE, 'RADIO' AS MEDIA_TYPE, DO_NOT_BILL, 
                      LINE_CANCELLED
FROM         dbo.RADIO_DETAIL1 AS RADIO_DETAIL1_4
WHERE		ABS(ISNULL(SEP_LINE_NET,0)) + ABS(ISNULL(SEP_COMM_AMT,0)) + ABS(ISNULL(SEP_REBATE_AMT,0)) + ABS(ISNULL(SEP_DISCOUNT,0)) 
				+ ABS(ISNULL(SEP_VENDOR_TAX,0)) + ABS(ISNULL(SEP_STATE_TAX,0)) + ABS(ISNULL(SEP_COUNTY_TAX,0)) + ABS(ISNULL(SEP_CITY_TAX,0)) 
				+ ABS(ISNULL(SEP_SPOTS,0)) + ABS(ISNULL(SEP_BILLING_AMT,0)) <> 0
UNION ALL
SELECT     ORDER_NBR, LINE_NBR, REV_NBR, SEQ_NBR, BRDCAST_YEAR * 100 + 10, BRDCAST_YEAR, 10 AS MONTH_IND, 'OCT' AS MONTH_SHORT, OCT_LINE_NET, OCT_COMM_AMT, 
                      OCT_REBATE_AMT, OCT_DISCOUNT, OCT_VENDOR_TAX, OCT_STATE_TAX, OCT_COUNTY_TAX, OCT_CITY_TAX, OCT_SPOTS, OCT_BILLING_AMT, 
                      OCT_AR_INV_NBR, OCT_AR_TYPE, OCT_AR_INV_SEQ, BILLING_USER, RECONCILE_LINE, 'RADIO' AS MEDIA_TYPE, DO_NOT_BILL, 
                      LINE_CANCELLED
FROM         dbo.RADIO_DETAIL1 AS RADIO_DETAIL1_3
WHERE		ABS(ISNULL(OCT_LINE_NET,0)) + ABS(ISNULL(OCT_COMM_AMT,0)) + ABS(ISNULL(OCT_REBATE_AMT,0)) + ABS(ISNULL(OCT_DISCOUNT,0)) 
				+ ABS(ISNULL(OCT_VENDOR_TAX,0)) + ABS(ISNULL(OCT_STATE_TAX,0)) + ABS(ISNULL(OCT_COUNTY_TAX,0)) + ABS(ISNULL(OCT_CITY_TAX,0)) 
				+ ABS(ISNULL(OCT_SPOTS,0)) + ABS(ISNULL(OCT_BILLING_AMT,0)) <> 0
UNION ALL
SELECT     ORDER_NBR, LINE_NBR, REV_NBR, SEQ_NBR, BRDCAST_YEAR * 100 + 11, BRDCAST_YEAR, 11 AS MONTH_IND, 'NOV' AS MONTH_SHORT, NOV_LINE_NET, NOV_COMM_AMT, 
                      NOV_REBATE_AMT, NOV_DISCOUNT, NOV_VENDOR_TAX, NOV_STATE_TAX, NOV_COUNTY_TAX, NOV_CITY_TAX, NOV_SPOTS, NOV_BILLING_AMT, 
                      NOV_AR_INV_NBR, NOV_AR_TYPE, NOV_AR_INV_SEQ, BILLING_USER, RECONCILE_LINE, 'RADIO' AS MEDIA_TYPE, DO_NOT_BILL, 
                      LINE_CANCELLED
FROM         dbo.RADIO_DETAIL1 AS RADIO_DETAIL1_2
WHERE		ABS(ISNULL(NOV_LINE_NET,0)) + ABS(ISNULL(NOV_COMM_AMT,0)) + ABS(ISNULL(NOV_REBATE_AMT,0)) + ABS(ISNULL(NOV_DISCOUNT,0)) 
				+ ABS(ISNULL(NOV_VENDOR_TAX,0)) + ABS(ISNULL(NOV_STATE_TAX,0)) + ABS(ISNULL(NOV_COUNTY_TAX,0)) + ABS(ISNULL(NOV_CITY_TAX,0)) 
				+ ABS(ISNULL(NOV_SPOTS,0)) + ABS(ISNULL(NOV_BILLING_AMT,0)) <> 0
UNION ALL
SELECT     ORDER_NBR, LINE_NBR, REV_NBR, SEQ_NBR, BRDCAST_YEAR * 100 + 12, BRDCAST_YEAR, 12 AS MONTH_IND, 'DEC' AS MONTH_SHORT, DEC_LINE_NET, DEC_COMM_AMT, 
                      DEC_REBATE_AMT, DEC_DISCOUNT, DEC_VENDOR_TAX, DEC_STATE_TAX, DEC_COUNTY_TAX, DEC_CITY_TAX, DEC_SPOTS, DEC_BILLING_AMT, 
                      DEC_AR_INV_NBR, DEC_AR_TYPE, DEC_AR_INV_SEQ, BILLING_USER, RECONCILE_LINE, 'RADIO' AS MEDIA_TYPE, DO_NOT_BILL, 
                      LINE_CANCELLED
FROM         dbo.RADIO_DETAIL1 AS RADIO_DETAIL1_1
WHERE		ABS(ISNULL(DEC_LINE_NET,0)) + ABS(ISNULL(DEC_COMM_AMT,0)) + ABS(ISNULL(DEC_REBATE_AMT,0)) + ABS(ISNULL(DEC_DISCOUNT,0)) 
				+ ABS(ISNULL(DEC_VENDOR_TAX,0)) + ABS(ISNULL(DEC_STATE_TAX,0)) + ABS(ISNULL(DEC_COUNTY_TAX,0)) + ABS(ISNULL(DEC_CITY_TAX,0)) 
				+ ABS(ISNULL(DEC_SPOTS,0)) + ABS(ISNULL(DEC_BILLING_AMT,0)) <> 0

