
CREATE VIEW dbo.V_TV_AMOUNTS(ORDER_NBR, LINE_NBR, REV_NBR, SEQ_NBR, LINE_NET, COMM_AMT, 
                      REBATE_AMT, LINE_DISC, VENDOR_TAX, STATE_TAX, COUNTY_TAX, CITY_TAX, SPOTS, BILL_AMT, AR_INV_NBR, AR_TYPE, AR_INV_SEQ, 
                      [MONTH], [YEAR], BILLING_USER, MEDIA_TYPE, GLACODE_CITY, GLACODE_COS, GLACODE_COUNTY, GLACODE_SALES, 
                      GLACODE_STATE, GLACODE_WIP, GLESEQ_CITY, GLESEQ_COS, GLESEQ_COUNTY, GLESEQ_SALES, GLESEQ_STATE, GLESEQ_WIP, 
                      GLEXACT, GLEXACT_DEF, RECONCILE_LINE, DO_NOT_BILL, BILL_TYPE_FLAG, BRDCAST_PERIOD)
AS

SELECT     d.ORDER_NBR, d.LINE_NBR, d.REV_NBR, d.SEQ_NBR, d.JAN_LINE_NET AS LINE_NET, d.JAN_COMM_AMT AS COMM_AMT, 
                      d.JAN_REBATE_AMT AS REBATE_AMT, d.JAN_DISCOUNT AS LINE_DISC, d.JAN_VENDOR_TAX AS VENDOR_TAX, d.JAN_STATE_TAX AS STATE_TAX, 
                      d.JAN_COUNTY_TAX AS COUNTY_TAX, d.JAN_CITY_TAX AS CITY_TAX, d.JAN_SPOTS AS SPOTS, d.JAN_BILLING_AMT AS BILL_AMT, 
                      d.JAN_AR_INV_NBR AS AR_INV_NBR, d.JAN_AR_TYPE AS AR_TYPE, d.JAN_AR_INV_SEQ AS AR_INV_SEQ, 'JAN' AS MONTH, 
                      d.BRDCAST_YEAR AS YEAR, d.BILLING_USER, 'TV' AS MEDIA_TYPE, g.JAN_GLACODE_CITY AS GLACODE_CITY, 
                      g.JAN_GLACODE_COS AS GLACODE_COS, g.JAN_GLACODE_COUNTY AS GLACODE_COUNTY, g.JAN_GLACODE_SALES AS GLACODE_SALES, 
                      g.JAN_GLACODE_STATE AS GLACODE_STATE, g.JAN_GLACODE_WIP AS GLACODE_WIP, g.JAN_GLESEQ_CITY AS GLESEQ_CITY, 
                      g.JAN_GLESEQ_COS AS GLESEQ_COS, g.JAN_GLESEQ_COUNTY AS GLESEQ_COUNTY, g.JAN_GLESEQ_SALES AS GLESEQ_SALES, 
                      g.JAN_GLESEQ_STATE AS GLESEQ_STATE, g.JAN_GLESEQ_WIP AS GLESEQ_WIP, g.JAN_GLEXACT AS GLEXACT, 
                      g.JAN_GLEXACT_DEF AS GLEXACT_DEF, d.RECONCILE_LINE, d.DO_NOT_BILL, h.BILL_TYPE_FLAG, 
                      d.BRDCAST_YEAR * 100 + 1 AS BRDCAST_PERIOD
FROM         dbo.TV_DETAIL1 AS d INNER JOIN
                      dbo.TV_GL AS g ON d.ORDER_NBR = g.ORDER_NBR AND d.REV_NBR = g.REV_NBR AND d.LINE_NBR = g.LINE_NBR AND 
                      d.SEQ_NBR = g.SEQ_NBR AND d.BRDCAST_YEAR = g.BRDCAST_YEAR INNER JOIN
                      dbo.TV_HEADER AS h ON g.ORDER_NBR = h.ORDER_NBR AND g.REV_NBR = h.REV_NBR
UNION ALL
SELECT     d.ORDER_NBR, d.LINE_NBR, d.REV_NBR, d.SEQ_NBR, d.FEB_LINE_NET, d.FEB_COMM_AMT, d.FEB_REBATE_AMT, d.FEB_DISCOUNT, 
                      d.FEB_VENDOR_TAX, d.FEB_STATE_TAX, d.FEB_COUNTY_TAX, d.FEB_CITY_TAX, d.FEB_SPOTS, d.FEB_BILLING_AMT, d.FEB_AR_INV_NBR, 
                      d.FEB_AR_TYPE, d.FEB_AR_INV_SEQ, 'FEB' AS EXPR1, d.BRDCAST_YEAR, d.BILLING_USER, 'TV' AS EXPR2, g.FEB_GLACODE_CITY, 
                      g.FEB_GLACODE_COS, g.FEB_GLACODE_COUNTY, g.FEB_GLACODE_SALES, g.FEB_GLACODE_STATE, g.FEB_GLACODE_WIP, g.FEB_GLESEQ_CITY, 
                      g.FEB_GLESEQ_COS, g.FEB_GLESEQ_COUNTY, g.FEB_GLESEQ_SALES, g.FEB_GLESEQ_STATE, g.FEB_GLESEQ_WIP, g.FEB_GLEXACT, 
                      g.FEB_GLEXACT_DEF, d.RECONCILE_LINE, d.DO_NOT_BILL, h.BILL_TYPE_FLAG, d.BRDCAST_YEAR * 100 + 2 AS BRDCAST_PERIOD
FROM         dbo.TV_DETAIL1 AS d INNER JOIN
                      dbo.TV_GL AS g ON d.ORDER_NBR = g.ORDER_NBR AND d.REV_NBR = g.REV_NBR AND d.LINE_NBR = g.LINE_NBR AND 
                      d.SEQ_NBR = g.SEQ_NBR AND d.BRDCAST_YEAR = g.BRDCAST_YEAR INNER JOIN
                      dbo.TV_HEADER AS h ON g.ORDER_NBR = h.ORDER_NBR AND g.REV_NBR = h.REV_NBR
UNION ALL
SELECT     d.ORDER_NBR, d.LINE_NBR, d.REV_NBR, d.SEQ_NBR, d.MAR_LINE_NET, d.MAR_COMM_AMT, d.MAR_REBATE_AMT, d.MAR_DISCOUNT, 
                      d.MAR_VENDOR_TAX, d.MAR_STATE_TAX, d.MAR_COUNTY_TAX, d.MAR_CITY_TAX, d.MAR_SPOTS, d.MAR_BILLING_AMT, d.MAR_AR_INV_NBR, 
                      d.MAR_AR_TYPE, d.MAR_AR_INV_SEQ, 'MAR' AS EXPR1, d.BRDCAST_YEAR, d.BILLING_USER, 'TV' AS EXPR2, g.MAR_GLACODE_CITY, 
                      g.MAR_GLACODE_COS, g.MAR_GLACODE_COUNTY, g.MAR_GLACODE_SALES, g.MAR_GLACODE_STATE, g.MAR_GLACODE_WIP, 
                      g.MAR_GLESEQ_CITY, g.MAR_GLESEQ_COS, g.MAR_GLESEQ_COUNTY, g.MAR_GLESEQ_SALES, g.MAR_GLESEQ_STATE, g.MAR_GLESEQ_WIP, 
                      g.MAR_GLEXACT, g.MAR_GLEXACT_DEF, d.RECONCILE_LINE, d.DO_NOT_BILL, h.BILL_TYPE_FLAG, 
                      d.BRDCAST_YEAR * 100 + 3 AS BRDCAST_PERIOD
FROM         dbo.TV_DETAIL1 AS d INNER JOIN
                      dbo.TV_GL AS g ON d.ORDER_NBR = g.ORDER_NBR AND d.REV_NBR = g.REV_NBR AND d.LINE_NBR = g.LINE_NBR AND 
                      d.SEQ_NBR = g.SEQ_NBR AND d.BRDCAST_YEAR = g.BRDCAST_YEAR INNER JOIN
                      dbo.TV_HEADER AS h ON g.ORDER_NBR = h.ORDER_NBR AND g.REV_NBR = h.REV_NBR
UNION ALL
SELECT     d.ORDER_NBR, d.LINE_NBR, d.REV_NBR, d.SEQ_NBR, d.APR_LINE_NET, d.APR_COMM_AMT, d.APR_REBATE_AMT, d.APR_DISCOUNT, 
                      d.APR_VENDOR_TAX, d.APR_STATE_TAX, d.APR_COUNTY_TAX, d.APR_CITY_TAX, d.APR_SPOTS, d.APR_BILLING_AMT, d.APR_AR_INV_NBR, 
                      d.APR_AR_TYPE, d.APR_AR_INV_SEQ, 'APR' AS EXPR1, d.BRDCAST_YEAR, d.BILLING_USER, 'TV' AS EXPR2, g.APR_GLACODE_CITY, 
                      g.APR_GLACODE_COS, g.APR_GLACODE_COUNTY, g.APR_GLACODE_SALES, g.APR_GLACODE_STATE, g.APR_GLACODE_WIP, g.APR_GLESEQ_CITY, 
                      g.APR_GLESEQ_COS, g.APR_GLESEQ_COUNTY, g.APR_GLESEQ_SALES, g.APR_GLESEQ_STATE, g.APR_GLESEQ_WIP, g.APR_GLEXACT, 
                      g.APR_GLEXACT_DEF, d.RECONCILE_LINE, d.DO_NOT_BILL, h.BILL_TYPE_FLAG, d.BRDCAST_YEAR * 100 + 4 AS BRDCAST_PERIOD
FROM         dbo.TV_DETAIL1 AS d INNER JOIN
                      dbo.TV_GL AS g ON d.ORDER_NBR = g.ORDER_NBR AND d.REV_NBR = g.REV_NBR AND d.LINE_NBR = g.LINE_NBR AND 
                      d.SEQ_NBR = g.SEQ_NBR AND d.BRDCAST_YEAR = g.BRDCAST_YEAR INNER JOIN
                      dbo.TV_HEADER AS h ON g.ORDER_NBR = h.ORDER_NBR AND g.REV_NBR = h.REV_NBR
UNION ALL
SELECT     d.ORDER_NBR, d.LINE_NBR, d.REV_NBR, d.SEQ_NBR, d.MAY_LINE_NET, d.MAY_COMM_AMT, d.MAY_REBATE_AMT, d.MAY_DISCOUNT, 
                      d.MAY_VENDOR_TAX, d.MAY_STATE_TAX, d.MAY_COUNTY_TAX, d.MAY_CITY_TAX, d.MAY_SPOTS, d.MAY_BILLING_AMT, d.MAY_AR_INV_NBR, 
                      d.MAY_AR_TYPE, d.MAY_AR_INV_SEQ, 'MAY' AS EXPR1, d.BRDCAST_YEAR, d.BILLING_USER, 'TV' AS EXPR2, g.MAY_GLACODE_CITY, 
                      g.MAY_GLACODE_COS, g.MAY_GLACODE_COUNTY, g.MAY_GLACODE_SALES, g.MAY_GLACODE_STATE, g.MAY_GLACODE_WIP, 
                      g.MAY_GLESEQ_CITY, g.MAY_GLESEQ_COS, g.MAY_GLESEQ_COUNTY, g.MAY_GLESEQ_SALES, g.MAY_GLESEQ_STATE, g.MAY_GLESEQ_WIP, 
                      g.MAY_GLEXACT, g.MAY_GLEXACT_DEF, d.RECONCILE_LINE, d.DO_NOT_BILL, h.BILL_TYPE_FLAG, 
                      d.BRDCAST_YEAR * 100 + 5 AS BRDCAST_PERIOD
FROM         dbo.TV_DETAIL1 AS d INNER JOIN
                      dbo.TV_GL AS g ON d.ORDER_NBR = g.ORDER_NBR AND d.REV_NBR = g.REV_NBR AND d.LINE_NBR = g.LINE_NBR AND 
                      d.SEQ_NBR = g.SEQ_NBR AND d.BRDCAST_YEAR = g.BRDCAST_YEAR INNER JOIN
                      dbo.TV_HEADER AS h ON g.ORDER_NBR = h.ORDER_NBR AND g.REV_NBR = h.REV_NBR
UNION ALL
SELECT     d.ORDER_NBR, d.LINE_NBR, d.REV_NBR, d.SEQ_NBR, d.JUN_LINE_NET, d.JUN_COMM_AMT, d.JUN_REBATE_AMT, d.JUN_DISCOUNT, 
                      d.JUN_VENDOR_TAX, d.JUN_STATE_TAX, d.JUN_COUNTY_TAX, d.JUN_CITY_TAX, d.JUN_SPOTS, d.JUN_BILLING_AMT, d.JUN_AR_INV_NBR, 
                      d.JUN_AR_TYPE, d.JUN_AR_INV_SEQ, 'JUN' AS EXPR1, d.BRDCAST_YEAR, d.BILLING_USER, 'TV' AS EXPR2, g.JUN_GLACODE_CITY, 
                      g.JUN_GLACODE_COS, g.JUN_GLACODE_COUNTY, g.JUN_GLACODE_SALES, g.JUN_GLACODE_STATE, g.JUN_GLACODE_WIP, g.JUN_GLESEQ_CITY, 
                      g.JUN_GLESEQ_COS, g.JUN_GLESEQ_COUNTY, g.JUN_GLESEQ_SALES, g.JUN_GLESEQ_STATE, g.JUN_GLESEQ_WIP, g.JUN_GLEXACT, 
                      g.JUN_GLEXACT_DEF, d.RECONCILE_LINE, d.DO_NOT_BILL, h.BILL_TYPE_FLAG, d.BRDCAST_YEAR * 100 + 6 AS BRDCAST_PERIOD
FROM         dbo.TV_DETAIL1 AS d INNER JOIN
                      dbo.TV_GL AS g ON d.ORDER_NBR = g.ORDER_NBR AND d.REV_NBR = g.REV_NBR AND d.LINE_NBR = g.LINE_NBR AND 
                      d.SEQ_NBR = g.SEQ_NBR AND d.BRDCAST_YEAR = g.BRDCAST_YEAR INNER JOIN
                      dbo.TV_HEADER AS h ON g.ORDER_NBR = h.ORDER_NBR AND g.REV_NBR = h.REV_NBR
UNION ALL
SELECT     d.ORDER_NBR, d.LINE_NBR, d.REV_NBR, d.SEQ_NBR, d.JUL_LINE_NET, d.JUL_COMM_AMT, d.JUL_REBATE_AMT, d.JUL_DISCOUNT, 
                      d.JUL_VENDOR_TAX, d.JUL_STATE_TAX, d.JUL_COUNTY_TAX, d.JUL_CITY_TAX, d.JUL_SPOTS, d.JUL_BILLING_AMT, d.JUL_AR_INV_NBR, 
                      d.JUL_AR_TYPE, d.JUL_AR_INV_SEQ, 'JUL' AS EXPR1, d.BRDCAST_YEAR, d.BILLING_USER, 'TV' AS EXPR2, g.JUL_GLACODE_CITY, 
                      g.JUL_GLACODE_COS, g.JUL_GLACODE_COUNTY, g.JUL_GLACODE_SALES, g.JUL_GLACODE_STATE, g.JUL_GLACODE_WIP, g.JUL_GLESEQ_CITY, 
                      g.JUL_GLESEQ_COS, g.JUL_GLESEQ_COUNTY, g.JUL_GLESEQ_SALES, g.JUL_GLESEQ_STATE, g.JUL_GLESEQ_WIP, g.JUL_GLEXACT, 
                      g.JUL_GLEXACT_DEF, d.RECONCILE_LINE, d.DO_NOT_BILL, h.BILL_TYPE_FLAG, d.BRDCAST_YEAR * 100 + 7 AS BRDCAST_PERIOD
FROM         dbo.TV_DETAIL1 AS d INNER JOIN
                      dbo.TV_GL AS g ON d.ORDER_NBR = g.ORDER_NBR AND d.REV_NBR = g.REV_NBR AND d.LINE_NBR = g.LINE_NBR AND 
                      d.SEQ_NBR = g.SEQ_NBR AND d.BRDCAST_YEAR = g.BRDCAST_YEAR INNER JOIN
                      dbo.TV_HEADER AS h ON g.ORDER_NBR = h.ORDER_NBR AND g.REV_NBR = h.REV_NBR
UNION ALL
SELECT     d.ORDER_NBR, d.LINE_NBR, d.REV_NBR, d.SEQ_NBR, d.AUG_LINE_NET, d.AUG_COMM_AMT, d.AUG_REBATE_AMT, d.AUG_DISCOUNT, 
                      d.AUG_VENDOR_TAX, d.AUG_STATE_TAX, d.AUG_COUNTY_TAX, d.AUG_CITY_TAX, d.AUG_SPOTS, d.AUG_BILLING_AMT, d.AUG_AR_INV_NBR, 
                      d.AUG_AR_TYPE, d.AUG_AR_INV_SEQ, 'AUG' AS EXPR1, d.BRDCAST_YEAR, d.BILLING_USER, 'TV' AS EXPR2, g.AUG_GLACODE_CITY, 
                      g.AUG_GLACODE_COS, g.AUG_GLACODE_COUNTY, g.AUG_GLACODE_SALES, g.AUG_GLACODE_STATE, g.AUG_GLACODE_WIP, 
                      g.AUG_GLESEQ_CITY, g.AUG_GLESEQ_COS, g.AUG_GLESEQ_COUNTY, g.AUG_GLESEQ_SALES, g.AUG_GLESEQ_STATE, g.AUG_GLESEQ_WIP, 
                      g.AUG_GLEXACT, g.AUG_GLEXACT_DEF, d.RECONCILE_LINE, d.DO_NOT_BILL, h.BILL_TYPE_FLAG, 
                      d.BRDCAST_YEAR * 100 + 8 AS BRDCAST_PERIOD
FROM         dbo.TV_DETAIL1 AS d INNER JOIN
                      dbo.TV_GL AS g ON d.ORDER_NBR = g.ORDER_NBR AND d.REV_NBR = g.REV_NBR AND d.LINE_NBR = g.LINE_NBR AND 
                      d.SEQ_NBR = g.SEQ_NBR AND d.BRDCAST_YEAR = g.BRDCAST_YEAR INNER JOIN
                      dbo.TV_HEADER AS h ON g.ORDER_NBR = h.ORDER_NBR AND g.REV_NBR = h.REV_NBR
UNION ALL
SELECT     d.ORDER_NBR, d.LINE_NBR, d.REV_NBR, d.SEQ_NBR, d.SEP_LINE_NET, d.SEP_COMM_AMT, d.SEP_REBATE_AMT, d.SEP_DISCOUNT, 
                      d.SEP_VENDOR_TAX, d.SEP_STATE_TAX, d.SEP_COUNTY_TAX, d.SEP_CITY_TAX, d.SEP_SPOTS, d.SEP_BILLING_AMT, d.SEP_AR_INV_NBR, 
                      d.SEP_AR_TYPE, d.SEP_AR_INV_SEQ, 'SEP' AS EXPR1, d.BRDCAST_YEAR, d.BILLING_USER, 'TV' AS EXPR2, g.SEP_GLACODE_CITY, 
                      g.SEP_GLACODE_COS, g.SEP_GLACODE_COUNTY, g.SEP_GLACODE_SALES, g.SEP_GLACODE_STATE, g.SEP_GLACODE_WIP, g.SEP_GLESEQ_CITY, 
                      g.SEP_GLESEQ_COS, g.SEP_GLESEQ_COUNTY, g.SEP_GLESEQ_SALES, g.SEP_GLESEQ_STATE, g.SEP_GLESEQ_WIP, g.SEP_GLEXACT, 
                      g.SEP_GLEXACT_DEF, d.RECONCILE_LINE, d.DO_NOT_BILL, h.BILL_TYPE_FLAG, d.BRDCAST_YEAR * 100 + 9 AS BRDCAST_PERIOD
FROM         dbo.TV_DETAIL1 AS d INNER JOIN
                      dbo.TV_GL AS g ON d.ORDER_NBR = g.ORDER_NBR AND d.REV_NBR = g.REV_NBR AND d.LINE_NBR = g.LINE_NBR AND 
                      d.SEQ_NBR = g.SEQ_NBR AND d.BRDCAST_YEAR = g.BRDCAST_YEAR INNER JOIN
                      dbo.TV_HEADER AS h ON g.ORDER_NBR = h.ORDER_NBR AND g.REV_NBR = h.REV_NBR
UNION ALL
SELECT     d.ORDER_NBR, d.LINE_NBR, d.REV_NBR, d.SEQ_NBR, d.OCT_LINE_NET, d.OCT_COMM_AMT, d.OCT_REBATE_AMT, d.OCT_DISCOUNT, 
                      d.OCT_VENDOR_TAX, d.OCT_STATE_TAX, d.OCT_COUNTY_TAX, d.OCT_CITY_TAX, d.OCT_SPOTS, d.OCT_BILLING_AMT, d.OCT_AR_INV_NBR, 
                      d.OCT_AR_TYPE, d.OCT_AR_INV_SEQ, 'OCT' AS EXPR1, d.BRDCAST_YEAR, d.BILLING_USER, 'TV' AS EXPR2, g.OCT_GLACODE_CITY, 
                      g.OCT_GLACODE_COS, g.OCT_GLACODE_COUNTY, g.OCT_GLACODE_SALES, g.OCT_GLACODE_STATE, g.OCT_GLACODE_WIP, g.OCT_GLESEQ_CITY, 
                      g.OCT_GLESEQ_COS, g.OCT_GLESEQ_COUNTY, g.OCT_GLESEQ_SALES, g.OCT_GLESEQ_STATE, g.OCT_GLESEQ_WIP, g.OCT_GLEXACT, 
                      g.OCT_GLEXACT_DEF, d.RECONCILE_LINE, d.DO_NOT_BILL, h.BILL_TYPE_FLAG, d.BRDCAST_YEAR * 100 + 10 AS BRDCAST_PERIOD
FROM         dbo.TV_DETAIL1 AS d INNER JOIN
                      dbo.TV_GL AS g ON d.ORDER_NBR = g.ORDER_NBR AND d.REV_NBR = g.REV_NBR AND d.LINE_NBR = g.LINE_NBR AND 
                      d.SEQ_NBR = g.SEQ_NBR AND d.BRDCAST_YEAR = g.BRDCAST_YEAR INNER JOIN
                      dbo.TV_HEADER AS h ON g.ORDER_NBR = h.ORDER_NBR AND g.REV_NBR = h.REV_NBR
UNION ALL
SELECT     d.ORDER_NBR, d.LINE_NBR, d.REV_NBR, d.SEQ_NBR, d.NOV_LINE_NET, d.NOV_COMM_AMT, d.NOV_REBATE_AMT, d.NOV_DISCOUNT, 
                      d.NOV_VENDOR_TAX, d.NOV_STATE_TAX, d.NOV_COUNTY_TAX, d.NOV_CITY_TAX, d.NOV_SPOTS, d.NOV_BILLING_AMT, d.NOV_AR_INV_NBR, 
                      d.NOV_AR_TYPE, d.NOV_AR_INV_SEQ, 'NOV' AS EXPR1, d.BRDCAST_YEAR, d.BILLING_USER, 'TV' AS EXPR2, g.NOV_GLACODE_CITY, 
                      g.NOV_GLACODE_COS, g.NOV_GLACODE_COUNTY, g.NOV_GLACODE_SALES, g.NOV_GLACODE_STATE, g.NOV_GLACODE_WIP, 
                      g.NOV_GLESEQ_CITY, g.NOV_GLESEQ_COS, g.NOV_GLESEQ_COUNTY, g.NOV_GLESEQ_SALES, g.NOV_GLESEQ_STATE, g.NOV_GLESEQ_WIP, 
                      g.NOV_GLEXACT, g.NOV_GLEXACT_DEF, d.RECONCILE_LINE, d.DO_NOT_BILL, h.BILL_TYPE_FLAG, 
                      d.BRDCAST_YEAR * 100 + 11 AS BRDCAST_PERIOD
FROM         dbo.TV_DETAIL1 AS d INNER JOIN
                      dbo.TV_GL AS g ON d.ORDER_NBR = g.ORDER_NBR AND d.REV_NBR = g.REV_NBR AND d.LINE_NBR = g.LINE_NBR AND 
                      d.SEQ_NBR = g.SEQ_NBR AND d.BRDCAST_YEAR = g.BRDCAST_YEAR INNER JOIN
                      dbo.TV_HEADER AS h ON g.ORDER_NBR = h.ORDER_NBR AND g.REV_NBR = h.REV_NBR
UNION ALL
SELECT     d .ORDER_NBR, d .LINE_NBR, d .REV_NBR, d .SEQ_NBR, d .DEC_LINE_NET, d .DEC_COMM_AMT, d .DEC_REBATE_AMT, d .DEC_DISCOUNT, 
                      d .DEC_VENDOR_TAX, d .DEC_STATE_TAX, d .DEC_COUNTY_TAX, d .DEC_CITY_TAX, d .DEC_SPOTS, d .DEC_BILLING_AMT, d .DEC_AR_INV_NBR, 
                      d .DEC_AR_TYPE, d .DEC_AR_INV_SEQ, 'DEC' AS EXPR1, d .BRDCAST_YEAR, d .BILLING_USER, 'TV' AS EXPR2, g.DEC_GLACODE_CITY, 
                      g.DEC_GLACODE_COS, g.DEC_GLACODE_COUNTY, g.DEC_GLACODE_SALES, g.DEC_GLACODE_STATE, g.DEC_GLACODE_WIP, 
                      g.DEC_GLESEQ_CITY, g.DEC_GLESEQ_COS, g.DEC_GLESEQ_COUNTY, g.DEC_GLESEQ_SALES, g.DEC_GLESEQ_STATE, g.DEC_GLESEQ_WIP, 
                      g.DEC_GLEXACT, g.DEC_GLEXACT_DEF, d .RECONCILE_LINE, d .DO_NOT_BILL, h.BILL_TYPE_FLAG, 
                      d .BRDCAST_YEAR * 100 + 12 AS BRDCAST_PERIOD
FROM         dbo.TV_DETAIL1 AS d INNER JOIN
                      dbo.TV_GL AS g ON d .ORDER_NBR = g.ORDER_NBR AND d .REV_NBR = g.REV_NBR AND d .LINE_NBR = g.LINE_NBR AND 
                      d .SEQ_NBR = g.SEQ_NBR AND d .BRDCAST_YEAR = g.BRDCAST_YEAR INNER JOIN
                      dbo.TV_HEADER AS h ON g.ORDER_NBR = h.ORDER_NBR AND g.REV_NBR = h.REV_NBR
