
CREATE VIEW dbo.V_TV_GL(ORDER_NBR, LINE_NBR, REV_NBR, SEQ_NBR, BRDCAST_YEAR, MONTH_IND, MONTH_SHORT, 
                      GLACODE_CITY, GLACODE_COS, GLACODE_COUNTY, GLACODE_SALES, GLACODE_STATE, GLACODE_WIP, 
                      GLESEQ_CITY, GLESEQ_COS, GLESEQ_COUNTY, GLESEQ_SALES, GLESEQ_STATE, GLESEQ_WIP, 
                      GLEXACT, GLEXACT_DEF ) 
AS

SELECT     ORDER_NBR, LINE_NBR, REV_NBR, SEQ_NBR, BRDCAST_YEAR, 1 AS MONTH_IND, 'JAN' AS MONTH_SHORT, JAN_GLACODE_CITY, 
					  JAN_GLACODE_COS, JAN_GLACODE_COUNTY, JAN_GLACODE_SALES, JAN_GLACODE_STATE, JAN_GLACODE_WIP, JAN_GLESEQ_CITY, 
		              JAN_GLESEQ_COS, JAN_GLESEQ_COUNTY, JAN_GLESEQ_SALES, JAN_GLESEQ_STATE, JAN_GLESEQ_WIP, JAN_GLEXACT, 
		              JAN_GLEXACT_DEF
FROM         dbo.TV_GL
UNION ALL
SELECT     ORDER_NBR, LINE_NBR, REV_NBR, SEQ_NBR, BRDCAST_YEAR, 2 AS MONTH_IND, 'FEB' AS MONTH_SHORT, FEB_GLACODE_CITY, 
                      FEB_GLACODE_COS, FEB_GLACODE_COUNTY, FEB_GLACODE_SALES, FEB_GLACODE_STATE, FEB_GLACODE_WIP, FEB_GLESEQ_CITY, 
                      FEB_GLESEQ_COS, FEB_GLESEQ_COUNTY, FEB_GLESEQ_SALES, FEB_GLESEQ_STATE, FEB_GLESEQ_WIP, FEB_GLEXACT, 
                      FEB_GLEXACT_DEF
FROM         dbo.TV_GL AS TV_GL_11
UNION ALL
SELECT     ORDER_NBR, LINE_NBR, REV_NBR, SEQ_NBR, BRDCAST_YEAR, 3 AS MONTH_IND, 'MAR' AS MONTH_SHORT, MAR_GLACODE_CITY, 
                      MAR_GLACODE_COS, MAR_GLACODE_COUNTY, MAR_GLACODE_SALES, MAR_GLACODE_STATE, MAR_GLACODE_WIP, MAR_GLESEQ_CITY, 
                      MAR_GLESEQ_COS, MAR_GLESEQ_COUNTY, MAR_GLESEQ_SALES, MAR_GLESEQ_STATE, MAR_GLESEQ_WIP, MAR_GLEXACT, 
                      MAR_GLEXACT_DEF
FROM         dbo.TV_GL AS TV_GL_10
UNION ALL
SELECT     ORDER_NBR, LINE_NBR, REV_NBR, SEQ_NBR, BRDCAST_YEAR, 4 AS MONTH_IND, 'APR' AS MONTH_SHORT, APR_GLACODE_CITY, 
                      APR_GLACODE_COS, APR_GLACODE_COUNTY, APR_GLACODE_SALES, APR_GLACODE_STATE, APR_GLACODE_WIP, APR_GLESEQ_CITY, 
                      APR_GLESEQ_COS, APR_GLESEQ_COUNTY, APR_GLESEQ_SALES, APR_GLESEQ_STATE, APR_GLESEQ_WIP, APR_GLEXACT, 
                      APR_GLEXACT_DEF
FROM         dbo.TV_GL AS TV_GL_9
UNION ALL
SELECT     ORDER_NBR, LINE_NBR, REV_NBR, SEQ_NBR, BRDCAST_YEAR, 5 AS MONTH_IND, 'MAY' AS MONTH_SHORT, MAY_GLACODE_CITY, 
                      MAY_GLACODE_COS, MAY_GLACODE_COUNTY, MAY_GLACODE_SALES, MAY_GLACODE_STATE, MAY_GLACODE_WIP, MAY_GLESEQ_CITY, 
                      MAY_GLESEQ_COS, MAY_GLESEQ_COUNTY, MAY_GLESEQ_SALES, MAY_GLESEQ_STATE, MAY_GLESEQ_WIP, MAY_GLEXACT, 
                      MAY_GLEXACT_DEF
FROM         dbo.TV_GL AS TV_GL_8
UNION ALL
SELECT     ORDER_NBR, LINE_NBR, REV_NBR, SEQ_NBR, BRDCAST_YEAR, 6 AS MONTH_IND, 'JUN' AS MONTH_SHORT, JUN_GLACODE_CITY, 
                      JUN_GLACODE_COS, JUN_GLACODE_COUNTY, JUN_GLACODE_SALES, JUN_GLACODE_STATE, JUN_GLACODE_WIP, JUN_GLESEQ_CITY, 
                      JUN_GLESEQ_COS, JUN_GLESEQ_COUNTY, JUN_GLESEQ_SALES, JUN_GLESEQ_STATE, JUN_GLESEQ_WIP, JUN_GLEXACT, 
                      JUN_GLEXACT_DEF
FROM         dbo.TV_GL AS TV_GL_7
UNION ALL
SELECT     ORDER_NBR, LINE_NBR, REV_NBR, SEQ_NBR, BRDCAST_YEAR, 7 AS MONTH_IND, 'JUL' AS MONTH_SHORT, JUL_GLACODE_CITY, 
                      JUL_GLACODE_COS, JUL_GLACODE_COUNTY, JUL_GLACODE_SALES, JUL_GLACODE_STATE, JUL_GLACODE_WIP, JUL_GLESEQ_CITY, 
                      JUL_GLESEQ_COS, JUL_GLESEQ_COUNTY, JUL_GLESEQ_SALES, JUL_GLESEQ_STATE, JUL_GLESEQ_WIP, JUL_GLEXACT, 
                      JUL_GLEXACT_DEF
FROM         dbo.TV_GL AS TV_GL_6
UNION ALL
SELECT     ORDER_NBR, LINE_NBR, REV_NBR, SEQ_NBR, BRDCAST_YEAR, 8 AS MONTH_IND, 'AUG' AS MONTH_SHORT, AUG_GLACODE_CITY, 
                      AUG_GLACODE_COS, AUG_GLACODE_COUNTY, AUG_GLACODE_SALES, AUG_GLACODE_STATE, AUG_GLACODE_WIP, AUG_GLESEQ_CITY, 
                      AUG_GLESEQ_COS, AUG_GLESEQ_COUNTY, AUG_GLESEQ_SALES, AUG_GLESEQ_STATE, AUG_GLESEQ_WIP, AUG_GLEXACT, 
                      AUG_GLEXACT_DEF
FROM         dbo.TV_GL AS TV_GL_5
UNION ALL
SELECT     ORDER_NBR, LINE_NBR, REV_NBR, SEQ_NBR, BRDCAST_YEAR, 9 AS MONTH_IND, 'SEP' AS MONTH_SHORT, SEP_GLACODE_CITY, 
                      SEP_GLACODE_COS, SEP_GLACODE_COUNTY, SEP_GLACODE_SALES, SEP_GLACODE_STATE, SEP_GLACODE_WIP, SEP_GLESEQ_CITY, 
                      SEP_GLESEQ_COS, SEP_GLESEQ_COUNTY, SEP_GLESEQ_SALES, SEP_GLESEQ_STATE, SEP_GLESEQ_WIP, SEP_GLEXACT, 
                      SEP_GLEXACT_DEF
FROM         dbo.TV_GL AS TV_GL_4
UNION ALL
SELECT     ORDER_NBR, LINE_NBR, REV_NBR, SEQ_NBR, BRDCAST_YEAR, 10 AS MONTH_IND, 'OCT' AS MONTH_SHORT, OCT_GLACODE_CITY, 
                      OCT_GLACODE_COS, OCT_GLACODE_COUNTY, OCT_GLACODE_SALES, OCT_GLACODE_STATE, OCT_GLACODE_WIP, OCT_GLESEQ_CITY, 
                      OCT_GLESEQ_COS, OCT_GLESEQ_COUNTY, OCT_GLESEQ_SALES, OCT_GLESEQ_STATE, OCT_GLESEQ_WIP, OCT_GLEXACT, 
                      OCT_GLEXACT_DEF
FROM         dbo.TV_GL AS TV_GL_3
UNION ALL
SELECT     ORDER_NBR, LINE_NBR, REV_NBR, SEQ_NBR, BRDCAST_YEAR, 11 AS MONTH_IND, 'NOV' AS MONTH_SHORT, NOV_GLACODE_CITY, 
                      NOV_GLACODE_COS, NOV_GLACODE_COUNTY, NOV_GLACODE_SALES, NOV_GLACODE_STATE, NOV_GLACODE_WIP, NOV_GLESEQ_CITY, 
                      NOV_GLESEQ_COS, NOV_GLESEQ_COUNTY, NOV_GLESEQ_SALES, NOV_GLESEQ_STATE, NOV_GLESEQ_WIP, NOV_GLEXACT, 
                      NOV_GLEXACT_DEF
FROM         dbo.TV_GL AS TV_GL_2
UNION
SELECT     ORDER_NBR, LINE_NBR, REV_NBR, SEQ_NBR, BRDCAST_YEAR, 12 AS MONTH_IND, 'DEC' AS MONTH_SHORT, DEC_GLACODE_CITY, 
                      DEC_GLACODE_COS, DEC_GLACODE_COUNTY, DEC_GLACODE_SALES, DEC_GLACODE_STATE, DEC_GLACODE_WIP, DEC_GLESEQ_CITY, 
                      DEC_GLESEQ_COS, DEC_GLESEQ_COUNTY, DEC_GLESEQ_SALES, DEC_GLESEQ_STATE, DEC_GLESEQ_WIP, DEC_GLEXACT, 
                      DEC_GLEXACT_DEF
FROM         dbo.TV_GL AS TV_GL_1
