
CREATE VIEW dbo.WV_CURRENT_CLIENT_DOCUMENTS
AS
SELECT   'Client' AS LEVEL, dbo.CLIENT_DOCUMENTS.CL_CODE, dbo.DOCUMENTS.DOCUMENT_ID, dbo.DOCUMENTS.FILENAME, dbo.DOCUMENTS.MIME_TYPE, 
                      dbo.DOCUMENTS.DESCRIPTION, dbo.DOCUMENTS.KEYWORDS, dbo.DOCUMENTS.UPLOADED_DATE, dbo.DOCUMENTS.USER_CODE, 
                      dbo.DOCUMENTS.FILE_SIZE,  dbo.DOCUMENTS.USER_CODE AS [USER_NAME], dbo.DOCUMENTS.REPOSITORY_FILENAME, 
                      dbo.DOCUMENT_TYPE.DOCUMENT_TYPE_DESC, ISNULL(dbo.DOCUMENTS.PRIVATE_FLAG, 0) AS PRIVATE_FLAG, 
                      dbo.DOCUMENTS.PROOFHQ_URL
FROM         dbo.DOCUMENTS INNER JOIN
                      dbo.CLIENT_DOCUMENTS ON dbo.DOCUMENTS.DOCUMENT_ID = dbo.CLIENT_DOCUMENTS.DOCUMENT_ID INNER JOIN
                      dbo.DOCUMENT_TYPE ON dbo.DOCUMENTS.DOCUMENT_TYPE_ID = dbo.DOCUMENT_TYPE.DOCUMENT_TYPE_ID
WHERE     (dbo.DOCUMENTS.DOCUMENT_ID IN
                          (SELECT     MAX(CLIENT_DOCUMENTS_1.DOCUMENT_ID) AS DOCUMENT_ID
                            FROM          dbo.CLIENT_DOCUMENTS AS CLIENT_DOCUMENTS_1 INNER JOIN
                                                   dbo.DOCUMENTS AS DOCUMENTS_1 ON CLIENT_DOCUMENTS_1.DOCUMENT_ID = DOCUMENTS_1.DOCUMENT_ID
                            GROUP BY CLIENT_DOCUMENTS_1.CL_CODE, DOCUMENTS_1.FILENAME))
