CREATE VIEW dbo.WV_CLIENT_DOCUMENTS
AS
	SELECT 
		dbo.CLIENT_DOCUMENTS.CL_CODE,
		dbo.DOCUMENTS.DOCUMENT_ID,
		dbo.DOCUMENTS.FILENAME,
		dbo.DOCUMENTS.MIME_TYPE,
		dbo.DOCUMENTS.DESCRIPTION,
		dbo.DOCUMENTS.KEYWORDS,
		dbo.DOCUMENTS.UPLOADED_DATE,
		dbo.DOCUMENTS.USER_CODE,
		dbo.DOCUMENTS.FILE_SIZE,
		 dbo.DOCUMENTS.USER_CODE AS [USER_NAME], 
		dbo.DOCUMENTS.REPOSITORY_FILENAME,
		dbo.DOCUMENTS.PROOFHQ_URL
	FROM 
		dbo.DOCUMENTS
		INNER JOIN dbo.CLIENT_DOCUMENTS ON dbo.DOCUMENTS.DOCUMENT_ID = dbo.CLIENT_DOCUMENTS.DOCUMENT_ID
