CREATE VIEW [dbo].[WV_CURRENT_JOB_DOCUMENTS]
AS

	SELECT  0 AS SORT, 'Job Number' AS LEVEL, dbo.JOB_DOCUMENTS.JOB_NUMBER, dbo.DOCUMENTS.DOCUMENT_ID, dbo.DOCUMENTS.FILENAME, dbo.DOCUMENTS.MIME_TYPE, 
						  dbo.DOCUMENTS.DESCRIPTION, dbo.DOCUMENTS.KEYWORDS, dbo.DOCUMENTS.UPLOADED_DATE, dbo.DOCUMENTS.USER_CODE, 
						  dbo.DOCUMENTS.FILE_SIZE,  dbo.DOCUMENTS.USER_CODE AS [USER_NAME], dbo.DOCUMENTS.REPOSITORY_FILENAME, 
						  dbo.DOCUMENT_TYPE.DOCUMENT_TYPE_DESC, ISNULL(dbo.DOCUMENTS.PRIVATE_FLAG, 0) AS PRIVATE_FLAG, 
                      dbo.DOCUMENTS.PROOFHQ_URL
	FROM         dbo.DOCUMENTS  INNER JOIN
						  dbo.JOB_DOCUMENTS ON dbo.DOCUMENTS.DOCUMENT_ID = dbo.JOB_DOCUMENTS.DOCUMENT_ID INNER JOIN
						  dbo.DOCUMENT_TYPE ON dbo.DOCUMENTS.DOCUMENT_TYPE_ID = dbo.DOCUMENT_TYPE.DOCUMENT_TYPE_ID
	WHERE     (dbo.DOCUMENTS.DOCUMENT_ID IN
							  (SELECT     MAX(JOB_DOCUMENTS_1.DOCUMENT_ID) AS DOCUMENT_ID
								FROM          dbo.JOB_DOCUMENTS AS JOB_DOCUMENTS_1 INNER JOIN
													   dbo.DOCUMENTS AS DOCUMENTS_1 ON JOB_DOCUMENTS_1.DOCUMENT_ID = DOCUMENTS_1.DOCUMENT_ID
								GROUP BY JOB_DOCUMENTS_1.JOB_NUMBER, DOCUMENTS_1.FILENAME))

	UNION

	SELECT DISTINCT 1 AS SORT, 'AP Invoice', dbo.AP_PRODUCTION.JOB_NUMBER, dbo.DOCUMENTS.DOCUMENT_ID, dbo.DOCUMENTS.FILENAME, dbo.DOCUMENTS.MIME_TYPE, 
		   dbo.DOCUMENTS.DESCRIPTION, dbo.DOCUMENTS.KEYWORDS, dbo.DOCUMENTS.UPLOADED_DATE, dbo.DOCUMENTS.USER_CODE, 
		   dbo.DOCUMENTS.FILE_SIZE,  dbo.DOCUMENTS.USER_CODE AS [USER_NAME], dbo.DOCUMENTS.REPOSITORY_FILENAME, 
		   dbo.DOCUMENT_TYPE.DOCUMENT_TYPE_DESC, ISNULL(dbo.DOCUMENTS.PRIVATE_FLAG, 0) AS PRIVATE_FLAG, 
                      dbo.DOCUMENTS.PROOFHQ_URL
	FROM dbo.DOCUMENTS 
	   INNER JOIN dbo.DOCUMENT_TYPE ON dbo.DOCUMENTS.DOCUMENT_TYPE_ID = dbo.DOCUMENT_TYPE.DOCUMENT_TYPE_ID
	   INNER JOIN AP_DOCUMENTS ON AP_DOCUMENTS.DOCUMENT_ID = dbo.DOCUMENTS.DOCUMENT_ID
	   INNER JOIN dbo.AP_PRODUCTION ON dbo.AP_PRODUCTION.AP_ID = dbo.AP_DOCUMENTS.AP_ID

	UNION    

	SELECT DISTINCT A.* FROM (	             
	SELECT TOP 100 PERCENT 
						  2 AS SORT, 'AR Invoice' AS EXPR1, dbo.AR_SUMMARY.JOB_NUMBER, dbo.DOCUMENTS.DOCUMENT_ID, dbo.DOCUMENTS.FILENAME, dbo.DOCUMENTS.MIME_TYPE, 
						  dbo.DOCUMENTS.DESCRIPTION, dbo.DOCUMENTS.KEYWORDS, dbo.DOCUMENTS.UPLOADED_DATE, dbo.DOCUMENTS.USER_CODE, dbo.DOCUMENTS.FILE_SIZE, 
						   dbo.DOCUMENTS.USER_CODE AS [USER_NAME], dbo.DOCUMENTS.REPOSITORY_FILENAME, dbo.DOCUMENT_TYPE.DOCUMENT_TYPE_DESC, 
						  ISNULL(dbo.DOCUMENTS.PRIVATE_FLAG, 0) AS PRIVATE_FLAG, 
                      dbo.DOCUMENTS.PROOFHQ_URL
	FROM         dbo.DOCUMENTS INNER JOIN
						  dbo.DOCUMENT_TYPE ON dbo.DOCUMENTS.DOCUMENT_TYPE_ID = dbo.DOCUMENT_TYPE.DOCUMENT_TYPE_ID INNER JOIN
						  dbo.ARINV_DOCUMENT ON dbo.DOCUMENTS.DOCUMENT_ID = dbo.ARINV_DOCUMENT.DOCUMENT_ID INNER JOIN
						  dbo.ACCT_REC ON dbo.ARINV_DOCUMENT.AR_INV_NBR = dbo.ACCT_REC.AR_INV_NBR AND dbo.ARINV_DOCUMENT.AR_INV_SEQ = dbo.ACCT_REC.AR_INV_SEQ AND 
						  dbo.ARINV_DOCUMENT.AR_TYPE = dbo.ACCT_REC.AR_TYPE INNER JOIN
						  dbo.AR_SUMMARY ON dbo.ARINV_DOCUMENT.AR_INV_NBR = dbo.AR_SUMMARY.AR_INV_NBR AND dbo.ARINV_DOCUMENT.AR_INV_SEQ = dbo.AR_SUMMARY.AR_INV_SEQ AND 
						  dbo.ARINV_DOCUMENT.AR_TYPE = dbo.AR_SUMMARY.AR_TYPE
	WHERE     (dbo.AR_SUMMARY.AR_INV_SEQ <> 99) AND (dbo.ACCT_REC.VOID_FLAG = 0 OR
						  dbo.ACCT_REC.VOID_FLAG IS NULL)
	ORDER BY dbo.AR_SUMMARY.AR_INV_NBR DESC) AS A
	WHERE A.DOCUMENT_ID IN (
							SELECT TOP 100 PERCENT MAX(dbo.ARINV_DOCUMENT.DOCUMENT_ID) 
							FROM         dbo.DOCUMENTS INNER JOIN
											  dbo.DOCUMENT_TYPE ON dbo.DOCUMENTS.DOCUMENT_TYPE_ID = dbo.DOCUMENT_TYPE.DOCUMENT_TYPE_ID INNER JOIN
											  dbo.ARINV_DOCUMENT ON dbo.DOCUMENTS.DOCUMENT_ID = dbo.ARINV_DOCUMENT.DOCUMENT_ID INNER JOIN
											  dbo.ACCT_REC ON dbo.ARINV_DOCUMENT.AR_INV_NBR = dbo.ACCT_REC.AR_INV_NBR AND dbo.ARINV_DOCUMENT.AR_INV_SEQ = dbo.ACCT_REC.AR_INV_SEQ AND 
											  dbo.ARINV_DOCUMENT.AR_TYPE = dbo.ACCT_REC.AR_TYPE INNER JOIN
											  dbo.AR_SUMMARY ON dbo.ARINV_DOCUMENT.AR_INV_NBR = dbo.AR_SUMMARY.AR_INV_NBR AND dbo.ARINV_DOCUMENT.AR_INV_SEQ = dbo.AR_SUMMARY.AR_INV_SEQ AND 
											  dbo.ARINV_DOCUMENT.AR_TYPE = dbo.AR_SUMMARY.AR_TYPE
							WHERE     (dbo.AR_SUMMARY.AR_INV_SEQ <> 99) AND (dbo.ACCT_REC.VOID_FLAG = 0 OR
												  dbo.ACCT_REC.VOID_FLAG IS NULL)
							GROUP BY dbo.ARINV_DOCUMENT.AR_INV_NBR, dbo.DOCUMENTS.FILENAME
							)
	

	UNION    
	             
	SELECT DISTINCT 3 AS SORT, 'Ad Number', dbo.JOB_COMPONENT.JOB_NUMBER, dbo.DOCUMENTS.DOCUMENT_ID, dbo.DOCUMENTS.FILENAME, dbo.DOCUMENTS.MIME_TYPE, 
		   dbo.DOCUMENTS.DESCRIPTION, dbo.DOCUMENTS.KEYWORDS, dbo.DOCUMENTS.UPLOADED_DATE, dbo.DOCUMENTS.USER_CODE, 
		   dbo.DOCUMENTS.FILE_SIZE,  dbo.DOCUMENTS.USER_CODE AS [USER_NAME], dbo.DOCUMENTS.REPOSITORY_FILENAME, 
		   dbo.DOCUMENT_TYPE.DOCUMENT_TYPE_DESC, ISNULL(dbo.DOCUMENTS.PRIVATE_FLAG, 0) AS PRIVATE_FLAG, 
                      dbo.DOCUMENTS.PROOFHQ_URL
	FROM dbo.DOCUMENTS 
	   INNER JOIN dbo.DOCUMENT_TYPE ON dbo.DOCUMENTS.DOCUMENT_TYPE_ID = dbo.DOCUMENT_TYPE.DOCUMENT_TYPE_ID
	   INNER JOIN AD_NUMBER ON DOCUMENTS.DOCUMENT_ID = AD_NUMBER.DOCUMENT_ID
	   INNER JOIN dbo.JOB_COMPONENT ON dbo.JOB_COMPONENT.AD_NBR = AD_NUMBER.AD_NBR

	UNION

	SELECT DISTINCT
		[SORT] =  4, 
		[LEVEL] = 'Task', 
		[JOB_NUMBER] = JOB_COMPONENT.JOB_NUMBER, 
		[DOCUMENT_ID] = DOCUMENTS.DOCUMENT_ID, 
		[FILENAME] = DOCUMENTS.[FILENAME], 
		[MIME_TYPE] = DOCUMENTS.MIME_TYPE,
		[DESCRIPTION] = DOCUMENTS.[DESCRIPTION], 
		[KEYWORDS] = DOCUMENTS.KEYWORDS, 
		[UPLOADED_DATE] = DOCUMENTS.UPLOADED_DATE, 
		[USER_CODE] = DOCUMENTS.USER_CODE,
		[FILE_SIZE] = DOCUMENTS.FILE_SIZE, 
		[USER_NAME] = DOCUMENTS.USER_CODE, 
		[REPOSITORY_FILENAME] = DOCUMENTS.REPOSITORY_FILENAME,
		[DOCUMENT_TYPE_DESC] = DOCUMENT_TYPE.DOCUMENT_TYPE_DESC, 
		[PRIVATE_FLAG] = ISNULL(dbo.DOCUMENTS.PRIVATE_FLAG, 0),
		[PROOFHQ_URL] = DOCUMENTS.PROOFHQ_URL
	FROM 
		dbo.DOCUMENTS 
	INNER JOIN 
		dbo.DOCUMENT_TYPE ON dbo.DOCUMENTS.DOCUMENT_TYPE_ID = dbo.DOCUMENT_TYPE.DOCUMENT_TYPE_ID
	INNER JOIN 
		dbo.JOB_TRAFFIC_DET_DOCS ON DOCUMENTS.DOCUMENT_ID = JOB_TRAFFIC_DET_DOCS.DOCUMENT_ID
	INNER JOIN 
		dbo.JOB_COMPONENT ON dbo.JOB_COMPONENT.JOB_NUMBER = JOB_TRAFFIC_DET_DOCS.JOB_NUMBER AND
							 dbo.JOB_COMPONENT.JOB_COMPONENT_NBR = JOB_TRAFFIC_DET_DOCS.JOB_COMPONENT_NBR
	WHERE
		DOCUMENTS.DOCUMENT_ID IN (	SELECT     
										MAX(JOB_TRAFFIC_DET_DOCS_1.DOCUMENT_ID) AS DOCUMENT_ID
									FROM
										dbo.JOB_TRAFFIC_DET_DOCS AS JOB_TRAFFIC_DET_DOCS_1 INNER JOIN
										dbo.DOCUMENTS AS DOCUMENTS_1 ON JOB_TRAFFIC_DET_DOCS_1.DOCUMENT_ID = DOCUMENTS_1.DOCUMENT_ID
									GROUP BY 
										JOB_TRAFFIC_DET_DOCS_1.JOB_NUMBER,
										JOB_TRAFFIC_DET_DOCS_1.JOB_COMPONENT_NBR,
										JOB_TRAFFIC_DET_DOCS_1.SEQ_NBR, 
										DOCUMENTS_1.[FILENAME] )

GO


