
-- View
CREATE VIEW [dbo].[WV_ESTIMATED_HOURS] /*WITH ENCRYPTION*/
AS
/*=========== QUERY ===========*/
SELECT     dbo.ESTIMATE_APPROVAL.JOB_NUMBER, dbo.ESTIMATE_APPROVAL.JOB_COMPONENT_NBR, dbo.ESTIMATE_REV_DET.FNC_CODE, 
                      dbo.ESTIMATE_REV_DET.EST_REV_SUP_BY_CDE, SUM(dbo.ESTIMATE_REV_DET.EST_REV_QUANTITY) AS SumOfEST_REF_QUANTITY
FROM         dbo.ESTIMATE_REV_DET INNER JOIN
                      dbo.ESTIMATE_APPROVAL ON dbo.ESTIMATE_REV_DET.ESTIMATE_NUMBER = dbo.ESTIMATE_APPROVAL.ESTIMATE_NUMBER AND 
                      dbo.ESTIMATE_REV_DET.EST_COMPONENT_NBR = dbo.ESTIMATE_APPROVAL.EST_COMPONENT_NBR AND 
                      dbo.ESTIMATE_REV_DET.EST_QUOTE_NBR = dbo.ESTIMATE_APPROVAL.EST_QUOTE_NBR AND 
                      dbo.ESTIMATE_REV_DET.EST_REV_NBR = dbo.ESTIMATE_APPROVAL.EST_REVISION_NBR
GROUP BY dbo.ESTIMATE_APPROVAL.JOB_NUMBER, dbo.ESTIMATE_APPROVAL.JOB_COMPONENT_NBR, dbo.ESTIMATE_REV_DET.FNC_CODE, 
                      dbo.ESTIMATE_REV_DET.EST_REV_SUP_BY_CDE
HAVING      (NOT (dbo.ESTIMATE_REV_DET.EST_REV_SUP_BY_CDE IS NULL))

/*=========== QUERY ===========*/
