CREATE TABLE [dbo].[NIELSEN_DEMO](
	[NIELSEN_DEMO_ID] [int] NOT NULL,
	[CODE] [varchar](7) NOT NULL,
	[TYPE] [char](1) NOT NULL,
	[SHORT_DESCRIPTION] [varchar](15) NOT NULL,
	[LONG_DESCRIPTION] [varchar](30) NOT NULL,
	[AGE_FROM] [smallint] NULL,
	[AGE_TO] [smallint] NULL,
	[GENDER] [char](1) NULL,
 CONSTRAINT [PK_NIELSEN_DEMO] PRIMARY KEY CLUSTERED 
(
	[NIELSEN_DEMO_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY],
 CONSTRAINT [UC_CODE] UNIQUE NONCLUSTERED 
(
	[CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
);