CREATE TABLE [dbo].[PROGRAM_TYPE] (
    [PROGRAM_TYPE_ID] INT          IDENTITY (1, 1) NOT NULL,
    [CODE]            VARCHAR (2)  NOT NULL,
    [NAME]            VARCHAR (50) NOT NULL,
    [SHORT_NAME]      VARCHAR (16) NOT NULL,
    CONSTRAINT [PK_PROGRAM_TYPE] PRIMARY KEY CLUSTERED ([PROGRAM_TYPE_ID] ASC) WITH (FILLFACTOR = 90)
);

