IF NOT EXISTS(SELECT 1 FROM dbo.COUNTRY WHERE [NAME] = 'Puerto Rico') BEGIN

	INSERT INTO dbo.COUNTRY ([NAME], ISO2, ISO3, ISO_NUMERIC) VALUES ('Puerto Rico', 'PR', 'PRI', 630)

END
IF NOT EXISTS(SELECT 1 FROM dbo.[RATINGS_SERVICE] WHERE [RATINGS_SERVICE_ID] = 5) BEGIN

    INSERT INTO [dbo].[RATINGS_SERVICE] ([RATINGS_SERVICE_ID], [NAME]) VALUES (5,'Nielsen Puerto Rico')

END
