DECLARE @ADV_SERVICE_ID int

IF NOT EXISTS(SELECT 1 FROM dbo.ADV_SERVICE WHERE [CODE] = 'AdvantageNielsenPuertoRicoWindowsService') BEGIN

    INSERT INTO [dbo].[ADV_SERVICE]([CODE], [NAME], [ENABLED])
    VALUES('AdvantageNielsenPuertoRicoWindowsService', 'Nielsen Puerto Rico', 0)

    SET @ADV_SERVICE_ID = SCOPE_IDENTITY()
    
    INSERT INTO [dbo].[ADV_SERVICE_SETTING] (ADV_SERVICE_ID, CODE, [DESCRIPTION], [VALUE], DEFAULT_VALUE)
    VALUES (@ADV_SERVICE_ID, 'RunAt', 'Run At', '2001-01-01 01:00:00.000', '2001-01-01 01:00:00.000')
    
    INSERT INTO [dbo].[ADV_SERVICE_SETTING] (ADV_SERVICE_ID, CODE, [DESCRIPTION], [VALUE], DEFAULT_VALUE)
    VALUES (@ADV_SERVICE_ID, 'EmployeeCode', 'Employee Code', '', '')
    
    INSERT INTO [dbo].[ADV_SERVICE_SETTING] (ADV_SERVICE_ID, CODE, [DESCRIPTION], [VALUE], DEFAULT_VALUE)
    VALUES (@ADV_SERVICE_ID, 'LocalFolder', 'Local Folder', '', '')

END ELSE BEGIN

    SELECT @ADV_SERVICE_ID = ADV_SERVICE_ID
    FROM [dbo].[ADV_SERVICE] WHERE [CODE] = 'AdvantageNielsenPuertoRicoWindowsService'
    
	IF NOT EXISTS(SELECT 1 FROM [dbo].[ADV_SERVICE_SETTING] WHERE ADV_SERVICE_ID = @ADV_SERVICE_ID AND CODE = 'LocalFolder')
		INSERT INTO [dbo].[ADV_SERVICE_SETTING] (ADV_SERVICE_ID, CODE, [DESCRIPTION], [VALUE], DEFAULT_VALUE)
		VALUES (@ADV_SERVICE_ID, 'LocalFolder', 'Local Folder', '', '')

END
GO