
IF NOT EXISTS(SELECT * FROM EXPORT_SYSTEMS WHERE EXPORT_SYSTEM = 'PAYMENT_MANAGER' AND ADV_COL_NAME = 'HSB1') BEGIN

	INSERT INTO dbo.EXPORT_SYSTEMS (EXPORT_SYSTEM, COLUMN_LABEL, ADV_COL_NAME) VALUES ('PAYMENT_MANAGER', 'FTB Integrated Payables ACH', 'HSB1')
		
END


