
IF NOT EXISTS(SELECT * FROM EXPORT_SYSTEMS WHERE EXPORT_SYSTEM = 'PAYMENT_MANAGER' AND ADV_COL_NAME = 'EXAP') BEGIN

	INSERT INTO dbo.EXPORT_SYSTEMS (EXPORT_SYSTEM, COLUMN_LABEL, ADV_COL_NAME) VALUES ('PAYMENT_MANAGER', 'Expert AP Pay CSV', 'EXAP')
		
END

SELECT * FROM EXPORT_SYSTEMS WHERE EXPORT_SYSTEM = 'PAYMENT_MANAGER'