
IF NOT EXISTS(SELECT * FROM EXPORT_SYSTEMS WHERE EXPORT_SYSTEM = 'PAYMENT_MANAGER' AND ADV_COL_NAME = 'WTB') BEGIN

	INSERT INTO dbo.EXPORT_SYSTEMS (EXPORT_SYSTEM, COLUMN_LABEL, ADV_COL_NAME) VALUES ('PAYMENT_MANAGER', 'Wintrust Bank - ACH', 'WTB')
		
END

--SELECT * FROM EXPORT_SYSTEMS WHERE EXPORT_SYSTEM = 'PAYMENT_MANAGER'
