DECLARE
	@CS_ENABLED BIT = NULL
;
SELECT 
	@CS_ENABLED = CAST(AGY_SETTINGS_VALUE AS BIT) 
FROM 
	AGY_SETTINGS A WITH(NOLOCK) 
WHERE 
	AGY_SETTINGS_CODE = 'CS_ENABLED'
;
-- Clients that never had CS should have NULL
-- If update rec only where it WAS enabled, we know that client once had CS but this script flipped it off.
IF @CS_ENABLED IS NOT NULL AND @CS_ENABLED = 1
BEGIN
	UPDATE AGY_SETTINGS WITH(ROWLOCK) 
	SET AGY_SETTINGS_VALUE = 0
	WHERE AGY_SETTINGS_CODE = 'CS_ENABLED'
	;
END
DELETE FROM AGY_SETTINGS_TAB WITH(ROWLOCK) 
WHERE 
	AGY_SETTINGS_APP = 7 
	AND AGY_SETTINGS_TAB = 5
;