DECLARE 
	@GRID_ID AS INT,
	@MAX_DEFAULT_ORDER_ID AS INT,
	@COLUMN_NAME AS VARCHAR(100),
	@GRID_NAME AS VARCHAR(100)

DECLARE GRID_NAME_CURSOR CURSOR FOR
SELECT GRID_ID, [NAME] FROM [GRID] WITH(NOLOCK) WHERE NAME IN ('RadGridAlertInbox', 'AAMTaskViewGrid', 'RadGridAlertDismissed', 'RadGridAlertAll', 'RadGridAlertDrafts');

OPEN GRID_NAME_CURSOR;
FETCH NEXT FROM GRID_NAME_CURSOR INTO @GRID_ID, @GRID_NAME;

WHILE (@@FETCH_STATUS = 0)
BEGIN
	--SELECT NAME FROM GRID WHERE GRID_ID = @GRID_ID
	SELECT @MAX_DEFAULT_ORDER_ID = MAX(DEFAULT_ORDER_ID) FROM GRID_COLUMN WITH(NOLOCK)
	WHERE GRID_ID = @GRID_ID;
	--SELECT @GRID_ID, @GRID_NAME
	BEGIN
		SET @COLUMN_NAME = 'TaskStatusDescription';		
		IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM GRID_COLUMN WITH(NOLOCK) WHERE GRID_ID = @GRID_ID AND NAME = @COLUMN_NAME)
		BEGIN
			INSERT INTO GRID_COLUMN (GRID_ID, [NAME], IS_EDITABLE, DEFAULT_ORDER_ID, DEFAULT_COLUMN_WIDTH) VALUES (@GRID_ID, @COLUMN_NAME, 0, @MAX_DEFAULT_ORDER_ID + 1, 200);
		END	
        
        IF @GRID_NAME = 'AAMTaskViewGrid' --AAMTaskViewGrid
            BEGIN
                SET @COLUMN_NAME = 'PM';		
		        IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM GRID_COLUMN WITH(NOLOCK) WHERE GRID_ID = @GRID_ID AND NAME = @COLUMN_NAME)
		        BEGIN
			        INSERT INTO GRID_COLUMN (GRID_ID, [NAME], IS_EDITABLE, DEFAULT_ORDER_ID, DEFAULT_COLUMN_WIDTH) VALUES (@GRID_ID, @COLUMN_NAME, 0, @MAX_DEFAULT_ORDER_ID + 1, 200);
		        END	
            END
	END

	FETCH NEXT FROM GRID_NAME_CURSOR INTO @GRID_ID, @GRID_NAME;
END
CLOSE GRID_NAME_CURSOR;
DEALLOCATE GRID_NAME_CURSOR;