UPDATE dbo.NPR_STATION SET ARIANNA_CHANNEL_ID = 11302
WHERE [NAME] = 'PUNTO 2 (WKAQ)'

UPDATE dbo.NPR_STATION SET ARIANNA_CHANNEL_ID = 11004
WHERE [NAME] = 'TELEISLA (WSTE)'

UPDATE dbo.NPR_STATION SET ARIANNA_CHANNEL_ID = 11002
WHERE [NAME] = 'TELEMUNDO PR (WKAQ)'

UPDATE dbo.NPR_STATION SET ARIANNA_CHANNEL_ID = 11003
WHERE [NAME] = 'TELEONCE (WLII)'

UPDATE dbo.NPR_STATION SET ARIANNA_CHANNEL_ID = 11995
WHERE [NAME] = 'UNIVISION PR (WLII)'

UPDATE dbo.NPR_STATION SET ARIANNA_CHANNEL_ID = 11085
WHERE [NAME] = 'WAPA DEPORTES (WAPA)'

UPDATE dbo.NPR_STATION SET ARIANNA_CHANNEL_ID = 11001
WHERE [NAME] = 'WAPA TV (WAPA)'

UPDATE dbo.NPR_STATION SET ARIANNA_CHANNEL_ID = 11092
WHERE [NAME] = 'MEGA TV (WTCV)'

UPDATE dbo.NPR_STATION SET ARIANNA_CHANNEL_ID = 11303
WHERE [NAME] = 'ABC PR (WORA)'

UPDATE dbo.NPR_STATION SET ARIANNA_CHANNEL_ID = 11081
WHERE [NAME] = 'FOX PR (WSJX)'

UPDATE dbo.NPR_STATION SET ARIANNA_CHANNEL_ID = 11082
WHERE [NAME] = 'NBC USVI'

UPDATE dbo.NPR_STATION SET ARIANNA_CHANNEL_ID = 11073
WHERE [NAME] = 'CBS PR'

UPDATE dbo.NPR_STATION SET ARIANNA_CHANNEL_ID = 11403
WHERE [NAME] = 'ABC5 PR (WORA)'