EXEC [dbo].[advsp_sql_remove_indexes] '[dbo].[MEDIA_BROADCAST_WORKSHEET_MARKET_DETAIL_DATE]', 'MEDIA_BROADCAST_WORKSHEET_MARKET_DETAIL_DATE_MEDIA_BROADCAST_WORKSHEET_MARKET_DETAIL_ID'
GO

CREATE NONCLUSTERED INDEX [MEDIA_BROADCAST_WORKSHEET_MARKET_DETAIL_DATE_MEDIA_BROADCAST_WORKSHEET_MARKET_DETAIL_ID] ON [dbo].[MEDIA_BROADCAST_WORKSHEET_MARKET_DETAIL_DATE]
(
	[MEDIA_BROADCAST_WORKSHEET_MARKET_DETAIL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

EXEC [dbo].[advsp_sql_remove_indexes] '[dbo].[MEDIA_BROADCAST_WORKSHEET_MARKET_DETAIL_DATE]', 'MEDIA_BROADCAST_WORKSHEET_MARKET_DETAIL_DATE_DATE_MARKET_DETAIL_ID'
GO

CREATE NONCLUSTERED INDEX [MEDIA_BROADCAST_WORKSHEET_MARKET_DETAIL_DATE_DATE_MARKET_DETAIL_ID] ON [dbo].[MEDIA_BROADCAST_WORKSHEET_MARKET_DETAIL_DATE]
(
	[ORDER_NBR] ASC
)
INCLUDE ( 	[MEDIA_BROADCAST_WORKSHEET_MARKET_DETAIL_ID]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO
