CREATE PROCEDURE [dbo].[advsp_job_template_Update_AccountExecutive] 
	@NEW_EMP_CODE VARCHAR(6),
	@COMPONENTS VARCHAR(MAX)
AS
BEGIN

	DECLARE @MGR_COL VARCHAR(20)
	DECLARE @JOB_COMPONENTS TABLE(JOB_NUMBER INT, JOB_COMPONENT_NBR SMALLINT)

	IF ISNULL(@NEW_EMP_CODE, '') = ''
		SET @NEW_EMP_CODE = NULL

	INSERT INTO @JOB_COMPONENTS
		SELECT DISTINCT
			[JOB_NUMBER] = CONVERT(INT, LEFT(items, CHARINDEX(',', items) - 1)),
			[JOB_COMPONENT_NBR] = CONVERT(SMALLINT, RIGHT(items, LEN(items) - CHARINDEX(',', items)))
		FROM
			dbo.udf_split_list(@COMPONENTS, '|')
			
	SELECT @MGR_COL = CAST(AGY_SETTINGS_VALUE AS VARCHAR(20)) FROM AGY_SETTINGS WITH(NOLOCK) WHERE AGY_SETTINGS_CODE = 'TRAFFIC_MGR_COL'

	IF @MGR_COL = 'TR_TITLE1'
		SET @MGR_COL = 'ASSIGN_1'

	IF @MGR_COL = 'TR_TITLE2'
		SET @MGR_COL = 'ASSIGN_2'

	IF @MGR_COL = 'TR_TITLE3'
		SET @MGR_COL = 'ASSIGN_3'
	
	IF @MGR_COL = 'TR_TITLE4'
		SET @MGR_COL = 'ASSIGN_4'
	
	IF @MGR_COL = 'TR_TITLE5'
		SET @MGR_COL = 'ASSIGN_5'

	UPDATE
		JT
	SET
		ASSIGN_1 = CASE WHEN @MGR_COL = 'ASSIGN_1' THEN @NEW_EMP_CODE ELSE ASSIGN_1 END,
		ASSIGN_2 = CASE WHEN @MGR_COL = 'ASSIGN_2' THEN @NEW_EMP_CODE ELSE ASSIGN_2 END,
		ASSIGN_3 = CASE WHEN @MGR_COL = 'ASSIGN_3' THEN @NEW_EMP_CODE ELSE ASSIGN_3 END,
		ASSIGN_4 = CASE WHEN @MGR_COL = 'ASSIGN_4' THEN @NEW_EMP_CODE ELSE ASSIGN_4 END,
		ASSIGN_5 = CASE WHEN @MGR_COL = 'ASSIGN_5' THEN @NEW_EMP_CODE ELSE ASSIGN_5 END
	FROM 
		dbo.JOB_TRAFFIC JT
	INNER JOIN
		@JOB_COMPONENTS JC ON JT.JOB_NUMBER = JC.JOB_NUMBER AND
							  JT.JOB_COMPONENT_NBR = JC.JOB_COMPONENT_NBR
	WHERE
		1 = CASE 
				WHEN @MGR_COL <> 'ASSIGN_1' THEN 1 WHEN ISNULL(ASSIGN_1, '') = ISNULL(@OLD_EMP_CODE, '') THEN 1
				WHEN @MGR_COL <> 'ASSIGN_2' THEN 1 WHEN ISNULL(ASSIGN_2, '') = ISNULL(@OLD_EMP_CODE, '') THEN 1
				WHEN @MGR_COL <> 'ASSIGN_3' THEN 1 WHEN ISNULL(ASSIGN_3, '') = ISNULL(@OLD_EMP_CODE, '') THEN 1
				WHEN @MGR_COL <> 'ASSIGN_4' THEN 1 WHEN ISNULL(ASSIGN_4, '') = ISNULL(@OLD_EMP_CODE, '') THEN 1
				WHEN @MGR_COL <> 'ASSIGN_5' THEN 1 WHEN ISNULL(ASSIGN_5, '') = ISNULL(@OLD_EMP_CODE, '') THEN 1 
				ELSE 0 
			END 
		
	SELECT @@ROWCOUNT

END