
CREATE PROCEDURE [dbo].[advsp_function_options] 
AS
BEGIN
	SET NOCOUNT ON

	SELECT f.FNC_TYPE, 
		f.FNC_ORDER, 
		f.FNC_CODE, 
		f.FNC_DESCRIPTION, 
		f.FNC_HEADING_ID, 
		fh.FNC_HEADING_SEQ, 
		fh.FNC_HEADING_DESC, 
		COALESCE(f2.FNC_CONSOLIDATION, f.FNC_CONSOLIDATION, f.FNC_CODE) AS CONSOL_FNC
	FROM dbo.FUNCTIONS f
	LEFT JOIN dbo.FUNCTIONS f2
		 ON f.FNC_CONSOLIDATION = f2.FNC_CODE
	LEFT JOIN dbo.FNC_HEADING fh 
		ON f.FNC_HEADING_ID = fh.FNC_HEADING_ID
	ORDER BY f.FNC_TYPE, f.FNC_ORDER
END
