IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[advsp_dismiss_alerts_for_employee]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
	DROP PROCEDURE [dbo].[advsp_dismiss_alerts_for_employee]
GO
CREATE PROCEDURE [dbo].[advsp_dismiss_alerts_for_employee] 
@CUT_OFF_DATE SMALLDATETIME,
@EMP_CODE VARCHAR(6)
AS
BEGIN
	INSERT INTO ALERT_RCPT_DISMISSED
	SELECT ALERT_RCPT.* FROM ALERT INNER JOIN ALERT_RCPT ON ALERT.ALERT_ID = ALERT_RCPT.ALERT_ID
	WHERE ALERT_RCPT.EMP_CODE = @EMP_CODE AND ALERT.GENERATED < @CUT_OFF_DATE;

	DELETE AR
	FROM ALERT_RCPT AR INNER JOIN ALERT A ON AR.ALERT_ID = A.ALERT_ID
	WHERE AR.EMP_CODE = @EMP_CODE AND A.GENERATED < @CUT_OFF_DATE;
END
