--DROP PROCEDURE advsp_job_version_update_value
CREATE PROCEDURE advsp_job_version_update_value
@JOB_VERSION_HDR_ID INT,
@JV_TMPLT_DTL_ID INT,
@JOB_VER_VALUE SQL_VARIANT
AS
BEGIN
	IF EXISTS (SELECT JOB_VER_HDR_ID FROM JOB_VER_DTL WHERE JOB_VER_HDR_ID = @JOB_VERSION_HDR_ID AND JV_TMPLT_DTL_ID = @JV_TMPLT_DTL_ID)
	BEGIN
		UPDATE JOB_VER_DTL SET JOB_VER_VALUE = @JOB_VER_VALUE WHERE JOB_VER_HDR_ID = @JOB_VERSION_HDR_ID AND JV_TMPLT_DTL_ID = @JV_TMPLT_DTL_ID;
	END
	ELSE
	BEGIN
		INSERT INTO JOB_VER_DTL (JOB_VER_HDR_ID, JV_TMPLT_DTL_ID, JOB_VER_VALUE) VALUES (@JOB_VERSION_HDR_ID, @JV_TMPLT_DTL_ID, @JOB_VER_VALUE);
	END
END