CREATE PROCEDURE [dbo].[advsp_gl_xref_export_export] 
	@RECORD_SOURCE_ID INT
AS
BEGIN

	SELECT
		[TargetAccountCode] = GLX.TARGET_GLACODE,
		[GeneralLedgerAccountCode] = GLXD.GLACODE
	FROM
		dbo.GLACCOUNT_XREF_EXPORT GLX
	LEFT OUTER JOIN
		dbo.GLACCOUNT_XREF_EXPORT_DETAIL GLXD ON GLX.GLACCOUNT_XREF_EXPORT_ID = GLXD.GLACCOUNT_XREF_EXPORT_ID
	WHERE
		GLX.RECORD_SOURCE_ID = @RECORD_SOURCE_ID

END