CREATE PROCEDURE [dbo].[advsp_load_drpt_job_service_fee]
	@CRITERIA SMALLINT,
	@FROM_DATE SMALLDATETIME,
	@TO_DATE SMALLDATETIME
AS
BEGIN

/*

CRITERIA
-------------
Fee Start Date = 0
Create Date = 1

*/

	SELECT
		[ID] = JOB_SERVICE_FEE.JOB_SERVICE_FEE_ID,
		[Description] = JOB_SERVICE_FEE.FEE_DESCRIPTION,
		[OfficeCode] = JOB_LOG.OFFICE_CODE,
		[OfficeName] = OFFICE.OFFICE_NAME,
		[ClientCode] = JOB_LOG.CL_CODE,
		[ClientName] = CLIENT.CL_NAME,
		[DivisionCode] = JOB_LOG.DIV_CODE,
		[DivisionName] = DIVISION.DIV_NAME,
		[ProductCode] = JOB_LOG.PRD_CODE,
		[ProductName] = PRODUCT.PRD_DESCRIPTION,
		[CampaignID] = JOB_LOG.CMP_IDENTIFIER,
		[CampaignCode] = CAMPAIGN.CMP_CODE,
		[CampaignName] = CAMPAIGN.CMP_NAME,
		[JobNumber] = JOB_SERVICE_FEE.JOB_NUMBER,
		[JobDescription] = JOB_LOG.JOB_DESC,
		[JobComponentNumber] = JOB_SERVICE_FEE.JOB_COMPONENT_NBR,
		[JobComponentDescription] = JOB_COMPONENT.JOB_COMP_DESC,
		[SalesClassCode] = JOB_LOG.SC_CODE,
		[SalesClassDescription] = SALES_CLASS.SC_DESCRIPTION,
		[FeeSetupDate] = JOB_SERVICE_FEE.FEE_SETUP_DATE,
		[FeeStartDate] = JOB_SERVICE_FEE.FEE_START_DATE,
		[FeeEndDate] = JOB_SERVICE_FEE.FEE_END_DATE,
		[Frequency] = CASE WHEN JOB_SERVICE_FEE.FREQUENCY = 1 THEN 'Weekly'
						   WHEN JOB_SERVICE_FEE.FREQUENCY = 2 THEN 'Monthly' 
						   WHEN JOB_SERVICE_FEE.FREQUENCY = 3 THEN 'Annually' END,
		[NumberOfFees] = JOB_SERVICE_FEE.NUMBER_OF_FEES,
		[FeeTypeDescription] = SERVICE_FEE_TYPE.[DESCRIPTION],
		[FunctionCode] = JOB_SERVICE_FEE.FNC_CODE,
		[FunctionDescription] = FUNCTIONS.FNC_DESCRIPTION,
		[Amount] = JOB_SERVICE_FEE.FEE_AMT,
		[MaxAmount] = JOB_SERVICE_FEE.MAX_AMT,
		[ContractNotes] = JOB_SERVICE_FEE.CONTACT_INFO,
		[ClientComments] = JOB_SERVICE_FEE.CLIENT_COMMENT,
		[CreatedDate] = JOB_SERVICE_FEE.CREATE_DATE,
		[CreatedByUserCode] = JOB_SERVICE_FEE.CREATED_BY,
		[ModifiedDate] = JOB_SERVICE_FEE.MODIFY_DATE,
		[ModifiedByUserCode] = JOB_SERVICE_FEE.MODIFIED_BY
	FROM
		dbo.JOB_SERVICE_FEE JOIN
		dbo.JOB_COMPONENT ON JOB_SERVICE_FEE.JOB_NUMBER = JOB_COMPONENT.JOB_NUMBER AND
							 JOB_SERVICE_FEE.JOB_COMPONENT_NBR = JOB_COMPONENT.JOB_COMPONENT_NBR JOIN
		dbo.JOB_LOG ON JOB_SERVICE_FEE.JOB_NUMBER = JOB_LOG.JOB_NUMBER LEFT OUTER JOIN
		dbo.OFFICE ON JOB_LOG.OFFICE_CODE = OFFICE.OFFICE_CODE JOIN
		dbo.CLIENT ON JOB_LOG.CL_CODE = CLIENT.CL_CODE JOIN
		dbo.DIVISION ON JOB_LOG.CL_CODE = DIVISION.CL_CODE AND
						JOB_LOG.DIV_CODE = DIVISION.DIV_CODE JOIN
		dbo.PRODUCT ON JOB_LOG.CL_CODE = PRODUCT.CL_CODE AND
					   JOB_LOG.DIV_CODE = PRODUCT.DIV_CODE  AND
					   JOB_LOG.PRD_CODE = PRODUCT.PRD_CODE LEFT OUTER JOIN
		dbo.CAMPAIGN ON JOB_LOG.CMP_IDENTIFIER = CAMPAIGN.CMP_IDENTIFIER JOIN
		dbo.SALES_CLASS ON JOB_LOG.SC_CODE = SALES_CLASS.SC_CODE JOIN
		dbo.FUNCTIONS ON JOB_SERVICE_FEE.FNC_CODE = FUNCTIONS.FNC_CODE LEFT OUTER JOIN
		dbo.SERVICE_FEE_TYPE ON JOB_COMPONENT.SERVICE_FEE_TYPE_ID = SERVICE_FEE_TYPE.SERVICE_FEE_TYPE_ID
	WHERE
		1 = CASE 
				WHEN @CRITERIA = 0 THEN 
					CASE
						WHEN JOB_SERVICE_FEE.FEE_START_DATE >= @FROM_DATE AND JOB_SERVICE_FEE.FEE_START_DATE <= @TO_DATE THEN 1
						ELSE 0
					END
				WHEN @CRITERIA = 1 THEN 
					CASE
						WHEN JOB_SERVICE_FEE.CREATE_DATE >= @FROM_DATE AND JOB_SERVICE_FEE.CREATE_DATE <= @TO_DATE THEN 1
						ELSE 0
					END
				ELSE 0 
			END
		
END

