IF EXISTS ( SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID( N'[dbo].[advsp_ap_vendor_search_purchase_orders]') AND OBJECTPROPERTY( id, N'IsProcedure' ) = 1 )
	DROP PROCEDURE [dbo].[advsp_ap_vendor_search_purchase_orders]
GO

CREATE PROCEDURE [dbo].[advsp_ap_vendor_search_purchase_orders]
AS
BEGIN
	SET NOCOUNT ON;
		
	SELECT
		[Number] = U.Number,
		[VendorName] = V.VN_NAME,
		[VendorCode] = V.VN_CODE
	FROM [dbo].VENDOR V
		INNER JOIN (
		SELECT
			VN_CODE,
			[Number] = O.PO_NUMBER
		FROM
			[dbo].PURCHASE_ORDER O
			INNER JOIN [dbo].PURCHASE_ORDER_DET D ON O.PO_NUMBER = D.PO_NUMBER 
			LEFT OUTER JOIN (
				SELECT SUM(AP_GL_AMT) AP_GL_AMT, PO_NUMBER, PO_LINE_NUMBER
				FROM AP_GL_DIST
				WHERE (MODIFY_DELETE IS NULL OR MODIFY_DELETE = 0)
				AND PO_NUMBER IS NOT NULL
				GROUP BY PO_NUMBER, PO_LINE_NUMBER) A ON A.PO_NUMBER = D.PO_NUMBER AND A.PO_LINE_NUMBER = D.LINE_NUMBER 
		WHERE
					(VOID_FLAG IS NULL OR VOID_FLAG = 0)
			AND		(O.PO_COMPLETE IS NULL OR O.PO_COMPLETE = 0)
			AND		(D.PO_COMPLETE IS NULL OR D.PO_COMPLETE = 0)
			AND		D.JOB_NUMBER IS NULL

	UNION

		SELECT
			VN_CODE,
			[Number] = O.PO_NUMBER
		FROM
			[dbo].PURCHASE_ORDER O
			INNER JOIN [dbo].PURCHASE_ORDER_DET D ON O.PO_NUMBER = D.PO_NUMBER 
			LEFT OUTER JOIN [dbo].AP_PRODUCTION A ON D.PO_NUMBER = A.PO_NUMBER AND D.LINE_NUMBER = A.PO_LINE_NUMBER AND	(A.MODIFY_DELETE IS NULL OR A.MODIFY_DELETE=0)
		WHERE
					(VOID_FLAG IS NULL OR VOID_FLAG = 0)
			AND		(O.PO_COMPLETE IS NULL OR O.PO_COMPLETE = 0)
			AND		(D.PO_COMPLETE IS NULL OR D.PO_COMPLETE = 0)
			AND		D.JOB_NUMBER IS NOT NULL
		) U
		ON V.VN_CODE = U.VN_CODE
		ORDER BY
			U.Number DESC
			
END
GO
