
CREATE PROCEDURE dbo.advsp_get_missing_time 
	@emp_super		int,		-- 0-emp; 1-super; 2-IT Contact
	@emp_code		varchar(6),	-- can be either emp or super
	@end_date		datetime,
	@Day_Week		int			-- 0-Daily; 1-Weekly
AS
SET NOCOUNT ON

DECLARE @CT AS integer

If @Day_Week = 0 --Daily
  BEGIN
  
	-- Check if missing time within emp/super/IT grace period
	SELECT @CT = count(*)
	FROM dbo.MISSING_TIME_DTL
	WHERE EMP_CODE = @emp_code 
	  AND WORKDATE <= @end_date
	  AND HOURS_WORKED < STANDARD_HRS
	  
	If @emp_super = 2
		SELECT @CT = count(*)
		FROM dbo.MISSING_TIME_DTL
		WHERE WORKDATE <= @end_date
		AND HOURS_WORKED < STANDARD_HRS
  
	-- If so, return all days missing time
	IF @CT > 0 
	  BEGIN
		If @emp_super = 0
			SELECT EMP_CODE, WORKDATE, DAYOFWEEK, WEEKOFDATE, STANDARD_HRS, HOURS_WORKED, VARIANCE
			FROM dbo.MISSING_TIME_DTL
			WHERE EMP_CODE = @emp_code 
			  AND HOURS_WORKED < STANDARD_HRS
			ORDER BY WORKDATE

		If @emp_super = 1
			SELECT EMP_CODE, WORKDATE, DAYOFWEEK, WEEKOFDATE, STANDARD_HRS, HOURS_WORKED, VARIANCE
			FROM dbo.MISSING_TIME_DTL
			WHERE SUPERVISOR_CODE = @emp_code 
			  AND HOURS_WORKED < STANDARD_HRS
			ORDER BY EMP_CODE, WORKDATE

		If @emp_super = 2
			SELECT DISTINCT EMP_CODE
			INTO #EMPS
			FROM dbo.MISSING_TIME_DTL
			WHERE  WORKDATE <= @end_date
			  AND HOURS_WORKED < STANDARD_HRS
  
			SELECT MTD.EMP_CODE, WORKDATE, DAYOFWEEK, WEEKOFDATE, STANDARD_HRS, HOURS_WORKED, VARIANCE
			FROM dbo.MISSING_TIME_DTL MTD
			INNER JOIN #EMPS ON #EMPS.EMP_CODE = MTD.EMP_CODE
			WHERE HOURS_WORKED < STANDARD_HRS
			ORDER BY MTD.EMP_CODE, WORKDATE 
	  END
	END

Else	--Weekly

  BEGIN
	
	If @emp_super = 0
	  BEGIN
		SELECT EMP_CODE, WEEKOFDATE, SUM(STANDARD_HRS) AS STANDARD_HRS, SUM(HOURS_WORKED) AS HOURS_WORKED
		INTO #TMP11
		FROM dbo.MISSING_TIME_DTL
		WHERE EMP_CODE = @emp_code AND WORKDATE <= @end_date
		GROUP BY EMP_CODE, WEEKOFDATE
		HAVING SUM(STANDARD_HRS) > SUM(HOURS_WORKED)
		
		SELECT @CT = count(*) FROM #TMP11
		IF @CT > 0
			BEGIN
				SELECT EMP_CODE, WEEKOFDATE, SUM(STANDARD_HRS) AS STANDARD_HRS, SUM(HOURS_WORKED) AS HOURS_WORKED
				INTO #TMP2
				FROM dbo.MISSING_TIME_DTL
				WHERE EMP_CODE = @emp_code
				GROUP BY EMP_CODE, WEEKOFDATE
				HAVING SUM(STANDARD_HRS) > SUM(HOURS_WORKED)
			
				SELECT MTD.EMP_CODE, MTD.WORKDATE, MTD.DAYOFWEEK, MTD.WEEKOFDATE, MTD.STANDARD_HRS, MTD.HOURS_WORKED, MTD.VARIANCE
				FROM dbo.MISSING_TIME_DTL MTD
				  INNER JOIN #TMP2 ON #TMP2.EMP_CODE = MTD.EMP_CODE AND #TMP2.WEEKOFDATE = MTD.WEEKOFDATE
				WHERE MTD.EMP_CODE = @emp_code 
				ORDER BY MTD.WORKDATE
			END
	  END
	
	If @emp_super = 1
	  BEGIN
		SELECT EMP_CODE, WEEKOFDATE, SUM(STANDARD_HRS) AS STANDARD_HRS, SUM(HOURS_WORKED) AS HOURS_WORKED
		INTO #TMP12
		FROM dbo.MISSING_TIME_DTL
		WHERE SUPERVISOR_CODE = @emp_code 
		  AND WORKDATE <= @end_date
		GROUP BY EMP_CODE, WEEKOFDATE
		HAVING SUM(STANDARD_HRS) > SUM(HOURS_WORKED)
		
		SELECT @CT = count(*) FROM #TMP12
		IF @CT > 0
			BEGIN
				SELECT EMP_CODE, WEEKOFDATE, SUM(STANDARD_HRS) AS STANDARD_HRS, SUM(HOURS_WORKED) AS HOURS_WORKED
				INTO #TMP21
				FROM dbo.MISSING_TIME_DTL
				WHERE SUPERVISOR_CODE = @emp_code 
				GROUP BY EMP_CODE, WEEKOFDATE
				HAVING SUM(STANDARD_HRS) > SUM(HOURS_WORKED)
		
				SELECT MTD.EMP_CODE, MTD.WORKDATE, MTD.DAYOFWEEK, MTD.WEEKOFDATE, MTD.STANDARD_HRS, MTD.HOURS_WORKED, MTD.VARIANCE
				FROM dbo.MISSING_TIME_DTL MTD
				  INNER JOIN #TMP21 ON #TMP21.EMP_CODE = MTD.EMP_CODE AND #TMP21.WEEKOFDATE = MTD.WEEKOFDATE
				WHERE MTD.SUPERVISOR_CODE = @emp_code 
				ORDER BY MTD.EMP_CODE, MTD.WORKDATE
			END
	  END
	
	If @emp_super = 2
	  BEGIN
		SELECT EMP_CODE, WEEKOFDATE, SUM(STANDARD_HRS) AS STANDARD_HRS, SUM(HOURS_WORKED) AS HOURS_WORKED
		INTO #TMP13
		FROM dbo.MISSING_TIME_DTL
		WHERE WORKDATE <= @end_date
		GROUP BY EMP_CODE, WEEKOFDATE
		HAVING SUM(STANDARD_HRS) > SUM(HOURS_WORKED)
		
		SELECT @CT = count(*) FROM #TMP13
		IF @CT > 0
			BEGIN
				SELECT EMP_CODE, WEEKOFDATE, SUM(STANDARD_HRS) AS STANDARD_HRS, SUM(HOURS_WORKED) AS HOURS_WORKED
				INTO #TMP22
				FROM dbo.MISSING_TIME_DTL
				GROUP BY EMP_CODE, WEEKOFDATE
				HAVING SUM(STANDARD_HRS) > SUM(HOURS_WORKED)
		
				SELECT MTD.EMP_CODE, MTD.WORKDATE, MTD.DAYOFWEEK, MTD.WEEKOFDATE, MTD.STANDARD_HRS, MTD.HOURS_WORKED, MTD.VARIANCE
				FROM dbo.MISSING_TIME_DTL MTD
				INNER JOIN #TMP22 ON #TMP22.EMP_CODE = MTD.EMP_CODE AND #TMP22.WEEKOFDATE = MTD.WEEKOFDATE
				ORDER BY MTD.EMP_CODE, MTD.WORKDATE
			END
	  END
  END
