CREATE PROCEDURE [dbo].[advsp_media_plan_estimate_template_tactics]
	@MEDIA_PLAN_ESTIMATE_TEMPLATE_ID int
AS

SELECT
	Selected = CAST(CASE WHEN mpett.MEDIA_TACTIC_ID IS NOT NULL THEN 1 ELSE 0 END as bit),
	MediaTacticID = mt.MEDIA_TACTIC_ID,
	MediaTactic = mt.[DESCRIPTION]
FROM dbo.MEDIA_TACTIC mt
	LEFT OUTER JOIN dbo.MEDIA_PLAN_ESTIMATE_TEMPLATE_TACTIC mpett ON mt.MEDIA_TACTIC_ID = mpett.MEDIA_TACTIC_ID AND mpett.MEDIA_PLAN_ESTIMATE_TEMPLATE_ID = @MEDIA_PLAN_ESTIMATE_TEMPLATE_ID
WHERE mt.IS_INACTIVE = 0
ORDER BY mt.[DESCRIPTION]
GO
