CREATE PROCEDURE advsp_media_manager_rfp_recipients
	@MEDIA_RFP_HEADER_IDs varchar(max)
AS

SELECT DISTINCT
	[VendorRepCode] = CASE WHEN VR.VR_CODE IS NOT NULL THEN VR.VR_CODE ELSE VC.VC_CODE END,
	[VendorCode] = MRH.VN_CODE,
	[Name] = CASE WHEN VR.VR_CODE IS NOT NULL THEN 
						COALESCE(VR.VR_FNAME, '') + ' ' + CASE WHEN NULLIF(VR.VR_MI,'') IS NULL THEN '' ELSE VR.VR_MI + '. ' END + COALESCE(VR.VR_LNAME, '')
				  ELSE
						COALESCE(VC.VC_FNAME, '') + ' ' + CASE WHEN NULLIF(VC.VC_MI,'') IS NULL THEN '' ELSE VC.VC_MI + '. ' END + COALESCE(VC.VC_LNAME, '')
				  END,
	[Email] = CASE WHEN VR.VR_CODE IS NOT NULL THEN VR.EMAIL_ADDRESS ELSE VC.EMAIL_ADDRESS END
FROM dbo.MEDIA_RFP_HEADER MRH
	INNER JOIN dbo.ALERT A ON MRH.ALERT_ID = A.ALERT_ID 
	INNER JOIN dbo.ALERT_COMMENT AC ON A.ALERT_ID = AC.ALERT_ID 
	LEFT OUTER JOIN dbo.VEN_REP VR ON AC.VR_CODE = VR.VR_CODE AND VR.VN_CODE = MRH.VN_CODE 
	LEFT OUTER JOIN dbo.VEN_CONT VC ON AC.VC_CODE = VC.VC_CODE AND VC.VN_CODE = MRH.VN_CODE 
WHERE MEDIA_RFP_HEADER_ID IN (SELECT * FROM dbo.udf_split_list(@MEDIA_RFP_HEADER_IDs, ','))
AND (
		NULLIF(AC.VC_CODE, '') IS NOT NULL 
	OR
		NULLIF(AC.VR_CODE, '') IS NOT NULL
	)

GO