if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[advsp_job_detail_oop_by_function_load_minimized]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [dbo].[advsp_job_detail_oop_by_function_load_minimized]
GO

CREATE PROCEDURE [dbo].[advsp_job_detail_oop_by_function_load_minimized](
	@DATE_TYPE AS int,
	@START_DATE AS smalldatetime,
	@END_DATE AS smalldatetime,
	@SHOW_JOBS_WO_DETAILS AS bit,
	@INCLUDE_CLOSED AS bit,
	@et_date_cutoff smalldatetime,
	@io_date_cutoff smalldatetime, 
	@ap_pp_cutoff varchar(6), 	
	@ClientCodeList varchar(max),
	@ClientDivisionCodeList varchar(max),
	@ClientDivisionProductCodeList varchar(max),
	@AECodeList varchar(max),
	@CampaignIDList varchar(max),
	--@IncludeBilledRange bit,
	--@BILLED_START_PERIOD varchar(6),
	--@BILLED_END_PERIOD varchar(6),
	--@DateOption varchar(10),
	--@Current_StartDate smalldatetime,
	--@Current_EndDate smalldatetime,
	--@CURRENT_PERIOD varchar(6),
	@JobTypeList varchar(max),
	@OOPFunctionList varchar(max)
)
AS
BEGIN

	DECLARE @TRAFFIC_MGR_COL varchar(20), @debug bit = 0	

	DECLARE @CurrentPeriodStartDate smalldatetime, @CurrentPeriodEndDate smalldatetime, @PriorStartDate smalldatetime, @PriorEndDate smalldatetime, @PriorPeriod varchar(6), @Year int

	--SELECT @Year = PPGLYEAR - 1
	--FROM POSTPERIOD
	--WHERE PPPERIOD = @CURRENT_PERIOD

	--SELECT @PriorPeriod = CAST(@Year AS VARCHAR(4)) + '12'
	--SELECT @PriorEndDate = PPENDDATE
	--FROM POSTPERIOD
	--WHERE PPPERIOD = @PriorPeriod

	--SELECT @PriorPeriod,@PriorEndDate

	--SELECT @CurrentPeriodStartDate = PPSRTDATE
	--FROM POSTPERIOD
	--WHERE PPPERIOD = @CURRENT_PERIOD

	--SELECT @CurrentPeriodEndDate = PPENDDATE
	--FROM POSTPERIOD
	--WHERE PPPERIOD = @CURRENT_PERIOD

	--if @DateOption = 'Current'
	--Begin
	--	if @Current_EndDate <> ''
	--	Begin
	--	 SET @et_date_cutoff = @Current_EndDate
	--	 SET @io_date_cutoff = @Current_EndDate
	--	End

	--	if @CURRENT_PERIOD <> ''
	--	Begin
	--	 SET @ap_pp_cutoff = @CURRENT_PERIOD
	--	End
	--End	

--SELECT @et_date_cutoff,@io_date_cutoff,@ap_pp_cutoff

	CREATE TABLE #JOB 
	(
		[ID] [int] IDENTITY(1,1) NOT NULL,
		[JobNumber] int,
		[JobComponentNumber] smallint,
		[OfficeCode] varchar(4),
		[OfficeDescription] varchar(30),
		[ClientCode] varchar(6) COLLATE SQL_Latin1_General_CP1_CS_AS,
		[ClientDescription] varchar(40),
		[DivisionCode] varchar(6) COLLATE SQL_Latin1_General_CP1_CS_AS,
		[DivisionDescription] varchar(40),
		[ProductCode] varchar(6) COLLATE SQL_Latin1_General_CP1_CS_AS,
		[ProductDescription] varchar(40),
		[SalesClassCode] varchar(6),
		[SalesClassDescription] varchar(30),
		[JobDescription] varchar(60),	
		[ComponentNumber] smallint,
		[ComponentDescription] varchar(60),
	);	
		
	CREATE TABLE #JOB_DETAIL 
	(
		[ID] [int] IDENTITY(1,1) NOT NULL,
		[ResourceType] varchar(3),
		[JobNumber] int,
		[JobComponentNumber] smallint,
		[FunctionType] varchar(1),
		[FunctionCode] varchar(6)  COLLATE SQL_Latin1_General_CP1_CS_AS,
		[FunctionDescription] varchar(30),
		[ItemID] int,
		[ItemSequenceNumber] int,
		[Hours] decimal(18,2),
		[EstimateHours] decimal(18,2),
		[FeeEstimate] decimal(18, 2),
		[OOPEstimate] decimal(18, 2),
		[EstimateTotal] decimal(18, 2),
		[FeeTotal] decimal(18, 2),
		[BillableOOPTotal] decimal(18, 2),
		[BillableTotal] decimal(18, 2)
	);

	SELECT 
		@TRAFFIC_MGR_COL = CAST(AGYS.AGY_SETTINGS_VALUE AS varchar(20)) 
	FROM 
		[dbo].[AGY_SETTINGS] AS AGYS
	WHERE 
		AGYS.AGY_SETTINGS_CODE = 'TRAFFIC_MGR_COL'	

IF @debug = 1 SELECT getdate() 'before JOB'		
	INSERT INTO #JOB
	SELECT
		[JobNumber] = JC.JOB_NUMBER,
		[JobComponentNumber] = JC.JOB_COMPONENT_NBR,
		[OfficeCode] = J.OFFICE_CODE,
		[OfficeDescription] = O.OFFICE_NAME,
		[ClientCode] = J.CL_CODE,
		[ClientDescription] = C.CL_NAME,
		[DivisionCode] = J.DIV_CODE,
		[DivisionDescription] = D.DIV_NAME,
		[ProductCode] = J.PRD_CODE,
		[ProductDescription] = P.PRD_DESCRIPTION,
		[SalesClassCode] = J.SC_CODE,
		[SalesClassDescription] = SC.SC_DESCRIPTION,
		[JobDescription] = J.JOB_DESC,
		[ComponentNumber] = JC.JOB_COMPONENT_NBR,
		[ComponentDescription] = JC.JOB_COMP_DESC
	FROM 
		[dbo].[JOB_COMPONENT] AS JC INNER JOIN
		[dbo].[JOB_LOG] AS J ON J.JOB_NUMBER = JC.JOB_NUMBER LEFT OUTER JOIN
		(SELECT	DISTINCT
			JOB_NUMBER
		 FROM
			dbo.JOB_COMPONENT
		 WHERE
			JOB_PROCESS_CONTRL NOT IN (6, 12)) COMPOPEN ON J.JOB_NUMBER = COMPOPEN.JOB_NUMBER LEFT OUTER JOIN
		[dbo].[OFFICE] AS O ON O.OFFICE_CODE = J.OFFICE_CODE INNER JOIN
		[dbo].[CLIENT] AS C ON C.CL_CODE = J.CL_CODE INNER JOIN
		[dbo].[DIVISION] AS D ON D.CL_CODE = J.CL_CODE AND
								 D.DIV_CODE = J.DIV_CODE INNER JOIN
		[dbo].[PRODUCT] AS P ON P.CL_CODE = J.CL_CODE AND
								P.DIV_CODE = J.DIV_CODE AND
								P.PRD_CODE = J.PRD_CODE LEFT OUTER JOIN
		[dbo].[SALES_CLASS] AS SC ON SC.SC_CODE = J.SC_CODE INNER JOIN
		[dbo].[EMPLOYEE_CLOAK] AS EMP ON EMP.EMP_CODE = JC.EMP_CODE LEFT OUTER JOIN
		[dbo].[JOB_TYPE] AS JT ON JT.JT_CODE = JC.JT_CODE LEFT OUTER JOIN
		[dbo].[DEPT_TEAM] AS DT ON DT.DP_TM_CODE = JC.DP_TM_CODE LEFT OUTER JOIN
		[dbo].[CDP_CONTACT_HDR] AS CC ON CC.CDP_CONTACT_ID = JC.CDP_CONTACT_ID LEFT OUTER JOIN
		[dbo].[JOB_PROC_CONTROLS] AS JPC ON JPC.JOB_PROCESS_CONTRL = JC.JOB_PROCESS_CONTRL LEFT OUTER JOIN
		[dbo].[SALES_TAX] AS ST ON ST.TAX_CODE = JC.TAX_CODE LEFT OUTER JOIN
		[dbo].[MARKET] AS M ON M.MARKET_CODE = JC.MARKET_CODE LEFT OUTER JOIN
		[dbo].[FISCAL_PERIOD] AS FP ON FP.FISCAL_PERIOD_CODE = JC.FISCAL_PERIOD_CODE LEFT OUTER JOIN
		[dbo].[ALERT_NOTIFY_HDR] AS AA ON AA.ALRT_NOTIFY_HDR_ID = JC.ALRT_NOTIFY_HDR_ID LEFT OUTER JOIN
		[dbo].[JOB_LOG_UDV1] AS JUDV1 ON JUDV1.UDV_CODE = J.UDV1_CODE LEFT OUTER JOIN
		[dbo].[JOB_LOG_UDV2] AS JUDV2 ON JUDV2.UDV_CODE = J.UDV2_CODE LEFT OUTER JOIN
		[dbo].[JOB_LOG_UDV3] AS JUDV3 ON JUDV3.UDV_CODE = J.UDV3_CODE LEFT OUTER JOIN
		[dbo].[JOB_LOG_UDV4] AS JUDV4 ON JUDV4.UDV_CODE = J.UDV4_CODE LEFT OUTER JOIN
		[dbo].[JOB_LOG_UDV5] AS JUDV5 ON JUDV5.UDV_CODE = J.UDV5_CODE LEFT OUTER JOIN
		[dbo].[JOB_CMP_UDV1] AS JCUDV1 ON JCUDV1.UDV_CODE = JC.UDV1_CODE LEFT OUTER JOIN
		[dbo].[JOB_CMP_UDV2] AS JCUDV2 ON JCUDV2.UDV_CODE = JC.UDV2_CODE LEFT OUTER JOIN
		[dbo].[JOB_CMP_UDV3] AS JCUDV3 ON JCUDV3.UDV_CODE = JC.UDV3_CODE LEFT OUTER JOIN
		[dbo].[JOB_CMP_UDV4] AS JCUDV4 ON JCUDV4.UDV_CODE = JC.UDV4_CODE LEFT OUTER JOIN
		[dbo].[JOB_CMP_UDV5] AS JCUDV5 ON JCUDV5.UDV_CODE = JC.UDV5_CODE LEFT OUTER JOIN 
		[dbo].[CAMPAIGN] AS CAMP ON J.CMP_IDENTIFIER = CAMP.CMP_IDENTIFIER LEFT OUTER JOIN
		[dbo].[ACCT_NUMBER] AS AN ON AN.ACCT_NBR = JC.ACCT_NBR LEFT OUTER JOIN
		(SELECT CL_CODE FROM [dbo].[AGENCY_CLIENTS]) AS ACL ON ACL.CL_CODE = C.CL_CODE LEFT OUTER JOIN 
		[dbo].[SERVICE_FEE_TYPE] AS SFT ON SFT.SERVICE_FEE_TYPE_ID = JC.SERVICE_FEE_TYPE_ID LEFT OUTER JOIN
		[dbo].[JOB_TRAFFIC] AS JOBT ON JOBT.JOB_NUMBER = JC.JOB_NUMBER AND JOBT.JOB_COMPONENT_NBR = JC.JOB_COMPONENT_NBR LEFT OUTER JOIN
		[dbo].[TRAFFIC] AS T ON T.TRF_CODE = JOBT.TRF_CODE LEFT OUTER JOIN
		(SELECT
				PM.JOB_NUMBER,
				PM.JOB_COMPONENT_NBR,
				PM.[MANAGER_CODE],
				[MANAGER] =  CASE WHEN PM.MANAGER_CODE IS NULL THEN NULL ELSE COALESCE((RTRIM(PEMP.EMP_FNAME) + ' '),'') + COALESCE((PEMP.EMP_MI + '. '),'') + COALESCE(PEMP.EMP_LNAME,'') END
			FROM
				(SELECT
					JT.JOB_NUMBER,
					JT.JOB_COMPONENT_NBR,
					[MANAGER_CODE] = CASE @TRAFFIC_MGR_COL  WHEN 'TR_TITLE1' THEN JT.ASSIGN_1   							
															WHEN 'TR_TITLE2' THEN JT.ASSIGN_2   							
															WHEN 'TR_TITLE3' THEN JT.ASSIGN_3  							
															WHEN 'TR_TITLE4' THEN JT.ASSIGN_4   							
															WHEN 'TR_TITLE5' THEN JT.ASSIGN_5  							
															ELSE NULL  END  					       
				FROM 
					[dbo].[JOB_TRAFFIC] AS JT) AS PM LEFT OUTER JOIN
					[dbo].[EMPLOYEE_CLOAK] AS PEMP ON PEMP.EMP_CODE = PM.[MANAGER_CODE]) AS PJM ON PJM.JOB_NUMBER = JC.JOB_NUMBER AND 
																								   PJM.JOB_COMPONENT_NBR = JC.JOB_COMPONENT_NBR LEFT OUTER JOIN
		(SELECT 
			JOB_NUMBER, 
			JOB_COMPONENT_NBR, 
			PROCESS_DATE = MAX(PROCESS_DATE) 
		 FROM 
			dbo.JOB_PROCESS_LOG 
		 GROUP BY 
			JOB_NUMBER, 
			JOB_COMPONENT_NBR) JPL_DATE ON JC.JOB_NUMBER = JPL_DATE.JOB_NUMBER AND
										   JC.JOB_COMPONENT_NBR = JPL_DATE.JOB_COMPONENT_NBR
	WHERE
		1 = CASE WHEN @DATE_TYPE = 1 THEN CASE WHEN J.CREATE_DATE >= @START_DATE AND J.CREATE_DATE <= CONVERT(DATETIME, @END_DATE +' 23:59:00', 101) THEN 1 ELSE 0 END
				 WHEN @DATE_TYPE = 2 THEN CASE WHEN JC.JOB_COMP_DATE >= @START_DATE AND JC.JOB_COMP_DATE <= CONVERT(DATETIME, @END_DATE +' 23:59:00', 101) THEN 1 ELSE 0 END
				 WHEN @DATE_TYPE = 3 THEN CASE WHEN JC.JOB_FIRST_USE_DATE >= @START_DATE AND JC.JOB_FIRST_USE_DATE <= CONVERT(DATETIME, @END_DATE +' 23:59:00', 101) THEN 1 ELSE 0 END
				 WHEN @DATE_TYPE = 4 THEN CASE WHEN JC.[START_DATE] >= @START_DATE AND JC.[START_DATE] <= CONVERT(DATETIME, @END_DATE +' 23:59:00', 101) THEN 1 ELSE 0 END 
				 WHEN @DATE_TYPE = 5 THEN 1 ElSE 1 END
		AND 1 = CASE WHEN @INCLUDE_CLOSED = 0 AND (JPC.JOB_PROCESS_DESC = 'Closed' OR JPC.JOB_PROCESS_DESC = 'Archive') THEN 0 ELSE 1 END
		AND	(@ClientCodeList IS NULL OR (@ClientCodeList IS NOT NULL AND J.CL_CODE IN (SELECT * FROM dbo.udf_split_list(@ClientCodeList, ','))))
		AND	(@ClientDivisionCodeList IS NULL OR (@ClientDivisionCodeList IS NOT NULL AND J.CL_CODE + '|' + J.DIV_CODE IN (SELECT * FROM dbo.udf_split_list(@ClientDivisionCodeList, ','))))
		AND	(@ClientDivisionProductCodeList IS NULL OR (@ClientDivisionProductCodeList IS NOT NULL AND J.CL_CODE + '|' + J.DIV_CODE + '|' + J.PRD_CODE IN (SELECT * FROM dbo.udf_split_list(@ClientDivisionProductCodeList, ','))))
		AND	(@AECodeList IS NULL OR (@AECodeList IS NOT NULL AND JC.EMP_CODE IN (SELECT * from dbo.udf_split_list(@AECodeList, ','))))
		AND (@CampaignIDList IS NULL OR (@CampaignIDList IS NOT NULL AND J.CMP_IDENTIFIER IN (SELECT * FROM dbo.udf_split_list(@CampaignIDList, ','))))
		AND (@JobTypeList IS NULL OR (@JobTypeList IS NOT NULL AND JC.JT_CODE IN (SELECT * FROM dbo.udf_split_list(@JobTypeList, ','))))
OPTION (RECOMPILE)
IF @debug = 1 SELECT getdate() 'after JOB'	

	--AB
	--INSERT INTO #JOB_DETAIL
	--SELECT
	--	[ResourceType] = 'AB',
	--	[JobNumber] = AB.JOB_NUMBER,
	--	[JobComponentNumber] = AB.JOB_COMPONENT_NBR,
	--	[FunctionType] = F.FNC_TYPE,
	--	[FunctionCode] = AB.FNC_CODE,
	--	[FunctionDescription] = F.FNC_DESCRIPTION,
	--	[ItemID] = AB.AB_ID,
	--	[ItemSequenceNumber] = AB.SEQ_NBR,
	--	[Hours] = 0,
	--	[EstimateHours] = 0,
	--	[FeeEstimate] = 0,
	--	[OOPEstimate] = 0,
	--	[EstimateTotal] = 0,
	--	[FeeTotal] = 0,
	--	[BillableOOPTotal] = 0,
	--	[BillableTotal] = 0
	--FROM 
	--	[dbo].[ADVANCE_BILLING] AS AB INNER JOIN  
	--	[dbo].[FUNCTIONS] AS F ON F.FNC_CODE = AB.FNC_CODE INNER JOIN 
	--	[dbo].[JOB_COMPONENT] AS JC ON JC.JOB_NUMBER = AB.JOB_NUMBER AND
	--								   JC.JOB_COMPONENT_NBR = AB.JOB_COMPONENT_NBR INNER JOIN
	--	[dbo].[JOB_LOG] AS J ON J.JOB_NUMBER = JC.JOB_NUMBER
	--WHERE
	--	1 = CASE WHEN @DATE_TYPE = 1 THEN CASE WHEN J.CREATE_DATE >= @START_DATE AND J.CREATE_DATE <= CONVERT(DATETIME, @END_DATE +' 23:59:00', 101) THEN 1 ELSE 0 END
	--			 WHEN @DATE_TYPE = 2 THEN CASE WHEN JC.JOB_COMP_DATE >= @START_DATE AND JC.JOB_COMP_DATE <= CONVERT(DATETIME, @END_DATE +' 23:59:00', 101) THEN 1 ELSE 0 END
	--			 WHEN @DATE_TYPE = 3 THEN CASE WHEN JC.JOB_FIRST_USE_DATE >= @START_DATE AND JC.JOB_FIRST_USE_DATE <= CONVERT(DATETIME, @END_DATE +' 23:59:00', 101) THEN 1 ELSE 0 END
	--			 WHEN @DATE_TYPE = 4 THEN CASE WHEN JC.[START_DATE] >= @START_DATE AND JC.[START_DATE] <= CONVERT(DATETIME, @END_DATE +' 23:59:00', 101) THEN 1 ELSE 0 END      
	--			 WHEN @DATE_TYPE = 5 THEN CASE WHEN AB.BILL_DATE >= @START_DATE AND AB.BILL_DATE <= CONVERT(DATETIME, @END_DATE +' 23:59:00', 101) THEN 1 ELSE 0 END ElSE 1 END 
	--		AND 1 = CASE WHEN @INCLUDE_CLOSED = 0 AND (JC.JOB_PROCESS_CONTRL IN (6,12)) THEN 0 ELSE 1 END

IF @debug = 1 SELECT getdate() 'after AB'
	
	--E
	INSERT INTO #JOB_DETAIL
	SELECT
		[ResourceType] = 'E',
		[JobNumber] = ETD.JOB_NUMBER,
		[JobComponentNumber] = ETD.JOB_COMPONENT_NBR,
		[FunctionType] = F.FNC_TYPE,
		[FunctionCode] = ETD.FNC_CODE,
		[FunctionDescription] = F.FNC_DESCRIPTION,
		[ItemID] = ETD.ET_ID,
		[ItemSequenceNumber] = ETD.ET_DTL_ID,
		[Hours] = CASE WHEN F.FNC_TYPE = 'E' THEN ISNULL(ETD.EMP_HOURS, 0) ELSE 0 END,
		[EstimateHours] = 0,
		[FeeEstimate] = 0,
		[OOPEstimate] = 0,
		[EstimateTotal] = 0,
		[FeeTotal] = CASE WHEN ISNULL(ETD.EMP_NON_BILL_FLAG, 0) = 0 THEN ISNULL(ETD.LINE_TOTAL, 0) - ISNULL(ETD.EXT_STATE_RESALE, 0) - ISNULL(ETD.EXT_COUNTY_RESALE, 0) - ISNULL(ETD.EXT_CITY_RESALE, 0) ELSE 0 END,
		[BillableOOPTotal] = 0,
		[BillableTotal] = 0
	FROM 
		[dbo].[EMP_TIME_DTL] AS ETD INNER JOIN
		[dbo].[EMP_TIME] AS ET ON ET.ET_ID = ETD.ET_ID INNER JOIN 
		[dbo].[FUNCTIONS] AS F ON F.FNC_CODE = ETD.FNC_CODE INNER JOIN 
		[dbo].[JOB_COMPONENT] AS JC ON JC.JOB_NUMBER = ETD.JOB_NUMBER AND
									   JC.JOB_COMPONENT_NBR = ETD.JOB_COMPONENT_NBR INNER JOIN
		[dbo].[JOB_LOG] AS J ON J.JOB_NUMBER = JC.JOB_NUMBER INNER JOIN 
		[dbo].[EMPLOYEE] AS EMP ON EMP.EMP_CODE = ET.EMP_CODE
	WHERE
		1 = CASE WHEN @DATE_TYPE = 1 THEN CASE WHEN J.CREATE_DATE >= @START_DATE AND J.CREATE_DATE <= CONVERT(DATETIME, @END_DATE +' 23:59:00', 101) THEN 1 ELSE 0 END
				 WHEN @DATE_TYPE = 2 THEN CASE WHEN JC.JOB_COMP_DATE >= @START_DATE AND JC.JOB_COMP_DATE <= CONVERT(DATETIME, @END_DATE +' 23:59:00', 101) THEN 1 ELSE 0 END
				 WHEN @DATE_TYPE = 3 THEN CASE WHEN JC.JOB_FIRST_USE_DATE >= @START_DATE AND JC.JOB_FIRST_USE_DATE <= CONVERT(DATETIME, @END_DATE +' 23:59:00', 101) THEN 1 ELSE 0 END
				 WHEN @DATE_TYPE = 4 THEN CASE WHEN JC.[START_DATE] >= @START_DATE AND JC.[START_DATE] <= CONVERT(DATETIME, @END_DATE +' 23:59:00', 101) THEN 1 ELSE 0 END    
				 WHEN @DATE_TYPE = 5 THEN CASE WHEN ET.EMP_DATE >= @START_DATE AND ET.EMP_DATE <= CONVERT(DATETIME, @END_DATE +' 23:59:00', 101) THEN 1 ELSE 0 END ElSE 1 END
				  AND ET.EMP_DATE <= @et_date_cutoff
			AND 1 = CASE WHEN @INCLUDE_CLOSED = 0 AND (JC.JOB_PROCESS_CONTRL IN (6,12)) THEN 0 ELSE 1 END

	DELETE FROM #JOB_DETAIL WHERE [ResourceType] = 'E' AND [Hours] = 0 and [FeeTotal] = 0

IF @debug = 1 SELECT getdate() 'after E'
	--EI
	INSERT INTO #JOB_DETAIL
	SELECT
		[ResourceType] = 'EI',
		[JobNumber] = EIA.JOB_NUMBER,
		[JobComponentNumber] = EIA.JOB_COMPONENT_NBR,
		[FunctionType] = F.FNC_TYPE,
		[FunctionCode] = ERD.FNC_CODE,
		[FunctionDescription] = F.FNC_DESCRIPTION,
		[ItemID] = 0,
		[ItemSequenceNumber] = 0,
		[Hours] = 0,
		[EstimateHours] = CASE WHEN F.FNC_TYPE = 'E' THEN ISNULL(ERD.EST_REV_QUANTITY, 0) ELSE 0 END,
		[FeeEstimate] = CASE WHEN F.FNC_TYPE = 'E' THEN ISNULL(ERD.LINE_TOTAL, 0) - ISNULL(ERD.EXT_STATE_RESALE, 0) - ISNULL(ERD.EXT_COUNTY_RESALE, 0) - ISNULL(ERD.EXT_CITY_RESALE, 0)
						  WHEN F.FNC_TYPE = 'V' THEN ISNULL(ERD.EXT_MARKUP_AMT, 0)
						  WHEN F.FNC_TYPE = 'I' THEN ISNULL(ERD.LINE_TOTAL, 0) - ISNULL(ERD.EXT_STATE_RESALE, 0) - ISNULL(ERD.EXT_COUNTY_RESALE, 0) - ISNULL(ERD.EXT_CITY_RESALE, 0) ELSE 0 END,
		[OOPEstimate] = CASE WHEN F.FNC_TYPE = 'V' THEN (ISNULL(ERD.LINE_TOTAL, 0) - ISNULL(ERD.EXT_STATE_RESALE, 0) - ISNULL(ERD.EXT_COUNTY_RESALE, 0) - ISNULL(ERD.EXT_CITY_RESALE, 0) - ISNULL(ERD.EXT_MARKUP_AMT, 0)) ELSE 0 END,
		[EstimateTotal] = 0,
		[FeeTotal] = 0,
		[BillableOOPTotal] = 0,
		[BillableTotal] = 0
	FROM 
		[dbo].[ESTIMATE_INT_APPR] AS EIA INNER JOIN 
		(SELECT
			EIA.ESTIMATE_NUMBER,
			EIA.EST_COMPONENT_NBR,
			EIA.EST_QUOTE_NBR,
			EIA.EST_REVISION_NBR
		FROM 
			[dbo].[ESTIMATE_INT_APPR] AS EIA LEFT JOIN 
			[dbo].[ESTIMATE_APPROVAL] AS EA ON EA.ESTIMATE_NUMBER = EIA.ESTIMATE_NUMBER AND
											   EA.EST_COMPONENT_NBR = EIA.EST_COMPONENT_NBR AND 
											   EA.EST_QUOTE_NBR = EIA.EST_QUOTE_NBR AND 
											   EA.EST_REVISION_NBR = EIA.EST_REVISION_NBR
		WHERE 
			EA.EST_APPR_BY IS NULL) AS EA ON EA.ESTIMATE_NUMBER = EIA.ESTIMATE_NUMBER AND 
											 EA.EST_COMPONENT_NBR = EIA.EST_COMPONENT_NBR AND 
											 EA.EST_QUOTE_NBR = EIA.EST_QUOTE_NBR AND 
											 EA.EST_REVISION_NBR = EIA.EST_REVISION_NBR INNER JOIN 
		[dbo].[ESTIMATE_REV_DET] AS ERD ON EIA.ESTIMATE_NUMBER = ERD.ESTIMATE_NUMBER AND 
										   EIA.EST_COMPONENT_NBR = ERD.EST_COMPONENT_NBR AND 
										   EIA.EST_QUOTE_NBR = ERD.EST_QUOTE_NBR AND 
										   EIA.EST_REVISION_NBR = ERD.EST_REV_NBR INNER JOIN   
		[dbo].[FUNCTIONS] AS F ON F.FNC_CODE = ERD.FNC_CODE INNER JOIN 
		[dbo].[JOB_COMPONENT] AS JC ON JC.JOB_NUMBER = EIA.JOB_NUMBER AND
									   JC.JOB_COMPONENT_NBR = EIA.JOB_COMPONENT_NBR INNER JOIN
		[dbo].[JOB_LOG] AS J ON J.JOB_NUMBER = JC.JOB_NUMBER
	WHERE
		1 = CASE WHEN @DATE_TYPE = 1 THEN CASE WHEN J.CREATE_DATE >= @START_DATE AND J.CREATE_DATE <= CONVERT(DATETIME, @END_DATE +' 23:59:00', 101) THEN 1 ELSE 0 END
				 WHEN @DATE_TYPE = 2 THEN CASE WHEN JC.JOB_COMP_DATE >= @START_DATE AND JC.JOB_COMP_DATE <= CONVERT(DATETIME, @END_DATE +' 23:59:00', 101) THEN 1 ELSE 0 END
				 WHEN @DATE_TYPE = 3 THEN CASE WHEN JC.JOB_FIRST_USE_DATE >= @START_DATE AND JC.JOB_FIRST_USE_DATE <= CONVERT(DATETIME, @END_DATE +' 23:59:00', 101) THEN 1 ELSE 0 END
				 WHEN @DATE_TYPE = 4 THEN CASE WHEN JC.[START_DATE] >= @START_DATE AND JC.[START_DATE] <= CONVERT(DATETIME, @END_DATE +' 23:59:00', 101) THEN 1 ELSE 1 END    
				 WHEN @DATE_TYPE = 5 THEN 1 ElSE 1 END
			AND 1 = CASE WHEN @INCLUDE_CLOSED = 0 AND (JC.JOB_PROCESS_CONTRL IN (6,12)) THEN 0 ELSE 1 END

	DELETE FROM #JOB_DETAIL WHERE ResourceType = 'EI' and [EstimateHours] = 0 AND [FeeEstimate] = 0 AND [OOPEstimate] = 0

IF @debug = 1 SELECT getdate() 'after EI'
	--ES
	INSERT INTO #JOB_DETAIL
	SELECT
		[ResourceType] = 'ES',
		[JobNumber] = EA.JOB_NUMBER,
		[JobComponentNumber] = EA.JOB_COMPONENT_NBR,
		[FunctionType] = F.FNC_TYPE,
		[FunctionCode] = ERD.FNC_CODE,
		[FunctionDescription] = F.FNC_DESCRIPTION,
		[ItemID] = 0,
		[ItemSequenceNumber] = 0,
		[Hours] = 0,
		[EstimateHours] = CASE WHEN F.FNC_TYPE = 'E' THEN ISNULL(ERD.EST_REV_QUANTITY, 0) ELSE 0 END,
		[FeeEstimate] = CASE WHEN F.FNC_TYPE = 'E' THEN ISNULL(ERD.LINE_TOTAL, 0) - ISNULL(ERD.EXT_STATE_RESALE, 0) - ISNULL(ERD.EXT_COUNTY_RESALE, 0) - ISNULL(ERD.EXT_CITY_RESALE, 0)
						  WHEN F.FNC_TYPE = 'V' THEN ISNULL(ERD.EXT_MARKUP_AMT, 0)
						  WHEN F.FNC_TYPE = 'I' THEN ISNULL(ERD.LINE_TOTAL, 0) - ISNULL(ERD.EXT_STATE_RESALE, 0) - ISNULL(ERD.EXT_COUNTY_RESALE, 0) - ISNULL(ERD.EXT_CITY_RESALE, 0) ELSE 0 END,
		[OOPEstimate] = CASE WHEN F.FNC_TYPE = 'V' THEN (ISNULL(ERD.LINE_TOTAL, 0) - ISNULL(ERD.EXT_STATE_RESALE, 0) - ISNULL(ERD.EXT_COUNTY_RESALE, 0) - ISNULL(ERD.EXT_CITY_RESALE, 0) - ISNULL(ERD.EXT_MARKUP_AMT, 0)) ELSE 0 END,
		[EstimateTotal] = 0,
		[FeeTotal] = 0,
		[BillableOOPTotal] = 0,
		[BillableTotal] = 0
	FROM 
		[dbo].[ESTIMATE_APPROVAL] AS EA INNER JOIN 
		[dbo].[ESTIMATE_REV_DET] AS ERD ON ERD.ESTIMATE_NUMBER = EA.ESTIMATE_NUMBER AND 
										   ERD.EST_COMPONENT_NBR = EA.EST_COMPONENT_NBR AND 
										   ERD.EST_QUOTE_NBR = EA.EST_QUOTE_NBR AND 
										   ERD.EST_REV_NBR = EA.EST_REVISION_NBR INNER JOIN  
		[dbo].[FUNCTIONS] AS F ON F.FNC_CODE = ERD.FNC_CODE INNER JOIN 
		[dbo].[JOB_COMPONENT] AS JC ON JC.JOB_NUMBER = EA.JOB_NUMBER AND
									   JC.JOB_COMPONENT_NBR = EA.JOB_COMPONENT_NBR INNER JOIN
		[dbo].[JOB_LOG] AS J ON J.JOB_NUMBER = JC.JOB_NUMBER
	WHERE
		1 = CASE WHEN @DATE_TYPE = 1 THEN CASE WHEN J.CREATE_DATE >= @START_DATE AND J.CREATE_DATE <= CONVERT(DATETIME, @END_DATE +' 23:59:00', 101) THEN 1 ELSE 0 END
				 WHEN @DATE_TYPE = 2 THEN CASE WHEN JC.JOB_COMP_DATE >= @START_DATE AND JC.JOB_COMP_DATE <= CONVERT(DATETIME, @END_DATE +' 23:59:00', 101) THEN 1 ELSE 0 END
				 WHEN @DATE_TYPE = 3 THEN CASE WHEN JC.JOB_FIRST_USE_DATE >= @START_DATE AND JC.JOB_FIRST_USE_DATE <= CONVERT(DATETIME, @END_DATE +' 23:59:00', 101) THEN 1 ELSE 0 END
				 WHEN @DATE_TYPE = 4 THEN CASE WHEN JC.[START_DATE] >= @START_DATE AND JC.[START_DATE] <= CONVERT(DATETIME, @END_DATE +' 23:59:00', 101) THEN 1 ELSE 1 END    
				 WHEN @DATE_TYPE = 5 THEN 1 ElSE 1 END
			AND 1 = CASE WHEN @INCLUDE_CLOSED = 0 AND (JC.JOB_PROCESS_CONTRL IN (6,12)) THEN 0 ELSE 1 END

	DELETE FROM #JOB_DETAIL WHERE ResourceType = 'ES' and [EstimateHours] = 0 AND [FeeEstimate] = 0 AND [OOPEstimate] = 0

IF @debug = 1 SELECT getdate() 'after ES'
	--I

	if @OOPFunctionList <> ''
	Begin
		INSERT INTO #JOB_DETAIL
		SELECT
			[ResourceType] = 'I',
			[JobNumber] = [IO].JOB_NUMBER,
			[JobComponentNumber] = [IO].JOB_COMPONENT_NBR,
			[FunctionType] = F.FNC_TYPE,
			[FunctionCode] = [IO].FNC_CODE,
			[FunctionDescription] = F.FNC_DESCRIPTION,
			[ItemID] = [IO].IO_ID,
			[ItemSequenceNumber] = [IO].SEQ_NBR,
			[Hours] = CASE WHEN F.FNC_TYPE = 'E' THEN ISNULL([IO].IO_QTY, 0) ELSE 0 END,
			[EstimateHours] = 0,
			[FeeEstimate] = 0,
			[OOPEstimate] = 0,
			[EstimateTotal] = 0,
			[FeeTotal] = CASE WHEN ISNULL([IO].NON_BILL_FLAG, 0) = 0 AND [IO].FNC_CODE NOT IN (SELECT * FROM dbo.udf_split_list(@OOPFunctionList, ',')) THEN ISNULL([IO].LINE_TOTAL, 0) - ISNULL([IO].EXT_STATE_RESALE, 0) - ISNULL([IO].EXT_COUNTY_RESALE, 0) - ISNULL([IO].EXT_CITY_RESALE, 0) ELSE 0 END,
			[BillableOOPTotal] = CASE WHEN ISNULL([IO].NON_BILL_FLAG, 0) = 0 AND [IO].FNC_CODE IN (SELECT * FROM dbo.udf_split_list(@OOPFunctionList, ',')) THEN ISNULL([IO].LINE_TOTAL, 0) - ISNULL([IO].EXT_STATE_RESALE, 0) - ISNULL([IO].EXT_COUNTY_RESALE, 0) - ISNULL([IO].EXT_CITY_RESALE, 0) ELSE 0 END,
			[BillableTotal] = 0	
		FROM 
			[dbo].[INCOME_ONLY] AS [IO] INNER JOIN  
			[dbo].[FUNCTIONS] AS F ON F.FNC_CODE = [IO].FNC_CODE INNER JOIN 
			[dbo].[JOB_COMPONENT] AS JC ON JC.JOB_NUMBER = [IO].JOB_NUMBER AND
										   JC.JOB_COMPONENT_NBR = [IO].JOB_COMPONENT_NBR INNER JOIN
			[dbo].[JOB_LOG] AS J ON J.JOB_NUMBER = JC.JOB_NUMBER
		WHERE
			1 = CASE WHEN @DATE_TYPE = 1 THEN CASE WHEN J.CREATE_DATE >= @START_DATE AND J.CREATE_DATE <= CONVERT(DATETIME, @END_DATE +' 23:59:00', 101) THEN 1 ELSE 0 END
					 WHEN @DATE_TYPE = 2 THEN CASE WHEN JC.JOB_COMP_DATE >= @START_DATE AND JC.JOB_COMP_DATE <= CONVERT(DATETIME, @END_DATE +' 23:59:00', 101) THEN 1 ELSE 0 END
					 WHEN @DATE_TYPE = 3 THEN CASE WHEN JC.JOB_FIRST_USE_DATE >= @START_DATE AND JC.JOB_FIRST_USE_DATE <= CONVERT(DATETIME, @END_DATE +' 23:59:00', 101) THEN 1 ELSE 0 END
					 WHEN @DATE_TYPE = 4 THEN CASE WHEN JC.[START_DATE] >= @START_DATE AND JC.[START_DATE] <= CONVERT(DATETIME, @END_DATE +' 23:59:00', 101) THEN 1 ELSE 0 END   
					 WHEN @DATE_TYPE = 5 THEN CASE WHEN [IO].IO_INV_DATE >= @START_DATE AND [IO].IO_INV_DATE <= CONVERT(DATETIME, @END_DATE +' 23:59:00', 101) THEN 1 ELSE 0 END ElSE 1 END
					  AND IO_INV_DATE <= @io_date_cutoff
				AND 1 = CASE WHEN @INCLUDE_CLOSED = 0 AND (JC.JOB_PROCESS_CONTRL IN (6,12)) THEN 0 ELSE 1 END

		DELETE FROM #JOB_DETAIL WHERE ResourceType = 'I' and [Hours] = 0 AND [FeeTotal] = 0 AND [BillableOOPTotal] = 0

	End
	Else
	Begin
		INSERT INTO #JOB_DETAIL
		SELECT
			[ResourceType] = 'I',
			[JobNumber] = [IO].JOB_NUMBER,
			[JobComponentNumber] = [IO].JOB_COMPONENT_NBR,
			[FunctionType] = F.FNC_TYPE,
			[FunctionCode] = [IO].FNC_CODE,
			[FunctionDescription] = F.FNC_DESCRIPTION,
			[ItemID] = [IO].IO_ID,
			[ItemSequenceNumber] = [IO].SEQ_NBR,
			[Hours] = CASE WHEN F.FNC_TYPE = 'E' THEN ISNULL([IO].IO_QTY, 0) ELSE 0 END,
			[EstimateHours] = 0,
			[FeeEstimate] = 0,
			[OOPEstimate] = 0,
			[EstimateTotal] = 0,
			[FeeTotal] = CASE WHEN ISNULL([IO].NON_BILL_FLAG, 0) = 0 THEN ISNULL([IO].LINE_TOTAL, 0) - ISNULL([IO].EXT_STATE_RESALE, 0) - ISNULL([IO].EXT_COUNTY_RESALE, 0) - ISNULL([IO].EXT_CITY_RESALE, 0) ELSE 0 END,
			[BillableOOPTotal] = 0,
			[BillableTotal] = 0	
		FROM 
			[dbo].[INCOME_ONLY] AS [IO] INNER JOIN  
			[dbo].[FUNCTIONS] AS F ON F.FNC_CODE = [IO].FNC_CODE INNER JOIN 
			[dbo].[JOB_COMPONENT] AS JC ON JC.JOB_NUMBER = [IO].JOB_NUMBER AND
										   JC.JOB_COMPONENT_NBR = [IO].JOB_COMPONENT_NBR INNER JOIN
			[dbo].[JOB_LOG] AS J ON J.JOB_NUMBER = JC.JOB_NUMBER
		WHERE
			1 = CASE WHEN @DATE_TYPE = 1 THEN CASE WHEN J.CREATE_DATE >= @START_DATE AND J.CREATE_DATE <= CONVERT(DATETIME, @END_DATE +' 23:59:00', 101) THEN 1 ELSE 0 END
					 WHEN @DATE_TYPE = 2 THEN CASE WHEN JC.JOB_COMP_DATE >= @START_DATE AND JC.JOB_COMP_DATE <= CONVERT(DATETIME, @END_DATE +' 23:59:00', 101) THEN 1 ELSE 0 END
					 WHEN @DATE_TYPE = 3 THEN CASE WHEN JC.JOB_FIRST_USE_DATE >= @START_DATE AND JC.JOB_FIRST_USE_DATE <= CONVERT(DATETIME, @END_DATE +' 23:59:00', 101) THEN 1 ELSE 0 END
					 WHEN @DATE_TYPE = 4 THEN CASE WHEN JC.[START_DATE] >= @START_DATE AND JC.[START_DATE] <= CONVERT(DATETIME, @END_DATE +' 23:59:00', 101) THEN 1 ELSE 0 END   
					 WHEN @DATE_TYPE = 5 THEN CASE WHEN [IO].IO_INV_DATE >= @START_DATE AND [IO].IO_INV_DATE <= CONVERT(DATETIME, @END_DATE +' 23:59:00', 101) THEN 1 ELSE 0 END ElSE 1 END
					  AND IO_INV_DATE <= @io_date_cutoff
				AND 1 = CASE WHEN @INCLUDE_CLOSED = 0 AND (JC.JOB_PROCESS_CONTRL IN (6,12)) THEN 0 ELSE 1 END

		DELETE FROM #JOB_DETAIL WHERE ResourceType = 'I' and [Hours] = 0 AND [FeeTotal] = 0

	End	
			
IF @debug = 1 SELECT getdate() 'after I'

	--V
	INSERT INTO #JOB_DETAIL
	SELECT
		[ResourceType] = 'V',
		[JobNumber] = APP.JOB_NUMBER,
		[JobComponentNumber] = APP.JOB_COMPONENT_NBR,
		[FunctionType] = F.FNC_TYPE,
		[FunctionCode] = APP.FNC_CODE,
		[FunctionDescription] = F.FNC_DESCRIPTION,
		[ItemID] = APP.AP_ID,
		[ItemSequenceNumber] = APP.AP_SEQ,
		[Hours] = CASE WHEN F.FNC_TYPE = 'E' THEN ISNULL(APP.AP_PROD_QUANTITY, 0) ELSE 0 END,
		[EstimateHours] = 0,
		[FeeEstimate] = 0,
		[OOPEstimate] = 0,
		[EstimateTotal] = 0,
		[FeeTotal] = CASE WHEN ISNULL(APP.AP_PROD_NOBILL_FLG, 0) = 0 THEN ISNULL(APP.EXT_MARKUP_AMT, 0) ELSE 0 END,
		[BillableOOPTotal] = CASE WHEN ISNULL(APP.AP_PROD_NOBILL_FLG, 0) = 0 THEN (ISNULL(APP.LINE_TOTAL, 0) - ISNULL(APP.EXT_STATE_RESALE, 0) - ISNULL(APP.EXT_COUNTY_RESALE, 0) - ISNULL(APP.EXT_CITY_RESALE, 0)) - ISNULL(APP.EXT_MARKUP_AMT, 0) ELSE 0 END,
		[BillableTotal] = 0
	FROM 
		[dbo].[AP_PRODUCTION] AS APP INNER JOIN 
		[dbo].[AP_HEADER] AS APH ON APH.AP_ID = APP.AP_ID AND 
							   APH.AP_SEQ = APP.AP_SEQ INNER JOIN    
		[dbo].[FUNCTIONS] AS F ON F.FNC_CODE = APP.FNC_CODE INNER JOIN 
		[dbo].[JOB_COMPONENT] AS JC ON JC.JOB_NUMBER = APP.JOB_NUMBER AND
									   JC.JOB_COMPONENT_NBR = APP.JOB_COMPONENT_NBR INNER JOIN
		[dbo].[JOB_LOG] AS J ON J.JOB_NUMBER = JC.JOB_NUMBER INNER JOIN 
		[dbo].[VENDOR] AS V ON V.VN_CODE = APH.VN_FRL_EMP_CODE
	WHERE
		1 = CASE WHEN @DATE_TYPE = 1 THEN CASE WHEN J.CREATE_DATE >= @START_DATE AND J.CREATE_DATE <= CONVERT(DATETIME, @END_DATE +' 23:59:00', 101) THEN 1 ELSE 0 END
				 WHEN @DATE_TYPE = 2 THEN CASE WHEN JC.JOB_COMP_DATE >= @START_DATE AND JC.JOB_COMP_DATE <= CONVERT(DATETIME, @END_DATE +' 23:59:00', 101) THEN 1 ELSE 0 END
				 WHEN @DATE_TYPE = 3 THEN CASE WHEN JC.JOB_FIRST_USE_DATE >= @START_DATE AND JC.JOB_FIRST_USE_DATE <= CONVERT(DATETIME, @END_DATE +' 23:59:00', 101) THEN 1 ELSE 0 END
				 WHEN @DATE_TYPE = 4 THEN CASE WHEN JC.[START_DATE] >= @START_DATE AND JC.[START_DATE] <= CONVERT(DATETIME, @END_DATE +' 23:59:00', 101) THEN 1 ELSE 0 END 
				 WHEN @DATE_TYPE = 5 THEN CASE WHEN APH.AP_INV_DATE >= @START_DATE AND APH.AP_INV_DATE <= CONVERT(DATETIME, @END_DATE +' 23:59:00', 101) THEN 1 ELSE 0 END ElSE 1 END
				  AND APP.POST_PERIOD <= @ap_pp_cutoff
			AND 1 = CASE WHEN @INCLUDE_CLOSED = 0 AND (JC.JOB_PROCESS_CONTRL IN (6,12)) THEN 0 ELSE 1 END
			--AND 1 = CASE WHEN @IncludeBilledRange = 1 AND AR.AR_POST_PERIOD BETWEEN @BILLED_START_PERIOD AND @BILLED_END_PERIOD THEN 1 
			--			 WHEN @IncludeBilledRange = 0 THEN 1 ELSE 0 END	

	DELETE FROM #JOB_DETAIL WHERE ResourceType = 'V' and [Hours] = 0 AND [FeeTotal] = 0 AND [BillableOOPTotal] = 0

IF @debug = 1 SELECT getdate() 'after V'
			
	IF @SHOW_JOBS_WO_DETAILS = 1 BEGIN
		--ND
		INSERT INTO #JOB_DETAIL
		SELECT
			[ResourceType] = 'ND',
			[JobNumber] = JC.JOB_NUMBER,
			[JobComponentNumber] = JC.JOB_COMPONENT_NBR,
			[FunctionType] = CAST(NULL AS varchar(1)),
			[FunctionCode] = CAST(NULL AS varchar(6)),
			[FunctionDescription] = CAST(NULL AS varchar(30)),
			[ItemID] = 0,
			[ItemSequenceNumber] = 0,
			[Hours] = 0,
			[EstimateHours] = 0,
			[FeeEstimate] = 0,
			[OOPEstimate] = 0,
			[EstimateTotal] = 0,
			[FeeTotal] = 0,
			[BillableOOPTotal] = 0,
			[BillableTotal] = 0
		FROM  
			[dbo].[JOB_COMPONENT] AS JC INNER JOIN
			[dbo].[JOB_LOG] AS J ON J.JOB_NUMBER = JC.JOB_NUMBER LEFT OUTER JOIN
			(SELECT 
				[JobNumber] = JOBTOTALS.[JobNumber],
				[ComponentNumber] = JOBTOTALS.[JobComponentNumber]
			FROM
				(SELECT
					[JobNumber] = AB.JOB_NUMBER,
					[JobComponentNumber] = AB.JOB_COMPONENT_NBR
				FROM 
					[dbo].[ADVANCE_BILLING] AS AB
						
				UNION ALL

				SELECT
					[JobNumber] = COOP.JOB_NUMBER,
					[JobComponentNumber] = COOP.JOB_COMPONENT_NBR
				FROM 
					[dbo].[CLIENT_OOP] AS COOP
							
				UNION ALL

				SELECT
					[JobNumber] = ETD.JOB_NUMBER,
					[JobComponentNumber] = ETD.JOB_COMPONENT_NBR
				FROM 
					[dbo].[EMP_TIME_DTL] AS ETD
								
				UNION ALL

				SELECT
					[JobNumber] = EIA.JOB_NUMBER,
					[JobComponentNumber] = EIA.JOB_COMPONENT_NBR
				FROM 
					[dbo].[ESTIMATE_INT_APPR] AS EIA
					
				UNION ALL

				SELECT
					[JobNumber] = EA.JOB_NUMBER,
					[JobComponentNumber] = EA.JOB_COMPONENT_NBR
				FROM 
					[dbo].[ESTIMATE_APPROVAL] AS EA
					
				UNION ALL

				SELECT
					[JobNumber] = [IO].JOB_NUMBER,
					[JobComponentNumber] = [IO].JOB_COMPONENT_NBR
				FROM 
					[dbo].[INCOME_ONLY] AS [IO]
						
				UNION ALL

				SELECT
					[JobNumber] = POD.JOB_NUMBER,
					[JobComponentNumber] = POD.JOB_COMPONENT_NBR
				FROM 
					[dbo].[PURCHASE_ORDER] AS PO INNER JOIN 
					[dbo].[PURCHASE_ORDER_DET] AS POD ON POD.PO_NUMBER = PO.PO_NUMBER
							
				UNION ALL

				SELECT
					[JobNumber] = APP.JOB_NUMBER,
					[JobComponentNumber] = APP.JOB_COMPONENT_NBR
				FROM 
					[dbo].[AP_PRODUCTION] AS APP) AS JOBTOTALS
			GROUP BY
				JOBTOTALS.[JobNumber],
				JOBTOTALS.[JobComponentNumber]) AS JOBDTLS ON JOBDTLS.JobNumber = JC.JOB_NUMBER AND
															  JOBDTLS.ComponentNumber = JC.JOB_COMPONENT_NBR
		WHERE
			JOBDTLS.JobNumber IS NULL AND
			JOBDTLS.ComponentNumber IS NULL AND
			1 = CASE WHEN @DATE_TYPE = 1 THEN CASE WHEN J.CREATE_DATE >= @START_DATE AND J.CREATE_DATE <= CONVERT(DATETIME, @END_DATE +' 23:59:00', 101) THEN 1 ELSE 0 END
					 WHEN @DATE_TYPE = 2 THEN CASE WHEN JC.JOB_COMP_DATE >= @START_DATE AND JC.JOB_COMP_DATE <= CONVERT(DATETIME, @END_DATE +' 23:59:00', 101) THEN 1 ELSE 0 END
					 WHEN @DATE_TYPE = 3 THEN CASE WHEN JC.JOB_FIRST_USE_DATE >= @START_DATE AND JC.JOB_FIRST_USE_DATE <= CONVERT(DATETIME, @END_DATE +' 23:59:00', 101) THEN 1 ELSE 0 END
					 WHEN @DATE_TYPE = 4 THEN CASE WHEN JC.[START_DATE] >= @START_DATE AND JC.[START_DATE] <= CONVERT(DATETIME, @END_DATE +' 23:59:00', 101) THEN 1 ELSE 0 END
					 WHEN @DATE_TYPE = 5 THEN 1 ElSE 1 END
		    AND 1 = CASE WHEN @INCLUDE_CLOSED = 0 AND (JC.JOB_PROCESS_CONTRL = 6 OR JC.JOB_PROCESS_CONTRL = 12) THEN 0 ELSE 1 END
IF @debug = 1 SELECT getdate() 'after ND'
				
	END
	
	SELECT 
		[ID] = NEWID(),
		JD.ResourceType,
		J.JobNumber,
		J.JobComponentNumber,
		J.OfficeCode,
		J.OfficeDescription,
		J.ClientCode,
		J.ClientDescription,
		J.DivisionCode,
		J.DivisionDescription,
		J.ProductCode,
		J.ProductDescription,
		J.SalesClassCode,
		J.SalesClassDescription,
		J.JobDescription,
		J.ComponentDescription,
		JD.FunctionType,
		JD.FunctionCode,
		JD.FunctionDescription,	
		JD.[Hours],
		JD.EstimateHours,
		JD.FeeEstimate,
		JD.OOPEstimate,
		[EstimateTotal] = JD.FeeEstimate + JD.OOPEstimate,
		[BillableFeeTotal] = JD.FeeTotal,
		JD.BillableOOPTotal,
		[BillableTotal] = JD.FeeTotal + JD.BillableOOPTotal	
	FROM 
		#JOB AS J INNER JOIN 
		#JOB_DETAIL AS JD ON J.[JobNumber] = JD.[JobNumber] AND
							 J.[JobComponentNumber] = JD.[JobComponentNumber]
OPTION (RECOMPILE)
IF @debug = 1 SELECT getdate() 'after END'

	DROP TABLE #JOB
	DROP TABLE #JOB_DETAIL 

END
