IF EXISTS (SELECT * FROM sysobjects WHERE id = object_id(N'[advsp_sec_pwd_validate_history]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
    DROP PROCEDURE [dbo].[advsp_sec_pwd_validate_history]
GO
CREATE PROCEDURE [dbo].[advsp_sec_pwd_validate_history]
@USER_CODE VARCHAR(100),
@ENCRYPTED_PWD VARCHAR(MAX)
AS
/*=========== QUERY ===========*/
BEGIN
	--	VARS
	BEGIN
		DECLARE
			@PWD_HIST_CT INT,
			@IS_VALID BIT
			;
		DECLARE @PASSWORDS TABLE (ID INT IDENTITY, TABLE_ID INT, [START_DATE] SMALLDATETIME, PASSWORD VARCHAR(MAX))
	END
	--	INIT
	BEGIN
		SELECT
			@IS_VALID = 1
			;
		SELECT
			@PWD_HIST_CT = CAST(COALESCE( A.AGY_SETTINGS_VALUE, A.AGY_SETTINGS_DEF, 0) AS INT)
		FROM 
			AGY_SETTINGS A WITH(NOLOCK)
		WHERE 
			A.AGY_SETTINGS_CODE = 'PWD_HIST_CT';
	END
	--	CHECK
	BEGIN
		IF ISNULL(@PWD_HIST_CT, 0) > 0
		BEGIN
			INSERT INTO @PASSWORDS
			SELECT 
				SPH.ID, SPH.[START_DATE], SPH.[PASSWORD]
			FROM 
				SEC_PWD_HIST SPH WITH(NOLOCK)
			WHERE 
				SPH.USER_CODE = @USER_CODE
			ORDER BY
				[START_DATE] DESC, ID DESC;
			DELETE FROM @PASSWORDS WHERE ID > @PWD_HIST_CT;
			IF EXISTS (SELECT 1 FROM @PASSWORDS WHERE [PASSWORD] = @ENCRYPTED_PWD)
			BEGIN
				SELECT @IS_VALID = 0;
			END
		END
	END
	--	RETURN
	BEGIN
		SELECT ISNULL(@IS_VALID, 1);
	END
END
/*=========== QUERY ===========*/
