CREATE PROCEDURE [dbo].[advsp_get_spot_matching_adjacency_settings] (
	@ORDER_NUMBERS varchar(max),
	@MEDIA_TYPE char(1)
)
AS
BEGIN

    CREATE TABLE #SMS_TEMP (
	    ORDER_NBR int NOT NULL,
	    ADJACENCY_BEFORE smallint NOT NULL,
	    ADJACENCY_AFTER smallint NOT NULL
    )

    INSERT INTO #SMS_TEMP
    SELECT DISTINCT MBWMDD.ORDER_NBR, MBWSMS.ADJACENCY_BEFORE, MBWSMS.ADJACENCY_AFTER
    FROM dbo.MEDIA_BROADCAST_WORKSHEET_MARKET_DETAIL_DATE MBWMDD
	    INNER JOIN dbo.MEDIA_BROADCAST_WORKSHEET_MARKET_DETAIL MBWMD ON MBWMDD.MEDIA_BROADCAST_WORKSHEET_MARKET_DETAIL_ID = MBWMD.MEDIA_BROADCAST_WORKSHEET_MARKET_DETAIL_ID 
	    INNER JOIN dbo.MEDIA_BROADCAST_WORKSHEET_MARKET MBWM ON MBWMD.MEDIA_BROADCAST_WORKSHEET_MARKET_ID = MBWM.MEDIA_BROADCAST_WORKSHEET_MARKET_ID 
	    INNER JOIN dbo.MEDIA_BROADCAST_WORKSHEET_SPOT_MATCHING_SETTING MBWSMS ON MBWM.MEDIA_BROADCAST_WORKSHEET_ID = MBWSMS.MEDIA_BROADCAST_WORKSHEET_ID 
    WHERE ORDER_NBR IN (SELECT items FROM dbo.udf_split_list(@ORDER_NUMBERS, ','))

    IF @MEDIA_TYPE = 'T' BEGIN

        INSERT INTO #SMS_TEMP
        SELECT H.ORDER_NBR, BDVS.ADJACENCY_BEFORE, BDVS.ADJACENCY_AFTER
        FROM dbo.BRDCAST_DTL_VERIFICATION_SETTING BDVS
	        INNER JOIN dbo.TV_HEADER H ON BDVS.CL_CODE = H.CL_CODE AND BDVS.MEDIA_TYPE_CODE = 'T'
        WHERE H.ORDER_NBR IN (SELECT items FROM dbo.udf_split_list(@ORDER_NUMBERS, ','))
        AND H.ORDER_NBR NOT IN (SELECT ORDER_NBR FROM #SMS_TEMP)
        
        INSERT INTO #SMS_TEMP
        SELECT D.items as ORDER_NBR, BDVS.ADJACENCY_BEFORE, BDVS.ADJACENCY_AFTER
        FROM dbo.BRDCAST_DTL_VERIFICATION_SETTING BDVS,
	        (SELECT items FROM dbo.udf_split_list(@ORDER_NUMBERS, ',')) D
        WHERE BDVS.CL_CODE IS NULL
        AND BDVS.MEDIA_TYPE_CODE = 'T'
        AND D.items NOT IN (SELECT ORDER_NBR FROM #SMS_TEMP)

    END ELSE BEGIN

        INSERT INTO #SMS_TEMP
        SELECT H.ORDER_NBR, BDVS.ADJACENCY_BEFORE, BDVS.ADJACENCY_AFTER
        FROM dbo.BRDCAST_DTL_VERIFICATION_SETTING BDVS
	        INNER JOIN dbo.RADIO_HEADER H ON BDVS.CL_CODE = H.CL_CODE AND BDVS.MEDIA_TYPE_CODE = 'R'
        WHERE H.ORDER_NBR IN (SELECT items FROM dbo.udf_split_list(@ORDER_NUMBERS, ','))
        AND H.ORDER_NBR NOT IN (SELECT ORDER_NBR FROM #SMS_TEMP)
        
        INSERT INTO #SMS_TEMP
        SELECT D.items as ORDER_NBR, BDVS.ADJACENCY_BEFORE, BDVS.ADJACENCY_AFTER
        FROM dbo.BRDCAST_DTL_VERIFICATION_SETTING BDVS,
	        (SELECT items FROM dbo.udf_split_list(@ORDER_NUMBERS, ',')) D
        WHERE BDVS.CL_CODE IS NULL
        AND BDVS.MEDIA_TYPE_CODE = 'R'
        AND D.items NOT IN (SELECT ORDER_NBR FROM #SMS_TEMP)

    END

    SELECT OrderNumber = ORDER_NBR,
        AdjacencyBefore = ADJACENCY_BEFORE,
        AdjacencyAfter = ADJACENCY_AFTER
    FROM #SMS_TEMP 
    
END
GO
