CREATE PROCEDURE [dbo].[advsp_media_broadcast_criteria]
	@MediaBroadcastWorksheetID	INT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT DISTINCT
		MBW.MEDIA_BROADCAST_WORKSHEET_ID		[MediaBroadcastWorksheetID]
		,MBW_M.MEDIA_BROADCAST_WORKSHEET_MARKET_ID		[MediaBroadcastWorksheetMarketID]
		,MBW.NAME								[MediaBroadcastWorksheetName]
		,MBW.START_DATE							[StartDate]
		,MBW.END_DATE							[EndDate]
		,MBW_M.IS_CABLE							[IsCable]
		,MBW_M.MARKET_CODE						[MarketCode]
		,M.MARKET_DESC							[MarketDescription]
		,MBW_MD.VN_CODE							[VendorCode]
		,ISNULL(V.VN_NAME,'No Data')			[VendorName]
		,MBW_M.SECONDARY_MEDIA_DEMO_ID			[SecondaryMediaDemoID]
		,ISNULL(SMD.CODE,'**')					[SecondaryMediaCode]
		,ISNULL(SMD.DESCRIPTION,'No Data')		[SecondaryMediaDescription]
	
	FROM
		MEDIA_BROADCAST_WORKSHEET MBW
			INNER JOIN MEDIA_BROADCAST_WORKSHEET_MARKET MBW_M
				ON MBW.MEDIA_BROADCAST_WORKSHEET_ID = MBW_M.MEDIA_BROADCAST_WORKSHEET_ID
				LEFT JOIN MARKET M
					ON MBW_M.MARKET_CODE = M.MARKET_CODE
			LEFT JOIN MEDIA_BROADCAST_WORKSHEET_MARKET_DETAIL MBW_MD
				ON MBW_M.MEDIA_BROADCAST_WORKSHEET_MARKET_ID = MBW_MD.MEDIA_BROADCAST_WORKSHEET_MARKET_ID
				LEFT JOIN VENDOR V
					ON MBW_MD.VN_CODE = V.VN_CODE
			LEFT JOIN MEDIA_DEMO SMD
				ON MBW_M.SECONDARY_MEDIA_DEMO_ID = SMD.MEDIA_DEMO_ID
	WHERE (1=1)
		AND (MBW.MEDIA_BROADCAST_WORKSHEET_ID = @MediaBroadcastWorksheetID)
END