CREATE PROCEDURE [dbo].[advsp_ap_import_update_vendor_to_vendor_pay_to]
	@BATCH_NAME varchar(50)
AS

--DECLARE @BATCH_NAME varchar(50)

--SET @BATCH_NAME = '4A''s Broadcast_10062020160652'

DECLARE	@ROW_COUNT int,
		@ROW_ID int,
		@PC_COUNT int,
		@VN_PAY_TO_CODE varchar(6),
		@MIN_IMPORT_ID int,
		@RESULT varchar(max)

SET @RESULT = ''

CREATE TABLE #INVOICES (
	ID int IDENTITY(1,1),
	INV_NUMBER varchar(20) COLLATE SQL_Latin1_General_CP1_CS_AS
)

INSERT INTO #INVOICES
SELECT DISTINCT INV_NUMBER
FROM dbo.IMP_AP_HEADER 
WHERE BATCH_NAME = @BATCH_NAME 

SET @ROW_COUNT = @@ROWCOUNT 
SET @ROW_ID = 1

--select * from #INVOICES

WHILE @ROW_ID <= @ROW_COUNT 
BEGIN

	SELECT @PC_COUNT = COUNT(DISTINCT VN_PAY_TO_CODE) 
	FROM dbo.VENDOR
	WHERE VN_CODE IN (
		SELECT DISTINCT VN_CODE FROM dbo.IMP_AP_HEADER 
		WHERE BATCH_NAME = @BATCH_NAME 
		AND INV_NUMBER = (SELECT INV_NUMBER FROM #INVOICES WHERE ID = @ROW_ID)
	)

	IF @PC_COUNT = 1 BEGIN
		SELECT @VN_PAY_TO_CODE = VN_PAY_TO_CODE 
		FROM dbo.VENDOR 
		WHERE VN_CODE IN (SELECT DISTINCT VN_CODE FROM dbo.IMP_AP_HEADER 
							WHERE BATCH_NAME = @BATCH_NAME 
							AND INV_NUMBER = (SELECT INV_NUMBER FROM #INVOICES WHERE ID = @ROW_ID))

		SELECT @MIN_IMPORT_ID = MIN(IMPORT_ID) FROM dbo.IMP_AP_HEADER 
		WHERE BATCH_NAME = @BATCH_NAME 
		AND INV_NUMBER = (SELECT INV_NUMBER FROM #INVOICES WHERE ID = @ROW_ID)

		--select @VN_PAY_TO_CODE, @MIN_IMPORT_ID 

		BEGIN TRY

			BEGIN TRAN VPT

			UPDATE M SET IMPORT_ID = @MIN_IMPORT_ID
			FROM dbo.IMP_AP_MEDIA M
			WHERE IMPORT_ID IN (SELECT DISTINCT IMPORT_ID
								FROM dbo.IMP_AP_HEADER 
								WHERE BATCH_NAME = @BATCH_NAME 
								AND INV_NUMBER = (SELECT INV_NUMBER FROM #INVOICES WHERE ID = @ROW_ID))
							
			UPDATE G SET IMPORT_ID = @MIN_IMPORT_ID
			FROM dbo.IMP_AP_GL G
			WHERE IMPORT_ID IN (SELECT DISTINCT IMPORT_ID
								FROM dbo.IMP_AP_HEADER 
								WHERE BATCH_NAME = @BATCH_NAME 
								AND INV_NUMBER = (SELECT INV_NUMBER FROM #INVOICES WHERE ID = @ROW_ID))
							
			UPDATE J SET IMPORT_ID = @MIN_IMPORT_ID
			FROM dbo.IMP_AP_JOB J
			WHERE IMPORT_ID IN (SELECT DISTINCT IMPORT_ID
								FROM dbo.IMP_AP_HEADER 
								WHERE BATCH_NAME = @BATCH_NAME 
								AND INV_NUMBER = (SELECT INV_NUMBER FROM #INVOICES WHERE ID = @ROW_ID))

			UPDATE dbo.IMP_AP_HEADER SET VN_CODE = @VN_PAY_TO_CODE 
			WHERE IMPORT_ID = @MIN_IMPORT_ID
		
			UPDATE H SET STATE_TAX_AMOUNT = (SELECT SUM(COALESCE(STATE_TAX_AMOUNT,0)) FROM dbo.IMP_AP_HEADER 
												WHERE BATCH_NAME = @BATCH_NAME 
												AND INV_NUMBER = (SELECT INV_NUMBER FROM #INVOICES WHERE ID = @ROW_ID)),
						 CITY_TAX_AMOUNT = (SELECT SUM(COALESCE(CITY_TAX_AMOUNT,0)) FROM dbo.IMP_AP_HEADER 
												WHERE BATCH_NAME = @BATCH_NAME 
												AND INV_NUMBER = (SELECT INV_NUMBER FROM #INVOICES WHERE ID = @ROW_ID))
			FROM dbo.IMP_AP_HEADER H
			WHERE H.IMPORT_ID = @MIN_IMPORT_ID

			UPDATE H SET INV_TOTAL_NET = (SELECT SUM(COALESCE(MEDIA_NET,0)) FROM dbo.IMP_AP_MEDIA WHERE IMPORT_ID = H.IMPORT_ID) + STATE_TAX_AMOUNT + CITY_TAX_AMOUNT 
			FROM dbo.IMP_AP_HEADER H
			WHERE H.IMPORT_ID = @MIN_IMPORT_ID
		
			DELETE dbo.IMP_AP_HEADER 
			WHERE IMPORT_ID IN (SELECT DISTINCT IMPORT_ID
								FROM dbo.IMP_AP_HEADER 
								WHERE BATCH_NAME = @BATCH_NAME 
								AND INV_NUMBER = (SELECT INV_NUMBER FROM #INVOICES WHERE ID = @ROW_ID))
			AND IMPORT_ID <> @MIN_IMPORT_ID 

			COMMIT TRAN VPT

		END TRY
		BEGIN CATCH
            SELECT @RESULT = ERROR_MESSAGE()
			ROLLBACK TRAN VPT
		END CATCH
		
	END
	ELSE
		SET @RESULT = 'One or more vendors for the same invoice number do not have the same pay to vendor.'

	SET @ROW_ID = @ROW_ID + 1

END

DROP TABLE #INVOICES 

SELECT @RESULT 

GO
