
CREATE PROCEDURE [dbo].[advsp_sec_module_create]
	@SEC_APPLICATION_ID AS int,
	@SEC_MODULE_CODE AS varchar(100),
	@DESCRIPTION AS varchar(100),
	@IS_INACTIVE AS bit,
	@IS_MENU_ITEM AS bit,
	@IS_CATEGORY AS bit,
	@IS_APPLICATION AS bit,
	@IS_REPORT AS bit,
	@IS_DESKTOP_OBJECT AS bit,
	@IS_DASH_QUERY AS bit,
	@PARENT_MODULE_CODE AS varchar(100),
	@IMAGENAME AS varchar(100),
	@SORT_ORDER AS int,
	@CUSTOM_PERMISSION AS bit,
	@WV_URL AS varchar(100),
	@WV_IMAGEPATHACTIVE AS varchar(100),
	@WV_IMAGEPATH AS varchar(100),
	@PB_APPNAME AS varchar(100),
	@PB_MENU AS varchar(100),
	@PB_NAME AS varchar(100),
	@PB_COMMAND_STRING AS varchar(50),
	@PB_ICON AS int,
	@PB_ALLOW_MULTI AS int,
	@WV_DO_NAME AS varchar(50),
	@WV_DO_DSIZE AS int,
	@WV_RPT_URL AS varchar(50),
	@WV_RPT_IMAGEPATHACTIVE AS varchar(50),
	@WV_RPT_IMAGEPATH AS varchar(50),
	@WV_RPT_DESCRIPTION AS varchar(2000),
	@WV_RPT_PREVIEWLOCATION AS varchar(255),
	@WV_RPT_LOCKED AS bit,
	@IS_BLOCKED AS bit = 0,
	@WV_IMAGEPATHLARGE AS varchar(50) = '',
	@WV_RPT_IMAGEPATHLARGE AS varchar(50) = ''
AS
BEGIN

	CREATE TABLE #SEC_USER_TEMP([ROW_ID] [int] IDENTITY(1,1),
								[SEC_USER_ID] [int] NOT NULL,
								[USER_CODE] [varchar](100) NOT NULL)
	CREATE TABLE #SEC_GROUP_TEMP([ROW_ID] [int] IDENTITY(1,1),
								 [SEC_GROUP_ID] [int] NOT NULL,
								 [NAME] [varchar](50) NOT NULL)
	CREATE TABLE #SEC_CPUSER_TEMP([ROW_ID] [int] IDENTITY(1,1),
								  [CPUSER_GUID] [uniqueidentifier] NOT NULL)

	DECLARE @SEC_MODULE_ID AS int
	DECLARE @SEC_MODULE_INFO_ID AS int
	DECLARE @ROW_COUNT AS int
	DECLARE @ROW_ID AS int
	DECLARE @USER_CODE AS varchar(100)
	DECLARE @SEC_USER_ID AS int
	DECLARE @SEC_GROUP_ID AS int
	DECLARE @GROUPNAME AS varchar(50)
	DECLARE @GROUPROW_COUNT AS int
	DECLARE @SQL AS nvarchar(1000)
	DECLARE @SQLPARAM AS nvarchar(1000)
	DECLARE @CAN_PRINT AS bit
	DECLARE @CAN_UPDATE AS bit
	DECLARE @CAN_ADD AS bit
	DECLARE @CUSTOM1 AS bit
	DECLARE @CUSTOM2 AS bit
	DECLARE @PARENT_MODULE_ID AS int
	DECLARE @CPUSER_GUID AS uniqueidentifier
	
	SET @SEC_MODULE_ID = 0
	SET @SEC_MODULE_INFO_ID = 0
	
	IF NOT EXISTS(SELECT * FROM [dbo].[SEC_MODULE] WHERE [SEC_MODULE_CODE] = @SEC_MODULE_CODE) BEGIN

		INSERT INTO 
			[dbo].[SEC_MODULE_INFO]([IMAGENAME], [SORT_ORDER], [CUSTOM_PERMISSION], [WV_URL],
									[WV_IMAGEPATHACTIVE], [WV_IMAGEPATH], [WV_IMAGEPATHLARGE], [PB_APPNAME], [PB_MENU],
									[PB_NAME], [PB_COMMAND_STRING], [PB_ICON], [PB_ALLOW_MULTI],
									[WV_DO_NAME], [WV_DO_DSIZE], [WV_RPT_URL], [WV_RPT_IMAGEPATHACTIVE],
									[WV_RPT_IMAGEPATH], [WV_RPT_IMAGEPATHLARGE], [WV_RPT_DESCRIPTION], [WV_RPT_PREVIEWLOCATION], [WV_RPT_LOCKED])
		VALUES
			(@IMAGENAME, @SORT_ORDER, @CUSTOM_PERMISSION, @WV_URL,
			 @WV_IMAGEPATHACTIVE, @WV_IMAGEPATH, @WV_IMAGEPATHLARGE, @PB_APPNAME, @PB_MENU,
			 @PB_NAME, @PB_COMMAND_STRING, @PB_ICON, @PB_ALLOW_MULTI,
			 @WV_DO_NAME, @WV_DO_DSIZE, @WV_RPT_URL, @WV_RPT_IMAGEPATHACTIVE,
			 @WV_RPT_IMAGEPATH, @WV_RPT_IMAGEPATHLARGE, @WV_RPT_DESCRIPTION, @WV_RPT_PREVIEWLOCATION, @WV_RPT_LOCKED)
						
		SET @SEC_MODULE_INFO_ID = @@IDENTITY
		
		INSERT INTO 
			[dbo].[SEC_MODULE]([SEC_MODULE_CODE], [DESCRIPTION], [IS_INACTIVE], [IS_MENU_ITEM], 
							   [IS_CATEGORY], [IS_APPLICATION], [IS_REPORT], [IS_DESKTOP_OBJECT], 
							   [IS_DASH_QUERY], [SEC_MODULE_INFO_ID])
		VALUES
			(@SEC_MODULE_CODE, @DESCRIPTION, @IS_INACTIVE, @IS_MENU_ITEM, 
			 @IS_CATEGORY, @IS_APPLICATION, @IS_REPORT, @IS_DESKTOP_OBJECT, 
			 @IS_DASH_QUERY, @SEC_MODULE_INFO_ID)
			 
		SET @SEC_MODULE_ID = @@IDENTITY
			
		IF @SEC_MODULE_ID > 0 AND EXISTS(SELECT * FROM [dbo].[SEC_APPLICATION] WHERE [SEC_APPLICATION_ID] = @SEC_APPLICATION_ID) BEGIN
		
			INSERT INTO
				[dbo].[SEC_APPLICATION_MOD]([SEC_APPLICATION_ID], [SEC_MODULE_ID])
			VALUES
				(@SEC_APPLICATION_ID, @SEC_MODULE_ID)
		
		END
			
		IF @SEC_MODULE_ID > 0 AND EXISTS(SELECT * FROM [dbo].[SEC_MODULE] WHERE [SEC_MODULE_CODE] = @PARENT_MODULE_CODE) BEGIN
		
			SET @PARENT_MODULE_ID = 0
			
			SELECT
				@PARENT_MODULE_ID = [SEC_MODULE_ID]
			FROM
				[dbo].[SEC_MODULE]
			WHERE
				[SEC_MODULE_CODE] = @PARENT_MODULE_CODE
				
			IF @PARENT_MODULE_ID > 0 BEGIN
			
				INSERT INTO
					[dbo].[SEC_MODULE_SUB]([PARENT_MODULE_ID], [SEC_MODULE_ID])
				VALUES
					(@PARENT_MODULE_ID, @SEC_MODULE_ID)
				
			END

		END
		
		IF @SEC_MODULE_ID > 0 BEGIN
		
			--\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
			--USER
			--\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
			
			INSERT INTO 
				#SEC_USER_TEMP([SEC_USER_ID], [USER_CODE])
			SELECT
				[SEC_USER].[SEC_USER_ID], [SEC_USER].[USER_CODE]
			FROM
				[dbo].[SEC_USER]
			
			SET @ROW_COUNT = @@ROWCOUNT
			SET @ROW_ID = 1

			SET @USER_CODE = ''
			SET @SEC_USER_ID = 0

			WHILE @ROW_ID <= @ROW_COUNT BEGIN

				SELECT
					@SEC_USER_ID = [SEC_USER_ID],
					@USER_CODE = [USER_CODE]
				FROM
					#SEC_USER_TEMP
				WHERE
					[ROW_ID] = @ROW_ID
					
				IF NOT EXISTS(SELECT * FROM [dbo].[SEC_USER_MODACCESS] WHERE [SEC_USER_ID] = @SEC_USER_ID AND [SEC_MODULE_ID] = @SEC_MODULE_ID) BEGIN

					INSERT INTO
						[dbo].[SEC_USER_MODACCESS]([SEC_USER_ID], [SEC_MODULE_ID], [IS_BLOCKED], [CAN_PRINT], [CAN_UPDATE], [CAN_ADD], [CUSTOM1], [CUSTOM2])
					VALUES
						(@SEC_USER_ID, @SEC_MODULE_ID, @IS_BLOCKED, 1, 1, 1, 0, 0)

				END

				SET @ROW_ID = @ROW_ID + 1
					
			END
			
			--\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
			--GROUP
			--\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
			
			INSERT INTO 
				#SEC_GROUP_TEMP([SEC_GROUP_ID], [NAME])
			SELECT
				[SEC_GROUP_ID], [NAME]
			FROM
				[dbo].[SEC_GROUP]
			
			SET @ROW_COUNT = @@ROWCOUNT
			SET @ROW_ID = 1

			SET @GROUPNAME = ''
			SET @SEC_GROUP_ID = 0
				
			WHILE @ROW_ID <= @ROW_COUNT BEGIN

				SELECT
					@SEC_GROUP_ID = [SEC_GROUP_ID],
					@GROUPNAME = [NAME]
				FROM
					#SEC_GROUP_TEMP
				WHERE
					[ROW_ID] = @ROW_ID

				IF NOT EXISTS(SELECT * FROM [dbo].[SEC_GROUP_MODACCESS] WHERE [SEC_GROUP_ID] = @SEC_GROUP_ID AND [SEC_MODULE_ID] = @SEC_MODULE_ID) BEGIN

					INSERT INTO
						[dbo].[SEC_GROUP_MODACCESS]([SEC_GROUP_ID], [SEC_MODULE_ID], [IS_BLOCKED], [CAN_PRINT], [CAN_UPDATE], [CAN_ADD], [CUSTOM1], [CUSTOM2])
					VALUES
						(@SEC_GROUP_ID, @SEC_MODULE_ID, @IS_BLOCKED, 1, 1, 1, 0, 0)

				END

				SET @ROW_ID = @ROW_ID + 1
					
			END
			
			--\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
			--CP USER
			--\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
			
			INSERT INTO 
				#SEC_CPUSER_TEMP([CPUSER_GUID])
			SELECT
				[USER_GUID]
			FROM
				[dbo].[CP_USER]
						
			SET @ROW_COUNT = @@ROWCOUNT
			SET @ROW_ID = 1
			
			SET @CPUSER_GUID = NULL
			
			WHILE @ROW_ID <= @ROW_COUNT BEGIN

				SELECT
					@CPUSER_GUID = [CPUSER_GUID]
				FROM
					#SEC_CPUSER_TEMP
				WHERE
					[ROW_ID] = @ROW_ID

				IF NOT EXISTS(SELECT * FROM [dbo].[SEC_CPUSER_MODACCESS] WHERE [CPUSER_GUID] = @CPUSER_GUID AND [SEC_MODULE_ID] = @SEC_MODULE_ID) BEGIN

					INSERT INTO
						[dbo].[SEC_CPUSER_MODACCESS]([CPUSER_GUID], [SEC_MODULE_ID], [IS_BLOCKED], [CAN_PRINT], [CAN_UPDATE], [CAN_ADD], [CUSTOM1], [CUSTOM2])
					VALUES
						(@CPUSER_GUID, @SEC_MODULE_ID, @IS_BLOCKED, 1, 1, 1, 0, 0)

				END

				SET @ROW_ID = @ROW_ID + 1
					
			END

		END

		DROP TABLE #SEC_USER_TEMP
		DROP TABLE #SEC_GROUP_TEMP
		DROP TABLE #SEC_CPUSER_TEMP
		
	END ELSE BEGIN
	
		SELECT 
			@SEC_MODULE_ID =  [SEC_MODULE_ID]
		FROM 
			[dbo].[SEC_MODULE] 
		WHERE 
			[SEC_MODULE_CODE] = @SEC_MODULE_CODE
			
		IF @SEC_MODULE_ID > 0 AND EXISTS(SELECT * FROM [dbo].[SEC_APPLICATION] WHERE [SEC_APPLICATION_ID] = @SEC_APPLICATION_ID) BEGIN
		
			IF NOT EXISTS(SELECT * FROM [dbo].[SEC_APPLICATION_MOD] WHERE [SEC_APPLICATION_ID] = @SEC_APPLICATION_ID AND [SEC_MODULE_ID] = @SEC_MODULE_ID) BEGIN
			
				INSERT INTO
					[dbo].[SEC_APPLICATION_MOD]([SEC_APPLICATION_ID], [SEC_MODULE_ID])
				VALUES
					(@SEC_APPLICATION_ID, @SEC_MODULE_ID)
				
			END

		END

		IF @SEC_MODULE_ID > 0 AND EXISTS(SELECT * FROM [dbo].[SEC_MODULE] WHERE [SEC_MODULE_CODE] = @PARENT_MODULE_CODE) BEGIN
		
			SET @PARENT_MODULE_ID = 0
			
			SELECT
				@PARENT_MODULE_ID = [SEC_MODULE_ID]
			FROM
				[dbo].[SEC_MODULE]
			WHERE
				[SEC_MODULE_CODE] = @PARENT_MODULE_CODE
				
			IF @PARENT_MODULE_ID > 0 BEGIN
			
				UPDATE 
					[dbo].[SEC_MODULE_SUB]
				SET 
					[PARENT_MODULE_ID] = @PARENT_MODULE_ID
				WHERE
					[SEC_MODULE_ID] = @SEC_MODULE_ID
				
			END

		END
		
		UPDATE 
			[dbo].[SEC_MODULE]
		SET 
			[DESCRIPTION] = @DESCRIPTION, 
			[IS_INACTIVE] = @IS_INACTIVE,  
			[IS_MENU_ITEM] = @IS_MENU_ITEM, 
			[IS_CATEGORY] = @IS_CATEGORY,  
			[IS_APPLICATION] = @IS_APPLICATION,  
			[IS_REPORT] = @IS_REPORT,  
			[IS_DESKTOP_OBJECT] = @IS_DESKTOP_OBJECT, 
			[IS_DASH_QUERY] = @IS_DASH_QUERY
		WHERE
			[SEC_MODULE_ID] = @SEC_MODULE_ID
			
		SELECT
			@SEC_MODULE_INFO_ID = [SEC_MODULE_INFO_ID]
		FROM
			[dbo].[SEC_MODULE]
		WHERE
			[SEC_MODULE_ID] = @SEC_MODULE_ID
			
		UPDATE
			[dbo].[SEC_MODULE_INFO]
		SET
			[IMAGENAME] = @IMAGENAME, 
			[SORT_ORDER] = @SORT_ORDER,  
			[CUSTOM_PERMISSION] = @CUSTOM_PERMISSION,  
			[WV_URL] = @WV_URL, 
			[WV_IMAGEPATHACTIVE] = @WV_IMAGEPATHACTIVE,  
			[WV_IMAGEPATH] = @WV_IMAGEPATH,  
			[PB_APPNAME] = @PB_APPNAME,  
			[PB_MENU] = @PB_MENU, 
			[PB_NAME] = @PB_NAME,  
			[PB_COMMAND_STRING] = @PB_COMMAND_STRING,  
			[PB_ICON] = @PB_ICON,  
			[PB_ALLOW_MULTI] = @PB_ALLOW_MULTI, 
			[WV_DO_NAME] = @WV_DO_NAME,  
			[WV_DO_DSIZE] = @WV_DO_DSIZE,  
			[WV_RPT_URL] = @WV_RPT_URL,  
			[WV_RPT_IMAGEPATHACTIVE] = @WV_RPT_IMAGEPATHACTIVE, 
			[WV_RPT_IMAGEPATH] = @WV_RPT_IMAGEPATH,  
			[WV_RPT_DESCRIPTION] = @WV_RPT_DESCRIPTION,  
			[WV_RPT_PREVIEWLOCATION] = @WV_RPT_PREVIEWLOCATION,  
			[WV_RPT_LOCKED] = @WV_RPT_LOCKED
		WHERE
			[SEC_MODULE_INFO_ID] = @SEC_MODULE_INFO_ID

	END

END