CREATE PROCEDURE advsp_ar_invoice_select_check_detail @ClientCashReceiptID int

AS 

SELECT	[InvoiceNumber] = CD.AR_INV_NBR,
		[SequenceNumber] = CD.AR_INV_SEQ,
		[InvoiceDate] = AR.AR_INV_DATE,
		[AmountPaid] = SUM(COALESCE(CD.CR_PAY_AMT, 0)),
		[WriteoffAmount] = SUM(COALESCE(CD.CR_ADJ_AMT, 0)),
		[OnAccountAmount] = CAST(NULL AS DECIMAL(14,2)),
		[Comment] = CAST(NULL AS VARCHAR(254)),
		[ClientCashReceiptID] = CD.REC_ID
FROM	dbo.CR_CLIENT_DTL CD
			INNER JOIN dbo.ACCT_REC AR ON CD.AR_INV_NBR = AR.AR_INV_NBR AND CD.AR_INV_SEQ = AR.AR_INV_SEQ AND CD.AR_TYPE = AR.AR_TYPE
WHERE
	CD.REC_ID = @ClientCashReceiptID
GROUP BY	CD.AR_INV_NBR,
			CD.AR_INV_SEQ,
			AR.AR_INV_DATE,
			CD.REC_ID
HAVING   SUM(COALESCE(CD.CR_PAY_AMT, 0)) <> 0 OR SUM(COALESCE(CD.CR_ADJ_AMT, 0)) <> 0

UNION

SELECT	CAST(NULL AS int),
		CAST(NULL AS smallint),
		CAST(NULL AS smalldatetime),
		CAST(NULL AS DECIMAL(14,2)),
		CAST(NULL AS DECIMAL(14,2)),
		SUM(COALESCE(CR_ON_ACCT.CR_OA_AMT, 0)) AS CR_OA_AMT,
		OA_COMMENT,
		CR_ON_ACCT.REC_ID
FROM	dbo.CR_ON_ACCT
WHERE	CR_ON_ACCT.REC_ID = @ClientCashReceiptID
GROUP BY CR_ON_ACCT.REC_ID, OA_COMMENT 
HAVING	SUM(COALESCE(CR_ON_ACCT.CR_OA_AMT, 0)) <> 0

ORDER BY 6, 3, 1
