CREATE PROCEDURE [dbo].[advsp_media_planning_has_pending_orders] 
	@MPDLLD_IDS	varchar(MAX)
AS
BEGIN

	SET NOCOUNT ON

	DECLARE @ROW_COUNT AS integer
	DECLARE @ROW_ID AS integer
	DECLARE @PLAN_ID AS varchar(20)
	DECLARE @HAS_PENDING_ORDERS AS bit
	CREATE TABLE #PLAN_IDS([RowID] [int] IDENTITY(1,1),
						   PLAN_ID varchar(20) NOT NULL)

	INSERT INTO #PLAN_IDS
	SELECT * FROM dbo.fn_intlist_to_table(@MPDLLD_IDS)

	SET @ROW_COUNT = @@ROWCOUNT
	SET @ROW_ID = 1
	SET @HAS_PENDING_ORDERS = 0

	WHILE @ROW_ID <= @ROW_COUNT BEGIN

		SELECT
			@PLAN_ID = PLAN_ID
		FROM 
			#PLAN_IDS
		WHERE
			RowID = @ROW_ID

		IF EXISTS(SELECT RECSEQ FROM dbo.PRINT_ORDER WHERE @PLAN_ID IN (SELECT items FROM dbo.udf_split_list(PLAN_IDS, ',')) AND POST_FLAG = 0) BEGIN

			SET @HAS_PENDING_ORDERS = 1
			PRINT CAST(@PLAN_ID AS varchar(MAX))

		END ELSE IF EXISTS(SELECT RECSEQ FROM dbo.BRDCAST_IMPORT WHERE @PLAN_ID IN (SELECT items FROM dbo.udf_split_list(PLAN_IDS, ',')) AND POST_FLAG = 0) BEGIN
		
			SET @HAS_PENDING_ORDERS = 1
			PRINT CAST(@PLAN_ID AS varchar(MAX))

		END
	
		IF @HAS_PENDING_ORDERS = 1 BEGIN

			BREAK;

		END

		SET @ROW_ID = @ROW_ID + 1
	
	END

	DROP TABLE #PLAN_IDS

	SELECT @HAS_PENDING_ORDERS


END
