CREATE PROCEDURE [dbo].[advsp_load_po_details] @PO_NUMBER INT 
AS
BEGIN

	SELECT [PONumber] = PURCHASE_ORDER_DET.PO_NUMBER,
		   [LineNumber] = PURCHASE_ORDER_DET.LINE_NUMBER,
		   [LineDescription] = PURCHASE_ORDER_DET.LINE_DESC,
		   [DetailDescription] = PURCHASE_ORDER_DET.DET_DESC,
		   [Instructions] = PURCHASE_ORDER_DET.DET_INSTRUCT,
		   [ClientCode] = JOB_LOG.CL_CODE,
		   [ClientName] = V_PRODUCT.CL_NAME,
		   [DivisionCode] = JOB_LOG.DIV_CODE,
		   [DivisionName] = V_PRODUCT.DIV_NAME,
		   [ProductCode] = JOB_LOG.PRD_CODE,
		   [ProductDescription] = V_PRODUCT.PRD_DESCRIPTION,
		   [JobNumber] = PURCHASE_ORDER_DET.JOB_NUMBER,
		   [JobDescription] = JOB_LOG.JOB_DESC,
		   [JobComponentNumber] = PURCHASE_ORDER_DET.JOB_COMPONENT_NBR,
		   [JobComponentID] = JOB_COMPONENT.ROWID,
		   [JobComponentDescription] = JOB_COMPONENT.JOB_COMP_DESC,
		   [FunctionCode] = PURCHASE_ORDER_DET.FNC_CODE,
		   [FunctionDescription] = V_FUNCTION.FNC_DESCRIPTION,
		   [GeneralLedgerCode] = PURCHASE_ORDER_DET.GLACODE,
		   [Quantity] = PURCHASE_ORDER_DET.PO_QTY,
		   [Rate] = PURCHASE_ORDER_DET.PO_RATE,
		   [ExtendedAmount] = PURCHASE_ORDER_DET.PO_EXT_AMOUNT,
		   [CommissionPercent] = PURCHASE_ORDER_DET.PO_COMM_PCT,
		   [TaxPercent] = PURCHASE_ORDER_DET.PO_TAX_PCT,
		   [ExtendedMarkupAmount] = PURCHASE_ORDER_DET.EXT_MARKUP_AMT,
		   [LineTotal] = ISNULL(PURCHASE_ORDER_DET.PO_EXT_AMOUNT, 0) + ISNULL(PURCHASE_ORDER_DET.EXT_MARKUP_AMT, 0),
		   [BillingApprovalID] = PURCHASE_ORDER_DET.BA_ID,
		   [IsAttachedToAP] = CONVERT(BIT, CASE 
												WHEN AP_PRODUCTION.PO_NUMBER IS NOT NULL AND AP_PRODUCTION.PO_LINE_NUMBER IS NOT NULL AND AP_PRODUCTION.CAN_DELETE = 0 THEN 1 
										        WHEN AP_GL_DIST.PO_NUMBER IS NOT NULL AND AP_GL_DIST.PO_LINE_NUMBER IS NOT NULL AND AP_GL_DIST.CAN_DELETE = 0 THEN 1
										        ELSE NULL 
										   END),
		   [IsComplete] = PURCHASE_ORDER_DET.PO_COMPLETE,
		   [UseCPM] = CONVERT(BIT, CASE WHEN V_FUNCTION.FNC_CPM_FLAG = 1 THEN 1 ELSE 0 END),
		   [CanDelete] = CONVERT(BIT, CASE 
										WHEN PURCHASE_ORDER.VOID_FLAG = 1 OR PURCHASE_ORDER.PO_APPROVAL_FLAG IN (1,2) THEN 0 
										WHEN PURCHASE_ORDER_DET.PO_COMPLETE = 1 THEN 0 
										WHEN AP_PRODUCTION.PO_NUMBER IS NOT NULL AND AP_PRODUCTION.PO_LINE_NUMBER IS NOT NULL AND AP_PRODUCTION.CAN_DELETE = 0 THEN 0
										WHEN AP_GL_DIST.PO_NUMBER IS NOT NULL AND AP_GL_DIST.PO_LINE_NUMBER IS NOT NULL AND AP_GL_DIST.CAN_DELETE = 0 THEN 0
										ELSE 1
									  END),
		   [LockedByJobComp] = CONVERT(BIT, CASE WHEN JOB_COMPONENT.JOB_PROCESS_CONTRL IS NULL THEN 0
											WHEN JOB_COMPONENT.JOB_PROCESS_CONTRL IN (6, 12) THEN 1 
											ELSE 0
									   END)
	FROM dbo.PURCHASE_ORDER JOIN
		 dbo.PURCHASE_ORDER_DET ON PURCHASE_ORDER.PO_NUMBER = PURCHASE_ORDER_DET.PO_NUMBER LEFT OUTER JOIN
		 dbo.JOB_COMPONENT ON PURCHASE_ORDER_DET.JOB_COMPONENT_NBR = JOB_COMPONENT.JOB_COMPONENT_NBR AND PURCHASE_ORDER_DET.JOB_NUMBER = JOB_COMPONENT.JOB_NUMBER LEFT OUTER JOIN
		 dbo.JOB_LOG ON PURCHASE_ORDER_DET.JOB_NUMBER = JOB_LOG.JOB_NUMBER LEFT OUTER JOIN
		 dbo.V_PRODUCT ON JOB_LOG.CL_CODE = V_PRODUCT.CL_CODE AND JOB_LOG.DIV_CODE = V_PRODUCT.DIV_CODE AND JOB_LOG.PRD_CODE = V_PRODUCT.PRD_CODE LEFT OUTER JOIN
		 dbo.V_FUNCTION ON PURCHASE_ORDER_DET.FNC_CODE = V_FUNCTION.FNC_CODE LEFT OUTER JOIN
		 (SELECT AP_PRODUCTION.PO_NUMBER, 
				 AP_PRODUCTION.PO_LINE_NUMBER,
				 [CAN_DELETE] = CASE WHEN COUNT(CASE WHEN COALESCE(AP_PRODUCTION.DELETE_FLAG, 0) = 0 THEN 1 ELSE NULL END) > 0 THEN 0 ELSE 1 END
		  FROM dbo.AP_PRODUCTION 
		  WHERE PO_NUMBER IS NOT NULL AND 
				PO_LINE_NUMBER IS NOT NULL AND
				(MODIFY_DELETE IS NULL OR MODIFY_DELETE = 0)
		  GROUP BY PO_NUMBER, PO_LINE_NUMBER) AS AP_PRODUCTION ON PURCHASE_ORDER_DET.PO_NUMBER = AP_PRODUCTION.PO_NUMBER AND PURCHASE_ORDER_DET.LINE_NUMBER = AP_PRODUCTION.PO_LINE_NUMBER LEFT OUTER JOIN
		  (SELECT AP_GL_DIST.PO_NUMBER, 
				 AP_GL_DIST.PO_LINE_NUMBER,
				 [CAN_DELETE] = CASE WHEN COUNT(CASE WHEN COALESCE(AP_GL_DIST.DELETE_FLAG, 0) = 0 THEN 1 ELSE NULL END) > 0 THEN 0 ELSE 1 END
		  FROM dbo.AP_GL_DIST 
		  WHERE PO_NUMBER IS NOT NULL AND 
				PO_LINE_NUMBER IS NOT NULL AND
				(MODIFY_DELETE IS NULL OR MODIFY_DELETE = 0)
		  GROUP BY PO_NUMBER, PO_LINE_NUMBER) AS AP_GL_DIST ON PURCHASE_ORDER_DET.PO_NUMBER = AP_GL_DIST.PO_NUMBER AND PURCHASE_ORDER_DET.LINE_NUMBER = AP_GL_DIST.PO_LINE_NUMBER
	WHERE PURCHASE_ORDER_DET.PO_NUMBER = @PO_NUMBER 
	ORDER BY [LINE_NUMBER] ASC

END
