CREATE PROCEDURE [dbo].[advsp_media1_order_bcst_amounts2] ( @user_code varchar(100) )
AS
BEGIN
SET NOCOUNT ON

--Stored procedure to extract broadcast NEW MONTHLY ORDER AMOUNTS
-- #00 09/02/11 - initial release
-- #01 12/14/13 - include sum of spots for individual weeks (704-453)	
 
-- ==========================================================
-- MAIN DATA TABLE
-- ==========================================================
CREATE TABLE #order_monthly(
	REC_TYPE						varchar(5) COLLATE SQL_Latin1_General_CP1_CS_AS,
	ORDER_TYPE						varchar(1) COLLATE SQL_Latin1_General_CP1_CS_AS,
	ORDER_NBR						int NOT NULL,
	LINE_NBR						smallint NULL, 
	REV_NBR							smallint NULL, 
	SEQ_NBR							smallint NULL, 
	MONTH_IND						smallint NULL, 
	MONTH_SHORT						varchar(3) COLLATE SQL_Latin1_General_CP1_CS_AS, 
	BRDCAST_YEAR					int NULL,
	BRDCAST_PER						int NULL,
	SPOTS1							int NULL,
	SPOTS2							int NULL,
	SPOTS3							int NULL,
	SPOTS4							int NULL,
	SPOTS5							int NULL,
	SPOTS6							int NULL,
	SPOTS7							int NULL, 
	SPOTS							int NULL,
	LINE_NET						decimal(15,2) NULL,
	COMM_AMT						decimal(15,2) NULL,
	REBATE_AMT						decimal(15,2) NULL,
	DISCOUNT						decimal(15,2) NULL,
	VENDOR_TAX						decimal(15,2) NULL,
	STATE_TAX						decimal(15,2) NULL,
	COUNTY_TAX						decimal(15,2) NULL,
	CITY_TAX						decimal(15,2) NULL,
	NETCHARGE						decimal(15,2) NULL,
	ADDL_CHARGE						decimal(15,2) NULL,
	LINE_TOTAL						decimal(15,2) NULL,
	BILLING_AMT						decimal(15,2) NULL,
	AR_INV_NBR						int NULL,
	AR_INV_SEQ						smallint NULL,
	AR_TYPE							varchar(3) COLLATE SQL_Latin1_General_CP1_CS_AS,
	BILLING_USER					varchar(100) COLLATE SQL_Latin1_General_CP1_CS_AS,
	BILL_TYPE_FLAG					smallint NULL,
	GRP								decimal(18,5) NULL,
	GROSS_IMPRESSIONS				decimal(18,5) NULL,
	MEDIA_DEMO_DESCRIPTION			varchar(50) COLLATE SQL_Latin1_General_CP1_CS_AS,
	BOOKEND							bit NULL,
	VALUE_ADDED						bit NULL)

-- ==========================================================
-- SECONDARY TABLES
-- ==========================================================
-- Temp table #media_orders - stores table of orders to be processed
CREATE TABLE #media_orders(
	[USER_ID]				varchar(100) COLLATE SQL_Latin1_General_CP1_CS_AS,
	ORDER_NBR				int NULL,
	ORDER_TYPE				varchar(1) COLLATE SQL_Latin1_General_CP1_CS_AS)
INSERT INTO #media_orders
SELECT [USER_ID], ORDER_NBR, ORDER_TYPE
FROM dbo.MEDIA_RPT_ORDERS AS rd
WHERE UPPER(rd.[USER_ID]) = UPPER(@user_code)
--SELECT * FROM #media_orders--------------------------------

-- Temp table #order_type-------------------------------------
CREATE TABLE #order_type(ORDER_TYPE varchar(100) COLLATE SQL_Latin1_General_CP1_CS_AS)
INSERT INTO #order_type
SELECT DISTINCT ORDER_TYPE 
FROM #media_orders
--SELECT * FROM #order_type

-- Temp table #ar_info
CREATE TABLE #ar_info(
	AR_INV_NBR						int NULL,
	AR_TYPE							varchar(3) COLLATE SQL_Latin1_General_CP1_CS_AS,
	GLEXACT							int NULL,
	AR_INV_DATE						smalldatetime NULL,
	AR_POST_PERIOD					varchar(6) COLLATE SQL_Latin1_General_CP1_CS_AS)

INSERT INTO #ar_info
SELECT ar.AR_INV_NBR,
	ar.AR_TYPE,
	MAX(ar.GLEXACT),
	MAX(ar.AR_INV_DATE),
	MAX(ar.AR_POST_PERIOD)
FROM dbo.ACCT_REC AS ar
GROUP BY ar.AR_INV_NBR, ar.AR_TYPE		--, ar.GLEXACT, ar.AR_INV_DATE, ar.AR_POST_PERIOD
--SELECT * FROM #ar_info

-- ==========================================================
-- EXTRACTION ROUTINES
-- ==========================================================
-- Radio------------------------------------------------------
IF EXISTS (SELECT ORDER_TYPE FROM #order_type WHERE ORDER_TYPE = 'R')
BEGIN
	INSERT INTO #order_monthly
		SELECT 'ORDER' AS REC_TYPE, 
		'R' AS ORDER_TYPE,
		d.ORDER_NBR,
		d.LINE_NBR, 
		d.REV_NBR,
		d.SEQ_NBR,
		d.MONTH_NBR, 
		CASE MONTH_NBR
			WHEN 1 THEN 'Jan'
			WHEN 2 THEN 'Feb'
			WHEN 3 THEN 'Mar'
			WHEN 4 THEN 'Apr'
			WHEN 5 THEN 'May'
			WHEN 6 THEN 'Jun'
			WHEN 7 THEN 'Jul'
			WHEN 8 THEN 'Aug'
			WHEN 9 THEN 'Sep'
			WHEN 10 THEN 'Oct'
			WHEN 11 THEN 'Nov'
			WHEN 12 THEN 'Dec'
		END,	
		d.YEAR_NBR,  
		d.YEAR_NBR * 100 + d.MONTH_NBR,
		SUM(d.SPOTS1),
		SUM(d.SPOTS2),
		SUM(d.SPOTS3),
		SUM(d.SPOTS4),
		SUM(d.SPOTS5),
		SUM(d.SPOTS6),
		SUM(d.SPOTS7),
		SUM(d.TOTAL_SPOTS),
		SUM(d.[EXT_NET_AMT]),
		SUM(d.[COMM_AMT]),
		SUM(d.[REBATE_AMT]),
		SUM(d.[DISCOUNT_AMT]),
		SUM(d.[NON_RESALE_AMT]),
		SUM(d.[STATE_AMT]),
		SUM(d.[COUNTY_AMT]),
		SUM(d.[CITY_AMT]),
		SUM(d.[NETCHARGE]),
		SUM(d.[ADDL_CHARGE]),
		SUM(d.[LINE_TOTAL]),
		SUM(d.BILLING_AMT) AS [BILLING_AMT],
		d.AR_INV_NBR,
		d.AR_INV_SEQ,
		d.AR_TYPE,
		d.BILLING_USER,
		d.BILL_TYPE_FLAG,
		GRP = SUM(MBW.GRP),
		GROSS_IMPRESSIONS = SUM(MBW.GROSS_IMPRESSIONS),
		MEDIA_DEMO_DESCRIPTION = MBW.MEDIA_DEMO_DESCRIPTION,
		BOOKEND = MBW.BOOKEND,
		VALUE_ADDED = MBW.VALUE_ADDED
	FROM #media_orders AS o
		INNER JOIN dbo.RADIO_DETAIL AS d ON o.ORDER_NBR = d.ORDER_NBR
		LEFT OUTER JOIN (SELECT
								a.ORDER_NBR,
								LINE_NBR = a.ORDER_LINE_NBR, 
								GRP = SUM(a.GRP),
								GROSS_IMPRESSIONS =SUM(a.GROSS_IMPRESSIONS),
								a.MEDIA_DEMO_DESCRIPTION,
								a.BOOKEND,
								a.VALUE_ADDED
							FROM
								(SELECT 
										ORDER_NBR, 
										ORDER_LINE_NBR, 
										GRP = MBWMDD.SPOTS * MBWMD.PRIMARY_AQH_RATING,
										GROSS_IMPRESSIONS = MBWMDD.SPOTS * MBWMD.PRIMARY_AQH,
										MEDIA_DEMO_DESCRIPTION = md.[DESCRIPTION],
										MBWMD.BOOKEND,
										MBWMD.VALUE_ADDED
									FROM 
										dbo.MEDIA_BROADCAST_WORKSHEET MBW
										INNER JOIN dbo.MEDIA_BROADCAST_WORKSHEET_MARKET MBWM ON MBWM.MEDIA_BROADCAST_WORKSHEET_ID = MBW.MEDIA_BROADCAST_WORKSHEET_ID
										INNER JOIN dbo.MEDIA_BROADCAST_WORKSHEET_MARKET_DETAIL MBWMD ON MBWMD.MEDIA_BROADCAST_WORKSHEET_MARKET_ID = MBWM.MEDIA_BROADCAST_WORKSHEET_MARKET_ID
										INNER JOIN dbo.MEDIA_BROADCAST_WORKSHEET_MARKET_DETAIL_DATE MBWMDD ON MBWMDD.MEDIA_BROADCAST_WORKSHEET_MARKET_DETAIL_ID = MBWMD.MEDIA_BROADCAST_WORKSHEET_MARKET_DETAIL_ID
										INNER JOIN dbo.MEDIA_DEMO md ON md.MEDIA_DEMO_ID = MBW.PRIMARY_MEDIA_DEMO_ID
									WHERE 
										ORDER_NBR IS NOT NULL AND MBWMD.REVISION_NUMBER IN (SELECT MAX(REVISION_NUMBER) FROM dbo.MEDIA_BROADCAST_WORKSHEET_MARKET_DETAIL WHERE MEDIA_BROADCAST_WORKSHEET_MARKET_ID = MBWMD.MEDIA_BROADCAST_WORKSHEET_MARKET_ID GROUP BY MEDIA_BROADCAST_WORKSHEET_MARKET_ID)) AS a
							GROUP BY
								a.ORDER_NBR,
								a.ORDER_LINE_NBR,
								a.MEDIA_DEMO_DESCRIPTION,
								a.BOOKEND,
								a.VALUE_ADDED) AS MBW ON MBW.ORDER_NBR = d.ORDER_NBR AND MBW.LINE_NBR = d.LINE_NBR
	GROUP BY 
		d.ORDER_NBR, d.LINE_NBR, d.REV_NBR, d.SEQ_NBR, d.MONTH_NBR,  
		d.YEAR_NBR, d.AR_INV_NBR, d.AR_INV_SEQ, d.AR_TYPE,
		d.BILLING_USER, d.BILL_TYPE_FLAG, MBW.MEDIA_DEMO_DESCRIPTION, MBW.BOOKEND, MBW.VALUE_ADDED
END

-- Television------------------------------------------------------
IF EXISTS (SELECT ORDER_TYPE FROM #order_type WHERE ORDER_TYPE = 'T')
BEGIN
	INSERT INTO #order_monthly
		SELECT 'ORDER' AS REC_TYPE, 
		'T' AS ORDER_TYPE,
		d.ORDER_NBR,
		d.LINE_NBR, 
		d.REV_NBR,
		d.SEQ_NBR,
		d.MONTH_NBR, 
		CASE MONTH_NBR
			WHEN 1 THEN 'Jan'
			WHEN 2 THEN 'Feb'
			WHEN 3 THEN 'Mar'
			WHEN 4 THEN 'Apr'
			WHEN 5 THEN 'May'
			WHEN 6 THEN 'Jun'
			WHEN 7 THEN 'Jul'
			WHEN 8 THEN 'Aug'
			WHEN 9 THEN 'Sep'
			WHEN 10 THEN 'Oct'
			WHEN 11 THEN 'Nov'
			WHEN 12 THEN 'Dec'
		END,	
		d.YEAR_NBR,  
		d.YEAR_NBR * 100 + d.MONTH_NBR,
		SUM(d.SPOTS1),
		SUM(d.SPOTS2),
		SUM(d.SPOTS3),
		SUM(d.SPOTS4),
		SUM(d.SPOTS5),
		SUM(d.SPOTS6),
		SUM(d.SPOTS7),
		SUM(d.TOTAL_SPOTS),
		SUM(d.[EXT_NET_AMT]),
		SUM(d.[COMM_AMT]),
		SUM(d.[REBATE_AMT]),
		SUM(d.[DISCOUNT_AMT]),
		SUM(d.[NON_RESALE_AMT]),
		SUM(d.[STATE_AMT]),
		SUM(d.[COUNTY_AMT]),
		SUM(d.[CITY_AMT]),
		SUM(d.[NETCHARGE]),
		SUM(d.[ADDL_CHARGE]),
		SUM(d.[LINE_TOTAL]),
		SUM(d.BILLING_AMT) AS [BILLING_AMT],
		d.AR_INV_NBR,
		d.AR_INV_SEQ,
		d.AR_TYPE,
		d.BILLING_USER,
		d.BILL_TYPE_FLAG,
		GRP = SUM(MBW.GRP),
		GROSS_IMPRESSIONS = SUM(MBW.GROSS_IMPRESSIONS),
		MEDIA_DEMO_DESCRIPTION = MBW.MEDIA_DEMO_DESCRIPTION,
		BOOKEND = MBW.BOOKEND,
		VALUE_ADDED = MBW.VALUE_ADDED
	FROM #media_orders AS o
		INNER JOIN dbo.TV_DETAIL AS d ON o.ORDER_NBR = d.ORDER_NBR
		LEFT OUTER JOIN (SELECT
								a.ORDER_NBR,
								LINE_NBR = a.ORDER_LINE_NBR, 
								GRP = SUM(a.GRP),
								GROSS_IMPRESSIONS =SUM(a.GROSS_IMPRESSIONS),
								a.MEDIA_DEMO_DESCRIPTION,
								a.BOOKEND,
								a.VALUE_ADDED
							FROM
								(SELECT 
										ORDER_NBR, 
										ORDER_LINE_NBR, 
										GRP = MBWMDD.SPOTS * MBWMD.PRIMARY_AQH_RATING,
										GROSS_IMPRESSIONS = MBWMDD.SPOTS * MBWMD.PRIMARY_AQH,
										MEDIA_DEMO_DESCRIPTION = md.[DESCRIPTION],
										MBWMD.BOOKEND,
										MBWMD.VALUE_ADDED
									FROM 
										dbo.MEDIA_BROADCAST_WORKSHEET MBW
										INNER JOIN dbo.MEDIA_BROADCAST_WORKSHEET_MARKET MBWM ON MBWM.MEDIA_BROADCAST_WORKSHEET_ID = MBW.MEDIA_BROADCAST_WORKSHEET_ID
										INNER JOIN dbo.MEDIA_BROADCAST_WORKSHEET_MARKET_DETAIL MBWMD ON MBWMD.MEDIA_BROADCAST_WORKSHEET_MARKET_ID = MBWM.MEDIA_BROADCAST_WORKSHEET_MARKET_ID
										INNER JOIN dbo.MEDIA_BROADCAST_WORKSHEET_MARKET_DETAIL_DATE MBWMDD ON MBWMDD.MEDIA_BROADCAST_WORKSHEET_MARKET_DETAIL_ID = MBWMD.MEDIA_BROADCAST_WORKSHEET_MARKET_DETAIL_ID
										INNER JOIN dbo.MEDIA_DEMO md ON md.MEDIA_DEMO_ID = MBW.PRIMARY_MEDIA_DEMO_ID
									WHERE 
										ORDER_NBR IS NOT NULL AND MBWMD.REVISION_NUMBER IN (SELECT MAX(REVISION_NUMBER) FROM dbo.MEDIA_BROADCAST_WORKSHEET_MARKET_DETAIL WHERE MEDIA_BROADCAST_WORKSHEET_MARKET_ID = MBWMD.MEDIA_BROADCAST_WORKSHEET_MARKET_ID GROUP BY MEDIA_BROADCAST_WORKSHEET_MARKET_ID)) AS a
							GROUP BY
								a.ORDER_NBR,
								a.ORDER_LINE_NBR,
								a.MEDIA_DEMO_DESCRIPTION,
								a.BOOKEND,
								a.VALUE_ADDED) AS MBW ON MBW.ORDER_NBR = d.ORDER_NBR AND MBW.LINE_NBR = d.LINE_NBR 
	GROUP BY 
		d.ORDER_NBR, d.LINE_NBR, d.REV_NBR, d.SEQ_NBR, d.MONTH_NBR,  
		d.YEAR_NBR, d.AR_INV_NBR, d.AR_INV_SEQ, d.AR_TYPE,
		d.BILLING_USER, d.BILL_TYPE_FLAG, MBW.MEDIA_DEMO_DESCRIPTION, MBW.BOOKEND, MBW.VALUE_ADDED
END

SELECT o.*, ar.GLEXACT, ar.AR_INV_DATE, ar.AR_POST_PERIOD
FROM #order_monthly AS o
LEFT JOIN #ar_info AS ar
	ON o.AR_INV_NBR = ar.AR_INV_NBR
	AND o.AR_TYPE = ar.AR_TYPE

END

GO