CREATE PROCEDURE [dbo].[advsp_broadcast_calendar_load]
AS
BEGIN

	SET NOCOUNT ON
	
	CREATE TABLE #BroadcastYear([RowID] [int] IDENTITY(1,1),
								[Year] [int])
									
	CREATE TABLE #BroadcastCalendar([Year] [int], 
									[Week] [int], 
									[Month] [int], 
									[WeekDate] [smalldatetime])

	DECLARE @RowCount AS int
	DECLARE @RowID AS int
	DECLARE @Year AS int
	DECLARE @WeekDate smalldatetime
	DECLARE @Count smallint
	DECLARE @WeekFound smallint
	DECLARE @Month int

	INSERT INTO #BroadcastYear
	SELECT 
		DISTINCT BRD_YEAR
	FROM 
		dbo.BRDCAST_CAL
	
	SET @RowCount = @@ROWCOUNT
	SET @RowID = 1

	WHILE @RowID <= @RowCount BEGIN

		SELECT
			@Year = [Year]
		FROM 
			#BroadcastYear
		WHERE
			RowID = @RowID

		SET @WeekFound = 0
		SET @Count = 0
		
		WHILE @Count < 60 AND @WeekFound < 53 BEGIN	
			
			SET @Count = @Count + 1 

			SELECT 
				@Month = CASE WHEN @Count BETWEEN 1 AND 5 THEN 1
							  WHEN @Count BETWEEN 6 AND 10 THEN 2
							  WHEN @Count BETWEEN 11 AND 15 THEN 3
							  WHEN @Count BETWEEN 16 AND 20 THEN 4
							  WHEN @Count BETWEEN 21 AND 25 THEN 5
							  WHEN @Count BETWEEN 26 AND 30 THEN 6
							  WHEN @Count BETWEEN 31 AND 35 THEN 7
							  WHEN @Count BETWEEN 36 AND 40 THEN 8
							  WHEN @Count BETWEEN 41 AND 45 THEN 9
							  WHEN @Count BETWEEN 46 AND 50 THEN 10
							  WHEN @Count BETWEEN 51 AND 55 THEN 11
							  WHEN @Count BETWEEN 56 AND 60 THEN 12 END,
				@WeekDate = CASE @Count WHEN 1 THEN JAN_WK1 WHEN 2 THEN JAN_WK2	WHEN 3 THEN JAN_WK3	WHEN 4 THEN JAN_WK4	WHEN 5 THEN JAN_WK5
										WHEN 6 THEN FEB_WK1	WHEN 7 THEN FEB_WK2	WHEN 8 THEN FEB_WK3	WHEN 9 THEN FEB_WK4	WHEN 10 THEN FEB_WK5
										WHEN 11 THEN MAR_WK1 WHEN 12 THEN MAR_WK2 WHEN 13 THEN MAR_WK3 WHEN 14 THEN MAR_WK4	WHEN 15 THEN MAR_WK5
										WHEN 16 THEN APR_WK1 WHEN 17 THEN APR_WK2 WHEN 18 THEN APR_WK3 WHEN 19 THEN APR_WK4 WHEN 20 THEN APR_WK5
										WHEN 21 THEN MAY_WK1 WHEN 22 THEN MAY_WK2 WHEN 23 THEN MAY_WK3 WHEN 24 THEN MAY_WK4	WHEN 25 THEN MAY_WK5
										WHEN 26 THEN JUN_WK1 WHEN 27 THEN JUN_WK2 WHEN 28 THEN JUN_WK3 WHEN 29 THEN JUN_WK4	WHEN 30 THEN JUN_WK5
										WHEN 31 THEN JUL_WK1 WHEN 32 THEN JUL_WK2 WHEN 33 THEN JUL_WK3 WHEN 34 THEN JUL_WK4	WHEN 35 THEN JUL_WK5
										WHEN 36 THEN AUG_WK1 WHEN 37 THEN AUG_WK2 WHEN 38 THEN AUG_WK3 WHEN 39 THEN AUG_WK4	WHEN 40 THEN AUG_WK5
										WHEN 41 THEN SEP_WK1 WHEN 42 THEN SEP_WK2 WHEN 43 THEN SEP_WK3 WHEN 44 THEN SEP_WK4 WHEN 45 THEN SEP_WK5
										WHEN 46 THEN OCT_WK1 WHEN 47 THEN OCT_WK2 WHEN 48 THEN OCT_WK3 WHEN 49 THEN OCT_WK4	WHEN 50 THEN OCT_WK5 
										WHEN 51 THEN NOV_WK1 WHEN 52 THEN NOV_WK2 WHEN 53 THEN NOV_WK3 WHEN 54 THEN NOV_WK4	WHEN 55 THEN NOV_WK5
										WHEN 56 THEN DEC_WK1 WHEN 57 THEN DEC_WK2 WHEN 58 THEN DEC_WK3 WHEN 59 THEN DEC_WK4	WHEN 60 THEN DEC_WK5 END
			FROM 
				dbo.BRDCAST_CAL
		    WHERE 
				BRD_YEAR = @Year
		
			IF @WeekDate IS NOT NULL BEGIN
			
				SET @WeekFound = @WeekFound + 1
				
				INSERT INTO #BroadcastCalendar 
				VALUES (@Year, @WeekFound, @Month, @WeekDate)
				
			END

			IF (@Count > 60) BEGIN
			
				BREAK
				
			END
			
		END

		SET @RowID = @RowID + 1
	
	END

	SELECT
		*
	FROM
		#BroadcastCalendar
		
	DROP TABLE #BroadcastYear
	DROP TABLE #BroadcastCalendar
	
END

GO


