if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[advsp_estimate_printing_quotes]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [dbo].[advsp_estimate_printing_quotes]
GO

CREATE PROCEDURE [dbo].[advsp_estimate_printing_quotes]
	@EstimateNumber AS Integer,
	@EstimateComponentNumber as Integer
AS
BEGIN

if @EstimateComponentNumber = 0
BEGIN
	SELECT 
			[JobNumber] = CAST(JC.JOB_NUMBER AS int),
			[JobDesc] = JL.JOB_DESC,
			[JobComponentNumber] = CAST(JC.JOB_COMPONENT_NBR AS smallint),
			[JobCompDesc] = JC.JOB_COMP_DESC,
			[JobComponent] = RIGHT('000000' + CAST(JC.JOB_NUMBER AS VARCHAR(15)), 6) + '-' + 
							 RIGHT('00' + CAST(JC.JOB_COMPONENT_NBR AS VARCHAR(10)), 2),
			[Estimate] = RIGHT('000000' + CAST(EL.ESTIMATE_NUMBER AS VARCHAR(15)), 6) + '-' + 
						 RIGHT('00' + CAST(EC.EST_COMPONENT_NBR AS VARCHAR(10)), 2) + '-' + 
						 RIGHT('00' + CAST(EQ.EST_QUOTE_NBR AS VARCHAR(10)), 2),
			[EstimateNumber] = EL.ESTIMATE_NUMBER,
			[EstDesc] = EL.EST_LOG_DESC,
			[EstimateComponentNumber] = EC.EST_COMPONENT_NBR,
			[EstCompDesc] = EC.EST_COMP_DESC,
			[QuoteNumber] = EQ.EST_QUOTE_NBR, 
			[QuoteDesc] = EQ.EST_QUOTE_DESC,
			[EstimateDate] = EL.EST_CREATE_DATE,
			[ClientCode] = EL.CL_CODE,   
			[ClientName] = C.CL_NAME, 
			[DivisionCode] = EL.DIV_CODE,   
			[DivisionName] = D.DIV_NAME, 
			[ProductCode] = EL.PRD_CODE, 
			[ProductName] = P.PRD_DESCRIPTION,
			[OfficeCode] = P.OFFICE_CODE,
			[OfficeName] = O.OFFICE_NAME,
			[Code] = RTRIM(LTRIM(STR(EL.ESTIMATE_NUMBER)))+'-'+RTRIM(LTRIM(STR(EC.EST_COMPONENT_NBR)))+'-'+RTRIM(LTRIM(STR(EQ.EST_QUOTE_NBR))),
			[Description] = RTRIM(LTRIM(STR(EL.ESTIMATE_NUMBER)))+'-'+RTRIM(LTRIM(STR(EC.EST_COMPONENT_NBR)))+'-'+RTRIM(LTRIM(STR(EQ.EST_QUOTE_NBR)))+ ' | ' + ISNULL(EQ.EST_QUOTE_DESC,'') +' | '+ EL.CL_CODE+' - '+EL.DIV_CODE+' - '+EL.PRD_CODE,
			[EstimateComment] = CAST(EL.EST_LOG_COMMENT AS varchar(MAX)),
			[EstimateComponentComment] = CAST(EC.EST_COMP_COMMENT AS varchar(MAX)),
			[EstimateQuoteComment] = CAST(EQ.EST_QTE_COMMENT AS varchar(MAX)),
			[CampaignID] = CASE WHEN EL.CMP_IDENTIFIER IS NOT NULL THEN EL.CMP_IDENTIFIER ELSE ISNULL(JL.CMP_IDENTIFIER,0) END,
			[CampaignCode] = CASE WHEN EL.CMP_IDENTIFIER IS NOT NULL THEN CMP_EST.CMP_CODE ELSE CMP.CMP_CODE END,
			[CampaignName] = CASE WHEN EL.CMP_IDENTIFIER IS NOT NULL THEN CMP_EST.CMP_NAME ELSE CMP.CMP_NAME END,
			[Campaign] = CASE WHEN EL.CMP_IDENTIFIER IS NOT NULL THEN 
							CASE WHEN CMP_EST.CMP_NAME IS NOT NULL THEN CMP_EST.CMP_NAME + ' (' + CAST(EL.CMP_IDENTIFIER AS VARCHAR(10)) + ')' ELSE NULL END 
						 ELSE 
						    CASE WHEN CMP.CMP_NAME IS NOT NULL THEN CMP.CMP_NAME + ' (' + CAST(JL.CMP_IDENTIFIER AS VARCHAR(10)) + ')' ELSE NULL END
						 END,
			[EstimateGroup] = CAST(EL.ESTIMATE_NUMBER AS VARCHAR(10)) + ' - ' + EL.EST_LOG_DESC,
			[CDP] = EL.CL_CODE + '|' + D.DIV_CODE + '|' + P.PRD_CODE,
			[EstimateContact] = EC.CDP_CONTACT_ID,
			[EstimateContactName] =  CDPC.CONT_FNAME + ' ' + CDPC.CONT_LNAME
		FROM  ESTIMATE_COMPONENT EC INNER JOIN
			  ESTIMATE_LOG EL ON EC.ESTIMATE_NUMBER = EL.ESTIMATE_NUMBER INNER JOIN
			  ESTIMATE_QUOTE EQ ON EC.ESTIMATE_NUMBER = EQ.ESTIMATE_NUMBER AND 
			  EC.EST_COMPONENT_NBR = EQ.EST_COMPONENT_NBR LEFT OUTER JOIN
			  JOB_COMPONENT JC ON JC.EST_COMPONENT_NBR = EC.EST_COMPONENT_NBR AND JC.ESTIMATE_NUMBER = EC.ESTIMATE_NUMBER INNER JOIN
			  PRODUCT P ON EL.CL_CODE = P.CL_CODE AND EL.DIV_CODE = P.DIV_CODE AND EL.PRD_CODE = P.PRD_CODE INNER JOIN
			  DIVISION D ON P.DIV_CODE = D.DIV_CODE AND P.CL_CODE = D.CL_CODE INNER JOIN
			  CLIENT C ON D.CL_CODE = C.CL_CODE LEFT OUTER JOIN
			  OFFICE O ON O.OFFICE_CODE = P.OFFICE_CODE LEFT OUTER JOIN
			  JOB_LOG JL ON JL.JOB_NUMBER = JC.JOB_NUMBER LEFT OUTER JOIN
			  CAMPAIGN CMP ON CMP.CMP_IDENTIFIER = JL.CMP_IDENTIFIER LEFT OUTER JOIN 
			  CDP_CONTACT_HDR AS CDPC ON CDPC.CDP_CONTACT_ID = EC.CDP_CONTACT_ID LEFT OUTER JOIN
			  CAMPAIGN CMP_EST ON CMP_EST.CMP_IDENTIFIER = EL.CMP_IDENTIFIER
		WHERE EL.ESTIMATE_NUMBER = @EstimateNumber		
END
ELSE
BEGIN
	SELECT 
			[JobNumber] = CAST(JC.JOB_NUMBER AS int),
			[JobDesc] = JL.JOB_DESC,
			[JobComponentNumber] = CAST(JC.JOB_COMPONENT_NBR AS smallint),
			[JobCompDesc] = JC.JOB_COMP_DESC,
			[JobComponent] = RIGHT('000000' + CAST(JC.JOB_NUMBER AS VARCHAR(15)), 6) + '-' + 
							 RIGHT('00' + CAST(JC.JOB_COMPONENT_NBR AS VARCHAR(10)), 2),
			[Estimate] = RIGHT('000000' + CAST(EL.ESTIMATE_NUMBER AS VARCHAR(15)), 6) + '-' + 
						 RIGHT('00' + CAST(EC.EST_COMPONENT_NBR AS VARCHAR(10)), 2) + '-' + 
						 RIGHT('00' + CAST(EQ.EST_QUOTE_NBR AS VARCHAR(10)), 2),
			[EstimateNumber] = EL.ESTIMATE_NUMBER,
			[EstDesc] = EL.EST_LOG_DESC,
			[EstimateComponentNumber] = EC.EST_COMPONENT_NBR,
			[EstCompDesc] = EC.EST_COMP_DESC,
			[QuoteNumber] = EQ.EST_QUOTE_NBR, 
			[QuoteDesc] = EQ.EST_QUOTE_DESC,
			[EstimateDate] = EL.EST_CREATE_DATE,
			[ClientCode] = EL.CL_CODE,   
			[ClientName] = C.CL_NAME, 
			[DivisionCode] = EL.DIV_CODE,   
			[DivisionName] = D.DIV_NAME, 
			[ProductCode] = EL.PRD_CODE, 
			[ProductName] = P.PRD_DESCRIPTION,
			[OfficeCode] = P.OFFICE_CODE,
			[OfficeName] = O.OFFICE_NAME,
			[Code] = RTRIM(LTRIM(STR(EL.ESTIMATE_NUMBER)))+'-'+RTRIM(LTRIM(STR(EC.EST_COMPONENT_NBR)))+'-'+RTRIM(LTRIM(STR(EQ.EST_QUOTE_NBR))),
			[Description] = RTRIM(LTRIM(STR(EL.ESTIMATE_NUMBER)))+'-'+RTRIM(LTRIM(STR(EC.EST_COMPONENT_NBR)))+'-'+RTRIM(LTRIM(STR(EQ.EST_QUOTE_NBR)))+ ' | ' + ISNULL(EQ.EST_QUOTE_DESC,'') +' | '+ EL.CL_CODE+' - '+EL.DIV_CODE+' - '+EL.PRD_CODE,
			[EstimateComment] = CAST(EL.EST_LOG_COMMENT AS varchar(MAX)),
			[EstimateComponentComment] = CAST(EC.EST_COMP_COMMENT AS varchar(MAX)),
			[EstimateQuoteComment] = CAST(EQ.EST_QTE_COMMENT AS varchar(MAX)),
			[CampaignID] = CASE WHEN EL.CMP_IDENTIFIER IS NOT NULL THEN EL.CMP_IDENTIFIER ELSE ISNULL(JL.CMP_IDENTIFIER,0) END,
			[CampaignCode] = CASE WHEN EL.CMP_IDENTIFIER IS NOT NULL THEN CMP_EST.CMP_CODE ELSE CMP.CMP_CODE END,
			[CampaignName] = CASE WHEN EL.CMP_IDENTIFIER IS NOT NULL THEN CMP_EST.CMP_NAME ELSE CMP.CMP_NAME END,
			[Campaign] = CASE WHEN EL.CMP_IDENTIFIER IS NOT NULL THEN 
							CASE WHEN CMP_EST.CMP_NAME IS NOT NULL THEN CMP_EST.CMP_NAME + ' (' + CAST(EL.CMP_IDENTIFIER AS VARCHAR(10)) + ')' ELSE NULL END 
						 ELSE 
						    CASE WHEN CMP.CMP_NAME IS NOT NULL THEN CMP.CMP_NAME + ' (' + CAST(JL.CMP_IDENTIFIER AS VARCHAR(10)) + ')' ELSE NULL END
						 END,
			[EstimateGroup] = CAST(EL.ESTIMATE_NUMBER AS VARCHAR(10)) + ' - ' + EL.EST_LOG_DESC,
			[CDP] = EL.CL_CODE + '|' + D.DIV_CODE + '|' + P.PRD_CODE,
			[EstimateContact] = EC.CDP_CONTACT_ID,
			[EstimateContactName] =  CDPC.CONT_FNAME + ' ' + CDPC.CONT_LNAME
		FROM  ESTIMATE_COMPONENT EC INNER JOIN
			  ESTIMATE_LOG EL ON EC.ESTIMATE_NUMBER = EL.ESTIMATE_NUMBER INNER JOIN
			  ESTIMATE_QUOTE EQ ON EC.ESTIMATE_NUMBER = EQ.ESTIMATE_NUMBER AND 
			  EC.EST_COMPONENT_NBR = EQ.EST_COMPONENT_NBR LEFT OUTER JOIN
			  JOB_COMPONENT JC ON JC.EST_COMPONENT_NBR = EC.EST_COMPONENT_NBR AND JC.ESTIMATE_NUMBER = EC.ESTIMATE_NUMBER INNER JOIN
			  PRODUCT P ON EL.CL_CODE = P.CL_CODE AND EL.DIV_CODE = P.DIV_CODE AND EL.PRD_CODE = P.PRD_CODE INNER JOIN
			  DIVISION D ON P.DIV_CODE = D.DIV_CODE AND P.CL_CODE = D.CL_CODE INNER JOIN
			  CLIENT C ON D.CL_CODE = C.CL_CODE LEFT OUTER JOIN
			  OFFICE O ON O.OFFICE_CODE = P.OFFICE_CODE LEFT OUTER JOIN
			  JOB_LOG JL ON JL.JOB_NUMBER = JC.JOB_NUMBER LEFT OUTER JOIN
			  CAMPAIGN CMP ON CMP.CMP_IDENTIFIER = JL.CMP_IDENTIFIER LEFT OUTER JOIN 
			  CDP_CONTACT_HDR AS CDPC ON CDPC.CDP_CONTACT_ID = EC.CDP_CONTACT_ID LEFT OUTER JOIN
			  CAMPAIGN CMP_EST ON CMP_EST.CMP_IDENTIFIER = EL.CMP_IDENTIFIER
		WHERE EL.ESTIMATE_NUMBER = @EstimateNumber AND EC.EST_COMPONENT_NBR = @EstimateComponentNumber		
END
	
		

END

GO


