CREATE PROCEDURE [dbo].[advsp_media_broadcast_schedule_report_summary_weekly] 
	@MEDIA_BROADCAST_WORKSHEET_MARKET_ID    VARCHAR(MAX) = '1'
	,@START_YEAR_MONTH						VARCHAR(10) = ''
	,@END_YEAR_MONTH						VARCHAR(10) = ''
	,@USE_PRIMARY_DEMO						VARCHAR(10) = ''
	,@HEADER								VARCHAR(100) = ''
	,@LOCATION_NAME							VARCHAR(100) = ''
	,@VENDOR_FILTER							VARCHAR(MAX) = ''
	,@NET_COST_INT							INT
AS
BEGIN

	SET NOCOUNT ON;
	
	DECLARE @Debug INT = 0
    DECLARE @Today DATE = GETDATE()

	DECLARE @NET_COST DECIMAL(18,3) = 1.00

	IF (@NET_COST_INT <> 100)
		SET @NET_COST = (@NET_COST_INT * 1.00)/100.00

	CREATE TABLE #VendorFilterTable (VN_CODE VARCHAR(20) COLLATE SQL_Latin1_General_CP1_CS_AS)

	CREATE UNIQUE INDEX VendorFilterTable_MarketID ON #VendorFilterTable (VN_CODE)

	CREATE TABLE #HeadLineTable (
		MEDIA_BROADCAST_WORKSHEET_MARKET_ID INT
		,START_DATE							DATE
		,END_DATE							DATE
	)

	CREATE UNIQUE INDEX HeadLineTable_MarketID ON #HeadLineTable (MEDIA_BROADCAST_WORKSHEET_MARKET_ID)

	DECLARE @START_DATE DATE
	DECLARE @END_DATE	DATE
	DECLARE @PRIMARY_DEMO INT

	IF (@START_YEAR_MONTH IS NOT NULL)
		SET @START_DATE = CONVERT(DATE,CONVERT(VARCHAR,(CONVERT(INT,@START_YEAR_MONTH) % 100))+'/01/'+CONVERT(VARCHAR,(CONVERT(INT,@START_YEAR_MONTH) / 100)))
	ELSE
		SET @START_DATE = NULL
	
	IF (@END_YEAR_MONTH IS NOT NULL)
		SET @END_DATE = DATEADD(DAY,-1,DATEADD(MONTH,1,CONVERT(DATE,CONVERT(VARCHAR,(CONVERT(INT,@END_YEAR_MONTH) % 100))+'/01/'+CONVERT(VARCHAR,(CONVERT(INT,@END_YEAR_MONTH) / 100)))))
	ELSE
		SET @END_DATE = NULL
	
	IF (@USE_PRIMARY_DEMO IS NOT NULL)
		SET @PRIMARY_DEMO = 1
	ELSE
		SET @PRIMARY_DEMO = 0

	INSERT INTO #HeadLineTable 
	SELECT 
		WORKSHEET.vint [MEDIA_BROADCAST_WORKSHEET_MARKET_ID]
		,@START_DATE	[START_DATE]
		,@END_DATE		[END_DATE]
	FROM
		[dbo].[charlist_to_table_int](@MEDIA_BROADCAST_WORKSHEET_MARKET_ID,',') WORKSHEET
			--INNER JOIN [dbo].[charlist_to_table_int](@START_YEAR_MONTH,',') STARTYEARMONTH
			--	ON WORKSHEET.listpos = STARTYEARMONTH.listpos
			--INNER JOIN [dbo].[charlist_to_table_int](@END_YEAR_MONTH,',') ENDYEARMONTH
			--	ON WORKSHEET.listpos = ENDYEARMONTH.listpos

	UPDATE #HeadLineTable
		SET
			START_DATE = [dbo].[advfn_broadcast_date](START_DATE,'B',HLT.MEDIA_BROADCAST_WORKSHEET_MARKET_ID)
			,END_DATE =  [dbo].[advfn_broadcast_date](END_DATE,'E', HLT.MEDIA_BROADCAST_WORKSHEET_MARKET_ID)
		FROM
			#HeadLineTable HLT

	IF (LEN(@VENDOR_FILTER) = 0)
		BEGIN			
			INSERT INTO #VendorFilterTable
			SELECT DISTINCT
				MBW_MD.VN_CODE
			FROM 
				MEDIA_BROADCAST_WORKSHEET MBW WITH (NOLOCK)
					INNER JOIN MEDIA_BROADCAST_WORKSHEET_MARKET MBW_M WITH (NOLOCK)
						ON MBW.MEDIA_BROADCAST_WORKSHEET_ID = MBW.MEDIA_BROADCAST_WORKSHEET_ID
					INNER JOIN MEDIA_BROADCAST_WORKSHEET_MARKET_DETAIL MBW_MD WITH (NOLOCK)
						ON MBW_M.MEDIA_BROADCAST_WORKSHEET_MARKET_ID = MBW_MD.MEDIA_BROADCAST_WORKSHEET_MARKET_ID
					INNER JOIN (SELECT 
							MEDIA_BROADCAST_WORKSHEET_MARKET_ID, REVISION_NUMBER = MAX(REVISION_NUMBER) 
						FROM dbo.MEDIA_BROADCAST_WORKSHEET_MARKET_DETAIL WITH (NOLOCK)
						GROUP BY MEDIA_BROADCAST_WORKSHEET_MARKET_ID) AS MMB_WM 
							ON MMB_WM.MEDIA_BROADCAST_WORKSHEET_MARKET_ID = MBW_MD.MEDIA_BROADCAST_WORKSHEET_MARKET_ID AND MBW_MD.REVISION_NUMBER = MMB_WM.REVISION_NUMBER
					INNER JOIN #HeadLineTable HLT
						ON MBW_M.MEDIA_BROADCAST_WORKSHEET_MARKET_ID = HLT.MEDIA_BROADCAST_WORKSHEET_MARKET_ID
			WHERE (1=1)
				AND MBW.IS_INACTIVE = 0
		END
	ELSE
		BEGIN
			INSERT INTO #VendorFilterTable
			SELECT
				VF.vstr
			FROM 
				dbo.charlist_to_table_tsa(@VENDOR_FILTER,',') VF
		END
		

	CREATE TABLE #MaxRevisionTable (
		MEDIA_BROADCAST_WORKSHEET_MARKET_ID INT
		,REVISION_NUMBER					INT
	)

	INSERT INTO #MaxRevisionTable
	SELECT 
		MEDIA_BROADCAST_WORKSHEET_MARKET_ID, 
		REVISION_NUMBER = MAX(REVISION_NUMBER) 
	FROM 
		dbo.MEDIA_BROADCAST_WORKSHEET_MARKET_DETAIL
	GROUP BY 
		MEDIA_BROADCAST_WORKSHEET_MARKET_ID

	DECLARE @TotalsTable TABLE
	(
		MEDIA_BROADCAST_WORKSHEET_MARKET_ID INT
		,[Date]								DATE
		,BroadcastDate						DATE
		,BroadCastWeekKey					BIGINT
		,PrimaryUniverse					BIGINT
		,PrimaryCume						BIGINT
		,PrimaryCumeImpressions				BIGINT
		,PrimaryGrossImpressions			BIGINT
		,PrimaryImpressions					BIGINT
		,PrimaryCPP							DECIMAL
		,PrimaryGRP							FLOAT

		,SecondaryUniverse					BIGINT
		,SecondaryCume						BIGINT
		,SecondaryCumeImpressions			BIGINT
		,SecondaryGrossImpressions			BIGINT
		,SecondaryImpressions				BIGINT
		,SecondaryCPP						DECIMAL
		,SecondaryGRP						FLOAT

		,Spots								INT
		,StationGross						DECIMAL(18,3)
		,Group1TotalGRP						FLOAT
		,Group2TotalGRP						FLOAT

		,MarketStationGross					DECIMAL(18,3)
		,MarketPrimaryGRP					FLOAT
		,MarketSecondaryGRP					FLOAT
	)

	INSERT INTO @TotalsTable
	SELECT
		MBW_M.MEDIA_BROADCAST_WORKSHEET_MARKET_ID
		,MBW_MDD.DATE
		,CASE WHEN ((CASE WHEN (MBW.MEDIA_BROADCAST_WORKSHEET_DATE_TYPE_ID =1) THEN 1 ELSE 7 END) = 7) THEN MC.BROADCAST_WEEKDATE ELSE MBW_MDD.DATE END
	
		--,(DATEPART(YEAR,MBW_MDD.DATE) * 10000) + (DATEPART(MONTH,MBW_MDD.DATE) * 100) + DATEPART(DAY,MBW_MDD.DATE)
		,(DATEPART(YEAR,CASE WHEN ((CASE WHEN (MBW.MEDIA_BROADCAST_WORKSHEET_DATE_TYPE_ID =1) THEN 1 ELSE 7 END) = 7) THEN MC.BROADCAST_WEEKDATE  ELSE MBW_MDD.DATE END) * 10000) 
			+ (DATEPART(MONTH,CASE WHEN ((CASE WHEN (MBW.MEDIA_BROADCAST_WORKSHEET_DATE_TYPE_ID =1) THEN 1 ELSE 7 END) = 7) THEN MC.BROADCAST_WEEKDATE  ELSE MBW_MDD.DATE END) * 100) 
			+ DATEPART(DAY,CASE WHEN ((CASE WHEN (MBW.MEDIA_BROADCAST_WORKSHEET_DATE_TYPE_ID =1) THEN 1 ELSE 7 END) = 7) THEN MC.BROADCAST_WEEKDATE  ELSE MBW_MDD.DATE END)
		,SUM(DISTINCT MBW_MD.PRIMARY_UNIVERSE)
		,SUM(DISTINCT MBW_MD.PRIMARY_CUME)
		,SUM(DISTINCT MBW_MD.PRIMARY_CUME_IMPRESSIONS)
		,CASE 
			WHEN (MBW.MEDIA_TYPE_CODE='T') THEN SUM(MBW_MDD.SPOTS * MBW_MD.PRIMARY_IMPRESSIONS)
			ELSE SUM(MBW_MDD.SPOTS * MBW_MD.PRIMARY_AQH)
		 END
		,CASE
			WHEN (MBW.MEDIA_TYPE_CODE='T') THEN SUM(DISTINCT MBW_MD.PRIMARY_IMPRESSIONS) 
			ELSE SUM(DISTINCT MBW_MD.PRIMARY_AQH) 
		 END
		,SUM(DISTINCT MBW_MD.PRIMARY_CPP)*1.0 
		
		,CASE
			WHEN (MBW.MEDIA_TYPE_CODE='T') THEN SUM(MBW_MD.PRIMARY_RATING * MBW_MDD.SPOTS * 1.000 )
			ELSE SUM(MBW_MD.PRIMARY_AQH_RATING * MBW_MDD.SPOTS * 1.000 )
		 END

		,SUM(DISTINCT MBW_MD.SECONDARY_UNIVERSE) 
		,SUM(DISTINCT MBW_MD.SECONDARY_CUME) 
		,SUM(DISTINCT MBW_MD.SECONDARY_CUME_IMPRESSIONS) 
		,CASE 
			WHEN (MBW.MEDIA_TYPE_CODE='T') THEN SUM(MBW_MDD.SPOTS * MBW_MD.SECONDARY_IMPRESSIONS)
			ELSE SUM(MBW_MDD.SPOTS * MBW_MD.SECONDARY_AQH)
		 END
		,CASE 
			WHEN (MBW.MEDIA_TYPE_CODE='T') THEN SUM(DISTINCT MBW_MD.SECONDARY_IMPRESSIONS) 
			ELSE SUM(DISTINCT MBW_MD.SECONDARY_AQH)
		END
		,SUM(DISTINCT MBW_MD.SECONDARY_CPP)*1.0 
		
		,CASE
			WHEN (MBW.MEDIA_TYPE_CODE='T') THEN SUM(MBW_MD.SECONDARY_RATING * MBW_MDD.SPOTS * 1.000)
			ELSE SUM(MBW_MD.SECONDARY_AQH_RATING * MBW_MDD.SPOTS * 1.000 )
		 END

		,SUM(MBW_MDD.SPOTS) 
		,SUM(MBW_MDD.RATE * MBW_MDD.SPOTS * @NET_COST)
		,CONVERT(FLOAT,SUM(MBW_MD.PRIMARY_GRP * MBW_MDD.SPOTS * 1.000))
		,CONVERT(FLOAT,SUM(MBW_MD.SECONDARY_GRP * MBW_MDD.SPOTS * 1.000))
		,0.0
		,CONVERT(FLOAT,0)
		,CONVERT(FLOAT,0)
	FROM
		MEDIA_BROADCAST_WORKSHEET MBW WITH (NOLOCK)
		INNER JOIN MEDIA_BROADCAST_WORKSHEET_MARKET MBW_M WITH (NOLOCK)
			ON MBW_M.MEDIA_BROADCAST_WORKSHEET_ID = MBW.MEDIA_BROADCAST_WORKSHEET_ID
		INNER JOIN MEDIA_BROADCAST_WORKSHEET_MARKET_DETAIL MBW_MD WITH (NOLOCK)
			ON MBW_MD.MEDIA_BROADCAST_WORKSHEET_MARKET_ID = MBW_M.MEDIA_BROADCAST_WORKSHEET_MARKET_ID
		INNER JOIN #MaxRevisionTable AS MMB_WM 
							ON MMB_WM.MEDIA_BROADCAST_WORKSHEET_MARKET_ID = MBW_MD.MEDIA_BROADCAST_WORKSHEET_MARKET_ID AND MBW_MD.REVISION_NUMBER = MMB_WM.REVISION_NUMBER
		INNER JOIN #VendorFilterTable VFT
			ON MBW_MD.VN_CODE = VFT.VN_CODE
		INNER JOIN MEDIA_BROADCAST_WORKSHEET_MARKET_DETAIL_DATE MBW_MDD WITH (NOLOCK)
			ON MBW_MD.MEDIA_BROADCAST_WORKSHEET_MARKET_DETAIL_ID = MBW_MDD.MEDIA_BROADCAST_WORKSHEET_MARKET_DETAIL_ID
		INNER JOIN #HeadLineTable HLT
			ON HLT.MEDIA_BROADCAST_WORKSHEET_MARKET_ID = MBW_M.MEDIA_BROADCAST_WORKSHEET_MARKET_ID
		INNER JOIN MEDIA_CALENDAR MC WITH (NOLOCK)
					ON MBW_MDD.DATE = MC.DATE
	WHERE (1=1)
		AND (MBW.IS_INACTIVE = 0)
		AND ((CASE WHEN ((CASE WHEN (MBW.MEDIA_BROADCAST_WORKSHEET_DATE_TYPE_ID =1) THEN 1 ELSE 7 END) = 7) THEN DATEADD(dd, -1*(DATEPART(dw, MBW_MDD.DATE)-2), MBW_MDD.DATE)  ELSE MBW_MDD.DATE END) BETWEEN HLT.START_DATE AND HLT.END_DATE)
	GROUP BY
		MBW.MEDIA_BROADCAST_WORKSHEET_DATE_TYPE_ID
		,MBW.MEDIA_TYPE_CODE
		,MBW_M.MEDIA_BROADCAST_WORKSHEET_MARKET_ID
		,CASE WHEN ((CASE WHEN (MBW.MEDIA_BROADCAST_WORKSHEET_DATE_TYPE_ID =1) THEN 1 ELSE 7 END) = 7) THEN MC.BROADCAST_WEEKDATE  ELSE MBW_MDD.DATE END
		,MBW_MDD.DATE
		,MC.BROADCAST_WEEKDATE
		
	DECLARE @SumTotalStationGross DECIMAL
	DECLARE @SumTotalGroup1GRP FLOAT
	DECLARE @SumTotalGroup2GRP FLOAT

	UPDATE @TotalsTable
		SET 
			Group1TotalGRP = SM.Group1TotalGRP
			,Group2TotalGRP = SM.Group2TotalGRP
		FROM @TotalsTable TT
			INNER JOIN (
							SELECT
								MEDIA_BROADCAST_WORKSHEET_MARKET_ID
								,SUM(TTX.PrimaryGRP) Group1TotalGRP
								,SUM(TTX.SecondaryGRP) Group2TotalGRP
							FROM
								@TotalsTable TTX
							GROUP BY 
								MEDIA_BROADCAST_WORKSHEET_MARKET_ID)SM
					ON TT.MEDIA_BROADCAST_WORKSHEET_MARKET_ID = SM.MEDIA_BROADCAST_WORKSHEET_MARKET_ID

	UPDATE @TotalsTable
		SET 
			MarketStationGross = SM.MarketStationGross
			,MarketPrimaryGRP = SM.MarketPrimaryGRP
			,MarketSecondaryGRP = SM.MarketSecondaryGRP
	FROM
		@TotalsTable TT
			INNER JOIN (
					SELECT
						MEDIA_BROADCAST_WORKSHEET_MARKET_ID
						,SUM(TX.StationGross) MarketStationGross
						,SUM(TX.Group1TotalGRP) MarketPrimaryGRP
						,SUM(TX.Group2TotalGRP) MarketSecondaryGRP
					FROM @TotalsTable TX
					GROUP BY
						MEDIA_BROADCAST_WORKSHEET_MARKET_ID
					)SM
				ON TT.MEDIA_BROADCAST_WORKSHEET_MARKET_ID = SM.MEDIA_BROADCAST_WORKSHEET_MARKET_ID

	SELECT
		@SumTotalStationGross = SUM(TT.StationGross)
		,@SumTotalGroup1GRP = SUM(TT.PrimaryGRP)
		,@SumTotalGroup2GRP = SUM(TT.SecondaryGRP)
	FROM @TotalsTable TT

	IF (@Debug = 1)
		BEGIN
			SELECT * FROm @TotalsTable
		END
		
	SELECT DISTINCT
		RH.MEDIA_BROADCAST_WORKSHEET_ID			
		,RH.MEDIA_BROADCAST_WORKSHEET_MARKET_ID
		,RH.WorksheetName
		,MC.BROADCAST_YEAR										[Broadcastyear]
		,MC.BROADCAST_QUARTER									[BroadcastQuarter]
		,MC.BROADCAST_WEEK_OF_QUARTER							[BroadcastWeekOfQuarter]
		,TT.BroadCastWeekKey
		--,MBW_MDD.DATE											[ReportDate]
		,TT.BroadcastDate										[ReportDate]
		,RH.MARKET_DESC											[MarketDescription]	
		,RH.MARKET_CODE											[MarketCode]
		,RH.IsGross
		,RH.GROUP1_NAME											[Group1Name]					
		,RH.GROUP1_ID								
		,RH.GROUP2_NAME											[Group2Name]			
		,RH.GROUP2_ID								
		,RH.EstimateComments						
		,RH.Estitmate								
		,RH.Description							
		,RH.ClientName								
		,RH.WorksheetName	
		,@HEADER HeaderBand								
		,D_T.NAME DateTypeName
		,RH.Media									
		,RH.Product								
		,RH.Market									
		,RH.PrimaryDemographic						
									
		,RH.StartDate								
		,RH.EndDate								
			
		,RH.DivisionName							
		,RH.RatingsServiceID						
		,RH.SharebookNielsenTVBookID				
		,RH.HutputNielsenTVBookID
		,RH.RadioBookID1
		,RH.RadioBookID2
		,RH.RadioBookID3
		,RH.RadioBookID4
		,RH.RadioBookID5
		,RH.Survey
		,RH.TRSource1
		,RH.TRSource2
		,RH.SurveyLine2
		,RH.PageHeaderComment
		,RH.PageHeaderLogoPathLand
		,RH.BuyerEmpCode
		,RH.Buyer
		,RH.RatingsSource
		,RH.UsePrimaryDemo
		,RH.[Geography]
		,RH.MediaTypeCode
		,RH.RadioSource

		,TT.PrimaryUniverse			
		,TT.PrimaryCume				
		,TT.PrimaryCumeImpressions		
		,TT.PrimaryGrossImpressions	
		,TT.PrimaryImpressions			
		,TT.PrimaryCPP			Group1PrimaryCPP		
		,TT.PrimaryGRP			Group1PrimaryGRP			
		,TT.Group1TotalGRP
		,TT.Group2TotalGRP
		,TT.SecondaryUniverse			
		,TT.SecondaryCume				
		,TT.SecondaryCumeImpressions	
		,TT.SecondaryGrossImpressions	
		,TT.SecondaryImpressions		
		,TT.SecondaryCPP		Group2PrimaryCPP		
		,TT.SecondaryGRP		Group2PrimaryGRP		
		,TT.Spots						
		,TT.StationGross
		,TT.MarketStationGross
		,TT.MarketPrimaryGRP
		,TT.MarketSecondaryGRP 
		,0.0 PrimaryRating
		,0.0 SecondaryRating
		,0.0 BookPrimaryRating
		,0.0 BookSecondaryRating
		 ,@SumTotalGroup1GRP		TotalGroup1GRP
		 ,@SumTotalGroup2GRP		TotalGroup2GRP
		 
		 ,CASE	
			WHEN (PrimaryGrossImpressions = 0) THEN 0.0
			ELSE StationGross/(PrimaryGrossImpressions * 0.001)
		  End			Group1CPM
		,CASE	
			WHEN (SecondaryGrossImpressions = 0) THEN 0.0
			ELSE StationGross/(SecondaryGrossImpressions * 0.001)
		  End			Group2CPM
 
	FROM 
		dbo.advtf_media_broadcast_schedule_header(@MEDIA_BROADCAST_WORKSHEET_MARKET_ID,@USE_PRIMARY_DEMO, @HEADER, @LOCATION_NAME ,@VENDOR_FILTER	) RH
			INNER JOIN MEDIA_BROADCAST_WORKSHEET MBW WITH (NOLOCK) ON MBW.MEDIA_BROADCAST_WORKSHEET_ID = RH.MEDIA_BROADCAST_WORKSHEET_ID
			INNER JOIN MEDIA_BROADCAST_WORKSHEET_MARKET MBW_M WITH (NOLOCK) ON MBW_M.MEDIA_BROADCAST_WORKSHEET_ID = RH.MEDIA_BROADCAST_WORKSHEET_ID
			INNER JOIN #HeadLineTable HLT ON MBW_M.MEDIA_BROADCAST_WORKSHEET_MARKET_ID = HLT.MEDIA_BROADCAST_WORKSHEET_MARKET_ID
			INNER JOIN @TotalsTable TT ON RH.MEDIA_BROADCAST_WORKSHEET_MARKET_ID = TT.MEDIA_BROADCAST_WORKSHEET_MARKET_ID
			INNER JOIN MEDIA_CALENDAR MC WITH (NOLOCK) ON TT.[Date] = MC.DATE
			INNER JOIN [dbo].[MEDIA_BROADCAST_WORKSHEET_DATE_TYPE] D_T WITH (NOLOCK) ON MBW.MEDIA_BROADCAST_WORKSHEET_DATE_TYPE_ID = D_T.MEDIA_BROADCAST_WORKSHEET_DATE_TYPE_ID
	WHERE (1=1)
			AND TT.BroadcastDate BETWEEN HLT.START_DATE AND HLT.END_DATE
	GROUP BY
		RH.MEDIA_BROADCAST_WORKSHEET_ID		
		,MBW.MEDIA_BROADCAST_WORKSHEET_DATE_TYPE_ID	
		,RH.MEDIA_BROADCAST_WORKSHEET_MARKET_ID
		,RH.WorksheetName
		,MC.BROADCAST_YEAR
		,MC.BROADCAST_QUARTER
		,MC.BROADCAST_WEEK_OF_QUARTER
		,MC.BROADCAST_WEEKDATE
		,TT.BroadcastDate
		,TT.BroadCastWeekKey
		--,MBW_MDD.DATE
		--,CASE WHEN ((CASE WHEN (MBW.MEDIA_BROADCAST_WORKSHEET_DATE_TYPE_ID =1) THEN 1 ELSE 7 END) = 7) THEN MC.BROADCAST_WEEKDATE  ELSE MBW_MDD.DATE END
		,RH.BuyOrder
		,RH.BuyRevision	
		,RH.MARKET_DESC							
		,RH.MARKET_CODE
		,RH.IsGross							
		,RH.GROUP1_NAME							
		,RH.GROUP1_ID								
		,RH.GROUP2_NAME							
		,RH.GROUP2_ID								
		,RH.EstimateComments						
		,RH.Estitmate								
		,RH.Description							
		,RH.ClientName	
		,RH.WorksheetName								
		,RH.HeaderBand	
		,D_T.NAME							
		,RH.Media									
		,RH.Product								
		,RH.Market									
		,RH.PrimaryDemographic												
		,RH.StartDate								
		,RH.EndDate												
		,RH.DivisionName							
		,RH.RatingsServiceID						
		,RH.SharebookNielsenTVBookID				
		,RH.HutputNielsenTVBookID
		,RH.RadioBookID1
		,RH.RadioBookID2
		,RH.RadioBookID3
		,RH.RadioBookID4
		,RH.RadioBookID5											
		,RH.Survey
		,RH.TRSource1
		,RH.TRSource2
		,RH.SurveyLine2
		,RH.PageHeaderComment
		,RH.PageHeaderLogoPathLand
		,RH.BuyerEmpCode
		,RH.Buyer
		,RH.RatingsSource
		,RH.UsePrimaryDemo
		,RH.MediaCode
		,RH.[Geography]
		,RH.MediaTypeCode
		,RH.RadioSource

		,TT.PrimaryUniverse			
		,TT.PrimaryCume				
		,TT.PrimaryCumeImpressions		
		,TT.PrimaryGrossImpressions	
		,TT.PrimaryImpressions			
		,TT.PrimaryCPP					
		,TT.PrimaryGRP					
		,TT.Group1TotalGRP
		,TT.Group2TotalGRP
		,TT.SecondaryUniverse			
		,TT.SecondaryCume				
		,TT.SecondaryCumeImpressions	
		,TT.SecondaryGrossImpressions	
		,TT.SecondaryImpressions		
		,TT.SecondaryCPP				
		,TT.SecondaryGRP				
		,TT.Spots						
		,TT.StationGross
		,TT.MarketStationGross
		,TT.MarketPrimaryGRP
		,TT.MarketSecondaryGRP	
		--,MBW_MD.BOOK_PRIMARY_RATING
		--,MBW_MD.BOOK_PRIMARY_AQH_RATING
		--,MBW_MD.BOOK_SECONDARY_RATING
		--,MBW_MD.BOOK_SECONDARY_AQH_RATING
	ORDER BY
		RH.MEDIA_BROADCAST_WORKSHEET_ID			
		,RH.MEDIA_BROADCAST_WORKSHEET_MARKET_ID
		,MC.BROADCAST_YEAR
		,MC.BROADCAST_QUARTER
		,MC.BROADCAST_WEEK_OF_QUARTER
	
END

GO