
CREATE PROCEDURE dbo.advsp_bill_cmd_ctr_brdcast_selection @order_number_in integer, @rt_flag_in varchar(10), @brdcast_mth1_in varchar(10), 
	@brdcast_mth2_in varchar(10), @bcc_id_in integer, @incl_zero_spots bit, @ret_val integer OUTPUT
AS

SET NOCOUNT ON

DECLARE @setup_active smallint, @brdcast_mth1 smalldatetime, @brdcast_mth2 smalldatetime

SELECT @ret_val = 0

CREATE TABLE #brdcast_selection (
	ROW_TYPE		varchar(1) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
	CL_CODE			varchar(6) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
	DIV_CODE		varchar(6) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
	PRD_CODE		varchar(6) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
	ORDER_NBR		integer NOT NULL,
	BRDCAST_MONTH	smalldatetime NULL,
	LINE_NBR		integer NULL,
	REV_NBR			smallint NULL,
	OFFICE_CODE		varchar(6) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
	CMP_IDENTIFIER	integer NULL,
	CMP_NAME		varchar(128) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
	MARKET_CODE		varchar(10) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
	VN_CODE			varchar(6) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
	VN_NAME			varchar(40) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
	LINK_ID			integer NULL,
	CLIENT_PO		varchar(25) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
	BUYER			varchar(40) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
	MAX_REV			integer NULL,
	ORDER_DESC		varchar(40) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
	MEDIA_TYPE		varchar(6) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
	SC_DESC			varchar(30) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
	MEDIA_FROM		varchar(8) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
	ORDER_DATE		smalldatetime NULL,
	INSERTION_DATE	smalldatetime NULL,
	CLOSE_DATE		smalldatetime NULL,
	DATE_TO_BILL	smalldatetime NULL,
	BILLING_USER	varchar(100) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
	NET_AMT			decimal(15,2) NULL,
	COMM_AMT		decimal(15,2) NULL,
	REBATE_AMT		decimal(15,2) NULL,
	ADDTL_CHARGES	decimal(15,2) NULL,
	DISCOUNT_AMT	decimal(15,2) NULL,
	NET_CHARGES		decimal(15,2) NULL,
	VENDOR_TAX		decimal(15,2) NULL,
	RESALE_TAX		decimal(15,2) NULL,
	BILLABLE_AMT	decimal(15,2) NULL,
	BILLED_AMT		decimal(15,2) NULL,
	UNBILLED_AMT	decimal(15,2) NULL,
	AP_POSTED_AMT	decimal(15,2) NULL,
	BILL_STATUS		smallint NULL,
	BILL_TYPE		smallint NULL,
	ORDER_PROC_CTL	smallint NULL,
	SETUP_COMPLETE	smallint NULL,
	SPOTS			integer NULL )

	SELECT @setup_active = ( SELECT COALESCE( BILL_MEDIA_TYPE, 0 ) FROM dbo.AGENCY )
	
	SELECT @brdcast_mth1 = CAST( @brdcast_mth1_in AS smalldatetime )
	SELECT @brdcast_mth2 = CAST( @brdcast_mth2_in AS smalldatetime )
	
	IF ( @rt_flag_in = 'Radio' )
	BEGIN
			INSERT INTO #brdcast_selection ( ROW_TYPE, CL_CODE, DIV_CODE, PRD_CODE, ORDER_NBR, LINE_NBR, REV_NBR, 
					BRDCAST_MONTH, OFFICE_CODE, CMP_IDENTIFIER, CMP_NAME, MARKET_CODE, VN_CODE, VN_NAME, LINK_ID, 
					CLIENT_PO, BUYER, MAX_REV, ORDER_DESC, MEDIA_TYPE, SC_DESC, MEDIA_FROM, ORDER_DATE, 
					ORDER_PROC_CTL, BILL_STATUS, SETUP_COMPLETE, BILLING_USER, BILL_TYPE, CLOSE_DATE, SPOTS, 
					NET_AMT, COMM_AMT, REBATE_AMT, DISCOUNT_AMT, NET_CHARGES, VENDOR_TAX, RESALE_TAX, 
					BILLABLE_AMT, BILLED_AMT, UNBILLED_AMT, AP_POSTED_AMT )
			 SELECT 'D', rh.CL_CODE, rh.DIV_CODE, rh.PRD_CODE, rh.ORDER_NBR, vrd.LINE_NBR, vrd.REV_NBR, 
					CAST( CAST( vrd.MONTH_IND AS varchar(2)) + '/01/' + CAST( vrd.BRDCAST_YEAR AS varchar(4)) AS smalldatetime ),
					p.OFFICE_CODE, rh.CMP_IDENTIFIER, c.CMP_NAME, rh.MARKET_CODE, rh.VN_CODE, v.VN_NAME, rh.LINK_ID, 
					rh.CLIENT_PO, rh.BUYER, NULL AS MAX_REV, rh.ORDER_DESC, rh.MEDIA_TYPE, sc.SC_DESCRIPTION, 
					'Radio', rh.ORDER_DATE, rh.ORD_PROCESS_CONTRL, COALESCE( p.PRD_RADIO_PRE_POST, 1 ), 
					CASE WHEN ( @setup_active = 1 ) THEN COALESCE( p.RADIO_SETUP_COMPLETE, 0 ) ELSE NULL END,
					rd.BILLING_USER, rh.BILL_TYPE_FLAG, rd.CLOSE_DATE, vrd.SPOTS, COALESCE( vrd.LINE_NET, 0.00 ), 
					COALESCE( vrd.COMM_AMT, 0.00 ), COALESCE( vrd.REBATE_AMT, 0.00 ), COALESCE( vrd.DISCOUNT, 0.00 ), 
					COALESCE( rd.NETCHARGES, 0.00 ), COALESCE( vrd.VENDOR_TAX, 0.00 ), 
					COALESCE( vrd.STATE_TAX , 0.00 ) + COALESCE( vrd.COUNTY_TAX, 0.00 ) + COALESCE( vrd.CITY_TAX, 0.00 ),
					COALESCE( vrd.BILLING_AMT, 0.00 ), 
					CASE WHEN vrd.AR_INV_NBR IS NULL THEN 0.00 ELSE COALESCE( vrd.BILLING_AMT, 0.00 ) END,
					CASE WHEN vrd.AR_INV_NBR IS NULL THEN COALESCE( vrd.BILLING_AMT, 0.00 ) ELSE 0.00 END,
					( SELECT COALESCE( SUM( COALESCE( ap.LINE_TOTAL, 0.00 )), 0.00 ) 
                        FROM dbo.AP_RADIO ap 
                       WHERE ap.ORDER_NBR = vrd.ORDER_NBR
						 AND ap.BRDCAST_MONTH = vrd.MONTH_SHORT
						 AND ap.BRDCAST_YEAR = vrd.BRDCAST_YEAR
                         AND ( ap.DELETE_FLAG IS NULL OR ap.DELETE_FLAG = 0 )) 
			   FROM dbo.V_RADIO_DETAIL1 vrd
		 INNER JOIN dbo.RADIO_DETAIL1 rd 
				 ON vrd.ORDER_NBR = rd.ORDER_NBR 
				AND vrd.LINE_NBR = rd.LINE_NBR 
				AND vrd.REV_NBR = rd.REV_NBR		
				AND vrd.SEQ_NBR = rd.SEQ_NBR
				AND vrd.BRDCAST_YEAR = rd.BRDCAST_YEAR
		 INNER JOIN dbo.RADIO_HEADER rh ON ( vrd.ORDER_NBR = rh.ORDER_NBR ) AND ( vrd.REV_NBR = rh.REV_NBR )
		 INNER JOIN dbo.VENDOR v ON ( rh.VN_CODE = v.VN_CODE ) 
		 INNER JOIN dbo.PRODUCT p ON ( rh.CL_CODE = p.CL_CODE AND rh.DIV_CODE = p.DIV_CODE AND rh.PRD_CODE = p.PRD_CODE ) 
	LEFT OUTER JOIN dbo.SALES_CLASS sc ON ( rh.MEDIA_TYPE = sc.SC_CODE ) 
	LEFT OUTER JOIN dbo.CAMPAIGN c ON ( rh.CMP_IDENTIFIER = c.CMP_IDENTIFIER ) 	
			  WHERE vrd.ORDER_NBR = @order_number_in   
				AND ( CAST( CAST( vrd.MONTH_IND AS varchar(2)) + '/01/' + CAST( vrd.BRDCAST_YEAR AS varchar(4)) AS smalldatetime ) 
					BETWEEN @brdcast_mth1 AND @brdcast_mth2 )
	END
	
	IF ( @rt_flag_in = 'TV' )
	BEGIN
			INSERT INTO #brdcast_selection ( ROW_TYPE, CL_CODE, DIV_CODE, PRD_CODE, ORDER_NBR, LINE_NBR, REV_NBR, 
					BRDCAST_MONTH, OFFICE_CODE, CMP_IDENTIFIER, CMP_NAME, MARKET_CODE, VN_CODE, VN_NAME, LINK_ID, 
					CLIENT_PO, BUYER, MAX_REV, ORDER_DESC, MEDIA_TYPE, SC_DESC, MEDIA_FROM, ORDER_DATE, 
					ORDER_PROC_CTL, BILL_STATUS, SETUP_COMPLETE, BILLING_USER, BILL_TYPE, CLOSE_DATE, SPOTS,
					NET_AMT, COMM_AMT, REBATE_AMT, DISCOUNT_AMT, NET_CHARGES, VENDOR_TAX, RESALE_TAX, 
					BILLABLE_AMT, BILLED_AMT, UNBILLED_AMT, AP_POSTED_AMT )
			 SELECT 'D', th.CL_CODE, th.DIV_CODE, th.PRD_CODE, th.ORDER_NBR, vtd.LINE_NBR, vtd.REV_NBR, 
					CAST( CAST( vtd.MONTH_IND AS varchar(2)) + '/01/' + CAST( vtd.BRDCAST_YEAR AS varchar(4)) AS smalldatetime ),
					th.OFFICE_CODE, th.CMP_IDENTIFIER, c.CMP_NAME, th.MARKET_CODE, th.VN_CODE, v.VN_NAME, th.LINK_ID, 
					th.CLIENT_PO, th.BUYER, NULL AS MAX_REV, th.ORDER_DESC, th.MEDIA_TYPE, sc.SC_DESCRIPTION, 
					'TV', th.ORDER_DATE, th.ORD_PROCESS_CONTRL, COALESCE( p.PRD_TV_PRE_POST, 1 ), 
					CASE WHEN ( @setup_active = 1 ) THEN COALESCE( p.TV_SETUP_COMPLETE, 0 ) ELSE NULL END,
					td.BILLING_USER, th.BILL_TYPE_FLAG, td.CLOSE_DATE, vtd.SPOTS, COALESCE( vtd.LINE_NET, 0.00 ), 
					COALESCE( vtd.COMM_AMT, 0.00 ), COALESCE( vtd.REBATE_AMT, 0.00 ), COALESCE( vtd.DISCOUNT, 0.00 ), 
					COALESCE( td.NETCHARGES, 0.00 ), COALESCE( vtd.VENDOR_TAX, 0.00 ), 
					COALESCE( vtd.STATE_TAX , 0.00 ) + COALESCE( vtd.COUNTY_TAX, 0.00 ) + COALESCE( vtd.CITY_TAX, 0.00 ),
					COALESCE( vtd.BILLING_AMT, 0.00 ), 
					CASE WHEN vtd.AR_INV_NBR IS NULL THEN 0.00 ELSE COALESCE( vtd.BILLING_AMT, 0.00 ) END,
					CASE WHEN vtd.AR_INV_NBR IS NULL THEN COALESCE( vtd.BILLING_AMT, 0.00 ) ELSE 0.00 END,
					( SELECT COALESCE( SUM( COALESCE( ap.LINE_TOTAL, 0.00 )), 0.00 ) 
                        FROM dbo.AP_TV ap 
                       WHERE ap.ORDER_NBR = vtd.ORDER_NBR
						 AND ap.BRDCAST_MONTH = vtd.MONTH_SHORT
						 AND ap.BRDCAST_YEAR = vtd.BRDCAST_YEAR
                         AND ( ap.DELETE_FLAG IS NULL OR ap.DELETE_FLAG = 0 )) 
			   FROM dbo.V_TV_DETAIL1 vtd
		 INNER JOIN dbo.TV_DETAIL1 td 
				 ON vtd.ORDER_NBR = td.ORDER_NBR 
				AND vtd.LINE_NBR = td.LINE_NBR 
				AND vtd.REV_NBR = td.REV_NBR		
				AND vtd.SEQ_NBR = td.SEQ_NBR
				AND vtd.BRDCAST_YEAR = td.BRDCAST_YEAR
		 INNER JOIN dbo.TV_HEADER th ON ( vtd.ORDER_NBR = th.ORDER_NBR ) AND ( vtd.REV_NBR = th.REV_NBR )
		 INNER JOIN dbo.VENDOR v ON ( th.VN_CODE = v.VN_CODE ) 
		 INNER JOIN dbo.PRODUCT p ON ( th.CL_CODE = p.CL_CODE AND th.DIV_CODE = p.DIV_CODE AND th.PRD_CODE = p.PRD_CODE ) 
	LEFT OUTER JOIN dbo.SALES_CLASS sc ON ( th.MEDIA_TYPE = sc.SC_CODE ) 
	LEFT OUTER JOIN dbo.CAMPAIGN c ON ( th.CMP_IDENTIFIER = c.CMP_IDENTIFIER ) 	
			  WHERE vtd.ORDER_NBR = @order_number_in
			  	AND ( CAST( CAST( vtd.MONTH_IND AS varchar(2)) + '/01/' + CAST( vtd.BRDCAST_YEAR AS varchar(4)) AS smalldatetime ) 
			  		BETWEEN @brdcast_mth1 AND @brdcast_mth2 )
	END                           
	         
	-- Summarized by line                           
	INSERT INTO #brdcast_selection ( ROW_TYPE, CL_CODE, DIV_CODE, PRD_CODE, ORDER_NBR, LINE_NBR, BRDCAST_MONTH, 
			MEDIA_FROM, VN_CODE, VN_NAME, BILL_STATUS, SETUP_COMPLETE, OFFICE_CODE, CMP_IDENTIFIER, CMP_NAME, 
			MARKET_CODE, LINK_ID, CLIENT_PO, BUYER, ORDER_DESC, MEDIA_TYPE, SC_DESC, ORDER_DATE, ORDER_PROC_CTL, 
			BILLING_USER, BILL_TYPE, CLOSE_DATE, NET_CHARGES, NET_AMT, COMM_AMT, REBATE_AMT, DISCOUNT_AMT, 
			VENDOR_TAX, RESALE_TAX,	BILLABLE_AMT, BILLED_AMT, UNBILLED_AMT, AP_POSTED_AMT )
	 SELECT 'L', BS.CL_CODE, BS.DIV_CODE, BS.PRD_CODE, BS.ORDER_NBR, BS.LINE_NBR, CAST( NULL AS smalldatetime ), 
			BS.MEDIA_FROM,
				( SELECT TOP 1 bs.VN_CODE FROM #brdcast_selection bs 
				   WHERE bs.ROW_TYPE = 'D' AND bs.ORDER_NBR = BS.ORDER_NBR AND bs.LINE_NBR = BS.LINE_NBR ORDER BY bs.ORDER_NBR DESC, bs.REV_NBR DESC ),
				( SELECT TOP 1 bs.VN_NAME FROM #brdcast_selection bs 
				   WHERE bs.ROW_TYPE = 'D' AND bs.ORDER_NBR = BS.ORDER_NBR AND bs.LINE_NBR = BS.LINE_NBR ORDER BY bs.ORDER_NBR DESC, bs.REV_NBR DESC ),
			BS.BILL_STATUS, BS.SETUP_COMPLETE, 
				( SELECT TOP 1 bs.OFFICE_CODE FROM #brdcast_selection bs 
				   WHERE bs.ROW_TYPE = 'D' AND bs.ORDER_NBR = BS.ORDER_NBR AND bs.LINE_NBR = BS.LINE_NBR ORDER BY bs.OFFICE_CODE DESC ),
				( SELECT TOP 1 bs.CMP_IDENTIFIER FROM #brdcast_selection bs 
				   WHERE bs.ROW_TYPE = 'D' AND bs.ORDER_NBR = BS.ORDER_NBR AND bs.LINE_NBR = BS.LINE_NBR ORDER BY bs.CMP_IDENTIFIER DESC ),
				( SELECT TOP 1 bs.CMP_NAME FROM #brdcast_selection bs 
				   WHERE bs.ROW_TYPE = 'D' AND bs.ORDER_NBR = BS.ORDER_NBR AND bs.LINE_NBR = BS.LINE_NBR ORDER BY bs.CMP_NAME DESC ),
				( SELECT TOP 1 bs.MARKET_CODE FROM #brdcast_selection bs 
				   WHERE bs.ROW_TYPE = 'D' AND bs.ORDER_NBR = BS.ORDER_NBR AND bs.LINE_NBR = BS.LINE_NBR ORDER BY bs.MARKET_CODE DESC ),
				( SELECT TOP 1 bs.LINK_ID FROM #brdcast_selection bs 
				   WHERE bs.ROW_TYPE = 'D' AND bs.ORDER_NBR = BS.ORDER_NBR AND bs.LINE_NBR = BS.LINE_NBR ORDER BY bs.LINK_ID DESC ),
				( SELECT TOP 1 bs.CLIENT_PO FROM #brdcast_selection bs 
				   WHERE bs.ROW_TYPE = 'D' AND bs.ORDER_NBR = BS.ORDER_NBR AND bs.LINE_NBR = BS.LINE_NBR ORDER BY bs.CLIENT_PO DESC ),
				( SELECT TOP 1 bs.BUYER FROM #brdcast_selection bs 
				   WHERE bs.ROW_TYPE = 'D' AND bs.ORDER_NBR = BS.ORDER_NBR AND bs.LINE_NBR = BS.LINE_NBR ORDER BY bs.BUYER DESC ),
				( SELECT TOP 1 bs.ORDER_DESC FROM #brdcast_selection bs 
				   WHERE bs.ROW_TYPE = 'D' AND bs.ORDER_NBR = BS.ORDER_NBR AND bs.LINE_NBR = BS.LINE_NBR ORDER BY bs.ORDER_DESC DESC ),
				( SELECT TOP 1 bs.MEDIA_TYPE FROM #brdcast_selection bs 
				   WHERE bs.ROW_TYPE = 'D' AND bs.ORDER_NBR = BS.ORDER_NBR AND bs.LINE_NBR = BS.LINE_NBR ORDER BY bs.MEDIA_TYPE DESC ),
				( SELECT TOP 1 bs.SC_DESC FROM #brdcast_selection bs 
				   WHERE bs.ROW_TYPE = 'D' AND bs.ORDER_NBR = BS.ORDER_NBR AND bs.LINE_NBR = BS.LINE_NBR ORDER BY bs.SC_DESC DESC ),
				( SELECT TOP 1 bs.ORDER_DATE FROM #brdcast_selection bs 
				   WHERE bs.ROW_TYPE = 'D' AND bs.ORDER_NBR = BS.ORDER_NBR AND bs.LINE_NBR = BS.LINE_NBR ORDER BY bs.ORDER_DATE DESC ),
				( SELECT TOP 1 bs.ORDER_PROC_CTL FROM #brdcast_selection bs 
				   WHERE bs.ROW_TYPE = 'D' AND bs.ORDER_NBR = BS.ORDER_NBR AND bs.LINE_NBR = BS.LINE_NBR ORDER BY bs.ORDER_PROC_CTL DESC ),
				( SELECT TOP 1 bs.BILLING_USER FROM #brdcast_selection bs
				   WHERE bs.ROW_TYPE = 'D' AND bs.ORDER_NBR = BS.ORDER_NBR AND bs.LINE_NBR = BS.LINE_NBR ORDER BY bs.BILLING_USER DESC ),  
				( SELECT TOP 1 bs.BILL_TYPE FROM #brdcast_selection bs 
				   WHERE bs.ROW_TYPE = 'D' AND bs.ORDER_NBR = BS.ORDER_NBR AND bs.LINE_NBR = BS.LINE_NBR ORDER BY bs.BILL_TYPE DESC ),
				( SELECT TOP 1 bs.CLOSE_DATE FROM #brdcast_selection bs 
				   WHERE bs.ROW_TYPE = 'D' AND bs.ORDER_NBR = BS.ORDER_NBR AND bs.LINE_NBR = BS.LINE_NBR ORDER BY bs.CLOSE_DATE DESC ),										
				( SELECT TOP 1 bs.NET_CHARGES FROM #brdcast_selection bs 
				   WHERE bs.ROW_TYPE = 'D' AND bs.ORDER_NBR = BS.ORDER_NBR AND bs.LINE_NBR = BS.LINE_NBR ORDER BY bs.NET_CHARGES DESC ),
	        COALESCE( SUM( BS.NET_AMT ), 0.00 ), COALESCE( SUM( BS.COMM_AMT ), 0.00 ), COALESCE( SUM( BS.REBATE_AMT ), 0.00 ), 
	        COALESCE( SUM( BS.DISCOUNT_AMT ), 0.00 ), COALESCE( SUM( BS.VENDOR_TAX ), 0.00 ), 
	        COALESCE( SUM( BS.RESALE_TAX ), 0.00 ), COALESCE( SUM( BS.BILLABLE_AMT ), 0.00 ), COALESCE( SUM( BS.BILLED_AMT ), 0.00 ),
	        COALESCE( SUM( BS.UNBILLED_AMT ), 0.00 ), COALESCE( SUM( BS.AP_POSTED_AMT ), 0.00 )
	   FROM #brdcast_selection BS
	  WHERE BS.ROW_TYPE = 'D'
   GROUP BY BS.CL_CODE, BS.DIV_CODE, BS.PRD_CODE, BS.ORDER_NBR, BS.LINE_NBR, BS.MEDIA_FROM, BS.BILL_STATUS, BS.SETUP_COMPLETE 
	 HAVING ( MAX( COALESCE( BS.UNBILLED_AMT, 0.00 )) <> 0.00 OR MIN( COALESCE( BS.UNBILLED_AMT, 0.00 )) <> 0.00 OR 
			( @incl_zero_spots = 1 AND ( MAX( COALESCE( BS.SPOTS, 0 )) <> 0 OR MIN( COALESCE( BS.SPOTS, 0 )) <> 0 )))

 SELECT '', bs.ROW_TYPE, bs.CL_CODE, bs.DIV_CODE, bs.PRD_CODE, bs.ORDER_NBR, bs.LINE_NBR, bs.REV_NBR, 
		bs.OFFICE_CODE, bs.CMP_IDENTIFIER, bs.CMP_NAME, bs.MEDIA_TYPE, bs.SC_DESC, bs.MARKET_CODE, 
		bs.VN_CODE, bs.VN_NAME, bs.LINK_ID, bs.CLIENT_PO, bs.BUYER, bs.MAX_REV, bs.ORDER_DESC, bs.MEDIA_FROM, 
		bs.ORDER_DATE, bs.INSERTION_DATE, bs.BRDCAST_MONTH, bs.CLOSE_DATE, bs.DATE_TO_BILL, bs.BILLING_USER, bs.NET_AMT, 
		bs.COMM_AMT, bs.REBATE_AMT, bs.ADDTL_CHARGES, bs.DISCOUNT_AMT, bs.NET_CHARGES, bs.VENDOR_TAX, bs.RESALE_TAX, 
		bs.BILLABLE_AMT, bs.BILLED_AMT, bs.UNBILLED_AMT, bs.AP_POSTED_AMT, bs.BILL_STATUS, bs.SETUP_COMPLETE, 
		bs.BILL_TYPE, bs.ORDER_PROC_CTL, CAST( NULL AS smallint ), '', CAST( NULL AS smallint ), CAST( NULL AS smallint )
   FROM #brdcast_selection bs	
  WHERE bs.ROW_TYPE = 'L' 

IF ( @@ROWCOUNT > 0 )
	SELECT @ret_val = 0
ELSE	
	SELECT @ret_val = -1
	
DROP TABLE #brdcast_selection
