CREATE PROC advsp_1099_report_all_vendors_summary @start_date smalldatetime, @end_date smalldatetime

AS

SELECT	[VendorPayToCode] = C.PAY_TO_CODE,
		[VendorName] = V.VN_NAME,
		[VendorTaxID] = V.VN_TAX_ID,
		[TotalAmountPaid] = SUM(P.AP_CHK_AMT),
		[Is1099] = CAST(COALESCE(H.FLAG_1099,0) AS bit),
		[IsActive] = CAST(COALESCE(V.VN_ACTIVE_FLAG,0) AS bit),
		[APAccount] = H.GLACODE + ' - ' + G.GLADESC,
		[BankCode] = P.BK_CODE,
		[Vendor1099Category] = COALESCE(V.VN_1099_INC_TYPE,0),
		[VendorCode] = V.VN_CODE 
FROM dbo.AP_PMT_HIST P
	INNER JOIN dbo.CHECK_REGISTER C ON P.BK_CODE = C.BK_CODE AND P.AP_CHK_NBR = C.CHECK_NBR AND (C.VOID_FLAG IS NULL OR C.VOID_FLAG = 0)
	INNER JOIN dbo.VENDOR V ON C.PAY_TO_CODE = V.VN_CODE 
	INNER JOIN dbo.AP_HEADER H ON P.AP_ID = H.AP_ID
	INNER JOIN dbo.GLACCOUNT G ON H.GLACODE = G.GLACODE 
WHERE	P.AP_CHK_DATE between @start_date AND @end_date
AND (H.DELETE_FLAG IS NULL OR H.DELETE_FLAG = 0)
AND (H.MODIFY_FLAG IS NULL OR H.MODIFY_FLAG = 0)
GROUP BY C.PAY_TO_CODE, V.VN_NAME, V.VN_TAX_ID, H.FLAG_1099, V.VN_ACTIVE_FLAG, H.GLACODE + ' - ' + G.GLADESC, P.BK_CODE, COALESCE(V.VN_1099_INC_TYPE,0), V.VN_CODE
GO
