CREATE PROCEDURE [dbo].[advsp_exp_rpt_load_dtl_rpt]
	@INV_NBR INT
AS
BEGIN

	SELECT 
		[InvoiceNumber] = EXPENSE_DETAIL.INV_NBR,
		[LineNumber] = EXPENSE_DETAIL.LINE_NBR,
		[ItemDate] = EXPENSE_DETAIL.ITEM_DATE,
		[Description] = EXPENSE_DETAIL.ITEM_DESC,
		[ClientCode] = EXPENSE_DETAIL.CL_CODE,
		[ClientName] = CLIENT.CL_NAME,
		[DivisionCode] = EXPENSE_DETAIL.DIV_CODE,
		[DivisionName] = DIVISION.DIV_NAME,
		[ProductCode] = EXPENSE_DETAIL.PRD_CODE,
		[ProductName] = PRODUCT.PRD_DESCRIPTION,
		[JobNumber] = EXPENSE_DETAIL.JOB_NBR,
		[JobDescription] = JOB_LOG.JOB_DESC,
		[JobComponentNumber] = EXPENSE_DETAIL.JOB_COMP_NBR,
		[JobComponentDescription] = JOB_COMPONENT.JOB_COMP_DESC,
		[FunctionCode] = EXPENSE_DETAIL.FNC_CODE,
		[FunctionDescription] = FUNCTIONS.FNC_DESCRIPTION,
		[Quantity] = EXPENSE_DETAIL.QTY,
		[Rate] = EXPENSE_DETAIL.RATE,
		[Amount] = EXPENSE_DETAIL.AMOUNT,
		[CreditCardFlag] = EXPENSE_DETAIL.CC_FLAG,
		[PaymentType] = EXPENSE_DETAIL.PAYMENT_TYPE,
		[NonBillable] = CONVERT(SMALLINT, CASE 
												WHEN ISNULL(EXPENSE_DETAIL.JOB_NBR, 0) > 0 AND ISNULL(EXPENSE_DETAIL.JOB_COMP_NBR, 0) > 0 THEN 
													(SELECT 
														BILL_RATE.NOBILL_FLAG 
													 FROM 
														dbo.advtf_get_billing_rate(EXPENSE_HEADER.EMP_CODE, EXPENSE_DETAIL.ITEM_DATE, EXPENSE_DETAIL.FNC_CODE, 
																				   EXPENSE_DETAIL.CL_CODE, EXPENSE_DETAIL.DIV_CODE, EXPENSE_DETAIL.PRD_CODE, 
																				   JOB_LOG.SC_CODE, FUNCTIONS.FNC_TYPE, EXPENSE_DETAIL.JOB_NBR, EXPENSE_DETAIL.JOB_COMP_NBR, NULL) BILL_RATE)
												ELSE 1
											END)
	FROM
		dbo.EXPENSE_DETAIL 
	INNER JOIN
		dbo.EXPENSE_HEADER ON EXPENSE_DETAIL.INV_NBR = EXPENSE_HEADER.INV_NBR
	LEFT OUTER JOIN
		dbo.CLIENT ON EXPENSE_DETAIL.CL_CODE = CLIENT.CL_CODE
	LEFT OUTER JOIN
		dbo.DIVISION ON EXPENSE_DETAIL.CL_CODE = DIVISION.CL_CODE AND
						EXPENSE_DETAIL.DIV_CODE = DIVISION.DIV_CODE
	LEFT OUTER JOIN
		dbo.PRODUCT ON EXPENSE_DETAIL.CL_CODE = PRODUCT.CL_CODE AND
					   EXPENSE_DETAIL.DIV_CODE = PRODUCT.DIV_CODE AND
					   EXPENSE_DETAIL.DIV_CODE = PRODUCT.PRD_CODE
	LEFT OUTER JOIN
		dbo.JOB_LOG ON EXPENSE_DETAIL.JOB_NBR = JOB_LOG.JOB_NUMBER
	LEFT OUTER JOIN
		dbo.JOB_COMPONENT ON EXPENSE_DETAIL.JOB_NBR = JOB_COMPONENT.JOB_NUMBER AND
							 EXPENSE_DETAIL.JOB_COMP_NBR = JOB_COMPONENT.JOB_COMPONENT_NBR
	LEFT OUTER JOIN
		dbo.FUNCTIONS ON EXPENSE_DETAIL.FNC_CODE = FUNCTIONS.FNC_CODE
	WHERE
		EXPENSE_DETAIL.INV_NBR = @INV_NBR AND
		EXPENSE_DETAIL.LINE_NBR > 0 -- LINE_NBR = 0 = System Generated
		
END