if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[proc_WV_PO_GetByJobComp]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [dbo].[proc_WV_PO_GetByJobComp]
GO

	CREATE PROCEDURE [dbo].[proc_WV_PO_GetByJobComp]
		@JOB_NUMBER INT,
		@JOB_COMPONENT_NBR SMALLINT
	AS	
	SELECT A.PO_NUMBER, LINE_NUMBER, B.VN_CODE, VN_NAME, A.JOB_NUMBER, JOB_COMPONENT_NBR, PO_EXT_AMOUNT, ISNULL(A.PO_COMPLETE,0) AS PO_COMPLETE,B.PO_APPROVAL_FLAG,
	CASE 
		WHEN ((B.PO_APPROVAL_FLAG = 1) OR (B.PO_APPROVAL_FLAG = 3)) 
		AND ((B.EXCEED = 1) OR (B.EXCEED = 0) OR (B.EXCEED IS NULL)) 
		AND ((B.PO_PRINTED = 0) OR (B.PO_PRINTED IS NULL)) 
		AND (NOT(B.PO_APPR_RULE_CODE IS NULL)) THEN '(Pending)' 
		WHEN (B.PO_APPROVAL_FLAG = 2) THEN CAST(A.PO_NUMBER AS VARCHAR(50)) 
		WHEN (NOT(B.PO_APPR_RULE_CODE IS NULL))
		AND ((B.EXCEED = 1) OR (B.EXCEED = 0) OR (B.EXCEED IS NULL))
		AND ((B.PO_PRINTED = 0) OR (B.PO_PRINTED IS NULL)) THEN '(Incomplete)'		
		ELSE CAST(A.PO_NUMBER AS VARCHAR(50)) 
	END AS PO_NUMBER_DISPLAY, PO_DESCRIPTION 
	FROM 
		PURCHASE_ORDER_DET A, PURCHASE_ORDER B, VENDOR C 
	WHERE 
		A.PO_NUMBER = B.PO_NUMBER AND B.VN_CODE = C.VN_CODE 
		AND JOB_NUMBER = @JOB_NUMBER
		AND JOB_COMPONENT_NBR = @JOB_COMPONENT_NBR
		AND ( B.VOID_FLAG IS NULL OR B.VOID_FLAG = 0 )
		AND (B.PO_APPROVAL_FLAG <> 3 OR B.PO_APPROVAL_FLAG IS NULL)
	ORDER BY 
		A.PO_NUMBER, LINE_NUMBER; 
	
