

CREATE PROCEDURE [dbo].[proc_JOB_TRAFFIC_DETUpdate]
(
	@JOB_NUMBER int,
	@JOB_COMPONENT_NBR smallint,
	@SEQ_NBR smallint,
	@FNC_CODE varchar(10) = NULL,
	@FNC_EST varchar(6) = NULL,
	@TASK_DESCRIPTION varchar(40) = NULL,
	@TASK_START_DATE smalldatetime = NULL,
	@JOB_DUE_DATE smalldatetime = NULL,
	@JOB_REVISED_DATE smalldatetime = NULL,
	@DUE_DATE_LOCK smallint = NULL,
	@JOB_COMPLETED_DATE smalldatetime = NULL,
	@JOB_ORDER smallint = NULL,
	@JOB_DAYS smallint = NULL,
	@PARENT_TASK varchar(10) = NULL,
	@FNC_COMMENTS text = NULL,
	@DUE_DATE_COMMENTS text = NULL,
	@REV_DATE_COMMENTS text = NULL,
	@JOB_HRS decimal(8,2) = NULL,
	@DUE_TIME varchar(10) = NULL,
	@REVISED_DUE_TIME varchar(10) = NULL,
	@TASK_STATUS varchar(1) = NULL,
	@MILESTONE smallint = NULL,
	@TRAFFIC_PHASE_ID int = NULL,
	@ROWID int,
	@TRF_ROLE varchar(6) = NULL,
	--NEED TO CLEAN:
	@TEMP_SEQ SMALLINT = NULL,
    @COMPLETED_COMMENTS TEXT = NULL,
    
	@TEMP_COMP_DATE smalldatetime = NULL output,
	@HOURS_ASSIGNED decimal(15,2) = NULL output,
	@EMP_CODE varchar(6) = NULL output
)
AS
BEGIN

	SET NOCOUNT OFF
	DECLARE @Err int

	UPDATE [JOB_TRAFFIC_DET]
	SET
		[FNC_CODE] = @FNC_CODE,
		[FNC_EST] = @FNC_EST,
		[TASK_DESCRIPTION] = @TASK_DESCRIPTION,
		[TASK_START_DATE] = @TASK_START_DATE,
		[JOB_DUE_DATE] = @JOB_DUE_DATE,
		[JOB_REVISED_DATE] = @JOB_REVISED_DATE,
		[DUE_DATE_LOCK] = @DUE_DATE_LOCK,
		[JOB_COMPLETED_DATE] = @JOB_COMPLETED_DATE,
		[JOB_ORDER] = @JOB_ORDER,
		[JOB_DAYS] = @JOB_DAYS,
		[PARENT_TASK] = @PARENT_TASK,
		[FNC_COMMENTS] = @FNC_COMMENTS,
		[DUE_DATE_COMMENTS] = @DUE_DATE_COMMENTS,
		[REV_DATE_COMMENTS] = @REV_DATE_COMMENTS,
		[JOB_HRS] = @JOB_HRS,
		[DUE_TIME] = @DUE_TIME,
		[REVISED_DUE_TIME] = @REVISED_DUE_TIME,
		[TASK_STATUS] = @TASK_STATUS,
		[MILESTONE] = @MILESTONE,
		[TRAFFIC_PHASE_ID] = @TRAFFIC_PHASE_ID,
		[TRF_ROLE] = @TRF_ROLE
	WHERE
		[JOB_COMPONENT_NBR] = @JOB_COMPONENT_NBR
	AND	[JOB_NUMBER] = @JOB_NUMBER
	AND	[SEQ_NBR] = @SEQ_NBR


	SET @Err = @@Error

    SELECT @TEMP_COMP_DATE = [TEMP_COMP_DATE], @HOURS_ASSIGNED = [HOURS_ASSIGNED], @EMP_CODE = [EMP_CODE]
      FROM [JOB_TRAFFIC_DET]
     WHERE [JOB_NUMBER] = @JOB_NUMBER AND [JOB_COMPONENT_NBR] = @JOB_COMPONENT_NBR AND [SEQ_NBR] = @SEQ_NBR


	RETURN @Err
END

