





CREATE PROCEDURE [dbo].[proc_WV_PO_GetPOApprDataByPO] 
@PONum int
AS

SELECT     PO_APPROVAL.PO_NUMBER, PO_APPROVAL.PO_APPR_RULE_CODE, PO_APPROVAL.SEQ_NBR, 
                      PO_APPROVAL.PO_APPR_RULE_ID, PO_APPR_RULE_EMP.EMP_CODE, PO_APPROVAL.PO_APPROVAL_FLAG, 
                      EMPLOYEE.EMP_FNAME + CASE WHEN EMPLOYEE.EMP_MI IS NULL THEN ' ' ELSE ' ' + EMPLOYEE.EMP_MI + '. ' END +  EMPLOYEE.EMP_LNAME AS EMPLOYEE_NAME
FROM         PO_APPROVAL INNER JOIN
                      PO_APPR_RULE_EMP ON PO_APPROVAL.PO_APPR_RULE_ID = PO_APPR_RULE_EMP.PO_APPR_RULE_ID LEFT OUTER JOIN
                      EMPLOYEE ON PO_APPR_RULE_EMP.EMP_CODE = EMPLOYEE.EMP_CODE
WHERE     (PO_APPROVAL.PO_NUMBER = @PONum)
























