

CREATE PROCEDURE [dbo].[proc_JOB_TRAFFIC_DETLoadByPrimaryKey]
(
	@JOB_COMPONENT_NBR smallint,
	@JOB_NUMBER int,
	@SEQ_NBR smallint
)
AS
BEGIN
	SET NOCOUNT ON
	DECLARE @Err int

	SELECT
		[JOB_NUMBER],
		[JOB_COMPONENT_NBR],
		[SEQ_NBR],
		[FNC_CODE],
		[FNC_EST],
		[TASK_DESCRIPTION],
		[TASK_START_DATE],
		[JOB_DUE_DATE],
		[JOB_REVISED_DATE],
		[DUE_DATE_LOCK],
		[JOB_COMPLETED_DATE],
		[JOB_ORDER],
		[JOB_DAYS],
		[PARENT_TASK],
		[FNC_COMMENTS],
		[DUE_DATE_COMMENTS],
		[REV_DATE_COMMENTS],
		[JOB_HRS],
		[DUE_TIME],
		[REVISED_DUE_TIME],
		[TASK_STATUS],
		[MILESTONE],
		[TRAFFIC_PHASE_ID],
		[ROWID],
		[TRF_ROLE],
		[TEMP_COMP_DATE],
		[HOURS_ASSIGNED],
		[EMP_CODE]
	FROM [JOB_TRAFFIC_DET]
	WHERE
		([JOB_COMPONENT_NBR] = @JOB_COMPONENT_NBR) AND
		([JOB_NUMBER] = @JOB_NUMBER) AND
		([SEQ_NBR] = @SEQ_NBR)

	SET @Err = @@Error

	RETURN @Err
END

