





CREATE PROCEDURE [dbo].[usp_wv_add_alert_bodyHTML]

@ALERT_TYPE_ID Int,
@ALERT_CAT_ID Int, 
@SUBJECT Varchar(254), 
@BODY text, 
@GENERATED datetime, 
@PRIORITY Int, 
@OFFICE_CODE varchar(4),
@CL_CODE Varchar(6), 
@DIV_CODE Varchar(6), 
@PRD_CODE Varchar(6), 
@CMP_ID Int, 
@JOB_NUMBER Int,
@JOB_COMPONENT_NBR Int, 
@EMP_CODE Varchar(6), 
@ALERT_LEVEL Varchar(50),
@ALERT_USER varchar(100),
@BODY_HTML text

AS

--Set NOCOUNT ON
declare @CMP_CODE as Varchar(6)
declare @AlertID as int

SELECT @CMP_CODE = CMP_CODE FROM CAMPAIGN WHERE CMP_IDENTIFIER = @CMP_ID
SELECT @AlertID = (max(ALERT_ID) + 1) from ALERT

INSERT INTO ALERT (ALERT_ID, ALERT_TYPE_ID, ALERT_CAT_ID, SUBJECT, BODY, GENERATED, PRIORITY, OFFICE_CODE, CL_CODE, DIV_CODE, PRD_CODE, CMP_CODE, JOB_NUMBER,
JOB_COMPONENT_NBR, EMP_CODE, ALERT_LEVEL, ALERT_USER, BODY_HTML, CMP_IDENTIFIER)
Values(@AlertID, @ALERT_TYPE_ID, @ALERT_CAT_ID, @SUBJECT, @BODY, @GENERATED, @PRIORITY, @OFFICE_CODE, @CL_CODE, @DIV_CODE, @PRD_CODE, @CMP_CODE, @JOB_NUMBER,
@JOB_COMPONENT_NBR, @EMP_CODE, @ALERT_LEVEL, @ALERT_USER, @BODY_HTML, @CMP_ID)


select ALERTID = @AlertID

