if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[usp_wv_Client_GetContact]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [dbo].[usp_wv_Client_GetContact]
GO

CREATE PROCEDURE [dbo].[usp_wv_Client_GetContact]
(
	@CDP_ID smallint
)
AS
BEGIN
	SET NOCOUNT OFF
	
	DECLARE 
	@ERR INT

	SELECT     CONT_CODE, ISNULL(CL_CODE, '') AS CL_CODE, ISNULL(EMAIL_ADDRESS, '') AS EMAIL_ADDRESS, ISNULL(CONT_FNAME, '') AS CONT_FNAME, ISNULL(CONT_LNAME, '') AS CONT_LNAME, ISNULL(CONT_MI, '') AS CONT_MI,
					  ISNULL(CONT_TITLE, '') AS CONT_TITLE, ISNULL(CONT_ADDRESS1, '') AS CONT_ADDRESS1, ISNULL(CONT_ADDRESS2, '') AS CONT_ADDRESS2, ISNULL(CONT_CITY, '') AS CONT_CITY, 
                      ISNULL(CONT_COUNTY, '') AS CONT_COUNTY, ISNULL(CONT_STATE, '') AS CONT_STATE, ISNULL(CONT_COUNTRY, '') AS CONT_COUNTRY, ISNULL(CONT_ZIP, '') AS CONT_ZIP,
					  ISNULL(CONT_TELEPHONE, '') AS CONT_TELEPHONE, ISNULL(CONT_EXTENTION, '') AS CONT_EXTENTION, ISNULL(CONT_FAX, '') AS CONT_FAX, ISNULL(CONT_FAX_EXTENTION, '') AS CONT_FAX_EXTENTION, 
					  ISNULL(SCHEDULE_USER, 0) AS SCHEDULE_USER, ISNULL(CP_USER, 0) AS CP_USER, ISNULL(CP_ALERTS, 0) AS CP_ALERTS, ISNULL(EMAIL_RCPT, 0) AS EMAIL_RCPT, ISNULL(INACTIVE_FLAG, 0) AS INACTIVE_FLAG,
					  ISNULL(CELL_PHONE, '') AS CELL_PHONE, ISNULL(CONT_COMMENT,'') AS CONT_COMMENT, ISNULL(CONTACT_TYPE_ID,0) AS CONTACT_TYPE_ID
	FROM         CDP_CONTACT_HDR
	WHERE CDP_CONTACT_ID = @CDP_ID
	
	SET @ERR = @@Error

	--RETURN @ERR
END




