

CREATE PROCEDURE [dbo].[usp_wv_Dashboard_GetEmpData]
(
	@DeptCode varchar(4)
)
AS
if @DeptCode <> '' AND @DeptCode <> 'All'
Begin
	SELECT DASH_DATA_EMP_TIME.EMP_CODE, isnull(EMP_FNAME,'') + ' ' + isnull(EMP_MI,'') + case when EMP_MI is not null then '. ' else '' end +  isnull(EMP_LNAME,'') AS EMP_DESC,
		 SUM(DASH_DATA_EMP_TIME.DIRECT_HOURS) AS DIRECT, SUM(DASH_DATA_EMP_TIME.NON_PROD_HOURS) AS NONDIRECT
	FROM DASH_DATA_EMP_TIME INNER JOIN
				 EMPLOYEE ON DASH_DATA_EMP_TIME.EMP_CODE = EMPLOYEE.EMP_CODE INNER JOIN charlist_to_table(@DeptCode, DEFAULT) d ON DASH_DATA_EMP_TIME.DP_TM_CODE = d.vstr collate database_default
	--WHERE DASH_DATA_EMP_TIME.DP_TM_CODE = @DeptCode
	GROUP BY DASH_DATA_EMP_TIME.EMP_CODE, EMP_FNAME, EMP_MI, EMP_LNAME
End
Else
Begin
	SELECT DASH_DATA_EMP_TIME.EMP_CODE, isnull(EMP_FNAME,'') + ' ' + isnull(EMP_MI,'') + case when EMP_MI is not null then '. ' else '' end +  isnull(EMP_LNAME,'') AS EMP_DESC,
			 SUM(DASH_DATA_EMP_TIME.DIRECT_HOURS) AS DIRECT, SUM(DASH_DATA_EMP_TIME.NON_PROD_HOURS) AS NONDIRECT
	FROM DASH_DATA_EMP_TIME INNER JOIN
				 EMPLOYEE ON DASH_DATA_EMP_TIME.EMP_CODE = EMPLOYEE.EMP_CODE
	GROUP BY DASH_DATA_EMP_TIME.EMP_CODE, EMP_FNAME, EMP_MI, EMP_LNAME
End




