

CREATE PROCEDURE [dbo].[usp_wv_dd_GetAllJobs_Filtered_Closed] 
@UserID VarChar(100),
@OfficeCode VarChar(4),
@Closed Bit
AS
Declare @Rescrictions Int
Declare @SqlStmt nvarchar(4000)

Set NoCount On

Select @Rescrictions = Count(*) 
FROM SEC_CLIENT
WHERE UPPER(USER_ID) = UPPER(@UserID)

If @Rescrictions > 0

	If @Closed = 0
	SELECT   JOB_LOG.JOB_NUMBER AS Code, STR(JOB_LOG.JOB_NUMBER) + ' - ' + isnull(JOB_LOG.JOB_DESC, '') AS Description
	FROM     JOB_LOG 
				INNER JOIN JOB_COMPONENT ON JOB_LOG.JOB_NUMBER = JOB_COMPONENT.JOB_NUMBER INNER JOIN
	                 SEC_CLIENT ON JOB_LOG.CL_CODE = SEC_CLIENT.CL_CODE AND JOB_LOG.DIV_CODE = SEC_CLIENT.DIV_CODE AND 
	                 JOB_LOG.PRD_CODE = SEC_CLIENT.PRD_CODE
				INNER JOIN JOB_TRAFFIC 
	 				ON JOB_COMPONENT.JOB_NUMBER = JOB_TRAFFIC.JOB_NUMBER 
					AND JOB_COMPONENT.JOB_COMPONENT_NBR = JOB_TRAFFIC.JOB_COMPONENT_NBR
	WHERE  UPPER(SEC_CLIENT.USER_ID) =  UPPER(@UserID) AND (SEC_CLIENT.TIME_ENTRY = 0 OR SEC_CLIENT.TIME_ENTRY IS NULL)
	AND JOB_LOG.OFFICE_CODE =  @OfficeCode 
	And JOB_TRAFFIC.COMPLETED_DATE IS NULL 
	GROUP BY JOB_LOG.JOB_NUMBER, JOB_LOG.JOB_DESC 
	ORDER BY JOB_LOG.JOB_NUMBER DESC
	Else
	SELECT   JOB_LOG.JOB_NUMBER AS Code, STR(JOB_LOG.JOB_NUMBER) + ' - ' + isnull(JOB_LOG.JOB_DESC, '') AS Description
	FROM     JOB_LOG INNER JOIN
	                 JOB_COMPONENT ON JOB_LOG.JOB_NUMBER = JOB_COMPONENT.JOB_NUMBER INNER JOIN
	                 SEC_CLIENT ON JOB_LOG.CL_CODE = SEC_CLIENT.CL_CODE AND JOB_LOG.DIV_CODE = SEC_CLIENT.DIV_CODE AND 
	                 JOB_LOG.PRD_CODE = SEC_CLIENT.PRD_CODE
	WHERE  UPPER(SEC_CLIENT.USER_ID) =  UPPER(@UserID) AND (SEC_CLIENT.TIME_ENTRY = 0 OR SEC_CLIENT.TIME_ENTRY IS NULL) 
	AND JOB_LOG.OFFICE_CODE =  @OfficeCode
	GROUP BY JOB_LOG.JOB_NUMBER, JOB_LOG.JOB_DESC 
	ORDER BY JOB_LOG.JOB_NUMBER DESC


ELSE

	If @Closed = 0
	SELECT  JOB_LOG.JOB_NUMBER as Code, str(JOB_LOG.JOB_NUMBER) + ' - ' + isnull(JOB_LOG.JOB_DESC, '') as Description
	FROM    JOB_LOG 
			INNER JOIN
	               JOB_COMPONENT ON JOB_LOG.JOB_NUMBER = JOB_COMPONENT.JOB_NUMBER 
	        INNER JOIN JOB_TRAFFIC 
	 			ON JOB_COMPONENT.JOB_NUMBER = JOB_TRAFFIC.JOB_NUMBER 
				AND JOB_COMPONENT.JOB_COMPONENT_NBR = JOB_TRAFFIC.JOB_COMPONENT_NBR
	WHERE JOB_LOG.OFFICE_CODE =  @OfficeCode 
	And JOB_TRAFFIC.COMPLETED_DATE IS NULL
	GROUP BY JOB_LOG.JOB_NUMBER, JOB_LOG.JOB_DESC 
	ORDER BY JOB_LOG.JOB_NUMBER DESC
	Else
	SELECT  JOB_LOG.JOB_NUMBER as Code, str(JOB_LOG.JOB_NUMBER) + ' - ' + isnull(JOB_LOG.JOB_DESC, '') as Description
	FROM    JOB_LOG 
			INNER JOIN
	               JOB_COMPONENT ON JOB_LOG.JOB_NUMBER = JOB_COMPONENT.JOB_NUMBER 
	WHERE JOB_LOG.OFFICE_CODE =  @OfficeCode
	GROUP BY JOB_LOG.JOB_NUMBER, JOB_LOG.JOB_DESC 
	ORDER BY JOB_LOG.JOB_NUMBER DESC 



