if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[usp_wv_ALERT_IsCcRecipient]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [dbo].[usp_wv_ALERT_IsCcRecipient]
GO

CREATE PROCEDURE [dbo].[usp_wv_ALERT_IsCcRecipient] /*WITH ENCRYPTION*/
@ALERT_ID INT,
@EMP_CODE VARCHAR(6)
AS
/*=========== QUERY ===========*/
	DECLARE
		@IS_CC BIT

	SET @IS_CC = 0;

	IF EXISTS(SELECT 1 FROM ALERT WITH(NOLOCK) WHERE ALERT_ID = @ALERT_ID AND NOT ALERT.ALRT_NOTIFY_HDR_ID IS NULL AND NOT ALERT.ALERT_STATE_ID IS NULL) --IS ASSIGNMENT
	BEGIN

		IF EXISTS(
			SELECT 1 FROM ALERT_RCPT WITH(NOLOCK) 
			WHERE ALERT_RCPT.EMP_CODE = @EMP_CODE 
			AND ALERT_RCPT.ALERT_ID = @ALERT_ID 
			AND (ALERT_RCPT.CURRENT_NOTIFY = 0 OR ALERT_RCPT.CURRENT_NOTIFY IS NULL)
		)
		BEGIN
			SET @IS_CC = 1;
		END
		IF @IS_CC = 0
		BEGIN
			IF EXISTS(
				SELECT 1 FROM ALERT_RCPT_DISMISSED WITH(NOLOCK) 
				WHERE ALERT_RCPT_DISMISSED.EMP_CODE = @EMP_CODE 
				AND ALERT_RCPT_DISMISSED.ALERT_ID = @ALERT_ID 
				AND (ALERT_RCPT_DISMISSED.CURRENT_NOTIFY = 0 OR ALERT_RCPT_DISMISSED.CURRENT_NOTIFY IS NULL)
			)
			BEGIN
				SET @IS_CC = 1;
			END
		END


	END

	SELECT @IS_CC AS IS_CC_RECIPIENT;
/*=========== QUERY ===========*/
GO
SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO