
CREATE PROCEDURE [dbo].[usp_wv_available_media] 
@Type as Varchar(3),
@Client as Varchar(6),
@Division as Varchar(6),
@Product as Varchar(6),
@USER_CODE AS VarChar(100)
AS

DECLARE @OfficeRestrictions AS INTEGER	
DECLARE @EMP_CODE AS varchar(6),@EmpRestrictions SMALLINT

SELECT @EmpRestrictions = ISNULL(COUNT(1),0) FROM SEC_EMP WHERE UPPER(USER_ID) = UPPER(@USER_CODE)

SELECT @EMP_CODE = EMP_CODE FROM [dbo].[SEC_USER] WHERE UPPER([USER_CODE]) = UPPER(@USER_CODE)
SELECT @OfficeRestrictions = COUNT(*) FROM EMP_OFFICE WHERE EMP_CODE = @EMP_CODE

DECLARE @sql AS VARCHAR(MAX)

If @Type = 'INT'
	set @sql = 'SELECT CAST(ORDER_NBR AS VARCHAR(10)) AS Code, 
		SUBSTRING(''000000'', 1, 6 - LEN(ORDER_NBR)) + CAST(ORDER_NBR AS VARCHAR(10)) + ''-'' + ORDER_DESC + '' / '' + VENDOR.VN_CODE + ''-'' + VENDOR.VN_NAME AS Description
		,ORDER_NBR AS SORTFLD
		FROM INTERNET_HEADER XX
		INNER JOIN VENDOR ON VENDOR.VN_CODE = XX.VN_CODE
		WHERE XX.CMP_IDENTIFIER IS NULL AND XX.ORD_PROCESS_CONTRL <> 6 AND XX.ORD_PROCESS_CONTRL IS NOT NULL AND (XX.RECONCILE_FLAG IS NULL OR XX.RECONCILE_FLAG = 0) 
		AND XX.CL_CODE = ''' + @Client + ''''

If @Type = 'MAG'
	set @sql = 'SELECT CAST(ORDER_NBR AS VARCHAR(10)) AS Code, 
		SUBSTRING(''000000'', 1, 6 - LEN(ORDER_NBR)) + CAST(ORDER_NBR AS VARCHAR(10))  + ''-'' + ORDER_DESC + '' / '' + VENDOR.VN_CODE + ''-'' + VENDOR.VN_NAME AS Description
		,ORDER_NBR AS SORTFLD
		FROM MAGAZINE_HEADER XX
		INNER JOIN VENDOR ON VENDOR.VN_CODE = XX.VN_CODE
		WHERE XX.CMP_IDENTIFIER IS NULL AND XX.ORD_PROCESS_CONTRL <> 6  AND XX.ORD_PROCESS_CONTRL IS NOT NULL AND (XX.RECONCILE_FLAG IS NULL OR XX.RECONCILE_FLAG = 0) 
		AND XX.CL_CODE = ''' + @Client + ''''
		
If @Type = 'NEW'
	set @sql = 'SELECT CAST(ORDER_NBR AS VARCHAR(10)) AS Code, 
		SUBSTRING(''000000'', 1, 6 - LEN(ORDER_NBR)) + CAST(ORDER_NBR AS VARCHAR(10)) + ''-'' + ORDER_DESC + '' / '' + VENDOR.VN_CODE + ''-'' + VENDOR.VN_NAME AS Description
		,ORDER_NBR AS SORTFLD
		FROM NEWSPAPER_HEADER XX
		INNER JOIN VENDOR ON VENDOR.VN_CODE = XX.VN_CODE
		WHERE XX.CMP_IDENTIFIER IS NULL AND XX.ORD_PROCESS_CONTRL <> 6  AND XX.ORD_PROCESS_CONTRL IS NOT NULL AND (XX.RECONCILE_FLAG IS NULL OR XX.RECONCILE_FLAG = 0) 
		AND XX.CL_CODE = ''' + @Client + ''''
		
If @Type = 'OOH'
	set @sql = 'SELECT CAST(ORDER_NBR AS VARCHAR(10)) AS Code, 
		SUBSTRING(''000000'', 1, 6 - LEN(ORDER_NBR)) + CAST(ORDER_NBR AS VARCHAR(10)) + ''-'' + ORDER_DESC + '' / '' + VENDOR.VN_CODE + ''-'' + VENDOR.VN_NAME AS Description
		,ORDER_NBR AS SORTFLD
		FROM OUTDOOR_HEADER XX
		INNER JOIN VENDOR ON VENDOR.VN_CODE = XX.VN_CODE
		WHERE XX.CMP_IDENTIFIER IS NULL AND XX.ORD_PROCESS_CONTRL <> 6 AND XX.ORD_PROCESS_CONTRL IS NOT NULL AND (XX.RECONCILE_FLAG IS NULL OR XX.RECONCILE_FLAG = 0) 
		AND XX.CL_CODE = ''' + @Client + ''''
		
If @Type = 'RAD'
	set @sql = 'SELECT CAST(ORDER_NBR AS VARCHAR(10)) AS Code, 
		SUBSTRING(''000000'', 1, 6 - LEN(ORDER_NBR)) + CAST(ORDER_NBR AS VARCHAR(10)) + ''-'' + ORDER_DESC + '' / '' + VENDOR.VN_CODE + ''-'' + VENDOR.VN_NAME AS Description
		,ORDER_NBR AS SORTFLD
		FROM RADIO_HDR XX
		INNER JOIN VENDOR ON VENDOR.VN_CODE = XX.VN_CODE
		WHERE XX.CMP_IDENTIFIER IS NULL AND XX.ORD_PROCESS_CONTRL <> 6  AND XX.ORD_PROCESS_CONTRL IS NOT NULL AND (XX.RECONCILE_FLAG IS NULL OR XX.RECONCILE_FLAG = 0) 
		AND XX.CL_CODE = ''' + @Client + ''''
		
If @Type = 'TV'
	set @sql = 'SELECT CAST(ORDER_NBR AS VARCHAR(10)) AS Code, 
		SUBSTRING(''000000'', 1, 6 - LEN(ORDER_NBR)) + CAST(ORDER_NBR AS VARCHAR(10)) + ''-'' + ORDER_DESC + '' / '' + VENDOR.VN_CODE + ''-'' + VENDOR.VN_NAME AS Description
		,ORDER_NBR AS SORTFLD
		FROM TV_HDR XX
		INNER JOIN VENDOR ON VENDOR.VN_CODE = XX.VN_CODE
		WHERE XX.CMP_IDENTIFIER IS NULL AND XX.ORD_PROCESS_CONTRL <> 6  AND XX.ORD_PROCESS_CONTRL IS NOT NULL AND (XX.RECONCILE_FLAG IS NULL OR XX.RECONCILE_FLAG = 0) 
		AND XX.CL_CODE = ''' + @Client + ''''
		
If @Type = 'JOB'
Begin
	set @sql = 'SELECT CAST(JOB_NUMBER AS VARCHAR(10)) AS Code, 
		SUBSTRING(''000000'', 1, 6 - LEN(JOB_NUMBER)) + CAST(JOB_NUMBER AS VARCHAR(10)) + ''-'' + JOB_DESC AS Description
		,JOB_NUMBER AS SORTFLD
		FROM JOB_LOG XX'
		if @OfficeRestrictions > 0
		Begin
			set @sql = @sql + ' INNER JOIN EMP_OFFICE ON XX.OFFICE_CODE = EMP_OFFICE.OFFICE_CODE AND EMP_OFFICE.EMP_CODE = ''' + @EMP_CODE + ''''
		End
		set @sql = @sql + ' WHERE CMP_IDENTIFIER IS NULL AND COMP_OPEN = 1 
		AND CL_CODE = ''' + @Client + ''''
End

If 	@Division <> ''
	set @sql = @sql + ' AND XX.DIV_CODE = ''' + @Division + ''''
	
If 	@Product <> ''
	set @sql = @sql + ' AND XX.PRD_CODE = ''' + @Product + ''''
 
set @sql = @sql + ' ORDER BY SORTFLD'

EXEC(@sql)
--print @sql