IF EXISTS (SELECT * FROM sysobjects WHERE id = object_id(N'[usp_wv_BA_ALERTS_VIEW_LIST]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
    DROP PROCEDURE [dbo].[usp_wv_BA_ALERTS_VIEW_LIST]
GO
CREATE PROCEDURE [dbo].[usp_wv_BA_ALERTS_VIEW_LIST] 
@BA_BATCH_ID AS INT,
@OFFSET DECIMAL (9,3)
AS
/*=========== QUERY ===========*/
BEGIN

	SELECT     
		ALERT.ALERT_ID, 
		ALERT.ALERT_TYPE_ID, 
		ALERT.ALERT_CAT_ID, 
		ALERT.[SUBJECT], 
		ALERT.BA_BATCH_ID, 
		[GENERATED] =	CASE ISNULL(@OFFSET, 0)
								WHEN 0 THEN COALESCE(ALERT.LAST_UPDATED, ALERT.[GENERATED])
								ELSE ISNULL(DATEADD(mi, (CONVERT(INT, @OFFSET) * 60) + (@OFFSET - CONVERT(INT, @OFFSET)), ISNULL(ALERT.LAST_UPDATED, ALERT.[GENERATED])), ISNULL(ALERT.LAST_UPDATED, ALERT.[GENERATED]))
							END,
		ALERT.[PRIORITY], 
		ALERT_TYPE.ALERT_TYPE_DESC, 
		ALERT_CATEGORY.ALERT_DESC, 
		ALERT.EMP_CODE, 
		ISNULL(EMPLOYEE.EMP_FNAME+' ','') + ISNULL(EMPLOYEE.EMP_MI+'. ','') + ISNULL(EMPLOYEE.EMP_LNAME,'') AS EMP_FML_NAME
	FROM         
		ALERT WITH (NOLOCK) 
		INNER JOIN ALERT_TYPE WITH (NOLOCK) ON ALERT.ALERT_TYPE_ID = ALERT_TYPE.ALERT_TYPE_ID 
		INNER JOIN ALERT_CATEGORY WITH (NOLOCK) ON ALERT.ALERT_CAT_ID = ALERT_CATEGORY.ALERT_CAT_ID 
		LEFT OUTER JOIN EMPLOYEE WITH (NOLOCK) ON ALERT.EMP_CODE = EMPLOYEE.EMP_CODE
	WHERE     
		1 =	CASE
				WHEN @BA_BATCH_ID IS NOT NULL AND ALERT.BA_BATCH_ID = @BA_BATCH_ID THEN 1 -- SHOW FOR SPECIFIC BATCH
				WHEN @BA_BATCH_ID IS NULL AND ALERT.BA_BATCH_ID IS NOT NULL THEN 1 -- SHOW ONLY BATCH ALERTS, BUT SHOW ALL
				ELSE 0
			END
	ORDER BY 
		ALERT.[GENERATED] DESC;

END
/*=========== QUERY ===========*/

