





CREATE PROCEDURE [dbo].[usp_wv_calendar_ddMagazine]
@OrderNumber Int,
@LineNumber Int,
@RevNumber Int
AS

 --Magazine Media Data
    SELECT  'M' AS TYPE, 'A' AS EST_ACT, MH.OFFICE_CODE, MH.ORDER_NBR, MH.ORDER_DESC, MH.MEDIA_TYPE, MH.CL_CODE, MH.DIV_CODE, 
                      MH.PRD_CODE, MH.CMP_IDENTIFIER, MH.CMP_CODE, C.CMP_NAME, MH.VN_CODE, V.VN_NAME, MH.BUYER, MH.CLIENT_PO, MH.MARKET_CODE, 
                      M.MARKET_DESC, MH.ORDER_ACCEPTED, MD.LINE_NBR, MD.ACTIVE_REV, MD.START_DATE, MD.END_DATE, MD.CLOSE_DATE, 
                      MD.MATL_CLOSE_DATE, MD.EXT_CLOSE_DATE, MD.EXT_MATL_DATE, MD.SIZE, MD.AD_NUMBER, MD.HEADLINE, MD.MATERIAL, 
                      MD.EDITION_ISSUE, MD.SECTION, MD.JOB_NUMBER, MD.JOB_COMPONENT_NBR, MD.PRODUCTION_SIZE, MD.EST_NBR, MD.EST_LINE_NBR, 
                      MD.EST_REV_NBR, MD.LINE_TOTAL, 0 AS COST_PER, 0 AS IMPRESSIONS, MD.LINE_CANCELLED, CL.CL_NAME, D.DIV_NAME, 
                      P.PRD_DESCRIPTION, MH.ORDER_COMMENT, MH.HOUSE_COMMENT, MD.BILLING_AMT, MH.LINK_ID,  MC.INSTRUCTIONS, MC.ORDER_COPY, 
                      MC.MATL_NOTES, MC.POSITION_INFO, MC.CLOSE_INFO, 
                      MC.RATE_INFO, MC.MISC_INFO, MC.IN_HOUSE_CMTS, VR.VR_FNAME, VR.VR_LNAME, 
                      VR.VR_MI, VR.VR_CODE, VR2.VR_FNAME AS VR_FNAME2, VR2.VR_LNAME AS VR_LNAME2, 
                      VR2.VR_MI AS VR_MI2, VR2.VR_CODE AS VR_CODE2, JC.JOB_COMP_DESC, JL.JOB_DESC, MH.ORDER_DATE, MD.REV_NBR, SC.SC_DESCRIPTION, MD.MAT_COMP, AD.AD_NBR_DESC, MD.SIZE_CODE
	FROM   MAGAZINE_HEADER AS MH INNER JOIN
                      MAGAZINE_DETAIL AS MD ON MH.ORDER_NBR = MD.ORDER_NBR INNER JOIN
                      VENDOR AS V ON MH.VN_CODE = V.VN_CODE INNER JOIN
                      CLIENT AS CL ON MH.CL_CODE = CL.CL_CODE INNER JOIN
                      DIVISION AS D ON CL.CL_CODE = D.CL_CODE INNER JOIN
                      PRODUCT AS P ON MH.CL_CODE = P.CL_CODE AND MH.DIV_CODE = P.DIV_CODE AND 
                      MH.PRD_CODE = P.PRD_CODE AND D.CL_CODE = P.CL_CODE AND 
                      D.DIV_CODE = P.DIV_CODE INNER JOIN
                      MAGAZINE_COMMENTS AS MC ON MH.ORDER_NBR = MC.ORDER_NBR AND 
                      MD.LINE_NBR = MC.LINE_NBR LEFT OUTER JOIN
                      SALES_CLASS SC ON MH.MEDIA_TYPE = SC.SC_CODE LEFT OUTER JOIN 
					  JOB_LOG JL ON MD.JOB_NUMBER = JL.JOB_NUMBER LEFT OUTER JOIN
                      JOB_COMPONENT JC ON MD.JOB_NUMBER = JC.JOB_NUMBER AND 
                      MD.JOB_COMPONENT_NBR = JC.JOB_COMPONENT_NBR LEFT OUTER JOIN
                      VEN_REP VR ON MH.VN_CODE = VR.VN_CODE AND 
                      MH.VR_CODE = VR.VR_CODE LEFT OUTER JOIN
                      VEN_REP VR2 ON MH.VN_CODE = VR2.VN_CODE AND MH.VR_CODE2 = VR2.VR_CODE LEFT OUTER JOIN
                      CAMPAIGN AS C ON MH.CMP_IDENTIFIER = C.CMP_IDENTIFIER LEFT OUTER JOIN
                      MARKET AS M ON MH.MARKET_CODE = M.MARKET_CODE LEFT OUTER JOIN
                      AD_NUMBER AD ON MD.AD_NUMBER = AD.AD_NBR
	 WHERE ACTIVE_REV = 1 AND MH.ORDER_NBR = @OrderNumber and MD.LINE_NBR = @LineNumber AND MD.REV_NBR = @RevNumber
                                                  




