if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[usp_wv_ALERT_DismissAssigneeCCRecipientRecord]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [dbo].[usp_wv_ALERT_DismissAssigneeCCRecipientRecord]
GO

CREATE PROCEDURE [dbo].[usp_wv_ALERT_DismissAssigneeCCRecipientRecord] /*WITH ENCRYPTION*/
@ALERT_ID INT
AS
/*=========== QUERY ===========*/
	DECLARE
		@ASSIGNEE_EMP_CODE VARCHAR(6),
		@ASSIGNEE_IS_CC BIT

	SET @ASSIGNEE_IS_CC = 0;

	SELECT @ASSIGNEE_EMP_CODE = A.EMP_CODE FROM
		(
		SELECT ALERT_RCPT.EMP_CODE FROM ALERT_RCPT WITH(NOLOCK) WHERE ALERT_RCPT.ALERT_ID = @ALERT_ID AND ALERT_RCPT.CURRENT_NOTIFY = 1
		UNION
		SELECT ALERT_RCPT_DISMISSED.EMP_CODE FROM ALERT_RCPT_DISMISSED WITH(NOLOCK) WHERE ALERT_RCPT_DISMISSED.ALERT_ID = @ALERT_ID AND ALERT_RCPT_DISMISSED.CURRENT_NOTIFY = 1
		) AS A;

	IF NOT @ASSIGNEE_EMP_CODE IS NULL
	BEGIN

		IF EXISTS (
			SELECT ALERT_RCPT.EMP_CODE FROM ALERT_RCPT WITH(NOLOCK) WHERE ALERT_RCPT.ALERT_ID = @ALERT_ID AND ALERT_RCPT.EMP_CODE = @ASSIGNEE_EMP_CODE AND (ALERT_RCPT.CURRENT_NOTIFY = 0 OR ALERT_RCPT.CURRENT_NOTIFY IS NULL)
			UNION
			SELECT ALERT_RCPT_DISMISSED.EMP_CODE FROM ALERT_RCPT_DISMISSED WITH(NOLOCK) WHERE ALERT_RCPT_DISMISSED.ALERT_ID = @ALERT_ID AND ALERT_RCPT_DISMISSED.EMP_CODE = @ASSIGNEE_EMP_CODE AND (ALERT_RCPT_DISMISSED.CURRENT_NOTIFY = 0 OR ALERT_RCPT_DISMISSED.CURRENT_NOTIFY IS NULL)
		)
		BEGIN

			SET @ASSIGNEE_IS_CC = 1;

		END

	END

	IF @ASSIGNEE_IS_CC = 1
	BEGIN

		EXEC [dbo].[advsp_alert_dismiss_alert] @ALERT_ID, @ASSIGNEE_EMP_CODE;

	END
/*=========== QUERY ===========*/
GO
SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO