
CREATE PROCEDURE [dbo].[usp_wv_ALERT_UNDISMISS_NOT_ASSIGNMENT] /*WITH ENCRYPTION*/
@ALERT_ID  INT,
@EMP_CODE  VARCHAR(6)
AS
/*=========== QUERY ===========*/
	UPDATE ALERT_RCPT_DISMISSED
	SET    PROCESSED = NULL
	WHERE  ALERT_ID = @ALERT_ID
			AND EMP_CODE = @EMP_CODE AND (CURRENT_NOTIFY IS NULL OR CURRENT_NOTIFY = 0);

	--COPY DISMISSED TO BACK TO MAIN TABLE
	INSERT INTO ALERT_RCPT
	SELECT *
	FROM   ALERT_RCPT_DISMISSED
	WHERE  ALERT_ID = @ALERT_ID
			AND EMP_CODE = @EMP_CODE AND (CURRENT_NOTIFY IS NULL OR CURRENT_NOTIFY = 0);

	--DELETE DISMISSED FROM DISMISSED TABLE
	DELETE 
	FROM   ALERT_RCPT_DISMISSED
	WHERE  ALERT_ID = @ALERT_ID
			AND EMP_CODE = @EMP_CODE AND (CURRENT_NOTIFY IS NULL OR CURRENT_NOTIFY = 0);
/*=========== QUERY ===========*/
