
CREATE PROCEDURE [dbo].[usp_wv_BA_POSTING_PERIODS] AS

		SELECT     
			PPPERIOD, PPARCURMTH
		FROM         
			POSTPERIOD WITH (NOLOCK)
		WHERE     
			PPARCURMTH NOT IN ('X') OR (PPARCURMTH IS NULL)
		ORDER BY 
			PPPERIOD
	
