
CREATE PROCEDURE [dbo].[usp_wv_ALERT_UNDISMISS_CP] /*WITH ENCRYPTION*/
@ALERT_ID  INT,
@CDP_CONTACT_ID  INT
AS
/*=========== QUERY ===========*/
	UPDATE CP_ALERT_RCPT_DISMISSED
	SET    PROCESSED = NULL
	WHERE  ALERT_ID = @ALERT_ID
			AND CDP_CONTACT_ID = @CDP_CONTACT_ID AND (CURRENT_NOTIFY IS NULL OR CURRENT_NOTIFY = 0);

	--COPY DISMISSED TO BACK TO MAIN TABLE
	INSERT INTO CP_ALERT_RCPT
	SELECT *
	FROM   CP_ALERT_RCPT_DISMISSED
	WHERE  ALERT_ID = @ALERT_ID
			AND CDP_CONTACT_ID = @CDP_CONTACT_ID AND (CURRENT_NOTIFY IS NULL OR CURRENT_NOTIFY = 0);

	--DELETE DISMISSED FROM DISMISSED TABLE
	DELETE 
	FROM   CP_ALERT_RCPT_DISMISSED
	WHERE  ALERT_ID = @ALERT_ID
			AND CDP_CONTACT_ID = @CDP_CONTACT_ID AND (CURRENT_NOTIFY IS NULL OR CURRENT_NOTIFY = 0);
/*=========== QUERY ===========*/
