SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS OFF 
GO
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[usp_wv_dd_Batch_GetClientsByBatchID]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
DROP PROCEDURE [dbo].[usp_wv_dd_Batch_GetClientsByBatchID]
GO
CREATE PROCEDURE [dbo].[usp_wv_dd_Batch_GetClientsByBatchID] /*WITH ENCRYPTION*/
	@BA_BATCH_ID AS INTEGER,
	@EXCLUDE_EXISTING BIT
AS
/*=========== QUERY ===========*/
		SET @EXCLUDE_EXISTING = ISNULL(@EXCLUDE_EXISTING,0);
		
		IF @EXCLUDE_EXISTING = 0
		BEGIN
			SELECT     
				DISTINCT (JOB_LOG.CL_CODE) AS CL_CODE, CLIENT.CL_NAME,
				JOB_LOG.CL_CODE AS code, JOB_LOG.CL_CODE+' - '+CLIENT.CL_NAME AS description
			FROM        
				CLIENT WITH(NOLOCK) INNER JOIN
				JOB_LOG WITH(NOLOCK) ON CLIENT.CL_CODE = JOB_LOG.CL_CODE INNER JOIN
				JOB_COMPONENT WITH(NOLOCK) ON JOB_LOG.JOB_NUMBER = JOB_COMPONENT.JOB_NUMBER
			WHERE     
				(JOB_COMPONENT.BA_BATCH_ID = @BA_BATCH_ID)
				AND (NOT (JOB_COMPONENT.JOB_PROCESS_CONTRL IN (2, 6, 12)))
			ORDER BY
				CL_CODE;		
		END

		IF @EXCLUDE_EXISTING = 1
		BEGIN
			SELECT     
				DISTINCT (JOB_LOG.CL_CODE) AS CL_CODE, CLIENT.CL_NAME,
				JOB_LOG.CL_CODE AS code, JOB_LOG.CL_CODE+' - '+CLIENT.CL_NAME AS description
			FROM        
				CLIENT WITH(NOLOCK) INNER JOIN
				JOB_LOG WITH(NOLOCK) ON CLIENT.CL_CODE = JOB_LOG.CL_CODE INNER JOIN
				JOB_COMPONENT WITH(NOLOCK) ON JOB_LOG.JOB_NUMBER = JOB_COMPONENT.JOB_NUMBER
			WHERE     
				(JOB_COMPONENT.BA_BATCH_ID = @BA_BATCH_ID)
				AND (NOT (JOB_COMPONENT.JOB_PROCESS_CONTRL IN (2, 6, 12)))
				AND JOB_LOG.CL_CODE NOT IN (
					SELECT 
						DISTINCT BILL_APPR_CL.CL_CODE
					FROM         
						BILL_APPR WITH(NOLOCK) INNER JOIN
						BILL_APPR_CL WITH(NOLOCK) ON BILL_APPR.BA_ID = BILL_APPR_CL.BA_ID
					WHERE     
						(BILL_APPR.BA_BATCH_ID = @BA_BATCH_ID)				
				)
			ORDER BY
				CL_CODE;		
		END
/*=========== QUERY ===========*/
GO
SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO