





/* CHANGE LOG:
==========================================================
ST, 20060504
	Created this sproc by duplicating the one with the same name but without the "_withClosed" at the end
	Created this to remove the filter that hides closed/active jobs.
	Could have done it in code or the original sproc...but was afraid of disrupting something else somewhere in app I wasn't aware of. 
*/
CREATE PROCEDURE [dbo].[usp_wv_dd_GetAllJobs_withClosed] 
@UserID VarChar(100)
AS
Declare @Rescrictions Int

Set NoCount On

DECLARE @EMP_CODE AS VARCHAR(6)
DECLARE @OfficeCount AS INTEGER

SELECT @EMP_CODE = EMP_CODE FROM SEC_USER WHERE UPPER(USER_CODE) = UPPER(@UserID)

SELECT @OfficeCount = COUNT(*) FROM EMP_OFFICE WHERE EMP_CODE = @EMP_CODE

Select @Rescrictions = Count(*) 
FROM SEC_CLIENT
WHERE UPPER(USER_ID) = UPPER(@UserID)

If @Rescrictions > 0
	If @OfficeCount = 0
		Begin
			SELECT     JOB_LOG.JOB_NUMBER AS Code, STR(JOB_LOG.JOB_NUMBER) + ' - ' +isnull(JOB_LOG.JOB_DESC, '') AS Description
			FROM         JOB_LOG INNER JOIN
								  JOB_COMPONENT ON JOB_LOG.JOB_NUMBER = JOB_COMPONENT.JOB_NUMBER INNER JOIN
								  SEC_CLIENT ON JOB_LOG.CL_CODE = SEC_CLIENT.CL_CODE AND JOB_LOG.DIV_CODE = SEC_CLIENT.DIV_CODE AND 
								  JOB_LOG.PRD_CODE = SEC_CLIENT.PRD_CODE
			WHERE    (UPPER(SEC_CLIENT.USER_ID) = UPPER(@UserID)) AND (SEC_CLIENT.TIME_ENTRY = 0 OR SEC_CLIENT.TIME_ENTRY IS NULL)
			--And JOB_TRAFFIC.COMPLETED_DATE IS NULL
			GROUP BY JOB_LOG.JOB_NUMBER, JOB_LOG.JOB_DESC
			ORDER BY JOB_LOG.JOB_NUMBER DESC
		End
		Else
		Begin
			SELECT     JOB_LOG.JOB_NUMBER AS Code, STR(JOB_LOG.JOB_NUMBER) + ' - ' +isnull(JOB_LOG.JOB_DESC, '') AS Description
			FROM         JOB_LOG INNER JOIN
								  JOB_COMPONENT ON JOB_LOG.JOB_NUMBER = JOB_COMPONENT.JOB_NUMBER INNER JOIN
								  SEC_CLIENT ON JOB_LOG.CL_CODE = SEC_CLIENT.CL_CODE AND JOB_LOG.DIV_CODE = SEC_CLIENT.DIV_CODE AND 
								  JOB_LOG.PRD_CODE = SEC_CLIENT.PRD_CODE
							INNER JOIN EMP_OFFICE ON JOB_LOG.OFFICE_CODE = EMP_OFFICE.OFFICE_CODE AND EMP_OFFICE.EMP_CODE = @EMP_CODE
			WHERE    (UPPER(SEC_CLIENT.USER_ID) = UPPER(@UserID)) AND (SEC_CLIENT.TIME_ENTRY = 0 OR SEC_CLIENT.TIME_ENTRY IS NULL)
			--And JOB_TRAFFIC.COMPLETED_DATE IS NULL
			GROUP BY JOB_LOG.JOB_NUMBER, JOB_LOG.JOB_DESC
			ORDER BY JOB_LOG.JOB_NUMBER DESC
		End
	
ELSE
	If @OfficeCount = 0
		Begin
			SELECT     JOB_LOG.JOB_NUMBER as Code, str(JOB_LOG.JOB_NUMBER) + ' - ' + isnull(JOB_LOG.JOB_DESC, '') as Description
			FROM         JOB_LOG 
					 INNER JOIN
								  JOB_COMPONENT ON JOB_LOG.JOB_NUMBER = JOB_COMPONENT.JOB_NUMBER 
			--WHERE     (JOB_COMPONENT.JOB_PROCESS_CONTRL NOT IN (2,3,5,9,10,13)) 
			--And JOB_TRAFFIC.COMPLETED_DATE IS NULL
			Group By JOB_LOG.JOB_NUMBER, JOB_LOG.JOB_DESC
			ORDER BY JOB_LOG.JOB_NUMBER DESC
		End
		Else
		Begin
			SELECT     JOB_LOG.JOB_NUMBER as Code, str(JOB_LOG.JOB_NUMBER) + ' - ' + isnull(JOB_LOG.JOB_DESC, '') as Description
			FROM         JOB_LOG 
					 INNER JOIN
								  JOB_COMPONENT ON JOB_LOG.JOB_NUMBER = JOB_COMPONENT.JOB_NUMBER 
							INNER JOIN EMP_OFFICE ON JOB_LOG.OFFICE_CODE = EMP_OFFICE.OFFICE_CODE AND EMP_OFFICE.EMP_CODE = @EMP_CODE
			--WHERE     (JOB_COMPONENT.JOB_PROCESS_CONTRL NOT IN (2,3,5,9,10,13)) 
			--And JOB_TRAFFIC.COMPLETED_DATE IS NULL
			Group By JOB_LOG.JOB_NUMBER, JOB_LOG.JOB_DESC
			ORDER BY JOB_LOG.JOB_NUMBER DESC
		End
	


















