SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS OFF 
GO
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[usp_wv_BA_BATCH_UPDATE]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
DROP PROCEDURE [dbo].[usp_wv_BA_BATCH_UPDATE]
GO
CREATE PROCEDURE [dbo].[usp_wv_BA_BATCH_UPDATE] /*WITH ENCRYPTION*/
@BA_BATCH_ID INT,
@BA_BATCH_DESC VARCHAR(50),
@BATCH_DATE SMALLDATETIME,
@MODIFY_USER VARCHAR(100),
@MODIFY_DATE SMALLDATETIME,
@DATE_CUTOFF SMALLDATETIME,
@PERIOD_CUTOFF VARCHAR(6),
@EMP_CODE VARCHAR(6),
@INCL_NB BIT,
@INCL_FEE BIT,
@INCL_INT BIT,
@INCL_NP BIT,
@INCL_MAG BIT,
@INCL_OD BIT,
@INCL_RA BIT,
@INCL_TV BIT,
@APPR_METHOD SMALLINT,
@APPLY_CRITERIA SMALLINT,
@SEL_OPTION SMALLINT,
@MANAGER_TYPE SMALLINT -- 1=AE, 2=PM
AS
/*=========== QUERY ===========*/

	DECLARE
		@ERR INT,
		@THIS_BATCH_ID INT
	
	--UPDATE BATCH TABLE:
	UPDATE 
		BILL_APPR_BATCH WITH(ROWLOCK)
	SET
		BA_BATCH_DESC = @BA_BATCH_DESC,
		BATCH_DATE = @BATCH_DATE,
		MODIFY_USER = @MODIFY_USER,
		MODIFY_DATE = @MODIFY_DATE,
		DATE_CUTOFF = @DATE_CUTOFF,
		PERIOD_CUTOFF = ''+@PERIOD_CUTOFF+'',
		EMP_CODE = @EMP_CODE,
		INCL_NB = @INCL_NB,
		INCL_FEE = @INCL_FEE,
		INCL_INT = @INCL_INT,
		INCL_NP = @INCL_NP,
		INCL_MAG = @INCL_MAG,
		INCL_OD = @INCL_OD,
		INCL_RA = @INCL_RA,
		INCL_TV = @INCL_TV,
		APPR_METHOD = @APPR_METHOD,
		SEL_OPTION = @SEL_OPTION,
		MANAGER_TYPE = @MANAGER_TYPE
	WHERE
		BILL_APPR_BATCH.BA_BATCH_ID = @BA_BATCH_ID;


	SET @THIS_BATCH_ID = @BA_BATCH_ID;

	IF @APPLY_CRITERIA = 1
	BEGIN
		EXEC usp_wv_BA_BATCH_CLEAR_SEL @BA_BATCH_ID,0;
		EXEC usp_wv_BA_BATCH_APPLY_CRITERIA @BA_BATCH_ID;
	END

	SELECT @THIS_BATCH_ID;

/*=========== QUERY ===========*/
GO
SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO


