
CREATE PROCEDURE [dbo].[usp_wv_BA_APPROVAL_JC_GET_AVAIL_FNC] 
    @JOB_NUMBER AS INTEGER,
    @JOB_COMPONENT_NBR AS SMALLINT,
    @BA_ID AS INTEGER,
    @BA_BATCH_ID AS INTEGER
AS

		--VARS NEEDED FOR BEN'S SPROC
DECLARE
	@DATE_CUTOFF AS SMALLDATETIME,
	@POST_PERIOD AS VARCHAR(6),
	@EXCL_NOBILL AS BIT,
	@EXCL_FEE AS BIT
	
SELECT 
	@DATE_CUTOFF = DATE_CUTOFF,
	@POST_PERIOD = PERIOD_CUTOFF,
	@EXCL_NOBILL = INCL_NB,
	@EXCL_FEE = INCL_FEE
FROM
    BILL_APPR_BATCH	WITH(NOLOCK)
WHERE 
	BA_BATCH_ID = @BA_BATCH_ID;
	
IF @EXCL_NOBILL = 1
    BEGIN
        SET @EXCL_NOBILL = 0
    END
ELSE
    BEGIN
        SET @EXCL_NOBILL = 1
    END

	
IF @EXCL_FEE = 1
    BEGIN
        SET @EXCL_FEE = 0
    END
ELSE
    BEGIN
        SET @EXCL_FEE = 1
    END
		    
		CREATE TABLE #CURR_FNC
			(
			 FNC_CODE VARCHAR(6) NOT NULL
			) ;
		--FNC'S THAT SHOULD BE ON THE GRID BECAUSE OF BEN'S FUNCTION:
		INSERT INTO
			#CURR_FNC (FNC_CODE)
			SELECT  DISTINCT
				FNC_CODE COLLATE SQL_Latin1_General_CP1_CS_AS
			FROM
				dbo.advtf_prod_bill_amts_by_fnc(@JOB_NUMBER,@JOB_COMPONENT_NBR,
												@DATE_CUTOFF,@POST_PERIOD, @EXCL_NOBILL, @EXCL_FEE) ;
		                                        
		 --FNC'S THAT EXIST FOR THE APPROVAL JOB COMP:
		INSERT INTO
			#CURR_FNC (FNC_CODE)
			SELECT  DISTINCT
				FNC_CODE COLLATE SQL_Latin1_General_CP1_CS_AS
			FROM
				BILL_APPR_DTL
			WHERE
				BA_ID = @BA_ID
				AND JOB_NUMBER = @JOB_NUMBER
				AND JOB_COMPONENT_NBR = @JOB_COMPONENT_NBR
				AND FNC_CODE NOT IN (SELECT DISTINCT
										FNC_CODE COLLATE SQL_Latin1_General_CP1_CS_AS
									 FROM
										#CURR_FNC) ;
		                                  
			
		SELECT
			FNC_CODE AS code,
			FNC_CODE + ' - ' + ISNULL(FNC_DESCRIPTION,FNC_CODE) AS description,
			FNC_CODE + ' - ' + ISNULL(FNC_DESCRIPTION,FNC_CODE) AS codedescription
		FROM
			FUNCTIONS
		WHERE
			FNC_CODE COLLATE SQL_Latin1_General_CP1_CS_AS NOT IN (
			SELECT DISTINCT
				FNC_CODE COLLATE SQL_Latin1_General_CP1_CS_AS
			FROM
				#CURR_FNC)
			AND FNC_TYPE NOT IN ('F','C')
			AND ((FNC_INACTIVE = 0) OR
                      (FNC_INACTIVE IS NULL))
				 ;
		        
		DROP TABLE #CURR_FNC ; 


    	
