


/*****************************************************************
Webvantage
This Stored Procedure gets a Tasks By a Date, 
******************************************************************/
CREATE PROCEDURE [dbo].[usp_wv_calendar_task_month_office] 
@UserID VarChar(100),
@EmpCode Varchar(6),
@ClientCode VarChar(6),
@DivCode VarChar(6),
@ProdCode VarChar(6),
@Office VarChar(4),
@Role VarChar(6),
@StartDate Varchar(10),
@EndDate Varchar(10),
@TaskStatus Varchar(1),
@ExcludeTempComplete Char(1),
@MilestonesOnly Char(1)
AS
Declare @Rescrictions Int
Declare @RescrictionsEmp Int

Set NoCount On

Select @Rescrictions = Count(*) 
FROM SEC_CLIENT
WHERE UPPER(USER_ID) = UPPER(@UserID)

Select @RescrictionsEmp = Count(*) 
FROM SEC_EMP
WHERE UPPER(USER_ID) = UPPER(@UserID)


If @MilestonesOnly = 'N' 
Begin
	If @Rescrictions > 0 and @RescrictionsEmp > 0
	   If @ExcludeTempComplete = 'Y'
				SELECT JOB_LOG.CL_CODE as CCode,
				 JOB_LOG.DIV_CODE as DCode,
				 JOB_LOG.PRD_CODE as PCode,
				 JOB_LOG.JOB_NUMBER as JobNum,
				 JOB_LOG.JOB_DESC as JobDesc,
				 JOB_COMPONENT.JOB_COMPONENT_NBR as CompNum,
				 JOB_COMPONENT.JOB_COMP_DESC as CompDesc,
				 STR(DATEPART(day, JOB_TRAFFIC_DET.JOB_REVISED_DATE)) as ThisDay,
				 isnull(JOB_TRAFFIC_DET.TASK_DESCRIPTION, '(' + ISNULL(JOB_TRAFFIC_DET.FNC_CODE,'') + ')') as Task, 
				 isnull(JOB_TRAFFIC_DET.TEMP_COMP_DATE, '1/1/1900') as TempCompDate,
				 JOB_TRAFFIC_DET.TASK_STATUS, STR(DATEPART(day, JOB_TRAFFIC_DET.TASK_START_DATE)) as ThisDayStart, JOB_TRAFFIC_DET.SEQ_NBR,
				 CLIENT.CL_NAME, DIVISION.DIV_NAME, PRODUCT.PRD_DESCRIPTION, TRAFFIC_FNC.TRF_CODE, JOB_TRAFFIC_DET.JOB_REVISED_DATE as RevisedDate, isnull(JOB_TRAFFIC_DET.TASK_START_DATE, '1/1/1900') as StartDate,
				 JOB_TRAFFIC_DET.EMP_CODE as empcodedispl,
				 dbo.udf_get_empl_name( JOB_TRAFFIC_DET.EMP_CODE, 'FML' ) AS empdescdispl
		FROM JOB_LOG INNER JOIN JOB_COMPONENT ON JOB_LOG.JOB_NUMBER = JOB_COMPONENT.JOB_NUMBER
						 INNER JOIN JOB_TRAFFIC_DET ON JOB_COMPONENT.JOB_NUMBER = JOB_TRAFFIC_DET.JOB_NUMBER AND
									JOB_COMPONENT.JOB_COMPONENT_NBR = JOB_TRAFFIC_DET.JOB_COMPONENT_NBR
						 INNER JOIN SEC_CLIENT ON JOB_LOG.CL_CODE = SEC_CLIENT.CL_CODE AND JOB_LOG.DIV_CODE = SEC_CLIENT.DIV_CODE AND JOB_LOG.PRD_CODE = SEC_CLIENT.PRD_CODE
						 INNER JOIN PRODUCT ON JOB_LOG.CL_CODE = PRODUCT.CL_CODE AND JOB_LOG.DIV_CODE = PRODUCT.DIV_CODE AND 
										   JOB_LOG.PRD_CODE = PRODUCT.PRD_CODE 
						 INNER JOIN DIVISION ON PRODUCT.CL_CODE = DIVISION.CL_CODE AND PRODUCT.DIV_CODE = DIVISION.DIV_CODE 
						 INNER JOIN CLIENT ON DIVISION.CL_CODE = CLIENT.CL_CODE
						 LEFT OUTER JOIN TRAFFIC_FNC ON JOB_TRAFFIC_DET.FNC_CODE = TRAFFIC_FNC.TRF_CODE
						 INNER JOIN [dbo].[advtf_sec_emp] (@UserID) AS SEC_EMP ON JOB_TRAFFIC_DET.EMP_CODE = SEC_EMP.EMP_CODE
						 LEFT OUTER JOIN TASK_TRAFFIC_ROLE ON JOB_TRAFFIC_DET.FNC_CODE = TASK_TRAFFIC_ROLE.TRF_CODE 
						 LEFT OUTER JOIN EMP_TRAFFIC_ROLE ON JOB_TRAFFIC_DET.EMP_CODE = EMP_TRAFFIC_ROLE.EMP_CODE
		WHERE (NOT (JOB_COMPONENT.JOB_PROCESS_CONTRL IN (6, 12))) AND
			  (UPPER(SEC_CLIENT.USER_ID) = UPPER(@UserID)) AND (SEC_CLIENT.TIME_ENTRY = 0 OR SEC_CLIENT.TIME_ENTRY IS NULL) AND
			  (Isnull(JOB_TRAFFIC_DET.EMP_CODE, '') Like '%' + @EmpCode) AND
			   JOB_LOG.CL_CODE Like '%' + @ClientCode AND
			   JOB_LOG.DIV_CODE Like '%' + @DivCode AND
			   JOB_LOG.PRD_CODE Like '%' + @ProdCode AND
			   JOB_LOG.OFFICE_CODE Like '%' + @Office AND
			   ((JOB_TRAFFIC_DET.JOB_REVISED_DATE >= @StartDate AND
			   JOB_TRAFFIC_DET.JOB_REVISED_DATE <= @EndDate) OR (JOB_TRAFFIC_DET.TASK_START_DATE >= @StartDate AND JOB_TRAFFIC_DET.TASK_START_DATE <= @EndDate)
			   OR (@StartDate >= JOB_TRAFFIC_DET.TASK_START_DATE and @EndDate <= JOB_TRAFFIC_DET.JOB_REVISED_DATE)) AND
			   JOB_TRAFFIC_DET.JOB_COMPLETED_DATE IS NULL AND
			  (ISNULL(TASK_TRAFFIC_ROLE.ROLE_CODE, '') Like '%' + @Role OR ISNULL(EMP_TRAFFIC_ROLE.ROLE_CODE, '') Like '%' + @Role) AND
				   ISNULL(JOB_TRAFFIC_DET.TASK_STATUS, '') Like Case @TaskStatus
													When 'P' Then 'P'
																When 'A' Then 'A'
													When '' Then '%'
														End AND
				   JOB_TRAFFIC_DET.TEMP_COMP_DATE IS NULL
		  GROUP BY JOB_LOG.CL_CODE,
			   JOB_LOG.DIV_CODE,
			   JOB_LOG.PRD_CODE,
			   JOB_LOG.JOB_NUMBER,
			   JOB_LOG.JOB_DESC,
			   JOB_COMPONENT.JOB_COMPONENT_NBR,
			   JOB_COMPONENT.JOB_COMP_DESC,
			   STR(DATEPART(day, JOB_TRAFFIC_DET.TASK_START_DATE)),
			   STR(DATEPART(day, JOB_TRAFFIC_DET.JOB_REVISED_DATE)),
			   ISNULL(JOB_TRAFFIC_DET.TASK_DESCRIPTION, '(' + ISNULL(JOB_TRAFFIC_DET.FNC_CODE,'') + ')') ,
			   JOB_TRAFFIC_DET.JOB_REVISED_DATE, 
			   JOB_TRAFFIC_DET.TASK_START_DATE,
			   JOB_TRAFFIC_DET.TEMP_COMP_DATE,
				   JOB_TRAFFIC_DET.TASK_STATUS,
				   JOB_TRAFFIC_DET.SEQ_NBR,
				   CLIENT.CL_NAME, DIVISION.DIV_NAME, PRODUCT.PRD_DESCRIPTION, TRAFFIC_FNC.TRF_CODE, JOB_TRAFFIC_DET.EMP_CODE
		  ORDER BY JOB_TRAFFIC_DET.JOB_REVISED_DATE

	   ELSE
		  SELECT JOB_LOG.CL_CODE as CCode,
				 JOB_LOG.DIV_CODE as DCode,
				 JOB_LOG.PRD_CODE as PCode,
				 JOB_LOG.JOB_NUMBER as JobNum,
				 JOB_LOG.JOB_DESC as JobDesc,
				 JOB_COMPONENT.JOB_COMPONENT_NBR as CompNum,
				 JOB_COMPONENT.JOB_COMP_DESC as CompDesc,
				 STR(DATEPART(day, JOB_TRAFFIC_DET.JOB_REVISED_DATE)) as ThisDay,
				 isnull(JOB_TRAFFIC_DET.TASK_DESCRIPTION, '(' + ISNULL(JOB_TRAFFIC_DET.FNC_CODE,'') + ')') as Task, 
				 isnull(JOB_TRAFFIC_DET.TEMP_COMP_DATE, '1/1/1900') as TempCompDate,
				 JOB_TRAFFIC_DET.TASK_STATUS, STR(DATEPART(day, JOB_TRAFFIC_DET.TASK_START_DATE)) as ThisDayStart, JOB_TRAFFIC_DET.SEQ_NBR,
				 CLIENT.CL_NAME, DIVISION.DIV_NAME, PRODUCT.PRD_DESCRIPTION, TRAFFIC_FNC.TRF_CODE, JOB_TRAFFIC_DET.JOB_REVISED_DATE as RevisedDate, isnull(JOB_TRAFFIC_DET.TASK_START_DATE, '1/1/1900') as StartDate,
				 JOB_TRAFFIC_DET.EMP_CODE as empcodedispl,
				 dbo.udf_get_empl_name( JOB_TRAFFIC_DET.EMP_CODE, 'FML' ) AS empdescdispl
		FROM JOB_LOG INNER JOIN JOB_COMPONENT ON JOB_LOG.JOB_NUMBER = JOB_COMPONENT.JOB_NUMBER
						 INNER JOIN JOB_TRAFFIC_DET ON JOB_COMPONENT.JOB_NUMBER = JOB_TRAFFIC_DET.JOB_NUMBER AND
									JOB_COMPONENT.JOB_COMPONENT_NBR = JOB_TRAFFIC_DET.JOB_COMPONENT_NBR
						 INNER JOIN SEC_CLIENT ON JOB_LOG.CL_CODE = SEC_CLIENT.CL_CODE AND JOB_LOG.DIV_CODE = SEC_CLIENT.DIV_CODE AND JOB_LOG.PRD_CODE = SEC_CLIENT.PRD_CODE
						 INNER JOIN PRODUCT ON JOB_LOG.CL_CODE = PRODUCT.CL_CODE AND JOB_LOG.DIV_CODE = PRODUCT.DIV_CODE AND 
										   JOB_LOG.PRD_CODE = PRODUCT.PRD_CODE 
						 INNER JOIN DIVISION ON PRODUCT.CL_CODE = DIVISION.CL_CODE AND PRODUCT.DIV_CODE = DIVISION.DIV_CODE 
						 INNER JOIN CLIENT ON DIVISION.CL_CODE = CLIENT.CL_CODE
						 LEFT OUTER JOIN TRAFFIC_FNC ON JOB_TRAFFIC_DET.FNC_CODE = TRAFFIC_FNC.TRF_CODE
						 INNER JOIN [dbo].[advtf_sec_emp] (@UserID) AS SEC_EMP ON JOB_TRAFFIC_DET.EMP_CODE = SEC_EMP.EMP_CODE
						 LEFT OUTER JOIN TASK_TRAFFIC_ROLE ON JOB_TRAFFIC_DET.FNC_CODE = TASK_TRAFFIC_ROLE.TRF_CODE 
						 LEFT OUTER JOIN EMP_TRAFFIC_ROLE ON JOB_TRAFFIC_DET.EMP_CODE = EMP_TRAFFIC_ROLE.EMP_CODE
		WHERE (NOT (JOB_COMPONENT.JOB_PROCESS_CONTRL IN (6, 12))) AND
			  (UPPER(SEC_CLIENT.USER_ID) = UPPER(@UserID)) AND (SEC_CLIENT.TIME_ENTRY = 0 OR SEC_CLIENT.TIME_ENTRY IS NULL) AND
			  (Isnull(JOB_TRAFFIC_DET.EMP_CODE, '') Like '%' + @EmpCode) AND
			   JOB_LOG.CL_CODE Like '%' + @ClientCode AND
			   JOB_LOG.DIV_CODE Like '%' + @DivCode AND
			   JOB_LOG.PRD_CODE Like '%' + @ProdCode AND
			   JOB_LOG.OFFICE_CODE Like '%' + @Office AND
			   ((JOB_TRAFFIC_DET.JOB_REVISED_DATE >= @StartDate AND
			   JOB_TRAFFIC_DET.JOB_REVISED_DATE <= @EndDate) OR (JOB_TRAFFIC_DET.TASK_START_DATE >= @StartDate AND JOB_TRAFFIC_DET.TASK_START_DATE <= @EndDate)
			   OR (@StartDate >= JOB_TRAFFIC_DET.TASK_START_DATE and @EndDate <= JOB_TRAFFIC_DET.JOB_REVISED_DATE)) AND
			   JOB_TRAFFIC_DET.JOB_COMPLETED_DATE IS NULL AND
			  (ISNULL(TASK_TRAFFIC_ROLE.ROLE_CODE, '') Like '%' + @Role OR ISNULL(EMP_TRAFFIC_ROLE.ROLE_CODE, '') Like '%' + @Role) AND
				   ISNULL(JOB_TRAFFIC_DET.TASK_STATUS, '') Like Case @TaskStatus
													When 'P' Then 'P'
																When 'A' Then 'A'
													When '' Then '%'
														End
		  GROUP BY JOB_LOG.CL_CODE,
			   JOB_LOG.DIV_CODE,
			   JOB_LOG.PRD_CODE,
			   JOB_LOG.JOB_NUMBER,
			   JOB_LOG.JOB_DESC,
			   JOB_COMPONENT.JOB_COMPONENT_NBR,
			   JOB_COMPONENT.JOB_COMP_DESC,
			   STR(DATEPART(day, JOB_TRAFFIC_DET.TASK_START_DATE)),
			   STR(DATEPART(day, JOB_TRAFFIC_DET.JOB_REVISED_DATE)),
			   ISNULL(JOB_TRAFFIC_DET.TASK_DESCRIPTION, '(' + ISNULL(JOB_TRAFFIC_DET.FNC_CODE,'') + ')') ,
			   JOB_TRAFFIC_DET.JOB_REVISED_DATE, 
			   JOB_TRAFFIC_DET.TASK_START_DATE,
			   JOB_TRAFFIC_DET.TEMP_COMP_DATE,
				   JOB_TRAFFIC_DET.TASK_STATUS,
				   JOB_TRAFFIC_DET.SEQ_NBR,
				   CLIENT.CL_NAME, DIVISION.DIV_NAME, PRODUCT.PRD_DESCRIPTION, TRAFFIC_FNC.TRF_CODE, JOB_TRAFFIC_DET.EMP_CODE
		  ORDER BY JOB_TRAFFIC_DET.JOB_REVISED_DATE
	      
	If @Rescrictions = 0 and @RescrictionsEmp > 0
	   If @ExcludeTempComplete = 'Y'
				SELECT JOB_LOG.CL_CODE as CCode,
				 JOB_LOG.DIV_CODE as DCode,
				 JOB_LOG.PRD_CODE as PCode,
				 JOB_LOG.JOB_NUMBER as JobNum,
				 JOB_LOG.JOB_DESC as JobDesc,
				 JOB_COMPONENT.JOB_COMPONENT_NBR as CompNum,
				 JOB_COMPONENT.JOB_COMP_DESC as CompDesc,
				 STR(DATEPART(day, JOB_TRAFFIC_DET.JOB_REVISED_DATE)) as ThisDay,
				 isnull(JOB_TRAFFIC_DET.TASK_DESCRIPTION, '(' + ISNULL(JOB_TRAFFIC_DET.FNC_CODE,'') + ')') as Task, 
				 isnull(JOB_TRAFFIC_DET.TEMP_COMP_DATE, '1/1/1900') as TempCompDate,
				 JOB_TRAFFIC_DET.TASK_STATUS, STR(DATEPART(day, JOB_TRAFFIC_DET.TASK_START_DATE)) as ThisDayStart, JOB_TRAFFIC_DET.SEQ_NBR,
				 CLIENT.CL_NAME, DIVISION.DIV_NAME, PRODUCT.PRD_DESCRIPTION, TRAFFIC_FNC.TRF_CODE, JOB_TRAFFIC_DET.JOB_REVISED_DATE as RevisedDate, isnull(JOB_TRAFFIC_DET.TASK_START_DATE, '1/1/1900') as StartDate,
				 JOB_TRAFFIC_DET.EMP_CODE as empcodedispl,
				 dbo.udf_get_empl_name( JOB_TRAFFIC_DET.EMP_CODE, 'FML' ) AS empdescdispl
		FROM JOB_LOG INNER JOIN JOB_COMPONENT ON JOB_LOG.JOB_NUMBER = JOB_COMPONENT.JOB_NUMBER
						 INNER JOIN JOB_TRAFFIC_DET ON JOB_COMPONENT.JOB_NUMBER = JOB_TRAFFIC_DET.JOB_NUMBER AND
									JOB_COMPONENT.JOB_COMPONENT_NBR = JOB_TRAFFIC_DET.JOB_COMPONENT_NBR
						 INNER JOIN PRODUCT ON JOB_LOG.CL_CODE = PRODUCT.CL_CODE AND JOB_LOG.DIV_CODE = PRODUCT.DIV_CODE AND 
										   JOB_LOG.PRD_CODE = PRODUCT.PRD_CODE 
						 INNER JOIN DIVISION ON PRODUCT.CL_CODE = DIVISION.CL_CODE AND PRODUCT.DIV_CODE = DIVISION.DIV_CODE 
						 INNER JOIN CLIENT ON DIVISION.CL_CODE = CLIENT.CL_CODE  
						 LEFT OUTER JOIN TRAFFIC_FNC ON JOB_TRAFFIC_DET.FNC_CODE = TRAFFIC_FNC.TRF_CODE
						 INNER JOIN [dbo].[advtf_sec_emp] (@UserID) AS SEC_EMP ON JOB_TRAFFIC_DET.EMP_CODE = SEC_EMP.EMP_CODE
						 LEFT OUTER JOIN TASK_TRAFFIC_ROLE ON JOB_TRAFFIC_DET.FNC_CODE = TASK_TRAFFIC_ROLE.TRF_CODE 
						 LEFT OUTER JOIN EMP_TRAFFIC_ROLE ON JOB_TRAFFIC_DET.EMP_CODE = EMP_TRAFFIC_ROLE.EMP_CODE
		WHERE (NOT (JOB_COMPONENT.JOB_PROCESS_CONTRL IN (6, 12))) AND
			  (Isnull(JOB_TRAFFIC_DET.EMP_CODE, '') Like '%' + @EmpCode) AND
			   JOB_LOG.CL_CODE Like '%' + @ClientCode AND
			   JOB_LOG.DIV_CODE Like '%' + @DivCode AND
			   JOB_LOG.PRD_CODE Like '%' + @ProdCode AND
			   JOB_LOG.OFFICE_CODE Like '%' + @Office AND
			   ((JOB_TRAFFIC_DET.JOB_REVISED_DATE >= @StartDate AND
			   JOB_TRAFFIC_DET.JOB_REVISED_DATE <= @EndDate) OR (JOB_TRAFFIC_DET.TASK_START_DATE >= @StartDate AND JOB_TRAFFIC_DET.TASK_START_DATE <= @EndDate)
			   OR (@StartDate >= JOB_TRAFFIC_DET.TASK_START_DATE and @EndDate <= JOB_TRAFFIC_DET.JOB_REVISED_DATE)) AND
			   JOB_TRAFFIC_DET.JOB_COMPLETED_DATE IS NULL AND
			  (ISNULL(TASK_TRAFFIC_ROLE.ROLE_CODE, '') Like '%' + @Role OR ISNULL(EMP_TRAFFIC_ROLE.ROLE_CODE, '') Like '%' + @Role) AND
				   ISNULL(JOB_TRAFFIC_DET.TASK_STATUS, '') Like Case @TaskStatus
													When 'P' Then 'P'
																When 'A' Then 'A'
													When '' Then '%'
														End AND
				   JOB_TRAFFIC_DET.TEMP_COMP_DATE IS NULL
		  GROUP BY JOB_LOG.CL_CODE,
			   JOB_LOG.DIV_CODE,
			   JOB_LOG.PRD_CODE,
			   JOB_LOG.JOB_NUMBER,
			   JOB_LOG.JOB_DESC,
			   JOB_COMPONENT.JOB_COMPONENT_NBR,
			   JOB_COMPONENT.JOB_COMP_DESC,
			   STR(DATEPART(day, JOB_TRAFFIC_DET.TASK_START_DATE)),
			   STR(DATEPART(day, JOB_TRAFFIC_DET.JOB_REVISED_DATE)),
			   ISNULL(JOB_TRAFFIC_DET.TASK_DESCRIPTION, '(' + ISNULL(JOB_TRAFFIC_DET.FNC_CODE,'') + ')') ,
			   JOB_TRAFFIC_DET.JOB_REVISED_DATE, 
			   JOB_TRAFFIC_DET.TASK_START_DATE,
			   JOB_TRAFFIC_DET.TEMP_COMP_DATE,
				   JOB_TRAFFIC_DET.TASK_STATUS,
				   JOB_TRAFFIC_DET.SEQ_NBR,
				   CLIENT.CL_NAME, DIVISION.DIV_NAME, PRODUCT.PRD_DESCRIPTION, TRAFFIC_FNC.TRF_CODE, JOB_TRAFFIC_DET.EMP_CODE
		  ORDER BY JOB_TRAFFIC_DET.JOB_REVISED_DATE

	   ELSE
		  SELECT JOB_LOG.CL_CODE as CCode,
				 JOB_LOG.DIV_CODE as DCode,
				 JOB_LOG.PRD_CODE as PCode,
				 JOB_LOG.JOB_NUMBER as JobNum,
				 JOB_LOG.JOB_DESC as JobDesc,
				 JOB_COMPONENT.JOB_COMPONENT_NBR as CompNum,
				 JOB_COMPONENT.JOB_COMP_DESC as CompDesc,
				 STR(DATEPART(day, JOB_TRAFFIC_DET.JOB_REVISED_DATE)) as ThisDay,
				 isnull(JOB_TRAFFIC_DET.TASK_DESCRIPTION, '(' + ISNULL(JOB_TRAFFIC_DET.FNC_CODE,'') + ')') as Task, 
				 isnull(JOB_TRAFFIC_DET.TEMP_COMP_DATE, '1/1/1900') as TempCompDate,
				 JOB_TRAFFIC_DET.TASK_STATUS, STR(DATEPART(day, JOB_TRAFFIC_DET.TASK_START_DATE)) as ThisDayStart, JOB_TRAFFIC_DET.SEQ_NBR,
				 CLIENT.CL_NAME, DIVISION.DIV_NAME, PRODUCT.PRD_DESCRIPTION, TRAFFIC_FNC.TRF_CODE, JOB_TRAFFIC_DET.JOB_REVISED_DATE as RevisedDate, isnull(JOB_TRAFFIC_DET.TASK_START_DATE, '1/1/1900') as StartDate,
				 JOB_TRAFFIC_DET.EMP_CODE as empcodedispl,
				 dbo.udf_get_empl_name( JOB_TRAFFIC_DET.EMP_CODE, 'FML' ) AS empdescdispl
		FROM JOB_LOG INNER JOIN JOB_COMPONENT ON JOB_LOG.JOB_NUMBER = JOB_COMPONENT.JOB_NUMBER
						 INNER JOIN JOB_TRAFFIC_DET ON JOB_COMPONENT.JOB_NUMBER = JOB_TRAFFIC_DET.JOB_NUMBER AND
									JOB_COMPONENT.JOB_COMPONENT_NBR = JOB_TRAFFIC_DET.JOB_COMPONENT_NBR
						 INNER JOIN PRODUCT ON JOB_LOG.CL_CODE = PRODUCT.CL_CODE AND JOB_LOG.DIV_CODE = PRODUCT.DIV_CODE AND 
										   JOB_LOG.PRD_CODE = PRODUCT.PRD_CODE 
						 INNER JOIN DIVISION ON PRODUCT.CL_CODE = DIVISION.CL_CODE AND PRODUCT.DIV_CODE = DIVISION.DIV_CODE 
						 INNER JOIN CLIENT ON DIVISION.CL_CODE = CLIENT.CL_CODE  
						 LEFT OUTER JOIN TRAFFIC_FNC ON JOB_TRAFFIC_DET.FNC_CODE = TRAFFIC_FNC.TRF_CODE
						 INNER JOIN [dbo].[advtf_sec_emp] (@UserID) AS SEC_EMP ON JOB_TRAFFIC_DET.EMP_CODE = SEC_EMP.EMP_CODE
						 LEFT OUTER JOIN TASK_TRAFFIC_ROLE ON JOB_TRAFFIC_DET.FNC_CODE = TASK_TRAFFIC_ROLE.TRF_CODE 
						 LEFT OUTER JOIN EMP_TRAFFIC_ROLE ON JOB_TRAFFIC_DET.EMP_CODE = EMP_TRAFFIC_ROLE.EMP_CODE
		WHERE (NOT (JOB_COMPONENT.JOB_PROCESS_CONTRL IN (6, 12))) AND
			  (Isnull(JOB_TRAFFIC_DET.EMP_CODE, '') Like '%' + @EmpCode) AND
			   JOB_LOG.CL_CODE Like '%' + @ClientCode AND
			   JOB_LOG.DIV_CODE Like '%' + @DivCode AND
			   JOB_LOG.PRD_CODE Like '%' + @ProdCode AND
			   JOB_LOG.OFFICE_CODE Like '%' + @Office AND
			   ((JOB_TRAFFIC_DET.JOB_REVISED_DATE >= @StartDate AND
			   JOB_TRAFFIC_DET.JOB_REVISED_DATE <= @EndDate) OR (JOB_TRAFFIC_DET.TASK_START_DATE >= @StartDate AND JOB_TRAFFIC_DET.TASK_START_DATE <= @EndDate)
			   OR (@StartDate >= JOB_TRAFFIC_DET.TASK_START_DATE and @EndDate <= JOB_TRAFFIC_DET.JOB_REVISED_DATE)) AND
			   JOB_TRAFFIC_DET.JOB_COMPLETED_DATE IS NULL AND
			  (ISNULL(TASK_TRAFFIC_ROLE.ROLE_CODE, '') Like '%' + @Role OR ISNULL(EMP_TRAFFIC_ROLE.ROLE_CODE, '') Like '%' + @Role) AND
				   ISNULL(JOB_TRAFFIC_DET.TASK_STATUS, '') Like Case @TaskStatus
													When 'P' Then 'P'
																When 'A' Then 'A'
													When '' Then '%'
														End
		  GROUP BY JOB_LOG.CL_CODE,
			   JOB_LOG.DIV_CODE,
			   JOB_LOG.PRD_CODE,
			   JOB_LOG.JOB_NUMBER,
			   JOB_LOG.JOB_DESC,
			   JOB_COMPONENT.JOB_COMPONENT_NBR,
			   JOB_COMPONENT.JOB_COMP_DESC,
			   STR(DATEPART(day, JOB_TRAFFIC_DET.TASK_START_DATE)),
			   STR(DATEPART(day, JOB_TRAFFIC_DET.JOB_REVISED_DATE)),
			   ISNULL(JOB_TRAFFIC_DET.TASK_DESCRIPTION, '(' + ISNULL(JOB_TRAFFIC_DET.FNC_CODE,'') + ')') ,
			   JOB_TRAFFIC_DET.JOB_REVISED_DATE, 
			   JOB_TRAFFIC_DET.TASK_START_DATE,
			   JOB_TRAFFIC_DET.TEMP_COMP_DATE,
				   JOB_TRAFFIC_DET.TASK_STATUS,
				   JOB_TRAFFIC_DET.SEQ_NBR,
				   CLIENT.CL_NAME, DIVISION.DIV_NAME, PRODUCT.PRD_DESCRIPTION, TRAFFIC_FNC.TRF_CODE, JOB_TRAFFIC_DET.EMP_CODE
		  ORDER BY JOB_TRAFFIC_DET.JOB_REVISED_DATE

	If @Rescrictions > 0 and @RescrictionsEmp = 0
	   If @ExcludeTempComplete = 'Y'
				SELECT JOB_LOG.CL_CODE as CCode,
				 JOB_LOG.DIV_CODE as DCode,
				 JOB_LOG.PRD_CODE as PCode,
				 JOB_LOG.JOB_NUMBER as JobNum,
				 JOB_LOG.JOB_DESC as JobDesc,
				 JOB_COMPONENT.JOB_COMPONENT_NBR as CompNum,
				 JOB_COMPONENT.JOB_COMP_DESC as CompDesc,
				 STR(DATEPART(day, JOB_TRAFFIC_DET.JOB_REVISED_DATE)) as ThisDay,
				 isnull(JOB_TRAFFIC_DET.TASK_DESCRIPTION, '(' + ISNULL(JOB_TRAFFIC_DET.FNC_CODE,'') + ')') as Task, 
				 isnull(JOB_TRAFFIC_DET.TEMP_COMP_DATE, '1/1/1900') as TempCompDate,
				 JOB_TRAFFIC_DET.TASK_STATUS, STR(DATEPART(day, JOB_TRAFFIC_DET.TASK_START_DATE)) as ThisDayStart, JOB_TRAFFIC_DET.SEQ_NBR,
				 CLIENT.CL_NAME, DIVISION.DIV_NAME, PRODUCT.PRD_DESCRIPTION, TRAFFIC_FNC.TRF_CODE, JOB_TRAFFIC_DET.JOB_REVISED_DATE as RevisedDate, isnull(JOB_TRAFFIC_DET.TASK_START_DATE, '1/1/1900') as StartDate,
				 JOB_TRAFFIC_DET.EMP_CODE as empcodedispl,
				 dbo.udf_get_empl_name( JOB_TRAFFIC_DET.EMP_CODE, 'FML' ) AS empdescdispl
		FROM JOB_LOG INNER JOIN JOB_COMPONENT ON JOB_LOG.JOB_NUMBER = JOB_COMPONENT.JOB_NUMBER
						 INNER JOIN JOB_TRAFFIC_DET ON JOB_COMPONENT.JOB_NUMBER = JOB_TRAFFIC_DET.JOB_NUMBER AND
									JOB_COMPONENT.JOB_COMPONENT_NBR = JOB_TRAFFIC_DET.JOB_COMPONENT_NBR
						 INNER JOIN SEC_CLIENT ON JOB_LOG.CL_CODE = SEC_CLIENT.CL_CODE AND JOB_LOG.DIV_CODE = SEC_CLIENT.DIV_CODE AND JOB_LOG.PRD_CODE = SEC_CLIENT.PRD_CODE
						 INNER JOIN PRODUCT ON JOB_LOG.CL_CODE = PRODUCT.CL_CODE AND JOB_LOG.DIV_CODE = PRODUCT.DIV_CODE AND 
										   JOB_LOG.PRD_CODE = PRODUCT.PRD_CODE 
						 INNER JOIN DIVISION ON PRODUCT.CL_CODE = DIVISION.CL_CODE AND PRODUCT.DIV_CODE = DIVISION.DIV_CODE 
						 INNER JOIN CLIENT ON DIVISION.CL_CODE = CLIENT.CL_CODE  
						 LEFT OUTER JOIN TRAFFIC_FNC ON JOB_TRAFFIC_DET.FNC_CODE = TRAFFIC_FNC.TRF_CODE
						 LEFT OUTER JOIN TASK_TRAFFIC_ROLE ON JOB_TRAFFIC_DET.FNC_CODE = TASK_TRAFFIC_ROLE.TRF_CODE 
						 LEFT OUTER JOIN EMP_TRAFFIC_ROLE ON JOB_TRAFFIC_DET.EMP_CODE = EMP_TRAFFIC_ROLE.EMP_CODE
		WHERE (NOT (JOB_COMPONENT.JOB_PROCESS_CONTRL IN (6, 12))) AND
			  (UPPER(SEC_CLIENT.USER_ID) = UPPER(@UserID)) AND (SEC_CLIENT.TIME_ENTRY = 0 OR SEC_CLIENT.TIME_ENTRY IS NULL) AND
			  (Isnull(JOB_TRAFFIC_DET.EMP_CODE, '') Like '%' + @EmpCode) AND
			   JOB_LOG.CL_CODE Like '%' + @ClientCode AND
			   JOB_LOG.DIV_CODE Like '%' + @DivCode AND
			   JOB_LOG.PRD_CODE Like '%' + @ProdCode AND
			   JOB_LOG.OFFICE_CODE Like '%' + @Office AND
			   ((JOB_TRAFFIC_DET.JOB_REVISED_DATE >= @StartDate AND
			   JOB_TRAFFIC_DET.JOB_REVISED_DATE <= @EndDate) OR (JOB_TRAFFIC_DET.TASK_START_DATE >= @StartDate AND JOB_TRAFFIC_DET.TASK_START_DATE <= @EndDate)
			   OR (@StartDate >= JOB_TRAFFIC_DET.TASK_START_DATE and @EndDate <= JOB_TRAFFIC_DET.JOB_REVISED_DATE)) AND
			   JOB_TRAFFIC_DET.JOB_COMPLETED_DATE IS NULL AND
			  (ISNULL(TASK_TRAFFIC_ROLE.ROLE_CODE, '') Like '%' + @Role OR ISNULL(EMP_TRAFFIC_ROLE.ROLE_CODE, '') Like '%' + @Role) AND
				   ISNULL(JOB_TRAFFIC_DET.TASK_STATUS, '') Like Case @TaskStatus
													When 'P' Then 'P'
																When 'A' Then 'A'
													When '' Then '%'
														End AND
				   JOB_TRAFFIC_DET.TEMP_COMP_DATE IS NULL
		  GROUP BY JOB_LOG.CL_CODE,
			   JOB_LOG.DIV_CODE,
			   JOB_LOG.PRD_CODE,
			   JOB_LOG.JOB_NUMBER,
			   JOB_LOG.JOB_DESC,
			   JOB_COMPONENT.JOB_COMPONENT_NBR,
			   JOB_COMPONENT.JOB_COMP_DESC,
			   STR(DATEPART(day, JOB_TRAFFIC_DET.TASK_START_DATE)),
			   STR(DATEPART(day, JOB_TRAFFIC_DET.JOB_REVISED_DATE)),
			   ISNULL(JOB_TRAFFIC_DET.TASK_DESCRIPTION, '(' + ISNULL(JOB_TRAFFIC_DET.FNC_CODE,'') + ')') ,
			   JOB_TRAFFIC_DET.JOB_REVISED_DATE, 
			   JOB_TRAFFIC_DET.TASK_START_DATE,
			   JOB_TRAFFIC_DET.TEMP_COMP_DATE,
				   JOB_TRAFFIC_DET.TASK_STATUS,
				   JOB_TRAFFIC_DET.SEQ_NBR,
				   CLIENT.CL_NAME, DIVISION.DIV_NAME, PRODUCT.PRD_DESCRIPTION, TRAFFIC_FNC.TRF_CODE, JOB_TRAFFIC_DET.EMP_CODE
		  ORDER BY JOB_TRAFFIC_DET.JOB_REVISED_DATE

	   ELSE
		  SELECT JOB_LOG.CL_CODE as CCode,
				 JOB_LOG.DIV_CODE as DCode,
				 JOB_LOG.PRD_CODE as PCode,
				 JOB_LOG.JOB_NUMBER as JobNum,
				 JOB_LOG.JOB_DESC as JobDesc,
				 JOB_COMPONENT.JOB_COMPONENT_NBR as CompNum,
				 JOB_COMPONENT.JOB_COMP_DESC as CompDesc,
				 STR(DATEPART(day, JOB_TRAFFIC_DET.JOB_REVISED_DATE)) as ThisDay,
				 isnull(JOB_TRAFFIC_DET.TASK_DESCRIPTION, '(' + ISNULL(JOB_TRAFFIC_DET.FNC_CODE,'') + ')') as Task, 
				 isnull(JOB_TRAFFIC_DET.TEMP_COMP_DATE, '1/1/1900') as TempCompDate,
				 JOB_TRAFFIC_DET.TASK_STATUS, STR(DATEPART(day, JOB_TRAFFIC_DET.TASK_START_DATE)) as ThisDayStart, JOB_TRAFFIC_DET.SEQ_NBR,
				 CLIENT.CL_NAME, DIVISION.DIV_NAME, PRODUCT.PRD_DESCRIPTION, TRAFFIC_FNC.TRF_CODE, JOB_TRAFFIC_DET.JOB_REVISED_DATE as RevisedDate, isnull(JOB_TRAFFIC_DET.TASK_START_DATE, '1/1/1900') as StartDate,
				 JOB_TRAFFIC_DET.EMP_CODE as empcodedispl,
				 dbo.udf_get_empl_name( JOB_TRAFFIC_DET.EMP_CODE, 'FML' ) AS empdescdispl
		FROM JOB_LOG INNER JOIN JOB_COMPONENT ON JOB_LOG.JOB_NUMBER = JOB_COMPONENT.JOB_NUMBER
						 INNER JOIN JOB_TRAFFIC_DET ON JOB_COMPONENT.JOB_NUMBER = JOB_TRAFFIC_DET.JOB_NUMBER AND
									JOB_COMPONENT.JOB_COMPONENT_NBR = JOB_TRAFFIC_DET.JOB_COMPONENT_NBR
						 INNER JOIN SEC_CLIENT ON JOB_LOG.CL_CODE = SEC_CLIENT.CL_CODE AND JOB_LOG.DIV_CODE = SEC_CLIENT.DIV_CODE AND JOB_LOG.PRD_CODE = SEC_CLIENT.PRD_CODE
						 INNER JOIN PRODUCT ON JOB_LOG.CL_CODE = PRODUCT.CL_CODE AND JOB_LOG.DIV_CODE = PRODUCT.DIV_CODE AND 
										   JOB_LOG.PRD_CODE = PRODUCT.PRD_CODE 
						 INNER JOIN DIVISION ON PRODUCT.CL_CODE = DIVISION.CL_CODE AND PRODUCT.DIV_CODE = DIVISION.DIV_CODE 
						 INNER JOIN CLIENT ON DIVISION.CL_CODE = CLIENT.CL_CODE 
						 LEFT OUTER JOIN TRAFFIC_FNC ON JOB_TRAFFIC_DET.FNC_CODE = TRAFFIC_FNC.TRF_CODE
						 LEFT OUTER JOIN TASK_TRAFFIC_ROLE ON JOB_TRAFFIC_DET.FNC_CODE = TASK_TRAFFIC_ROLE.TRF_CODE 
						 LEFT OUTER JOIN EMP_TRAFFIC_ROLE ON JOB_TRAFFIC_DET.EMP_CODE = EMP_TRAFFIC_ROLE.EMP_CODE
		WHERE (NOT (JOB_COMPONENT.JOB_PROCESS_CONTRL IN (6, 12))) AND
			  (UPPER(SEC_CLIENT.USER_ID) = UPPER(@UserID)) AND (SEC_CLIENT.TIME_ENTRY = 0 OR SEC_CLIENT.TIME_ENTRY IS NULL) AND
			  (Isnull(JOB_TRAFFIC_DET.EMP_CODE, '') Like '%' + @EmpCode) AND
			   JOB_LOG.CL_CODE Like '%' + @ClientCode AND
			   JOB_LOG.DIV_CODE Like '%' + @DivCode AND
			   JOB_LOG.PRD_CODE Like '%' + @ProdCode AND
			   JOB_LOG.OFFICE_CODE Like '%' + @Office AND
			   ((JOB_TRAFFIC_DET.JOB_REVISED_DATE >= @StartDate AND
			   JOB_TRAFFIC_DET.JOB_REVISED_DATE <= @EndDate) OR (JOB_TRAFFIC_DET.TASK_START_DATE >= @StartDate AND JOB_TRAFFIC_DET.TASK_START_DATE <= @EndDate)
			   OR (@StartDate >= JOB_TRAFFIC_DET.TASK_START_DATE and @EndDate <= JOB_TRAFFIC_DET.JOB_REVISED_DATE)) AND
			   JOB_TRAFFIC_DET.JOB_COMPLETED_DATE IS NULL AND
			  (ISNULL(TASK_TRAFFIC_ROLE.ROLE_CODE, '') Like '%' + @Role OR ISNULL(EMP_TRAFFIC_ROLE.ROLE_CODE, '') Like '%' + @Role) AND
				   ISNULL(JOB_TRAFFIC_DET.TASK_STATUS, '') Like Case @TaskStatus
													When 'P' Then 'P'
																When 'A' Then 'A'
													When '' Then '%'
														End
		  GROUP BY JOB_LOG.CL_CODE,
			   JOB_LOG.DIV_CODE,
			   JOB_LOG.PRD_CODE,
			   JOB_LOG.JOB_NUMBER,
			   JOB_LOG.JOB_DESC,
			   JOB_COMPONENT.JOB_COMPONENT_NBR,
			   JOB_COMPONENT.JOB_COMP_DESC,
			   STR(DATEPART(day, JOB_TRAFFIC_DET.TASK_START_DATE)),
			   STR(DATEPART(day, JOB_TRAFFIC_DET.JOB_REVISED_DATE)),
			   ISNULL(JOB_TRAFFIC_DET.TASK_DESCRIPTION, '(' + ISNULL(JOB_TRAFFIC_DET.FNC_CODE,'') + ')') ,
			   JOB_TRAFFIC_DET.JOB_REVISED_DATE, 
			   JOB_TRAFFIC_DET.TASK_START_DATE,
			   JOB_TRAFFIC_DET.TEMP_COMP_DATE,
				   JOB_TRAFFIC_DET.TASK_STATUS,
				   JOB_TRAFFIC_DET.SEQ_NBR,
				   CLIENT.CL_NAME, DIVISION.DIV_NAME, PRODUCT.PRD_DESCRIPTION, TRAFFIC_FNC.TRF_CODE, JOB_TRAFFIC_DET.EMP_CODE
		  ORDER BY JOB_TRAFFIC_DET.JOB_REVISED_DATE

	If @Rescrictions = 0 and @RescrictionsEmp = 0
	   IF @ExcludeTempComplete = 'Y'
				SELECT JOB_LOG.CL_CODE as CCode,
			 JOB_LOG.DIV_CODE as DCode,
			 JOB_LOG.PRD_CODE as PCode,
			 JOB_LOG.JOB_NUMBER as JobNum,
			 JOB_LOG.JOB_DESC as JobDesc,
			 JOB_COMPONENT.JOB_COMPONENT_NBR as CompNum,
			 JOB_COMPONENT.JOB_COMP_DESC as CompDesc,
			 STR(DATEPART(day, JOB_TRAFFIC_DET.JOB_REVISED_DATE)) as ThisDay,
			 -- JOB_TRAFFIC_DET.TASK_DESCRIPTION + '(' + JOB_TRAFFIC_DET.FNC_CODE + ')' as Task
			 isnull(JOB_TRAFFIC_DET.TASK_DESCRIPTION, '(' + ISNULL(JOB_TRAFFIC_DET.FNC_CODE,'') + ')') as Task,
			 isnull(JOB_TRAFFIC_DET.TEMP_COMP_DATE, '1/1/1900') as TempCompDate,
				 JOB_TRAFFIC_DET.TASK_STATUS, STR(DATEPART(day, JOB_TRAFFIC_DET.TASK_START_DATE)) as ThisDayStart, JOB_TRAFFIC_DET.SEQ_NBR,
				 CLIENT.CL_NAME, DIVISION.DIV_NAME, PRODUCT.PRD_DESCRIPTION, TRAFFIC_FNC.TRF_CODE, JOB_TRAFFIC_DET.JOB_REVISED_DATE as RevisedDate, isnull(JOB_TRAFFIC_DET.TASK_START_DATE, '1/1/1900') as StartDate,
				 JOB_TRAFFIC_DET.EMP_CODE as empcodedispl,
				 dbo.udf_get_empl_name( JOB_TRAFFIC_DET.EMP_CODE, 'FML' ) AS empdescdispl
		FROM JOB_LOG INNER JOIN JOB_COMPONENT ON JOB_LOG.JOB_NUMBER = JOB_COMPONENT.JOB_NUMBER
					 INNER JOIN JOB_TRAFFIC_DET ON JOB_COMPONENT.JOB_NUMBER = JOB_TRAFFIC_DET.JOB_NUMBER AND
												   JOB_COMPONENT.JOB_COMPONENT_NBR = JOB_TRAFFIC_DET.JOB_COMPONENT_NBR
					 INNER JOIN PRODUCT ON JOB_LOG.CL_CODE = PRODUCT.CL_CODE AND JOB_LOG.DIV_CODE = PRODUCT.DIV_CODE AND 
										   JOB_LOG.PRD_CODE = PRODUCT.PRD_CODE 
					 INNER JOIN DIVISION ON PRODUCT.CL_CODE = DIVISION.CL_CODE AND PRODUCT.DIV_CODE = DIVISION.DIV_CODE 
					 INNER JOIN CLIENT ON DIVISION.CL_CODE = CLIENT.CL_CODE 
					 LEFT OUTER JOIN TRAFFIC_FNC ON JOB_TRAFFIC_DET.FNC_CODE = TRAFFIC_FNC.TRF_CODE                               
					 LEFT OUTER JOIN TASK_TRAFFIC_ROLE ON JOB_TRAFFIC_DET.FNC_CODE = TASK_TRAFFIC_ROLE.TRF_CODE 
					 LEFT OUTER JOIN EMP_TRAFFIC_ROLE ON JOB_TRAFFIC_DET.EMP_CODE = EMP_TRAFFIC_ROLE.EMP_CODE
		WHERE (NOT (JOB_COMPONENT.JOB_PROCESS_CONTRL IN (6, 12))) AND
			  (isnull(JOB_TRAFFIC_DET.EMP_CODE, '') Like '%' + @EmpCode) AND
			  JOB_LOG.CL_CODE Like '%' + @ClientCode AND
			  JOB_LOG.DIV_CODE Like '%' + @DivCode AND
			  JOB_LOG.PRD_CODE Like '%' + @ProdCode AND
			  JOB_LOG.OFFICE_CODE Like '%' + @Office AND
			  ((JOB_TRAFFIC_DET.JOB_REVISED_DATE >= @StartDate AND
			   JOB_TRAFFIC_DET.JOB_REVISED_DATE <= @EndDate) OR (JOB_TRAFFIC_DET.TASK_START_DATE >= @StartDate AND JOB_TRAFFIC_DET.TASK_START_DATE <= @EndDate)
			   OR (@StartDate >= JOB_TRAFFIC_DET.TASK_START_DATE and @EndDate <= JOB_TRAFFIC_DET.JOB_REVISED_DATE)) AND
			  JOB_TRAFFIC_DET.JOB_COMPLETED_DATE IS NULL AND
			  (ISNULL(TASK_TRAFFIC_ROLE.ROLE_CODE, '') Like '%' + @Role OR ISNULL(EMP_TRAFFIC_ROLE.ROLE_CODE, '') Like '%' + @Role) AND
			   ISNULL(JOB_TRAFFIC_DET.TASK_STATUS, '') Like Case @TaskStatus
													When 'P' Then 'P'
																When 'A' Then 'A'
														When '' Then '%'
														End AND
				 JOB_TRAFFIC_DET.TEMP_COMP_DATE IS NULL
		GROUP BY JOB_LOG.CL_CODE,
			 JOB_LOG.DIV_CODE,
			 JOB_LOG.PRD_CODE,
			 JOB_LOG.JOB_NUMBER,
			 JOB_LOG.JOB_DESC,
			 JOB_COMPONENT.JOB_COMPONENT_NBR,
			 JOB_COMPONENT.JOB_COMP_DESC,
			 STR(DATEPART(day, JOB_TRAFFIC_DET.TASK_START_DATE)),
			 STR(DATEPART(day, JOB_TRAFFIC_DET.JOB_REVISED_DATE)),
			 isnull(JOB_TRAFFIC_DET.TASK_DESCRIPTION, '(' + ISNULL(JOB_TRAFFIC_DET.FNC_CODE,'') + ')') ,
			 JOB_TRAFFIC_DET.JOB_REVISED_DATE,
			 JOB_TRAFFIC_DET.TASK_START_DATE,
			 JOB_TRAFFIC_DET.TEMP_COMP_DATE,
				 JOB_TRAFFIC_DET.TASK_STATUS,
				 JOB_TRAFFIC_DET.SEQ_NBR,
				 CLIENT.CL_NAME, DIVISION.DIV_NAME, PRODUCT.PRD_DESCRIPTION, TRAFFIC_FNC.TRF_CODE, JOB_TRAFFIC_DET.EMP_CODE
		ORDER BY JOB_TRAFFIC_DET.JOB_REVISED_DATE
	   ELSE

		  SELECT JOB_LOG.CL_CODE as CCode,
			 JOB_LOG.DIV_CODE as DCode,
			 JOB_LOG.PRD_CODE as PCode,
			 JOB_LOG.JOB_NUMBER as JobNum,
			 JOB_LOG.JOB_DESC as JobDesc,
			 JOB_COMPONENT.JOB_COMPONENT_NBR as CompNum,
			 JOB_COMPONENT.JOB_COMP_DESC as CompDesc,
			 STR(DATEPART(day, JOB_TRAFFIC_DET.JOB_REVISED_DATE)) as ThisDay,
			 -- JOB_TRAFFIC_DET.TASK_DESCRIPTION + '(' + JOB_TRAFFIC_DET.FNC_CODE + ')' as Task
			 isnull(JOB_TRAFFIC_DET.TASK_DESCRIPTION, '(' + ISNULL(JOB_TRAFFIC_DET.FNC_CODE,'') + ')') as Task,
			 isnull(JOB_TRAFFIC_DET.TEMP_COMP_DATE, '1/1/1900') as TempCompDate,
				 JOB_TRAFFIC_DET.TASK_STATUS, STR(DATEPART(day, JOB_TRAFFIC_DET.TASK_START_DATE)) as ThisDayStart, JOB_TRAFFIC_DET.SEQ_NBR,
				 CLIENT.CL_NAME, DIVISION.DIV_NAME, PRODUCT.PRD_DESCRIPTION, TRAFFIC_FNC.TRF_CODE, JOB_TRAFFIC_DET.JOB_REVISED_DATE as RevisedDate, isnull(JOB_TRAFFIC_DET.TASK_START_DATE, '1/1/1900') as StartDate,
				 JOB_TRAFFIC_DET.EMP_CODE as empcodedispl,
				 dbo.udf_get_empl_name( JOB_TRAFFIC_DET.EMP_CODE, 'FML' ) AS empdescdispl
		FROM JOB_LOG INNER JOIN JOB_COMPONENT ON JOB_LOG.JOB_NUMBER = JOB_COMPONENT.JOB_NUMBER
					 INNER JOIN JOB_TRAFFIC_DET ON JOB_COMPONENT.JOB_NUMBER = JOB_TRAFFIC_DET.JOB_NUMBER AND
												   JOB_COMPONENT.JOB_COMPONENT_NBR = JOB_TRAFFIC_DET.JOB_COMPONENT_NBR
					 INNER JOIN PRODUCT ON JOB_LOG.CL_CODE = PRODUCT.CL_CODE AND JOB_LOG.DIV_CODE = PRODUCT.DIV_CODE AND 
										   JOB_LOG.PRD_CODE = PRODUCT.PRD_CODE 
					 INNER JOIN DIVISION ON PRODUCT.CL_CODE = DIVISION.CL_CODE AND PRODUCT.DIV_CODE = DIVISION.DIV_CODE 
					 INNER JOIN CLIENT ON DIVISION.CL_CODE = CLIENT.CL_CODE  
					 LEFT OUTER JOIN TRAFFIC_FNC ON JOB_TRAFFIC_DET.FNC_CODE = TRAFFIC_FNC.TRF_CODE                            
					 LEFT OUTER JOIN TASK_TRAFFIC_ROLE ON JOB_TRAFFIC_DET.FNC_CODE = TASK_TRAFFIC_ROLE.TRF_CODE 
					 LEFT OUTER JOIN EMP_TRAFFIC_ROLE ON JOB_TRAFFIC_DET.EMP_CODE = EMP_TRAFFIC_ROLE.EMP_CODE
		WHERE (NOT (JOB_COMPONENT.JOB_PROCESS_CONTRL IN (6, 12))) AND
			  (isnull(JOB_TRAFFIC_DET.EMP_CODE, '') Like '%' + @EmpCode) AND
			  JOB_LOG.CL_CODE Like '%' + @ClientCode AND
			  JOB_LOG.DIV_CODE Like '%' + @DivCode AND
			  JOB_LOG.PRD_CODE Like '%' + @ProdCode AND
			  JOB_LOG.OFFICE_CODE Like '%' + @Office AND
			  ((JOB_TRAFFIC_DET.JOB_REVISED_DATE >= @StartDate AND
			   JOB_TRAFFIC_DET.JOB_REVISED_DATE <= @EndDate) OR (JOB_TRAFFIC_DET.TASK_START_DATE >= @StartDate AND JOB_TRAFFIC_DET.TASK_START_DATE <= @EndDate)
			   OR (@StartDate >= JOB_TRAFFIC_DET.TASK_START_DATE and @EndDate <= JOB_TRAFFIC_DET.JOB_REVISED_DATE)) AND
			  JOB_TRAFFIC_DET.JOB_COMPLETED_DATE IS NULL AND
			  (ISNULL(TASK_TRAFFIC_ROLE.ROLE_CODE, '') Like '%' + @Role OR ISNULL(EMP_TRAFFIC_ROLE.ROLE_CODE, '') Like '%' + @Role) AND
			   ISNULL(JOB_TRAFFIC_DET.TASK_STATUS, '') Like Case @TaskStatus
													When 'P' Then 'P'
																When 'A' Then 'A'
														When '' Then '%'
														End
		GROUP BY JOB_LOG.CL_CODE,

			 JOB_LOG.DIV_CODE,
			 JOB_LOG.PRD_CODE,
			 JOB_LOG.JOB_NUMBER,
			 JOB_LOG.JOB_DESC,
			 JOB_COMPONENT.JOB_COMPONENT_NBR,
			 JOB_COMPONENT.JOB_COMP_DESC,
			 STR(DATEPART(day, JOB_TRAFFIC_DET.TASK_START_DATE)),
			 STR(DATEPART(day, JOB_TRAFFIC_DET.JOB_REVISED_DATE)),
			 isnull(JOB_TRAFFIC_DET.TASK_DESCRIPTION, '(' + ISNULL(JOB_TRAFFIC_DET.FNC_CODE,'') + ')') ,
			 JOB_TRAFFIC_DET.JOB_REVISED_DATE,
			 JOB_TRAFFIC_DET.TASK_START_DATE,
			 JOB_TRAFFIC_DET.TEMP_COMP_DATE,
				 JOB_TRAFFIC_DET.TASK_STATUS,
				 JOB_TRAFFIC_DET.SEQ_NBR,
				 CLIENT.CL_NAME, DIVISION.DIV_NAME, PRODUCT.PRD_DESCRIPTION, TRAFFIC_FNC.TRF_CODE, JOB_TRAFFIC_DET.EMP_CODE
		ORDER BY JOB_TRAFFIC_DET.JOB_REVISED_DATE
End
Else
Begin
	If @Rescrictions > 0 and @RescrictionsEmp > 0
	   If @ExcludeTempComplete = 'Y'
				SELECT JOB_LOG.CL_CODE as CCode,
				 JOB_LOG.DIV_CODE as DCode,
				 JOB_LOG.PRD_CODE as PCode,
				 JOB_LOG.JOB_NUMBER as JobNum,
				 JOB_LOG.JOB_DESC as JobDesc,
				 JOB_COMPONENT.JOB_COMPONENT_NBR as CompNum,
				 JOB_COMPONENT.JOB_COMP_DESC as CompDesc,
				 STR(DATEPART(day, JOB_TRAFFIC_DET.JOB_REVISED_DATE)) as ThisDay,
				 isnull(JOB_TRAFFIC_DET.TASK_DESCRIPTION, '(' + ISNULL(JOB_TRAFFIC_DET.FNC_CODE,'') + ')') as Task, 
				 isnull(JOB_TRAFFIC_DET.TEMP_COMP_DATE, '1/1/1900') as TempCompDate,
				 JOB_TRAFFIC_DET.TASK_STATUS, STR(DATEPART(day, JOB_TRAFFIC_DET.TASK_START_DATE)) as ThisDayStart, JOB_TRAFFIC_DET.SEQ_NBR,
				 CLIENT.CL_NAME, DIVISION.DIV_NAME, PRODUCT.PRD_DESCRIPTION, TRAFFIC_FNC.TRF_CODE, JOB_TRAFFIC_DET.JOB_REVISED_DATE as RevisedDate, isnull(JOB_TRAFFIC_DET.TASK_START_DATE, '1/1/1900') as StartDate,
				 JOB_TRAFFIC_DET.EMP_CODE as empcodedispl,
				 dbo.udf_get_empl_name( JOB_TRAFFIC_DET.EMP_CODE, 'FML' ) AS empdescdispl
		FROM JOB_LOG INNER JOIN JOB_COMPONENT ON JOB_LOG.JOB_NUMBER = JOB_COMPONENT.JOB_NUMBER
						 INNER JOIN JOB_TRAFFIC_DET ON JOB_COMPONENT.JOB_NUMBER = JOB_TRAFFIC_DET.JOB_NUMBER AND
									JOB_COMPONENT.JOB_COMPONENT_NBR = JOB_TRAFFIC_DET.JOB_COMPONENT_NBR
						 INNER JOIN SEC_CLIENT ON JOB_LOG.CL_CODE = SEC_CLIENT.CL_CODE AND JOB_LOG.DIV_CODE = SEC_CLIENT.DIV_CODE AND JOB_LOG.PRD_CODE = SEC_CLIENT.PRD_CODE
						 INNER JOIN PRODUCT ON JOB_LOG.CL_CODE = PRODUCT.CL_CODE AND JOB_LOG.DIV_CODE = PRODUCT.DIV_CODE AND 
										   JOB_LOG.PRD_CODE = PRODUCT.PRD_CODE 
						 INNER JOIN DIVISION ON PRODUCT.CL_CODE = DIVISION.CL_CODE AND PRODUCT.DIV_CODE = DIVISION.DIV_CODE 
						 INNER JOIN CLIENT ON DIVISION.CL_CODE = CLIENT.CL_CODE
						 LEFT OUTER JOIN TRAFFIC_FNC ON JOB_TRAFFIC_DET.FNC_CODE = TRAFFIC_FNC.TRF_CODE
						 INNER JOIN [dbo].[advtf_sec_emp] (@UserID) AS SEC_EMP ON JOB_TRAFFIC_DET.EMP_CODE = SEC_EMP.EMP_CODE
						 LEFT OUTER JOIN TASK_TRAFFIC_ROLE ON JOB_TRAFFIC_DET.FNC_CODE = TASK_TRAFFIC_ROLE.TRF_CODE 
						 LEFT OUTER JOIN EMP_TRAFFIC_ROLE ON JOB_TRAFFIC_DET.EMP_CODE = EMP_TRAFFIC_ROLE.EMP_CODE
		WHERE (NOT (JOB_COMPONENT.JOB_PROCESS_CONTRL IN (6, 12))) AND
			  (UPPER(SEC_CLIENT.USER_ID) = UPPER(@UserID)) AND (SEC_CLIENT.TIME_ENTRY = 0 OR SEC_CLIENT.TIME_ENTRY IS NULL) AND
			  (Isnull(JOB_TRAFFIC_DET.EMP_CODE, '') Like '%' + @EmpCode) AND
			   JOB_LOG.CL_CODE Like '%' + @ClientCode AND
			   JOB_LOG.DIV_CODE Like '%' + @DivCode AND
			   JOB_LOG.PRD_CODE Like '%' + @ProdCode AND
			   JOB_LOG.OFFICE_CODE Like '%' + @Office AND
			   ((JOB_TRAFFIC_DET.JOB_REVISED_DATE >= @StartDate AND
			   JOB_TRAFFIC_DET.JOB_REVISED_DATE <= @EndDate) OR (JOB_TRAFFIC_DET.TASK_START_DATE >= @StartDate AND JOB_TRAFFIC_DET.TASK_START_DATE <= @EndDate)
			   OR (@StartDate >= JOB_TRAFFIC_DET.TASK_START_DATE and @EndDate <= JOB_TRAFFIC_DET.JOB_REVISED_DATE)) AND
			   JOB_TRAFFIC_DET.JOB_COMPLETED_DATE IS NULL AND
			   JOB_TRAFFIC_DET.MILESTONE = 1 AND
			  (ISNULL(TASK_TRAFFIC_ROLE.ROLE_CODE, '') Like '%' + @Role OR ISNULL(EMP_TRAFFIC_ROLE.ROLE_CODE, '') Like '%' + @Role) AND
				   ISNULL(JOB_TRAFFIC_DET.TASK_STATUS, '') Like Case @TaskStatus
													When 'P' Then 'P'
																When 'A' Then 'A'
													When '' Then '%'
														End AND
				   JOB_TRAFFIC_DET.TEMP_COMP_DATE IS NULL
		  GROUP BY JOB_LOG.CL_CODE,
			   JOB_LOG.DIV_CODE,
			   JOB_LOG.PRD_CODE,
			   JOB_LOG.JOB_NUMBER,
			   JOB_LOG.JOB_DESC,
			   JOB_COMPONENT.JOB_COMPONENT_NBR,
			   JOB_COMPONENT.JOB_COMP_DESC,
			   STR(DATEPART(day, JOB_TRAFFIC_DET.TASK_START_DATE)),
			   STR(DATEPART(day, JOB_TRAFFIC_DET.JOB_REVISED_DATE)),
			   ISNULL(JOB_TRAFFIC_DET.TASK_DESCRIPTION, '(' + ISNULL(JOB_TRAFFIC_DET.FNC_CODE,'') + ')') ,
			   JOB_TRAFFIC_DET.JOB_REVISED_DATE, 
			   JOB_TRAFFIC_DET.TASK_START_DATE,
			   JOB_TRAFFIC_DET.TEMP_COMP_DATE,
				   JOB_TRAFFIC_DET.TASK_STATUS,
				   JOB_TRAFFIC_DET.SEQ_NBR,
				   CLIENT.CL_NAME, DIVISION.DIV_NAME, PRODUCT.PRD_DESCRIPTION, TRAFFIC_FNC.TRF_CODE, JOB_TRAFFIC_DET.EMP_CODE
		  ORDER BY JOB_TRAFFIC_DET.JOB_REVISED_DATE

	   ELSE
		  SELECT JOB_LOG.CL_CODE as CCode,
				 JOB_LOG.DIV_CODE as DCode,
				 JOB_LOG.PRD_CODE as PCode,
				 JOB_LOG.JOB_NUMBER as JobNum,
				 JOB_LOG.JOB_DESC as JobDesc,
				 JOB_COMPONENT.JOB_COMPONENT_NBR as CompNum,
				 JOB_COMPONENT.JOB_COMP_DESC as CompDesc,
				 STR(DATEPART(day, JOB_TRAFFIC_DET.JOB_REVISED_DATE)) as ThisDay,
				 isnull(JOB_TRAFFIC_DET.TASK_DESCRIPTION, '(' + ISNULL(JOB_TRAFFIC_DET.FNC_CODE,'') + ')') as Task, 
				 isnull(JOB_TRAFFIC_DET.TEMP_COMP_DATE, '1/1/1900') as TempCompDate,
				 JOB_TRAFFIC_DET.TASK_STATUS, STR(DATEPART(day, JOB_TRAFFIC_DET.TASK_START_DATE)) as ThisDayStart, JOB_TRAFFIC_DET.SEQ_NBR,
				 CLIENT.CL_NAME, DIVISION.DIV_NAME, PRODUCT.PRD_DESCRIPTION, TRAFFIC_FNC.TRF_CODE, JOB_TRAFFIC_DET.JOB_REVISED_DATE as RevisedDate, isnull(JOB_TRAFFIC_DET.TASK_START_DATE, '1/1/1900') as StartDate,
				 JOB_TRAFFIC_DET.EMP_CODE as empcodedispl,
				 dbo.udf_get_empl_name( JOB_TRAFFIC_DET.EMP_CODE, 'FML' ) AS empdescdispl
		FROM JOB_LOG INNER JOIN JOB_COMPONENT ON JOB_LOG.JOB_NUMBER = JOB_COMPONENT.JOB_NUMBER
						 INNER JOIN JOB_TRAFFIC_DET ON JOB_COMPONENT.JOB_NUMBER = JOB_TRAFFIC_DET.JOB_NUMBER AND
									JOB_COMPONENT.JOB_COMPONENT_NBR = JOB_TRAFFIC_DET.JOB_COMPONENT_NBR
						 INNER JOIN SEC_CLIENT ON JOB_LOG.CL_CODE = SEC_CLIENT.CL_CODE AND JOB_LOG.DIV_CODE = SEC_CLIENT.DIV_CODE AND JOB_LOG.PRD_CODE = SEC_CLIENT.PRD_CODE
						 INNER JOIN PRODUCT ON JOB_LOG.CL_CODE = PRODUCT.CL_CODE AND JOB_LOG.DIV_CODE = PRODUCT.DIV_CODE AND 
										   JOB_LOG.PRD_CODE = PRODUCT.PRD_CODE 
						 INNER JOIN DIVISION ON PRODUCT.CL_CODE = DIVISION.CL_CODE AND PRODUCT.DIV_CODE = DIVISION.DIV_CODE 
						 INNER JOIN CLIENT ON DIVISION.CL_CODE = CLIENT.CL_CODE
						 LEFT OUTER JOIN TRAFFIC_FNC ON JOB_TRAFFIC_DET.FNC_CODE = TRAFFIC_FNC.TRF_CODE
						 INNER JOIN [dbo].[advtf_sec_emp] (@UserID) AS SEC_EMP ON JOB_TRAFFIC_DET.EMP_CODE = SEC_EMP.EMP_CODE
						 LEFT OUTER JOIN TASK_TRAFFIC_ROLE ON JOB_TRAFFIC_DET.FNC_CODE = TASK_TRAFFIC_ROLE.TRF_CODE 
						 LEFT OUTER JOIN EMP_TRAFFIC_ROLE ON JOB_TRAFFIC_DET.EMP_CODE = EMP_TRAFFIC_ROLE.EMP_CODE
		WHERE (NOT (JOB_COMPONENT.JOB_PROCESS_CONTRL IN (6, 12))) AND
			  (UPPER(SEC_CLIENT.USER_ID) = UPPER(@UserID)) AND (SEC_CLIENT.TIME_ENTRY = 0 OR SEC_CLIENT.TIME_ENTRY IS NULL) AND
			  (Isnull(JOB_TRAFFIC_DET.EMP_CODE, '') Like '%' + @EmpCode) AND
			   JOB_LOG.CL_CODE Like '%' + @ClientCode AND
			   JOB_LOG.DIV_CODE Like '%' + @DivCode AND
			   JOB_LOG.PRD_CODE Like '%' + @ProdCode AND
			   JOB_LOG.OFFICE_CODE Like '%' + @Office AND
			   ((JOB_TRAFFIC_DET.JOB_REVISED_DATE >= @StartDate AND
			   JOB_TRAFFIC_DET.JOB_REVISED_DATE <= @EndDate) OR (JOB_TRAFFIC_DET.TASK_START_DATE >= @StartDate AND JOB_TRAFFIC_DET.TASK_START_DATE <= @EndDate)
			   OR (@StartDate >= JOB_TRAFFIC_DET.TASK_START_DATE and @EndDate <= JOB_TRAFFIC_DET.JOB_REVISED_DATE)) AND
			   JOB_TRAFFIC_DET.JOB_COMPLETED_DATE IS NULL AND
			   JOB_TRAFFIC_DET.MILESTONE = 1 AND
			  (ISNULL(TASK_TRAFFIC_ROLE.ROLE_CODE, '') Like '%' + @Role OR ISNULL(EMP_TRAFFIC_ROLE.ROLE_CODE, '') Like '%' + @Role) AND
				   ISNULL(JOB_TRAFFIC_DET.TASK_STATUS, '') Like Case @TaskStatus
													When 'P' Then 'P'
																When 'A' Then 'A'
													When '' Then '%'
														End
		  GROUP BY JOB_LOG.CL_CODE,
			   JOB_LOG.DIV_CODE,
			   JOB_LOG.PRD_CODE,
			   JOB_LOG.JOB_NUMBER,
			   JOB_LOG.JOB_DESC,
			   JOB_COMPONENT.JOB_COMPONENT_NBR,
			   JOB_COMPONENT.JOB_COMP_DESC,
			   STR(DATEPART(day, JOB_TRAFFIC_DET.TASK_START_DATE)),
			   STR(DATEPART(day, JOB_TRAFFIC_DET.JOB_REVISED_DATE)),
			   ISNULL(JOB_TRAFFIC_DET.TASK_DESCRIPTION, '(' + ISNULL(JOB_TRAFFIC_DET.FNC_CODE,'') + ')') ,
			   JOB_TRAFFIC_DET.JOB_REVISED_DATE, 
			   JOB_TRAFFIC_DET.TASK_START_DATE,
			   JOB_TRAFFIC_DET.TEMP_COMP_DATE,
				   JOB_TRAFFIC_DET.TASK_STATUS,
				   JOB_TRAFFIC_DET.SEQ_NBR,
				   CLIENT.CL_NAME, DIVISION.DIV_NAME, PRODUCT.PRD_DESCRIPTION, TRAFFIC_FNC.TRF_CODE, JOB_TRAFFIC_DET.EMP_CODE
		  ORDER BY JOB_TRAFFIC_DET.JOB_REVISED_DATE
	      
	If @Rescrictions = 0 and @RescrictionsEmp > 0
	   If @ExcludeTempComplete = 'Y'
				SELECT JOB_LOG.CL_CODE as CCode,
				 JOB_LOG.DIV_CODE as DCode,
				 JOB_LOG.PRD_CODE as PCode,
				 JOB_LOG.JOB_NUMBER as JobNum,
				 JOB_LOG.JOB_DESC as JobDesc,
				 JOB_COMPONENT.JOB_COMPONENT_NBR as CompNum,
				 JOB_COMPONENT.JOB_COMP_DESC as CompDesc,
				 STR(DATEPART(day, JOB_TRAFFIC_DET.JOB_REVISED_DATE)) as ThisDay,
				 isnull(JOB_TRAFFIC_DET.TASK_DESCRIPTION, '(' + ISNULL(JOB_TRAFFIC_DET.FNC_CODE,'') + ')') as Task, 
				 isnull(JOB_TRAFFIC_DET.TEMP_COMP_DATE, '1/1/1900') as TempCompDate,
				 JOB_TRAFFIC_DET.TASK_STATUS, STR(DATEPART(day, JOB_TRAFFIC_DET.TASK_START_DATE)) as ThisDayStart, JOB_TRAFFIC_DET.SEQ_NBR,
				 CLIENT.CL_NAME, DIVISION.DIV_NAME, PRODUCT.PRD_DESCRIPTION, TRAFFIC_FNC.TRF_CODE, JOB_TRAFFIC_DET.JOB_REVISED_DATE as RevisedDate, isnull(JOB_TRAFFIC_DET.TASK_START_DATE, '1/1/1900') as StartDate,
				 JOB_TRAFFIC_DET.EMP_CODE as empcodedispl,
				 dbo.udf_get_empl_name( JOB_TRAFFIC_DET.EMP_CODE, 'FML' ) AS empdescdispl
		FROM JOB_LOG INNER JOIN JOB_COMPONENT ON JOB_LOG.JOB_NUMBER = JOB_COMPONENT.JOB_NUMBER
						 INNER JOIN JOB_TRAFFIC_DET ON JOB_COMPONENT.JOB_NUMBER = JOB_TRAFFIC_DET.JOB_NUMBER AND
									JOB_COMPONENT.JOB_COMPONENT_NBR = JOB_TRAFFIC_DET.JOB_COMPONENT_NBR
						 INNER JOIN PRODUCT ON JOB_LOG.CL_CODE = PRODUCT.CL_CODE AND JOB_LOG.DIV_CODE = PRODUCT.DIV_CODE AND 
										   JOB_LOG.PRD_CODE = PRODUCT.PRD_CODE 
						 INNER JOIN DIVISION ON PRODUCT.CL_CODE = DIVISION.CL_CODE AND PRODUCT.DIV_CODE = DIVISION.DIV_CODE 
						 INNER JOIN CLIENT ON DIVISION.CL_CODE = CLIENT.CL_CODE  
						 LEFT OUTER JOIN TRAFFIC_FNC ON JOB_TRAFFIC_DET.FNC_CODE = TRAFFIC_FNC.TRF_CODE
						 INNER JOIN [dbo].[advtf_sec_emp] (@UserID) AS SEC_EMP ON JOB_TRAFFIC_DET.EMP_CODE = SEC_EMP.EMP_CODE
						 LEFT OUTER JOIN TASK_TRAFFIC_ROLE ON JOB_TRAFFIC_DET.FNC_CODE = TASK_TRAFFIC_ROLE.TRF_CODE 
						 LEFT OUTER JOIN EMP_TRAFFIC_ROLE ON JOB_TRAFFIC_DET.EMP_CODE = EMP_TRAFFIC_ROLE.EMP_CODE
		WHERE (NOT (JOB_COMPONENT.JOB_PROCESS_CONTRL IN (6, 12))) AND
			  (Isnull(JOB_TRAFFIC_DET.EMP_CODE, '') Like '%' + @EmpCode) AND
			   JOB_LOG.CL_CODE Like '%' + @ClientCode AND
			   JOB_LOG.DIV_CODE Like '%' + @DivCode AND
			   JOB_LOG.PRD_CODE Like '%' + @ProdCode AND
			   JOB_LOG.OFFICE_CODE Like '%' + @Office AND
			   ((JOB_TRAFFIC_DET.JOB_REVISED_DATE >= @StartDate AND
			   JOB_TRAFFIC_DET.JOB_REVISED_DATE <= @EndDate) OR (JOB_TRAFFIC_DET.TASK_START_DATE >= @StartDate AND JOB_TRAFFIC_DET.TASK_START_DATE <= @EndDate)
			   OR (@StartDate >= JOB_TRAFFIC_DET.TASK_START_DATE and @EndDate <= JOB_TRAFFIC_DET.JOB_REVISED_DATE)) AND
			   JOB_TRAFFIC_DET.JOB_COMPLETED_DATE IS NULL AND
			   JOB_TRAFFIC_DET.MILESTONE = 1 AND
			  (ISNULL(TASK_TRAFFIC_ROLE.ROLE_CODE, '') Like '%' + @Role OR ISNULL(EMP_TRAFFIC_ROLE.ROLE_CODE, '') Like '%' + @Role) AND
				   ISNULL(JOB_TRAFFIC_DET.TASK_STATUS, '') Like Case @TaskStatus
													When 'P' Then 'P'
																When 'A' Then 'A'
													When '' Then '%'
														End AND
				   JOB_TRAFFIC_DET.TEMP_COMP_DATE IS NULL
		  GROUP BY JOB_LOG.CL_CODE,
			   JOB_LOG.DIV_CODE,
			   JOB_LOG.PRD_CODE,
			   JOB_LOG.JOB_NUMBER,
			   JOB_LOG.JOB_DESC,
			   JOB_COMPONENT.JOB_COMPONENT_NBR,
			   JOB_COMPONENT.JOB_COMP_DESC,
			   STR(DATEPART(day, JOB_TRAFFIC_DET.TASK_START_DATE)),
			   STR(DATEPART(day, JOB_TRAFFIC_DET.JOB_REVISED_DATE)),
			   ISNULL(JOB_TRAFFIC_DET.TASK_DESCRIPTION, '(' + ISNULL(JOB_TRAFFIC_DET.FNC_CODE,'') + ')') ,
			   JOB_TRAFFIC_DET.JOB_REVISED_DATE, 
			   JOB_TRAFFIC_DET.TASK_START_DATE,
			   JOB_TRAFFIC_DET.TEMP_COMP_DATE,
				   JOB_TRAFFIC_DET.TASK_STATUS,
				   JOB_TRAFFIC_DET.SEQ_NBR,
				   CLIENT.CL_NAME, DIVISION.DIV_NAME, PRODUCT.PRD_DESCRIPTION, TRAFFIC_FNC.TRF_CODE, JOB_TRAFFIC_DET.EMP_CODE
		  ORDER BY JOB_TRAFFIC_DET.JOB_REVISED_DATE

	   ELSE
		  SELECT JOB_LOG.CL_CODE as CCode,
				 JOB_LOG.DIV_CODE as DCode,
				 JOB_LOG.PRD_CODE as PCode,
				 JOB_LOG.JOB_NUMBER as JobNum,
				 JOB_LOG.JOB_DESC as JobDesc,
				 JOB_COMPONENT.JOB_COMPONENT_NBR as CompNum,
				 JOB_COMPONENT.JOB_COMP_DESC as CompDesc,
				 STR(DATEPART(day, JOB_TRAFFIC_DET.JOB_REVISED_DATE)) as ThisDay,
				 isnull(JOB_TRAFFIC_DET.TASK_DESCRIPTION, '(' + ISNULL(JOB_TRAFFIC_DET.FNC_CODE,'') + ')') as Task, 
				 isnull(JOB_TRAFFIC_DET.TEMP_COMP_DATE, '1/1/1900') as TempCompDate,
				 JOB_TRAFFIC_DET.TASK_STATUS, STR(DATEPART(day, JOB_TRAFFIC_DET.TASK_START_DATE)) as ThisDayStart, JOB_TRAFFIC_DET.SEQ_NBR,
				 CLIENT.CL_NAME, DIVISION.DIV_NAME, PRODUCT.PRD_DESCRIPTION, TRAFFIC_FNC.TRF_CODE, JOB_TRAFFIC_DET.JOB_REVISED_DATE as RevisedDate, isnull(JOB_TRAFFIC_DET.TASK_START_DATE, '1/1/1900') as StartDate,
				 JOB_TRAFFIC_DET.EMP_CODE as empcodedispl,
				 dbo.udf_get_empl_name( JOB_TRAFFIC_DET.EMP_CODE, 'FML' ) AS empdescdispl
		FROM JOB_LOG INNER JOIN JOB_COMPONENT ON JOB_LOG.JOB_NUMBER = JOB_COMPONENT.JOB_NUMBER
						 INNER JOIN JOB_TRAFFIC_DET ON JOB_COMPONENT.JOB_NUMBER = JOB_TRAFFIC_DET.JOB_NUMBER AND
									JOB_COMPONENT.JOB_COMPONENT_NBR = JOB_TRAFFIC_DET.JOB_COMPONENT_NBR
						 INNER JOIN PRODUCT ON JOB_LOG.CL_CODE = PRODUCT.CL_CODE AND JOB_LOG.DIV_CODE = PRODUCT.DIV_CODE AND 
										   JOB_LOG.PRD_CODE = PRODUCT.PRD_CODE 
						 INNER JOIN DIVISION ON PRODUCT.CL_CODE = DIVISION.CL_CODE AND PRODUCT.DIV_CODE = DIVISION.DIV_CODE 
						 INNER JOIN CLIENT ON DIVISION.CL_CODE = CLIENT.CL_CODE  
						 LEFT OUTER JOIN TRAFFIC_FNC ON JOB_TRAFFIC_DET.FNC_CODE = TRAFFIC_FNC.TRF_CODE
						 INNER JOIN [dbo].[advtf_sec_emp] (@UserID) AS SEC_EMP ON JOB_TRAFFIC_DET.EMP_CODE = SEC_EMP.EMP_CODE
						 LEFT OUTER JOIN TASK_TRAFFIC_ROLE ON JOB_TRAFFIC_DET.FNC_CODE = TASK_TRAFFIC_ROLE.TRF_CODE 
						 LEFT OUTER JOIN EMP_TRAFFIC_ROLE ON JOB_TRAFFIC_DET.EMP_CODE = EMP_TRAFFIC_ROLE.EMP_CODE
		WHERE (NOT (JOB_COMPONENT.JOB_PROCESS_CONTRL IN (6, 12))) AND
			  (Isnull(JOB_TRAFFIC_DET.EMP_CODE, '') Like '%' + @EmpCode) AND
			   JOB_LOG.CL_CODE Like '%' + @ClientCode AND
			   JOB_LOG.DIV_CODE Like '%' + @DivCode AND
			   JOB_LOG.PRD_CODE Like '%' + @ProdCode AND
			   JOB_LOG.OFFICE_CODE Like '%' + @Office AND
			   ((JOB_TRAFFIC_DET.JOB_REVISED_DATE >= @StartDate AND
			   JOB_TRAFFIC_DET.JOB_REVISED_DATE <= @EndDate) OR (JOB_TRAFFIC_DET.TASK_START_DATE >= @StartDate AND JOB_TRAFFIC_DET.TASK_START_DATE <= @EndDate)
			   OR (@StartDate >= JOB_TRAFFIC_DET.TASK_START_DATE and @EndDate <= JOB_TRAFFIC_DET.JOB_REVISED_DATE)) AND
			   JOB_TRAFFIC_DET.JOB_COMPLETED_DATE IS NULL AND
			   JOB_TRAFFIC_DET.MILESTONE = 1 AND
			  (ISNULL(TASK_TRAFFIC_ROLE.ROLE_CODE, '') Like '%' + @Role OR ISNULL(EMP_TRAFFIC_ROLE.ROLE_CODE, '') Like '%' + @Role) AND
				   ISNULL(JOB_TRAFFIC_DET.TASK_STATUS, '') Like Case @TaskStatus
													When 'P' Then 'P'
																When 'A' Then 'A'
													When '' Then '%'
														End
		  GROUP BY JOB_LOG.CL_CODE,
			   JOB_LOG.DIV_CODE,
			   JOB_LOG.PRD_CODE,
			   JOB_LOG.JOB_NUMBER,
			   JOB_LOG.JOB_DESC,
			   JOB_COMPONENT.JOB_COMPONENT_NBR,
			   JOB_COMPONENT.JOB_COMP_DESC,
			   STR(DATEPART(day, JOB_TRAFFIC_DET.TASK_START_DATE)),
			   STR(DATEPART(day, JOB_TRAFFIC_DET.JOB_REVISED_DATE)),
			   ISNULL(JOB_TRAFFIC_DET.TASK_DESCRIPTION, '(' + ISNULL(JOB_TRAFFIC_DET.FNC_CODE,'') + ')') ,
			   JOB_TRAFFIC_DET.JOB_REVISED_DATE, 
			   JOB_TRAFFIC_DET.TASK_START_DATE,
			   JOB_TRAFFIC_DET.TEMP_COMP_DATE,
				   JOB_TRAFFIC_DET.TASK_STATUS,
				   JOB_TRAFFIC_DET.SEQ_NBR,
				   CLIENT.CL_NAME, DIVISION.DIV_NAME, PRODUCT.PRD_DESCRIPTION, TRAFFIC_FNC.TRF_CODE, JOB_TRAFFIC_DET.EMP_CODE
		  ORDER BY JOB_TRAFFIC_DET.JOB_REVISED_DATE

	If @Rescrictions > 0 and @RescrictionsEmp = 0
	   If @ExcludeTempComplete = 'Y'
				SELECT JOB_LOG.CL_CODE as CCode,
				 JOB_LOG.DIV_CODE as DCode,
				 JOB_LOG.PRD_CODE as PCode,
				 JOB_LOG.JOB_NUMBER as JobNum,
				 JOB_LOG.JOB_DESC as JobDesc,
				 JOB_COMPONENT.JOB_COMPONENT_NBR as CompNum,
				 JOB_COMPONENT.JOB_COMP_DESC as CompDesc,
				 STR(DATEPART(day, JOB_TRAFFIC_DET.JOB_REVISED_DATE)) as ThisDay,
				 isnull(JOB_TRAFFIC_DET.TASK_DESCRIPTION, '(' + ISNULL(JOB_TRAFFIC_DET.FNC_CODE,'') + ')') as Task, 
				 isnull(JOB_TRAFFIC_DET.TEMP_COMP_DATE, '1/1/1900') as TempCompDate,
				 JOB_TRAFFIC_DET.TASK_STATUS, STR(DATEPART(day, JOB_TRAFFIC_DET.TASK_START_DATE)) as ThisDayStart, JOB_TRAFFIC_DET.SEQ_NBR,
				 CLIENT.CL_NAME, DIVISION.DIV_NAME, PRODUCT.PRD_DESCRIPTION, TRAFFIC_FNC.TRF_CODE, JOB_TRAFFIC_DET.JOB_REVISED_DATE as RevisedDate, isnull(JOB_TRAFFIC_DET.TASK_START_DATE, '1/1/1900') as StartDate,
				 JOB_TRAFFIC_DET.EMP_CODE as empcodedispl,
				 dbo.udf_get_empl_name( JOB_TRAFFIC_DET.EMP_CODE, 'FML' ) AS empdescdispl
		FROM JOB_LOG INNER JOIN JOB_COMPONENT ON JOB_LOG.JOB_NUMBER = JOB_COMPONENT.JOB_NUMBER
						 INNER JOIN JOB_TRAFFIC_DET ON JOB_COMPONENT.JOB_NUMBER = JOB_TRAFFIC_DET.JOB_NUMBER AND
									JOB_COMPONENT.JOB_COMPONENT_NBR = JOB_TRAFFIC_DET.JOB_COMPONENT_NBR
						 INNER JOIN SEC_CLIENT ON JOB_LOG.CL_CODE = SEC_CLIENT.CL_CODE AND JOB_LOG.DIV_CODE = SEC_CLIENT.DIV_CODE AND JOB_LOG.PRD_CODE = SEC_CLIENT.PRD_CODE
						 INNER JOIN PRODUCT ON JOB_LOG.CL_CODE = PRODUCT.CL_CODE AND JOB_LOG.DIV_CODE = PRODUCT.DIV_CODE AND 
										   JOB_LOG.PRD_CODE = PRODUCT.PRD_CODE 
						 INNER JOIN DIVISION ON PRODUCT.CL_CODE = DIVISION.CL_CODE AND PRODUCT.DIV_CODE = DIVISION.DIV_CODE 
						 INNER JOIN CLIENT ON DIVISION.CL_CODE = CLIENT.CL_CODE  
						 LEFT OUTER JOIN TRAFFIC_FNC ON JOB_TRAFFIC_DET.FNC_CODE = TRAFFIC_FNC.TRF_CODE
						 LEFT OUTER JOIN TASK_TRAFFIC_ROLE ON JOB_TRAFFIC_DET.FNC_CODE = TASK_TRAFFIC_ROLE.TRF_CODE 
						 LEFT OUTER JOIN EMP_TRAFFIC_ROLE ON JOB_TRAFFIC_DET.EMP_CODE = EMP_TRAFFIC_ROLE.EMP_CODE
		WHERE (NOT (JOB_COMPONENT.JOB_PROCESS_CONTRL IN (6, 12))) AND
			  (UPPER(SEC_CLIENT.USER_ID) = UPPER(@UserID)) AND (SEC_CLIENT.TIME_ENTRY = 0 OR SEC_CLIENT.TIME_ENTRY IS NULL) AND
			  (Isnull(JOB_TRAFFIC_DET.EMP_CODE, '') Like '%' + @EmpCode) AND
			   JOB_LOG.CL_CODE Like '%' + @ClientCode AND
			   JOB_LOG.DIV_CODE Like '%' + @DivCode AND
			   JOB_LOG.PRD_CODE Like '%' + @ProdCode AND
			   JOB_LOG.OFFICE_CODE Like '%' + @Office AND
			   ((JOB_TRAFFIC_DET.JOB_REVISED_DATE >= @StartDate AND
			   JOB_TRAFFIC_DET.JOB_REVISED_DATE <= @EndDate) OR (JOB_TRAFFIC_DET.TASK_START_DATE >= @StartDate AND JOB_TRAFFIC_DET.TASK_START_DATE <= @EndDate)
			   OR (@StartDate >= JOB_TRAFFIC_DET.TASK_START_DATE and @EndDate <= JOB_TRAFFIC_DET.JOB_REVISED_DATE)) AND
			   JOB_TRAFFIC_DET.JOB_COMPLETED_DATE IS NULL AND
			   JOB_TRAFFIC_DET.MILESTONE = 1 AND
			  (ISNULL(TASK_TRAFFIC_ROLE.ROLE_CODE, '') Like '%' + @Role OR ISNULL(EMP_TRAFFIC_ROLE.ROLE_CODE, '') Like '%' + @Role) AND
				   ISNULL(JOB_TRAFFIC_DET.TASK_STATUS, '') Like Case @TaskStatus
													When 'P' Then 'P'
																When 'A' Then 'A'
													When '' Then '%'
														End AND
				   JOB_TRAFFIC_DET.TEMP_COMP_DATE IS NULL
		  GROUP BY JOB_LOG.CL_CODE,
			   JOB_LOG.DIV_CODE,
			   JOB_LOG.PRD_CODE,
			   JOB_LOG.JOB_NUMBER,
			   JOB_LOG.JOB_DESC,
			   JOB_COMPONENT.JOB_COMPONENT_NBR,
			   JOB_COMPONENT.JOB_COMP_DESC,
			   STR(DATEPART(day, JOB_TRAFFIC_DET.TASK_START_DATE)),
			   STR(DATEPART(day, JOB_TRAFFIC_DET.JOB_REVISED_DATE)),
			   ISNULL(JOB_TRAFFIC_DET.TASK_DESCRIPTION, '(' + ISNULL(JOB_TRAFFIC_DET.FNC_CODE,'') + ')') ,
			   JOB_TRAFFIC_DET.JOB_REVISED_DATE, 
			   JOB_TRAFFIC_DET.TASK_START_DATE,
			   JOB_TRAFFIC_DET.TEMP_COMP_DATE,
				   JOB_TRAFFIC_DET.TASK_STATUS,
				   JOB_TRAFFIC_DET.SEQ_NBR,
				   CLIENT.CL_NAME, DIVISION.DIV_NAME, PRODUCT.PRD_DESCRIPTION, TRAFFIC_FNC.TRF_CODE, JOB_TRAFFIC_DET.EMP_CODE
		  ORDER BY JOB_TRAFFIC_DET.JOB_REVISED_DATE

	   ELSE
		  SELECT JOB_LOG.CL_CODE as CCode,
				 JOB_LOG.DIV_CODE as DCode,
				 JOB_LOG.PRD_CODE as PCode,
				 JOB_LOG.JOB_NUMBER as JobNum,
				 JOB_LOG.JOB_DESC as JobDesc,
				 JOB_COMPONENT.JOB_COMPONENT_NBR as CompNum,
				 JOB_COMPONENT.JOB_COMP_DESC as CompDesc,
				 STR(DATEPART(day, JOB_TRAFFIC_DET.JOB_REVISED_DATE)) as ThisDay,
				 isnull(JOB_TRAFFIC_DET.TASK_DESCRIPTION, '(' + ISNULL(JOB_TRAFFIC_DET.FNC_CODE,'') + ')') as Task, 
				 isnull(JOB_TRAFFIC_DET.TEMP_COMP_DATE, '1/1/1900') as TempCompDate,
				 JOB_TRAFFIC_DET.TASK_STATUS, STR(DATEPART(day, JOB_TRAFFIC_DET.TASK_START_DATE)) as ThisDayStart, JOB_TRAFFIC_DET.SEQ_NBR,
				 CLIENT.CL_NAME, DIVISION.DIV_NAME, PRODUCT.PRD_DESCRIPTION, TRAFFIC_FNC.TRF_CODE, JOB_TRAFFIC_DET.JOB_REVISED_DATE as RevisedDate, isnull(JOB_TRAFFIC_DET.TASK_START_DATE, '1/1/1900') as StartDate,
				 JOB_TRAFFIC_DET.EMP_CODE as empcodedispl,
				 dbo.udf_get_empl_name( JOB_TRAFFIC_DET.EMP_CODE, 'FML' ) AS empdescdispl
		FROM JOB_LOG INNER JOIN JOB_COMPONENT ON JOB_LOG.JOB_NUMBER = JOB_COMPONENT.JOB_NUMBER
						 INNER JOIN JOB_TRAFFIC_DET ON JOB_COMPONENT.JOB_NUMBER = JOB_TRAFFIC_DET.JOB_NUMBER AND
									JOB_COMPONENT.JOB_COMPONENT_NBR = JOB_TRAFFIC_DET.JOB_COMPONENT_NBR
						 INNER JOIN SEC_CLIENT ON JOB_LOG.CL_CODE = SEC_CLIENT.CL_CODE AND JOB_LOG.DIV_CODE = SEC_CLIENT.DIV_CODE AND JOB_LOG.PRD_CODE = SEC_CLIENT.PRD_CODE
						 INNER JOIN PRODUCT ON JOB_LOG.CL_CODE = PRODUCT.CL_CODE AND JOB_LOG.DIV_CODE = PRODUCT.DIV_CODE AND 
										   JOB_LOG.PRD_CODE = PRODUCT.PRD_CODE 
						 INNER JOIN DIVISION ON PRODUCT.CL_CODE = DIVISION.CL_CODE AND PRODUCT.DIV_CODE = DIVISION.DIV_CODE 
						 INNER JOIN CLIENT ON DIVISION.CL_CODE = CLIENT.CL_CODE 
						 LEFT OUTER JOIN TRAFFIC_FNC ON JOB_TRAFFIC_DET.FNC_CODE = TRAFFIC_FNC.TRF_CODE
						 LEFT OUTER JOIN TASK_TRAFFIC_ROLE ON JOB_TRAFFIC_DET.FNC_CODE = TASK_TRAFFIC_ROLE.TRF_CODE 
						 LEFT OUTER JOIN EMP_TRAFFIC_ROLE ON JOB_TRAFFIC_DET.EMP_CODE = EMP_TRAFFIC_ROLE.EMP_CODE
		WHERE (NOT (JOB_COMPONENT.JOB_PROCESS_CONTRL IN (6, 12))) AND
			  (UPPER(SEC_CLIENT.USER_ID) = UPPER(@UserID)) AND (SEC_CLIENT.TIME_ENTRY = 0 OR SEC_CLIENT.TIME_ENTRY IS NULL) AND
			  (Isnull(JOB_TRAFFIC_DET.EMP_CODE, '') Like '%' + @EmpCode) AND
			   JOB_LOG.CL_CODE Like '%' + @ClientCode AND
			   JOB_LOG.DIV_CODE Like '%' + @DivCode AND
			   JOB_LOG.PRD_CODE Like '%' + @ProdCode AND
			   JOB_LOG.OFFICE_CODE Like '%' + @Office AND
			   ((JOB_TRAFFIC_DET.JOB_REVISED_DATE >= @StartDate AND
			   JOB_TRAFFIC_DET.JOB_REVISED_DATE <= @EndDate) OR (JOB_TRAFFIC_DET.TASK_START_DATE >= @StartDate AND JOB_TRAFFIC_DET.TASK_START_DATE <= @EndDate)
			   OR (@StartDate >= JOB_TRAFFIC_DET.TASK_START_DATE and @EndDate <= JOB_TRAFFIC_DET.JOB_REVISED_DATE)) AND
			   JOB_TRAFFIC_DET.JOB_COMPLETED_DATE IS NULL AND
			   JOB_TRAFFIC_DET.MILESTONE = 1 AND
			  (ISNULL(TASK_TRAFFIC_ROLE.ROLE_CODE, '') Like '%' + @Role OR ISNULL(EMP_TRAFFIC_ROLE.ROLE_CODE, '') Like '%' + @Role) AND
				   ISNULL(JOB_TRAFFIC_DET.TASK_STATUS, '') Like Case @TaskStatus
													When 'P' Then 'P'
																When 'A' Then 'A'
													When '' Then '%'
														End
		  GROUP BY JOB_LOG.CL_CODE,
			   JOB_LOG.DIV_CODE,
			   JOB_LOG.PRD_CODE,
			   JOB_LOG.JOB_NUMBER,
			   JOB_LOG.JOB_DESC,
			   JOB_COMPONENT.JOB_COMPONENT_NBR,
			   JOB_COMPONENT.JOB_COMP_DESC,
			   STR(DATEPART(day, JOB_TRAFFIC_DET.TASK_START_DATE)),
			   STR(DATEPART(day, JOB_TRAFFIC_DET.JOB_REVISED_DATE)),
			   ISNULL(JOB_TRAFFIC_DET.TASK_DESCRIPTION, '(' + ISNULL(JOB_TRAFFIC_DET.FNC_CODE,'') + ')') ,
			   JOB_TRAFFIC_DET.JOB_REVISED_DATE, 
			   JOB_TRAFFIC_DET.TASK_START_DATE,
			   JOB_TRAFFIC_DET.TEMP_COMP_DATE,
				   JOB_TRAFFIC_DET.TASK_STATUS,
				   JOB_TRAFFIC_DET.SEQ_NBR,
				   CLIENT.CL_NAME, DIVISION.DIV_NAME, PRODUCT.PRD_DESCRIPTION, TRAFFIC_FNC.TRF_CODE, JOB_TRAFFIC_DET.EMP_CODE
		  ORDER BY JOB_TRAFFIC_DET.JOB_REVISED_DATE

	If @Rescrictions = 0 and @RescrictionsEmp = 0
	   IF @ExcludeTempComplete = 'Y'
				SELECT JOB_LOG.CL_CODE as CCode,
			 JOB_LOG.DIV_CODE as DCode,
			 JOB_LOG.PRD_CODE as PCode,
			 JOB_LOG.JOB_NUMBER as JobNum,
			 JOB_LOG.JOB_DESC as JobDesc,
			 JOB_COMPONENT.JOB_COMPONENT_NBR as CompNum,
			 JOB_COMPONENT.JOB_COMP_DESC as CompDesc,
			 STR(DATEPART(day, JOB_TRAFFIC_DET.JOB_REVISED_DATE)) as ThisDay,
			 -- JOB_TRAFFIC_DET.TASK_DESCRIPTION + '(' + JOB_TRAFFIC_DET.FNC_CODE + ')' as Task
			 isnull(JOB_TRAFFIC_DET.TASK_DESCRIPTION, '(' + ISNULL(JOB_TRAFFIC_DET.FNC_CODE,'') + ')') as Task,
			 isnull(JOB_TRAFFIC_DET.TEMP_COMP_DATE, '1/1/1900') as TempCompDate,
				 JOB_TRAFFIC_DET.TASK_STATUS, STR(DATEPART(day, JOB_TRAFFIC_DET.TASK_START_DATE)) as ThisDayStart, JOB_TRAFFIC_DET.SEQ_NBR,
				 CLIENT.CL_NAME, DIVISION.DIV_NAME, PRODUCT.PRD_DESCRIPTION, TRAFFIC_FNC.TRF_CODE, JOB_TRAFFIC_DET.JOB_REVISED_DATE as RevisedDate, isnull(JOB_TRAFFIC_DET.TASK_START_DATE, '1/1/1900') as StartDate,
				 JOB_TRAFFIC_DET.EMP_CODE as empcodedispl,
				 dbo.udf_get_empl_name( JOB_TRAFFIC_DET.EMP_CODE, 'FML' ) AS empdescdispl
		FROM JOB_LOG INNER JOIN JOB_COMPONENT ON JOB_LOG.JOB_NUMBER = JOB_COMPONENT.JOB_NUMBER
					 INNER JOIN JOB_TRAFFIC_DET ON JOB_COMPONENT.JOB_NUMBER = JOB_TRAFFIC_DET.JOB_NUMBER AND
												   JOB_COMPONENT.JOB_COMPONENT_NBR = JOB_TRAFFIC_DET.JOB_COMPONENT_NBR
					 INNER JOIN PRODUCT ON JOB_LOG.CL_CODE = PRODUCT.CL_CODE AND JOB_LOG.DIV_CODE = PRODUCT.DIV_CODE AND 
										   JOB_LOG.PRD_CODE = PRODUCT.PRD_CODE 
					 INNER JOIN DIVISION ON PRODUCT.CL_CODE = DIVISION.CL_CODE AND PRODUCT.DIV_CODE = DIVISION.DIV_CODE 
					 INNER JOIN CLIENT ON DIVISION.CL_CODE = CLIENT.CL_CODE 
					 LEFT OUTER JOIN TRAFFIC_FNC ON JOB_TRAFFIC_DET.FNC_CODE = TRAFFIC_FNC.TRF_CODE                               
					 LEFT OUTER JOIN TASK_TRAFFIC_ROLE ON JOB_TRAFFIC_DET.FNC_CODE = TASK_TRAFFIC_ROLE.TRF_CODE 
					 LEFT OUTER JOIN EMP_TRAFFIC_ROLE ON JOB_TRAFFIC_DET.EMP_CODE = EMP_TRAFFIC_ROLE.EMP_CODE
		WHERE (NOT (JOB_COMPONENT.JOB_PROCESS_CONTRL IN (6, 12))) AND
			  (isnull(JOB_TRAFFIC_DET.EMP_CODE, '') Like '%' + @EmpCode) AND
			  JOB_LOG.CL_CODE Like '%' + @ClientCode AND
			  JOB_LOG.DIV_CODE Like '%' + @DivCode AND
			  JOB_LOG.PRD_CODE Like '%' + @ProdCode AND
			 JOB_LOG.OFFICE_CODE Like '%' + @Office AND
			  ((JOB_TRAFFIC_DET.JOB_REVISED_DATE >= @StartDate AND
			   JOB_TRAFFIC_DET.JOB_REVISED_DATE <= @EndDate) OR (JOB_TRAFFIC_DET.TASK_START_DATE >= @StartDate AND JOB_TRAFFIC_DET.TASK_START_DATE <= @EndDate)
			   OR (@StartDate >= JOB_TRAFFIC_DET.TASK_START_DATE and @EndDate <= JOB_TRAFFIC_DET.JOB_REVISED_DATE)) AND
			  JOB_TRAFFIC_DET.JOB_COMPLETED_DATE IS NULL AND
			  JOB_TRAFFIC_DET.MILESTONE = 1 AND
			  (ISNULL(TASK_TRAFFIC_ROLE.ROLE_CODE, '') Like '%' + @Role OR ISNULL(EMP_TRAFFIC_ROLE.ROLE_CODE, '') Like '%' + @Role) AND
			   ISNULL(JOB_TRAFFIC_DET.TASK_STATUS, '') Like Case @TaskStatus
													When 'P' Then 'P'
																When 'A' Then 'A'
														When '' Then '%'
														End AND
				 JOB_TRAFFIC_DET.TEMP_COMP_DATE IS NULL
		GROUP BY JOB_LOG.CL_CODE,
			 JOB_LOG.DIV_CODE,
			 JOB_LOG.PRD_CODE,
			 JOB_LOG.JOB_NUMBER,
			 JOB_LOG.JOB_DESC,
			 JOB_COMPONENT.JOB_COMPONENT_NBR,
			 JOB_COMPONENT.JOB_COMP_DESC,
			 STR(DATEPART(day, JOB_TRAFFIC_DET.TASK_START_DATE)),
			 STR(DATEPART(day, JOB_TRAFFIC_DET.JOB_REVISED_DATE)),
			 isnull(JOB_TRAFFIC_DET.TASK_DESCRIPTION, '(' + ISNULL(JOB_TRAFFIC_DET.FNC_CODE,'') + ')') ,
			 JOB_TRAFFIC_DET.JOB_REVISED_DATE,
			 JOB_TRAFFIC_DET.TASK_START_DATE,
			 JOB_TRAFFIC_DET.TEMP_COMP_DATE,
				 JOB_TRAFFIC_DET.TASK_STATUS,
				 JOB_TRAFFIC_DET.SEQ_NBR,
				 CLIENT.CL_NAME, DIVISION.DIV_NAME, PRODUCT.PRD_DESCRIPTION, TRAFFIC_FNC.TRF_CODE, JOB_TRAFFIC_DET.EMP_CODE
		ORDER BY JOB_TRAFFIC_DET.JOB_REVISED_DATE
	   ELSE

		  SELECT JOB_LOG.CL_CODE as CCode,
			 JOB_LOG.DIV_CODE as DCode,
			 JOB_LOG.PRD_CODE as PCode,
			 JOB_LOG.JOB_NUMBER as JobNum,
			 JOB_LOG.JOB_DESC as JobDesc,
			 JOB_COMPONENT.JOB_COMPONENT_NBR as CompNum,
			 JOB_COMPONENT.JOB_COMP_DESC as CompDesc,
			 STR(DATEPART(day, JOB_TRAFFIC_DET.JOB_REVISED_DATE)) as ThisDay,
			 -- JOB_TRAFFIC_DET.TASK_DESCRIPTION + '(' + JOB_TRAFFIC_DET.FNC_CODE + ')' as Task
			 isnull(JOB_TRAFFIC_DET.TASK_DESCRIPTION, '(' + ISNULL(JOB_TRAFFIC_DET.FNC_CODE,'') + ')') as Task,
			 isnull(JOB_TRAFFIC_DET.TEMP_COMP_DATE, '1/1/1900') as TempCompDate,
				 JOB_TRAFFIC_DET.TASK_STATUS, STR(DATEPART(day, JOB_TRAFFIC_DET.TASK_START_DATE)) as ThisDayStart, JOB_TRAFFIC_DET.SEQ_NBR,
				 CLIENT.CL_NAME, DIVISION.DIV_NAME, PRODUCT.PRD_DESCRIPTION, TRAFFIC_FNC.TRF_CODE, JOB_TRAFFIC_DET.JOB_REVISED_DATE as RevisedDate, isnull(JOB_TRAFFIC_DET.TASK_START_DATE, '1/1/1900') as StartDate,
				 JOB_TRAFFIC_DET.EMP_CODE as empcodedispl,
				 dbo.udf_get_empl_name( JOB_TRAFFIC_DET.EMP_CODE, 'FML' ) AS empdescdispl
		FROM JOB_LOG INNER JOIN JOB_COMPONENT ON JOB_LOG.JOB_NUMBER = JOB_COMPONENT.JOB_NUMBER
					 INNER JOIN JOB_TRAFFIC_DET ON JOB_COMPONENT.JOB_NUMBER = JOB_TRAFFIC_DET.JOB_NUMBER AND
												   JOB_COMPONENT.JOB_COMPONENT_NBR = JOB_TRAFFIC_DET.JOB_COMPONENT_NBR
					 INNER JOIN PRODUCT ON JOB_LOG.CL_CODE = PRODUCT.CL_CODE AND JOB_LOG.DIV_CODE = PRODUCT.DIV_CODE AND 
										   JOB_LOG.PRD_CODE = PRODUCT.PRD_CODE 
					 INNER JOIN DIVISION ON PRODUCT.CL_CODE = DIVISION.CL_CODE AND PRODUCT.DIV_CODE = DIVISION.DIV_CODE 
					 INNER JOIN CLIENT ON DIVISION.CL_CODE = CLIENT.CL_CODE  
					 LEFT OUTER JOIN TRAFFIC_FNC ON JOB_TRAFFIC_DET.FNC_CODE = TRAFFIC_FNC.TRF_CODE                            
					 LEFT OUTER JOIN TASK_TRAFFIC_ROLE ON JOB_TRAFFIC_DET.FNC_CODE = TASK_TRAFFIC_ROLE.TRF_CODE 
					 LEFT OUTER JOIN EMP_TRAFFIC_ROLE ON JOB_TRAFFIC_DET.EMP_CODE = EMP_TRAFFIC_ROLE.EMP_CODE
		WHERE (NOT (JOB_COMPONENT.JOB_PROCESS_CONTRL IN (6, 12))) AND
			  (isnull(JOB_TRAFFIC_DET.EMP_CODE, '') Like '%' + @EmpCode) AND
			  JOB_LOG.CL_CODE Like '%' + @ClientCode AND
			  JOB_LOG.DIV_CODE Like '%' + @DivCode AND
			  JOB_LOG.PRD_CODE Like '%' + @ProdCode AND
			 JOB_LOG.OFFICE_CODE Like '%' + @Office AND
			  ((JOB_TRAFFIC_DET.JOB_REVISED_DATE >= @StartDate AND
			   JOB_TRAFFIC_DET.JOB_REVISED_DATE <= @EndDate) OR (JOB_TRAFFIC_DET.TASK_START_DATE >= @StartDate AND JOB_TRAFFIC_DET.TASK_START_DATE <= @EndDate)
			   OR (@StartDate >= JOB_TRAFFIC_DET.TASK_START_DATE and @EndDate <= JOB_TRAFFIC_DET.JOB_REVISED_DATE)) AND
			  JOB_TRAFFIC_DET.JOB_COMPLETED_DATE IS NULL AND
			  JOB_TRAFFIC_DET.MILESTONE = 1 AND
			  (ISNULL(TASK_TRAFFIC_ROLE.ROLE_CODE, '') Like '%' + @Role OR ISNULL(EMP_TRAFFIC_ROLE.ROLE_CODE, '') Like '%' + @Role) AND
			   ISNULL(JOB_TRAFFIC_DET.TASK_STATUS, '') Like Case @TaskStatus
													When 'P' Then 'P'
																When 'A' Then 'A'
														When '' Then '%'
														End
		GROUP BY JOB_LOG.CL_CODE,

			 JOB_LOG.DIV_CODE,
			 JOB_LOG.PRD_CODE,
			 JOB_LOG.JOB_NUMBER,
			 JOB_LOG.JOB_DESC,
			 JOB_COMPONENT.JOB_COMPONENT_NBR,
			 JOB_COMPONENT.JOB_COMP_DESC,
			 STR(DATEPART(day, JOB_TRAFFIC_DET.TASK_START_DATE)),
			 STR(DATEPART(day, JOB_TRAFFIC_DET.JOB_REVISED_DATE)),
			 isnull(JOB_TRAFFIC_DET.TASK_DESCRIPTION, '(' + ISNULL(JOB_TRAFFIC_DET.FNC_CODE,'') + ')') ,
			 JOB_TRAFFIC_DET.JOB_REVISED_DATE,
			 JOB_TRAFFIC_DET.TASK_START_DATE,
			 JOB_TRAFFIC_DET.TEMP_COMP_DATE,
				 JOB_TRAFFIC_DET.TASK_STATUS,
				 JOB_TRAFFIC_DET.SEQ_NBR,
				 CLIENT.CL_NAME, DIVISION.DIV_NAME, PRODUCT.PRD_DESCRIPTION, TRAFFIC_FNC.TRF_CODE, JOB_TRAFFIC_DET.EMP_CODE
		ORDER BY JOB_TRAFFIC_DET.JOB_REVISED_DATE
End



