if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[usp_wv_AD_NUMBER_GET]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [dbo].[usp_wv_AD_NUMBER_GET]
GO

CREATE PROCEDURE [dbo].[usp_wv_AD_NUMBER_GET]
	@CL_CODE AS VARCHAR(6),
	@INCL_INACTIVE AS BIT

 AS
 
 IF @INCL_INACTIVE = 1
 BEGIN
     SELECT 
           AD_NUMBER.AD_NBR,
           AD_NUMBER.AD_NBR AS CODE,
           AD_NUMBER.AD_NBR_DESC,
           AD_NUMBER.AD_NBR+'|'+
           ISNULL(AD_NUMBER.AD_NBR_DESC,'')+'|'+
           CONVERT(VARCHAR(1), ISNULL(AD_NUMBER.ACTIVE,1)) AS CMD_ARG,
           AD_NUMBER.AD_NBR+' - '+
           AD_NUMBER.AD_NBR_DESC AS DESCRIPTION,
           ISNULL(AD_NUMBER.ACTIVE,1) AS ACTIVE,
           AD_NUMBER.DEF_BLKPLT_VER_CODE,
           AD_NUMBER.DEF_BLKPLT_VER2_CODE,
           AD_NUMBER.CL_CODE,
           AD_NUMBER.COLOR,
           DOCUMENTS.DOCUMENT_ID,
           DOCUMENTS.FILENAME,
           DOCUMENTS.REPOSITORY_FILENAME,
           DOCUMENTS.MIME_TYPE,
           DOCUMENTS.DESCRIPTION,
           DOCUMENTS.KEYWORDS,
           DOCUMENTS.UPLOADED_DATE,
           DOCUMENTS.USER_CODE,
           DOCUMENTS.FILE_SIZE,
           DOCUMENTS.PRIVATE_FLAG,
           DOCUMENTS.DOCUMENT_TYPE_ID
    FROM   AD_NUMBER WITH(NOLOCK)
           LEFT OUTER JOIN DOCUMENTS WITH(NOLOCK)
                ON  AD_NUMBER.DOCUMENT_ID = DOCUMENTS.DOCUMENT_ID
    WHERE
        ((AD_NUMBER.CL_CODE IS NULL) OR (AD_NUMBER.CL_CODE = @CL_CODE)) AND (EXP_DT >= GETDATE() OR EXP_DT IS NULL);
END
        
 IF @INCL_INACTIVE = 0
 BEGIN
     SELECT 
           AD_NUMBER.AD_NBR,
           AD_NUMBER.AD_NBR AS CODE,
           AD_NUMBER.AD_NBR_DESC,
           AD_NUMBER.AD_NBR+'|'+
           ISNULL(AD_NUMBER.AD_NBR_DESC,'')+'|'+
           CONVERT(VARCHAR(1), ISNULL(AD_NUMBER.ACTIVE,1)) AS CMD_ARG,
           AD_NUMBER.AD_NBR+' - '+
           AD_NUMBER.AD_NBR_DESC AS DESCRIPTION,
           ISNULL(AD_NUMBER.ACTIVE,1) AS ACTIVE,
           AD_NUMBER.DEF_BLKPLT_VER_CODE,
           AD_NUMBER.DEF_BLKPLT_VER2_CODE,
           AD_NUMBER.CL_CODE,
           AD_NUMBER.COLOR,
           DOCUMENTS.DOCUMENT_ID,
           DOCUMENTS.FILENAME,
           DOCUMENTS.REPOSITORY_FILENAME,
           DOCUMENTS.MIME_TYPE,
           DOCUMENTS.DESCRIPTION,
           DOCUMENTS.KEYWORDS,
           DOCUMENTS.UPLOADED_DATE,
           DOCUMENTS.USER_CODE,
           DOCUMENTS.FILE_SIZE,
           DOCUMENTS.PRIVATE_FLAG,
           DOCUMENTS.DOCUMENT_TYPE_ID
    FROM   AD_NUMBER WITH(NOLOCK)
           LEFT OUTER JOIN DOCUMENTS WITH(NOLOCK)
                ON  AD_NUMBER.DOCUMENT_ID = DOCUMENTS.DOCUMENT_ID
    WHERE
        (AD_NUMBER.ACTIVE = 1 OR (AD_NUMBER.ACTIVE IS NULL)) 
        AND ((AD_NUMBER.CL_CODE IS NULL) OR (AD_NUMBER.CL_CODE = @CL_CODE)) AND (EXP_DT >= GETDATE() OR EXP_DT IS NULL);
END
               
