
CREATE PROCEDURE [dbo].[usp_wv_check_missing_time_employee] 
@EMP_CODE		VARCHAR(6),
@ThisDate		DateTime
AS

DECLARE @WK_TIME AS INT
DECLARE @StartDate datetime, @EndDate datetime

SELECT @WK_TIME = ISNULL(WEEKLY_TIME,2) FROM EMPLOYEE WHERE EMP_CODE = @EMP_CODE

IF @WK_TIME = 2
	SELECT @WK_TIME = ISNULL(WEEKLY_TIME,0) FROM AGENCY

IF @WK_TIME = 0	--Daily
  BEGIN
	IF EXISTS(
			SELECT WORKDATE, DAYOFWEEK, WEEKOFDATE, STANDARD_HRS, HOURS_WORKED, VARIANCE, '' AS SPACER
			FROM MISSING_TIME_DTL
			WHERE EMP_CODE = @EMP_CODE AND WORKDATE = @ThisDate 		
	)
		SELECT 1
	ELSE
		SELECT 0

--	SELECT WORKDATE, DAYOFWEEK, WEEKOFDATE, STANDARD_HRS, HOURS_WORKED, VARIANCE, '' AS SPACER
--	FROM MISSING_TIME_DTL
--	WHERE EMP_CODE = @EMP_CODE 
--	AND STANDARD_HRS > HOURS_WORKED
--	ORDER BY WORKDATE
  END
IF @WK_TIME = 1	--Weekly 
  BEGIN 
	IF EXISTS(
			SELECT WORKDATE, DAYOFWEEK, WEEKOFDATE, STANDARD_HRS, HOURS_WORKED, VARIANCE, '' AS SPACER
			FROM MISSING_TIME_DTL
			WHERE EMP_CODE = @EMP_CODE AND WORKDATE = @ThisDate 			
	)
		SELECT 1
	ELSE
		SELECT 0
  
--	SELECT WEEKOFDATE, SUM(STANDARD_HRS) AS STANDARD_HRS, SUM(HOURS_WORKED) AS HOURS_WORKED
--	INTO #TMP2
--	FROM MISSING_TIME_DTL
--	WHERE EMP_CODE = @EMP_CODE
--	GROUP BY  WEEKOFDATE
--	HAVING SUM(STANDARD_HRS) > SUM(HOURS_WORKED)
--
--	SELECT MTD.WORKDATE, MTD.DAYOFWEEK, MTD.WEEKOFDATE, MTD.STANDARD_HRS, MTD.HOURS_WORKED, MTD.VARIANCE, '' AS SPACER
--	FROM MISSING_TIME_DTL MTD
--	   INNER JOIN #TMP2 ON #TMP2.WEEKOFDATE = MTD.WEEKOFDATE
--	WHERE MTD.EMP_CODE = @EMP_CODE 
--	ORDER BY MTD.WORKDATE
  END




