
CREATE PROCEDURE [dbo].[usp_wv_AD_NUMBER_GET_DETAILS] 
	@AD_NBR VARCHAR(30)
AS

    SELECT AD_NUMBER.AD_NBR,
           AD_NUMBER.AD_NBR_DESC,
           AD_NUMBER.ACTIVE,
           AD_NUMBER.DEF_BLKPLT_VER_CODE,
           AD_NUMBER.DEF_BLKPLT_VER2_CODE,
           AD_NUMBER.CL_CODE,
           AD_NUMBER.DOCUMENT_ID,
           CLIENT.CL_NAME,
           DOCUMENTS.FILENAME,
           DOCUMENTS.REPOSITORY_FILENAME,
           DOCUMENTS.MIME_TYPE,
           DOCUMENTS.DESCRIPTION,
           DOCUMENTS.KEYWORDS,
           DOCUMENTS.UPLOADED_DATE,
           DOCUMENTS.USER_CODE,
           DOCUMENTS.FILE_SIZE,
           DOCUMENTS.PRIVATE_FLAG,
           DOCUMENTS.DOCUMENT_TYPE_ID
		   ,AD_NUMBER.COLOR
    FROM   AD_NUMBER WITH (NOLOCK)
           LEFT OUTER JOIN DOCUMENTS WITH (NOLOCK)
                ON  AD_NUMBER.DOCUMENT_ID = DOCUMENTS.DOCUMENT_ID
           LEFT OUTER JOIN CLIENT WITH (NOLOCK)
                ON  AD_NUMBER.CL_CODE = CLIENT.CL_CODE
     WHERE  AD_NBR = @AD_NBR;	
	
