--DROP PROCEDURE [dbo].[usp_wv_ALERT_GET_ATTACHMENTS]
CREATE PROCEDURE [dbo].[usp_wv_ALERT_GET_ATTACHMENTS] /*WITH ENCRYPTION*/
@ALERT_ID INT,
@EMP_CODE VARCHAR(6),
@OFFSET [DECIMAL](9,3)
AS
/*=========== QUERY ===========*/
BEGIN	

	SELECT ALERT_ATTACHMENT.ATTACHMENT_ID,
			ALERT_ATTACHMENT.ALERT_ID,
			DOCUMENTS.FILENAME,
			[dbo].[advfn_local_date](@OFFSET, ALERT_ATTACHMENT.GENERATED_DATE) AS GENERATED_DATE,
			CASE WHEN USER_CODE_CP IS NULL OR USER_CODE_CP = 0 THEN ISNULL(EMPLOYEE.EMP_FNAME+' ','') + ISNULL(EMPLOYEE.EMP_MI+'. ','') + ISNULL(EMPLOYEE.EMP_LNAME,'')
			ELSE (SELECT CONT_FML FROM CDP_CONTACT_HDR WITH (NOLOCK) WHERE CDP_CONTACT_ID = USER_CODE_CP) END AS [USER_NAME],
			DOCUMENTS.MIME_TYPE,
			DOCUMENTS.REPOSITORY_FILENAME,
			DOCUMENTS.DOCUMENT_ID,
			DOCUMENTS.FILE_SIZE,
			CASE 
				WHEN DOCUMENTS.FILE_SIZE > 0 THEN CAST(DOCUMENTS.FILE_SIZE / 1024 AS INT)
				ELSE 0
			END AS FILE_SIZE_KB,
			DOCUMENTS.DESCRIPTION,
			ALERT_ATTACHMENT.USER_CODE,
			ISNULL(DOCUMENTS.PRIVATE_FLAG, 0) AS PRIVATE_FLAG,
			CASE 
				WHEN DOCUMENTS.PRIVATE_FLAG IS NULL OR DOCUMENTS.PRIVATE_FLAG = 0 THEN 	'No'
				ELSE 'Yes'
			END AS IS_PRIVATE,
			DOCUMENTS.PROOFHQ_URL,
			(SELECT COUNT(1) FROM DOCUMENTS DH WHERE DH.[FILENAME] = DOCUMENTS.[FILENAME]) AS HISTORY_COUNT
	FROM   EMPLOYEE WITH (NOLOCK) INNER JOIN
			SEC_USER WITH (NOLOCK) ON EMPLOYEE.EMP_CODE = SEC_USER.EMP_CODE RIGHT OUTER JOIN
			ALERT_ATTACHMENT WITH (NOLOCK) INNER JOIN
			DOCUMENTS WITH (NOLOCK) ON ALERT_ATTACHMENT.DOCUMENT_ID = DOCUMENTS.DOCUMENT_ID ON 
			UPPER(SEC_USER.USER_CODE) = UPPER(ALERT_ATTACHMENT.USER_CODE)
	WHERE  ALERT_ATTACHMENT.ALERT_ID = @ALERT_ID AND
			DOCUMENTS.DOCUMENT_ID IN (SELECT     
										MAX(ALERT_ATTACHMENT_1.DOCUMENT_ID) AS DOCUMENT_ID
										FROM          
										dbo.ALERT_ATTACHMENT AS ALERT_ATTACHMENT_1 INNER JOIN
										dbo.DOCUMENTS AS DOCUMENTS_1 ON ALERT_ATTACHMENT_1.DOCUMENT_ID = DOCUMENTS_1.DOCUMENT_ID
										GROUP BY 
										ALERT_ATTACHMENT_1.ALERT_ID, 
										DOCUMENTS_1.FILENAME)
	ORDER BY ALERT_ATTACHMENT.GENERATED_DATE;

END
/*=========== QUERY ===========*/