

/*****************************************************************
Webvantage
This Stored Procedure gets a Tasks By a Date, 
******************************************************************/
CREATE PROCEDURE [dbo].[usp_wv_calendar_workload_employee_all] 
@UserID VarChar(100),
@EmpCode Varchar(6),
@StartDate SmallDatetime,
@EndDate SmallDatetime,
@ClientCode Varchar(6),
@DivisionCode Varchar(6),
@ProductCode Varchar(6),
@JobNum Varchar(6),
@JobComp Varchar(6),
@Role VarChar(6),
@TaskStatus Varchar(1),
@ExcludeTempComplete Char(1)

AS
Declare @Rescrictions Int
Declare @RescrictionsEmp Int
--
--Set NoCount On
--
Select @Rescrictions = Count(*) 
FROM SEC_CLIENT
WHERE UPPER(USER_ID) = UPPER(@UserID)

Select @RescrictionsEmp = Count(*) 
FROM SEC_EMP
WHERE UPPER(USER_ID) = UPPER(@UserID)

if @Rescrictions > 0 and @RescrictionsEmp > 0
	If @ExcludeTempComplete = 'Y'
			SELECT     JOB_TRAFFIC_DET.JOB_NUMBER, JOB_TRAFFIC_DET.JOB_COMPONENT_NBR, JOB_TRAFFIC_DET.FNC_CODE, JOB_TRAFFIC_DET.TASK_DESCRIPTION, 
								  JOB_TRAFFIC_DET.JOB_HRS, JOB_TRAFFIC_DET.TASK_START_DATE, JOB_TRAFFIC_DET.JOB_REVISED_DATE, JOB_TRAFFIC_DET.EMP_CODE,
								  JOB_LOG.JOB_DESC, JOB_LOG.OFFICE_CODE, JOB_LOG.CL_CODE, JOB_LOG.DIV_CODE, JOB_LOG.PRD_CODE, CASE WHEN JOB_TRAFFIC_DET.TASK_START_DATE IS NULL THEN JOB_TRAFFIC_DET.JOB_REVISED_DATE ELSE JOB_TRAFFIC_DET.TASK_START_DATE END AS SORT
			FROM         JOB_COMPONENT INNER JOIN
								  JOB_TRAFFIC_DET ON JOB_COMPONENT.JOB_NUMBER = JOB_TRAFFIC_DET.JOB_NUMBER AND 
								  JOB_COMPONENT.JOB_COMPONENT_NBR = JOB_TRAFFIC_DET.JOB_COMPONENT_NBR INNER JOIN
											  JOB_LOG ON JOB_COMPONENT.JOB_NUMBER = JOB_LOG.JOB_NUMBER INNER JOIN
											  SEC_CLIENT ON JOB_LOG.CL_CODE = SEC_CLIENT.CL_CODE AND JOB_LOG.DIV_CODE = SEC_CLIENT.DIV_CODE AND 
											  JOB_LOG.PRD_CODE = SEC_CLIENT.PRD_CODE INNER JOIN
											  [dbo].[advtf_sec_emp] (@UserID) AS SEC_EMP ON JOB_TRAFFIC_DET.EMP_CODE = SEC_EMP.EMP_CODE LEFT OUTER JOIN
											  EMP_TRAFFIC_ROLE ON JOB_TRAFFIC_DET.EMP_CODE = EMP_TRAFFIC_ROLE.EMP_CODE LEFT OUTER JOIN
											  TASK_TRAFFIC_ROLE ON JOB_TRAFFIC_DET.FNC_CODE = TASK_TRAFFIC_ROLE.TRF_CODE
			WHERE     (JOB_COMPONENT.JOB_PROCESS_CONTRL <> 6) AND (JOB_COMPONENT.JOB_PROCESS_CONTRL <> 12) AND (JOB_TRAFFIC_DET.JOB_REVISED_DATE >= @StartDate) AND (JOB_TRAFFIC_DET.JOB_REVISED_DATE <= @EndDate)
								  AND JOB_TRAFFIC_DET.JOB_COMPLETED_DATE IS NULL AND JOB_LOG.CL_CODE Like '%' + @ClientCode AND JOB_LOG.DIV_CODE Like '%' + @DivisionCode AND JOB_LOG.PRD_CODE Like '%' + @ProductCode  
								  AND JOB_LOG.JOB_NUMBER Like '%' + @JobNum AND JOB_COMPONENT.JOB_COMPONENT_NBR Like '%' + @JobComp AND (ISNULL(TASK_TRAFFIC_ROLE.ROLE_CODE, '') Like '%' + @Role OR ISNULL(EMP_TRAFFIC_ROLE.ROLE_CODE, '') Like '%' + @Role) AND
								  ISNULL(JOB_TRAFFIC_DET.TASK_STATUS, '') Like Case @TaskStatus
																When 'P' Then 'P'
																			When 'A' Then 'A'
																When '' Then '%'
																	End AND JOB_TRAFFIC_DET.TEMP_COMP_DATE IS NULL AND (UPPER(SEC_CLIENT.USER_ID) = UPPER(@UserID)) AND (SEC_CLIENT.TIME_ENTRY = 0 OR SEC_CLIENT.TIME_ENTRY IS NULL) 
						AND JOB_TRAFFIC_DET.EMP_CODE IS NOT NULL
			 
			UNION
			SELECT     JOB_NUMBER, JOB_COMPONENT_NBR, FNC_CODE, NON_TASK_DESC AS TASK_DESCRIPTION, HOURS AS JOB_HRS,
					   CASE WHEN ALL_DAY = 1 THEN START_DATE ELSE (STR(DATEPART(month, START_DATE)) + '/' + STR(DATEPART(day, START_DATE)) + '/' + STR(DATEPART(year, START_DATE)) + ' ' + STR(DATEPART(hour, START_TIME)) + ':' + STR(DATEPART(minute, START_TIME)) + ':' + STR(DATEPART(second, START_TIME))) END AS TASK_START_DATE,
					   CASE WHEN ALL_DAY = 1 THEN END_DATE ELSE (STR(DATEPART(month, END_DATE)) + '/' + STR(DATEPART(day, END_DATE)) + '/' + STR(DATEPART(year, END_DATE)) + ' ' + STR(DATEPART(hour, END_TIME)) + ':' + STR(DATEPART(minute, END_TIME)) + ':' + STR(DATEPART(second, END_TIME))) END AS JOB_REVISED_DATE,  
								  EMP_CODE, '' AS JOB_DESC, 
								  '' AS OFFICE_CODE, '' AS CL_CODE, '' AS DIV_CODE, '' AS PRD_CODE,
								  CASE WHEN ALL_DAY = 1 THEN START_DATE ELSE (STR(DATEPART(month, START_DATE)) + '/' + STR(DATEPART(day, START_DATE)) + '/' + STR(DATEPART(year, START_DATE)) + ' ' + STR(DATEPART(hour, START_TIME)) + ':' + STR(DATEPART(minute, START_TIME)) + ':' + STR(DATEPART(second, START_TIME))) END AS SORT
			FROM         EMP_NON_TASKS	
			WHERE       (START_DATE >= @StartDate) AND (END_DATE <= @EndDate) AND 
										  (TYPE = 'H') 
			UNION
			SELECT     EMP_NON_TASKS.JOB_NUMBER, EMP_NON_TASKS.JOB_COMPONENT_NBR, EMP_NON_TASKS.FNC_CODE, EMP_NON_TASKS.NON_TASK_DESC AS TASK_DESCRIPTION, EMP_NON_TASKS.HOURS AS JOB_HRS,
					   CASE WHEN EMP_NON_TASKS.ALL_DAY = 1 THEN EMP_NON_TASKS.START_DATE ELSE (STR(DATEPART(month, EMP_NON_TASKS.START_DATE)) + '/' + STR(DATEPART(day, EMP_NON_TASKS.START_DATE)) + '/' + STR(DATEPART(year, EMP_NON_TASKS.START_DATE)) + ' ' + STR(DATEPART(hour, EMP_NON_TASKS.START_TIME)) + ':' + STR(DATEPART(minute, EMP_NON_TASKS.START_TIME)) + ':' + STR(DATEPART(second, EMP_NON_TASKS.START_TIME))) END AS TASK_START_DATE,
					   CASE WHEN EMP_NON_TASKS.ALL_DAY = 1 THEN EMP_NON_TASKS.END_DATE ELSE (STR(DATEPART(month, EMP_NON_TASKS.END_DATE)) + '/' + STR(DATEPART(day, EMP_NON_TASKS.END_DATE)) + '/' + STR(DATEPART(year, EMP_NON_TASKS.END_DATE)) + ' ' + STR(DATEPART(hour, EMP_NON_TASKS.END_TIME)) + ':' + STR(DATEPART(minute, EMP_NON_TASKS.END_TIME)) + ':' + STR(DATEPART(second, EMP_NON_TASKS.END_TIME))) END AS JOB_REVISED_DATE,  
								  EMP_NON_TASKS.EMP_CODE, '' AS JOB_DESC, 
								  '' AS OFFICE_CODE, '' AS CL_CODE, '' AS DIV_CODE, '' AS PRD_CODE,
								  CASE WHEN EMP_NON_TASKS.ALL_DAY = 1 THEN EMP_NON_TASKS.START_DATE ELSE (STR(DATEPART(month, EMP_NON_TASKS.START_DATE)) + '/' + STR(DATEPART(day, EMP_NON_TASKS.START_DATE)) + '/' + STR(DATEPART(year, EMP_NON_TASKS.START_DATE)) + ' ' + STR(DATEPART(hour, EMP_NON_TASKS.START_TIME)) + ':' + STR(DATEPART(minute, EMP_NON_TASKS.START_TIME)) + ':' + STR(DATEPART(second, EMP_NON_TASKS.START_TIME))) END AS SORT
			FROM         EMP_NON_TASKS INNER JOIN
                         [dbo].[advtf_sec_emp] (@UserID) AS SEC_EMP ON EMP_NON_TASKS.EMP_CODE = SEC_EMP.EMP_CODE	
			WHERE       (EMP_NON_TASKS.START_DATE >= @StartDate) AND (EMP_NON_TASKS.END_DATE <= @EndDate) AND 
										  (EMP_NON_TASKS.TYPE = 'A') 
			ORDER BY JOB_TRAFFIC_DET.EMP_CODE, SORT							  
										  
	Else
			SELECT     JOB_TRAFFIC_DET.JOB_NUMBER, JOB_TRAFFIC_DET.JOB_COMPONENT_NBR, JOB_TRAFFIC_DET.FNC_CODE, JOB_TRAFFIC_DET.TASK_DESCRIPTION, 
								  JOB_TRAFFIC_DET.JOB_HRS, JOB_TRAFFIC_DET.TASK_START_DATE, JOB_TRAFFIC_DET.JOB_REVISED_DATE, JOB_TRAFFIC_DET.EMP_CODE,
								  JOB_LOG.JOB_DESC, JOB_LOG.OFFICE_CODE, JOB_LOG.CL_CODE, JOB_LOG.DIV_CODE, JOB_LOG.PRD_CODE, CASE WHEN JOB_TRAFFIC_DET.TASK_START_DATE IS NULL THEN JOB_TRAFFIC_DET.JOB_REVISED_DATE ELSE JOB_TRAFFIC_DET.TASK_START_DATE END AS SORT
			FROM         JOB_COMPONENT INNER JOIN
								  JOB_TRAFFIC_DET ON JOB_COMPONENT.JOB_NUMBER = JOB_TRAFFIC_DET.JOB_NUMBER AND 
								  JOB_COMPONENT.JOB_COMPONENT_NBR = JOB_TRAFFIC_DET.JOB_COMPONENT_NBR INNER JOIN
											  JOB_LOG ON JOB_COMPONENT.JOB_NUMBER = JOB_LOG.JOB_NUMBER INNER JOIN
											  SEC_CLIENT ON JOB_LOG.CL_CODE = SEC_CLIENT.CL_CODE AND JOB_LOG.DIV_CODE = SEC_CLIENT.DIV_CODE AND 
											  JOB_LOG.PRD_CODE = SEC_CLIENT.PRD_CODE INNER JOIN
											  [dbo].[advtf_sec_emp] (@UserID) AS SEC_EMP ON JOB_TRAFFIC_DET.EMP_CODE = SEC_EMP.EMP_CODE LEFT OUTER JOIN
											  EMP_TRAFFIC_ROLE ON JOB_TRAFFIC_DET.EMP_CODE = EMP_TRAFFIC_ROLE.EMP_CODE LEFT OUTER JOIN
											  TASK_TRAFFIC_ROLE ON JOB_TRAFFIC_DET.FNC_CODE = TASK_TRAFFIC_ROLE.TRF_CODE
			WHERE     (JOB_COMPONENT.JOB_PROCESS_CONTRL <> 6) AND (JOB_COMPONENT.JOB_PROCESS_CONTRL <> 12) AND (JOB_TRAFFIC_DET.JOB_REVISED_DATE >= @StartDate) AND (JOB_TRAFFIC_DET.JOB_REVISED_DATE <= @EndDate) 
								AND JOB_TRAFFIC_DET.JOB_COMPLETED_DATE IS NULL AND JOB_LOG.CL_CODE Like '%' + @ClientCode AND JOB_LOG.DIV_CODE Like '%' + @DivisionCode AND JOB_LOG.PRD_CODE Like '%' + @ProductCode  
								  AND JOB_LOG.JOB_NUMBER Like '%' + @JobNum AND JOB_COMPONENT.JOB_COMPONENT_NBR Like '%' + @JobComp AND (ISNULL(TASK_TRAFFIC_ROLE.ROLE_CODE, '') Like '%' + @Role OR ISNULL(EMP_TRAFFIC_ROLE.ROLE_CODE, '') Like '%' + @Role) AND
								  ISNULL(JOB_TRAFFIC_DET.TASK_STATUS, '') Like Case @TaskStatus
																When 'P' Then 'P'
																			When 'A' Then 'A'
																When '' Then '%'
																	End AND (UPPER(SEC_CLIENT.USER_ID) = UPPER(@UserID)) AND (SEC_CLIENT.TIME_ENTRY = 0 OR SEC_CLIENT.TIME_ENTRY IS NULL) 
						AND JOB_TRAFFIC_DET.EMP_CODE IS NOT NULL 
			UNION
			SELECT     JOB_NUMBER, JOB_COMPONENT_NBR, FNC_CODE, NON_TASK_DESC AS TASK_DESCRIPTION, HOURS AS JOB_HRS,
					   CASE WHEN ALL_DAY = 1 THEN START_DATE ELSE (STR(DATEPART(month, START_DATE)) + '/' + STR(DATEPART(day, START_DATE)) + '/' + STR(DATEPART(year, START_DATE)) + ' ' + STR(DATEPART(hour, START_TIME)) + ':' + STR(DATEPART(minute, START_TIME)) + ':' + STR(DATEPART(second, START_TIME))) END AS TASK_START_DATE,
					   CASE WHEN ALL_DAY = 1 THEN END_DATE ELSE (STR(DATEPART(month, END_DATE)) + '/' + STR(DATEPART(day, END_DATE)) + '/' + STR(DATEPART(year, END_DATE)) + ' ' + STR(DATEPART(hour, END_TIME)) + ':' + STR(DATEPART(minute, END_TIME)) + ':' + STR(DATEPART(second, END_TIME))) END AS JOB_REVISED_DATE,  
								  EMP_CODE, '' AS JOB_DESC, 
								  '' AS OFFICE_CODE, '' AS CL_CODE, '' AS DIV_CODE, '' AS PRD_CODE,
								  CASE WHEN ALL_DAY = 1 THEN START_DATE ELSE (STR(DATEPART(month, START_DATE)) + '/' + STR(DATEPART(day, START_DATE)) + '/' + STR(DATEPART(year, START_DATE)) + ' ' + STR(DATEPART(hour, START_TIME)) + ':' + STR(DATEPART(minute, START_TIME)) + ':' + STR(DATEPART(second, START_TIME))) END AS SORT
			FROM         EMP_NON_TASKS	
			WHERE       (START_DATE >= @StartDate) AND (END_DATE <= @EndDate) AND 
										  (TYPE = 'H') 
			UNION
			SELECT     EMP_NON_TASKS.JOB_NUMBER, EMP_NON_TASKS.JOB_COMPONENT_NBR, EMP_NON_TASKS.FNC_CODE, EMP_NON_TASKS.NON_TASK_DESC AS TASK_DESCRIPTION, EMP_NON_TASKS.HOURS AS JOB_HRS,
					   CASE WHEN EMP_NON_TASKS.ALL_DAY = 1 THEN EMP_NON_TASKS.START_DATE ELSE (STR(DATEPART(month, EMP_NON_TASKS.START_DATE)) + '/' + STR(DATEPART(day, EMP_NON_TASKS.START_DATE)) + '/' + STR(DATEPART(year, EMP_NON_TASKS.START_DATE)) + ' ' + STR(DATEPART(hour, EMP_NON_TASKS.START_TIME)) + ':' + STR(DATEPART(minute, EMP_NON_TASKS.START_TIME)) + ':' + STR(DATEPART(second, EMP_NON_TASKS.START_TIME))) END AS TASK_START_DATE,
					   CASE WHEN EMP_NON_TASKS.ALL_DAY = 1 THEN EMP_NON_TASKS.END_DATE ELSE (STR(DATEPART(month, EMP_NON_TASKS.END_DATE)) + '/' + STR(DATEPART(day, EMP_NON_TASKS.END_DATE)) + '/' + STR(DATEPART(year, EMP_NON_TASKS.END_DATE)) + ' ' + STR(DATEPART(hour, EMP_NON_TASKS.END_TIME)) + ':' + STR(DATEPART(minute, EMP_NON_TASKS.END_TIME)) + ':' + STR(DATEPART(second, EMP_NON_TASKS.END_TIME))) END AS JOB_REVISED_DATE,  
								  EMP_NON_TASKS.EMP_CODE, '' AS JOB_DESC, 
								  '' AS OFFICE_CODE, '' AS CL_CODE, '' AS DIV_CODE, '' AS PRD_CODE,
								  CASE WHEN EMP_NON_TASKS.ALL_DAY = 1 THEN EMP_NON_TASKS.START_DATE ELSE (STR(DATEPART(month, EMP_NON_TASKS.START_DATE)) + '/' + STR(DATEPART(day, EMP_NON_TASKS.START_DATE)) + '/' + STR(DATEPART(year, EMP_NON_TASKS.START_DATE)) + ' ' + STR(DATEPART(hour, EMP_NON_TASKS.START_TIME)) + ':' + STR(DATEPART(minute, EMP_NON_TASKS.START_TIME)) + ':' + STR(DATEPART(second, EMP_NON_TASKS.START_TIME))) END AS SORT
			FROM         EMP_NON_TASKS INNER JOIN
                         [dbo].[advtf_sec_emp] (@UserID) AS SEC_EMP ON EMP_NON_TASKS.EMP_CODE = SEC_EMP.EMP_CODE	
			WHERE       (EMP_NON_TASKS.START_DATE >= @StartDate) AND (EMP_NON_TASKS.END_DATE <= @EndDate) AND 
										  (EMP_NON_TASKS.TYPE = 'A') 
			ORDER BY JOB_TRAFFIC_DET.EMP_CODE, SORT	
if @Rescrictions = 0 and @RescrictionsEmp > 0
	If @ExcludeTempComplete = 'Y'
			SELECT     JOB_TRAFFIC_DET.JOB_NUMBER, JOB_TRAFFIC_DET.JOB_COMPONENT_NBR, JOB_TRAFFIC_DET.FNC_CODE, JOB_TRAFFIC_DET.TASK_DESCRIPTION, 
								  JOB_TRAFFIC_DET.JOB_HRS, JOB_TRAFFIC_DET.TASK_START_DATE, JOB_TRAFFIC_DET.JOB_REVISED_DATE, JOB_TRAFFIC_DET.EMP_CODE,
								  JOB_LOG.JOB_DESC, JOB_LOG.OFFICE_CODE, JOB_LOG.CL_CODE, JOB_LOG.DIV_CODE, JOB_LOG.PRD_CODE, CASE WHEN JOB_TRAFFIC_DET.TASK_START_DATE IS NULL THEN JOB_TRAFFIC_DET.JOB_REVISED_DATE ELSE JOB_TRAFFIC_DET.TASK_START_DATE END AS SORT
			FROM         JOB_COMPONENT INNER JOIN
								  JOB_TRAFFIC_DET ON JOB_COMPONENT.JOB_NUMBER = JOB_TRAFFIC_DET.JOB_NUMBER AND 
								  JOB_COMPONENT.JOB_COMPONENT_NBR = JOB_TRAFFIC_DET.JOB_COMPONENT_NBR INNER JOIN
											  JOB_LOG ON JOB_COMPONENT.JOB_NUMBER = JOB_LOG.JOB_NUMBER INNER JOIN
											  [dbo].[advtf_sec_emp] (@UserID) AS SEC_EMP ON JOB_TRAFFIC_DET.EMP_CODE = SEC_EMP.EMP_CODE LEFT OUTER JOIN
											  EMP_TRAFFIC_ROLE ON JOB_TRAFFIC_DET.EMP_CODE = EMP_TRAFFIC_ROLE.EMP_CODE LEFT OUTER JOIN
											  TASK_TRAFFIC_ROLE ON JOB_TRAFFIC_DET.FNC_CODE = TASK_TRAFFIC_ROLE.TRF_CODE
			WHERE     (JOB_COMPONENT.JOB_PROCESS_CONTRL <> 6) AND (JOB_COMPONENT.JOB_PROCESS_CONTRL <> 12) AND (JOB_TRAFFIC_DET.JOB_REVISED_DATE >= @StartDate) AND (JOB_TRAFFIC_DET.JOB_REVISED_DATE <= @EndDate) AND 
								   JOB_TRAFFIC_DET.JOB_COMPLETED_DATE IS NULL AND JOB_LOG.CL_CODE Like '%' + @ClientCode AND JOB_LOG.DIV_CODE Like '%' + @DivisionCode AND JOB_LOG.PRD_CODE Like '%' + @ProductCode  
								  AND JOB_LOG.JOB_NUMBER Like '%' + @JobNum AND JOB_COMPONENT.JOB_COMPONENT_NBR Like '%' + @JobComp AND (ISNULL(TASK_TRAFFIC_ROLE.ROLE_CODE, '') Like '%' + @Role OR ISNULL(EMP_TRAFFIC_ROLE.ROLE_CODE, '') Like '%' + @Role) AND
								  ISNULL(JOB_TRAFFIC_DET.TASK_STATUS, '') Like Case @TaskStatus
																When 'P' Then 'P'
																			When 'A' Then 'A'
																When '' Then '%'
																	End AND JOB_TRAFFIC_DET.TEMP_COMP_DATE IS NULL 
						AND JOB_TRAFFIC_DET.EMP_CODE IS NOT NULL 
			UNION
			SELECT     JOB_NUMBER, JOB_COMPONENT_NBR, FNC_CODE, NON_TASK_DESC AS TASK_DESCRIPTION, HOURS AS JOB_HRS,
					   CASE WHEN ALL_DAY = 1 THEN START_DATE ELSE (STR(DATEPART(month, START_DATE)) + '/' + STR(DATEPART(day, START_DATE)) + '/' + STR(DATEPART(year, START_DATE)) + ' ' + STR(DATEPART(hour, START_TIME)) + ':' + STR(DATEPART(minute, START_TIME)) + ':' + STR(DATEPART(second, START_TIME))) END AS TASK_START_DATE,
					   CASE WHEN ALL_DAY = 1 THEN END_DATE ELSE (STR(DATEPART(month, END_DATE)) + '/' + STR(DATEPART(day, END_DATE)) + '/' + STR(DATEPART(year, END_DATE)) + ' ' + STR(DATEPART(hour, END_TIME)) + ':' + STR(DATEPART(minute, END_TIME)) + ':' + STR(DATEPART(second, END_TIME))) END AS JOB_REVISED_DATE,  
								  EMP_CODE, '' AS JOB_DESC, 
								  '' AS OFFICE_CODE, '' AS CL_CODE, '' AS DIV_CODE, '' AS PRD_CODE,
								  CASE WHEN ALL_DAY = 1 THEN START_DATE ELSE (STR(DATEPART(month, START_DATE)) + '/' + STR(DATEPART(day, START_DATE)) + '/' + STR(DATEPART(year, START_DATE)) + ' ' + STR(DATEPART(hour, START_TIME)) + ':' + STR(DATEPART(minute, START_TIME)) + ':' + STR(DATEPART(second, START_TIME))) END AS SORT
			FROM         EMP_NON_TASKS	
			WHERE       (START_DATE >= @StartDate) AND (END_DATE <= @EndDate) AND 
										  (TYPE = 'H') 
			UNION
			SELECT     EMP_NON_TASKS.JOB_NUMBER, EMP_NON_TASKS.JOB_COMPONENT_NBR, EMP_NON_TASKS.FNC_CODE, EMP_NON_TASKS.NON_TASK_DESC AS TASK_DESCRIPTION, EMP_NON_TASKS.HOURS AS JOB_HRS,
					   CASE WHEN EMP_NON_TASKS.ALL_DAY = 1 THEN EMP_NON_TASKS.START_DATE ELSE (STR(DATEPART(month, EMP_NON_TASKS.START_DATE)) + '/' + STR(DATEPART(day, EMP_NON_TASKS.START_DATE)) + '/' + STR(DATEPART(year, EMP_NON_TASKS.START_DATE)) + ' ' + STR(DATEPART(hour, EMP_NON_TASKS.START_TIME)) + ':' + STR(DATEPART(minute, EMP_NON_TASKS.START_TIME)) + ':' + STR(DATEPART(second, EMP_NON_TASKS.START_TIME))) END AS TASK_START_DATE,
					   CASE WHEN EMP_NON_TASKS.ALL_DAY = 1 THEN EMP_NON_TASKS.END_DATE ELSE (STR(DATEPART(month, EMP_NON_TASKS.END_DATE)) + '/' + STR(DATEPART(day, EMP_NON_TASKS.END_DATE)) + '/' + STR(DATEPART(year, EMP_NON_TASKS.END_DATE)) + ' ' + STR(DATEPART(hour, EMP_NON_TASKS.END_TIME)) + ':' + STR(DATEPART(minute, EMP_NON_TASKS.END_TIME)) + ':' + STR(DATEPART(second, EMP_NON_TASKS.END_TIME))) END AS JOB_REVISED_DATE,  
								  EMP_NON_TASKS.EMP_CODE, '' AS JOB_DESC, 
								  '' AS OFFICE_CODE, '' AS CL_CODE, '' AS DIV_CODE, '' AS PRD_CODE,
								  CASE WHEN EMP_NON_TASKS.ALL_DAY = 1 THEN EMP_NON_TASKS.START_DATE ELSE (STR(DATEPART(month, EMP_NON_TASKS.START_DATE)) + '/' + STR(DATEPART(day, EMP_NON_TASKS.START_DATE)) + '/' + STR(DATEPART(year, EMP_NON_TASKS.START_DATE)) + ' ' + STR(DATEPART(hour, EMP_NON_TASKS.START_TIME)) + ':' + STR(DATEPART(minute, EMP_NON_TASKS.START_TIME)) + ':' + STR(DATEPART(second, EMP_NON_TASKS.START_TIME))) END AS SORT
			FROM         EMP_NON_TASKS INNER JOIN
                         [dbo].[advtf_sec_emp] (@UserID) AS SEC_EMP ON EMP_NON_TASKS.EMP_CODE = SEC_EMP.EMP_CODE	
			WHERE       (EMP_NON_TASKS.START_DATE >= @StartDate) AND (EMP_NON_TASKS.END_DATE <= @EndDate) AND 
										  (EMP_NON_TASKS.TYPE = 'A') 
			ORDER BY JOB_TRAFFIC_DET.EMP_CODE, SORT							  
										  
	Else
			SELECT     JOB_TRAFFIC_DET.JOB_NUMBER, JOB_TRAFFIC_DET.JOB_COMPONENT_NBR, JOB_TRAFFIC_DET.FNC_CODE, JOB_TRAFFIC_DET.TASK_DESCRIPTION, 
								  JOB_TRAFFIC_DET.JOB_HRS, JOB_TRAFFIC_DET.TASK_START_DATE, JOB_TRAFFIC_DET.JOB_REVISED_DATE, JOB_TRAFFIC_DET.EMP_CODE,
								  JOB_LOG.JOB_DESC, JOB_LOG.OFFICE_CODE, JOB_LOG.CL_CODE, JOB_LOG.DIV_CODE, JOB_LOG.PRD_CODE, CASE WHEN JOB_TRAFFIC_DET.TASK_START_DATE IS NULL THEN JOB_TRAFFIC_DET.JOB_REVISED_DATE ELSE JOB_TRAFFIC_DET.TASK_START_DATE END AS SORT
			FROM         JOB_COMPONENT INNER JOIN
								  JOB_TRAFFIC_DET ON JOB_COMPONENT.JOB_NUMBER = JOB_TRAFFIC_DET.JOB_NUMBER AND 
								  JOB_COMPONENT.JOB_COMPONENT_NBR = JOB_TRAFFIC_DET.JOB_COMPONENT_NBR INNER JOIN
											  JOB_LOG ON JOB_COMPONENT.JOB_NUMBER = JOB_LOG.JOB_NUMBER INNER JOIN
											  [dbo].[advtf_sec_emp] (@UserID) AS SEC_EMP ON JOB_TRAFFIC_DET.EMP_CODE = SEC_EMP.EMP_CODE LEFT OUTER JOIN
											  EMP_TRAFFIC_ROLE ON JOB_TRAFFIC_DET.EMP_CODE = EMP_TRAFFIC_ROLE.EMP_CODE LEFT OUTER JOIN
											  TASK_TRAFFIC_ROLE ON JOB_TRAFFIC_DET.FNC_CODE = TASK_TRAFFIC_ROLE.TRF_CODE
			WHERE     (JOB_COMPONENT.JOB_PROCESS_CONTRL <> 6) AND (JOB_COMPONENT.JOB_PROCESS_CONTRL <> 12) AND (JOB_TRAFFIC_DET.JOB_REVISED_DATE >= @StartDate) AND (JOB_TRAFFIC_DET.JOB_REVISED_DATE <= @EndDate) AND 
								   JOB_TRAFFIC_DET.JOB_COMPLETED_DATE IS NULL AND JOB_LOG.CL_CODE Like '%' + @ClientCode AND JOB_LOG.DIV_CODE Like '%' + @DivisionCode AND JOB_LOG.PRD_CODE Like '%' + @ProductCode  
								  AND JOB_LOG.JOB_NUMBER Like '%' + @JobNum AND JOB_COMPONENT.JOB_COMPONENT_NBR Like '%' + @JobComp AND (ISNULL(TASK_TRAFFIC_ROLE.ROLE_CODE, '') Like '%' + @Role OR ISNULL(EMP_TRAFFIC_ROLE.ROLE_CODE, '') Like '%' + @Role) AND
								  ISNULL(JOB_TRAFFIC_DET.TASK_STATUS, '') Like Case @TaskStatus
																When 'P' Then 'P'
																			When 'A' Then 'A'
																When '' Then '%'
																	End
						AND JOB_TRAFFIC_DET.EMP_CODE IS NOT NULL 
			UNION
			SELECT     JOB_NUMBER, JOB_COMPONENT_NBR, FNC_CODE, NON_TASK_DESC AS TASK_DESCRIPTION, HOURS AS JOB_HRS,
					   CASE WHEN ALL_DAY = 1 THEN START_DATE ELSE (STR(DATEPART(month, START_DATE)) + '/' + STR(DATEPART(day, START_DATE)) + '/' + STR(DATEPART(year, START_DATE)) + ' ' + STR(DATEPART(hour, START_TIME)) + ':' + STR(DATEPART(minute, START_TIME)) + ':' + STR(DATEPART(second, START_TIME))) END AS TASK_START_DATE,
					   CASE WHEN ALL_DAY = 1 THEN END_DATE ELSE (STR(DATEPART(month, END_DATE)) + '/' + STR(DATEPART(day, END_DATE)) + '/' + STR(DATEPART(year, END_DATE)) + ' ' + STR(DATEPART(hour, END_TIME)) + ':' + STR(DATEPART(minute, END_TIME)) + ':' + STR(DATEPART(second, END_TIME))) END AS JOB_REVISED_DATE,  
								  EMP_CODE, '' AS JOB_DESC, 
								  '' AS OFFICE_CODE, '' AS CL_CODE, '' AS DIV_CODE, '' AS PRD_CODE,
								  CASE WHEN ALL_DAY = 1 THEN START_DATE ELSE (STR(DATEPART(month, START_DATE)) + '/' + STR(DATEPART(day, START_DATE)) + '/' + STR(DATEPART(year, START_DATE)) + ' ' + STR(DATEPART(hour, START_TIME)) + ':' + STR(DATEPART(minute, START_TIME)) + ':' + STR(DATEPART(second, START_TIME))) END AS SORT
			FROM         EMP_NON_TASKS	
			WHERE       (START_DATE >= @StartDate) AND (END_DATE <= @EndDate) AND 
										  (TYPE = 'H') 
			UNION
			SELECT     EMP_NON_TASKS.JOB_NUMBER, EMP_NON_TASKS.JOB_COMPONENT_NBR, EMP_NON_TASKS.FNC_CODE, EMP_NON_TASKS.NON_TASK_DESC AS TASK_DESCRIPTION, EMP_NON_TASKS.HOURS AS JOB_HRS,
					   CASE WHEN EMP_NON_TASKS.ALL_DAY = 1 THEN EMP_NON_TASKS.START_DATE ELSE (STR(DATEPART(month, EMP_NON_TASKS.START_DATE)) + '/' + STR(DATEPART(day, EMP_NON_TASKS.START_DATE)) + '/' + STR(DATEPART(year, EMP_NON_TASKS.START_DATE)) + ' ' + STR(DATEPART(hour, EMP_NON_TASKS.START_TIME)) + ':' + STR(DATEPART(minute, EMP_NON_TASKS.START_TIME)) + ':' + STR(DATEPART(second, EMP_NON_TASKS.START_TIME))) END AS TASK_START_DATE,
					   CASE WHEN EMP_NON_TASKS.ALL_DAY = 1 THEN EMP_NON_TASKS.END_DATE ELSE (STR(DATEPART(month, EMP_NON_TASKS.END_DATE)) + '/' + STR(DATEPART(day, EMP_NON_TASKS.END_DATE)) + '/' + STR(DATEPART(year, EMP_NON_TASKS.END_DATE)) + ' ' + STR(DATEPART(hour, EMP_NON_TASKS.END_TIME)) + ':' + STR(DATEPART(minute, EMP_NON_TASKS.END_TIME)) + ':' + STR(DATEPART(second, EMP_NON_TASKS.END_TIME))) END AS JOB_REVISED_DATE,  
								  EMP_NON_TASKS.EMP_CODE, '' AS JOB_DESC, 
								  '' AS OFFICE_CODE, '' AS CL_CODE, '' AS DIV_CODE, '' AS PRD_CODE,
								  CASE WHEN EMP_NON_TASKS.ALL_DAY = 1 THEN EMP_NON_TASKS.START_DATE ELSE (STR(DATEPART(month, EMP_NON_TASKS.START_DATE)) + '/' + STR(DATEPART(day, EMP_NON_TASKS.START_DATE)) + '/' + STR(DATEPART(year, EMP_NON_TASKS.START_DATE)) + ' ' + STR(DATEPART(hour, EMP_NON_TASKS.START_TIME)) + ':' + STR(DATEPART(minute, EMP_NON_TASKS.START_TIME)) + ':' + STR(DATEPART(second, EMP_NON_TASKS.START_TIME))) END AS SORT
			FROM         EMP_NON_TASKS INNER JOIN
                         [dbo].[advtf_sec_emp] (@UserID) AS SEC_EMP ON EMP_NON_TASKS.EMP_CODE = SEC_EMP.EMP_CODE	
			WHERE       (EMP_NON_TASKS.START_DATE >= @StartDate) AND (EMP_NON_TASKS.END_DATE <= @EndDate) AND 
										  (EMP_NON_TASKS.TYPE = 'A')	
			ORDER BY JOB_TRAFFIC_DET.EMP_CODE, SORT	
if @Rescrictions > 0 and @RescrictionsEmp = 0
	If @ExcludeTempComplete = 'Y'
			SELECT     JOB_TRAFFIC_DET.JOB_NUMBER, JOB_TRAFFIC_DET.JOB_COMPONENT_NBR, JOB_TRAFFIC_DET.FNC_CODE, JOB_TRAFFIC_DET.TASK_DESCRIPTION, 
								  JOB_TRAFFIC_DET.JOB_HRS, JOB_TRAFFIC_DET.TASK_START_DATE, JOB_TRAFFIC_DET.JOB_REVISED_DATE, JOB_TRAFFIC_DET.EMP_CODE,
								  JOB_LOG.JOB_DESC, JOB_LOG.OFFICE_CODE, JOB_LOG.CL_CODE, JOB_LOG.DIV_CODE, JOB_LOG.PRD_CODE, CASE WHEN JOB_TRAFFIC_DET.TASK_START_DATE IS NULL THEN JOB_TRAFFIC_DET.JOB_REVISED_DATE ELSE JOB_TRAFFIC_DET.TASK_START_DATE END AS SORT
			FROM         JOB_COMPONENT INNER JOIN
								  JOB_TRAFFIC_DET ON JOB_COMPONENT.JOB_NUMBER = JOB_TRAFFIC_DET.JOB_NUMBER AND 
								  JOB_COMPONENT.JOB_COMPONENT_NBR = JOB_TRAFFIC_DET.JOB_COMPONENT_NBR INNER JOIN
											  JOB_LOG ON JOB_COMPONENT.JOB_NUMBER = JOB_LOG.JOB_NUMBER INNER JOIN
											  SEC_CLIENT ON JOB_LOG.CL_CODE = SEC_CLIENT.CL_CODE AND JOB_LOG.DIV_CODE = SEC_CLIENT.DIV_CODE AND 
											  JOB_LOG.PRD_CODE = SEC_CLIENT.PRD_CODE LEFT OUTER JOIN
											  EMP_TRAFFIC_ROLE ON JOB_TRAFFIC_DET.EMP_CODE = EMP_TRAFFIC_ROLE.EMP_CODE LEFT OUTER JOIN
											  TASK_TRAFFIC_ROLE ON JOB_TRAFFIC_DET.FNC_CODE = TASK_TRAFFIC_ROLE.TRF_CODE
			WHERE     (JOB_COMPONENT.JOB_PROCESS_CONTRL <> 6) AND (JOB_COMPONENT.JOB_PROCESS_CONTRL <> 12) AND (JOB_TRAFFIC_DET.JOB_REVISED_DATE >= @StartDate) AND (JOB_TRAFFIC_DET.JOB_REVISED_DATE <= @EndDate) AND 
								  JOB_TRAFFIC_DET.JOB_COMPLETED_DATE IS NULL AND JOB_LOG.CL_CODE Like '%' + @ClientCode AND JOB_LOG.DIV_CODE Like '%' + @DivisionCode AND JOB_LOG.PRD_CODE Like '%' + @ProductCode  
								  AND JOB_LOG.JOB_NUMBER Like '%' + @JobNum AND JOB_COMPONENT.JOB_COMPONENT_NBR Like '%' + @JobComp AND (ISNULL(TASK_TRAFFIC_ROLE.ROLE_CODE, '') Like '%' + @Role OR ISNULL(EMP_TRAFFIC_ROLE.ROLE_CODE, '') Like '%' + @Role) AND
								  ISNULL(JOB_TRAFFIC_DET.TASK_STATUS, '') Like Case @TaskStatus
																When 'P' Then 'P'
																			When 'A' Then 'A'
																When '' Then '%'
																	End AND JOB_TRAFFIC_DET.TEMP_COMP_DATE IS NULL AND (UPPER(SEC_CLIENT.USER_ID) = UPPER(@UserID)) AND (SEC_CLIENT.TIME_ENTRY = 0 OR SEC_CLIENT.TIME_ENTRY IS NULL)
				AND JOB_TRAFFIC_DET.EMP_CODE IS NOT NULL 
			UNION
			SELECT     JOB_NUMBER, JOB_COMPONENT_NBR, FNC_CODE, NON_TASK_DESC AS TASK_DESCRIPTION, HOURS AS JOB_HRS,
					   CASE WHEN ALL_DAY = 1 THEN START_DATE ELSE (STR(DATEPART(month, START_DATE)) + '/' + STR(DATEPART(day, START_DATE)) + '/' + STR(DATEPART(year, START_DATE)) + ' ' + STR(DATEPART(hour, START_TIME)) + ':' + STR(DATEPART(minute, START_TIME)) + ':' + STR(DATEPART(second, START_TIME))) END AS TASK_START_DATE,
					   CASE WHEN ALL_DAY = 1 THEN END_DATE ELSE (STR(DATEPART(month, END_DATE)) + '/' + STR(DATEPART(day, END_DATE)) + '/' + STR(DATEPART(year, END_DATE)) + ' ' + STR(DATEPART(hour, END_TIME)) + ':' + STR(DATEPART(minute, END_TIME)) + ':' + STR(DATEPART(second, END_TIME))) END AS JOB_REVISED_DATE,  
								  EMP_CODE, '' AS JOB_DESC, 
								  '' AS OFFICE_CODE, '' AS CL_CODE, '' AS DIV_CODE, '' AS PRD_CODE,
								  CASE WHEN ALL_DAY = 1 THEN START_DATE ELSE (STR(DATEPART(month, START_DATE)) + '/' + STR(DATEPART(day, START_DATE)) + '/' + STR(DATEPART(year, START_DATE)) + ' ' + STR(DATEPART(hour, START_TIME)) + ':' + STR(DATEPART(minute, START_TIME)) + ':' + STR(DATEPART(second, START_TIME))) END AS SORT
			FROM         EMP_NON_TASKS	
			WHERE       (START_DATE >= @StartDate) AND (END_DATE <= @EndDate) AND 
										  (TYPE = 'H') 
			UNION
			SELECT     JOB_NUMBER, JOB_COMPONENT_NBR, FNC_CODE, NON_TASK_DESC AS TASK_DESCRIPTION, HOURS AS JOB_HRS,
					   CASE WHEN ALL_DAY = 1 THEN START_DATE ELSE (STR(DATEPART(month, START_DATE)) + '/' + STR(DATEPART(day, START_DATE)) + '/' + STR(DATEPART(year, START_DATE)) + ' ' + STR(DATEPART(hour, START_TIME)) + ':' + STR(DATEPART(minute, START_TIME)) + ':' + STR(DATEPART(second, START_TIME))) END AS TASK_START_DATE,
					   CASE WHEN ALL_DAY = 1 THEN END_DATE ELSE (STR(DATEPART(month, END_DATE)) + '/' + STR(DATEPART(day, END_DATE)) + '/' + STR(DATEPART(year, END_DATE)) + ' ' + STR(DATEPART(hour, END_TIME)) + ':' + STR(DATEPART(minute, END_TIME)) + ':' + STR(DATEPART(second, END_TIME))) END AS JOB_REVISED_DATE,  
								  EMP_CODE, '' AS JOB_DESC, 
								  '' AS OFFICE_CODE, '' AS CL_CODE, '' AS DIV_CODE, '' AS PRD_CODE,
								  CASE WHEN ALL_DAY = 1 THEN START_DATE ELSE (STR(DATEPART(month, START_DATE)) + '/' + STR(DATEPART(day, START_DATE)) + '/' + STR(DATEPART(year, START_DATE)) + ' ' + STR(DATEPART(hour, START_TIME)) + ':' + STR(DATEPART(minute, START_TIME)) + ':' + STR(DATEPART(second, START_TIME))) END AS SORT
			FROM         EMP_NON_TASKS	
			WHERE       (START_DATE >= @StartDate) AND (END_DATE <= @EndDate) AND 
										  (TYPE = 'A')
			ORDER BY JOB_TRAFFIC_DET.EMP_CODE, SORT							  
										  
	Else
			SELECT     JOB_TRAFFIC_DET.JOB_NUMBER, JOB_TRAFFIC_DET.JOB_COMPONENT_NBR, JOB_TRAFFIC_DET.FNC_CODE, JOB_TRAFFIC_DET.TASK_DESCRIPTION, 
								  JOB_TRAFFIC_DET.JOB_HRS, JOB_TRAFFIC_DET.TASK_START_DATE, JOB_TRAFFIC_DET.JOB_REVISED_DATE, JOB_TRAFFIC_DET.EMP_CODE,
								  JOB_LOG.JOB_DESC, JOB_LOG.OFFICE_CODE, JOB_LOG.CL_CODE, JOB_LOG.DIV_CODE, JOB_LOG.PRD_CODE, CASE WHEN JOB_TRAFFIC_DET.TASK_START_DATE IS NULL THEN JOB_TRAFFIC_DET.JOB_REVISED_DATE ELSE JOB_TRAFFIC_DET.TASK_START_DATE END AS SORT
			FROM         JOB_COMPONENT INNER JOIN
								  JOB_TRAFFIC_DET ON JOB_COMPONENT.JOB_NUMBER = JOB_TRAFFIC_DET.JOB_NUMBER AND 
								  JOB_COMPONENT.JOB_COMPONENT_NBR = JOB_TRAFFIC_DET.JOB_COMPONENT_NBR INNER JOIN
											  JOB_LOG ON JOB_COMPONENT.JOB_NUMBER = JOB_LOG.JOB_NUMBER INNER JOIN
											  SEC_CLIENT ON JOB_LOG.CL_CODE = SEC_CLIENT.CL_CODE AND JOB_LOG.DIV_CODE = SEC_CLIENT.DIV_CODE AND 
											  JOB_LOG.PRD_CODE = SEC_CLIENT.PRD_CODE LEFT OUTER JOIN
											  EMP_TRAFFIC_ROLE ON JOB_TRAFFIC_DET.EMP_CODE = EMP_TRAFFIC_ROLE.EMP_CODE LEFT OUTER JOIN
											  TASK_TRAFFIC_ROLE ON JOB_TRAFFIC_DET.FNC_CODE = TASK_TRAFFIC_ROLE.TRF_CODE
			WHERE     (JOB_COMPONENT.JOB_PROCESS_CONTRL <> 6) AND (JOB_COMPONENT.JOB_PROCESS_CONTRL <> 12) AND (JOB_TRAFFIC_DET.JOB_REVISED_DATE >= @StartDate) AND (JOB_TRAFFIC_DET.JOB_REVISED_DATE <= @EndDate) AND 
								   JOB_TRAFFIC_DET.JOB_COMPLETED_DATE IS NULL AND JOB_LOG.CL_CODE Like '%' + @ClientCode AND JOB_LOG.DIV_CODE Like '%' + @DivisionCode AND JOB_LOG.PRD_CODE Like '%' + @ProductCode  
								  AND JOB_LOG.JOB_NUMBER Like '%' + @JobNum AND JOB_COMPONENT.JOB_COMPONENT_NBR Like '%' + @JobComp AND (ISNULL(TASK_TRAFFIC_ROLE.ROLE_CODE, '') Like '%' + @Role OR ISNULL(EMP_TRAFFIC_ROLE.ROLE_CODE, '') Like '%' + @Role) AND
								  ISNULL(JOB_TRAFFIC_DET.TASK_STATUS, '') Like Case @TaskStatus
																When 'P' Then 'P'
																			When 'A' Then 'A'
																When '' Then '%'
																	End AND (UPPER(SEC_CLIENT.USER_ID) = UPPER(@UserID)) AND (SEC_CLIENT.TIME_ENTRY = 0 OR SEC_CLIENT.TIME_ENTRY IS NULL)
					AND JOB_TRAFFIC_DET.EMP_CODE IS NOT NULL 
			UNION
			SELECT     JOB_NUMBER, JOB_COMPONENT_NBR, FNC_CODE, NON_TASK_DESC AS TASK_DESCRIPTION, HOURS AS JOB_HRS,
					   CASE WHEN ALL_DAY = 1 THEN START_DATE ELSE (STR(DATEPART(month, START_DATE)) + '/' + STR(DATEPART(day, START_DATE)) + '/' + STR(DATEPART(year, START_DATE)) + ' ' + STR(DATEPART(hour, START_TIME)) + ':' + STR(DATEPART(minute, START_TIME)) + ':' + STR(DATEPART(second, START_TIME))) END AS TASK_START_DATE,
					   CASE WHEN ALL_DAY = 1 THEN END_DATE ELSE (STR(DATEPART(month, END_DATE)) + '/' + STR(DATEPART(day, END_DATE)) + '/' + STR(DATEPART(year, END_DATE)) + ' ' + STR(DATEPART(hour, END_TIME)) + ':' + STR(DATEPART(minute, END_TIME)) + ':' + STR(DATEPART(second, END_TIME))) END AS JOB_REVISED_DATE,  
								  EMP_CODE, '' AS JOB_DESC, 
								  '' AS OFFICE_CODE, '' AS CL_CODE, '' AS DIV_CODE, '' AS PRD_CODE,
								  CASE WHEN ALL_DAY = 1 THEN START_DATE ELSE (STR(DATEPART(month, START_DATE)) + '/' + STR(DATEPART(day, START_DATE)) + '/' + STR(DATEPART(year, START_DATE)) + ' ' + STR(DATEPART(hour, START_TIME)) + ':' + STR(DATEPART(minute, START_TIME)) + ':' + STR(DATEPART(second, START_TIME))) END AS SORT
			FROM         EMP_NON_TASKS	
			WHERE       (START_DATE >= @StartDate) AND (END_DATE <= @EndDate) AND 
										  (TYPE = 'H') 
			UNION
			SELECT     JOB_NUMBER, JOB_COMPONENT_NBR, FNC_CODE, NON_TASK_DESC AS TASK_DESCRIPTION, HOURS AS JOB_HRS,
					   CASE WHEN ALL_DAY = 1 THEN START_DATE ELSE (STR(DATEPART(month, START_DATE)) + '/' + STR(DATEPART(day, START_DATE)) + '/' + STR(DATEPART(year, START_DATE)) + ' ' + STR(DATEPART(hour, START_TIME)) + ':' + STR(DATEPART(minute, START_TIME)) + ':' + STR(DATEPART(second, START_TIME))) END AS TASK_START_DATE,
					   CASE WHEN ALL_DAY = 1 THEN END_DATE ELSE (STR(DATEPART(month, END_DATE)) + '/' + STR(DATEPART(day, END_DATE)) + '/' + STR(DATEPART(year, END_DATE)) + ' ' + STR(DATEPART(hour, END_TIME)) + ':' + STR(DATEPART(minute, END_TIME)) + ':' + STR(DATEPART(second, END_TIME))) END AS JOB_REVISED_DATE,  
								  EMP_CODE, '' AS JOB_DESC, 
								  '' AS OFFICE_CODE, '' AS CL_CODE, '' AS DIV_CODE, '' AS PRD_CODE,
								  CASE WHEN ALL_DAY = 1 THEN START_DATE ELSE (STR(DATEPART(month, START_DATE)) + '/' + STR(DATEPART(day, START_DATE)) + '/' + STR(DATEPART(year, START_DATE)) + ' ' + STR(DATEPART(hour, START_TIME)) + ':' + STR(DATEPART(minute, START_TIME)) + ':' + STR(DATEPART(second, START_TIME))) END AS SORT
			FROM         EMP_NON_TASKS	
			WHERE       (START_DATE >= @StartDate) AND (END_DATE <= @EndDate) AND 
										  (TYPE = 'A')	
			ORDER BY JOB_TRAFFIC_DET.EMP_CODE, SORT							  						  
if @Rescrictions = 0 and @RescrictionsEmp = 0
	if @ExcludeTempComplete = 'Y'									 
		SELECT     JOB_TRAFFIC_DET.JOB_NUMBER, JOB_TRAFFIC_DET.JOB_COMPONENT_NBR, JOB_TRAFFIC_DET.FNC_CODE, JOB_TRAFFIC_DET.TASK_DESCRIPTION, 
								  JOB_TRAFFIC_DET.JOB_HRS, JOB_TRAFFIC_DET.TASK_START_DATE, JOB_TRAFFIC_DET.JOB_REVISED_DATE, JOB_TRAFFIC_DET.EMP_CODE,
								  JOB_LOG.JOB_DESC, JOB_LOG.OFFICE_CODE, JOB_LOG.CL_CODE, JOB_LOG.DIV_CODE, JOB_LOG.PRD_CODE, CASE WHEN JOB_TRAFFIC_DET.TASK_START_DATE IS NULL THEN JOB_TRAFFIC_DET.JOB_REVISED_DATE ELSE JOB_TRAFFIC_DET.TASK_START_DATE END AS SORT
			FROM         JOB_COMPONENT INNER JOIN
								  JOB_TRAFFIC_DET ON JOB_COMPONENT.JOB_NUMBER = JOB_TRAFFIC_DET.JOB_NUMBER AND 
								  JOB_COMPONENT.JOB_COMPONENT_NBR = JOB_TRAFFIC_DET.JOB_COMPONENT_NBR INNER JOIN
											  JOB_LOG ON JOB_COMPONENT.JOB_NUMBER = JOB_LOG.JOB_NUMBER LEFT OUTER JOIN
											  EMP_TRAFFIC_ROLE ON JOB_TRAFFIC_DET.EMP_CODE = EMP_TRAFFIC_ROLE.EMP_CODE LEFT OUTER JOIN
											  TASK_TRAFFIC_ROLE ON JOB_TRAFFIC_DET.FNC_CODE = TASK_TRAFFIC_ROLE.TRF_CODE
			WHERE     (JOB_COMPONENT.JOB_PROCESS_CONTRL <> 6) AND (JOB_COMPONENT.JOB_PROCESS_CONTRL <> 12) AND (JOB_TRAFFIC_DET.JOB_REVISED_DATE >= @StartDate) AND (JOB_TRAFFIC_DET.JOB_REVISED_DATE <= @EndDate) AND 
								   JOB_TRAFFIC_DET.JOB_COMPLETED_DATE IS NULL AND JOB_LOG.CL_CODE Like '%' + @ClientCode AND JOB_LOG.DIV_CODE Like '%' + @DivisionCode AND JOB_LOG.PRD_CODE Like '%' + @ProductCode  
								  AND JOB_LOG.JOB_NUMBER Like '%' + @JobNum AND JOB_COMPONENT.JOB_COMPONENT_NBR Like '%' + @JobComp AND (ISNULL(TASK_TRAFFIC_ROLE.ROLE_CODE, '') Like '%' + @Role OR ISNULL(EMP_TRAFFIC_ROLE.ROLE_CODE, '') Like '%' + @Role) AND
								  ISNULL(JOB_TRAFFIC_DET.TASK_STATUS, '') Like Case @TaskStatus
																When 'P' Then 'P'
																			When 'A' Then 'A'
																When '' Then '%'
																	End AND JOB_TRAFFIC_DET.TEMP_COMP_DATE IS NULL
					AND JOB_TRAFFIC_DET.EMP_CODE IS NOT NULL 
			UNION
			SELECT     JOB_NUMBER, JOB_COMPONENT_NBR, FNC_CODE, NON_TASK_DESC AS TASK_DESCRIPTION, HOURS AS JOB_HRS,
					   CASE WHEN ALL_DAY = 1 THEN START_DATE ELSE (STR(DATEPART(month, START_DATE)) + '/' + STR(DATEPART(day, START_DATE)) + '/' + STR(DATEPART(year, START_DATE)) + ' ' + STR(DATEPART(hour, START_TIME)) + ':' + STR(DATEPART(minute, START_TIME)) + ':' + STR(DATEPART(second, START_TIME))) END AS TASK_START_DATE,
					   CASE WHEN ALL_DAY = 1 THEN END_DATE ELSE (STR(DATEPART(month, END_DATE)) + '/' + STR(DATEPART(day, END_DATE)) + '/' + STR(DATEPART(year, END_DATE)) + ' ' + STR(DATEPART(hour, END_TIME)) + ':' + STR(DATEPART(minute, END_TIME)) + ':' + STR(DATEPART(second, END_TIME))) END AS JOB_REVISED_DATE,  
								  EMP_CODE, '' AS JOB_DESC, 
								  '' AS OFFICE_CODE, '' AS CL_CODE, '' AS DIV_CODE, '' AS PRD_CODE,
								  CASE WHEN ALL_DAY = 1 THEN START_DATE ELSE (STR(DATEPART(month, START_DATE)) + '/' + STR(DATEPART(day, START_DATE)) + '/' + STR(DATEPART(year, START_DATE)) + ' ' + STR(DATEPART(hour, START_TIME)) + ':' + STR(DATEPART(minute, START_TIME)) + ':' + STR(DATEPART(second, START_TIME))) END AS SORT
			FROM         EMP_NON_TASKS	
			WHERE       (START_DATE >= @StartDate) AND (END_DATE <= @EndDate) AND 
										  (TYPE = 'H') 
			UNION
			SELECT     JOB_NUMBER, JOB_COMPONENT_NBR, FNC_CODE, NON_TASK_DESC AS TASK_DESCRIPTION, HOURS AS JOB_HRS,
					   CASE WHEN ALL_DAY = 1 THEN START_DATE ELSE (STR(DATEPART(month, START_DATE)) + '/' + STR(DATEPART(day, START_DATE)) + '/' + STR(DATEPART(year, START_DATE)) + ' ' + STR(DATEPART(hour, START_TIME)) + ':' + STR(DATEPART(minute, START_TIME)) + ':' + STR(DATEPART(second, START_TIME))) END AS TASK_START_DATE,
					   CASE WHEN ALL_DAY = 1 THEN END_DATE ELSE (STR(DATEPART(month, END_DATE)) + '/' + STR(DATEPART(day, END_DATE)) + '/' + STR(DATEPART(year, END_DATE)) + ' ' + STR(DATEPART(hour, END_TIME)) + ':' + STR(DATEPART(minute, END_TIME)) + ':' + STR(DATEPART(second, END_TIME))) END AS JOB_REVISED_DATE,  
								  EMP_CODE, '' AS JOB_DESC, 
								  '' AS OFFICE_CODE, '' AS CL_CODE, '' AS DIV_CODE, '' AS PRD_CODE,
								  CASE WHEN ALL_DAY = 1 THEN START_DATE ELSE (STR(DATEPART(month, START_DATE)) + '/' + STR(DATEPART(day, START_DATE)) + '/' + STR(DATEPART(year, START_DATE)) + ' ' + STR(DATEPART(hour, START_TIME)) + ':' + STR(DATEPART(minute, START_TIME)) + ':' + STR(DATEPART(second, START_TIME))) END AS SORT
			FROM         EMP_NON_TASKS	
			WHERE       (START_DATE >= @StartDate) AND (END_DATE <= @EndDate) AND 
										  (TYPE = 'A') 
			ORDER BY JOB_TRAFFIC_DET.EMP_CODE, SORT							  
	Else
				SELECT     JOB_TRAFFIC_DET.JOB_NUMBER, JOB_TRAFFIC_DET.JOB_COMPONENT_NBR, JOB_TRAFFIC_DET.FNC_CODE, JOB_TRAFFIC_DET.TASK_DESCRIPTION, 
								  JOB_TRAFFIC_DET.JOB_HRS, JOB_TRAFFIC_DET.TASK_START_DATE, JOB_TRAFFIC_DET.JOB_REVISED_DATE, JOB_TRAFFIC_DET.EMP_CODE,
								  JOB_LOG.JOB_DESC, JOB_LOG.OFFICE_CODE, JOB_LOG.CL_CODE, JOB_LOG.DIV_CODE, JOB_LOG.PRD_CODE, CASE WHEN JOB_TRAFFIC_DET.TASK_START_DATE IS NULL THEN JOB_TRAFFIC_DET.JOB_REVISED_DATE ELSE JOB_TRAFFIC_DET.TASK_START_DATE END AS SORT
			FROM         JOB_COMPONENT INNER JOIN
								  JOB_TRAFFIC_DET ON JOB_COMPONENT.JOB_NUMBER = JOB_TRAFFIC_DET.JOB_NUMBER AND 
								  JOB_COMPONENT.JOB_COMPONENT_NBR = JOB_TRAFFIC_DET.JOB_COMPONENT_NBR INNER JOIN
											  JOB_LOG ON JOB_COMPONENT.JOB_NUMBER = JOB_LOG.JOB_NUMBER LEFT OUTER JOIN
											  EMP_TRAFFIC_ROLE ON JOB_TRAFFIC_DET.EMP_CODE = EMP_TRAFFIC_ROLE.EMP_CODE LEFT OUTER JOIN
											  TASK_TRAFFIC_ROLE ON JOB_TRAFFIC_DET.FNC_CODE = TASK_TRAFFIC_ROLE.TRF_CODE
			WHERE     (JOB_COMPONENT.JOB_PROCESS_CONTRL <> 6) AND (JOB_COMPONENT.JOB_PROCESS_CONTRL <> 12) AND (JOB_TRAFFIC_DET.JOB_REVISED_DATE >= @StartDate) AND (JOB_TRAFFIC_DET.JOB_REVISED_DATE <= @EndDate) AND 
								   JOB_TRAFFIC_DET.JOB_COMPLETED_DATE IS NULL AND JOB_LOG.CL_CODE Like '%' + @ClientCode AND JOB_LOG.DIV_CODE Like '%' + @DivisionCode AND JOB_LOG.PRD_CODE Like '%' + @ProductCode  
								  AND JOB_LOG.JOB_NUMBER Like '%' + @JobNum AND JOB_COMPONENT.JOB_COMPONENT_NBR Like '%' + @JobComp AND (ISNULL(TASK_TRAFFIC_ROLE.ROLE_CODE, '') Like '%' + @Role OR ISNULL(EMP_TRAFFIC_ROLE.ROLE_CODE, '') Like '%' + @Role) AND
								  ISNULL(JOB_TRAFFIC_DET.TASK_STATUS, '') Like Case @TaskStatus
																When 'P' Then 'P'
																			When 'A' Then 'A'
																When '' Then '%'
																	End 
					AND JOB_TRAFFIC_DET.EMP_CODE IS NOT NULL 
			UNION
			SELECT     JOB_NUMBER, JOB_COMPONENT_NBR, FNC_CODE, NON_TASK_DESC AS TASK_DESCRIPTION, HOURS AS JOB_HRS,
					   CASE WHEN ALL_DAY = 1 THEN START_DATE ELSE (STR(DATEPART(month, START_DATE)) + '/' + STR(DATEPART(day, START_DATE)) + '/' + STR(DATEPART(year, START_DATE)) + ' ' + STR(DATEPART(hour, START_TIME)) + ':' + STR(DATEPART(minute, START_TIME)) + ':' + STR(DATEPART(second, START_TIME))) END AS TASK_START_DATE,
					   CASE WHEN ALL_DAY = 1 THEN END_DATE ELSE (STR(DATEPART(month, END_DATE)) + '/' + STR(DATEPART(day, END_DATE)) + '/' + STR(DATEPART(year, END_DATE)) + ' ' + STR(DATEPART(hour, END_TIME)) + ':' + STR(DATEPART(minute, END_TIME)) + ':' + STR(DATEPART(second, END_TIME))) END AS JOB_REVISED_DATE,  
								  EMP_CODE, '' AS JOB_DESC, 
								  '' AS OFFICE_CODE, '' AS CL_CODE, '' AS DIV_CODE, '' AS PRD_CODE,
								  CASE WHEN ALL_DAY = 1 THEN START_DATE ELSE (STR(DATEPART(month, START_DATE)) + '/' + STR(DATEPART(day, START_DATE)) + '/' + STR(DATEPART(year, START_DATE)) + ' ' + STR(DATEPART(hour, START_TIME)) + ':' + STR(DATEPART(minute, START_TIME)) + ':' + STR(DATEPART(second, START_TIME))) END AS SORT
			FROM         EMP_NON_TASKS	
			WHERE       (START_DATE >= @StartDate) AND (END_DATE <= @EndDate) AND 
										  (TYPE = 'H') 
			UNION
			SELECT     JOB_NUMBER, JOB_COMPONENT_NBR, FNC_CODE, NON_TASK_DESC AS TASK_DESCRIPTION, HOURS AS JOB_HRS,
					   CASE WHEN ALL_DAY = 1 THEN START_DATE ELSE (STR(DATEPART(month, START_DATE)) + '/' + STR(DATEPART(day, START_DATE)) + '/' + STR(DATEPART(year, START_DATE)) + ' ' + STR(DATEPART(hour, START_TIME)) + ':' + STR(DATEPART(minute, START_TIME)) + ':' + STR(DATEPART(second, START_TIME))) END AS TASK_START_DATE,
					   CASE WHEN ALL_DAY = 1 THEN END_DATE ELSE (STR(DATEPART(month, END_DATE)) + '/' + STR(DATEPART(day, END_DATE)) + '/' + STR(DATEPART(year, END_DATE)) + ' ' + STR(DATEPART(hour, END_TIME)) + ':' + STR(DATEPART(minute, END_TIME)) + ':' + STR(DATEPART(second, END_TIME))) END AS JOB_REVISED_DATE,  
								  EMP_CODE, '' AS JOB_DESC, 
								  '' AS OFFICE_CODE, '' AS CL_CODE, '' AS DIV_CODE, '' AS PRD_CODE,
								  CASE WHEN ALL_DAY = 1 THEN START_DATE ELSE (STR(DATEPART(month, START_DATE)) + '/' + STR(DATEPART(day, START_DATE)) + '/' + STR(DATEPART(year, START_DATE)) + ' ' + STR(DATEPART(hour, START_TIME)) + ':' + STR(DATEPART(minute, START_TIME)) + ':' + STR(DATEPART(second, START_TIME))) END AS SORT
			FROM         EMP_NON_TASKS	
			WHERE       (START_DATE >= @StartDate) AND (END_DATE <= @EndDate) AND 
										  (TYPE = 'A')										  
			ORDER BY JOB_TRAFFIC_DET.EMP_CODE, SORT					  
								  
