
CREATE PROCEDURE [dbo].[usp_wv_ALERT_INBOX_SEARCH_JOB_COMP] /*WITH ENCRYPTION*/
	@SEARCH_CRITERIA     VARCHAR(100),
	@EMP_CODE            VARCHAR(6),
	@JOB_NUMBER         INT,
	@JOB_COMPONENT_NBR  SMALLINT
AS
/*=========== QUERY ===========*/
	--THIS PATH ALLOWS THE SEARCH CRITERIA TO RETURN THE ALERT SEQ NUMBER
	IF ISNUMERIC(@SEARCH_CRITERIA) = 1
		BEGIN
			SELECT *
			FROM   WV_MYALERTSLIST WITH(NOLOCK)
			WHERE  (
					   --(LOWER_SUBJECT LIKE '%' + LOWER(@SEARCH_CRITERIA) + '%')
					   --OR (LOWER(USER_NAME) LIKE '%' + LOWER(@SEARCH_CRITERIA) + '%')
					   --OR LOWER_BODY LIKE '%' + LOWER(@SEARCH_CRITERIA)
					   --OR 
					   ID = CAST(@SEARCH_CRITERIA AS VARCHAR)
				   )
				   --AND (EMP_CODE = @EMP_CODE)
				   AND JOB_NUMBER = @JOB_NUMBER;
				   --AND JOB_COMPONENT_NBR = @JOB_COMPONENT_NBR;
		END
	ELSE
		--THIS IS THE NORMAL PATH
		BEGIN
			SELECT *
			FROM   WV_MYALERTSLIST WITH(NOLOCK)
			WHERE  (
					   (LOWER_SUBJECT LIKE '%' + LOWER(@SEARCH_CRITERIA) + '%')
					   OR (LOWER(USER_NAME) LIKE '%' + LOWER(@SEARCH_CRITERIA) + '%')
					   OR LOWER_BODY LIKE '%' + LOWER(@SEARCH_CRITERIA)
				   )
				   --AND (EMP_CODE = @EMP_CODE)
				   AND JOB_NUMBER = @JOB_NUMBER;
				   --AND JOB_COMPONENT_NBR = @JOB_COMPONENT_NBR;
		END

/*=========== QUERY ===========*/
