SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS OFF 
GO
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[usp_wv_BA_BATCH_INSERT]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
DROP PROCEDURE [dbo].[usp_wv_BA_BATCH_INSERT]
GO
CREATE PROCEDURE [dbo].[usp_wv_BA_BATCH_INSERT] /*WITH ENCRYPTION*/
	@BA_BATCH_DESC VARCHAR(50),
	@BATCH_DATE SMALLDATETIME,
	@CREATE_USER VARCHAR(100),
	@CREATE_DATE SMALLDATETIME,
	@MODIFY_USER VARCHAR(100),
	@MODIFY_DATE SMALLDATETIME,
	@DATE_CUTOFF SMALLDATETIME,
	@PERIOD_CUTOFF VARCHAR(6),
	@EMP_CODE VARCHAR(6),
	@INCL_NB BIT,
	@INCL_FEE BIT,
	@INCL_INT BIT,
	@INCL_NP BIT,
	@INCL_MAG BIT,
	@INCL_OD BIT,
	@INCL_RA BIT,
	@INCL_TV BIT,
	@BA_EXISTS BIT,
	@APPROVED BIT,
	@FINISHED BIT,
	@BILLED_ANY BIT,
	@BILLED_ALL BIT,
	@APPR_METHOD SMALLINT,
	@SEL_OPTION SMALLINT,
	@MANAGER_TYPE SMALLINT -- 1=AE, 2=PM
AS
/*=========== QUERY ===========*/
	DECLARE
		@ERR INT,
		@THIS_BATCH_ID INT
	
	SET @THIS_BATCH_ID = 0;
	
	--INSERT INTO BATCH TABLE:
	INSERT INTO BILL_APPR_BATCH
		(
			BA_BATCH_DESC,
			BATCH_DATE,
			CREATE_USER,
			CREATE_DATE,
			MODIFY_USER,
			MODIFY_DATE,
			DATE_CUTOFF,
			PERIOD_CUTOFF,
			EMP_CODE,
			INCL_NO_DTL,
			INCL_NB,
			INCL_FEE,
			INCL_INT,
			INCL_NP,
			INCL_MAG,
			INCL_OD,
			INCL_RA,
			INCL_TV,
			APPROVED,
			FINISHED,
			APPR_METHOD,
			SEL_OPTION,
			MANAGER_TYPE
		) 
		VALUES 
		( 
			@BA_BATCH_DESC,
			@BATCH_DATE,
			@CREATE_USER,
			@CREATE_DATE,
			@MODIFY_USER,
			@MODIFY_DATE,
			@DATE_CUTOFF,
			''+@PERIOD_CUTOFF+'',
			@EMP_CODE,
			0,
			@INCL_NB,
			@INCL_FEE,
			@INCL_INT,
			@INCL_NP,
			@INCL_MAG,
			@INCL_OD,
			@INCL_RA,
			@INCL_TV,
			@APPROVED,
			@FINISHED,
			@APPR_METHOD,
			@SEL_OPTION,
			@MANAGER_TYPE
		) ;

	SET @ERR = @@ERROR;
	SET @THIS_BATCH_ID = SCOPE_IDENTITY();

	--IF @THIS_BATCH_ID > 0
	--BEGIN
	--	EXEC usp_wv_BA_BATCH_APPLY_CRITERIA @THIS_BATCH_ID;
	--END

	SELECT @THIS_BATCH_ID;

/*=========== QUERY ===========*/
GO
SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO



