--DROP PROCEDURE [dbo].[usp_wv_ALERT_NOTIFY_EMPS_COPY] 
CREATE PROCEDURE [dbo].[usp_wv_ALERT_NOTIFY_EMPS_COPY] /*WITH ENCRYPTION*/
@SOURCE_ALRT_NOTIFY_HDR_ID INT,
@SOURCE_ALERT_STATE_ID INT,
@TARGET_ALRT_NOTIFY_HDR_ID INT,
@TARGET_ALERT_STATE_ID INT
AS
/*=========== QUERY ===========*/
	DECLARE @SOURCE_DFLT_EMP_CODE  VARCHAR(6),
			@SOURCE_SORT_ORDER     INT,
			@SOURCE_IS_DFLT BIT,
			@SOURCE_IS_COMPLETED BIT,
			@SOURCE_EMP_LOOKUP_TYPE TINYINT,
			@SOURCE_DFLT_ROLE_CODE VARCHAR(6),
			@SOURCE_DFLT_DEPT_TEAM_CODE VARCHAR(4),
			@SOURCE_DFLT_ALERT_GROUP_CODE VARCHAR(50)

	IF @TARGET_ALRT_NOTIFY_HDR_ID IS NULL
	BEGIN	
		SET @TARGET_ALRT_NOTIFY_HDR_ID = @SOURCE_ALRT_NOTIFY_HDR_ID;
	END

	SELECT @SOURCE_DFLT_EMP_CODE = DFLT_EMP_CODE,
		   @SOURCE_SORT_ORDER = SORT_ORDER,
		   @SOURCE_IS_DFLT = IS_DFLT,
		   @SOURCE_IS_COMPLETED = IS_COMPLETED,
		   @SOURCE_EMP_LOOKUP_TYPE = EMP_LOOKUP_TYPE,
		   @SOURCE_DFLT_ROLE_CODE = DFLT_ROLE_CODE,
		   @SOURCE_DFLT_DEPT_TEAM_CODE = DFLT_DEPT_TEAM_CODE,
		   @SOURCE_DFLT_ALERT_GROUP_CODE = DFLT_ALERT_GROUP_CODE
	FROM   ALERT_NOTIFY_STATES WITH(NOLOCK)
	WHERE  ALRT_NOTIFY_HDR_ID = @SOURCE_ALRT_NOTIFY_HDR_ID
		   AND ALERT_STATE_ID = @SOURCE_ALERT_STATE_ID;
	
	UPDATE ALERT_NOTIFY_STATES WITH(ROWLOCK)
	SET    DFLT_EMP_CODE = @SOURCE_DFLT_EMP_CODE,
			IS_DFLT = @SOURCE_IS_DFLT,
			IS_COMPLETED = @SOURCE_IS_COMPLETED,
			EMP_LOOKUP_TYPE = @SOURCE_EMP_LOOKUP_TYPE,
			DFLT_ROLE_CODE = @SOURCE_DFLT_ROLE_CODE,
			DFLT_DEPT_TEAM_CODE = @SOURCE_DFLT_DEPT_TEAM_CODE,
			DFLT_ALERT_GROUP_CODE = @SOURCE_DFLT_ALERT_GROUP_CODE
	WHERE  ALRT_NOTIFY_HDR_ID = @TARGET_ALRT_NOTIFY_HDR_ID
		   AND ALERT_STATE_ID = @TARGET_ALERT_STATE_ID;
	
	DELETE 
	FROM   ALERT_NOTIFY_EMPS
	WHERE  ALERT_STATE_ID = @TARGET_ALERT_STATE_ID
		   AND ALRT_NOTIFY_HDR_ID = @TARGET_ALRT_NOTIFY_HDR_ID
		   AND EMP_CODE IN (SELECT DISTINCT EMP_CODE 
							FROM ALERT_NOTIFY_EMPS 
							WHERE ALERT_NOTIFY_EMPS.ALERT_STATE_ID = @SOURCE_ALERT_STATE_ID
							AND ALERT_NOTIFY_EMPS.ALRT_NOTIFY_HDR_ID = @SOURCE_ALRT_NOTIFY_HDR_ID);
	
	INSERT INTO ALERT_NOTIFY_EMPS
	  (
		ALERT_STATE_ID,
		ALRT_NOTIFY_HDR_ID,
		EMP_CODE
	  )
	SELECT @TARGET_ALERT_STATE_ID,
		   @TARGET_ALRT_NOTIFY_HDR_ID,
		   EMP_CODE
	FROM   ALERT_NOTIFY_EMPS AS A
	WHERE  ALERT_STATE_ID = @SOURCE_ALERT_STATE_ID
		   AND ALRT_NOTIFY_HDR_ID = @SOURCE_ALRT_NOTIFY_HDR_ID;
/*=========== QUERY ===========*/
