
CREATE PROCEDURE [dbo].[usp_wv_BA_BILL_APPR_HDR_INSERT] 
	@BA_ID AS INTEGER,
	@JOB_NUMBER AS INTEGER,
	@JOB_COMPONENT_NBR AS SMALLINT,
	@ACCT_EXEC AS VARCHAR(6),
	@APPROVED_AMT AS DECIMAL(15,2),
	@APPR_COMMENTS AS TEXT,
	@CLIENT_COMMENTS AS TEXT,
	@CREATE_USER AS VARCHAR(100),
	@AR_INV_NBR AS INTEGER,
	@INVOICE_DATE AS SMALLDATETIME,
	@BILL_TYPE AS TINYINT,
	@APPR_STATUS AS SMALLINT

AS
DECLARE
	@THIS_BA_HDR_ID AS INTEGER
	
	INSERT INTO BILL_APPR_HDR WITH(ROWLOCK)
		(
			BA_ID,
			JOB_NUMBER,
			JOB_COMPONENT_NBR,
			ACCT_EXEC,
			APPROVED_AMT,
			APPR_COMMENTS,
			CLIENT_COMMENTS,
			CREATE_DATE,
			CREATE_USER,
			AR_INV_NBR,
			INVOICE_DATE,
			BILL_TYPE,
			APPR_STATUS	
		)	
	VALUES	
		(
			@BA_ID,
			@JOB_NUMBER,
			@JOB_COMPONENT_NBR,
			@ACCT_EXEC,
			@APPROVED_AMT,
			@APPR_COMMENTS,
			@CLIENT_COMMENTS,
			GETDATE(),
			@CREATE_USER,
			@AR_INV_NBR,
			@INVOICE_DATE,
			@BILL_TYPE,
			@APPR_STATUS	
		);

	SET @THIS_BA_HDR_ID = SCOPE_IDENTITY();			

	SELECT @THIS_BA_HDR_ID;
	
	
