SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS OFF 
GO
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[usp_wv_BOOKMARKS_FOLDER_ADD]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
DROP PROCEDURE [dbo].[usp_wv_BOOKMARKS_FOLDER_ADD]
GO
CREATE PROCEDURE [dbo].[usp_wv_BOOKMARKS_FOLDER_ADD] /*WITH ENCRYPTION*/
@USER_CODE VARCHAR(100),
@NAME VARCHAR(50),
@DESCRIPTION VARCHAR(100),
@PARENT_ID INT,
@SEQ_NBR INT
AS
/*=========== QUERY ===========*/
	DECLARE @NEW_ID INT
	SET @NEW_ID = 0

	IF EXISTS (SELECT ID FROM WV_BOOKMARK_FOLDERS WITH(NOLOCK) WHERE UPPER(USER_CODE) = UPPER(@USER_CODE) AND NAME = @NAME)
	BEGIN
		SET @NEW_ID = -1;
	END

	IF @NEW_ID <> -1
	BEGIN
		INSERT INTO WV_BOOKMARK_FOLDERS WITH(ROWLOCK) 
		(USER_CODE, NAME, [DESCRIPTION], PARENT_ID, SEQ_NBR) 
		VALUES (@USER_CODE, @NAME, @DESCRIPTION, @PARENT_ID, @SEQ_NBR);

		SET @NEW_ID = @@IDENTITY;
	END

	SELECT @NEW_ID;
/*=========== QUERY ===========*/
GO
SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO