
CREATE PROCEDURE [dbo].[usp_wv_ALERT_NOTIFY_ALERT_INSERT_HDR_ID] 
	@ALERT_ID INT
AS
/*=========== QUERY ===========*/

    DECLARE @JOB_NUMBER          INT,
            @JOB_COMPONENT_NBR   SMALLINT,
            @ALRT_NOTIFY_HDR_ID  INT
    	
    SELECT @JOB_NUMBER = ISNULL(JOB_NUMBER, 0),
           @JOB_COMPONENT_NBR = ISNULL(JOB_COMPONENT_NBR, 0)
    FROM   ALERT WITH(NOLOCK)
    WHERE  ALERT_ID = @ALERT_ID;	


    SELECT @ALRT_NOTIFY_HDR_ID = ISNULL(ALRT_NOTIFY_HDR_ID, 0)
    FROM   JOB_COMPONENT WITH(NOLOCK)
    WHERE  JOB_NUMBER = @JOB_NUMBER
           AND JOB_COMPONENT_NBR = @JOB_COMPONENT_NBR;


    IF NOT @ALRT_NOTIFY_HDR_ID IS NULL
    BEGIN
        UPDATE ALERT WITH(ROWLOCK)
        SET    ALRT_NOTIFY_HDR_ID = @ALRT_NOTIFY_HDR_ID
        WHERE  ALERT_ID = @ALERT_ID;
    END

/*=========== QUERY ===========*/
