SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS OFF 
GO
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[usp_wv_BOOKMARKS_ADD]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
DROP PROCEDURE [dbo].[usp_wv_BOOKMARKS_ADD]
GO
CREATE PROCEDURE [dbo].[usp_wv_BOOKMARKS_ADD] /*WITH ENCRYPTION*/
@BOOKMARK_TYPE_ID INT,
@USER_CODE VARCHAR(100),
@NAME VARCHAR(100),
@DESCRIPTION VARCHAR(500),
@PAGE_URL VARCHAR(2000)
AS
/*=========== QUERY ===========*/

		DECLARE
		@CURRENT_ID INT
		
		SELECT @CURRENT_ID = ID
		FROM WV_BOOKMARKS WITH(NOLOCK)
		WHERE WV_BOOKMARKS.USER_CODE = @USER_CODE
		AND UPPER(WV_BOOKMARKS.PAGE_URL) = UPPER(@PAGE_URL);
		
		IF @CURRENT_ID IS NULL OR @CURRENT_ID = 0
		BEGIN
		
			INSERT INTO WV_BOOKMARKS WITH(ROWLOCK)
			(BOOKMARK_TYPE_ID, USER_CODE, [NAME], [DESCRIPTION], PAGE_URL) 
			VALUES 
			(@BOOKMARK_TYPE_ID, @USER_CODE, @NAME, @DESCRIPTION, @PAGE_URL);
			
			SET @CURRENT_ID = @@IDENTITY;
			
		END
		ELSE
		BEGIN
			--DELETE FROM WV_BOOKMARKS WITH(ROWLOCK) WHERE WV_BOOKMARKS.ID = @CURRENT_ID;
			SET @CURRENT_ID = -1;
		END


		----IF @CURRENT_ID > 0
		----BEGIN

		--	IF NOT EXISTS(
		--		SELECT WV_USER_WORKSPACE.NAME
		--		FROM WV_USER_WORKSPACE WITH(NOLOCK) INNER JOIN
		--		WV_WORKSPACE_OBJECT WITH(NOLOCK) ON WV_USER_WORKSPACE.WORKSPACE_ID = WV_WORKSPACE_OBJECT.WORKSPACE_ID
		--		WHERE (WV_USER_WORKSPACE.USER_CODE = @USER_CODE) AND DESKTOP_OBJECT_ID = 416
		--	)
		--	BEGIN
		--	--NO BOOKMARK DO ON ANY WORKSPACES
		--		SET @CURRENT_ID = -2
		--	END			
		----END
		
		SELECT ISNULL(@CURRENT_ID, 0);	

/*=========== QUERY ===========*/
GO
SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO