
CREATE PROCEDURE [dbo].[usp_wv_ALERT_GET_TASK_ASSIGNMENTS] /*WITH ENCRYPTION*/
	@JOB_NUMBER INT,
	@JOB_COMPONENT_NBR SMALLINT,
	@SEQ_NBR SMALLINT
AS
/*=========== QUERY ===========*/
	SELECT ALERT.JOB_NUMBER,
	       ALERT.JOB_COMPONENT_NBR,
	       ALERT.TASK_SEQ_NBR,
	       ALERT.SUBJECT,
	       ALERT_RCPT.EMP_CODE,
	       ALERT.PRIORITY,
	       ALERT.DUE_DATE,
	       ALERT.TIME_DUE,
	       ISNULL(EMPLOYEE.EMP_FNAME+' ','')+ISNULL(EMPLOYEE.EMP_MI+'. ','')+ISNULL(EMPLOYEE.EMP_LNAME,'') AS EMP_FML_NAME
	FROM   ALERT_RCPT WITH (NOLOCK)
	       INNER JOIN ALERT WITH (NOLOCK)
	            ON  ALERT_RCPT.ALERT_ID = ALERT.ALERT_ID
	       INNER JOIN EMPLOYEE
	            ON  ALERT_RCPT.EMP_CODE = EMPLOYEE.EMP_CODE
	WHERE  (ALERT_RCPT.CURRENT_NOTIFY = 1)
	       AND (ALERT.JOB_NUMBER = @JOB_NUMBER)
	       AND (ALERT.JOB_COMPONENT_NBR = @JOB_COMPONENT_NBR)
	       AND (ALERT.TASK_SEQ_NBR = @SEQ_NBR)
UNION
	SELECT ALERT.JOB_NUMBER,
	       ALERT.JOB_COMPONENT_NBR,
	       ALERT.TASK_SEQ_NBR,
	       ALERT.SUBJECT,
	       ALERT_RCPT_DISMISSED.EMP_CODE,
	       ALERT.PRIORITY,
	       ALERT.DUE_DATE,
	       ALERT.TIME_DUE,
	       ISNULL(EMPLOYEE.EMP_FNAME+' ','')+ISNULL(EMPLOYEE.EMP_MI+'. ','')+ISNULL(EMPLOYEE.EMP_LNAME,'') AS EMP_FML_NAME
	FROM   ALERT_RCPT_DISMISSED WITH (NOLOCK)
	       INNER JOIN ALERT WITH (NOLOCK)
	            ON  ALERT_RCPT_DISMISSED.ALERT_ID = ALERT.ALERT_ID
	       INNER JOIN EMPLOYEE
	            ON  ALERT_RCPT_DISMISSED.EMP_CODE = EMPLOYEE.EMP_CODE
	WHERE  (ALERT_RCPT_DISMISSED.CURRENT_NOTIFY = 1)
	       AND (ALERT.JOB_NUMBER = @JOB_NUMBER)
	       AND (ALERT.JOB_COMPONENT_NBR = @JOB_COMPONENT_NBR)
	       AND (ALERT.TASK_SEQ_NBR = @SEQ_NBR)       
/*=========== QUERY ===========*/
