
CREATE PROCEDURE [dbo].[usp_wv_ALERT_NOTIFY_EMPS_BY_HDRID] 
	@ALRT_NOTIFY_HDR_ID INT
AS

SELECT DISTINCT EMPLOYEE.EMP_CODE,
       [dbo].[udf_get_empl_name](EMPLOYEE.EMP_CODE, 'FML') EMP_FML,
       EMPLOYEE.EMP_EMAIL
FROM   ALERT_NOTIFY_STATES WITH(NOLOCK)
       INNER JOIN ALERT_NOTIFY_HDR WITH(NOLOCK)
            ON  ALERT_NOTIFY_STATES.ALRT_NOTIFY_HDR_ID = ALERT_NOTIFY_HDR.ALRT_NOTIFY_HDR_ID
       INNER JOIN ALERT_STATES WITH(NOLOCK)
            ON  ALERT_NOTIFY_STATES.ALERT_STATE_ID = ALERT_STATES.ALERT_STATE_ID
       INNER JOIN ALERT_NOTIFY_EMPS WITH(NOLOCK)
            ON  ALERT_STATES.ALERT_STATE_ID = ALERT_NOTIFY_EMPS.ALERT_STATE_ID
       INNER JOIN EMPLOYEE WITH(NOLOCK)
            ON  ALERT_NOTIFY_EMPS.EMP_CODE = EMPLOYEE.EMP_CODE
WHERE  (
           ALERT_NOTIFY_STATES.ALRT_NOTIFY_HDR_ID = @ALRT_NOTIFY_HDR_ID
       )
       AND (
               EMPLOYEE.EMP_TERM_DATE IS NULL
               OR EMPLOYEE.EMP_TERM_DATE > GETDATE()
           )
       AND (
               ALERT_STATES.ACTIVE_FLAG IS NULL
               OR ALERT_STATES.ACTIVE_FLAG = 1
           )
       AND (
               ALERT_NOTIFY_HDR.ACTIVE_FLAG IS NULL
               OR ALERT_NOTIFY_HDR.ACTIVE_FLAG = 1
           )

