SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS OFF 
GO
if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[usp_wv_dd_GetClientsAE]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [dbo].[usp_wv_dd_GetClientsAE]
GO
CREATE PROCEDURE [dbo].[usp_wv_dd_GetClientsAE] 
@UserID VARCHAR(100),
@OBJECT_ID INT
AS
/*=========== QUERY ===========*/
	DECLARE @RESTRICTIONS INT, @EMP_CODE VARCHAR(6), @OfficeCount AS INTEGER

	SET NOCOUNT ON

	SELECT @RESTRICTIONS = COUNT(*) 
	FROM SEC_CLIENT WITH(NOLOCK)
	WHERE UPPER(USER_ID) = UPPER(@UserID);

	SELECT @EMP_CODE = EMP_CODE
	FROM SEC_USER WITH(NOLOCK)
	WHERE UPPER(USER_CODE) = UPPER(@UserID);

	SELECT @OfficeCount = COUNT(*) FROM EMP_OFFICE WHERE EMP_CODE = @EMP_CODE;

	DECLARE @RESULTS TABLE
	(
		Code VARCHAR(10),
		[Description] VARCHAR(500)
	)	

	If @RESTRICTIONS > 0
	BEGIN
		If @OfficeCount = 0
		Begin
			INSERT INTO @RESULTS
			SELECT     
				DISTINCT CLIENT.CL_CODE AS Code, CLIENT.CL_CODE + ' - ' + ISNULL(CLIENT.CL_NAME, '') AS Description
			FROM         
				CLIENT INNER JOIN
				ACCOUNT_EXECUTIVE ON CLIENT.CL_CODE = ACCOUNT_EXECUTIVE.CL_CODE INNER JOIN
				SEC_CLIENT ON CLIENT.CL_CODE = SEC_CLIENT.CL_CODE
			WHERE     
				(CLIENT.ACTIVE_FLAG = 1) AND (UPPER(SEC_CLIENT.USER_ID) = UPPER(@UserID)) 
				AND (SEC_CLIENT.TIME_ENTRY = 0 OR SEC_CLIENT.TIME_ENTRY IS NULL);
		End	
		Else
		Begin
			INSERT INTO @RESULTS
			SELECT     
				DISTINCT CLIENT.CL_CODE AS Code, CLIENT.CL_CODE + ' - ' + ISNULL(CLIENT.CL_NAME, '') AS Description
			FROM         
				CLIENT INNER JOIN
				ACCOUNT_EXECUTIVE ON CLIENT.CL_CODE = ACCOUNT_EXECUTIVE.CL_CODE INNER JOIN
				SEC_CLIENT ON CLIENT.CL_CODE = SEC_CLIENT.CL_CODE INNER JOIN
                          DIVISION ON CLIENT.CL_CODE = DIVISION.CL_CODE INNER JOIN
                           PRODUCT ON DIVISION.CL_CODE = PRODUCT.CL_CODE AND DIVISION.DIV_CODE = PRODUCT.DIV_CODE INNER JOIN 
						   EMP_OFFICE ON PRODUCT.OFFICE_CODE = EMP_OFFICE.OFFICE_CODE AND EMP_OFFICE.EMP_CODE = @EMP_CODE
			WHERE     
				(CLIENT.ACTIVE_FLAG = 1) AND (UPPER(SEC_CLIENT.USER_ID) = UPPER(@UserID)) 
				AND (SEC_CLIENT.TIME_ENTRY = 0 OR SEC_CLIENT.TIME_ENTRY IS NULL);
		End
		
		
	END	
	ELSE
	BEGIN
		If @OfficeCount = 0
		Begin
			INSERT INTO @RESULTS
			SELECT     
				DISTINCT CLIENT.CL_CODE AS Code, CLIENT.CL_CODE + ' - ' + ISNULL(CLIENT.CL_NAME, '') AS Description
			FROM         
				CLIENT INNER JOIN
				ACCOUNT_EXECUTIVE ON CLIENT.CL_CODE = ACCOUNT_EXECUTIVE.CL_CODE 
			WHERE     
				(CLIENT.ACTIVE_FLAG = 1);
		End	
		Else
		Begin
			INSERT INTO @RESULTS
			SELECT     
				DISTINCT CLIENT.CL_CODE AS Code, CLIENT.CL_CODE + ' - ' + ISNULL(CLIENT.CL_NAME, '') AS Description
			FROM         
				CLIENT INNER JOIN
				ACCOUNT_EXECUTIVE ON CLIENT.CL_CODE = ACCOUNT_EXECUTIVE.CL_CODE INNER JOIN
                          DIVISION ON CLIENT.CL_CODE = DIVISION.CL_CODE INNER JOIN
                           PRODUCT ON DIVISION.CL_CODE = PRODUCT.CL_CODE AND DIVISION.DIV_CODE = PRODUCT.DIV_CODE INNER JOIN 
						   EMP_OFFICE ON PRODUCT.OFFICE_CODE = EMP_OFFICE.OFFICE_CODE AND EMP_OFFICE.EMP_CODE = @EMP_CODE
			WHERE     
				(CLIENT.ACTIVE_FLAG = 1);
		End
		
		
	END	

	DECLARE @EMPLOYEE_HAS_MGMT_RESTRICTIONS BIT;
	SELECT @EMPLOYEE_HAS_MGMT_RESTRICTIONS = [dbo].[fn_my_objects_employee_has_dynamic_restriction](@EMP_CODE, @OBJECT_ID); 

	IF @EMPLOYEE_HAS_MGMT_RESTRICTIONS = 1
	BEGIN
	
		SELECT DISTINCT R.* 
		FROM @RESULTS AS R INNER JOIN [dbo].[fn_my_objects_get_dynamic_restrictions](@OBJECT_ID, @EMP_CODE) AS DR
		ON R.Code = DR.CL_CODE
		ORDER BY R.Code;
	
	END
	ELSE
	BEGIN

		SELECT DISTINCT R.* 
		FROM @RESULTS AS R 
		ORDER BY R.Code;

	END	
/*=========== QUERY ===========*/
GO
SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO