




CREATE PROCEDURE [dbo].[usp_cp_GetAlertRecipients] 
@Group varchar(50), 
@JobNum int,
@JobCompNum int
AS

declare @T_EmailGroup table (EMPGROUP varchar(255), 
								EMPCODE varchar(150), 
								DESCRIPTION Varchar(2000),
								Checked bit)

IF @Group <> ''
	    BEGIN
		    insert into @T_EmailGroup (EMPGROUP, EMPCODE, DESCRIPTION, Checked)
		    select A.EMPGROUP, A.EMPCODE, A.DESCRIPTION, A.Checked from
		    (SELECT  'Root' as EMPGROUP, EMAIL_GROUP.EMAIL_GR_CODE + ':Root' as  EMPCODE, EMAIL_GROUP.EMAIL_GR_CODE as DESCRIPTION, 1 as Checked
		    from EMAIL_GROUP INNER JOIN JOB_COMPONENT ON JOB_COMPONENT.EMAIL_GR_CODE = EMAIL_GROUP.EMAIL_GR_CODE
		    where EMAIL_GROUP.EMAIL_GR_CODE LIKE @Group+'%' AND ((EMAIL_GROUP.INACTIVE_FLAG = 0) OR (EMAIL_GROUP.INACTIVE_FLAG IS NULL))
				AND JOB_COMPONENT.JOB_NUMBER = @JobNum AND JOB_COMPONENT.JOB_COMPONENT_NBR = @JobCompNum
		    Group by EMAIL_GROUP.EMAIL_GR_CODE) A
    		
		    insert into @T_EmailGroup (EMPGROUP, EMPCODE, DESCRIPTION, Checked)
		    select A.EMPGROUP, A.EMPCODE, A.DESCRIPTION, A.Checked from
		    (SELECT  EMAIL_GROUP.EMAIL_GR_CODE as EMPGROUP, EMAIL_GROUP.EMP_CODE as EMPCODE,  isnull(EMPLOYEE.EMP_LNAME, '') + ', ' + isnull(EMPLOYEE.EMP_FNAME, '') + ' ' + isnull(EMPLOYEE.EMP_MI, '') as DESCRIPTION, 1 as Checked
		    from EMAIL_GROUP left outer join EMPLOYEE on
		    EMAIL_GROUP.EMP_CODE = EMPLOYEE.EMP_CODE INNER JOIN JOB_COMPONENT ON JOB_COMPONENT.EMAIL_GR_CODE = EMAIL_GROUP.EMAIL_GR_CODE
		    where EMAIL_GROUP.EMAIL_GR_CODE LIKE @Group+'%' AND ((EMAIL_GROUP.INACTIVE_FLAG = 0) OR (EMAIL_GROUP.INACTIVE_FLAG IS NULL))
				AND JOB_COMPONENT.JOB_NUMBER = @JobNum AND JOB_COMPONENT.JOB_COMPONENT_NBR = @JobCompNum) A ORDER BY A.DESCRIPTION		
        END
        ELSE
        BEGIN
  		    --Check to see if there is a default group
		    insert into @T_EmailGroup (EMPGROUP, EMPCODE, DESCRIPTION, Checked)
		    select A.EMPGROUP, A.EMPCODE, A.DESCRIPTION, A.Checked from
		    (SELECT  'Root' as EMPGROUP, EMAIL_GROUP.EMAIL_GR_CODE + ':Root' as  EMPCODE, EMAIL_GROUP.EMAIL_GR_CODE as DESCRIPTION, 1 as Checked
		    from EMAIL_GROUP INNER JOIN JOB_COMPONENT ON JOB_COMPONENT.EMAIL_GR_CODE = EMAIL_GROUP.EMAIL_GR_CODE
		    where EMAIL_GROUP.EMAIL_GR_CODE = @Group AND ((EMAIL_GROUP.INACTIVE_FLAG = 0) OR (EMAIL_GROUP.INACTIVE_FLAG IS NULL))
				AND JOB_COMPONENT.JOB_NUMBER = @JobNum AND JOB_COMPONENT.JOB_COMPONENT_NBR = @JobCompNum
		    Group by EMAIL_GROUP.EMAIL_GR_CODE) A
    		
		    insert into @T_EmailGroup (EMPGROUP, EMPCODE, DESCRIPTION, Checked)
		    select A.EMPGROUP, A.EMPCODE, A.DESCRIPTION, A.Checked from
		    (SELECT  'Root' as EMPGROUP, EMAIL_GROUP.EMAIL_GR_CODE + ':Root' as  EMPCODE, EMAIL_GROUP.EMAIL_GR_CODE as DESCRIPTION, 0 as Checked
		    from EMAIL_GROUP INNER JOIN JOB_COMPONENT ON JOB_COMPONENT.EMAIL_GR_CODE = EMAIL_GROUP.EMAIL_GR_CODE
		    where EMAIL_GROUP.EMAIL_GR_CODE <> @Group AND ((EMAIL_GROUP.INACTIVE_FLAG = 0) OR (EMAIL_GROUP.INACTIVE_FLAG IS NULL))
				AND JOB_COMPONENT.JOB_NUMBER = @JobNum AND JOB_COMPONENT.JOB_COMPONENT_NBR = @JobCompNum
		    Group by EMAIL_GROUP.EMAIL_GR_CODE) A
    		
		    --Check to see if there is a default group
		    insert into @T_EmailGroup (EMPGROUP, EMPCODE, DESCRIPTION, Checked)
		    select A.EMPGROUP, A.EMPCODE, A.DESCRIPTION, A.Checked from
		    (SELECT  EMAIL_GROUP.EMAIL_GR_CODE as EMPGROUP, EMAIL_GROUP.EMP_CODE as EMPCODE,  isnull(EMPLOYEE.EMP_LNAME, '') + ', ' + isnull(EMPLOYEE.EMP_FNAME, '') + ' ' + isnull(EMPLOYEE.EMP_MI, '') as DESCRIPTION, 1 as Checked
		    from EMAIL_GROUP left outer join EMPLOYEE on
		    EMAIL_GROUP.EMP_CODE = EMPLOYEE.EMP_CODE INNER JOIN JOB_COMPONENT ON JOB_COMPONENT.EMAIL_GR_CODE = EMAIL_GROUP.EMAIL_GR_CODE
		    where EMAIL_GROUP.EMAIL_GR_CODE = @Group and ALERT_EMAIL <> 0  AND ((EMAIL_GROUP.INACTIVE_FLAG = 0) OR (EMAIL_GROUP.INACTIVE_FLAG IS NULL))
				AND JOB_COMPONENT.JOB_NUMBER = @JobNum AND JOB_COMPONENT.JOB_COMPONENT_NBR = @JobCompNum) A ORDER BY A.DESCRIPTION
    		
		    --Check to see if user flagged not to receive emails.
		    insert into @T_EmailGroup (EMPGROUP, EMPCODE, DESCRIPTION, Checked)
		    select A.EMPGROUP, A.EMPCODE, A.DESCRIPTION, A.Checked from
		    (SELECT  EMAIL_GROUP.EMAIL_GR_CODE as EMPGROUP, EMAIL_GROUP.EMP_CODE as EMPCODE, isnull(EMPLOYEE.EMP_LNAME, '') + ', ' + isnull(EMPLOYEE.EMP_FNAME, '') + ' ' + isnull(EMPLOYEE.EMP_MI, '')  as DESCRIPTION, 0 AS Checked
		    from EMAIL_GROUP left outer join EMPLOYEE on
		    EMAIL_GROUP.EMP_CODE = EMPLOYEE.EMP_CODE INNER JOIN JOB_COMPONENT ON JOB_COMPONENT.EMAIL_GR_CODE = EMAIL_GROUP.EMAIL_GR_CODE
		    where EMAIL_GROUP.EMAIL_GR_CODE = @Group and ALERT_EMAIL = 0  AND ((EMAIL_GROUP.INACTIVE_FLAG = 0) OR (EMAIL_GROUP.INACTIVE_FLAG IS NULL))
				AND JOB_COMPONENT.JOB_NUMBER = @JobNum AND JOB_COMPONENT.JOB_COMPONENT_NBR = @JobCompNum) A ORDER BY A.DESCRIPTION
    		
		    insert into @T_EmailGroup (EMPGROUP, EMPCODE, DESCRIPTION, Checked)
		    select A.EMPGROUP, A.EMPCODE, A.DESCRIPTION, A.Checked from
		    (SELECT  EMAIL_GROUP.EMAIL_GR_CODE as EMPGROUP, EMAIL_GROUP.EMP_CODE as EMPCODE,  isnull(EMPLOYEE.EMP_LNAME, '') + ', ' + isnull(EMPLOYEE.EMP_FNAME, '') + ' ' + isnull(EMPLOYEE.EMP_MI, '') as DESCRIPTION, 0 as Checked
		    from EMAIL_GROUP left outer join EMPLOYEE on
		    EMAIL_GROUP.EMP_CODE = EMPLOYEE.EMP_CODE INNER JOIN JOB_COMPONENT ON JOB_COMPONENT.EMAIL_GR_CODE = EMAIL_GROUP.EMAIL_GR_CODE
		    where EMAIL_GROUP.EMAIL_GR_CODE <> @Group and ALERT_EMAIL <> 0 AND ((EMAIL_GROUP.INACTIVE_FLAG = 0) OR (EMAIL_GROUP.INACTIVE_FLAG IS NULL))
				AND JOB_COMPONENT.JOB_NUMBER = @JobNum AND JOB_COMPONENT.JOB_COMPONENT_NBR = @JobCompNum) A ORDER BY A.DESCRIPTION
    		
		    --Check to see if the user flagged not to receive emails.
		    insert into @T_EmailGroup (EMPGROUP, EMPCODE, DESCRIPTION, Checked)
		    select A.EMPGROUP, A.EMPCODE, A.DESCRIPTION, A.Checked from
		    (SELECT  EMAIL_GROUP.EMAIL_GR_CODE as EMPGROUP, EMAIL_GROUP.EMP_CODE as EMPCODE,  isnull(EMPLOYEE.EMP_LNAME, '') + ', ' + isnull(EMPLOYEE.EMP_FNAME, '') + ' ' + isnull(EMPLOYEE.EMP_MI, '')  as DESCRIPTION, 0 AS Checked
		    from EMAIL_GROUP left outer join EMPLOYEE on
		    EMAIL_GROUP.EMP_CODE = EMPLOYEE.EMP_CODE INNER JOIN JOB_COMPONENT ON JOB_COMPONENT.EMAIL_GR_CODE = EMAIL_GROUP.EMAIL_GR_CODE
		    where EMAIL_GROUP.EMAIL_GR_CODE <> @Group and ALERT_EMAIL = 0 AND ((EMAIL_GROUP.INACTIVE_FLAG = 0) OR (EMAIL_GROUP.INACTIVE_FLAG IS NULL))
				AND JOB_COMPONENT.JOB_NUMBER = @JobNum AND JOB_COMPONENT.JOB_COMPONENT_NBR = @JobCompNum) A ORDER BY A.DESCRIPTION
      END


Select * from @T_EmailGroup














