


















--region [dbo].[usp_InserttblNew]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   ComputerUser1 using CodeSmith 3.0.7.406
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_InserttblNew]
-- Date Generated: Sunday, August 21, 2005
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_News_Insert]
	@NewsDate datetime,
	@NewsTitle varchar(100),
	@NewsText varchar(500),
	@Active bit
AS

SET NOCOUNT ON

INSERT INTO [dbo].[tblNews] (
	[NewsDate],
	[NewsTitle],
	[NewsText],
	[Active]
) VALUES (
	@NewsDate,
	@NewsTitle,
	@NewsText,
	@Active
)

Select SCOPE_IDENTITY()

--endregion

















