













CREATE PROCEDURE [dbo].[usp_cp_Task_Get] 
@JobNo Int, 
@JobComp Int, 
@SeqNo Int,
@EmpCode Varchar(6)
AS

Set NoCount On
		SELECT     '(' + JOB_LOG.CL_CODE + ') ' + CLIENT.CL_NAME AS CLIENT, '(' + JOB_LOG.DIV_CODE + ') ' + DIVISION.DIV_NAME AS DIVISION, 
								  '(' + JOB_LOG.PRD_CODE + ') ' + PRODUCT.PRD_DESCRIPTION AS PRODUCT, '(' + CAST(JOB_LOG.JOB_NUMBER AS VarChar(10)) 
								  + ') ' + JOB_LOG.JOB_DESC AS Job, '(' + CAST(JOB_COMPONENT.JOB_COMPONENT_NBR AS VarChar(10)) 
								  + ') ' + JOB_COMPONENT.JOB_COMP_DESC AS JobComp, '(' + ISNULL(JOB_TRAFFIC_DET.FNC_CODE, '') 
								  + ') ' + ISNULL(JOB_TRAFFIC_DET.TASK_DESCRIPTION, '') AS Task, CONVERT(char, JOB_TRAFFIC_DET.JOB_DUE_DATE, 101) AS DueDate, 
								  CONVERT(char, JOB_TRAFFIC_DET.JOB_REVISED_DATE, 101) AS RevDueDate, ISNULL(JOB_TRAFFIC_DET.DUE_TIME, '') AS DueTime, ISNULL(JOB_TRAFFIC_DET.REVISED_DUE_TIME, '') 
								  AS RevDueTime, CONVERT(char, JOB_TRAFFIC_DET.TASK_START_DATE, 101) AS TaskStartDate, 
								  ISNULL(JOB_TRAFFIC_DET.FNC_COMMENTS,'') AS Comments, ISNULL(CONVERT(char, JOB_TRAFFIC_DET.TEMP_COMP_DATE, 101), '') AS TempCompDate, 
								  JOB_TRAFFIC_DET.JOB_HRS AS HoursAllowed, ISNULL(JOB_TRAFFIC_DET.TASK_STATUS,'P') AS TaskStatus, 
								  TRAFFIC_PHASE.PHASE_DESC AS Phase, CONVERT(char, JOB_COMPONENT.START_DATE, 101) AS JobStartDate, CONVERT(char, 
								  JOB_COMPONENT.JOB_FIRST_USE_DATE, 101) AS JobDueDate, '(' + ISNULL(TRAFFIC.TRF_CODE, '') 
								  + ') ' + ISNULL(TRAFFIC.TRF_DESCRIPTION, '') AS TrafficStatus, JOB_TRAFFIC.TRF_COMMENTS AS TrafficComments, 
								  '('+JOB_COMPONENT.EMP_CODE+') '+ ISNULL(EMPLOYEE.EMP_FNAME,'')+' '+ISNULL(EMPLOYEE.EMP_MI,'')+' '+ISNULL(EMPLOYEE.EMP_LNAME,'') AS AE,
				                  ISNULL(V_JOB_TRAFFIC_DET_EMPS.EMP_LFI_LIST,'') AS Employee, '' AS CompletedComments, 'CContacts' AS Contacts
			FROM         JOB_LOG INNER JOIN
								  CLIENT ON CLIENT.CL_CODE = JOB_LOG.CL_CODE INNER JOIN
								  DIVISION ON DIVISION.DIV_CODE = JOB_LOG.DIV_CODE AND DIVISION.CL_CODE = JOB_LOG.CL_CODE INNER JOIN
								  PRODUCT ON PRODUCT.CL_CODE = JOB_LOG.CL_CODE AND PRODUCT.DIV_CODE = JOB_LOG.DIV_CODE AND 
								  PRODUCT.PRD_CODE = JOB_LOG.PRD_CODE INNER JOIN
								  JOB_COMPONENT ON JOB_LOG.JOB_NUMBER = JOB_COMPONENT.JOB_NUMBER INNER JOIN
								  JOB_TRAFFIC_DET ON JOB_COMPONENT.JOB_NUMBER = JOB_TRAFFIC_DET.JOB_NUMBER AND 
								  JOB_COMPONENT.JOB_COMPONENT_NBR = JOB_TRAFFIC_DET.JOB_COMPONENT_NBR LEFT OUTER JOIN
								  TRAFFIC_PHASE ON JOB_TRAFFIC_DET.TRAFFIC_PHASE_ID = TRAFFIC_PHASE.TRAFFIC_PHASE_ID INNER JOIN
								  JOB_TRAFFIC ON JOB_COMPONENT.JOB_NUMBER = JOB_TRAFFIC.JOB_NUMBER AND 
								  JOB_COMPONENT.JOB_COMPONENT_NBR = JOB_TRAFFIC.JOB_COMPONENT_NBR INNER JOIN
								  TRAFFIC ON JOB_TRAFFIC.TRF_CODE = TRAFFIC.TRF_CODE LEFT OUTER JOIN
								  EMPLOYEE ON JOB_COMPONENT.EMP_CODE = EMPLOYEE.EMP_CODE INNER JOIN
								  V_JOB_TRAFFIC_DET_EMPS ON JOB_TRAFFIC_DET.JOB_NUMBER = V_JOB_TRAFFIC_DET_EMPS.JOB_NUMBER AND 
								  JOB_TRAFFIC_DET.JOB_COMPONENT_NBR = V_JOB_TRAFFIC_DET_EMPS.JOB_COMPONENT_NBR AND V_JOB_TRAFFIC_DET_EMPS.SEQ_NBR = JOB_TRAFFIC_DET.SEQ_NBR
			 WHERE (JOB_TRAFFIC_DET.JOB_NUMBER = @JobNo) AND
				   (JOB_TRAFFIC_DET.JOB_COMPONENT_NBR = @JobComp) AND
				   (JOB_TRAFFIC_DET.SEQ_NBR = @SeqNo)












