





CREATE PROCEDURE [dbo].[usp_wv_calendar_ddInternet]
@OrderNumber Int,
@LineNumber Int,
@RevNumber Int
AS

 --Internet Media Data   
	                                                  
SELECT 'I' AS TYPE, 'A' AS EST_ACT, IH.OFFICE_CODE, IH.ORDER_NBR, 
		IH.ORDER_DESC, IH.MEDIA_TYPE, IH.CL_CODE, 
		IH.DIV_CODE, IH.PRD_CODE, IH.CMP_IDENTIFIER, 
		IH.CMP_CODE, C.CMP_NAME, IH.VN_CODE, V.VN_NAME, IH.BUYER, IH.CLIENT_PO, 
		IH.MARKET_CODE, M.MARKET_DESC, IH.ORDER_ACCEPTED, ID.LINE_NBR, 
		ID.ACTIVE_REV,'' AS FLIGHT_DATES, ID.START_DATE, ID.END_DATE, 
		'' AS MEDIA_MONTH, '' AS MEDIA_YEAR,
		ID.CLOSE_DATE, ID.MATL_CLOSE_DATE, ID.EXT_CLOSE_DATE, 
		ID.EXT_MATL_DATE, ID.CREATIVE_SIZE,
		0 AS PRINT_COLUMNS, 0 AS PRINT_INCHES, 0 AS PRINT_LINES, ID.AD_NUMBER, 
		ID.HEADLINE, ID.INTERNET_TYPE, '' AS OUTDOOR_TYPE, '' AS MATERIAL,
		'' AS EDITION_ISSUE,'' AS SECTION, '' AS START_TIME, '' AS END_TIME,'' AS LENGTH, '' AS TAG, '' AS PROGRAMMING,
		'' AS MATL_NOTES, '' AS REMARKS, ID.JOB_NUMBER, 
		ID.JOB_COMPONENT_NBR, '' AS PRODUCTION_SIZE, ID.EST_NBR, ID.EST_LINE_NBR, 
		ID.EST_REV_NBR, ID.LINE_TOTAL,ID.COST_RATE AS COST_PER,  
		ID.GUARANTEED_IMPRESS AS IMPRESSIONS, ID.LINE_CANCELLED, CL.CL_NAME, D.DIV_NAME, P.PRD_DESCRIPTION,
		ID.BILLING_AMT, IH.LINK_ID,VR.VR_FNAME, VR.VR_LNAME, 
        VR.VR_MI, VR.VR_CODE, VR2.VR_FNAME AS VR_FNAME2, VR2.VR_LNAME AS VR_LNAME2, 
        VR2.VR_MI AS VR_MI2, VR2.VR_CODE AS VR_CODE2, JC.JOB_COMP_DESC, JL.JOB_DESC,  IH.ORDER_DATE, ID.REV_NBR, ID.URL, ID.TARGET_AUDIENCE, 
		ID.PLACEMENT_1, ID.PLACEMENT_2, ID.SIZE, IT.OD_DESC, SC.SC_DESCRIPTION, ID.MAT_COMP, AD.AD_NBR_DESC, ID.COPY_AREA, ID.COST_TYPE
	FROM INTERNET_HEADER IH INNER JOIN INTERNET_DETAIL ID ON IH.ORDER_NBR = ID.ORDER_NBR
						 INNER JOIN VENDOR V ON IH.VN_CODE = V.VN_CODE
						 INNER JOIN CLIENT AS CL ON IH.CL_CODE = CL.CL_CODE INNER JOIN
						 DIVISION AS D ON CL.CL_CODE = D.CL_CODE INNER JOIN
						 PRODUCT AS P ON IH.CL_CODE = P.CL_CODE AND IH.DIV_CODE = P.DIV_CODE AND 
						 IH.PRD_CODE = P.PRD_CODE AND D.CL_CODE = P.CL_CODE AND 
						 D.DIV_CODE = P.DIV_CODE LEFT OUTER JOIN 
						 JOB_LOG JL ON ID.JOB_NUMBER = JL.JOB_NUMBER LEFT OUTER JOIN
                         SALES_CLASS SC ON IH.MEDIA_TYPE = SC.SC_CODE LEFT OUTER JOIN
						 JOB_COMPONENT JC ON ID.JOB_NUMBER = JC.JOB_NUMBER AND 
					     ID.JOB_COMPONENT_NBR = JC.JOB_COMPONENT_NBR LEFT OUTER JOIN
						 VEN_REP VR ON IH.VN_CODE = VR.VN_CODE AND 
						 IH.VR_CODE = VR.VR_CODE LEFT OUTER JOIN
						 VEN_REP VR2 ON IH.VN_CODE = VR2.VN_CODE AND IH.VR_CODE2 = VR2.VR_CODE
						 LEFT OUTER JOIN CAMPAIGN C ON IH.CMP_IDENTIFIER = C.CMP_IDENTIFIER
						 LEFT OUTER JOIN MARKET M ON IH.MARKET_CODE = M.MARKET_CODE LEFT OUTER JOIN
						 INTERNET_TYPE IT ON ID.INTERNET_TYPE = IT.OD_CODE LEFT OUTER JOIN
                         AD_NUMBER AD ON ID.AD_NUMBER = AD.AD_NBR
	WHERE ACTIVE_REV = 1 AND IH.ORDER_NBR = @OrderNumber and ID.LINE_NBR = @LineNumber AND ID.REV_NBR = @RevNumber


