if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[usp_wv_calendar_ddRadio]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [dbo].[usp_wv_calendar_ddRadio]
GO



CREATE PROCEDURE [dbo].[usp_wv_calendar_ddRadio]
@OrderNumber Int,
@LineNumber Int,
@RevNumber Int,
@Year Int
AS
IF EXISTS (SELECT ORDER_NBR FROM RADIO_HEADER WHERE ORDER_NBR = @OrderNumber)
BEGIN
	SELECT     'R' AS Type, 'A' AS EST_ACT, RADIO_HEADER.OFFICE_CODE, RADIO_DETAIL1.ORDER_NBR, RADIO_HEADER.ORDER_DESC, 
                      RADIO_HEADER.MEDIA_TYPE, RADIO_HEADER.CL_CODE, RADIO_HEADER.DIV_CODE, RADIO_HEADER.PRD_CODE, 
                      RADIO_HEADER.CMP_IDENTIFIER, CAMPAIGN.CMP_CODE, CAMPAIGN.CMP_NAME, RADIO_HEADER.VN_CODE, VENDOR.VN_NAME, 
                      RADIO_HEADER.BUYER, RADIO_HEADER.CLIENT_PO, RADIO_HEADER.MARKET_CODE, MARKET.MARKET_DESC, 
                      RADIO_DETAIL1.LINE_NBR, RADIO_HEADER.FLIGHT_FROM, RADIO_HEADER.FLIGHT_TO, RADIO_DETAIL1.CLOSE_DATE, 
                      RADIO_DETAIL1.EXT_CLOSE_DATE, RADIO_DETAIL1.MATL_CLOSE_DATE, RADIO_DETAIL1.EXT_MATL_DATE, 
                      RADIO_DETAIL1.START_TIME, RADIO_DETAIL1.END_TIME, RADIO_DETAIL1.LENGTH, RADIO_DETAIL1.TAG, 
                      RADIO_DETAIL1.PROGRAMMING, RADIO_DETAIL2.MATL_NOTES, RADIO_DETAIL1.REMARKS, RADIO_DETAIL1.JOB_NUMBER, 
                      RADIO_DETAIL1.JOB_COMPONENT_NBR, RADIO_HEADER.LINK_ID, RADIO_DETAIL1.LINE_TOTAL, (SELECT SUM(TOTAL_SPOTS) FROM RADIO_DETAIL1 WHERE ORDER_NBR = @OrderNumber AND LINE_NBR = @LineNumber) AS TOTAL_SPOTS,  
                      CLIENT.CL_NAME, DIVISION.DIV_NAME, PRODUCT.PRD_DESCRIPTION, VEN_REP_1.VR_FNAME, VEN_REP_1.VR_LNAME, 
                      VEN_REP_1.VR_MI, VEN_REP_1.VR_CODE, VEN_REP.VR_FNAME AS VR_FNAME2, VEN_REP.VR_LNAME AS VR_LNAME2, 
                      VEN_REP.VR_MI AS VR_MI2, VEN_REP.VR_CODE AS VR_CODE2, JOB_COMPONENT.JOB_COMP_DESC, JOB_LOG.JOB_DESC, 
                      RADIO_HEADER.ORDER_DATE, RADIO_DETAIL1.REV_NBR, RADIO_DETAIL1.LINE_CANCELLED, SC.SC_DESCRIPTION, RADIO_DETAIL1.MAT_COMP, '' AS [START_DATE]
	FROM         RADIO_HEADER INNER JOIN
                      RADIO_DETAIL1 ON RADIO_HEADER.ORDER_NBR = RADIO_DETAIL1.ORDER_NBR AND 
                      RADIO_HEADER.REV_NBR = RADIO_DETAIL1.REV_NBR INNER JOIN
                      RADIO_DETAIL2 ON RADIO_DETAIL1.ORDER_NBR = RADIO_DETAIL2.ORDER_NBR AND 
                      RADIO_DETAIL1.LINE_NBR = RADIO_DETAIL2.LINE_NBR AND RADIO_DETAIL1.REV_NBR = RADIO_DETAIL2.REV_NBR AND 
                      RADIO_DETAIL1.SEQ_NBR = RADIO_DETAIL2.SEQ_NBR AND 
                      RADIO_DETAIL1.BRDCAST_YEAR = RADIO_DETAIL2.BRDCAST_YEAR INNER JOIN
                      CLIENT ON RADIO_HEADER.CL_CODE = CLIENT.CL_CODE INNER JOIN
                      DIVISION ON CLIENT.CL_CODE = DIVISION.CL_CODE INNER JOIN
                      PRODUCT ON RADIO_HEADER.CL_CODE = PRODUCT.CL_CODE AND RADIO_HEADER.DIV_CODE = PRODUCT.DIV_CODE AND 
                      RADIO_HEADER.PRD_CODE = PRODUCT.PRD_CODE AND DIVISION.CL_CODE = PRODUCT.CL_CODE AND 
                      DIVISION.DIV_CODE = PRODUCT.DIV_CODE INNER JOIN
                      VENDOR ON RADIO_HEADER.VN_CODE = VENDOR.VN_CODE LEFT OUTER JOIN
                      VEN_REP AS VEN_REP_1 ON RADIO_HEADER.VR_CODE2 = VEN_REP_1.VR_CODE AND 
                      RADIO_HEADER.VN_CODE = VEN_REP_1.VN_CODE AND RADIO_HEADER.VN_CODE = VEN_REP_1.VN_CODE LEFT OUTER JOIN
                      VEN_REP ON RADIO_HEADER.VR_CODE = VEN_REP.VR_CODE AND RADIO_HEADER.VN_CODE = VEN_REP.VN_CODE AND 
                      RADIO_HEADER.VN_CODE = VEN_REP.VN_CODE LEFT OUTER JOIN
                      JOB_LOG ON RADIO_DETAIL1.JOB_NUMBER = JOB_LOG.JOB_NUMBER LEFT OUTER JOIN
                      JOB_COMPONENT ON RADIO_DETAIL1.JOB_NUMBER = JOB_COMPONENT.JOB_NUMBER AND 
                      RADIO_DETAIL1.JOB_COMPONENT_NBR = JOB_COMPONENT.JOB_COMPONENT_NBR LEFT OUTER JOIN
                      MARKET ON RADIO_HEADER.MARKET_CODE = MARKET.MARKET_CODE LEFT OUTER JOIN
                      CAMPAIGN ON RADIO_HEADER.CMP_IDENTIFIER = CAMPAIGN.CMP_IDENTIFIER LEFT OUTER JOIN
                      SALES_CLASS SC ON RADIO_HEADER.MEDIA_TYPE = SC.SC_CODE                                                  

	WHERE RADIO_HEADER.ORDER_NBR = @OrderNumber and RADIO_DETAIL1.LINE_NBR = @LineNumber and RADIO_DETAIL1.REV_NBR = @RevNumber and RADIO_DETAIL1.BRDCAST_YEAR = @Year
END
 --Radio Media Data   
IF EXISTS (SELECT ORDER_NBR FROM RADIO_HDR WHERE ORDER_NBR = @OrderNumber) 
BEGIN
		SELECT     'R' AS Type, 'A' AS EST_ACT, RADIO_HDR.OFFICE_CODE, RADIO_DETAIL.ORDER_NBR, RADIO_HDR.ORDER_DESC, 
                      RADIO_HDR.MEDIA_TYPE, RADIO_HDR.CL_CODE, RADIO_HDR.DIV_CODE, RADIO_HDR.PRD_CODE, 
                      RADIO_HDR.CMP_IDENTIFIER, CAMPAIGN.CMP_CODE, CAMPAIGN.CMP_NAME, RADIO_HDR.VN_CODE, VENDOR.VN_NAME, 
                      RADIO_HDR.BUYER, RADIO_HDR.CLIENT_PO, RADIO_HDR.MARKET_CODE, MARKET.MARKET_DESC, 
                      RADIO_DETAIL.LINE_NBR, RADIO_HDR.START_DATE AS FLIGHT_FROM, RADIO_HDR.END_DATE AS FLIGHT_TO, RADIO_DETAIL.CLOSE_DATE, 
                      RADIO_DETAIL.EXT_CLOSE_DATE, RADIO_DETAIL.MATL_CLOSE_DATE, RADIO_DETAIL.EXT_MATL_DATE, 
                      RADIO_DETAIL.START_TIME, RADIO_DETAIL.END_TIME, RADIO_DETAIL.LENGTH, RADIO_DETAIL.TAG, 
                      RADIO_DETAIL.PROGRAMMING, '' AS MATL_NOTES, RADIO_DETAIL.REMARKS, RADIO_DETAIL.JOB_NUMBER, 
                      RADIO_DETAIL.JOB_COMPONENT_NBR, RADIO_HDR.LINK_ID, RADIO_DETAIL.LINE_TOTAL, (SELECT SUM(TOTAL_SPOTS) FROM RADIO_DETAIL WHERE ORDER_NBR = @OrderNumber AND LINE_NBR = @LineNumber) AS TOTAL_SPOTS,  
                      CLIENT.CL_NAME, DIVISION.DIV_NAME, PRODUCT.PRD_DESCRIPTION, VEN_REP_1.VR_FNAME, VEN_REP_1.VR_LNAME, 
                      VEN_REP_1.VR_MI, VEN_REP_1.VR_CODE, VEN_REP.VR_FNAME AS VR_FNAME2, VEN_REP.VR_LNAME AS VR_LNAME2, 
                      VEN_REP.VR_MI AS VR_MI2, VEN_REP.VR_CODE AS VR_CODE2, JOB_COMPONENT.JOB_COMP_DESC, JOB_LOG.JOB_DESC, 
                      RADIO_HDR.ORDER_DATE, RADIO_DETAIL.REV_NBR, RADIO_DETAIL.LINE_CANCELLED, SC.SC_DESCRIPTION, RADIO_DETAIL.MAT_COMP, RADIO_DETAIL.[START_DATE]
	FROM         RADIO_HDR INNER JOIN
                      RADIO_DETAIL ON RADIO_HDR.ORDER_NBR = RADIO_DETAIL.ORDER_NBR INNER JOIN
                      CLIENT ON RADIO_HDR.CL_CODE = CLIENT.CL_CODE INNER JOIN
                      DIVISION ON CLIENT.CL_CODE = DIVISION.CL_CODE INNER JOIN
                      PRODUCT ON RADIO_HDR.CL_CODE = PRODUCT.CL_CODE AND RADIO_HDR.DIV_CODE = PRODUCT.DIV_CODE AND 
                      RADIO_HDR.PRD_CODE = PRODUCT.PRD_CODE AND DIVISION.CL_CODE = PRODUCT.CL_CODE AND 
                      DIVISION.DIV_CODE = PRODUCT.DIV_CODE INNER JOIN
                      VENDOR ON RADIO_HDR.VN_CODE = VENDOR.VN_CODE LEFT OUTER JOIN
                      VEN_REP AS VEN_REP_1 ON RADIO_HDR.VR_CODE2 = VEN_REP_1.VR_CODE AND 
                      RADIO_HDR.VN_CODE = VEN_REP_1.VN_CODE AND RADIO_HDR.VN_CODE = VEN_REP_1.VN_CODE LEFT OUTER JOIN
                      VEN_REP ON RADIO_HDR.VR_CODE = VEN_REP.VR_CODE AND RADIO_HDR.VN_CODE = VEN_REP.VN_CODE AND 
                      RADIO_HDR.VN_CODE = VEN_REP.VN_CODE LEFT OUTER JOIN
                      JOB_LOG ON RADIO_DETAIL.JOB_NUMBER = JOB_LOG.JOB_NUMBER LEFT OUTER JOIN
                      JOB_COMPONENT ON RADIO_DETAIL.JOB_NUMBER = JOB_COMPONENT.JOB_NUMBER AND 
                      RADIO_DETAIL.JOB_COMPONENT_NBR = JOB_COMPONENT.JOB_COMPONENT_NBR LEFT OUTER JOIN
                      MARKET ON RADIO_HDR.MARKET_CODE = MARKET.MARKET_CODE LEFT OUTER JOIN
                      CAMPAIGN ON RADIO_HDR.CMP_IDENTIFIER = CAMPAIGN.CMP_IDENTIFIER LEFT OUTER JOIN
                      SALES_CLASS SC ON RADIO_HDR.MEDIA_TYPE = SC.SC_CODE                                                  

	WHERE RADIO_HDR.ORDER_NBR = @OrderNumber and RADIO_DETAIL.LINE_NBR = @LineNumber and RADIO_DETAIL.REV_NBR = @RevNumber and RADIO_DETAIL.YEAR_NBR = @Year

END	


