
CREATE PROCEDURE [dbo].[usp_wv_BA_APPROVAL_JC_GET_USER_FUNCTION_DEFAULT] 
	@FNC_CODE AS VARCHAR(6),
	@JOB_NUMBER AS INT,
	@JOB_COMPONENT_NBR AS SMALLINT,
	@BA_BATCH_ID AS INT


AS

DECLARE
	@ROW_BILLING_RATE AS DECIMAL(9,2),
	@ROW_RATE_LEVEL AS SMALLINT,
	@ROW_TAX_CODE AS VARCHAR(4),
	@ROW_TAX_LEVEL SMALLINT,
	@ROW_NOBILL_FLAG SMALLINT,
	@ROW_NOBILL_LEVEL SMALLINT,
	@ROW_COMM DECIMAL(9,3),
	@ROW_COMM_LEVEL SMALLINT,
	@ROW_TAX_COMM SMALLINT,
	@ROW_TAX_COMM_ONLY SMALLINT,
	@ROW_TAX_COMM_FLAGS_LEVEL SMALLINT,
	@ROW_FEE_TIME_FLAG SMALLINT,
	@ROW_FEE_TIME_LEVEL SMALLINT,
	@ROW_STATE_PERCENT DECIMAL(8,4),
	@ROW_COUNTY_PERCENT DECIMAL(8,4),
	@ROW_CITY_PERCENT DECIMAL(8,4),
	@ROW_TAX_RESALE SMALLINT,
	@ROW_TAX_RESALE_NUMBER VARCHAR(20)
	



EXECUTE dbo.usp_wv_BA_APPROVAL_JC_GET_BILLING_RATES
				@THIS_FNC_CODE = @FNC_CODE,
				@THIS_JOB_NUMBER = @JOB_NUMBER,
				@THIS_JOB_COMPONENT_NBR = @JOB_COMPONENT_NBR,
				@THIS_BATCH_ID = @BA_BATCH_ID, 
				@THIS_BILLING_RATE = @ROW_BILLING_RATE OUTPUT,
				@THIS_RATE_LEVEL = @ROW_RATE_LEVEL OUTPUT,
				@THIS_TAX_CODE = @ROW_TAX_CODE OUTPUT,
				@THIS_TAX_LEVEL = @ROW_TAX_LEVEL OUTPUT,
				@THIS_NOBILL_FLAG = @ROW_NOBILL_FLAG OUTPUT,
				@THIS_NOBILL_LEVEL = @ROW_NOBILL_LEVEL OUTPUT,
				@THIS_COMM = @ROW_COMM OUTPUT,
				@THIS_COMM_LEVEL = @ROW_COMM_LEVEL OUTPUT,
				@THIS_TAX_COMM = @ROW_TAX_COMM OUTPUT,
				@THIS_TAX_COMM_ONLY = @ROW_TAX_COMM_ONLY OUTPUT,
				@THIS_TAX_COMM_FLAGS_LEVEL = @ROW_TAX_COMM_FLAGS_LEVEL OUTPUT,
				@THIS_FEE_TIME_FLAG = @ROW_FEE_TIME_FLAG OUTPUT,
				@THIS_FEE_TIME_LEVEL = @ROW_FEE_TIME_LEVEL OUTPUT;
				
				
IF (NOT (@ROW_TAX_CODE IS NULL))			
BEGIN
	SELECT
		@ROW_STATE_PERCENT = TAX_STATE_PERCENT,
		@ROW_COUNTY_PERCENT = TAX_COUNTY_PERCENT,
		@ROW_CITY_PERCENT = TAX_CITY_PERCENT,
		@ROW_TAX_RESALE = TAX_RESALE,
		@ROW_TAX_RESALE_NUMBER = TAX_RESALE_NUMBER
	FROM
		SALES_TAX WITH(NOLOCK)
	WHERE
		TAX_CODE = @ROW_TAX_CODE;	
			

	
END				
				
SELECT 
	@ROW_BILLING_RATE AS BILLING_RATE,
	@ROW_RATE_LEVEL AS RATE_LEVEL,
	@ROW_TAX_CODE AS TAX_CODE,
	@ROW_TAX_LEVEL AS TAX_LEVEL,
	@ROW_NOBILL_FLAG AS NOBILL_FLAG,
	@ROW_NOBILL_LEVEL AS NOBILL_LEVEL,
	@ROW_COMM AS COMM,
	@ROW_COMM_LEVEL AS COMM_LEVEL,
	@ROW_TAX_COMM AS TAX_COMM,
	@ROW_TAX_COMM_ONLY AS TAX_COMM_ONLY,
	@ROW_TAX_COMM_FLAGS_LEVEL AS TAX_COMM_FLAGS_LEVEL,
	@ROW_FEE_TIME_FLAG AS FEE_TIME_FLAG,
	@ROW_FEE_TIME_LEVEL AS FEE_TIME_LEVEL,
	ISNULL(@ROW_STATE_PERCENT,0.00) AS TAX_STATE_PERCENT,
	ISNULL(@ROW_COUNTY_PERCENT,0.00) AS TAX_COUNTY_PERCENT,
	ISNULL(@ROW_CITY_PERCENT,0.00) AS TAX_CITY_PERCENT,
	@ROW_TAX_RESALE AS TAX_RESALE,
	@ROW_TAX_RESALE_NUMBER AS TAX_RESALE_NUMBER;

EXEC usp_wv_validate_functioncode_all @FNC_CODE;	


