
CREATE PROCEDURE [dbo].[usp_wv_ALERT_STATES_INSERT] /*WITH ENCRYPTION*/
	@ALERT_STATE_NAME VARCHAR(100),
	@ACTIVE_FLAG BIT,
	@DFLT_ALERT_CAT_ID INT
AS
/*=========== QUERY ===========*/
	DECLARE @NEW_ID INT
	
	INSERT INTO ALERT_STATES WITH(ROWLOCK)
	(
		ALERT_STATE_NAME,
		ACTIVE_FLAG,
		DFLT_ALERT_CAT_ID
	)
	VALUES
	(
		@ALERT_STATE_NAME,
		@ACTIVE_FLAG,
		@DFLT_ALERT_CAT_ID
	);
	SELECT @NEW_ID = SCOPE_IDENTITY();
	SELECT @NEW_ID;
	RETURN @NEW_ID;
/*=========== QUERY ===========*/
