








/*****************************************************************
Gets Media Types for Drop Down s
******************************************************************/
CREATE PROCEDURE [dbo].[usp_cp_dd_GetMediaTypes] 
@CDPID int
AS
Declare @Restrictions Int

Set NoCount on

Select @Restrictions = Count(*) 
FROM CP_SEC_CLIENT
Where CDP_CONTACT_ID = @CDPID

SELECT DISTINCT MEDIA_TYPE
FROM MAGAZINE_HEADER INNER JOIN
      CP_SEC_CLIENT ON MAGAZINE_HEADER.CL_CODE = CP_SEC_CLIENT.CL_CODE AND 
      MAGAZINE_HEADER.DIV_CODE = CP_SEC_CLIENT.DIV_CODE AND 
      MAGAZINE_HEADER.PRD_CODE = CP_SEC_CLIENT.PRD_CODE
WHERE CP_SEC_CLIENT.CDP_CONTACT_ID = @CDPID
UNION
SELECT DISTINCT MEDIA_TYPE
FROM NEWSPAPER_HEADER INNER JOIN
      CP_SEC_CLIENT ON NEWSPAPER_HEADER.CL_CODE = CP_SEC_CLIENT.CL_CODE AND 
      NEWSPAPER_HEADER.DIV_CODE = CP_SEC_CLIENT.DIV_CODE AND 
      NEWSPAPER_HEADER.PRD_CODE = CP_SEC_CLIENT.PRD_CODE
WHERE CP_SEC_CLIENT.CDP_CONTACT_ID = @CDPID
UNION
SELECT DISTINCT MEDIA_TYPE
FROM INTERNET_HEADER INNER JOIN
      CP_SEC_CLIENT ON INTERNET_HEADER.CL_CODE = CP_SEC_CLIENT.CL_CODE AND 
      INTERNET_HEADER.DIV_CODE = CP_SEC_CLIENT.DIV_CODE AND 
      INTERNET_HEADER.PRD_CODE = CP_SEC_CLIENT.PRD_CODE
WHERE CP_SEC_CLIENT.CDP_CONTACT_ID = @CDPID
UNION
SELECT DISTINCT MEDIA_TYPE
FROM OUTDOOR_HEADER INNER JOIN
      CP_SEC_CLIENT ON OUTDOOR_HEADER.CL_CODE = CP_SEC_CLIENT.CL_CODE AND 
      OUTDOOR_HEADER.DIV_CODE = CP_SEC_CLIENT.DIV_CODE AND 
      OUTDOOR_HEADER.PRD_CODE = CP_SEC_CLIENT.PRD_CODE
WHERE CP_SEC_CLIENT.CDP_CONTACT_ID = @CDPID
UNION
SELECT DISTINCT MEDIA_TYPE
FROM RADIO_HEADER INNER JOIN
      CP_SEC_CLIENT ON RADIO_HEADER.CL_CODE = CP_SEC_CLIENT.CL_CODE AND 
      RADIO_HEADER.DIV_CODE = CP_SEC_CLIENT.DIV_CODE AND 
      RADIO_HEADER.PRD_CODE = CP_SEC_CLIENT.PRD_CODE
WHERE CP_SEC_CLIENT.CDP_CONTACT_ID = @CDPID
UNION
SELECT DISTINCT MEDIA_TYPE
FROM TV_HEADER INNER JOIN
      CP_SEC_CLIENT ON TV_HEADER.CL_CODE = CP_SEC_CLIENT.CL_CODE AND 
      TV_HEADER.DIV_CODE = CP_SEC_CLIENT.DIV_CODE AND 
      TV_HEADER.PRD_CODE = CP_SEC_CLIENT.PRD_CODE
WHERE CP_SEC_CLIENT.CDP_CONTACT_ID = @CDPID




















