--DROP FUNCTION [dbo].[advfn_local_date]
CREATE FUNCTION [dbo].[advfn_local_date](
@OFFSET [DECIMAL](9,3),
@date SMALLDATETIME
)
RETURNS SMALLDATETIME
AS
BEGIN

	DECLARE 
		@OFFSET_HOURS INT,
		@OFFSET_TOTAL_MINUTES INT,
		@RETURN_DATE SMALLDATETIME;
	
	IF NOT @date IS NULL
	BEGIN
		IF @OFFSET IS NULL
		BEGIN
			SELECT 
				@OFFSET = TIME_ZONE.OFFSET_HOURS - TIME_ZONE_DB.OFFSET_HOURS
			FROM            
				AGENCY WITH(NOLOCK) INNER JOIN
				TIME_ZONE AS TIME_ZONE_DB WITH(NOLOCK) ON AGENCY.DB_TIMEZONE_ID = TIME_ZONE_DB.ID INNER JOIN
				TIME_ZONE  WITH(NOLOCK) ON AGENCY.TIMEZONE_ID = TIME_ZONE.ID;
		END

		SET @OFFSET = ISNULL(@OFFSET, 0);
	
		IF @OFFSET <> 0
		BEGIN
			SET @OFFSET_HOURS = CONVERT(INT, @OFFSET);
			SET @OFFSET_TOTAL_MINUTES = (@OFFSET_HOURS * 60) + (@OFFSET - @OFFSET_HOURS);
			SET @RETURN_DATE = ISNULL(DATEADD(mi, @OFFSET_TOTAL_MINUTES, @date), @date);
		END
		ELSE
		BEGIN
			SET @RETURN_DATE = @date;
		END
	END

	RETURN @RETURN_DATE;

END