CREATE FUNCTION [dbo].[advfn_media_manager_get_order_line_status] ( 
	@order_number integer, 
	@line_number smallint
)
RETURNS varchar(100)
WITH SCHEMABINDING
AS
BEGIN
	DECLARE @order_line_status varchar(100)

	SELECT TOP 1 @order_line_status = OS.STATUS_DESC 
	FROM
		(
		SELECT REC_ID, ORDER_NBR, LINE_NBR, REV_NBR, [STATUS], REVISED_DATE FROM dbo.INTERNET_ORDER_STATUS
		UNION
		SELECT REC_ID, ORDER_NBR, LINE_NBR, REV_NBR, [STATUS], REVISED_DATE FROM dbo.MAGAZINE_ORDER_STATUS
		UNION
		SELECT REC_ID, ORDER_NBR, LINE_NBR, REV_NBR, [STATUS], REVISED_DATE FROM dbo.NEWSPAPER_ORDER_STATUS
		UNION
		SELECT REC_ID, ORDER_NBR, LINE_NBR, REV_NBR, [STATUS], REVISED_DATE FROM dbo.OUTDOOR_ORDER_STATUS
		UNION
		SELECT REC_ID, ORDER_NBR, LINE_NBR, REV_NBR, [STATUS], REVISED_DATE FROM dbo.RADIO_ORDER_STATUS
		UNION
		SELECT REC_ID, ORDER_NBR, LINE_NBR, REV_NBR, [STATUS], REVISED_DATE FROM dbo.TV_ORDER_STATUS
		) Statuses
			INNER JOIN dbo.ORDER_STATUS OS ON Statuses.STATUS = OS.STATUS 
	WHERE ORDER_NBR =@order_number
	AND LINE_NBR = @line_number
	ORDER BY REVISED_DATE DESC, REC_ID DESC

	RETURN @order_line_status
END
GO