IF EXISTS(SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'BILL_APPR_BATCH' AND COLUMN_NAME = 'PROCESSED_ALL')
	ALTER TABLE dbo.BILL_APPR_BATCH DROP COLUMN PROCESSED_ALL
GO

CREATE FUNCTION dbo.advfn_bill_appr_processed_all ( @ba_batch_id integer )
RETURNS bit
AS
BEGIN
	RETURN
	(
			CASE WHEN NOT EXISTS(
								SELECT 1
								FROM dbo.BILL_APPR_BATCH bab
									LEFT OUTER JOIN dbo.BILL_APPR ba ON ( bab.BA_BATCH_ID = ba.BA_BATCH_ID )
									LEFT OUTER JOIN dbo.BILL_APPR_HDR bah ON ( ba.BA_ID = bah.BA_ID )
								WHERE bab.BA_BATCH_ID = @ba_batch_id
								AND bah.PROCESSED = 0
								) THEN 1 ELSE 0 END
	)
END
GO

IF NOT EXISTS(SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'BILL_APPR_BATCH' AND COLUMN_NAME = 'PROCESSED_ALL')
	ALTER TABLE dbo.BILL_APPR_BATCH ADD PROCESSED_ALL AS ([dbo].[advfn_bill_appr_processed_all]([BA_BATCH_ID]))
GO
