CREATE FUNCTION [dbo].[advfn_get_po_display_num] ( @PO_NUMBER INT )
RETURNS VARCHAR(12)
AS
BEGIN

	DECLARE @PO_DISPLAY_NUMBER VARCHAR(12)

	SELECT @PO_DISPLAY_NUMBER = DISPLAY_PO_NUMBER FROM dbo.V_PURCHASE_ORDER WHERE PO_NUMBER = @PO_NUMBER
	
	RETURN @PO_DISPLAY_NUMBER
	
END