CREATE FUNCTION [dbo].[advfn_get_next_media_import_order_id] ( @SourceCode varchar(2))
RETURNS int
AS
BEGIN
declare @OrderID int

SELECT @OrderID = MAX(Orders.ORDER_ID)
FROM (
		SELECT COALESCE(MAX(IMPORT_ORDER_NBR), 0) + 1 AS ORDER_ID
		FROM dbo.BRD_IMPORT_XREF 
		WHERE IMPORTED_FROM = @SourceCode UNION
		
		SELECT COALESCE(MAX(LINK_ID), 0) + 1
		FROM dbo.BRDCAST_IMPORT
		WHERE MEDIA_INTERFACE = @SourceCode UNION

		SELECT COALESCE(MAX(IMPORT_ORDER_NBR), 0) + 1
		FROM dbo.PRINT_IMPORT_XREF 
		WHERE IMPORTED_FROM = @SourceCode UNION

		SELECT COALESCE(MAX(ACCT_ORD_NBR), 0) + 1
		FROM dbo.PRINT_ORDER 
		WHERE MEDIA_INTERFACE = @SourceCode
	) Orders

RETURN @OrderID
END

GO

