CREATE FUNCTION [dbo].[advfn_bookend_verify]
	(@DTL_ID INT,
	 @MEDIA_TYPE VARCHAR(10),
	 @BOOKEND_MAX_SEPARATION SMALLINT,
	 @VERIFY_TIME_SEP BIT,
	 @TIME_SEPARATION INT)
RETURNS VARCHAR(20) WITH SCHEMABINDING
AS
BEGIN

	DECLARE @ORDER_NBR INT,
			@ORDER_LINE_NBR SMALLINT,
			@VERIFIED VARCHAR(20), --:   'Time Sep | ', -2 = 'Bookend | '
			@ID INT,
			@IS_TIME_SEP_VERIFIED BIT,
			@PREV_DTL_ID INT,
			@SPOT_DATETIME smalldatetime,
			@PREV_SPOT_DATETIME smalldatetime
			
	DECLARE @SPOTS TABLE (
		ID int IDENTITY(1,1) NOT NULL,
		DTL_ID INT NOT NULL,
		SPOT_DATETIME SMALLDATETIME NOT NULL
	)

	SELECT @ORDER_NBR = ORDER_NBR, @ORDER_LINE_NBR = ORDER_LINE_NBR 
	FROM dbo.AP_TV_BROADCAST_DTL 
	WHERE DTL_ID = @DTL_ID

	INSERT INTO @SPOTS (DTL_ID, SPOT_DATETIME)
	SELECT DTL_ID, [RUN_DATE] + CAST(TIME_OF_DAY AS smalldatetime)
	FROM dbo.AP_TV_BROADCAST_DTL 
	WHERE ORDER_NBR = @ORDER_NBR
	AND ORDER_LINE_NBR = @ORDER_LINE_NBR
	ORDER BY RUN_DATE, TIME_OF_DAY 

	SET @VERIFIED = ''

	IF @MEDIA_TYPE = 'Radio'
	BEGIN

		SET @VERIFIED = ''

	END
	ELSE IF @MEDIA_TYPE = 'TV'
	BEGIN
		--IF (SELECT COUNT(1) FROM @SPOTS) % 2 = 1 --AND EXISTS(SELECT 1 FROM @SPOTS WHERE ID > (SELECT ID FROM @SPOTS WHERE DTL_ID = @DTL_ID))
		--	SET @VERIFIED = 'Bookend Sep | '
		--ELSE BEGIN
			
			SELECT @ID = ID, @SPOT_DATETIME = SPOT_DATETIME FROM @SPOTS WHERE DTL_ID = @DTL_ID
				
			SELECT @PREV_DTL_ID = DTL_ID, @PREV_SPOT_DATETIME = SPOT_DATETIME FROM @SPOTS WHERE ID = @ID - 1

			IF (SELECT ID FROM @SPOTS WHERE DTL_ID = @DTL_ID) % 2 = 0 BEGIN --even numbered spot
				
				IF @PREV_DTL_ID IS NOT NULL
					IF (SELECT DATEADD(minute,@BOOKEND_MAX_SEPARATION,SPOT_DATETIME) FROM @SPOTS WHERE ID = @ID - 1) < (SELECT SPOT_DATETIME FROM @SPOTS WHERE ID = @ID)
						SET @VERIFIED = 'Bookend Sep | '
				
			END ELSE BEGIN  --odd numbered spot

				IF @PREV_DTL_ID IS NOT NULL AND @VERIFY_TIME_SEP = 1 AND @TIME_SEPARATION <> 0 BEGIN
					IF (SELECT DATEDIFF(N, @PREV_SPOT_DATETIME, @SPOT_DATETIME)) < @TIME_SEPARATION
						SET @VERIFIED = 'Time Sep | '
					--SELECT @IS_TIME_SEP_VERIFIED = dbo.advfn_time_sep_verify(@PREV_DTL_ID, @MEDIA_TYPE, @TIME_SEPARATION)
					--IF @IS_TIME_SEP_VERIFIED = 0
					--	SET @VERIFIED = 'Time Sep | '
				END

			END
			
		--END
	END
	
	RETURN @VERIFIED

END
GO
