IF EXISTS ( SELECT * FROM sysobjects WHERE id = OBJECT_ID( N'[dbo].[advtf_paymentcenter_GetInvoiceTypesByBatch]' ) AND xtype IN ( N'FN', N'IF', N'TF' ))
BEGIN
	DROP FUNCTION [dbo].[advtf_paymentcenter_GetInvoiceTypesByBatch]
END
GO
CREATE FUNCTION [dbo].[advtf_paymentcenter_GetInvoiceTypesByBatch](@BATCH_ID INTEGER)       
RETURNS @INVOICE_TYPES TABLE (AP_ID INT, INVOICE_TYPE VARCHAR(25)) WITH SCHEMABINDING       
AS     
BEGIN

	BEGIN
				INSERT INTO @INVOICE_TYPES
				SELECT A.AP_ID, A.MEDIA_TYPE FROM (
				SELECT AP.AP_ID, 'Internet' AS MEDIA_TYPE
				FROM dbo.AP_INTERNET AP WITH (NOLOCK) JOIN dbo.AP_PMT_HIST I WITH (NOLOCK) ON AP.AP_ID = I.AP_ID			
				WHERE I.GLEXACT = @BATCH_ID
				UNION
				SELECT AP.AP_ID, 'Newspaper' AS MEDIA_TYPE
				FROM dbo.AP_NEWSPAPER AP WITH (NOLOCK) JOIN dbo.AP_PMT_HIST I WITH (NOLOCK) ON AP.AP_ID = I.AP_ID			
				WHERE I.GLEXACT = @BATCH_ID
				UNION
				SELECT AP.AP_ID, 'Magazine' AS MEDIA_TYPE
				FROM dbo.AP_MAGAZINE AP WITH (NOLOCK) JOIN dbo.AP_PMT_HIST I WITH (NOLOCK) ON AP.AP_ID = I.AP_ID			
				WHERE I.GLEXACT = @BATCH_ID
				UNION
				SELECT AP.AP_ID, 'Radio' AS MEDIA_TYPE
				FROM dbo.AP_RADIO AP WITH (NOLOCK) JOIN dbo.AP_PMT_HIST I WITH (NOLOCK) ON AP.AP_ID = I.AP_ID			
				WHERE I.GLEXACT = @BATCH_ID
				--RADIO_HEADER IS A LEGACY TABLE
				UNION
				SELECT AP.AP_ID, 'Television' AS MEDIA_TYPE
				FROM dbo.AP_TV AP WITH (NOLOCK) JOIN dbo.AP_PMT_HIST I WITH (NOLOCK) ON AP.AP_ID = I.AP_ID			
				WHERE I.GLEXACT = @BATCH_ID
				--TV_HEADER IS A LEGACY TABLE
				UNION
				SELECT AP.AP_ID, 'Outdoor' AS MEDIA_TYPE
				FROM dbo.AP_OUTDOOR AP WITH (NOLOCK) JOIN dbo.AP_PMT_HIST I WITH (NOLOCK) ON AP.AP_ID = I.AP_ID			
				WHERE I.GLEXACT = @BATCH_ID
				UNION
				SELECT AP.AP_ID, 'Production' AS MEDIA_TYPE
				FROM dbo.AP_PRODUCTION AP WITH (NOLOCK) JOIN dbo.AP_PMT_HIST I WITH (NOLOCK) ON AP.AP_ID = I.AP_ID			
				WHERE I.GLEXACT = @BATCH_ID
				UNION
				SELECT AP.AP_ID, 'GL Dist' AS MEDIA_TYPE
				FROM dbo.AP_GL_DIST AP WITH (NOLOCK) JOIN dbo.AP_PMT_HIST I WITH (NOLOCK) ON AP.AP_ID = I.AP_ID			
				WHERE I.GLEXACT = @BATCH_ID) A
	END

	RETURN

END