IF EXISTS ( SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID( N'[dbo].[advtf_unassigned_active_backlog_alerts]' ) AND xtype IN ( N'FN', N'IF', N'TF' ))
BEGIN
	DROP FUNCTION [dbo].[advtf_unassigned_active_backlog_alerts]
END
GO

CREATE FUNCTION [dbo].[advtf_unassigned_active_backlog_alerts] (
)
RETURNS
@RETURN_TABLE TABLE (
    ALERT_ID INT
)
AS
BEGIN
    BEGIN
	   IF EXISTS (
		  SELECT 1
		  FROM 
			 BOARD B
			 INNER JOIN SPRINT_HDR SH ON B.ID = SH.BOARD_ID
		  WHERE
			 SH.IS_ACTIVE = 1 AND B.INCL_ALL_JOBS = 1
	   )
	   BEGIN
		   INSERT INTO @RETURN_TABLE
		  SELECT A.ALERT_ID
		  FROM 
			 ALERT A
		  WHERE
			 A.IS_WORK_ITEM = 1 
			 AND (
				    (NOT A.ALRT_NOTIFY_HDR_ID IS NULL AND NOT A.ALERT_STATE_ID IS NULL AND A.ASSIGNED_EMP_CODE IS NULL) -- ROUTED
				    OR (A.ALERT_LEVEL <> 'BRD' AND A.ALRT_NOTIFY_HDR_ID IS NULL AND A.ALERT_STATE_ID IS NULL AND (A.BOARD_STATE_ID IS NULL OR A.BOARD_STATE_ID = -1)) -- MULTI
				 )
			 AND (SELECT COUNT(1) FROM (SELECT A.ALERT_ID FROM ALERT_RCPT AR WHERE AR.ALERT_ID = A.ALERT_ID AND AR.CURRENT_NOTIFY = 1 
								   UNION 
								   SELECT A.ALERT_ID FROM ALERT_RCPT_DISMISSED ARD WHERE ARD.ALERT_ID = A.ALERT_ID AND ARD.CURRENT_NOTIFY = 1) AS Z) = 0 -- NO ASSIGNEES
		      AND (SELECT COUNT(1) FROM SPRINT_DTL SD INNER JOIN SPRINT_HDR SH ON SD.SPRINT_HDR_ID = SH.ID WHERE SD.ALERT_ID = A.ALERT_ID AND SH.IS_ACTIVE = 1) = 0
	   END
	   ELSE
	   BEGIN
		   INSERT INTO @RETURN_TABLE
		  SELECT A.ALERT_ID
		  FROM 
			 BOARD B
			 INNER JOIN SPRINT_HDR SH ON B.ID = SH.BOARD_ID
			 INNER JOIN BOARD_JOB BJ ON B.ID = BJ.BOARD_ID
			 INNER JOIN ALERT A ON BJ.JOB_NUMBER = A.JOB_NUMBER AND BJ.JOB_COMPONENT_NBR = A.JOB_COMPONENT_NBR
		  WHERE
			 SH.IS_ACTIVE = 1
			 AND A.IS_WORK_ITEM = 1 
			 AND (
				    (NOT A.ALRT_NOTIFY_HDR_ID IS NULL AND NOT A.ALERT_STATE_ID IS NULL AND A.ASSIGNED_EMP_CODE IS NULL)
				    OR (A.ALERT_LEVEL <> 'BRD' AND A.ALRT_NOTIFY_HDR_ID IS NULL AND A.ALERT_STATE_ID IS NULL AND (A.BOARD_STATE_ID IS NULL OR A.BOARD_STATE_ID = -1))
				 )
			 AND (SELECT COUNT(1) FROM (SELECT A.ALERT_ID FROM ALERT_RCPT AR WHERE AR.ALERT_ID = A.ALERT_ID AND AR.CURRENT_NOTIFY = 1 
								   UNION 
								   SELECT A.ALERT_ID FROM ALERT_RCPT_DISMISSED ARD WHERE ARD.ALERT_ID = A.ALERT_ID AND ARD.CURRENT_NOTIFY = 1) AS Z) = 0
	   END
    END

    RETURN

END

GO