IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[fn_my_objects_employee_has_dynamic_restriction]') AND xtype IN (N'FN', N'IF', N'TF'))
DROP FUNCTION [dbo].[fn_my_objects_employee_has_dynamic_restriction]
GO
CREATE FUNCTION [dbo].[fn_my_objects_employee_has_dynamic_restriction] (@EMP_CODE AS VARCHAR(6), @OBJECT_ID INT)
RETURNS BIT
AS
BEGIN

	DECLARE 
		@HAS_RESTRICTION BIT,
		@EMP_HAS_RESTRICTION BIT,
		@OBJECT_HAS_RESTRICTION BIT
		
	SET @HAS_RESTRICTION = 0;
	SET @EMP_HAS_RESTRICTION = 0;
	SET @OBJECT_HAS_RESTRICTION = 0;
	
	IF EXISTS (

		SELECT *
		FROM         
			MY_OBJ_DEF_SETTINGS
		WHERE     
			(MY_OBJ_DEF_SETTINGS.IS_STATIC = 0) 
			AND (MY_OBJ_DEF_SETTINGS.OBJECT_ID = @OBJECT_ID)
			AND (MY_OBJ_DEF_SETTINGS.CHECKED = 1)
			
	)
	BEGIN

		SET @OBJECT_HAS_RESTRICTION = 1;
		
	END		

	IF EXISTS (

		SELECT * 
		FROM 
			ACCOUNT_EXECUTIVE AS A
		WHERE
			(INACTIVE_FLAG = 0 OR INACTIVE_FLAG IS NULL )
			AND A.EMP_CODE = @EMP_CODE
			
	)
	BEGIN

		SET @EMP_HAS_RESTRICTION = 1;
		
	END	
		
	IF @EMP_HAS_RESTRICTION = 1 AND @OBJECT_HAS_RESTRICTION = 1
	BEGIN
	
		SET @HAS_RESTRICTION = 1;
		
	END	
		
	RETURN @HAS_RESTRICTION;

END