--DROP FUNCTION [dbo].[fn_my_objects_get_dynamic_restrictions]
CREATE FUNCTION [dbo].[fn_my_objects_get_dynamic_restrictions] (@OBJECT_ID AS INT, @EMP_CODE AS VARCHAR(6))
RETURNS @OBJECT_DEFINITIONS TABLE 
(
	CL_CODE VARCHAR(6),
	DIV_CODE VARCHAR(6),
	PRD_CODE VARCHAR(6)
)
AS
BEGIN

	IF @OBJECT_ID = 3 -- MY CLIENT AGING
	BEGIN
		
		-- INSERT ONLY DEFAULT AE FOR MGMT LEVEL AE
		INSERT INTO @OBJECT_DEFINITIONS(
			CL_CODE, 
			DIV_CODE, 
			PRD_CODE 
			)
		SELECT DISTINCT
			B.CL_CODE, 
			B.DIV_CODE,
			B.PRD_CODE
		FROM 
			[dbo].[fn_my_objects_get_object_definitions] (@OBJECT_ID, 1) AS A
			INNER JOIN ACCOUNT_EXECUTIVE AS B WITH(NOLOCK) ON A.DEFINITION_ID = B.MGMT_LVL_ID
		WHERE 
			A.IS_STATIC = 0 
			AND B.EMP_CODE = @EMP_CODE
			AND (B.INACTIVE_FLAG = 0 OR B.INACTIVE_FLAG IS NULL)
			AND B.MGMT_LVL_ID = 1; -- AE
			--AND B.DEFAULT_AE = 1; -- AND ONLY DEFAULT AE

		-- INSERT THE OTHER MGMT LEVELS
		INSERT INTO @OBJECT_DEFINITIONS(
			CL_CODE, 
			DIV_CODE, 
			PRD_CODE 
			)
		SELECT DISTINCT
			B.CL_CODE, 
			B.DIV_CODE,
			B.PRD_CODE
		FROM 
			[dbo].[fn_my_objects_get_object_definitions] (@OBJECT_ID, 1) AS A
			INNER JOIN ACCOUNT_EXECUTIVE AS B WITH(NOLOCK) ON A.DEFINITION_ID = B.MGMT_LVL_ID
		WHERE 
			A.IS_STATIC = 0 
			AND B.EMP_CODE = @EMP_CODE
			AND (B.INACTIVE_FLAG = 0 OR B.INACTIVE_FLAG IS NULL)
			AND B.MGMT_LVL_ID <> 1; -- NOT AE; DON'T CARE ABOUT DEFAULT AE FLAG

	END
	ELSE
	BEGIN

		--DON'T CARE IF DEFAULT AE OR NOT FOR OTHER OBJECTS
		INSERT INTO @OBJECT_DEFINITIONS(
			CL_CODE, 
			DIV_CODE, 
			PRD_CODE 
			)
		SELECT DISTINCT
			B.CL_CODE, 
			B.DIV_CODE,
			B.PRD_CODE
		FROM 
			[dbo].[fn_my_objects_get_object_definitions] (@OBJECT_ID, 1) AS A
			INNER JOIN ACCOUNT_EXECUTIVE AS B WITH(NOLOCK) ON A.DEFINITION_ID = B.MGMT_LVL_ID
		WHERE 
			A.IS_STATIC = 0 
			AND B.EMP_CODE = @EMP_CODE
			AND (B.INACTIVE_FLAG = 0 OR B.INACTIVE_FLAG IS NULL);

	END
		
RETURN

END