
CREATE FUNCTION [dbo].[udf_get_emp_time_dlt_hours_sum] ( @et_id integer )  		  	
RETURNS DECIMAL(7,2) AS  	

BEGIN  
	DECLARE @EMP_HOURS	DECIMAL(7,2)
	DECLARE @EMP_HOURS_NP	DECIMAL(7,2)

	SELECT @EMP_HOURS = SUM(EMP_TIME_DTL.EMP_HOURS) 
	FROM EMP_TIME_DTL 
	WHERE EMP_TIME_DTL.ET_ID = @et_id 
	
	SELECT @EMP_HOURS_NP = SUM(EMP_TIME_NP.EMP_HOURS)
	FROM EMP_TIME_NP 
	WHERE EMP_TIME_NP.ET_ID = @et_id
	
	SET @EMP_HOURS = ISNULL(@EMP_HOURS,0) + ISNULL(@EMP_HOURS_NP,0)

	RETURN ISNULL(@EMP_HOURS,0)
END	
