
CREATE FUNCTION [dbo].[udf_ap_get_direct_bill_amt] (@al_ap_id INT, @as_vn_category VARCHAR(1))
RETURNS decimal(14,2)
/*Returns direct bill amount for given AP */
AS
BEGIN
	DECLARE @ldec_prod_amt decimal(14,2)
	DECLARE @ldec_media_amt decimal(14,2), @ldec_media_amt2 decimal(14,2)
	DECLARE @ldec_total_amt decimal(14,2)

	--PJH 08/29/07 - Added "AND AB_FLAG NOT IN (6)"
	--PJH 10/23/07 - added EXT_NONRESALE_TAX Per EC
	SET @ldec_prod_amt = (
			SELECT ( COALESCE(SUM(AP.AP_PROD_EXT_AMT), 0) 
				+ COALESCE(SUM(AP.EXT_NONRESALE_TAX), 0) )
			FROM AP_PRODUCTION AP
			WHERE AP.AP_ID = @al_ap_id AND AB_FLAG NOT IN (6)
			AND AR_INV_NBR IS NOT NULL
			AND (AP_PROD_NOBILL_FLG = 0 OR AP_PROD_NOBILL_FLG IS NULL) )
	
	IF @as_vn_category = 'N'
		BEGIN
		SET @ldec_media_amt = (SELECT COALESCE(SUM(OD.EXT_NET_AMT), 0) + COALESCE(SUM(OD.DISCOUNT_AMT), 0) +
					COALESCE(SUM(OD.NETCHARGE), 0) + COALESCE(SUM(OD.VENDOR_TAX), 0)
			FROM V_NEWS_DETAIL OD, AP_NEWSPAPER AP
			WHERE AP.AP_ID = @al_ap_id AND OD.AR_INV_NBR IS NOT NULL AND
			OD.ORDER_NBR = AP.ORDER_NBR AND OD.LINE_NBR = AP.ORDER_LINE_NBR)
		END
	ELSE
	IF @as_vn_category = 'M'
		BEGIN
		SET @ldec_media_amt = (SELECT COALESCE(SUM(OD.EXT_NET_AMT), 0) + COALESCE(SUM(OD.DISCOUNT_AMT), 0) +
					COALESCE(SUM(OD.NETCHARGE), 0) + COALESCE(SUM(OD.VENDOR_TAX), 0)
			FROM V_MAG_DETAIL OD, AP_MAGAZINE AP
			WHERE AP.AP_ID = @al_ap_id AND OD.AR_INV_NBR IS NOT NULL AND
			OD.ORDER_NBR = AP.ORDER_NBR AND OD.LINE_NBR = AP.ORDER_LINE_NBR)
		END
	ELSE
	IF @as_vn_category = 'R'
		BEGIN
		SET @ldec_media_amt = (SELECT COALESCE(SUM(OD.MON_LINE_NET), 0) + COALESCE(SUM(OD.MON_VENDOR_TAX), 0) +
					COALESCE(SUM(OD.MON_DISCOUNT), 0)
			FROM V_RADIO_DETAIL OD, AP_RADIO AP
			WHERE AP.AP_ID = @al_ap_id AND OD.MON_AR_INV_NBR IS NOT NULL AND
			OD.ORDER_NBR = AP.ORDER_NBR AND OD.MONTH_SHORT = AP.BRDCAST_MONTH)
		END
	ELSE
	IF @as_vn_category = 'T'
		BEGIN
		SET @ldec_media_amt = (SELECT COALESCE(SUM(OD.MON_LINE_NET), 0) + COALESCE(SUM(OD.MON_VENDOR_TAX), 0) +
					COALESCE(SUM(OD.MON_DISCOUNT), 0)
			FROM V_TV_DETAIL OD, AP_TV AP
			WHERE AP.AP_ID = @al_ap_id AND OD.MON_AR_INV_NBR IS NOT NULL AND
			OD.ORDER_NBR = AP.ORDER_NBR AND OD.MONTH_SHORT = AP.BRDCAST_MONTH)
		END
	ELSE
	IF @as_vn_category = 'O'
		SET @ldec_media_amt = (SELECT COALESCE(SUM(OD.EXT_NET_AMT), 0) + COALESCE(SUM(OD.DISCOUNT_AMT), 0) +
					COALESCE(SUM(OD.NETCHARGE), 0) + COALESCE(SUM(OD.NON_RESALE_AMT), 0)
			FROM OUTDOOR_DETAIL OD, AP_OUTDOOR AP
			WHERE AP.AP_ID = @al_ap_id AND OD.AR_INV_NBR IS NOT NULL AND
			OD.ORDER_NBR = AP.ORDER_NBR AND OD.LINE_NBR = AP.ORDER_LINE_NBR)
	ELSE
	IF @as_vn_category = 'I'
		SET @ldec_media_amt = (SELECT COALESCE(SUM(OD.EXT_NET_AMT), 0) + COALESCE(SUM(OD.DISCOUNT_AMT), 0) +
					COALESCE(SUM(OD.NETCHARGE), 0) + COALESCE(SUM(OD.NON_RESALE_AMT), 0)
			FROM INTERNET_DETAIL OD, AP_INTERNET AP
			WHERE AP.AP_ID = @al_ap_id AND OD.AR_INV_NBR IS NOT NULL AND
			OD.ORDER_NBR = AP.ORDER_NBR AND OD.LINE_NBR = AP.ORDER_LINE_NBR)
	
	IF @ldec_media_amt IS NULL
		SET @ldec_media_amt = 0

	IF @ldec_media_amt2 IS NULL
		SET @ldec_media_amt2 = 0
	
	IF @ldec_prod_amt IS NULL
		SET @ldec_prod_amt = 0
	
	SET @ldec_total_amt = @ldec_media_amt + @ldec_media_amt2 + @ldec_prod_amt
	
	RETURN @ldec_total_amt
END
