
CREATE FUNCTION [dbo].[wvfn_timeserial]
(
	@THE_DATE SMALLDATETIME,
	@RETURN_FULL_DATE_TIME_SERIAL BIT
)
RETURNS FLOAT
AS
BEGIN
    DECLARE @RETURN_VALUE FLOAT;
    
    IF @THE_DATE IS NULL
        BEGIN
            SET @RETURN_VALUE = 0;
        END
    ELSE
        BEGIN
            --WILL RETURN A FLOAT OF THE FULL DATE TIME TO DO NUMERICAL COMPARISON
            IF @RETURN_FULL_DATE_TIME_SERIAL = 0
            BEGIN
	            SET @RETURN_VALUE = CAST(@THE_DATE AS FLOAT) - FLOOR(CAST(@THE_DATE AS FLOAT));
            END
            --WILL RETURN A FLOAT OF JUST THE TIME TO DO NUMERICAL COMPARISON
            IF @RETURN_FULL_DATE_TIME_SERIAL = 1
            BEGIN
	            SET @RETURN_VALUE = CAST(@THE_DATE AS FLOAT) ;
            END
        END
    
    RETURN @RETURN_VALUE;  
END
