--DROP FUNCTION dbo.wvfn_ts_minimum_time_entry
CREATE FUNCTION dbo.wvfn_ts_minimum_time_entry
(

@HOURS DECIMAL(7,2),
@FOR_GENERAL_ENTRY BIT

)
RETURNS DECIMAL(7,2)
AS
BEGIN

	SET @HOURS = ISNULL(@HOURS, 0.00);
	SET @FOR_GENERAL_ENTRY = ISNULL(@FOR_GENERAL_ENTRY, 0);

	IF @HOURS > 0.00
	BEGIN

			DECLARE
			@TS_MIN_TIME DECIMAL(7,2),
			@TS_ROUND_TO DECIMAL(7,2)

			IF @FOR_GENERAL_ENTRY = 1
			BEGIN

				SELECT @TS_MIN_TIME = CONVERT(DECIMAL(7,2), ISNULL(AGY_SETTINGS.AGY_SETTINGS_VALUE, AGY_SETTINGS.AGY_SETTINGS_DEF)) 
				FROM AGY_SETTINGS WITH(NOLOCK) WHERE AGY_SETTINGS.AGY_SETTINGS_CODE = 'TS_MIN_TIME';

			END
			ELSE
			BEGIN

				SELECT @TS_MIN_TIME = CONVERT(DECIMAL(7,2), ISNULL(AGY_SETTINGS.AGY_SETTINGS_VALUE, AGY_SETTINGS.AGY_SETTINGS_DEF)) 
				FROM AGY_SETTINGS WITH(NOLOCK) WHERE AGY_SETTINGS.AGY_SETTINGS_CODE = 'TS_STOP_MIN_TIME';

			END

			SET @TS_MIN_TIME = ISNULL(@TS_MIN_TIME, 0.00);

			IF @TS_MIN_TIME > 0.00
			BEGIN
				IF @HOURS < @TS_MIN_TIME
				BEGIN
					SET @HOURS = @TS_MIN_TIME;
				END
			END

			IF @FOR_GENERAL_ENTRY = 1
			BEGIN

				SELECT @TS_ROUND_TO = CONVERT(DECIMAL(7,2), ISNULL(AGY_SETTINGS.AGY_SETTINGS_VALUE, AGY_SETTINGS.AGY_SETTINGS_DEF)) 
				FROM AGY_SETTINGS WITH(NOLOCK) WHERE AGY_SETTINGS.AGY_SETTINGS_CODE = 'TS_ROUND_TO';

			END
			ELSE
			BEGIN

				SELECT @TS_ROUND_TO = CONVERT(DECIMAL(7,2), ISNULL(AGY_SETTINGS.AGY_SETTINGS_VALUE, AGY_SETTINGS.AGY_SETTINGS_DEF)) 
				FROM AGY_SETTINGS WITH(NOLOCK) WHERE AGY_SETTINGS.AGY_SETTINGS_CODE = 'TS_STOP_ROUND_TO';

			END
			SET @TS_ROUND_TO = ISNULL(@TS_ROUND_TO, 0.00);

			IF @TS_ROUND_TO > 0.0
			BEGIN
		
				DECLARE
				@HOURS_MODULUS DECIMAL(7,2);

				SET @HOURS_MODULUS = 1
		
			END

	END

	RETURN @HOURS;
	
END
                      

