// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace AdvantageFramework.Core.Security.Database.Views
{
    [Keyless]
    public partial class ModuleStructure
    {
        [Column("ID")]
        public long Id { get; set; }
        [Column("ParentModuleID")]
        public int? ParentModuleId { get; set; }
        [StringLength(100)]
        public string ParentModule { get; set; }
        public int? ParentModuleSortOrder { get; set; }
        [Column("SubParentModuleID")]
        public int? SubParentModuleId { get; set; }
        [StringLength(100)]
        public string SubParentModule { get; set; }
        public int? SubParentModuleSortOrder { get; set; }
        [Column("SubSubParentModuleID")]
        public int? SubSubParentModuleId { get; set; }
        [StringLength(100)]
        public string SubSubParentModule { get; set; }
        public int? SubSubParentModuleSortOrder { get; set; }
        [Column("ModuleID")]
        public int ModuleId { get; set; }
        [Required]
        [StringLength(100)]
        public string ModuleCode { get; set; }
        [Required]
        [StringLength(100)]
        public string Module { get; set; }
        public int? ModuleSortOrder { get; set; }
        public bool? ModuleHasCustomPermission { get; set; }
    }
}
