SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, QUOTED_IDENTIFIER, CONCAT_NULL_YIELDS_NULL, XACT_ABORT ON
GO
SET NUMERIC_ROUNDABORT OFF
GO

--MAKE SURE ALL DISMISSED ALERTS ARE MOVED TO THE DIMISSED TABLE
IF EXISTS (SELECT * FROM   dbo.sysobjects WHERE  id = OBJECT_ID(N'[dbo].[ALERT_RCPT_DISMISSED]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
	--MOVE DIMISSED TO DISMISSED TABLE
	INSERT INTO ALERT_RCPT_DISMISSED
	SELECT *
	FROM   ALERT_RCPT
	WHERE  (NOT (ALERT_RCPT.PROCESSED IS NULL));
	--DELETE DISMISSED FROM MAIN TABLE
	DELETE 
	FROM   ALERT_RCPT
	WHERE  (NOT (ALERT_RCPT.PROCESSED IS NULL));
END




/* Client Portal Data Insertions  */
/* CP Desktop Object Categories */
IF NOT EXISTS (SELECT ID FROM [dbo].[CP_DESKTOP_OBJECT_CATEGORY] WHERE ID = 2)
	BEGIN
	SET IDENTITY_INSERT [dbo].[CP_DESKTOP_OBJECT_CATEGORY] ON
		INSERT INTO [dbo].[CP_DESKTOP_OBJECT_CATEGORY] (ID, CATEGORY) VALUES(2, 'Production');
	SET IDENTITY_INSERT [dbo].[CP_DESKTOP_OBJECT_CATEGORY] OFF
	END
ELSE
	BEGIN
	UPDATE [dbo].[CP_DESKTOP_OBJECT_CATEGORY] SET CATEGORY='Production' WHERE ID=2;
	END
GO

IF NOT EXISTS (SELECT ID FROM [dbo].[CP_DESKTOP_OBJECT_CATEGORY] WHERE ID = 3)
	BEGIN
	SET IDENTITY_INSERT [dbo].[CP_DESKTOP_OBJECT_CATEGORY] ON
		INSERT INTO [dbo].[CP_DESKTOP_OBJECT_CATEGORY] (ID, CATEGORY) VALUES(3, 'Media');
	SET IDENTITY_INSERT [dbo].[CP_DESKTOP_OBJECT_CATEGORY] OFF
	END
ELSE
	BEGIN
	UPDATE [dbo].[CP_DESKTOP_OBJECT_CATEGORY] SET CATEGORY='Media' WHERE ID=3;
	END
GO

IF NOT EXISTS (SELECT ID FROM [dbo].[CP_DESKTOP_OBJECT_CATEGORY] WHERE ID = 4)
	BEGIN
	SET IDENTITY_INSERT [dbo].[CP_DESKTOP_OBJECT_CATEGORY] ON
		INSERT INTO [dbo].[CP_DESKTOP_OBJECT_CATEGORY] (ID, CATEGORY) VALUES(4, 'Finance');
	SET IDENTITY_INSERT [dbo].[CP_DESKTOP_OBJECT_CATEGORY] OFF
	END
ELSE
	BEGIN
	UPDATE [dbo].[CP_DESKTOP_OBJECT_CATEGORY] SET CATEGORY='Finance' WHERE ID= 4;
	END
GO

IF NOT EXISTS (SELECT ID FROM [dbo].[CP_DESKTOP_OBJECT_CATEGORY] WHERE ID = 5)
	BEGIN
	SET IDENTITY_INSERT [dbo].[CP_DESKTOP_OBJECT_CATEGORY] ON
		INSERT INTO [dbo].[CP_DESKTOP_OBJECT_CATEGORY] (ID, CATEGORY) VALUES(5, 'Client');
	SET IDENTITY_INSERT [dbo].[CP_DESKTOP_OBJECT_CATEGORY] OFF
	END
ELSE
	BEGIN
	UPDATE [dbo].[CP_DESKTOP_OBJECT_CATEGORY] SET CATEGORY='Client' WHERE ID=5;
	END
GO

IF NOT EXISTS (SELECT ID FROM CP_DESKTOP_OBJECT_CATEGORY WHERE ID = 6)
	BEGIN
	SET IDENTITY_INSERT [dbo].[CP_DESKTOP_OBJECT_CATEGORY] ON
		INSERT INTO [dbo].[CP_DESKTOP_OBJECT_CATEGORY] (ID, CATEGORY) VALUES(6, 'General');
	SET IDENTITY_INSERT [dbo].[CP_DESKTOP_OBJECT_CATEGORY] OFF
	END
ELSE
	BEGIN
	UPDATE [dbo].[CP_DESKTOP_OBJECT_CATEGORY] SET CATEGORY='General' WHERE ID=6;
	END
GO

/* CP Application Categories */
IF NOT EXISTS (SELECT CATID FROM [dbo].[CP_APPLICATIONS_CATEGORY] WHERE CATID = 1)
	BEGIN
	SET IDENTITY_INSERT [dbo].[CP_APPLICATIONS_CATEGORY] ON
		INSERT INTO [dbo].[CP_APPLICATIONS_CATEGORY] (CATID, CATEGORY, ICONPATH, SORT_ORDER)
		VALUES(1, 'Desktop', '/icons/desktop.png', 0);
	SET IDENTITY_INSERT [dbo].[CP_APPLICATIONS_CATEGORY] OFF
	END
ELSE
	BEGIN
	UPDATE [dbo].[CP_APPLICATIONS_CATEGORY] SET CATEGORY='Desktop' WHERE CATID=1;
	END
GO

IF NOT EXISTS (SELECT CATID FROM [dbo].[CP_APPLICATIONS_CATEGORY] WHERE CATID = 2)
	BEGIN
	SET IDENTITY_INSERT [dbo].[CP_APPLICATIONS_CATEGORY] ON
		INSERT INTO [dbo].[CP_APPLICATIONS_CATEGORY] (CATID, CATEGORY, ICONPATH, SORT_ORDER)
		VALUES(2, 'Production', '/icons/gears.png', 2);
	SET IDENTITY_INSERT [dbo].[CP_APPLICATIONS_CATEGORY] OFF
	END
ELSE
	BEGIN
	UPDATE [dbo].[CP_APPLICATIONS_CATEGORY] SET CATEGORY='Production' WHERE CATID=2;
	END
GO

IF NOT EXISTS (SELECT CATID FROM [dbo].[CP_APPLICATIONS_CATEGORY] WHERE CATID = 3)
	BEGIN
	SET IDENTITY_INSERT [dbo].[CP_APPLICATIONS_CATEGORY] ON
		INSERT INTO [dbo].[CP_APPLICATIONS_CATEGORY] (CATID, CATEGORY, ICONPATH, SORT_ORDER)
		VALUES(3, 'Media', '/icons/tv.png', 3);
	SET IDENTITY_INSERT [dbo].[CP_APPLICATIONS_CATEGORY] OFF
	END
ELSE
	BEGIN
	UPDATE [dbo].[CP_APPLICATIONS_CATEGORY] SET CATEGORY='Media' WHERE CATID=3;
	END
GO

IF NOT EXISTS (SELECT CATID FROM [dbo].[CP_APPLICATIONS_CATEGORY] WHERE CATID = 4)
	BEGIN
	SET IDENTITY_INSERT [dbo].[CP_APPLICATIONS_CATEGORY] ON
		INSERT INTO [dbo].[CP_APPLICATIONS_CATEGORY] (CATID, CATEGORY, ICONPATH, SORT_ORDER)
		VALUES(4, 'Communication', '/icons/discussion.png', 1);
	SET IDENTITY_INSERT [dbo].[CP_APPLICATIONS_CATEGORY] OFF
	END
ELSE
	BEGIN
	UPDATE [dbo].[CP_APPLICATIONS_CATEGORY] SET CATEGORY='Communication' WHERE CATID=4;
	END
GO

/* CP Desktop Objects*/
IF NOT EXISTS (SELECT ID FROM [dbo].[CP_DESKTOP_OBJECTS] WHERE ID = 1)
	BEGIN
	SET IDENTITY_INSERT [dbo].[CP_DESKTOP_OBJECTS] ON
		INSERT INTO CP_DESKTOP_OBJECTS (ID, CATEGORY_ID, NAME, DESCRIPTION, SECURITY_LEVEL, ACTIVE, ASCX_FILENAME)
		VALUES(1, 2, 'Milestone Task List', 'A list of upcoming tasks that are marked as milestones.', 1, 1, 'MilestoneTaskList.ascx');
	SET IDENTITY_INSERT [dbo].[CP_DESKTOP_OBJECTS] OFF
	END
GO

IF NOT EXISTS (SELECT ID FROM [dbo].[CP_DESKTOP_OBJECTS] WHERE ID = 2)
	BEGIN
	SET IDENTITY_INSERT [dbo].[CP_DESKTOP_OBJECTS] ON
		INSERT INTO [dbo].[CP_DESKTOP_OBJECTS] (ID, CATEGORY_ID, NAME, DESCRIPTION, SECURITY_LEVEL, ACTIVE, ASCX_FILENAME)
		VALUES(2, 2, 'Project List', '.', 1, 1, 'ProjectList.ascx');
	SET IDENTITY_INSERT [dbo].[CP_DESKTOP_OBJECTS] OFF
	END
GO

IF NOT EXISTS (SELECT ID FROM [dbo].[CP_DESKTOP_OBJECTS] WHERE ID = 3)
	BEGIN
	SET IDENTITY_INSERT [dbo].[CP_DESKTOP_OBJECTS] ON
		INSERT INTO [dbo].[CP_DESKTOP_OBJECTS] (ID, CATEGORY_ID, NAME, DESCRIPTION, SECURITY_LEVEL, ACTIVE, ASCX_FILENAME)
		VALUES(3, 6, 'New Alerts', 'A list of your new alerts.', 1, 1, 'Alerts.ascx');
	SET IDENTITY_INSERT [dbo].[CP_DESKTOP_OBJECTS] OFF
	END
GO

IF NOT EXISTS (SELECT ID FROM [dbo].[CP_DESKTOP_OBJECTS] WHERE ID = 5)
	BEGIN
	SET IDENTITY_INSERT [dbo].[CP_DESKTOP_OBJECTS] ON
		INSERT INTO [dbo].[CP_DESKTOP_OBJECTS] (ID, CATEGORY_ID, NAME, DESCRIPTION, SECURITY_LEVEL, ACTIVE, ASCX_FILENAME)
		VALUES(5, 6, 'Quick Launch', 'A customizable module that allows you to create icons to your applications.', 1, 1, 'QuickLaunch.ascx');
	SET IDENTITY_INSERT [dbo].[CP_DESKTOP_OBJECTS] OFF
	END
GO
IF NOT EXISTS (SELECT ID FROM [dbo].[CP_DESKTOP_OBJECTS] WHERE ID = 6)
	BEGIN
	SET IDENTITY_INSERT [dbo].[CP_DESKTOP_OBJECTS] ON
		INSERT INTO [dbo].[CP_DESKTOP_OBJECTS] (ID, CATEGORY_ID, NAME, DESCRIPTION, SECURITY_LEVEL, ACTIVE, ASCX_FILENAME)
		VALUES(6, 6, 'Alert Summary', 'A summary of Alerts.', 1, 1, 'AlertSummary.ascx');
	SET IDENTITY_INSERT [dbo].[CP_DESKTOP_OBJECTS] OFF
	END
GO

/* CP APPLICATIONS */

IF NOT EXISTS (SELECT APPID FROM [dbo].[CP_APPLICATIONS] WHERE APPID = 101)
	BEGIN
	SET IDENTITY_INSERT [dbo].[CP_APPLICATIONS] ON
		INSERT INTO [dbo].[CP_APPLICATIONS] (APPID, CATID, APPNAME, URL, IMAGEPATH, ACTIVE, SORTORDER)
		VALUES(101, 4, 'Alerts', '/AlertInbox.aspx', 'messages.png', 1, '0');
	SET IDENTITY_INSERT [dbo].[CP_APPLICATIONS] OFF
	END
GO
IF NOT EXISTS (SELECT APPID FROM [dbo].[CP_APPLICATIONS] WHERE APPID = 104)
	BEGIN
	SET IDENTITY_INSERT [dbo].[CP_APPLICATIONS] ON
		INSERT INTO [dbo].[CP_APPLICATIONS] (APPID, CATID, APPNAME, URL, IMAGEPATH, ACTIVE, SORTORDER)
		VALUES(104, 2, 'Production Milestone Calendar', '/ProductionCalendarMonthView.aspx?ms=1', 'calendar_preferences.png', 1, '1');
	SET IDENTITY_INSERT [dbo].[CP_APPLICATIONS] OFF
	END
GO
IF NOT EXISTS (SELECT APPID FROM [dbo].[CP_APPLICATIONS] WHERE APPID = 105)
	BEGIN
	SET IDENTITY_INSERT [dbo].[CP_APPLICATIONS] ON
		INSERT INTO [dbo].[CP_APPLICATIONS] (APPID, CATID, APPNAME, URL, IMAGEPATH, ACTIVE, SORTORDER)
		VALUES(105, 2, 'Production Calendar', '/ProductionCalendarMonthView.aspx?ms=0', 'calendar.png', 1, '2');
	SET IDENTITY_INSERT [dbo].[CP_APPLICATIONS] OFF
	END
GO
IF NOT EXISTS (SELECT APPID FROM [dbo].[CP_APPLICATIONS] WHERE APPID = 107)
	BEGIN
	SET IDENTITY_INSERT [dbo].[CP_APPLICATIONS] ON
		INSERT INTO [dbo].[CP_APPLICATIONS] (APPID, CATID, APPNAME, URL, IMAGEPATH, ACTIVE, SORTORDER)
		VALUES(107, 3, 'Media Calendar', '/MediaCalendarMonthView.aspx', 'date-time.png', 1, '4');
	SET IDENTITY_INSERT [dbo].[CP_APPLICATIONS] OFF
	END
GO

UPDATE JOB_TRAFFIC_SETUP_ITEMS SET COLUMN_NAME = 'colTASK_CODE,colTASK_CODE_LOOKUP' WHERE COLUMN_NAME = 'colTASK_CODE'
UPDATE JOB_TRAFFIC_SETUP_ITEMS SET ACTIVE = 3 WHERE COLUMN_NAME = 'colDetails'
UPDATE JOB_TRAFFIC_SETUP_ITEMS SET ACTIVE = 3 WHERE COLUMN_NAME = 'colMoveUp,colMoveDown'
UPDATE JOB_TRAFFIC_SETUP_ITEMS SET ACTIVE = 3 WHERE COLUMN_NAME = 'colTASK_STATUS'
UPDATE JOB_TRAFFIC_SETUP_ITEMS SET ACTIVE = 3 WHERE COLUMN_NAME = 'colSEQ_NBR'
UPDATE JOB_TRAFFIC_SETUP_ITEMS SET ACTIVE = 3 WHERE COLUMN_NAME = 'colLock'
UPDATE JOB_TRAFFIC_SETUP_ITEMS SET ACTIVE = 3 WHERE COLUMN_NAME = 'colJOB_DUE_DATE'
UPDATE JOB_TRAFFIC_SETUP_ITEMS SET ACTIVE = 3 WHERE COLUMN_NAME = 'colTEMP_COMP_DATE'
UPDATE JOB_TRAFFIC_SETUP_ITEMS SET ACTIVE = 3 WHERE COLUMN_NAME = 'colDISPERSED_JOB_HRS'
UPDATE JOB_TRAFFIC_SETUP_ITEMS SET ACTIVE = 3 WHERE COLUMN_NAME = 'colEMP_CODE'
UPDATE JOB_TRAFFIC_SETUP_ITEMS SET ACTIVE = 3 WHERE COLUMN_NAME = 'colEMP_CODE_IMGBTN'
UPDATE JOB_TRAFFIC_SETUP_ITEMS SET ACTIVE = 3 WHERE COLUMN_NAME = 'colCLI_CONTACT'
UPDATE JOB_TRAFFIC_SETUP_ITEMS SET ACTIVE = 3 WHERE COLUMN_NAME = 'colCLI_CONTACT_IMGBTN'
UPDATE JOB_TRAFFIC_SETUP_ITEMS SET ACTIVE = 3 WHERE COLUMN_NAME = 'colComments'
UPDATE JOB_TRAFFIC_SETUP_ITEMS SET ACTIVE = 3 WHERE COLUMN_NAME = 'colSave'
UPDATE JOB_TRAFFIC_SETUP_ITEMS SET ACTIVE = 1, COLUMN_LONG_DESC = 'Predecessor' WHERE COLUMN_NAME = 'colPREDECESSORS_TEXT'

DELETE FROM JOB_TRAFFIC_SETUP_ITEMS WITH(ROWLOCK) WHERE COLUMN_NAME = 'colSave';

UPDATE ESTIMATE_SETUP_DTL SET DISPLAY_TYPE = NULL WHERE COLUMN_ID = 4 AND HDR_CODE = 'DFLT'
UPDATE ESTIMATE_SETUP_DTL SET DISPLAY_TYPE = NULL WHERE COLUMN_ID = 9 AND HDR_CODE = 'DFLT'
UPDATE ESTIMATE_SETUP_DTL SET DISPLAY_TYPE = NULL WHERE COLUMN_ID = 10 AND HDR_CODE = 'DFLT'
UPDATE ESTIMATE_SETUP_DTL SET DISPLAY_TYPE = NULL WHERE COLUMN_ID = 11 AND HDR_CODE = 'DFLT'
UPDATE ESTIMATE_SETUP_DTL SET DISPLAY_TYPE = NULL WHERE COLUMN_ID = 12 AND HDR_CODE = 'DFLT'

UPDATE JOB_TMPLT_ITEMS WITH(ROWLOCK) SET CONTROL_TYPE = 14 WHERE ITEM_CODE = 'JOB_COMPONENT.AD_NBR' AND CONTROL_TYPE <> 14;

/* Alert Categories */
IF NOT EXISTS (SELECT ALERT_CAT_ID FROM ALERT_CATEGORY WHERE ALERT_CAT_ID = 42)
BEGIN
	INSERT INTO ALERT_CATEGORY (ALERT_CAT_ID, ALERT_TYPE_ID, ALERT_DESC, PROMPT, GROUP_LVL_SECURITY, PDF_ATTACHMENT)
	VALUES(42, 1, 'Task Modified', NULL, 0, NULL);
END		
GO

IF NOT EXISTS (SELECT * FROM AGY_SETTINGS WHERE AGY_SETTINGS_CODE = 'RSC_RPT_NO_ETI_CLR')
	BEGIN
		INSERT INTO AGY_SETTINGS WITH(ROWLOCK)
		(
			AGY_SETTINGS_CODE,
			AGY_SETTINGS_DESC,
			AGY_SETTINGS_VALUE,
			AGY_SETTINGS_DEF
		) 
		VALUES
		(
			'RSC_RPT_NO_ETI_CLR',
			'Resource Report Color for events without event type',
			'#D8D8D8',
			'#D8D8D8'
		);
	END
IF NOT EXISTS (SELECT * FROM AGY_SETTINGS WHERE AGY_SETTINGS_CODE = 'RSC_RPT_STC_CLR')
	BEGIN
		INSERT INTO AGY_SETTINGS WITH(ROWLOCK)
		(
			AGY_SETTINGS_CODE,
			AGY_SETTINGS_DESC,
			AGY_SETTINGS_VALUE,
			AGY_SETTINGS_DEF
		) 
		VALUES
		(
			'RSC_RPT_STC_CLR',
			'Resource Report Color for events with STATIC event type',
			'#FF444D',
			'#FF444D'
		);
	END
IF NOT EXISTS (SELECT * FROM AGY_SETTINGS WHERE AGY_SETTINGS_CODE = 'RSC_RPT_FLX_CLR')
	BEGIN
		INSERT INTO AGY_SETTINGS WITH(ROWLOCK)
		(
			AGY_SETTINGS_CODE,
			AGY_SETTINGS_DESC,
			AGY_SETTINGS_VALUE,
			AGY_SETTINGS_DEF
		) 
		VALUES
		(
			'RSC_RPT_FLX_CLR',
			'Resource Report Color for events with FLEX event type',
			'#7CCA62',
			'#7CCA62'
		);
	END
IF NOT EXISTS (SELECT * FROM AGY_SETTINGS WHERE AGY_SETTINGS_CODE = 'RSC_RPT_PRE_CLR')
	BEGIN
		INSERT INTO AGY_SETTINGS WITH(ROWLOCK)
		(
			AGY_SETTINGS_CODE,
			AGY_SETTINGS_DESC,
			AGY_SETTINGS_VALUE,
			AGY_SETTINGS_DEF
		) 
		VALUES
		(
			'RSC_RPT_PRE_CLR',
			'Resource Report Color for events witH Pre-emptable event type',
			'#5ABAFF',
			'#5ABAFF'
		);
	END
IF NOT EXISTS (SELECT * FROM AGY_SETTINGS WHERE AGY_SETTINGS_CODE = 'RSC_RPT_HLD_CLR')
	BEGIN
		INSERT INTO AGY_SETTINGS WITH(ROWLOCK)
		(
			AGY_SETTINGS_CODE,
			AGY_SETTINGS_DESC,
			AGY_SETTINGS_VALUE,
			AGY_SETTINGS_DEF
		) 
		VALUES
		(
			'RSC_RPT_HLD_CLR',
			'Resource Report Color for events witH HOLD event type',
			'#F1D925F',
			'#F1D925F'
		);
	END

UPDATE AGY_SETTINGS WITH(ROWLOCK) SET AGY_SETTINGS_VALUE = '#CCCCCC',AGY_SETTINGS_DEF='#CCCCCC' WHERE AGY_SETTINGS_CODE = 'RSC_RPT_NO_ETI_CLR';
UPDATE AGY_SETTINGS WITH(ROWLOCK) SET AGY_SETTINGS_VALUE = '#FF444D',AGY_SETTINGS_DEF='#FF444D' WHERE AGY_SETTINGS_CODE = 'RSC_RPT_STC_CLR';
UPDATE AGY_SETTINGS WITH(ROWLOCK) SET AGY_SETTINGS_VALUE = '#A9CF58',AGY_SETTINGS_DEF='#A9CF58' WHERE AGY_SETTINGS_CODE = 'RSC_RPT_FLX_CLR';
UPDATE AGY_SETTINGS WITH(ROWLOCK) SET AGY_SETTINGS_VALUE = '#43A3FA',AGY_SETTINGS_DEF='#43A3FA' WHERE AGY_SETTINGS_CODE = 'RSC_RPT_PRE_CLR';
UPDATE AGY_SETTINGS WITH(ROWLOCK) SET AGY_SETTINGS_VALUE = '#F8EA85',AGY_SETTINGS_DEF='#F8EA85' WHERE AGY_SETTINGS_CODE = 'RSC_RPT_HLD_CLR';


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING OFF
GO
	
--IF NOT EXISTS(SELECT * FROM dbo.DB_UPDATE WHERE FUNCTION_NAME = 'RESTRUCTURE GRID ORDER') BEGIN

--	DROP TABLE [dbo].[GRID_COLUMN_SETTING]
--	DROP TABLE [dbo].[GRID_COLUMN]
--	DROP TABLE [dbo].[GRID]

--	CREATE TABLE [dbo].[GRID](
--		[GRID_ID] [int] IDENTITY(1,1) NOT NULL,
--		[NAME] [varchar](100) NOT NULL,
--	 CONSTRAINT [PK_GRID] PRIMARY KEY CLUSTERED 
--	(
--		[GRID_ID] ASC
--	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
--	) ON [PRIMARY]

--	CREATE TABLE [dbo].[GRID_COLUMN](
--		[GRID_COLUMN_ID] [int] IDENTITY(1,1) NOT NULL,
--		[GRID_ID] [int] NOT NULL,
--		[NAME] [varchar](100) NOT NULL,
--		[IS_EDITABLE] [bit] NOT NULL,
--	 CONSTRAINT [PK_GRID_COLUMN] PRIMARY KEY CLUSTERED 
--	(
--		[GRID_COLUMN_ID] ASC
--	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
--	) ON [PRIMARY]

--	ALTER TABLE [dbo].[GRID_COLUMN]  WITH CHECK ADD  CONSTRAINT [FK_GRID_COLUMN_GRID] FOREIGN KEY([GRID_ID])
--	REFERENCES [dbo].[GRID] ([GRID_ID])

--	ALTER TABLE [dbo].[GRID_COLUMN] CHECK CONSTRAINT [FK_GRID_COLUMN_GRID]

--	CREATE TABLE [dbo].[GRID_COLUMN_SETTING](
--		[GRIDCOLUMNSETTING_ID] [int] IDENTITY(1,1) NOT NULL,
--		[GRID_ID] [int] NOT NULL,
--		[GRID_COLUMN_ID] [int] NOT NULL,
--		[USER_CODE] [varchar](100) NOT NULL,
--		[IS_VISIBLE] [bit] NOT NULL,
--	 CONSTRAINT [PK_GRID_COLUMN_SETTING] PRIMARY KEY CLUSTERED 
--	(
--		[GRIDCOLUMNSETTING_ID] ASC
--	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
--	) ON [PRIMARY]

--	ALTER TABLE [dbo].[GRID_COLUMN_SETTING]  WITH CHECK ADD  CONSTRAINT [FK_GRID_COLUMN_SETTING_GRID] FOREIGN KEY([GRID_ID])
--	REFERENCES [dbo].[GRID] ([GRID_ID])

--	ALTER TABLE [dbo].[GRID_COLUMN_SETTING] CHECK CONSTRAINT [FK_GRID_COLUMN_SETTING_GRID]

--	ALTER TABLE [dbo].[GRID_COLUMN_SETTING]  WITH CHECK ADD  CONSTRAINT [FK_GRID_COLUMN_SETTING_GRID_COLUMN] FOREIGN KEY([GRID_COLUMN_ID])
--	REFERENCES [dbo].[GRID_COLUMN] ([GRID_COLUMN_ID])

--	ALTER TABLE [dbo].[GRID_COLUMN_SETTING] CHECK CONSTRAINT [FK_GRID_COLUMN_SETTING_GRID_COLUMN]

--	INSERT INTO 
--		dbo.DB_UPDATE(VERSION_ID, PATCH, [DESCRIPTION], FUNCTION_NAME )
--	VALUES
--		('v6.50.00', '##SCRIPT_NAME##.sql', 'WV Script Version: ##SCRIPT_VERSION##', 'RESTRUCTURE GRID ORDER')

--END
--GO

--IF NOT EXISTS(SELECT * FROM dbo.DB_UPDATE WHERE FUNCTION_NAME = 'CLEAR_USER_COLUMNS_20111005') 
--BEGIN
--	DELETE FROM [dbo].[GRID_COLUMN_SETTING];
--	INSERT INTO 
--		dbo.DB_UPDATE(VERSION_ID, PATCH, [DESCRIPTION], FUNCTION_NAME )
--	VALUES
--		('v6.50.00', '##SCRIPT_NAME##.sql', 'WV Script Version: ##SCRIPT_VERSION##', 'CLEAR_USER_COLUMNS_20111005')
--END
--GO


--IF NOT EXISTS (SELECT GRID_ID FROM dbo.GRID WHERE GRID_ID = 1) BEGIN

--	SET IDENTITY_INSERT dbo.GRID ON
	
--	INSERT INTO dbo.GRID([GRID_ID], [NAME])
--	VALUES(1, 'QVAAllRadGrid')
	
--	SET IDENTITY_INSERT dbo.GRID OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID 
--	SET [NAME]='QVAAllRadGrid'
--	WHERE GRID_ID=1
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_ID FROM dbo.GRID WHERE GRID_ID = 2) BEGIN

--	SET IDENTITY_INSERT dbo.GRID ON
	
--	INSERT INTO dbo.GRID([GRID_ID], [NAME])
--	VALUES(2, 'RadGridAlertInbox')
	
--	SET IDENTITY_INSERT dbo.GRID OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID 
--	SET [NAME]='RadGridAlertInbox'
--	WHERE GRID_ID=2
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_ID FROM dbo.GRID WHERE GRID_ID = 3) BEGIN

--	SET IDENTITY_INSERT dbo.GRID ON
	
--	INSERT INTO dbo.GRID([GRID_ID], [NAME])
--	VALUES(3, 'RadGridEmployeeTimeForecastOfficeDetailJobComponents')
	
--	SET IDENTITY_INSERT dbo.GRID OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID 
--	SET [NAME]='RadGridEmployeeTimeForecastOfficeDetailJobComponents'
--	WHERE GRID_ID=3
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_ID FROM dbo.GRID WHERE GRID_ID = 4) BEGIN

--	SET IDENTITY_INSERT dbo.GRID ON
	
--	INSERT INTO dbo.GRID([GRID_ID], [NAME])
--	VALUES(4, 'RadGridMyAlerts')
	
--	SET IDENTITY_INSERT dbo.GRID OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID 
--	SET [NAME]='RadGridMyAlerts'
--	WHERE GRID_ID=4
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_ID FROM dbo.GRID WHERE GRID_ID = 5) BEGIN

--	SET IDENTITY_INSERT dbo.GRID ON
	
--	INSERT INTO dbo.GRID([GRID_ID], [NAME])
--	VALUES(5, 'RadGridProjectViewpointMain')
	
--	SET IDENTITY_INSERT dbo.GRID OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID 
--	SET [NAME]='RadGridProjectViewpointMain'
--	WHERE GRID_ID=5
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_ID FROM dbo.GRID WHERE GRID_ID = 6) BEGIN

--	SET IDENTITY_INSERT dbo.GRID ON
	
--	INSERT INTO dbo.GRID([GRID_ID], [NAME])
--	VALUES(6, 'RadGridQVA')
	
--	SET IDENTITY_INSERT dbo.GRID OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID 
--	SET [NAME]='RadGridQVA'
--	WHERE GRID_ID=6
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_ID FROM dbo.GRID WHERE GRID_ID = 7) BEGIN

--	SET IDENTITY_INSERT dbo.GRID ON
	
--	INSERT INTO dbo.GRID([GRID_ID], [NAME])
--	VALUES(7, 'RadGridTimesheet')
	
--	SET IDENTITY_INSERT dbo.GRID OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID 
--	SET [NAME]='RadGridTimesheet'
--	WHERE GRID_ID=7
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_ID FROM dbo.GRID WHERE GRID_ID = 8) BEGIN

--	SET IDENTITY_INSERT dbo.GRID ON
	
--	INSERT INTO dbo.GRID([GRID_ID], [NAME])
--	VALUES(8, 'TaskRadGrid')
	
--	SET IDENTITY_INSERT dbo.GRID OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID 
--	SET [NAME]='TaskRadGrid'
--	WHERE GRID_ID=8
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_ID FROM dbo.GRID WHERE GRID_ID = 9) BEGIN

--	SET IDENTITY_INSERT dbo.GRID ON
	
--	INSERT INTO dbo.GRID([GRID_ID], [NAME])
--	VALUES(9, 'TasksRG')
	
--	SET IDENTITY_INSERT dbo.GRID OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID 
--	SET [NAME]='TasksRG'
--	WHERE GRID_ID=9
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 1) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(1, 1, 'ActualHours', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=1, 
--		[NAME]='ActualHours',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=1
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 2) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(2, 1, 'colDetails', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=1, 
--		[NAME]='colDetails',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=2
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 3) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(3, 1, 'column', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=1, 
--		[NAME]='column',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=3
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 4) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(4, 1, 'column2', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=1, 
--		[NAME]='column2',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=4
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 5) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(5, 1, 'column3', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=1, 
--		[NAME]='column3',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=5
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 6) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(6, 1, 'column4', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=1, 
--		[NAME]='column4',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=6
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 7) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(7, 1, 'column5', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=1, 
--		[NAME]='column5',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=7
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 8) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(8, 1, 'column6', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=1, 
--		[NAME]='column6',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=8
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 9) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(9, 1, 'DueDate', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=1, 
--		[NAME]='DueDate',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=9
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 10) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(10, 1, 'Flag', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=1, 
--		[NAME]='Flag',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=10
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 11) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(11, 1, 'PercentOfQuoted', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=1, 
--		[NAME]='PercentOfQuoted',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=11
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 12) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(12, 1, 'PercentOfQuotedAmt', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=1, 
--		[NAME]='PercentOfQuotedAmt',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=12
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 13) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(13, 1, 'QuoteHours', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=1, 
--		[NAME]='QuoteHours',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=13
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 14) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(14, 2, 'ALERT_STATE_NAME', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=2, 
--		[NAME]='ALERT_STATE_NAME',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=14
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 15) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(15, 2, 'AlertTYPE', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=2, 
--		[NAME]='AlertTYPE',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=15
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 16) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(16, 2, 'AttachmentColumn', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=2, 
--		[NAME]='AttachmentColumn',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=16
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 17) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(17, 2, 'CATEGORY', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=2, 
--		[NAME]='CATEGORY',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=17
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 18) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(18, 2, 'CL_NAME', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=2, 
--		[NAME]='CL_NAME',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=18
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 19) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(19, 2, 'ColALERT_ID', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=2, 
--		[NAME]='ColALERT_ID',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=19
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 20) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(20, 2, 'ColID', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=2, 
--		[NAME]='ColID',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=20
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 21) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(21, 2, 'CurrentNotifyEmpFMLColumn', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=2, 
--		[NAME]='CurrentNotifyEmpFMLColumn',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=21
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 22) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(22, 2, 'DUE_DATE', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=2, 
--		[NAME]='DUE_DATE',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=22
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 23) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(23, 2, 'GridBoundColumnBUILD', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=2, 
--		[NAME]='GridBoundColumnBUILD',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=23
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 24) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(24, 2, 'GridBoundColumnVER', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=2, 
--		[NAME]='GridBoundColumnVER',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=24
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 25) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(25, 2, 'Priority', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=2, 
--		[NAME]='Priority',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=25
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 26) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(26, 2, 'Sent', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=2, 
--		[NAME]='Sent',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=26
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 27) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(27, 2, 'SUBJECT', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=2, 
--		[NAME]='SUBJECT',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=27
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 28) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(28, 2, 'SubjectColumn', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=2, 
--		[NAME]='SubjectColumn',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=28
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 29) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(29, 2, 'TemplateColumn1', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=2, 
--		[NAME]='TemplateColumn1',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=29
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 30) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(30, 2, 'TemplateColumn2', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=2, 
--		[NAME]='TemplateColumn2',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=30
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 31) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(31, 2, 'USER_NAME', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=2, 
--		[NAME]='USER_NAME',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=31
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 32) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(32, 3, 'GridBoundColumnAccountExecutive', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=3, 
--		[NAME]='GridBoundColumnAccountExecutive',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=32
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 33) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(33, 3, 'GridBoundColumnActualAmount', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=3, 
--		[NAME]='GridBoundColumnActualAmount',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=33
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 34) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(34, 3, 'GridBoundColumnActualHours', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=3, 
--		[NAME]='GridBoundColumnActualHours',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=34
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 35) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(35, 3, 'GridBoundColumnClient', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=3, 
--		[NAME]='GridBoundColumnClient',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=35
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 36) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(36, 3, 'GridBoundColumnForecastedAmount', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=3, 
--		[NAME]='GridBoundColumnForecastedAmount',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=36
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 37) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(37, 3, 'GridBoundColumnForecastedHours', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=3, 
--		[NAME]='GridBoundColumnForecastedHours',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=37
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 38) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(38, 3, 'GridBoundColumnJobAndJobComponent', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=3, 
--		[NAME]='GridBoundColumnJobAndJobComponent',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=38
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 39) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(39, 3, 'GridBoundColumnOffice', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=3, 
--		[NAME]='GridBoundColumnOffice',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=39
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 40) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(40, 3, 'GridBoundColumnSalesClass', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=3, 
--		[NAME]='GridBoundColumnSalesClass',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=40
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 41) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(41, 3, 'GridBoundColumnVarianceAmount', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=3, 
--		[NAME]='GridBoundColumnVarianceAmount',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=41
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 42) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(42, 3, 'GridBoundColumnVarianceHours', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=3, 
--		[NAME]='GridBoundColumnVarianceHours',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=42
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 43) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(43, 4, 'AlertTYPE', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=4, 
--		[NAME]='AlertTYPE',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=43
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 44) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(44, 4, 'colClient', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=4, 
--		[NAME]='colClient',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=44
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 45) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(45, 4, 'colLastUpdatedBy', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=4, 
--		[NAME]='colLastUpdatedBy',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=45
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 46) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(46, 4, 'colProject', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=4, 
--		[NAME]='colProject',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=46
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 47) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(47, 4, 'column', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=4, 
--		[NAME]='column',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=47
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 48) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(48, 4, 'DismissColumn', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=4, 
--		[NAME]='DismissColumn',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=48
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 49) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(49, 4, 'PriorityColumn', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=4, 
--		[NAME]='PriorityColumn',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=49
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 50) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(50, 4, 'READ_ALERT', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=4, 
--		[NAME]='READ_ALERT',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=50
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 51) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(51, 4, 'SubjectColumn', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=4, 
--		[NAME]='SubjectColumn',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=51
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 52) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(52, 4, 'ViewColumn', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=4, 
--		[NAME]='ViewColumn',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=52
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 53) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(53, 5, 'AcctExec', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=5, 
--		[NAME]='AcctExec',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=53
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 54) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(54, 5, 'alerts', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=5, 
--		[NAME]='alerts',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=54
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 55) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(55, 5, 'cb', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=5, 
--		[NAME]='cb',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=55
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 56) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(56, 5, 'CDP', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=5, 
--		[NAME]='CDP',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=56
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 57) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(57, 5, 'CL_CODE', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=5, 
--		[NAME]='CL_CODE',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=57
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 58) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(58, 5, 'COMPLETED_DATE', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=5, 
--		[NAME]='COMPLETED_DATE',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=58
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 59) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(59, 5, 'DIV_CODE', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=5, 
--		[NAME]='DIV_CODE',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=59
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 60) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(60, 5, 'documents', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=5, 
--		[NAME]='documents',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=60
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 61) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(61, 5, 'DueActualDate', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=5, 
--		[NAME]='DueActualDate',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=61
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 62) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(62, 5, 'est', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=5, 
--		[NAME]='est',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=62
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 63) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(63, 5, 'GridBoundColumnStatus', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=5, 
--		[NAME]='GridBoundColumnStatus',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=63
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 64) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(64, 5, 'GridTemplateColumnPrint', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=5, 
--		[NAME]='GridTemplateColumnPrint',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=64
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 65) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(65, 5, 'GridTemplateColumnViewDetail', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=5, 
--		[NAME]='GridTemplateColumnViewDetail',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=65
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 66) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(66, 5, 'JOB_COMPONENT_NBR', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=5, 
--		[NAME]='JOB_COMPONENT_NBR',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=66
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 67) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(67, 5, 'JOB_NUMBER', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=5, 
--		[NAME]='JOB_NUMBER',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=67
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 68) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(68, 5, 'JOB_PROCESS_CONTRL', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=5, 
--		[NAME]='JOB_PROCESS_CONTRL',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=68
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 69) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(69, 5, 'JobAndComp', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=5, 
--		[NAME]='JobAndComp',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=69
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 70) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(70, 5, 'openClosed', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=5, 
--		[NAME]='openClosed',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=70
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 71) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(71, 5, 'PRD_CODE', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=5, 
--		[NAME]='PRD_CODE',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=71
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 72) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(72, 5, 'PROCESS_DATE', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=5, 
--		[NAME]='PROCESS_DATE',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=72
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 73) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(73, 5, 'qva', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=5, 
--		[NAME]='qva',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=73
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 74) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(74, 5, 'sched', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=5, 
--		[NAME]='sched',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=74
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 75) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(75, 5, 'specs', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=5, 
--		[NAME]='specs',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=75
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 76) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(76, 5, 'summary', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=5, 
--		[NAME]='summary',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=76
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 77) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(77, 5, 'versions', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=5, 
--		[NAME]='versions',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=77
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 78) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(78, 6, 'ActualHours', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=6, 
--		[NAME]='ActualHours',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=78
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 79) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(79, 6, 'colDetails', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=6, 
--		[NAME]='colDetails',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=79
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 80) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(80, 6, 'column', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=6, 
--		[NAME]='column',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=80
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 81) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(81, 6, 'column2', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=6, 
--		[NAME]='column2',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=81
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 82) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(82, 6, 'column3', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=6, 
--		[NAME]='column3',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=82
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 83) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(83, 6, 'column4', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=6, 
--		[NAME]='column4',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=83
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 84) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(84, 6, 'DueDate', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=6, 
--		[NAME]='DueDate',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=84
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 85) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(85, 6, 'Flag', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=6, 
--		[NAME]='Flag',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=85
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 86) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(86, 6, 'PercentOfQuoted', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=6, 
--		[NAME]='PercentOfQuoted',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=86
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 87) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(87, 6, 'PercentOfQuotedAmt', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=6, 
--		[NAME]='PercentOfQuotedAmt',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=87
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 88) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(88, 6, 'QuoteHours', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=6, 
--		[NAME]='QuoteHours',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=88
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 89) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(89, 7, 'colCommentsFriday', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=7, 
--		[NAME]='colCommentsFriday',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=89
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 90) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(90, 7, 'colCommentsMonday', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=7, 
--		[NAME]='colCommentsMonday',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=90
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 91) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(91, 7, 'colCommentsSaturday', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=7, 
--		[NAME]='colCommentsSaturday',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=91
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 92) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(92, 7, 'colCommentsSunday', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=7, 
--		[NAME]='colCommentsSunday',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=92
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 93) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(93, 7, 'colCommentsThursday', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=7, 
--		[NAME]='colCommentsThursday',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=93
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 94) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(94, 7, 'colCommentsTuesday', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=7, 
--		[NAME]='colCommentsTuesday',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=94
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 95) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(95, 7, 'colCommentsView', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=7, 
--		[NAME]='colCommentsView',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=95
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 96) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(96, 7, 'colCommentsWednesday', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=7, 
--		[NAME]='colCommentsWednesday',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=96
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 97) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(97, 7, 'colDelete', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=7, 
--		[NAME]='colDelete',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=97
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 98) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(98, 7, 'colDepartment', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=7, 
--		[NAME]='colDepartment',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=98
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 99) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(99, 7, 'colDetails', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=7, 
--		[NAME]='colDetails',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=99
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 100) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(100, 7, 'colFriday', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=7, 
--		[NAME]='colFriday',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=100
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 101) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(101, 7, 'colFunctionCategory', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=7, 
--		[NAME]='colFunctionCategory',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=101
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 102) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(102, 7, 'colMonday', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=7, 
--		[NAME]='colMonday',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=102
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 103) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(103, 7, 'colProductCategory', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=7, 
--		[NAME]='colProductCategory',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=103
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 104) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(104, 7, 'colSaturday', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=7, 
--		[NAME]='colSaturday',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=104
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 105) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(105, 7, 'colSave', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=7, 
--		[NAME]='colSave',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=105
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 106) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(106, 7, 'colSunday', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=7, 
--		[NAME]='colSunday',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=106
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 107) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(107, 7, 'colThursday', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=7, 
--		[NAME]='colThursday',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=107
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 108) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(108, 7, 'colTotalHours', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=7, 
--		[NAME]='colTotalHours',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=108
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 109) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(109, 7, 'colTuesday', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=7, 
--		[NAME]='colTuesday',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=109
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 110) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(110, 7, 'colWednesday', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=7, 
--		[NAME]='colWednesday',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=110
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 111) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(111, 7, 'GridBoundColumnClientDesc', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=7, 
--		[NAME]='GridBoundColumnClientDesc',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=111
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 112) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(112, 7, 'GridBoundColumnDivisionDesc', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=7, 
--		[NAME]='GridBoundColumnDivisionDesc',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=112
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 113) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(113, 7, 'GridBoundColumnProductDesc', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=7, 
--		[NAME]='GridBoundColumnProductDesc',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=113
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 114) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(114, 7, 'GridTemplateColumnAddToTemplate', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=7, 
--		[NAME]='GridTemplateColumnAddToTemplate',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=114
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 115) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(115, 7, 'GridTemplateColumnCDP', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=7, 
--		[NAME]='GridTemplateColumnCDP',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=115
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 116) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(116, 7, 'GridTemplateColumnJobAndComponentNumber', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=7, 
--		[NAME]='GridTemplateColumnJobAndComponentNumber',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=116
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 117) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(117, 7, 'GridTemplateColumnJobComponentDescription', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=7, 
--		[NAME]='GridTemplateColumnJobComponentDescription',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=117
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 118) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(118, 7, 'GridTemplateColumnJobDescription', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=7, 
--		[NAME]='GridTemplateColumnJobDescription',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=118
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 119) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(119, 8, 'cdp', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=8, 
--		[NAME]='cdp',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=119
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 120) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(120, 8, 'column', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=8, 
--		[NAME]='column',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=120
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 121) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(121, 8, 'column10', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=8, 
--		[NAME]='column10',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=121
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 122) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(122, 8, 'column11', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=8, 
--		[NAME]='column11',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=122
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 123) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(123, 8, 'column12', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=8, 
--		[NAME]='column12',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=123
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 124) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(124, 8, 'column13', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=8, 
--		[NAME]='column13',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=124
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 125) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(125, 8, 'column14', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=8, 
--		[NAME]='column14',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=125
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 126) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(126, 8, 'column3', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=8, 
--		[NAME]='column3',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=126
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 127) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(127, 8, 'column31', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=8, 
--		[NAME]='column31',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=127
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 128) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(128, 8, 'column7', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=8, 
--		[NAME]='column7',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=128
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 129) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(129, 8, 'column77', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=8, 
--		[NAME]='column77',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=129
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 130) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(130, 8, 'column78', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=8, 
--		[NAME]='column78',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=130
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 131) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(131, 8, 'column8', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=8, 
--		[NAME]='column8',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=131
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 132) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(132, 8, 'column9', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=8, 
--		[NAME]='column9',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=132
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 133) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(133, 8, 'taskcolumn', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=8, 
--		[NAME]='taskcolumn',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=133
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 134) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(134, 8, 'TemplateColumn', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=8, 
--		[NAME]='TemplateColumn',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=134
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 135) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(135, 8, 'TemplateColumn1', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=8, 
--		[NAME]='TemplateColumn1',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=135
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 136) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(136, 8, 'TemplateColumn2', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=8, 
--		[NAME]='TemplateColumn2',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=136
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 137) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(137, 8, 'TemplateColumn3', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=8, 
--		[NAME]='TemplateColumn3',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=137
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 138) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(138, 8, 'TemplateColumn4', 0)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=8, 
--		[NAME]='TemplateColumn4',
--		[IS_EDITABLE]=0
--	WHERE GRID_COLUMN_ID=138
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 139) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(139, 9, 'column1', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=9, 
--		[NAME]='column1',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=139
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 140) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(140, 9, 'column12', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=9, 
--		[NAME]='column12',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=140
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 141) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(141, 9, 'column2', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=9, 
--		[NAME]='column2',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=141
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 142) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(142, 9, 'column3', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=9, 
--		[NAME]='column3',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=142
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 143) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(143, 9, 'column31', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=9, 
--		[NAME]='column31',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=143
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 144) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(144, 9, 'column4', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=9, 
--		[NAME]='column4',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=144
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 145) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(145, 9, 'column5', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=9, 
--		[NAME]='column5',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=145
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 146) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(146, 9, 'column6', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=9, 
--		[NAME]='column6',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=146
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 147) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(147, 9, 'column66', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=9, 
--		[NAME]='column66',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=147
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 148) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(148, 9, 'column7', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=9, 
--		[NAME]='column7',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=148
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 149) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(149, 9, 'TemplateColumn1', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=9, 
--		[NAME]='TemplateColumn1',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=149
	
--END
--GO

--IF NOT EXISTS (SELECT GRID_COLUMN_ID FROM dbo.GRID_COLUMN WHERE GRID_COLUMN_ID = 150) BEGIN

--	SET IDENTITY_INSERT dbo.GRID_COLUMN ON
	
--	INSERT INTO dbo.GRID_COLUMN([GRID_COLUMN_ID], [GRID_ID], [NAME], [IS_EDITABLE])
--	VALUES(150, 9, 'TemplateColumn2', 1)
	
--	SET IDENTITY_INSERT dbo.GRID_COLUMN OFF
	
--END ELSE BEGIN

--	UPDATE dbo.GRID_COLUMN 
--	SET [GRID_ID]=9, 
--		[NAME]='TemplateColumn2',
--		[IS_EDITABLE]=1
--	WHERE GRID_COLUMN_ID=150
	
--END
--GO

/* BEGIN Grant Execute permissions for stored procedures to Public user */

GRANT EXECUTE ON usp_grant_execute_on_sp_to_public TO PUBLIC 
GO
EXEC usp_grant_execute_on_sp_to_public
GO
/* END Grant Execute permissions for stored procedures to Public user */

/* BEGIN DB VERSION UPDATE */
DELETE FROM WV_APPLICATION WHERE SETTINGS = 'DatabaseVersion';
GO

UPDATE ADVAN_UPDATE SET WEBVAN_VERSION_ID = '3.50.04'

GO
