/*  Add Index IDX_VENDOR_VN_PAY_TO_CODE on VENDOR.sql */

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='IDX_VENDOR_VN_PAY_TO_CODE' AND object_id = OBJECT_ID('[dbo].[VENDOR]'))
BEGIN
	CREATE NONCLUSTERED INDEX [IDX_VENDOR_VN_PAY_TO_CODE]
	ON [dbo].[VENDOR] ([VN_PAY_TO_CODE])
END

GO
