IF NOT EXISTS(SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'VENDOR' AND COLUMN_NAME = 'IS_COMBO_RADIO_STATION') BEGIN

	ALTER TABLE [dbo].[VENDOR] ADD [IS_COMBO_RADIO_STATION] bit NOT NULL DEFAULT(0)
		
END
GO