IF NOT EXISTS (	SELECT COLUMN_NAME 
				FROM INFORMATION_SCHEMA.COLUMNS 
				WHERE 
					TABLE_NAME = 'PROOFING_MARKUP' 
					AND COLUMN_NAME = 'PROOFING_X_REVIEWER_ID') 
BEGIN
	ALTER TABLE [dbo].[PROOFING_MARKUP] ADD [PROOFING_X_REVIEWER_ID] [INT] NULL;	
END
GO
