IF NOT EXISTS(SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'NPR_STATION' AND COLUMN_NAME = 'ETAM_XREF') BEGIN

	ALTER TABLE [dbo].[NPR_STATION] ADD [ETAM_XREF] [int] NULL

END
GO
