IF NOT EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'QUICKBOOKS_SETTING' AND COLUMN_NAME = 'BILL_PRODUCTION_ACCOUNT') BEGIN

	ALTER TABLE [dbo].[QUICKBOOKS_SETTING] ADD [BILL_PRODUCTION_ACCOUNT] [varchar](21) NOT NULL DEFAULT('')
	
END
GO