IF NOT EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'VENDOR' AND COLUMN_NAME = 'CANADIAN_VENDOR_TYPE') BEGIN

	ALTER TABLE [dbo].[VENDOR] ADD [CANADIAN_VENDOR_TYPE] [int] NOT NULL DEFAULT(0)
	
END
GO