IF NOT EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'ALERT_ATTACHMENT' AND COLUMN_NAME = 'THUMBNAIL') 
BEGIN

	    ALTER TABLE [dbo].[ALERT_ATTACHMENT] ADD [THUMBNAIL] IMAGE NULL;
		
END
GO
