IF NOT EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MEDIA_BROADCAST_WORKSHEET' AND COLUMN_NAME = 'NPR_PREPOPULATE_DATES') 
BEGIN
	ALTER TABLE [dbo].[MEDIA_BROADCAST_WORKSHEET] ADD [NPR_PREPOPULATE_DATES] [bit] NOT NULL DEFAULT(0);
END
GO