IF NOT EXISTS(SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MEDIA_PLAN_DTL' AND COLUMN_NAME = 'MEDIA_DEMO_ID') BEGIN

	ALTER TABLE [dbo].[MEDIA_PLAN_DTL] ADD [MEDIA_DEMO_ID] [int] NULL
		
    ALTER TABLE [dbo].[MEDIA_PLAN_DTL]  WITH CHECK ADD  CONSTRAINT [FK_MEDIA_PLAN_DTL_MEDIA_DEMO] FOREIGN KEY([MEDIA_DEMO_ID])
    REFERENCES [dbo].[MEDIA_DEMO] ([MEDIA_DEMO_ID])

    ALTER TABLE [dbo].[MEDIA_PLAN_DTL] CHECK CONSTRAINT [FK_MEDIA_PLAN_DTL_MEDIA_DEMO]

END
GO

