IF NOT EXISTS(SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'NPR_STATION' AND COLUMN_NAME = 'ARIANNA_CHANNEL_ID') BEGIN

	ALTER TABLE [dbo].[NPR_STATION] ADD [ARIANNA_CHANNEL_ID] [int] NULL

END
GO
