'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AlertAssignmentState
    Public Property ID As Integer
    Public Property Name As String
    Public Property SortOrder As Nullable(Of Integer)
    Public Property IsActive As Nullable(Of Boolean)
    Public Property DefaultAlertCategoryCode As Nullable(Of Integer)

    Public Overridable Property Alert As ICollection(Of Alert) = New HashSet(Of Alert)
    Public Overridable Property AlertAssignmentTemplateEmployee As ICollection(Of AlertAssignmentTemplateEmployee) = New HashSet(Of AlertAssignmentTemplateEmployee)
    Public Overridable Property AlertAssignmentTemplateState As ICollection(Of AlertAssignmentTemplateState) = New HashSet(Of AlertAssignmentTemplateState)

End Class
