'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EmailRecipients
    Public Property Code As String
    Public Property FullName As String
    Public Property IsEmployee As Nullable(Of Boolean)
    Public Property IsClientContact As Nullable(Of Boolean)
    Public Property InAlertGroup As Nullable(Of Boolean)
    Public Property ConceptShareUserID As Nullable(Of Integer)
    Public Property Picture As Byte()
    Public Property IsConceptShareUser As Nullable(Of Boolean)

End Class
