'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Alert_AddAttachments
    
    '''<summary>
    '''DivUploadAttachments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivUploadAttachments As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''LinkButtonHelpFileSelection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButtonHelpFileSelection As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''RadUploadAlertDocuments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadUploadAlertDocuments As Global.Telerik.Web.UI.RadAsyncUpload
    
    '''<summary>
    '''LabelFileSizeLimitMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelFileSizeLimitMessage As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DivLinkDocuments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivLinkDocuments As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''CheckBoxLinkExistingFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxLinkExistingFile As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''DivLinkDocumentsRadListBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivLinkDocumentsRadListBox As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''RadListBoxLinkableDocuments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadListBoxLinkableDocuments As Global.Telerik.Web.UI.RadListBox
    
    '''<summary>
    '''TextBoxAttachmentComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxAttachmentComment As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ButtonUploadAttachments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonUploadAttachments As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ChkUploadToRepository control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkUploadToRepository As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''CheckBoxUploadToProofHQ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxUploadToProofHQ As Global.System.Web.UI.WebControls.CheckBox
End Class
