'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Chat_NewRoomCreator

    '''<summary>
    '''RadToolbarNewChatRoom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolbarNewChatRoom As Global.Telerik.Web.UI.RadToolBar

    '''<summary>
    '''UpdatePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''RadioButtonListEmployeeType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonListEmployeeType As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''RadListBoxEmployees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadListBoxEmployees As Global.Telerik.Web.UI.RadListBox

    '''<summary>
    '''RequiredFieldValidatorRoomName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidatorRoomName As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''TextBoxRoomName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxRoomName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBoxRoomDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxRoomDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CheckBoxIsPrivate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxIsPrivate As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CheckBoxSaveRoom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxSaveRoom As Global.System.Web.UI.WebControls.CheckBox
End Class
