'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DefaultParent

    '''<summary>
    '''ParentPageHead control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ParentPageHead As Global.System.Web.UI.HtmlControls.HtmlHead

    '''<summary>
    '''MaterialCSSLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MaterialCSSLink As Global.System.Web.UI.HtmlControls.HtmlLink

    '''<summary>
    '''RadStyleSheetManagerParent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadStyleSheetManagerParent As Global.Telerik.Web.UI.RadStyleSheetManager

    '''<summary>
    '''RadCodeBlockParent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCodeBlockParent As Global.Telerik.Web.UI.RadCodeBlock

    '''<summary>
    '''BodyTagParent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BodyTagParent As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''FrmParent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FrmParent As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''RadScriptManagerParent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptManagerParent As Global.Telerik.Web.UI.RadScriptManager

    '''<summary>
    '''framecontentLeft control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents framecontentLeft As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''DivNewPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivNewPanel As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ImageAdvantage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageAdvantage As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''DivAppPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivAppPanel As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ImageApps control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageApps As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''ASPxBinaryImageEmp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxBinaryImageEmp As Global.DevExpress.Web.ASPxBinaryImage

    '''<summary>
    '''DivUserInitial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivUserInitial As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LiteralEmployeeInitial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralEmployeeInitial As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LinkUserSchedulePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkUserSchedulePanel As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''DivDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivDate As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LiteralDayOfMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralDayOfMonth As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LiteralMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralMonth As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''DivTimeWarnings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivTimeWarnings As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''DivMissingTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivMissingTime As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ImageButtonMissingTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonMissingTime As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImageButtonDashboard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonDashboard As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImageButtonBoards control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonBoards As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImageButtonNextWorkspace control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonNextWorkspace As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImageButtonPreviousWorkspace control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonPreviousWorkspace As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''LinkUserBookmarksPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkUserBookmarksPanel As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''ImageButtonBookmarks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonBookmarks As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImageButtonNewApplications control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonNewApplications As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''HrCountSeparator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HrCountSeparator As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LinkUserAssignmentsPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkUserAssignmentsPanel As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''DivUserPanelAssignmentCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivUserPanelAssignmentCount As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LabelUserPanelAssignmentCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelUserPanelAssignmentCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LiteralUserPanelAssignmentCountLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralUserPanelAssignmentCountLabel As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LinkUserAlertsPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkUserAlertsPanel As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''DivUserPanelAlertCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivUserPanelAlertCount As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LabelUserPanelAlertCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelUserPanelAlertCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LiteralUserPanelAlertCountLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralUserPanelAlertCountLabel As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LinkUserReviewsPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkUserReviewsPanel As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''DivUserPanelReviewCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivUserPanelReviewCount As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LabelUserPanelReviewCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelUserPanelReviewCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LiteralUserPanelReviewCountLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralUserPanelReviewCountLabel As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LinkUserTasksPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkUserTasksPanel As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''DivUserPanelTaskCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivUserPanelTaskCount As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LabelUserPanelTaskCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelUserPanelTaskCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LiteralUserPanelTaskCountLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralUserPanelTaskCountLabel As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''DivUserPanelTimeCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivUserPanelTimeCount As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LabelUserPanelTimeCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelUserPanelTimeCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LiteralUserPanelTimeCountLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralUserPanelTimeCountLabel As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''DivChatButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivChatButton As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ImageButtonChat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonChat As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''HrSignOut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HrSignOut As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ImageButtonSignOut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonSignOut As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''maincontent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents maincontent As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ImageLogo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageLogo As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''UpdatePanelRadDock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelRadDock As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''RadDockLayoutParent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDockLayoutParent As Global.Telerik.Web.UI.RadDockLayout

    '''<summary>
    '''DivLeftDock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivLeftDock As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''RadDockZoneLeft control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDockZoneLeft As Global.Telerik.Web.UI.RadDockZone

    '''<summary>
    '''DivRightDock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivRightDock As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''RadDockZoneCenter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDockZoneCenter As Global.Telerik.Web.UI.RadDockZone

    '''<summary>
    '''DivDefaultWorkspace control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivDefaultWorkspace As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''DefaultWorkspaceLinkUserAssignmentsPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DefaultWorkspaceLinkUserAssignmentsPanel As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''DivDefaultWorkspaceAssignmentsBadge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivDefaultWorkspaceAssignmentsBadge As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LabelDefaultWorkspaceAssignmentCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelDefaultWorkspaceAssignmentCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LiteralDefaultWorkspaceAssignmentCountLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralDefaultWorkspaceAssignmentCountLabel As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''DefaultWorkspaceLinkUserAlertsPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DefaultWorkspaceLinkUserAlertsPanel As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''DivDefaultWorkspaceAlertsBadge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivDefaultWorkspaceAlertsBadge As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LabelDefaultWorkspaceAlertCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelDefaultWorkspaceAlertCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LiteralDefaultWorkspaceAlertCountLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralDefaultWorkspaceAlertCountLabel As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''DefaultWorkspaceLinkUserReviewsPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DefaultWorkspaceLinkUserReviewsPanel As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''DivDefaultWorkspaceReviewsBadge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivDefaultWorkspaceReviewsBadge As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LabelDefaultWorkspaceReviewCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelDefaultWorkspaceReviewCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LiteralDefaultWorkspaceReviewCountLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralDefaultWorkspaceReviewCountLabel As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''DefaultWorkspaceLinkUserTasksPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DefaultWorkspaceLinkUserTasksPanel As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''DivDefaultWorkspaceTasksBadge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivDefaultWorkspaceTasksBadge As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LabelDefaultWorkspaceTaskCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelDefaultWorkspaceTaskCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LiteralDefaultWorkspaceTaskCountLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralDefaultWorkspaceTaskCountLabel As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''DivDefaultWorkspaceRadRadialGaugeHoursToday control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivDefaultWorkspaceRadRadialGaugeHoursToday As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''RadRadialGaugeHoursToday control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadRadialGaugeHoursToday As Global.Telerik.Web.UI.RadRadialGauge

    '''<summary>
    '''DivDefaultWorkspaceRadRadialGaugeHoursThisWeek control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivDefaultWorkspaceRadRadialGaugeHoursThisWeek As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''RadRadialGaugeHoursThisWeek control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadRadialGaugeHoursThisWeek As Global.Telerik.Web.UI.RadRadialGauge

    '''<summary>
    '''DivDefaultWorkspaceLeftMiddle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivDefaultWorkspaceLeftMiddle As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''iFrameDefaultWorkspaceLeftMiddle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents iFrameDefaultWorkspaceLeftMiddle As Global.System.Web.UI.HtmlControls.HtmlIframe

    '''<summary>
    '''DivDefaultWorkspaceLeftBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivDefaultWorkspaceLeftBottom As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''RepeaterDefaultWorkspaceFavorites control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RepeaterDefaultWorkspaceFavorites As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''UpdatePanelRight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelRight As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''PlaceHolderDefaultWorkspaceRight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PlaceHolderDefaultWorkspaceRight As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''RadTreeViewMainMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTreeViewMainMenu As Global.Telerik.Web.UI.RadTreeView

    '''<summary>
    '''RadTreeViewApps control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTreeViewApps As Global.Telerik.Web.UI.RadTreeView

    '''<summary>
    '''LabelEmployeeWelcome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelEmployeeWelcome As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ImageButtonSetColors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonSetColors As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImageButtonTheme control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonTheme As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''UpdatePanelUserSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelUserSummary As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''UserSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UserSummary As Global.Webvantage.DesktopCardsMySummary

    '''<summary>
    '''DivWeather control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivWeather As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''RadTreeViewUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTreeViewUser As Global.Telerik.Web.UI.RadTreeView

    '''<summary>
    '''DivServerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivServerName As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LiteralServer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralServer As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LiteralDatabase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralDatabase As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''DivUserSchedule control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivUserSchedule As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''UpdatePanelUserSchedule control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelUserSchedule As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''PlaceHolderUserSchedule control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PlaceHolderUserSchedule As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''RadScriptBlockSlider control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptBlockSlider As Global.Telerik.Web.UI.RadScriptBlock

    '''<summary>
    '''HiddenFieldWindowLogger control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenFieldWindowLogger As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenFieldWorkspaceLogger control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenFieldWorkspaceLogger As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenFieldCurrentWorkspaceId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenFieldCurrentWorkspaceId As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenFieldFloatDesktopObjects control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenFieldFloatDesktopObjects As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenFieldAutoOpenWindowsLoaded control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenFieldAutoOpenWindowsLoaded As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenFieldChatEnabled control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenFieldChatEnabled As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''RadCodeBlockParentBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCodeBlockParentBottom As Global.Telerik.Web.UI.RadCodeBlock

    '''<summary>
    '''RadSkinManagerParent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadSkinManagerParent As Global.Telerik.Web.UI.RadSkinManager

    '''<summary>
    '''RadFormDecoratorParent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadFormDecoratorParent As Global.Telerik.Web.UI.RadFormDecorator

    '''<summary>
    '''RadContextMenuWorkspaces control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadContextMenuWorkspaces As Global.Telerik.Web.UI.RadContextMenu

    '''<summary>
    '''RadAjaxManagerParent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxManagerParent As Global.Telerik.Web.UI.RadAjaxManager

    '''<summary>
    '''RadWindowManagerParent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadWindowManagerParent As Global.Telerik.Web.UI.RadWindowManager

    '''<summary>
    '''RadNotificationLicenseKey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadNotificationLicenseKey As Global.Telerik.Web.UI.RadNotification

    '''<summary>
    '''LabelNotificationMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelNotificationMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RadButtonDontRemindMeAgain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadButtonDontRemindMeAgain As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''RadButtonRemindMeAgainTomorrow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadButtonRemindMeAgainTomorrow As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''RadNotificationParent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadNotificationParent As Global.Telerik.Web.UI.RadNotification

    '''<summary>
    '''RadPersistenceManagerParent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPersistenceManagerParent As Global.Telerik.Web.UI.RadPersistenceManager
End Class
