'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Documents_List2
    
    '''<summary>
    '''RadScriptBlock2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptBlock2 As Global.Telerik.Web.UI.RadScriptBlock
    
    '''<summary>
    '''RadToolbarInvoiceDocuments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolbarInvoiceDocuments As Global.Telerik.Web.UI.RadToolBar
    
    '''<summary>
    '''RadToolBarButtonUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolBarButtonUpload As Global.Telerik.Web.UI.RadToolBarButton
    
    '''<summary>
    '''RadToolBarButtonDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolBarButtonDelete As Global.Telerik.Web.UI.RadToolBarButton
    
    '''<summary>
    '''RadToolBarButtonDeleteSeparator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolBarButtonDeleteSeparator As Global.Telerik.Web.UI.RadToolBarButton
    
    '''<summary>
    '''RadgridInvoiceDocuments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadgridInvoiceDocuments As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''RadWindowLookUp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadWindowLookUp As Global.Telerik.Web.UI.RadWindow
    
    '''<summary>
    '''HiddenFieldControlsToSet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenFieldControlsToSet As Global.System.Web.UI.WebControls.HiddenField
End Class
