'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EmployeeTimeForecast_AddEmployees

    '''<summary>
    '''UpdatePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''TdRadToolBarEmployeeTimeForecastEmployee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TdRadToolBarEmployeeTimeForecastEmployee As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''RadToolBarEmployeeTimeForecastEmployee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolBarEmployeeTimeForecastEmployee As Global.Telerik.Web.UI.RadToolBar

    '''<summary>
    '''RadToolBarButtonFirstSeparator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolBarButtonFirstSeparator As Global.Telerik.Web.UI.RadToolBarButton

    '''<summary>
    '''RadToolBarButtonDone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolBarButtonDone As Global.Telerik.Web.UI.RadToolBarButton

    '''<summary>
    '''RadToolBarButtonSecondSeparator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolBarButtonSecondSeparator As Global.Telerik.Web.UI.RadToolBarButton

    '''<summary>
    '''DropDownListOffice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownListOffice As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''RadListBoxAvailableEmployees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadListBoxAvailableEmployees As Global.Telerik.Web.UI.RadListBox

    '''<summary>
    '''RadListBoxCurrentEmployees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadListBoxCurrentEmployees As Global.Telerik.Web.UI.RadListBox
End Class
