'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Employee_Card

    '''<summary>
    '''DivEmployee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivEmployee As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''DivFlipper control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivFlipper As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''DivFront control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivFront As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ASPxBinaryImageEmp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxBinaryImageEmp As Global.DevExpress.Web.ASPxBinaryImage

    '''<summary>
    '''LabelProjectManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelProjectManager As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelTaskCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelTaskCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelTotalHours control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelTotalHours As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelActualHours control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelActualHours As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelHoursGraph control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelHoursGraph As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelEmployeeName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelEmployeeName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DivBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivBack As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''DivEmployeeInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivEmployeeInfo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LabelBackFullName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelBackFullName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelBackNickName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelBackNickName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelBackEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelBackEmail As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelBackCellPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelBackCellPhone As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelBackDefaultRole control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelBackDefaultRole As Global.System.Web.UI.WebControls.Label
End Class
