'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Estimating_JobHistory

    '''<summary>
    '''lblMSG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMSG As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''HlClient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HlClient As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''TxtClientCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtClientCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtClientDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtClientDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HlDivision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HlDivision As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''TxtDivisionCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtDivisionCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtDivisionDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtDivisionDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HlProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HlProduct As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''TxtProductCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtProductCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtProductDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtProductDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HlJobType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HlJobType As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''TxtJobType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtJobType As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtJobTypeDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtJobTypeDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RadDatePickerJobCutOffDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePickerJobCutOffDate As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''RadDatePickerToDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePickerToDate As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''cbShowClosed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbShowClosed As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''hfjobs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfjobs As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfcomps control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfcomps As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfcount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfcount As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfestclient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfestclient As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfestdivision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfestdivision As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfestproduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfestproduct As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfestjob control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfestjob As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfestcomp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfestcomp As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfsalesclass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfsalesclass As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''BtnRefresh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnRefresh As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnGetHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGetHistory As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnCopy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCopy As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''butExport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents butExport As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''SummaryTabs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SummaryTabs As Global.Telerik.Web.UI.RadTabStrip

    '''<summary>
    '''Tab1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Tab1 As Global.Telerik.Web.UI.RadTab

    '''<summary>
    '''pnlJH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlJH As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''RadGridJobHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridJobHistory As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''pnlQva control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlQva As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''RadGridQvASummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridQvASummary As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''pnlFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFilter As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''QvaRadgridJob control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QvaRadgridJob As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''UpdatePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''rbIncludeNB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbIncludeNB As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbBreakoutAllNB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbBreakoutAllNB As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbBreakoutNBForFT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbBreakoutNBForFT As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''cbEmployeeTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbEmployeeTime As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbIncomeOnly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbIncomeOnly As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbVendor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbVendor As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''butClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents butClear As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''butOk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents butOk As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LitScript control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LitScript As Global.System.Web.UI.WebControls.Literal
End Class
