'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class JobTemplate_New

    '''<summary>
    '''TableCellCreate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCellCreate As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''CollapsablePanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CollapsablePanel2 As Global.eWorld.UI.CollapsablePanel

    '''<summary>
    '''RadComboBoxJobTemplate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadComboBoxJobTemplate As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''DivOffice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivOffice As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''HlOffice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HlOffice As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''TxtOffice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtOffice As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RFVOffice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFVOffice As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''hlClient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlClient As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''txtClient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtClient As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfv As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblUniqueClient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUniqueClient As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hlDivision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlDivision As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''txtDivision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDivision As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Requiredfieldvalidator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Requiredfieldvalidator1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''hlProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlProduct As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''txtProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProduct As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Requiredfieldvalidator2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Requiredfieldvalidator2 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtJobDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtJobDesc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvJobDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvJobDescription As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtCompDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCompDesc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''MessageComp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MessageComp As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rfvComponentDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvComponentDesc As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''hlSalesClass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlSalesClass As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''txtSalesClass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSalesClass As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Requiredfieldvalidator3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Requiredfieldvalidator3 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''hlAE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlAE As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''txtAE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Requiredfieldvalidator4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Requiredfieldvalidator4 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''LinkButtonCampaign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButtonCampaign As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''txtCampaign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCampaign As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''hfCampaignID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfCampaignID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''RequiredfieldvalidatorCampaign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredfieldvalidatorCampaign As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''HyperLinkJobType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLinkJobType As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''TextBoxJobType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxJobType As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RequiredFieldValidatorJobType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidatorJobType As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''CheckBoxCreateSchedule control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxCreateSchedule As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''DivSchedule control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivSchedule As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LabelStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''HyperLinkStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLinkStatus As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''TextBoxTrafficScheduleStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxTrafficScheduleStatus As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LabelManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelManager As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''HyperLinkTrafficManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLinkTrafficManager As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''TextBoxTrafficManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxTrafficManager As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RequiredfieldvalidatorTrafficManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredfieldvalidatorTrafficManager As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''CheckBoxOverride control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxOverride As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''butCreateJob control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents butCreateJob As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''butCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents butCancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''TableCellBoards control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCellBoards As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''CollapsablePanelBoards control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CollapsablePanelBoards As Global.eWorld.UI.CollapsablePanel

    '''<summary>
    '''RadListBoxBoards control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadListBoxBoards As Global.Telerik.Web.UI.RadListBox

    '''<summary>
    '''CheckBoxShowCopyFromExistingJob control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxShowCopyFromExistingJob As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CollapsablePanelHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CollapsablePanelHeader As Global.eWorld.UI.CollapsablePanel

    '''<summary>
    '''divCDP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCDP As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''HlClientSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HlClientSource As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''TxtClientSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtClientSource As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtClientSourceDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtClientSourceDesc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HlDivisionSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HlDivisionSource As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''TxtDivisionSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtDivisionSource As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtDivisionSourceDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtDivisionSourceDesc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HlProductSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HlProductSource As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''TxtProductSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtProductSource As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtProductSourceDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtProductSourceDesc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HlJobTypeSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HlJobTypeSource As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''TxtJobTypeSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtJobTypeSource As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtJobTypeSourceDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtJobTypeSourceDesc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HyperLinkStatusFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLinkStatusFilter As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''TextBoxStatusFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxStatusFilter As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBoxStatusFilterDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxStatusFilterDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HlJobSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HlJobSource As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''TxtJobSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtJobSource As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtJobSourceDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtJobSourceDesc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LabelSalesClassSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelSalesClassSource As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TxtSalesClassSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtSalesClassSource As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtSalesClassDescriptionSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtSalesClassDescriptionSource As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cbShowClosed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbShowClosed As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''DivCopyTrafficManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivCopyTrafficManager As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LabelStatusCopy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelStatusCopy As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hlStatusCopy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlStatusCopy As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''txtStatusCopy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStatusCopy As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtStatusDescCopy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStatusDescCopy As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DivCopyJobProjectScheduleDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivCopyJobProjectScheduleDate As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LabelTrafficManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelTrafficManager As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''HyperLinkCopyTrafficManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLinkCopyTrafficManager As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''TextBoxCopyTrafficManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxCopyTrafficManager As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RequiredfieldvalidatorTextBoxCopyTrafficManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredfieldvalidatorTextBoxCopyTrafficManager As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''TextBoxCopyTrafficManagerDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxCopyTrafficManagerDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnCopyJob control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCopyJob As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ButtonClearCopy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonClearCopy As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cbCopyCreativeBrief control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbCopyCreativeBrief As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbCopySpecs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbCopySpecs As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbCopyDestinations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbCopyDestinations As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CheckBoxJobDocumentAssociations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxJobDocumentAssociations As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CheckBoxJobCompDocumentAssociations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxJobCompDocumentAssociations As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbCopyProjectSchedule control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbCopyProjectSchedule As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''DivCopyJobProjectScheduleStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivCopyJobProjectScheduleStatus As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CheckBoxListCopyOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxListCopyOptions As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''RadGridJobCopy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridJobCopy As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''btnComps control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnComps As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''rcbfooter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbfooter As Global.Telerik.Web.UI.RadScriptBlock
End Class
