'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Maintenance_CalendarTime
    
    '''<summary>
    '''RadComboBoxCalendarType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadComboBoxCalendarType As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''DivEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivEmail As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''TextBoxEmailAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxEmailAddress As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''DivEmailUserName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivEmailUserName As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''TextBoxEmailUserName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxEmailUserName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''DivEmailPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivEmailPassword As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''TextBoxEmailPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxEmailPassword As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''DivHost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivHost As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''TextBoxHost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxHost As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''DivPort control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivPort As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''TextBoxPort control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxPort As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''DivSSL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivSSL As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''CheckboxSSL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckboxSSL As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''DivGoogleServices control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivGoogleServices As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''LabelCalendarSync control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelCalendarSync As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''RadButtonDisableCalendarSync control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadButtonDisableCalendarSync As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''RadButtonEnableCalendarSync control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadButtonEnableCalendarSync As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''ButtonSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonSave As Global.System.Web.UI.WebControls.Button
End Class
