'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Maintenance_AddDiary

    '''<summary>
    '''RadToolbarProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolbarProduct As Global.Telerik.Web.UI.RadToolBar

    '''<summary>
    '''RadToolBarButtonSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolBarButtonSave As Global.Telerik.Web.UI.RadToolBarButton

    '''<summary>
    '''RadToolBarButtonNew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolBarButtonNew As Global.Telerik.Web.UI.RadToolBarButton

    '''<summary>
    '''RadToolBarButtonUploadDocument control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolBarButtonUploadDocument As Global.Telerik.Web.UI.RadToolBarButton

    '''<summary>
    '''RadToolBarButtonDocuments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolBarButtonDocuments As Global.Telerik.Web.UI.RadToolBarButton

    '''<summary>
    '''RadToolBarRefresh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolBarRefresh As Global.Telerik.Web.UI.RadToolBarButton

    '''<summary>
    '''CollapsablePanelHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CollapsablePanelHeader As Global.eWorld.UI.CollapsablePanel

    '''<summary>
    '''UpdatePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''TextBoxProductCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxProductCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RFVCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFVCode As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''CheckBoxIsNewBusiness control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxIsNewBusiness As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''TextBoxProductName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxProductName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RFVName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFVName As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''CheckBoxIsInactive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxIsInactive As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''RadComboBoxClient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadComboBoxClient As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''RFVClient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFVClient As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''RadComboBoxDivision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadComboBoxDivision As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''RFVDivision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFVDivision As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''RadComboBoxOffice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadComboBoxOffice As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''RFVOffice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFVOffice As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''CollapsablePanelAddresses control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CollapsablePanelAddresses As Global.eWorld.UI.CollapsablePanel

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''LinkButtonBilling_Client control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButtonBilling_Client As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LinkButtonBilling_Division control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButtonBilling_Division As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''TextBoxBillingAddress1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxBillingAddress1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBoxBillingAddress2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxBillingAddress2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBoxBillingCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxBillingCity As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBoxBillingCounty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxBillingCounty As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBoxBillingState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxBillingState As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBoxBillingZip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxBillingZip As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBoxBillingCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxBillingCountry As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LinkButtonStatement_Client control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButtonStatement_Client As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LinkButtonStatement_Division control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButtonStatement_Division As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LinkButtonStatement_Billing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButtonStatement_Billing As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''TextBoxStatementAddress1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxStatementAddress1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBoxStatementAddress2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxStatementAddress2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBoxStatementCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxStatementCity As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBoxStatementCounty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxStatementCounty As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBoxStatementState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxStatementState As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBoxStatementZip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxStatementZip As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBoxStatementCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxStatementCountry As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBoxBillingPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxBillingPhone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBoxBillingPhoneExt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxBillingPhoneExt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBoxBillingFax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxBillingFax As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBoxBillingFaxExt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxBillingFaxExt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBoxStatementPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxStatementPhone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBoxStatementPhoneExt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxStatementPhoneExt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBoxStatementFax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxStatementFax As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBoxStatementFaxExt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxStatementFaxExt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CollapsablePanelOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CollapsablePanelOptions As Global.eWorld.UI.CollapsablePanel

    '''<summary>
    '''TextBoxAttentionLine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxAttentionLine As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RadComboBoxCurrency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadComboBoxCurrency As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''TextBoxUserDefinedField1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxUserDefinedField1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBoxUserDefinedField2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxUserDefinedField2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBoxUserDefinedField3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxUserDefinedField3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBoxUserDefinedField4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxUserDefinedField4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''UpdatePanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel2 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''RadGridSortKeys control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridSortKeys As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''CollapsablePanelAccountExecutives control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CollapsablePanelAccountExecutives As Global.eWorld.UI.CollapsablePanel

    '''<summary>
    '''UpdatePanel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel3 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''RadGridEmployees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridEmployees As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''ImageButtonAddAccountExecutive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonAddAccountExecutive As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImageButtonRemoveAccountExecutive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonRemoveAccountExecutive As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''RadGridAccountExecutives control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridAccountExecutives As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''CollapsablePanelContacts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CollapsablePanelContacts As Global.eWorld.UI.CollapsablePanel

    '''<summary>
    '''UpdatePanel4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel4 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''RadGridContacts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridContacts As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''ButtonAddContact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonAddContact As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''CollapsablePanelCompanyProfile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CollapsablePanelCompanyProfile As Global.eWorld.UI.CollapsablePanel

    '''<summary>
    '''RadComboBoxIndustry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadComboBoxIndustry As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''RadComboBoxSpecialty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadComboBoxSpecialty As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''RadComboBoxRegion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadComboBoxRegion As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''RadNumericTextBoxRevenue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadNumericTextBoxRevenue As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''RadNumericTextBoxNumEmployees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadNumericTextBoxNumEmployees As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''CheckBoxCaseStudy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxCaseStudy As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CheckBoxReference control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxReference As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''UpdatePanel5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel5 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''RadGridCompanyProfileAffiliations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridCompanyProfileAffiliations As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''TextBoxNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxNotes As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBoxCompanyProfileID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxCompanyProfileID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CollapsablePanelActivitySummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CollapsablePanelActivitySummary As Global.eWorld.UI.CollapsablePanel

    '''<summary>
    '''RadDatePickerLeadDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePickerLeadDate As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''RadComboBoxSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadComboBoxSource As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''TextBoxLastActivityDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxLastActivityDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RadDatePickerLastContactDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePickerLastContactDate As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''RadDatePickerSoldDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePickerSoldDate As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''RadDatePickerLostDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePickerLostDate As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''RadNumericTextBoxProbability control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadNumericTextBoxProbability As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''RadComboBoxRating control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadComboBoxRating As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''TextBoxCurrentProvider control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxCurrentProvider As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RowTotalOpportunity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RowTotalOpportunity As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''RadNumericTextBoxTotalOpportunity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadNumericTextBoxTotalOpportunity As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''UpdatePanel6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel6 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''RadGridCompetitors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridCompetitors As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''TextBoxActivityID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxActivityID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RadGridActivitySummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridActivitySummary As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''ButtonAddDiary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonAddDiary As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''CollapsablePanelContracts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CollapsablePanelContracts As Global.eWorld.UI.CollapsablePanel

    '''<summary>
    '''RadGridContracts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridContracts As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''ButtonAddContract control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonAddContract As Global.System.Web.UI.WebControls.Button
End Class
