'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MediaCalendar
    
    '''<summary>
    '''RadScriptBlock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptBlock As Global.Telerik.Web.UI.RadScriptBlock
    
    '''<summary>
    '''RadToolBarMediaCalendar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolBarMediaCalendar As Global.Telerik.Web.UI.RadToolBar
    
    '''<summary>
    '''RadToolbarButtonRefresh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolbarButtonRefresh As Global.Telerik.Web.UI.RadToolBarButton
    
    '''<summary>
    '''RadTabStrip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTabStrip As Global.Telerik.Web.UI.RadTabStrip
    
    '''<summary>
    '''Tab1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Tab1 As Global.Telerik.Web.UI.RadTab
    
    '''<summary>
    '''RadMultiPageCalendar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadMultiPageCalendar As Global.Telerik.Web.UI.RadMultiPage
    
    '''<summary>
    '''RadPageViewCalendar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageViewCalendar As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''RadSchedulerProjectMediaCalendar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadSchedulerProjectMediaCalendar As Global.Telerik.Web.UI.RadScheduler
    
    '''<summary>
    '''SchedulerAppointmentContextMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SchedulerAppointmentContextMenu As Global.Telerik.Web.UI.RadSchedulerContextMenu
    
    '''<summary>
    '''RadSchedulerContextMenuDocuments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadSchedulerContextMenuDocuments As Global.Telerik.Web.UI.RadSchedulerContextMenu
End Class
