'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Reporting_MediaSpecificationReports

    '''<summary>
    '''RadToolBarDynamicReportTemplates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolBarDynamicReportTemplates As Global.Telerik.Web.UI.RadToolBar

    '''<summary>
    '''RadToolBarButtonFirstSeparator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolBarButtonFirstSeparator As Global.Telerik.Web.UI.RadToolBarButton

    '''<summary>
    '''RadToolBarButtonAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolBarButtonAdd As Global.Telerik.Web.UI.RadToolBarButton

    '''<summary>
    '''RadToolBarButtonSecondSeparator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolBarButtonSecondSeparator As Global.Telerik.Web.UI.RadToolBarButton

    '''<summary>
    '''RadComboBoxReportCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadComboBoxReportCategory As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''UpdatePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''RadGridDynamicReportTemplates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridDynamicReportTemplates As Global.Telerik.Web.UI.RadGrid
End Class
