'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Reporting_DynamicReportColumnEdit

    '''<summary>
    '''RadScriptBlockRadWindow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptBlockRadWindow As Global.Telerik.Web.UI.RadScriptBlock

    '''<summary>
    '''TdRadToolBarDynamicReportColumnEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TdRadToolBarDynamicReportColumnEdit As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''RadToolBarDynamicReportColumnEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolBarDynamicReportColumnEdit As Global.Telerik.Web.UI.RadToolBar

    '''<summary>
    '''RadToolBarSeparatorFirstSeparator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolBarSeparatorFirstSeparator As Global.Telerik.Web.UI.RadToolBarButton

    '''<summary>
    '''RadToolBarButtonOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolBarButtonOK As Global.Telerik.Web.UI.RadToolBarButton

    '''<summary>
    '''RadToolBarSeparatorSecondSeparator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolBarSeparatorSecondSeparator As Global.Telerik.Web.UI.RadToolBarButton

    '''<summary>
    '''RadToolBarButtonCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolBarButtonCancel As Global.Telerik.Web.UI.RadToolBarButton

    '''<summary>
    '''RadToolBarSeparatorThirdSeparator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolBarSeparatorThirdSeparator As Global.Telerik.Web.UI.RadToolBarButton

    '''<summary>
    '''RadToolBarButtonReset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolBarButtonReset As Global.Telerik.Web.UI.RadToolBarButton

    '''<summary>
    '''RadToolBarSeparatorFourthSeparator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolBarSeparatorFourthSeparator As Global.Telerik.Web.UI.RadToolBarButton

    '''<summary>
    '''RadToolBarButtonSelectAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolBarButtonSelectAll As Global.Telerik.Web.UI.RadToolBarButton

    '''<summary>
    '''RadToolBarSeparatorFifthSeparator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolBarSeparatorFifthSeparator As Global.Telerik.Web.UI.RadToolBarButton

    '''<summary>
    '''RadToolBarButtonDeselectAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolBarButtonDeselectAll As Global.Telerik.Web.UI.RadToolBarButton

    '''<summary>
    '''RadToolBarSeparatorSixthSeparator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolBarSeparatorSixthSeparator As Global.Telerik.Web.UI.RadToolBarButton

    '''<summary>
    '''RadToolBarButtonShowOnlyVisibleColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolBarButtonShowOnlyVisibleColumns As Global.Telerik.Web.UI.RadToolBarButton

    '''<summary>
    '''RadToolBarSeparatorSeventhSeparator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolBarSeparatorSeventhSeparator As Global.Telerik.Web.UI.RadToolBarButton

    '''<summary>
    '''UpdatePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''RadGridDynamicReportColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridDynamicReportColumns As Global.Telerik.Web.UI.RadGrid
End Class
