'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Reporting_InitialLoadingDirectTime
    
    '''<summary>
    '''RadScriptBlockRadWindow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptBlockRadWindow As Global.Telerik.Web.UI.RadScriptBlock
    
    '''<summary>
    '''RadToolBarDynamicReportInitialLoading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolBarDynamicReportInitialLoading As Global.Telerik.Web.UI.RadToolBar
    
    '''<summary>
    '''RadToolBarSeparatorFirstSeparator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolBarSeparatorFirstSeparator As Global.Telerik.Web.UI.RadToolBarButton
    
    '''<summary>
    '''RadToolBarButtonOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolBarButtonOK As Global.Telerik.Web.UI.RadToolBarButton
    
    '''<summary>
    '''RadToolBarSeparatorSecondSeparator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolBarSeparatorSecondSeparator As Global.Telerik.Web.UI.RadToolBarButton
    
    '''<summary>
    '''RadToolBarButtonCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolBarButtonCancel As Global.Telerik.Web.UI.RadToolBarButton
    
    '''<summary>
    '''RadToolBarSeparatorThirdSeparator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolBarSeparatorThirdSeparator As Global.Telerik.Web.UI.RadToolBarButton
    
    '''<summary>
    '''RadTabStripTaskCalendar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTabStripTaskCalendar As Global.Telerik.Web.UI.RadTabStrip
    
    '''<summary>
    '''RadMultiPageCalendar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadMultiPageCalendar As Global.Telerik.Web.UI.RadMultiPage
    
    '''<summary>
    '''RadPageViewOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageViewOptions As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''Fieldset1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fieldset1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''RadComboBoxCriteria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadComboBoxCriteria As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''tdFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdFrom As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''RadDatePickerFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePickerFrom As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadButtonYTD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadButtonYTD As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''RadButton1Year control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadButton1Year As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''trTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trTo As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''RadDatePickerTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePickerTo As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadButtonMTD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadButtonMTD As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''RadButton2Years control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadButton2Years As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''tr1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr1 As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''CheckBoxOnlyActiveEmployees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxOnlyActiveEmployees As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''RadPageViewWorkloadSelectCDP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageViewWorkloadSelectCDP As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''RadioButtonAllCDP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonAllCDP As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RadioButtonChoose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonChoose As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''PanelCDP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelCDP As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''RadioButtonClient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonClient As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RadioButtonClientDivision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonClientDivision As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RadioButtonClientDivisionProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonClientDivisionProduct As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RadGridClient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridClient As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''RadGridCD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridCD As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''RadGridCDP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridCDP As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''RadPageViewSelectCampaigns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageViewSelectCampaigns As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''RadioButtonAllCampaigns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonAllCampaigns As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RadioButtonChooseCampaigns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonChooseCampaigns As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RadGridCampaigns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridCampaigns As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''RadPageViewSelectJobs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageViewSelectJobs As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''RadioButtonAllJobs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonAllJobs As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RadioButtonChooseJobs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonChooseJobs As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RadioButtonOpenJobs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonOpenJobs As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RadioButtonOpenClosedJobs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonOpenClosedJobs As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RadGridJobs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridJobs As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''RadPageViewSelectDepartmentTeams control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageViewSelectDepartmentTeams As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''RadioButtonAllDepartmentTeams control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonAllDepartmentTeams As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RadioButtonChooseDepartmentTeams control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonChooseDepartmentTeams As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RadGridDepartmentTeams control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridDepartmentTeams As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''RadPageViewEmployees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageViewEmployees As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''RadioButtonAllEmployees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonAllEmployees As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RadioButtonChooseEmployees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonChooseEmployees As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RadGridEmployees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridEmployees As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''RadPageViewFunctions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageViewFunctions As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''RadioButtonAllFunctions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonAllFunctions As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RadioButtonChooseFunctions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonChooseFunctions As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RadGridFunctions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridFunctions As Global.Telerik.Web.UI.RadGrid
End Class
