'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Reporting_InitialLoadingClientPLDetail

    '''<summary>
    '''RadScriptBlockRadWindow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptBlockRadWindow As Global.Telerik.Web.UI.RadScriptBlock

    '''<summary>
    '''RadToolBarDynamicReportInitialLoading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolBarDynamicReportInitialLoading As Global.Telerik.Web.UI.RadToolBar

    '''<summary>
    '''RadToolBarSeparatorFirstSeparator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolBarSeparatorFirstSeparator As Global.Telerik.Web.UI.RadToolBarButton

    '''<summary>
    '''RadToolBarButtonOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolBarButtonOK As Global.Telerik.Web.UI.RadToolBarButton

    '''<summary>
    '''RadToolBarSeparatorSecondSeparator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolBarSeparatorSecondSeparator As Global.Telerik.Web.UI.RadToolBarButton

    '''<summary>
    '''RadToolBarButtonCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolBarButtonCancel As Global.Telerik.Web.UI.RadToolBarButton

    '''<summary>
    '''RadToolBarSeparatorThirdSeparator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolBarSeparatorThirdSeparator As Global.Telerik.Web.UI.RadToolBarButton

    '''<summary>
    '''RadTabStripTaskCalendar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTabStripTaskCalendar As Global.Telerik.Web.UI.RadTabStrip

    '''<summary>
    '''RadMultiPageCalendar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadMultiPageCalendar As Global.Telerik.Web.UI.RadMultiPage

    '''<summary>
    '''RadPageViewOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageViewOptions As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''RadComboBoxStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadComboBoxStart As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''RadButtonYTD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadButtonYTD As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''RadButton1Year control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadButton1Year As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''RadButton2YTD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadButton2YTD As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''RadComboBoxEnd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadComboBoxEnd As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''RadButtonMTD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadButtonMTD As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''RadButton2Years control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadButton2Years As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''RadioButtonStandard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonStandard As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''RadioButtonAlternate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonAlternate As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''FieldsetGroupBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FieldsetGroupBy As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CheckBoxOffice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxOffice As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CheckBoxType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxType As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CheckBoxCampaign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxCampaign As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CheckBoxClient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxClient As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CheckBoxSalesClass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxSalesClass As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CheckBoxAccountExecutive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxAccountExecutive As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CheckBoxDivision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxDivision As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CheckBoxPostPeriod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxPostPeriod As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CheckBoxProductUDF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxProductUDF As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CheckBoxProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxProduct As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CheckBoxYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxYear As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Fieldset1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fieldset1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CheckBoxManualInvoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxManualInvoice As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CheckBoxGLEntries control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxGLEntries As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CheckBoxBilledIncomeRecognized control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxBilledIncomeRecognized As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Fieldset2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fieldset2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''RadioButtonOverhead control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonOverhead As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''RadioButtonFTE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonFTE As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''RadioButtonCost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonCost As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''RadioButtonHours control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonHours As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''RadioButtonCombine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonCombine As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''RadioButtonBreakout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonBreakout As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''CheckBoxExcludeNewBusiness control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxExcludeNewBusiness As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CheckBoxDirectExpenseOperatingOnly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxDirectExpenseOperatingOnly As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''LabelOverheadSet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelOverheadSet As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RadComboBoxOverheadSet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadComboBoxOverheadSet As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''RadPageViewSelectOffices control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageViewSelectOffices As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''RadioButtonAllOffices control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonAllOffices As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''RadioButtonChooseOffices control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonChooseOffices As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''RadGridOffice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridOffice As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''RadPageViewWorkloadSelectCDP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageViewWorkloadSelectCDP As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''RadioButtonAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonAll As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''RadioButtonChoose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonChoose As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''PanelCDP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelCDP As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''RadioButtonClient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonClient As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''RadioButtonClientDivision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonClientDivision As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''RadioButtonClientDivisionProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonClientDivisionProduct As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''RadGridClient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridClient As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''RadGridCD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridCD As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''RadGridCDP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridCDP As Global.Telerik.Web.UI.RadGrid
End Class
