'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Reporting_InitialLoadingEmployeeInOutBoard
    
    '''<summary>
    '''RadScriptBlockRadWindow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptBlockRadWindow As Global.Telerik.Web.UI.RadScriptBlock
    
    '''<summary>
    '''RadToolBarDynamicReportInitialLoading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolBarDynamicReportInitialLoading As Global.Telerik.Web.UI.RadToolBar
    
    '''<summary>
    '''RadToolBarSeparatorFirstSeparator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolBarSeparatorFirstSeparator As Global.Telerik.Web.UI.RadToolBarButton
    
    '''<summary>
    '''RadToolBarButtonOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolBarButtonOK As Global.Telerik.Web.UI.RadToolBarButton
    
    '''<summary>
    '''RadToolBarSeparatorSecondSeparator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolBarSeparatorSecondSeparator As Global.Telerik.Web.UI.RadToolBarButton
    
    '''<summary>
    '''RadToolBarButtonCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolBarButtonCancel As Global.Telerik.Web.UI.RadToolBarButton
    
    '''<summary>
    '''RadToolBarSeparatorThirdSeparator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolBarSeparatorThirdSeparator As Global.Telerik.Web.UI.RadToolBarButton
    
    '''<summary>
    '''RadDatePickerStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePickerStart As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''CheckBoxLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxLimit As Global.System.Web.UI.WebControls.CheckBox
End Class
