'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Scheduler_EventTasks

    '''<summary>
    '''RadScriptBlock1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptBlock1 As Global.Telerik.Web.UI.RadScriptBlock

    '''<summary>
    '''RadToolbarEventTasksScheduler control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolbarEventTasksScheduler As Global.Telerik.Web.UI.RadToolBar

    '''<summary>
    '''RadToolBarButtonStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolBarButtonStartDate As Global.Telerik.Web.UI.RadToolBarButton

    '''<summary>
    '''RadToolBarButtonEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolBarButtonEndDate As Global.Telerik.Web.UI.RadToolBarButton

    '''<summary>
    '''RadToolBarButtonRole control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolBarButtonRole As Global.Telerik.Web.UI.RadToolBarButton

    '''<summary>
    '''RadToolbarButtonFindEmployees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolbarButtonFindEmployees As Global.Telerik.Web.UI.RadToolBarButton

    '''<summary>
    '''RadToolbarButtonRefresh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolbarButtonRefresh As Global.Telerik.Web.UI.RadToolBarButton

    '''<summary>
    '''HiddenFieldCurrentRecord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenFieldCurrentRecord As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenFieldMoveDirection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenFieldMoveDirection As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''RadGridEventTasksScheduler control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridEventTasksScheduler As Global.Telerik.Web.UI.RadGrid
End Class
