'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class TimeLine2

    '''<summary>
    '''PrintImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PrintImage As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''pnlJob control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlJob As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''hlJob control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlJob As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''txtJob control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtJob As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnlComponent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlComponent As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''hlJobComp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlJobComp As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''txtJobComp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtJobComp As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnlPeriod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPeriod As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''rbPeriod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbPeriod As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''butRefresh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents butRefresh As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''butClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents butClear As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''dlJobs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dlJobs As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''dgTimeline control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgTimeline As Global.System.Web.UI.WebControls.DataGrid
End Class
