'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Timesheet_CopyFrom

    '''<summary>
    '''RadScriptBlock1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptBlock1 As Global.Telerik.Web.UI.RadScriptBlock

    '''<summary>
    '''RadToolbarCopyFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolbarCopyFrom As Global.Telerik.Web.UI.RadToolBar

    '''<summary>
    '''GetCalendarTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GetCalendarTime As Global.Telerik.Web.UI.RadToolBarButton

    '''<summary>
    '''RadToolCopyTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolCopyTo As Global.Telerik.Web.UI.RadToolTip

    '''<summary>
    '''DivCopyHours control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivCopyHours As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CheckBoxOnlyRT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxOnlyRT As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ButtonGetTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonGetTime As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''RadCalendarCopyToSelectedWeek control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCalendarCopyToSelectedWeek As Global.Telerik.Web.UI.RadCalendar

    '''<summary>
    '''LabelInstruction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelInstruction As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNoTimesheetCopy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoTimesheetCopy As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''MultiViewCopyFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MultiViewCopyFrom As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''ViewMyTimesheets control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ViewMyTimesheets As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''ViewMyProjects control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ViewMyProjects As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''ViewMyTemplate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ViewMyTemplate As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''UpdatePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''DropGroupBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropGroupBy As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''RadGridTimesheetTemplate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridTimesheetTemplate As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''ViewEmployeeTimeStaging control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ViewEmployeeTimeStaging As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''RadGridTimesheetStaging control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridTimesheetStaging As Global.Telerik.Web.UI.RadGrid
End Class
