'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Timesheet_Stopwatch

    '''<summary>
    '''LiteralStartTimer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralStartTimer As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''TrCounter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrCounter As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''ImageButtonStop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonStop As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''LabelJobDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelJobDescription As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TextBoxComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxComment As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TrTimeOver control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrTimeOver As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''LinkButtonClearStopwatch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButtonClearStopwatch As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LinkButtonViewInTimesheet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButtonViewInTimesheet As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''TrButtons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrButtons As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''ButtonCancelStopwatch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonCancelStopwatch As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ButtonViewEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonViewEntry As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ButtonStop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonStop As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''TrNoStopwatch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrNoStopwatch As Global.System.Web.UI.HtmlControls.HtmlTableRow
End Class
