'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class VendorQuote

    '''<summary>
    '''RadScriptBlock1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptBlock1 As Global.Telerik.Web.UI.RadScriptBlock

    '''<summary>
    '''RadScriptBlock4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptBlock4 As Global.Telerik.Web.UI.RadScriptBlock

    '''<summary>
    '''RadToolbarVendorQuote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolbarVendorQuote As Global.Telerik.Web.UI.RadToolBar

    '''<summary>
    '''CollapsableHead control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CollapsableHead As Global.eWorld.UI.CollapsablePanel

    '''<summary>
    '''TxtRFQ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtRFQ As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''hfVendorQteNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfVendorQteNum As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TxtRFQDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtRFQDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RadDatePickerRequestDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePickerRequestDate As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''RadDatePickerDueDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePickerDueDate As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''TxtDescriptionOfProject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtDescriptionOfProject As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ImgBtnComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImgBtnComments As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''RadTabStrip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTabStrip As Global.Telerik.Web.UI.RadTabStrip

    '''<summary>
    '''Tab1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Tab1 As Global.Telerik.Web.UI.RadTab

    '''<summary>
    '''Tab2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Tab2 As Global.Telerik.Web.UI.RadTab

    '''<summary>
    '''pnlVersions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlVersions As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''RadScriptBlock3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptBlock3 As Global.Telerik.Web.UI.RadScriptBlock

    '''<summary>
    '''RadToolbarVersions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolbarVersions As Global.Telerik.Web.UI.RadToolBar

    '''<summary>
    '''RadGridVersions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridVersions As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''pnlVendors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlVendors As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''RadScriptBlock2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptBlock2 As Global.Telerik.Web.UI.RadScriptBlock

    '''<summary>
    '''RadToolbarVendors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolbarVendors As Global.Telerik.Web.UI.RadToolBar

    '''<summary>
    '''RadGridVendors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridVendors As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''RadGridVendorReplies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridVendorReplies As Global.Telerik.Web.UI.RadGrid
End Class
