IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[advtf_media_broadcast_schedule_header]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [dbo].[advtf_media_broadcast_schedule_header]
GO

CREATE FUNCTION [dbo].[advtf_media_broadcast_schedule_header]
(
	@MEDIA_BROADCAST_WORKSHEET_MARKET_ID	VARCHAR(1000) = ''
	,@USE_PRIMARY_DEMO						VARCHAR(10) = ''
	,@HEADER								VARCHAR(100)  = ''
	,@LOCATION_NAME							VARCHAR(100) = ''
	,@VENDOR_FILTER							VARCHAR(MAX) = ''
)
RETURNS 
@ReportHeader TABLE 
(
	MEDIA_BROADCAST_WORKSHEET_ID			INT
	,MEDIA_BROADCAST_WORKSHEET_MARKET_ID	INT
	,DateTypeName							VARCHAR(100)
	,BuyOrder								VARCHAR(200)
	,BuyRevision							INT
	,MARKET_DESC							VARCHAR(200)
	,MARKET_CODE							VARCHAR(200)
	,FilterUsePrimary						INT
	,GROUP1_NAME							VARCHAR(200)
	,GROUP1_ID								INT
	,GROUP2_NAME							VARCHAR(200)
	,GROUP2_ID								INT
	,EstimateComments						VARCHAR(200)
	,Estitmate								VARCHAR(200)
	,Description							VARCHAR(200)
	,ClientName								VARCHAR(200)
	,WorksheetName							VARCHAR(200)
	,HeaderBand								VARCHAR(200)
	,Media									VARCHAR(200)
	,MediaCode								VARCHAR(200)
	,Product								VARCHAR(200)
	,Market									VARCHAR(200)
	,PrimaryDemographic						VARCHAR(200)
	--,Separation								INT
	,StartDate								DATE
	,EndDate								DATE
	,BillingName							VARCHAR(200)
	,BillingAddress1						VARCHAR(200)
	,BillingAddress2						VARCHAR(200)
	,BillingAddressCity						VARCHAR(200)
	,BillingAddressState					VARCHAR(200)
	,BillingAddressZip						VARCHAR(200)
	,BillingPhone							VARCHAR(200)
	,BillingPhoneExtension					VARCHAR(200)
	,BillingFax								VARCHAR(200)
	,BillingFaxExtension					VARCHAR(200)
	,DivisionName							VARCHAR(200)
	,RatingsServiceID						INT
	,SharebookNielsenTVBookID				INT
	,HutputNielsenTVBookID					INT
	,RadioBookID1							INT
	,RadioBookID2							INT
	,RadioBookID3							INT
	,RadioBookID4							INT
	,RadioBookID5							INT
	,BuyerEmpCode							VARCHAR(50)
	,Buyer									VARCHAR(100)
	,VendorName								VARCHAR(50)
	,VendorAddress1							VARCHAR(50)
	,VendorAddress2							VARCHAR(50)
	,VendorAddress3							VARCHAR(50)
	,VendorAddressCity						VARCHAR(50)
	,VendorAddressState						VARCHAR(10)
	,VendorAddressZip						VARCHAR(10)
	,VendorPhone							VARCHAR(20)
	,VendorPhoneExtension					VARCHAR(20)
	,VendorFax								VARCHAR(20)
	,VendorFaxExtension						VARCHAR(20)
	,VendorCode								VARCHAR(20)
	,Survey									VARCHAR(100)
	,SurveyLine2							VARCHAR(100)
	,MediaGroupingID						INT	
	,TRSource1								VARCHAR(100)
	,TRSource2								VARCHAR(100)
	,PageHeaderLogoPathLand					VARCHAR(200)
	,PageHeaderComment						VARCHAR(200)
	,RatingsSource							VARCHAR(100)
	,UsePrimaryDemo							INT
	,IsCable								BIT
	,[Geography]							VARCHAR(100)
	,MediaTypeCode							VARCHAR(10)
	,RadioSource							VARCHAR(20)
	,IsGross								BIT
)
AS
BEGIN
	-- Fill the table variable with the rows for your result set
	DECLARE @PageHeaderLogoPathLand VARCHAR(500)
	DECLARE @PageHeaderComment VARCHAR(500)
	DECLARE @VendorFilterTable AS TABLE (VN_CODE VARCHAR(20))

	SELECT TOP 1
			@PageHeaderLogoPathLand = Location.DFLT_LOGO_PATH_LAND
			,@PageHeaderComment = Location.LOC_HDR
	FROM
		[dbo].[advtf_location_query]() Location
	WHERE 
		Location.LOC_ID = @LOCATION_NAME

	DECLARE @Filter AS TABLE (
		MEDIA_BROADCAST_WORKSHEET_MARKET_ID INT
		,USE_PRIMARY_DEMO	INT)

	INSERT INTO @Filter 
	SELECT 
		WORKSHEET.vint [MEDIA_BROADCAST_WORKSHEET_MARKET_ID]
		,CONVERT(INT,@USE_PRIMARY_DEMO)	[USE_PRIMARY_DEMO]
	FROM
		[dbo].[charlist_to_table_int](@MEDIA_BROADCAST_WORKSHEET_MARKET_ID,',') WORKSHEET
			--INNER JOIN [dbo].[charlist_to_table_int](@USE_PRIMARY_DEMO,',') USEPRIMARYDEMO
			--	ON WORKSHEET.listpos = USEPRIMARYDEMO.listpos
			


    IF (LEN(@VENDOR_FILTER) = 0)
		BEGIN
			INSERT INTO @VendorFilterTable
			SELECT DISTINCT
				MBW_MD.VN_CODE
			FROM 
				MEDIA_BROADCAST_WORKSHEET MBW

					INNER JOIN MEDIA_BROADCAST_WORKSHEET_MARKET MBW_M
						ON MBW.MEDIA_BROADCAST_WORKSHEET_ID = MBW.MEDIA_BROADCAST_WORKSHEET_ID
					INNER JOIN MEDIA_BROADCAST_WORKSHEET_MARKET_DETAIL MBW_MD
						ON MBW_M.MEDIA_BROADCAST_WORKSHEET_MARKET_ID = MBW_MD.MEDIA_BROADCAST_WORKSHEET_MARKET_ID
					INNER JOIN (SELECT 
							MEDIA_BROADCAST_WORKSHEET_MARKET_ID, REVISION_NUMBER = MAX(REVISION_NUMBER) 
						FROM dbo.MEDIA_BROADCAST_WORKSHEET_MARKET_DETAIL
						GROUP BY MEDIA_BROADCAST_WORKSHEET_MARKET_ID) AS MMB_WM 
							ON MMB_WM.MEDIA_BROADCAST_WORKSHEET_MARKET_ID = MBW_MD.MEDIA_BROADCAST_WORKSHEET_MARKET_ID AND MBW_MD.REVISION_NUMBER = MMB_WM.REVISION_NUMBER
					INNER JOIN @Filter HLT
						ON MBW_M.MEDIA_BROADCAST_WORKSHEET_MARKET_ID = HLT.MEDIA_BROADCAST_WORKSHEET_MARKET_ID
			WHERE (1=1)
				AND MBW.IS_INACTIVE = 0
		END
	ELSE
		BEGIN
			INSERT INTO @VendorFilterTable
			SELECT
				VF.vstr
			FROM 
				dbo.charlist_to_table_tsa(@VENDOR_FILTER,',') VF
		END


	DECLARE @BuyOrder VARCHAR(100)

	INSERT INTO @ReportHeader
	SELECT DISTINCT
		MBW.MEDIA_BROADCAST_WORKSHEET_ID
		,MBW_M.MEDIA_BROADCAST_WORKSHEET_MARKET_ID	
		,MBW_DT.NAME
		,''
		,MBW_MD.REVISION_NUMBER
		,CASE 
			WHEN (MBW_M.IS_CABLE = 1) THEN M.MARKET_DESC + ' (Cable)'
			ELSE M.MARKET_DESC
		 END													[MARKET_DESC]
		,MBW_M.MARKET_CODE
		,FILTER.USE_PRIMARY_DEMO
		,M_D.DESCRIPTION									[GROUP1_NAME]
		,M_D.MEDIA_DEMO_ID									[GROUP1_ID]
		,CASE 
			WHEN (FILTER.USE_PRIMARY_DEMO = 1) THEN NULL
			ELSE DEM2BRIDGE_M_D.DESCRIPTION
		 END												[GROUP2_NAME]
		,CASE
			WHEN (FILTER.USE_PRIMARY_DEMO = 1) THEN NULL
			ELSE MBW_M.SECONDARY_MEDIA_DEMO_ID						
		 END												[GROUP2_ID]
		
		,'<BeforePrintCall_EstimateComments>'				[EstimateComments]
		,CONVERT(VARCHAR,MBW.MEDIA_BROADCAST_WORKSHEET_ID)	[Estimate]
		,MBW.NAME											[Description]
		,CL.CL_NAME											[ClientName]
		,MBW.NAME											[WorksheetName]
		,COALESCE(MBW.NAME,'') 
				+'--'+COALESCE(@HEADER,'')					[HeaderBand]
		,SC.SC_DESCRIPTION									[Media]
		,MBW.MEDIA_TYPE_CODE								[MediaCode]
		,COALESCE(P.PRD_DESCRIPTION,'')						[Product]
		,M.MARKET_DESC										[Market]
		,COALESCE(M_D.DESCRIPTION,'')						[PrimaryDemographic]
		--,CONVERT(int,MBW_MD.LENGTH)							[Separation]
		,MBW.START_DATE										[StartDate]
		,MBW.END_DATE										[EndDate]
		,COALESCE(P.PRD_ATTENTION,'')						[BillingName]
		,COALESCE(P.PRD_BILL_ADDRESS1,'')					[BillingAddress1]
		,COALESCE(P.PRD_BILL_ADDRESS2,'')					[BillingAddress2]
		,COALESCE(P.PRD_BILL_CITY,'')						[BillingCity]
		,COALESCE(P.PRD_BILL_STATE,'')						[BillingState]
		,COALESCE(P.PRD_BILL_ZIP,'')						[BillingZip]
		,CASE 
			WHEN ((P.PRD_BILL_TELEPHONE IS NOT NULL) AND (LEN(P.PRD_BILL_TELEPHONE)>1)) THEN '(' + Substring(P.PRD_BILL_TELEPHONE,1,3) + ') ' + Substring(P.PRD_BILL_TELEPHONE,4,3) + '-' + Substring(P.PRD_BILL_TELEPHONE,7,4)
			ELSE ''
			END			AS	[BillingPhone]
		,CASE 
			WHEN ((P.PRD_BILL_EXTENTION IS NOT NULL) AND (LEN(P.PRD_BILL_EXTENTION) >1)) THEN 'Ext. '+P.PRD_BILL_EXTENTION
			ELSE ''
			END			AS	[BillingPhoneExtension]
		,CASE 
			WHEN ((P.PRD_BILL_FAX IS NOT NULL) AND(LEN(P.PRD_BILL_FAX) >1)) THEN '(' + Substring(P.PRD_BILL_FAX,1,3) + ') ' + Substring(P.PRD_BILL_FAX,4,3) + '-' + Substring(P.PRD_BILL_FAX,7,4)
			ELSE ''
			END				AS	[BillingFax]
		,CASE 
			WHEN ((P.PRD_BILL_FAX_EXT IS NOT NULL) AND (LEN(P.PRD_BILL_FAX_EXT)>1))THEN 'Ext. '+P.PRD_BILL_FAX_EXT
			ELSE ''
			END			AS	[BillingFaxExtension]
		,DIV.DIV_NAME								AS	[DivisionName]
		,MBW.RATINGS_SERVICE_ID						AS  [RatingsServiceID]
		,MBW_M.SHAREBOOK_NIELSEN_TV_BOOK_ID			AS  [SharebookNielsenTVBookID]
		,MBW_M.HUTPUT_NIELSEN_TV_BOOK_ID			AS  [HutputNielsenTVBookID]
		,MBW_M.NIELSEN_RADIO_PERIOD_ID1				AS  [RadioBookID1]
		,MBW_M.NIELSEN_RADIO_PERIOD_ID2				AS  [RadioBookID2]

		,MBW_M.NIELSEN_RADIO_PERIOD_ID3				AS  [RadioBookID3]
		,MBW_M.NIELSEN_RADIO_PERIOD_ID4				AS  [RadioBookID4]
		,MBW_M.NIELSEN_RADIO_PERIOD_ID5				AS  [RadioBookID5]

		,MBW_M.BUYER_EMP_CODE
		,E.EMP_FNAME+ ' ' + E.EMP_LNAME			AS	[Buyer]
		,V.VN_NAME									[VendorName]
		,MAX(COALESCE(V.VN_ADDRESS1,''))			[VendorAddress1]
		,COALESCE(V.VN_ADDRESS2,'')				[VendorAddress2]
		,COALESCE(V.VN_ADDRESS3,'')				[VendorAddress3]
		,COALESCE(V.VN_CITY,'')					[VendorCity]
		,COALESCE(V.VN_STATE,'')					[VendorState]
		,COALESCE(V.VN_ZIP,'')					[VendorZip]
		,CASE 
			WHEN ((V.VN_PHONE IS NOT NULL) AND (LEN(V.VN_PHONE)>1)) THEN '(' + Substring(V.VN_PHONE,1,3) + ') ' + Substring(V.VN_PHONE,4,3) + '-' + Substring(V.VN_PHONE,7,4)
			ELSE ''
			END					AS	[VendorPhone]
		,CASE 
			WHEN((V.VN_PHONE_EXT IS NOT NULL) AND (LEN(V.VN_PHONE_EXT)>1)) THEN 'Ext. '+V.VN_PHONE_EXT
			ELSE ''
			END				AS	[VendorPhoneExtension]
		,CASE 
			WHEN ((V.VN_FAX_NUMBER IS NOT NULL) AND (LEN(V.VN_FAX_NUMBER)>1)) THEN '(' + Substring(V.VN_FAX_NUMBER,1,3) + ') ' + Substring(V.VN_FAX_NUMBER,4,3) + '-' + Substring(V.VN_FAX_NUMBER,7,4)
			ELSE ''
			END			AS	[VendorFax]
		,CASE 
			WHEN ((V.VN_FAX_EXTENTION IS NOT NULL) AND (LEN(V.VN_FAX_EXTENTION)>1)) THEN 'Ext. '+V.VN_FAX_EXTENTION
			ELSE ''
			END			AS	[VendorFaxExtension]
		,MBW_MD.VN_CODE									[VendorCode]
		,'<Share Book Info>'							[Survey]
		,'<H/PUT Book Info>'							[SurveyLine2]
		, 0												[MediaGroupingID]
		,CASE 
				WHEN (MBW.MEDIA_TYPE_CODE = 'T') THEN 'Share Book'
				ELSE 'Survey'
			 END [TRSource1]

			 ,CASE 
				WHEN (MBW.MEDIA_TYPE_CODE = 'T') THEN CASE WHEN MBW.RATINGS_SERVICE_ID = 1 THEN 'H/PUT Book' ELSE 'SIU Book' END 
				ELSE ''
			 END [TRSource2]				
		,@PageHeaderLogoPathLand	[PageHeaderLogoPathLand]
		,@PageHeaderComment			[PageHeaderComment]
		,'<Ratings Source>'			[RatingsSource]
		,COALESCE(FILTER.USE_PRIMARY_DEMO,0)	[UsePrimaryDemo]
		,MBW_M.IS_CABLE
		,CASE 
			WHEN (MBW.MEDIA_TYPE_CODE='T') THEN MBW_TVG.NAME
			ELSE MBW_RG.NAME
		END															[Geography]
		,MBW.MEDIA_TYPE_CODE
		,CASE WHEN (MBW_M.EXTERNAL_RADIO_SOURCE = 0) THEN 'Nielsen' ELSE 'Eastlan' END
		,MBW.IS_GROSS
	FROM
		[dbo].[MEDIA_BROADCAST_WORKSHEET] MBW
				LEFT JOIN [dbo].[CLIENT] CL
					ON MBW.CL_CODE = CL.CL_CODE
				LEFT JOIN [dbo].[DIVISION] DIV
					ON MBW.CL_CODE = DIV.CL_CODE
						AND MBW.DIV_CODE = DIV.DIV_CODE
				LEFT JOIN [dbo].[SALES_CLASS] SC
					ON MBW.SC_CODE = SC.SC_CODE
				LEFT JOIN [dbo].[PRODUCT] P
					ON MBW.CL_CODE = P.CL_CODE
						AND MBW.DIV_CODE = P.DIV_CODE
						AND MBW.PRD_CODE = P.PRD_CODE
				LEFT JOIN MEDIA_BROADCAST_WORKSHEET_DATE_TYPE MBW_DT
					ON MBW.MEDIA_BROADCAST_WORKSHEET_DATE_TYPE_ID = MBW_DT.MEDIA_BROADCAST_WORKSHEET_DATE_TYPE_ID
				LEFT OUTER JOIN [dbo].[MEDIA_DEMO] M_D
					ON MBW.PRIMARY_MEDIA_DEMO_ID = M_D.MEDIA_DEMO_ID
				
				INNER JOIN [dbo].[MEDIA_BROADCAST_WORKSHEET_MARKET]MBW_M
					ON MBW.MEDIA_BROADCAST_WORKSHEET_ID = MBW_M.MEDIA_BROADCAST_WORKSHEET_ID
					LEFT JOIN [dbo].[EMPLOYEE] E
						ON MBW_M.BUYER_EMP_CODE = E.EMP_CODE
					LEFT JOIN [dbo].[MEDIA_DEMO] DEM2BRIDGE_M_D
							ON MBW_M.SECONDARY_MEDIA_DEMO_ID = DEM2BRIDGE_M_D.MEDIA_DEMO_ID
				INNER JOIN @Filter FILTER
					ON MBW_M.MEDIA_BROADCAST_WORKSHEET_MARKET_ID = FILTER.MEDIA_BROADCAST_WORKSHEET_MARKET_ID
					INNER JOIN [dbo].[MARKET] M
						ON MBW_M.MARKET_CODE = M.MARKET_CODE
				INNER JOIN [dbo].[MEDIA_BROADCAST_WORKSHEET_MARKET_DETAIL] MBW_MD
					ON MBW_M.MEDIA_BROADCAST_WORKSHEET_MARKET_ID = MBW_MD.MEDIA_BROADCAST_WORKSHEET_MARKET_ID
					INNER JOIN @VendorFilterTable VFT
						ON MBW_MD.VN_CODE = VFT.VN_CODE
					INNER JOIN (SELECT 
							MEDIA_BROADCAST_WORKSHEET_MARKET_ID, REVISION_NUMBER = MAX(REVISION_NUMBER) 
						FROM dbo.MEDIA_BROADCAST_WORKSHEET_MARKET_DETAIL
						GROUP BY MEDIA_BROADCAST_WORKSHEET_MARKET_ID) AS MMB_WM 
							ON MMB_WM.MEDIA_BROADCAST_WORKSHEET_MARKET_ID = MBW_MD.MEDIA_BROADCAST_WORKSHEET_MARKET_ID AND MBW_MD.REVISION_NUMBER = MMB_WM.REVISION_NUMBER
					INNER JOIN [dbo].[VENDOR] V
						ON MBW_MD.VN_CODE = V.VN_CODE
			LEFT JOIN [dbo].[MEDIA_BROADCAST_WORKSHEET_MARKET_TV_GEOGRAPHY] MBW_TVG
				ON MBW_M.MEDIA_BROADCAST_WORKSHEET_MARKET_TV_GEOGRAPHY_ID = MBW_TVG.MEDIA_BROADCAST_WORKSHEET_MARKET_TV_GEOGRAPHY_ID
			LEFT JOIN [dbo].[MEDIA_BROADCAST_WORKSHEET_MARKET_RADIO_GEOGRAPHY] MBW_RG
				ON MBW_M.MEDIA_BROADCAST_WORKSHEET_MARKET_RADIO_GEOGRAPHY_ID = MBW_RG.MEDIA_BROADCAST_WORKSHEET_MARKET_RADIO_GEOGRAPHY_ID
				
	WHERE (1=1)
		--AND MBW.IS_INACTIVE = 0
		--AND DEM2BRIDGE_M_D.MEDIA_DEMO_ID = CASE WHEN (FILTER.USE_PRIMARY_DEMO <> 1) THEN FILTER.SECONDARY_DEMO_ID ELSE DEM2BRIDGE_M_D.MEDIA_DEMO_ID END
	GROUP BY
		MBW.MEDIA_BROADCAST_WORKSHEET_ID
		,MBW_M.MEDIA_BROADCAST_WORKSHEET_MARKET_ID
		,MBW_DT.NAME
		,MBW_MD.REVISION_NUMBER
		,CL.CL_NAME	
		,MBW.NAME	
		,M.MARKET_DESC
		,M.IS_CABLE
		,MBW_M.MARKET_CODE
		,M_D.DESCRIPTION
		,M_D.MEDIA_DEMO_ID	
		,FILTER.USE_PRIMARY_DEMO
		,DEM2BRIDGE_M_D.DESCRIPTION
		,DEM2BRIDGE_M_D.MEDIA_DEMO_ID
		,MBW_M.SECONDARY_MEDIA_DEMO_ID
		,MBW.NAME
		,SC.SC_DESCRIPTION
		,MBW.MEDIA_TYPE_CODE	
		,P.PRD_DESCRIPTION	
		,MBW_MD.LENGTH
		,MBW.START_DATE	
		,MBW.END_DATE
		,P.PRD_ATTENTION
		,P.PRD_BILL_ADDRESS1
		,P.PRD_BILL_ADDRESS2
		,P.PRD_BILL_CITY	
		,P.PRD_BILL_STATE
		,P.PRD_BILL_ZIP
		,P.PRD_BILL_TELEPHONE
		,P.PRD_BILL_EXTENTION
		,P.PRD_BILL_FAX
		,P.PRD_BILL_FAX_EXT
		,DIV.DIV_NAME
		,MBW_M.SHAREBOOK_NIELSEN_TV_BOOK_ID
		,MBW_M.HUTPUT_NIELSEN_TV_BOOK_ID
		,MBW_M.NIELSEN_RADIO_PERIOD_ID1
		,MBW_M.NIELSEN_RADIO_PERIOD_ID2
		,MBW_M.NIELSEN_RADIO_PERIOD_ID3
		,MBW_M.NIELSEN_RADIO_PERIOD_ID4
		,MBW_M.NIELSEN_RADIO_PERIOD_ID5
		,MBW_M.BUYER_EMP_CODE
		,MBW_M.EXTERNAL_RADIO_SOURCE
		,E.EMP_FNAME
		,E.EMP_LNAME
		,MBW.RATINGS_SERVICE_ID
		,CL.CL_ATTENTION
		,V.VN_NAME
		,V.VN_ADDRESS1
		,V.VN_ADDRESS2
		,V.VN_ADDRESS3
		,V.VN_CITY	
		,V.VN_STATE
		,V.VN_ZIP
		,V.VN_PHONE
		,V.VN_PHONE_EXT
		,V.VN_FAX_NUMBER
		,V.VN_FAX_EXTENTION
		,MBW_MD.VN_CODE
		,FILTER.USE_PRIMARY_DEMO
		,MBW_M.IS_CABLE
		,MBW_TVG.NAME
		,MBW_RG.NAME
		,MBW.IS_GROSS
	RETURN 

END