CREATE TABLE [dbo].[CLIENT_ORDER_STATE](
	[CLIENT_ORDER_STATE_ID] [int] IDENTITY(1,1) NOT NULL,
	[CLIENT_ORDER_ID] [int] NOT NULL,
	[STATE] [varchar](2) NOT NULL,
 CONSTRAINT [PK_CLIENT_ORDER_STATE] PRIMARY KEY CLUSTERED ([CLIENT_ORDER_STATE_ID] ASC),
 CONSTRAINT [FK_CLIENT_ORDER_STATE_CLIENT_COUNTY_ORDER] FOREIGN KEY([CLIENT_ORDER_ID]) REFERENCES [dbo].[CLIENT_ORDER] ([CLIENT_ORDER_ID])
);
