CREATE TABLE [dbo].[NCC_TV_FUSION_HUTPUT] (
    [NCC_TV_FUSION_HUTPUT_ID] BIGINT        IDENTITY (1, 1) NOT NULL,
    [NCC_TV_FUSION_UE_ID]     BIGINT        NOT NULL,
    [HUTPUT_DATETIME]         SMALLDATETIME NOT NULL,
    [HOUSEHOLD_HUT]           INT           NOT NULL,
    [CHILDREN_2TO5_PUT]       INT           NOT NULL,
    [CHILDREN_6TO11_PUT]      INT           NOT NULL,
    [MALES_12TO17_PUT]        INT           NOT NULL,
    [MALES_18TO20_PUT]        INT           NOT NULL,
    [MALES_21TO24_PUT]        INT           NOT NULL,
    [MALES_25TO34_PUT]        INT           NOT NULL,
    [MALES_35TO49_PUT]        INT           NOT NULL,
    [MALES_50TO54_PUT]        INT           NOT NULL,
    [MALES_55TO64_PUT]        INT           NOT NULL,
    [MALES_65PLUS_PUT]        INT           NOT NULL,
    [FEMALES_12TO17_PUT]      INT           NOT NULL,
    [FEMALES_18TO20_PUT]      INT           NOT NULL,
    [FEMALES_21TO24_PUT]      INT           NOT NULL,
    [FEMALES_25TO34_PUT]      INT           NOT NULL,
    [FEMALES_35TO49_PUT]      INT           NOT NULL,
    [FEMALES_50TO54_PUT]      INT           NOT NULL,
    [FEMALES_55TO64_PUT]      INT           NOT NULL,
    [FEMALES_65PLUS_PUT]      INT           NOT NULL,
    CONSTRAINT [PK_NCC_TV_FUSION_HUTPUT] PRIMARY KEY CLUSTERED ([NCC_TV_FUSION_HUTPUT_ID] ASC),
	CONSTRAINT [FK_NCC_TV_FUSION_HUTPUT_NCC_TV_FUSION_UNIVERSE] FOREIGN KEY([NCC_TV_FUSION_UE_ID]) REFERENCES [dbo].[NCC_TV_FUSION_UE] ([NCC_TV_FUSION_UE_ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [NCC_TV_FUSION_HUTPUT_UNIQUE]
    ON [dbo].[NCC_TV_FUSION_HUTPUT]([NCC_TV_FUSION_UE_ID] ASC, [HUTPUT_DATETIME] ASC);

