CREATE TABLE [dbo].[NCC_TV_AI_UE] (
    [NCC_TV_AI_UE_ID] BIGINT   IDENTITY (1, 1) NOT NULL,
    [SYSCODE]         SMALLINT NOT NULL,
	[NCC_TV_AI_UE_LOG_ID] INT NOT NULL,
    [STATION_CODE]    INT      NOT NULL,
    [SAMPLE_TYPE]     CHAR (1) NOT NULL,
    [HH_AIUE]         INT      NOT NULL,
    CONSTRAINT [PK_NCC_TV_AI_UE] PRIMARY KEY CLUSTERED ([NCC_TV_AI_UE_ID] ASC),
	CONSTRAINT [FK_NCC_TV_AI_UE_NCC_TV_AI_UE_LOG] FOREIGN KEY([NCC_TV_AI_UE_LOG_ID]) REFERENCES [dbo].[NCC_TV_AI_UE_LOG] ([NCC_TV_AI_UE_LOG_ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [NCC_TV_AI_UE_UNIQUE]
    ON [dbo].[NCC_TV_AI_UE]([SYSCODE] ASC, [NCC_TV_AI_UE_LOG_ID] ASC, [STATION_CODE] ASC);
GO

CREATE NONCLUSTERED INDEX [NCC_TV_AI_UE_NCC_TV_AI_UE_LOG_ID]
    ON [dbo].[NCC_TV_AI_UE]([NCC_TV_AI_UE_LOG_ID] ASC);