CREATE TABLE [dbo].[NCC_TV_CABLENET] (
    [NCC_TV_CABLENET_ID] INT           IDENTITY (1, 1) NOT NULL,
    [NETWORK_CODE]       VARCHAR (4)   NOT NULL,
    [NETWORK_NAME]       VARCHAR (100) NOT NULL,
    [STATION_CODE]       INT           NULL,
    [COMSCORE_STATION_CODE] INT NULL, 
    CONSTRAINT [PK_NCC_TV_CABLENET] PRIMARY KEY CLUSTERED ([NCC_TV_CABLENET_ID] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [NCC_TV_CABLENET_UNIQUE]
    ON [dbo].[NCC_TV_CABLENET]([NETWORK_CODE] ASC);

