CREATE TABLE [dbo].[NIELSEN_TV_HUTPUT] (
    [NIELSEN_TV_HUTPUT_ID] BIGINT        IDENTITY (1, 1) NOT NULL,
    [NIELSEN_TV_BOOK_ID]   INT           NOT NULL,
    [HUTPUT_DATETIME]      SMALLDATETIME NOT NULL,
    [METROA_HOUSEHOLD_HUT] INT           NOT NULL,
    [METROB_HOUSEHOLD_HUT] INT           NOT NULL,
    [HOUSEHOLD_HUT]        INT           NOT NULL,
    [CHILDREN_2TO5_PUT]    INT           NOT NULL,
    [CHILDREN_6TO11_PUT]   INT           NOT NULL,
    [MALES_12TO14_PUT]     INT           NOT NULL,
    [MALES_15TO17_PUT]     INT           NOT NULL,
    [MALES_18TO20_PUT]     INT           NOT NULL,
    [MALES_21TO24_PUT]     INT           NOT NULL,
    [MALES_25TO34_PUT]     INT           NOT NULL,
    [MALES_35TO49_PUT]     INT           NOT NULL,
    [MALES_50TO54_PUT]     INT           NOT NULL,
    [MALES_55TO64_PUT]     INT           NOT NULL,
    [MALES_65PLUS_PUT]     INT           NOT NULL,
    [FEMALES_12TO14_PUT]   INT           NOT NULL,
    [FEMALES_15TO17_PUT]   INT           NOT NULL,
    [FEMALES_18TO20_PUT]   INT           NOT NULL,
    [FEMALES_21TO24_PUT]   INT           NOT NULL,
    [FEMALES_25TO34_PUT]   INT           NOT NULL,
    [FEMALES_35TO49_PUT]   INT           NOT NULL,
    [FEMALES_50TO54_PUT]   INT           NOT NULL,
    [FEMALES_55TO64_PUT]   INT           NOT NULL,
    [FEMALES_65PLUS_PUT]   INT           NOT NULL,
    [WORKING_WOMEN_PUT]    INT           NOT NULL,
    CONSTRAINT [PK_NIELSEN_TV_HUTPUT] PRIMARY KEY CLUSTERED ([NIELSEN_TV_HUTPUT_ID] ASC),
	CONSTRAINT [FK_NIELSEN_TV_HUTPUT_NIELSEN_TV_BOOK] FOREIGN KEY ([NIELSEN_TV_BOOK_ID]) REFERENCES [dbo].[NIELSEN_TV_BOOK] ([NIELSEN_TV_BOOK_ID]),
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [NIELSEN_TV_HUTPUT_UNIQUE]
    ON [dbo].[NIELSEN_TV_HUTPUT]([NIELSEN_TV_BOOK_ID] ASC, [HUTPUT_DATETIME] ASC);

