CREATE TABLE [dbo].[NIELSEN_RADIO_PUR] (
    [NIELSEN_RADIO_PUR_ID]            BIGINT IDENTITY (1, 1) NOT NULL,
    [NIELSEN_RADIO_SEGMENT_PARENT_ID] INT    NOT NULL,
    [NIELSEN_RADIO_SEGMENT_CHILD_ID]  INT    NOT NULL,
    [FEMALES_6TO11_PUR]               INT    NOT NULL,
    [FEMALES_12TO17_PUR]              INT    NOT NULL,
    [FEMALES_18TO20_PUR]              INT    NOT NULL,
    [FEMALES_18TO24_PUR]              INT    NOT NULL,
    [FEMALES_21TO24_PUR]              INT    NOT NULL,
    [FEMALES_25TO34_PUR]              INT    NOT NULL,
    [FEMALES_35TO44_PUR]              INT    NOT NULL,
    [FEMALES_35TO49_PUR]              INT    NOT NULL,
    [FEMALES_45TO49_PUR]              INT    NOT NULL,
    [FEMALES_50TO54_PUR]              INT    NOT NULL,
    [FEMALES_55TO64_PUR]              INT    NOT NULL,
    [FEMALES_65PLUS_PUR]              INT    NOT NULL,
    [MALES_6TO11_PUR]                 INT    NOT NULL,
    [MALES_12TO17_PUR]                INT    NOT NULL,
    [MALES_18TO20_PUR]                INT    NOT NULL,
    [MALES_18TO24_PUR]                INT    NOT NULL,
    [MALES_21TO24_PUR]                INT    NOT NULL,
    [MALES_25TO34_PUR]                INT    NOT NULL,
    [MALES_35TO44_PUR]                INT    NOT NULL,
    [MALES_35TO49_PUR]                INT    NOT NULL,
    [MALES_45TO49_PUR]                INT    NOT NULL,
    [MALES_50TO54_PUR]                INT    NOT NULL,
    [MALES_55TO64_PUR]                INT    NOT NULL,
    [MALES_65PLUS_PUR]                INT    NOT NULL,
    CONSTRAINT [PK_NIELSEN_RADIO_PUR] PRIMARY KEY CLUSTERED ([NIELSEN_RADIO_PUR_ID] ASC),
    CONSTRAINT [FK_NIELSEN_RADIO_PUR_NIELSEN_RADIO_SEGMENT_CHILD] FOREIGN KEY ([NIELSEN_RADIO_SEGMENT_CHILD_ID]) REFERENCES [dbo].[NIELSEN_RADIO_SEGMENT_CHILD] ([NIELSEN_RADIO_SEGMENT_CHILD_ID]),
    CONSTRAINT [FK_NIELSEN_RADIO_PUR_NIELSEN_RADIO_SEGMENT_PARENT] FOREIGN KEY ([NIELSEN_RADIO_SEGMENT_PARENT_ID]) REFERENCES [dbo].[NIELSEN_RADIO_SEGMENT_PARENT] ([NIELSEN_RADIO_SEGMENT_PARENT_ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [NIELSEN_RADIO_PUR_UNIQUE]
    ON [dbo].[NIELSEN_RADIO_PUR]([NIELSEN_RADIO_SEGMENT_PARENT_ID] ASC, [NIELSEN_RADIO_SEGMENT_CHILD_ID] ASC);

