CREATE TABLE [dbo].[NIELSEN_RADIO_PERIOD] (
    [NIELSEN_RADIO_PERIOD_ID]        INT           IDENTITY (1, 1) NOT NULL,
    [NIELSEN_RADIO_REPORT_TYPE_CODE] VARCHAR (2)   NOT NULL,
    [NIELSEN_PERIOD_ID]              INT           NOT NULL,
    [NIELSEN_RADIO_MARKET_NUMBER]    INT           NOT NULL,
    [SHORT_NAME]                     VARCHAR (6)   NOT NULL,
    [NAME]                           VARCHAR (36)  NOT NULL,
    [START_DATE]                     SMALLDATETIME NOT NULL,
    [END_DATE]                       SMALLDATETIME NOT NULL,
    [STANDARD_CONDENSED_INDICATOR]   CHAR (1)      NOT NULL,
    [VALIDATED]                      BIT           NOT NULL,
    [COPYRIGHT]                      VARCHAR (36)  NOT NULL,
    [SOURCE] SMALLINT NOT NULL DEFAULT 0, 
    CONSTRAINT [PK_NIELSEN_RADIO_PERIOD] PRIMARY KEY CLUSTERED ([NIELSEN_RADIO_PERIOD_ID] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [NIELSEN_RADIO_PERIOD_UNIQUE]
    ON [dbo].[NIELSEN_RADIO_PERIOD]([NIELSEN_RADIO_REPORT_TYPE_CODE] ASC, [NIELSEN_PERIOD_ID] ASC, [NIELSEN_RADIO_MARKET_NUMBER] ASC, [SOURCE] ASC);

