CREATE TABLE [dbo].[NIELSEN_RADIO_PERIOD_REVISION] (
    [NIELSEN_RADIO_PERIOD_REVISION_ID] INT IDENTITY (1, 1) NOT NULL,
    [OLD_NIELSEN_RADIO_PERIOD_ID]      INT NOT NULL,
    [NEW_NIELSEN_RADIO_PERIOD_ID]      INT NOT NULL,
    CONSTRAINT [PK_NIELSEN_RADIO_PERIOD_REVISION] PRIMARY KEY CLUSTERED ([NIELSEN_RADIO_PERIOD_REVISION_ID] ASC)
);

