CREATE TABLE [dbo].[NIELSEN_TV_BOOK_REVISION] (
    [NIELSEN_TV_BOOK_REVISION_ID] INT IDENTITY (1, 1) NOT NULL,
    [OLD_NIELSEN_TV_BOOK_ID]      INT NOT NULL,
    [NEW_NIELSEN_TV_BOOK_ID]      INT NOT NULL,
    CONSTRAINT [PK_NIELSEN_TV_BOOK_REVISION] PRIMARY KEY CLUSTERED ([NIELSEN_TV_BOOK_REVISION_ID] ASC)
);

