CREATE TABLE [dbo].[NIELSEN_RADIO_SEGMENT_PARENT] (
    [NIELSEN_RADIO_SEGMENT_PARENT_ID] INT      IDENTITY (1, 1) NOT NULL,
    [NIELSEN_RADIO_PERIOD_ID]         INT      NOT NULL,
    [GEO_INDICATOR]                   SMALLINT NOT NULL,
    [NIELSEN_RADIO_QUALITATIVE_ID]    INT      NOT NULL,
    CONSTRAINT [PK_NIELSEN_RADIO_SEGMENT_PARENT] PRIMARY KEY CLUSTERED ([NIELSEN_RADIO_SEGMENT_PARENT_ID] ASC),
    CONSTRAINT [FK_NIELSEN_RADIO_SEGMENT_PARENT_NIELSEN_RADIO_PERIOD] FOREIGN KEY ([NIELSEN_RADIO_PERIOD_ID]) REFERENCES [dbo].[NIELSEN_RADIO_PERIOD] ([NIELSEN_RADIO_PERIOD_ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [NIELSEN_RADIO_SEGMENT_PARENT_UNIQUE]
    ON [dbo].[NIELSEN_RADIO_SEGMENT_PARENT]([NIELSEN_RADIO_PERIOD_ID] ASC, [GEO_INDICATOR] ASC, [NIELSEN_RADIO_QUALITATIVE_ID] ASC);

