CREATE TABLE [dbo].[NIELSEN_RADIO_MARKET] (
    [NUMBER]                  INT          NOT NULL,
    [NAME]                    VARCHAR (32) NOT NULL,
    [NIELSEN_RADIO_MARKET_ID] INT          IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_NIELSEN_RADIO_MARKET] PRIMARY KEY CLUSTERED ([NUMBER] ASC)
);

