CREATE TABLE [dbo].[NIELSEN_RADIO_DEMOGRAPHIC] (
    [NIELSEN_RADIO_DEMOGRAPHIC_ID] INT          IDENTITY (1, 1) NOT NULL,
    [NUMBER]                       INT          NOT NULL,
    [NAME]                         VARCHAR (50) NOT NULL,
    [AGESEX_CODE]                  VARCHAR (10) NOT NULL,
    [QUALITATIVE_CODE]             VARCHAR (10) NOT NULL,
    CONSTRAINT [PK_NIELSEN_RADIO_DEMOGRAPHIC] PRIMARY KEY CLUSTERED ([NIELSEN_RADIO_DEMOGRAPHIC_ID] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [NIELSEN_RADIO_DEMOGRAPHIC_UNIQUE]
    ON [dbo].[NIELSEN_RADIO_DEMOGRAPHIC]([NUMBER] ASC);

