CREATE TABLE [dbo].[RATINGS_SERVICE] (
    [RATINGS_SERVICE_ID] INT          NOT NULL,
    [NAME]               VARCHAR (20) NOT NULL,
    CONSTRAINT [PK_RATINGS_SERVICE] PRIMARY KEY CLUSTERED ([RATINGS_SERVICE_ID] ASC)
);

