IF NOT EXISTS (SELECT MEDIA_MARKET_BREAK_ID FROM dbo.MEDIA_MARKET_BREAK WHERE MEDIA_MARKET_BREAK_ID = 1)
	INSERT INTO dbo.MEDIA_MARKET_BREAK ([MEDIA_MARKET_BREAK_ID], [BROADCAST_TYPE_ID], [RATINGS_SERVICE_ID], [NAME], [DESCRIPTION], [SHORT_DESCRIPTION]) 
	VALUES (1, 2, 1, 'All PP', 'All Persons', 'All Persons')
