INSERT INTO NCC_TV_LPM_MARKET (NIELSEN_MARKET_NUM) VALUES (124)
INSERT INTO NCC_TV_LPM_MARKET (NIELSEN_MARKET_NUM) VALUES (112)
INSERT INTO NCC_TV_LPM_MARKET (NIELSEN_MARKET_NUM) VALUES (106)
INSERT INTO NCC_TV_LPM_MARKET (NIELSEN_MARKET_NUM) VALUES (117)
INSERT INTO NCC_TV_LPM_MARKET (NIELSEN_MARKET_NUM) VALUES (202)
INSERT INTO NCC_TV_LPM_MARKET (NIELSEN_MARKET_NUM) VALUES (110)
INSERT INTO NCC_TV_LPM_MARKET (NIELSEN_MARKET_NUM) VALUES (223)
INSERT INTO NCC_TV_LPM_MARKET (NIELSEN_MARKET_NUM) VALUES (351)
INSERT INTO NCC_TV_LPM_MARKET (NIELSEN_MARKET_NUM) VALUES (105)
INSERT INTO NCC_TV_LPM_MARKET (NIELSEN_MARKET_NUM) VALUES (218)
INSERT INTO NCC_TV_LPM_MARKET (NIELSEN_MARKET_NUM) VALUES (403)
INSERT INTO NCC_TV_LPM_MARKET (NIELSEN_MARKET_NUM) VALUES (128)
INSERT INTO NCC_TV_LPM_MARKET (NIELSEN_MARKET_NUM) VALUES (213)
INSERT INTO NCC_TV_LPM_MARKET (NIELSEN_MARKET_NUM) VALUES (101)
INSERT INTO NCC_TV_LPM_MARKET (NIELSEN_MARKET_NUM) VALUES (134)
INSERT INTO NCC_TV_LPM_MARKET (NIELSEN_MARKET_NUM) VALUES (104)
INSERT INTO NCC_TV_LPM_MARKET (NIELSEN_MARKET_NUM) VALUES (353)
INSERT INTO NCC_TV_LPM_MARKET (NIELSEN_MARKET_NUM) VALUES (108)
INSERT INTO NCC_TV_LPM_MARKET (NIELSEN_MARKET_NUM) VALUES (420)
INSERT INTO NCC_TV_LPM_MARKET (NIELSEN_MARKET_NUM) VALUES (462)
INSERT INTO NCC_TV_LPM_MARKET (NIELSEN_MARKET_NUM) VALUES (407)
INSERT INTO NCC_TV_LPM_MARKET (NIELSEN_MARKET_NUM) VALUES (419)
INSERT INTO NCC_TV_LPM_MARKET (NIELSEN_MARKET_NUM) VALUES (209)
INSERT INTO NCC_TV_LPM_MARKET (NIELSEN_MARKET_NUM) VALUES (139)
INSERT INTO NCC_TV_LPM_MARKET (NIELSEN_MARKET_NUM) VALUES (111)













