IF NOT EXISTS (SELECT BROADCAST_TYPE_ID FROM BROADCAST_TYPE WHERE BROADCAST_TYPE_ID = 1)
	INSERT [BROADCAST_TYPE] (BROADCAST_TYPE_ID, NAME) VALUES (1, 'Local TV')
IF NOT EXISTS (SELECT BROADCAST_TYPE_ID FROM BROADCAST_TYPE WHERE BROADCAST_TYPE_ID = 2)
	INSERT [BROADCAST_TYPE] (BROADCAST_TYPE_ID, NAME) VALUES (2, 'Network TV')