IF (SELECT COUNT(1) FROM dbo.NIELSEN_RADIO_REPORT_TYPE) = 0 BEGIN
	INSERT INTO dbo.NIELSEN_RADIO_REPORT_TYPE VALUES ('1', 'Radio Market Report (Diary)')
	INSERT INTO dbo.NIELSEN_RADIO_REPORT_TYPE VALUES ('2', 'Ethnic Black (Diary)')
	INSERT INTO dbo.NIELSEN_RADIO_REPORT_TYPE VALUES ('3', 'Ethnic Hispanic (Diary)')
	INSERT INTO dbo.NIELSEN_RADIO_REPORT_TYPE VALUES ('4', 'National (Diary)')
	INSERT INTO dbo.NIELSEN_RADIO_REPORT_TYPE VALUES ('5', 'Standard (PPM)')
	INSERT INTO dbo.NIELSEN_RADIO_REPORT_TYPE VALUES ('6', 'Small Markets (Diary)')
	INSERT INTO dbo.NIELSEN_RADIO_REPORT_TYPE VALUES ('7', 'Ethnic Black (PPM)')
	INSERT INTO dbo.NIELSEN_RADIO_REPORT_TYPE VALUES ('8', 'Ethnic Hispanic (PPM)')
	INSERT INTO dbo.NIELSEN_RADIO_REPORT_TYPE VALUES ('9', 'PPM/Diary Combo Nationwide')
	INSERT INTO dbo.NIELSEN_RADIO_REPORT_TYPE VALUES ('D', 'Meter/Diary DMA')
	INSERT INTO dbo.NIELSEN_RADIO_REPORT_TYPE VALUES ('C', 'Meter/Diary CSAR')
	INSERT INTO dbo.NIELSEN_RADIO_REPORT_TYPE VALUES ('I', 'Integrated Audio Service')
END
