

CREATE PROCEDURE [dbo].[usp_wv_Estimating_Copy_AddEstimateComponent]
(
	@EST_NBR INT,
	@EstNo INT,
	@EstComp INT,
	@EstCompDesc VARCHAR(60),
	@JOB_NUMBER INT,
	@JOB_COMPONENT_NBR INT,
	@CDP_CONTACT_ID INT,
	@EST_COMPONENT_NBR INT OUTPUT
)
AS
BEGIN
	SET NOCOUNT OFF
	DECLARE 
	@ERR INT,
	@NEXT_EST_COMP_NBR INT
	
    SELECT @NEXT_EST_COMP_NBR = ISNULL(MAX(EST_COMPONENT_NBR),0) + 1 FROM ESTIMATE_COMPONENT WHERE ESTIMATE_NUMBER = @EST_NBR 
    
    INSERT INTO [ESTIMATE_COMPONENT]
		(
			[ESTIMATE_NUMBER],
			[EST_COMPONENT_NBR],
			[EST_COMP_DESC],
			[EST_COMP_COMMENT],
			[PRESET_CODE],
			[FNC_SORT_ORDER],
			[MODIFIED_BY],
			[MODIFIED_DATE],
			[CDP_CONTACT_ID],
			[DISPLAY_EMP_TITLE],
			[EST_COMP_COMMENT_HTML]
		)
		SELECT     @EST_NBR, @NEXT_EST_COMP_NBR, @EstCompDesc, EST_COMP_COMMENT, PRESET_CODE, FNC_SORT_ORDER, MODIFIED_BY, MODIFIED_DATE, @CDP_CONTACT_ID, 
                      DISPLAY_EMP_TITLE,EST_COMP_COMMENT_HTML
		FROM       ESTIMATE_COMPONENT
		WHERE     (ESTIMATE_NUMBER = @EstNo) AND (EST_COMPONENT_NBR = @EstComp)

	SET @ERR = @@Error

	--RETURN @ERR
END

IF DATALENGTH(@JOB_NUMBER) > 0 AND DATALENGTH(@JOB_COMPONENT_NBR) > 0
    BEGIN
        EXECUTE usp_wv_Estimating_Update_JobEstimate @JOB_NUMBER,@JOB_COMPONENT_NBR,@EST_NBR,@NEXT_EST_COMP_NBR
    END

SELECT @EST_COMPONENT_NBR = @NEXT_EST_COMP_NBR


