
CREATE PROCEDURE [dbo].[usp_wv_EVENT_GEN_UPDATE] 
		@EVENT_GEN_ID INT,
		@EVENT_GEN_LABEL VARCHAR(50),
		@EVENT_GEN_DESC_LONG TEXT,
		@TYPE VARCHAR(6),
		@START_DATE SMALLDATETIME,
		@END_DATE SMALLDATETIME,
		@START_TIME SMALLDATETIME,
		@END_TIME SMALLDATETIME,
		@OCCUR INT,
		@DAY_INCREMENT INT,
		@DAYS VARCHAR(50),
		@QTY_HOURS DECIMAL(9,2),
		@FNC_CODE VARCHAR(6),
		@AD_NUMBER VARCHAR(30),
		@QTY_TYPE SMALLINT,
		@EVENT_TYPE_ID SMALLINT
AS

	UPDATE EVENT_GEN WITH(ROWLOCK)
	SET
        EVENT_GEN_LABEL = @EVENT_GEN_LABEL,
        EVENT_GEN_DESC_LONG = @EVENT_GEN_DESC_LONG,
        TYPE = @TYPE,
        START_DATE = @START_DATE,
        END_DATE = @END_DATE,
        START_TIME = @START_TIME,
        END_TIME = @END_TIME,
        OCCUR = @OCCUR,
        DAY_INCREMENT = @DAY_INCREMENT,
        DAYS = @DAYS,
        QTY_HOURS = @QTY_HOURS,
        QTY_TYPE = @QTY_TYPE,
        FNC_CODE = @FNC_CODE,
        AD_NUMBER = @AD_NUMBER,
		EVENT_TYPE_ID = @EVENT_TYPE_ID
	WHERE EVENT_GEN.EVENT_GEN_ID = @EVENT_GEN_ID;

