







CREATE PROCEDURE [dbo].[usp_wv_reports_traffic_schedule_GetTasks]
	@Milestone smallint,
	@TaskTemplate varchar(6)

AS

if @TaskTemplate = 'AllT' and @Milestone = 0
Begin
SELECT
	TRF_CODE AS FNC_CODE, TRF_CODE + ' - ' + TRF_DESC AS Description, TRF_INACTIVE, FNC_CODE as Function_Code
FROM
	TRAFFIC_FNC
WHERE
	((TRF_INACTIVE IS NULL) OR (TRF_INACTIVE = 0))	
End

if @TaskTemplate <> 'AllT' and @Milestone = 0
Begin
	SELECT     TRF_PRESET_HDR.TRF_PRESET_CODE, TRF_PRESET_DTL.FNC_CODE, TRF_PRESET_DTL.TRF_PRESET_ORDER, 
						  TRF_PRESET_DTL.MILESTONE
	FROM         TRF_PRESET_HDR INNER JOIN
						  TRF_PRESET_DTL ON TRF_PRESET_HDR.TRF_PRESET_CODE = TRF_PRESET_DTL.TRF_PRESET_CODE INNER JOIN
                      TRAFFIC_FNC ON TRF_PRESET_DTL.FNC_CODE = TRAFFIC_FNC.TRF_CODE
	WHERE     (TRF_PRESET_HDR.TRF_PRESET_CODE = @TaskTemplate) AND ((TRAFFIC_FNC.TRF_INACTIVE IS NULL) OR (TRAFFIC_FNC.TRF_INACTIVE = 0))
	ORDER BY TRF_PRESET_DTL.TRF_PRESET_ORDER
End 

if @TaskTemplate = 'AllT' and @Milestone = 1
Begin
SELECT
	TRF_CODE AS FNC_CODE, TRF_CODE + ' - ' + TRF_DESC AS Description, TRF_INACTIVE, FNC_CODE as Function_Code
FROM
	TRAFFIC_FNC
WHERE
	((TRF_INACTIVE IS NULL) OR (TRF_INACTIVE = 0)) AND MILESTONE = 1
End

if @TaskTemplate <> 'AllT' and @Milestone = 1
Begin
	SELECT     TRF_PRESET_HDR.TRF_PRESET_CODE, TRF_PRESET_DTL.FNC_CODE, TRF_PRESET_DTL.TRF_PRESET_ORDER, 
						  TRF_PRESET_DTL.MILESTONE
	FROM         TRF_PRESET_HDR INNER JOIN
						  TRF_PRESET_DTL ON TRF_PRESET_HDR.TRF_PRESET_CODE = TRF_PRESET_DTL.TRF_PRESET_CODE INNER JOIN
                      TRAFFIC_FNC ON TRF_PRESET_DTL.FNC_CODE = TRAFFIC_FNC.TRF_CODE
	WHERE     (TRF_PRESET_HDR.TRF_PRESET_CODE = @TaskTemplate) AND (TRF_PRESET_DTL.MILESTONE = 1) AND ((TRAFFIC_FNC.TRF_INACTIVE IS NULL) OR (TRAFFIC_FNC.TRF_INACTIVE = 0))
	ORDER BY TRF_PRESET_DTL.TRF_PRESET_ORDER
End













