
CREATE PROCEDURE [dbo].[usp_wv_GetCPProfileData] 
@ClCode as VarChar(6)
AS

if @ClCode <> ''
Begin
	SELECT     CP_BINARY_IMAGES.BINARY_IMAGE_ID, CLIENT.CL_CODE, CLIENT.CL_NAME, 
                      CP_BINARY_IMAGES.BINARY_IMAGE_LOGO, CP_BINARY_IMAGES.BINARY_IMAGE_WP, CP_BINARY_IMAGES.BINARY_IMAGE_WV_WP, CP_BINARY_IMAGES.BINARY_IMAGE_WV_SC,
					  CP_BINARY_IMAGES.BINARY_IMAGE_WV_THEME, CP_BINARY_IMAGES.BINARY_BACKGROUND
	FROM         CP_BINARY_IMAGES RIGHT OUTER JOIN
                      CLIENT ON CP_BINARY_IMAGES.BINARY_IMAGE_CLIENT = CLIENT.CL_CODE
	WHERE     (BINARY_IMAGE_CLIENT = @ClCode)
End
Else
Begin
	SELECT     CP_BINARY_IMAGES.BINARY_IMAGE_ID, CLIENT.CL_CODE, CLIENT.CL_NAME, 
                      CP_BINARY_IMAGES.BINARY_IMAGE_LOGO, CP_BINARY_IMAGES.BINARY_IMAGE_WP, CP_BINARY_IMAGES.BINARY_IMAGE_WV_WP, CP_BINARY_IMAGES.BINARY_IMAGE_WV_SC,
					  CP_BINARY_IMAGES.BINARY_IMAGE_WV_THEME, CP_BINARY_IMAGES.BINARY_BACKGROUND
	FROM         CP_BINARY_IMAGES RIGHT OUTER JOIN
                      CLIENT ON CP_BINARY_IMAGES.BINARY_IMAGE_CLIENT = CLIENT.CL_CODE
	WHERE		ACTIVE_FLAG = 1
End


