
CREATE PROCEDURE [dbo].[usp_wv_RESOURCES_VIEW_LIST] 

AS


	SELECT RESOURCE.RESOURCE_CODE,
		   RESOURCE.RESOURCE_DESC,
		   RESOURCE_TYPE.RESOURCE_TYPE_CODE,
		   RESOURCE_TYPE.RESOURCE_TYPE_DESC,
		   RESOURCE.RESOURCE_CODE+' - '+RESOURCE.RESOURCE_DESC AS RES_DISPLAY
	FROM   RESOURCE WITH(NOLOCK)
		   INNER JOIN RESOURCE_TYPE WITH(NOLOCK)
				ON  RESOURCE.RESOURCE_TYPE_CODE = RESOURCE_TYPE.RESOURCE_TYPE_CODE
	WHERE  (
			   (RESOURCE.INACTIVE_FLAG = 0)
			   OR 
			   (RESOURCE.INACTIVE_FLAG IS NULL)
		   )
		   AND 
		   (
			   (RESOURCE_TYPE.INACTIVE_FLAG = 0)
			   OR 
			   (RESOURCE_TYPE.INACTIVE_FLAG IS NULL)
		   );
		   
		   
