if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[usp_wv_Estimate_getCDPInfo]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [dbo].[usp_wv_Estimate_getCDPInfo]
GO

CREATE PROCEDURE [dbo].[usp_wv_Estimate_getCDPInfo]
@LEVEL varchar(25),
@CLIENT varchar(6),
@DIVISION varchar(6),
@PRODUCT varchar(6),
@CONTACT varchar(6)
AS

if @LEVEL = 'Client' or @LEVEL = 'Division' or @LEVEL = 'Product'
Begin
	if @CLIENT = '' and @DIVISION = '' and @PRODUCT = ''
	Begin
		SELECT     PRODUCT.CL_CODE, CLIENT.CL_NAME, PRODUCT.DIV_CODE, DIVISION.DIV_NAME, PRODUCT.PRD_CODE,PRODUCT.PRD_DESCRIPTION,
					  ISNULL(CL_BADDRESS1,'') AS CL_BADDRESS1, ISNULL(CL_BADDRESS2,'') AS CL_BADDRESS2, ISNULL(CL_BCITY,'') AS CL_BCITY, ISNULL(CL_BSTATE,'') AS CL_BSTATE, ISNULL(CL_BZIP,'') AS CL_BZIP, ISNULL(CL_FOOTER,'') AS CL_FOOTER, ISNULL(CL_ATTENTION,'') AS CL_ATTENTION,
					  ISNULL(CL_BCOUNTRY,'') AS CL_BCOUNTRY, ISNULL(DIVISION.DIV_BADDRESS1,'') AS DIV_BADDRESS1, ISNULL(DIVISION.DIV_BADDRESS2,'') AS DIV_BADDRESS2, 
                      ISNULL(DIVISION.DIV_BCITY,'') AS DIV_BCITY, ISNULL(DIVISION.DIV_BSTATE,'') AS DIV_BSTATE, ISNULL(DIVISION.DIV_BZIP,'') AS DIV_BZIP, ISNULL(CLIENT.CL_FOOTER,'') AS CL_FOOTER, ISNULL(DIVISION.DIV_ATTENTION,'') AS DIV_ATTENTION, ISNULL(DIV_BCOUNTRY,'') AS DIV_BCOUNTRY,
					  ISNULL(PRODUCT.PRD_BILL_ADDRESS1,'') AS PRD_BILL_ADDRESS1, ISNULL(PRODUCT.PRD_BILL_ADDRESS2,'') AS PRD_BILL_ADDRESS2, ISNULL(PRODUCT.PRD_BILL_CITY,'') AS PRD_BILL_CITY, 
                      ISNULL(PRODUCT.PRD_BILL_STATE,'') AS PRD_BILL_STATE, ISNULL(PRODUCT.PRD_BILL_ZIP,'') AS PRD_BILL_ZIP, PRODUCT.PRD_BILL_TELEPHONE, PRODUCT.PRD_BILL_FAX, ISNULL(CLIENT.CL_FOOTER,'') AS CL_FOOTER, ISNULL(PRODUCT.PRD_ATTENTION,'') AS PRD_ATTENTION,
                      ISNULL(USER_DEFINED1, '') AS USER_DEFINED1, ISNULL(USER_DEFINED2, '') AS USER_DEFINED2, ISNULL(PRODUCT.PRD_BILL_COUNTRY,'') AS PRD_BILL_COUNTRY
		FROM         DIVISION INNER JOIN
						  CLIENT ON DIVISION.CL_CODE = CLIENT.CL_CODE INNER JOIN
						  PRODUCT ON DIVISION.CL_CODE = PRODUCT.CL_CODE AND DIVISION.DIV_CODE = PRODUCT.DIV_CODE         
		--WHERE     (PRODUCT.CL_CODE = @CLIENT) AND (PRODUCT.DIV_CODE = @DIVISION) AND (PRODUCT.PRD_CODE = @PRODUCT)
	End
	Else
	Begin
		SELECT     PRODUCT.CL_CODE, CLIENT.CL_NAME, PRODUCT.DIV_CODE, DIVISION.DIV_NAME, PRODUCT.PRD_CODE,PRODUCT.PRD_DESCRIPTION,
					  ISNULL(CL_BADDRESS1,'') AS CL_BADDRESS1, ISNULL(CL_BADDRESS2,'') AS CL_BADDRESS2, ISNULL(CL_BCITY,'') AS CL_BCITY, ISNULL(CL_BSTATE,'') AS CL_BSTATE, ISNULL(CL_BZIP,'') AS CL_BZIP, ISNULL(CL_FOOTER,'') AS CL_FOOTER, ISNULL(CL_ATTENTION,'') AS CL_ATTENTION,
					  ISNULL(CL_BCOUNTRY,'') AS CL_BCOUNTRY, ISNULL(DIVISION.DIV_BADDRESS1,'') AS DIV_BADDRESS1, ISNULL(DIVISION.DIV_BADDRESS2,'') AS DIV_BADDRESS2, 
                      ISNULL(DIVISION.DIV_BCITY,'') AS DIV_BCITY, ISNULL(DIVISION.DIV_BSTATE,'') AS DIV_BSTATE, ISNULL(DIVISION.DIV_BZIP,'') AS DIV_BZIP, ISNULL(CLIENT.CL_FOOTER,'') AS CL_FOOTER, ISNULL(DIVISION.DIV_ATTENTION,'') AS DIV_ATTENTION, ISNULL(DIV_BCOUNTRY,'') AS DIV_BCOUNTRY,
					  ISNULL(PRODUCT.PRD_BILL_ADDRESS1,'') AS PRD_BILL_ADDRESS1, ISNULL(PRODUCT.PRD_BILL_ADDRESS2,'') AS PRD_BILL_ADDRESS2, ISNULL(PRODUCT.PRD_BILL_CITY,'') AS PRD_BILL_CITY, 
                      ISNULL(PRODUCT.PRD_BILL_STATE,'') AS PRD_BILL_STATE, ISNULL(PRODUCT.PRD_BILL_ZIP,'') AS PRD_BILL_ZIP, PRODUCT.PRD_BILL_TELEPHONE, PRODUCT.PRD_BILL_FAX, ISNULL(CLIENT.CL_FOOTER,'') AS CL_FOOTER, ISNULL(PRODUCT.PRD_ATTENTION,'') AS PRD_ATTENTION,
                      ISNULL(USER_DEFINED1, '') AS USER_DEFINED1, ISNULL(USER_DEFINED2, '') AS USER_DEFINED2, ISNULL(PRODUCT.PRD_BILL_COUNTRY,'') AS PRD_BILL_COUNTRY
		FROM         DIVISION INNER JOIN
						  CLIENT ON DIVISION.CL_CODE = CLIENT.CL_CODE INNER JOIN
						  PRODUCT ON DIVISION.CL_CODE = PRODUCT.CL_CODE AND DIVISION.DIV_CODE = PRODUCT.DIV_CODE         
		WHERE     (PRODUCT.CL_CODE = @CLIENT) AND (PRODUCT.DIV_CODE = @DIVISION) AND (PRODUCT.PRD_CODE = @PRODUCT)
	End	
End

if @LEVEL = 'CDP'
Begin
	SELECT     PRODUCT.CL_CODE, CLIENT.CL_NAME, PRODUCT.DIV_CODE, DIVISION.DIV_NAME, PRODUCT.PRD_CODE, 
                      PRODUCT.PRD_DESCRIPTION, ISNULL(PRODUCT.PRD_STATE_ADDR1,'') AS PRD_STATE_ADDR1, ISNULL(PRODUCT.PRD_STATE_ADDR2,'') AS PRD_STATE_ADDR2, ISNULL(PRODUCT.PRD_STATE_CITY,'') AS PRD_STATE_CITY, 
                      ISNULL(PRODUCT.PRD_STATE_STATE,'') AS PRD_STATE_STATE, ISNULL(PRODUCT.PRD_STATE_ZIP,'') AS PRD_STATE_ZIP, PRODUCT.PRD_STATE_TELEPHON, PRODUCT.PRD_STATE_FAX, ISNULL(PRODUCT.PRD_ATTENTION,'') AS PRD_ATTENTION,
                      ISNULL(USER_DEFINED1, '') AS USER_DEFINED1, ISNULL(USER_DEFINED2, '') AS USER_DEFINED2, ISNULL(CL_SADDRESS1,'') AS CL_SADDRESS1, ISNULL(CL_SADDRESS2,'') AS CL_SADDRESS2, ISNULL(CL_SCITY,'') AS CL_SCITY, ISNULL(CL_SSTATE,'') AS CL_SSTATE,
					  ISNULL(CL_SZIP,'') AS CL_SZIP, ISNULL(CL_ATTENTION,'') AS CL_ATTENTION, ISNULL(DIVISION.DIV_SADDRESS1,'') AS DIV_SADDRESS1, ISNULL(DIVISION.DIV_SADDRESS2,'') AS DIV_SADDRESS2, 
                      ISNULL(DIVISION.DIV_SCITY,'') AS DIV_SCITY, ISNULL(DIVISION.DIV_SSTATE,'') AS DIV_SSTATE, ISNULL(DIVISION.DIV_SZIP,'') AS DIV_SZIP, ISNULL(CLIENT.CL_FOOTER,'') AS CL_FOOTER, ISNULL(DIVISION.DIV_ATTENTION,'') AS DIV_ATTENTION,
					  ISNULL(CL_SCOUNTRY,'') AS CL_SCOUNTRY, ISNULL(DIV_SCOUNTRY,'') AS DIV_SCOUNTRY, ISNULL(PRODUCT.PRD_STATE_COUNTRY,'') AS PRD_STATE_COUNTRY
	FROM         DIVISION INNER JOIN
                      CLIENT ON DIVISION.CL_CODE = CLIENT.CL_CODE INNER JOIN
                      PRODUCT ON DIVISION.CL_CODE = PRODUCT.CL_CODE AND DIVISION.DIV_CODE = PRODUCT.DIV_CODE         
	WHERE     (PRODUCT.CL_CODE = @CLIENT) AND (PRODUCT.DIV_CODE = @DIVISION) AND (PRODUCT.PRD_CODE = @PRODUCT)
End        





