

CREATE PROCEDURE [dbo].[usp_wv_Vendor_Quote_UpdateRequest]
(
	@ESTIMATE_NUMBER INT,
	@EST_COMPONENT_NBR SMALLINT,
	@VENDOR_QTE_NBR INT,
	@VENDOR_QTE_DESC VARCHAR(60),
	@VN_QTE_MEMO TEXT,
	@CREATE_DATE SMALLDATETIME,
	@USER_ID VARCHAR(100)
)
AS
BEGIN
	SET NOCOUNT OFF

			UPDATE [VENDOR_QTE_HDR] WITH(ROWLOCK)
	            SET
					[VENDOR_QTE_DESC] = @VENDOR_QTE_DESC,
					[VN_QTE_MEMO] = @VN_QTE_MEMO,
					[CREATE_DATE] = @CREATE_DATE
	           WHERE
		            [ESTIMATE_NUMBER] = @ESTIMATE_NUMBER AND 
		            [EST_COMPONENT_NBR] = @EST_COMPONENT_NBR AND 
		            [VENDOR_QTE_NBR] = @VENDOR_QTE_NBR
	    
				
END





