

CREATE PROCEDURE [dbo].[usp_wv_get_direct_exp_det] 
@startPP	varchar(6),
@endPP	varchar(6),
@invoice varchar(20)
AS

Set NoCount On

DECLARE @sql varchar(4000)
DECLARE @sql_from varchar(4000)
DECLARE @sql_where varchar(4000)


set @sql =  'SELECT AP_HEADER.VN_FRL_EMP_CODE, 
  AP_HEADER.AP_INV_VCHR, 
  JOB_LOG.CL_CODE, JOB_LOG.DIV_CODE, JOB_LOG.PRD_CODE, 
  AP_PRODUCTION.JOB_NUMBER, JOB_LOG.JOB_DESC, AP_PRODUCTION.JOB_COMPONENT_NBR, JOB_COMPONENT.JOB_COMP_DESC, 
  FUNCTIONS.FNC_CODE, FUNCTIONS.FNC_DESCRIPTION, 
  Sum([AP_PROD_EXT_AMT]+[EXT_NONRESALE_TAX]) AS AMT '


set @sql_from =  ' FROM AP_PRODUCTION 
  INNER JOIN GLACCOUNT ON AP_PRODUCTION.GLACODE = GLACCOUNT.GLACODE 
  INNER JOIN FUNCTIONS ON AP_PRODUCTION.FNC_CODE = FUNCTIONS.FNC_CODE 
  INNER JOIN AP_HEADER ON AP_PRODUCTION.AP_SEQ = AP_HEADER.AP_SEQ 
 	AND AP_PRODUCTION.AP_ID = AP_HEADER.AP_ID 
  INNER JOIN JOB_COMPONENT ON AP_PRODUCTION.JOB_COMPONENT_NBR = JOB_COMPONENT.JOB_COMPONENT_NBR 
	AND AP_PRODUCTION.JOB_NUMBER = JOB_COMPONENT.JOB_NUMBER
  INNER JOIN JOB_LOG ON JOB_COMPONENT.JOB_NUMBER = JOB_LOG.JOB_NUMBER '


set @sql_where = ' WHERE AP_PRODUCTION.AP_PROD_NOBILL_FLG = 1
AND AP_PRODUCTION.POST_PERIOD BETWEEN ''' + @startPP + ''' AND ''' + @endPP + '''
AND AP_HEADER.AP_INV_VCHR = ''' + @invoice + ''''


set @sql = @sql + @sql_from + @sql_where

set @sql = @sql + ' GROUP BY AP_HEADER.VN_FRL_EMP_CODE, AP_HEADER.AP_INV_VCHR, JOB_LOG.CL_CODE, JOB_LOG.DIV_CODE, JOB_LOG.PRD_CODE, 
	AP_PRODUCTION.JOB_NUMBER, JOB_LOG.JOB_DESC, AP_PRODUCTION.JOB_COMPONENT_NBR, JOB_COMPONENT.JOB_COMP_DESC, 
	FUNCTIONS.FNC_CODE, FUNCTIONS.FNC_DESCRIPTION '

EXEC(@sql)


