
CREATE PROCEDURE [dbo].[usp_wv_RESOURCES_GET_DETAILS] 
	@RESOURCE_CODE AS VARCHAR(6),
	@EVENT_ID AS INT

AS


DECLARE
	@RESOURCE_TYPE_CODE AS VARCHAR(6),
	@RESOURCE_TYPE_DESC AS VARCHAR(30),
	@RESOURCE_PRIORITY AS SMALLINT,
	@LAST_DATE AS DATETIME,
	@LAST_START_TIME AS DATETIME,
	@LAST_END_TIME AS DATETIME,
	@LAST_AD_NUMBER AS VARCHAR(30),
	@LAST_EVENT_ID AS INT,
	@THIS_EVENT_DATE AS DATETIME,
	@LAST_JOB_NUMBER AS INT,
	@LAST_JOB_COMPONENT_NBR AS SMALLINT
	
	
	
    SELECT 
	    @RESOURCE_PRIORITY = RESOURCE.RESOURCE_PRIORITY,
	    @RESOURCE_TYPE_CODE = RESOURCE_TYPE.RESOURCE_TYPE_CODE,
	    @RESOURCE_TYPE_DESC = RESOURCE_TYPE.RESOURCE_TYPE_DESC
    FROM
	    RESOURCE WITH(NOLOCK)
	    INNER JOIN RESOURCE_TYPE WITH(NOLOCK) ON RESOURCE.RESOURCE_TYPE_CODE = RESOURCE_TYPE.RESOURCE_TYPE_CODE
    WHERE
	    RESOURCE.RESOURCE_CODE = @RESOURCE_CODE;
    	

    IF NOT (@EVENT_ID IS NULL)
	    BEGIN
		    SELECT @THIS_EVENT_DATE = EVENT_DATE FROM EVENT WITH(NOLOCK) WHERE EVENT_ID = @EVENT_ID;
		    SELECT 
			    @LAST_DATE = A.EVENT_DATE,
			    @LAST_START_TIME = A.START_TIME,
			    @LAST_END_TIME = A.END_TIME,
			    @LAST_AD_NUMBER = A.AD_NUMBER,
			    @LAST_EVENT_ID = EVENT_ID
		    FROM
		    (	
		    SELECT     
			    TOP 1 MAX(EVENT_DATE) AS EVENT_DATE, 
			    START_TIME, 
			    END_TIME, 
			    AD_NUMBER, 
			    EVENT_ID,
			    @RESOURCE_PRIORITY AS RESOURCE_PRIORITY,
			    @RESOURCE_TYPE_CODE +' - '+@RESOURCE_TYPE_DESC AS RESOURCE_TYPE
		    FROM         
			    EVENT WITH(NOLOCK)
		    WHERE     
			    (EVENT_ID <> @EVENT_ID) AND EVENT_DATE < @THIS_EVENT_DATE AND RESOURCE_CODE = @RESOURCE_CODE
		    GROUP BY 
			    START_TIME, END_TIME, AD_NUMBER, EVENT_ID
		    ORDER BY 
			    MAX(EVENT_DATE) DESC) AS A;
	    END
    ELSE
	    BEGIN
		    SELECT 
			    @LAST_DATE = A.EVENT_DATE,
			    @LAST_START_TIME = A.START_TIME,
			    @LAST_END_TIME = A.END_TIME,
			    @LAST_AD_NUMBER = A.AD_NUMBER,
			    @LAST_EVENT_ID = EVENT_ID
		    FROM
		    (
		    SELECT     
			    TOP 1 MAX(EVENT_DATE) AS EVENT_DATE, 
			    START_TIME, 
			    END_TIME, 
			    AD_NUMBER, 
			    EVENT_ID
		    FROM         
			    EVENT WITH(NOLOCK)
		    WHERE
			    RESOURCE_CODE = @RESOURCE_CODE	
		    GROUP BY 
			    START_TIME, END_TIME, AD_NUMBER, EVENT_ID
		    ORDER BY 
			    MAX(EVENT_DATE) DESC) AS A;
	    END
	    
    IF NOT (@LAST_EVENT_ID IS NULL)
	    BEGIN
            SELECT @LAST_JOB_NUMBER = JOB_NUMBER, @LAST_JOB_COMPONENT_NBR = JOB_COMPONENT_NBR FROM EVENT WITH(NOLOCK) WHERE EVENT_ID = @LAST_EVENT_ID;
        END	    

	SELECT 
		@RESOURCE_TYPE_CODE +' - '+@RESOURCE_TYPE_DESC AS RESOURCE_TYPE,
		@RESOURCE_PRIORITY AS RESOURCE_PRIORITY,
		@LAST_DATE AS LAST_DATE,
		@LAST_START_TIME AS LAST_START_TIME,
		@LAST_END_TIME AS LAST_END_TIME,
		@LAST_AD_NUMBER AS LAST_AD_NUMBER,
		@LAST_JOB_NUMBER AS LAST_JOB_NUMBER, 
		@LAST_JOB_COMPONENT_NBR AS LAST_JOB_COMPONENT_NBR,
		RIGHT(REPLICATE('0', 6) + CONVERT(VARCHAR(20), 
		@LAST_JOB_NUMBER), 6) + '/' + RIGHT(REPLICATE('0', 2) + CONVERT(VARCHAR(20), @LAST_JOB_COMPONENT_NBR), 2) 
		AS LAST_JOB_AND_COMPONENT,
		@LAST_EVENT_ID AS LAST_EVENT_ID;








