
CREATE PROCEDURE [dbo].[usp_wv_WORKSPACE_DELETE] /*WITH ENCRYPTION*/
	@WORKSPACE_ID INT
AS
/*=========== QUERY ===========*/
	DECLARE
	@NEXT_WORKSPACE_ID INT,
	@USER_CODE VARCHAR(100)
		
	SELECT @USER_CODE = USER_CODE FROM WV_USER_WORKSPACE WITH(NOLOCK) WHERE	WORKSPACE_ID = @WORKSPACE_ID;
	
	SELECT TOP 1 @NEXT_WORKSPACE_ID = WORKSPACE_ID FROM WV_USER_WORKSPACE WITH(NOLOCK) WHERE UPPER(USER_CODE) = UPPER(@USER_CODE) AND WORKSPACE_ID > @WORKSPACE_ID ORDER BY SORT_ORDER, WORKSPACE_ID;
	
	IF @NEXT_WORKSPACE_ID IS NULL
	BEGIN
		SELECT @NEXT_WORKSPACE_ID = MIN(WORKSPACE_ID) FROM WV_USER_WORKSPACE  WITH(NOLOCK) WHERE UPPER(USER_CODE) = UPPER(@USER_CODE);
	END
	
	DELETE FROM WV_USER_QUICK_LAUNCH_APPS WITH(ROWLOCK) WHERE TABNO = @WORKSPACE_ID;
	DELETE FROM WV_USER_QUICK_LAUNCH_REPORTS WITH(ROWLOCK) WHERE TABNO = @WORKSPACE_ID;
	DELETE FROM WV_WORKSPACE_OBJECT WITH(ROWLOCK) WHERE WORKSPACE_ID = @WORKSPACE_ID;
	DELETE FROM WV_USER_WORKSPACE WITH(ROWLOCK) WHERE WORKSPACE_ID = @WORKSPACE_ID;
	
	SELECT ISNULL(@NEXT_WORKSPACE_ID,0);
	--EXEC [dbo].[usp_wv_WORKSPACE_NAVIGATE] @USER_CODE, '+'

/*=========== QUERY ===========*/
