
CREATE PROCEDURE [dbo].[usp_wv_Traffic_Schedule_SaveTask_ContactListString] 
@CONTACT_IDS VARCHAR(2000),
@JOB_NUMBER INT,
@JOB_COMPONENT_NBR INT,
@SEQ_NBR SMALLINT
AS

IF DATALENGTH(@CONTACT_IDS) = 0
    BEGIN
	    DELETE FROM JOB_TRAFFIC_DET_CNTS WHERE (JOB_NUMBER = @JOB_NUMBER) AND (JOB_COMPONENT_NBR = @JOB_COMPONENT_NBR) AND (SEQ_NBR = @SEQ_NBR)
    END
ELSE
	BEGIN
		DECLARE
        @USER_ENTERED TABLE
        (
		CDP_CONTACT_ID INT
        )
        DECLARE
        @TABLE_LIST TABLE
        (
		CDP_CONTACT_ID INT
        )


        DECLARE 

		@CDP_CONTACT_ID INT,
        @POS INT,
		@POS2 INT,
        @IS_IN_TABLE INT,
        @IS_VALID_CONT_CODE INT



        --TEST DATA:
        --SET @EMP_LIST = 'rcs,ama,lmn,wab,jtg,jh,,'
        --SET @JOB_NUMBER = 15
        --SET @JOB_COMPONENT_NBR = 1
        --SET @SEQ_NBR = 1

        --SELECT @DEFAULT_HOURS = JOB_HRS FROM JOB_TRAFFIC_DET WITH(NOLOCK) WHERE (JOB_NUMBER = @JOB_NUMBER) AND (JOB_COMPONENT_NBR = @JOB_COMPONENT_NBR) AND (SEQ_NBR = @SEQ_NBR)


        --GET WHAT'S ALREADY IN REAL TABLE INTO:
        INSERT INTO @TABLE_LIST(CDP_CONTACT_ID)
        SELECT CDP_CONTACT_ID FROM JOB_TRAFFIC_DET_CNTS WITH(NOLOCK) WHERE (JOB_NUMBER = @JOB_NUMBER) AND (JOB_COMPONENT_NBR = @JOB_COMPONENT_NBR) AND (SEQ_NBR = @SEQ_NBR)


        --LOOP THROUGH LIST AND INSERT INTO 
        SET @CONTACT_IDS = LTRIM(RTRIM(@CONTACT_IDS)) + ','		
        SET @POS = CHARINDEX(',',@CONTACT_IDS,1)

        IF REPLACE(@CONTACT_IDS,',','') <> ''
        BEGIN
	        WHILE @POS > 0
		        BEGIN
					SET @CDP_CONTACT_ID = LTRIM(RTRIM(LEFT(@CONTACT_IDS, @POS - 1)))
			        IF @CDP_CONTACT_ID <> ''
			        BEGIN
				        INSERT INTO @USER_ENTERED(CDP_CONTACT_ID) VALUES(@CDP_CONTACT_ID)
			        END
		        SET @CONTACT_IDS = RIGHT(@CONTACT_IDS,LEN(@CONTACT_IDS) - @POS)
		        SET @POS = CHARINDEX(',',@CONTACT_IDS,1)
		        END
        END

        --SELECT * FROM @TABLE_LIST ORDER BY EMP_CODE
        --SELECT * FROM @USER_ENTERED ORDER BY EMP_CODE

        --RECS TO DELETE:
        ----SELECT * FROM @TABLE_LIST WHERE EMP_CODE NOT IN (SELECT * FROM @USER_ENTERED)
        --RECS FOR INSERT:
        ----SELECT * FROM @USER_ENTERED WHERE EMP_CODE NOT IN (SELECT * FROM @TABLE_LIST)

        /* */
        DELETE FROM JOB_TRAFFIC_DET_CNTS WHERE ((JOB_NUMBER = @JOB_NUMBER) AND (JOB_COMPONENT_NBR = @JOB_COMPONENT_NBR) AND (SEQ_NBR = @SEQ_NBR))
        AND JOB_TRAFFIC_DET_CNTS.CDP_CONTACT_ID IN (SELECT CDP_CONTACT_ID DATABASE_DEFAULT FROM @TABLE_LIST WHERE CDP_CONTACT_ID NOT IN (SELECT CDP_CONTACT_ID DATABASE_DEFAULT FROM @USER_ENTERED))

        INSERT INTO JOB_TRAFFIC_DET_CNTS WITH(ROWLOCK)(JOB_NUMBER, JOB_COMPONENT_NBR, SEQ_NBR, CDP_CONTACT_ID)
        SELECT @JOB_NUMBER, @JOB_COMPONENT_NBR, @SEQ_NBR, CDP_CONTACT_ID FROM @USER_ENTERED WHERE CDP_CONTACT_ID NOT IN (SELECT * FROM @TABLE_LIST)

	END





