
CREATE PROCEDURE [dbo].[usp_wv_WORKSPACE_ADD] /*WITH ENCRYPTION*/
	@USER_CODE VARCHAR(100),
	@WORKSPACE_NAME VARCHAR(50)
AS
/*=========== QUERY ===========*/
	DECLARE @REC_COUNT   INT,
			@SORT_ORDER  INT

	SET @SORT_ORDER = 0;
		
	SELECT @REC_COUNT = ISNULL(COUNT(1), 0)
	FROM   WV_USER_WORKSPACE WITH(NOLOCK)
	WHERE  UPPER(NAME) = UPPER(@WORKSPACE_NAME)
		   AND UPPER(USER_CODE) = UPPER(@USER_CODE);
       
	SELECT @SORT_ORDER = ISNULL(MAX(SORT_ORDER), 0)
	FROM   WV_USER_WORKSPACE WITH(NOLOCK)
	WHERE  UPPER(USER_CODE) = UPPER(@USER_CODE);

	IF @REC_COUNT IS NULL
	BEGIN
		SET @REC_COUNT = 0;
	END
	IF @SORT_ORDER IS NULL
	BEGIN
		SET @SORT_ORDER = 0;
	END

	SET @SORT_ORDER = @SORT_ORDER + 1;

    DECLARE @ROWID INT;
	SET @ROWID = 0;

	IF @REC_COUNT = 0
	BEGIN
		INSERT INTO WV_USER_WORKSPACE WITH
		  (
			ROWLOCK
		  )(USER_CODE, NAME, [DESCRIPTION], SORT_ORDER)
		VALUES
		  (
			@USER_CODE,
			@WORKSPACE_NAME,
			@WORKSPACE_NAME,
			@SORT_ORDER
		  );
		SELECT @ROWID = SCOPE_IDENTITY();
		SET @ROWID = ISNULL(@ROWID,0);

		IF @ROWID > 0 
		BEGIN
			DELETE FROM APP_VARS WITH(ROWLOCK) WHERE [APPLICATION] = 'MY_SETTINGS' AND VARIABLE_NAME = 'CURRENT_WORKSPACE' AND UPPER(USERID) = UPPER(@USER_CODE);
			INSERT INTO APP_VARS WITH
			  (
				ROWLOCK
			  )(
				   USERID,
				   [APPLICATION],
				   VARIABLE_GROUP,
				   VARIABLE_NAME,
				   VARIABLE_TYPE,
				   VARIABLE_ORDER,
				   VARIABLE_VALUE
			   )
			VALUES
			  (
				@USER_CODE,
				'MY_SETTINGS',
				0,
				'CURRENT_WORKSPACE',
				'String',
				NULL,
				@ROWID
			  );

		END

	END	

	DECLARE @RTN INT;
	IF @REC_COUNT > 0
	BEGIN
		SET @RTN = -1;
	END
	IF @ROWID > 0
	BEGIN
		SET @RTN = @ROWID;
	END

	SELECT ISNULL(@RTN,0)
/*=========== QUERY ===========*/
