IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[usp_wv_Estimating_Copy_AddEstimate]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
DROP PROCEDURE [dbo].[usp_wv_Estimating_Copy_AddEstimate]
GO

CREATE PROCEDURE [dbo].[usp_wv_Estimating_Copy_AddEstimate]
(
	@EstNo INT,
	@EST_LOG_DESC VARCHAR(60),
	@CLIENT VARCHAR(6),
	@DIVISION VARCHAR(6),
	@PRODUCT VARCHAR(6),
	@SALES_CLASS VARCHAR(6),
	@MARKUP_PCT DECIMAL(7,3),
	@USER_ID VARCHAR(100),
	@CMP_IDENTIFIER INT,
	@EST_NUM INT OUTPUT,
	@CREATE_DATE SMALLDATETIME

)
AS
BEGIN
	SET NOCOUNT OFF
	
	DECLARE 
	@ERR INT,
	@NEXT_EST_NBR INT
	
    --SELECT @NEXT_EST_NBR = ISNULL(MAX(ESTIMATE_NUMBER),-1) + 1 FROM ESTIMATE_LOG 
    SELECT    @NEXT_EST_NBR = LAST_NBR + 1
    FROM         ASSIGN_NBR
    WHERE     (COLUMNNAME = 'EST_NUMBER')
    
    INSERT INTO [ESTIMATE_LOG]
		(
			[ESTIMATE_NUMBER],
			[CL_CODE],
			[DIV_CODE],
			[PRD_CODE],
			[CMP_CODE],
			[SC_CODE],
			[EST_MARKUP_PCT],
			[USER_ID],
			[EST_CREATE_DATE],
			[EST_LOG_COMMENT],
			[EST_LOG_DESC],
			[CMP_IDENTIFIER],
			[CMP_LINE_NBR],
			[EST_LOG_COMMENT_HTML]
		)
		SELECT  @NEXT_EST_NBR, @CLIENT, @DIVISION, @PRODUCT, NULL, @SALES_CLASS, @MARKUP_PCT, @USER_ID, @CREATE_DATE, EST_LOG_COMMENT, 
                      @EST_LOG_DESC, @CMP_IDENTIFIER, NULL, EST_LOG_COMMENT_HTML
		FROM    ESTIMATE_LOG
		WHERE  (ESTIMATE_NUMBER = @EstNo)

	
	SET @ERR = @@Error

	--RETURN @ERR
END


    
If @NEXT_EST_NBR > 0
    BEGIN
        Update ASSIGN_NBR
        Set LAST_NBR = @NEXT_EST_NBR
        WHERE     (COLUMNNAME = 'EST_NUMBER')
    END


SELECT @EST_NUM = @NEXT_EST_NBR;