
CREATE PROCEDURE [dbo].[usp_wv_dd_GetResources] 

AS

		SELECT     RESOURCE.RESOURCE_CODE, RESOURCE.RESOURCE_DESC, RESOURCE.RESOURCE_PRIORITY, RESOURCE_TYPE.RESOURCE_TYPE_CODE, 
							  RESOURCE_TYPE.RESOURCE_TYPE_DESC
		FROM         RESOURCE WITH(NOLOCK) INNER JOIN
							  RESOURCE_TYPE WITH(NOLOCK) ON RESOURCE.RESOURCE_TYPE_CODE = RESOURCE_TYPE.RESOURCE_TYPE_CODE
		WHERE     (RESOURCE.INACTIVE_FLAG IS NULL OR RESOURCE.INACTIVE_FLAG = 0) 
					AND (RESOURCE_TYPE.INACTIVE_FLAG IS NULL OR RESOURCE_TYPE.INACTIVE_FLAG = 0)
		ORDER BY RESOURCE_TYPE.RESOURCE_TYPE_CODE ASC, RESOURCE.RESOURCE_CODE ASC;


