

CREATE PROCEDURE [dbo].[usp_wv_Vendor_GetContact]
(
	@Vendor varchar(6),
	@Contact varchar(6),
	@UserID varchar(100)
)
AS
Declare @Restrictions Int,
		@sql nvarchar(4000),
		@paramlist nvarchar(4000)

Select @Restrictions = Count(*) 
FROM SEC_CLIENT
WHERE UPPER(USER_ID) = UPPER(@UserID)


SELECT   VENDOR.VN_CODE, VENDOR.VN_NAME, VEN_CONT.VC_CODE, ISNULL(VEN_CONT.VC_FNAME,'') AS VC_FNAME, ISNULL(VEN_CONT.VC_MI,'') AS VC_MI, ISNULL(VEN_CONT.VC_TITLE,'') AS VC_TITLE,
                      ISNULL(VEN_CONT.VC_LNAME,'') AS VC_LNAME, ISNULL(VEN_CONT.EMAIL_ADDRESS,'') AS EMAIL_ADDRESS, ISNULL(VEN_CONT.VC_ADDRESS1,'') AS VC_ADDRESS1, ISNULL(VEN_CONT.VC_ADDRESS2,'') AS VC_ADDRESS2, 
                      ISNULL(VEN_CONT.VC_CITY,'') AS VC_CITY, ISNULL(VEN_CONT.VC_COUNTY,'') AS VC_COUNTY, ISNULL(VEN_CONT.VC_STATE,'') AS VC_STATE, ISNULL(VEN_CONT.VC_ZIP,'') AS VC_ZIP,
					  ISNULL(VEN_CONT.VC_COUNTRY,'') AS VC_COUNTRY, ISNULL(VEN_CONT.VC_TELEPHONE,'') AS VC_TELEPHONE, ISNULL(VEN_CONT.VC_EXTENTION,'') AS VC_EXTENTION,
					  ISNULL(VEN_CONT.VC_PHONE_CELL,'') AS VC_PHONE_CELL, ISNULL(VEN_CONT.VC_FAX,'') AS VC_FAX, ISNULL(VEN_CONT.VC_FAX_EXTENTION,'') AS VC_FAX_EXTENTION
FROM     VEN_CONT LEFT OUTER JOIN
                      VENDOR ON VEN_CONT.VN_CODE = VENDOR.VN_CODE
WHERE     (VENDOR.VN_CODE = @Vendor) AND (VEN_CONT.VC_CODE = @Contact)




