
CREATE PROCEDURE [dbo].[usp_wv_LOOKUP_PRD_HAS_ONE_DIV_AND_CL] /*WITH ENCRYPTION*/
@PRD_CODE  VARCHAR(6)
AS
/*=========== QUERY ===========*/
	DECLARE @CT        INT

	SELECT @CT = COUNT(1)
	FROM   CLIENT WITH(NOLOCK)
		   INNER JOIN DIVISION WITH(NOLOCK)
				ON  CLIENT.CL_CODE = DIVISION.CL_CODE
		   INNER JOIN PRODUCT WITH(NOLOCK)
				ON  DIVISION.CL_CODE = PRODUCT.CL_CODE
				AND DIVISION.DIV_CODE = PRODUCT.DIV_CODE
	WHERE  PRODUCT.PRD_CODE = @PRD_CODE;
	
	SET @CT = ISNULL(@CT, 0);

	IF @CT = 1
	BEGIN
		SELECT 1 AS HAS_ONE_CLIENT,
			   CLIENT.CL_CODE,
			   CLIENT.CL_NAME,
			   DIVISION.DIV_CODE,
			   DIVISION.DIV_NAME,
			   PRODUCT.PRD_CODE,
			   PRODUCT.PRD_DESCRIPTION
		FROM   CLIENT WITH(NOLOCK)
			   INNER JOIN DIVISION WITH(NOLOCK)
					ON  CLIENT.CL_CODE = DIVISION.CL_CODE
			   INNER JOIN PRODUCT WITH(NOLOCK)
					ON  DIVISION.CL_CODE = PRODUCT.CL_CODE
					AND DIVISION.DIV_CODE = PRODUCT.DIV_CODE
		WHERE  PRODUCT.PRD_CODE = @PRD_CODE;
	END
	ELSE
	BEGIN
		SELECT 0 AS HAS_ONE_CLIENT,
			   NULL AS CL_CODE,
			   NULL AS CL_NAME,
			   NULL AS DIV_CODE,
			   NULL AS DIV_NAME,
			   NULL AS PRD_CODE,
			   NULL AS PRD_DESCRIPTION;
	END
/*=========== QUERY ===========*/
