if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[usp_wv_EVENT_DISTINCT_AD_NUMS_BY_DATE]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [dbo].[usp_wv_EVENT_DISTINCT_AD_NUMS_BY_DATE]
GO

CREATE PROCEDURE [dbo].[usp_wv_EVENT_DISTINCT_AD_NUMS_BY_DATE] /*WITH ENCRYPTION*/
@START_DATE SMALLDATETIME,
@END_DATE SMALLDATETIME
AS
/*=========== QUERY ===========*/
	SET @START_DATE = CONVERT(
			DATETIME,
			CONVERT(CHAR(10), DATEPART(yyyy, @START_DATE), 101) 
			+
			'-' +
			CONVERT(CHAR(10), DATEPART(mm, @START_DATE), 101) +
			'-' +
			CONVERT(CHAR(10), DATEPART(dd, @START_DATE), 101) +
			' 00:00:00'
		) 
	
	SET @END_DATE = CONVERT(
			DATETIME,
			CONVERT(CHAR(10), DATEPART(yyyy, @END_DATE), 101) 
			+
			'-' +
			CONVERT(CHAR(10), DATEPART(mm, @END_DATE), 101) +
			'-' +
			CONVERT(CHAR(10), DATEPART(dd, @END_DATE), 101) +
			' 23:59:00'
		) 


	SELECT DISTINCT 
		   ISNULL(EVENT.AD_NUMBER, '[None]') AS AD_NUMBER,
		   ISNULL(AD_NUMBER.AD_NBR + ' - ' + AD_NUMBER.AD_NBR_DESC, '[None]') AS 
		   AD_NBR_DESC
	FROM   EVENT WITH (NOLOCK)
		   LEFT OUTER JOIN AD_NUMBER
				ON  EVENT.AD_NUMBER = AD_NUMBER.AD_NBR
	WHERE EVENT.EVENT_DATE BETWEEN @START_DATE AND @END_DATE
	ORDER BY AD_NUMBER, AD_NBR_DESC;

/*=========== QUERY ===========*/
GO
SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO