

/***************************************************************************************
Webvantage
This Stored Procedure retrieves a campaign
21-Jan-2010 - jtg - Created

****************************************************************************************/
CREATE PROCEDURE [dbo].[usp_wv_get_campaign_by_code] 
	@CmpCode	VARCHAR(6)
AS

SELECT ISNULL(CAMPAIGN.OFFICE_CODE, '') AS OFFICE_CODE, ISNULL(OFFICE_NAME, '') AS OFFICE_DESC,
	CAMPAIGN.CL_CODE, ISNULL(CLIENT.CL_NAME, '') AS CL_DESC,
	ISNULL(CAMPAIGN.DIV_CODE,'') AS DIV_CODE, ISNULL(DIVISION.DIV_NAME, '') AS DIV_DESC,
	ISNULL(CAMPAIGN.PRD_CODE,'') AS PRD_CODE, ISNULL(PRODUCT.PRD_DESCRIPTION,'') AS PRD_DESC,
	CMP_CODE, 
	ISNULL(CMP_BEG_DATE, '') AS CMP_BEG_DATE,
	ISNULL(CMP_END_DATE, '') AS  CMP_END_DATE,
	CMP_NAME, 
	ISNULL(CMP_DIRECT, 0) AS CMP_DIRECT,
	ISNULL(CMP_MAGAZINE, 0) AS CMP_MAGAZINE,
	ISNULL(CMP_NEWSPAPER, 0) AS CMP_NEWSPAPER,
	ISNULL(CMP_OUTDOOR, 0) AS CMP_OUTDOOR,
	ISNULL(CMP_PRINT_COLL, 0) AS CMP_PRINT_COLL,
	ISNULL(CMP_RADIO, 0) AS CMP_RADIO,
	ISNULL(CMP_TELEVISION, 0) AS CMP_TELEVISION,
	ISNULL(CMP_OTHER, 0) AS CMP_OTHER,
	ISNULL(CMP_OTHER_EXPLAIN,'') AS CMP_OTHER_EXPLAIN, CMP_IDENTIFIER, 
	ISNULL(CMP_CLOSED, 0) AS CMP_CLOSED,
	ISNULL(CMP_BILL_BUDGET, 0) AS CMP_BILL_BUDGET,
	ISNULL(CMP_INC_BUDGET, 0) AS CMP_INC_BUDGET,
	CMP_TYPE, 
	ISNULL(CMP_COMMENTS,'') AS CMP_COMMENTS,
	ISNULL(ALERT_GROUP, '') AS ALERT_GROUP,
	ISNULL(CMP_INTERNET, 0) AS CMP_INTERNET

FROM CAMPAIGN
  INNER JOIN CLIENT ON CAMPAIGN.CL_CODE = CLIENT.CL_CODE
  LEFT OUTER JOIN DIVISION ON CAMPAIGN.CL_CODE = DIVISION.CL_CODE AND CAMPAIGN.DIV_CODE = DIVISION.DIV_CODE
  LEFT OUTER JOIN PRODUCT ON CAMPAIGN.CL_CODE = PRODUCT.CL_CODE AND CAMPAIGN.DIV_CODE = PRODUCT.DIV_CODE AND CAMPAIGN.PRD_CODE = PRODUCT.PRD_CODE
  LEFT OUTER JOIN OFFICE ON CAMPAIGN.OFFICE_CODE = OFFICE.OFFICE_CODE

WHERE CMP_CODE = @CmpCode



