if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[usp_wv_Estimating_Quote_Copy_Function]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [dbo].[usp_wv_Estimating_Quote_Copy_Function]
GO


CREATE PROCEDURE [dbo].[usp_wv_Estimating_Quote_Copy_Function] 
@EstNo Int,
@EstCompNo Int,
@QuoteNo Int,
@RevNo Int,
@SeqNo Int
AS
    DECLARE 
	@ERR INT,
	@NEXT_SEQ_NBR INT
		 
    SELECT @NEXT_SEQ_NBR = ISNULL(MAX(SEQ_NBR),-1) + 1 FROM ESTIMATE_REV_DET
	WHERE ESTIMATE_NUMBER = @EstNo AND EST_COMPONENT_NBR = @EstCompNo  AND EST_QUOTE_NBR = @QuoteNo AND EST_REV_NBR = @RevNo
			

INSERT INTO [ESTIMATE_REV_DET]
		(
		   [ESTIMATE_NUMBER]
		  ,[EST_COMPONENT_NBR]
		  ,[EST_QUOTE_NBR]
		  ,[EST_REV_NBR]
		  ,[SEQ_NBR]
		  ,[FNC_CODE]
		  ,[EST_REV_COMM_PCT]
		  ,[EST_REV_CONT_PCT]
		  ,[EST_REV_QUANTITY]
		  ,[EST_REV_RATE]
		  ,[EST_REV_SUP_BY_CDE]
		  ,[EST_REV_SUP_BY_NTE]
		  ,[EST_REV_EXT_AMT]
		  ,[TAX_CODE]
		  ,[EST_FNC_COMMENT]
		  ,[TAX_STATE_PCT]
		  ,[TAX_COUNTY_PCT]
		  ,[TAX_CITY_PCT]
		  ,[TAX_COMM]
		  ,[TAX_COMM_ONLY]
		  ,[TAX_RESALE]
		  ,[EXT_MARKUP_AMT]
		  ,[EXT_NONRESALE_TAX]
		  ,[EXT_STATE_RESALE]
		  ,[EXT_COUNTY_RESALE]
		  ,[EXT_CITY_RESALE]
		  ,[EXT_CONTINGENCY]
		  ,[EXT_MU_CONT]
		  ,[EXT_STATE_CONT]
		  ,[EXT_COUNTY_CONT]
		  ,[EXT_CITY_CONT]
		  ,[EXT_NR_CONT]
		  ,[LINE_TOTAL_CONT]
		  ,[LINE_TOTAL]
		  ,[EST_CPM_FLAG]
		  ,[EST_FNC_TYPE]
		  ,[EST_COMM_FLAG]
		  ,[EST_TAX_FLAG]
		  ,[EST_NONBILL_FLAG]
		  ,[INCL_CPU]
		  ,[FEE_TIME]
		  ,[EMPLOYEE_TITLE_ID]
		  ,[EST_PHASE_ID]
		  ,[EST_PHASE_DESC]
		  ,[EST_FNC_COMMENT_HTML]
		  ,[EST_REV_SUP_BY_HTML]
		)
SELECT     ESTIMATE_QUOTE.ESTIMATE_NUMBER, ESTIMATE_QUOTE.EST_COMPONENT_NBR, ESTIMATE_QUOTE.EST_QUOTE_NBR, 
                      ESTIMATE_REV.EST_REV_NBR, @NEXT_SEQ_NBR, ESTIMATE_REV_DET.FNC_CODE, ESTIMATE_REV_DET.EST_REV_COMM_PCT,
				      ESTIMATE_REV_DET.EST_REV_CONT_PCT, ESTIMATE_REV_DET.EST_REV_QUANTITY, ESTIMATE_REV_DET.EST_REV_RATE, 
					  ESTIMATE_REV_DET.EST_REV_SUP_BY_CDE, ESTIMATE_REV_DET.EST_REV_SUP_BY_NTE,   
                      ESTIMATE_REV_DET.EST_REV_EXT_AMT, ESTIMATE_REV_DET.TAX_CODE, ESTIMATE_REV_DET.EST_FNC_COMMENT,
					  ESTIMATE_REV_DET.TAX_STATE_PCT, ESTIMATE_REV_DET.TAX_COUNTY_PCT, ESTIMATE_REV_DET.TAX_CITY_PCT, ESTIMATE_REV_DET.TAX_COMM, ESTIMATE_REV_DET.TAX_COMM_ONLY, 
                      ESTIMATE_REV_DET.TAX_RESALE, ESTIMATE_REV_DET.EXT_MARKUP_AMT, ESTIMATE_REV_DET.EXT_NONRESALE_TAX, ESTIMATE_REV_DET.EXT_STATE_RESALE, 
                      ESTIMATE_REV_DET.EXT_COUNTY_RESALE, ESTIMATE_REV_DET.EXT_CITY_RESALE,
                      ESTIMATE_REV_DET.EXT_CONTINGENCY, ESTIMATE_REV_DET.EXT_MU_CONT, ESTIMATE_REV_DET.EXT_STATE_CONT, ESTIMATE_REV_DET.EXT_COUNTY_CONT, ESTIMATE_REV_DET.EXT_CITY_CONT, 
                      ESTIMATE_REV_DET.EXT_NR_CONT, ESTIMATE_REV_DET.LINE_TOTAL_CONT, ESTIMATE_REV_DET.LINE_TOTAL, ESTIMATE_REV_DET.EST_CPM_FLAG, 
					  ESTIMATE_REV_DET.EST_FNC_TYPE, ESTIMATE_REV_DET.EST_COMM_FLAG, ESTIMATE_REV_DET.EST_TAX_FLAG, ESTIMATE_REV_DET.EST_NONBILL_FLAG, ESTIMATE_REV_DET.INCL_CPU,  
		              ESTIMATE_REV_DET.FEE_TIME, ESTIMATE_REV_DET.EMPLOYEE_TITLE_ID, ESTIMATE_REV_DET.EST_PHASE_ID, ESTIMATE_REV_DET.EST_PHASE_DESC,
					  ESTIMATE_REV_DET.EST_FNC_COMMENT_HTML, ESTIMATE_REV_DET.EST_REV_SUP_BY_HTML
FROM         ESTIMATE_QUOTE INNER JOIN
                      ESTIMATE_REV ON ESTIMATE_QUOTE.ESTIMATE_NUMBER = ESTIMATE_REV.ESTIMATE_NUMBER AND 
                      ESTIMATE_QUOTE.EST_COMPONENT_NBR = ESTIMATE_REV.EST_COMPONENT_NBR AND 
                      ESTIMATE_QUOTE.EST_QUOTE_NBR = ESTIMATE_REV.EST_QUOTE_NBR INNER JOIN
                      ESTIMATE_COMPONENT ON ESTIMATE_QUOTE.ESTIMATE_NUMBER = ESTIMATE_COMPONENT.ESTIMATE_NUMBER AND 
                      ESTIMATE_QUOTE.EST_COMPONENT_NBR = ESTIMATE_COMPONENT.EST_COMPONENT_NBR INNER JOIN
                      ESTIMATE_LOG ON ESTIMATE_COMPONENT.ESTIMATE_NUMBER = ESTIMATE_LOG.ESTIMATE_NUMBER INNER JOIN
                      ESTIMATE_REV_DET ON ESTIMATE_REV.ESTIMATE_NUMBER = ESTIMATE_REV_DET.ESTIMATE_NUMBER AND 
                      ESTIMATE_REV.EST_COMPONENT_NBR = ESTIMATE_REV_DET.EST_COMPONENT_NBR AND 
                      ESTIMATE_REV.EST_QUOTE_NBR = ESTIMATE_REV_DET.EST_QUOTE_NBR AND 
                      ESTIMATE_REV.EST_REV_NBR = ESTIMATE_REV_DET.EST_REV_NBR INNER JOIN
                      FUNCTIONS ON ESTIMATE_REV_DET.FNC_CODE = FUNCTIONS.FNC_CODE LEFT OUTER JOIN
                      JOB_COMPONENT ON ESTIMATE_COMPONENT.ESTIMATE_NUMBER = JOB_COMPONENT.ESTIMATE_NUMBER AND 
                      ESTIMATE_COMPONENT.EST_COMPONENT_NBR = JOB_COMPONENT.EST_COMPONENT_NBR
WHERE     (ESTIMATE_QUOTE.ESTIMATE_NUMBER = @EstNo) AND (ESTIMATE_QUOTE.EST_COMPONENT_NBR = @EstCompNo) AND 
                      (ESTIMATE_QUOTE.EST_QUOTE_NBR = @QuoteNo) AND (ESTIMATE_REV.EST_REV_NBR = @RevNo) AND (ESTIMATE_REV_DET.SEQ_NBR = @SeqNo)
ORDER BY ESTIMATE_REV_DET.SEQ_NBR





















