
CREATE PROCEDURE [dbo].[usp_wv_EVENT_GET_DETAILS] 
	@EVENT_ID INTEGER

AS
    
    DECLARE
        @JOB_NUMBER AS INT,
        @JOB_COMPONENT_NBR AS SMALLINT
        
--EVENT HEADER
SELECT     EVENT.EVENT_ID, EVENT.EVENT_LABEL, EVENT.EVENT_DESC_LONG, EVENT.TYPE, EVENT.EVENT_DATE, EVENT.ALL_DAY, EVENT.QTY_HRS, 
                      ISNULL(EVENT.QTY_TYPE, 1) AS QTY_TYPE, EVENT.START_TIME, EVENT.END_TIME, EVENT.RESOURCE_CODE, EVENT.JOB_NUMBER, 
                      EVENT.JOB_COMPONENT_NBR, EVENT.FNC_CODE, EVENT.AD_NUMBER, EVENT.EVENT_COMMENT, EVENT.INCOME_ONLY_ID, 
                      EVENT.EVENT_GEN_ID, EVENT.CREATE_DATE, EVENT.CREATE_USER, EVENT.MODIFY_DATE, EVENT.MODIFY_USER, 
                      FUNCTIONS.FNC_DESCRIPTION, FUNCTIONS.FNC_CODE + ISNULL(' - ' + FUNCTIONS.FNC_DESCRIPTION, '') AS FNC_CODE_DESC, 
                      AD_NUMBER.AD_NBR_DESC, AD_NUMBER.COLOR AS AD_NBR_COLOR, JOB_LOG.JOB_DESC, JOB_COMPONENT.JOB_COMP_DESC,
                      RIGHT(REPLICATE('0', 6) + CONVERT(VARCHAR(20), 
					JOB_COMPONENT.JOB_NUMBER), 6) + '-' + RIGHT(REPLICATE('0', 3) + CONVERT(VARCHAR(20), JOB_COMPONENT.JOB_COMPONENT_NBR), 3) 
					+ '  ' + ISNULL(JOB_LOG.JOB_DESC, '') + ' / ' + ISNULL(JOB_COMPONENT.JOB_COMP_DESC, '') AS JOB_AND_COMP,EVENT.EVENT_TYPE_ID
FROM         EVENT WITH (NOLOCK) LEFT OUTER JOIN
                      JOB_COMPONENT WITH (NOLOCK) ON EVENT.JOB_NUMBER = JOB_COMPONENT.JOB_NUMBER AND 
                      EVENT.JOB_COMPONENT_NBR = JOB_COMPONENT.JOB_COMPONENT_NBR LEFT OUTER JOIN
                      JOB_LOG WITH (NOLOCK) ON EVENT.JOB_NUMBER = JOB_LOG.JOB_NUMBER LEFT OUTER JOIN
                      AD_NUMBER WITH (NOLOCK) ON EVENT.AD_NUMBER = AD_NUMBER.AD_NBR LEFT OUTER JOIN
                      FUNCTIONS WITH (NOLOCK) ON EVENT.FNC_CODE = FUNCTIONS.FNC_CODE
WHERE     (EVENT.EVENT_ID = @EVENT_ID);
    
--RELATED EVENTS:
    SELECT 
           @JOB_NUMBER = EVENT.JOB_NUMBER,
           @JOB_COMPONENT_NBR = EVENT.JOB_COMPONENT_NBR
    FROM   [EVENT] WITH (NOLOCK)
    WHERE  EVENT.EVENT_ID = @EVENT_ID;
    
    SELECT     
           EVENT_ID, EVENT_LABEL, EVENT_DESC_LONG, EVENT_DATE, ALL_DAY, QTY_HRS, START_TIME, END_TIME
    FROM         
           [EVENT] WITH (NOLOCK)
    WHERE     
           EVENT.JOB_NUMBER = @JOB_NUMBER 
           AND EVENT.JOB_COMPONENT_NBR = @JOB_COMPONENT_NBR
           AND EVENT.EVENT_ID <> @EVENT_ID;



--THE EVENT'S TASKS:                          
    SELECT 
        EVENT_TASK.EVENT_TASK_ID,
        EVENT_TASK.EVENT_ID,
        EVENT_TASK.TASK_CODE,
        EVENT_TASK.EMP_CODE,
        EVENT_TASK.START_DATE,
        EVENT_TASK.END_DATE,
        EVENT_TASK.START_TIME,
        EVENT_TASK.END_TIME,
        EVENT_TASK.TEMP_COMP_DATE,
        EVENT_TASK.HOURS_ALLOWED,
        EVENT_TASK.COMMENTS,
        EVENT_TASK.COMPLETED_COMMENTS	
    FROM   EVENT_TASK WITH (NOLOCK)
           LEFT OUTER JOIN EMPLOYEE WITH (NOLOCK)
                ON  EVENT_TASK.EMP_CODE = EMPLOYEE.EMP_CODE
    WHERE  EVENT_TASK.EVENT_ID = @EVENT_ID;



