

CREATE PROCEDURE [dbo].[usp_wv_Vendor_Quote_GetRequestVendorReplies]
(
	@EstNo Int,
	@EstCompNo Int,
	@VendorQteNo Int,
	@UserID varchar(100)
)
AS
Declare @Restrictions Int,
		@sql nvarchar(4000),
		@paramlist nvarchar(4000)

Select @Restrictions = Count(*) 
FROM SEC_CLIENT
WHERE UPPER(USER_ID) = UPPER(@UserID)


SELECT     VENDOR_QTE_HDR.ESTIMATE_NUMBER, VENDOR_QTE_HDR.EST_COMPONENT_NBR, VENDOR_QTE_HDR.VENDOR_QTE_NBR, 
                      VENDOR_QTE_DTL.EST_QUOTE_NBR, VENDOR_QTE_DTL.EST_REV_NBR, ESTIMATE_QUOTE.EST_QUOTE_DESC, 
                      VENDOR_QTE_DTL.EST_FNC_CODE, FUNCTIONS.FNC_DESCRIPTION, VENDOR_QTE_DTL.QTY, VENDOR_QTE_DTL.VN_CODE, 
                      VENDOR.VN_NAME, VENDOR_QTE_DTL.REPLY_RATE, VENDOR_QTE_DTL.REPLY_AMT, VENDOR_QTE_DTL.REPLY_NOTES, 
                      VENDOR_QTE_DTL.APPROVED_FLAG, VENDOR_QTE_DTL.APPROVED_BY, VENDOR_QTE_DTL.APPROVAL_NOTES
FROM         VENDOR_QTE_HDR INNER JOIN
                      VENDOR_QTE_DTL ON VENDOR_QTE_HDR.ESTIMATE_NUMBER = VENDOR_QTE_DTL.ESTIMATE_NUMBER AND 
                      VENDOR_QTE_HDR.EST_COMPONENT_NBR = VENDOR_QTE_DTL.EST_COMPONENT_NBR AND 
                      VENDOR_QTE_HDR.VENDOR_QTE_NBR = VENDOR_QTE_DTL.VENDOR_QTE_NBR INNER JOIN
                      VENDOR_QTE_VEN ON VENDOR_QTE_DTL.ESTIMATE_NUMBER = VENDOR_QTE_VEN.ESTIMATE_NUMBER AND 
                      VENDOR_QTE_DTL.EST_COMPONENT_NBR = VENDOR_QTE_VEN.EST_COMPONENT_NBR AND 
                      VENDOR_QTE_DTL.VENDOR_QTE_NBR = VENDOR_QTE_VEN.VENDOR_QTE_NBR AND 
                      VENDOR_QTE_DTL.VN_CODE = VENDOR_QTE_VEN.VN_CODE LEFT OUTER JOIN
                      VENDOR ON VENDOR_QTE_DTL.VN_CODE = VENDOR.VN_CODE LEFT OUTER JOIN
                      FUNCTIONS ON VENDOR_QTE_DTL.EST_FNC_CODE = FUNCTIONS.FNC_CODE LEFT OUTER JOIN
                      ESTIMATE_QUOTE ON VENDOR_QTE_DTL.ESTIMATE_NUMBER = ESTIMATE_QUOTE.ESTIMATE_NUMBER AND 
                      VENDOR_QTE_DTL.EST_COMPONENT_NBR = ESTIMATE_QUOTE.EST_COMPONENT_NBR AND 
                      VENDOR_QTE_DTL.EST_QUOTE_NBR = ESTIMATE_QUOTE.EST_QUOTE_NBR
WHERE     (VENDOR_QTE_HDR.ESTIMATE_NUMBER = @EstNo) AND (VENDOR_QTE_HDR.EST_COMPONENT_NBR = @EstCompNo) AND (VENDOR_QTE_HDR.VENDOR_QTE_NBR = @VendorQteNo)
ORDER BY VENDOR_QTE_DTL.EST_QUOTE_NBR, VENDOR_QTE_DTL.VN_CODE, VENDOR_QTE_DTL.EST_FNC_CODE



