
CREATE PROCEDURE [dbo].[usp_wv_WV_DESK_TMPLT_HDR_UPDATE_QUICK_LAUNCH] 
	@USER_CODE VARCHAR(100),
	@WV_TMPLT_HDR_ID INT


AS

        DECLARE
	        @QL_APPS VARCHAR(4000),
	        @QL_RPTS VARCHAR(4000)


        SET @QL_APPS = ''
        SET @QL_RPTS = ''

        EXEC usp_wv_WV_DESK_TMPLT_CLEAN_QUICK_LAUNCH @USER_CODE;

        --BUILD STRING FOR TEMPLATE FIELD: QUICK_LAUNCH
        SELECT @QL_APPS = @QL_APPS +  'A,'+CAST(TABNO AS VARCHAR(10)) + ','+CAST(APPID AS VARCHAR(10))+'|' FROM WV_USER_QUICK_LAUNCH_APPS WITH(NOLOCK) WHERE UPPER(USERID) = UPPER(@USER_CODE);
        IF (LEN(@QL_APPS) > 1)
        BEGIN
	        SELECT @QL_APPS = SUBSTRING(@QL_APPS,1,LEN(@QL_APPS)-1);
        END	
        SELECT @QL_RPTS = @QL_RPTS +  'R,'+CAST(TABNO AS VARCHAR(10)) + ','+CAST(REPORTID AS VARCHAR(10))+'|' FROM WV_USER_QUICK_LAUNCH_REPORTS WITH(NOLOCK) WHERE UPPER(USERID) = UPPER(@USER_CODE);
        IF (LEN(@QL_RPTS) > 1)
        BEGIN
	        SELECT @QL_RPTS = SUBSTRING(@QL_RPTS,1,LEN(@QL_RPTS)-1);
        END	

        --SELECT @QL_APPS+@QL_RPTS;
        --UPDATE WV_DESK_TMPLT_HDR WITH(ROWLOCK)
        --SET
	    --    QUICK_LAUNCH = @QL_APPS+@QL_RPTS
        --WHERE
	    --   WV_DESK_TMPLT_HDR.WV_TMPLT_HDR_ID = @WV_TMPLT_HDR_ID;	
	
	
