CREATE PROCEDURE [dbo].[usp_wv_DocumentManager_DeleteExpenseDetailDocument]
@DOCUMENT_ID INT,
@INV_NBR INT,
@EXPDETAILID INT,
@ROWID INT
AS

	DELETE EXPENSE_DETAIL_DOCS WHERE DOCUMENT_ID = @DOCUMENT_ID AND EXPDETAILID = @EXPDETAILID AND ROWID=@ROWID
    DELETE EXPENSE_DOCS WHERE DOCUMENT_ID = @DOCUMENT_ID AND INV_NBR = @INV_NBR
    DELETE DOCUMENTS WHERE DOCUMENT_ID = @DOCUMENT_ID