IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[usp_wv_dto_tasks]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
DROP PROCEDURE [dbo].[usp_wv_dto_tasks]
GO

/*****************************************************************
Webvantage Desktop 
Modication Description / Date / Developer
=============================================
This Stored Procedure gets Tasks   / 01-16-04 / Steve Moreno
Modified To handle new tables with multiple employees for tasks /05-21-08/ ATC
Modified to handle task level documents / 04-15-15 / TAP
******************************************************************/
CREATE PROCEDURE [dbo].[usp_wv_dto_tasks] 
@UserID Varchar(100),
@EmpCode Varchar(6),
@StartDate Datetime,
@TaskStatus Varchar(10) = '',
@TaskShow as Varchar(10),
@Search as Varchar(500),
@CP as int,
@CPID as int
AS

DECLARE @Rescrictions INT, @SqlStmt VARCHAR(MAX), @HAS_TASK_SQL AS SMALLINT, @RestrictionsCP Int
SET @SqlStmt = ''
SET @HAS_TASK_SQL = 0
SELECT @Rescrictions = Count(*) FROM SEC_CLIENT WHERE UPPER(USER_ID) = UPPER(@UserID);

Select @RestrictionsCP = Count(*) 
FROM CP_SEC_CLIENT
Where CDP_CONTACT_ID = @CPID

SET @SqlStmt = @SqlStmt + 'SELECT A.* FROM('

IF RTRIM(LTRIM(@TaskStatus)) = '' --ALL
OR LEFT(RTRIM(LTRIM(@TaskStatus)), 1 ) = 'P' 
OR LEFT(RTRIM(LTRIM(@TaskStatus)), 1 ) = 'A' 
OR LEFT(RTRIM(LTRIM(@TaskStatus)), 1 ) = 'H' 
OR LEFT(RTRIM(LTRIM(@TaskStatus)), 1 ) = 'L' 
BEGIN
IF @CP = 1
	BEGIN
		IF @RestrictionsCP > 0
			SET @SqlStmt =  @SqlStmt + N'
			     SELECT JOB_LOG.CL_CODE + ''/'' + JOB_LOG.DIV_CODE + ''/'' + JOB_LOG.PRD_CODE as CDP,  
					( RIGHT(REPLICATE(''0'', 6) + CONVERT(VARCHAR(20), JOB_LOG.JOB_NUMBER),6) + ''/'' + RIGHT(REPLICATE(''0'', 2) + CONVERT(VARCHAR(20), JOB_COMPONENT.JOB_COMPONENT_NBR),2) + '' - '' + JOB_COMPONENT.JOB_COMP_DESC ) as JobData, 
					
					
					isnull(JOB_TRAFFIC_DET.TASK_DESCRIPTION, '''') as Task, 
					JOB_TRAFFIC_DET.FNC_COMMENTS,
					JOB_TRAFFIC_DET.TASK_START_DATE as StartDate,
					JOB_TRAFFIC_DET.JOB_REVISED_DATE as DueDate, 
					ISNULL(JOB_TRAFFIC_DET.REVISED_DUE_TIME,'''') as DueTime, 
					JOB_TRAFFIC_DET.JOB_NUMBER as JobNo, 
					JOB_TRAFFIC_DET.JOB_COMPONENT_NBR as JobComp, 
					JOB_TRAFFIC_DET.JOB_HRS as HoursAllowed,
					JOB_TRAFFIC_DET.SEQ_NBR as SeqNo,
					JOB_TRAFFIC_DET.TEMP_COMP_DATE as TempCompleteDate, JOB_TRAFFIC_DET.EMP_CODE as EmpCode, 0 AS IS_EVENT, -1 AS EVENT_TASK_ID, ISNULL(JOB_TRAFFIC_DET.TASK_STATUS,''P'') AS TASK_STATUS,
					JOB_LOG.JOB_DESC, JOB_COMPONENT.JOB_COMP_DESC, (RIGHT(REPLICATE(''0'', 6) + CONVERT(VARCHAR(20), JOB_LOG.JOB_NUMBER),6) + ''/'' + RIGHT(REPLICATE(''0'', 2) + CONVERT(VARCHAR(20), JOB_COMPONENT.JOB_COMPONENT_NBR),2)) as JOB_COMP,
					[HAS_DOCUMENTS] = CONVERT(BIT, CASE WHEN JOB_TRAFFIC_DET_DOCS.JOB_NUMBER IS NOT NULL THEN 1 ELSE 0 END)
				   FROM JOB_LOG	
				 INNER JOIN CLIENT ON CLIENT.CL_CODE = JOB_LOG.CL_CODE INNER JOIN JOB_COMPONENT ON JOB_LOG.JOB_NUMBER = JOB_COMPONENT.JOB_NUMBER
				 INNER JOIN JOB_TRAFFIC_DET ON JOB_COMPONENT.JOB_NUMBER = JOB_TRAFFIC_DET.JOB_NUMBER AND JOB_COMPONENT.JOB_COMPONENT_NBR = JOB_TRAFFIC_DET.JOB_COMPONENT_NBR
				 INNER JOIN JOB_TRAFFIC ON JOB_COMPONENT.JOB_NUMBER = JOB_TRAFFIC.JOB_NUMBER AND JOB_COMPONENT.JOB_COMPONENT_NBR = JOB_TRAFFIC.JOB_COMPONENT_NBR 
				 INNER JOIN CP_SEC_CLIENT ON JOB_LOG.CL_CODE = CP_SEC_CLIENT.CL_CODE AND JOB_LOG.DIV_CODE = CP_SEC_CLIENT.DIV_CODE AND JOB_LOG.PRD_CODE = CP_SEC_CLIENT.PRD_CODE
				 INNER JOIN JOB_TRAFFIC_DET_CNTS ON JOB_TRAFFIC_DET_CNTS.JOB_NUMBER = JOB_TRAFFIC_DET.JOB_NUMBER AND JOB_TRAFFIC_DET_CNTS.JOB_COMPONENT_NBR = JOB_TRAFFIC_DET.JOB_COMPONENT_NBR 
					AND JOB_TRAFFIC_DET_CNTS.SEQ_NBR = JOB_TRAFFIC_DET.SEQ_NBR
				 LEFT OUTER JOIN (SELECT JOB_NUMBER, JOB_COMPONENT_NBR, SEQ_NBR FROM dbo.JOB_TRAFFIC_DET_DOCS GROUP BY JOB_NUMBER, JOB_COMPONENT_NBR, SEQ_NBR) JOB_TRAFFIC_DET_DOCS ON JOB_TRAFFIC_DET.JOB_NUMBER = JOB_TRAFFIC_DET_DOCS.JOB_NUMBER 
					AND JOB_TRAFFIC_DET.JOB_COMPONENT_NBR = JOB_TRAFFIC_DET_DOCS.JOB_COMPONENT_NBR 
					AND JOB_TRAFFIC_DET.SEQ_NBR = JOB_TRAFFIC_DET_DOCS.SEQ_NBR
				  WHERE (NOT (JOB_COMPONENT.JOB_PROCESS_CONTRL IN (6, 12)))	AND (CP_SEC_CLIENT.CDP_CONTACT_ID = ''' + CAST(@CPID AS VARCHAR(6)) + ''')
					AND (JOB_TRAFFIC_DET_CNTS.CDP_CONTACT_ID = ''' + CAST(@CPID AS VARCHAR(6)) + ''') AND JOB_TRAFFIC_DET.JOB_COMPLETED_DATE IS NULL AND JOB_TRAFFIC.COMPLETED_DATE IS NULL '

		ELSE
			SET @SqlStmt =  @SqlStmt + N'
			     SELECT JOB_LOG.CL_CODE + ''/'' + JOB_LOG.DIV_CODE + ''/'' + JOB_LOG.PRD_CODE as CDP,  
					( RIGHT(REPLICATE(''0'', 6) + CONVERT(VARCHAR(20), JOB_LOG.JOB_NUMBER),6) + ''/'' + RIGHT(REPLICATE(''0'', 2) + CONVERT(VARCHAR(20), JOB_COMPONENT.JOB_COMPONENT_NBR),2) + '' - '' + JOB_COMPONENT.JOB_COMP_DESC ) as JobData, 
					isnull(JOB_TRAFFIC_DET.TASK_DESCRIPTION, '''') as Task, 
					JOB_TRAFFIC_DET.FNC_COMMENTS,
					JOB_TRAFFIC_DET.TASK_START_DATE as StartDate, 		
					JOB_TRAFFIC_DET.JOB_REVISED_DATE as DueDate, 
					ISNULL(JOB_TRAFFIC_DET.REVISED_DUE_TIME,'''') as DueTime, 
					JOB_TRAFFIC_DET.JOB_NUMBER as JobNo, 
					JOB_TRAFFIC_DET.JOB_COMPONENT_NBR as JobComp, 			
					JOB_TRAFFIC_DET.JOB_HRS as HoursAllowed, 
					JOB_TRAFFIC_DET.SEQ_NBR as SeqNo,
					JOB_TRAFFIC_DET.TEMP_COMP_DATE as TempCompleteDate, JOB_TRAFFIC_DET.EMP_CODE as EmpCode, 0 AS IS_EVENT, -1 AS EVENT_TASK_ID, ISNULL(JOB_TRAFFIC_DET.TASK_STATUS,''P'') AS TASK_STATUS,
					JOB_LOG.JOB_DESC, JOB_COMPONENT.JOB_COMP_DESC, (RIGHT(REPLICATE(''0'', 6) + CONVERT(VARCHAR(20), JOB_LOG.JOB_NUMBER),6) + ''/'' + RIGHT(REPLICATE(''0'', 2) + CONVERT(VARCHAR(20), JOB_COMPONENT.JOB_COMPONENT_NBR),2)) as JOB_COMP,
					[HAS_DOCUMENTS] = CONVERT(BIT, CASE WHEN JOB_TRAFFIC_DET_DOCS.JOB_NUMBER IS NOT NULL THEN 1 ELSE 0 END)
	    			   FROM JOB_LOG 
				 INNER JOIN CLIENT ON CLIENT.CL_CODE = JOB_LOG.CL_CODE INNER JOIN JOB_COMPONENT ON JOB_LOG.JOB_NUMBER = JOB_COMPONENT.JOB_NUMBER 
				 INNER JOIN JOB_TRAFFIC_DET ON JOB_COMPONENT.JOB_NUMBER = JOB_TRAFFIC_DET.JOB_NUMBER AND JOB_COMPONENT.JOB_COMPONENT_NBR = JOB_TRAFFIC_DET.JOB_COMPONENT_NBR
				 INNER JOIN JOB_TRAFFIC ON JOB_COMPONENT.JOB_NUMBER = JOB_TRAFFIC.JOB_NUMBER AND JOB_COMPONENT.JOB_COMPONENT_NBR = JOB_TRAFFIC.JOB_COMPONENT_NBR 
				 INNER JOIN JOB_TRAFFIC_DET_CNTS ON JOB_TRAFFIC_DET_CNTS.JOB_NUMBER = JOB_TRAFFIC_DET.JOB_NUMBER AND JOB_TRAFFIC_DET_CNTS.JOB_COMPONENT_NBR = JOB_TRAFFIC_DET.JOB_COMPONENT_NBR 
					AND JOB_TRAFFIC_DET_CNTS.SEQ_NBR = JOB_TRAFFIC_DET.SEQ_NBR
				 LEFT OUTER JOIN (SELECT JOB_NUMBER, JOB_COMPONENT_NBR, SEQ_NBR FROM dbo.JOB_TRAFFIC_DET_DOCS GROUP BY JOB_NUMBER, JOB_COMPONENT_NBR, SEQ_NBR) JOB_TRAFFIC_DET_DOCS ON JOB_TRAFFIC_DET.JOB_NUMBER = JOB_TRAFFIC_DET_DOCS.JOB_NUMBER 
					AND JOB_TRAFFIC_DET.JOB_COMPONENT_NBR = JOB_TRAFFIC_DET_DOCS.JOB_COMPONENT_NBR 
					AND JOB_TRAFFIC_DET.SEQ_NBR = JOB_TRAFFIC_DET_DOCS.SEQ_NBR  
	 			  WHERE (NOT (JOB_COMPONENT.JOB_PROCESS_CONTRL IN (6, 12))) AND (JOB_TRAFFIC_DET_CNTS.CDP_CONTACT_ID = ''' + CAST(@CPID AS VARCHAR(6)) + ''') 	 	     
	 				AND JOB_TRAFFIC_DET.JOB_COMPLETED_DATE IS NULL AND JOB_TRAFFIC.COMPLETED_DATE IS NULL ' 
	END
ELSE
	BEGIN
		IF @Rescrictions > 0
				SET @SqlStmt =  @SqlStmt + N'
					 SELECT JOB_LOG.CL_CODE + ''/'' + JOB_LOG.DIV_CODE + ''/'' + JOB_LOG.PRD_CODE as CDP,  
						( RIGHT(REPLICATE(''0'', 6) + CONVERT(VARCHAR(20), JOB_LOG.JOB_NUMBER),6) + ''/'' + RIGHT(REPLICATE(''0'', 2) + CONVERT(VARCHAR(20), JOB_COMPONENT.JOB_COMPONENT_NBR),2) + '' - '' + JOB_COMPONENT.JOB_COMP_DESC ) as JobData,
						isnull(V_JOB_TRAFFIC_DET.TASK_DESCRIPTION, '''') as Task, 
						V_JOB_TRAFFIC_DET.FNC_COMMENTS,
						V_JOB_TRAFFIC_DET.TASK_START_DATE as StartDate,
						V_JOB_TRAFFIC_DET.JOB_REVISED_DATE as DueDate, 
						ISNULL(V_JOB_TRAFFIC_DET.REVISED_DUE_TIME,'''') as DueTime, 
						V_JOB_TRAFFIC_DET.JOB_NUMBER as JobNo, 
						V_JOB_TRAFFIC_DET.JOB_COMPONENT_NBR as JobComp, 
						V_JOB_TRAFFIC_DET.JOB_HRS as HoursAllowed,
						V_JOB_TRAFFIC_DET.SEQ_NBR as SeqNo,
						V_JOB_TRAFFIC_DET.TEMP_COMP_DATE as TempCompleteDate, V_JOB_TRAFFIC_DET.EMP_CODE as EmpCode, 0 AS IS_EVENT, -1 AS EVENT_TASK_ID, ISNULL(V_JOB_TRAFFIC_DET.TASK_STATUS,''P'') AS TASK_STATUS,
					JOB_LOG.JOB_DESC, JOB_COMPONENT.JOB_COMP_DESC, (RIGHT(REPLICATE(''0'', 6) + CONVERT(VARCHAR(20), JOB_LOG.JOB_NUMBER),6) + ''/'' + RIGHT(REPLICATE(''0'', 2) + CONVERT(VARCHAR(20), JOB_COMPONENT.JOB_COMPONENT_NBR),2)) as JOB_COMP,
					[HAS_DOCUMENTS] = CONVERT(BIT, CASE WHEN JOB_TRAFFIC_DET_DOCS.JOB_NUMBER IS NOT NULL THEN 1 ELSE 0 END)
					   FROM JOB_LOG	INNER JOIN CLIENT ON CLIENT.CL_CODE = JOB_LOG.CL_CODE INNER JOIN JOB_COMPONENT ON JOB_LOG.JOB_NUMBER = JOB_COMPONENT.JOB_NUMBER
					 INNER JOIN V_JOB_TRAFFIC_DET ON JOB_COMPONENT.JOB_NUMBER = V_JOB_TRAFFIC_DET.JOB_NUMBER AND JOB_COMPONENT.JOB_COMPONENT_NBR = V_JOB_TRAFFIC_DET.JOB_COMPONENT_NBR
					 INNER JOIN JOB_TRAFFIC ON JOB_COMPONENT.JOB_NUMBER = JOB_TRAFFIC.JOB_NUMBER AND JOB_COMPONENT.JOB_COMPONENT_NBR = JOB_TRAFFIC.JOB_COMPONENT_NBR 
					 INNER JOIN SEC_CLIENT ON JOB_LOG.CL_CODE = SEC_CLIENT.CL_CODE AND JOB_LOG.DIV_CODE = SEC_CLIENT.DIV_CODE AND JOB_LOG.PRD_CODE = SEC_CLIENT.PRD_CODE
					 LEFT OUTER JOIN (SELECT JOB_NUMBER, JOB_COMPONENT_NBR, SEQ_NBR FROM dbo.JOB_TRAFFIC_DET_DOCS GROUP BY JOB_NUMBER, JOB_COMPONENT_NBR, SEQ_NBR) JOB_TRAFFIC_DET_DOCS ON V_JOB_TRAFFIC_DET.JOB_NUMBER = JOB_TRAFFIC_DET_DOCS.JOB_NUMBER 
						AND V_JOB_TRAFFIC_DET.JOB_COMPONENT_NBR = JOB_TRAFFIC_DET_DOCS.JOB_COMPONENT_NBR 
						AND V_JOB_TRAFFIC_DET.SEQ_NBR = JOB_TRAFFIC_DET_DOCS.SEQ_NBR
					  WHERE (NOT (JOB_COMPONENT.JOB_PROCESS_CONTRL IN (6, 12)))	AND (UPPER(SEC_CLIENT.USER_ID) = UPPER(''' + @UserID + ''')) AND (SEC_CLIENT.TIME_ENTRY = 0 OR SEC_CLIENT.TIME_ENTRY IS NULL)
						AND (V_JOB_TRAFFIC_DET.EMP_CODE = ''' + @EmpCode + ''')	AND V_JOB_TRAFFIC_DET.JOB_COMPLETED_DATE IS NULL AND JOB_TRAFFIC.COMPLETED_DATE IS NULL '

			ELSE
				SET @SqlStmt =  @SqlStmt + N'
					 SELECT JOB_LOG.CL_CODE + ''/'' + JOB_LOG.DIV_CODE + ''/'' + JOB_LOG.PRD_CODE as CDP,  
						( RIGHT(REPLICATE(''0'', 6) + CONVERT(VARCHAR(20), JOB_LOG.JOB_NUMBER),6) + ''/'' + RIGHT(REPLICATE(''0'', 2) + CONVERT(VARCHAR(20), JOB_COMPONENT.JOB_COMPONENT_NBR),2) + '' - '' + JOB_COMPONENT.JOB_COMP_DESC ) as JobData, 
						isnull(V_JOB_TRAFFIC_DET.TASK_DESCRIPTION, '''') as Task, 
						V_JOB_TRAFFIC_DET.FNC_COMMENTS,
						V_JOB_TRAFFIC_DET.TASK_START_DATE as StartDate, 		
						V_JOB_TRAFFIC_DET.JOB_REVISED_DATE as DueDate, 
						ISNULL(V_JOB_TRAFFIC_DET.REVISED_DUE_TIME,'''') as DueTime, 
						V_JOB_TRAFFIC_DET.JOB_NUMBER as JobNo, 
						V_JOB_TRAFFIC_DET.JOB_COMPONENT_NBR as JobComp, 			
						V_JOB_TRAFFIC_DET.JOB_HRS as HoursAllowed, 
						V_JOB_TRAFFIC_DET.SEQ_NBR as SeqNo,
						V_JOB_TRAFFIC_DET.TEMP_COMP_DATE as TempCompleteDate, V_JOB_TRAFFIC_DET.EMP_CODE as EmpCode, 0 AS IS_EVENT, -1 AS EVENT_TASK_ID, ISNULL(V_JOB_TRAFFIC_DET.TASK_STATUS,''P'') AS TASK_STATUS,
					JOB_LOG.JOB_DESC, JOB_COMPONENT.JOB_COMP_DESC, (RIGHT(REPLICATE(''0'', 6) + CONVERT(VARCHAR(20), JOB_LOG.JOB_NUMBER),6) + ''/'' + RIGHT(REPLICATE(''0'', 2) + CONVERT(VARCHAR(20), JOB_COMPONENT.JOB_COMPONENT_NBR),2)) as JOB_COMP,
					[HAS_DOCUMENTS] = CONVERT(BIT, CASE WHEN JOB_TRAFFIC_DET_DOCS.JOB_NUMBER IS NOT NULL THEN 1 ELSE 0 END)
	    				   FROM JOB_LOG INNER JOIN CLIENT ON CLIENT.CL_CODE = JOB_LOG.CL_CODE 
					 INNER JOIN JOB_COMPONENT ON JOB_LOG.JOB_NUMBER = JOB_COMPONENT.JOB_NUMBER 
					 INNER JOIN V_JOB_TRAFFIC_DET ON JOB_COMPONENT.JOB_NUMBER = V_JOB_TRAFFIC_DET.JOB_NUMBER AND JOB_COMPONENT.JOB_COMPONENT_NBR = V_JOB_TRAFFIC_DET.JOB_COMPONENT_NBR
					 INNER JOIN JOB_TRAFFIC ON JOB_COMPONENT.JOB_NUMBER = JOB_TRAFFIC.JOB_NUMBER AND JOB_COMPONENT.JOB_COMPONENT_NBR = JOB_TRAFFIC.JOB_COMPONENT_NBR 
					 LEFT OUTER JOIN (SELECT JOB_NUMBER, JOB_COMPONENT_NBR, SEQ_NBR FROM dbo.JOB_TRAFFIC_DET_DOCS GROUP BY JOB_NUMBER, JOB_COMPONENT_NBR, SEQ_NBR) JOB_TRAFFIC_DET_DOCS ON V_JOB_TRAFFIC_DET.JOB_NUMBER = JOB_TRAFFIC_DET_DOCS.JOB_NUMBER 
						AND V_JOB_TRAFFIC_DET.JOB_COMPONENT_NBR = JOB_TRAFFIC_DET_DOCS.JOB_COMPONENT_NBR 
						AND V_JOB_TRAFFIC_DET.SEQ_NBR = JOB_TRAFFIC_DET_DOCS.SEQ_NBR  
	 				  WHERE (NOT (JOB_COMPONENT.JOB_PROCESS_CONTRL IN (6, 12))) AND (V_JOB_TRAFFIC_DET.EMP_CODE = ''' + @EmpCode + ''') AND V_JOB_TRAFFIC_DET.JOB_COMPLETED_DATE IS NULL AND JOB_TRAFFIC.COMPLETED_DATE IS NULL ' 
	END
		
		IF @TaskShow = 'Today'
			BEGIN
				SET @SqlStmt = @SqlStmt + N' AND (''' + CONVERT( VARCHAR(8), @StartDate, 1 ) + ''' >= V_JOB_TRAFFIC_DET.TASK_START_DATE OR V_JOB_TRAFFIC_DET.TASK_START_DATE IS NULL) '
			END
		If LEFT( @TaskStatus, 1 ) = 'P' 
			BEGIN
				SET @SqlStmt = @SqlStmt + N' AND (V_JOB_TRAFFIC_DET.TASK_STATUS IN ( ''P'', '''' ) OR V_JOB_TRAFFIC_DET.TASK_STATUS IS NULL) '
			END
		ELSE IF LEFT( @TaskStatus, 1 ) = 'A'
			BEGIN
				SET @SqlStmt = @SqlStmt + N' AND V_JOB_TRAFFIC_DET.TASK_STATUS = ''A'' '
			END
		ELSE IF LEFT( @TaskStatus, 1 ) = 'H'
			BEGIN
				SET @SqlStmt = @SqlStmt + N' AND V_JOB_TRAFFIC_DET.TASK_STATUS = ''H'' '
			END
		ELSE IF LEFT( @TaskStatus, 1 ) = 'L'
			BEGIN
				SET @SqlStmt = @SqlStmt + N' AND V_JOB_TRAFFIC_DET.TASK_STATUS = ''L'' '
			END
SET @HAS_TASK_SQL = 1
END
PRINT @HAS_TASK_SQL

IF @HAS_TASK_SQL = 1 AND
(
(RTRIM(LTRIM(@TaskStatus)) = '' --ALL
OR LEFT(RTRIM(LTRIM(@TaskStatus)), 1 ) = 'E') --EVENTS
AND @CP = 0
)
BEGIN
	SET @SqlStmt = @SqlStmt + N' UNION ALL'
END

--ADD IN EVENT TASKS
IF (RTRIM(LTRIM(@TaskStatus)) = '' --ALL
OR LEFT(RTRIM(LTRIM(@TaskStatus)), 1 ) = 'E') --EVENTS
AND @CP = 0
BEGIN
	If @Rescrictions > 0
		BEGIN
			SET @SqlStmt = @SqlStmt + N'
			SELECT   
					    JOB_LOG.CL_CODE + ''/'' + JOB_LOG.DIV_CODE + ''/'' + JOB_LOG.PRD_CODE AS CDP, 
					( RIGHT(REPLICATE(''0'', 6) + CONVERT(VARCHAR(20), JOB_LOG.JOB_NUMBER),6) + ''/'' + RIGHT(REPLICATE(''0'', 2) + CONVERT(VARCHAR(20), JOB_COMPONENT.JOB_COMPONENT_NBR),2) + '' - '' + JOB_COMPONENT.JOB_COMP_DESC )
					+ ISNULL('' / '' + EVENT.EVENT_LABEL, '''') + ISNULL('' / '' + EVENT.AD_NUMBER, '''') AS JobData, 
                      TRAFFIC_FNC.TRF_DESC AS Task, EVENT_TASK.COMMENTS AS FNC_COMMENTS, EVENT_TASK.START_TIME AS StartDate, EVENT_TASK.END_TIME AS DueDate, LTRIM(SUBSTRING(CONVERT(VARCHAR(20), EVENT_TASK.START_TIME, 22), 
                      10, 5) + RIGHT(CONVERT(VARCHAR(20), EVENT_TASK.START_TIME, 22), 3)) + '' - '' + LTRIM(SUBSTRING(CONVERT(VARCHAR(20), 
                      EVENT_TASK.END_TIME, 22), 10, 5) + RIGHT(CONVERT(VARCHAR(20), EVENT_TASK.END_TIME, 22), 3)) AS DueTime, 
                      JOB_LOG.JOB_NUMBER AS JobNo, JOB_COMPONENT.JOB_COMPONENT_NBR AS JobComp, EVENT_TASK.HOURS_ALLOWED AS HoursAllowed, 
                      - 1 AS SeqNo, EVENT_TASK.TEMP_COMP_DATE AS TempCompleteDate, EVENT_TASK.EMP_CODE AS EmpCode, 1 AS IS_EVENT, EVENT_TASK.EVENT_TASK_ID,'''' AS TASK_STATUS,
					JOB_LOG.JOB_DESC, JOB_COMPONENT.JOB_COMP_DESC, (RIGHT(REPLICATE(''0'', 6) + CONVERT(VARCHAR(20), JOB_LOG.JOB_NUMBER),6) + ''/'' + RIGHT(REPLICATE(''0'', 2) + CONVERT(VARCHAR(20), JOB_COMPONENT.JOB_COMPONENT_NBR),2)) as JOB_COMP,
					[HAS_DOCUMENTS] = CONVERT(BIT, 0)'
            --IF @HAS_TASK_SQL = 1
            --    BEGIN
            --        SET @SqlStmt = @SqlStmt + ', '''''
            --    END
			SET @SqlStmt = @SqlStmt + ' FROM EVENT_TASK WITH (NOLOCK) INNER JOIN EVENT WITH (NOLOCK) ON EVENT_TASK.EVENT_ID = EVENT.EVENT_ID INNER JOIN
								  JOB_COMPONENT WITH (NOLOCK) ON EVENT.JOB_NUMBER = JOB_COMPONENT.JOB_NUMBER AND EVENT.JOB_COMPONENT_NBR = JOB_COMPONENT.JOB_COMPONENT_NBR INNER JOIN
								  JOB_LOG WITH (NOLOCK) ON JOB_COMPONENT.JOB_NUMBER = JOB_LOG.JOB_NUMBER INNER JOIN TRAFFIC_FNC WITH (NOLOCK) ON EVENT_TASK.TASK_CODE = TRAFFIC_FNC.TRF_CODE INNER JOIN
								  SEC_CLIENT ON JOB_LOG.CL_CODE = SEC_CLIENT.CL_CODE AND JOB_LOG.DIV_CODE = SEC_CLIENT.DIV_CODE AND JOB_LOG.PRD_CODE = SEC_CLIENT.PRD_CODE
			WHERE     (EVENT_TASK.EMP_CODE = ''' + @EmpCode + ''') AND (NOT (JOB_COMPONENT.JOB_PROCESS_CONTRL IN (6, 12))) AND (UPPER(SEC_CLIENT.USER_ID) = UPPER(''' + @UserID + ''')) AND (SEC_CLIENT.TIME_ENTRY = 0 OR SEC_CLIENT.TIME_ENTRY IS NULL) 
			'
			IF @TaskShow = 'Today'
			BEGIN
				SET @SqlStmt = @SqlStmt + N' AND ''' + CONVERT( VARCHAR(8), @StartDate, 1 ) + ''' >= EVENT_TASK.START_TIME '
			END

		END
	ELSE --NO RESTRICTIONS
		BEGIN
			SET @SqlStmt = @SqlStmt + '
				SELECT     
					    JOB_LOG.CL_CODE + ''/'' + JOB_LOG.DIV_CODE + ''/'' + JOB_LOG.PRD_CODE AS CDP, 
					( RIGHT(REPLICATE(''0'', 6) + CONVERT(VARCHAR(20), JOB_LOG.JOB_NUMBER),6) + ''/'' + RIGHT(REPLICATE(''0'', 2) + CONVERT(VARCHAR(20), JOB_COMPONENT.JOB_COMPONENT_NBR),2) + '' - '' + JOB_COMPONENT.JOB_COMP_DESC )
					+ ISNULL('' / '' + EVENT.EVENT_LABEL, '''') + ISNULL('' / '' + EVENT.AD_NUMBER, '''') AS JobData, 
									  TRAFFIC_FNC.TRF_DESC AS Task, EVENT_TASK.COMMENTS AS FNC_COMMENTS, EVENT_TASK.START_TIME AS StartDate, EVENT_TASK.END_TIME AS DueDate, LTRIM(SUBSTRING(CONVERT(VARCHAR(20), EVENT_TASK.START_TIME, 22), 
									  10, 5) + RIGHT(CONVERT(VARCHAR(20), EVENT_TASK.START_TIME, 22), 3)) + '' - '' + LTRIM(SUBSTRING(CONVERT(VARCHAR(20), 
									  EVENT_TASK.END_TIME, 22), 10, 5) + RIGHT(CONVERT(VARCHAR(20), EVENT_TASK.END_TIME, 22), 3)) AS DueTime, 
									  JOB_LOG.JOB_NUMBER AS JobNo, JOB_COMPONENT.JOB_COMPONENT_NBR AS JobComp, EVENT_TASK.HOURS_ALLOWED AS HoursAllowed, 
									  - 1 AS SeqNo, EVENT_TASK.TEMP_COMP_DATE AS TempCompleteDate, EVENT_TASK.EMP_CODE AS EmpCode, 1 AS IS_EVENT, EVENT_TASK.EVENT_TASK_ID,'''' AS TASK_STATUS,
					JOB_LOG.JOB_DESC, JOB_COMPONENT.JOB_COMP_DESC, (RIGHT(REPLICATE(''0'', 6) + CONVERT(VARCHAR(20), JOB_LOG.JOB_NUMBER),6) + ''/'' + RIGHT(REPLICATE(''0'', 2) + CONVERT(VARCHAR(20), JOB_COMPONENT.JOB_COMPONENT_NBR),2)) as JOB_COMP,
					[HAS_DOCUMENTS] = CONVERT(BIT, 0)'
            --IF @HAS_TASK_SQL = 1
            --    BEGIN
            --        SET @SqlStmt = @SqlStmt + ', '''''
            --    END
			SET @SqlStmt = @SqlStmt + ' FROM EVENT_TASK WITH (NOLOCK) INNER JOIN EVENT WITH (NOLOCK) ON EVENT_TASK.EVENT_ID = EVENT.EVENT_ID INNER JOIN
									  JOB_COMPONENT WITH (NOLOCK) ON EVENT.JOB_NUMBER = JOB_COMPONENT.JOB_NUMBER AND EVENT.JOB_COMPONENT_NBR = JOB_COMPONENT.JOB_COMPONENT_NBR INNER JOIN
									  JOB_LOG WITH (NOLOCK) ON JOB_COMPONENT.JOB_NUMBER = JOB_LOG.JOB_NUMBER INNER JOIN TRAFFIC_FNC WITH (NOLOCK) ON EVENT_TASK.TASK_CODE = TRAFFIC_FNC.TRF_CODE
				WHERE EVENT_TASK.EMP_CODE = ''' + @EmpCode + '''  AND (NOT (JOB_COMPONENT.JOB_PROCESS_CONTRL IN (6, 12))) 
			'
			IF @TaskShow = 'Today'
			BEGIN
				SET @SqlStmt = @SqlStmt + N' AND ''' + CONVERT( VARCHAR(8), @StartDate, 1 ) + ''' >= EVENT_TASK.START_TIME '
			END
		END
END
SET @SqlStmt = @SqlStmt + ') AS A'
if @Search <> ''
 Begin
    SET @SqlStmt = @SqlStmt + ' WHERE LOWER(A.JobData) LIKE ''%' + LOWER(@Search) + '%'' OR LOWER(A.CDP) LIKE ''%' + LOWER(@Search) + '%'' OR LOWER(A.Task) LIKE ''%' + LOWER(@Search) + '%'' OR LOWER(Cast(A.FNC_COMMENTS as varchar)) LIKE ''%' + LOWER(@Search) + '%'''
                                
 End

SET @SqlStmt = @SqlStmt + ' ORDER BY A.DueDate,CDP,JobData;'

PRINT @SqlStmt

EXEC (@SqlStmt)












