

CREATE PROCEDURE [dbo].[usp_wv_Traffic_Schedule_GetContactList]
@JOB_NUMBER INT,
@JOB_COMPONENT_NBR INT,
@SEQ SMALLINT
AS

        SELECT     
            JOB_TRAFFIC_DET_CNTS.ID, 
            JOB_TRAFFIC_DET_CNTS.JOB_NUMBER, 
            JOB_TRAFFIC_DET_CNTS.JOB_COMPONENT_NBR, 
            JOB_TRAFFIC_DET_CNTS.SEQ_NBR, 
			JOB_TRAFFIC_DET_CNTS.CDP_CONTACT_ID,
            CDP_CONTACT_HDR.CONT_CODE, 
            CDP_CONTACT_HDR.CONT_FML
        FROM         
            JOB_TRAFFIC_DET_CNTS LEFT OUTER JOIN
            CDP_CONTACT_HDR ON JOB_TRAFFIC_DET_CNTS.CDP_CONTACT_ID = CDP_CONTACT_HDR.CDP_CONTACT_ID
        WHERE     
                    ((JOB_TRAFFIC_DET_CNTS.JOB_NUMBER = @JOB_NUMBER) 
                    AND (JOB_TRAFFIC_DET_CNTS.JOB_COMPONENT_NBR = @JOB_COMPONENT_NBR) 
                    AND (JOB_TRAFFIC_DET_CNTS.SEQ_NBR = @SEQ))



