

CREATE PROCEDURE [dbo].[usp_wv_Estimating_AddNew_AddEstimateComponent]
(
	@EST_NBR INT,
	@EST_COMP_DESC VARCHAR(60),
	@CDP_CONTACT_ID INT,
	@EST_COMPONENT_NBR INT OUTPUT
)
AS
BEGIN
	SET NOCOUNT OFF
	DECLARE 
	@ERR INT,
	@NEXT_EST_COMP_NBR INT
	
    SELECT @NEXT_EST_COMP_NBR = ISNULL(MAX(EST_COMPONENT_NBR),-1) + 1 FROM ESTIMATE_COMPONENT WHERE ESTIMATE_NUMBER = @EST_NBR 
    
    INSERT INTO [ESTIMATE_COMPONENT]
		(
			[ESTIMATE_NUMBER],
			[EST_COMPONENT_NBR],
			[EST_COMP_DESC],
			[EST_COMP_COMMENT],
			[PRESET_CODE],
			[FNC_SORT_ORDER],
			[MODIFIED_BY],
			[MODIFIED_DATE],
			[CDP_CONTACT_ID],
			[DISPLAY_EMP_TITLE],
			[EST_COMP_COMMENT_HTML]
		)
		VALUES
		(
			@EST_NBR,
			@NEXT_EST_COMP_NBR,
			@EST_COMP_DESC,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			@CDP_CONTACT_ID,
			NULL,
			NULL
		)	

	SET @ERR = @@Error

	--RETURN @ERR
END

SELECT @EST_COMPONENT_NBR = @NEXT_EST_COMP_NBR


