

CREATE PROCEDURE [dbo].[usp_wv_Traffic_Schedule_GetEmpList_ByRole]
@JOB_NUMBER INT,
@JOB_COMPONENT_NBR INT,
@SEQ SMALLINT,
@Roles varchar(4000)
AS

        SELECT DISTINCT    
            JOB_TRAFFIC_DET_EMPS.ID, 
            JOB_TRAFFIC_DET_EMPS.JOB_NUMBER, 
            JOB_TRAFFIC_DET_EMPS.JOB_COMPONENT_NBR, 
            JOB_TRAFFIC_DET_EMPS.SEQ_NBR, 
            JOB_TRAFFIC_DET_EMPS.EMP_CODE, 
            ISNULL(EMPLOYEE.EMP_FNAME + ' ', '')+ ISNULL(EMPLOYEE.EMP_MI + '. ', '') + ISNULL(EMPLOYEE.EMP_LNAME, '') AS EMP_NAME, 
            ISNULL(JOB_TRAFFIC_DET_EMPS.HOURS_ALLOWED, 0) AS HOURS_ALLOWED,
			JOB_TRAFFIC_DET_EMPS.TEMP_COMP_DATE, 
			--JOB_TRAFFIC_DET_EMPS.COMPLETED_COMMENTS,
			JOB_TRAFFIC_DET_EMPS.PERCENT_COMPLETE
       FROM         
            JOB_TRAFFIC_DET_EMPS WITH(NOLOCK) INNER JOIN
			EMP_TRAFFIC_ROLE ON JOB_TRAFFIC_DET_EMPS.EMP_CODE = EMP_TRAFFIC_ROLE.EMP_CODE LEFT OUTER JOIN
            EMPLOYEE WITH(NOLOCK) ON JOB_TRAFFIC_DET_EMPS.EMP_CODE = EMPLOYEE.EMP_CODE
			INNER JOIN charlist_to_table(@Roles, DEFAULT) e ON EMP_TRAFFIC_ROLE.ROLE_CODE = e.vstr collate database_default
        WHERE     
                    ((JOB_TRAFFIC_DET_EMPS.JOB_NUMBER = @JOB_NUMBER) 
                    AND (JOB_TRAFFIC_DET_EMPS.JOB_COMPONENT_NBR = @JOB_COMPONENT_NBR) 
                    AND (JOB_TRAFFIC_DET_EMPS.SEQ_NBR = @SEQ));


