

CREATE PROCEDURE [dbo].[usp_wv_Estimating_AddNewRevision]
(
	@ESTIMATE_NUMBER INT,
	@EST_COMPONENT_NBR INT,
	@EST_QUOTE_NBR INT,
	@EST_REV_NBR INT,
	@SPEC_VER INT,
	@SPEC_REV INT,
	@SPEC_QTY_SEQ_NBR INT,
	@JOB_QTY INT
	
)
AS
BEGIN
	SET NOCOUNT OFF
	DECLARE 
	@ERR INT,
	@NEXT_EST_NBR INT
	
    --SELECT @NEXT_EST_NBR = ISNULL(MAX(ESTIMATE_NUMBER),-1) + 1 FROM ESTIMATE_LOG 
    
    INSERT INTO [ESTIMATE_REV]
		(
			[ESTIMATE_NUMBER],
			[EST_COMPONENT_NBR],
			[EST_QUOTE_NBR],
			[EST_REV_NBR],
			[EST_REV_COMMENT],
			[SPEC_VER],
			[SPEC_REV],
			[SPEC_QTY_SEQ_NBR],
			[JOB_QTY],
			[SPEC_RTF]
		)
		VALUES
		(
			@ESTIMATE_NUMBER,
			@EST_COMPONENT_NBR,
			@EST_QUOTE_NBR,
			@EST_REV_NBR,
			NULL,
			@SPEC_VER,
			@SPEC_REV,
			@SPEC_QTY_SEQ_NBR,
			@JOB_QTY,
			NULL
		)	

	

	SET @ERR = @@Error

	--RETURN @ERR
END

--SELECT @QTE_NUM = @NEXT_EST_NBR


