

CREATE PROCEDURE [dbo].[usp_wv_GetJobOrderFormSettings]
@UserID Varchar(100)
AS

SELECT     
    USER_ID, 
    ISNULL(JOB_ORDER_FORM,0) AS JOB_ORDER_FORM, 
    ISNULL(TRAFFIC_SCHED,0) AS TRAFFIC_SCHED, 
    ISNULL(MILESTONE,0) AS MILESTONE, 
    ISNULL(DUE_DATE,0) AS DUE_DATE, 
    ISNULL(EMPL_ASSIGN,0) AS EMPL_ASSIGN, 
    ISNULL(OMIT_EMPTY_FLDS,0) AS OMIT_EMPTY_FLDS, 
    ISNULL(TRAFFIC_SCHED_TITLE,'') AS TRAFFIC_SCHED_TITLE, 
    ISNULL(SCHED_MILESTONE_TITLE,'') AS SCHED_MILESTONE_TITLE, 
    ISNULL(CREATIVE_BRIEF_TITLE,'') AS CREATIVE_BRIEF_TITLE, 
    ISNULL(JOB_SPEC_TITLE,'') AS JOB_SPEC_TITLE, --10
    ISNULL(REPORT_TITLE_PLACEMENT,'') AS REPORT_TITLE_PLACEMENT, 
    ISNULL(LOCATION_ID,'') AS LOCATION_ID, 
    ISNULL(CREATIVE_BRIEF,0) AS CREATIVE_BRIEF, 
    ISNULL(CREATIVE_BRIEF_AO,0) AS CREATIVE_BRIEF_AO, 
    ISNULL(JOB_SPECS,0) AS JOB_SPECS, 
    ISNULL(JOB_SPECS_AO,0) AS JOB_SPECS_AO, 
    ISNULL(TRAFFIC_GENERAL_ASSIGN,0) AS TRAFFIC_GENERAL_ASSIGN, 
    ISNULL(KEY_ASSIGN_TITLE,'') AS KEY_ASSIGN_TITLE,
    ISNULL(SCHED_COMMENTS,0) AS SCHED_COMMENTS, 
    ISNULL(VENDOR_SPECS,0) AS VENDOR_SPECS, 
    ISNULL(MEDIA_SPECS,0) AS MEDIA_SPECS, 
    ISNULL(JOB_VERSIONS,0) AS JOB_VERSIONS,
	ISNULL(OMIT_EMPTY_FLDS_CB,0) AS OMIT_EMPTY_FLDS_CB,
	ISNULL(OMIT_EMPTY_FLDS_JV,0) AS OMIT_EMPTY_FLDS_JV,
	ISNULL(OMIT_EMPTY_FLDS_JS,0) AS OMIT_EMPTY_FLDS_JS 
FROM       PRINT_JOB_ORDER_DEF
WHERE     (UPPER(USER_ID) = UPPER(@UserID))



