
CREATE PROCEDURE [dbo].[usp_wv_required_job_comp_blackplate]
@CLI_CODE VARCHAR(6),
@CODE varchar(6),
@ITEMCODE varchar(32),
@VERSION int
AS
DECLARE
@return INT

if @VERSION = 1
Begin
	SELECT @return = 
		CASE 
			WHEN BLACKPLATE_VER_R = 1 THEN 1
			WHEN (SELECT ISNULL(BLACKPLATE_VER_R,0) FROM CLIENT WHERE CL_CODE = @CLI_CODE) = 1 THEN 1
		ELSE
			(SELECT ISNULL(REQUIRED,0) FROM JOB_TMPLT_DTL WHERE JOB_TMPLT_DTL.JOB_TMPLT_CODE = @CODE AND JOB_TMPLT_DTL.ITEM_CODE = @ITEMCODE)
		END
	FROM AGENCY 
	SELECT ISNULL(@return,0)
End
if @VERSION = 2
Begin
	SELECT @return = 
		CASE 
			WHEN BLACKPLATE_VER2_R = 1 THEN 1
			WHEN (SELECT ISNULL(BLACKPLATE_VER2_R,0) FROM CLIENT WHERE CL_CODE = @CLI_CODE) = 1 THEN 1
		ELSE
			(SELECT ISNULL(REQUIRED,0) FROM JOB_TMPLT_DTL WHERE JOB_TMPLT_DTL.JOB_TMPLT_CODE = @CODE AND JOB_TMPLT_DTL.ITEM_CODE = @ITEMCODE)
		END
	FROM AGENCY 
	SELECT ISNULL(@return,0)
end
--SELECT @return = 
--	CASE 
--		EMAIL_GR_CODE_R WHEN 1 THEN 1
--	ELSE
--		(SELECT ISNULL(EMAIL_GR_CODE_R,0) FROM AGENCY)
--	END
--FROM CLIENT 
--WHERE CLIENT.CL_CODE = @CLI_CODE
--SELECT ISNULL(@return,0)

