SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS OFF 
GO
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[usp_wv_SaveEmployeeNickname]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
DROP PROCEDURE [dbo].[usp_wv_SaveEmployeeNickname]
GO
CREATE PROCEDURE [dbo].[usp_wv_SaveEmployeeNickname] /*WITH ENCRYPTION*/
@EMP_CODE VARCHAR(6),
@NICKNAME VARCHAR(10)
AS
/*=========== QUERY ===========*/
IF EXISTS (SELECT EMP_CODE FROM EMPLOYEE_PICTURE WHERE EMP_CODE = @EMP_CODE)
BEGIN
	UPDATE EMPLOYEE_PICTURE
	SET EMP_NICKNAME = @NICKNAME
	WHERE 
	EMP_CODE = @EMP_CODE;
END
ELSE
BEGIN
	INSERT INTO EMPLOYEE_PICTURE (EMP_CODE, EMP_NICKNAME) VALUES (@EMP_CODE, @NICKNAME);
END
/*=========== QUERY ===========*/
GO
SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO