
CREATE PROCEDURE [dbo].[usp_wv_GetManagerLabel] 
@USER_ID VARCHAR(100)
AS
DECLARE 
@MGR_COL VARCHAR(20),
@RESTRICTED SMALLINT

SELECT @RESTRICTED = ISNULL(COUNT(1),0) FROM SEC_EMP WHERE UPPER(USER_ID) = UPPER(@USER_ID)

SELECT @MGR_COL = CAST( AGY_SETTINGS_VALUE AS varchar(20) )
FROM AGY_SETTINGS WHERE AGY_SETTINGS_CODE = 'TRAFFIC_MGR_COL' 

SELECT ISNULL(AGY_SETTINGS_VALUE,'Manager') AS ManagerLabel
FROM AGY_SETTINGS WHERE AGY_SETTINGS_CODE = @MGR_COL


