

CREATE PROCEDURE [dbo].[usp_wv_Job_Template_GetComments] 
@JOB_NUMBER AS int,
@JOB_COMPONENT_NBR AS int


AS

SET NOCOUNT ON

SELECT     ISNULL(JOB_LOG.JOB_COMMENTS,'') AS JOB_COMMENTS, ISNULL(JOB_COMPONENT.JOB_COMP_COMMENTS,'') AS JOB_COMP_COMMENTS, 
		   ISNULL(JOB_COMPONENT.CREATIVE_INSTR,'')AS CREATIVE_INSTR, ISNULL(JOB_COMPONENT.JOB_DEL_INSTRUCT,'') AS JOB_DEL_INSTRUCT,
		   ISNULL(JOB_LOG.JOB_COMMENTS_HTML,'') AS JOB_COMMENTS_HTML, ISNULL(JOB_COMPONENT.JC_COMMENTS_HTML,'') AS JC_COMMENTS_HTML, 
		   ISNULL(JOB_COMPONENT.CREATIVE_INSTR_HTML,'')AS CREATIVE_INSTR_HTML, ISNULL(JOB_COMPONENT.JOB_DEL_INSTR_HTML,'') AS JOB_DEL_INSTR_HTML
FROM         JOB_LOG INNER JOIN
                      JOB_COMPONENT ON JOB_LOG.JOB_NUMBER = JOB_COMPONENT.JOB_NUMBER
WHERE     (JOB_COMPONENT.JOB_NUMBER = @JOB_NUMBER) AND (JOB_COMPONENT.JOB_COMPONENT_NBR = @JOB_COMPONENT_NBR)

