
CREATE PROCEDURE [dbo].[usp_wv_Traffic_Schedule_GetQuickTaskReport] 
	@JOB_NUMBER INT,
	@JOB_COMPONENT_NBR SMALLINT
AS

    SELECT     
	    V_JOB_TRAFFIC_DET.FNC_CODE, 
	    V_JOB_TRAFFIC_DET.TASK_DESCRIPTION, 
	    V_JOB_TRAFFIC_DET.TASK_START_DATE, 
	    V_JOB_TRAFFIC_DET.JOB_REVISED_DATE, 
	    V_JOB_TRAFFIC_DET_EMPS.EMP_CODE_LIST, 
	    V_JOB_TRAFFIC_DET_EMPS.EMP_LFI_LIST
    FROM         
	    V_JOB_TRAFFIC_DET INNER JOIN
	    V_JOB_TRAFFIC_DET_EMPS ON V_JOB_TRAFFIC_DET.JOB_NUMBER = V_JOB_TRAFFIC_DET_EMPS.JOB_NUMBER AND 
	    V_JOB_TRAFFIC_DET.JOB_COMPONENT_NBR = V_JOB_TRAFFIC_DET_EMPS.JOB_COMPONENT_NBR AND 
	    V_JOB_TRAFFIC_DET.SEQ_NBR = V_JOB_TRAFFIC_DET_EMPS.SEQ_NBR
    WHERE     
	    (V_JOB_TRAFFIC_DET.JOB_NUMBER = @JOB_NUMBER) 
	    AND (V_JOB_TRAFFIC_DET.JOB_COMPONENT_NBR = @JOB_COMPONENT_NBR)

