






















CREATE PROCEDURE [dbo].[usp_wv_Estimating_Quote_DetailsAlert] 
@EstNo Int,
@EstCompNo Int,
@QuoteNo Int,
@RevNo Int
AS
SELECT     ESTIMATE_QUOTE.ESTIMATE_NUMBER, ESTIMATE_QUOTE.EST_COMPONENT_NBR, ESTIMATE_QUOTE.EST_QUOTE_NBR, 
                      ESTIMATE_QUOTE.EST_QUOTE_DESC, ESTIMATE_REV.EST_REV_NBR, ESTIMATE_REV_DET.SEQ_NBR, 
                      ESTIMATE_REV_DET.FNC_CODE, FUNCTIONS.FNC_DESCRIPTION, ESTIMATE_REV_DET.EST_FNC_COMMENT, ESTIMATE_REV_DET.EST_REV_SUP_BY_CDE, 
                      ESTIMATE_REV_DET.EST_REV_SUP_BY_NTE, ESTIMATE_REV_DET.EST_REV_QUANTITY, ESTIMATE_REV_DET.EST_REV_RATE, 
                      ESTIMATE_REV_DET.EST_REV_EXT_AMT, ESTIMATE_REV_DET.TAX_CODE, ESTIMATE_REV_DET.EST_REV_COMM_PCT, ESTIMATE_REV_DET.EXT_MARKUP_AMT, 
                      ESTIMATE_REV_DET.LINE_TOTAL, ESTIMATE_REV_DET.EST_REV_CONT_PCT, ESTIMATE_REV_DET.EXT_CONTINGENCY,
					  ESTIMATE_REV_DET.INCL_CPU, ESTIMATE_REV_DET.TAX_STATE_PCT, ESTIMATE_REV_DET.TAX_COUNTY_PCT, 
                      ESTIMATE_REV_DET.TAX_CITY_PCT, ESTIMATE_REV_DET.TAX_COMM, ESTIMATE_REV_DET.TAX_COMM_ONLY, 
                      ESTIMATE_REV_DET.TAX_RESALE, ESTIMATE_REV_DET.EXT_NONRESALE_TAX, ESTIMATE_REV_DET.EXT_STATE_RESALE, 
                      ESTIMATE_REV_DET.EXT_COUNTY_RESALE, ESTIMATE_REV_DET.EXT_CITY_RESALE, ESTIMATE_REV_DET.EXT_MU_CONT, 
                      ESTIMATE_REV_DET.EXT_STATE_CONT, ESTIMATE_REV_DET.EXT_COUNTY_CONT, ESTIMATE_REV_DET.EXT_CITY_CONT, 
                      ESTIMATE_REV_DET.EXT_NR_CONT, ESTIMATE_REV_DET.LINE_TOTAL_CONT, ESTIMATE_REV_DET.EST_CPM_FLAG, 
                      ESTIMATE_REV_DET.EST_FNC_TYPE, ESTIMATE_REV_DET.EST_COMM_FLAG, ESTIMATE_REV_DET.EST_TAX_FLAG, 
                      ESTIMATE_REV_DET.EST_NONBILL_FLAG, ISNULL(ESTIMATE_REV_DET.FEE_TIME,0) AS FEE_TIME, ESTIMATE_REV_DET.EMPLOYEE_TITLE_ID, FUNCTIONS.FNC_TYPE,
					  ESTIMATE_REV_DET.EST_PHASE_ID, ISNULL(ESTIMATE_REV_DET.EST_PHASE_DESC, '''') as EST_PHASE_DESC, FNC_HEADING.FNC_HEADING_ID,
					  FNC_HEADING.FNC_HEADING_DESC, FNC_HEADING.FNC_HEADING_SEQ, ISNULL(FUNCTIONS.FNC_CONSOLIDATION, '''') AS FNC_CONSOLIDATION,
					  CASE WHEN ESTIMATE_REV_DET.EST_FNC_TYPE = 'E' THEN 'Employee'
						   WHEN ESTIMATE_REV_DET.EST_FNC_TYPE = 'V' THEN 'Vendor'
						   WHEN ESTIMATE_REV_DET.EST_FNC_TYPE = 'I' THEN 'Income Only'
						   WHEN ESTIMATE_REV_DET.EST_FNC_TYPE = 'C' THEN 'Client OOP'
						   ELSE '' END AS FNC_TYPE_DESC 
FROM         ESTIMATE_QUOTE INNER JOIN
                      ESTIMATE_REV ON ESTIMATE_QUOTE.ESTIMATE_NUMBER = ESTIMATE_REV.ESTIMATE_NUMBER AND 
                      ESTIMATE_QUOTE.EST_COMPONENT_NBR = ESTIMATE_REV.EST_COMPONENT_NBR AND 
                      ESTIMATE_QUOTE.EST_QUOTE_NBR = ESTIMATE_REV.EST_QUOTE_NBR INNER JOIN
                      ESTIMATE_COMPONENT ON ESTIMATE_QUOTE.ESTIMATE_NUMBER = ESTIMATE_COMPONENT.ESTIMATE_NUMBER AND 
                      ESTIMATE_QUOTE.EST_COMPONENT_NBR = ESTIMATE_COMPONENT.EST_COMPONENT_NBR INNER JOIN
                      ESTIMATE_LOG ON ESTIMATE_COMPONENT.ESTIMATE_NUMBER = ESTIMATE_LOG.ESTIMATE_NUMBER INNER JOIN
                      ESTIMATE_REV_DET ON ESTIMATE_REV.ESTIMATE_NUMBER = ESTIMATE_REV_DET.ESTIMATE_NUMBER AND 
                      ESTIMATE_REV.EST_COMPONENT_NBR = ESTIMATE_REV_DET.EST_COMPONENT_NBR AND 
                      ESTIMATE_REV.EST_QUOTE_NBR = ESTIMATE_REV_DET.EST_QUOTE_NBR AND 
                      ESTIMATE_REV.EST_REV_NBR = ESTIMATE_REV_DET.EST_REV_NBR INNER JOIN
                      FUNCTIONS ON ESTIMATE_REV_DET.FNC_CODE = FUNCTIONS.FNC_CODE LEFT OUTER JOIN
                      JOB_COMPONENT ON ESTIMATE_COMPONENT.ESTIMATE_NUMBER = JOB_COMPONENT.ESTIMATE_NUMBER AND 
                      ESTIMATE_COMPONENT.EST_COMPONENT_NBR = JOB_COMPONENT.EST_COMPONENT_NBR LEFT OUTER JOIN
                      FNC_HEADING ON FUNCTIONS.FNC_HEADING_ID = FNC_HEADING.FNC_HEADING_ID
WHERE     (ESTIMATE_QUOTE.ESTIMATE_NUMBER = @EstNo) AND (ESTIMATE_QUOTE.EST_COMPONENT_NBR = @EstCompNo) AND 
                      (ESTIMATE_QUOTE.EST_QUOTE_NBR = @QuoteNo) AND (ESTIMATE_REV.EST_REV_NBR = @RevNo) AND ((FUNCTIONS.FNC_INACTIVE <> 1) OR (FUNCTIONS.FNC_INACTIVE IS NULL))
ORDER BY ESTIMATE_REV_DET.EST_FNC_TYPE, FUNCTIONS.FNC_DESCRIPTION





















