
CREATE PROCEDURE [dbo].[usp_wv_EVENT_TASK_GET_DETAILS] 
	@EVENT_TASK_ID AS INT
AS


    SELECT 
        EVENT_TASK.EVENT_TASK_ID,
        RIGHT(REPLICATE('0', 6) + CONVERT(VARCHAR(20),ISNULL(EVENT_TASK.EVENT_ID,0)), 6) AS EVENT_TASK_EVENT_ID,
        EVENT_TASK.EMP_CODE AS EVENT_TASK_EMP_CODE,
        ISNULL(ISNULL(EMPLOYEE.EMP_FNAME + ' ', '') + ISNULL(EMPLOYEE.EMP_MI + '. ', '')+ ISNULL(EMPLOYEE.EMP_LNAME, ''),'') AS EVENT_TASK_EMP_FML_NAME,
        ISNULL(EVENT_TASK.EMP_CODE +' - ','')+ISNULL(ISNULL(EMPLOYEE.EMP_FNAME + ' ', '') + ISNULL(EMPLOYEE.EMP_MI + '. ', '')+ ISNULL(EMPLOYEE.EMP_LNAME, ''),'') AS EVENT_TASK_EMPLOYEE,
        EVENT_TASK.START_DATE AS EVENT_TASK_START_DATE,
        EVENT_TASK.END_DATE AS EVENT_TASK_END_DATE,
        EVENT_TASK.START_TIME AS EVENT_TASK_START_TIME,
        EVENT_TASK.END_TIME AS EVENT_TASK_END_TIME,
        EVENT_TASK.TEMP_COMP_DATE AS EVENT_TASK_TEMP_COMP_DATE,
        EVENT_TASK.HOURS_ALLOWED AS EVENT_TASK_HOURS_ALLOWED,
        EVENT_TASK.COMMENTS AS EVENT_TASK_COMMENTS,
        EVENT_TASK.COMPLETED_COMMENTS AS EVENT_TASK_COMPLETED_COMMENTS,
        EVENT_TASK.ROW_TYPE AS EVENT_TASK_ROW_TYPE,
        TRAFFIC_FNC.TRF_CODE +' - '+TRAFFIC_FNC.TRF_DESC AS EVENT_TASK_TRF,
        EVENT_TASK.TASK_CODE AS EVENT_TASK_TRF_CODE,
        TRAFFIC_FNC.TRF_DESC AS EVENT_TASK_TRF_DESC,
        RIGHT(REPLICATE('0', 6) + CONVERT(VARCHAR(20),ISNULL(EVENT_TASK.EVENT_ID,0)), 6) + ISNULL(' - ' + EVENT.EVENT_LABEL,'') AS [EVENT],
        EVENT.EVENT_LABEL,
        EVENT.EVENT_DESC_LONG,
        EVENT.EVENT_DATE,
        EVENT.EVENT_END_DATE,
        EVENT.QTY_HRS AS EVENT_QTY_HRS,
        EVENT.QTY_TYPE AS EVENT_QTY_TYPE,
        EVENT.START_TIME AS EVENT_START_TIME,
        EVENT.END_TIME AS EVENT_END_TIME,
        RESOURCE.RESOURCE_CODE+ISNULL(' - '+RESOURCE.RESOURCE_DESC,'') AS EVENT_RESOURCE,
        RIGHT(REPLICATE('0', 6) + CONVERT(VARCHAR(20),ISNULL(JOB_LOG.JOB_NUMBER,0)), 6) + ' - ' +JOB_LOG.JOB_DESC AS JOB,
        RIGHT(REPLICATE('0', 2) + CONVERT(VARCHAR(20),ISNULL(JOB_COMPONENT.JOB_COMPONENT_NBR,0)), 2) + ' - ' +JOB_COMPONENT.JOB_COMP_DESC AS JOB_COMPONENT,
        CLIENT.CL_CODE+ISNULL(' - '+CLIENT.CL_NAME,'') AS CLIENT,
        DIVISION.DIV_CODE+ISNULL(' - '+DIVISION.DIV_NAME,'') AS DIVISION,
        PRODUCT.PRD_CODE+ISNULL(' - '+PRODUCT.PRD_DESCRIPTION,'') AS PRODUCT,
        ISNULL(OFFICE.OFFICE_CODE,'')+ISNULL(' - '+OFFICE.OFFICE_NAME,'') AS OFFICE
    FROM         
        EVENT_TASK WITH (NOLOCK) INNER JOIN
        EVENT WITH (NOLOCK) ON EVENT_TASK.EVENT_ID = EVENT.EVENT_ID INNER JOIN
        JOB_COMPONENT WITH (NOLOCK) ON EVENT.JOB_NUMBER = JOB_COMPONENT.JOB_NUMBER AND 
        EVENT.JOB_COMPONENT_NBR = JOB_COMPONENT.JOB_COMPONENT_NBR INNER JOIN
        JOB_LOG WITH (NOLOCK) ON JOB_COMPONENT.JOB_NUMBER = JOB_LOG.JOB_NUMBER INNER JOIN
        CLIENT WITH (NOLOCK) ON JOB_LOG.CL_CODE = CLIENT.CL_CODE INNER JOIN
        PRODUCT WITH (NOLOCK) ON JOB_LOG.CL_CODE = PRODUCT.CL_CODE AND JOB_LOG.DIV_CODE = PRODUCT.DIV_CODE AND 
        JOB_LOG.PRD_CODE = PRODUCT.PRD_CODE INNER JOIN
        DIVISION WITH (NOLOCK) ON JOB_LOG.CL_CODE = DIVISION.CL_CODE AND JOB_LOG.DIV_CODE = DIVISION.DIV_CODE INNER JOIN
        TRAFFIC_FNC WITH (NOLOCK) ON EVENT_TASK.TASK_CODE = TRAFFIC_FNC.TRF_CODE LEFT OUTER JOIN
        EMPLOYEE ON EVENT_TASK.EMP_CODE = EMPLOYEE.EMP_CODE LEFT OUTER JOIN
        OFFICE WITH (NOLOCK) ON JOB_LOG.OFFICE_CODE = OFFICE.OFFICE_CODE AND 
        PRODUCT.OFFICE_CODE = OFFICE.OFFICE_CODE LEFT OUTER JOIN
        RESOURCE WITH (NOLOCK) ON EVENT.RESOURCE_CODE = RESOURCE.RESOURCE_CODE
    WHERE     
        (EVENT_TASK.EVENT_TASK_ID = @EVENT_TASK_ID);


