

CREATE PROCEDURE [dbo].[usp_wv_Vendor_Quote_UpdateRequestQuote]
(
	@ESTIMATE_NUMBER INT,
	@EST_COMPONENT_NBR SMALLINT,
	@VENDOR_QTE_NBR INT,
	@EST_QUOTE_NBR INT,
	@EST_REV_NBR INT,
	@VN_QTE_SPECS TEXT
)
AS
BEGIN
	SET NOCOUNT OFF

			UPDATE [VENDOR_QTE_SPECS] WITH(ROWLOCK)
	            SET
					[VN_QTE_SPECS] = @VN_QTE_SPECS
	           WHERE
		            [ESTIMATE_NUMBER] = @ESTIMATE_NUMBER AND 
		            [EST_COMPONENT_NBR] = @EST_COMPONENT_NBR AND 
		            [VENDOR_QTE_NBR] = @VENDOR_QTE_NBR AND
					[EST_QUOTE_NBR] = @EST_QUOTE_NBR AND
					[EST_REV_NBR] = @EST_REV_NBR
	    
				
END





