

CREATE PROCEDURE [dbo].[usp_wv_Vendor_Quote_UpdateRequestVendor]
(
	@ESTIMATE_NUMBER INT,
	@EST_COMPONENT_NBR SMALLINT,
	@VENDOR_QTE_NBR INT,
	@VN_CODE VARCHAR(6),
	@VN_CONT_CODE VARCHAR(4),
	@VN_NOTES TEXT,
	@DISPATCH_DATE SMALLDATETIME,
	@REPLY_DATE SMALLDATETIME,
	@DUE_DATE SMALLDATETIME
)
AS
BEGIN
	SET NOCOUNT OFF

			UPDATE [VENDOR_QTE_VEN] WITH(ROWLOCK)
	            SET
					[VN_CONT_CODE] = @VN_CONT_CODE,
					[VN_NOTES] = @VN_NOTES,
					[DISPATCH_DATE] = @DISPATCH_DATE,
					[REPLY_DATE] = @REPLY_DATE,
					[DUE_DATE] = @DUE_DATE
	           WHERE
		            [ESTIMATE_NUMBER] = @ESTIMATE_NUMBER AND 
		            [EST_COMPONENT_NBR] = @EST_COMPONENT_NBR AND 
		            [VENDOR_QTE_NBR] = @VENDOR_QTE_NBR AND
					[VN_CODE] = @VN_CODE
	    
				
END





