
CREATE PROCEDURE [dbo].[usp_wv_EVENT_UPDATE] 
	@EVENT_ID AS INT,
	@EVENT_LABEL AS VARCHAR(50),
	@EVENT_DESC_LONG AS TEXT,
	@EVENT_DATE AS SMALLDATETIME,
	@QTY_HRS AS DECIMAL(15,2),
	@QTY_TYPE AS SMALLINT,
	@START_TIME AS SMALLDATETIME,
	@END_TIME AS SMALLDATETIME,
	@RESOURCE_CODE AS VARCHAR(6),
	@AD_NUMBER AS VARCHAR(30),
	@EVENT_COMMENT AS TEXT,
	@INCOME_ONLY_ID AS INT,
	@MODIFY_DATE AS SMALLDATETIME,
	@MODIFY_USER AS VARCHAR(100),
	@EVENT_TYPE_ID AS SMALLINT
AS

    UPDATE [EVENT] WITH(ROWLOCK)
    SET
        EVENT_LABEL = @EVENT_LABEL,
        EVENT_DESC_LONG = @EVENT_DESC_LONG,
        EVENT_DATE = @EVENT_DATE,
        QTY_HRS = @QTY_HRS,
        QTY_TYPE = @QTY_TYPE,
        START_TIME = @START_TIME,
        END_TIME = @END_TIME,
        RESOURCE_CODE = @RESOURCE_CODE,
        AD_NUMBER = @AD_NUMBER,
        EVENT_COMMENT = @EVENT_COMMENT,
        INCOME_ONLY_ID = @INCOME_ONLY_ID,
        MODIFY_DATE = @MODIFY_DATE,
        MODIFY_USER = @MODIFY_USER,
		EVENT_TYPE_ID = @EVENT_TYPE_ID
    WHERE
        EVENT_ID = @EVENT_ID;	
	
	
