
CREATE PROCEDURE [dbo].[usp_wv_Traffic_Schedule_NotifyGetNextEmpCodes] 
@JOB_NUMBER INT,
@JOB_COMPONENT_NBR SMALLINT

AS
DECLARE
@NEXT_SEQ AS INT

SELECT  TOP 1   @NEXT_SEQ =  JOB_TRAFFIC_DET.SEQ_NBR
FROM JOB_TRAFFIC_DET
WHERE (JOB_NUMBER = @JOB_NUMBER AND JOB_COMPONENT_NBR = @JOB_COMPONENT_NBR)
AND (JOB_COMPLETED_DATE IS NULL)
ORDER BY JOB_TRAFFIC_DET.JOB_ORDER, JOB_TRAFFIC_DET.SEQ_NBR


SELECT EMP_CODE FROM JOB_TRAFFIC_DET_EMPS 
WHERE 
 (JOB_NUMBER = @JOB_NUMBER AND JOB_COMPONENT_NBR = @JOB_COMPONENT_NBR AND SEQ_NBR = @NEXT_SEQ)
