

CREATE PROCEDURE [dbo].[usp_wv_Traffic_Schedule_GetQuotedHours]
	@JOB_NUMBER INT,
@JOB_COMPONENT_NBR INT,
@FNC_CODE varchar(6),
@EMPCODE varchar(6)
AS
BEGIN

	SET NOCOUNT ON;

      SELECT     dbo.WV_ESTIMATED_HOURS.JOB_NUMBER, dbo.WV_ESTIMATED_HOURS.JOB_COMPONENT_NBR, dbo.WV_ESTIMATED_HOURS.FNC_CODE, 
                      dbo.WV_SCHEDULEFN.EMP_CODE, dbo.WV_ESTIMATED_HOURS.SumOfEST_REF_QUANTITY
	FROM         dbo.WV_SCHEDULEFN INNER JOIN
                      dbo.WV_ESTIMATED_HOURS ON dbo.WV_SCHEDULEFN.JOB_NUMBER = dbo.WV_ESTIMATED_HOURS.JOB_NUMBER AND 
                      dbo.WV_SCHEDULEFN.JOB_COMPONENT_NBR = dbo.WV_ESTIMATED_HOURS.JOB_COMPONENT_NBR AND 
                      dbo.WV_SCHEDULEFN.FNC_EST = dbo.WV_ESTIMATED_HOURS.FNC_CODE and dbo.WV_SCHEDULEFN.EMP_CODE = dbo.WV_ESTIMATED_HOURS.EST_REV_SUP_BY_CDE
	WHERE     (dbo.WV_ESTIMATED_HOURS.JOB_NUMBER = @JOB_NUMBER) AND (dbo.WV_ESTIMATED_HOURS.JOB_COMPONENT_NBR = @JOB_COMPONENT_NBR) AND 
                      (dbo.WV_SCHEDULEFN.FNC_EST = @FNC_CODE) AND (dbo.WV_ESTIMATED_HOURS.FNC_CODE = @FNC_CODE)  AND dbo.WV_SCHEDULEFN.EMP_CODE=@EMPCODE
                
                      
END

