IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[usp_wv_AAMUpdateColumnWidthSettings]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
DROP PROCEDURE [dbo].[usp_wv_AAMUpdateColumnWidthSettings]
GO

/****** Object:  StoredProcedure [dbo].[usp_wv_AAMUpdateColumnWidthSettings]    Script Date: 7/21/2020 4:21:43 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[usp_wv_AAMUpdateColumnWidthSettings] /*WITH ENCRYPTION*/
@GRID_NAME VARCHAR(100),
@USER_CODE VARCHAR(100),
@COLUMN_NAME VARCHAR(100),
@NEW_COLUMN_WIDTH INT

AS

DECLARE @GRID_COLUMN_ID INT
DECLARE @GRID_ID INT

SELECT @GRID_ID = GRID_ID FROM GRID WITH(NOLOCK) WHERE NAME = @GRID_NAME;
SELECT @GRID_COLUMN_ID = GRID_COLUMN_ID FROM GRID_COLUMN WITH(NOLOCK) WHERE GRID_ID = @GRID_ID AND NAME = @COLUMN_NAME;

--UPDATE NEW LOCATION FOR MOVED COLUMN
UPDATE GRID_COLUMN_SETTING WITH(ROWLOCK)
SET COLUMN_WIDTH = @NEW_COLUMN_WIDTH
WHERE GRID_COLUMN_ID = @GRID_COLUMN_ID
AND GRID_ID = @GRID_ID
AND USER_CODE = @USER_CODE