IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[usp_wv_ALERT_ADD_MENTION]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
    DROP PROCEDURE [dbo].[usp_wv_ALERT_ADD_MENTION]
GO
CREATE PROCEDURE [dbo].[usp_wv_ALERT_ADD_MENTION]

@ALERT_ID INT,
@EMP_CODE VARCHAR(6),
@DESCRIPTION_MENTION INT,
@USER_CODE VARCHAR(6)

AS

DECLARE @COMMENT_ID INT = 0

--BEGIN
	--IF @DESCRIPTION_MENTION = 0 THE MENTION IS INCLUDED IN THE MAIN ALERT DESCRIPTION/BODY
	--OTHERWISE IT'S CONTAINED IN A COMMENT WITH AN ASSOCIATED COMMENT_ID
	--IF @DESCRIPTION_MENTION = 1		
	--	SELECT @COMMENT_ID = 0
	--ELSE
	--	SELECT @COMMENT_ID = MAX(COMMENT_ID) + 1 FROM ALERT_COMMENT WITH (NOLOCK)
--END

BEGIN
	INSERT INTO ALERT_MENTION WITH (ROWLOCK) VALUES (@ALERT_ID, @COMMENT_ID, @EMP_CODE, @USER_CODE)
END