
CREATE PROCEDURE [dbo].[usp_wv_Traffic_Schedule_GetAssignmentLabels] AS

SELECT     AGY_SETTINGS_CODE, ISNULL(CAST(AGY_SETTINGS_VALUE AS varchar(20)), '') AS AGY_SETTINGS_VALUE
FROM         AGY_SETTINGS
WHERE     (AGY_SETTINGS_CODE = 'TR_TITLE1') OR
                      (AGY_SETTINGS_CODE = 'TR_TITLE2') OR
                      (AGY_SETTINGS_CODE = 'TR_TITLE3') OR
                      (AGY_SETTINGS_CODE = 'TR_TITLE4') OR
                      (AGY_SETTINGS_CODE = 'TR_TITLE5')
ORDER BY AGY_SETTINGS_CODE;

SELECT ISNULL(CAST(AGY_SETTINGS_VALUE AS varchar(20)),'') FROM dbo.AGY_SETTINGS WHERE AGY_SETTINGS_CODE = 'TRAFFIC_MGR_COL' 
        
