--DROP PROCEDURE usp_wv_get_arptJobVersion
CREATE PROCEDURE usp_wv_get_arptJobVersion 
@JobVersHdrID INT
AS
BEGIN

	DECLARE
		@SECTION_TYPE_ID INT;

	SELECT @SECTION_TYPE_ID = JV_DTYPE_ID FROM JOB_VER_DTYPE WHERE UPPER(JV_DTYPE_DESC) = 'SECTION';

	SELECT 
		CASE JVD.IsSection
			WHEN 1 THEN UPPER(JVTD.JV_TMPLT_LABEL)
			ELSE JVTD.JV_TMPLT_LABEL
		END AS LABEL,
		CASE JVT.ADVAN_DTYPE_ID 
			WHEN 1 THEN CASE JVTD.JV_DTYPE_ID
							WHEN @SECTION_TYPE_ID THEN NULL
							ELSE CONVERT(VARCHAR(2000), JVD.JobVersionValue)
						END 
			WHEN 6 THEN CONVERT(VARCHAR(8000), JVD.JobVersionValue)
			WHEN 7 THEN CONVERT(VARCHAR(3), CASE JVD.JobVersionValue WHEN '0' THEN 'No' ELSE 'Yes' END )
			ELSE CONVERT(VARCHAR(20), JVD.JobVersionValue)
		END AS VALUE,
		JVTH.JV_TMPLT_DESC AS JV_TMPLT_DESC,
		CASE
			WHEN JVTD.JV_DTYPE_ID = @SECTION_TYPE_ID THEN CAST(1 AS BIT)
			ELSE CAST(0 AS BIT)
		END AS IS_SECTION -- 11
	FROM [dbo].[advtf_job_version_load](@JobVersHdrID) JVD
		INNER JOIN JOB_VER_TMPLT_DTL JVTD ON JVD.JobVersionTemplateDetailID = JVTD.JV_TMPLT_DTL_ID
		INNER JOIN JOB_VER_DTYPE JVT ON JVTD.JV_DTYPE_ID = JVT.JV_DTYPE_ID
		INNER JOIN JOB_VER_TMPLT_HDR JVTH ON JVTH.JV_TMPLT_CODE = JVTD.JV_TMPLT_CODE;

END