SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS OFF 
GO
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[usp_wv_DeleteEmployeeCustomWallpaper]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
DROP PROCEDURE [dbo].[usp_wv_DeleteEmployeeCustomWallpaper]
GO
CREATE PROCEDURE [dbo].[usp_wv_DeleteEmployeeCustomWallpaper] /*WITH ENCRYPTION*/
@EMP_CODE VARCHAR(6),
@USER_CODE VARCHAR(100)
AS
/*=========== QUERY ===========*/
	DECLARE @FILENAME VARCHAR(500)

	SELECT @FILENAME = VARIABLE_VALUE FROM APP_VARS WITH(NOLOCK)
	WHERE UPPER(USERID) = UPPER(@USER_CODE) 
	AND [APPLICATION] = 'MY_SETTINGS' 
	AND (VARIABLE_NAME = 'MY_WALLPAPER');

	UPDATE APP_VARS WITH(ROWLOCK) 
	SET VARIABLE_VALUE = '' 
	WHERE UPPER(USERID) = UPPER(@USER_CODE)
	AND [APPLICATION] = 'MY_SETTINGS' 
	AND (VARIABLE_NAME = 'WALLPAPER' OR VARIABLE_NAME = 'MY_WALLPAPER');

	UPDATE EMPLOYEE_PICTURE 
	SET EMP_WALLPAPER = NULL 
	WHERE EMP_CODE = @EMP_CODE;

	SELECT ISNULL(@FILENAME, '') AS [FILENAME];
/*=========== QUERY ===========*/
GO
SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO