SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS OFF 
GO
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[usp_wv_ts_DefaultFunctionAndDept]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
DROP PROCEDURE [dbo].[usp_wv_ts_DefaultFunctionAndDept]
GO
CREATE PROCEDURE [dbo].[usp_wv_ts_DefaultFunctionAndDept] /*WITH ENCRYPTION*/
@EMP_CODE VARCHAR(6),
@JOB_NUMBER INT,
@JOB_COMPONENT_NBR SMALLINT,
@SEQ_NBR SMALLINT
AS
/*=========== QUERY ===========*/
	DECLARE 
		@EMP_DEF_FNC_CODE AS VARCHAR(6), 
		@TASK_TRF_CODE AS VARCHAR(6), 
		@TASK_FNC_CODE AS VARCHAR(6),
		
		@EMP_DP_TM_CODE AS VARCHAR(4),
		@TASK_DP_TM_CODE AS VARCHAR(4),
		@FUNCTION_DP_TM_CODE AS VARCHAR(4),
		@JOB_COMPONENT_DP_TM_CODE AS VARCHAR(4)
		
	SELECT @EMP_DP_TM_CODE = DP_TM_CODE, @EMP_DEF_FNC_CODE = DEF_FNC_CODE FROM EMPLOYEE WITH(NOLOCK) WHERE EMP_CODE = @EMP_CODE;

	IF @EMP_DP_TM_CODE IS NULL OR RTRIM(LTRIM(@EMP_DP_TM_CODE)) = ''
	BEGIN
		SET @EMP_DP_TM_CODE = (SELECT TOP 1 DP_TM_CODE FROM EMP_DP_TM WITH(NOLOCK) WHERE EMP_CODE = @EMP_CODE ORDER BY DP_TM_DESC)
	END
	
	SET @JOB_NUMBER = ISNULL(@JOB_NUMBER, 0);
	SET @JOB_COMPONENT_NBR = ISNULL(@JOB_COMPONENT_NBR, 0);
	SET @SEQ_NBR = ISNULL(@SEQ_NBR, -1);
	
	IF @JOB_NUMBER > 0 AND @JOB_COMPONENT_NBR > 0 
	BEGIN
		SELECT @JOB_COMPONENT_DP_TM_CODE = DP_TM_CODE FROM JOB_COMPONENT WITH(NOLOCK) WHERE JOB_NUMBER = @JOB_NUMBER AND JOB_COMPONENT_NBR = @JOB_COMPONENT_NBR;		
	END
	
	IF @JOB_NUMBER > 0 AND @JOB_COMPONENT_NBR > 0 AND @SEQ_NBR > -1
	BEGIN
	
		SELECT     
			@TASK_TRF_CODE = JOB_TRAFFIC_DET.FNC_EST, 
			@TASK_DP_TM_CODE = DEPT_TEAM.DP_TM_CODE
		FROM         JOB_TRAFFIC_DET WITH(NOLOCK) INNER JOIN
							  JOB_COMPONENT WITH(NOLOCK) ON JOB_TRAFFIC_DET.JOB_NUMBER = JOB_COMPONENT.JOB_NUMBER AND 
							  JOB_TRAFFIC_DET.JOB_COMPONENT_NBR = JOB_COMPONENT.JOB_COMPONENT_NBR LEFT OUTER JOIN
							  DEPT_TEAM WITH(NOLOCK) ON JOB_COMPONENT.DP_TM_CODE = DEPT_TEAM.DP_TM_CODE                      						                       
		WHERE    (JOB_TRAFFIC_DET.JOB_NUMBER = @JOB_NUMBER) 
							AND (JOB_TRAFFIC_DET.JOB_COMPONENT_NBR = @JOB_COMPONENT_NBR) 
							AND (JOB_TRAFFIC_DET.SEQ_NBR = @SEQ_NBR);
							
		IF NOT @TASK_TRF_CODE IS NULL
		BEGIN
		
			SELECT     
				@TASK_FNC_CODE = FUNCTIONS.FNC_CODE, 
				@FUNCTION_DP_TM_CODE = FUNCTIONS.DP_TM_CODE
			FROM FUNCTIONS WITH(NOLOCK)
			WHERE FUNCTIONS.FNC_CODE = @TASK_TRF_CODE AND (FUNCTIONS.FNC_INACTIVE = 0 OR FUNCTIONS.FNC_INACTIVE IS NULL);
			
		END
		
	END	
	
	SELECT 
		COALESCE(@TASK_TRF_CODE, @EMP_DEF_FNC_CODE, @TASK_FNC_CODE) AS FNC_CODE, 
		COALESCE(@FUNCTION_DP_TM_CODE, @EMP_DP_TM_CODE) AS DP_TM_CODE,
		COALESCE(@TASK_TRF_CODE, @EMP_DEF_FNC_CODE, @TASK_FNC_CODE) AS FunctionCode, 
		COALESCE(@FUNCTION_DP_TM_CODE, @EMP_DP_TM_CODE) AS DepartmentCode
	;
	
	
/*=========== QUERY ===========*/
GO
SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO