
CREATE PROCEDURE usp_wv_Estimating_Print_Details_JVS
	@JobNum	integer,
	@JobCompNum integer
AS

SET NOCOUNT ON



SELECT     JOB_VER_HDR.JOB_NUMBER, JOB_VER_HDR.JOB_COMPONENT_NBR, JOB_VER_DTL.JOB_VER_HDR_ID, 
                      JOB_VER_DTL.JV_TMPLT_DTL_ID, JOB_VER_DTL.JOB_VER_VALUE, JOB_VER_TMPLT_HDR.JV_TMPLT_CODE, JOB_VER_TMPLT_DTL.JV_TMPLT_LABEL
FROM         JOB_VER_HDR INNER JOIN
                      JOB_VER_DTL ON JOB_VER_HDR.JOB_VER_HDR_ID = JOB_VER_DTL.JOB_VER_HDR_ID INNER JOIN
                      JOB_VER_TMPLT_HDR ON JOB_VER_HDR.JV_TMPLT_CODE = JOB_VER_TMPLT_HDR.JV_TMPLT_CODE INNER JOIN
                      JOB_VER_TMPLT_DTL ON JOB_VER_DTL.JV_TMPLT_DTL_ID = JOB_VER_TMPLT_DTL.JV_TMPLT_DTL_ID
WHERE     (JOB_VER_HDR.JOB_NUMBER = @JobNum) AND (JOB_VER_HDR.JOB_COMPONENT_NBR = @JobCompNum)



SET QUOTED_IDENTIFIER ON 
