if exists (select * from sysobjects where id = object_id(N'[dbo].[usp_wv_DocumentManager_GetCampaignDocuments]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [dbo].[usp_wv_DocumentManager_GetCampaignDocuments]
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS OFF 
GO


CREATE PROCEDURE [dbo].[usp_wv_DocumentManager_GetCampaignDocuments]
@CMP_ID Int,
@Private Int,
@User varchar(100)
AS

DECLARE @CMP_STR AS VARCHAR(15)
DECLARE @sql as varchar(4000)

SELECT @CMP_STR = CAST(@CMP_ID AS VARCHAR(15))
				
set @sql = 'SELECT ''Campaign Document'' AS LEVEL, CAMPAIGN.CMP_CODE, CAMPAIGN.CMP_NAME, DOCUMENTS.DOCUMENT_ID, DOCUMENTS.FILENAME, 
  DOCUMENTS.MIME_TYPE, DOCUMENTS.DESCRIPTION, DOCUMENTS.KEYWORDS, DOCUMENTS.UPLOADED_DATE, 
  DOCUMENTS.USER_CODE, DOCUMENTS.FILE_SIZE, SEC_USER.USER_NAME, DOCUMENTS.REPOSITORY_FILENAME, 
  DOCUMENT_TYPE.DOCUMENT_TYPE_DESC, ISNULL(DOCUMENTS.PRIVATE_FLAG,0) AS PRIVATE_FLAG 
FROM CAMPAIGN_DOCUMENTS 
  INNER JOIN CAMPAIGN ON CAMPAIGN_DOCUMENTS.CMP_IDENTIFIER = CAMPAIGN.CMP_IDENTIFIER 
  INNER JOIN DOCUMENTS ON CAMPAIGN_DOCUMENTS.DOCUMENT_ID = DOCUMENTS.DOCUMENT_ID AND ( DOCUMENTS.PRIVATE_FLAG = 0 OR DOCUMENTS.PRIVATE_FLAG IS NULL '
 
 If @Private = 1	-- Has access to private files  
	set @sql = @sql + ' OR DOCUMENTS.PRIVATE_FLAG = 1 ' 

set @sql = @sql + ')'
  
 set @sql = @sql + ' INNER JOIN DOCUMENT_TYPE ON DOCUMENTS.DOCUMENT_TYPE_ID = DOCUMENT_TYPE.DOCUMENT_TYPE_ID 
  LEFT OUTER JOIN SEC_USER ON UPPER(DOCUMENTS.USER_CODE) = UPPER(SEC_USER.USER_CODE) '
  
  
set @sql = @sql + ' WHERE CAMPAIGN_DOCUMENTS.CMP_IDENTIFIER = ' + @CMP_STR 


EXEC(@sql)
--print(@sql)

GO
SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO
