
CREATE PROCEDURE [dbo].[usp_wv_Estimating_AddNew_GetTaxData] 
@TAX_CODE VARCHAR(4)
AS

    SELECT     
	    TAX_CODE, 
	    TAX_DESCRIPTION, 
	    ISNULL(TAX_STATE_PERCENT,0) AS TAX_STATE_PERCENT,
		ISNULL(TAX_COUNTY_PERCENT,0) AS TAX_COUNTY_PERCENT,
		ISNULL(TAX_CITY_PERCENT,0) AS TAX_CITY_PERCENT, 
		ISNULL(TAX_RESALE,0) as TAX_RESALE
    FROM         
	    SALES_TAX WITH(NOLOCK)
    WHERE     
	    (TAX_CODE = @TAX_CODE)
	    AND
	    ((INACTIVE_FLAG = 0) OR
                      (INACTIVE_FLAG IS NULL))
	    
