

CREATE PROCEDURE [dbo].[usp_wv_Traffic_Schedule_CountTasks]
@JobNum AS INT,
@JobCompNum AS INT
AS




SELECT	
	COUNT(1)
FROM  
	JOB_COMPONENT WITH(NOLOCK) INNER JOIN
	JOB_TRAFFIC WITH(NOLOCK)  ON JOB_COMPONENT.JOB_NUMBER = JOB_TRAFFIC.JOB_NUMBER AND 
	JOB_COMPONENT.JOB_COMPONENT_NBR = JOB_TRAFFIC.JOB_COMPONENT_NBR INNER JOIN
	JOB_TRAFFIC_DET  WITH(NOLOCK) ON JOB_TRAFFIC_DET.JOB_NUMBER = JOB_TRAFFIC.JOB_NUMBER AND 
	JOB_TRAFFIC_DET.JOB_COMPONENT_NBR = JOB_TRAFFIC.JOB_COMPONENT_NBR INNER JOIN
	JOB_LOG  WITH(NOLOCK) ON JOB_TRAFFIC.JOB_NUMBER = JOB_LOG.JOB_NUMBER LEFT OUTER JOIN
	TRAFFIC_PHASE  WITH(NOLOCK) ON JOB_TRAFFIC_DET.TRAFFIC_PHASE_ID = TRAFFIC_PHASE.TRAFFIC_PHASE_ID LEFT OUTER JOIN
	TASK_TRAFFIC_ROLE WITH(NOLOCK)  ON JOB_TRAFFIC_DET.FNC_CODE = TASK_TRAFFIC_ROLE.TRF_CODE LEFT OUTER JOIN
	EMP_TRAFFIC_ROLE  WITH(NOLOCK) ON JOB_TRAFFIC_DET.EMP_CODE = EMP_TRAFFIC_ROLE.EMP_CODE
WHERE  
	(NOT (JOB_COMPONENT.JOB_PROCESS_CONTRL IN (6, 12)))
	AND JOB_TRAFFIC.COMPLETED_DATE IS NULL
	AND JOB_LOG.JOB_NUMBER = @JobNum
	AND JOB_TRAFFIC.JOB_COMPONENT_NBR = @JobCompNum




