

CREATE PROCEDURE [dbo].[usp_wv_Job_Template_GetTemplates] AS

SET NOCOUNT ON

SELECT     
	DISTINCT JOB_TMPLT_CODE as Code, ISNULL(JOB_TMPLT_DESC, JOB_TMPLT_CODE) as Description
FROM
	JOB_TMPLT_HDR
WHERE ( INACTIVE_FLAG = 0 OR INACTIVE_FLAG IS NULL )



