
CREATE PROCEDURE [dbo].[usp_wv_LOOKUP_DIVISION_HAS_ONE_CLIENT] /*WITH ENCRYPTION*/
@DIV_CODE  VARCHAR(6)
AS
/*=========== QUERY ===========*/
	DECLARE @CT        INT

	SELECT @CT = COUNT(1)
	FROM   CLIENT WITH(NOLOCK)
		   INNER JOIN DIVISION WITH(NOLOCK)
				ON  CLIENT.CL_CODE = DIVISION.CL_CODE
	WHERE  DIVISION.DIV_CODE = @DIV_CODE;	
	SET @CT = ISNULL(@CT, 0);

	IF @CT = 1
	BEGIN
		SELECT 1 AS HAS_ONE_CLIENT,
			   CLIENT.CL_CODE,
			   CLIENT.CL_NAME,
			   DIVISION.DIV_CODE,
			   DIVISION.DIV_NAME
		FROM   CLIENT WITH(NOLOCK)
			   INNER JOIN DIVISION WITH(NOLOCK)
					ON  CLIENT.CL_CODE = DIVISION.CL_CODE
		WHERE  DIVISION.DIV_CODE = @DIV_CODE;
	END
	ELSE
	BEGIN
		SELECT 0 AS HAS_ONE_CLIENT,
			   NULL AS CL_CODE,
			   NULL AS CL_NAME,
			   NULL AS DIV_CODE,
			   NULL AS DIV_NAME;
	END
/*=========== QUERY ===========*/
