







CREATE PROCEDURE [dbo].[usp_wv_job_GetTrafficAssignments]
@JobNum INT,
@JobCompNum INT
AS

SELECT     JOB_TRAFFIC.ASSIGN_1 AS EmpCode, EMPLOYEE.EMP_FNAME, EMPLOYEE.EMP_MI, EMPLOYEE.EMP_LNAME, '1' AS Type
FROM         JOB_TRAFFIC INNER JOIN
                      EMPLOYEE ON JOB_TRAFFIC.ASSIGN_1 = EMPLOYEE.EMP_CODE
WHERE     (JOB_TRAFFIC.JOB_NUMBER = @JobNum) AND (JOB_TRAFFIC.JOB_COMPONENT_NBR = @JobCompNum)
UNION
SELECT     JOB_TRAFFIC.ASSIGN_2 AS EmpCode, EMPLOYEE.EMP_FNAME, EMPLOYEE.EMP_MI, EMPLOYEE.EMP_LNAME, '2' AS Type
FROM         JOB_TRAFFIC INNER JOIN
                      EMPLOYEE ON JOB_TRAFFIC.ASSIGN_2 = EMPLOYEE.EMP_CODE
WHERE     (JOB_TRAFFIC.JOB_NUMBER = @JobNum) AND (JOB_TRAFFIC.JOB_COMPONENT_NBR = @JobCompNum)
UNION
SELECT     JOB_TRAFFIC.ASSIGN_3 AS EmpCode, EMPLOYEE.EMP_FNAME, EMPLOYEE.EMP_MI, EMPLOYEE.EMP_LNAME, '3' AS Type
FROM         JOB_TRAFFIC INNER JOIN
                      EMPLOYEE ON JOB_TRAFFIC.ASSIGN_3 = EMPLOYEE.EMP_CODE
WHERE     (JOB_TRAFFIC.JOB_NUMBER = @JobNum) AND (JOB_TRAFFIC.JOB_COMPONENT_NBR = @JobCompNum)
UNION
SELECT     JOB_TRAFFIC.ASSIGN_4 AS EmpCode, EMPLOYEE.EMP_FNAME, EMPLOYEE.EMP_MI, EMPLOYEE.EMP_LNAME, '4' AS Type
FROM         JOB_TRAFFIC INNER JOIN
                      EMPLOYEE ON JOB_TRAFFIC.ASSIGN_4 = EMPLOYEE.EMP_CODE
WHERE     (JOB_TRAFFIC.JOB_NUMBER = @JobNum) AND (JOB_TRAFFIC.JOB_COMPONENT_NBR = @JobCompNum)
UNION
SELECT     JOB_TRAFFIC.ASSIGN_5 AS EmpCode, EMPLOYEE.EMP_FNAME, EMPLOYEE.EMP_MI, EMPLOYEE.EMP_LNAME, '5' AS Type
FROM         JOB_TRAFFIC INNER JOIN
                      EMPLOYEE ON JOB_TRAFFIC.ASSIGN_5 = EMPLOYEE.EMP_CODE
WHERE     (JOB_TRAFFIC.JOB_NUMBER = @JobNum) AND (JOB_TRAFFIC.JOB_COMPONENT_NBR = @JobCompNum)



















