CREATE PROCEDURE [dbo].[usp_wv_sum_rep_by_client]
@UserID as VarChar(100),
@Start_Date smalldatetime,
@End_Date smalldatetime,
@IncludeCS Char(1),
@AEs Varchar(4000),
@CP as int,
@CPID as int
AS

Declare @Rescrictions Int, @RestrictionsCP Int

DECLARE @EMP_CDE AS VARCHAR(6)
DECLARE @RestrictionsOffice AS INTEGER

SELECT @EMP_CDE = EMP_CODE FROM SEC_USER WHERE UPPER(USER_CODE) = UPPER(@UserID)

SELECT @RestrictionsOffice = COUNT(*) FROM EMP_OFFICE WHERE EMP_CODE = @EMP_CDE

Select @Rescrictions = Count(*) 
FROM SEC_CLIENT
Where UPPER(USER_ID) = UPPER(@UserID) 

Select @RestrictionsCP = Count(*) 
FROM CP_SEC_CLIENT
Where CDP_CONTACT_ID = @CPID
IF @CP = 1
	BEGIN
		If @AEs = '%'  
		   BEGIN
			If @RestrictionsCP > 0
				BEGIN
					if @IncludeCS = '1'
					BEGIN
						SELECT     dbo.JOB_LOG.CL_CODE, dbo.JOB_LOG.DIV_CODE, dbo.JOB_LOG.PRD_CODE, dbo.CLIENT.CL_NAME AS Client, dbo.DIVISION.DIV_NAME AS Division, 
								  dbo.PRODUCT.PRD_DESCRIPTION AS Product, dbo.JOB_LOG.JOB_NUMBER, dbo.JOB_LOG.OFFICE_CODE, dbo.JOB_LOG.JOB_DESC, 
								  dbo.JOB_LOG.JOB_CLI_REF, dbo.JOB_COMPONENT.JOB_COMPONENT_NBR, dbo.JOB_COMPONENT.JOB_COMP_DESC, 
								  dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL, dbo.JOB_COMPONENT.JOB_COMP_DATE, dbo.EMPLOYEE.EMP_CODE, 
								  dbo.EMPLOYEE.EMP_FNAME + ' ' + dbo.EMPLOYEE.EMP_LNAME AS [Account Executive], dbo.JOB_COMPONENT.START_DATE AS [Start Date],
								  dbo.JOB_COMPONENT.JOB_FIRST_USE_DATE AS [Due Date], dbo.JOB_LOG.USER_ID AS [User ID], 
								  dbo.CLIENT.CL_NAME + ' - ' + dbo.DIVISION.DIV_NAME + ' - ' + dbo.PRODUCT.PRD_DESCRIPTION AS CDP, dbo.JOB_LOG.SC_CODE, 
								  dbo.SALES_CLASS.SC_DESCRIPTION, dbo.JOB_TRAFFIC.COMPLETED_DATE, dbo.JOB_TRAFFIC.ROWID, dbo.JOB_TRAFFIC.TRF_COMMENTS, 
								  dbo.JOB_COMPONENT.TRF_SCHEDULE_REQ, dbo.JOB_TYPE.JT_CODE, dbo.JOB_TYPE.JT_DESC, dbo.TRAFFIC.TRF_CODE, 
								  dbo.TRAFFIC.TRF_DESCRIPTION, dbo.JOB_COMPONENT.ESTIMATE_NUMBER, dbo.ESTIMATE_APPROVAL.JOB_NUMBER AS EJobNum, 
								  dbo.ESTIMATE_APPROVAL.JOB_COMPONENT_NBR AS EJobComNum, JOB_TRAFFIC.MGR_EMP_CODE, dbo.JOB_COMPONENT.JOB_QTY
						FROM         dbo.JOB_LOG INNER JOIN
											  dbo.JOB_COMPONENT ON dbo.JOB_LOG.JOB_NUMBER = dbo.JOB_COMPONENT.JOB_NUMBER INNER JOIN
											  dbo.EMPLOYEE ON dbo.JOB_COMPONENT.EMP_CODE = dbo.EMPLOYEE.EMP_CODE LEFT OUTER JOIN
											  dbo.JOB_TYPE ON dbo.JOB_COMPONENT.JT_CODE = dbo.JOB_TYPE.JT_CODE INNER JOIN
											  dbo.CLIENT ON dbo.JOB_LOG.CL_CODE = dbo.CLIENT.CL_CODE INNER JOIN
											  dbo.PRODUCT ON dbo.JOB_LOG.CL_CODE = dbo.PRODUCT.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.PRODUCT.DIV_CODE AND 
											  dbo.JOB_LOG.PRD_CODE = dbo.PRODUCT.PRD_CODE INNER JOIN
											  dbo.DIVISION ON dbo.JOB_LOG.CL_CODE = dbo.DIVISION.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.DIVISION.DIV_CODE INNER JOIN
											  dbo.CP_SEC_CLIENT ON dbo.JOB_LOG.CL_CODE = dbo.CP_SEC_CLIENT.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.CP_SEC_CLIENT.DIV_CODE AND 
											  dbo.JOB_LOG.PRD_CODE = dbo.CP_SEC_CLIENT.PRD_CODE INNER JOIN
											  dbo.SALES_CLASS ON dbo.JOB_LOG.SC_CODE = dbo.SALES_CLASS.SC_CODE INNER JOIN
											  dbo.JOB_TRAFFIC ON dbo.JOB_LOG.JOB_NUMBER = dbo.JOB_TRAFFIC.JOB_NUMBER AND 
											  dbo.JOB_COMPONENT.JOB_COMPONENT_NBR = dbo.JOB_TRAFFIC.JOB_COMPONENT_NBR LEFT OUTER JOIN
											  dbo.TRAFFIC ON dbo.JOB_TRAFFIC.TRF_CODE = dbo.TRAFFIC.TRF_CODE LEFT OUTER JOIN
											  dbo.ESTIMATE_APPROVAL ON dbo.JOB_COMPONENT.JOB_NUMBER = dbo.ESTIMATE_APPROVAL.JOB_NUMBER AND 
											  dbo.JOB_COMPONENT.JOB_COMPONENT_NBR = dbo.ESTIMATE_APPROVAL.JOB_COMPONENT_NBR
						WHERE     (dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL <> 6) AND (dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL <> 12) AND 
											  (JOB_COMPONENT.JOB_FIRST_USE_DATE >= @Start_Date AND JOB_COMPONENT.JOB_FIRST_USE_DATE <= @End_Date) AND CP_SEC_CLIENT.CDP_CONTACT_ID = @CPID
						order by JOB_LOG.CL_CODE,
							JOB_LOG.DIV_CODE,
							JOB_LOG.PRD_CODE,
							JOB_COMPONENT.JOB_NUMBER, JOB_COMPONENT.JOB_COMPONENT_NBR
					END
					Else
					BEGIN
						SELECT     dbo.JOB_LOG.CL_CODE, dbo.JOB_LOG.DIV_CODE, dbo.JOB_LOG.PRD_CODE, dbo.CLIENT.CL_NAME AS Client, dbo.DIVISION.DIV_NAME AS Division, 
								  dbo.PRODUCT.PRD_DESCRIPTION AS Product, dbo.JOB_LOG.JOB_NUMBER, dbo.JOB_LOG.OFFICE_CODE, dbo.JOB_LOG.JOB_DESC, 
								  dbo.JOB_LOG.JOB_CLI_REF, dbo.JOB_COMPONENT.JOB_COMPONENT_NBR, dbo.JOB_COMPONENT.JOB_COMP_DESC, 
								  dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL, dbo.JOB_COMPONENT.JOB_COMP_DATE, dbo.EMPLOYEE.EMP_CODE, 
								  dbo.EMPLOYEE.EMP_FNAME + ' ' + dbo.EMPLOYEE.EMP_LNAME AS [Account Executive], dbo.JOB_COMPONENT.START_DATE AS [Start Date],
								  dbo.JOB_COMPONENT.JOB_FIRST_USE_DATE AS [Due Date], dbo.JOB_LOG.USER_ID AS [User ID], 
								  dbo.CLIENT.CL_NAME + ' - ' + dbo.DIVISION.DIV_NAME + ' - ' + dbo.PRODUCT.PRD_DESCRIPTION AS CDP, dbo.JOB_LOG.SC_CODE, 
								  dbo.SALES_CLASS.SC_DESCRIPTION, dbo.JOB_TRAFFIC.COMPLETED_DATE, dbo.JOB_TRAFFIC.ROWID, dbo.JOB_TRAFFIC.TRF_COMMENTS, 
								  dbo.JOB_COMPONENT.TRF_SCHEDULE_REQ, dbo.JOB_TYPE.JT_CODE, dbo.JOB_TYPE.JT_DESC, dbo.TRAFFIC.TRF_CODE, 
								  dbo.TRAFFIC.TRF_DESCRIPTION, dbo.JOB_COMPONENT.ESTIMATE_NUMBER, dbo.ESTIMATE_APPROVAL.JOB_NUMBER AS EJobNum, 
								  dbo.ESTIMATE_APPROVAL.JOB_COMPONENT_NBR AS EJobComNum, JOB_TRAFFIC.MGR_EMP_CODE, dbo.JOB_COMPONENT.JOB_QTY
						FROM         dbo.JOB_LOG INNER JOIN
											  dbo.JOB_COMPONENT ON dbo.JOB_LOG.JOB_NUMBER = dbo.JOB_COMPONENT.JOB_NUMBER INNER JOIN
											  dbo.EMPLOYEE ON dbo.JOB_COMPONENT.EMP_CODE = dbo.EMPLOYEE.EMP_CODE LEFT OUTER JOIN
											  dbo.JOB_TYPE ON dbo.JOB_COMPONENT.JT_CODE = dbo.JOB_TYPE.JT_CODE INNER JOIN
											  dbo.CLIENT ON dbo.JOB_LOG.CL_CODE = dbo.CLIENT.CL_CODE INNER JOIN
											  dbo.PRODUCT ON dbo.JOB_LOG.CL_CODE = dbo.PRODUCT.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.PRODUCT.DIV_CODE AND 
											  dbo.JOB_LOG.PRD_CODE = dbo.PRODUCT.PRD_CODE INNER JOIN
											  dbo.DIVISION ON dbo.JOB_LOG.CL_CODE = dbo.DIVISION.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.DIVISION.DIV_CODE INNER JOIN
											  dbo.CP_SEC_CLIENT ON dbo.JOB_LOG.CL_CODE = dbo.CP_SEC_CLIENT.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.CP_SEC_CLIENT.DIV_CODE AND 
											  dbo.JOB_LOG.PRD_CODE = dbo.CP_SEC_CLIENT.PRD_CODE INNER JOIN
											  dbo.SALES_CLASS ON dbo.JOB_LOG.SC_CODE = dbo.SALES_CLASS.SC_CODE INNER JOIN
											  dbo.JOB_TRAFFIC ON dbo.JOB_LOG.JOB_NUMBER = dbo.JOB_TRAFFIC.JOB_NUMBER AND 
											  dbo.JOB_COMPONENT.JOB_COMPONENT_NBR = dbo.JOB_TRAFFIC.JOB_COMPONENT_NBR LEFT OUTER JOIN
											  dbo.TRAFFIC ON dbo.JOB_TRAFFIC.TRF_CODE = dbo.TRAFFIC.TRF_CODE LEFT OUTER JOIN
											  dbo.ESTIMATE_APPROVAL ON dbo.JOB_COMPONENT.JOB_NUMBER = dbo.ESTIMATE_APPROVAL.JOB_NUMBER AND 
											  dbo.JOB_COMPONENT.JOB_COMPONENT_NBR = dbo.ESTIMATE_APPROVAL.JOB_COMPONENT_NBR
						WHERE     (dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL <> 6) AND (dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL <> 12) AND 
											  (dbo.JOB_TRAFFIC.COMPLETED_DATE IS NULL) AND (JOB_COMPONENT.JOB_FIRST_USE_DATE >= @Start_Date AND JOB_COMPONENT.JOB_FIRST_USE_DATE <= @End_Date) AND CP_SEC_CLIENT.CDP_CONTACT_ID = @CPID
						order by JOB_LOG.CL_CODE,
							JOB_LOG.DIV_CODE,
							JOB_LOG.PRD_CODE,
							JOB_COMPONENT.JOB_NUMBER, JOB_COMPONENT.JOB_COMPONENT_NBR
					END
		
				END
			ELSE
				BEGIN
					If @IncludeCS = '1'
					BEGIN
						SELECT     dbo.JOB_LOG.CL_CODE, dbo.JOB_LOG.DIV_CODE, dbo.JOB_LOG.PRD_CODE, dbo.CLIENT.CL_NAME AS Client, dbo.DIVISION.DIV_NAME AS Division, 
								  dbo.PRODUCT.PRD_DESCRIPTION AS Product, dbo.JOB_LOG.JOB_NUMBER, dbo.JOB_LOG.OFFICE_CODE, dbo.JOB_LOG.JOB_DESC, 
								  dbo.JOB_LOG.JOB_CLI_REF, dbo.JOB_COMPONENT.JOB_COMPONENT_NBR, dbo.JOB_COMPONENT.JOB_COMP_DESC, 
								  dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL, dbo.JOB_COMPONENT.JOB_COMP_DATE, dbo.EMPLOYEE.EMP_CODE, 
								  dbo.EMPLOYEE.EMP_FNAME + ' ' + dbo.EMPLOYEE.EMP_LNAME AS [Account Executive], dbo.JOB_COMPONENT.START_DATE AS [Start Date],
								  dbo.JOB_COMPONENT.JOB_FIRST_USE_DATE AS [Due Date], dbo.JOB_LOG.USER_ID AS [User ID], 
								  dbo.CLIENT.CL_NAME + ' - ' + dbo.DIVISION.DIV_NAME + ' - ' + dbo.PRODUCT.PRD_DESCRIPTION AS CDP, dbo.JOB_LOG.SC_CODE, 
								  dbo.SALES_CLASS.SC_DESCRIPTION, dbo.JOB_TRAFFIC.COMPLETED_DATE, dbo.JOB_TRAFFIC.ROWID, dbo.JOB_TRAFFIC.TRF_COMMENTS, 
								  dbo.JOB_COMPONENT.TRF_SCHEDULE_REQ, dbo.JOB_TYPE.JT_CODE, dbo.JOB_TYPE.JT_DESC, dbo.TRAFFIC.TRF_CODE, 
								  dbo.TRAFFIC.TRF_DESCRIPTION, dbo.JOB_COMPONENT.ESTIMATE_NUMBER, dbo.ESTIMATE_APPROVAL.JOB_NUMBER AS EJobNum, 
								  dbo.ESTIMATE_APPROVAL.JOB_COMPONENT_NBR AS EJobComNum, JOB_TRAFFIC.MGR_EMP_CODE, dbo.JOB_COMPONENT.JOB_QTY
						FROM         dbo.JOB_LOG INNER JOIN
											  dbo.JOB_COMPONENT ON dbo.JOB_LOG.JOB_NUMBER = dbo.JOB_COMPONENT.JOB_NUMBER INNER JOIN
											  dbo.EMPLOYEE ON dbo.JOB_COMPONENT.EMP_CODE = dbo.EMPLOYEE.EMP_CODE LEFT OUTER JOIN
											  dbo.JOB_TYPE ON dbo.JOB_COMPONENT.JT_CODE = dbo.JOB_TYPE.JT_CODE INNER JOIN
											  dbo.CLIENT ON dbo.JOB_LOG.CL_CODE = dbo.CLIENT.CL_CODE INNER JOIN
											  dbo.PRODUCT ON dbo.JOB_LOG.CL_CODE = dbo.PRODUCT.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.PRODUCT.DIV_CODE AND 
											  dbo.JOB_LOG.PRD_CODE = dbo.PRODUCT.PRD_CODE INNER JOIN
											  dbo.DIVISION ON dbo.JOB_LOG.CL_CODE = dbo.DIVISION.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.DIVISION.DIV_CODE INNER JOIN
											  dbo.SALES_CLASS ON dbo.JOB_LOG.SC_CODE = dbo.SALES_CLASS.SC_CODE INNER JOIN
											  dbo.JOB_TRAFFIC ON dbo.JOB_LOG.JOB_NUMBER = dbo.JOB_TRAFFIC.JOB_NUMBER AND 
											  dbo.JOB_COMPONENT.JOB_COMPONENT_NBR = dbo.JOB_TRAFFIC.JOB_COMPONENT_NBR LEFT OUTER JOIN
											  dbo.TRAFFIC ON dbo.JOB_TRAFFIC.TRF_CODE = dbo.TRAFFIC.TRF_CODE LEFT OUTER JOIN
											  dbo.ESTIMATE_APPROVAL ON dbo.JOB_COMPONENT.JOB_NUMBER = dbo.ESTIMATE_APPROVAL.JOB_NUMBER AND 
											  dbo.JOB_COMPONENT.JOB_COMPONENT_NBR = dbo.ESTIMATE_APPROVAL.JOB_COMPONENT_NBR
						WHERE     (dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL <> 6) AND (dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL <> 12) AND 
											  (JOB_COMPONENT.JOB_FIRST_USE_DATE >= @Start_Date AND JOB_COMPONENT.JOB_FIRST_USE_DATE <= @End_Date)
						order by JOB_LOG.CL_CODE,
							JOB_LOG.DIV_CODE,
							JOB_LOG.PRD_CODE,
							JOB_COMPONENT.JOB_NUMBER, JOB_COMPONENT.JOB_COMPONENT_NBR
					END
					Else
					BEGIN
						SELECT     dbo.JOB_LOG.CL_CODE, dbo.JOB_LOG.DIV_CODE, dbo.JOB_LOG.PRD_CODE, dbo.CLIENT.CL_NAME AS Client, dbo.DIVISION.DIV_NAME AS Division, 
								  dbo.PRODUCT.PRD_DESCRIPTION AS Product, dbo.JOB_LOG.JOB_NUMBER, dbo.JOB_LOG.OFFICE_CODE, dbo.JOB_LOG.JOB_DESC, 
								  dbo.JOB_LOG.JOB_CLI_REF, dbo.JOB_COMPONENT.JOB_COMPONENT_NBR, dbo.JOB_COMPONENT.JOB_COMP_DESC, 
								  dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL, dbo.JOB_COMPONENT.JOB_COMP_DATE, dbo.EMPLOYEE.EMP_CODE, 
								  dbo.EMPLOYEE.EMP_FNAME + ' ' + dbo.EMPLOYEE.EMP_LNAME AS [Account Executive], dbo.JOB_COMPONENT.START_DATE AS [Start Date],
								  dbo.JOB_COMPONENT.JOB_FIRST_USE_DATE AS [Due Date], dbo.JOB_LOG.USER_ID AS [User ID], 
								  dbo.CLIENT.CL_NAME + ' - ' + dbo.DIVISION.DIV_NAME + ' - ' + dbo.PRODUCT.PRD_DESCRIPTION AS CDP, dbo.JOB_LOG.SC_CODE, 
								  dbo.SALES_CLASS.SC_DESCRIPTION, dbo.JOB_TRAFFIC.COMPLETED_DATE, dbo.JOB_TRAFFIC.ROWID, dbo.JOB_TRAFFIC.TRF_COMMENTS, 
								  dbo.JOB_COMPONENT.TRF_SCHEDULE_REQ, dbo.JOB_TYPE.JT_CODE, dbo.JOB_TYPE.JT_DESC, dbo.TRAFFIC.TRF_CODE, 
								  dbo.TRAFFIC.TRF_DESCRIPTION, dbo.JOB_COMPONENT.ESTIMATE_NUMBER, dbo.ESTIMATE_APPROVAL.JOB_NUMBER AS EJobNum, 
								  dbo.ESTIMATE_APPROVAL.JOB_COMPONENT_NBR AS EJobComNum, JOB_TRAFFIC.MGR_EMP_CODE, dbo.JOB_COMPONENT.JOB_QTY
						FROM         dbo.JOB_LOG INNER JOIN
											  dbo.JOB_COMPONENT ON dbo.JOB_LOG.JOB_NUMBER = dbo.JOB_COMPONENT.JOB_NUMBER INNER JOIN
											  dbo.EMPLOYEE ON dbo.JOB_COMPONENT.EMP_CODE = dbo.EMPLOYEE.EMP_CODE LEFT OUTER JOIN
											  dbo.JOB_TYPE ON dbo.JOB_COMPONENT.JT_CODE = dbo.JOB_TYPE.JT_CODE INNER JOIN
											  dbo.CLIENT ON dbo.JOB_LOG.CL_CODE = dbo.CLIENT.CL_CODE INNER JOIN
											  dbo.PRODUCT ON dbo.JOB_LOG.CL_CODE = dbo.PRODUCT.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.PRODUCT.DIV_CODE AND 
											  dbo.JOB_LOG.PRD_CODE = dbo.PRODUCT.PRD_CODE INNER JOIN
											  dbo.DIVISION ON dbo.JOB_LOG.CL_CODE = dbo.DIVISION.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.DIVISION.DIV_CODE INNER JOIN
											  dbo.SALES_CLASS ON dbo.JOB_LOG.SC_CODE = dbo.SALES_CLASS.SC_CODE INNER JOIN
											  dbo.JOB_TRAFFIC ON dbo.JOB_LOG.JOB_NUMBER = dbo.JOB_TRAFFIC.JOB_NUMBER AND 
											  dbo.JOB_COMPONENT.JOB_COMPONENT_NBR = dbo.JOB_TRAFFIC.JOB_COMPONENT_NBR LEFT OUTER JOIN
											  dbo.TRAFFIC ON dbo.JOB_TRAFFIC.TRF_CODE = dbo.TRAFFIC.TRF_CODE LEFT OUTER JOIN
											  dbo.ESTIMATE_APPROVAL ON dbo.JOB_COMPONENT.JOB_NUMBER = dbo.ESTIMATE_APPROVAL.JOB_NUMBER AND 
											  dbo.JOB_COMPONENT.JOB_COMPONENT_NBR = dbo.ESTIMATE_APPROVAL.JOB_COMPONENT_NBR
						WHERE     (dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL <> 6) AND (dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL <> 12) AND 
											  (dbo.JOB_TRAFFIC.COMPLETED_DATE IS NULL) AND (JOB_COMPONENT.JOB_FIRST_USE_DATE >= @Start_Date AND JOB_COMPONENT.JOB_FIRST_USE_DATE <= @End_Date)
						order by JOB_LOG.CL_CODE,
							JOB_LOG.DIV_CODE,
							JOB_LOG.PRD_CODE,
							JOB_COMPONENT.JOB_NUMBER, JOB_COMPONENT.JOB_COMPONENT_NBR
					END

				END
			END

		ELSE --@AE <> '%'
			BEGIN
				If @RestrictionsCP > 0
				BEGIN
					if @IncludeCS = '1'
					BEGIN
						SELECT     dbo.JOB_LOG.CL_CODE, dbo.JOB_LOG.DIV_CODE, dbo.JOB_LOG.PRD_CODE, dbo.CLIENT.CL_NAME AS Client, dbo.DIVISION.DIV_NAME AS Division, 
								  dbo.PRODUCT.PRD_DESCRIPTION AS Product, dbo.JOB_LOG.JOB_NUMBER, dbo.JOB_LOG.OFFICE_CODE, dbo.JOB_LOG.JOB_DESC, 
								  dbo.JOB_LOG.JOB_CLI_REF, dbo.JOB_COMPONENT.JOB_COMPONENT_NBR, dbo.JOB_COMPONENT.JOB_COMP_DESC, 
								  dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL, dbo.JOB_COMPONENT.JOB_COMP_DATE, dbo.EMPLOYEE.EMP_CODE, 
								  dbo.EMPLOYEE.EMP_FNAME + ' ' + dbo.EMPLOYEE.EMP_LNAME AS [Account Executive], dbo.JOB_COMPONENT.START_DATE AS [Start Date],
								  dbo.JOB_COMPONENT.JOB_FIRST_USE_DATE AS [Due Date], dbo.JOB_LOG.USER_ID AS [User ID], 
								  dbo.CLIENT.CL_NAME + ' - ' + dbo.DIVISION.DIV_NAME + ' - ' + dbo.PRODUCT.PRD_DESCRIPTION AS CDP, dbo.JOB_LOG.SC_CODE, 
								  dbo.SALES_CLASS.SC_DESCRIPTION, dbo.JOB_TRAFFIC.COMPLETED_DATE, dbo.JOB_TRAFFIC.ROWID, dbo.JOB_TRAFFIC.TRF_COMMENTS, 
								  dbo.JOB_COMPONENT.TRF_SCHEDULE_REQ, dbo.JOB_TYPE.JT_CODE, dbo.JOB_TYPE.JT_DESC, dbo.TRAFFIC.TRF_CODE, 
								  dbo.TRAFFIC.TRF_DESCRIPTION, dbo.JOB_COMPONENT.ESTIMATE_NUMBER, dbo.ESTIMATE_APPROVAL.JOB_NUMBER AS EJobNum, 
								  dbo.ESTIMATE_APPROVAL.JOB_COMPONENT_NBR AS EJobComNum, JOB_TRAFFIC.MGR_EMP_CODE, dbo.JOB_COMPONENT.JOB_QTY
						FROM         dbo.JOB_LOG INNER JOIN
											  dbo.JOB_COMPONENT ON dbo.JOB_LOG.JOB_NUMBER = dbo.JOB_COMPONENT.JOB_NUMBER INNER JOIN
											  dbo.EMPLOYEE ON dbo.JOB_COMPONENT.EMP_CODE = dbo.EMPLOYEE.EMP_CODE LEFT OUTER JOIN
											  dbo.JOB_TYPE ON dbo.JOB_COMPONENT.JT_CODE = dbo.JOB_TYPE.JT_CODE INNER JOIN
											  dbo.CLIENT ON dbo.JOB_LOG.CL_CODE = dbo.CLIENT.CL_CODE INNER JOIN
											  dbo.PRODUCT ON dbo.JOB_LOG.CL_CODE = dbo.PRODUCT.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.PRODUCT.DIV_CODE AND 
											  dbo.JOB_LOG.PRD_CODE = dbo.PRODUCT.PRD_CODE INNER JOIN
											  dbo.DIVISION ON dbo.JOB_LOG.CL_CODE = dbo.DIVISION.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.DIVISION.DIV_CODE INNER JOIN
											  dbo.CP_SEC_CLIENT ON dbo.JOB_LOG.CL_CODE = dbo.CP_SEC_CLIENT.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.CP_SEC_CLIENT.DIV_CODE AND 
											  dbo.JOB_LOG.PRD_CODE = dbo.CP_SEC_CLIENT.PRD_CODE INNER JOIN
											  dbo.SALES_CLASS ON dbo.JOB_LOG.SC_CODE = dbo.SALES_CLASS.SC_CODE INNER JOIN
											  dbo.JOB_TRAFFIC ON dbo.JOB_LOG.JOB_NUMBER = dbo.JOB_TRAFFIC.JOB_NUMBER AND 
											  dbo.JOB_COMPONENT.JOB_COMPONENT_NBR = dbo.JOB_TRAFFIC.JOB_COMPONENT_NBR LEFT OUTER JOIN
											  dbo.TRAFFIC ON dbo.JOB_TRAFFIC.TRF_CODE = dbo.TRAFFIC.TRF_CODE LEFT OUTER JOIN
											  dbo.ESTIMATE_APPROVAL ON dbo.JOB_COMPONENT.JOB_NUMBER = dbo.ESTIMATE_APPROVAL.JOB_NUMBER AND 
											  dbo.JOB_COMPONENT.JOB_COMPONENT_NBR = dbo.ESTIMATE_APPROVAL.JOB_COMPONENT_NBR
									INNER JOIN charlist_to_table(@AEs, DEFAULT) g ON JOB_COMPONENT.EMP_CODE = g.vstr collate database_default
						WHERE     (dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL <> 6) AND (dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL <> 12) AND 
											  (JOB_COMPONENT.JOB_FIRST_USE_DATE >= @Start_Date AND JOB_COMPONENT.JOB_FIRST_USE_DATE <= @End_Date) AND CP_SEC_CLIENT.CDP_CONTACT_ID = @CPID
						order by JOB_LOG.CL_CODE,
							JOB_LOG.DIV_CODE,
							JOB_LOG.PRD_CODE,
							JOB_COMPONENT.JOB_NUMBER, JOB_COMPONENT.JOB_COMPONENT_NBR
					END
					Else	--@IncludeCS = '1'
					BEGIN
						SELECT     dbo.JOB_LOG.CL_CODE, dbo.JOB_LOG.DIV_CODE, dbo.JOB_LOG.PRD_CODE, dbo.CLIENT.CL_NAME AS Client, dbo.DIVISION.DIV_NAME AS Division, 
								  dbo.PRODUCT.PRD_DESCRIPTION AS Product, dbo.JOB_LOG.JOB_NUMBER, dbo.JOB_LOG.OFFICE_CODE, dbo.JOB_LOG.JOB_DESC, 
								  dbo.JOB_LOG.JOB_CLI_REF, dbo.JOB_COMPONENT.JOB_COMPONENT_NBR, dbo.JOB_COMPONENT.JOB_COMP_DESC, 
								  dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL, dbo.JOB_COMPONENT.JOB_COMP_DATE, dbo.EMPLOYEE.EMP_CODE, 
								  dbo.EMPLOYEE.EMP_FNAME + ' ' + dbo.EMPLOYEE.EMP_LNAME AS [Account Executive], dbo.JOB_COMPONENT.START_DATE AS [Start Date],
								  dbo.JOB_COMPONENT.JOB_FIRST_USE_DATE AS [Due Date], dbo.JOB_LOG.USER_ID AS [User ID], 
								  dbo.CLIENT.CL_NAME + ' - ' + dbo.DIVISION.DIV_NAME + ' - ' + dbo.PRODUCT.PRD_DESCRIPTION AS CDP, dbo.JOB_LOG.SC_CODE, 
								  dbo.SALES_CLASS.SC_DESCRIPTION, dbo.JOB_TRAFFIC.COMPLETED_DATE, dbo.JOB_TRAFFIC.ROWID, dbo.JOB_TRAFFIC.TRF_COMMENTS, 
								  dbo.JOB_COMPONENT.TRF_SCHEDULE_REQ, dbo.JOB_TYPE.JT_CODE, dbo.JOB_TYPE.JT_DESC, dbo.TRAFFIC.TRF_CODE, 
								  dbo.TRAFFIC.TRF_DESCRIPTION, dbo.JOB_COMPONENT.ESTIMATE_NUMBER, dbo.ESTIMATE_APPROVAL.JOB_NUMBER AS EJobNum, 
								  dbo.ESTIMATE_APPROVAL.JOB_COMPONENT_NBR AS EJobComNum, JOB_TRAFFIC.MGR_EMP_CODE, dbo.JOB_COMPONENT.JOB_QTY
						FROM         dbo.JOB_LOG INNER JOIN
											  dbo.JOB_COMPONENT ON dbo.JOB_LOG.JOB_NUMBER = dbo.JOB_COMPONENT.JOB_NUMBER INNER JOIN
											  dbo.EMPLOYEE ON dbo.JOB_COMPONENT.EMP_CODE = dbo.EMPLOYEE.EMP_CODE LEFT OUTER JOIN
											  dbo.JOB_TYPE ON dbo.JOB_COMPONENT.JT_CODE = dbo.JOB_TYPE.JT_CODE INNER JOIN
											  dbo.CLIENT ON dbo.JOB_LOG.CL_CODE = dbo.CLIENT.CL_CODE INNER JOIN
											  dbo.PRODUCT ON dbo.JOB_LOG.CL_CODE = dbo.PRODUCT.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.PRODUCT.DIV_CODE AND 
											  dbo.JOB_LOG.PRD_CODE = dbo.PRODUCT.PRD_CODE INNER JOIN
											  dbo.DIVISION ON dbo.JOB_LOG.CL_CODE = dbo.DIVISION.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.DIVISION.DIV_CODE INNER JOIN
											  dbo.CP_SEC_CLIENT ON dbo.JOB_LOG.CL_CODE = dbo.CP_SEC_CLIENT.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.CP_SEC_CLIENT.DIV_CODE AND 
											  dbo.JOB_LOG.PRD_CODE = dbo.CP_SEC_CLIENT.PRD_CODE INNER JOIN
											  dbo.SALES_CLASS ON dbo.JOB_LOG.SC_CODE = dbo.SALES_CLASS.SC_CODE INNER JOIN
											  dbo.JOB_TRAFFIC ON dbo.JOB_LOG.JOB_NUMBER = dbo.JOB_TRAFFIC.JOB_NUMBER AND 
											  dbo.JOB_COMPONENT.JOB_COMPONENT_NBR = dbo.JOB_TRAFFIC.JOB_COMPONENT_NBR LEFT OUTER JOIN
											  dbo.TRAFFIC ON dbo.JOB_TRAFFIC.TRF_CODE = dbo.TRAFFIC.TRF_CODE LEFT OUTER JOIN
											  dbo.ESTIMATE_APPROVAL ON dbo.JOB_COMPONENT.JOB_NUMBER = dbo.ESTIMATE_APPROVAL.JOB_NUMBER AND 
											  dbo.JOB_COMPONENT.JOB_COMPONENT_NBR = dbo.ESTIMATE_APPROVAL.JOB_COMPONENT_NBR
									INNER JOIN charlist_to_table(@AEs, DEFAULT) g ON JOB_COMPONENT.EMP_CODE = g.vstr collate database_default
						WHERE     (dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL <> 6) AND (dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL <> 12) AND 
											  (dbo.JOB_TRAFFIC.COMPLETED_DATE IS NULL) AND (JOB_COMPONENT.JOB_FIRST_USE_DATE >= @Start_Date AND JOB_COMPONENT.JOB_FIRST_USE_DATE <= @End_Date) AND CP_SEC_CLIENT.CDP_CONTACT_ID = @CPID
						order by JOB_LOG.CL_CODE,
							JOB_LOG.DIV_CODE,
							JOB_LOG.PRD_CODE,
							JOB_COMPONENT.JOB_NUMBER, JOB_COMPONENT.JOB_COMPONENT_NBR
					END
		
				END
			ELSE	--@RestrictionsCP > 0
				BEGIN
					If @IncludeCS = '1'
					BEGIN
						SELECT     dbo.JOB_LOG.CL_CODE, dbo.JOB_LOG.DIV_CODE, dbo.JOB_LOG.PRD_CODE, dbo.CLIENT.CL_NAME AS Client, dbo.DIVISION.DIV_NAME AS Division, 
								  dbo.PRODUCT.PRD_DESCRIPTION AS Product, dbo.JOB_LOG.JOB_NUMBER, dbo.JOB_LOG.OFFICE_CODE, dbo.JOB_LOG.JOB_DESC, 
								  dbo.JOB_LOG.JOB_CLI_REF, dbo.JOB_COMPONENT.JOB_COMPONENT_NBR, dbo.JOB_COMPONENT.JOB_COMP_DESC, 
								  dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL, dbo.JOB_COMPONENT.JOB_COMP_DATE, dbo.EMPLOYEE.EMP_CODE, 
								  dbo.EMPLOYEE.EMP_FNAME + ' ' + dbo.EMPLOYEE.EMP_LNAME AS [Account Executive], dbo.JOB_COMPONENT.START_DATE AS [Start Date],
								  dbo.JOB_COMPONENT.JOB_FIRST_USE_DATE AS [Due Date], dbo.JOB_LOG.USER_ID AS [User ID], 
								  dbo.CLIENT.CL_NAME + ' - ' + dbo.DIVISION.DIV_NAME + ' - ' + dbo.PRODUCT.PRD_DESCRIPTION AS CDP, dbo.JOB_LOG.SC_CODE, 
								  dbo.SALES_CLASS.SC_DESCRIPTION, dbo.JOB_TRAFFIC.COMPLETED_DATE, dbo.JOB_TRAFFIC.ROWID, dbo.JOB_TRAFFIC.TRF_COMMENTS, 
								  dbo.JOB_COMPONENT.TRF_SCHEDULE_REQ, dbo.JOB_TYPE.JT_CODE, dbo.JOB_TYPE.JT_DESC, dbo.TRAFFIC.TRF_CODE, 
								  dbo.TRAFFIC.TRF_DESCRIPTION, dbo.JOB_COMPONENT.ESTIMATE_NUMBER, dbo.ESTIMATE_APPROVAL.JOB_NUMBER AS EJobNum, 
								  dbo.ESTIMATE_APPROVAL.JOB_COMPONENT_NBR AS EJobComNum, JOB_TRAFFIC.MGR_EMP_CODE, dbo.JOB_COMPONENT.JOB_QTY
						FROM         dbo.JOB_LOG INNER JOIN
											  dbo.JOB_COMPONENT ON dbo.JOB_LOG.JOB_NUMBER = dbo.JOB_COMPONENT.JOB_NUMBER INNER JOIN
											  dbo.EMPLOYEE ON dbo.JOB_COMPONENT.EMP_CODE = dbo.EMPLOYEE.EMP_CODE LEFT OUTER JOIN
											  dbo.JOB_TYPE ON dbo.JOB_COMPONENT.JT_CODE = dbo.JOB_TYPE.JT_CODE INNER JOIN
											  dbo.CLIENT ON dbo.JOB_LOG.CL_CODE = dbo.CLIENT.CL_CODE INNER JOIN
											  dbo.PRODUCT ON dbo.JOB_LOG.CL_CODE = dbo.PRODUCT.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.PRODUCT.DIV_CODE AND 
											  dbo.JOB_LOG.PRD_CODE = dbo.PRODUCT.PRD_CODE INNER JOIN
											  dbo.DIVISION ON dbo.JOB_LOG.CL_CODE = dbo.DIVISION.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.DIVISION.DIV_CODE INNER JOIN
											  dbo.SALES_CLASS ON dbo.JOB_LOG.SC_CODE = dbo.SALES_CLASS.SC_CODE INNER JOIN
											  dbo.JOB_TRAFFIC ON dbo.JOB_LOG.JOB_NUMBER = dbo.JOB_TRAFFIC.JOB_NUMBER AND 
											  dbo.JOB_COMPONENT.JOB_COMPONENT_NBR = dbo.JOB_TRAFFIC.JOB_COMPONENT_NBR LEFT OUTER JOIN
											  dbo.TRAFFIC ON dbo.JOB_TRAFFIC.TRF_CODE = dbo.TRAFFIC.TRF_CODE LEFT OUTER JOIN
											  dbo.ESTIMATE_APPROVAL ON dbo.JOB_COMPONENT.JOB_NUMBER = dbo.ESTIMATE_APPROVAL.JOB_NUMBER AND 
											  dbo.JOB_COMPONENT.JOB_COMPONENT_NBR = dbo.ESTIMATE_APPROVAL.JOB_COMPONENT_NBR
									INNER JOIN charlist_to_table(@AEs, DEFAULT) g ON JOB_COMPONENT.EMP_CODE = g.vstr collate database_default
						WHERE     (dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL <> 6) AND (dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL <> 12) AND 
											  (JOB_COMPONENT.JOB_FIRST_USE_DATE >= @Start_Date AND JOB_COMPONENT.JOB_FIRST_USE_DATE <= @End_Date)
						order by JOB_LOG.CL_CODE,
							JOB_LOG.DIV_CODE,
							JOB_LOG.PRD_CODE,
							JOB_COMPONENT.JOB_NUMBER, JOB_COMPONENT.JOB_COMPONENT_NBR
					END
					Else	--@IncludeCS = '1'
					BEGIN
						SELECT     dbo.JOB_LOG.CL_CODE, dbo.JOB_LOG.DIV_CODE, dbo.JOB_LOG.PRD_CODE, dbo.CLIENT.CL_NAME AS Client, dbo.DIVISION.DIV_NAME AS Division, 
								  dbo.PRODUCT.PRD_DESCRIPTION AS Product, dbo.JOB_LOG.JOB_NUMBER, dbo.JOB_LOG.OFFICE_CODE, dbo.JOB_LOG.JOB_DESC, 
								  dbo.JOB_LOG.JOB_CLI_REF, dbo.JOB_COMPONENT.JOB_COMPONENT_NBR, dbo.JOB_COMPONENT.JOB_COMP_DESC, 
								  dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL, dbo.JOB_COMPONENT.JOB_COMP_DATE, dbo.EMPLOYEE.EMP_CODE, 
								  dbo.EMPLOYEE.EMP_FNAME + ' ' + dbo.EMPLOYEE.EMP_LNAME AS [Account Executive], dbo.JOB_COMPONENT.START_DATE AS [Start Date],
								  dbo.JOB_COMPONENT.JOB_FIRST_USE_DATE AS [Due Date], dbo.JOB_LOG.USER_ID AS [User ID], 
								  dbo.CLIENT.CL_NAME + ' - ' + dbo.DIVISION.DIV_NAME + ' - ' + dbo.PRODUCT.PRD_DESCRIPTION AS CDP, dbo.JOB_LOG.SC_CODE, 
								  dbo.SALES_CLASS.SC_DESCRIPTION, dbo.JOB_TRAFFIC.COMPLETED_DATE, dbo.JOB_TRAFFIC.ROWID, dbo.JOB_TRAFFIC.TRF_COMMENTS, 
								  dbo.JOB_COMPONENT.TRF_SCHEDULE_REQ, dbo.JOB_TYPE.JT_CODE, dbo.JOB_TYPE.JT_DESC, dbo.TRAFFIC.TRF_CODE, 
								  dbo.TRAFFIC.TRF_DESCRIPTION, dbo.JOB_COMPONENT.ESTIMATE_NUMBER, dbo.ESTIMATE_APPROVAL.JOB_NUMBER AS EJobNum, 
								  dbo.ESTIMATE_APPROVAL.JOB_COMPONENT_NBR AS EJobComNum, JOB_TRAFFIC.MGR_EMP_CODE, dbo.JOB_COMPONENT.JOB_QTY
						FROM         dbo.JOB_LOG INNER JOIN
											  dbo.JOB_COMPONENT ON dbo.JOB_LOG.JOB_NUMBER = dbo.JOB_COMPONENT.JOB_NUMBER INNER JOIN
											  dbo.EMPLOYEE ON dbo.JOB_COMPONENT.EMP_CODE = dbo.EMPLOYEE.EMP_CODE LEFT OUTER JOIN
											  dbo.JOB_TYPE ON dbo.JOB_COMPONENT.JT_CODE = dbo.JOB_TYPE.JT_CODE INNER JOIN
											  dbo.CLIENT ON dbo.JOB_LOG.CL_CODE = dbo.CLIENT.CL_CODE INNER JOIN
											  dbo.PRODUCT ON dbo.JOB_LOG.CL_CODE = dbo.PRODUCT.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.PRODUCT.DIV_CODE AND 
											  dbo.JOB_LOG.PRD_CODE = dbo.PRODUCT.PRD_CODE INNER JOIN
											  dbo.DIVISION ON dbo.JOB_LOG.CL_CODE = dbo.DIVISION.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.DIVISION.DIV_CODE INNER JOIN
											  dbo.SALES_CLASS ON dbo.JOB_LOG.SC_CODE = dbo.SALES_CLASS.SC_CODE INNER JOIN
											  dbo.JOB_TRAFFIC ON dbo.JOB_LOG.JOB_NUMBER = dbo.JOB_TRAFFIC.JOB_NUMBER AND 
											  dbo.JOB_COMPONENT.JOB_COMPONENT_NBR = dbo.JOB_TRAFFIC.JOB_COMPONENT_NBR LEFT OUTER JOIN
											  dbo.TRAFFIC ON dbo.JOB_TRAFFIC.TRF_CODE = dbo.TRAFFIC.TRF_CODE LEFT OUTER JOIN
											  dbo.ESTIMATE_APPROVAL ON dbo.JOB_COMPONENT.JOB_NUMBER = dbo.ESTIMATE_APPROVAL.JOB_NUMBER AND 
											  dbo.JOB_COMPONENT.JOB_COMPONENT_NBR = dbo.ESTIMATE_APPROVAL.JOB_COMPONENT_NBR
									INNER JOIN charlist_to_table(@AEs, DEFAULT) g ON JOB_COMPONENT.EMP_CODE = g.vstr collate database_default
						WHERE     (dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL <> 6) AND (dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL <> 12) AND 
											  (dbo.JOB_TRAFFIC.COMPLETED_DATE IS NULL) AND (JOB_COMPONENT.JOB_FIRST_USE_DATE >= @Start_Date AND JOB_COMPONENT.JOB_FIRST_USE_DATE <= @End_Date)
						order by JOB_LOG.CL_CODE,
							JOB_LOG.DIV_CODE,
							JOB_LOG.PRD_CODE,
							JOB_COMPONENT.JOB_NUMBER, JOB_COMPONENT.JOB_COMPONENT_NBR
					END	--@IncludeCS = '1'
				END
			END
	END
ELSE
	BEGIN
		If @AEs = '%'  
		   BEGIN
			If @Rescrictions > 0
				BEGIN
					if @IncludeCS = '1'
					BEGIN
						if @RestrictionsOffice > 0
						Begin
							SELECT     dbo.JOB_LOG.CL_CODE, dbo.JOB_LOG.DIV_CODE, dbo.JOB_LOG.PRD_CODE, dbo.CLIENT.CL_NAME AS Client, dbo.DIVISION.DIV_NAME AS Division, 
									  dbo.PRODUCT.PRD_DESCRIPTION AS Product, dbo.JOB_LOG.JOB_NUMBER, dbo.JOB_LOG.OFFICE_CODE, dbo.JOB_LOG.JOB_DESC, 
									  dbo.JOB_LOG.JOB_CLI_REF, dbo.JOB_COMPONENT.JOB_COMPONENT_NBR, dbo.JOB_COMPONENT.JOB_COMP_DESC, 
									  dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL, dbo.JOB_COMPONENT.JOB_COMP_DATE, dbo.EMPLOYEE.EMP_CODE, 
									  dbo.EMPLOYEE.EMP_FNAME + ' ' + dbo.EMPLOYEE.EMP_LNAME AS [Account Executive], dbo.JOB_COMPONENT.START_DATE AS [Start Date],
									  dbo.JOB_COMPONENT.JOB_FIRST_USE_DATE AS [Due Date], dbo.JOB_LOG.USER_ID AS [User ID], 
									  dbo.CLIENT.CL_NAME + ' - ' + dbo.DIVISION.DIV_NAME + ' - ' + dbo.PRODUCT.PRD_DESCRIPTION AS CDP, dbo.JOB_LOG.SC_CODE, 
									  dbo.SALES_CLASS.SC_DESCRIPTION, dbo.JOB_TRAFFIC.COMPLETED_DATE, dbo.JOB_TRAFFIC.ROWID, dbo.JOB_TRAFFIC.TRF_COMMENTS, 
									  dbo.JOB_COMPONENT.TRF_SCHEDULE_REQ, dbo.JOB_TYPE.JT_CODE, dbo.JOB_TYPE.JT_DESC, dbo.TRAFFIC.TRF_CODE, 
									  dbo.TRAFFIC.TRF_DESCRIPTION, dbo.JOB_COMPONENT.ESTIMATE_NUMBER, dbo.ESTIMATE_APPROVAL.JOB_NUMBER AS EJobNum, 
									  dbo.ESTIMATE_APPROVAL.JOB_COMPONENT_NBR AS EJobComNum, JOB_TRAFFIC.MGR_EMP_CODE, dbo.JOB_COMPONENT.JOB_QTY
							FROM         dbo.JOB_LOG INNER JOIN
												  dbo.JOB_COMPONENT ON dbo.JOB_LOG.JOB_NUMBER = dbo.JOB_COMPONENT.JOB_NUMBER INNER JOIN
												  dbo.EMPLOYEE ON dbo.JOB_COMPONENT.EMP_CODE = dbo.EMPLOYEE.EMP_CODE LEFT OUTER JOIN
												  dbo.JOB_TYPE ON dbo.JOB_COMPONENT.JT_CODE = dbo.JOB_TYPE.JT_CODE INNER JOIN
												  dbo.CLIENT ON dbo.JOB_LOG.CL_CODE = dbo.CLIENT.CL_CODE INNER JOIN
												  dbo.PRODUCT ON dbo.JOB_LOG.CL_CODE = dbo.PRODUCT.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.PRODUCT.DIV_CODE AND 
												  dbo.JOB_LOG.PRD_CODE = dbo.PRODUCT.PRD_CODE INNER JOIN
												  dbo.DIVISION ON dbo.JOB_LOG.CL_CODE = dbo.DIVISION.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.DIVISION.DIV_CODE INNER JOIN
												  dbo.SEC_CLIENT ON dbo.JOB_LOG.CL_CODE = dbo.SEC_CLIENT.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.SEC_CLIENT.DIV_CODE AND 
												  dbo.JOB_LOG.PRD_CODE = dbo.SEC_CLIENT.PRD_CODE INNER JOIN
												  dbo.SALES_CLASS ON dbo.JOB_LOG.SC_CODE = dbo.SALES_CLASS.SC_CODE INNER JOIN
												  dbo.JOB_TRAFFIC ON dbo.JOB_LOG.JOB_NUMBER = dbo.JOB_TRAFFIC.JOB_NUMBER AND 
												  dbo.JOB_COMPONENT.JOB_COMPONENT_NBR = dbo.JOB_TRAFFIC.JOB_COMPONENT_NBR LEFT OUTER JOIN
												  dbo.TRAFFIC ON dbo.JOB_TRAFFIC.TRF_CODE = dbo.TRAFFIC.TRF_CODE LEFT OUTER JOIN
												  dbo.ESTIMATE_APPROVAL ON dbo.JOB_COMPONENT.JOB_NUMBER = dbo.ESTIMATE_APPROVAL.JOB_NUMBER AND 
												  dbo.JOB_COMPONENT.JOB_COMPONENT_NBR = dbo.ESTIMATE_APPROVAL.JOB_COMPONENT_NBR INNER JOIN EMP_OFFICE ON EMP_OFFICE.OFFICE_CODE = JOB_LOG.OFFICE_CODE AND EMP_OFFICE.EMP_CODE = @EMP_CDE
							WHERE     (dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL <> 6) AND (dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL <> 12) AND 
												  (JOB_COMPONENT.JOB_FIRST_USE_DATE >= @Start_Date AND JOB_COMPONENT.JOB_FIRST_USE_DATE <= @End_Date) AND UPPER(SEC_CLIENT.USER_ID) = UPPER(@UserID) AND (SEC_CLIENT.TIME_ENTRY = 0 OR SEC_CLIENT.TIME_ENTRY IS NULL)
							order by JOB_LOG.CL_CODE,
								JOB_LOG.DIV_CODE,
								JOB_LOG.PRD_CODE,
								JOB_COMPONENT.JOB_NUMBER, JOB_COMPONENT.JOB_COMPONENT_NBR
						End
						Else
						Begin
							SELECT     dbo.JOB_LOG.CL_CODE, dbo.JOB_LOG.DIV_CODE, dbo.JOB_LOG.PRD_CODE, dbo.CLIENT.CL_NAME AS Client, dbo.DIVISION.DIV_NAME AS Division, 
									  dbo.PRODUCT.PRD_DESCRIPTION AS Product, dbo.JOB_LOG.JOB_NUMBER, dbo.JOB_LOG.OFFICE_CODE, dbo.JOB_LOG.JOB_DESC, 
									  dbo.JOB_LOG.JOB_CLI_REF, dbo.JOB_COMPONENT.JOB_COMPONENT_NBR, dbo.JOB_COMPONENT.JOB_COMP_DESC, 
									  dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL, dbo.JOB_COMPONENT.JOB_COMP_DATE, dbo.EMPLOYEE.EMP_CODE, 
									  dbo.EMPLOYEE.EMP_FNAME + ' ' + dbo.EMPLOYEE.EMP_LNAME AS [Account Executive], dbo.JOB_COMPONENT.START_DATE AS [Start Date],
									  dbo.JOB_COMPONENT.JOB_FIRST_USE_DATE AS [Due Date], dbo.JOB_LOG.USER_ID AS [User ID], 
									  dbo.CLIENT.CL_NAME + ' - ' + dbo.DIVISION.DIV_NAME + ' - ' + dbo.PRODUCT.PRD_DESCRIPTION AS CDP, dbo.JOB_LOG.SC_CODE, 
									  dbo.SALES_CLASS.SC_DESCRIPTION, dbo.JOB_TRAFFIC.COMPLETED_DATE, dbo.JOB_TRAFFIC.ROWID, dbo.JOB_TRAFFIC.TRF_COMMENTS, 
									  dbo.JOB_COMPONENT.TRF_SCHEDULE_REQ, dbo.JOB_TYPE.JT_CODE, dbo.JOB_TYPE.JT_DESC, dbo.TRAFFIC.TRF_CODE, 
									  dbo.TRAFFIC.TRF_DESCRIPTION, dbo.JOB_COMPONENT.ESTIMATE_NUMBER, dbo.ESTIMATE_APPROVAL.JOB_NUMBER AS EJobNum, 
									  dbo.ESTIMATE_APPROVAL.JOB_COMPONENT_NBR AS EJobComNum, JOB_TRAFFIC.MGR_EMP_CODE, dbo.JOB_COMPONENT.JOB_QTY
							FROM         dbo.JOB_LOG INNER JOIN
												  dbo.JOB_COMPONENT ON dbo.JOB_LOG.JOB_NUMBER = dbo.JOB_COMPONENT.JOB_NUMBER INNER JOIN
												  dbo.EMPLOYEE ON dbo.JOB_COMPONENT.EMP_CODE = dbo.EMPLOYEE.EMP_CODE LEFT OUTER JOIN
												  dbo.JOB_TYPE ON dbo.JOB_COMPONENT.JT_CODE = dbo.JOB_TYPE.JT_CODE INNER JOIN
												  dbo.CLIENT ON dbo.JOB_LOG.CL_CODE = dbo.CLIENT.CL_CODE INNER JOIN
												  dbo.PRODUCT ON dbo.JOB_LOG.CL_CODE = dbo.PRODUCT.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.PRODUCT.DIV_CODE AND 
												  dbo.JOB_LOG.PRD_CODE = dbo.PRODUCT.PRD_CODE INNER JOIN
												  dbo.DIVISION ON dbo.JOB_LOG.CL_CODE = dbo.DIVISION.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.DIVISION.DIV_CODE INNER JOIN
												  dbo.SEC_CLIENT ON dbo.JOB_LOG.CL_CODE = dbo.SEC_CLIENT.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.SEC_CLIENT.DIV_CODE AND 
												  dbo.JOB_LOG.PRD_CODE = dbo.SEC_CLIENT.PRD_CODE INNER JOIN
												  dbo.SALES_CLASS ON dbo.JOB_LOG.SC_CODE = dbo.SALES_CLASS.SC_CODE INNER JOIN
												  dbo.JOB_TRAFFIC ON dbo.JOB_LOG.JOB_NUMBER = dbo.JOB_TRAFFIC.JOB_NUMBER AND 
												  dbo.JOB_COMPONENT.JOB_COMPONENT_NBR = dbo.JOB_TRAFFIC.JOB_COMPONENT_NBR LEFT OUTER JOIN
												  dbo.TRAFFIC ON dbo.JOB_TRAFFIC.TRF_CODE = dbo.TRAFFIC.TRF_CODE LEFT OUTER JOIN
												  dbo.ESTIMATE_APPROVAL ON dbo.JOB_COMPONENT.JOB_NUMBER = dbo.ESTIMATE_APPROVAL.JOB_NUMBER AND 
												  dbo.JOB_COMPONENT.JOB_COMPONENT_NBR = dbo.ESTIMATE_APPROVAL.JOB_COMPONENT_NBR
							WHERE     (dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL <> 6) AND (dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL <> 12) AND 
												  (JOB_COMPONENT.JOB_FIRST_USE_DATE >= @Start_Date AND JOB_COMPONENT.JOB_FIRST_USE_DATE <= @End_Date) AND UPPER(SEC_CLIENT.USER_ID) = UPPER(@UserID) AND (SEC_CLIENT.TIME_ENTRY = 0 OR SEC_CLIENT.TIME_ENTRY IS NULL)
							order by JOB_LOG.CL_CODE,
								JOB_LOG.DIV_CODE,
								JOB_LOG.PRD_CODE,
								JOB_COMPONENT.JOB_NUMBER, JOB_COMPONENT.JOB_COMPONENT_NBR
						End
						
					END
					Else
					BEGIN
						if @RestrictionsOffice > 0
						Begin
							SELECT     dbo.JOB_LOG.CL_CODE, dbo.JOB_LOG.DIV_CODE, dbo.JOB_LOG.PRD_CODE, dbo.CLIENT.CL_NAME AS Client, dbo.DIVISION.DIV_NAME AS Division, 
									  dbo.PRODUCT.PRD_DESCRIPTION AS Product, dbo.JOB_LOG.JOB_NUMBER, dbo.JOB_LOG.OFFICE_CODE, dbo.JOB_LOG.JOB_DESC, 
									  dbo.JOB_LOG.JOB_CLI_REF, dbo.JOB_COMPONENT.JOB_COMPONENT_NBR, dbo.JOB_COMPONENT.JOB_COMP_DESC, 
									  dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL, dbo.JOB_COMPONENT.JOB_COMP_DATE, dbo.EMPLOYEE.EMP_CODE, 
									  dbo.EMPLOYEE.EMP_FNAME + ' ' + dbo.EMPLOYEE.EMP_LNAME AS [Account Executive], dbo.JOB_COMPONENT.START_DATE AS [Start Date],
									  dbo.JOB_COMPONENT.JOB_FIRST_USE_DATE AS [Due Date], dbo.JOB_LOG.USER_ID AS [User ID], 
									  dbo.CLIENT.CL_NAME + ' - ' + dbo.DIVISION.DIV_NAME + ' - ' + dbo.PRODUCT.PRD_DESCRIPTION AS CDP, dbo.JOB_LOG.SC_CODE, 
									  dbo.SALES_CLASS.SC_DESCRIPTION, dbo.JOB_TRAFFIC.COMPLETED_DATE, dbo.JOB_TRAFFIC.ROWID, dbo.JOB_TRAFFIC.TRF_COMMENTS, 
									  dbo.JOB_COMPONENT.TRF_SCHEDULE_REQ, dbo.JOB_TYPE.JT_CODE, dbo.JOB_TYPE.JT_DESC, dbo.TRAFFIC.TRF_CODE, 
									  dbo.TRAFFIC.TRF_DESCRIPTION, dbo.JOB_COMPONENT.ESTIMATE_NUMBER, dbo.ESTIMATE_APPROVAL.JOB_NUMBER AS EJobNum, 
									  dbo.ESTIMATE_APPROVAL.JOB_COMPONENT_NBR AS EJobComNum, JOB_TRAFFIC.MGR_EMP_CODE, dbo.JOB_COMPONENT.JOB_QTY
							FROM         dbo.JOB_LOG INNER JOIN
												  dbo.JOB_COMPONENT ON dbo.JOB_LOG.JOB_NUMBER = dbo.JOB_COMPONENT.JOB_NUMBER INNER JOIN
												  dbo.EMPLOYEE ON dbo.JOB_COMPONENT.EMP_CODE = dbo.EMPLOYEE.EMP_CODE LEFT OUTER JOIN
												  dbo.JOB_TYPE ON dbo.JOB_COMPONENT.JT_CODE = dbo.JOB_TYPE.JT_CODE INNER JOIN
												  dbo.CLIENT ON dbo.JOB_LOG.CL_CODE = dbo.CLIENT.CL_CODE INNER JOIN
												  dbo.PRODUCT ON dbo.JOB_LOG.CL_CODE = dbo.PRODUCT.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.PRODUCT.DIV_CODE AND 
												  dbo.JOB_LOG.PRD_CODE = dbo.PRODUCT.PRD_CODE INNER JOIN
												  dbo.DIVISION ON dbo.JOB_LOG.CL_CODE = dbo.DIVISION.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.DIVISION.DIV_CODE INNER JOIN
												  dbo.SEC_CLIENT ON dbo.JOB_LOG.CL_CODE = dbo.SEC_CLIENT.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.SEC_CLIENT.DIV_CODE AND 
												  dbo.JOB_LOG.PRD_CODE = dbo.SEC_CLIENT.PRD_CODE INNER JOIN
												  dbo.SALES_CLASS ON dbo.JOB_LOG.SC_CODE = dbo.SALES_CLASS.SC_CODE INNER JOIN
												  dbo.JOB_TRAFFIC ON dbo.JOB_LOG.JOB_NUMBER = dbo.JOB_TRAFFIC.JOB_NUMBER AND 
												  dbo.JOB_COMPONENT.JOB_COMPONENT_NBR = dbo.JOB_TRAFFIC.JOB_COMPONENT_NBR LEFT OUTER JOIN
												  dbo.TRAFFIC ON dbo.JOB_TRAFFIC.TRF_CODE = dbo.TRAFFIC.TRF_CODE LEFT OUTER JOIN
												  dbo.ESTIMATE_APPROVAL ON dbo.JOB_COMPONENT.JOB_NUMBER = dbo.ESTIMATE_APPROVAL.JOB_NUMBER AND 
												  dbo.JOB_COMPONENT.JOB_COMPONENT_NBR = dbo.ESTIMATE_APPROVAL.JOB_COMPONENT_NBR INNER JOIN EMP_OFFICE ON EMP_OFFICE.OFFICE_CODE = JOB_LOG.OFFICE_CODE AND EMP_OFFICE.EMP_CODE = @EMP_CDE
							WHERE     (dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL <> 6) AND (dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL <> 12) AND 
												  (dbo.JOB_TRAFFIC.COMPLETED_DATE IS NULL) AND (JOB_COMPONENT.JOB_FIRST_USE_DATE >= @Start_Date AND JOB_COMPONENT.JOB_FIRST_USE_DATE <= @End_Date) AND UPPER(SEC_CLIENT.USER_ID) = UPPER(@UserID) AND (SEC_CLIENT.TIME_ENTRY = 0 OR SEC_CLIENT.TIME_ENTRY IS NULL)
							order by JOB_LOG.CL_CODE,
								JOB_LOG.DIV_CODE,
								JOB_LOG.PRD_CODE,
								JOB_COMPONENT.JOB_NUMBER, JOB_COMPONENT.JOB_COMPONENT_NBR
						End
						Else
						Begin
							SELECT     dbo.JOB_LOG.CL_CODE, dbo.JOB_LOG.DIV_CODE, dbo.JOB_LOG.PRD_CODE, dbo.CLIENT.CL_NAME AS Client, dbo.DIVISION.DIV_NAME AS Division, 
									  dbo.PRODUCT.PRD_DESCRIPTION AS Product, dbo.JOB_LOG.JOB_NUMBER, dbo.JOB_LOG.OFFICE_CODE, dbo.JOB_LOG.JOB_DESC, 
									  dbo.JOB_LOG.JOB_CLI_REF, dbo.JOB_COMPONENT.JOB_COMPONENT_NBR, dbo.JOB_COMPONENT.JOB_COMP_DESC, 
									  dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL, dbo.JOB_COMPONENT.JOB_COMP_DATE, dbo.EMPLOYEE.EMP_CODE, 
									  dbo.EMPLOYEE.EMP_FNAME + ' ' + dbo.EMPLOYEE.EMP_LNAME AS [Account Executive], dbo.JOB_COMPONENT.START_DATE AS [Start Date],
									  dbo.JOB_COMPONENT.JOB_FIRST_USE_DATE AS [Due Date], dbo.JOB_LOG.USER_ID AS [User ID], 
									  dbo.CLIENT.CL_NAME + ' - ' + dbo.DIVISION.DIV_NAME + ' - ' + dbo.PRODUCT.PRD_DESCRIPTION AS CDP, dbo.JOB_LOG.SC_CODE, 
									  dbo.SALES_CLASS.SC_DESCRIPTION, dbo.JOB_TRAFFIC.COMPLETED_DATE, dbo.JOB_TRAFFIC.ROWID, dbo.JOB_TRAFFIC.TRF_COMMENTS, 
									  dbo.JOB_COMPONENT.TRF_SCHEDULE_REQ, dbo.JOB_TYPE.JT_CODE, dbo.JOB_TYPE.JT_DESC, dbo.TRAFFIC.TRF_CODE, 
									  dbo.TRAFFIC.TRF_DESCRIPTION, dbo.JOB_COMPONENT.ESTIMATE_NUMBER, dbo.ESTIMATE_APPROVAL.JOB_NUMBER AS EJobNum, 
									  dbo.ESTIMATE_APPROVAL.JOB_COMPONENT_NBR AS EJobComNum, JOB_TRAFFIC.MGR_EMP_CODE, dbo.JOB_COMPONENT.JOB_QTY
							FROM         dbo.JOB_LOG INNER JOIN
												  dbo.JOB_COMPONENT ON dbo.JOB_LOG.JOB_NUMBER = dbo.JOB_COMPONENT.JOB_NUMBER INNER JOIN
												  dbo.EMPLOYEE ON dbo.JOB_COMPONENT.EMP_CODE = dbo.EMPLOYEE.EMP_CODE LEFT OUTER JOIN
												  dbo.JOB_TYPE ON dbo.JOB_COMPONENT.JT_CODE = dbo.JOB_TYPE.JT_CODE INNER JOIN
												  dbo.CLIENT ON dbo.JOB_LOG.CL_CODE = dbo.CLIENT.CL_CODE INNER JOIN
												  dbo.PRODUCT ON dbo.JOB_LOG.CL_CODE = dbo.PRODUCT.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.PRODUCT.DIV_CODE AND 
												  dbo.JOB_LOG.PRD_CODE = dbo.PRODUCT.PRD_CODE INNER JOIN
												  dbo.DIVISION ON dbo.JOB_LOG.CL_CODE = dbo.DIVISION.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.DIVISION.DIV_CODE INNER JOIN
												  dbo.SEC_CLIENT ON dbo.JOB_LOG.CL_CODE = dbo.SEC_CLIENT.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.SEC_CLIENT.DIV_CODE AND 
												  dbo.JOB_LOG.PRD_CODE = dbo.SEC_CLIENT.PRD_CODE INNER JOIN
												  dbo.SALES_CLASS ON dbo.JOB_LOG.SC_CODE = dbo.SALES_CLASS.SC_CODE INNER JOIN
												  dbo.JOB_TRAFFIC ON dbo.JOB_LOG.JOB_NUMBER = dbo.JOB_TRAFFIC.JOB_NUMBER AND 
												  dbo.JOB_COMPONENT.JOB_COMPONENT_NBR = dbo.JOB_TRAFFIC.JOB_COMPONENT_NBR LEFT OUTER JOIN
												  dbo.TRAFFIC ON dbo.JOB_TRAFFIC.TRF_CODE = dbo.TRAFFIC.TRF_CODE LEFT OUTER JOIN
												  dbo.ESTIMATE_APPROVAL ON dbo.JOB_COMPONENT.JOB_NUMBER = dbo.ESTIMATE_APPROVAL.JOB_NUMBER AND 
												  dbo.JOB_COMPONENT.JOB_COMPONENT_NBR = dbo.ESTIMATE_APPROVAL.JOB_COMPONENT_NBR
							WHERE     (dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL <> 6) AND (dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL <> 12) AND 
												  (dbo.JOB_TRAFFIC.COMPLETED_DATE IS NULL) AND (JOB_COMPONENT.JOB_FIRST_USE_DATE >= @Start_Date AND JOB_COMPONENT.JOB_FIRST_USE_DATE <= @End_Date) AND UPPER(SEC_CLIENT.USER_ID) = UPPER(@UserID) AND (SEC_CLIENT.TIME_ENTRY = 0 OR SEC_CLIENT.TIME_ENTRY IS NULL)
							order by JOB_LOG.CL_CODE,
								JOB_LOG.DIV_CODE,
								JOB_LOG.PRD_CODE,
								JOB_COMPONENT.JOB_NUMBER, JOB_COMPONENT.JOB_COMPONENT_NBR
						End
						
					END
		
				END
			ELSE
				BEGIN
					If @IncludeCS = '1'
					BEGIN
						if @RestrictionsOffice > 0
						Begin
							SELECT     dbo.JOB_LOG.CL_CODE, dbo.JOB_LOG.DIV_CODE, dbo.JOB_LOG.PRD_CODE, dbo.CLIENT.CL_NAME AS Client, dbo.DIVISION.DIV_NAME AS Division, 
									  dbo.PRODUCT.PRD_DESCRIPTION AS Product, dbo.JOB_LOG.JOB_NUMBER, dbo.JOB_LOG.OFFICE_CODE, dbo.JOB_LOG.JOB_DESC, 
									  dbo.JOB_LOG.JOB_CLI_REF, dbo.JOB_COMPONENT.JOB_COMPONENT_NBR, dbo.JOB_COMPONENT.JOB_COMP_DESC, 
									  dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL, dbo.JOB_COMPONENT.JOB_COMP_DATE, dbo.EMPLOYEE.EMP_CODE, 
									  dbo.EMPLOYEE.EMP_FNAME + ' ' + dbo.EMPLOYEE.EMP_LNAME AS [Account Executive], dbo.JOB_COMPONENT.START_DATE AS [Start Date],
									  dbo.JOB_COMPONENT.JOB_FIRST_USE_DATE AS [Due Date], dbo.JOB_LOG.USER_ID AS [User ID], 
									  dbo.CLIENT.CL_NAME + ' - ' + dbo.DIVISION.DIV_NAME + ' - ' + dbo.PRODUCT.PRD_DESCRIPTION AS CDP, dbo.JOB_LOG.SC_CODE, 
									  dbo.SALES_CLASS.SC_DESCRIPTION, dbo.JOB_TRAFFIC.COMPLETED_DATE, dbo.JOB_TRAFFIC.ROWID, dbo.JOB_TRAFFIC.TRF_COMMENTS, 
									  dbo.JOB_COMPONENT.TRF_SCHEDULE_REQ, dbo.JOB_TYPE.JT_CODE, dbo.JOB_TYPE.JT_DESC, dbo.TRAFFIC.TRF_CODE, 
									  dbo.TRAFFIC.TRF_DESCRIPTION, dbo.JOB_COMPONENT.ESTIMATE_NUMBER, dbo.ESTIMATE_APPROVAL.JOB_NUMBER AS EJobNum, 
									  dbo.ESTIMATE_APPROVAL.JOB_COMPONENT_NBR AS EJobComNum, JOB_TRAFFIC.MGR_EMP_CODE, dbo.JOB_COMPONENT.JOB_QTY
							FROM         dbo.JOB_LOG INNER JOIN
												  dbo.JOB_COMPONENT ON dbo.JOB_LOG.JOB_NUMBER = dbo.JOB_COMPONENT.JOB_NUMBER INNER JOIN
												  dbo.EMPLOYEE ON dbo.JOB_COMPONENT.EMP_CODE = dbo.EMPLOYEE.EMP_CODE LEFT OUTER JOIN
												  dbo.JOB_TYPE ON dbo.JOB_COMPONENT.JT_CODE = dbo.JOB_TYPE.JT_CODE INNER JOIN
												  dbo.CLIENT ON dbo.JOB_LOG.CL_CODE = dbo.CLIENT.CL_CODE INNER JOIN
												  dbo.PRODUCT ON dbo.JOB_LOG.CL_CODE = dbo.PRODUCT.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.PRODUCT.DIV_CODE AND 
												  dbo.JOB_LOG.PRD_CODE = dbo.PRODUCT.PRD_CODE INNER JOIN
												  dbo.DIVISION ON dbo.JOB_LOG.CL_CODE = dbo.DIVISION.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.DIVISION.DIV_CODE INNER JOIN
												  dbo.SALES_CLASS ON dbo.JOB_LOG.SC_CODE = dbo.SALES_CLASS.SC_CODE INNER JOIN
												  dbo.JOB_TRAFFIC ON dbo.JOB_LOG.JOB_NUMBER = dbo.JOB_TRAFFIC.JOB_NUMBER AND 
												  dbo.JOB_COMPONENT.JOB_COMPONENT_NBR = dbo.JOB_TRAFFIC.JOB_COMPONENT_NBR LEFT OUTER JOIN
												  dbo.TRAFFIC ON dbo.JOB_TRAFFIC.TRF_CODE = dbo.TRAFFIC.TRF_CODE LEFT OUTER JOIN
												  dbo.ESTIMATE_APPROVAL ON dbo.JOB_COMPONENT.JOB_NUMBER = dbo.ESTIMATE_APPROVAL.JOB_NUMBER AND 
												  dbo.JOB_COMPONENT.JOB_COMPONENT_NBR = dbo.ESTIMATE_APPROVAL.JOB_COMPONENT_NBR INNER JOIN EMP_OFFICE ON EMP_OFFICE.OFFICE_CODE = JOB_LOG.OFFICE_CODE AND EMP_OFFICE.EMP_CODE = @EMP_CDE
							WHERE     (dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL <> 6) AND (dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL <> 12) AND 
												  (JOB_COMPONENT.JOB_FIRST_USE_DATE >= @Start_Date AND JOB_COMPONENT.JOB_FIRST_USE_DATE <= @End_Date)
							order by JOB_LOG.CL_CODE,
								JOB_LOG.DIV_CODE,
								JOB_LOG.PRD_CODE,
								JOB_COMPONENT.JOB_NUMBER, JOB_COMPONENT.JOB_COMPONENT_NBR
						End
						Else
						Begin
							SELECT     dbo.JOB_LOG.CL_CODE, dbo.JOB_LOG.DIV_CODE, dbo.JOB_LOG.PRD_CODE, dbo.CLIENT.CL_NAME AS Client, dbo.DIVISION.DIV_NAME AS Division, 
									  dbo.PRODUCT.PRD_DESCRIPTION AS Product, dbo.JOB_LOG.JOB_NUMBER, dbo.JOB_LOG.OFFICE_CODE, dbo.JOB_LOG.JOB_DESC, 
									  dbo.JOB_LOG.JOB_CLI_REF, dbo.JOB_COMPONENT.JOB_COMPONENT_NBR, dbo.JOB_COMPONENT.JOB_COMP_DESC, 
									  dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL, dbo.JOB_COMPONENT.JOB_COMP_DATE, dbo.EMPLOYEE.EMP_CODE, 
									  dbo.EMPLOYEE.EMP_FNAME + ' ' + dbo.EMPLOYEE.EMP_LNAME AS [Account Executive], dbo.JOB_COMPONENT.START_DATE AS [Start Date],
									  dbo.JOB_COMPONENT.JOB_FIRST_USE_DATE AS [Due Date], dbo.JOB_LOG.USER_ID AS [User ID], 
									  dbo.CLIENT.CL_NAME + ' - ' + dbo.DIVISION.DIV_NAME + ' - ' + dbo.PRODUCT.PRD_DESCRIPTION AS CDP, dbo.JOB_LOG.SC_CODE, 
									  dbo.SALES_CLASS.SC_DESCRIPTION, dbo.JOB_TRAFFIC.COMPLETED_DATE, dbo.JOB_TRAFFIC.ROWID, dbo.JOB_TRAFFIC.TRF_COMMENTS, 
									  dbo.JOB_COMPONENT.TRF_SCHEDULE_REQ, dbo.JOB_TYPE.JT_CODE, dbo.JOB_TYPE.JT_DESC, dbo.TRAFFIC.TRF_CODE, 
									  dbo.TRAFFIC.TRF_DESCRIPTION, dbo.JOB_COMPONENT.ESTIMATE_NUMBER, dbo.ESTIMATE_APPROVAL.JOB_NUMBER AS EJobNum, 
									  dbo.ESTIMATE_APPROVAL.JOB_COMPONENT_NBR AS EJobComNum, JOB_TRAFFIC.MGR_EMP_CODE, dbo.JOB_COMPONENT.JOB_QTY
							FROM         dbo.JOB_LOG INNER JOIN
												  dbo.JOB_COMPONENT ON dbo.JOB_LOG.JOB_NUMBER = dbo.JOB_COMPONENT.JOB_NUMBER INNER JOIN
												  dbo.EMPLOYEE ON dbo.JOB_COMPONENT.EMP_CODE = dbo.EMPLOYEE.EMP_CODE LEFT OUTER JOIN
												  dbo.JOB_TYPE ON dbo.JOB_COMPONENT.JT_CODE = dbo.JOB_TYPE.JT_CODE INNER JOIN
												  dbo.CLIENT ON dbo.JOB_LOG.CL_CODE = dbo.CLIENT.CL_CODE INNER JOIN
												  dbo.PRODUCT ON dbo.JOB_LOG.CL_CODE = dbo.PRODUCT.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.PRODUCT.DIV_CODE AND 
												  dbo.JOB_LOG.PRD_CODE = dbo.PRODUCT.PRD_CODE INNER JOIN
												  dbo.DIVISION ON dbo.JOB_LOG.CL_CODE = dbo.DIVISION.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.DIVISION.DIV_CODE INNER JOIN
												  dbo.SALES_CLASS ON dbo.JOB_LOG.SC_CODE = dbo.SALES_CLASS.SC_CODE INNER JOIN
												  dbo.JOB_TRAFFIC ON dbo.JOB_LOG.JOB_NUMBER = dbo.JOB_TRAFFIC.JOB_NUMBER AND 
												  dbo.JOB_COMPONENT.JOB_COMPONENT_NBR = dbo.JOB_TRAFFIC.JOB_COMPONENT_NBR LEFT OUTER JOIN
												  dbo.TRAFFIC ON dbo.JOB_TRAFFIC.TRF_CODE = dbo.TRAFFIC.TRF_CODE LEFT OUTER JOIN
												  dbo.ESTIMATE_APPROVAL ON dbo.JOB_COMPONENT.JOB_NUMBER = dbo.ESTIMATE_APPROVAL.JOB_NUMBER AND 
												  dbo.JOB_COMPONENT.JOB_COMPONENT_NBR = dbo.ESTIMATE_APPROVAL.JOB_COMPONENT_NBR
							WHERE     (dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL <> 6) AND (dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL <> 12) AND 
												  (JOB_COMPONENT.JOB_FIRST_USE_DATE >= @Start_Date AND JOB_COMPONENT.JOB_FIRST_USE_DATE <= @End_Date)
							order by JOB_LOG.CL_CODE,
								JOB_LOG.DIV_CODE,
								JOB_LOG.PRD_CODE,
								JOB_COMPONENT.JOB_NUMBER, JOB_COMPONENT.JOB_COMPONENT_NBR
						End
						
					END
					Else
					BEGIN
						if @RestrictionsOffice > 0
						Begin
							SELECT     dbo.JOB_LOG.CL_CODE, dbo.JOB_LOG.DIV_CODE, dbo.JOB_LOG.PRD_CODE, dbo.CLIENT.CL_NAME AS Client, dbo.DIVISION.DIV_NAME AS Division, 
									  dbo.PRODUCT.PRD_DESCRIPTION AS Product, dbo.JOB_LOG.JOB_NUMBER, dbo.JOB_LOG.OFFICE_CODE, dbo.JOB_LOG.JOB_DESC, 
									  dbo.JOB_LOG.JOB_CLI_REF, dbo.JOB_COMPONENT.JOB_COMPONENT_NBR, dbo.JOB_COMPONENT.JOB_COMP_DESC, 
									  dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL, dbo.JOB_COMPONENT.JOB_COMP_DATE, dbo.EMPLOYEE.EMP_CODE, 
									  dbo.EMPLOYEE.EMP_FNAME + ' ' + dbo.EMPLOYEE.EMP_LNAME AS [Account Executive], dbo.JOB_COMPONENT.START_DATE AS [Start Date],
									  dbo.JOB_COMPONENT.JOB_FIRST_USE_DATE AS [Due Date], dbo.JOB_LOG.USER_ID AS [User ID], 
									  dbo.CLIENT.CL_NAME + ' - ' + dbo.DIVISION.DIV_NAME + ' - ' + dbo.PRODUCT.PRD_DESCRIPTION AS CDP, dbo.JOB_LOG.SC_CODE, 
									  dbo.SALES_CLASS.SC_DESCRIPTION, dbo.JOB_TRAFFIC.COMPLETED_DATE, dbo.JOB_TRAFFIC.ROWID, dbo.JOB_TRAFFIC.TRF_COMMENTS, 
									  dbo.JOB_COMPONENT.TRF_SCHEDULE_REQ, dbo.JOB_TYPE.JT_CODE, dbo.JOB_TYPE.JT_DESC, dbo.TRAFFIC.TRF_CODE, 
									  dbo.TRAFFIC.TRF_DESCRIPTION, dbo.JOB_COMPONENT.ESTIMATE_NUMBER, dbo.ESTIMATE_APPROVAL.JOB_NUMBER AS EJobNum, 
									  dbo.ESTIMATE_APPROVAL.JOB_COMPONENT_NBR AS EJobComNum, JOB_TRAFFIC.MGR_EMP_CODE, dbo.JOB_COMPONENT.JOB_QTY
							FROM         dbo.JOB_LOG INNER JOIN
												  dbo.JOB_COMPONENT ON dbo.JOB_LOG.JOB_NUMBER = dbo.JOB_COMPONENT.JOB_NUMBER INNER JOIN
												  dbo.EMPLOYEE ON dbo.JOB_COMPONENT.EMP_CODE = dbo.EMPLOYEE.EMP_CODE LEFT OUTER JOIN
												  dbo.JOB_TYPE ON dbo.JOB_COMPONENT.JT_CODE = dbo.JOB_TYPE.JT_CODE INNER JOIN
												  dbo.CLIENT ON dbo.JOB_LOG.CL_CODE = dbo.CLIENT.CL_CODE INNER JOIN
												  dbo.PRODUCT ON dbo.JOB_LOG.CL_CODE = dbo.PRODUCT.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.PRODUCT.DIV_CODE AND 
												  dbo.JOB_LOG.PRD_CODE = dbo.PRODUCT.PRD_CODE INNER JOIN
												  dbo.DIVISION ON dbo.JOB_LOG.CL_CODE = dbo.DIVISION.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.DIVISION.DIV_CODE INNER JOIN
												  dbo.SALES_CLASS ON dbo.JOB_LOG.SC_CODE = dbo.SALES_CLASS.SC_CODE INNER JOIN
												  dbo.JOB_TRAFFIC ON dbo.JOB_LOG.JOB_NUMBER = dbo.JOB_TRAFFIC.JOB_NUMBER AND 
												  dbo.JOB_COMPONENT.JOB_COMPONENT_NBR = dbo.JOB_TRAFFIC.JOB_COMPONENT_NBR LEFT OUTER JOIN
												  dbo.TRAFFIC ON dbo.JOB_TRAFFIC.TRF_CODE = dbo.TRAFFIC.TRF_CODE LEFT OUTER JOIN
												  dbo.ESTIMATE_APPROVAL ON dbo.JOB_COMPONENT.JOB_NUMBER = dbo.ESTIMATE_APPROVAL.JOB_NUMBER AND 
												  dbo.JOB_COMPONENT.JOB_COMPONENT_NBR = dbo.ESTIMATE_APPROVAL.JOB_COMPONENT_NBR INNER JOIN EMP_OFFICE ON EMP_OFFICE.OFFICE_CODE = JOB_LOG.OFFICE_CODE AND EMP_OFFICE.EMP_CODE = @EMP_CDE
							WHERE     (dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL <> 6) AND (dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL <> 12) AND 
												  (dbo.JOB_TRAFFIC.COMPLETED_DATE IS NULL) AND (JOB_COMPONENT.JOB_FIRST_USE_DATE >= @Start_Date AND JOB_COMPONENT.JOB_FIRST_USE_DATE <= @End_Date)
							order by JOB_LOG.CL_CODE,
								JOB_LOG.DIV_CODE,
								JOB_LOG.PRD_CODE,
								JOB_COMPONENT.JOB_NUMBER, JOB_COMPONENT.JOB_COMPONENT_NBR
						End
						Else
						Begin
							SELECT     dbo.JOB_LOG.CL_CODE, dbo.JOB_LOG.DIV_CODE, dbo.JOB_LOG.PRD_CODE, dbo.CLIENT.CL_NAME AS Client, dbo.DIVISION.DIV_NAME AS Division, 
									  dbo.PRODUCT.PRD_DESCRIPTION AS Product, dbo.JOB_LOG.JOB_NUMBER, dbo.JOB_LOG.OFFICE_CODE, dbo.JOB_LOG.JOB_DESC, 
									  dbo.JOB_LOG.JOB_CLI_REF, dbo.JOB_COMPONENT.JOB_COMPONENT_NBR, dbo.JOB_COMPONENT.JOB_COMP_DESC, 
									  dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL, dbo.JOB_COMPONENT.JOB_COMP_DATE, dbo.EMPLOYEE.EMP_CODE, 
									  dbo.EMPLOYEE.EMP_FNAME + ' ' + dbo.EMPLOYEE.EMP_LNAME AS [Account Executive], dbo.JOB_COMPONENT.START_DATE AS [Start Date],
									  dbo.JOB_COMPONENT.JOB_FIRST_USE_DATE AS [Due Date], dbo.JOB_LOG.USER_ID AS [User ID], 
									  dbo.CLIENT.CL_NAME + ' - ' + dbo.DIVISION.DIV_NAME + ' - ' + dbo.PRODUCT.PRD_DESCRIPTION AS CDP, dbo.JOB_LOG.SC_CODE, 
									  dbo.SALES_CLASS.SC_DESCRIPTION, dbo.JOB_TRAFFIC.COMPLETED_DATE, dbo.JOB_TRAFFIC.ROWID, dbo.JOB_TRAFFIC.TRF_COMMENTS, 
									  dbo.JOB_COMPONENT.TRF_SCHEDULE_REQ, dbo.JOB_TYPE.JT_CODE, dbo.JOB_TYPE.JT_DESC, dbo.TRAFFIC.TRF_CODE, 
									  dbo.TRAFFIC.TRF_DESCRIPTION, dbo.JOB_COMPONENT.ESTIMATE_NUMBER, dbo.ESTIMATE_APPROVAL.JOB_NUMBER AS EJobNum, 
									  dbo.ESTIMATE_APPROVAL.JOB_COMPONENT_NBR AS EJobComNum, JOB_TRAFFIC.MGR_EMP_CODE, dbo.JOB_COMPONENT.JOB_QTY
							FROM         dbo.JOB_LOG INNER JOIN
												  dbo.JOB_COMPONENT ON dbo.JOB_LOG.JOB_NUMBER = dbo.JOB_COMPONENT.JOB_NUMBER INNER JOIN
												  dbo.EMPLOYEE ON dbo.JOB_COMPONENT.EMP_CODE = dbo.EMPLOYEE.EMP_CODE LEFT OUTER JOIN
												  dbo.JOB_TYPE ON dbo.JOB_COMPONENT.JT_CODE = dbo.JOB_TYPE.JT_CODE INNER JOIN
												  dbo.CLIENT ON dbo.JOB_LOG.CL_CODE = dbo.CLIENT.CL_CODE INNER JOIN
												  dbo.PRODUCT ON dbo.JOB_LOG.CL_CODE = dbo.PRODUCT.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.PRODUCT.DIV_CODE AND 
												  dbo.JOB_LOG.PRD_CODE = dbo.PRODUCT.PRD_CODE INNER JOIN
												  dbo.DIVISION ON dbo.JOB_LOG.CL_CODE = dbo.DIVISION.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.DIVISION.DIV_CODE INNER JOIN
												  dbo.SALES_CLASS ON dbo.JOB_LOG.SC_CODE = dbo.SALES_CLASS.SC_CODE INNER JOIN
												  dbo.JOB_TRAFFIC ON dbo.JOB_LOG.JOB_NUMBER = dbo.JOB_TRAFFIC.JOB_NUMBER AND 
												  dbo.JOB_COMPONENT.JOB_COMPONENT_NBR = dbo.JOB_TRAFFIC.JOB_COMPONENT_NBR LEFT OUTER JOIN
												  dbo.TRAFFIC ON dbo.JOB_TRAFFIC.TRF_CODE = dbo.TRAFFIC.TRF_CODE LEFT OUTER JOIN
												  dbo.ESTIMATE_APPROVAL ON dbo.JOB_COMPONENT.JOB_NUMBER = dbo.ESTIMATE_APPROVAL.JOB_NUMBER AND 
												  dbo.JOB_COMPONENT.JOB_COMPONENT_NBR = dbo.ESTIMATE_APPROVAL.JOB_COMPONENT_NBR
							WHERE     (dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL <> 6) AND (dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL <> 12) AND 
												  (dbo.JOB_TRAFFIC.COMPLETED_DATE IS NULL) AND (JOB_COMPONENT.JOB_FIRST_USE_DATE >= @Start_Date AND JOB_COMPONENT.JOB_FIRST_USE_DATE <= @End_Date)
							order by JOB_LOG.CL_CODE,
								JOB_LOG.DIV_CODE,
								JOB_LOG.PRD_CODE,
								JOB_COMPONENT.JOB_NUMBER, JOB_COMPONENT.JOB_COMPONENT_NBR
						End
						
					END

				END
			END

		ELSE --@AE <> '%'
			BEGIN
				If @Rescrictions > 0
				BEGIN
					if @IncludeCS = '1'
					BEGIN
						if @RestrictionsOffice > 0
						Begin
							SELECT     dbo.JOB_LOG.CL_CODE, dbo.JOB_LOG.DIV_CODE, dbo.JOB_LOG.PRD_CODE, dbo.CLIENT.CL_NAME AS Client, dbo.DIVISION.DIV_NAME AS Division, 
									  dbo.PRODUCT.PRD_DESCRIPTION AS Product, dbo.JOB_LOG.JOB_NUMBER, dbo.JOB_LOG.OFFICE_CODE, dbo.JOB_LOG.JOB_DESC, 
									  dbo.JOB_LOG.JOB_CLI_REF, dbo.JOB_COMPONENT.JOB_COMPONENT_NBR, dbo.JOB_COMPONENT.JOB_COMP_DESC, 
									  dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL, dbo.JOB_COMPONENT.JOB_COMP_DATE, dbo.EMPLOYEE.EMP_CODE, 
									  dbo.EMPLOYEE.EMP_FNAME + ' ' + dbo.EMPLOYEE.EMP_LNAME AS [Account Executive], dbo.JOB_COMPONENT.START_DATE AS [Start Date],
									  dbo.JOB_COMPONENT.JOB_FIRST_USE_DATE AS [Due Date], dbo.JOB_LOG.USER_ID AS [User ID], 
									  dbo.CLIENT.CL_NAME + ' - ' + dbo.DIVISION.DIV_NAME + ' - ' + dbo.PRODUCT.PRD_DESCRIPTION AS CDP, dbo.JOB_LOG.SC_CODE, 
									  dbo.SALES_CLASS.SC_DESCRIPTION, dbo.JOB_TRAFFIC.COMPLETED_DATE, dbo.JOB_TRAFFIC.ROWID, dbo.JOB_TRAFFIC.TRF_COMMENTS, 
									  dbo.JOB_COMPONENT.TRF_SCHEDULE_REQ, dbo.JOB_TYPE.JT_CODE, dbo.JOB_TYPE.JT_DESC, dbo.TRAFFIC.TRF_CODE, 
									  dbo.TRAFFIC.TRF_DESCRIPTION, dbo.JOB_COMPONENT.ESTIMATE_NUMBER, dbo.ESTIMATE_APPROVAL.JOB_NUMBER AS EJobNum, 
									  dbo.ESTIMATE_APPROVAL.JOB_COMPONENT_NBR AS EJobComNum, JOB_TRAFFIC.MGR_EMP_CODE, dbo.JOB_COMPONENT.JOB_QTY
							FROM         dbo.JOB_LOG INNER JOIN
												  dbo.JOB_COMPONENT ON dbo.JOB_LOG.JOB_NUMBER = dbo.JOB_COMPONENT.JOB_NUMBER INNER JOIN
												  dbo.EMPLOYEE ON dbo.JOB_COMPONENT.EMP_CODE = dbo.EMPLOYEE.EMP_CODE LEFT OUTER JOIN
												  dbo.JOB_TYPE ON dbo.JOB_COMPONENT.JT_CODE = dbo.JOB_TYPE.JT_CODE INNER JOIN
												  dbo.CLIENT ON dbo.JOB_LOG.CL_CODE = dbo.CLIENT.CL_CODE INNER JOIN
												  dbo.PRODUCT ON dbo.JOB_LOG.CL_CODE = dbo.PRODUCT.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.PRODUCT.DIV_CODE AND 
												  dbo.JOB_LOG.PRD_CODE = dbo.PRODUCT.PRD_CODE INNER JOIN
												  dbo.DIVISION ON dbo.JOB_LOG.CL_CODE = dbo.DIVISION.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.DIVISION.DIV_CODE INNER JOIN
												  dbo.SEC_CLIENT ON dbo.JOB_LOG.CL_CODE = dbo.SEC_CLIENT.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.SEC_CLIENT.DIV_CODE AND 
												  dbo.JOB_LOG.PRD_CODE = dbo.SEC_CLIENT.PRD_CODE INNER JOIN
												  dbo.SALES_CLASS ON dbo.JOB_LOG.SC_CODE = dbo.SALES_CLASS.SC_CODE INNER JOIN
												  dbo.JOB_TRAFFIC ON dbo.JOB_LOG.JOB_NUMBER = dbo.JOB_TRAFFIC.JOB_NUMBER AND 
												  dbo.JOB_COMPONENT.JOB_COMPONENT_NBR = dbo.JOB_TRAFFIC.JOB_COMPONENT_NBR LEFT OUTER JOIN
												  dbo.TRAFFIC ON dbo.JOB_TRAFFIC.TRF_CODE = dbo.TRAFFIC.TRF_CODE LEFT OUTER JOIN
												  dbo.ESTIMATE_APPROVAL ON dbo.JOB_COMPONENT.JOB_NUMBER = dbo.ESTIMATE_APPROVAL.JOB_NUMBER AND 
												  dbo.JOB_COMPONENT.JOB_COMPONENT_NBR = dbo.ESTIMATE_APPROVAL.JOB_COMPONENT_NBR INNER JOIN EMP_OFFICE ON EMP_OFFICE.OFFICE_CODE = JOB_LOG.OFFICE_CODE AND EMP_OFFICE.EMP_CODE = @EMP_CDE
										INNER JOIN charlist_to_table(@AEs, DEFAULT) g ON JOB_COMPONENT.EMP_CODE = g.vstr collate database_default
							WHERE     (dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL <> 6) AND (dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL <> 12) AND 
												  (JOB_COMPONENT.JOB_FIRST_USE_DATE >= @Start_Date AND JOB_COMPONENT.JOB_FIRST_USE_DATE <= @End_Date) AND UPPER(SEC_CLIENT.USER_ID) = UPPER(@UserID) AND (SEC_CLIENT.TIME_ENTRY = 0 OR SEC_CLIENT.TIME_ENTRY IS NULL)
							order by JOB_LOG.CL_CODE,
								JOB_LOG.DIV_CODE,
								JOB_LOG.PRD_CODE,
								JOB_COMPONENT.JOB_NUMBER, JOB_COMPONENT.JOB_COMPONENT_NBR
						End
						Else
						Begin
							SELECT     dbo.JOB_LOG.CL_CODE, dbo.JOB_LOG.DIV_CODE, dbo.JOB_LOG.PRD_CODE, dbo.CLIENT.CL_NAME AS Client, dbo.DIVISION.DIV_NAME AS Division, 
									  dbo.PRODUCT.PRD_DESCRIPTION AS Product, dbo.JOB_LOG.JOB_NUMBER, dbo.JOB_LOG.OFFICE_CODE, dbo.JOB_LOG.JOB_DESC, 
									  dbo.JOB_LOG.JOB_CLI_REF, dbo.JOB_COMPONENT.JOB_COMPONENT_NBR, dbo.JOB_COMPONENT.JOB_COMP_DESC, 
									  dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL, dbo.JOB_COMPONENT.JOB_COMP_DATE, dbo.EMPLOYEE.EMP_CODE, 
									  dbo.EMPLOYEE.EMP_FNAME + ' ' + dbo.EMPLOYEE.EMP_LNAME AS [Account Executive], dbo.JOB_COMPONENT.START_DATE AS [Start Date],
									  dbo.JOB_COMPONENT.JOB_FIRST_USE_DATE AS [Due Date], dbo.JOB_LOG.USER_ID AS [User ID], 
									  dbo.CLIENT.CL_NAME + ' - ' + dbo.DIVISION.DIV_NAME + ' - ' + dbo.PRODUCT.PRD_DESCRIPTION AS CDP, dbo.JOB_LOG.SC_CODE, 
									  dbo.SALES_CLASS.SC_DESCRIPTION, dbo.JOB_TRAFFIC.COMPLETED_DATE, dbo.JOB_TRAFFIC.ROWID, dbo.JOB_TRAFFIC.TRF_COMMENTS, 
									  dbo.JOB_COMPONENT.TRF_SCHEDULE_REQ, dbo.JOB_TYPE.JT_CODE, dbo.JOB_TYPE.JT_DESC, dbo.TRAFFIC.TRF_CODE, 
									  dbo.TRAFFIC.TRF_DESCRIPTION, dbo.JOB_COMPONENT.ESTIMATE_NUMBER, dbo.ESTIMATE_APPROVAL.JOB_NUMBER AS EJobNum, 
									  dbo.ESTIMATE_APPROVAL.JOB_COMPONENT_NBR AS EJobComNum, JOB_TRAFFIC.MGR_EMP_CODE, dbo.JOB_COMPONENT.JOB_QTY
							FROM         dbo.JOB_LOG INNER JOIN
												  dbo.JOB_COMPONENT ON dbo.JOB_LOG.JOB_NUMBER = dbo.JOB_COMPONENT.JOB_NUMBER INNER JOIN
												  dbo.EMPLOYEE ON dbo.JOB_COMPONENT.EMP_CODE = dbo.EMPLOYEE.EMP_CODE LEFT OUTER JOIN
												  dbo.JOB_TYPE ON dbo.JOB_COMPONENT.JT_CODE = dbo.JOB_TYPE.JT_CODE INNER JOIN
												  dbo.CLIENT ON dbo.JOB_LOG.CL_CODE = dbo.CLIENT.CL_CODE INNER JOIN
												  dbo.PRODUCT ON dbo.JOB_LOG.CL_CODE = dbo.PRODUCT.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.PRODUCT.DIV_CODE AND 
												  dbo.JOB_LOG.PRD_CODE = dbo.PRODUCT.PRD_CODE INNER JOIN
												  dbo.DIVISION ON dbo.JOB_LOG.CL_CODE = dbo.DIVISION.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.DIVISION.DIV_CODE INNER JOIN
												  dbo.SEC_CLIENT ON dbo.JOB_LOG.CL_CODE = dbo.SEC_CLIENT.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.SEC_CLIENT.DIV_CODE AND 
												  dbo.JOB_LOG.PRD_CODE = dbo.SEC_CLIENT.PRD_CODE INNER JOIN
												  dbo.SALES_CLASS ON dbo.JOB_LOG.SC_CODE = dbo.SALES_CLASS.SC_CODE INNER JOIN
												  dbo.JOB_TRAFFIC ON dbo.JOB_LOG.JOB_NUMBER = dbo.JOB_TRAFFIC.JOB_NUMBER AND 
												  dbo.JOB_COMPONENT.JOB_COMPONENT_NBR = dbo.JOB_TRAFFIC.JOB_COMPONENT_NBR LEFT OUTER JOIN
												  dbo.TRAFFIC ON dbo.JOB_TRAFFIC.TRF_CODE = dbo.TRAFFIC.TRF_CODE LEFT OUTER JOIN
												  dbo.ESTIMATE_APPROVAL ON dbo.JOB_COMPONENT.JOB_NUMBER = dbo.ESTIMATE_APPROVAL.JOB_NUMBER AND 
												  dbo.JOB_COMPONENT.JOB_COMPONENT_NBR = dbo.ESTIMATE_APPROVAL.JOB_COMPONENT_NBR
										INNER JOIN charlist_to_table(@AEs, DEFAULT) g ON JOB_COMPONENT.EMP_CODE = g.vstr collate database_default
							WHERE     (dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL <> 6) AND (dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL <> 12) AND 
												  (JOB_COMPONENT.JOB_FIRST_USE_DATE >= @Start_Date AND JOB_COMPONENT.JOB_FIRST_USE_DATE <= @End_Date) AND UPPER(SEC_CLIENT.USER_ID) = UPPER(@UserID) AND (SEC_CLIENT.TIME_ENTRY = 0 OR SEC_CLIENT.TIME_ENTRY IS NULL)
							order by JOB_LOG.CL_CODE,
								JOB_LOG.DIV_CODE,
								JOB_LOG.PRD_CODE,
								JOB_COMPONENT.JOB_NUMBER, JOB_COMPONENT.JOB_COMPONENT_NBR
						End
						
					END
					Else	--@IncludeCS = '1'
					BEGIN
						if @RestrictionsOffice > 0
						Begin
							SELECT     dbo.JOB_LOG.CL_CODE, dbo.JOB_LOG.DIV_CODE, dbo.JOB_LOG.PRD_CODE, dbo.CLIENT.CL_NAME AS Client, dbo.DIVISION.DIV_NAME AS Division, 
									  dbo.PRODUCT.PRD_DESCRIPTION AS Product, dbo.JOB_LOG.JOB_NUMBER, dbo.JOB_LOG.OFFICE_CODE, dbo.JOB_LOG.JOB_DESC, 
									  dbo.JOB_LOG.JOB_CLI_REF, dbo.JOB_COMPONENT.JOB_COMPONENT_NBR, dbo.JOB_COMPONENT.JOB_COMP_DESC, 
									  dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL, dbo.JOB_COMPONENT.JOB_COMP_DATE, dbo.EMPLOYEE.EMP_CODE, 
									  dbo.EMPLOYEE.EMP_FNAME + ' ' + dbo.EMPLOYEE.EMP_LNAME AS [Account Executive], dbo.JOB_COMPONENT.START_DATE AS [Start Date],
									  dbo.JOB_COMPONENT.JOB_FIRST_USE_DATE AS [Due Date], dbo.JOB_LOG.USER_ID AS [User ID], 
									  dbo.CLIENT.CL_NAME + ' - ' + dbo.DIVISION.DIV_NAME + ' - ' + dbo.PRODUCT.PRD_DESCRIPTION AS CDP, dbo.JOB_LOG.SC_CODE, 
									  dbo.SALES_CLASS.SC_DESCRIPTION, dbo.JOB_TRAFFIC.COMPLETED_DATE, dbo.JOB_TRAFFIC.ROWID, dbo.JOB_TRAFFIC.TRF_COMMENTS, 
									  dbo.JOB_COMPONENT.TRF_SCHEDULE_REQ, dbo.JOB_TYPE.JT_CODE, dbo.JOB_TYPE.JT_DESC, dbo.TRAFFIC.TRF_CODE, 
									  dbo.TRAFFIC.TRF_DESCRIPTION, dbo.JOB_COMPONENT.ESTIMATE_NUMBER, dbo.ESTIMATE_APPROVAL.JOB_NUMBER AS EJobNum, 
									  dbo.ESTIMATE_APPROVAL.JOB_COMPONENT_NBR AS EJobComNum, JOB_TRAFFIC.MGR_EMP_CODE, dbo.JOB_COMPONENT.JOB_QTY
							FROM         dbo.JOB_LOG INNER JOIN
												  dbo.JOB_COMPONENT ON dbo.JOB_LOG.JOB_NUMBER = dbo.JOB_COMPONENT.JOB_NUMBER INNER JOIN
												  dbo.EMPLOYEE ON dbo.JOB_COMPONENT.EMP_CODE = dbo.EMPLOYEE.EMP_CODE LEFT OUTER JOIN
												  dbo.JOB_TYPE ON dbo.JOB_COMPONENT.JT_CODE = dbo.JOB_TYPE.JT_CODE INNER JOIN
												  dbo.CLIENT ON dbo.JOB_LOG.CL_CODE = dbo.CLIENT.CL_CODE INNER JOIN
												  dbo.PRODUCT ON dbo.JOB_LOG.CL_CODE = dbo.PRODUCT.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.PRODUCT.DIV_CODE AND 
												  dbo.JOB_LOG.PRD_CODE = dbo.PRODUCT.PRD_CODE INNER JOIN
												  dbo.DIVISION ON dbo.JOB_LOG.CL_CODE = dbo.DIVISION.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.DIVISION.DIV_CODE INNER JOIN
												  dbo.SEC_CLIENT ON dbo.JOB_LOG.CL_CODE = dbo.SEC_CLIENT.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.SEC_CLIENT.DIV_CODE AND 
												  dbo.JOB_LOG.PRD_CODE = dbo.SEC_CLIENT.PRD_CODE INNER JOIN
												  dbo.SALES_CLASS ON dbo.JOB_LOG.SC_CODE = dbo.SALES_CLASS.SC_CODE INNER JOIN
												  dbo.JOB_TRAFFIC ON dbo.JOB_LOG.JOB_NUMBER = dbo.JOB_TRAFFIC.JOB_NUMBER AND 
												  dbo.JOB_COMPONENT.JOB_COMPONENT_NBR = dbo.JOB_TRAFFIC.JOB_COMPONENT_NBR LEFT OUTER JOIN
												  dbo.TRAFFIC ON dbo.JOB_TRAFFIC.TRF_CODE = dbo.TRAFFIC.TRF_CODE LEFT OUTER JOIN
												  dbo.ESTIMATE_APPROVAL ON dbo.JOB_COMPONENT.JOB_NUMBER = dbo.ESTIMATE_APPROVAL.JOB_NUMBER AND 
												  dbo.JOB_COMPONENT.JOB_COMPONENT_NBR = dbo.ESTIMATE_APPROVAL.JOB_COMPONENT_NBR INNER JOIN EMP_OFFICE ON EMP_OFFICE.OFFICE_CODE = JOB_LOG.OFFICE_CODE AND EMP_OFFICE.EMP_CODE = @EMP_CDE
										INNER JOIN charlist_to_table(@AEs, DEFAULT) g ON JOB_COMPONENT.EMP_CODE = g.vstr collate database_default
							WHERE     (dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL <> 6) AND (dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL <> 12) AND 
												  (dbo.JOB_TRAFFIC.COMPLETED_DATE IS NULL) AND (JOB_COMPONENT.JOB_FIRST_USE_DATE >= @Start_Date AND JOB_COMPONENT.JOB_FIRST_USE_DATE <= @End_Date) AND UPPER(SEC_CLIENT.USER_ID) = UPPER(@UserID) AND (SEC_CLIENT.TIME_ENTRY = 0 OR SEC_CLIENT.TIME_ENTRY IS NULL)
							order by JOB_LOG.CL_CODE,
								JOB_LOG.DIV_CODE,
								JOB_LOG.PRD_CODE,
								JOB_COMPONENT.JOB_NUMBER, JOB_COMPONENT.JOB_COMPONENT_NBR
						End
						Else
						Begin
							SELECT     dbo.JOB_LOG.CL_CODE, dbo.JOB_LOG.DIV_CODE, dbo.JOB_LOG.PRD_CODE, dbo.CLIENT.CL_NAME AS Client, dbo.DIVISION.DIV_NAME AS Division, 
									  dbo.PRODUCT.PRD_DESCRIPTION AS Product, dbo.JOB_LOG.JOB_NUMBER, dbo.JOB_LOG.OFFICE_CODE, dbo.JOB_LOG.JOB_DESC, 
									  dbo.JOB_LOG.JOB_CLI_REF, dbo.JOB_COMPONENT.JOB_COMPONENT_NBR, dbo.JOB_COMPONENT.JOB_COMP_DESC, 
									  dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL, dbo.JOB_COMPONENT.JOB_COMP_DATE, dbo.EMPLOYEE.EMP_CODE, 
									  dbo.EMPLOYEE.EMP_FNAME + ' ' + dbo.EMPLOYEE.EMP_LNAME AS [Account Executive], dbo.JOB_COMPONENT.START_DATE AS [Start Date],
									  dbo.JOB_COMPONENT.JOB_FIRST_USE_DATE AS [Due Date], dbo.JOB_LOG.USER_ID AS [User ID], 
									  dbo.CLIENT.CL_NAME + ' - ' + dbo.DIVISION.DIV_NAME + ' - ' + dbo.PRODUCT.PRD_DESCRIPTION AS CDP, dbo.JOB_LOG.SC_CODE, 
									  dbo.SALES_CLASS.SC_DESCRIPTION, dbo.JOB_TRAFFIC.COMPLETED_DATE, dbo.JOB_TRAFFIC.ROWID, dbo.JOB_TRAFFIC.TRF_COMMENTS, 
									  dbo.JOB_COMPONENT.TRF_SCHEDULE_REQ, dbo.JOB_TYPE.JT_CODE, dbo.JOB_TYPE.JT_DESC, dbo.TRAFFIC.TRF_CODE, 
									  dbo.TRAFFIC.TRF_DESCRIPTION, dbo.JOB_COMPONENT.ESTIMATE_NUMBER, dbo.ESTIMATE_APPROVAL.JOB_NUMBER AS EJobNum, 
									  dbo.ESTIMATE_APPROVAL.JOB_COMPONENT_NBR AS EJobComNum, JOB_TRAFFIC.MGR_EMP_CODE, dbo.JOB_COMPONENT.JOB_QTY
							FROM         dbo.JOB_LOG INNER JOIN
												  dbo.JOB_COMPONENT ON dbo.JOB_LOG.JOB_NUMBER = dbo.JOB_COMPONENT.JOB_NUMBER INNER JOIN
												  dbo.EMPLOYEE ON dbo.JOB_COMPONENT.EMP_CODE = dbo.EMPLOYEE.EMP_CODE LEFT OUTER JOIN
												  dbo.JOB_TYPE ON dbo.JOB_COMPONENT.JT_CODE = dbo.JOB_TYPE.JT_CODE INNER JOIN
												  dbo.CLIENT ON dbo.JOB_LOG.CL_CODE = dbo.CLIENT.CL_CODE INNER JOIN
												  dbo.PRODUCT ON dbo.JOB_LOG.CL_CODE = dbo.PRODUCT.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.PRODUCT.DIV_CODE AND 
												  dbo.JOB_LOG.PRD_CODE = dbo.PRODUCT.PRD_CODE INNER JOIN
												  dbo.DIVISION ON dbo.JOB_LOG.CL_CODE = dbo.DIVISION.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.DIVISION.DIV_CODE INNER JOIN
												  dbo.SEC_CLIENT ON dbo.JOB_LOG.CL_CODE = dbo.SEC_CLIENT.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.SEC_CLIENT.DIV_CODE AND 
												  dbo.JOB_LOG.PRD_CODE = dbo.SEC_CLIENT.PRD_CODE INNER JOIN
												  dbo.SALES_CLASS ON dbo.JOB_LOG.SC_CODE = dbo.SALES_CLASS.SC_CODE INNER JOIN
												  dbo.JOB_TRAFFIC ON dbo.JOB_LOG.JOB_NUMBER = dbo.JOB_TRAFFIC.JOB_NUMBER AND 
												  dbo.JOB_COMPONENT.JOB_COMPONENT_NBR = dbo.JOB_TRAFFIC.JOB_COMPONENT_NBR LEFT OUTER JOIN
												  dbo.TRAFFIC ON dbo.JOB_TRAFFIC.TRF_CODE = dbo.TRAFFIC.TRF_CODE LEFT OUTER JOIN
												  dbo.ESTIMATE_APPROVAL ON dbo.JOB_COMPONENT.JOB_NUMBER = dbo.ESTIMATE_APPROVAL.JOB_NUMBER AND 
												  dbo.JOB_COMPONENT.JOB_COMPONENT_NBR = dbo.ESTIMATE_APPROVAL.JOB_COMPONENT_NBR
										INNER JOIN charlist_to_table(@AEs, DEFAULT) g ON JOB_COMPONENT.EMP_CODE = g.vstr collate database_default
							WHERE     (dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL <> 6) AND (dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL <> 12) AND 
												  (dbo.JOB_TRAFFIC.COMPLETED_DATE IS NULL) AND (JOB_COMPONENT.JOB_FIRST_USE_DATE >= @Start_Date AND JOB_COMPONENT.JOB_FIRST_USE_DATE <= @End_Date) AND UPPER(SEC_CLIENT.USER_ID) = UPPER(@UserID) AND (SEC_CLIENT.TIME_ENTRY = 0 OR SEC_CLIENT.TIME_ENTRY IS NULL)
							order by JOB_LOG.CL_CODE,
								JOB_LOG.DIV_CODE,
								JOB_LOG.PRD_CODE,
								JOB_COMPONENT.JOB_NUMBER, JOB_COMPONENT.JOB_COMPONENT_NBR
						End
						
					END
		
				END
			ELSE	--@Rescrictions > 0
				BEGIN
					If @IncludeCS = '1'
					BEGIN
						if @RestrictionsOffice > 0
						Begin
							SELECT     dbo.JOB_LOG.CL_CODE, dbo.JOB_LOG.DIV_CODE, dbo.JOB_LOG.PRD_CODE, dbo.CLIENT.CL_NAME AS Client, dbo.DIVISION.DIV_NAME AS Division, 
									  dbo.PRODUCT.PRD_DESCRIPTION AS Product, dbo.JOB_LOG.JOB_NUMBER, dbo.JOB_LOG.OFFICE_CODE, dbo.JOB_LOG.JOB_DESC, 
									  dbo.JOB_LOG.JOB_CLI_REF, dbo.JOB_COMPONENT.JOB_COMPONENT_NBR, dbo.JOB_COMPONENT.JOB_COMP_DESC, 
									  dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL, dbo.JOB_COMPONENT.JOB_COMP_DATE, dbo.EMPLOYEE.EMP_CODE, 
									  dbo.EMPLOYEE.EMP_FNAME + ' ' + dbo.EMPLOYEE.EMP_LNAME AS [Account Executive], dbo.JOB_COMPONENT.START_DATE AS [Start Date],
									  dbo.JOB_COMPONENT.JOB_FIRST_USE_DATE AS [Due Date], dbo.JOB_LOG.USER_ID AS [User ID], 
									  dbo.CLIENT.CL_NAME + ' - ' + dbo.DIVISION.DIV_NAME + ' - ' + dbo.PRODUCT.PRD_DESCRIPTION AS CDP, dbo.JOB_LOG.SC_CODE, 
									  dbo.SALES_CLASS.SC_DESCRIPTION, dbo.JOB_TRAFFIC.COMPLETED_DATE, dbo.JOB_TRAFFIC.ROWID, dbo.JOB_TRAFFIC.TRF_COMMENTS, 
									  dbo.JOB_COMPONENT.TRF_SCHEDULE_REQ, dbo.JOB_TYPE.JT_CODE, dbo.JOB_TYPE.JT_DESC, dbo.TRAFFIC.TRF_CODE, 
									  dbo.TRAFFIC.TRF_DESCRIPTION, dbo.JOB_COMPONENT.ESTIMATE_NUMBER, dbo.ESTIMATE_APPROVAL.JOB_NUMBER AS EJobNum, 
									  dbo.ESTIMATE_APPROVAL.JOB_COMPONENT_NBR AS EJobComNum, JOB_TRAFFIC.MGR_EMP_CODE, dbo.JOB_COMPONENT.JOB_QTY
							FROM         dbo.JOB_LOG INNER JOIN
												  dbo.JOB_COMPONENT ON dbo.JOB_LOG.JOB_NUMBER = dbo.JOB_COMPONENT.JOB_NUMBER INNER JOIN
												  dbo.EMPLOYEE ON dbo.JOB_COMPONENT.EMP_CODE = dbo.EMPLOYEE.EMP_CODE LEFT OUTER JOIN
												  dbo.JOB_TYPE ON dbo.JOB_COMPONENT.JT_CODE = dbo.JOB_TYPE.JT_CODE INNER JOIN
												  dbo.CLIENT ON dbo.JOB_LOG.CL_CODE = dbo.CLIENT.CL_CODE INNER JOIN
												  dbo.PRODUCT ON dbo.JOB_LOG.CL_CODE = dbo.PRODUCT.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.PRODUCT.DIV_CODE AND 
												  dbo.JOB_LOG.PRD_CODE = dbo.PRODUCT.PRD_CODE INNER JOIN
												  dbo.DIVISION ON dbo.JOB_LOG.CL_CODE = dbo.DIVISION.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.DIVISION.DIV_CODE INNER JOIN
												  dbo.SALES_CLASS ON dbo.JOB_LOG.SC_CODE = dbo.SALES_CLASS.SC_CODE INNER JOIN
												  dbo.JOB_TRAFFIC ON dbo.JOB_LOG.JOB_NUMBER = dbo.JOB_TRAFFIC.JOB_NUMBER AND 
												  dbo.JOB_COMPONENT.JOB_COMPONENT_NBR = dbo.JOB_TRAFFIC.JOB_COMPONENT_NBR LEFT OUTER JOIN
												  dbo.TRAFFIC ON dbo.JOB_TRAFFIC.TRF_CODE = dbo.TRAFFIC.TRF_CODE LEFT OUTER JOIN
												  dbo.ESTIMATE_APPROVAL ON dbo.JOB_COMPONENT.JOB_NUMBER = dbo.ESTIMATE_APPROVAL.JOB_NUMBER AND 
												  dbo.JOB_COMPONENT.JOB_COMPONENT_NBR = dbo.ESTIMATE_APPROVAL.JOB_COMPONENT_NBR INNER JOIN EMP_OFFICE ON EMP_OFFICE.OFFICE_CODE = JOB_LOG.OFFICE_CODE AND EMP_OFFICE.EMP_CODE = @EMP_CDE
										INNER JOIN charlist_to_table(@AEs, DEFAULT) g ON JOB_COMPONENT.EMP_CODE = g.vstr collate database_default
							WHERE     (dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL <> 6) AND (dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL <> 12) AND 
												  (JOB_COMPONENT.JOB_FIRST_USE_DATE >= @Start_Date AND JOB_COMPONENT.JOB_FIRST_USE_DATE <= @End_Date)
							order by JOB_LOG.CL_CODE,
								JOB_LOG.DIV_CODE,
								JOB_LOG.PRD_CODE,
								JOB_COMPONENT.JOB_NUMBER, JOB_COMPONENT.JOB_COMPONENT_NBR
						End
						Else
						Begin
							SELECT     dbo.JOB_LOG.CL_CODE, dbo.JOB_LOG.DIV_CODE, dbo.JOB_LOG.PRD_CODE, dbo.CLIENT.CL_NAME AS Client, dbo.DIVISION.DIV_NAME AS Division, 
									  dbo.PRODUCT.PRD_DESCRIPTION AS Product, dbo.JOB_LOG.JOB_NUMBER, dbo.JOB_LOG.OFFICE_CODE, dbo.JOB_LOG.JOB_DESC, 
									  dbo.JOB_LOG.JOB_CLI_REF, dbo.JOB_COMPONENT.JOB_COMPONENT_NBR, dbo.JOB_COMPONENT.JOB_COMP_DESC, 
									  dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL, dbo.JOB_COMPONENT.JOB_COMP_DATE, dbo.EMPLOYEE.EMP_CODE, 
									  dbo.EMPLOYEE.EMP_FNAME + ' ' + dbo.EMPLOYEE.EMP_LNAME AS [Account Executive], dbo.JOB_COMPONENT.START_DATE AS [Start Date],
									  dbo.JOB_COMPONENT.JOB_FIRST_USE_DATE AS [Due Date], dbo.JOB_LOG.USER_ID AS [User ID], 
									  dbo.CLIENT.CL_NAME + ' - ' + dbo.DIVISION.DIV_NAME + ' - ' + dbo.PRODUCT.PRD_DESCRIPTION AS CDP, dbo.JOB_LOG.SC_CODE, 
									  dbo.SALES_CLASS.SC_DESCRIPTION, dbo.JOB_TRAFFIC.COMPLETED_DATE, dbo.JOB_TRAFFIC.ROWID, dbo.JOB_TRAFFIC.TRF_COMMENTS, 
									  dbo.JOB_COMPONENT.TRF_SCHEDULE_REQ, dbo.JOB_TYPE.JT_CODE, dbo.JOB_TYPE.JT_DESC, dbo.TRAFFIC.TRF_CODE, 
									  dbo.TRAFFIC.TRF_DESCRIPTION, dbo.JOB_COMPONENT.ESTIMATE_NUMBER, dbo.ESTIMATE_APPROVAL.JOB_NUMBER AS EJobNum, 
									  dbo.ESTIMATE_APPROVAL.JOB_COMPONENT_NBR AS EJobComNum, JOB_TRAFFIC.MGR_EMP_CODE, dbo.JOB_COMPONENT.JOB_QTY
							FROM         dbo.JOB_LOG INNER JOIN
												  dbo.JOB_COMPONENT ON dbo.JOB_LOG.JOB_NUMBER = dbo.JOB_COMPONENT.JOB_NUMBER INNER JOIN
												  dbo.EMPLOYEE ON dbo.JOB_COMPONENT.EMP_CODE = dbo.EMPLOYEE.EMP_CODE LEFT OUTER JOIN
												  dbo.JOB_TYPE ON dbo.JOB_COMPONENT.JT_CODE = dbo.JOB_TYPE.JT_CODE INNER JOIN
												  dbo.CLIENT ON dbo.JOB_LOG.CL_CODE = dbo.CLIENT.CL_CODE INNER JOIN
												  dbo.PRODUCT ON dbo.JOB_LOG.CL_CODE = dbo.PRODUCT.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.PRODUCT.DIV_CODE AND 
												  dbo.JOB_LOG.PRD_CODE = dbo.PRODUCT.PRD_CODE INNER JOIN
												  dbo.DIVISION ON dbo.JOB_LOG.CL_CODE = dbo.DIVISION.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.DIVISION.DIV_CODE INNER JOIN
												  dbo.SALES_CLASS ON dbo.JOB_LOG.SC_CODE = dbo.SALES_CLASS.SC_CODE INNER JOIN
												  dbo.JOB_TRAFFIC ON dbo.JOB_LOG.JOB_NUMBER = dbo.JOB_TRAFFIC.JOB_NUMBER AND 
												  dbo.JOB_COMPONENT.JOB_COMPONENT_NBR = dbo.JOB_TRAFFIC.JOB_COMPONENT_NBR LEFT OUTER JOIN
												  dbo.TRAFFIC ON dbo.JOB_TRAFFIC.TRF_CODE = dbo.TRAFFIC.TRF_CODE LEFT OUTER JOIN
												  dbo.ESTIMATE_APPROVAL ON dbo.JOB_COMPONENT.JOB_NUMBER = dbo.ESTIMATE_APPROVAL.JOB_NUMBER AND 
												  dbo.JOB_COMPONENT.JOB_COMPONENT_NBR = dbo.ESTIMATE_APPROVAL.JOB_COMPONENT_NBR
										INNER JOIN charlist_to_table(@AEs, DEFAULT) g ON JOB_COMPONENT.EMP_CODE = g.vstr collate database_default
							WHERE     (dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL <> 6) AND (dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL <> 12) AND 
												  (JOB_COMPONENT.JOB_FIRST_USE_DATE >= @Start_Date AND JOB_COMPONENT.JOB_FIRST_USE_DATE <= @End_Date)
							order by JOB_LOG.CL_CODE,
								JOB_LOG.DIV_CODE,
								JOB_LOG.PRD_CODE,
								JOB_COMPONENT.JOB_NUMBER, JOB_COMPONENT.JOB_COMPONENT_NBR
						End
						
					END
					Else	--@IncludeCS = '1'
					BEGIN
						if @RestrictionsOffice > 0
						Begin
							SELECT     dbo.JOB_LOG.CL_CODE, dbo.JOB_LOG.DIV_CODE, dbo.JOB_LOG.PRD_CODE, dbo.CLIENT.CL_NAME AS Client, dbo.DIVISION.DIV_NAME AS Division, 
									  dbo.PRODUCT.PRD_DESCRIPTION AS Product, dbo.JOB_LOG.JOB_NUMBER, dbo.JOB_LOG.OFFICE_CODE, dbo.JOB_LOG.JOB_DESC, 
									  dbo.JOB_LOG.JOB_CLI_REF, dbo.JOB_COMPONENT.JOB_COMPONENT_NBR, dbo.JOB_COMPONENT.JOB_COMP_DESC, 
									  dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL, dbo.JOB_COMPONENT.JOB_COMP_DATE, dbo.EMPLOYEE.EMP_CODE, 
									  dbo.EMPLOYEE.EMP_FNAME + ' ' + dbo.EMPLOYEE.EMP_LNAME AS [Account Executive], dbo.JOB_COMPONENT.START_DATE AS [Start Date],
									  dbo.JOB_COMPONENT.JOB_FIRST_USE_DATE AS [Due Date], dbo.JOB_LOG.USER_ID AS [User ID], 
									  dbo.CLIENT.CL_NAME + ' - ' + dbo.DIVISION.DIV_NAME + ' - ' + dbo.PRODUCT.PRD_DESCRIPTION AS CDP, dbo.JOB_LOG.SC_CODE, 
									  dbo.SALES_CLASS.SC_DESCRIPTION, dbo.JOB_TRAFFIC.COMPLETED_DATE, dbo.JOB_TRAFFIC.ROWID, dbo.JOB_TRAFFIC.TRF_COMMENTS, 
									  dbo.JOB_COMPONENT.TRF_SCHEDULE_REQ, dbo.JOB_TYPE.JT_CODE, dbo.JOB_TYPE.JT_DESC, dbo.TRAFFIC.TRF_CODE, 
									  dbo.TRAFFIC.TRF_DESCRIPTION, dbo.JOB_COMPONENT.ESTIMATE_NUMBER, dbo.ESTIMATE_APPROVAL.JOB_NUMBER AS EJobNum, 
									  dbo.ESTIMATE_APPROVAL.JOB_COMPONENT_NBR AS EJobComNum, JOB_TRAFFIC.MGR_EMP_CODE, dbo.JOB_COMPONENT.JOB_QTY
							FROM         dbo.JOB_LOG INNER JOIN
												  dbo.JOB_COMPONENT ON dbo.JOB_LOG.JOB_NUMBER = dbo.JOB_COMPONENT.JOB_NUMBER INNER JOIN
												  dbo.EMPLOYEE ON dbo.JOB_COMPONENT.EMP_CODE = dbo.EMPLOYEE.EMP_CODE LEFT OUTER JOIN
												  dbo.JOB_TYPE ON dbo.JOB_COMPONENT.JT_CODE = dbo.JOB_TYPE.JT_CODE INNER JOIN
												  dbo.CLIENT ON dbo.JOB_LOG.CL_CODE = dbo.CLIENT.CL_CODE INNER JOIN
												  dbo.PRODUCT ON dbo.JOB_LOG.CL_CODE = dbo.PRODUCT.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.PRODUCT.DIV_CODE AND 
												  dbo.JOB_LOG.PRD_CODE = dbo.PRODUCT.PRD_CODE INNER JOIN
												  dbo.DIVISION ON dbo.JOB_LOG.CL_CODE = dbo.DIVISION.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.DIVISION.DIV_CODE INNER JOIN
												  dbo.SALES_CLASS ON dbo.JOB_LOG.SC_CODE = dbo.SALES_CLASS.SC_CODE INNER JOIN
												  dbo.JOB_TRAFFIC ON dbo.JOB_LOG.JOB_NUMBER = dbo.JOB_TRAFFIC.JOB_NUMBER AND 
												  dbo.JOB_COMPONENT.JOB_COMPONENT_NBR = dbo.JOB_TRAFFIC.JOB_COMPONENT_NBR LEFT OUTER JOIN
												  dbo.TRAFFIC ON dbo.JOB_TRAFFIC.TRF_CODE = dbo.TRAFFIC.TRF_CODE LEFT OUTER JOIN
												  dbo.ESTIMATE_APPROVAL ON dbo.JOB_COMPONENT.JOB_NUMBER = dbo.ESTIMATE_APPROVAL.JOB_NUMBER AND 
												  dbo.JOB_COMPONENT.JOB_COMPONENT_NBR = dbo.ESTIMATE_APPROVAL.JOB_COMPONENT_NBR INNER JOIN EMP_OFFICE ON EMP_OFFICE.OFFICE_CODE = JOB_LOG.OFFICE_CODE AND EMP_OFFICE.EMP_CODE = @EMP_CDE
										INNER JOIN charlist_to_table(@AEs, DEFAULT) g ON JOB_COMPONENT.EMP_CODE = g.vstr collate database_default
							WHERE     (dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL <> 6) AND (dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL <> 12) AND 
												  (dbo.JOB_TRAFFIC.COMPLETED_DATE IS NULL) AND (JOB_COMPONENT.JOB_FIRST_USE_DATE >= @Start_Date AND JOB_COMPONENT.JOB_FIRST_USE_DATE <= @End_Date)
							order by JOB_LOG.CL_CODE,
								JOB_LOG.DIV_CODE,
								JOB_LOG.PRD_CODE,
								JOB_COMPONENT.JOB_NUMBER, JOB_COMPONENT.JOB_COMPONENT_NBR
						End
						Else
						Begin
							SELECT     dbo.JOB_LOG.CL_CODE, dbo.JOB_LOG.DIV_CODE, dbo.JOB_LOG.PRD_CODE, dbo.CLIENT.CL_NAME AS Client, dbo.DIVISION.DIV_NAME AS Division, 
									  dbo.PRODUCT.PRD_DESCRIPTION AS Product, dbo.JOB_LOG.JOB_NUMBER, dbo.JOB_LOG.OFFICE_CODE, dbo.JOB_LOG.JOB_DESC, 
									  dbo.JOB_LOG.JOB_CLI_REF, dbo.JOB_COMPONENT.JOB_COMPONENT_NBR, dbo.JOB_COMPONENT.JOB_COMP_DESC, 
									  dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL, dbo.JOB_COMPONENT.JOB_COMP_DATE, dbo.EMPLOYEE.EMP_CODE, 
									  dbo.EMPLOYEE.EMP_FNAME + ' ' + dbo.EMPLOYEE.EMP_LNAME AS [Account Executive], dbo.JOB_COMPONENT.START_DATE AS [Start Date],
									  dbo.JOB_COMPONENT.JOB_FIRST_USE_DATE AS [Due Date], dbo.JOB_LOG.USER_ID AS [User ID], 
									  dbo.CLIENT.CL_NAME + ' - ' + dbo.DIVISION.DIV_NAME + ' - ' + dbo.PRODUCT.PRD_DESCRIPTION AS CDP, dbo.JOB_LOG.SC_CODE, 
									  dbo.SALES_CLASS.SC_DESCRIPTION, dbo.JOB_TRAFFIC.COMPLETED_DATE, dbo.JOB_TRAFFIC.ROWID, dbo.JOB_TRAFFIC.TRF_COMMENTS, 
									  dbo.JOB_COMPONENT.TRF_SCHEDULE_REQ, dbo.JOB_TYPE.JT_CODE, dbo.JOB_TYPE.JT_DESC, dbo.TRAFFIC.TRF_CODE, 
									  dbo.TRAFFIC.TRF_DESCRIPTION, dbo.JOB_COMPONENT.ESTIMATE_NUMBER, dbo.ESTIMATE_APPROVAL.JOB_NUMBER AS EJobNum, 
									  dbo.ESTIMATE_APPROVAL.JOB_COMPONENT_NBR AS EJobComNum, JOB_TRAFFIC.MGR_EMP_CODE, dbo.JOB_COMPONENT.JOB_QTY
							FROM         dbo.JOB_LOG INNER JOIN
												  dbo.JOB_COMPONENT ON dbo.JOB_LOG.JOB_NUMBER = dbo.JOB_COMPONENT.JOB_NUMBER INNER JOIN
												  dbo.EMPLOYEE ON dbo.JOB_COMPONENT.EMP_CODE = dbo.EMPLOYEE.EMP_CODE LEFT OUTER JOIN
												  dbo.JOB_TYPE ON dbo.JOB_COMPONENT.JT_CODE = dbo.JOB_TYPE.JT_CODE INNER JOIN
												  dbo.CLIENT ON dbo.JOB_LOG.CL_CODE = dbo.CLIENT.CL_CODE INNER JOIN
												  dbo.PRODUCT ON dbo.JOB_LOG.CL_CODE = dbo.PRODUCT.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.PRODUCT.DIV_CODE AND 
												  dbo.JOB_LOG.PRD_CODE = dbo.PRODUCT.PRD_CODE INNER JOIN
												  dbo.DIVISION ON dbo.JOB_LOG.CL_CODE = dbo.DIVISION.CL_CODE AND dbo.JOB_LOG.DIV_CODE = dbo.DIVISION.DIV_CODE INNER JOIN
												  dbo.SALES_CLASS ON dbo.JOB_LOG.SC_CODE = dbo.SALES_CLASS.SC_CODE INNER JOIN
												  dbo.JOB_TRAFFIC ON dbo.JOB_LOG.JOB_NUMBER = dbo.JOB_TRAFFIC.JOB_NUMBER AND 
												  dbo.JOB_COMPONENT.JOB_COMPONENT_NBR = dbo.JOB_TRAFFIC.JOB_COMPONENT_NBR LEFT OUTER JOIN
												  dbo.TRAFFIC ON dbo.JOB_TRAFFIC.TRF_CODE = dbo.TRAFFIC.TRF_CODE LEFT OUTER JOIN
												  dbo.ESTIMATE_APPROVAL ON dbo.JOB_COMPONENT.JOB_NUMBER = dbo.ESTIMATE_APPROVAL.JOB_NUMBER AND 
												  dbo.JOB_COMPONENT.JOB_COMPONENT_NBR = dbo.ESTIMATE_APPROVAL.JOB_COMPONENT_NBR
										INNER JOIN charlist_to_table(@AEs, DEFAULT) g ON JOB_COMPONENT.EMP_CODE = g.vstr collate database_default
							WHERE     (dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL <> 6) AND (dbo.JOB_COMPONENT.JOB_PROCESS_CONTRL <> 12) AND 
												  (dbo.JOB_TRAFFIC.COMPLETED_DATE IS NULL) AND (JOB_COMPONENT.JOB_FIRST_USE_DATE >= @Start_Date AND JOB_COMPONENT.JOB_FIRST_USE_DATE <= @End_Date)
							order by JOB_LOG.CL_CODE,
								JOB_LOG.DIV_CODE,
								JOB_LOG.PRD_CODE,
								JOB_COMPONENT.JOB_NUMBER, JOB_COMPONENT.JOB_COMPONENT_NBR
						End
						
					END	--@IncludeCS = '1'
				END
			END
	END
--print @Rescrictions
--@UserID



