

CREATE PROCEDURE [dbo].[usp_wv_Estimating_AddNew_AddQuote]
(
	@ESTIMATE_NUMBER INT,
	@EST_COMPONENT_NBR INT,
	@EST_QUOTE_NBR INT,
	@EST_REV_NBR INT
)
AS
BEGIN
	SET NOCOUNT OFF
	DECLARE 
	@ERR INT,
	@NEXT_EST_NBR INT
	
    --SELECT @NEXT_EST_NBR = ISNULL(MAX(ESTIMATE_NUMBER),-1) + 1 FROM ESTIMATE_LOG 
    
    INSERT INTO [ESTIMATE_QUOTE]
		(
			[ESTIMATE_NUMBER],
			[EST_COMPONENT_NBR],
			[EST_QUOTE_NBR],
			[EST_QTE_COMMENT],
			[EST_QUOTE_DESC],
			[EST_QTE_COMMENT_HTML]
		)
		VALUES
		(
			@ESTIMATE_NUMBER,
			@EST_COMPONENT_NBR,
			@EST_QUOTE_NBR,
			NULL,
			NULL,
			NULL
		)

	INSERT INTO [ESTIMATE_REV]
		(
			[ESTIMATE_NUMBER],
			[EST_COMPONENT_NBR],
			[EST_QUOTE_NBR],
			[EST_REV_NBR],
			[EST_REV_COMMENT],
			[TECHNOLOGY_PCT],
			[TECHNOLOGY_AMT],
			[SPEC_VER],
			[SPEC_REV],
			[SPEC_QTY_SEQ_NBR],
			[JOB_QTY],
			[SPEC_RTF],
			[BLENDED_TIME_RATE],
			[EST_REV_COMMENT_HTML]
		)
		VALUES
		(
			@ESTIMATE_NUMBER,
			@EST_COMPONENT_NBR,
			@EST_QUOTE_NBR,
			@EST_REV_NBR,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL
		)	

	SET @ERR = @@Error

	--RETURN @ERR
END

--SELECT @QTE_NUM = @NEXT_EST_NBR


