--DROP PROCEDURE [dbo].[usp_wv_get_attached_media_all]
CREATE PROCEDURE [dbo].[usp_wv_get_attached_media_all] 
@CmpID as Integer
AS

SELECT 1 as SORT, 'INTERNET' AS TYPE, CAST(ORDER_NBR AS VARCHAR(10)) AS ORDER_NBR,  ORDER_DESC, VENDOR.VN_CODE, VENDOR.VN_NAME,
	SALES_CLASS.SC_CODE, SALES_CLASS.SC_DESCRIPTION, ORDER_DATE, 'Internet Orders' AS GROUP_DESC, ORDER_NBR as SORT_ORDER
FROM INTERNET_HEADER XX
  INNER JOIN VENDOR ON VENDOR.VN_CODE = XX.VN_CODE
  INNER JOIN SALES_CLASS ON SALES_CLASS.SC_CODE = XX.MEDIA_TYPE
WHERE XX.CMP_IDENTIFIER = @CmpID 
UNION
SELECT 1, 'MAGAZINE', CAST(ORDER_NBR AS VARCHAR(10)), ORDER_DESC, VENDOR.VN_CODE,VENDOR.VN_NAME,
	SALES_CLASS.SC_CODE, SALES_CLASS.SC_DESCRIPTION, ORDER_DATE, 'Magazine Orders', ORDER_NBR
FROM MAGAZINE_HEADER XX
  INNER JOIN VENDOR ON VENDOR.VN_CODE = XX.VN_CODE
  INNER JOIN SALES_CLASS ON SALES_CLASS.SC_CODE = XX.MEDIA_TYPE
WHERE XX.CMP_IDENTIFIER = @CmpID 
UNION	
SELECT 1, 'NEWSPAPER', CAST(ORDER_NBR AS VARCHAR(10)), ORDER_DESC, VENDOR.VN_CODE, VENDOR.VN_NAME,
	SALES_CLASS.SC_CODE, SALES_CLASS.SC_DESCRIPTION, ORDER_DATE, 'Newspaper Orders', ORDER_NBR
FROM NEWSPAPER_HEADER XX
  INNER JOIN VENDOR ON VENDOR.VN_CODE = XX.VN_CODE
  INNER JOIN SALES_CLASS ON SALES_CLASS.SC_CODE = XX.MEDIA_TYPE
WHERE XX.CMP_IDENTIFIER = @CmpID 
UNION		
SELECT 1, 'OUTDOOR', CAST(ORDER_NBR AS VARCHAR(10)), ORDER_DESC, VENDOR.VN_CODE, VENDOR.VN_NAME,
	SALES_CLASS.SC_CODE, SALES_CLASS.SC_DESCRIPTION, ORDER_DATE, 'Out of Home Orders', ORDER_NBR
FROM OUTDOOR_HEADER XX
  INNER JOIN VENDOR ON VENDOR.VN_CODE = XX.VN_CODE
  INNER JOIN SALES_CLASS ON SALES_CLASS.SC_CODE = XX.MEDIA_TYPE
WHERE XX.CMP_IDENTIFIER = @CmpID
UNION		
SELECT 1, 'RADIO', CAST(ORDER_NBR AS VARCHAR(10)), ORDER_DESC, VENDOR.VN_CODE, VENDOR.VN_NAME,
	SALES_CLASS.SC_CODE, SALES_CLASS.SC_DESCRIPTION, ORDER_DATE, 'Radio Orders', ORDER_NBR
FROM RADIO_HDR XX
  INNER JOIN VENDOR ON VENDOR.VN_CODE = XX.VN_CODE
  INNER JOIN SALES_CLASS ON SALES_CLASS.SC_CODE = XX.MEDIA_TYPE
WHERE XX.CMP_IDENTIFIER = @CmpID
  --AND XX.REV_NBR = (SELECT MAX(XX2.REV_NBR) FROM RADIO_HEADER XX2 WHERE XX.ORDER_NBR = XX2.ORDER_NBR )
UNION	
SELECT 1, 'TV', CAST(ORDER_NBR AS VARCHAR(10)), ORDER_DESC, VENDOR.VN_CODE, VENDOR.VN_NAME,
	SALES_CLASS.SC_CODE, SALES_CLASS.SC_DESCRIPTION, ORDER_DATE, 'TV Orders', ORDER_NBR
FROM TV_HDR XX
  INNER JOIN VENDOR ON VENDOR.VN_CODE = XX.VN_CODE
  INNER JOIN SALES_CLASS ON SALES_CLASS.SC_CODE = XX.MEDIA_TYPE
WHERE XX.CMP_IDENTIFIER = @CmpID
  --AND XX.REV_NBR = (SELECT MAX(XX2.REV_NBR) FROM TV_HEADER XX2 WHERE XX.ORDER_NBR = XX2.ORDER_NBR )
UNION		
SELECT 0, 'JOB', CAST(JOB_NUMBER AS VARCHAR(10)), JOB_DESC, '','', XX.SC_CODE, SALES_CLASS.SC_DESCRIPTION, JOB_DATE_OPENED, 'Production Jobs', JOB_NUMBER
FROM JOB_LOG XX
  INNER JOIN SALES_CLASS ON SALES_CLASS.SC_CODE = XX.SC_CODE
WHERE CMP_IDENTIFIER = @CmpID
ORDER BY SORT, TYPE, SORT_ORDER


