
CREATE PROCEDURE [dbo].[usp_wv_Job_Template_GetDetailsForNewComp]
@JobNum INT,
@CL_CODE VARCHAR(6) OUTPUT,
@DIV_CODE VARCHAR(6) OUTPUT,
@PRD_CODE VARCHAR(6) OUTPUT,
@CliDescript VARCHAR(400) OUTPUT,
@DivDescript VARCHAR(400) OUTPUT,
@ProdDescript VARCHAR(400) OUTPUT,
@JobDescript VARCHAR(400) OUTPUT

AS

SELECT     
	@CL_CODE = JOB_LOG.CL_CODE, 
	@CliDescript = JOB_LOG.CL_CODE+'&nbsp;-&nbsp;'+CLIENT.CL_NAME, 
	@DIV_CODE = JOB_LOG.DIV_CODE, 
	@DivDescript = JOB_LOG.DIV_CODE+'&nbsp;-&nbsp;'+DIVISION.DIV_NAME, 
	@PRD_CODE = JOB_LOG.PRD_CODE, 
	@ProdDescript = JOB_LOG.PRD_CODE+'&nbsp;-&nbsp;'+PRODUCT.PRD_DESCRIPTION, 
	--JOB_LOG.JOB_NUMBER, 
	@JobDescript = CONVERT(VARCHAR(25), JOB_LOG.JOB_NUMBER)+'&nbsp;-&nbsp;'+JOB_LOG.JOB_DESC
FROM 
	JOB_LOG INNER JOIN
	CLIENT ON JOB_LOG.CL_CODE = CLIENT.CL_CODE INNER JOIN
	PRODUCT ON JOB_LOG.CL_CODE = PRODUCT.CL_CODE AND JOB_LOG.DIV_CODE = PRODUCT.DIV_CODE AND 
	JOB_LOG.PRD_CODE = PRODUCT.PRD_CODE INNER JOIN
	DIVISION ON JOB_LOG.CL_CODE = DIVISION.CL_CODE AND JOB_LOG.DIV_CODE = DIVISION.DIV_CODE
WHERE
	JOB_LOG.JOB_NUMBER = @JobNum

