

CREATE PROCEDURE [dbo].[usp_wv_Vendor_Quote_AddNewVendor]
(
	@ESTIMATE_NUMBER INT,
	@EST_COMPONENT_NBR SMALLINT,
	@VENDOR_QTE_NBR INT,
	@VN_CODE VARCHAR(6),
	@VN_CONT_CODE VARCHAR(4),
	@VN_NOTES TEXT,
	@DISPATCH_DATE smalldatetime,
	@DUE_DATE smalldatetime,
	@REPLY_DATE smalldatetime,
	@SUBMITTED_BY varchar(100)
)
AS
BEGIN
	SET NOCOUNT OFF
	
	DECLARE 
	@ERR INT--,
	--@NEXT_EST_NBR INT
	
    --SELECT @NEXT_EST_NBR = ISNULL(MAX(ESTIMATE_NUMBER),-1) + 1 FROM ESTIMATE_LOG 
    
    INSERT INTO [VENDOR_QTE_VEN]
		(
			[ESTIMATE_NUMBER],
			[EST_COMPONENT_NBR],
			[VENDOR_QTE_NBR],
			[VN_CODE],
			[VN_CONT_CODE],
			[VN_NOTES],
			[DISPATCH_DATE],
			[DUE_DATE],
			[REPLY_DATE],
			[SUBMITTED_BY]
		)
		VALUES
		(
			@ESTIMATE_NUMBER,
			@EST_COMPONENT_NBR,
			@VENDOR_QTE_NBR,
			@VN_CODE,
			@VN_CONT_CODE,
			@VN_NOTES,
			@DISPATCH_DATE,
			@DUE_DATE,
			@REPLY_DATE,
			@SUBMITTED_BY
		)

	
	SET @ERR = @@Error

	--RETURN @ERR
END




