
CREATE PROCEDURE [dbo].[usp_wv_SOFTWARE_VERSION_GET_BY_SOFTWARE_PRODUCT] /*WITH ENCRYPTION*/
@SOFTWARE_PRODUCT_ID INT
AS
/*=========== QUERY ===========*/
	SELECT VERSION_ID,
		   VERSION,
		   VERSION_DESC,
		   ACTIVE_FLAG,
		   CASE 
				WHEN (
						 SELECT COUNT(1)
						 FROM   SOFTWARE_PRODUCT_VERSION WITH(NOLOCK)
						 WHERE  SOFTWARE_PRODUCT_VERSION.PRODUCT_ID = @SOFTWARE_PRODUCT_ID
								AND SOFTWARE_PRODUCT_VERSION.VERSION_ID = SOFTWARE_VERSION.VERSION_ID
					 ) > 0 THEN 1
				ELSE 0
		   END AS ON_THIS_PRODUCT,
		   CASE 
				WHEN (
						 SELECT COUNT(1)
						 FROM   SOFTWARE_PRODUCT_VERSION WITH(NOLOCK)
						 WHERE  SOFTWARE_PRODUCT_VERSION.PRODUCT_ID = @SOFTWARE_PRODUCT_ID
								AND SOFTWARE_PRODUCT_VERSION.VERSION_ID = SOFTWARE_VERSION.VERSION_ID
					 ) > 0 THEN (
						 SELECT CAST(VERSION_ID AS VARCHAR)+'|'+CAST([ID] AS VARCHAR)
						 FROM   SOFTWARE_PRODUCT_VERSION WITH(NOLOCK)
						 WHERE  SOFTWARE_PRODUCT_VERSION.PRODUCT_ID = @SOFTWARE_PRODUCT_ID
								AND SOFTWARE_PRODUCT_VERSION.VERSION_ID = SOFTWARE_VERSION.VERSION_ID
					 )
				ELSE CAST(VERSION_ID AS VARCHAR)+'|0'
		   END AS DATAKEY
	FROM   SOFTWARE_VERSION WITH(NOLOCK)
	WHERE  (ACTIVE_FLAG = 1 OR ACTIVE_FLAG IS NULL);
/*=========== QUERY ===========*/
