
CREATE PROCEDURE [dbo].[usp_wv_WV_DESK_TMPLT_RENAME] 
		@USER_ID VARCHAR(100),
		@WV_TMPLT_HDR_ID INT,
		@WV_TMPLT_DESC VARCHAR(50)

AS

        UPDATE WV_DESK_TMPLT_HDR WITH(ROWLOCK) 
        SET WV_TMPLT_DESC = @WV_TMPLT_DESC 
        WHERE	WV_TMPLT_HDR_ID = @WV_TMPLT_HDR_ID;-- AND CREATE_USER = @USER_ID;


