IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[usp_wv_EmployeeUtilizationUpdateColumnOrderSettings]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
DROP PROCEDURE [dbo].[usp_wv_EmployeeUtilizationUpdateColumnOrderSettings]
GO

/****** Object:  StoredProcedure [dbo].[usp_wv_AAMUpdateColumnOrderSettings]    Script Date: 7/21/2020 4:21:43 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[usp_wv_EmployeeUtilizationUpdateColumnOrderSettings] /*WITH ENCRYPTION*/
@GRID_NAME VARCHAR(100),
@USER_CODE VARCHAR(100),
@COLUMN_NAME VARCHAR(100),
@NEW_COLUMN_ORDER_ID INT

AS

DECLARE @GRID_COLUMN_ID INT
DECLARE @GRID_ID INT
DECLARE @OLD_COLUMN_ORDER_ID INT

SELECT @GRID_ID = GRID_ID FROM GRID WITH(NOLOCK) WHERE NAME = @GRID_NAME;
SELECT @GRID_COLUMN_ID = GRID_COLUMN_ID FROM GRID_COLUMN WITH(NOLOCK) WHERE GRID_ID = @GRID_ID AND NAME = @COLUMN_NAME;
SELECT @OLD_COLUMN_ORDER_ID = COLUMN_ORDER_ID FROM GRID_COLUMN_SETTING WITH(NOLOCK) WHERE GRID_ID = @GRID_ID AND GRID_COLUMN_ID = @GRID_COLUMN_ID

--UPDATE AFFECTED COLUMNS UPSTREAM
IF @OLD_COLUMN_ORDER_ID > @NEW_COLUMN_ORDER_ID
	BEGIN
		UPDATE GRID_COLUMN_SETTING WITH(ROWLOCK)
		SET COLUMN_ORDER_ID = COLUMN_ORDER_ID + 1
		WHERE COLUMN_ORDER_ID BETWEEN @NEW_COLUMN_ORDER_ID AND (@OLD_COLUMN_ORDER_ID - 1)
		AND GRID_ID = @GRID_ID
		AND USER_CODE = @USER_CODE
	END

--UPDATE AFFECTED COLUMNS DOWNSTREAM
IF @OLD_COLUMN_ORDER_ID < @NEW_COLUMN_ORDER_ID
	BEGIN
		UPDATE GRID_COLUMN_SETTING WITH(ROWLOCK)
		SET COLUMN_ORDER_ID = COLUMN_ORDER_ID - 1
		WHERE COLUMN_ORDER_ID BETWEEN (@OLD_COLUMN_ORDER_ID + 1) AND (@NEW_COLUMN_ORDER_ID)
		AND GRID_ID = @GRID_ID
		AND USER_CODE = @USER_CODE
	END

--UPDATE NEW LOCATION FOR MOVED COLUMN
UPDATE GRID_COLUMN_SETTING WITH(ROWLOCK)
SET COLUMN_ORDER_ID = @NEW_COLUMN_ORDER_ID
WHERE GRID_COLUMN_ID = @GRID_COLUMN_ID
AND GRID_ID = @GRID_ID
AND USER_CODE = @USER_CODE