

CREATE PROCEDURE [dbo].[usp_wv_Estimating_Save_UserColumns] 
@HDR_CODE VARCHAR(6),
@COLUMN_ID INT,
@SHOW_ON_GRID SMALLINT
--@SHOW_ON_ADDNEW SMALLINT

AS
DECLARE 
@CURRENTLY_INCLUDES INT,
@NEXT_SEQ INT,
@DISPLAY_TYPE VARCHAR(4)

SELECT     @CURRENTLY_INCLUDES = COUNT(1)
FROM         ESTIMATE_SETUP_DTL WITH(NOLOCK)
WHERE     (HDR_CODE = @HDR_CODE) AND (COLUMN_ID = @COLUMN_ID)

SET @DISPLAY_TYPE = ''

--IF @SHOW_ON_GRID = 1 AND @SHOW_ON_ADDNEW = 1
--BEGIN
--    SET @DISPLAY_TYPE = 'GA'
--END

IF @SHOW_ON_GRID = 1 --AND @SHOW_ON_ADDNEW = 0
BEGIN
    SET @DISPLAY_TYPE = 'G'
END

--IF @SHOW_ON_GRID = 0 AND @SHOW_ON_ADDNEW = 1
--BEGIN
--    SET @DISPLAY_TYPE = 'A'
--END

IF @SHOW_ON_GRID = 0 --AND @SHOW_ON_ADDNEW = 0
BEGIN
    SET @DISPLAY_TYPE = ''
END

IF @CURRENTLY_INCLUDES = 0 AND @DISPLAY_TYPE <> ''
    BEGIN --INSERT
        SELECT @NEXT_SEQ = ISNULL(MAX(SEQ),0)+1 FROM ESTIMATE_SETUP_DTL WHERE (HDR_CODE = @HDR_CODE)
        INSERT INTO ESTIMATE_SETUP_DTL WITH(ROWLOCK)
        (
            HDR_CODE,
            COLUMN_ID,
            SHOW_LONG_DESC,
            SEQ,
            DISPLAY_TYPE
        )
        VALUES
        (
            @HDR_CODE,
            @COLUMN_ID,
            0,
            @NEXT_SEQ,
            @DISPLAY_TYPE
        )
    END
    
IF @CURRENTLY_INCLUDES > 0 AND @DISPLAY_TYPE <> ''
    BEGIN --UPDATE
        UPDATE  ESTIMATE_SETUP_DTL WITH(ROWLOCK)
        SET DISPLAY_TYPE = @DISPLAY_TYPE
        WHERE    (HDR_CODE = @HDR_CODE) AND (COLUMN_ID = @COLUMN_ID)
    END
    
    
IF @SHOW_ON_GRID = 0 --AND @SHOW_ON_ADDNEW = 0
    BEGIN --DELETE
        DELETE 
        FROM         ESTIMATE_SETUP_DTL WITH(ROWLOCK)
        WHERE     (HDR_CODE = @HDR_CODE) AND (COLUMN_ID = @COLUMN_ID)
    END  






