if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[usp_wv_Estimating_Info]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [dbo].[usp_wv_Estimating_Info]
GO


CREATE PROCEDURE [dbo].[usp_wv_Estimating_Info] 
@EstNo Integer
AS

	SELECT ESTIMATE_LOG.ESTIMATE_NUMBER,
		   ESTIMATE_LOG.EST_LOG_DESC,
		   ESTIMATE_COMPONENT.EST_COMPONENT_NBR,
		   ESTIMATE_COMPONENT.EST_COMP_DESC,
		   ESTIMATE_LOG.CL_CODE,
		   CLIENT.CL_NAME,
		   ESTIMATE_LOG.DIV_CODE,
		   DIVISION.DIV_NAME,
		   ESTIMATE_LOG.PRD_CODE,
		   PRODUCT.PRD_DESCRIPTION,
		   JOB_LOG.JOB_NUMBER,
		   JOB_LOG.JOB_DESC,
		   JOB_COMPONENT.JOB_COMPONENT_NBR,
		   JOB_COMPONENT.JOB_COMP_DESC,
		   ESTIMATE_LOG.SC_CODE,
		   ESTIMATE_LOG.CMP_IDENTIFIER,
		   CAMPAIGN.CMP_CODE,
		   CAMPAIGN.CMP_NAME
	FROM   JOB_LOG WITH(NOLOCK)
		   INNER JOIN JOB_COMPONENT WITH(NOLOCK)
				ON  JOB_LOG.JOB_NUMBER = JOB_COMPONENT.JOB_NUMBER
		   RIGHT OUTER JOIN ESTIMATE_COMPONENT WITH(NOLOCK)
		   INNER JOIN ESTIMATE_LOG WITH(NOLOCK)
				ON  ESTIMATE_COMPONENT.ESTIMATE_NUMBER = ESTIMATE_LOG.ESTIMATE_NUMBER
		   INNER JOIN PRODUCT WITH(NOLOCK)
				ON  ESTIMATE_LOG.CL_CODE = PRODUCT.CL_CODE
				AND ESTIMATE_LOG.DIV_CODE = PRODUCT.DIV_CODE
				AND ESTIMATE_LOG.PRD_CODE = PRODUCT.PRD_CODE
		   INNER JOIN DIVISION WITH(NOLOCK)
				ON  PRODUCT.CL_CODE = DIVISION.CL_CODE
				AND PRODUCT.DIV_CODE = DIVISION.DIV_CODE
		   INNER JOIN CLIENT WITH(NOLOCK)
				ON  DIVISION.CL_CODE = CLIENT.CL_CODE
				ON  JOB_COMPONENT.ESTIMATE_NUMBER = ESTIMATE_COMPONENT.ESTIMATE_NUMBER
				AND JOB_COMPONENT.EST_COMPONENT_NBR = ESTIMATE_COMPONENT.EST_COMPONENT_NBR
		   LEFT OUTER JOIN CAMPAIGN ON CAMPAIGN.CMP_IDENTIFIER = ESTIMATE_LOG.CMP_IDENTIFIER
	WHERE  ESTIMATE_LOG.ESTIMATE_NUMBER = @EstNo;

