SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS OFF 
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[usp_wv_nontask_GetTaskData]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [dbo].[usp_wv_nontask_GetTaskData]
GO

CREATE PROCEDURE [dbo].[usp_wv_nontask_GetTaskData]
@TaskID INT,
@USER_ID VARCHAR(100)
AS

	DECLARE @RESTRICTED INT;

	SELECT @RESTRICTED = COUNT(1)
	FROM   SEC_EMP WITH(NOLOCK)
	WHERE  UPPER(SEC_EMP.[USER_ID]) = UPPER(@USER_ID);

	SET @RESTRICTED = ISNULL(@RESTRICTED, 0);

	IF @RESTRICTED = 0
	BEGIN
		SELECT ENT.NON_TASK_ID,
			   ENT.TYPE,
			   ENT.NON_TASK_DESC,
			   ENT.EMP_CODE,
			   ENT.ALL_DAY,
			   ENT.START_DATE,
			   ENT.END_DATE,
			   ENT.START_TIME,
			   ENT.END_TIME,
			   ISNULL(ENT.CATEGORY, '') AS CATEGORY,
			   ENT.JOB_NUMBER,
			   ENT.JOB_COMPONENT_NBR,
			   ENT.FNC_CODE,
			   ENT.CL_CODE,
			   ENT.DIV_CODE,
			   ENT.PRD_CODE,
			   ENT.[PRIORITY],
			   ENT.REMINDER,
			   ENT.RECURRENCE,
			   ENT.RECURRENCE_PARENT,
			   ENT.TASK_CODE,
			   ENT.NON_EMP_TASK_DESC,
			   ENT.NON_EMP_TASK_HTML,
			   C.CL_NAME,D.DIV_NAME,
			   P.PRD_DESCRIPTION, 
			   JL.JOB_DESC,
			   JC.JOB_COMP_DESC,
			   ENT.CDP_CONTACT_ID,
			   CH.CONT_CODE,
			   CH.CONT_FML
		FROM   EMP_NON_TASKS ENT WITH(NOLOCK)
				LEFT OUTER JOIN JOB_COMPONENT JC ON JC.JOB_NUMBER = ENT.JOB_NUMBER AND JC.JOB_COMPONENT_NBR = ENT.JOB_COMPONENT_NBR
				LEFT OUTER JOIN JOB_LOG JL ON JL.JOB_NUMBER = ENT.JOB_NUMBER
				LEFT OUTER JOIN PRODUCT P ON P.CL_CODE = ENT.CL_CODE AND P.DIV_CODE = ENT.DIV_CODE AND P.PRD_CODE = ENT.PRD_CODE
				LEFT OUTER JOIN DIVISION D ON D.CL_CODE = ENT.CL_CODE AND D.DIV_CODE = ENT.DIV_CODE
				LEFT OUTER JOIN CLIENT C ON C.CL_CODE = ENT.CL_CODE
				LEFT OUTER JOIN CDP_CONTACT_HDR CH ON CH.CDP_CONTACT_ID = ENT.CDP_CONTACT_ID
		WHERE  NON_TASK_ID = @TaskID;

		SELECT NON_TASK_ID_EMP, NON_TASK_ID, EMP_NON_TASKS_EMPS.EMP_CODE, coalesce((rtrim(EMP_FNAME) + ' '),'') + coalesce((EMP_MI + '. '),'') + coalesce(EMP_LNAME,'') AS EMP_NAME, EMP_NON_TASKS_EMPS.EMP_CODE + '|' + ISNULL(EMAIL_ADDRESS,'') AS EMP_EMAIL
		FROM EMP_NON_TASKS_EMPS INNER JOIN EMPLOYEE ON EMP_NON_TASKS_EMPS.EMP_CODE = EMPLOYEE.EMP_CODE
		WHERE  NON_TASK_ID = @TaskID;

	END
	ELSE
	BEGIN
		SELECT EMP_NON_TASKS.NON_TASK_ID,
			   EMP_NON_TASKS.TYPE,
			   EMP_NON_TASKS.NON_TASK_DESC,
			   EMP_NON_TASKS.EMP_CODE,
			   EMP_NON_TASKS.ALL_DAY,
			   EMP_NON_TASKS.START_DATE,
			   EMP_NON_TASKS.END_DATE,
			   EMP_NON_TASKS.START_TIME,
			   EMP_NON_TASKS.END_TIME,
			   ISNULL(EMP_NON_TASKS.CATEGORY, '') AS CATEGORY,
			   EMP_NON_TASKS.JOB_NUMBER,
			   EMP_NON_TASKS.JOB_COMPONENT_NBR,
			   EMP_NON_TASKS.FNC_CODE,
			   EMP_NON_TASKS.CL_CODE,
			   EMP_NON_TASKS.DIV_CODE,
			   EMP_NON_TASKS.PRD_CODE,
			   EMP_NON_TASKS.[PRIORITY],
			   EMP_NON_TASKS.REMINDER,
			   EMP_NON_TASKS.RECURRENCE,
			   EMP_NON_TASKS.RECURRENCE_PARENT,
			   EMP_NON_TASKS.TASK_CODE,
			   EMP_NON_TASKS.NON_EMP_TASK_DESC,
			   EMP_NON_TASKS.NON_EMP_TASK_HTML,
			   C.CL_NAME,D.DIV_NAME,
			   P.PRD_DESCRIPTION, 
			   JL.JOB_DESC,
			   JC.JOB_COMP_DESC,
			   EMP_NON_TASKS.CDP_CONTACT_ID,
			   CH.CONT_CODE,
			   CH.CONT_FML
		FROM   EMP_NON_TASKS WITH (NOLOCK)
			   INNER JOIN [dbo].[advtf_sec_emp] (@USER_ID) AS SEC_EMP
					ON  EMP_NON_TASKS.EMP_CODE = SEC_EMP.EMP_CODE
				LEFT OUTER JOIN JOB_COMPONENT JC ON JC.JOB_NUMBER = EMP_NON_TASKS.JOB_NUMBER AND JC.JOB_COMPONENT_NBR = EMP_NON_TASKS.JOB_COMPONENT_NBR
				LEFT OUTER JOIN JOB_LOG JL ON JL.JOB_NUMBER = EMP_NON_TASKS.JOB_NUMBER
				LEFT OUTER JOIN PRODUCT P ON P.CL_CODE = EMP_NON_TASKS.CL_CODE AND P.DIV_CODE = EMP_NON_TASKS.DIV_CODE AND P.PRD_CODE = EMP_NON_TASKS.PRD_CODE
				LEFT OUTER JOIN DIVISION D ON D.CL_CODE = EMP_NON_TASKS.CL_CODE AND D.DIV_CODE = EMP_NON_TASKS.DIV_CODE
				LEFT OUTER JOIN CLIENT C ON C.CL_CODE = EMP_NON_TASKS.CL_CODE
				LEFT OUTER JOIN CDP_CONTACT_HDR CH ON CH.CDP_CONTACT_ID = EMP_NON_TASKS.CDP_CONTACT_ID
		WHERE  (EMP_NON_TASKS.NON_TASK_ID = @TaskID) AND SEC_EMP.EMP_CODE = EMP_NON_TASKS.EMP_CODE

		SELECT NON_TASK_ID_EMP, NON_TASK_ID, EMP_NON_TASKS_EMPS.EMP_CODE, coalesce((rtrim(EMP_FNAME) + ' '),'') + coalesce((EMP_MI + '. '),'') + coalesce(EMP_LNAME,'') AS EMP_NAME, EMP_NON_TASKS_EMPS.EMP_CODE + '|' + ISNULL(EMAIL_ADDRESS,'') AS EMP_EMAIL
		FROM EMP_NON_TASKS_EMPS WITH (NOLOCK)
			INNER JOIN EMPLOYEE WITH (NOLOCK) ON EMP_NON_TASKS_EMPS.EMP_CODE = EMPLOYEE.EMP_CODE
			INNER JOIN [dbo].[advtf_sec_emp] (@USER_ID) AS SEC_EMP
					ON  EMP_NON_TASKS_EMPS.EMP_CODE = SEC_EMP.EMP_CODE
		WHERE  NON_TASK_ID = @TaskID AND SEC_EMP.EMP_CODE = EMP_NON_TASKS_EMPS.EMP_CODE;
	END

GO
SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO 