
CREATE PROCEDURE [dbo].[usp_wv_get_alert_group_emps_by_order] 
@Type as varchar(3),
@ORDER_NBR as Integer,
@CAT_ID as Integer
AS

If @Type = 'INT'
	SELECT  EG.EMP_CODE
		FROM INTERNET_HEADER XX
		INNER JOIN PRODUCT P ON P.CL_CODE = XX.CL_CODE AND P.DIV_CODE = XX.DIV_CODE AND P.PRD_CODE = XX.PRD_CODE
		INNER JOIN ALERT_GROUP AG ON AG.E_GROUP = P.EMAIL_GR_CODE AND AG.ACTIVE_FLAG = 1 AND AG.ALERT_CAT_ID = @CAT_ID
		INNER JOIN EMAIL_GROUP EG ON AG.E_GROUP = EG.EMAIL_GR_CODE AND (EG.INACTIVE_FLAG IS NULL OR EG.INACTIVE_FLAG = 0)
		WHERE XX.ORDER_NBR = @ORDER_NBR

If @Type = 'MAG'
	SELECT  EG.EMP_CODE
		FROM MAGAZINE_HEADER XX
		INNER JOIN PRODUCT P ON P.CL_CODE = XX.CL_CODE AND P.DIV_CODE = XX.DIV_CODE AND P.PRD_CODE = XX.PRD_CODE
		INNER JOIN ALERT_GROUP AG ON AG.E_GROUP = P.EMAIL_GR_CODE AND AG.ACTIVE_FLAG = 1 AND AG.ALERT_CAT_ID = @CAT_ID
		INNER JOIN EMAIL_GROUP EG ON AG.E_GROUP = EG.EMAIL_GR_CODE AND (EG.INACTIVE_FLAG IS NULL OR EG.INACTIVE_FLAG = 0)
		WHERE XX.ORDER_NBR = @ORDER_NBR

If @Type = 'NEW'
	SELECT  EG.EMP_CODE
		FROM NEWSPAPER_HEADER XX
		INNER JOIN PRODUCT P ON P.CL_CODE = XX.CL_CODE AND P.DIV_CODE = XX.DIV_CODE AND P.PRD_CODE = XX.PRD_CODE
		INNER JOIN ALERT_GROUP AG ON AG.E_GROUP = P.EMAIL_GR_CODE AND AG.ACTIVE_FLAG = 1 AND AG.ALERT_CAT_ID = @CAT_ID
		INNER JOIN EMAIL_GROUP EG ON AG.E_GROUP = EG.EMAIL_GR_CODE AND (EG.INACTIVE_FLAG IS NULL OR EG.INACTIVE_FLAG = 0)
		WHERE XX.ORDER_NBR = @ORDER_NBR

If @Type = 'OOH'
	SELECT  EG.EMP_CODE
		FROM OUTDOOR_HEADER XX
		INNER JOIN PRODUCT P ON P.CL_CODE = XX.CL_CODE AND P.DIV_CODE = XX.DIV_CODE AND P.PRD_CODE = XX.PRD_CODE
		INNER JOIN ALERT_GROUP AG ON AG.E_GROUP = P.EMAIL_GR_CODE AND AG.ACTIVE_FLAG = 1 AND AG.ALERT_CAT_ID = @CAT_ID
		INNER JOIN EMAIL_GROUP EG ON AG.E_GROUP = EG.EMAIL_GR_CODE AND (EG.INACTIVE_FLAG IS NULL OR EG.INACTIVE_FLAG = 0)
		WHERE XX.ORDER_NBR = @ORDER_NBR

If @Type = 'RAD'
	SELECT  EG.EMP_CODE
		FROM RADIO_HEADER XX
		INNER JOIN PRODUCT P ON P.CL_CODE = XX.CL_CODE AND P.DIV_CODE = XX.DIV_CODE AND P.PRD_CODE = XX.PRD_CODE
		INNER JOIN ALERT_GROUP AG ON AG.E_GROUP = P.EMAIL_GR_CODE AND AG.ACTIVE_FLAG = 1 AND AG.ALERT_CAT_ID = @CAT_ID
		INNER JOIN EMAIL_GROUP EG ON AG.E_GROUP = EG.EMAIL_GR_CODE AND (EG.INACTIVE_FLAG IS NULL OR EG.INACTIVE_FLAG = 0)
		WHERE XX.ORDER_NBR = @ORDER_NBR
		AND XX.REV_NBR = (SELECT MAX(XX2.REV_NBR) FROM RADIO_HEADER XX2 WHERE XX2.ORDER_NBR = @ORDER_NBR)

If @Type = 'TV'
	SELECT  EG.EMP_CODE
		FROM TV_HEADER XX
		INNER JOIN PRODUCT P ON P.CL_CODE = XX.CL_CODE AND P.DIV_CODE = XX.DIV_CODE AND P.PRD_CODE = XX.PRD_CODE
		INNER JOIN ALERT_GROUP AG ON AG.E_GROUP = P.EMAIL_GR_CODE AND AG.ACTIVE_FLAG = 1 AND AG.ALERT_CAT_ID = @CAT_ID
		INNER JOIN EMAIL_GROUP EG ON AG.E_GROUP = EG.EMAIL_GR_CODE AND (EG.INACTIVE_FLAG IS NULL OR EG.INACTIVE_FLAG = 0)
		WHERE XX.ORDER_NBR = @ORDER_NBR
		AND XX.REV_NBR = (SELECT MAX(XX2.REV_NBR) FROM RADIO_HEADER XX2 WHERE XX2.ORDER_NBR = @ORDER_NBR)


--If @Type = 'JOB'
--	set @sql = 'SELECT CAST(JOB_NUMBER AS VARCHAR(10)) AS Code, CAST(JOB_NUMBER AS VARCHAR(10)) + ''-'' + JOB_DESC AS Description
--		FROM JOB_LOG XX
--		WHERE CMP_IDENTIFIER = ' + @CmpIDStr

--EXEC(@sql)
--print(@sql)


