






















CREATE PROCEDURE [dbo].[usp_wv_Estimating_Quote_Revisions] 
@EstNo Int,
@EstCompNo Int,
@QuoteNo Int
AS
SELECT     ESTIMATE_QUOTE.ESTIMATE_NUMBER, ESTIMATE_LOG.EST_LOG_DESC, ESTIMATE_QUOTE.EST_COMPONENT_NBR, 
                      ESTIMATE_COMPONENT.EST_COMP_DESC, ESTIMATE_QUOTE.EST_QUOTE_NBR, ISNULL(ESTIMATE_QUOTE.EST_QUOTE_DESC,'') AS EST_QUOTE_DESC, 
                      ('00' + CAST(ESTIMATE_REV.EST_REV_NBR AS VARCHAR(3))) AS EST_REV_NBR_PAD, ESTIMATE_REV.EST_REV_NBR
FROM         ESTIMATE_QUOTE INNER JOIN
                      ESTIMATE_REV ON ESTIMATE_QUOTE.ESTIMATE_NUMBER = ESTIMATE_REV.ESTIMATE_NUMBER AND 
                      ESTIMATE_QUOTE.EST_COMPONENT_NBR = ESTIMATE_REV.EST_COMPONENT_NBR AND 
                      ESTIMATE_QUOTE.EST_QUOTE_NBR = ESTIMATE_REV.EST_QUOTE_NBR INNER JOIN
                      ESTIMATE_COMPONENT ON ESTIMATE_QUOTE.ESTIMATE_NUMBER = ESTIMATE_COMPONENT.ESTIMATE_NUMBER AND 
                      ESTIMATE_QUOTE.EST_COMPONENT_NBR = ESTIMATE_COMPONENT.EST_COMPONENT_NBR INNER JOIN
                      ESTIMATE_LOG ON ESTIMATE_COMPONENT.ESTIMATE_NUMBER = ESTIMATE_LOG.ESTIMATE_NUMBER LEFT OUTER JOIN
                      JOB_COMPONENT ON ESTIMATE_COMPONENT.ESTIMATE_NUMBER = JOB_COMPONENT.ESTIMATE_NUMBER AND 
                      ESTIMATE_COMPONENT.EST_COMPONENT_NBR = JOB_COMPONENT.EST_COMPONENT_NBR
WHERE     (ESTIMATE_QUOTE.ESTIMATE_NUMBER = @EstNo) AND (ESTIMATE_QUOTE.EST_COMPONENT_NBR = @EstCompNo) AND 
                      (ESTIMATE_QUOTE.EST_QUOTE_NBR = @QuoteNo)






















