

CREATE PROCEDURE [dbo].[usp_wv_Vendor_Quote_UpdateDetailQty]
(
	@ESTIMATE_NUMBER INT,
	@EST_COMPONENT_NBR SMALLINT,
	@VENDOR_QTE_NBR INT,
	@EST_QUOTE_NBR INT,
	@EST_REV_NBR INT,
	@EST_FNC_CODE VARCHAR(6),
	@QTY INT
)
AS
BEGIN
	SET NOCOUNT OFF
	
	DECLARE 
	@ERR INT

	UPDATE [VENDOR_QTE_DTL]
	SET	[QTY] = @QTY
	WHERE [ESTIMATE_NUMBER] = @ESTIMATE_NUMBER AND
		  [EST_COMPONENT_NBR] = @EST_COMPONENT_NBR AND
		  [EST_QUOTE_NBR] = @EST_QUOTE_NBR AND
		  [EST_REV_NBR] = @EST_REV_NBR AND
		  [VENDOR_QTE_NBR] = @VENDOR_QTE_NBR AND
		  [EST_FNC_CODE] = @EST_FNC_CODE
    
 
	SET @ERR = @@Error

	--RETURN @ERR
END




