
CREATE PROCEDURE [dbo].[usp_wv_Traffic_Schedule_SaveHeader_Multi] 
@JOB_NUMBER INT,
@JOB_COMPONENT_NBR SMALLINT,
@TRF_CODE VARCHAR(10),
@START_DATE SMALLDATETIME,
@JOB_FIRST_USE_DATE SMALLDATETIME,
@COMPLETED_DATE SMALLDATETIME,
@TRF_COMMENTS TEXT,
@PERCENT_COMPLETE decimal(7,3)
AS

            UPDATE JOB_TRAFFIC WITH(ROWLOCK)
            SET
	            TRF_CODE = @TRF_CODE,
	            TRF_COMMENTS = @TRF_COMMENTS,
	            COMPLETED_DATE = @COMPLETED_DATE,
				PERCENT_COMPLETE = @PERCENT_COMPLETE
            WHERE
	            JOB_NUMBER = @JOB_NUMBER
	            AND JOB_COMPONENT_NBR = @JOB_COMPONENT_NBR;

            UPDATE JOB_COMPONENT WITH(ROWLOCK)
            SET 
	            START_DATE = @START_DATE,
	            JOB_FIRST_USE_DATE = @JOB_FIRST_USE_DATE
            WHERE
	            JOB_NUMBER = @JOB_NUMBER
	            AND JOB_COMPONENT_NBR = @JOB_COMPONENT_NBR;

