

CREATE PROCEDURE [dbo].[usp_wv_traffic_GetPhase_All]
AS

	SELECT A.Code,A.DESCRIPTION, A.PHASE_ORDER 
	FROM
	(
		SELECT 0 AS Code,
			   '[None]' AS DESCRIPTION,
			   -2 AS PHASE_ORDER
			   
		UNION

		SELECT TRAFFIC_PHASE_ID AS Code,
			   ISNULL(PHASE_DESC, '') AS DESCRIPTION,
			   ISNULL(PHASE_ORDER, -1) AS PHASE_ORDER
		FROM   TRAFFIC_PHASE WITH(NOLOCK)
		WHERE  (INACTIVE_FLAG = 0)
			   OR (INACTIVE_FLAG IS NULL)
	) AS A
	ORDER BY
		A.PHASE_ORDER,
		A.[DESCRIPTION]		   



