

CREATE PROCEDURE [dbo].[usp_wv_reports_traffic_schedule_GetEmpNames]
@JOB_NUMBER INT,
@JOB_COMPONENT_NBR INT,
@SEQ SMALLINT
AS

        SELECT     
            JOB_TRAFFIC_DET_EMPS.ID, 
            JOB_TRAFFIC_DET_EMPS.JOB_NUMBER, 
            JOB_TRAFFIC_DET_EMPS.JOB_COMPONENT_NBR, 
            JOB_TRAFFIC_DET_EMPS.SEQ_NBR, 
            JOB_TRAFFIC_DET_EMPS.EMP_CODE, 
            ISNULL(EMPLOYEE.EMP_FNAME + ' ', '')+ ISNULL(EMPLOYEE.EMP_MI + '. ', '') + ISNULL(EMPLOYEE.EMP_LNAME, '') AS EMP_NAME, 
            ISNULL(JOB_TRAFFIC_DET_EMPS.HOURS_ALLOWED, 0) AS HOURS_ALLOWED,
			SubString(EMPLOYEE.EMP_FNAME, 1, 1) + ' ' + EMPLOYEE.EMP_LNAME as EmpName
        FROM         
            JOB_TRAFFIC_DET_EMPS LEFT OUTER JOIN
            EMPLOYEE ON JOB_TRAFFIC_DET_EMPS.EMP_CODE = EMPLOYEE.EMP_CODE
        WHERE     
                    ((JOB_TRAFFIC_DET_EMPS.JOB_NUMBER = @JOB_NUMBER) 
                    AND (JOB_TRAFFIC_DET_EMPS.JOB_COMPONENT_NBR = @JOB_COMPONENT_NBR) 
                    AND (JOB_TRAFFIC_DET_EMPS.SEQ_NBR = @SEQ))



