

CREATE PROCEDURE [dbo].[usp_wv_Vendor_Quote_Copy_AddRequest]
(
	@ESTIMATE_NUMBER INT,
	@EST_COMPONENT_NBR SMALLINT,
	@VENDOR_QTE_NBR INT,
	@VendorQteNum INT,
	@CREATED_BY VARCHAR(100),
	@CREATE_DATE smalldatetime,
	@USER_ID VARCHAR(100)
)
AS
BEGIN
	SET NOCOUNT OFF
	
	DECLARE 
	@ERR INT
    
    INSERT INTO [VENDOR_QTE_HDR]
		(
			[ESTIMATE_NUMBER],
			[EST_COMPONENT_NBR],
			[VENDOR_QTE_NBR],
			[VENDOR_QTE_DESC],
			[VN_QTE_MEMO],
			[CREATED_BY],
			[CREATE_DATE]
		)
		SELECT ESTIMATE_NUMBER, EST_COMPONENT_NBR, @VendorQteNum, VENDOR_QTE_DESC, VN_QTE_MEMO, @CREATED_BY, @CREATE_DATE 
	    FROM VENDOR_QTE_HDR
		WHERE (ESTIMATE_NUMBER = @ESTIMATE_NUMBER) AND (EST_COMPONENT_NBR = @EST_COMPONENT_NBR) AND (VENDOR_QTE_NBR = @VENDOR_QTE_NBR)
		
	INSERT INTO [VENDOR_QTE_SPECS]
		(
			[ESTIMATE_NUMBER],
			[EST_COMPONENT_NBR],
			[VENDOR_QTE_NBR],
			[EST_QUOTE_NBR],
			[EST_REV_NBR],
			[VN_QTE_SPECS]
		)
		SELECT ESTIMATE_NUMBER, EST_COMPONENT_NBR, @VendorQteNum, EST_QUOTE_NBR, EST_REV_NBR, VN_QTE_SPECS 
	    FROM VENDOR_QTE_SPECS
		WHERE (ESTIMATE_NUMBER = @ESTIMATE_NUMBER) AND (EST_COMPONENT_NBR = @EST_COMPONENT_NBR) AND (VENDOR_QTE_NBR = @VENDOR_QTE_NBR)
	
	INSERT INTO [VENDOR_QTE_FNC]
		(
			[ESTIMATE_NUMBER],
			[EST_COMPONENT_NBR],
			[VENDOR_QTE_NBR],
			[EST_FNC_CODE],
			[FNC_NOTES]
		)
		SELECT ESTIMATE_NUMBER, EST_COMPONENT_NBR, @VendorQteNum, EST_FNC_CODE, FNC_NOTES
	    FROM VENDOR_QTE_FNC
		WHERE (ESTIMATE_NUMBER = @ESTIMATE_NUMBER) AND (EST_COMPONENT_NBR = @EST_COMPONENT_NBR) AND (VENDOR_QTE_NBR = @VENDOR_QTE_NBR)

	INSERT INTO [VENDOR_QTE_VEN]
		(
			[ESTIMATE_NUMBER],
			[EST_COMPONENT_NBR],
			[VENDOR_QTE_NBR],
			[VN_CODE],
			[VN_CONT_CODE],
			[VN_NOTES],
			[DISPATCH_DATE],
			[DUE_DATE],
			[REPLY_DATE],
			[SUBMITTED_BY]
		)
		SELECT ESTIMATE_NUMBER, EST_COMPONENT_NBR, @VendorQteNum, VN_CODE, VN_CONT_CODE, VN_NOTES, NULL, NULL, NULL, @USER_ID
	    FROM VENDOR_QTE_VEN
		WHERE (ESTIMATE_NUMBER = @ESTIMATE_NUMBER) AND (EST_COMPONENT_NBR = @EST_COMPONENT_NBR) AND (VENDOR_QTE_NBR = @VENDOR_QTE_NBR)

	INSERT INTO [VENDOR_QTE_DTL]
		(
			[ESTIMATE_NUMBER],
			[EST_COMPONENT_NBR],
			[VENDOR_QTE_NBR],
			[EST_QUOTE_NBR],
			[EST_REV_NBR],
			[EST_FNC_CODE],
			[VN_CODE],
			[CREATED_BY],
			[CREATE_DATE],
			[REPLY_RATE],
			[REPLY_AMT],
			[REPLY_NOTES],
			[APPROVED_FLAG],
			[APPROVAL_NOTES],
			[APPROVED_BY],
			[APPROVED_DATE],
			[QTY]
		)
		SELECT ESTIMATE_NUMBER, EST_COMPONENT_NBR, @VendorQteNum, EST_QUOTE_NBR, EST_REV_NBR, EST_FNC_CODE, VN_CODE, 
				@CREATED_BY, @CREATE_DATE, 0, 0, NULL, 0, NULL, NULL, NULL, QTY 
	    FROM VENDOR_QTE_DTL
		WHERE (ESTIMATE_NUMBER = @ESTIMATE_NUMBER) AND (EST_COMPONENT_NBR = @EST_COMPONENT_NBR) AND (VENDOR_QTE_NBR = @VENDOR_QTE_NBR)

	
	SET @ERR = @@Error

	--RETURN @ERR
END




