SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS OFF 
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[usp_WV_WORKSPACE_TMPLT_DELETE]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [dbo].[usp_WV_WORKSPACE_TMPLT_DELETE]
GO

CREATE PROCEDURE [dbo].[usp_WV_WORKSPACE_TMPLT_DELETE] /*WITH ENCRYPTION*/
@WORKSPACE_TEMPLATE_ID INT
AS
/*=========== QUERY ===========*/
	DELETE FROM WV_WORKSPACE_TMPLT_ITEM WITH(ROWLOCK) WHERE WV_WORKSPACE_TMPLT_ITEM.WORKSPACE_ID IN (
		SELECT WV_WORKSPACE_TMPLT_DTL.WORKSPACE_ID FROM WV_WORKSPACE_TMPLT_DTL WHERE WV_WORKSPACE_TMPLT_DTL.TEMPLATE_ID = @WORKSPACE_TEMPLATE_ID
	);
	DELETE FROM WV_WORKSPACE_TMPLT_DTL WITH(ROWLOCK) WHERE WV_WORKSPACE_TMPLT_DTL.TEMPLATE_ID = @WORKSPACE_TEMPLATE_ID;
	DELETE FROM WV_WORKSPACE_TMPLT_HDR WITH(ROWLOCK) WHERE WV_WORKSPACE_TMPLT_HDR.TEMPLATE_ID = @WORKSPACE_TEMPLATE_ID;
/*=========== QUERY ===========*/
GO
SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO